                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047de1
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6243 K
Stellar class: F8
Age: 5.431 billion years  (1.703 billion left on main sequence)
Habitable ecosphere radius: 1.237 AU

Planets present at:
1	  0.348 AU	no atmosphere
2	  0.605 AU	greenhouse
3	  0.752 AU	no atmosphere
4	  1.813 AU	high pressure
5	  2.596 AU	cold
6	  3.662 AU	gas giant
7	  5.795 AU	gas giant
8	 13.830 AU	gas giant
9	 30.272 AU	gas giant
10	 49.971 AU	gas giant



Planet 1	
   Distance from primary:	0.348	AU
   Mass:			0.114	Earth masses
   Equatorial radius:		3133.6	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		244.17	degrees Celcius
   Normal daytime temperature:	460.04	degrees Celcius
   Normal night temperature:	-182.32	degrees Celcius
   Maximum temperature:   	463.08	degrees Celcius
   Minimum temperature:   	-192.70	degrees Celcius
   Escape Velocity:		5.39	km/sec
   Molecular weight retained:	27.34 and above
   Surface acceleration:	463.24	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.065
   Length of year:		71.65	days
   Length of day:		1719.50	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.605	AU
   Mass:			0.843	Earth masses
   Equatorial radius:		6057.9	km
   Density:			5.413	grams/cc
   Eccentricity of orbit:	0.119
   Surface gravity:		0.93	Earth gees
   Surface pressure:		67.640	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		477.53	degrees Celcius
   Maximum temperature:   	492.55	degrees Celcius
   Minimum temperature:   	416.90	degrees Celcius
   Escape Velocity:		10.54	km/sec
   Molecular weight retained:	7.15 and above
   Surface acceleration:	916.40	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.495
   Length of year:		164.44	days
   Length of day:		3105.97	hours
   Boiling point of water:	268.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1106
				Cesium       melts at 28    boils at 1147
				Gallium      melts at 30    boils at 3612
				Rubidium     melts at 39    boils at 1122
				Potassium    melts at 63    boils at 1235
				Sodium       melts at 98    boils at 1403
				Indium       melts at 157   boils at 3143
				Lithium      melts at 181   boils at 2079
				Selenium     melts at 217   boils at 1118
				Tin          melts at 232   boils at 3931
				Polonium     melts at 254   boils at 1520
				Bismuth      melts at 271   boils at 2394
				Thallium     melts at 304   boils at 2239
				Cadmium      melts at 321   boils at 1234
				Lead         melts at 328   boils at 2665
				Zinc         melts at 420   boils at 1440
				Tellurium    melts at 450   boils at 1561
   gasses in atmosphere:
				Sulfur           27.7%  PP 18762.1 mb
				Nitrogen         71.4%  PP 48319.1 mb
				Phosphorus        0.5%  PP  369.7 mb
				CarbonDioxide     0.1%  PP   44.2 mb
				Ozone             0.1%  PP   38.5 mb
				Ethanol           0.1%  PP   45.3 mb


Planet 3	
   Distance from primary:	0.752	AU
   Mass:			0.251	Earth masses
   Equatorial radius:		4066.1	km
   Density:			5.320	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		80.05	degrees Celcius
   Maximum temperature:   	260.93	degrees Celcius
   Minimum temperature:   	-227.54	degrees Celcius
   Escape Velocity:		7.01	km/sec
   Molecular weight retained:	16.15 and above
   Surface acceleration:	604.54	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.051
   Length of year:		227.78	days
   Length of day:		5466.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.813	AU
   Mass:			1.832	Earth masses
   Equatorial radius:		7791.4	km
   Density:			5.528	grams/cc
   Eccentricity of orbit:	0.137
   Surface gravity:		1.23	Earth gees
   Surface pressure:		3.128	Earth atmospheres
   Surface temperature:		-78.46	degrees Celcius
   Normal daytime temperature:	-76.92	degrees Celcius
   Normal night temperature:	-80.08	degrees Celcius
   Maximum temperature:   	-63.53	degrees Celcius
   Minimum temperature:   	-94.39	degrees Celcius
   Escape Velocity:		13.70	km/sec
   Molecular weight retained:	4.23 and above
   Surface acceleration:	1203.68	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.751
   Length of year:		853.47	days
   Length of day:		13.83	hours
   Boiling point of water:	134.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.09
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 111
				Chlorine     melts at -101  boils at -12
   gasses in atmosphere:
				Nitrogen         99.9%  PP 3124.1 mb


Planet 5	
   Distance from primary:	2.596	AU
   Mass:			1.422	Earth masses
   Equatorial radius:		7180.0	km
   Density:			5.483	grams/cc
   Eccentricity of orbit:	0.109
   Surface gravity:		1.12	Earth gees
   Surface pressure:		1.637	Earth atmospheres
   Surface temperature:		-98.20	degrees Celcius
   Normal daytime temperature:	-96.23	degrees Celcius
   Normal night temperature:	-100.29	degrees Celcius
   Maximum temperature:   	-79.90	degrees Celcius
   Minimum temperature:   	-117.88	degrees Celcius
   Escape Velocity:		12.57	km/sec
   Molecular weight retained:	5.02 and above
   Surface acceleration:	1100.30	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.633
   Length of year:		1462.41	days
   Length of day:		14.45	hours
   Boiling point of water:	114.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	96.79
   liquids at surface:
				Ethanol      melts at -114  boils at 92
				Chlorine     melts at -101  boils at -25
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1635.6 mb
				Ozone             0.1%  PP    0.8 mb


Planet 6	*gas giant*
   Distance from primary:	3.662	AU
   Mass:			19.490	Earth masses
   Equatorial radius:		27576.5	km
   Density:			1.326	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		23.74	km/sec
   Molecular weight retained:	1.41 and above
   Surface acceleration:	1022.04	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.520
   Length of year:		2449.42	days
   Length of day:		12.78	hours


Planet 7	*gas giant*
   Distance from primary:	5.795	AU
   Mass:			807.529	Earth masses
   Equatorial radius:		84895.3	km
   Density:			1.883	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		87.10	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4468.17	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.471
   Length of year:		4871.99	days
   Length of day:		6.11	hours


Planet 8	*gas giant*
   Distance from primary:	13.830	AU
   Mass:			434.557	Earth masses
   Equatorial radius:		76185.3	km
   Density:			1.402	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		67.45	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	2985.68	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.478
   Length of year:		17969.85	days
   Length of day:		7.48	hours


Planet 9	*gas giant*
   Distance from primary:	30.272	AU
   Mass:			3.234	Earth masses
   Equatorial radius:		19474.4	km
   Density:			0.625	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		11.51	km/sec
   Molecular weight retained:	5.99 and above
   Surface acceleration:	340.05	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.526
   Length of year:		58227.35	days
   Length of day:		22.16	hours


Planet 10	*gas giant*
   Distance from primary:	49.971	AU
   Mass:			0.340	Earth masses
   Equatorial radius:		10528.7	km
   Density:			0.416	grams/cc
   Eccentricity of orbit:	0.123
   Escape Velocity:		5.08	km/sec
   Molecular weight retained:	30.80 and above
   Surface acceleration:	122.40	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.512
   Length of year:		123491.69	days
   Length of day:		36.94	hours


