                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504894a
Stellar mass: 1.11 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6270 K
Stellar class: F8
Age: 1.089 billion years  (5.661 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.348 AU	no atmosphere
2	  0.476 AU	no atmosphere
3	  0.567 AU	no atmosphere
4	  0.909 AU	greenhouse
5	  1.382 AU	no atmosphere
6	  1.474 AU	high pressure
7	  2.311 AU	gas giant
8	  3.591 AU	gas giant
9	  5.112 AU	gas giant
10	 12.173 AU	gas giant
11	 20.227 AU	gas giant
12	 42.814 AU	gas giant



Planet 1	
   Distance from primary:	0.348	AU
   Mass:			0.035	Earth masses
   Equatorial radius:		2120.9	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		254.22	degrees Celcius
   Normal daytime temperature:	472.29	degrees Celcius
   Normal night temperature:	-180.59	degrees Celcius
   Maximum temperature:   	475.41	degrees Celcius
   Minimum temperature:   	-191.45	degrees Celcius
   Escape Velocity:		3.64	km/sec
   Molecular weight retained:	59.96 and above
   Surface acceleration:	312.13	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.055
   Length of year:		71.30	days
   Length of day:		1711.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.476	AU
   Mass:			0.105	Earth masses
   Equatorial radius:		3047.0	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.154
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		175.33	degrees Celcius
   Normal daytime temperature:	375.80	degrees Celcius
   Normal night temperature:	-196.85	degrees Celcius
   Maximum temperature:   	379.18	degrees Celcius
   Minimum temperature:   	-207.19	degrees Celcius
   Escape Velocity:		5.24	km/sec
   Molecular weight retained:	28.93 and above
   Surface acceleration:	450.23	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.077
   Length of year:		113.96	days
   Length of day:		2007.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.567	AU
   Mass:			0.448	Earth masses
   Equatorial radius:		4925.5	km
   Density:			5.355	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		136.62	degrees Celcius
   Normal daytime temperature:	281.37	degrees Celcius
   Normal night temperature:	-41.15	degrees Celcius
   Maximum temperature:   	298.59	degrees Celcius
   Minimum temperature:   	-68.72	degrees Celcius
   Escape Velocity:		8.52	km/sec
   Molecular weight retained:	10.93 and above
   Surface acceleration:	737.16	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.087
   Length of year:		148.15	days
   Length of day:		153.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.909	AU
   Mass:			0.235	Earth masses
   Equatorial radius:		3979.3	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.60	Earth gees
   Surface pressure:		4.232	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		62.56	degrees Celcius
   Normal daytime temperature:	65.91	degrees Celcius
   Normal night temperature:	58.83	degrees Celcius
   Maximum temperature:   	79.16	degrees Celcius
   Minimum temperature:   	44.99	degrees Celcius
   Escape Velocity:		6.86	km/sec
   Molecular weight retained:	16.87 and above
   Surface acceleration:	591.27	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.451
   Length of year:		300.72	days
   Length of day:		21.64	hours
   Boiling point of water:	144.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 120
				Mercury      melts at -39   boils at 432
				Water        melts at 0     boils at 145
				Francium     melts at 27    boils at 790
				Cesium       melts at 28    boils at 821
				Gallium      melts at 30    boils at 2722
				Rubidium     melts at 39    boils at 802
				Phosphorus   melts at 44    boils at 347
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP 1972.5 mb
				Ammonia           0.5%  PP   22.5 mb
				Ozone            49.2%  PP 2082.0 mb
				Neon              0.4%  PP   16.9 mb
				Krypton           2.8%  PP  119.7 mb
				Xenon             0.3%  PP   14.0 mb


Planet 5	
   Distance from primary:	1.382	AU
   Mass:			0.246	Earth masses
   Equatorial radius:		4039.1	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.050	Earth atmospheres
   Surface temperature:		-10.05	degrees Celcius
   Normal daytime temperature:	6.37	degrees Celcius
   Normal night temperature:	-26.96	degrees Celcius
   Maximum temperature:   	34.54	degrees Celcius
   Minimum temperature:   	-56.22	degrees Celcius
   Escape Velocity:		6.96	km/sec
   Molecular weight retained:	16.37 and above
   Surface acceleration:	600.40	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.267
   Length of year:		563.66	days
   Length of day:		19.70	hours
   Boiling point of water:	32.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	4.26
   Ice cover percentage:	20.52
   liquids at surface:
				Ethanol      melts at -114  boils at 15
				Mercury      melts at -39   boils at 243
   gasses in atmosphere:
				CarbonDioxide    30.1%  PP   15.0 mb
				Ammonia           1.7%  PP    0.8 mb
				Ozone            31.8%  PP   15.8 mb
				Chlorine         32.9%  PP   16.4 mb
				Fluorine          1.2%  PP    0.6 mb
				Neon              0.3%  PP    0.1 mb
				Krypton           1.8%  PP    0.9 mb
				Xenon             0.2%  PP    0.1 mb


Planet 6	
   Distance from primary:	1.474	AU
   Mass:			1.762	Earth masses
   Equatorial radius:		7694.5	km
   Density:			5.520	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		1.21	Earth gees
   Surface pressure:		2.592	Earth atmospheres
   Surface temperature:		13.01	degrees Celcius
   Normal daytime temperature:	15.49	degrees Celcius
   Normal night temperature:	10.37	degrees Celcius
   Maximum temperature:   	30.48	degrees Celcius
   Minimum temperature:   	-5.44	degrees Celcius
   Escape Velocity:		13.52	km/sec
   Molecular weight retained:	4.35 and above
   Surface acceleration:	1187.14	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.261
   Length of year:		621.22	days
   Length of day:		13.92	hours
   Boiling point of water:	128.2	degrees Celcius
   Hydrosphere percentage:	71.80
   Cloud cover percentage:	41.08
   Ice cover percentage:	2.48
   liquids at surface:
				Ethanol      melts at -114  boils at 105
				Mercury      melts at -39   boils at 405
				Bromine      melts at -7    boils at 85
				Water        melts at 0     boils at 128
   gasses in atmosphere:
				Oxygen            9.9%  PP  256.4 mb
				Nitrogen         90.0%  PP 2332.1 mb


Planet 7	*gas giant*
   Distance from primary:	2.311	AU
   Mass:			67.609	Earth masses
   Equatorial radius:		38034.2	km
   Density:			1.753	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		37.65	km/sec
   Molecular weight retained:	0.56 and above
   Surface acceleration:	1863.78	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.462
   Length of year:		1219.06	days
   Length of day:		9.47	hours


Planet 8	*gas giant*
   Distance from primary:	3.591	AU
   Mass:			179.683	Earth masses
   Equatorial radius:		52474.3	km
   Density:			1.774	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		52.26	km/sec
   Molecular weight retained:	0.29 and above
   Surface acceleration:	2602.28	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.507
   Length of year:		2361.60	days
   Length of day:		8.01	hours


Planet 9	*gas giant*
   Distance from primary:	5.112	AU
   Mass:			99.517	Earth masses
   Equatorial radius:		45486.1	km
   Density:			1.509	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		41.77	km/sec
   Molecular weight retained:	0.45 and above
   Surface acceleration:	1918.14	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.547
   Length of year:		4010.90	days
   Length of day:		9.33	hours


Planet 10	*gas giant*
   Distance from primary:	12.173	AU
   Mass:			20.360	Earth masses
   Equatorial radius:		30781.4	km
   Density:			0.996	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		22.97	km/sec
   Molecular weight retained:	1.50 and above
   Surface acceleration:	856.94	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.469
   Length of year:		14739.76	days
   Length of day:		13.96	hours


Planet 11	*gas giant*
   Distance from primary:	20.227	AU
   Mass:			169.888	Earth masses
   Equatorial radius:		59621.1	km
   Density:			1.144	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		47.67	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	1905.91	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.450
   Length of year:		31563.73	days
   Length of day:		9.36	hours


Planet 12	*gas giant*
   Distance from primary:	42.814	AU
   Mass:			1.066	Earth masses
   Equatorial radius:		14461.0	km
   Density:			0.503	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		7.67	km/sec
   Molecular weight retained:	13.50 and above
   Surface acceleration:	203.33	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.470
   Length of year:		97226.69	days
   Length of day:		28.66	hours


