                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d85
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6274 K
Stellar class: F8
Age: 4.128 billion years  (3.018 billion left on main sequence)
Habitable ecosphere radius: 1.236 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.609 AU	no atmosphere
3	  0.762 AU	no atmosphere
4	  1.081 AU	greenhouse
5	  1.717 AU	gas giant
6	  2.151 AU	high pressure
7	  3.175 AU	no atmosphere
8	  5.048 AU	gas giant
9	 11.810 AU	gas giant
10	 19.865 AU	gas giant
11	 38.709 AU	gas giant
12	 51.114 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.370	AU
   Mass:			0.278	Earth masses
   Equatorial radius:		4205.9	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.129
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		227.41	degrees Celcius
   Normal daytime temperature:	438.94	degrees Celcius
   Normal night temperature:	-179.99	degrees Celcius
   Maximum temperature:   	442.42	degrees Celcius
   Minimum temperature:   	-191.80	degrees Celcius
   Escape Velocity:		7.26	km/sec
   Molecular weight retained:	15.08 and above
   Surface acceleration:	625.93	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.068
   Length of year:		78.77	days
   Length of day:		1457.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.609	AU
   Mass:			0.456	Earth masses
   Equatorial radius:		4951.8	km
   Density:			5.356	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		115.72	degrees Celcius
   Maximum temperature:   	305.69	degrees Celcius
   Minimum temperature:   	-223.09	degrees Celcius
   Escape Velocity:		8.57	km/sec
   Molecular weight retained:	10.81 and above
   Surface acceleration:	741.26	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.082
   Length of year:		166.15	days
   Length of day:		3987.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.762	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1448.6	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		76.41	degrees Celcius
   Maximum temperature:   	256.24	degrees Celcius
   Minimum temperature:   	-227.96	degrees Celcius
   Escape Velocity:		2.48	km/sec
   Molecular weight retained:	128.78 and above
   Surface acceleration:	212.76	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.061
   Length of year:		232.66	days
   Length of day:		5583.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.081	AU
   Mass:			0.352	Earth masses
   Equatorial radius:		4547.8	km
   Density:			5.339	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.69	Earth gees
   Surface pressure:		9.855	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		33.37	degrees Celcius
   Maximum temperature:   	44.01	degrees Celcius
   Minimum temperature:   	22.17	degrees Celcius
   Escape Velocity:		7.86	km/sec
   Molecular weight retained:	12.86 and above
   Surface acceleration:	678.55	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.597
   Length of year:		392.92	days
   Length of day:		20.06	hours
   Boiling point of water:	175.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.07
   liquids at surface:
				Ethanol      melts at -114  boils at 150
				Mercury      melts at -39   boils at 485
				Bromine      melts at -7    boils at 127
				Water        melts at 0     boils at 176
				Francium     melts at 27    boils at 870
				Cesium       melts at 28    boils at 904
				Gallium      melts at 30    boils at 2947
   gasses in atmosphere:
				Nitrogen         99.0%  PP 9759.8 mb
				CarbonDioxide     0.4%  PP   36.7 mb
				Methane           0.1%  PP    7.8 mb
				Ammonia           0.1%  PP    9.7 mb
				Ozone             0.4%  PP   37.8 mb


Planet 5	*gas giant*
   Distance from primary:	1.717	AU
   Mass:			36.228	Earth masses
   Equatorial radius:		31024.4	km
   Density:			1.731	grams/cc
   Eccentricity of orbit:	0.119
   Escape Velocity:		30.52	km/sec
   Molecular weight retained:	0.85 and above
   Surface acceleration:	1501.00	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.493
   Length of year:		786.82	days
   Length of day:		10.55	hours


Planet 6	
   Distance from primary:	2.151	AU
   Mass:			1.708	Earth masses
   Equatorial radius:		7616.5	km
   Density:			5.515	grams/cc
   Eccentricity of orbit:	0.126
   Surface gravity:		1.20	Earth gees
   Surface pressure:		2.935	Earth atmospheres
   Surface temperature:		-97.29	degrees Celcius
   Normal daytime temperature:	-95.85	degrees Celcius
   Normal night temperature:	-98.83	degrees Celcius
   Maximum temperature:   	-82.44	degrees Celcius
   Minimum temperature:   	-113.21	degrees Celcius
   Escape Velocity:		13.37	km/sec
   Molecular weight retained:	4.44 and above
   Surface acceleration:	1173.86	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.764
   Length of year:		1103.27	days
   Length of day:		13.99	hours
   Boiling point of water:	132.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 109
				Chlorine     melts at -101  boils at -13
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2932.5 mb


Planet 7	
   Distance from primary:	3.175	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2031.9	km
   Density:			5.264	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-113.16	degrees Celcius
   Normal daytime temperature:	-93.85	degrees Celcius
   Normal night temperature:	-132.50	degrees Celcius
   Maximum temperature:   	-71.71	degrees Celcius
   Minimum temperature:   	-155.28	degrees Celcius
   Escape Velocity:		3.49	km/sec
   Molecular weight retained:	65.34 and above
   Surface acceleration:	298.94	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.288
   Length of year:		1978.54	days
   Length of day:		27.75	hours
   Boiling point of water:	-29.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	25.40
   liquids at surface:
				Ethanol      melts at -114  boils at -34
   gasses in atmosphere:
				Krypton          100.0%  PP    0.7 mb


Planet 8	*gas giant*
   Distance from primary:	5.048	AU
   Mass:			771.560	Earth masses
   Equatorial radius:		82823.8	km
   Density:			1.938	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		86.20	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4485.37	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.464
   Length of year:		3961.68	days
   Length of day:		6.10	hours


Planet 9	*gas giant*
   Distance from primary:	11.810	AU
   Mass:			561.730	Earth masses
   Equatorial radius:		81042.2	km
   Density:			1.506	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		74.35	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3410.70	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.519
   Length of year:		14180.44	days
   Length of day:		7.00	hours


Planet 10	*gas giant*
   Distance from primary:	19.865	AU
   Mass:			24.371	Earth masses
   Equatorial radius:		33891.6	km
   Density:			0.893	grams/cc
   Eccentricity of orbit:	0.117
   Escape Velocity:		23.95	km/sec
   Molecular weight retained:	1.38 and above
   Surface acceleration:	846.12	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.502
   Length of year:		30957.77	days
   Length of day:		14.05	hours


Planet 11	*gas giant*
   Distance from primary:	38.709	AU
   Mass:			1.945	Earth masses
   Equatorial radius:		17140.2	km
   Density:			0.551	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		9.51	km/sec
   Molecular weight retained:	8.77 and above
   Surface acceleration:	264.05	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.520
   Length of year:		84214.68	days
   Length of day:		25.15	hours


Planet 12	
   Distance from primary:	51.114	AU
   Mass:			0.044	Earth masses
   Equatorial radius:		3054.5	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.26	degrees Celcius
   Normal daytime temperature:	-225.04	degrees Celcius
   Normal night temperature:	-237.34	degrees Celcius
   Maximum temperature:   	-208.62	degrees Celcius
   Minimum temperature:   	-253.25	degrees Celcius
   Escape Velocity:		3.39	km/sec
   Molecular weight retained:	69.18 and above
   Surface acceleration:	187.82	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.141
   Length of year:		127785.10	days
   Length of day:		34.97	hours
   Boiling point of water:	-78.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


