                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486ef
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6349 K
Stellar class: F7
Age: 2.405 billion years  (4.422 billion left on main sequence)
Habitable ecosphere radius: 1.272 AU

Planets present at:
1	  0.531 AU	no atmosphere
2	  0.674 AU	no atmosphere
3	  1.251 AU	high pressure
4	  1.415 AU	no atmosphere
5	  2.210 AU	cold
6	  3.478 AU	gas giant
7	  5.414 AU	no atmosphere
8	  7.437 AU	gas giant
9	 10.363 AU	gas giant
10	 24.180 AU	gas giant
11	 39.746 AU	gas giant
12	 50.016 AU	no atmosphere



Planet 1	
   Distance from primary:	0.531	AU
   Mass:			0.571	Earth masses
   Equatorial radius:		5333.7	km
   Density:			5.374	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.55	degrees Celcius
   Maximum temperature:   	347.74	degrees Celcius
   Minimum temperature:   	-216.89	degrees Celcius
   Escape Velocity:		9.24	km/sec
   Molecular weight retained:	9.29 and above
   Surface acceleration:	801.12	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.079
   Length of year:		134.61	days
   Length of day:		3230.52	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.674	AU
   Mass:			0.281	Earth masses
   Equatorial radius:		4221.3	km
   Density:			5.326	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		104.14	degrees Celcius
   Maximum temperature:   	291.17	degrees Celcius
   Minimum temperature:   	-224.16	degrees Celcius
   Escape Velocity:		7.28	km/sec
   Molecular weight retained:	14.97 and above
   Surface acceleration:	628.29	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.058
   Length of year:		192.51	days
   Length of day:		3662.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	1.251	AU
   Mass:			2.263	Earth masses
   Equatorial radius:		8337.7	km
   Density:			5.571	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		1.32	Earth gees
   Surface pressure:		4.620	Earth atmospheres
   Surface temperature:		19.79	degrees Celcius
   Normal daytime temperature:	21.62	degrees Celcius
   Normal night temperature:	17.83	degrees Celcius
   Maximum temperature:   	33.41	degrees Celcius
   Minimum temperature:   	5.45	degrees Celcius
   Escape Velocity:		14.71	km/sec
   Molecular weight retained:	3.67 and above
   Surface acceleration:	1298.21	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.461
   Length of year:		486.55	days
   Length of day:		13.36	hours
   Boiling point of water:	147.5	degrees Celcius
   Hydrosphere percentage:	84.87
   Cloud cover percentage:	88.94
   Ice cover percentage:	0.80
   liquids at surface:
				Ethanol      melts at -114  boils at 123
				Mercury      melts at -39   boils at 437
				Bromine      melts at -7    boils at 102
				Water        melts at 0     boils at 148
   gasses in atmosphere:
				Nitrogen          1.2%  PP   54.8 mb
				Helium           98.8%  PP 4564.5 mb


Planet 4	
   Distance from primary:	1.415	AU
   Mass:			0.014	Earth masses
   Equatorial radius:		1554.6	km
   Density:			5.257	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-13.28	degrees Celcius
   Normal daytime temperature:	27.00	degrees Celcius
   Normal night temperature:	-53.92	degrees Celcius
   Maximum temperature:   	55.81	degrees Celcius
   Minimum temperature:   	-83.02	degrees Celcius
   Escape Velocity:		2.66	km/sec
   Molecular weight retained:	111.79 and above
   Surface acceleration:	228.38	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.068
   Length of year:		584.79	days
   Length of day:		37.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	
   Distance from primary:	2.210	AU
   Mass:			1.339	Earth masses
   Equatorial radius:		7040.1	km
   Density:			5.474	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		1.10	Earth gees
   Surface pressure:		1.631	Earth atmospheres
   Surface temperature:		-95.17	degrees Celcius
   Normal daytime temperature:	-93.13	degrees Celcius
   Normal night temperature:	-97.31	degrees Celcius
   Maximum temperature:   	-78.27	degrees Celcius
   Minimum temperature:   	-113.32	degrees Celcius
   Escape Velocity:		12.31	km/sec
   Molecular weight retained:	5.23 and above
   Surface acceleration:	1076.99	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.730
   Length of year:		1141.90	days
   Length of day:		14.61	hours
   Boiling point of water:	114.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 92
				Chlorine     melts at -101  boils at -25
   gasses in atmosphere:
				Oxygen            1.0%  PP   16.1 mb
				Nitrogen         98.9%  PP 1613.2 mb


Planet 6	*gas giant*
   Distance from primary:	3.478	AU
   Mass:			523.330	Earth masses
   Equatorial radius:		71524.4	km
   Density:			2.041	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		76.39	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	4079.50	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.482
   Length of year:		2252.80	days
   Length of day:		6.40	hours


Planet 7	
   Distance from primary:	5.414	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		4556.3	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.013	Earth atmospheres
   Surface temperature:		-146.42	degrees Celcius
   Normal daytime temperature:	-132.38	degrees Celcius
   Normal night temperature:	-160.64	degrees Celcius
   Maximum temperature:   	-114.40	degrees Celcius
   Minimum temperature:   	-179.48	degrees Celcius
   Escape Velocity:		5.07	km/sec
   Molecular weight retained:	30.84 and above
   Surface acceleration:	282.43	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.242
   Length of year:		4378.84	days
   Length of day:		28.52	hours
   Boiling point of water:	8.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	17.79
   gasses in atmosphere:
				Argon             1.5%  PP    0.2 mb
				Krypton          98.5%  PP   12.3 mb


Planet 8	*gas giant*
   Distance from primary:	7.437	AU
   Mass:			3.568	Earth masses
   Equatorial radius:		17786.7	km
   Density:			0.905	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		12.65	km/sec
   Molecular weight retained:	4.96 and above
   Surface acceleration:	449.70	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.509
   Length of year:		7049.45	days
   Length of day:		19.27	hours


Planet 9	*gas giant*
   Distance from primary:	10.363	AU
   Mass:			693.070	Earth masses
   Equatorial radius:		85025.9	km
   Density:			1.609	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		80.63	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3823.09	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.540
   Length of year:		11584.16	days
   Length of day:		6.61	hours


Planet 10	*gas giant*
   Distance from primary:	24.180	AU
   Mass:			28.985	Earth masses
   Equatorial radius:		36151.1	km
   Density:			0.875	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		25.29	km/sec
   Molecular weight retained:	1.24 and above
   Surface acceleration:	884.43	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.491
   Length of year:		41326.95	days
   Length of day:		13.74	hours


Planet 11	*gas giant*
   Distance from primary:	39.746	AU
   Mass:			1.154	Earth masses
   Equatorial radius:		14716.0	km
   Density:			0.517	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		7.91	km/sec
   Molecular weight retained:	12.69 and above
   Surface acceleration:	212.51	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.537
   Length of year:		87095.82	days
   Length of day:		28.04	hours


Planet 12	
   Distance from primary:	50.016	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		2489.0	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.35	degrees Celcius
   Normal daytime temperature:	-223.43	degrees Celcius
   Normal night temperature:	-237.14	degrees Celcius
   Maximum temperature:   	-210.93	degrees Celcius
   Minimum temperature:   	-249.70	degrees Celcius
   Escape Velocity:		2.76	km/sec
   Molecular weight retained:	104.42 and above
   Surface acceleration:	152.71	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.153
   Length of year:		122947.34	days
   Length of day:		38.78	hours
   Boiling point of water:	-87.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


