                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048416
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6291 K
Stellar class: F8
Age: 4.727 billion years  (2.195 billion left on main sequence)
Habitable ecosphere radius: 1.261 AU

Planets present at:
1	  0.375 AU	no atmosphere
2	  0.483 AU	no atmosphere
3	  0.720 AU	greenhouse
4	  0.988 AU	no atmosphere
5	  1.549 AU	gas giant
6	  2.818 AU	gas giant
7	  4.128 AU	cold
8	  7.206 AU	gas giant
9	 16.369 AU	gas giant
10	 30.280 AU	no atmosphere
11	 35.445 AU	no atmosphere
12	 48.138 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.375	AU
   Mass:			0.258	Earth masses
   Equatorial radius:		4103.2	km
   Density:			5.321	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.56	degrees Celcius
   Normal daytime temperature:	441.84	degrees Celcius
   Normal night temperature:	-181.81	degrees Celcius
   Maximum temperature:   	445.17	degrees Celcius
   Minimum temperature:   	-193.09	degrees Celcius
   Escape Velocity:		7.08	km/sec
   Molecular weight retained:	15.85 and above
   Surface acceleration:	610.21	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.068
   Length of year:		79.83	days
   Length of day:		1561.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.483	AU
   Mass:			1/489.4	Earth masses
   Equatorial radius:		822.0	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.12	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		168.35	degrees Celcius
   Maximum temperature:   	370.68	degrees Celcius
   Minimum temperature:   	-212.02	degrees Celcius
   Escape Velocity:		1.41	km/sec
   Molecular weight retained:	400.42 and above
   Surface acceleration:	120.59	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.076
   Length of year:		117.06	days
   Length of day:		2809.52	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.720	AU
   Mass:			0.859	Earth masses
   Equatorial radius:		6093.6	km
   Density:			5.415	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.94	Earth gees
   Surface pressure:		71.258	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		484.27	degrees Celcius
   Maximum temperature:   	490.06	degrees Celcius
   Minimum temperature:   	475.35	degrees Celcius
   Escape Velocity:		10.60	km/sec
   Molecular weight retained:	7.06 and above
   Surface acceleration:	922.15	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.450
   Length of year:		212.85	days
   Length of day:		33.36	hours
   Boiling point of water:	271.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1114
				Cesium       melts at 28    boils at 1155
				Gallium      melts at 30    boils at 3634
				Rubidium     melts at 39    boils at 1130
				Potassium    melts at 63    boils at 1243
				Sodium       melts at 98    boils at 1413
				Indium       melts at 157   boils at 3162
				Lithium      melts at 181   boils at 2092
				Selenium     melts at 217   boils at 1126
				Tin          melts at 232   boils at 3955
				Polonium     melts at 254   boils at 1530
				Bismuth      melts at 271   boils at 2409
				Thallium     melts at 304   boils at 2253
				Cadmium      melts at 321   boils at 1242
				Lead         melts at 328   boils at 2682
				Zinc         melts at 420   boils at 1450
				Tellurium    melts at 450   boils at 1571
   gasses in atmosphere:
				Sulfur           25.7%  PP 18295.6 mb
				Nitrogen         73.6%  PP 52415.0 mb
				Phosphorus        0.5%  PP  361.8 mb
				CarbonDioxide     0.1%  PP   41.8 mb
				Ozone             0.1%  PP   36.6 mb
				Ethanol           0.1%  PP   42.6 mb


Planet 4	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.988	AU
   Mass:			1/457.7	Earth masses
   Equatorial radius:		840.6	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.157
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		37.98	degrees Celcius
   Maximum temperature:   	207.53	degrees Celcius
   Minimum temperature:   	-232.19	degrees Celcius
   Escape Velocity:		1.44	km/sec
   Molecular weight retained:	382.90 and above
   Surface acceleration:	123.32	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.050
   Length of year:		341.84	days
   Length of day:		5982.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 5	*gas giant*
   Distance from primary:	1.549	AU
   Mass:			4.296	Earth masses
   Equatorial radius:		16488.4	km
   Density:			1.368	grams/cc
   Eccentricity of orbit:	0.198
   Escape Velocity:		14.42	km/sec
   Molecular weight retained:	3.82 and above
   Surface acceleration:	630.19	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.486
   Length of year:		671.52	days
   Length of day:		16.29	hours


Planet 6	*gas giant*
   Distance from primary:	2.818	AU
   Mass:			179.365	Earth masses
   Equatorial radius:		51466.3	km
   Density:			1.877	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		52.72	km/sec
   Molecular weight retained:	0.29 and above
   Surface acceleration:	2700.43	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.518
   Length of year:		1647.15	days
   Length of day:		7.87	hours


Planet 7	
   Distance from primary:	4.128	AU
   Mass:			1.078	Earth masses
   Equatorial radius:		6562.5	km
   Density:			5.443	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		1.02	Earth gees
   Surface pressure:		1.044	Earth atmospheres
   Surface temperature:		-138.65	degrees Celcius
   Normal daytime temperature:	-136.68	degrees Celcius
   Normal night temperature:	-140.73	degrees Celcius
   Maximum temperature:   	-120.94	degrees Celcius
   Minimum temperature:   	-157.95	degrees Celcius
   Escape Velocity:		11.45	km/sec
   Molecular weight retained:	6.06 and above
   Surface acceleration:	998.25	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.668
   Length of year:		2920.42	days
   Length of day:		15.17	hours
   Boiling point of water:	101.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	97.51
   liquids at surface:
				Ozone        melts at -193  boils at -111
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1043.4 mb


Planet 8	*gas giant*
   Distance from primary:	7.206	AU
   Mass:			761.707	Earth masses
   Equatorial radius:		84855.0	km
   Density:			1.779	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		84.61	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4218.64	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.533
   Length of year:		6728.51	days
   Length of day:		6.29	hours


Planet 9	*gas giant*
   Distance from primary:	16.369	AU
   Mass:			143.310	Earth masses
   Equatorial radius:		55816.7	km
   Density:			1.176	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		45.25	km/sec
   Molecular weight retained:	0.39 and above
   Surface acceleration:	1834.37	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.531
   Length of year:		23055.69	days
   Length of day:		9.54	hours


Planet 10	
   Distance from primary:	30.280	AU
   Mass:			0.048	Earth masses
   Equatorial radius:		3136.5	km
   Density:			2.201	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-218.56	degrees Celcius
   Normal daytime temperature:	-210.56	degrees Celcius
   Normal night temperature:	-226.49	degrees Celcius
   Maximum temperature:   	-196.34	degrees Celcius
   Minimum temperature:   	-241.19	degrees Celcius
   Escape Velocity:		3.48	km/sec
   Molecular weight retained:	65.59 and above
   Surface acceleration:	192.93	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.162
   Length of year:		58019.16	days
   Length of day:		34.50	hours
   Boiling point of water:	-77.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04
   liquids at surface:
				Fluorine     melts at -220  boils at -217


Planet 11	
   Distance from primary:	35.445	AU
   Mass:			0.255	Earth masses
   Equatorial radius:		5464.5	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-222.29	degrees Celcius
   Normal daytime temperature:	-216.48	degrees Celcius
   Normal night temperature:	-228.04	degrees Celcius
   Maximum temperature:   	-200.91	degrees Celcius
   Minimum temperature:   	-244.22	degrees Celcius
   Escape Velocity:		6.10	km/sec
   Molecular weight retained:	21.31 and above
   Surface acceleration:	340.93	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.160
   Length of year:		73479.58	days
   Length of day:		25.96	hours
   Boiling point of water:	-46.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 12	*gas giant*
   Distance from primary:	48.138	AU
   Mass:			0.253	Earth masses
   Equatorial radius:		9615.9	km
   Density:			0.407	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		4.58	km/sec
   Molecular weight retained:	37.77 and above
   Surface acceleration:	109.28	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.503
   Length of year:		116299.45	days
   Length of day:		39.10	hours


