                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b9f
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6234 K
Stellar class: F8
Age: 2.137 billion years  (5.076 billion left on main sequence)
Habitable ecosphere radius: 1.228 AU

Planets present at:
1	  0.354 AU	no atmosphere
2	  0.394 AU	no atmosphere
3	  0.447 AU	no atmosphere
4	  0.747 AU	no atmosphere
5	  0.906 AU	greenhouse
6	  1.474 AU	cold
7	  2.087 AU	gas giant
8	  4.196 AU	gas giant
9	  8.885 AU	gas giant
10	 27.107 AU	gas giant
11	 43.234 AU	no atmosphere



Planet 1	
   Distance from primary:	0.354	AU
   Mass:			0.017	Earth masses
   Equatorial radius:		1662.6	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		236.57	degrees Celcius
   Maximum temperature:   	453.74	degrees Celcius
   Minimum temperature:   	-194.02	degrees Celcius
   Escape Velocity:		2.85	km/sec
   Molecular weight retained:	97.71 and above
   Surface acceleration:	244.32	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.073
   Length of year:		73.71	days
   Length of day:		1769.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.394	AU
   Mass:			1/121.5	Earth masses
   Equatorial radius:		1307.4	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		209.79	degrees Celcius
   Maximum temperature:   	421.33	degrees Celcius
   Minimum temperature:   	-201.62	degrees Celcius
   Escape Velocity:		2.24	km/sec
   Molecular weight retained:	158.15 and above
   Surface acceleration:	191.96	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.076
   Length of year:		86.50	days
   Length of day:		2075.97	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.447	AU
   Mass:			0.312	Earth masses
   Equatorial radius:		4372.9	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		180.54	degrees Celcius
   Maximum temperature:   	385.75	degrees Celcius
   Minimum temperature:   	-209.35	degrees Celcius
   Escape Velocity:		7.55	km/sec
   Molecular weight retained:	13.93 and above
   Surface acceleration:	651.58	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.072
   Length of year:		104.68	days
   Length of day:		2512.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.747	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		2569.7	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		79.61	degrees Celcius
   Maximum temperature:   	260.19	degrees Celcius
   Minimum temperature:   	-227.58	degrees Celcius
   Escape Velocity:		4.41	km/sec
   Molecular weight retained:	40.77 and above
   Surface acceleration:	378.85	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.055
   Length of year:		225.86	days
   Length of day:		5420.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.906	AU
   Mass:			1.610	Earth masses
   Equatorial radius:		7473.8	km
   Density:			5.504	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		1.17	Earth gees
   Surface pressure:		232.767	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		467.13	degrees Celcius
   Maximum temperature:   	469.95	degrees Celcius
   Minimum temperature:   	462.22	degrees Celcius
   Escape Velocity:		13.11	km/sec
   Molecular weight retained:	4.62 and above
   Surface acceleration:	1149.68	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.597
   Length of year:		301.88	days
   Length of day:		14.65	hours
   Boiling point of water:	351.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1317
				Cesium       melts at 28    boils at 1364
				Gallium      melts at 30    boils at 4206
				Rubidium     melts at 39    boils at 1335
				Potassium    melts at 63    boils at 1465
				Sodium       melts at 98    boils at 1659
				Indium       melts at 157   boils at 3665
				Lithium      melts at 181   boils at 2438
				Selenium     melts at 217   boils at 1330
				Tin          melts at 232   boils at 4574
				Polonium     melts at 254   boils at 1794
				Bismuth      melts at 271   boils at 2801
				Thallium     melts at 304   boils at 2622
				Cadmium      melts at 321   boils at 1464
				Lead         melts at 328   boils at 3114
				Zinc         melts at 420   boils at 1702
				Tellurium    melts at 450   boils at 1841
   gasses in atmosphere:
				Sulfur           18.6%  PP 43287.1 mb
				Nitrogen         80.8%  PP 188167.6 mb
				Phosphorus        0.4%  PP  865.8 mb


Planet 6	
   Distance from primary:	1.474	AU
   Mass:			0.699	Earth masses
   Equatorial radius:		5696.5	km
   Density:			5.393	grams/cc
   Eccentricity of orbit:	0.134
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.505	Earth atmospheres
   Surface temperature:		-5.96	degrees Celcius
   Normal daytime temperature:	-0.05	degrees Celcius
   Normal night temperature:	-12.21	degrees Celcius
   Maximum temperature:   	24.46	degrees Celcius
   Minimum temperature:   	-38.16	degrees Celcius
   Escape Velocity:		9.89	km/sec
   Molecular weight retained:	8.12 and above
   Surface acceleration:	858.57	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.241
   Length of year:		626.58	days
   Length of day:		16.42	hours
   Boiling point of water:	82.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	10.33
   Ice cover percentage:	14.54
   liquids at surface:
				Ethanol      melts at -114  boils at 62
				Mercury      melts at -39   boils at 327
				Bromine      melts at -7    boils at 44
   gasses in atmosphere:
				Oxygen           29.1%  PP  147.2 mb
				Nitrogen         70.7%  PP  357.2 mb


Planet 7	*gas giant*
   Distance from primary:	2.087	AU
   Mass:			7.697	Earth masses
   Equatorial radius:		20079.8	km
   Density:			1.357	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		17.48	km/sec
   Molecular weight retained:	2.60 and above
   Surface acceleration:	761.25	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.465
   Length of year:		1055.60	days
   Length of day:		14.81	hours


Planet 8	*gas giant*
   Distance from primary:	4.196	AU
   Mass:			153.751	Earth masses
   Equatorial radius:		50974.5	km
   Density:			1.656	grams/cc
   Eccentricity of orbit:	0.167
   Escape Velocity:		49.05	km/sec
   Molecular weight retained:	0.33 and above
   Surface acceleration:	2359.67	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.458
   Length of year:		3008.90	days
   Length of day:		8.41	hours


Planet 9	*gas giant*
   Distance from primary:	8.885	AU
   Mass:			1238.042	Earth masses
   Equatorial radius:		99707.5	km
   Density:			1.782	grams/cc
   Eccentricity of orbit:	0.087
   Escape Velocity:		99.52	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4966.15	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.480
   Length of year:		9256.33	days
   Length of day:		5.80	hours


Planet 10	*gas giant*
   Distance from primary:	27.107	AU
   Mass:			27.846	Earth masses
   Equatorial radius:		36177.4	km
   Density:			0.839	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		24.78	km/sec
   Molecular weight retained:	1.29 and above
   Surface acceleration:	848.45	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.543
   Length of year:		49408.59	days
   Length of day:		14.03	hours


Planet 11	
   Distance from primary:	43.234	AU
   Mass:			0.351	Earth masses
   Equatorial radius:		6064.1	km
   Density:			2.243	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.20	degrees Celcius
   Normal daytime temperature:	-222.20	degrees Celcius
   Normal night temperature:	-232.13	degrees Celcius
   Maximum temperature:   	-207.52	degrees Celcius
   Minimum temperature:   	-247.32	degrees Celcius
   Escape Velocity:		6.79	km/sec
   Molecular weight retained:	17.21 and above
   Surface acceleration:	380.21	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.151
   Length of year:		99525.42	days
   Length of day:		24.58	hours
   Boiling point of water:	-42.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


