                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a53
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6323 K
Stellar class: F7
Age: 3.529 billion years  (3.187 billion left on main sequence)
Habitable ecosphere radius: 1.285 AU

Planets present at:
1	  0.368 AU	no atmosphere
2	  0.435 AU	no atmosphere
3	  0.497 AU	no atmosphere
4	  0.650 AU	no atmosphere
5	  0.999 AU	greenhouse
6	  1.600 AU	gas giant
7	  2.358 AU	gas giant
8	  5.176 AU	gas giant
9	  6.642 AU	gas giant
10	 10.920 AU	gas giant
11	 18.038 AU	gas giant
12	 32.365 AU	gas giant
13	 45.835 AU	no atmosphere



Planet 1	
   Distance from primary:	0.368	AU
   Mass:			0.020	Earth masses
   Equatorial radius:		1754.2	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		239.53	degrees Celcius
   Normal daytime temperature:	454.59	degrees Celcius
   Normal night temperature:	-185.15	degrees Celcius
   Maximum temperature:   	457.58	degrees Celcius
   Minimum temperature:   	-195.22	degrees Celcius
   Escape Velocity:		3.01	km/sec
   Molecular weight retained:	87.75 and above
   Surface acceleration:	257.86	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.065
   Length of year:		77.30	days
   Length of day:		1855.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.435	AU
   Mass:			0.043	Earth masses
   Equatorial radius:		2262.3	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		198.73	degrees Celcius
   Maximum temperature:   	408.00	degrees Celcius
   Minimum temperature:   	-205.76	degrees Celcius
   Escape Velocity:		3.88	km/sec
   Molecular weight retained:	52.67 and above
   Surface acceleration:	333.11	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.060
   Length of year:		99.58	days
   Length of day:		2389.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.497	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		3179.0	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		165.45	degrees Celcius
   Maximum temperature:   	367.14	degrees Celcius
   Minimum temperature:   	-212.91	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.56 and above
   Surface acceleration:	470.07	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.085
   Length of year:		121.49	days
   Length of day:		2915.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.650	AU
   Mass:			0.455	Earth masses
   Equatorial radius:		4948.8	km
   Density:			5.356	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		112.88	degrees Celcius
   Maximum temperature:   	302.10	degrees Celcius
   Minimum temperature:   	-223.70	degrees Celcius
   Escape Velocity:		8.56	km/sec
   Molecular weight retained:	10.83 and above
   Surface acceleration:	740.79	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.061
   Length of year:		181.74	days
   Length of day:		4361.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	0.999	AU
   Mass:			1.401	Earth masses
   Equatorial radius:		7145.6	km
   Density:			5.481	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		1.12	Earth gees
   Surface pressure:		205.090	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		465.68	degrees Celcius
   Maximum temperature:   	468.60	degrees Celcius
   Minimum temperature:   	460.66	degrees Celcius
   Escape Velocity:		12.51	km/sec
   Molecular weight retained:	5.07 and above
   Surface acceleration:	1094.56	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.517
   Length of year:		346.33	days
   Length of day:		15.05	hours
   Boiling point of water:	341.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1292
				Cesium       melts at 28    boils at 1338
				Gallium      melts at 30    boils at 4137
				Rubidium     melts at 39    boils at 1310
				Potassium    melts at 63    boils at 1439
				Sodium       melts at 98    boils at 1629
				Indium       melts at 157   boils at 3604
				Lithium      melts at 181   boils at 2396
				Selenium     melts at 217   boils at 1306
				Tin          melts at 232   boils at 4499
				Polonium     melts at 254   boils at 1762
				Bismuth      melts at 271   boils at 2754
				Thallium     melts at 304   boils at 2578
				Cadmium      melts at 321   boils at 1437
				Lead         melts at 328   boils at 3062
				Zinc         melts at 420   boils at 1671
				Tellurium    melts at 450   boils at 1808
   gasses in atmosphere:
				Sulfur           20.0%  PP 40952.0 mb
				Nitrogen         79.4%  PP 162915.6 mb
				Phosphorus        0.4%  PP  817.0 mb


Planet 6	*gas giant*
   Distance from primary:	1.600	AU
   Mass:			8.600	Earth masses
   Equatorial radius:		20210.1	km
   Density:			1.487	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		18.42	km/sec
   Molecular weight retained:	2.34 and above
   Surface acceleration:	839.63	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.499
   Length of year:		702.08	days
   Length of day:		14.11	hours


Planet 7	*gas giant*
   Distance from primary:	2.358	AU
   Mass:			8.996	Earth masses
   Equatorial radius:		21149.2	km
   Density:			1.357	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		18.42	km/sec
   Molecular weight retained:	2.34 and above
   Surface acceleration:	802.00	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.515
   Length of year:		1255.64	days
   Length of day:		14.43	hours


Planet 8	*gas giant*
   Distance from primary:	5.176	AU
   Mass:			3.773	Earth masses
   Equatorial radius:		17525.8	km
   Density:			1.000	grams/cc
   Eccentricity of orbit:	0.124
   Escape Velocity:		13.10	km/sec
   Molecular weight retained:	4.62 and above
   Surface acceleration:	489.79	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.518
   Length of year:		4084.16	days
   Length of day:		18.47	hours


Planet 9	*gas giant*
   Distance from primary:	6.642	AU
   Mass:			55.320	Earth masses
   Equatorial radius:		39161.6	km
   Density:			1.314	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		33.57	km/sec
   Molecular weight retained:	0.70 and above
   Surface acceleration:	1438.48	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.495
   Length of year:		5936.35	days
   Length of day:		10.78	hours


Planet 10	*gas giant*
   Distance from primary:	10.920	AU
   Mass:			191.337	Earth masses
   Equatorial radius:		58619.1	km
   Density:			1.355	grams/cc
   Eccentricity of orbit:	0.115
   Escape Velocity:		51.02	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2220.54	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.491
   Length of year:		12512.92	days
   Length of day:		8.67	hours


Planet 11	*gas giant*
   Distance from primary:	18.038	AU
   Mass:			24.000	Earth masses
   Equatorial radius:		33360.9	km
   Density:			0.922	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		23.95	km/sec
   Molecular weight retained:	1.38 and above
   Surface acceleration:	859.95	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.501
   Length of year:		26569.32	days
   Length of day:		13.94	hours


Planet 12	*gas giant*
   Distance from primary:	32.365	AU
   Mass:			33.650	Earth masses
   Equatorial radius:		38654.9	km
   Density:			0.831	grams/cc
   Eccentricity of orbit:	0.190
   Escape Velocity:		26.35	km/sec
   Molecular weight retained:	1.14 and above
   Surface acceleration:	898.08	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.480
   Length of year:		63856.96	days
   Length of day:		13.64	hours


Planet 13	
   Distance from primary:	45.835	AU
   Mass:			0.220	Earth masses
   Equatorial radius:		5202.2	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.183
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.05	degrees Celcius
   Normal daytime temperature:	-222.77	degrees Celcius
   Normal night temperature:	-233.24	degrees Celcius
   Maximum temperature:   	-210.84	degrees Celcius
   Minimum temperature:   	-245.77	degrees Celcius
   Escape Velocity:		5.81	km/sec
   Molecular weight retained:	23.55 and above
   Surface acceleration:	323.92	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.162
   Length of year:		107624.43	days
   Length of day:		26.63	hours
   Boiling point of water:	-50.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


