                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488e7
Stellar mass: 1.11 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6272 K
Stellar class: F8
Age: 4.393 billion years  (2.369 billion left on main sequence)
Habitable ecosphere radius: 1.279 AU

Planets present at:
1	  0.344 AU	no atmosphere
2	  0.611 AU	no atmosphere
3	  0.915 AU	no atmosphere
4	  1.232 AU	gas giant
5	  2.046 AU	gas giant
6	  3.626 AU	gas giant
7	  6.033 AU	gas giant
8	 14.935 AU	gas giant
9	 30.256 AU	gas giant
10	 45.472 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.344	AU
   Mass:			0.180	Earth masses
   Equatorial radius:		3644.7	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.130
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		253.08	degrees Celcius
   Normal daytime temperature:	469.85	degrees Celcius
   Normal night temperature:	-171.45	degrees Celcius
   Maximum temperature:   	473.51	degrees Celcius
   Minimum temperature:   	-184.50	degrees Celcius
   Escape Velocity:		6.28	km/sec
   Molecular weight retained:	20.15 and above
   Surface acceleration:	540.39	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.081
   Length of year:		70.19	days
   Length of day:		1298.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.611	AU
   Mass:			0.689	Earth masses
   Equatorial radius:		5670.4	km
   Density:			5.392	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.87	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		125.05	degrees Celcius
   Maximum temperature:   	317.38	degrees Celcius
   Minimum temperature:   	-221.96	degrees Celcius
   Escape Velocity:		9.84	km/sec
   Molecular weight retained:	8.19 and above
   Surface acceleration:	854.41	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.051
   Length of year:		165.97	days
   Length of day:		3983.38	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.915	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1423.6	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		52.03	degrees Celcius
   Maximum temperature:   	225.40	degrees Celcius
   Minimum temperature:   	-230.87	degrees Celcius
   Escape Velocity:		2.44	km/sec
   Molecular weight retained:	133.35 and above
   Surface acceleration:	209.07	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.055
   Length of year:		303.86	days
   Length of day:		7292.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	*gas giant*
   Distance from primary:	1.232	AU
   Mass:			3.994	Earth masses
   Equatorial radius:		15816.2	km
   Density:			1.440	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		14.19	km/sec
   Molecular weight retained:	3.94 and above
   Surface acceleration:	636.69	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.496
   Length of year:		474.58	days
   Length of day:		16.25	hours


Planet 5	*gas giant*
   Distance from primary:	2.046	AU
   Mass:			8.603	Earth masses
   Equatorial radius:		20638.0	km
   Density:			1.396	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		18.23	km/sec
   Molecular weight retained:	2.39 and above
   Surface acceleration:	805.47	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.490
   Length of year:		1016.04	days
   Length of day:		14.40	hours


Planet 6	*gas giant*
   Distance from primary:	3.626	AU
   Mass:			11.050	Earth masses
   Equatorial radius:		23285.2	km
   Density:			1.249	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		19.45	km/sec
   Molecular weight retained:	2.10 and above
   Surface acceleration:	812.72	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.506
   Length of year:		2396.57	days
   Length of day:		14.34	hours


Planet 7	*gas giant*
   Distance from primary:	6.033	AU
   Mass:			1013.248	Earth masses
   Equatorial radius:		90753.1	km
   Density:			1.934	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		94.37	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4906.06	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.523
   Length of year:		5136.73	days
   Length of day:		5.84	hours


Planet 8	*gas giant*
   Distance from primary:	14.935	AU
   Mass:			26.202	Earth masses
   Equatorial radius:		33704.2	km
   Density:			0.977	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		24.90	km/sec
   Molecular weight retained:	1.28 and above
   Surface acceleration:	919.83	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.491
   Length of year:		20035.74	days
   Length of day:		13.48	hours


Planet 9	*gas giant*
   Distance from primary:	30.256	AU
   Mass:			41.674	Earth masses
   Equatorial radius:		40927.2	km
   Density:			0.867	grams/cc
   Eccentricity of orbit:	0.153
   Escape Velocity:		28.50	km/sec
   Molecular weight retained:	0.98 and above
   Surface acceleration:	992.15	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.522
   Length of year:		57769.68	days
   Length of day:		12.98	hours


Planet 10	
   Distance from primary:	45.472	AU
   Mass:			0.249	Earth masses
   Equatorial radius:		5422.2	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.121
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.64	degrees Celcius
   Normal daytime temperature:	-222.42	degrees Celcius
   Normal night temperature:	-232.78	degrees Celcius
   Maximum temperature:   	-207.21	degrees Celcius
   Minimum temperature:   	-248.36	degrees Celcius
   Escape Velocity:		6.06	km/sec
   Molecular weight retained:	21.65 and above
   Surface acceleration:	338.18	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.140
   Length of year:		106447.26	days
   Length of day:		26.06	hours
   Boiling point of water:	-46.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


