                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e4d
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6183 K
Stellar class: F8
Age: 5.472 billion years  (1.647 billion left on main sequence)
Habitable ecosphere radius: 1.239 AU

Planets present at:
1	  0.372 AU	no atmosphere
2	  0.492 AU	no atmosphere
3	  0.701 AU	greenhouse
4	  1.234 AU	no atmosphere
5	  1.681 AU	cold
6	  2.097 AU	cold
7	  2.853 AU	gas giant
8	  6.362 AU	gas giant
9	 11.273 AU	gas giant
10	 24.590 AU	gas giant
11	 33.377 AU	no atmosphere
12	 45.109 AU	gas giant



Planet 1	
   Distance from primary:	0.372	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		1718.5	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		223.74	degrees Celcius
   Maximum temperature:   	438.23	degrees Celcius
   Minimum temperature:   	-197.72	degrees Celcius
   Escape Velocity:		2.95	km/sec
   Molecular weight retained:	91.44 and above
   Surface acceleration:	252.58	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.089
   Length of year:		79.41	days
   Length of day:		1905.79	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.492	AU
   Mass:			0.146	Earth masses
   Equatorial radius:		3400.2	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.154
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		161.67	degrees Celcius
   Normal daytime temperature:	358.99	degrees Celcius
   Normal night temperature:	-200.03	degrees Celcius
   Maximum temperature:   	362.48	degrees Celcius
   Minimum temperature:   	-210.47	degrees Celcius
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.19 and above
   Surface acceleration:	503.39	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.068
   Length of year:		120.62	days
   Length of day:		2120.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.701	AU
   Mass:			1.380	Earth masses
   Equatorial radius:		7110.3	km
   Density:			5.479	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		1.11	Earth gees
   Surface pressure:		155.430	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		540.98	degrees Celcius
   Maximum temperature:   	544.51	degrees Celcius
   Minimum temperature:   	533.98	degrees Celcius
   Escape Velocity:		12.44	km/sec
   Molecular weight retained:	5.13 and above
   Surface acceleration:	1088.67	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.551
   Length of year:		204.99	days
   Length of day:		27.89	hours
   Boiling point of water:	321.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1241
				Cesium       melts at 28    boils at 1286
				Gallium      melts at 30    boils at 3993
				Rubidium     melts at 39    boils at 1259
				Potassium    melts at 63    boils at 1383
				Sodium       melts at 98    boils at 1567
				Indium       melts at 157   boils at 3478
				Lithium      melts at 181   boils at 2309
				Selenium     melts at 217   boils at 1254
				Tin          melts at 232   boils at 4343
				Polonium     melts at 254   boils at 1696
				Bismuth      melts at 271   boils at 2655
				Thallium     melts at 304   boils at 2485
				Cadmium      melts at 321   boils at 1382
				Lead         melts at 328   boils at 2953
				Zinc         melts at 420   boils at 1608
				Tellurium    melts at 450   boils at 1740
   gasses in atmosphere:
				Sulfur           22.7%  PP 35296.2 mb
				Nitrogen         76.6%  PP 119093.5 mb
				Phosphorus        0.5%  PP  700.1 mb
				CarbonDioxide     0.1%  PP   78.9 mb
				Ethanol           0.1%  PP   80.3 mb


Planet 4	
   Distance from primary:	1.234	AU
   Mass:			0.251	Earth masses
   Equatorial radius:		4067.0	km
   Density:			5.320	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.056	Earth atmospheres
   Surface temperature:		8.50	degrees Celcius
   Normal daytime temperature:	26.44	degrees Celcius
   Normal night temperature:	-10.04	degrees Celcius
   Maximum temperature:   	54.77	degrees Celcius
   Minimum temperature:   	-39.39	degrees Celcius
   Escape Velocity:		7.01	km/sec
   Molecular weight retained:	16.14 and above
   Surface acceleration:	604.67	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.184
   Length of year:		478.83	days
   Length of day:		20.87	hours
   Boiling point of water:	34.6	degrees Celcius
   Hydrosphere percentage:	39.07
   Cloud cover percentage:	18.69
   Ice cover percentage:	3.32
   liquids at surface:
				Ethanol      melts at -114  boils at 17
				Mercury      melts at -39   boils at 247
				Water        melts at 0     boils at 35
   gasses in atmosphere:
				CarbonDioxide    45.1%  PP   25.3 mb
				Ammonia           2.6%  PP    1.5 mb
				Ozone            48.2%  PP   27.1 mb
				Chlorine          0.2%  PP    0.1 mb
				Argon             0.2%  PP    0.1 mb
				Neon              0.4%  PP    0.2 mb
				Krypton           3.0%  PP    1.7 mb
				Xenon             0.4%  PP    0.2 mb


Planet 5	
   Distance from primary:	1.681	AU
   Mass:			0.422	Earth masses
   Equatorial radius:		4828.7	km
   Density:			5.351	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.192	Earth atmospheres
   Surface temperature:		-72.98	degrees Celcius
   Normal daytime temperature:	-65.66	degrees Celcius
   Normal night temperature:	-80.64	degrees Celcius
   Maximum temperature:   	-43.29	degrees Celcius
   Minimum temperature:   	-104.45	degrees Celcius
   Escape Velocity:		8.35	km/sec
   Molecular weight retained:	11.38 and above
   Surface acceleration:	722.08	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.644
   Length of year:		762.01	days
   Length of day:		17.96	hours
   Boiling point of water:	59.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.08
   Ice cover percentage:	84.77
   liquids at surface:
				Ethanol      melts at -114  boils at 40
				Chlorine     melts at -101  boils at -60
				Ammonia      melts at -78   boils at -59
   gasses in atmosphere:
				Oxygen            3.4%  PP    6.5 mb
				Nitrogen         96.3%  PP  185.3 mb
				CarbonDioxide     0.2%  PP    0.3 mb
				Ozone             0.2%  PP    0.3 mb


Planet 6	
   Distance from primary:	2.097	AU
   Mass:			0.551	Earth masses
   Equatorial radius:		5270.4	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.326	Earth atmospheres
   Surface temperature:		-93.57	degrees Celcius
   Normal daytime temperature:	-88.55	degrees Celcius
   Normal night temperature:	-98.84	degrees Celcius
   Maximum temperature:   	-66.45	degrees Celcius
   Minimum temperature:   	-122.59	degrees Celcius
   Escape Velocity:		9.13	km/sec
   Molecular weight retained:	9.52 and above
   Surface acceleration:	791.15	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.677
   Length of year:		1061.55	days
   Length of day:		17.06	hours
   Boiling point of water:	71.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	92.44
   liquids at surface:
				Ethanol      melts at -114  boils at 52
				Chlorine     melts at -101  boils at -52
   gasses in atmosphere:
				Oxygen            1.2%  PP    3.8 mb
				Nitrogen         98.7%  PP  322.1 mb
				Ozone             0.1%  PP    0.3 mb


Planet 7	*gas giant*
   Distance from primary:	2.853	AU
   Mass:			237.766	Earth masses
   Equatorial radius:		56015.5	km
   Density:			1.930	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		58.18	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	3021.84	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.516
   Length of year:		1683.54	days
   Length of day:		7.44	hours


Planet 8	*gas giant*
   Distance from primary:	6.362	AU
   Mass:			756.795	Earth masses
   Equatorial radius:		83945.2	km
   Density:			1.826	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		84.80	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4282.78	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.518
   Length of year:		5603.17	days
   Length of day:		6.25	hours


Planet 9	*gas giant*
   Distance from primary:	11.273	AU
   Mass:			395.865	Earth masses
   Equatorial radius:		72880.9	km
   Density:			1.459	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		65.82	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	2972.07	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.538
   Length of year:		13221.51	days
   Length of day:		7.50	hours


Planet 10	*gas giant*
   Distance from primary:	24.590	AU
   Mass:			3.201	Earth masses
   Equatorial radius:		19080.7	km
   Density:			0.657	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		11.57	km/sec
   Molecular weight retained:	5.93 and above
   Surface acceleration:	350.61	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.460
   Length of year:		42618.02	days
   Length of day:		21.83	hours


Planet 11	
   Distance from primary:	33.377	AU
   Mass:			0.197	Earth masses
   Equatorial radius:		5020.2	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-220.93	degrees Celcius
   Normal daytime temperature:	-214.72	degrees Celcius
   Normal night temperature:	-227.08	degrees Celcius
   Maximum temperature:   	-201.58	degrees Celcius
   Minimum temperature:   	-240.97	degrees Celcius
   Escape Velocity:		5.60	km/sec
   Molecular weight retained:	25.33 and above
   Surface acceleration:	312.17	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.139
   Length of year:		67392.28	days
   Length of day:		27.13	hours
   Boiling point of water:	-51.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	*gas giant*
   Distance from primary:	45.109	AU
   Mass:			0.727	Earth masses
   Equatorial radius:		13025.6	km
   Density:			0.469	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		6.67	km/sec
   Molecular weight retained:	17.83 and above
   Surface acceleration:	170.88	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.541
   Length of year:		105887.93	days
   Length of day:		31.27	hours


