                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047de5
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6083 K
Stellar class: F9
Age: 4.427 billion years  (2.705 billion left on main sequence)
Habitable ecosphere radius: 1.237 AU

Planets present at:
1	  0.328 AU	no atmosphere
2	  0.521 AU	no atmosphere
3	  0.718 AU	greenhouse
4	  1.366 AU	
5	  1.909 AU	no atmosphere
6	  2.405 AU	gas giant
7	  4.982 AU	gas giant
8	  8.347 AU	gas giant
9	 14.978 AU	gas giant
10	 36.166 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.328	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		3179.5	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.136
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		259.16	degrees Celcius
   Normal daytime temperature:	476.89	degrees Celcius
   Normal night temperature:	-167.08	degrees Celcius
   Maximum temperature:   	480.65	degrees Celcius
   Minimum temperature:   	-180.73	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.55 and above
   Surface acceleration:	470.14	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.069
   Length of year:		65.56	days
   Length of day:		1196.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.521	AU
   Mass:			0.143	Earth masses
   Equatorial radius:		3379.7	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		146.43	degrees Celcius
   Maximum temperature:   	343.66	degrees Celcius
   Minimum temperature:   	-216.47	degrees Celcius
   Escape Velocity:		5.82	km/sec
   Molecular weight retained:	23.47 and above
   Surface acceleration:	500.30	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.090
   Length of year:		131.62	days
   Length of day:		3158.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.718	AU
   Mass:			0.564	Earth masses
   Equatorial radius:		5311.2	km
   Density:			5.373	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.81	Earth gees
   Surface pressure:		32.171	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		258.36	degrees Celcius
   Maximum temperature:   	267.86	degrees Celcius
   Minimum temperature:   	246.87	degrees Celcius
   Escape Velocity:		9.20	km/sec
   Molecular weight retained:	9.37 and above
   Surface acceleration:	797.59	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.497
   Length of year:		212.86	days
   Length of day:		56.25	hours
   Boiling point of water:	228.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 574
				Francium     melts at 27    boils at 1004
				Cesium       melts at 28    boils at 1042
				Gallium      melts at 30    boils at 3325
				Rubidium     melts at 39    boils at 1019
				Phosphorus   melts at 44    boils at 471
				Potassium    melts at 63    boils at 1124
				Sodium       melts at 98    boils at 1279
				Sulfur       melts at 113   boils at 692
				Indium       melts at 157   boils at 2891
				Lithium      melts at 181   boils at 1905
				Selenium     melts at 217   boils at 1015
				Tin          melts at 232   boils at 3621
				Polonium     melts at 254   boils at 1388
   gasses in atmosphere:
				Nitrogen         99.5%  PP 32014.3 mb
				Water             0.1%  PP   16.5 mb
				CarbonDioxide     0.1%  PP   36.5 mb
				Ozone             0.1%  PP   35.6 mb
				Ethanol           0.1%  PP   37.4 mb


Planet 4	
   Distance from primary:	1.366	AU
   Mass:			1.485	Earth masses
   Equatorial radius:		7280.1	km
   Density:			5.490	grams/cc
   Eccentricity of orbit:	0.212
   Surface gravity:		1.14	Earth gees
   Surface pressure:		1.620	Earth atmospheres
   Surface temperature:		15.26	degrees Celcius
   Normal daytime temperature:	18.52	degrees Celcius
   Normal night temperature:	11.80	degrees Celcius
   Maximum temperature:   	39.48	degrees Celcius
   Minimum temperature:   	-10.35	degrees Celcius
   Escape Velocity:		12.75	km/sec
   Molecular weight retained:	4.88 and above
   Surface acceleration:	1117.06	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.247
   Length of year:		557.87	days
   Length of day:		14.44	hours
   Boiling point of water:	113.8	degrees Celcius
   Hydrosphere percentage:	59.49
   Cloud cover percentage:	40.80
   Ice cover percentage:	1.82
   liquids at surface:
				Ethanol      melts at -114  boils at 92
				Mercury      melts at -39   boils at 380
				Bromine      melts at -7    boils at 72
				Water        melts at 0     boils at 114
   gasses in atmosphere:
				Oxygen            9.1%  PP  147.6 mb
				Nitrogen         90.7%  PP 1469.4 mb


Planet 5	
   Distance from primary:	1.909	AU
   Mass:			0.256	Earth masses
   Equatorial radius:		4093.4	km
   Density:			5.321	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.048	Earth atmospheres
   Surface temperature:		-65.57	degrees Celcius
   Normal daytime temperature:	-52.58	degrees Celcius
   Normal night temperature:	-78.91	degrees Celcius
   Maximum temperature:   	-27.14	degrees Celcius
   Minimum temperature:   	-105.56	degrees Celcius
   Escape Velocity:		7.06	km/sec
   Molecular weight retained:	15.93 and above
   Surface acceleration:	608.71	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.418
   Length of year:		921.77	days
   Length of day:		19.50	hours
   Boiling point of water:	31.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.08
   Ice cover percentage:	48.54
   liquids at surface:
				Ethanol      melts at -114  boils at 14
   gasses in atmosphere:
				Oxygen           54.4%  PP   26.1 mb
				CarbonDioxide    21.2%  PP   10.2 mb
				Methane           0.1%  PP    0.1 mb
				Ozone            22.5%  PP   10.8 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.2%  PP    0.1 mb
				Krypton           1.3%  PP    0.6 mb
				Xenon             0.2%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.405	AU
   Mass:			88.985	Earth masses
   Equatorial radius:		41465.0	km
   Density:			1.781	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		41.37	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	2063.93	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.464
   Length of year:		1303.73	days
   Length of day:		9.00	hours


Planet 7	*gas giant*
   Distance from primary:	4.982	AU
   Mass:			130.557	Earth masses
   Equatorial radius:		49271.3	km
   Density:			1.557	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		45.97	km/sec
   Molecular weight retained:	0.38 and above
   Surface acceleration:	2144.63	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.502
   Length of year:		3886.45	days
   Length of day:		8.83	hours


Planet 8	*gas giant*
   Distance from primary:	8.347	AU
   Mass:			174.649	Earth masses
   Equatorial radius:		55992.5	km
   Density:			1.420	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		49.88	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2221.50	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.451
   Length of year:		8428.31	days
   Length of day:		8.67	hours


Planet 9	*gas giant*
   Distance from primary:	14.978	AU
   Mass:			401.172	Earth masses
   Equatorial radius:		74925.7	km
   Density:			1.361	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		65.35	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2849.76	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.508
   Length of year:		20254.26	days
   Length of day:		7.66	hours


Planet 10	*gas giant*
   Distance from primary:	36.166	AU
   Mass:			7.850	Earth masses
   Equatorial radius:		25599.7	km
   Density:			0.668	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		15.64	km/sec
   Molecular weight retained:	3.25 and above
   Surface acceleration:	477.69	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.486
   Length of year:		76034.65	days
   Length of day:		18.70	hours


