                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048196
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6329 K
Stellar class: F7
Age: 3.680 billion years  (3.326 billion left on main sequence)
Habitable ecosphere radius: 1.251 AU

Planets present at:
1	  0.328 AU	no atmosphere
2	  0.398 AU	no atmosphere
3	  0.475 AU	no atmosphere
4	  0.755 AU	greenhouse
5	  1.217 AU	no atmosphere
6	  1.488 AU	high pressure
7	  2.795 AU	gas giant
8	  4.125 AU	gas giant
9	  8.764 AU	gas giant
10	 11.134 AU	no atmosphere
11	 17.412 AU	gas giant
12	 36.743 AU	gas giant
13	 49.687 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.328	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		2331.1	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		263.39	degrees Celcius
   Normal daytime temperature:	482.32	degrees Celcius
   Normal night temperature:	-168.86	degrees Celcius
   Maximum temperature:   	485.83	degrees Celcius
   Minimum temperature:   	-181.49	degrees Celcius
   Escape Velocity:		4.00	km/sec
   Molecular weight retained:	49.59 and above
   Surface acceleration:	343.34	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.056
   Length of year:		65.63	days
   Length of day:		1273.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.398	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		1505.2	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		212.83	degrees Celcius
   Maximum temperature:   	425.07	degrees Celcius
   Minimum temperature:   	-201.38	degrees Celcius
   Escape Velocity:		2.58	km/sec
   Molecular weight retained:	119.27 and above
   Surface acceleration:	221.10	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.068
   Length of year:		87.48	days
   Length of day:		2099.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.475	AU
   Mass:			0.383	Earth masses
   Equatorial radius:		4674.8	km
   Density:			5.344	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		170.04	degrees Celcius
   Maximum temperature:   	372.91	degrees Celcius
   Minimum temperature:   	-212.08	degrees Celcius
   Escape Velocity:		8.08	km/sec
   Molecular weight retained:	12.16 and above
   Surface acceleration:	698.20	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.080
   Length of year:		114.27	days
   Length of day:		2742.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.755	AU
   Mass:			1.011	Earth masses
   Equatorial radius:		6426.6	km
   Density:			5.434	grams/cc
   Eccentricity of orbit:	0.118
   Surface gravity:		0.99	Earth gees
   Surface pressure:		80.890	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		461.24	degrees Celcius
   Maximum temperature:   	466.27	degrees Celcius
   Minimum temperature:   	453.86	degrees Celcius
   Escape Velocity:		11.20	km/sec
   Molecular weight retained:	6.33 and above
   Surface acceleration:	976.07	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.496
   Length of year:		228.90	days
   Length of day:		20.96	hours
   Boiling point of water:	279.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1133
				Cesium       melts at 28    boils at 1175
				Gallium      melts at 30    boils at 3688
				Rubidium     melts at 39    boils at 1149
				Potassium    melts at 63    boils at 1264
				Sodium       melts at 98    boils at 1436
				Indium       melts at 157   boils at 3210
				Lithium      melts at 181   boils at 2125
				Selenium     melts at 217   boils at 1145
				Tin          melts at 232   boils at 4014
				Polonium     melts at 254   boils at 1555
				Bismuth      melts at 271   boils at 2446
				Thallium     melts at 304   boils at 2288
				Cadmium      melts at 321   boils at 1263
				Lead         melts at 328   boils at 2723
				Zinc         melts at 420   boils at 1474
				Tellurium    melts at 450   boils at 1596
   gasses in atmosphere:
				Sulfur           22.8%  PP 18440.8 mb
				Nitrogen         76.5%  PP 61893.3 mb
				Phosphorus        0.5%  PP  366.3 mb
				CarbonDioxide     0.1%  PP   40.7 mb
				Ethanol           0.1%  PP   41.3 mb


Planet 5	
   Distance from primary:	1.217	AU
   Mass:			0.010	Earth masses
   Equatorial radius:		1402.7	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		3.74	degrees Celcius
   Normal daytime temperature:	95.84	degrees Celcius
   Normal night temperature:	-94.92	degrees Celcius
   Maximum temperature:   	117.88	degrees Celcius
   Minimum temperature:   	-119.89	degrees Celcius
   Escape Velocity:		2.40	km/sec
   Molecular weight retained:	137.37 and above
   Surface acceleration:	205.99	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.081
   Length of year:		468.31	days
   Length of day:		110.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	
   Distance from primary:	1.488	AU
   Mass:			1.747	Earth masses
   Equatorial radius:		7672.5	km
   Density:			5.519	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		1.21	Earth gees
   Surface pressure:		3.308	Earth atmospheres
   Surface temperature:		11.66	degrees Celcius
   Normal daytime temperature:	13.86	degrees Celcius
   Normal night temperature:	9.32	degrees Celcius
   Maximum temperature:   	27.44	degrees Celcius
   Minimum temperature:   	-4.97	degrees Celcius
   Escape Velocity:		13.48	km/sec
   Molecular weight retained:	4.37 and above
   Surface acceleration:	1183.39	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.255
   Length of year:		633.01	days
   Length of day:		13.97	hours
   Boiling point of water:	136.1	degrees Celcius
   Hydrosphere percentage:	92.96
   Cloud cover percentage:	49.84
   Ice cover percentage:	2.76
   liquids at surface:
				Ethanol      melts at -114  boils at 113
				Mercury      melts at -39   boils at 418
				Bromine      melts at -7    boils at 92
				Water        melts at 0     boils at 136
   gasses in atmosphere:
				Oxygen            1.1%  PP   37.3 mb
				Nitrogen         98.7%  PP 3264.9 mb


Planet 7	*gas giant*
   Distance from primary:	2.795	AU
   Mass:			357.546	Earth masses
   Equatorial radius:		62934.0	km
   Density:			2.047	grams/cc
   Eccentricity of orbit:	0.113
   Escape Velocity:		67.31	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3599.98	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.497
   Length of year:		1629.29	days
   Length of day:		6.81	hours


Planet 8	*gas giant*
   Distance from primary:	4.125	AU
   Mass:			66.014	Earth masses
   Equatorial radius:		39716.3	km
   Density:			1.504	grams/cc
   Eccentricity of orbit:	0.176
   Escape Velocity:		36.41	km/sec
   Molecular weight retained:	0.60 and above
   Surface acceleration:	1668.93	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.452
   Length of year:		2921.32	days
   Length of day:		10.00	hours


Planet 9	*gas giant*
   Distance from primary:	8.764	AU
   Mass:			25.752	Earth masses
   Equatorial radius:		32136.9	km
   Density:			1.107	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		25.28	km/sec
   Molecular weight retained:	1.24 and above
   Surface acceleration:	994.34	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.466
   Length of year:		9049.09	days
   Length of day:		12.96	hours


Planet 10	
   Distance from primary:	11.134	AU
   Mass:			0.363	Earth masses
   Equatorial radius:		6133.5	km
   Density:			2.245	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.077	Earth atmospheres
   Surface temperature:		-181.62	degrees Celcius
   Normal daytime temperature:	-175.51	degrees Celcius
   Normal night temperature:	-187.99	degrees Celcius
   Maximum temperature:   	-158.44	degrees Celcius
   Minimum temperature:   	-206.61	degrees Celcius
   Escape Velocity:		6.87	km/sec
   Molecular weight retained:	16.82 and above
   Surface acceleration:	384.79	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.290
   Length of year:		12957.28	days
   Length of day:		24.43	hours
   Boiling point of water:	40.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.46
   liquids at surface:
				Ozone        melts at -193  boils at -138
				Methane      melts at -183  boils at -181
   gasses in atmosphere:
				Fluorine          6.0%  PP    4.6 mb
				Argon            21.7%  PP   16.7 mb
				Neon             72.3%  PP   55.7 mb


Planet 11	*gas giant*
   Distance from primary:	17.412	AU
   Mass:			592.920	Earth masses
   Equatorial radius:		84948.0	km
   Density:			1.380	grams/cc
   Eccentricity of orbit:	0.191
   Escape Velocity:		74.61	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3276.64	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.538
   Length of year:		25318.79	days
   Length of day:		7.14	hours


Planet 12	*gas giant*
   Distance from primary:	36.743	AU
   Mass:			1.586	Earth masses
   Equatorial radius:		16061.9	km
   Density:			0.546	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		8.87	km/sec
   Molecular weight retained:	10.08 and above
   Surface acceleration:	245.13	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.468
   Length of year:		77676.81	days
   Length of day:		26.10	hours


Planet 13	
   Distance from primary:	49.687	AU
   Mass:			0.081	Earth masses
   Equatorial radius:		3739.9	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.69	degrees Celcius
   Normal daytime temperature:	-224.92	degrees Celcius
   Normal night temperature:	-236.33	degrees Celcius
   Maximum temperature:   	-210.06	degrees Celcius
   Minimum temperature:   	-251.19	degrees Celcius
   Escape Velocity:		4.15	km/sec
   Molecular weight retained:	46.00 and above
   Surface acceleration:	230.72	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.164
   Length of year:		122152.31	days
   Length of day:		31.55	hours
   Boiling point of water:	-66.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


