                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047bbf
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6171 K
Stellar class: F8
Age: 2.313 billion years  (4.895 billion left on main sequence)
Habitable ecosphere radius: 1.229 AU

Planets present at:
1	  0.378 AU	no atmosphere
2	  0.450 AU	no atmosphere
3	  0.743 AU	greenhouse
4	  0.997 AU	greenhouse
5	  1.467 AU	cold
6	  2.299 AU	gas giant
7	  3.470 AU	gas giant
8	  6.180 AU	gas giant
9	 11.368 AU	gas giant
10	 18.643 AU	gas giant
11	 36.629 AU	gas giant
12	 50.182 AU	no atmosphere



Planet 1	
   Distance from primary:	0.378	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1935.3	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		218.72	degrees Celcius
   Maximum temperature:   	432.27	degrees Celcius
   Minimum temperature:   	-199.44	degrees Celcius
   Escape Velocity:		3.32	km/sec
   Molecular weight retained:	72.05 and above
   Surface acceleration:	284.63	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.086
   Length of year:		81.27	days
   Length of day:		1950.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.450	AU
   Mass:			0.082	Earth masses
   Equatorial radius:		2808.0	km
   Density:			5.281	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		181.09	degrees Celcius
   Maximum temperature:   	386.46	degrees Celcius
   Minimum temperature:   	-209.44	degrees Celcius
   Escape Velocity:		4.82	km/sec
   Molecular weight retained:	34.11 and above
   Surface acceleration:	414.43	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.055
   Length of year:		105.75	days
   Length of day:		2537.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.743	AU
   Mass:			0.369	Earth masses
   Equatorial radius:		4620.4	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.70	Earth gees
   Surface pressure:		12.866	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		127.67	degrees Celcius
   Maximum temperature:   	139.52	degrees Celcius
   Minimum temperature:   	114.89	degrees Celcius
   Escape Velocity:		7.98	km/sec
   Molecular weight retained:	12.45 and above
   Surface acceleration:	689.77	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.561
   Length of year:		224.11	days
   Length of day:		31.56	hours
   Boiling point of water:	186.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 503
				Francium     melts at 27    boils at 898
				Cesium       melts at 28    boils at 932
				Gallium      melts at 30    boils at 3025
				Rubidium     melts at 39    boils at 911
				Phosphorus   melts at 44    boils at 409
				Potassium    melts at 63    boils at 1007
				Sodium       melts at 98    boils at 1150
				Sulfur       melts at 113   boils at 612
				Iodine       melts at 114   boils at 292
   gasses in atmosphere:
				Nitrogen         99.0%  PP 12731.1 mb
				Water             0.1%  PP   12.0 mb
				CarbonDioxide     0.3%  PP   33.2 mb
				Methane           0.1%  PP    8.4 mb
				Ammonia           0.1%  PP   10.1 mb
				Ozone             0.3%  PP   34.2 mb
				Ethanol           0.3%  PP   34.0 mb


Planet 4	
   Distance from primary:	0.997	AU
   Mass:			1.868	Earth masses
   Equatorial radius:		7840.1	km
   Density:			5.532	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		1.24	Earth gees
   Surface pressure:		343.709	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		511.36	degrees Celcius
   Maximum temperature:   	513.50	degrees Celcius
   Minimum temperature:   	506.71	degrees Celcius
   Escape Velocity:		13.79	km/sec
   Molecular weight retained:	4.18 and above
   Surface acceleration:	1212.02	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.524
   Length of year:		348.69	days
   Length of day:		14.03	hours
   Boiling point of water:	382.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1397
				Cesium       melts at 28    boils at 1447
				Gallium      melts at 30    boils at 4432
				Rubidium     melts at 39    boils at 1417
				Potassium    melts at 63    boils at 1553
				Sodium       melts at 98    boils at 1757
				Indium       melts at 157   boils at 3864
				Lithium      melts at 181   boils at 2575
				Selenium     melts at 217   boils at 1411
				Tin          melts at 232   boils at 4819
				Polonium     melts at 254   boils at 1898
				Bismuth      melts at 271   boils at 2957
				Thallium     melts at 304   boils at 2769
				Cadmium      melts at 321   boils at 1552
				Lead         melts at 328   boils at 3286
				Zinc         melts at 420   boils at 1802
				Tellurium    melts at 450   boils at 1948
   gasses in atmosphere:
				Sulfur           18.1%  PP 62146.7 mb
				Nitrogen         81.4%  PP 279698.5 mb
				Phosphorus        0.4%  PP 1244.0 mb


Planet 5	
   Distance from primary:	1.467	AU
   Mass:			0.574	Earth masses
   Equatorial radius:		5340.2	km
   Density:			5.375	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.306	Earth atmospheres
   Surface temperature:		-13.50	degrees Celcius
   Normal daytime temperature:	-6.07	degrees Celcius
   Normal night temperature:	-21.32	degrees Celcius
   Maximum temperature:   	17.72	degrees Celcius
   Minimum temperature:   	-46.44	degrees Celcius
   Escape Velocity:		9.26	km/sec
   Molecular weight retained:	9.27 and above
   Surface acceleration:	802.14	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.295
   Length of year:		621.76	days
   Length of day:		17.01	hours
   Boiling point of water:	70.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	5.03
   Ice cover percentage:	26.48
   liquids at surface:
				Ethanol      melts at -114  boils at 50
				Mercury      melts at -39   boils at 306
   gasses in atmosphere:
				Oxygen           37.1%  PP  113.4 mb
				Nitrogen         62.8%  PP  192.0 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 6	*gas giant*
   Distance from primary:	2.299	AU
   Mass:			4.520	Earth masses
   Equatorial radius:		17331.2	km
   Density:			1.239	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		14.42	km/sec
   Molecular weight retained:	3.82 and above
   Surface acceleration:	600.13	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.472
   Length of year:		1220.29	days
   Length of day:		16.68	hours


Planet 7	*gas giant*
   Distance from primary:	3.470	AU
   Mass:			5.724	Earth masses
   Equatorial radius:		19214.4	km
   Density:			1.151	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		15.41	km/sec
   Molecular weight retained:	3.34 and above
   Surface acceleration:	618.24	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.537
   Length of year:		2262.98	days
   Length of day:		16.44	hours


Planet 8	*gas giant*
   Distance from primary:	6.180	AU
   Mass:			120.751	Earth masses
   Equatorial radius:		49061.8	km
   Density:			1.459	grams/cc
   Eccentricity of orbit:	0.244
   Escape Velocity:		44.31	km/sec
   Molecular weight retained:	0.40 and above
   Surface acceleration:	2000.52	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.479
   Length of year:		5377.03	days
   Length of day:		9.14	hours


Planet 9	*gas giant*
   Distance from primary:	11.368	AU
   Mass:			942.093	Earth masses
   Equatorial radius:		93978.5	km
   Density:			1.620	grams/cc
   Eccentricity of orbit:	0.086
   Escape Velocity:		89.42	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4253.79	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.453
   Length of year:		13400.34	days
   Length of day:		6.27	hours


Planet 10	*gas giant*
   Distance from primary:	18.643	AU
   Mass:			7.634	Earth masses
   Equatorial radius:		24041.2	km
   Density:			0.784	grams/cc
   Eccentricity of orbit:	0.134
   Escape Velocity:		15.91	km/sec
   Molecular weight retained:	3.13 and above
   Surface acceleration:	526.72	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.459
   Length of year:		28179.58	days
   Length of day:		17.81	hours


Planet 11	*gas giant*
   Distance from primary:	36.629	AU
   Mass:			5.030	Earth masses
   Equatorial radius:		22519.8	km
   Density:			0.628	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		13.35	km/sec
   Molecular weight retained:	4.46 and above
   Surface acceleration:	395.56	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.473
   Length of year:		77606.59	days
   Length of day:		20.55	hours


Planet 12	
   Distance from primary:	50.182	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		2014.8	km
   Density:			2.192	grams/cc
   Eccentricity of orbit:	0.184
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.20	degrees Celcius
   Normal daytime temperature:	-223.78	degrees Celcius
   Normal night temperature:	-238.45	degrees Celcius
   Maximum temperature:   	-206.41	degrees Celcius
   Minimum temperature:   	-254.70	degrees Celcius
   Escape Velocity:		2.23	km/sec
   Molecular weight retained:	159.60 and above
   Surface acceleration:	123.43	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.157
   Length of year:		124447.22	days
   Length of day:		43.14	hours
   Boiling point of water:	-96.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


