                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504838c
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6335 K
Stellar class: F7
Age: 4.917 billion years  (2.023 billion left on main sequence)
Habitable ecosphere radius: 1.259 AU

Planets present at:
1	  0.359 AU	no atmosphere
2	  0.476 AU	no atmosphere
3	  0.517 AU	no atmosphere
4	  0.638 AU	no atmosphere
5	  1.071 AU	greenhouse
6	  1.239 AU	no atmosphere
7	  1.374 AU	no atmosphere
8	  1.763 AU	gas giant
9	  2.188 AU	cold
10	  3.382 AU	cold
11	  5.520 AU	gas giant
12	  8.131 AU	gas giant
13	 12.140 AU	gas giant
14	 23.409 AU	gas giant
15	 33.527 AU	gas giant
16	 50.171 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.359	AU
   Mass:			0.074	Earth masses
   Equatorial radius:		2712.0	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.98	degrees Celcius
   Normal daytime temperature:	455.25	degrees Celcius
   Normal night temperature:	-175.06	degrees Celcius
   Maximum temperature:   	458.84	degrees Celcius
   Minimum temperature:   	-187.58	degrees Celcius
   Escape Velocity:		4.66	km/sec
   Molecular weight retained:	36.58 and above
   Surface acceleration:	400.09	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.061
   Length of year:		74.89	days
   Length of day:		1350.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.476	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		1969.1	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		174.78	degrees Celcius
   Maximum temperature:   	378.79	degrees Celcius
   Minimum temperature:   	-211.45	degrees Celcius
   Escape Velocity:		3.38	km/sec
   Molecular weight retained:	69.59 and above
   Surface acceleration:	289.64	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.049
   Length of year:		114.32	days
   Length of day:		2743.62	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.517	AU
   Mass:			0.371	Earth masses
   Equatorial radius:		4625.8	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		155.88	degrees Celcius
   Maximum temperature:   	355.40	degrees Celcius
   Minimum temperature:   	-215.08	degrees Celcius
   Escape Velocity:		7.99	km/sec
   Molecular weight retained:	12.42 and above
   Surface acceleration:	690.61	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.057
   Length of year:		129.32	days
   Length of day:		3103.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.638	AU
   Mass:			0.256	Earth masses
   Equatorial radius:		4092.6	km
   Density:			5.321	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		113.37	degrees Celcius
   Maximum temperature:   	302.80	degrees Celcius
   Minimum temperature:   	-223.61	degrees Celcius
   Escape Velocity:		7.06	km/sec
   Molecular weight retained:	15.94 and above
   Surface acceleration:	608.59	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.052
   Length of year:		177.52	days
   Length of day:		4260.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	1.071	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		3540.1	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.53	Earth gees
   Surface pressure:		2.708	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		51.08	degrees Celcius
   Normal daytime temperature:	55.85	degrees Celcius
   Normal night temperature:	45.76	degrees Celcius
   Maximum temperature:   	71.76	degrees Celcius
   Minimum temperature:   	29.09	degrees Celcius
   Escape Velocity:		6.09	km/sec
   Molecular weight retained:	21.38 and above
   Surface acceleration:	524.53	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.038
   Length of year:		386.07	days
   Length of day:		26.12	hours
   Boiling point of water:	129.6	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 106
				Mercury      melts at -39   boils at 407
				Bromine      melts at -7    boils at 86
				Water        melts at 0     boils at 130
				Francium     melts at 27    boils at 752
				Cesium       melts at 28    boils at 783
				Gallium      melts at 30    boils at 2615
				Rubidium     melts at 39    boils at 764
				Phosphorus   melts at 44    boils at 325
   gasses in atmosphere:
				CarbonDioxide    45.7%  PP 1236.4 mb
				Ozone            50.2%  PP 1358.5 mb
				Argon             0.2%  PP    4.2 mb
				Krypton           3.5%  PP   96.0 mb
				Xenon             0.5%  PP   12.4 mb


Planet 6	
   Distance from primary:	1.239	AU
   Mass:			0.203	Earth masses
   Equatorial radius:		3794.8	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.042	Earth atmospheres
   Surface temperature:		14.97	degrees Celcius
   Normal daytime temperature:	35.44	degrees Celcius
   Normal night temperature:	-6.13	degrees Celcius
   Maximum temperature:   	63.87	degrees Celcius
   Minimum temperature:   	-35.47	degrees Celcius
   Escape Velocity:		6.54	km/sec
   Molecular weight retained:	18.57 and above
   Surface acceleration:	563.17	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.113
   Length of year:		480.53	days
   Length of day:		21.71	hours
   Boiling point of water:	29.1	degrees Celcius
   Hydrosphere percentage:	41.14
   Cloud cover percentage:	0.00
   Ice cover percentage:	1.92
   liquids at surface:
				Mercury      melts at -39   boils at 238
				Water        melts at 0     boils at 30
   gasses in atmosphere:
				CarbonDioxide    45.9%  PP   19.2 mb
				Ozone            49.7%  PP   20.7 mb
				Chlorine          0.4%  PP    0.1 mb
				Argon             0.2%  PP    0.1 mb
				Neon              0.2%  PP    0.1 mb
				Krypton           3.2%  PP    1.3 mb
				Xenon             0.4%  PP    0.2 mb


Planet 7	
   Distance from primary:	1.374	AU
   Mass:			0.223	Earth masses
   Equatorial radius:		3913.7	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.049	Earth atmospheres
   Surface temperature:		-13.99	degrees Celcius
   Normal daytime temperature:	2.95	degrees Celcius
   Normal night temperature:	-31.44	degrees Celcius
   Maximum temperature:   	29.65	degrees Celcius
   Minimum temperature:   	-59.13	degrees Celcius
   Escape Velocity:		6.75	km/sec
   Molecular weight retained:	17.45 and above
   Surface acceleration:	581.27	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.292
   Length of year:		560.96	days
   Length of day:		20.59	hours
   Boiling point of water:	31.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	3.65
   Ice cover percentage:	27.86
   liquids at surface:
				Ethanol      melts at -114  boils at 15
				Mercury      melts at -39   boils at 243
   gasses in atmosphere:
				CarbonDioxide    46.2%  PP   22.5 mb
				Ozone            49.6%  PP   24.1 mb
				Chlorine          0.3%  PP    0.2 mb
				Argon             0.2%  PP    0.1 mb
				Neon              0.3%  PP    0.1 mb
				Krypton           3.1%  PP    1.5 mb
				Xenon             0.4%  PP    0.2 mb


Planet 8	*gas giant*
   Distance from primary:	1.763	AU
   Mass:			32.562	Earth masses
   Equatorial radius:		30094.0	km
   Density:			1.705	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		29.38	km/sec
   Molecular weight retained:	0.92 and above
   Surface acceleration:	1433.82	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.519
   Length of year:		815.63	days
   Length of day:		10.79	hours


Planet 9	
   Distance from primary:	2.188	AU
   Mass:			0.964	Earth masses
   Equatorial radius:		6327.9	km
   Density:			5.429	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.98	Earth gees
   Surface pressure:		0.741	Earth atmospheres
   Surface temperature:		-82.56	degrees Celcius
   Normal daytime temperature:	-79.21	degrees Celcius
   Normal night temperature:	-86.10	degrees Celcius
   Maximum temperature:   	-59.64	degrees Celcius
   Minimum temperature:   	-107.14	degrees Celcius
   Escape Velocity:		11.02	km/sec
   Molecular weight retained:	6.53 and above
   Surface acceleration:	960.03	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.606
   Length of year:		1127.57	days
   Length of day:		15.48	hours
   Boiling point of water:	91.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	83.20
   liquids at surface:
				Ethanol      melts at -114  boils at 71
				Chlorine     melts at -101  boils at -39
   gasses in atmosphere:
				Oxygen            0.2%  PP    1.3 mb
				Nitrogen         99.7%  PP  738.7 mb
				Ozone             0.1%  PP    0.4 mb


Planet 10	
   Distance from primary:	3.382	AU
   Mass:			1.081	Earth masses
   Equatorial radius:		6568.8	km
   Density:			5.443	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		1.02	Earth gees
   Surface pressure:		0.931	Earth atmospheres
   Surface temperature:		-116.73	degrees Celcius
   Normal daytime temperature:	-114.31	degrees Celcius
   Normal night temperature:	-119.29	degrees Celcius
   Maximum temperature:   	-98.53	degrees Celcius
   Minimum temperature:   	-136.42	degrees Celcius
   Escape Velocity:		11.46	km/sec
   Molecular weight retained:	6.05 and above
   Surface acceleration:	999.28	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.585
   Length of year:		2166.67	days
   Length of day:		15.16	hours
   Boiling point of water:	98.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	86.47
   liquids at surface:
				Ozone        melts at -193  boils at -113
   gasses in atmosphere:
				Oxygen            0.1%  PP    0.5 mb
				Nitrogen         99.9%  PP  929.7 mb


Planet 11	*gas giant*
   Distance from primary:	5.520	AU
   Mass:			4.192	Earth masses
   Equatorial radius:		18201.5	km
   Density:			0.992	grams/cc
   Eccentricity of orbit:	0.089
   Escape Velocity:		13.55	km/sec
   Molecular weight retained:	4.32 and above
   Surface acceleration:	504.59	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.542
   Length of year:		4517.19	days
   Length of day:		18.19	hours


Planet 12	*gas giant*
   Distance from primary:	8.131	AU
   Mass:			1057.345	Earth masses
   Equatorial radius:		94330.1	km
   Density:			1.797	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		94.55	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4738.66	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.473
   Length of year:		8064.50	days
   Length of day:		5.94	hours


Planet 13	*gas giant*
   Distance from primary:	12.140	AU
   Mass:			173.234	Earth masses
   Equatorial radius:		57547.9	km
   Density:			1.297	grams/cc
   Eccentricity of orbit:	0.109
   Escape Velocity:		49.00	km/sec
   Molecular weight retained:	0.33 and above
   Surface acceleration:	2086.00	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.501
   Length of year:		14731.18	days
   Length of day:		8.95	hours


Planet 14	*gas giant*
   Distance from primary:	23.409	AU
   Mass:			0.451	Earth masses
   Equatorial radius:		10714.7	km
   Density:			0.523	grams/cc
   Eccentricity of orbit:	0.125
   Escape Velocity:		5.79	km/sec
   Molecular weight retained:	23.65 and above
   Surface acceleration:	156.65	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.533
   Length of year:		39450.97	days
   Length of day:		32.66	hours


Planet 15	*gas giant*
   Distance from primary:	33.527	AU
   Mass:			11.490	Earth masses
   Equatorial radius:		28386.8	km
   Density:			0.717	grams/cc
   Eccentricity of orbit:	0.087
   Escape Velocity:		17.97	km/sec
   Molecular weight retained:	2.46 and above
   Surface acceleration:	568.62	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.506
   Length of year:		67620.05	days
   Length of day:		17.14	hours


Planet 16	
   Distance from primary:	50.171	AU
   Mass:			0.158	Earth masses
   Equatorial radius:		4670.0	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.41	degrees Celcius
   Normal daytime temperature:	-225.16	degrees Celcius
   Normal night temperature:	-235.56	degrees Celcius
   Maximum temperature:   	-208.11	degrees Celcius
   Minimum temperature:   	-252.37	degrees Celcius
   Escape Velocity:		5.20	km/sec
   Molecular weight retained:	29.34 and above
   Surface acceleration:	289.70	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.154
   Length of year:		123784.78	days
   Length of day:		28.16	hours
   Boiling point of water:	-56.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


