                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048956
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6404 K
Stellar class: F7
Age: 1.006 billion years  (5.742 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.427 AU	no atmosphere
2	  0.706 AU	greenhouse
3	  1.014 AU	greenhouse
4	  1.764 AU	gas giant
5	  2.792 AU	gas giant
6	  6.345 AU	gas giant
7	 12.525 AU	gas giant
8	 23.680 AU	gas giant
9	 37.606 AU	gas giant
10	 49.201 AU	no atmosphere



Planet 1	
   Distance from primary:	0.427	AU
   Mass:			0.297	Earth masses
   Equatorial radius:		4299.6	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.41	degrees Celcius
   Maximum temperature:   	411.31	degrees Celcius
   Minimum temperature:   	-205.13	degrees Celcius
   Escape Velocity:		7.42	km/sec
   Molecular weight retained:	14.42 and above
   Surface acceleration:	640.31	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.068
   Length of year:		96.88	days
   Length of day:		2325.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.706	AU
   Mass:			0.889	Earth masses
   Equatorial radius:		6163.1	km
   Density:			5.419	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.95	Earth gees
   Surface pressure:		60.185	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		422.52	degrees Celcius
   Maximum temperature:   	428.13	degrees Celcius
   Minimum temperature:   	414.99	degrees Celcius
   Escape Velocity:		10.73	km/sec
   Molecular weight retained:	6.90 and above
   Surface acceleration:	933.36	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.496
   Length of year:		205.86	days
   Length of day:		17.92	hours
   Boiling point of water:	261.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1089
				Cesium       melts at 28    boils at 1129
				Gallium      melts at 30    boils at 3564
				Rubidium     melts at 39    boils at 1105
				Potassium    melts at 63    boils at 1216
				Sodium       melts at 98    boils at 1382
				Sulfur       melts at 113   boils at 756
				Indium       melts at 157   boils at 3101
				Lithium      melts at 181   boils at 2050
				Selenium     melts at 217   boils at 1101
				Tin          melts at 232   boils at 3879
				Polonium     melts at 254   boils at 1498
				Bismuth      melts at 271   boils at 2361
				Thallium     melts at 304   boils at 2208
				Cadmium      melts at 321   boils at 1215
				Lead         melts at 328   boils at 2629
				Zinc         melts at 420   boils at 1419
   gasses in atmosphere:
				Nitrogen         99.2%  PP 59688.3 mb
				Phosphorus        0.5%  PP  323.0 mb
				CarbonDioxide     0.1%  PP   34.4 mb
				Ozone             0.1%  PP   34.1 mb
				Ethanol           0.1%  PP   34.8 mb


Planet 3	
   Distance from primary:	1.014	AU
   Mass:			0.257	Earth masses
   Equatorial radius:		4098.1	km
   Density:			5.321	grams/cc
   Eccentricity of orbit:	0.186
   Surface gravity:		0.62	Earth gees
   Surface pressure:		4.781	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		45.12	degrees Celcius
   Normal daytime temperature:	47.95	degrees Celcius
   Normal night temperature:	42.00	degrees Celcius
   Maximum temperature:   	61.61	degrees Celcius
   Minimum temperature:   	27.71	degrees Celcius
   Escape Velocity:		7.07	km/sec
   Molecular weight retained:	15.89 and above
   Surface acceleration:	609.42	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.458
   Length of year:		354.54	days
   Length of day:		20.21	hours
   Boiling point of water:	148.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 124
				Mercury      melts at -39   boils at 439
				Bromine      melts at -7    boils at 103
				Water        melts at 0     boils at 149
				Francium     melts at 27    boils at 801
				Cesium       melts at 28    boils at 833
				Gallium      melts at 30    boils at 2753
				Rubidium     melts at 39    boils at 813
				Phosphorus   melts at 44    boils at 353
   gasses in atmosphere:
				Oxygen           12.2%  PP  584.9 mb
				CarbonDioxide    39.3%  PP 1880.2 mb
				Methane           0.4%  PP   18.3 mb
				Ammonia           3.7%  PP  178.3 mb
				Ozone            41.3%  PP 1973.4 mb
				Neon              0.4%  PP   20.3 mb
				Krypton           2.3%  PP  110.9 mb
				Xenon             0.3%  PP   12.8 mb


Planet 4	*gas giant*
   Distance from primary:	1.764	AU
   Mass:			47.013	Earth masses
   Equatorial radius:		33448.9	km
   Density:			1.793	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		33.48	km/sec
   Molecular weight retained:	0.71 and above
   Surface acceleration:	1675.69	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.458
   Length of year:		813.24	days
   Length of day:		9.98	hours


Planet 5	*gas giant*
   Distance from primary:	2.792	AU
   Mass:			20.902	Earth masses
   Equatorial radius:		27436.0	km
   Density:			1.444	grams/cc
   Eccentricity of orbit:	0.135
   Escape Velocity:		24.65	km/sec
   Molecular weight retained:	1.31 and above
   Surface acceleration:	1107.35	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.463
   Length of year:		1619.22	days
   Length of day:		12.28	hours


Planet 6	*gas giant*
   Distance from primary:	6.345	AU
   Mass:			646.278	Earth masses
   Equatorial radius:		79924.5	km
   Density:			1.806	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		80.31	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4034.59	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.529
   Length of year:		5542.18	days
   Length of day:		6.43	hours


Planet 7	*gas giant*
   Distance from primary:	12.525	AU
   Mass:			3.006	Earth masses
   Equatorial radius:		17660.1	km
   Density:			0.779	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		11.65	km/sec
   Molecular weight retained:	5.85 and above
   Surface acceleration:	384.34	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.505
   Length of year:		15384.45	days
   Length of day:		20.85	hours


Planet 8	*gas giant*
   Distance from primary:	23.680	AU
   Mass:			245.942	Earth masses
   Equatorial radius:		67291.7	km
   Density:			1.152	grams/cc
   Eccentricity of orbit:	0.245
   Escape Velocity:		53.99	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2165.95	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.458
   Length of year:		39977.72	days
   Length of day:		8.78	hours


Planet 9	*gas giant*
   Distance from primary:	37.606	AU
   Mass:			0.607	Earth masses
   Equatorial radius:		12135.0	km
   Density:			0.484	grams/cc
   Eccentricity of orbit:	0.172
   Escape Velocity:		6.31	km/sec
   Molecular weight retained:	19.91 and above
   Surface acceleration:	164.25	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.490
   Length of year:		80035.91	days
   Length of day:		31.89	hours


Planet 10	
   Distance from primary:	49.201	AU
   Mass:			0.059	Earth masses
   Equatorial radius:		3369.5	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.088
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.71	degrees Celcius
   Normal daytime temperature:	-223.54	degrees Celcius
   Normal night temperature:	-235.77	degrees Celcius
   Maximum temperature:   	-210.68	degrees Celcius
   Minimum temperature:   	-248.87	degrees Celcius
   Escape Velocity:		3.74	km/sec
   Molecular weight retained:	56.77 and above
   Surface acceleration:	207.48	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.144
   Length of year:		119772.22	days
   Length of day:		33.27	hours
   Boiling point of water:	-73.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


