                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488b6
Stellar mass: 1.11 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6414 K
Stellar class: F7
Age: 4.037 billion years  (2.732 billion left on main sequence)
Habitable ecosphere radius: 1.279 AU

Planets present at:
1	  0.418 AU	no atmosphere
2	  0.477 AU	no atmosphere
3	  0.642 AU	greenhouse
4	  0.813 AU	no atmosphere
5	  1.832 AU	cold
6	  2.115 AU	gas giant
7	  3.923 AU	gas giant
8	  6.815 AU	gas giant
9	 14.476 AU	gas giant
10	 28.829 AU	gas giant
11	 49.299 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.418	AU
   Mass:			0.046	Earth masses
   Equatorial radius:		2311.1	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		208.48	degrees Celcius
   Normal daytime temperature:	416.42	degrees Celcius
   Normal night temperature:	-189.14	degrees Celcius
   Maximum temperature:   	419.79	degrees Celcius
   Minimum temperature:   	-200.11	degrees Celcius
   Escape Velocity:		3.97	km/sec
   Molecular weight retained:	50.46 and above
   Surface acceleration:	340.37	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.049
   Length of year:		93.84	days
   Length of day:		1796.80	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.477	AU
   Mass:			0.050	Earth masses
   Equatorial radius:		2388.5	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		174.91	degrees Celcius
   Maximum temperature:   	378.96	degrees Celcius
   Minimum temperature:   	-211.49	degrees Celcius
   Escape Velocity:		4.10	km/sec
   Molecular weight retained:	47.23 and above
   Surface acceleration:	351.87	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.072
   Length of year:		114.48	days
   Length of day:		2747.49	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.642	AU
   Mass:			1.108	Earth masses
   Equatorial radius:		6621.5	km
   Density:			5.447	grams/cc
   Eccentricity of orbit:	0.110
   Surface gravity:		1.03	Earth gees
   Surface pressure:		113.128	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		543.86	degrees Celcius
   Maximum temperature:   	549.22	degrees Celcius
   Minimum temperature:   	533.72	degrees Celcius
   Escape Velocity:		11.55	km/sec
   Molecular weight retained:	5.95 and above
   Surface acceleration:	1007.90	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.564
   Length of year:		178.41	days
   Length of day:		57.73	hours
   Boiling point of water:	300.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1187
				Cesium       melts at 28    boils at 1230
				Gallium      melts at 30    boils at 3839
				Rubidium     melts at 39    boils at 1204
				Potassium    melts at 63    boils at 1323
				Sodium       melts at 98    boils at 1501
				Indium       melts at 157   boils at 3343
				Lithium      melts at 181   boils at 2216
				Selenium     melts at 217   boils at 1199
				Tin          melts at 232   boils at 4177
				Polonium     melts at 254   boils at 1625
				Bismuth      melts at 271   boils at 2550
				Thallium     melts at 304   boils at 2385
				Cadmium      melts at 321   boils at 1322
				Lead         melts at 328   boils at 2837
				Zinc         melts at 420   boils at 1540
				Tellurium    melts at 450   boils at 1668
   gasses in atmosphere:
				Sulfur           23.1%  PP 26133.1 mb
				Nitrogen         76.2%  PP 86213.2 mb
				Phosphorus        0.5%  PP  518.4 mb
				CarbonDioxide     0.1%  PP   58.3 mb
				Ethanol           0.1%  PP   59.3 mb


Planet 4	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.813	AU
   Mass:			0.096	Earth masses
   Equatorial radius:		2961.3	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.100
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		70.95	degrees Celcius
   Maximum temperature:   	249.55	degrees Celcius
   Minimum temperature:   	-228.41	degrees Celcius
   Escape Velocity:		5.09	km/sec
   Molecular weight retained:	30.64 and above
   Surface acceleration:	437.38	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.064
   Length of year:		254.39	days
   Length of day:		4990.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.832	AU
   Mass:			0.870	Earth masses
   Equatorial radius:		6118.7	km
   Density:			5.416	grams/cc
   Eccentricity of orbit:	0.141
   Surface gravity:		0.94	Earth gees
   Surface pressure:		0.720	Earth atmospheres
   Surface temperature:		-66.70	degrees Celcius
   Normal daytime temperature:	-62.96	degrees Celcius
   Normal night temperature:	-70.65	degrees Celcius
   Maximum temperature:   	-41.88	degrees Celcius
   Minimum temperature:   	-93.22	degrees Celcius
   Escape Velocity:		10.65	km/sec
   Molecular weight retained:	7.00 and above
   Surface acceleration:	926.20	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.630
   Length of year:		860.67	days
   Length of day:		15.77	hours
   Boiling point of water:	91.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.14
   Ice cover percentage:	95.86
   liquids at surface:
				Ethanol      melts at -114  boils at 70
				Chlorine     melts at -101  boils at -40
				Ammonia      melts at -78   boils at -39
   gasses in atmosphere:
				Oxygen            0.9%  PP    6.4 mb
				Nitrogen         98.9%  PP  712.2 mb
				CarbonDioxide     0.1%  PP    0.4 mb
				Ozone             0.1%  PP    0.5 mb


Planet 6	*gas giant*
   Distance from primary:	2.115	AU
   Mass:			38.658	Earth masses
   Equatorial radius:		32079.1	km
   Density:			1.671	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		31.00	km/sec
   Molecular weight retained:	0.83 and above
   Surface acceleration:	1498.09	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.525
   Length of year:		1067.61	days
   Length of day:		10.56	hours


Planet 7	*gas giant*
   Distance from primary:	3.923	AU
   Mass:			3.072	Earth masses
   Equatorial radius:		16136.7	km
   Density:			1.043	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		12.32	km/sec
   Molecular weight retained:	5.23 and above
   Surface acceleration:	470.49	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.478
   Length of year:		2698.08	days
   Length of day:		18.84	hours


Planet 8	*gas giant*
   Distance from primary:	6.815	AU
   Mass:			628.409	Earth masses
   Equatorial radius:		79759.6	km
   Density:			1.767	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		79.27	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3939.27	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.550
   Length of year:		6171.83	days
   Length of day:		6.51	hours


Planet 9	*gas giant*
   Distance from primary:	14.476	AU
   Mass:			42.748	Earth masses
   Equatorial radius:		38777.4	km
   Density:			1.046	grams/cc
   Eccentricity of orbit:	0.105
   Escape Velocity:		29.65	km/sec
   Molecular weight retained:	0.90 and above
   Surface acceleration:	1133.71	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.532
   Length of year:		19122.00	days
   Length of day:		12.14	hours


Planet 10	*gas giant*
   Distance from primary:	28.829	AU
   Mass:			21.107	Earth masses
   Equatorial radius:		33428.4	km
   Density:			0.806	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		22.44	km/sec
   Molecular weight retained:	1.58 and above
   Surface acceleration:	753.24	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.471
   Length of year:		53738.85	days
   Length of day:		14.89	hours


Planet 11	
   Distance from primary:	49.299	AU
   Mass:			0.214	Earth masses
   Equatorial radius:		5158.3	km
   Density:			2.227	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.68	degrees Celcius
   Normal daytime temperature:	-224.57	degrees Celcius
   Normal night temperature:	-234.69	degrees Celcius
   Maximum temperature:   	-211.11	degrees Celcius
   Minimum temperature:   	-248.56	degrees Celcius
   Escape Velocity:		5.76	km/sec
   Molecular weight retained:	23.96 and above
   Surface acceleration:	321.08	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.155
   Length of year:		120175.92	days
   Length of day:		26.75	hours
   Boiling point of water:	-50.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


