                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048918
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6140 K
Stellar class: F9
Age: 4.191 billion years  (2.566 billion left on main sequence)
Habitable ecosphere radius: 1.280 AU

Planets present at:
1	  0.433 AU	no atmosphere
2	  0.604 AU	no atmosphere
3	  1.349 AU	
4	  2.058 AU	gas giant
5	  4.194 AU	gas giant
6	  8.105 AU	gas giant
7	 19.115 AU	gas giant
8	 31.715 AU	gas giant
9	 35.375 AU	no atmosphere
10	 43.841 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.433	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		3631.6	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.190
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		198.75	degrees Celcius
   Normal daytime temperature:	404.08	degrees Celcius
   Normal night temperature:	-187.88	degrees Celcius
   Maximum temperature:   	407.73	degrees Celcius
   Minimum temperature:   	-199.70	degrees Celcius
   Escape Velocity:		6.25	km/sec
   Molecular weight retained:	20.30 and above
   Surface acceleration:	538.41	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.062
   Length of year:		98.88	days
   Length of day:		1616.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.604	AU
   Mass:			0.524	Earth masses
   Equatorial radius:		5183.5	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.79	degrees Celcius
   Maximum temperature:   	316.92	degrees Celcius
   Minimum temperature:   	-221.45	degrees Celcius
   Escape Velocity:		8.98	km/sec
   Molecular weight retained:	9.85 and above
   Surface acceleration:	777.51	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.079
   Length of year:		162.73	days
   Length of day:		3905.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.349	AU
   Mass:			1.056	Earth masses
   Equatorial radius:		6519.4	km
   Density:			5.440	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		1.01	Earth gees
   Surface pressure:		1.028	Earth atmospheres
   Surface temperature:		16.17	degrees Celcius
   Normal daytime temperature:	20.47	degrees Celcius
   Normal night temperature:	11.59	degrees Celcius
   Maximum temperature:   	42.07	degrees Celcius
   Minimum temperature:   	-11.24	degrees Celcius
   Escape Velocity:		11.37	km/sec
   Molecular weight retained:	6.14 and above
   Surface acceleration:	991.20	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.261
   Length of year:		544.06	days
   Length of day:		15.36	hours
   Boiling point of water:	100.8	degrees Celcius
   Hydrosphere percentage:	66.18
   Cloud cover percentage:	50.43
   Ice cover percentage:	1.50
   liquids at surface:
				Ethanol      melts at -114  boils at 79
				Mercury      melts at -39   boils at 358
				Bromine      melts at -7    boils at 60
				Water        melts at 0     boils at 101
   gasses in atmosphere:
				Oxygen           20.5%  PP  210.6 mb
				Nitrogen         79.4%  PP  815.9 mb


Planet 4	*gas giant*
   Distance from primary:	2.058	AU
   Mass:			101.148	Earth masses
   Equatorial radius:		42367.0	km
   Density:			1.898	grams/cc
   Eccentricity of orbit:	0.113
   Escape Velocity:		43.64	km/sec
   Molecular weight retained:	0.42 and above
   Surface acceleration:	2247.19	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.456
   Length of year:		1024.55	days
   Length of day:		8.62	hours


Planet 5	*gas giant*
   Distance from primary:	4.194	AU
   Mass:			516.412	Earth masses
   Equatorial radius:		72327.5	km
   Density:			1.948	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		75.46	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3936.66	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.476
   Length of year:		2978.83	days
   Length of day:		6.51	hours


Planet 6	*gas giant*
   Distance from primary:	8.105	AU
   Mass:			483.851	Earth masses
   Equatorial radius:		74972.0	km
   Density:			1.638	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		71.74	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3432.83	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.495
   Length of year:		8003.39	days
   Length of day:		6.98	hours


Planet 7	*gas giant*
   Distance from primary:	19.115	AU
   Mass:			50.873	Earth masses
   Equatorial radius:		41748.1	km
   Density:			0.998	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		31.18	km/sec
   Molecular weight retained:	0.82 and above
   Surface acceleration:	1163.99	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.540
   Length of year:		29006.84	days
   Length of day:		11.98	hours


Planet 8	*gas giant*
   Distance from primary:	31.715	AU
   Mass:			12.032	Earth masses
   Equatorial radius:		28598.0	km
   Density:			0.734	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		18.32	km/sec
   Molecular weight retained:	2.37 and above
   Surface acceleration:	586.69	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.518
   Length of year:		61994.24	days
   Length of day:		16.87	hours


Planet 9	
   Distance from primary:	35.375	AU
   Mass:			0.059	Earth masses
   Equatorial radius:		3365.4	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-221.86	degrees Celcius
   Normal daytime temperature:	-214.56	degrees Celcius
   Normal night temperature:	-229.07	degrees Celcius
   Maximum temperature:   	-198.96	degrees Celcius
   Minimum temperature:   	-245.00	degrees Celcius
   Escape Velocity:		3.73	km/sec
   Molecular weight retained:	56.91 and above
   Surface acceleration:	207.23	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.136
   Length of year:		73029.68	days
   Length of day:		33.29	hours
   Boiling point of water:	-74.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


Planet 10	
   Distance from primary:	43.841	AU
   Mass:			0.076	Earth masses
   Equatorial radius:		3664.6	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.20	degrees Celcius
   Normal daytime temperature:	-220.90	degrees Celcius
   Normal night temperature:	-233.39	degrees Celcius
   Maximum temperature:   	-207.24	degrees Celcius
   Minimum temperature:   	-247.38	degrees Celcius
   Escape Velocity:		4.07	km/sec
   Molecular weight retained:	47.93 and above
   Surface acceleration:	225.98	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.146
   Length of year:		100757.87	days
   Length of day:		31.88	hours
   Boiling point of water:	-70.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


