                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950489a6
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6241 K
Stellar class: F8
Age: 4.602 billion years  (2.136 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.312 AU	no atmosphere
2	  0.444 AU	no atmosphere
3	  0.614 AU	no atmosphere
4	  0.872 AU	greenhouse
5	  1.573 AU	gas giant
6	  2.323 AU	no atmosphere
7	  4.044 AU	gas giant
8	  6.504 AU	gas giant
9	 10.105 AU	no atmosphere
10	 11.868 AU	gas giant
11	 17.533 AU	gas giant
12	 33.791 AU	no atmosphere
13	 37.048 AU	no atmosphere
14	 47.044 AU	gas giant
15	 51.675 AU	no atmosphere



Planet 1	
   Distance from primary:	0.312	AU
   Mass:			0.064	Earth masses
   Equatorial radius:		2589.0	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		281.33	degrees Celcius
   Normal daytime temperature:	504.68	degrees Celcius
   Normal night temperature:	-170.68	degrees Celcius
   Maximum temperature:   	507.87	degrees Celcius
   Minimum temperature:   	-182.31	degrees Celcius
   Escape Velocity:		4.45	km/sec
   Molecular weight retained:	40.16 and above
   Surface acceleration:	381.72	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.077
   Length of year:		60.37	days
   Length of day:		1448.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.444	AU
   Mass:			0.065	Earth masses
   Equatorial radius:		2597.0	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.56	degrees Celcius
   Maximum temperature:   	400.59	degrees Celcius
   Minimum temperature:   	-207.57	degrees Celcius
   Escape Velocity:		4.46	km/sec
   Molecular weight retained:	39.91 and above
   Surface acceleration:	382.93	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.069
   Length of year:		102.56	days
   Length of day:		2461.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.614	AU
   Mass:			0.175	Earth masses
   Equatorial radius:		3611.4	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.138
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		121.79	degrees Celcius
   Maximum temperature:   	313.16	degrees Celcius
   Minimum temperature:   	-220.21	degrees Celcius
   Escape Velocity:		6.22	km/sec
   Molecular weight retained:	20.53 and above
   Surface acceleration:	535.34	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.079
   Length of year:		166.87	days
   Length of day:		3035.70	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.872	AU
   Mass:			1.529	Earth masses
   Equatorial radius:		7350.3	km
   Density:			5.495	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		1.15	Earth gees
   Surface pressure:		199.423	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		515.92	degrees Celcius
   Maximum temperature:   	518.74	degrees Celcius
   Minimum temperature:   	510.43	degrees Celcius
   Escape Velocity:		12.88	km/sec
   Molecular weight retained:	4.78 and above
   Surface acceleration:	1128.86	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.511
   Length of year:		282.47	days
   Length of day:		15.90	hours
   Boiling point of water:	339.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1287
				Cesium       melts at 28    boils at 1333
				Gallium      melts at 30    boils at 4122
				Rubidium     melts at 39    boils at 1305
				Potassium    melts at 63    boils at 1433
				Sodium       melts at 98    boils at 1623
				Indium       melts at 157   boils at 3591
				Lithium      melts at 181   boils at 2387
				Selenium     melts at 217   boils at 1300
				Tin          melts at 232   boils at 4483
				Polonium     melts at 254   boils at 1755
				Bismuth      melts at 271   boils at 2744
				Thallium     melts at 304   boils at 2568
				Cadmium      melts at 321   boils at 1432
				Lead         melts at 328   boils at 3051
				Zinc         melts at 420   boils at 1665
				Tellurium    melts at 450   boils at 1801
   gasses in atmosphere:
				Sulfur           20.6%  PP 41174.2 mb
				Nitrogen         78.7%  PP 157032.0 mb
				Phosphorus        0.4%  PP  819.9 mb


Planet 5	*gas giant*
   Distance from primary:	1.573	AU
   Mass:			8.565	Earth masses
   Equatorial radius:		20160.6	km
   Density:			1.491	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		18.41	km/sec
   Molecular weight retained:	2.34 and above
   Surface acceleration:	840.37	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.499
   Length of year:		684.30	days
   Length of day:		14.10	hours


Planet 6	
   Distance from primary:	2.323	AU
   Mass:			0.183	Earth masses
   Equatorial radius:		3661.5	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.033	Earth atmospheres
   Surface temperature:		-89.55	degrees Celcius
   Normal daytime temperature:	-76.41	degrees Celcius
   Normal night temperature:	-102.98	degrees Celcius
   Maximum temperature:   	-52.32	degrees Celcius
   Minimum temperature:   	-128.25	degrees Celcius
   Escape Velocity:		6.31	km/sec
   Molecular weight retained:	19.97 and above
   Surface acceleration:	542.92	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.500
   Length of year:		1228.44	days
   Length of day:		20.60	hours
   Boiling point of water:	25.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	58.93
   liquids at surface:
				Ethanol      melts at -114  boils at 8
				Chlorine     melts at -101  boils at -82
   gasses in atmosphere:
				Ozone            93.1%  PP   31.0 mb
				Argon             0.3%  PP    0.1 mb
				Krypton           5.8%  PP    1.9 mb
				Xenon             0.7%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	4.044	AU
   Mass:			923.621	Earth masses
   Equatorial radius:		85423.3	km
   Density:			2.114	grams/cc
   Eccentricity of orbit:	0.104
   Escape Velocity:		92.86	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	5047.54	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.518
   Length of year:		2818.70	days
   Length of day:		5.75	hours


Planet 8	*gas giant*
   Distance from primary:	6.504	AU
   Mass:			78.193	Earth masses
   Equatorial radius:		43252.2	km
   Density:			1.379	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		37.97	km/sec
   Molecular weight retained:	0.55 and above
   Surface acceleration:	1666.83	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.481
   Length of year:		5754.63	days
   Length of day:		10.01	hours


Planet 9	
   Distance from primary:	10.105	AU
   Mass:			0.118	Earth masses
   Equatorial radius:		4232.2	km
   Density:			2.214	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.011	Earth atmospheres
   Surface temperature:		-181.05	degrees Celcius
   Normal daytime temperature:	-170.34	degrees Celcius
   Normal night temperature:	-191.88	degrees Celcius
   Maximum temperature:   	-151.44	degrees Celcius
   Minimum temperature:   	-211.86	degrees Celcius
   Escape Velocity:		4.71	km/sec
   Molecular weight retained:	35.82 and above
   Surface acceleration:	261.81	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.276
   Length of year:		11145.90	days
   Length of day:		29.62	hours
   Boiling point of water:	6.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	21.86
   liquids at surface:
				Ozone        melts at -193  boils at -152
   gasses in atmosphere:
				Argon            100.0%  PP   10.6 mb


Planet 10	*gas giant*
   Distance from primary:	11.868	AU
   Mass:			1.090	Earth masses
   Equatorial radius:		13078.8	km
   Density:			0.695	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		8.15	km/sec
   Molecular weight retained:	11.94 and above
   Surface acceleration:	254.22	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.542
   Length of year:		14186.45	days
   Length of day:		25.63	hours


Planet 11	*gas giant*
   Distance from primary:	17.533	AU
   Mass:			273.323	Earth masses
   Equatorial radius:		67673.9	km
   Density:			1.258	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		56.76	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2379.98	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.484
   Length of year:		25464.12	days
   Length of day:		8.38	hours


Planet 12	
   Distance from primary:	33.791	AU
   Mass:			0.205	Earth masses
   Equatorial radius:		5082.7	km
   Density:			2.226	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-220.53	degrees Celcius
   Normal daytime temperature:	-214.31	degrees Celcius
   Normal night temperature:	-226.69	degrees Celcius
   Maximum temperature:   	-202.03	degrees Celcius
   Minimum temperature:   	-239.73	degrees Celcius
   Escape Velocity:		5.67	km/sec
   Molecular weight retained:	24.70 and above
   Surface acceleration:	316.20	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.151
   Length of year:		68156.07	days
   Length of day:		26.95	hours
   Boiling point of water:	-51.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 13	
   Distance from primary:	37.048	AU
   Mass:			0.137	Earth masses
   Equatorial radius:		4449.6	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-222.98	degrees Celcius
   Normal daytime temperature:	-216.67	degrees Celcius
   Normal night temperature:	-229.21	degrees Celcius
   Maximum temperature:   	-203.26	degrees Celcius
   Minimum temperature:   	-243.24	degrees Celcius
   Escape Velocity:		4.95	km/sec
   Molecular weight retained:	32.36 and above
   Surface acceleration:	275.63	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.138
   Length of year:		78244.64	days
   Length of day:		28.87	hours
   Boiling point of water:	-60.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 14	*gas giant*
   Distance from primary:	47.044	AU
   Mass:			0.236	Earth masses
   Equatorial radius:		9385.2	km
   Density:			0.407	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		4.48	km/sec
   Molecular weight retained:	39.61 and above
   Surface acceleration:	106.76	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.542
   Length of year:		111960.09	days
   Length of day:		39.56	hours


Planet 15	
   Distance from primary:	51.675	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		2317.0	km
   Density:			2.194	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.14	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.77	degrees Celcius
   Normal daytime temperature:	-223.70	degrees Celcius
   Normal night temperature:	-237.69	degrees Celcius
   Maximum temperature:   	-209.42	degrees Celcius
   Minimum temperature:   	-251.71	degrees Celcius
   Escape Velocity:		2.57	km/sec
   Molecular weight retained:	120.57 and above
   Surface acceleration:	142.08	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.145
   Length of year:		128892.75	days
   Length of day:		40.21	hours
   Boiling point of water:	-89.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


