                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a47
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6191 K
Stellar class: F8
Age: 3.845 billion years  (2.873 billion left on main sequence)
Habitable ecosphere radius: 1.285 AU

Planets present at:
1	  0.365 AU	no atmosphere
2	  0.402 AU	no atmosphere
3	  0.573 AU	no atmosphere
4	  0.962 AU	greenhouse
5	  1.689 AU	gas giant
6	  2.952 AU	gas giant
7	  5.991 AU	gas giant
8	 15.144 AU	gas giant
9	 29.132 AU	gas giant
10	 46.747 AU	no atmosphere



Planet 1	
   Distance from primary:	0.365	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		1520.7	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.19	degrees Celcius
   Maximum temperature:   	458.28	degrees Celcius
   Minimum temperature:   	-194.53	degrees Celcius
   Escape Velocity:		2.61	km/sec
   Molecular weight retained:	116.84 and above
   Surface acceleration:	223.38	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.073
   Length of year:		76.51	days
   Length of day:		1836.17	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.402	AU
   Mass:			0.192	Earth masses
   Equatorial radius:		3723.2	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		216.77	degrees Celcius
   Maximum temperature:   	429.93	degrees Celcius
   Minimum temperature:   	-201.03	degrees Celcius
   Escape Velocity:		6.41	km/sec
   Molecular weight retained:	19.30 and above
   Surface acceleration:	552.29	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.067
   Length of year:		88.44	days
   Length of day:		2122.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.573	AU
   Mass:			0.332	Earth masses
   Equatorial radius:		4459.9	km
   Density:			5.335	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.68	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		135.68	degrees Celcius
   Maximum temperature:   	330.40	degrees Celcius
   Minimum temperature:   	-219.23	degrees Celcius
   Escape Velocity:		7.70	km/sec
   Molecular weight retained:	13.38 and above
   Surface acceleration:	664.98	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.081
   Length of year:		150.52	days
   Length of day:		3612.36	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.962	AU
   Mass:			0.997	Earth masses
   Equatorial radius:		6396.9	km
   Density:			5.433	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.99	Earth gees
   Surface pressure:		95.795	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		390.31	degrees Celcius
   Maximum temperature:   	394.71	degrees Celcius
   Minimum temperature:   	384.38	degrees Celcius
   Escape Velocity:		11.15	km/sec
   Molecular weight retained:	6.39 and above
   Surface acceleration:	971.23	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.533
   Length of year:		327.09	days
   Length of day:		16.50	hours
   Boiling point of water:	289.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1160
				Cesium       melts at 28    boils at 1202
				Gallium      melts at 30    boils at 3763
				Rubidium     melts at 39    boils at 1176
				Potassium    melts at 63    boils at 1293
				Sodium       melts at 98    boils at 1468
				Sulfur       melts at 113   boils at 810
				Indium       melts at 157   boils at 3276
				Lithium      melts at 181   boils at 2170
				Selenium     melts at 217   boils at 1172
				Tin          melts at 232   boils at 4094
				Polonium     melts at 254   boils at 1589
				Bismuth      melts at 271   boils at 2497
				Thallium     melts at 304   boils at 2336
				Cadmium      melts at 321   boils at 1292
				Lead         melts at 328   boils at 2779
   gasses in atmosphere:
				Nitrogen         99.1%  PP 94963.7 mb
				Phosphorus        0.6%  PP  549.0 mb
				CarbonDioxide     0.1%  PP   60.4 mb
				Ozone             0.1%  PP   51.6 mb
				Ethanol           0.1%  PP   61.3 mb


Planet 5	*gas giant*
   Distance from primary:	1.689	AU
   Mass:			26.511	Earth masses
   Equatorial radius:		28192.4	km
   Density:			1.688	grams/cc
   Eccentricity of orbit:	0.089
   Escape Velocity:		27.39	km/sec
   Molecular weight retained:	1.06 and above
   Surface acceleration:	1330.15	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.459
   Length of year:		761.19	days
   Length of day:		11.21	hours


Planet 6	*gas giant*
   Distance from primary:	2.952	AU
   Mass:			27.322	Earth masses
   Equatorial radius:		29796.5	km
   Density:			1.474	grams/cc
   Eccentricity of orbit:	0.154
   Escape Velocity:		27.04	km/sec
   Molecular weight retained:	1.09 and above
   Surface acceleration:	1227.22	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.466
   Length of year:		1759.45	days
   Length of day:		11.67	hours


Planet 7	*gas giant*
   Distance from primary:	5.991	AU
   Mass:			883.773	Earth masses
   Equatorial radius:		87124.7	km
   Density:			1.907	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		89.95	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4642.99	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.543
   Length of year:		5079.96	days
   Length of day:		6.00	hours


Planet 8	*gas giant*
   Distance from primary:	15.144	AU
   Mass:			232.766	Earth masses
   Equatorial radius:		63783.2	km
   Density:			1.280	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		53.95	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2281.63	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.522
   Length of year:		20435.19	days
   Length of day:		8.56	hours


Planet 9	*gas giant*
   Distance from primary:	29.132	AU
   Mass:			24.726	Earth masses
   Equatorial radius:		35024.0	km
   Density:			0.821	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		23.73	km/sec
   Molecular weight retained:	1.41 and above
   Surface acceleration:	803.81	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.464
   Length of year:		54536.12	days
   Length of day:		14.42	hours


Planet 10	
   Distance from primary:	46.747	AU
   Mass:			0.115	Earth masses
   Equatorial radius:		4200.1	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.129
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.72	degrees Celcius
   Normal daytime temperature:	-222.99	degrees Celcius
   Normal night temperature:	-234.35	degrees Celcius
   Maximum temperature:   	-210.68	degrees Celcius
   Minimum temperature:   	-247.10	degrees Celcius
   Escape Velocity:		4.67	km/sec
   Molecular weight retained:	36.38 and above
   Surface acceleration:	259.78	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.160
   Length of year:		110856.46	days
   Length of day:		29.73	hours
   Boiling point of water:	-63.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


