                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950480b4
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6237 K
Stellar class: F8
Age: 2.966 billion years  (4.069 billion left on main sequence)
Habitable ecosphere radius: 1.248 AU

Planets present at:
1	  0.381 AU	no atmosphere
2	  0.493 AU	no atmosphere
3	  0.655 AU	no atmosphere
4	  1.084 AU	greenhouse
5	  1.665 AU	high pressure
6	  3.264 AU	gas giant
7	  4.015 AU	gas giant
8	  5.432 AU	gas giant
9	  8.607 AU	gas giant
10	 15.573 AU	gas giant
11	 29.353 AU	gas giant
12	 50.630 AU	gas giant



Planet 1	
   Distance from primary:	0.381	AU
   Mass:			0.053	Earth masses
   Equatorial radius:		2431.6	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		224.05	degrees Celcius
   Maximum temperature:   	438.81	degrees Celcius
   Minimum temperature:   	-198.86	degrees Celcius
   Escape Velocity:		4.17	km/sec
   Molecular weight retained:	45.56 and above
   Surface acceleration:	358.28	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.059
   Length of year:		82.02	days
   Length of day:		1968.48	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.493	AU
   Mass:			0.130	Earth masses
   Equatorial radius:		3275.3	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		161.00	degrees Celcius
   Maximum temperature:   	361.87	degrees Celcius
   Minimum temperature:   	-214.25	degrees Celcius
   Escape Velocity:		5.63	km/sec
   Molecular weight retained:	25.01 and above
   Surface acceleration:	484.57	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.081
   Length of year:		120.97	days
   Length of day:		2903.22	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.655	AU
   Mass:			0.077	Earth masses
   Equatorial radius:		2752.7	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		105.35	degrees Celcius
   Maximum temperature:   	292.78	degrees Celcius
   Minimum temperature:   	-224.54	degrees Celcius
   Escape Velocity:		4.73	km/sec
   Molecular weight retained:	35.50 and above
   Surface acceleration:	406.17	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.064
   Length of year:		185.11	days
   Length of day:		4442.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.084	AU
   Mass:			1.038	Earth masses
   Equatorial radius:		6482.4	km
   Density:			5.438	grams/cc
   Eccentricity of orbit:	0.226
   Surface gravity:		1.00	Earth gees
   Surface pressure:		101.956	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		329.25	degrees Celcius
   Maximum temperature:   	333.85	degrees Celcius
   Minimum temperature:   	323.58	degrees Celcius
   Escape Velocity:		11.30	km/sec
   Molecular weight retained:	6.22 and above
   Surface acceleration:	985.16	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.589
   Length of year:		393.69	days
   Length of day:		15.65	hours
   Boiling point of water:	293.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 684
				Francium     melts at 27    boils at 1170
				Cesium       melts at 28    boils at 1212
				Gallium      melts at 30    boils at 3791
				Rubidium     melts at 39    boils at 1186
				Potassium    melts at 63    boils at 1304
				Sodium       melts at 98    boils at 1480
				Sulfur       melts at 113   boils at 817
				Indium       melts at 157   boils at 3300
				Lithium      melts at 181   boils at 2187
				Selenium     melts at 217   boils at 1182
				Tin          melts at 232   boils at 4125
				Polonium     melts at 254   boils at 1602
				Bismuth      melts at 271   boils at 2517
				Astatine     melts at 302   boils at 654
				Thallium     melts at 304   boils at 2354
				Cadmium      melts at 321   boils at 1303
				Lead         melts at 328   boils at 2801
   gasses in atmosphere:
				Nitrogen         99.2%  PP 101130.0 mb
				Phosphorus        0.5%  PP  543.6 mb
				CarbonDioxide     0.1%  PP   58.5 mb
				Ozone             0.1%  PP   51.4 mb
				Ethanol           0.1%  PP   59.2 mb


Planet 5	
   Distance from primary:	1.665	AU
   Mass:			2.293	Earth masses
   Equatorial radius:		8373.3	km
   Density:			5.574	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		1.33	Earth gees
   Surface pressure:		4.459	Earth atmospheres
   Surface temperature:		6.78	degrees Celcius
   Normal daytime temperature:	8.56	degrees Celcius
   Normal night temperature:	4.89	degrees Celcius
   Maximum temperature:   	21.12	degrees Celcius
   Minimum temperature:   	-8.31	degrees Celcius
   Escape Velocity:		14.78	km/sec
   Molecular weight retained:	3.63 and above
   Surface acceleration:	1304.44	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.169
   Length of year:		749.57	days
   Length of day:		13.28	hours
   Boiling point of water:	146.3	degrees Celcius
   Hydrosphere percentage:	80.15
   Cloud cover percentage:	30.40
   Ice cover percentage:	4.72
   liquids at surface:
				Ethanol      melts at -114  boils at 122
				Mercury      melts at -39   boils at 435
				Bromine      melts at -7    boils at 101
				Water        melts at 0     boils at 146
   gasses in atmosphere:
				Nitrogen          1.1%  PP   47.9 mb
				Helium           98.9%  PP 4410.9 mb


Planet 6	*gas giant*
   Distance from primary:	3.264	AU
   Mass:			3.245	Earth masses
   Equatorial radius:		16180.0	km
   Density:			1.093	grams/cc
   Eccentricity of orbit:	0.123
   Escape Velocity:		12.65	km/sec
   Molecular weight retained:	4.96 and above
   Surface acceleration:	494.32	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.450
   Length of year:		2057.89	days
   Length of day:		18.38	hours


Planet 7	*gas giant*
   Distance from primary:	4.015	AU
   Mass:			10.713	Earth masses
   Equatorial radius:		23321.6	km
   Density:			1.205	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		19.14	km/sec
   Molecular weight retained:	2.17 and above
   Surface acceleration:	785.48	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.478
   Length of year:		2807.81	days
   Length of day:		14.58	hours


Planet 8	*gas giant*
   Distance from primary:	5.432	AU
   Mass:			4.849	Earth masses
   Equatorial radius:		18979.5	km
   Density:			1.012	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		14.27	km/sec
   Molecular weight retained:	3.90 and above
   Surface acceleration:	536.80	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.517
   Length of year:		4418.17	days
   Length of day:		17.64	hours


Planet 9	*gas giant*
   Distance from primary:	8.607	AU
   Mass:			156.895	Earth masses
   Equatorial radius:		54368.7	km
   Density:			1.393	grams/cc
   Eccentricity of orbit:	0.184
   Escape Velocity:		47.97	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2116.65	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.457
   Length of year:		8810.29	days
   Length of day:		8.88	hours


Planet 10	*gas giant*
   Distance from primary:	15.573	AU
   Mass:			196.061	Earth masses
   Equatorial radius:		60958.9	km
   Density:			1.235	grams/cc
   Eccentricity of orbit:	0.127
   Escape Velocity:		50.65	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2104.05	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.461
   Length of year:		21440.53	days
   Length of day:		8.91	hours


Planet 11	*gas giant*
   Distance from primary:	29.353	AU
   Mass:			24.956	Earth masses
   Equatorial radius:		35226.7	km
   Density:			0.815	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		23.77	km/sec
   Molecular weight retained:	1.40 and above
   Surface acceleration:	802.00	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.545
   Length of year:		55493.75	days
   Length of day:		14.43	hours


Planet 12	*gas giant*
   Distance from primary:	50.630	AU
   Mass:			0.438	Earth masses
   Equatorial radius:		11334.2	km
   Density:			0.429	grams/cc
   Eccentricity of orbit:	0.303
   Escape Velocity:		5.55	km/sec
   Molecular weight retained:	25.78 and above
   Surface acceleration:	135.83	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.476
   Length of year:		125715.96	days
   Length of day:		35.07	hours


