                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504884e
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6306 K
Stellar class: F7
Age: 5.949 billion years  (0.832 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.403 AU	no atmosphere
2	  0.546 AU	no atmosphere
3	  1.060 AU	greenhouse
4	  1.747 AU	cold
5	  2.370 AU	cold
6	  3.547 AU	gas giant
7	  7.677 AU	gas giant
8	 11.645 AU	gas giant
9	 27.603 AU	gas giant
10	 50.495 AU	no atmosphere



Planet 1	
   Distance from primary:	0.403	AU
   Mass:			0.050	Earth masses
   Equatorial radius:		2378.5	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		215.15	degrees Celcius
   Maximum temperature:   	428.00	degrees Celcius
   Minimum temperature:   	-201.50	degrees Celcius
   Escape Velocity:		4.08	km/sec
   Molecular weight retained:	47.63 and above
   Surface acceleration:	350.39	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.064
   Length of year:		88.83	days
   Length of day:		2131.84	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.546	AU
   Mass:			0.517	Earth masses
   Equatorial radius:		5159.7	km
   Density:			5.366	grams/cc
   Eccentricity of orbit:	0.133
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		146.29	degrees Celcius
   Maximum temperature:   	343.58	degrees Celcius
   Minimum temperature:   	-215.14	degrees Celcius
   Escape Velocity:		8.94	km/sec
   Molecular weight retained:	9.94 and above
   Surface acceleration:	773.77	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.064
   Length of year:		140.20	days
   Length of day:		2574.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.060	AU
   Mass:			1.796	Earth masses
   Equatorial radius:		7741.2	km
   Density:			5.524	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		1.22	Earth gees
   Surface pressure:		327.988	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		528.74	degrees Celcius
   Maximum temperature:   	530.94	degrees Celcius
   Minimum temperature:   	523.82	degrees Celcius
   Escape Velocity:		13.60	km/sec
   Molecular weight retained:	4.29 and above
   Surface acceleration:	1195.11	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.439
   Length of year:		378.98	days
   Length of day:		14.38	hours
   Boiling point of water:	378.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1387
				Cesium       melts at 28    boils at 1436
				Gallium      melts at 30    boils at 4404
				Rubidium     melts at 39    boils at 1406
				Potassium    melts at 63    boils at 1542
				Sodium       melts at 98    boils at 1745
				Indium       melts at 157   boils at 3839
				Lithium      melts at 181   boils at 2558
				Selenium     melts at 217   boils at 1401
				Tin          melts at 232   boils at 4788
				Polonium     melts at 254   boils at 1885
				Bismuth      melts at 271   boils at 2937
				Thallium     melts at 304   boils at 2750
				Cadmium      melts at 321   boils at 1541
				Lead         melts at 328   boils at 3264
				Zinc         melts at 420   boils at 1789
				Tellurium    melts at 450   boils at 1934
   gasses in atmosphere:
				Sulfur           20.2%  PP 66263.1 mb
				Nitrogen         79.2%  PP 259824.6 mb
				Phosphorus        0.4%  PP 1320.3 mb


Planet 4	
   Distance from primary:	1.747	AU
   Mass:			1.371	Earth masses
   Equatorial radius:		7095.0	km
   Density:			5.478	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		1.11	Earth gees
   Surface pressure:		1.465	Earth atmospheres
   Surface temperature:		-68.91	degrees Celcius
   Normal daytime temperature:	-66.46	degrees Celcius
   Normal night temperature:	-71.50	degrees Celcius
   Maximum temperature:   	-51.08	degrees Celcius
   Minimum temperature:   	-87.96	degrees Celcius
   Escape Velocity:		12.41	km/sec
   Molecular weight retained:	5.15 and above
   Surface acceleration:	1086.12	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.705
   Length of year:		801.86	days
   Length of day:		14.57	hours
   Boiling point of water:	110.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.13
   Ice cover percentage:	92.04
   liquids at surface:
				Ethanol      melts at -114  boils at 89
				Chlorine     melts at -101  boils at -27
				Ammonia      melts at -78   boils at -27
				Radon        melts at -71   boils at -56
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1463.0 mb
				CarbonDioxide     0.1%  PP    0.8 mb
				Ozone             0.1%  PP    0.8 mb


Planet 5	
   Distance from primary:	2.370	AU
   Mass:			0.604	Earth masses
   Equatorial radius:		5431.5	km
   Density:			5.379	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.299	Earth atmospheres
   Surface temperature:		-82.68	degrees Celcius
   Normal daytime temperature:	-77.24	degrees Celcius
   Normal night temperature:	-88.40	degrees Celcius
   Maximum temperature:   	-55.37	degrees Celcius
   Minimum temperature:   	-111.83	degrees Celcius
   Escape Velocity:		9.42	km/sec
   Molecular weight retained:	8.95 and above
   Surface acceleration:	816.56	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.505
   Length of year:		1267.39	days
   Length of day:		16.78	hours
   Boiling point of water:	69.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	72.84
   liquids at surface:
				Ethanol      melts at -114  boils at 50
				Chlorine     melts at -101  boils at -53
   gasses in atmosphere:
				Oxygen            0.8%  PP    2.3 mb
				Nitrogen         99.1%  PP  296.7 mb
				Ozone             0.1%  PP    0.3 mb


Planet 6	*gas giant*
   Distance from primary:	3.547	AU
   Mass:			671.358	Earth masses
   Equatorial radius:		77013.1	km
   Density:			2.097	grams/cc
   Eccentricity of orbit:	0.097
   Escape Velocity:		83.38	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4514.03	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.455
   Length of year:		2317.55	days
   Length of day:		6.08	hours


Planet 7	*gas giant*
   Distance from primary:	7.677	AU
   Mass:			6.103	Earth masses
   Equatorial radius:		20849.4	km
   Density:			0.961	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		15.28	km/sec
   Molecular weight retained:	3.40 and above
   Surface acceleration:	559.86	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.451
   Length of year:		7386.48	days
   Length of day:		17.27	hours


Planet 8	*gas giant*
   Distance from primary:	11.645	AU
   Mass:			525.703	Earth masses
   Equatorial radius:		79179.4	km
   Density:			1.511	grams/cc
   Eccentricity of orbit:	0.078
   Escape Velocity:		72.77	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3343.91	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.513
   Length of year:		13791.07	days
   Length of day:		7.07	hours


Planet 9	*gas giant*
   Distance from primary:	27.603	AU
   Mass:			44.619	Earth masses
   Equatorial radius:		41438.8	km
   Density:			0.895	grams/cc
   Eccentricity of orbit:	0.177
   Escape Velocity:		29.31	km/sec
   Molecular weight retained:	0.92 and above
   Surface acceleration:	1036.21	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.511
   Length of year:		50359.27	days
   Length of day:		12.70	hours


Planet 10	
   Distance from primary:	50.495	AU
   Mass:			0.175	Earth masses
   Equatorial radius:		4824.9	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.04	degrees Celcius
   Normal daytime temperature:	-224.82	degrees Celcius
   Normal night temperature:	-235.16	degrees Celcius
   Maximum temperature:   	-208.94	degrees Celcius
   Minimum temperature:   	-251.08	degrees Celcius
   Escape Velocity:		5.38	km/sec
   Molecular weight retained:	27.46 and above
   Surface acceleration:	299.61	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.140
   Length of year:		124608.86	days
   Length of day:		27.69	hours
   Boiling point of water:	-53.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


