                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e40
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6095 K
Stellar class: F9
Age: 3.035 billion years  (4.085 billion left on main sequence)
Habitable ecosphere radius: 1.238 AU

Planets present at:
1	  0.309 AU	no atmosphere
2	  0.451 AU	no atmosphere
3	  0.517 AU	no atmosphere
4	  0.648 AU	no atmosphere
5	  0.970 AU	greenhouse
6	  1.510 AU	no atmosphere
7	  2.701 AU	gas giant
8	  6.439 AU	gas giant
9	 16.468 AU	gas giant
10	 22.733 AU	gas giant
11	 37.883 AU	gas giant
12	 48.686 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.309	AU
   Mass:			0.082	Earth masses
   Equatorial radius:		2803.2	km
   Density:			5.281	grams/cc
   Eccentricity of orbit:	0.144
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		274.80	degrees Celcius
   Normal daytime temperature:	495.39	degrees Celcius
   Normal night temperature:	-159.55	degrees Celcius
   Maximum temperature:   	499.30	degrees Celcius
   Minimum temperature:   	-174.16	degrees Celcius
   Escape Velocity:		4.82	km/sec
   Molecular weight retained:	34.22 and above
   Surface acceleration:	413.72	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.070
   Length of year:		60.14	days
   Length of day:		1079.94	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.451	AU
   Mass:			0.014	Earth masses
   Equatorial radius:		1563.2	km
   Density:			5.257	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		180.94	degrees Celcius
   Maximum temperature:   	386.17	degrees Celcius
   Minimum temperature:   	-209.16	degrees Celcius
   Escape Velocity:		2.68	km/sec
   Molecular weight retained:	110.56 and above
   Surface acceleration:	229.66	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.066
   Length of year:		105.99	days
   Length of day:		2543.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.517	AU
   Mass:			0.093	Earth masses
   Equatorial radius:		2929.7	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.55	degrees Celcius
   Maximum temperature:   	346.55	degrees Celcius
   Minimum temperature:   	-216.91	degrees Celcius
   Escape Velocity:		5.03	km/sec
   Molecular weight retained:	31.31 and above
   Surface acceleration:	432.64	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.089
   Length of year:		129.89	days
   Length of day:		3117.45	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.648	AU
   Mass:			0.228	Earth masses
   Equatorial radius:		3942.6	km
   Density:			5.315	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		106.56	degrees Celcius
   Maximum temperature:   	294.23	degrees Celcius
   Minimum temperature:   	-224.39	degrees Celcius
   Escape Velocity:		6.80	km/sec
   Molecular weight retained:	17.19 and above
   Surface acceleration:	585.68	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.059
   Length of year:		182.35	days
   Length of day:		4376.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.970	AU
   Mass:			2.946	Earth masses
   Equatorial radius:		9068.9	km
   Density:			5.635	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		1.46	Earth gees
   Surface pressure:		834.654	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		650.09	degrees Celcius
   Maximum temperature:   	650.74	degrees Celcius
   Minimum temperature:   	645.31	degrees Celcius
   Escape Velocity:		16.10	km/sec
   Molecular weight retained:	3.06 and above
   Surface acceleration:	1428.28	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.541
   Length of year:		333.98	days
   Length of day:		12.94	hours
   Boiling point of water:	468.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1615
				Cesium       melts at 28    boils at 1670
				Gallium      melts at 30    boils at 5045
				Rubidium     melts at 39    boils at 1637
				Potassium    melts at 63    boils at 1791
				Sodium       melts at 98    boils at 2021
				Indium       melts at 157   boils at 4403
				Lithium      melts at 181   boils at 2946
				Selenium     melts at 217   boils at 1631
				Tin          melts at 232   boils at 5482
				Polonium     melts at 254   boils at 2181
				Bismuth      melts at 271   boils at 3378
				Thallium     melts at 304   boils at 3165
				Cadmium      melts at 321   boils at 1790
				Lead         melts at 328   boils at 3749
				Zinc         melts at 420   boils at 2072
				Tellurium    melts at 450   boils at 2237
				Antimony     melts at 631   boils at 3423
				Neptunium    melts at 640   boils at 8024
				Plutonium    melts at 641   boils at 6689
				Magnesium    melts at 649   boils at 2465
   gasses in atmosphere:
				Sulfur            0.1%  PP  857.2 mb
				Nitrogen          0.5%  PP 4068.7 mb
				Helium           99.4%  PP 829703.4 mb


Planet 6	
   Distance from primary:	1.510	AU
   Mass:			0.062	Earth masses
   Equatorial radius:		2553.3	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.003	Earth atmospheres
   Surface temperature:		-44.84	degrees Celcius
   Normal daytime temperature:	-19.86	degrees Celcius
   Normal night temperature:	-69.98	degrees Celcius
   Maximum temperature:   	6.14	degrees Celcius
   Minimum temperature:   	-96.50	degrees Celcius
   Escape Velocity:		4.38	km/sec
   Molecular weight retained:	41.30 and above
   Surface acceleration:	376.41	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.340
   Length of year:		648.60	days
   Length of day:		25.60	hours
   Boiling point of water:	-11.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	34.72
   liquids at surface:
				Ethanol      melts at -114  boils at -23
   gasses in atmosphere:
				CarbonDioxide    26.4%  PP    0.8 mb
				Ozone            61.0%  PP    2.0 mb
				Krypton          10.9%  PP    0.4 mb
				Xenon             1.6%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	2.701	AU
   Mass:			230.335	Earth masses
   Equatorial radius:		55246.9	km
   Density:			1.949	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		57.66	km/sec
   Molecular weight retained:	0.24 and above
   Surface acceleration:	3009.42	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.542
   Length of year:		1550.66	days
   Length of day:		7.45	hours


Planet 8	*gas giant*
   Distance from primary:	6.439	AU
   Mass:			1348.799	Earth masses
   Equatorial radius:		99457.2	km
   Density:			1.956	grams/cc
   Eccentricity of orbit:	0.145
   Escape Velocity:		104.00	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5437.69	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.537
   Length of year:		5700.70	days
   Length of day:		5.54	hours


Planet 9	*gas giant*
   Distance from primary:	16.468	AU
   Mass:			13.673	Earth masses
   Equatorial radius:		28184.5	km
   Density:			0.871	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		19.67	km/sec
   Molecular weight retained:	2.05 and above
   Surface acceleration:	686.41	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.483
   Length of year:		23355.89	days
   Length of day:		15.60	hours


Planet 10	*gas giant*
   Distance from primary:	22.733	AU
   Mass:			28.790	Earth masses
   Equatorial radius:		35974.8	km
   Density:			0.882	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		25.26	km/sec
   Molecular weight retained:	1.24 and above
   Surface acceleration:	887.13	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.469
   Length of year:		37882.25	days
   Length of day:		13.72	hours


Planet 11	*gas giant*
   Distance from primary:	37.883	AU
   Mass:			2.575	Earth masses
   Equatorial radius:		18564.3	km
   Density:			0.574	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		10.52	km/sec
   Molecular weight retained:	7.18 and above
   Surface acceleration:	297.96	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.544
   Length of year:		81493.02	days
   Length of day:		23.68	hours


Planet 12	
   Distance from primary:	48.686	AU
   Mass:			0.086	Earth masses
   Equatorial radius:		3822.4	km
   Density:			2.208	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.14	degrees Celcius
   Normal daytime temperature:	-224.36	degrees Celcius
   Normal night temperature:	-235.81	degrees Celcius
   Maximum temperature:   	-210.06	degrees Celcius
   Minimum temperature:   	-250.24	degrees Celcius
   Escape Velocity:		4.25	km/sec
   Molecular weight retained:	44.02 and above
   Surface acceleration:	235.91	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.140
   Length of year:		118732.40	days
   Length of day:		31.20	hours
   Boiling point of water:	-65.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


