                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048148
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6098 K
Stellar class: F9
Age: 4.994 billion years  (2.022 billion left on main sequence)
Habitable ecosphere radius: 1.250 AU

Planets present at:
1	  0.356 AU	no atmosphere
2	  0.618 AU	greenhouse
3	  1.173 AU	no atmosphere
4	  1.362 AU	gas giant
5	  2.222 AU	gas giant
6	  5.021 AU	gas giant
7	  7.867 AU	gas giant
8	 13.316 AU	no atmosphere
9	 20.627 AU	gas giant
10	 27.844 AU	no atmosphere
11	 48.993 AU	gas giant



Planet 1	
   Distance from primary:	0.356	AU
   Mass:			0.108	Earth masses
   Equatorial radius:		3076.6	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.30	degrees Celcius
   Normal daytime temperature:	455.42	degrees Celcius
   Normal night temperature:	-183.93	degrees Celcius
   Maximum temperature:   	458.51	degrees Celcius
   Minimum temperature:   	-194.40	degrees Celcius
   Escape Velocity:		5.29	km/sec
   Molecular weight retained:	28.37 and above
   Surface acceleration:	454.68	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.065
   Length of year:		74.24	days
   Length of day:		1781.80	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.618	AU
   Mass:			1.027	Earth masses
   Equatorial radius:		6460.4	km
   Density:			5.437	grams/cc
   Eccentricity of orbit:	0.148
   Surface gravity:		1.00	Earth gees
   Surface pressure:		109.585	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		597.43	degrees Celcius
   Maximum temperature:   	609.13	degrees Celcius
   Minimum temperature:   	541.65	degrees Celcius
   Escape Velocity:		11.26	km/sec
   Molecular weight retained:	6.26 and above
   Surface acceleration:	981.57	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.444
   Length of year:		169.29	days
   Length of day:		3018.40	hours
   Boiling point of water:	298.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1181
				Cesium       melts at 28    boils at 1224
				Gallium      melts at 30    boils at 3824
				Rubidium     melts at 39    boils at 1198
				Potassium    melts at 63    boils at 1317
				Sodium       melts at 98    boils at 1495
				Indium       melts at 157   boils at 3330
				Lithium      melts at 181   boils at 2207
				Selenium     melts at 217   boils at 1194
				Tin          melts at 232   boils at 4161
				Polonium     melts at 254   boils at 1618
				Bismuth      melts at 271   boils at 2539
				Thallium     melts at 304   boils at 2376
				Cadmium      melts at 321   boils at 1316
				Lead         melts at 328   boils at 2826
				Zinc         melts at 420   boils at 1534
				Tellurium    melts at 450   boils at 1661
   gasses in atmosphere:
				Sulfur           25.0%  PP 27390.7 mb
				Nitrogen         74.3%  PP 81381.5 mb
				Phosphorus        0.5%  PP  541.6 mb
				CarbonDioxide     0.1%  PP   62.7 mb
				Ethanol           0.1%  PP   64.0 mb


Planet 3	
   Distance from primary:	1.173	AU
   Mass:			0.022	Earth masses
   Equatorial radius:		1814.0	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		10.19	degrees Celcius
   Normal daytime temperature:	86.02	degrees Celcius
   Normal night temperature:	-68.85	degrees Celcius
   Maximum temperature:   	112.10	degrees Celcius
   Minimum temperature:   	-96.52	degrees Celcius
   Escape Velocity:		3.11	km/sec
   Molecular weight retained:	82.04 and above
   Surface acceleration:	266.70	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.062
   Length of year:		443.24	days
   Length of day:		77.44	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 4	*gas giant*
   Distance from primary:	1.362	AU
   Mass:			5.087	Earth masses
   Equatorial radius:		17148.8	km
   Density:			1.439	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		15.38	km/sec
   Molecular weight retained:	3.36 and above
   Surface acceleration:	689.80	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.473
   Length of year:		554.73	days
   Length of day:		15.59	hours


Planet 5	*gas giant*
   Distance from primary:	2.222	AU
   Mass:			61.717	Earth masses
   Equatorial radius:		36989.9	km
   Density:			1.740	grams/cc
   Eccentricity of orbit:	0.156
   Escape Velocity:		36.48	km/sec
   Molecular weight retained:	0.60 and above
   Surface acceleration:	1798.79	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.545
   Length of year:		1154.94	days
   Length of day:		9.64	hours


Planet 6	*gas giant*
   Distance from primary:	5.021	AU
   Mass:			12.900	Earth masses
   Equatorial radius:		25079.3	km
   Density:			1.167	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		20.25	km/sec
   Molecular weight retained:	1.94 and above
   Surface acceleration:	817.88	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.525
   Length of year:		3925.13	days
   Length of day:		14.29	hours


Planet 7	*gas giant*
   Distance from primary:	7.867	AU
   Mass:			1057.983	Earth masses
   Equatorial radius:		94142.1	km
   Density:			1.809	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		94.67	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4760.48	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.456
   Length of year:		7686.07	days
   Length of day:		5.92	hours


Planet 8	
   Distance from primary:	13.316	AU
   Mass:			0.139	Earth masses
   Equatorial radius:		4473.8	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.016	Earth atmospheres
   Surface temperature:		-194.02	degrees Celcius
   Normal daytime temperature:	-185.41	degrees Celcius
   Normal night temperature:	-202.76	degrees Celcius
   Maximum temperature:   	-166.85	degrees Celcius
   Minimum temperature:   	-222.49	degrees Celcius
   Escape Velocity:		4.98	km/sec
   Molecular weight retained:	32.01 and above
   Surface acceleration:	277.17	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.281
   Length of year:		16949.49	days
   Length of day:		28.79	hours
   Boiling point of water:	12.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.24


Planet 9	*gas giant*
   Distance from primary:	20.627	AU
   Mass:			201.505	Earth masses
   Equatorial radius:		62894.6	km
   Density:			1.156	grams/cc
   Eccentricity of orbit:	0.091
   Escape Velocity:		50.55	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2031.42	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.511
   Length of year:		32670.32	days
   Length of day:		9.07	hours


Planet 10	
   Distance from primary:	27.844	AU
   Mass:			0.274	Earth masses
   Equatorial radius:		5595.2	km
   Density:			2.235	grams/cc
   Eccentricity of orbit:	0.220
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-215.83	degrees Celcius
   Normal daytime temperature:	-209.34	degrees Celcius
   Normal night temperature:	-222.26	degrees Celcius
   Maximum temperature:   	-189.97	degrees Celcius
   Minimum temperature:   	-242.22	degrees Celcius
   Escape Velocity:		6.25	km/sec
   Molecular weight retained:	20.30 and above
   Surface acceleration:	349.44	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.148
   Length of year:		51251.78	days
   Length of day:		25.64	hours
   Boiling point of water:	-44.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 11	*gas giant*
   Distance from primary:	48.993	AU
   Mass:			0.226	Earth masses
   Equatorial radius:		9323.0	km
   Density:			0.398	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		4.40	km/sec
   Molecular weight retained:	41.03 and above
   Surface acceleration:	103.77	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.510
   Length of year:		119625.94	days
   Length of day:		40.12	hours


