                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048150
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6084 K
Stellar class: F9
Age: 1.758 billion years  (5.257 billion left on main sequence)
Habitable ecosphere radius: 1.250 AU

Planets present at:
1	  0.394 AU	no atmosphere
2	  0.460 AU	no atmosphere
3	  0.716 AU	greenhouse
4	  1.030 AU	no atmosphere
5	  1.361 AU	
6	  1.999 AU	gas giant
7	  3.797 AU	gas giant
8	  6.009 AU	high pressure
9	 12.828 AU	gas giant
10	 16.766 AU	gas giant
11	 22.924 AU	gas giant
12	 36.645 AU	gas giant
13	 49.503 AU	no atmosphere



Planet 1	
   Distance from primary:	0.394	AU
   Mass:			0.207	Earth masses
   Equatorial radius:		3818.5	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		212.95	degrees Celcius
   Maximum temperature:   	425.31	degrees Celcius
   Minimum temperature:   	-201.50	degrees Celcius
   Escape Velocity:		6.58	km/sec
   Molecular weight retained:	18.34 and above
   Surface acceleration:	566.78	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.084
   Length of year:		86.18	days
   Length of day:		2068.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.460	AU
   Mass:			1/1739	Earth masses
   Equatorial radius:		538.7	km
   Density:			5.247	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.08	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		178.81	degrees Celcius
   Maximum temperature:   	383.69	degrees Celcius
   Minimum temperature:   	-210.19	degrees Celcius
   Escape Velocity:		0.92	km/sec
   Molecular weight retained:	932.52 and above
   Surface acceleration:	79.01	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.066
   Length of year:		108.81	days
   Length of day:		2611.34	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.716	AU
   Mass:			1.052	Earth masses
   Equatorial radius:		6510.6	km
   Density:			5.440	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		1.01	Earth gees
   Surface pressure:		100.968	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		478.49	degrees Celcius
   Maximum temperature:   	482.72	degrees Celcius
   Minimum temperature:   	471.85	degrees Celcius
   Escape Velocity:		11.35	km/sec
   Molecular weight retained:	6.16 and above
   Surface acceleration:	989.77	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.564
   Length of year:		211.28	days
   Length of day:		18.37	hours
   Boiling point of water:	292.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1168
				Cesium       melts at 28    boils at 1211
				Gallium      melts at 30    boils at 3786
				Rubidium     melts at 39    boils at 1185
				Potassium    melts at 63    boils at 1303
				Sodium       melts at 98    boils at 1478
				Indium       melts at 157   boils at 3296
				Lithium      melts at 181   boils at 2184
				Selenium     melts at 217   boils at 1180
				Tin          melts at 232   boils at 4120
				Polonium     melts at 254   boils at 1600
				Bismuth      melts at 271   boils at 2514
				Thallium     melts at 304   boils at 2351
				Cadmium      melts at 321   boils at 1302
				Lead         melts at 328   boils at 2797
				Zinc         melts at 420   boils at 1517
				Tellurium    melts at 450   boils at 1643
   gasses in atmosphere:
				Sulfur           20.7%  PP 20921.2 mb
				Nitrogen         78.6%  PP 79407.7 mb
				Phosphorus        0.4%  PP  417.2 mb


Planet 4	
   Distance from primary:	1.030	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		2691.4	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		29.55	degrees Celcius
   Normal daytime temperature:	67.74	degrees Celcius
   Normal night temperature:	-9.04	degrees Celcius
   Maximum temperature:   	98.46	degrees Celcius
   Minimum temperature:   	-40.32	degrees Celcius
   Escape Velocity:		4.62	km/sec
   Molecular weight retained:	37.15 and above
   Surface acceleration:	397.01	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.058
   Length of year:		364.74	days
   Length of day:		29.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374


Planet 5	
   Distance from primary:	1.361	AU
   Mass:			0.722	Earth masses
   Equatorial radius:		5757.3	km
   Density:			5.396	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.89	Earth gees
   Surface pressure:		0.506	Earth atmospheres
   Surface temperature:		9.56	degrees Celcius
   Normal daytime temperature:	15.78	degrees Celcius
   Normal night temperature:	2.98	degrees Celcius
   Maximum temperature:   	38.41	degrees Celcius
   Minimum temperature:   	-20.92	degrees Celcius
   Escape Velocity:		10.00	km/sec
   Molecular weight retained:	7.94 and above
   Surface acceleration:	868.25	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.218
   Length of year:		553.61	days
   Length of day:		16.35	hours
   Boiling point of water:	82.1	degrees Celcius
   Hydrosphere percentage:	61.13
   Cloud cover percentage:	27.62
   Ice cover percentage:	3.63
   liquids at surface:
				Ethanol      melts at -114  boils at 62
				Mercury      melts at -39   boils at 327
				Bromine      melts at -7    boils at 44
				Water        melts at 0     boils at 82
   gasses in atmosphere:
				Oxygen           41.3%  PP  208.9 mb
				Nitrogen         58.6%  PP  296.4 mb


Planet 6	*gas giant*
   Distance from primary:	1.999	AU
   Mass:			12.261	Earth masses
   Equatorial radius:		22884.8	km
   Density:			1.460	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		20.67	km/sec
   Molecular weight retained:	1.86 and above
   Surface acceleration:	933.61	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.480
   Length of year:		986.09	days
   Length of day:		13.38	hours


Planet 7	*gas giant*
   Distance from primary:	3.797	AU
   Mass:			487.803	Earth masses
   Equatorial radius:		70687.8	km
   Density:			1.971	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		74.19	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3893.09	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.531
   Length of year:		2578.84	days
   Length of day:		6.55	hours


Planet 8	
   Distance from primary:	6.009	AU
   Mass:			71.627	Earth masses
   Equatorial radius:		27666.1	km
   Density:			4.826	grams/cc
   Eccentricity of orbit:	0.097
   Surface gravity:		3.80	Earth gees
   Surface pressure:		3821.264	Earth atmospheres
   Surface temperature:		235.01	degrees Celcius
   Maximum temperature:   	236.61	degrees Celcius
   Minimum temperature:   	233.01	degrees Celcius
   Escape Velocity:		45.44	km/sec
   Molecular weight retained:	0.38 and above
   Surface acceleration:	3731.79	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.498
   Length of year:		5138.21	days
   Length of day:		7.85	hours
   Boiling point of water:	681.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 1339
				Francium     melts at 27    boils at 2158
				Cesium       melts at 28    boils at 2229
				Gallium      melts at 30    boils at 6574
				Rubidium     melts at 39    boils at 2186
				Phosphorus   melts at 44    boils at 1144
				Potassium    melts at 63    boils at 2385
				Sodium       melts at 98    boils at 2681
				Sulfur       melts at 113   boils at 1564
				Indium       melts at 157   boils at 5747
				Lithium      melts at 181   boils at 3872
				Selenium     melts at 217   boils at 2178
				Tin          melts at 232   boils at 7137
   gasses in atmosphere:
				Nitrogen          0.1%  PP 4769.7 mb
				Helium           99.9%  PP 3816487.7 mb


Planet 9	*gas giant*
   Distance from primary:	12.828	AU
   Mass:			34.369	Earth masses
   Equatorial radius:		36089.8	km
   Density:			1.043	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		27.56	km/sec
   Molecular weight retained:	1.05 and above
   Surface acceleration:	1052.30	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.520
   Length of year:		16025.61	days
   Length of day:		12.60	hours


Planet 10	*gas giant*
   Distance from primary:	16.766	AU
   Mass:			2.019	Earth masses
   Equatorial radius:		16144.9	km
   Density:			0.685	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		9.99	km/sec
   Molecular weight retained:	7.96 and above
   Surface acceleration:	308.92	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.495
   Length of year:		23946.69	days
   Length of day:		23.25	hours


Planet 11	*gas giant*
   Distance from primary:	22.924	AU
   Mass:			59.977	Earth masses
   Equatorial radius:		44558.1	km
   Density:			0.967	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		32.77	km/sec
   Molecular weight retained:	0.74 and above
   Surface acceleration:	1204.69	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.452
   Length of year:		38282.11	days
   Length of day:		11.78	hours


Planet 12	*gas giant*
   Distance from primary:	36.645	AU
   Mass:			1.110	Earth masses
   Equatorial radius:		14472.8	km
   Density:			0.523	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		7.82	km/sec
   Molecular weight retained:	12.98 and above
   Surface acceleration:	211.34	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.534
   Length of year:		77379.74	days
   Length of day:		28.11	hours


Planet 13	
   Distance from primary:	49.503	AU
   Mass:			0.043	Earth masses
   Equatorial radius:		3040.1	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.160
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.46	degrees Celcius
   Normal daytime temperature:	-224.12	degrees Celcius
   Normal night temperature:	-236.68	degrees Celcius
   Maximum temperature:   	-213.34	degrees Celcius
   Minimum temperature:   	-247.79	degrees Celcius
   Escape Velocity:		3.37	km/sec
   Molecular weight retained:	69.84 and above
   Surface acceleration:	186.92	cm/sec2
   Axial tilt:			70	degrees
   Planetary albedo:		0.151
   Length of year:		121494.65	days
   Length of day:		35.05	hours
   Boiling point of water:	-78.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


