                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d43
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6171 K
Stellar class: F8
Age: 5.352 billion years  (1.803 billion left on main sequence)
Habitable ecosphere radius: 1.235 AU

Planets present at:
1	  0.321 AU	no atmosphere
2	  0.435 AU	no atmosphere
3	  0.606 AU	no atmosphere
4	  1.206 AU	
5	  1.819 AU	gas giant
6	  4.478 AU	gas giant
7	  8.645 AU	gas giant
8	 13.497 AU	gas giant
9	 40.198 AU	no atmosphere
10	 27.723 AU	gas giant
11	 45.676 AU	gas giant



Planet 1	
   Distance from primary:	0.321	AU
   Mass:			0.038	Earth masses
   Equatorial radius:		2169.4	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		265.88	degrees Celcius
   Normal daytime temperature:	486.09	degrees Celcius
   Normal night temperature:	-175.09	degrees Celcius
   Maximum temperature:   	489.06	degrees Celcius
   Minimum temperature:   	-185.56	degrees Celcius
   Escape Velocity:		3.72	km/sec
   Molecular weight retained:	57.30 and above
   Surface acceleration:	319.32	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.057
   Length of year:		63.59	days
   Length of day:		1526.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.435	AU
   Mass:			0.115	Earth masses
   Equatorial radius:		3139.7	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		187.65	degrees Celcius
   Maximum temperature:   	394.56	degrees Celcius
   Minimum temperature:   	-208.06	degrees Celcius
   Escape Velocity:		5.40	km/sec
   Molecular weight retained:	27.24 and above
   Surface acceleration:	464.16	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.075
   Length of year:		100.33	days
   Length of day:		2407.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.606	AU
   Mass:			0.496	Earth masses
   Equatorial radius:		5092.3	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		117.98	degrees Celcius
   Maximum temperature:   	308.55	degrees Celcius
   Minimum temperature:   	-222.87	degrees Celcius
   Escape Velocity:		8.82	km/sec
   Molecular weight retained:	10.21 and above
   Surface acceleration:	763.22	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.069
   Length of year:		164.84	days
   Length of day:		3956.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.206	AU
   Mass:			0.495	Earth masses
   Equatorial radius:		5087.6	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.209	Earth atmospheres
   Surface temperature:		12.85	degrees Celcius
   Normal daytime temperature:	23.02	degrees Celcius
   Normal night temperature:	2.17	degrees Celcius
   Maximum temperature:   	50.17	degrees Celcius
   Minimum temperature:   	-26.34	degrees Celcius
   Escape Velocity:		8.81	km/sec
   Molecular weight retained:	10.23 and above
   Surface acceleration:	762.47	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.236
   Length of year:		463.26	days
   Length of day:		18.12	hours
   Boiling point of water:	61.4	degrees Celcius
   Hydrosphere percentage:	47.21
   Cloud cover percentage:	29.49
   Ice cover percentage:	2.14
   liquids at surface:
				Ethanol      melts at -114  boils at 42
				Mercury      melts at -39   boils at 292
				Bromine      melts at -7    boils at 25
				Water        melts at 0     boils at 61
   gasses in atmosphere:
				Oxygen           47.4%  PP   99.1 mb
				Nitrogen         52.4%  PP  109.7 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.819	AU
   Mass:			51.555	Earth masses
   Equatorial radius:		34554.3	km
   Density:			1.783	grams/cc
   Eccentricity of orbit:	0.204
   Escape Velocity:		34.50	km/sec
   Molecular weight retained:	0.67 and above
   Surface acceleration:	1721.89	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.508
   Length of year:		857.78	days
   Length of day:		9.85	hours


Planet 6	*gas giant*
   Distance from primary:	4.478	AU
   Mass:			701.899	Earth masses
   Equatorial radius:		79773.9	km
   Density:			1.973	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		83.77	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4398.38	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.452
   Length of year:		3310.74	days
   Length of day:		6.16	hours


Planet 7	*gas giant*
   Distance from primary:	8.645	AU
   Mass:			10.312	Earth masses
   Equatorial radius:		24607.3	km
   Density:			0.988	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		18.28	km/sec
   Molecular weight retained:	2.38 and above
   Surface acceleration:	679.13	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.506
   Length of year:		8889.90	days
   Length of day:		15.68	hours


Planet 8	*gas giant*
   Distance from primary:	13.497	AU
   Mass:			510.674	Earth masses
   Equatorial radius:		79708.3	km
   Density:			1.439	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		71.48	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3205.35	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.459
   Length of year:		17330.06	days
   Length of day:		7.22	hours


Planet 9	
   Distance from primary:	40.198	AU
   Mass:			0.188	Earth masses
   Equatorial radius:		4944.7	km
   Density:			2.224	grams/cc
   Eccentricity of orbit:	0.267
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.82	degrees Celcius
   Normal daytime temperature:	-220.15	degrees Celcius
   Normal night temperature:	-231.40	degrees Celcius
   Maximum temperature:   	-201.81	degrees Celcius
   Minimum temperature:   	-249.71	degrees Celcius
   Escape Velocity:		5.51	km/sec
   Molecular weight retained:	26.12 and above
   Surface acceleration:	307.31	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.152
   Length of year:		89135.52	days
   Length of day:		27.34	hours
   Boiling point of water:	-52.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 10	*gas giant*
   Distance from primary:	27.723	AU
   Mass:			6.010	Earth masses
   Equatorial radius:		23165.4	km
   Density:			0.690	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		14.38	km/sec
   Molecular weight retained:	3.84 and above
   Surface acceleration:	446.58	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.474
   Length of year:		51048.53	days
   Length of day:		19.34	hours


Planet 11	*gas giant*
   Distance from primary:	45.676	AU
   Mass:			0.670	Earth masses
   Equatorial radius:		12733.3	km
   Density:			0.463	grams/cc
   Eccentricity of orbit:	0.085
   Escape Velocity:		6.48	km/sec
   Molecular weight retained:	18.93 and above
   Surface acceleration:	164.69	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.535
   Length of year:		107960.06	days
   Length of day:		31.85	hours


