                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950480ce
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6108 K
Stellar class: F9
Age: 4.578 billion years  (2.454 billion left on main sequence)
Habitable ecosphere radius: 1.248 AU

Planets present at:
1	  0.328 AU	no atmosphere
2	  0.503 AU	no atmosphere
3	  0.725 AU	no atmosphere
4	  0.972 AU	greenhouse
5	  1.907 AU	cold
6	  3.044 AU	gas giant
7	  4.749 AU	gas giant
8	  5.610 AU	gas giant
9	 11.200 AU	gas giant
10	 19.760 AU	gas giant
11	 39.329 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.328	AU
   Mass:			0.117	Earth masses
   Equatorial radius:		3160.0	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.196
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		258.65	degrees Celcius
   Normal daytime temperature:	475.61	degrees Celcius
   Normal night temperature:	-161.61	degrees Celcius
   Maximum temperature:   	479.75	degrees Celcius
   Minimum temperature:   	-176.81	degrees Celcius
   Escape Velocity:		5.43	km/sec
   Molecular weight retained:	26.88 and above
   Surface acceleration:	467.21	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.088
   Length of year:		65.47	days
   Length of day:		1056.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.503	AU
   Mass:			0.191	Earth masses
   Equatorial radius:		3716.3	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		157.48	degrees Celcius
   Maximum temperature:   	357.46	degrees Celcius
   Minimum temperature:   	-214.80	degrees Celcius
   Escape Velocity:		6.40	km/sec
   Molecular weight retained:	19.37 and above
   Surface acceleration:	551.24	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.077
   Length of year:		124.47	days
   Length of day:		2987.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.725	AU
   Mass:			0.230	Earth masses
   Equatorial radius:		3953.8	km
   Density:			5.316	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		87.05	degrees Celcius
   Maximum temperature:   	269.76	degrees Celcius
   Minimum temperature:   	-226.72	degrees Celcius
   Escape Velocity:		6.82	km/sec
   Molecular weight retained:	17.09 and above
   Surface acceleration:	587.38	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.060
   Length of year:		215.62	days
   Length of day:		5174.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.972	AU
   Mass:			1.814	Earth masses
   Equatorial radius:		7766.1	km
   Density:			5.526	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		1.22	Earth gees
   Surface pressure:		316.105	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		549.95	degrees Celcius
   Maximum temperature:   	552.00	degrees Celcius
   Minimum temperature:   	544.94	degrees Celcius
   Escape Velocity:		13.65	km/sec
   Molecular weight retained:	4.26 and above
   Surface acceleration:	1199.36	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.438
   Length of year:		334.41	days
   Length of day:		14.49	hours
   Boiling point of water:	375.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1379
				Cesium       melts at 28    boils at 1428
				Gallium      melts at 30    boils at 4382
				Rubidium     melts at 39    boils at 1398
				Potassium    melts at 63    boils at 1534
				Sodium       melts at 98    boils at 1735
				Indium       melts at 157   boils at 3820
				Lithium      melts at 181   boils at 2545
				Selenium     melts at 217   boils at 1393
				Tin          melts at 232   boils at 4764
				Polonium     melts at 254   boils at 1875
				Bismuth      melts at 271   boils at 2922
				Thallium     melts at 304   boils at 2736
				Cadmium      melts at 321   boils at 1532
				Lead         melts at 328   boils at 3248
				Zinc         melts at 420   boils at 1779
				Tellurium    melts at 450   boils at 1924
   gasses in atmosphere:
				Sulfur           19.6%  PP 61823.9 mb
				Nitrogen         79.9%  PP 252479.9 mb
				Phosphorus        0.4%  PP 1233.5 mb


Planet 5	
   Distance from primary:	1.907	AU
   Mass:			1.313	Earth masses
   Equatorial radius:		6996.2	km
   Density:			5.471	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.373	Earth atmospheres
   Surface temperature:		-76.36	degrees Celcius
   Normal daytime temperature:	-73.91	degrees Celcius
   Normal night temperature:	-78.95	degrees Celcius
   Maximum temperature:   	-58.48	degrees Celcius
   Minimum temperature:   	-95.50	degrees Celcius
   Escape Velocity:		12.23	km/sec
   Molecular weight retained:	5.30 and above
   Surface acceleration:	1069.70	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.680
   Length of year:		918.90	days
   Length of day:		14.67	hours
   Boiling point of water:	109.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.08
   Ice cover percentage:	92.65
   liquids at surface:
				Ethanol      melts at -114  boils at 87
				Chlorine     melts at -101  boils at -28
				Ammonia      melts at -78   boils at -28
   gasses in atmosphere:
				Nitrogen         99.8%  PP 1371.3 mb
				CarbonDioxide     0.1%  PP    0.7 mb
				Ozone             0.1%  PP    0.7 mb


Planet 6	*gas giant*
   Distance from primary:	3.044	AU
   Mass:			34.411	Earth masses
   Equatorial radius:		32028.7	km
   Density:			1.494	grams/cc
   Eccentricity of orbit:	0.163
   Escape Velocity:		29.27	km/sec
   Molecular weight retained:	0.93 and above
   Surface acceleration:	1337.71	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.463
   Length of year:		1853.24	days
   Length of day:		11.17	hours


Planet 7	*gas giant*
   Distance from primary:	4.749	AU
   Mass:			1.395	Earth masses
   Equatorial radius:		13049.1	km
   Density:			0.896	grams/cc
   Eccentricity of orbit:	0.094
   Escape Velocity:		9.23	km/sec
   Molecular weight retained:	9.31 and above
   Surface acceleration:	326.66	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.544
   Length of year:		3611.05	days
   Length of day:		22.61	hours


Planet 8	*gas giant*
   Distance from primary:	5.610	AU
   Mass:			30.549	Earth masses
   Equatorial radius:		32552.3	km
   Density:			1.264	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		27.36	km/sec
   Molecular weight retained:	1.06 and above
   Surface acceleration:	1149.66	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.532
   Length of year:		4636.18	days
   Length of day:		12.05	hours


Planet 9	*gas giant*
   Distance from primary:	11.200	AU
   Mass:			957.349	Earth masses
   Equatorial radius:		94180.4	km
   Density:			1.635	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		90.04	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4304.16	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.463
   Length of year:		13062.33	days
   Length of day:		6.23	hours


Planet 10	*gas giant*
   Distance from primary:	19.760	AU
   Mass:			58.408	Earth masses
   Equatorial radius:		43676.8	km
   Density:			1.000	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		32.66	km/sec
   Molecular weight retained:	0.74 and above
   Surface acceleration:	1220.99	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.476
   Length of year:		30648.72	days
   Length of day:		11.70	hours


Planet 11	*gas giant*
   Distance from primary:	39.329	AU
   Mass:			1.787	Earth masses
   Equatorial radius:		16729.9	km
   Density:			0.545	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		9.23	km/sec
   Molecular weight retained:	9.32 and above
   Surface acceleration:	254.65	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.501
   Length of year:		86062.93	days
   Length of day:		25.61	hours


