                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048661
Stellar mass: 1.10 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6242 K
Stellar class: F8
Age: 1.048 billion years  (5.797 billion left on main sequence)
Habitable ecosphere radius: 1.270 AU

Planets present at:
1	  0.379 AU	no atmosphere
2	  0.543 AU	no atmosphere
3	  0.695 AU	greenhouse
4	  0.773 AU	no atmosphere
5	  1.329 AU	gas giant
6	  2.251 AU	gas giant
7	  4.281 AU	gas giant
8	  7.858 AU	gas giant
9	 11.095 AU	gas giant
10	 17.668 AU	gas giant
11	 23.999 AU	gas giant
12	 38.676 AU	gas giant
13	 50.798 AU	no atmosphere



Planet 1	
   Distance from primary:	0.379	AU
   Mass:			0.053	Earth masses
   Equatorial radius:		2437.0	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		226.73	degrees Celcius
   Maximum temperature:   	442.05	degrees Celcius
   Minimum temperature:   	-198.17	degrees Celcius
   Escape Velocity:		4.18	km/sec
   Molecular weight retained:	45.36 and above
   Surface acceleration:	359.08	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.078
   Length of year:		81.24	days
   Length of day:		1949.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.543	AU
   Mass:			0.189	Earth masses
   Equatorial radius:		3702.7	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.134
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		147.54	degrees Celcius
   Maximum temperature:   	345.14	degrees Celcius
   Minimum temperature:   	-214.91	degrees Celcius
   Escape Velocity:		6.38	km/sec
   Molecular weight retained:	19.52 and above
   Surface acceleration:	549.19	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.054
   Length of year:		139.02	days
   Length of day:		2550.36	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.695	AU
   Mass:			0.689	Earth masses
   Equatorial radius:		5670.2	km
   Density:			5.392	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.87	Earth gees
   Surface pressure:		34.593	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		264.78	degrees Celcius
   Maximum temperature:   	271.85	degrees Celcius
   Minimum temperature:   	256.78	degrees Celcius
   Escape Velocity:		9.84	km/sec
   Molecular weight retained:	8.19 and above
   Surface acceleration:	854.39	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.545
   Length of year:		201.32	days
   Length of day:		19.88	hours
   Boiling point of water:	232.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 580
				Francium     melts at 27    boils at 1014
				Cesium       melts at 28    boils at 1052
				Gallium      melts at 30    boils at 3351
				Rubidium     melts at 39    boils at 1029
				Phosphorus   melts at 44    boils at 477
				Potassium    melts at 63    boils at 1134
				Sodium       melts at 98    boils at 1291
				Sulfur       melts at 113   boils at 699
				Indium       melts at 157   boils at 2914
				Lithium      melts at 181   boils at 1921
				Selenium     melts at 217   boils at 1024
				Tin          melts at 232   boils at 3649
				Polonium     melts at 254   boils at 1400
   gasses in atmosphere:
				Nitrogen         99.7%  PP 34477.9 mb
				CarbonDioxide     0.1%  PP   23.7 mb
				Ozone             0.1%  PP   23.9 mb
				Ethanol           0.1%  PP   24.0 mb


Planet 4	
   Distance from primary:	0.773	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		2660.6	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		76.55	degrees Celcius
   Normal daytime temperature:	156.73	degrees Celcius
   Normal night temperature:	-7.73	degrees Celcius
   Maximum temperature:   	184.63	degrees Celcius
   Minimum temperature:   	-37.81	degrees Celcius
   Escape Velocity:		4.57	km/sec
   Molecular weight retained:	38.02 and above
   Surface acceleration:	392.40	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.084
   Length of year:		236.22	days
   Length of day:		63.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	*gas giant*
   Distance from primary:	1.329	AU
   Mass:			4.128	Earth masses
   Equatorial radius:		16081.1	km
   Density:			1.416	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		14.31	km/sec
   Molecular weight retained:	3.88 and above
   Surface acceleration:	636.61	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.545
   Length of year:		532.59	days
   Length of day:		16.21	hours


Planet 6	*gas giant*
   Distance from primary:	2.251	AU
   Mass:			6.999	Earth masses
   Equatorial radius:		19600.2	km
   Density:			1.326	grams/cc
   Eccentricity of orbit:	0.117
   Escape Velocity:		16.88	km/sec
   Molecular weight retained:	2.79 and above
   Surface acceleration:	726.52	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.490
   Length of year:		1174.31	days
   Length of day:		15.16	hours


Planet 7	*gas giant*
   Distance from primary:	4.281	AU
   Mass:			194.240	Earth masses
   Equatorial radius:		54511.3	km
   Density:			1.711	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		53.31	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2606.78	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.509
   Length of year:		3078.56	days
   Length of day:		8.01	hours


Planet 8	*gas giant*
   Distance from primary:	7.858	AU
   Mass:			7.979	Earth masses
   Equatorial radius:		22600.2	km
   Density:			0.986	grams/cc
   Eccentricity of orbit:	0.119
   Escape Velocity:		16.78	km/sec
   Molecular weight retained:	2.82 and above
   Surface acceleration:	622.98	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.480
   Length of year:		7659.64	days
   Length of day:		16.38	hours


Planet 9	*gas giant*
   Distance from primary:	11.095	AU
   Mass:			187.088	Earth masses
   Equatorial radius:		58371.6	km
   Density:			1.342	grams/cc
   Eccentricity of orbit:	0.114
   Escape Velocity:		50.56	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2189.69	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.517
   Length of year:		12845.89	days
   Length of day:		8.73	hours


Planet 10	*gas giant*
   Distance from primary:	17.668	AU
   Mass:			0.972	Earth masses
   Equatorial radius:		13083.0	km
   Density:			0.619	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		7.70	km/sec
   Molecular weight retained:	13.40 and above
   Surface acceleration:	226.36	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.507
   Length of year:		25822.38	days
   Length of day:		27.17	hours


Planet 11	*gas giant*
   Distance from primary:	23.999	AU
   Mass:			54.095	Earth masses
   Equatorial radius:		43346.0	km
   Density:			0.948	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		31.55	km/sec
   Molecular weight retained:	0.80 and above
   Surface acceleration:	1148.15	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.473
   Length of year:		40874.95	days
   Length of day:		12.06	hours


Planet 12	*gas giant*
   Distance from primary:	38.676	AU
   Mass:			1.836	Earth masses
   Equatorial radius:		16814.6	km
   Density:			0.551	grams/cc
   Eccentricity of orbit:	0.105
   Escape Velocity:		9.33	km/sec
   Molecular weight retained:	9.11 and above
   Surface acceleration:	258.98	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.451
   Length of year:		83630.24	days
   Length of day:		25.40	hours


Planet 13	
   Distance from primary:	50.798	AU
   Mass:			0.037	Earth masses
   Equatorial radius:		2895.6	km
   Density:			2.199	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.18	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.72	degrees Celcius
   Normal daytime temperature:	-224.28	degrees Celcius
   Normal night temperature:	-237.03	degrees Celcius
   Maximum temperature:   	-211.99	degrees Celcius
   Minimum temperature:   	-249.49	degrees Celcius
   Escape Velocity:		3.21	km/sec
   Molecular weight retained:	77.04 and above
   Surface acceleration:	177.93	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.154
   Length of year:		125885.18	days
   Length of day:		35.93	hours
   Boiling point of water:	-79.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


