                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048569
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6122 K
Stellar class: F9
Age: 3.171 billion years  (3.706 billion left on main sequence)
Habitable ecosphere radius: 1.266 AU

Planets present at:
1	  0.333 AU	no atmosphere
2	  0.634 AU	greenhouse
3	  1.033 AU	greenhouse
4	  1.644 AU	no atmosphere
5	  2.245 AU	cold
6	  3.969 AU	gas giant
7	 14.810 AU	gas giant
8	 34.878 AU	gas giant



Planet 1	
   Distance from primary:	0.333	AU
   Mass:			0.124	Earth masses
   Equatorial radius:		3222.6	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		260.44	degrees Celcius
   Normal daytime temperature:	479.65	degrees Celcius
   Normal night temperature:	-177.62	degrees Celcius
   Maximum temperature:   	482.74	degrees Celcius
   Minimum temperature:   	-188.50	degrees Celcius
   Escape Velocity:		5.54	km/sec
   Molecular weight retained:	25.84 and above
   Surface acceleration:	476.63	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.072
   Length of year:		66.86	days
   Length of day:		1604.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.634	AU
   Mass:			0.611	Earth masses
   Equatorial radius:		5451.7	km
   Density:			5.380	grams/cc
   Eccentricity of orbit:	0.165
   Surface gravity:		0.84	Earth gees
   Surface pressure:		40.225	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		319.46	degrees Celcius
   Maximum temperature:   	337.29	degrees Celcius
   Minimum temperature:   	258.22	degrees Celcius
   Escape Velocity:		9.45	km/sec
   Molecular weight retained:	8.88 and above
   Surface acceleration:	819.74	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.474
   Length of year:		175.62	days
   Length of day:		3021.50	hours
   Boiling point of water:	240.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 593
				Francium     melts at 27    boils at 1033
				Cesium       melts at 28    boils at 1072
				Gallium      melts at 30    boils at 3407
				Rubidium     melts at 39    boils at 1048
				Potassium    melts at 63    boils at 1155
				Sodium       melts at 98    boils at 1315
				Sulfur       melts at 113   boils at 714
				Indium       melts at 157   boils at 2963
				Lithium      melts at 181   boils at 1955
				Selenium     melts at 217   boils at 1044
				Tin          melts at 232   boils at 3710
				Polonium     melts at 254   boils at 1425
				Bismuth      melts at 271   boils at 2253
				Astatine     melts at 302   boils at 566
				Thallium     melts at 304   boils at 2106
   gasses in atmosphere:
				Nitrogen         98.8%  PP 39729.4 mb
				Phosphorus        0.8%  PP  325.9 mb
				CarbonDioxide     0.1%  PP   38.1 mb
				Ozone             0.1%  PP   37.1 mb
				Ethanol           0.1%  PP   38.9 mb


Planet 3	
   Distance from primary:	1.033	AU
   Mass:			1.760	Earth masses
   Equatorial radius:		7690.8	km
   Density:			5.520	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		1.21	Earth gees
   Surface pressure:		251.232	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		444.83	degrees Celcius
   Maximum temperature:   	447.55	degrees Celcius
   Minimum temperature:   	440.25	degrees Celcius
   Escape Velocity:		13.51	km/sec
   Molecular weight retained:	4.35 and above
   Surface acceleration:	1186.51	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.585
   Length of year:		365.08	days
   Length of day:		14.24	hours
   Boiling point of water:	357.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1332
				Cesium       melts at 28    boils at 1379
				Gallium      melts at 30    boils at 4248
				Rubidium     melts at 39    boils at 1351
				Potassium    melts at 63    boils at 1482
				Sodium       melts at 98    boils at 1678
				Indium       melts at 157   boils at 3702
				Lithium      melts at 181   boils at 2464
				Selenium     melts at 217   boils at 1345
				Tin          melts at 232   boils at 4620
				Polonium     melts at 254   boils at 1814
				Bismuth      melts at 271   boils at 2831
				Thallium     melts at 304   boils at 2650
				Cadmium      melts at 321   boils at 1481
				Lead         melts at 328   boils at 3147
				Zinc         melts at 420   boils at 1721
   gasses in atmosphere:
				Sulfur           18.7%  PP 47061.3 mb
				Nitrogen         80.7%  PP 202763.2 mb
				Phosphorus        0.4%  PP  940.8 mb


Planet 4	
   Distance from primary:	1.644	AU
   Mass:			0.017	Earth masses
   Equatorial radius:		1669.7	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-32.66	degrees Celcius
   Normal daytime temperature:	0.95	degrees Celcius
   Normal night temperature:	-66.45	degrees Celcius
   Maximum temperature:   	27.86	degrees Celcius
   Minimum temperature:   	-93.61	degrees Celcius
   Escape Velocity:		2.86	km/sec
   Molecular weight retained:	96.88 and above
   Surface acceleration:	245.37	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.069
   Length of year:		733.08	days
   Length of day:		32.72	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	
   Distance from primary:	2.245	AU
   Mass:			1.405	Earth masses
   Equatorial radius:		7151.4	km
   Density:			5.481	grams/cc
   Eccentricity of orbit:	0.100
   Surface gravity:		1.12	Earth gees
   Surface pressure:		1.622	Earth atmospheres
   Surface temperature:		-93.18	degrees Celcius
   Normal daytime temperature:	-91.14	degrees Celcius
   Normal night temperature:	-95.34	degrees Celcius
   Maximum temperature:   	-74.91	degrees Celcius
   Minimum temperature:   	-112.81	degrees Celcius
   Escape Velocity:		12.52	km/sec
   Molecular weight retained:	5.07 and above
   Surface acceleration:	1095.54	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.706
   Length of year:		1170.02	days
   Length of day:		14.48	hours
   Boiling point of water:	113.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	97.84
   liquids at surface:
				Ethanol      melts at -114  boils at 92
				Chlorine     melts at -101  boils at -25
   gasses in atmosphere:
				Oxygen            0.1%  PP    2.0 mb
				Nitrogen         99.8%  PP 1618.3 mb


Planet 6	*gas giant*
   Distance from primary:	3.969	AU
   Mass:			1219.122	Earth masses
   Equatorial radius:		92582.2	km
   Density:			2.192	grams/cc
   Eccentricity of orbit:	0.175
   Escape Velocity:		102.48	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5671.94	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.491
   Length of year:		2746.99	days
   Length of day:		5.43	hours


Planet 7	*gas giant*
   Distance from primary:	14.810	AU
   Mass:			1142.192	Earth masses
   Equatorial radius:		101373.0	km
   Density:			1.564	grams/cc
   Eccentricity of orbit:	0.268
   Escape Velocity:		94.80	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4432.34	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.502
   Length of year:		19798.32	days
   Length of day:		6.14	hours


Planet 8	*gas giant*
   Distance from primary:	34.878	AU
   Mass:			10.692	Earth masses
   Equatorial radius:		27875.8	km
   Density:			0.704	grams/cc
   Eccentricity of orbit:	0.215
   Escape Velocity:		17.49	km/sec
   Molecular weight retained:	2.59 and above
   Surface acceleration:	548.73	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.549
   Length of year:		71661.65	days
   Length of day:		17.45	hours


