                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a60
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6418 K
Stellar class: F7
Age: 2.354 billion years  (4.361 billion left on main sequence)
Habitable ecosphere radius: 1.285 AU

Planets present at:
1	  0.319 AU	no atmosphere
2	  0.393 AU	no atmosphere
3	  0.422 AU	no atmosphere
4	  0.517 AU	no atmosphere
5	  0.630 AU	greenhouse
6	  0.797 AU	no atmosphere
7	  1.267 AU	no atmosphere
8	  1.414 AU	no atmosphere
9	  1.682 AU	no atmosphere
10	  1.856 AU	gas giant
11	  3.417 AU	gas giant
12	  7.236 AU	gas giant
13	 23.238 AU	gas giant
14	 43.120 AU	no atmosphere



Planet 1	
   Distance from primary:	0.319	AU
   Mass:			0.038	Earth masses
   Equatorial radius:		2175.5	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		276.46	degrees Celcius
   Normal daytime temperature:	498.89	degrees Celcius
   Normal night temperature:	-172.70	degrees Celcius
   Maximum temperature:   	501.92	degrees Celcius
   Minimum temperature:   	-183.59	degrees Celcius
   Escape Velocity:		3.73	km/sec
   Molecular weight retained:	56.97 and above
   Surface acceleration:	320.23	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.072
   Length of year:		62.43	days
   Length of day:		1498.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.393	AU
   Mass:			1/1063	Earth masses
   Equatorial radius:		634.9	km
   Density:			5.248	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.09	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		222.50	degrees Celcius
   Maximum temperature:   	436.84	degrees Celcius
   Minimum temperature:   	-199.38	degrees Celcius
   Escape Velocity:		1.09	km/sec
   Molecular weight retained:	671.48 and above
   Surface acceleration:	93.11	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.066
   Length of year:		85.50	days
   Length of day:		2052.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.422	AU
   Mass:			0.036	Earth masses
   Equatorial radius:		2135.3	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		205.57	degrees Celcius
   Maximum temperature:   	416.48	degrees Celcius
   Minimum temperature:   	-204.53	degrees Celcius
   Escape Velocity:		3.66	km/sec
   Molecular weight retained:	59.15 and above
   Surface acceleration:	314.26	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.062
   Length of year:		95.19	days
   Length of day:		2284.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 4	
   Distance from primary:	0.517	AU
   Mass:			0.068	Earth masses
   Equatorial radius:		2640.7	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		160.41	degrees Celcius
   Maximum temperature:   	361.29	degrees Celcius
   Minimum temperature:   	-215.36	degrees Celcius
   Escape Velocity:		4.54	km/sec
   Molecular weight retained:	38.59 and above
   Surface acceleration:	389.45	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.056
   Length of year:		128.76	days
   Length of day:		3090.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 5	
   Distance from primary:	0.630	AU
   Mass:			0.785	Earth masses
   Equatorial radius:		5918.7	km
   Density:			5.405	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		0.91	Earth gees
   Surface pressure:		66.095	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		446.84	degrees Celcius
   Maximum temperature:   	453.48	degrees Celcius
   Minimum temperature:   	437.06	degrees Celcius
   Escape Velocity:		10.29	km/sec
   Molecular weight retained:	7.50 and above
   Surface acceleration:	894.06	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.565
   Length of year:		173.41	days
   Length of day:		44.67	hours
   Boiling point of water:	267.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1103
				Cesium       melts at 28    boils at 1143
				Gallium      melts at 30    boils at 3602
				Rubidium     melts at 39    boils at 1119
				Potassium    melts at 63    boils at 1231
				Sodium       melts at 98    boils at 1399
				Indium       melts at 157   boils at 3135
				Lithium      melts at 181   boils at 2073
				Selenium     melts at 217   boils at 1114
				Tin          melts at 232   boils at 3921
				Polonium     melts at 254   boils at 1515
				Bismuth      melts at 271   boils at 2387
				Thallium     melts at 304   boils at 2232
				Cadmium      melts at 321   boils at 1230
				Lead         melts at 328   boils at 2658
				Zinc         melts at 420   boils at 1436
   gasses in atmosphere:
				Sulfur           24.2%  PP 15990.2 mb
				Nitrogen         75.1%  PP 49620.7 mb
				Phosphorus        0.5%  PP  317.4 mb
				CarbonDioxide     0.1%  PP   35.4 mb
				Ozone             0.1%  PP   33.7 mb
				Ethanol           0.1%  PP   35.9 mb


Planet 6	
   Distance from primary:	0.797	AU
   Mass:			0.248	Earth masses
   Equatorial radius:		4051.5	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		74.60	degrees Celcius
   Normal daytime temperature:	122.80	degrees Celcius
   Normal night temperature:	25.46	degrees Celcius
   Maximum temperature:   	152.70	degrees Celcius
   Minimum temperature:   	-5.13	degrees Celcius
   Escape Velocity:		6.99	km/sec
   Molecular weight retained:	16.27 and above
   Surface acceleration:	602.30	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.071
   Length of year:		246.69	days
   Length of day:		32.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 7	
   Distance from primary:	1.267	AU
   Mass:			1/397.8	Earth masses
   Equatorial radius:		880.8	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		1.18	degrees Celcius
   Maximum temperature:   	159.98	degrees Celcius
   Minimum temperature:   	-236.74	degrees Celcius
   Escape Velocity:		1.51	km/sec
   Molecular weight retained:	348.76 and above
   Surface acceleration:	129.21	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.090
   Length of year:		494.87	days
   Length of day:		11876.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 8	
   Distance from primary:	1.414	AU
   Mass:			0.324	Earth masses
   Equatorial radius:		4424.6	km
   Density:			5.334	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.094	Earth atmospheres
   Surface temperature:		-12.17	degrees Celcius
   Normal daytime temperature:	0.80	degrees Celcius
   Normal night temperature:	-25.64	degrees Celcius
   Maximum temperature:   	27.52	degrees Celcius
   Minimum temperature:   	-53.58	degrees Celcius
   Escape Velocity:		7.64	km/sec
   Molecular weight retained:	13.60 and above
   Surface acceleration:	659.54	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.290
   Length of year:		582.87	days
   Length of day:		18.86	hours
   Boiling point of water:	44.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	4.66
   Ice cover percentage:	22.56
   liquids at surface:
				Ethanol      melts at -114  boils at 27
				Mercury      melts at -39   boils at 264
   gasses in atmosphere:
				Oxygen           80.7%  PP   76.2 mb
				Nitrogen         18.9%  PP   17.8 mb
				CarbonDioxide     0.2%  PP    0.2 mb
				Ozone             0.2%  PP    0.2 mb


Planet 9	
   Distance from primary:	1.682	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		4010.1	km
   Density:			5.318	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.056	Earth atmospheres
   Surface temperature:		-54.68	degrees Celcius
   Normal daytime temperature:	-41.38	degrees Celcius
   Normal night temperature:	-68.36	degrees Celcius
   Maximum temperature:   	-15.68	degrees Celcius
   Minimum temperature:   	-95.25	degrees Celcius
   Escape Velocity:		6.91	km/sec
   Molecular weight retained:	16.61 and above
   Surface acceleration:	595.98	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.490
   Length of year:		756.26	days
   Length of day:		19.72	hours
   Boiling point of water:	34.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.24
   Ice cover percentage:	62.34
   liquids at surface:
				Ethanol      melts at -114  boils at 17
   gasses in atmosphere:
				CarbonDioxide    46.7%  PP   25.9 mb
				Ozone            49.4%  PP   27.4 mb
				Fluorine          0.3%  PP    0.1 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.4%  PP    0.2 mb
				Krypton           2.8%  PP    1.6 mb
				Xenon             0.3%  PP    0.2 mb


Planet 10	*gas giant*
   Distance from primary:	1.856	AU
   Mass:			13.167	Earth masses
   Equatorial radius:		23168.1	km
   Density:			1.511	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		21.29	km/sec
   Molecular weight retained:	1.75 and above
   Surface acceleration:	978.27	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.450
   Length of year:		876.85	days
   Length of day:		13.07	hours


Planet 11	*gas giant*
   Distance from primary:	3.417	AU
   Mass:			112.133	Earth masses
   Equatorial radius:		45530.6	km
   Density:			1.695	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		44.32	km/sec
   Molecular weight retained:	0.40 and above
   Surface acceleration:	2157.09	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.523
   Length of year:		2190.66	days
   Length of day:		8.80	hours


Planet 12	*gas giant*
   Distance from primary:	7.236	AU
   Mass:			1147.933	Earth masses
   Equatorial radius:		95519.3	km
   Density:			1.879	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		97.90	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5017.34	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.521
   Length of year:		6740.51	days
   Length of day:		5.77	hours


Planet 13	*gas giant*
   Distance from primary:	23.238	AU
   Mass:			266.140	Earth masses
   Equatorial radius:		68732.8	km
   Density:			1.170	grams/cc
   Eccentricity of orbit:	0.243
   Escape Velocity:		55.57	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2246.58	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.453
   Length of year:		38838.09	days
   Length of day:		8.62	hours


Planet 14	
   Distance from primary:	43.120	AU
   Mass:			0.387	Earth masses
   Equatorial radius:		6265.5	km
   Density:			2.247	grams/cc
   Eccentricity of orbit:	0.098
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.94	degrees Celcius
   Normal daytime temperature:	-220.89	degrees Celcius
   Normal night temperature:	-230.93	degrees Celcius
   Maximum temperature:   	-208.00	degrees Celcius
   Minimum temperature:   	-244.53	degrees Celcius
   Escape Velocity:		7.02	km/sec
   Molecular weight retained:	16.10 and above
   Surface acceleration:	393.54	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.146
   Length of year:		98204.11	days
   Length of day:		24.16	hours
   Boiling point of water:	-38.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.4 mb


