                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e8f
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6287 K
Stellar class: F8
Age: 2.884 billion years  (4.226 billion left on main sequence)
Habitable ecosphere radius: 1.240 AU

Planets present at:
1	  0.456 AU	no atmosphere
2	  0.732 AU	no atmosphere
3	  0.868 AU	no atmosphere
4	  1.113 AU	greenhouse
5	  1.357 AU	cold
6	  1.623 AU	high pressure
7	  1.904 AU	cold
8	  3.940 AU	gas giant
9	  9.215 AU	gas giant
10	 25.663 AU	gas giant
11	 38.786 AU	gas giant
12	 48.291 AU	no atmosphere



Planet 1	
   Distance from primary:	0.456	AU
   Mass:			0.289	Earth masses
   Equatorial radius:		4264.0	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		179.58	degrees Celcius
   Maximum temperature:   	384.67	degrees Celcius
   Minimum temperature:   	-210.09	degrees Celcius
   Escape Velocity:		7.36	km/sec
   Molecular weight retained:	14.66 and above
   Surface acceleration:	634.85	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.061
   Length of year:		107.50	days
   Length of day:		2580.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 2	
   Distance from primary:	0.732	AU
   Mass:			0.104	Earth masses
   Equatorial radius:		3036.0	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		81.70	degrees Celcius
   Maximum temperature:   	262.94	degrees Celcius
   Minimum temperature:   	-227.31	degrees Celcius
   Escape Velocity:		5.22	km/sec
   Molecular weight retained:	29.14 and above
   Surface acceleration:	448.59	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.087
   Length of year:		218.68	days
   Length of day:		5248.43	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	0.868	AU
   Mass:			0.025	Earth masses
   Equatorial radius:		1903.2	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		52.59	degrees Celcius
   Maximum temperature:   	226.17	degrees Celcius
   Minimum temperature:   	-230.74	degrees Celcius
   Escape Velocity:		3.26	km/sec
   Molecular weight retained:	74.51 and above
   Surface acceleration:	279.88	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.088
   Length of year:		282.46	days
   Length of day:		6779.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	1.113	AU
   Mass:			2.398	Earth masses
   Equatorial radius:		8493.8	km
   Density:			5.584	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		1.35	Earth gees
   Surface pressure:		536.420	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		497.49	degrees Celcius
   Maximum temperature:   	499.30	degrees Celcius
   Minimum temperature:   	493.37	degrees Celcius
   Escape Velocity:		15.01	km/sec
   Molecular weight retained:	3.53 and above
   Surface acceleration:	1325.62	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.600
   Length of year:		410.44	days
   Length of day:		13.30	hours
   Boiling point of water:	423.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1500
				Cesium       melts at 28    boils at 1552
				Gallium      melts at 30    boils at 4721
				Rubidium     melts at 39    boils at 1520
				Potassium    melts at 63    boils at 1665
				Sodium       melts at 98    boils at 1882
				Indium       melts at 157   boils at 4118
				Lithium      melts at 181   boils at 2750
				Selenium     melts at 217   boils at 1515
				Tin          melts at 232   boils at 5132
				Polonium     melts at 254   boils at 2032
				Bismuth      melts at 271   boils at 3155
				Thallium     melts at 304   boils at 2955
				Cadmium      melts at 321   boils at 1664
				Lead         melts at 328   boils at 3504
				Zinc         melts at 420   boils at 1929
				Tellurium    melts at 450   boils at 2084
   gasses in atmosphere:
				Sulfur            0.2%  PP 1022.2 mb
				Nitrogen          0.9%  PP 4774.2 mb
				Helium           98.9%  PP 530594.1 mb


Planet 5	
   Distance from primary:	1.357	AU
   Mass:			0.467	Earth masses
   Equatorial radius:		4990.2	km
   Density:			5.358	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.191	Earth atmospheres
   Surface temperature:		-3.97	degrees Celcius
   Normal daytime temperature:	5.78	degrees Celcius
   Normal night temperature:	-14.17	degrees Celcius
   Maximum temperature:   	29.85	degrees Celcius
   Minimum temperature:   	-39.48	degrees Celcius
   Escape Velocity:		8.64	km/sec
   Molecular weight retained:	10.64 and above
   Surface acceleration:	747.24	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.242
   Length of year:		552.09	days
   Length of day:		17.74	hours
   Boiling point of water:	59.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	8.93
   Ice cover percentage:	12.06
   liquids at surface:
				Ethanol      melts at -114  boils at 40
				Mercury      melts at -39   boils at 288
				Bromine      melts at -7    boils at 23
   gasses in atmosphere:
				Oxygen           33.2%  PP   63.5 mb
				Nitrogen         66.6%  PP  127.5 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 6	
   Distance from primary:	1.623	AU
   Mass:			1.805	Earth masses
   Equatorial radius:		7753.6	km
   Density:			5.525	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		1.22	Earth gees
   Surface pressure:		2.407	Earth atmospheres
   Surface temperature:		-3.85	degrees Celcius
   Normal daytime temperature:	-1.43	degrees Celcius
   Normal night temperature:	-6.41	degrees Celcius
   Maximum temperature:   	14.07	degrees Celcius
   Minimum temperature:   	-22.80	degrees Celcius
   Escape Velocity:		13.63	km/sec
   Molecular weight retained:	4.28 and above
   Surface acceleration:	1197.21	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.241
   Length of year:		722.24	days
   Length of day:		13.87	hours
   Boiling point of water:	125.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	12.72
   Ice cover percentage:	11.26
   liquids at surface:
				Ethanol      melts at -114  boils at 103
				Mercury      melts at -39   boils at 401
				Bromine      melts at -7    boils at 83
   gasses in atmosphere:
				Nitrogen         99.8%  PP 2402.4 mb


Planet 7	
   Distance from primary:	1.904	AU
   Mass:			0.442	Earth masses
   Equatorial radius:		4902.4	km
   Density:			5.354	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.153	Earth atmospheres
   Surface temperature:		-72.67	degrees Celcius
   Normal daytime temperature:	-64.75	degrees Celcius
   Normal night temperature:	-80.94	degrees Celcius
   Maximum temperature:   	-41.92	degrees Celcius
   Minimum temperature:   	-105.19	degrees Celcius
   Escape Velocity:		8.48	km/sec
   Molecular weight retained:	11.04 and above
   Surface acceleration:	733.55	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.533
   Length of year:		918.13	days
   Length of day:		17.72	hours
   Boiling point of water:	54.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	62.55
   liquids at surface:
				Ethanol      melts at -114  boils at 36
				Chlorine     melts at -101  boils at -63
				Ammonia      melts at -78   boils at -63
   gasses in atmosphere:
				Oxygen           37.1%  PP   56.9 mb
				Nitrogen         62.7%  PP   96.1 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 8	*gas giant*
   Distance from primary:	3.940	AU
   Mass:			113.297	Earth masses
   Equatorial radius:		46352.0	km
   Density:			1.623	grams/cc
   Eccentricity of orbit:	0.114
   Escape Velocity:		44.15	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	2102.91	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.548
   Length of year:		2732.49	days
   Length of day:		8.91	hours


Planet 9	*gas giant*
   Distance from primary:	9.215	AU
   Mass:			1902.496	Earth masses
   Equatorial radius:		113276.2	km
   Density:			1.868	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		115.74	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5912.70	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.487
   Length of year:		9748.86	days
   Length of day:		5.32	hours


Planet 10	*gas giant*
   Distance from primary:	25.663	AU
   Mass:			0.311	Earth masses
   Equatorial radius:		9699.3	km
   Density:			0.486	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		5.06	km/sec
   Molecular weight retained:	31.05 and above
   Surface acceleration:	131.77	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.487
   Length of year:		45430.12	days
   Length of day:		35.60	hours


Planet 11	*gas giant*
   Distance from primary:	38.786	AU
   Mass:			2.174	Earth masses
   Equatorial radius:		17702.5	km
   Density:			0.559	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		9.90	km/sec
   Molecular weight retained:	8.11 and above
   Surface acceleration:	276.61	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.452
   Length of year:		84409.54	days
   Length of day:		24.57	hours


Planet 12	
   Distance from primary:	48.291	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		2178.9	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		0.14	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.98	degrees Celcius
   Normal daytime temperature:	-222.59	degrees Celcius
   Normal night temperature:	-237.22	degrees Celcius
   Maximum temperature:   	-207.56	degrees Celcius
   Minimum temperature:   	-251.86	degrees Celcius
   Escape Velocity:		2.41	km/sec
   Molecular weight retained:	136.40 and above
   Surface acceleration:	133.55	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.140
   Length of year:		117268.53	days
   Length of day:		41.47	hours
   Boiling point of water:	-92.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


