                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504811e
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6256 K
Stellar class: F8
Age: 5.064 billion years  (1.957 billion left on main sequence)
Habitable ecosphere radius: 1.249 AU

Planets present at:
1	  0.349 AU	no atmosphere
2	  0.453 AU	no atmosphere
3	  0.797 AU	greenhouse
4	  1.294 AU	
5	  2.859 AU	gas giant
6	  4.529 AU	gas giant
7	  8.202 AU	high pressure
8	 12.828 AU	gas giant
9	 22.354 AU	no atmosphere
10	 34.191 AU	gas giant
11	 50.219 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.349	AU
   Mass:			0.032	Earth masses
   Equatorial radius:		2056.9	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		246.34	degrees Celcius
   Normal daytime temperature:	461.62	degrees Celcius
   Normal night temperature:	-172.64	degrees Celcius
   Maximum temperature:   	465.28	degrees Celcius
   Minimum temperature:   	-185.56	degrees Celcius
   Escape Velocity:		3.53	km/sec
   Molecular weight retained:	63.76 and above
   Surface acceleration:	302.65	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.058
   Length of year:		72.04	days
   Length of day:		1297.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.453	AU
   Mass:			0.219	Earth masses
   Equatorial radius:		3887.9	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		182.03	degrees Celcius
   Maximum temperature:   	387.63	degrees Celcius
   Minimum temperature:   	-209.43	degrees Celcius
   Escape Velocity:		6.70	km/sec
   Molecular weight retained:	17.68 and above
   Surface acceleration:	577.33	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.067
   Length of year:		106.40	days
   Length of day:		2553.49	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.797	AU
   Mass:			1.740	Earth masses
   Equatorial radius:		7663.1	km
   Density:			5.518	grams/cc
   Eccentricity of orbit:	0.157
   Surface gravity:		1.20	Earth gees
   Surface pressure:		276.189	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		578.10	degrees Celcius
   Maximum temperature:   	580.30	degrees Celcius
   Minimum temperature:   	572.49	degrees Celcius
   Escape Velocity:		13.46	km/sec
   Molecular weight retained:	4.38 and above
   Surface acceleration:	1181.79	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.528
   Length of year:		248.46	days
   Length of day:		16.79	hours
   Boiling point of water:	364.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1351
				Cesium       melts at 28    boils at 1399
				Gallium      melts at 30    boils at 4302
				Rubidium     melts at 39    boils at 1370
				Potassium    melts at 63    boils at 1503
				Sodium       melts at 98    boils at 1701
				Indium       melts at 157   boils at 3750
				Lithium      melts at 181   boils at 2497
				Selenium     melts at 217   boils at 1365
				Tin          melts at 232   boils at 4678
				Polonium     melts at 254   boils at 1838
				Bismuth      melts at 271   boils at 2868
				Thallium     melts at 304   boils at 2685
				Cadmium      melts at 321   boils at 1502
				Lead         melts at 328   boils at 3188
				Zinc         melts at 420   boils at 1744
				Tellurium    melts at 450   boils at 1886
   gasses in atmosphere:
				Sulfur           20.6%  PP 57026.6 mb
				Nitrogen         78.8%  PP 217504.2 mb
				Phosphorus        0.4%  PP 1135.2 mb


Planet 4	
   Distance from primary:	1.294	AU
   Mass:			1.390	Earth masses
   Equatorial radius:		7126.8	km
   Density:			5.480	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		1.11	Earth gees
   Surface pressure:		1.752	Earth atmospheres
   Surface temperature:		17.87	degrees Celcius
   Normal daytime temperature:	21.07	degrees Celcius
   Normal night temperature:	14.45	degrees Celcius
   Maximum temperature:   	37.75	degrees Celcius
   Minimum temperature:   	-3.14	degrees Celcius
   Escape Velocity:		12.47	km/sec
   Molecular weight retained:	5.10 and above
   Surface acceleration:	1091.42	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.321
   Length of year:		513.27	days
   Length of day:		14.67	hours
   Boiling point of water:	116.1	degrees Celcius
   Hydrosphere percentage:	71.71
   Cloud cover percentage:	59.95
   Ice cover percentage:	1.26
   liquids at surface:
				Ethanol      melts at -114  boils at 94
				Mercury      melts at -39   boils at 384
				Bromine      melts at -7    boils at 74
				Water        melts at 0     boils at 116
   gasses in atmosphere:
				Oxygen            6.7%  PP  116.6 mb
				Nitrogen         93.2%  PP 1632.1 mb
				CarbonDioxide     0.1%  PP    0.9 mb
				Ozone             0.1%  PP    0.9 mb


Planet 5	*gas giant*
   Distance from primary:	2.859	AU
   Mass:			414.181	Earth masses
   Equatorial radius:		65822.5	km
   Density:			2.072	grams/cc
   Eccentricity of orbit:	0.125
   Escape Velocity:		70.84	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3812.25	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.476
   Length of year:		1685.37	days
   Length of day:		6.62	hours


Planet 6	*gas giant*
   Distance from primary:	4.529	AU
   Mass:			3.915	Earth masses
   Equatorial radius:		17561.7	km
   Density:			1.031	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		13.33	km/sec
   Molecular weight retained:	4.46 and above
   Surface acceleration:	506.25	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.471
   Length of year:		3362.57	days
   Length of day:		18.17	hours


Planet 7	
   Distance from primary:	8.202	AU
   Mass:			8.576	Earth masses
   Equatorial radius:		16542.3	km
   Density:			2.703	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		1.27	Earth gees
   Surface pressure:		51.765	Earth atmospheres
   Surface temperature:		-92.99	degrees Celcius
   Maximum temperature:   	-88.69	degrees Celcius
   Minimum temperature:   	-97.47	degrees Celcius
   Escape Velocity:		20.33	km/sec
   Molecular weight retained:	1.92 and above
   Surface acceleration:	1249.82	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.652
   Length of year:		8194.81	days
   Length of day:		13.56	hours
   Boiling point of water:	253.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	95.62
   liquids at surface:
				Ethanol      melts at -114  boils at 223
				Chlorine     melts at -101  boils at 64
   gasses in atmosphere:
				Nitrogen          0.2%  PP  103.0 mb
				Helium           99.8%  PP 51661.4 mb


Planet 8	*gas giant*
   Distance from primary:	12.828	AU
   Mass:			182.858	Earth masses
   Equatorial radius:		58767.9	km
   Density:			1.286	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		49.82	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2111.41	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.540
   Length of year:		16024.17	days
   Length of day:		8.89	hours


Planet 9	
   Distance from primary:	22.354	AU
   Mass:			0.322	Earth masses
   Equatorial radius:		5895.2	km
   Density:			2.240	grams/cc
   Eccentricity of orbit:	0.109
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-208.71	degrees Celcius
   Normal daytime temperature:	-201.60	degrees Celcius
   Normal night temperature:	-215.79	degrees Celcius
   Maximum temperature:   	-185.44	degrees Celcius
   Minimum temperature:   	-232.96	degrees Celcius
   Escape Velocity:		6.60	km/sec
   Molecular weight retained:	18.24 and above
   Surface acceleration:	369.08	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.147
   Length of year:		36872.39	days
   Length of day:		24.95	hours
   Boiling point of water:	-43.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 10	*gas giant*
   Distance from primary:	34.191	AU
   Mass:			29.021	Earth masses
   Equatorial radius:		37278.8	km
   Density:			0.799	grams/cc
   Eccentricity of orbit:	0.245
   Escape Velocity:		24.92	km/sec
   Molecular weight retained:	1.28 and above
   Surface acceleration:	832.77	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.525
   Length of year:		69745.16	days
   Length of day:		14.16	hours


Planet 11	
   Distance from primary:	50.219	AU
   Mass:			0.113	Earth masses
   Equatorial radius:		4172.2	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.161
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.82	degrees Celcius
   Normal daytime temperature:	-225.34	degrees Celcius
   Normal night temperature:	-236.18	degrees Celcius
   Maximum temperature:   	-213.26	degrees Celcius
   Minimum temperature:   	-248.65	degrees Celcius
   Escape Velocity:		4.64	km/sec
   Molecular weight retained:	36.87 and above
   Surface acceleration:	258.01	cm/sec2
   Axial tilt:			65	degrees
   Planetary albedo:		0.156
   Length of year:		124155.99	days
   Length of day:		29.84	hours
   Boiling point of water:	-62.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


