                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047daf
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6113 K
Stellar class: F9
Age: 5.755 billion years  (1.385 billion left on main sequence)
Habitable ecosphere radius: 1.236 AU

Planets present at:
1	  0.400 AU	no atmosphere
2	  0.705 AU	greenhouse
3	  1.366 AU	gas giant
4	  1.746 AU	cold
5	  4.657 AU	gas giant
6	 10.767 AU	gas giant
7	 17.290 AU	gas giant
8	 25.073 AU	gas giant
9	 31.964 AU	gas giant
10	 44.250 AU	no atmosphere
11	 51.345 AU	no atmosphere



Planet 1	
   Distance from primary:	0.400	AU
   Mass:			0.164	Earth masses
   Equatorial radius:		3536.2	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		210.59	degrees Celcius
   Maximum temperature:   	422.50	degrees Celcius
   Minimum temperature:   	-202.42	degrees Celcius
   Escape Velocity:		6.09	km/sec
   Molecular weight retained:	21.42 and above
   Surface acceleration:	523.96	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.053
   Length of year:		88.41	days
   Length of day:		2121.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.705	AU
   Mass:			0.748	Earth masses
   Equatorial radius:		5825.7	km
   Density:			5.400	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.90	Earth gees
   Surface pressure:		43.817	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		275.76	degrees Celcius
   Maximum temperature:   	285.11	degrees Celcius
   Minimum temperature:   	263.64	degrees Celcius
   Escape Velocity:		10.12	km/sec
   Molecular weight retained:	7.75 and above
   Surface acceleration:	879.17	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.517
   Length of year:		206.98	days
   Length of day:		82.38	hours
   Boiling point of water:	244.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 601
				Francium     melts at 27    boils at 1045
				Cesium       melts at 28    boils at 1084
				Gallium      melts at 30    boils at 3439
				Rubidium     melts at 39    boils at 1060
				Phosphorus   melts at 44    boils at 495
				Potassium    melts at 63    boils at 1168
				Sodium       melts at 98    boils at 1329
				Sulfur       melts at 113   boils at 723
				Indium       melts at 157   boils at 2991
				Lithium      melts at 181   boils at 1974
				Selenium     melts at 217   boils at 1056
				Tin          melts at 232   boils at 3744
				Polonium     melts at 254   boils at 1440
				Bismuth      melts at 271   boils at 2275
   gasses in atmosphere:
				Nitrogen         99.6%  PP 43635.2 mb
				CarbonDioxide     0.1%  PP   42.2 mb
				Ozone             0.1%  PP   38.9 mb
				Ethanol           0.1%  PP   43.3 mb


Planet 3	*gas giant*
   Distance from primary:	1.366	AU
   Mass:			10.319	Earth masses
   Equatorial radius:		21102.0	km
   Density:			1.567	grams/cc
   Eccentricity of orbit:	0.145
   Escape Velocity:		19.75	km/sec
   Molecular weight retained:	2.04 and above
   Surface acceleration:	924.16	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.450
   Length of year:		558.02	days
   Length of day:		13.46	hours


Planet 4	
   Distance from primary:	1.746	AU
   Mass:			1.152	Earth masses
   Equatorial radius:		6705.4	km
   Density:			5.452	grams/cc
   Eccentricity of orbit:	0.158
   Surface gravity:		1.04	Earth gees
   Surface pressure:		0.979	Earth atmospheres
   Surface temperature:		-60.90	degrees Celcius
   Normal daytime temperature:	-57.72	degrees Celcius
   Normal night temperature:	-64.26	degrees Celcius
   Maximum temperature:   	-38.14	degrees Celcius
   Minimum temperature:   	-85.20	degrees Celcius
   Escape Velocity:		11.71	km/sec
   Molecular weight retained:	5.79 and above
   Surface acceleration:	1021.67	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.613
   Length of year:		806.79	days
   Length of day:		15.03	hours
   Boiling point of water:	99.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.18
   Ice cover percentage:	81.96
   liquids at surface:
				Ethanol      melts at -114  boils at 78
				Chlorine     melts at -101  boils at -34
				Ammonia      melts at -78   boils at -34
   gasses in atmosphere:
				Nitrogen         99.8%  PP  977.5 mb
				CarbonDioxide     0.1%  PP    0.6 mb
				Ozone             0.1%  PP    0.6 mb


Planet 5	*gas giant*
   Distance from primary:	4.657	AU
   Mass:			379.791	Earth masses
   Equatorial radius:		66901.2	km
   Density:			1.810	grams/cc
   Eccentricity of orbit:	0.216
   Escape Velocity:		67.29	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3383.90	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.518
   Length of year:		3511.49	days
   Length of day:		7.03	hours


Planet 6	*gas giant*
   Distance from primary:	10.767	AU
   Mass:			193.789	Earth masses
   Equatorial radius:		58957.6	km
   Density:			1.349	grams/cc
   Eccentricity of orbit:	0.165
   Escape Velocity:		51.20	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2223.25	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.463
   Length of year:		12349.52	days
   Length of day:		8.67	hours


Planet 7	*gas giant*
   Distance from primary:	17.290	AU
   Mass:			19.571	Earth masses
   Equatorial radius:		31424.1	km
   Density:			0.900	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		22.29	km/sec
   Molecular weight retained:	1.60 and above
   Surface acceleration:	790.35	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.480
   Length of year:		25136.52	days
   Length of day:		14.54	hours


Planet 8	*gas giant*
   Distance from primary:	25.073	AU
   Mass:			38.099	Earth masses
   Equatorial radius:		39363.7	km
   Density:			0.891	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		27.78	km/sec
   Molecular weight retained:	1.03 and above
   Surface acceleration:	980.54	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.521
   Length of year:		43892.96	days
   Length of day:		13.05	hours


Planet 9	*gas giant*
   Distance from primary:	31.964	AU
   Mass:			1.129	Earth masses
   Equatorial radius:		14393.2	km
   Density:			0.540	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		7.91	km/sec
   Molecular weight retained:	12.69 and above
   Surface acceleration:	217.34	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.526
   Length of year:		63183.77	days
   Length of day:		27.72	hours


Planet 10	
   Distance from primary:	44.250	AU
   Mass:			0.223	Earth masses
   Equatorial radius:		5226.0	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.89	degrees Celcius
   Normal daytime temperature:	-222.61	degrees Celcius
   Normal night temperature:	-233.09	degrees Celcius
   Maximum temperature:   	-209.73	degrees Celcius
   Minimum temperature:   	-246.52	degrees Celcius
   Escape Velocity:		5.83	km/sec
   Molecular weight retained:	23.34 and above
   Surface acceleration:	325.46	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.145
   Length of year:		102917.86	days
   Length of day:		26.57	hours
   Boiling point of water:	-49.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 11	
   Distance from primary:	51.345	AU
   Mass:			1/137.2	Earth masses
   Equatorial radius:		1680.9	km
   Density:			2.190	grams/cc
   Eccentricity of orbit:	0.111
   Surface gravity:		0.10	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.37	degrees Celcius
   Normal daytime temperature:	-223.42	degrees Celcius
   Normal night temperature:	-239.14	degrees Celcius
   Maximum temperature:   	-209.10	degrees Celcius
   Minimum temperature:   	-252.89	degrees Celcius
   Escape Velocity:		1.86	km/sec
   Molecular weight retained:	229.52 and above
   Surface acceleration:	102.88	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.143
   Length of year:		128636.22	days
   Length of day:		47.25	hours
   Boiling point of water:	-102.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.02


