                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486df
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6384 K
Stellar class: F7
Age: 2.698 billion years  (4.131 billion left on main sequence)
Habitable ecosphere radius: 1.272 AU

Planets present at:
1	  0.462 AU	no atmosphere
2	  0.707 AU	no atmosphere
3	  1.530 AU	high pressure
4	  3.022 AU	gas giant
5	  6.146 AU	gas giant
6	 13.954 AU	gas giant
7	 17.127 AU	no atmosphere
8	 27.916 AU	no atmosphere
9	 34.683 AU	gas giant
10	 49.675 AU	no atmosphere



Planet 1	
   Distance from primary:	0.462	AU
   Mass:			0.314	Earth masses
   Equatorial radius:		4381.1	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		183.50	degrees Celcius
   Maximum temperature:   	389.62	degrees Celcius
   Minimum temperature:   	-210.13	degrees Celcius
   Escape Velocity:		7.56	km/sec
   Molecular weight retained:	13.88 and above
   Surface acceleration:	652.84	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.049
   Length of year:		109.32	days
   Length of day:		2623.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.707	AU
   Mass:			0.372	Earth masses
   Equatorial radius:		4630.6	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		93.07	degrees Celcius
   Normal daytime temperature:	169.70	degrees Celcius
   Normal night temperature:	12.80	degrees Celcius
   Maximum temperature:   	197.16	degrees Celcius
   Minimum temperature:   	-16.42	degrees Celcius
   Escape Velocity:		8.00	km/sec
   Molecular weight retained:	12.40 and above
   Surface acceleration:	691.35	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.080
   Length of year:		206.75	days
   Length of day:		56.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	1.530	AU
   Mass:			28.677	Earth masses
   Equatorial radius:		17865.1	km
   Density:			7.176	grams/cc
   Eccentricity of orbit:	0.220
   Surface gravity:		3.65	Earth gees
   Surface pressure:		777.124	Earth atmospheres
   Surface temperature:		428.51	degrees Celcius
   Maximum temperature:   	430.36	degrees Celcius
   Minimum temperature:   	425.16	degrees Celcius
   Escape Velocity:		35.78	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	3583.10	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.620
   Length of year:		657.50	days
   Length of day:		8.01	hours
   Boiling point of water:	460.6	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1595
				Cesium       melts at 28    boils at 1650
				Gallium      melts at 30    boils at 4990
				Rubidium     melts at 39    boils at 1617
				Potassium    melts at 63    boils at 1770
				Sodium       melts at 98    boils at 1998
				Sulfur       melts at 113   boils at 1139
				Indium       melts at 157   boils at 4355
				Lithium      melts at 181   boils at 2913
				Selenium     melts at 217   boils at 1611
				Tin          melts at 232   boils at 5423
				Polonium     melts at 254   boils at 2156
				Bismuth      melts at 271   boils at 3340
				Thallium     melts at 304   boils at 3129
				Cadmium      melts at 321   boils at 1768
				Lead         melts at 328   boils at 3708
				Zinc         melts at 420   boils at 2048
   gasses in atmosphere:
				Nitrogen          0.1%  PP 1083.0 mb
				Helium           99.9%  PP 776035.2 mb


Planet 4	*gas giant*
   Distance from primary:	3.022	AU
   Mass:			4.055	Earth masses
   Equatorial radius:		17129.3	km
   Density:			1.151	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		13.74	km/sec
   Molecular weight retained:	4.20 and above
   Surface acceleration:	551.15	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.466
   Length of year:		1826.26	days
   Length of day:		17.41	hours


Planet 5	*gas giant*
   Distance from primary:	6.146	AU
   Mass:			847.295	Earth masses
   Equatorial radius:		86317.8	km
   Density:			1.880	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		88.48	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4534.96	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.517
   Length of year:		5289.96	days
   Length of day:		6.07	hours


Planet 6	*gas giant*
   Distance from primary:	13.954	AU
   Mass:			405.965	Earth masses
   Equatorial radius:		74571.9	km
   Density:			1.397	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		65.89	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	2911.24	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.498
   Length of year:		18108.12	days
   Length of day:		7.57	hours


Planet 7	
   Distance from primary:	17.127	AU
   Mass:			0.293	Earth masses
   Equatorial radius:		5718.1	km
   Density:			2.237	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.068	Earth atmospheres
   Surface temperature:		-199.82	degrees Celcius
   Normal daytime temperature:	-194.55	degrees Celcius
   Normal night temperature:	-205.28	degrees Celcius
   Maximum temperature:   	-180.55	degrees Celcius
   Minimum temperature:   	-220.65	degrees Celcius
   Escape Velocity:		6.39	km/sec
   Molecular weight retained:	19.42 and above
   Surface acceleration:	357.47	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.326
   Length of year:		24637.88	days
   Length of day:		25.35	hours
   Boiling point of water:	38.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	30.60
   liquids at surface:
				Oxygen       melts at -218  boils at -198
   gasses in atmosphere:
				Neon             100.0%  PP   67.6 mb


Planet 8	
   Distance from primary:	27.916	AU
   Mass:			0.167	Earth masses
   Equatorial radius:		4755.5	km
   Density:			2.221	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-215.58	degrees Celcius
   Normal daytime temperature:	-208.55	degrees Celcius
   Normal night temperature:	-222.55	degrees Celcius
   Maximum temperature:   	-192.46	degrees Celcius
   Minimum temperature:   	-239.38	degrees Celcius
   Escape Velocity:		5.30	km/sec
   Molecular weight retained:	28.28 and above
   Surface acceleration:	295.17	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.152
   Length of year:		51267.52	days
   Length of day:		27.90	hours
   Boiling point of water:	-54.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 9	*gas giant*
   Distance from primary:	34.683	AU
   Mass:			5.233	Earth masses
   Equatorial radius:		22612.9	km
   Density:			0.646	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		13.59	km/sec
   Molecular weight retained:	4.30 and above
   Surface acceleration:	408.12	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.546
   Length of year:		70997.47	days
   Length of day:		20.23	hours


Planet 10	
   Distance from primary:	49.675	AU
   Mass:			0.154	Earth masses
   Equatorial radius:		4628.0	km
   Density:			2.219	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.77	degrees Celcius
   Normal daytime temperature:	-224.42	degrees Celcius
   Normal night temperature:	-235.03	degrees Celcius
   Maximum temperature:   	-208.62	degrees Celcius
   Minimum temperature:   	-250.87	degrees Celcius
   Escape Velocity:		5.15	km/sec
   Molecular weight retained:	29.88 and above
   Surface acceleration:	287.01	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.138
   Length of year:		121695.17	days
   Length of day:		28.29	hours
   Boiling point of water:	-56.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


