                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048993
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6400 K
Stellar class: F7
Age: 4.359 billion years  (2.381 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.393 AU	no atmosphere
2	  0.501 AU	no atmosphere
3	  0.926 AU	greenhouse
4	  1.473 AU	gas giant
5	  4.360 AU	gas giant
6	  7.899 AU	no atmosphere
7	 11.230 AU	gas giant
8	 28.419 AU	gas giant
9	 48.864 AU	no atmosphere



Planet 1	
   Distance from primary:	0.393	AU
   Mass:			0.181	Earth masses
   Equatorial radius:		3652.2	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		221.37	degrees Celcius
   Maximum temperature:   	435.53	degrees Celcius
   Minimum temperature:   	-199.80	degrees Celcius
   Escape Velocity:		6.29	km/sec
   Molecular weight retained:	20.07 and above
   Surface acceleration:	541.53	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.072
   Length of year:		85.42	days
   Length of day:		2050.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.501	AU
   Mass:			0.133	Earth masses
   Equatorial radius:		3298.3	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		165.29	degrees Celcius
   Maximum temperature:   	367.23	degrees Celcius
   Minimum temperature:   	-213.99	degrees Celcius
   Escape Velocity:		5.67	km/sec
   Molecular weight retained:	24.66 and above
   Surface acceleration:	488.02	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.069
   Length of year:		122.91	days
   Length of day:		2949.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.926	AU
   Mass:			1.886	Earth masses
   Equatorial radius:		7864.5	km
   Density:			5.533	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		1.24	Earth gees
   Surface pressure:		279.663	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		511.88	degrees Celcius
   Maximum temperature:   	514.28	degrees Celcius
   Minimum temperature:   	506.94	degrees Celcius
   Escape Velocity:		13.83	km/sec
   Molecular weight retained:	4.15 and above
   Surface acceleration:	1216.21	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.566
   Length of year:		309.23	days
   Length of day:		14.57	hours
   Boiling point of water:	365.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1354
				Cesium       melts at 28    boils at 1402
				Gallium      melts at 30    boils at 4310
				Rubidium     melts at 39    boils at 1373
				Potassium    melts at 63    boils at 1506
				Sodium       melts at 98    boils at 1704
				Indium       melts at 157   boils at 3756
				Lithium      melts at 181   boils at 2501
				Selenium     melts at 217   boils at 1367
				Tin          melts at 232   boils at 4686
				Polonium     melts at 254   boils at 1842
				Bismuth      melts at 271   boils at 2873
				Thallium     melts at 304   boils at 2690
				Cadmium      melts at 321   boils at 1504
				Lead         melts at 328   boils at 3193
				Zinc         melts at 420   boils at 1748
				Tellurium    melts at 450   boils at 1890
   gasses in atmosphere:
				Sulfur           19.4%  PP 54332.5 mb
				Nitrogen         80.0%  PP 223735.3 mb
				Phosphorus        0.4%  PP 1084.3 mb


Planet 4	*gas giant*
   Distance from primary:	1.473	AU
   Mass:			12.257	Earth masses
   Equatorial radius:		22261.0	km
   Density:			1.585	grams/cc
   Eccentricity of orbit:	0.255
   Escape Velocity:		20.96	km/sec
   Molecular weight retained:	1.81 and above
   Surface acceleration:	986.34	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.493
   Length of year:		620.51	days
   Length of day:		13.02	hours


Planet 5	*gas giant*
   Distance from primary:	4.360	AU
   Mass:			881.041	Earth masses
   Equatorial radius:		84785.7	km
   Density:			2.063	grams/cc
   Eccentricity of orbit:	0.071
   Escape Velocity:		91.04	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4887.54	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.506
   Length of year:		3154.91	days
   Length of day:		5.85	hours


Planet 6	
   Distance from primary:	7.899	AU
   Mass:			0.231	Earth masses
   Equatorial radius:		5290.7	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.041	Earth atmospheres
   Surface temperature:		-167.52	degrees Celcius
   Normal daytime temperature:	-158.54	degrees Celcius
   Normal night temperature:	-176.77	degrees Celcius
   Maximum temperature:   	-142.35	degrees Celcius
   Minimum temperature:   	-194.17	degrees Celcius
   Escape Velocity:		5.91	km/sec
   Molecular weight retained:	22.76 and above
   Surface acceleration:	329.64	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.306
   Length of year:		7703.26	days
   Length of day:		26.40	hours
   Boiling point of water:	28.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	27.53
   liquids at surface:
				Ozone        melts at -193  boils at -143
   gasses in atmosphere:
				Argon            100.0%  PP   41.1 mb


Planet 7	*gas giant*
   Distance from primary:	11.230	AU
   Mass:			158.641	Earth masses
   Equatorial radius:		55641.1	km
   Density:			1.314	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		47.69	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2043.45	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.501
   Length of year:		13055.12	days
   Length of day:		9.04	hours


Planet 8	*gas giant*
   Distance from primary:	28.419	AU
   Mass:			146.191	Earth masses
   Equatorial radius:		58701.1	km
   Density:			1.031	grams/cc
   Eccentricity of orbit:	0.350
   Escape Velocity:		44.57	km/sec
   Molecular weight retained:	0.40 and above
   Surface acceleration:	1691.86	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.513
   Length of year:		52560.03	days
   Length of day:		9.94	hours


Planet 9	
   Distance from primary:	48.864	AU
   Mass:			0.166	Earth masses
   Equatorial radius:		4743.7	km
   Density:			2.221	grams/cc
   Eccentricity of orbit:	0.177
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.44	degrees Celcius
   Normal daytime temperature:	-224.11	degrees Celcius
   Normal night temperature:	-234.68	degrees Celcius
   Maximum temperature:   	-206.09	degrees Celcius
   Minimum temperature:   	-252.36	degrees Celcius
   Escape Velocity:		5.29	km/sec
   Molecular weight retained:	28.42 and above
   Surface acceleration:	294.41	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.154
   Length of year:		118526.42	days
   Length of day:		27.93	hours
   Boiling point of water:	-56.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


