                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048ab9
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6195 K
Stellar class: F8
Age: 1.237 billion years  (5.467 billion left on main sequence)
Habitable ecosphere radius: 1.287 AU

Planets present at:
1	  0.349 AU	no atmosphere
2	  0.416 AU	no atmosphere
3	  0.644 AU	no atmosphere
4	  1.284 AU	high pressure
5	  2.033 AU	gas giant
6	  3.254 AU	gas giant
7	  6.135 AU	gas giant
8	 10.578 AU	gas giant
9	 24.380 AU	gas giant
10	 36.003 AU	gas giant
11	 45.061 AU	no atmosphere



Planet 1	
   Distance from primary:	0.349	AU
   Mass:			0.025	Earth masses
   Equatorial radius:		1886.2	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.05	degrees Celcius
   Normal daytime temperature:	473.30	degrees Celcius
   Normal night temperature:	-180.47	degrees Celcius
   Maximum temperature:   	476.41	degrees Celcius
   Minimum temperature:   	-191.29	degrees Celcius
   Escape Velocity:		3.23	km/sec
   Molecular weight retained:	75.86 and above
   Surface acceleration:	277.37	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.056
   Length of year:		71.34	days
   Length of day:		1712.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.416	AU
   Mass:			0.238	Earth masses
   Equatorial radius:		3998.9	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		206.41	degrees Celcius
   Maximum temperature:   	417.35	degrees Celcius
   Minimum temperature:   	-203.58	degrees Celcius
   Escape Velocity:		6.89	km/sec
   Molecular weight retained:	16.70 and above
   Surface acceleration:	594.26	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.084
   Length of year:		93.19	days
   Length of day:		2236.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.644	AU
   Mass:			0.495	Earth masses
   Equatorial radius:		5088.1	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		113.80	degrees Celcius
   Normal daytime temperature:	163.92	degrees Celcius
   Normal night temperature:	62.45	degrees Celcius
   Maximum temperature:   	194.13	degrees Celcius
   Minimum temperature:   	31.36	degrees Celcius
   Escape Velocity:		8.81	km/sec
   Molecular weight retained:	10.23 and above
   Surface acceleration:	762.56	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.072
   Length of year:		179.18	days
   Length of day:		30.61	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.284	AU
   Mass:			1.609	Earth masses
   Equatorial radius:		7471.5	km
   Density:			5.504	grams/cc
   Eccentricity of orbit:	0.207
   Surface gravity:		1.17	Earth gees
   Surface pressure:		2.006	Earth atmospheres
   Surface temperature:		19.55	degrees Celcius
   Normal daytime temperature:	22.47	degrees Celcius
   Normal night temperature:	16.44	degrees Celcius
   Maximum temperature:   	41.42	degrees Celcius
   Minimum temperature:   	-3.56	degrees Celcius
   Escape Velocity:		13.10	km/sec
   Molecular weight retained:	4.62 and above
   Surface acceleration:	1149.29	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.367
   Length of year:		504.65	days
   Length of day:		14.17	hours
   Boiling point of water:	120.2	degrees Celcius
   Hydrosphere percentage:	64.56
   Cloud cover percentage:	64.36
   Ice cover percentage:	0.89
   liquids at surface:
				Ethanol      melts at -114  boils at 98
				Mercury      melts at -39   boils at 391
				Bromine      melts at -7    boils at 78
				Water        melts at 0     boils at 120
   gasses in atmosphere:
				Oxygen           12.8%  PP  256.6 mb
				Nitrogen         87.1%  PP 1746.8 mb


Planet 5	*gas giant*
   Distance from primary:	2.033	AU
   Mass:			2.884	Earth masses
   Equatorial radius:		14990.5	km
   Density:			1.222	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		12.39	km/sec
   Molecular weight retained:	5.17 and above
   Surface acceleration:	511.86	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.460
   Length of year:		1005.36	days
   Length of day:		18.07	hours


Planet 6	*gas giant*
   Distance from primary:	3.254	AU
   Mass:			48.837	Earth masses
   Equatorial radius:		35579.7	km
   Density:			1.547	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		33.09	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1538.47	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.528
   Length of year:		2034.85	days
   Length of day:		10.42	hours


Planet 7	*gas giant*
   Distance from primary:	6.135	AU
   Mass:			1048.849	Earth masses
   Equatorial radius:		91758.4	km
   Density:			1.937	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		95.48	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4967.76	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.464
   Length of year:		5261.93	days
   Length of day:		5.80	hours


Planet 8	*gas giant*
   Distance from primary:	10.578	AU
   Mass:			278.890	Earth masses
   Equatorial radius:		65248.7	km
   Density:			1.433	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		58.39	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2612.34	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.468
   Length of year:		11925.67	days
   Length of day:		8.00	hours


Planet 9	*gas giant*
   Distance from primary:	24.380	AU
   Mass:			3.697	Earth masses
   Equatorial radius:		19821.9	km
   Density:			0.677	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		12.20	km/sec
   Molecular weight retained:	5.34 and above
   Surface acceleration:	375.18	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.543
   Length of year:		41741.27	days
   Length of day:		21.10	hours


Planet 10	*gas giant*
   Distance from primary:	36.003	AU
   Mass:			2.734	Earth masses
   Equatorial radius:		18752.1	km
   Density:			0.592	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		10.78	km/sec
   Molecular weight retained:	6.83 and above
   Surface acceleration:	310.06	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.539
   Length of year:		74905.37	days
   Length of day:		23.21	hours


Planet 11	
   Distance from primary:	45.061	AU
   Mass:			0.146	Earth masses
   Equatorial radius:		4545.4	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.69	degrees Celcius
   Normal daytime temperature:	-222.03	degrees Celcius
   Normal night temperature:	-233.26	degrees Celcius
   Maximum temperature:   	-209.90	degrees Celcius
   Minimum temperature:   	-245.93	degrees Celcius
   Escape Velocity:		5.06	km/sec
   Molecular weight retained:	30.99 and above
   Surface acceleration:	281.73	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.148
   Length of year:		104884.02	days
   Length of day:		28.55	hours
   Boiling point of water:	-56.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


