                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ba7
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6219 K
Stellar class: F8
Age: 3.494 billion years  (3.718 billion left on main sequence)
Habitable ecosphere radius: 1.229 AU

Planets present at:
1	  0.343 AU	no atmosphere
2	  0.414 AU	no atmosphere
3	  0.519 AU	no atmosphere
4	  0.908 AU	greenhouse
5	  1.328 AU	high pressure
6	  2.015 AU	gas giant
7	  3.201 AU	gas giant
8	  8.154 AU	gas giant
9	 13.348 AU	no atmosphere
10	 22.286 AU	gas giant
11	 29.408 AU	gas giant
12	 48.204 AU	no atmosphere



Planet 1	
   Distance from primary:	0.343	AU
   Mass:			0.189	Earth masses
   Equatorial radius:		3701.5	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		244.44	degrees Celcius
   Normal daytime temperature:	460.30	degrees Celcius
   Normal night temperature:	-181.75	degrees Celcius
   Maximum temperature:   	463.45	degrees Celcius
   Minimum temperature:   	-192.55	degrees Celcius
   Escape Velocity:		6.38	km/sec
   Molecular weight retained:	19.53 and above
   Surface acceleration:	549.01	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.075
   Length of year:		70.35	days
   Length of day:		1688.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.414	AU
   Mass:			0.058	Earth masses
   Equatorial radius:		2505.8	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		199.28	degrees Celcius
   Maximum temperature:   	408.67	degrees Celcius
   Minimum temperature:   	-204.92	degrees Celcius
   Escape Velocity:		4.30	km/sec
   Molecular weight retained:	42.89 and above
   Surface acceleration:	369.32	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.066
   Length of year:		93.13	days
   Length of day:		2235.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.519	AU
   Mass:			0.209	Earth masses
   Equatorial radius:		3831.0	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.20	degrees Celcius
   Maximum temperature:   	347.06	degrees Celcius
   Minimum temperature:   	-214.15	degrees Celcius
   Escape Velocity:		6.60	km/sec
   Molecular weight retained:	18.22 and above
   Surface acceleration:	568.68	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.061
   Length of year:		130.97	days
   Length of day:		2534.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.908	AU
   Mass:			0.720	Earth masses
   Equatorial radius:		5752.9	km
   Density:			5.396	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.88	Earth gees
   Surface pressure:		41.778	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		192.63	degrees Celcius
   Maximum temperature:   	198.80	degrees Celcius
   Minimum temperature:   	185.91	degrees Celcius
   Escape Velocity:		9.99	km/sec
   Molecular weight retained:	7.95 and above
   Surface acceleration:	867.56	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.571
   Length of year:		302.68	days
   Length of day:		18.29	hours
   Boiling point of water:	241.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 597
				Francium     melts at 27    boils at 1038
				Cesium       melts at 28    boils at 1077
				Gallium      melts at 30    boils at 3421
				Rubidium     melts at 39    boils at 1054
				Phosphorus   melts at 44    boils at 491
				Potassium    melts at 63    boils at 1161
				Sodium       melts at 98    boils at 1321
				Sulfur       melts at 113   boils at 718
				Indium       melts at 157   boils at 2975
				Lithium      melts at 181   boils at 1963
   gasses in atmosphere:
				Nitrogen         99.6%  PP 41629.3 mb
				CarbonDioxide     0.1%  PP   32.2 mb
				Ozone             0.1%  PP   30.9 mb
				Ethanol           0.1%  PP   32.7 mb


Planet 5	
   Distance from primary:	1.328	AU
   Mass:			1.532	Earth masses
   Equatorial radius:		7354.2	km
   Density:			5.496	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		1.15	Earth gees
   Surface pressure:		2.227	Earth atmospheres
   Surface temperature:		14.57	degrees Celcius
   Normal daytime temperature:	17.33	degrees Celcius
   Normal night temperature:	11.63	degrees Celcius
   Maximum temperature:   	32.76	degrees Celcius
   Minimum temperature:   	-4.64	degrees Celcius
   Escape Velocity:		12.89	km/sec
   Molecular weight retained:	4.78 and above
   Surface acceleration:	1129.52	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.318
   Length of year:		535.50	days
   Length of day:		14.35	hours
   Boiling point of water:	123.4	degrees Celcius
   Hydrosphere percentage:	77.68
   Cloud cover percentage:	55.38
   Ice cover percentage:	1.70
   liquids at surface:
				Ethanol      melts at -114  boils at 101
				Mercury      melts at -39   boils at 396
				Bromine      melts at -7    boils at 80
				Water        melts at 0     boils at 123
   gasses in atmosphere:
				Oxygen            5.3%  PP  117.3 mb
				Nitrogen         94.6%  PP 2105.7 mb


Planet 6	*gas giant*
   Distance from primary:	2.015	AU
   Mass:			2.366	Earth masses
   Equatorial radius:		14193.2	km
   Density:			1.181	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		11.53	km/sec
   Molecular weight retained:	5.97 and above
   Surface acceleration:	468.45	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.453
   Length of year:		1001.17	days
   Length of day:		18.89	hours


Planet 7	*gas giant*
   Distance from primary:	3.201	AU
   Mass:			188.708	Earth masses
   Equatorial radius:		52905.8	km
   Density:			1.818	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		53.34	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2688.58	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.485
   Length of year:		2004.68	days
   Length of day:		7.88	hours


Planet 8	*gas giant*
   Distance from primary:	8.154	AU
   Mass:			1407.177	Earth masses
   Equatorial radius:		102763.5	km
   Density:			1.850	grams/cc
   Eccentricity of orbit:	0.105
   Escape Velocity:		104.51	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5313.86	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.454
   Length of year:		8136.25	days
   Length of day:		5.61	hours


Planet 9	
   Distance from primary:	13.348	AU
   Mass:			1/456.6	Earth masses
   Equatorial radius:		1126.2	km
   Density:			2.188	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.07	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-192.38	degrees Celcius
   Normal daytime temperature:	-174.32	degrees Celcius
   Normal night temperature:	-210.36	degrees Celcius
   Maximum temperature:   	-155.41	degrees Celcius
   Minimum temperature:   	-228.95	degrees Celcius
   Escape Velocity:		1.25	km/sec
   Molecular weight retained:	511.84 and above
   Surface acceleration:	68.86	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.175
   Length of year:		17073.40	days
   Length of day:		57.76	hours
   Boiling point of water:	-81.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	4.32
   liquids at surface:
				Ozone        melts at -193  boils at -166


Planet 10	*gas giant*
   Distance from primary:	22.286	AU
   Mass:			2.132	Earth masses
   Equatorial radius:		16821.4	km
   Density:			0.639	grams/cc
   Eccentricity of orbit:	0.198
   Escape Velocity:		10.05	km/sec
   Molecular weight retained:	7.85 and above
   Surface acceleration:	300.49	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.508
   Length of year:		36833.32	days
   Length of day:		23.58	hours


Planet 11	*gas giant*
   Distance from primary:	29.408	AU
   Mass:			25.332	Earth masses
   Equatorial radius:		35432.3	km
   Density:			0.813	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		23.88	km/sec
   Molecular weight retained:	1.39 and above
   Surface acceleration:	804.67	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.536
   Length of year:		55830.90	days
   Length of day:		14.41	hours


Planet 12	
   Distance from primary:	48.204	AU
   Mass:			0.219	Earth masses
   Equatorial radius:		5195.0	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.95	degrees Celcius
   Normal daytime temperature:	-224.90	degrees Celcius
   Normal night temperature:	-234.91	degrees Celcius
   Maximum temperature:   	-210.74	degrees Celcius
   Minimum temperature:   	-249.41	degrees Celcius
   Escape Velocity:		5.80	km/sec
   Molecular weight retained:	23.62 and above
   Surface acceleration:	323.45	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.149
   Length of year:		117170.26	days
   Length of day:		26.65	hours
   Boiling point of water:	-48.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10


