                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950483c5
Stellar mass: 1.10 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6182 K
Stellar class: F8
Age: 2.242 billion years  (4.690 billion left on main sequence)
Habitable ecosphere radius: 1.260 AU

Planets present at:
1	  0.441 AU	no atmosphere
2	  0.624 AU	no atmosphere
3	  0.915 AU	greenhouse
4	  1.763 AU	no atmosphere
5	  2.125 AU	high pressure
6	  3.610 AU	gas giant
7	  4.857 AU	gas giant
8	  8.395 AU	gas giant
9	 11.648 AU	gas giant
10	 26.997 AU	gas giant
11	 37.096 AU	gas giant
12	 48.663 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.441	AU
   Mass:			0.506	Earth masses
   Equatorial radius:		5126.1	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.177
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		190.96	degrees Celcius
   Normal daytime temperature:	394.67	degrees Celcius
   Normal night temperature:	-190.69	degrees Celcius
   Maximum temperature:   	398.32	degrees Celcius
   Minimum temperature:   	-202.37	degrees Celcius
   Escape Velocity:		8.88	km/sec
   Molecular weight retained:	10.08 and above
   Surface acceleration:	768.51	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.059
   Length of year:		102.06	days
   Length of day:		1712.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.624	AU
   Mass:			0.436	Earth masses
   Equatorial radius:		4879.8	km
   Density:			5.353	grams/cc
   Eccentricity of orbit:	0.145
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		115.85	degrees Celcius
   Maximum temperature:   	305.90	degrees Celcius
   Minimum temperature:   	-221.66	degrees Celcius
   Escape Velocity:		8.44	km/sec
   Molecular weight retained:	11.14 and above
   Surface acceleration:	730.03	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.070
   Length of year:		171.87	days
   Length of day:		3077.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.915	AU
   Mass:			0.493	Earth masses
   Equatorial radius:		5080.2	km
   Density:			5.362	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.78	Earth gees
   Surface pressure:		20.794	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		126.66	degrees Celcius
   Maximum temperature:   	135.12	degrees Celcius
   Minimum temperature:   	117.68	degrees Celcius
   Escape Velocity:		8.80	km/sec
   Molecular weight retained:	10.26 and above
   Surface acceleration:	761.33	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.451
   Length of year:		305.06	days
   Length of day:		19.17	hours
   Boiling point of water:	207.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 539
				Francium     melts at 27    boils at 951
				Cesium       melts at 28    boils at 987
				Gallium      melts at 30    boils at 3176
				Rubidium     melts at 39    boils at 965
				Phosphorus   melts at 44    boils at 440
				Potassium    melts at 63    boils at 1066
				Sodium       melts at 98    boils at 1215
				Sulfur       melts at 113   boils at 652
				Iodine       melts at 114   boils at 318
   gasses in atmosphere:
				Nitrogen         99.5%  PP 20693.7 mb
				Water             0.1%  PP   11.1 mb
				CarbonDioxide     0.1%  PP   22.6 mb
				Ozone             0.1%  PP   22.8 mb
				Ethanol           0.1%  PP   23.0 mb


Planet 4	
   Distance from primary:	1.763	AU
   Mass:			0.224	Earth masses
   Equatorial radius:		3918.7	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.151
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.046	Earth atmospheres
   Surface temperature:		-57.31	degrees Celcius
   Normal daytime temperature:	-43.41	degrees Celcius
   Normal night temperature:	-71.59	degrees Celcius
   Maximum temperature:   	-17.04	degrees Celcius
   Minimum temperature:   	-99.14	degrees Celcius
   Escape Velocity:		6.75	km/sec
   Molecular weight retained:	17.40 and above
   Surface acceleration:	582.04	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.439
   Length of year:		815.27	days
   Length of day:		19.94	hours
   Boiling point of water:	31.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.18
   Ice cover percentage:	58.28
   liquids at surface:
				Ethanol      melts at -114  boils at 14
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP   21.6 mb
				Ozone            49.5%  PP   22.9 mb
				Fluorine          0.2%  PP    0.1 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.3%  PP    0.2 mb
				Krypton           2.9%  PP    1.3 mb
				Xenon             0.3%  PP    0.2 mb


Planet 5	
   Distance from primary:	2.125	AU
   Mass:			1.952	Earth masses
   Equatorial radius:		7951.9	km
   Density:			5.540	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		1.26	Earth gees
   Surface pressure:		3.713	Earth atmospheres
   Surface temperature:		-85.49	degrees Celcius
   Normal daytime temperature:	-84.14	degrees Celcius
   Normal night temperature:	-86.91	degrees Celcius
   Maximum temperature:   	-73.02	degrees Celcius
   Minimum temperature:   	-98.79	degrees Celcius
   Escape Velocity:		13.99	km/sec
   Molecular weight retained:	4.05 and above
   Surface acceleration:	1231.22	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.723
   Length of year:		1078.75	days
   Length of day:		13.66	hours
   Boiling point of water:	140.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 116
				Chlorine     melts at -101  boils at -8
   gasses in atmosphere:
				Nitrogen         99.9%  PP 3709.9 mb


Planet 6	*gas giant*
   Distance from primary:	3.610	AU
   Mass:			647.306	Earth masses
   Equatorial radius:		76398.8	km
   Density:			2.071	grams/cc
   Eccentricity of orbit:	0.087
   Escape Velocity:		82.20	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4422.59	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.518
   Length of year:		2387.04	days
   Length of day:		6.15	hours


Planet 7	*gas giant*
   Distance from primary:	4.857	AU
   Mass:			1.132	Earth masses
   Equatorial radius:		12290.5	km
   Density:			0.870	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		8.57	km/sec
   Molecular weight retained:	10.81 and above
   Surface acceleration:	298.73	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.500
   Length of year:		3727.87	days
   Length of day:		23.65	hours


Planet 8	*gas giant*
   Distance from primary:	8.395	AU
   Mass:			0.954	Earth masses
   Equatorial radius:		12240.8	km
   Density:			0.743	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		7.89	km/sec
   Molecular weight retained:	12.76 and above
   Surface acceleration:	254.02	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.497
   Length of year:		8470.97	days
   Length of day:		25.64	hours


Planet 9	*gas giant*
   Distance from primary:	11.648	AU
   Mass:			527.372	Earth masses
   Equatorial radius:		79345.5	km
   Density:			1.506	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		72.81	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3340.50	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.507
   Length of year:		13835.36	days
   Length of day:		7.07	hours


Planet 10	*gas giant*
   Distance from primary:	26.997	AU
   Mass:			2.363	Earth masses
   Equatorial radius:		17576.0	km
   Density:			0.621	grams/cc
   Eccentricity of orbit:	0.201
   Escape Velocity:		10.36	km/sec
   Molecular weight retained:	7.40 and above
   Surface acceleration:	305.04	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.473
   Length of year:		48854.61	days
   Length of day:		23.40	hours


Planet 11	*gas giant*
   Distance from primary:	37.096	AU
   Mass:			3.630	Earth masses
   Equatorial radius:		20455.2	km
   Density:			0.605	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		11.90	km/sec
   Molecular weight retained:	5.61 and above
   Surface acceleration:	345.98	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.545
   Length of year:		78689.07	days
   Length of day:		21.97	hours


Planet 12	
   Distance from primary:	48.663	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		4252.6	km
   Density:			2.214	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.03	degrees Celcius
   Normal daytime temperature:	-224.50	degrees Celcius
   Normal night temperature:	-235.46	degrees Celcius
   Maximum temperature:   	-211.87	degrees Celcius
   Minimum temperature:   	-248.47	degrees Celcius
   Escape Velocity:		4.73	km/sec
   Molecular weight retained:	35.47 and above
   Surface acceleration:	263.10	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.161
   Length of year:		118230.93	days
   Length of day:		29.55	hours
   Boiling point of water:	-60.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


