                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048443
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6320 K
Stellar class: F7
Age: 4.316 billion years  (2.599 billion left on main sequence)
Habitable ecosphere radius: 1.262 AU

Planets present at:
1	  0.336 AU	no atmosphere
2	  0.558 AU	no atmosphere
3	  0.650 AU	no atmosphere
4	  1.239 AU	
5	  1.626 AU	gas giant
6	  2.105 AU	no atmosphere
7	  4.808 AU	gas giant
8	  7.974 AU	gas giant
9	 12.308 AU	gas giant
10	 18.812 AU	no atmosphere
11	 28.888 AU	no atmosphere
12	 34.620 AU	no atmosphere
13	 47.999 AU	gas giant



Planet 1	
   Distance from primary:	0.336	AU
   Mass:			0.110	Earth masses
   Equatorial radius:		3096.3	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		257.78	degrees Celcius
   Normal daytime temperature:	476.46	degrees Celcius
   Normal night temperature:	-178.47	degrees Celcius
   Maximum temperature:   	479.54	degrees Celcius
   Minimum temperature:   	-189.23	degrees Celcius
   Escape Velocity:		5.32	km/sec
   Molecular weight retained:	28.01 and above
   Surface acceleration:	457.64	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.069
   Length of year:		67.75	days
   Length of day:		1625.98	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.558	AU
   Mass:			0.606	Earth masses
   Equatorial radius:		5437.1	km
   Density:			5.380	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		136.89	degrees Celcius
   Maximum temperature:   	332.15	degrees Celcius
   Minimum temperature:   	-219.59	degrees Celcius
   Escape Velocity:		9.43	km/sec
   Molecular weight retained:	8.93 and above
   Surface acceleration:	817.44	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.086
   Length of year:		145.14	days
   Length of day:		3483.48	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.650	AU
   Mass:			0.030	Earth masses
   Equatorial radius:		2017.9	km
   Density:			5.264	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		106.74	degrees Celcius
   Maximum temperature:   	294.50	degrees Celcius
   Minimum temperature:   	-224.37	degrees Celcius
   Escape Velocity:		3.46	km/sec
   Molecular weight retained:	66.26 and above
   Surface acceleration:	296.86	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.087
   Length of year:		182.36	days
   Length of day:		4376.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.239	AU
   Mass:			0.478	Earth masses
   Equatorial radius:		5028.4	km
   Density:			5.360	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.77	Earth gees
   Surface pressure:		0.173	Earth atmospheres
   Surface temperature:		11.56	degrees Celcius
   Normal daytime temperature:	22.42	degrees Celcius
   Normal night temperature:	0.17	degrees Celcius
   Maximum temperature:   	49.54	degrees Celcius
   Minimum temperature:   	-28.27	degrees Celcius
   Escape Velocity:		8.70	km/sec
   Molecular weight retained:	10.48 and above
   Surface acceleration:	753.22	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.230
   Length of year:		480.13	days
   Length of day:		18.01	hours
   Boiling point of water:	57.2	degrees Celcius
   Hydrosphere percentage:	41.37
   Cloud cover percentage:	23.76
   Ice cover percentage:	2.47
   liquids at surface:
				Ethanol      melts at -114  boils at 38
				Mercury      melts at -39   boils at 285
				Bromine      melts at -7    boils at 21
				Water        melts at 0     boils at 57
   gasses in atmosphere:
				Oxygen           52.3%  PP   90.4 mb
				Nitrogen         47.5%  PP   82.2 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.626	AU
   Mass:			22.924	Earth masses
   Equatorial radius:		26978.2	km
   Density:			1.666	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		26.03	km/sec
   Molecular weight retained:	1.17 and above
   Surface acceleration:	1256.02	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.478
   Length of year:		722.11	days
   Length of day:		11.53	hours


Planet 6	
   Distance from primary:	2.105	AU
   Mass:			0.209	Earth masses
   Equatorial radius:		3831.4	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.138
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.043	Earth atmospheres
   Surface temperature:		-77.39	degrees Celcius
   Normal daytime temperature:	-64.40	degrees Celcius
   Normal night temperature:	-90.71	degrees Celcius
   Maximum temperature:   	-38.55	degrees Celcius
   Minimum temperature:   	-117.82	degrees Celcius
   Escape Velocity:		6.60	km/sec
   Molecular weight retained:	18.21 and above
   Surface acceleration:	568.75	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.458
   Length of year:		1063.63	days
   Length of day:		20.15	hours
   Boiling point of water:	29.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	60.11
   liquids at surface:
				Ethanol      melts at -114  boils at 12
   gasses in atmosphere:
				CarbonDioxide    46.5%  PP   19.8 mb
				Ozone            49.7%  PP   21.2 mb
				Argon             0.1%  PP    0.1 mb
				Neon              0.2%  PP    0.1 mb
				Krypton           3.0%  PP    1.3 mb
				Xenon             0.4%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	4.808	AU
   Mass:			9.106	Earth masses
   Equatorial radius:		22557.8	km
   Density:			1.132	grams/cc
   Eccentricity of orbit:	0.118
   Escape Velocity:		17.94	km/sec
   Molecular weight retained:	2.47 and above
   Surface acceleration:	713.62	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.462
   Length of year:		3670.87	days
   Length of day:		15.30	hours


Planet 8	*gas giant*
   Distance from primary:	7.974	AU
   Mass:			1282.847	Earth masses
   Equatorial radius:		99621.6	km
   Density:			1.851	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		101.34	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5154.74	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.501
   Length of year:		7826.16	days
   Length of day:		5.69	hours


Planet 9	*gas giant*
   Distance from primary:	12.308	AU
   Mass:			245.635	Earth masses
   Equatorial radius:		63779.1	km
   Density:			1.351	grams/cc
   Eccentricity of orbit:	0.155
   Escape Velocity:		55.42	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2408.09	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.527
   Length of year:		15028.03	days
   Length of day:		8.33	hours


Planet 10	
   Distance from primary:	18.812	AU
   Mass:			0.158	Earth masses
   Equatorial radius:		4661.6	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.020	Earth atmospheres
   Surface temperature:		-205.10	degrees Celcius
   Normal daytime temperature:	-198.09	degrees Celcius
   Normal night temperature:	-212.22	degrees Celcius
   Maximum temperature:   	-181.40	degrees Celcius
   Minimum temperature:   	-230.05	degrees Celcius
   Escape Velocity:		5.19	km/sec
   Molecular weight retained:	29.45 and above
   Surface acceleration:	289.16	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.289
   Length of year:		28408.84	days
   Length of day:		28.18	hours
   Boiling point of water:	16.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	25.59
   liquids at surface:
				Oxygen       melts at -218  boils at -203


Planet 11	
   Distance from primary:	28.888	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		4557.0	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.25	degrees Celcius
   Normal daytime temperature:	-210.29	degrees Celcius
   Normal night temperature:	-224.14	degrees Celcius
   Maximum temperature:   	-194.87	degrees Celcius
   Minimum temperature:   	-240.26	degrees Celcius
   Escape Velocity:		5.07	km/sec
   Molecular weight retained:	30.83 and above
   Surface acceleration:	282.47	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.164
   Length of year:		54059.99	days
   Length of day:		28.52	hours
   Boiling point of water:	-59.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06
   liquids at surface:
				Fluorine     melts at -220  boils at -217
				Oxygen       melts at -218  boils at -213


Planet 12	
   Distance from primary:	34.620	AU
   Mass:			0.242	Earth masses
   Equatorial radius:		5370.6	km
   Density:			2.231	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-221.49	degrees Celcius
   Normal daytime temperature:	-215.53	degrees Celcius
   Normal night temperature:	-227.38	degrees Celcius
   Maximum temperature:   	-202.12	degrees Celcius
   Minimum temperature:   	-241.54	degrees Celcius
   Escape Velocity:		6.00	km/sec
   Molecular weight retained:	22.07 and above
   Surface acceleration:	334.83	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.147
   Length of year:		70921.28	days
   Length of day:		26.19	hours
   Boiling point of water:	-46.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10


Planet 13	*gas giant*
   Distance from primary:	47.999	AU
   Mass:			0.516	Earth masses
   Equatorial radius:		11829.4	km
   Density:			0.445	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		5.90	km/sec
   Molecular weight retained:	22.82 and above
   Surface acceleration:	147.06	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.459
   Length of year:		115780.36	days
   Length of day:		33.70	hours


