                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047dcc
Stellar mass: 1.09 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6170 K
Stellar class: F8
Age: 4.192 billion years  (2.945 billion left on main sequence)
Habitable ecosphere radius: 1.237 AU

Planets present at:
1	  0.335 AU	no atmosphere
2	  0.567 AU	no atmosphere
3	  0.850 AU	no atmosphere
4	  1.014 AU	greenhouse
5	  1.635 AU	no atmosphere
6	  2.028 AU	gas giant
7	  3.075 AU	gas giant
8	  8.767 AU	gas giant
9	 20.601 AU	gas giant
10	 47.448 AU	gas giant



Planet 1	
   Distance from primary:	0.335	AU
   Mass:			0.161	Earth masses
   Equatorial radius:		3514.0	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		254.03	degrees Celcius
   Normal daytime temperature:	471.88	degrees Celcius
   Normal night temperature:	-179.03	degrees Celcius
   Maximum temperature:   	475.03	degrees Celcius
   Minimum temperature:   	-190.04	degrees Celcius
   Escape Velocity:		6.05	km/sec
   Molecular weight retained:	21.70 and above
   Surface acceleration:	520.59	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.065
   Length of year:		67.66	days
   Length of day:		1623.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.567	AU
   Mass:			0.280	Earth masses
   Equatorial radius:		4215.8	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.29	degrees Celcius
   Maximum temperature:   	327.53	degrees Celcius
   Minimum temperature:   	-219.82	degrees Celcius
   Escape Velocity:		7.27	km/sec
   Molecular weight retained:	15.00 and above
   Surface acceleration:	627.45	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.053
   Length of year:		149.19	days
   Length of day:		3580.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.850	AU
   Mass:			0.152	Earth masses
   Equatorial radius:		3444.0	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		55.95	degrees Celcius
   Normal daytime temperature:	141.04	degrees Celcius
   Normal night temperature:	-34.04	degrees Celcius
   Maximum temperature:   	166.82	degrees Celcius
   Minimum temperature:   	-62.21	degrees Celcius
   Escape Velocity:		5.93	km/sec
   Molecular weight retained:	22.60 and above
   Surface acceleration:	510.01	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.085
   Length of year:		273.80	days
   Length of day:		75.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	1.014	AU
   Mass:			1.586	Earth masses
   Equatorial radius:		7437.0	km
   Density:			5.502	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		1.17	Earth gees
   Surface pressure:		209.525	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		454.70	degrees Celcius
   Maximum temperature:   	457.57	degrees Celcius
   Minimum temperature:   	449.84	degrees Celcius
   Escape Velocity:		13.04	km/sec
   Molecular weight retained:	4.67 and above
   Surface acceleration:	1143.47	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.501
   Length of year:		357.14	days
   Length of day:		14.70	hours
   Boiling point of water:	343.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1296
				Cesium       melts at 28    boils at 1343
				Gallium      melts at 30    boils at 4148
				Rubidium     melts at 39    boils at 1315
				Potassium    melts at 63    boils at 1443
				Sodium       melts at 98    boils at 1634
				Indium       melts at 157   boils at 3614
				Lithium      melts at 181   boils at 2403
				Selenium     melts at 217   boils at 1310
				Tin          melts at 232   boils at 4512
				Polonium     melts at 254   boils at 1767
				Bismuth      melts at 271   boils at 2762
				Thallium     melts at 304   boils at 2585
				Cadmium      melts at 321   boils at 1442
				Lead         melts at 328   boils at 3071
				Zinc         melts at 420   boils at 1676
				Tellurium    melts at 450   boils at 1814
   gasses in atmosphere:
				Sulfur           19.8%  PP 41387.3 mb
				Nitrogen         79.7%  PP 166909.2 mb
				Phosphorus        0.4%  PP  825.7 mb


Planet 5	
   Distance from primary:	1.635	AU
   Mass:			0.237	Earth masses
   Equatorial radius:		3992.6	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.052	Earth atmospheres
   Surface temperature:		-51.68	degrees Celcius
   Normal daytime temperature:	-37.86	degrees Celcius
   Normal night temperature:	-65.90	degrees Celcius
   Maximum temperature:   	-14.00	degrees Celcius
   Minimum temperature:   	-90.81	degrees Celcius
   Escape Velocity:		6.88	km/sec
   Molecular weight retained:	16.76 and above
   Surface acceleration:	593.31	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.448
   Length of year:		731.22	days
   Length of day:		19.87	hours
   Boiling point of water:	33.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.28
   Ice cover percentage:	59.38
   liquids at surface:
				Ethanol      melts at -114  boils at 16
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP   24.1 mb
				Ozone            49.6%  PP   25.7 mb
				Argon             0.1%  PP    0.1 mb
				Neon              0.4%  PP    0.2 mb
				Krypton           3.0%  PP    1.5 mb
				Xenon             0.4%  PP    0.2 mb


Planet 6	*gas giant*
   Distance from primary:	2.028	AU
   Mass:			33.521	Earth masses
   Equatorial radius:		30751.1	km
   Density:			1.645	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		29.49	km/sec
   Molecular weight retained:	0.91 and above
   Surface acceleration:	1413.63	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.513
   Length of year:		1009.90	days
   Length of day:		10.87	hours


Planet 7	*gas giant*
   Distance from primary:	3.075	AU
   Mass:			51.622	Earth masses
   Equatorial radius:		36109.0	km
   Density:			1.565	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		33.77	km/sec
   Molecular weight retained:	0.70 and above
   Surface acceleration:	1578.86	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.545
   Length of year:		1885.30	days
   Length of day:		10.29	hours


Planet 8	*gas giant*
   Distance from primary:	8.767	AU
   Mass:			633.168	Earth masses
   Equatorial radius:		81858.2	km
   Density:			1.647	grams/cc
   Eccentricity of orbit:	0.248
   Escape Velocity:		78.54	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3768.20	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.469
   Length of year:		9067.52	days
   Length of day:		6.66	hours


Planet 9	*gas giant*
   Distance from primary:	20.601	AU
   Mass:			244.677	Earth masses
   Equatorial radius:		66610.9	km
   Density:			1.181	grams/cc
   Eccentricity of orbit:	0.126
   Escape Velocity:		54.13	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2199.08	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.461
   Length of year:		32679.57	days
   Length of day:		8.72	hours


Planet 10	*gas giant*
   Distance from primary:	47.448	AU
   Mass:			0.504	Earth masses
   Equatorial radius:		11754.7	km
   Density:			0.443	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.22 and above
   Surface acceleration:	145.39	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.525
   Length of year:		114264.17	days
   Length of day:		33.90	hours


