                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048b30
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6306 K
Stellar class: F7
Age: 4.589 billion years  (2.100 billion left on main sequence)
Habitable ecosphere radius: 1.288 AU

Planets present at:
1	  0.344 AU	no atmosphere
2	  0.496 AU	no atmosphere
3	  0.689 AU	no atmosphere
4	  1.059 AU	greenhouse
5	  1.405 AU	gas giant
6	  2.592 AU	gas giant
7	  5.382 AU	gas giant
8	 12.929 AU	gas giant
9	 18.973 AU	no atmosphere
10	 24.650 AU	no atmosphere
11	 31.839 AU	gas giant
12	 49.562 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.344	AU
   Mass:			0.346	Earth masses
   Equatorial radius:		4520.3	km
   Density:			5.338	grams/cc
   Eccentricity of orbit:	0.247
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		256.18	degrees Celcius
   Normal daytime temperature:	472.37	degrees Celcius
   Normal night temperature:	-160.23	degrees Celcius
   Maximum temperature:   	476.80	degrees Celcius
   Minimum temperature:   	-176.58	degrees Celcius
   Escape Velocity:		7.81	km/sec
   Molecular weight retained:	13.02 and above
   Surface acceleration:	674.30	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.072
   Length of year:		70.06	days
   Length of day:		1016.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.496	AU
   Mass:			0.131	Earth masses
   Equatorial radius:		3279.9	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		166.67	degrees Celcius
   Maximum temperature:   	368.78	degrees Celcius
   Minimum temperature:   	-213.15	degrees Celcius
   Escape Velocity:		5.64	km/sec
   Molecular weight retained:	24.94 and above
   Surface acceleration:	485.25	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.084
   Length of year:		120.97	days
   Length of day:		2903.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.689	AU
   Mass:			0.129	Earth masses
   Equatorial radius:		3260.6	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		102.34	degrees Celcius
   Maximum temperature:   	288.95	degrees Celcius
   Minimum temperature:   	-224.96	degrees Celcius
   Escape Velocity:		5.61	km/sec
   Molecular weight retained:	25.24 and above
   Surface acceleration:	482.36	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.059
   Length of year:		198.42	days
   Length of day:		4762.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.059	AU
   Mass:			0.380	Earth masses
   Equatorial radius:		4664.2	km
   Density:			5.344	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		0.71	Earth gees
   Surface pressure:		12.795	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		69.85	degrees Celcius
   Maximum temperature:   	79.95	degrees Celcius
   Minimum temperature:   	59.20	degrees Celcius
   Escape Velocity:		8.06	km/sec
   Molecular weight retained:	12.22 and above
   Surface acceleration:	696.54	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.564
   Length of year:		377.61	days
   Length of day:		20.21	hours
   Boiling point of water:	186.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 160
				Mercury      melts at -39   boils at 503
				Water        melts at 0     boils at 187
				Francium     melts at 27    boils at 897
				Cesium       melts at 28    boils at 932
				Gallium      melts at 30    boils at 3023
				Rubidium     melts at 39    boils at 911
				Phosphorus   melts at 44    boils at 409
				Potassium    melts at 63    boils at 1006
   gasses in atmosphere:
				Nitrogen         99.3%  PP 12709.4 mb
				CarbonDioxide     0.3%  PP   32.4 mb
				Methane           0.1%  PP    7.9 mb
				Ammonia           0.1%  PP    9.3 mb
				Ozone             0.3%  PP   33.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.405	AU
   Mass:			8.596	Earth masses
   Equatorial radius:		19984.9	km
   Density:			1.537	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		18.52	km/sec
   Molecular weight retained:	2.31 and above
   Surface acceleration:	858.29	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.522
   Length of year:		577.05	days
   Length of day:		13.96	hours


Planet 6	*gas giant*
   Distance from primary:	2.592	AU
   Mass:			11.950	Earth masses
   Equatorial radius:		23152.7	km
   Density:			1.374	grams/cc
   Eccentricity of orbit:	0.174
   Escape Velocity:		20.29	km/sec
   Molecular weight retained:	1.93 and above
   Surface acceleration:	888.99	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.501
   Length of year:		1446.63	days
   Length of day:		13.71	hours


Planet 7	*gas giant*
   Distance from primary:	5.382	AU
   Mass:			960.350	Earth masses
   Equatorial radius:		88448.3	km
   Density:			1.980	grams/cc
   Eccentricity of orbit:	0.093
   Escape Velocity:		93.06	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4895.42	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.464
   Length of year:		4322.76	days
   Length of day:		5.84	hours


Planet 8	*gas giant*
   Distance from primary:	12.929	AU
   Mass:			515.397	Earth masses
   Equatorial radius:		79354.6	km
   Density:			1.472	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		71.97	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3263.90	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.511
   Length of year:		16103.45	days
   Length of day:		7.15	hours


Planet 9	
   Distance from primary:	18.973	AU
   Mass:			1/110.9	Earth masses
   Equatorial radius:		1804.1	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-204.51	degrees Celcius
   Normal daytime temperature:	-191.81	degrees Celcius
   Normal night temperature:	-217.15	degrees Celcius
   Maximum temperature:   	-176.48	degrees Celcius
   Minimum temperature:   	-232.73	degrees Celcius
   Escape Velocity:		2.00	km/sec
   Molecular weight retained:	199.16 and above
   Surface acceleration:	110.46	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.210
   Length of year:		28648.23	days
   Length of day:		45.60	hours
   Boiling point of water:	-55.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	9.09


Planet 10	
   Distance from primary:	24.650	AU
   Mass:			0.222	Earth masses
   Equatorial radius:		5220.6	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-211.17	degrees Celcius
   Normal daytime temperature:	-203.92	degrees Celcius
   Normal night temperature:	-218.37	degrees Celcius
   Maximum temperature:   	-187.21	degrees Celcius
   Minimum temperature:   	-235.97	degrees Celcius
   Escape Velocity:		5.83	km/sec
   Molecular weight retained:	23.39 and above
   Surface acceleration:	325.11	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.138
   Length of year:		42424.40	days
   Length of day:		26.58	hours
   Boiling point of water:	-49.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 11	*gas giant*
   Distance from primary:	31.839	AU
   Mass:			14.611	Earth masses
   Equatorial radius:		30258.1	km
   Density:			0.753	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		19.62	km/sec
   Molecular weight retained:	2.06 and above
   Surface acceleration:	636.39	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.498
   Length of year:		62274.17	days
   Length of day:		16.20	hours


Planet 12	
   Distance from primary:	49.562	AU
   Mass:			0.137	Earth masses
   Equatorial radius:		4455.5	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.98	degrees Celcius
   Normal daytime temperature:	-224.55	degrees Celcius
   Normal night temperature:	-235.29	degrees Celcius
   Maximum temperature:   	-212.10	degrees Celcius
   Minimum temperature:   	-248.17	degrees Celcius
   Escape Velocity:		4.96	km/sec
   Molecular weight retained:	32.28 and above
   Surface acceleration:	276.01	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.164
   Length of year:		120950.84	days
   Length of day:		28.85	hours
   Boiling point of water:	-60.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


