                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950489a3
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6366 K
Stellar class: F7
Age: 3.885 billion years  (2.853 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.311 AU	no atmosphere
2	  0.489 AU	no atmosphere
3	  0.567 AU	no atmosphere
4	  0.619 AU	no atmosphere
5	  1.308 AU	
6	  1.766 AU	gas giant
7	  2.896 AU	gas giant
8	  4.887 AU	gas giant
9	  7.851 AU	gas giant
10	 14.135 AU	gas giant
11	 33.206 AU	gas giant



Planet 1	
   Distance from primary:	0.311	AU
   Mass:			0.156	Earth masses
   Equatorial radius:		3474.3	km
   Density:			5.300	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		284.47	degrees Celcius
   Normal daytime temperature:	508.47	degrees Celcius
   Normal night temperature:	-170.09	degrees Celcius
   Maximum temperature:   	511.70	degrees Celcius
   Minimum temperature:   	-181.94	degrees Celcius
   Escape Velocity:		5.98	km/sec
   Molecular weight retained:	22.20 and above
   Surface acceleration:	514.59	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.058
   Length of year:		60.27	days
   Length of day:		1446.49	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.489	AU
   Mass:			0.018	Earth masses
   Equatorial radius:		1705.8	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		168.00	degrees Celcius
   Maximum temperature:   	370.46	degrees Celcius
   Minimum temperature:   	-212.90	degrees Celcius
   Escape Velocity:		2.92	km/sec
   Molecular weight retained:	92.81 and above
   Surface acceleration:	250.70	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.088
   Length of year:		118.75	days
   Length of day:		2850.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.567	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1422.6	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		138.48	degrees Celcius
   Maximum temperature:   	333.90	degrees Celcius
   Minimum temperature:   	-218.80	degrees Celcius
   Escape Velocity:		2.44	km/sec
   Molecular weight retained:	133.54 and above
   Surface acceleration:	208.93	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.071
   Length of year:		148.32	days
   Length of day:		3559.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.619	AU
   Mass:			0.587	Earth masses
   Equatorial radius:		5381.0	km
   Density:			5.377	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		122.06	degrees Celcius
   Maximum temperature:   	313.52	degrees Celcius
   Minimum temperature:   	-222.06	degrees Celcius
   Escape Velocity:		9.33	km/sec
   Molecular weight retained:	9.12 and above
   Surface acceleration:	808.58	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.062
   Length of year:		168.83	days
   Length of day:		4051.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	1.308	AU
   Mass:			0.976	Earth masses
   Equatorial radius:		6354.1	km
   Density:			5.430	grams/cc
   Eccentricity of orbit:	0.122
   Surface gravity:		0.98	Earth gees
   Surface pressure:		0.845	Earth atmospheres
   Surface temperature:		17.25	degrees Celcius
   Normal daytime temperature:	22.07	degrees Celcius
   Normal night temperature:	12.14	degrees Celcius
   Maximum temperature:   	45.90	degrees Celcius
   Minimum temperature:   	-13.06	degrees Celcius
   Escape Velocity:		11.07	km/sec
   Molecular weight retained:	6.48 and above
   Surface acceleration:	964.28	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.279
   Length of year:		519.30	days
   Length of day:		15.61	hours
   Boiling point of water:	95.4	degrees Celcius
   Hydrosphere percentage:	61.97
   Cloud cover percentage:	51.81
   Ice cover percentage:	1.26
   liquids at surface:
				Ethanol      melts at -114  boils at 74
				Mercury      melts at -39   boils at 349
				Bromine      melts at -7    boils at 55
				Water        melts at 0     boils at 95
   gasses in atmosphere:
				Oxygen           26.4%  PP  223.5 mb
				Nitrogen         73.4%  PP  620.4 mb


Planet 6	*gas giant*
   Distance from primary:	1.766	AU
   Mass:			19.297	Earth masses
   Equatorial radius:		25797.7	km
   Density:			1.604	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		24.42	km/sec
   Molecular weight retained:	1.33 and above
   Surface acceleration:	1156.27	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.506
   Length of year:		814.17	days
   Length of day:		12.02	hours


Planet 7	*gas giant*
   Distance from primary:	2.896	AU
   Mass:			16.699	Earth masses
   Equatorial radius:		25773.2	km
   Density:			1.392	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		22.73	km/sec
   Molecular weight retained:	1.54 and above
   Surface acceleration:	1002.52	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.529
   Length of year:		1709.72	days
   Length of day:		12.91	hours


Planet 8	*gas giant*
   Distance from primary:	4.887	AU
   Mass:			32.312	Earth masses
   Equatorial radius:		32637.8	km
   Density:			1.326	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		28.10	km/sec
   Molecular weight retained:	1.01 and above
   Surface acceleration:	1209.64	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.452
   Length of year:		3748.62	days
   Length of day:		11.75	hours


Planet 9	*gas giant*
   Distance from primary:	7.851	AU
   Mass:			234.818	Earth masses
   Equatorial radius:		60549.8	km
   Density:			1.509	grams/cc
   Eccentricity of orbit:	0.080
   Escape Velocity:		55.62	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2554.14	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.482
   Length of year:		7631.14	days
   Length of day:		8.09	hours


Planet 10	*gas giant*
   Distance from primary:	14.135	AU
   Mass:			446.505	Earth masses
   Equatorial radius:		76699.8	km
   Density:			1.412	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		68.14	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3026.75	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.466
   Length of year:		18428.31	days
   Length of day:		7.43	hours


Planet 11	*gas giant*
   Distance from primary:	33.206	AU
   Mass:			12.804	Earth masses
   Equatorial radius:		29228.8	km
   Density:			0.732	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		18.69	km/sec
   Molecular weight retained:	2.27 and above
   Surface acceleration:	597.65	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.526
   Length of year:		66394.76	days
   Length of day:		16.72	hours


