                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ce1
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6134 K
Stellar class: F9
Age: 5.962 billion years  (1.206 billion left on main sequence)
Habitable ecosphere radius: 1.233 AU

Planets present at:
1	  0.328 AU	no atmosphere
2	  0.409 AU	no atmosphere
3	  0.487 AU	no atmosphere
4	  0.661 AU	no atmosphere
5	  0.757 AU	greenhouse
6	  1.290 AU	
7	  2.680 AU	gas giant
8	  5.688 AU	gas giant
9	 10.093 AU	gas giant
10	 17.211 AU	gas giant
11	 38.920 AU	no atmosphere
12	 42.727 AU	gas giant
13	 47.648 AU	no atmosphere



Planet 1	
   Distance from primary:	0.328	AU
   Mass:			0.046	Earth masses
   Equatorial radius:		2322.0	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		257.39	degrees Celcius
   Normal daytime temperature:	475.87	degrees Celcius
   Normal night temperature:	-177.54	degrees Celcius
   Maximum temperature:   	479.09	degrees Celcius
   Minimum temperature:   	-188.87	degrees Celcius
   Escape Velocity:		3.99	km/sec
   Molecular weight retained:	49.98 and above
   Surface acceleration:	341.98	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.074
   Length of year:		65.66	days
   Length of day:		1575.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.409	AU
   Mass:			0.204	Earth masses
   Equatorial radius:		3797.6	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.11	degrees Celcius
   Maximum temperature:   	410.74	degrees Celcius
   Minimum temperature:   	-203.78	degrees Celcius
   Escape Velocity:		6.54	km/sec
   Molecular weight retained:	18.54 and above
   Surface acceleration:	563.60	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.081
   Length of year:		91.42	days
   Length of day:		2194.15	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.487	AU
   Mass:			1/423.5	Earth masses
   Equatorial radius:		862.6	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		164.14	degrees Celcius
   Maximum temperature:   	365.71	degrees Celcius
   Minimum temperature:   	-213.50	degrees Celcius
   Escape Velocity:		1.48	km/sec
   Molecular weight retained:	363.60 and above
   Surface acceleration:	126.55	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.059
   Length of year:		118.73	days
   Length of day:		2849.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.661	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1646.7	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		102.40	degrees Celcius
   Maximum temperature:   	288.99	degrees Celcius
   Minimum temperature:   	-224.88	degrees Celcius
   Escape Velocity:		2.82	km/sec
   Molecular weight retained:	99.61 and above
   Surface acceleration:	241.98	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.054
   Length of year:		188.18	days
   Length of day:		4516.38	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.757	AU
   Mass:			1.121	Earth masses
   Equatorial radius:		6646.0	km
   Density:			5.448	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		1.03	Earth gees
   Surface pressure:		121.845	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		505.77	degrees Celcius
   Maximum temperature:   	509.77	degrees Celcius
   Minimum temperature:   	498.84	degrees Celcius
   Escape Velocity:		11.60	km/sec
   Molecular weight retained:	5.90 and above
   Surface acceleration:	1011.92	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.484
   Length of year:		230.54	days
   Length of day:		24.60	hours
   Boiling point of water:	305.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1199
				Cesium       melts at 28    boils at 1242
				Gallium      melts at 30    boils at 3874
				Rubidium     melts at 39    boils at 1216
				Potassium    melts at 63    boils at 1336
				Sodium       melts at 98    boils at 1516
				Indium       melts at 157   boils at 3373
				Lithium      melts at 181   boils at 2237
				Selenium     melts at 217   boils at 1211
				Tin          melts at 232   boils at 4215
				Polonium     melts at 254   boils at 1641
				Bismuth      melts at 271   boils at 2574
				Thallium     melts at 304   boils at 2408
				Cadmium      melts at 321   boils at 1335
				Lead         melts at 328   boils at 2863
				Zinc         melts at 420   boils at 1555
				Tellurium    melts at 450   boils at 1684
   gasses in atmosphere:
				Sulfur           24.3%  PP 29554.0 mb
				Nitrogen         75.0%  PP 91419.3 mb
				Phosphorus        0.5%  PP  585.0 mb
				CarbonDioxide     0.1%  PP   67.2 mb
				Ethanol           0.1%  PP   68.5 mb


Planet 6	
   Distance from primary:	1.290	AU
   Mass:			1.617	Earth masses
   Equatorial radius:		7483.3	km
   Density:			5.505	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		1.17	Earth gees
   Surface pressure:		1.994	Earth atmospheres
   Surface temperature:		16.59	degrees Celcius
   Normal daytime temperature:	19.51	degrees Celcius
   Normal night temperature:	13.47	degrees Celcius
   Maximum temperature:   	36.71	degrees Celcius
   Minimum temperature:   	-4.67	degrees Celcius
   Escape Velocity:		13.13	km/sec
   Molecular weight retained:	4.61 and above
   Surface acceleration:	1151.29	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.332
   Length of year:		512.33	days
   Length of day:		14.29	hours
   Boiling point of water:	120.0	degrees Celcius
   Hydrosphere percentage:	63.66
   Cloud cover percentage:	49.26
   Ice cover percentage:	1.46
   liquids at surface:
				Ethanol      melts at -114  boils at 97
				Mercury      melts at -39   boils at 391
				Bromine      melts at -7    boils at 77
				Water        melts at 0     boils at 120
   gasses in atmosphere:
				Oxygen            3.8%  PP   76.1 mb
				Nitrogen         96.0%  PP 1914.6 mb
				CarbonDioxide     0.1%  PP    1.0 mb
				Ozone             0.1%  PP    1.1 mb


Planet 7	*gas giant*
   Distance from primary:	2.680	AU
   Mass:			105.357	Earth masses
   Equatorial radius:		43964.8	km
   Density:			1.769	grams/cc
   Eccentricity of orbit:	0.167
   Escape Velocity:		43.72	km/sec
   Molecular weight retained:	0.42 and above
   Surface acceleration:	2173.68	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.529
   Length of year:		1534.48	days
   Length of day:		8.77	hours


Planet 8	*gas giant*
   Distance from primary:	5.688	AU
   Mass:			281.367	Earth masses
   Equatorial radius:		62340.1	km
   Density:			1.657	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		60.00	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2887.20	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.513
   Length of year:		4743.45	days
   Length of day:		7.61	hours


Planet 9	*gas giant*
   Distance from primary:	10.093	AU
   Mass:			156.199	Earth masses
   Equatorial radius:		55077.8	km
   Density:			1.334	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		47.56	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2053.35	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.527
   Length of year:		11215.26	days
   Length of day:		9.02	hours


Planet 10	*gas giant*
   Distance from primary:	17.211	AU
   Mass:			133.332	Earth masses
   Equatorial radius:		54984.6	km
   Density:			1.144	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		43.98	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1758.70	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.489
   Length of year:		24973.43	days
   Length of day:		9.75	hours


Planet 11	
   Distance from primary:	38.920	AU
   Mass:			0.204	Earth masses
   Equatorial radius:		5079.4	km
   Density:			2.226	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-224.87	degrees Celcius
   Normal daytime temperature:	-219.16	degrees Celcius
   Normal night temperature:	-230.50	degrees Celcius
   Maximum temperature:   	-206.89	degrees Celcius
   Minimum temperature:   	-243.44	degrees Celcius
   Escape Velocity:		5.67	km/sec
   Molecular weight retained:	24.73 and above
   Surface acceleration:	315.98	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.137
   Length of year:		84936.82	days
   Length of day:		26.96	hours
   Boiling point of water:	-51.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	*gas giant*
   Distance from primary:	42.727	AU
   Mass:			0.976	Earth masses
   Equatorial radius:		14135.9	km
   Density:			0.493	grams/cc
   Eccentricity of orbit:	0.070
   Escape Velocity:		7.42	km/sec
   Molecular weight retained:	14.41 and above
   Surface acceleration:	194.82	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.517
   Length of year:		97699.64	days
   Length of day:		29.28	hours


Planet 13	
   Distance from primary:	47.648	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		2484.4	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.04	degrees Celcius
   Normal daytime temperature:	-223.06	degrees Celcius
   Normal night temperature:	-236.88	degrees Celcius
   Maximum temperature:   	-212.43	degrees Celcius
   Minimum temperature:   	-247.76	degrees Celcius
   Escape Velocity:		2.75	km/sec
   Molecular weight retained:	104.81 and above
   Surface acceleration:	152.42	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.158
   Length of year:		115056.63	days
   Length of day:		38.82	hours
   Boiling point of water:	-85.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


