                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047da7
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6127 K
Stellar class: F9
Age: 2.300 billion years  (4.841 billion left on main sequence)
Habitable ecosphere radius: 1.236 AU

Planets present at:
1	  0.371 AU	no atmosphere
2	  0.396 AU	no atmosphere
3	  0.523 AU	no atmosphere
4	  0.692 AU	no atmosphere
5	  0.891 AU	greenhouse
6	  1.290 AU	
7	  2.125 AU	gas giant
8	  3.921 AU	cold
9	  5.076 AU	gas giant
10	 10.886 AU	gas giant
11	 22.778 AU	gas giant
12	 41.847 AU	gas giant



Planet 1	
   Distance from primary:	0.371	AU
   Mass:			1/126.6	Earth masses
   Equatorial radius:		1289.7	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		227.25	degrees Celcius
   Maximum temperature:   	442.61	degrees Celcius
   Minimum temperature:   	-197.44	degrees Celcius
   Escape Velocity:		2.21	km/sec
   Molecular weight retained:	162.53 and above
   Surface acceleration:	189.35	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.064
   Length of year:		79.13	days
   Length of day:		1899.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.396	AU
   Mass:			0.210	Earth masses
   Equatorial radius:		3835.2	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		210.96	degrees Celcius
   Maximum temperature:   	422.88	degrees Celcius
   Minimum temperature:   	-201.91	degrees Celcius
   Escape Velocity:		6.61	km/sec
   Molecular weight retained:	18.18 and above
   Surface acceleration:	569.32	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.067
   Length of year:		87.18	days
   Length of day:		2092.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.523	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1940.2	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.27	degrees Celcius
   Maximum temperature:   	345.96	degrees Celcius
   Minimum temperature:   	-214.37	degrees Celcius
   Escape Velocity:		3.33	km/sec
   Molecular weight retained:	71.69 and above
   Surface acceleration:	285.36	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.068
   Length of year:		132.09	days
   Length of day:		2508.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.692	AU
   Mass:			0.101	Earth masses
   Equatorial radius:		3010.4	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		93.49	degrees Celcius
   Maximum temperature:   	277.79	degrees Celcius
   Minimum temperature:   	-225.93	degrees Celcius
   Escape Velocity:		5.17	km/sec
   Molecular weight retained:	29.64 and above
   Surface acceleration:	444.75	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.063
   Length of year:		201.45	days
   Length of day:		4834.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.891	AU
   Mass:			1.638	Earth masses
   Equatorial radius:		7514.3	km
   Density:			5.507	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		1.18	Earth gees
   Surface pressure:		287.069	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		559.75	degrees Celcius
   Maximum temperature:   	561.88	degrees Celcius
   Minimum temperature:   	554.53	degrees Celcius
   Escape Velocity:		13.18	km/sec
   Molecular weight retained:	4.57 and above
   Surface acceleration:	1156.53	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.462
   Length of year:		294.23	days
   Length of day:		14.70	hours
   Boiling point of water:	367.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1359
				Cesium       melts at 28    boils at 1407
				Gallium      melts at 30    boils at 4325
				Rubidium     melts at 39    boils at 1378
				Potassium    melts at 63    boils at 1512
				Sodium       melts at 98    boils at 1711
				Indium       melts at 157   boils at 3770
				Lithium      melts at 181   boils at 2510
				Selenium     melts at 217   boils at 1373
				Tin          melts at 232   boils at 4703
				Polonium     melts at 254   boils at 1849
				Bismuth      melts at 271   boils at 2883
				Thallium     melts at 304   boils at 2699
				Cadmium      melts at 321   boils at 1510
				Lead         melts at 328   boils at 3204
				Zinc         melts at 420   boils at 1754
				Tellurium    melts at 450   boils at 1897
   gasses in atmosphere:
				Sulfur           18.7%  PP 53584.0 mb
				Nitrogen         80.8%  PP 231873.1 mb
				Phosphorus        0.4%  PP 1071.5 mb


Planet 6	
   Distance from primary:	1.290	AU
   Mass:			0.555	Earth masses
   Equatorial radius:		5283.1	km
   Density:			5.372	grams/cc
   Eccentricity of orbit:	0.143
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.315	Earth atmospheres
   Surface temperature:		10.27	degrees Celcius
   Normal daytime temperature:	18.35	degrees Celcius
   Normal night temperature:	1.75	degrees Celcius
   Maximum temperature:   	46.11	degrees Celcius
   Minimum temperature:   	-27.52	degrees Celcius
   Escape Velocity:		9.15	km/sec
   Molecular weight retained:	9.47 and above
   Surface acceleration:	793.16	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.237
   Length of year:		512.04	days
   Length of day:		17.21	hours
   Boiling point of water:	70.7	degrees Celcius
   Hydrosphere percentage:	58.80
   Cloud cover percentage:	28.65
   Ice cover percentage:	3.22
   liquids at surface:
				Ethanol      melts at -114  boils at 51
				Mercury      melts at -39   boils at 307
				Bromine      melts at -7    boils at 33
				Water        melts at 0     boils at 71
   gasses in atmosphere:
				Oxygen           53.6%  PP  169.1 mb
				Nitrogen         46.2%  PP  145.7 mb


Planet 7	*gas giant*
   Distance from primary:	2.125	AU
   Mass:			53.475	Earth masses
   Equatorial radius:		35377.3	km
   Density:			1.723	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		34.72	km/sec
   Molecular weight retained:	0.66 and above
   Surface acceleration:	1703.89	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.543
   Length of year:		1083.16	days
   Length of day:		9.90	hours


Planet 8	
   Distance from primary:	3.921	AU
   Mass:			0.822	Earth masses
   Equatorial radius:		6008.1	km
   Density:			5.410	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.541	Earth atmospheres
   Surface temperature:		-129.46	degrees Celcius
   Normal daytime temperature:	-126.46	degrees Celcius
   Normal night temperature:	-132.62	degrees Celcius
   Maximum temperature:   	-108.71	degrees Celcius
   Minimum temperature:   	-151.99	degrees Celcius
   Escape Velocity:		10.45	km/sec
   Molecular weight retained:	7.27 and above
   Surface acceleration:	908.40	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.561
   Length of year:		2714.37	days
   Length of day:		15.90	hours
   Boiling point of water:	83.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	79.02
   liquids at surface:
				Ozone        melts at -193  boils at -119
   gasses in atmosphere:
				Oxygen           22.1%  PP  119.4 mb
				Nitrogen         77.9%  PP  421.5 mb


Planet 9	*gas giant*
   Distance from primary:	5.076	AU
   Mass:			190.826	Earth masses
   Equatorial radius:		55128.9	km
   Density:			1.625	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		52.54	km/sec
   Molecular weight retained:	0.29 and above
   Surface acceleration:	2503.91	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.494
   Length of year:		3997.96	days
   Length of day:		8.17	hours


Planet 10	*gas giant*
   Distance from primary:	10.886	AU
   Mass:			353.645	Earth masses
   Equatorial radius:		70328.9	km
   Density:			1.451	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		63.33	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2851.27	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.481
   Length of year:		12551.34	days
   Length of day:		7.65	hours


Planet 11	*gas giant*
   Distance from primary:	22.778	AU
   Mass:			149.655	Earth masses
   Equatorial radius:		58200.3	km
   Density:			1.083	grams/cc
   Eccentricity of orbit:	0.115
   Escape Velocity:		45.29	km/sec
   Molecular weight retained:	0.39 and above
   Surface acceleration:	1761.90	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.549
   Length of year:		38001.75	days
   Length of day:		9.74	hours


Planet 12	*gas giant*
   Distance from primary:	41.847	AU
   Mass:			0.447	Earth masses
   Equatorial radius:		11232.9	km
   Density:			0.450	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		5.63	km/sec
   Molecular weight retained:	25.02 and above
   Surface acceleration:	141.22	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.470
   Length of year:		94649.85	days
   Length of day:		34.39	hours


