                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950482fb
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6355 K
Stellar class: F7
Age: 3.103 billion years  (3.856 billion left on main sequence)
Habitable ecosphere radius: 1.257 AU

Planets present at:
1	  0.429 AU	no atmosphere
2	  0.568 AU	no atmosphere
3	  0.931 AU	greenhouse
4	  1.791 AU	gas giant
5	  2.041 AU	cold
6	  3.060 AU	no atmosphere
7	  4.657 AU	gas giant
8	  8.772 AU	gas giant
9	 14.360 AU	gas giant
10	 21.285 AU	gas giant
11	 44.771 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.429	AU
   Mass:			0.145	Earth masses
   Equatorial radius:		3396.6	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.226
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		194.55	degrees Celcius
   Normal daytime temperature:	398.59	degrees Celcius
   Normal night temperature:	-186.04	degrees Celcius
   Maximum temperature:   	402.42	degrees Celcius
   Minimum temperature:   	-198.50	degrees Celcius
   Escape Velocity:		5.84	km/sec
   Molecular weight retained:	23.24 and above
   Surface acceleration:	502.85	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.079
   Length of year:		97.80	days
   Length of day:		1480.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.568	AU
   Mass:			0.284	Earth masses
   Equatorial radius:		4238.0	km
   Density:			5.326	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		135.32	degrees Celcius
   Maximum temperature:   	330.03	degrees Celcius
   Minimum temperature:   	-219.48	degrees Celcius
   Escape Velocity:		7.31	km/sec
   Molecular weight retained:	14.85 and above
   Surface acceleration:	630.86	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.060
   Length of year:		149.12	days
   Length of day:		3578.84	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.931	AU
   Mass:			1.470	Earth masses
   Equatorial radius:		7257.5	km
   Density:			5.489	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		1.13	Earth gees
   Surface pressure:		182.308	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		463.74	degrees Celcius
   Maximum temperature:   	466.86	degrees Celcius
   Minimum temperature:   	458.53	degrees Celcius
   Escape Velocity:		12.71	km/sec
   Molecular weight retained:	4.91 and above
   Surface acceleration:	1113.28	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.533
   Length of year:		312.83	days
   Length of day:		15.08	hours
   Boiling point of water:	333.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1270
				Cesium       melts at 28    boils at 1316
				Gallium      melts at 30    boils at 4074
				Rubidium     melts at 39    boils at 1288
				Potassium    melts at 63    boils at 1414
				Sodium       melts at 98    boils at 1603
				Indium       melts at 157   boils at 3550
				Lithium      melts at 181   boils at 2359
				Selenium     melts at 217   boils at 1283
				Tin          melts at 232   boils at 4432
				Polonium     melts at 254   boils at 1733
				Bismuth      melts at 271   boils at 2711
				Thallium     melts at 304   boils at 2537
				Cadmium      melts at 321   boils at 1413
				Lead         melts at 328   boils at 3015
				Zinc         melts at 420   boils at 1644
				Tellurium    melts at 450   boils at 1779
   gasses in atmosphere:
				Sulfur           19.6%  PP 35694.2 mb
				Nitrogen         79.8%  PP 145539.5 mb
				Phosphorus        0.4%  PP  712.5 mb


Planet 4	*gas giant*
   Distance from primary:	1.791	AU
   Mass:			13.062	Earth masses
   Equatorial radius:		23088.6	km
   Density:			1.514	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		21.24	km/sec
   Molecular weight retained:	1.76 and above
   Surface acceleration:	977.11	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.495
   Length of year:		835.27	days
   Length of day:		13.08	hours


Planet 5	
   Distance from primary:	2.041	AU
   Mass:			0.937	Earth masses
   Equatorial radius:		6268.7	km
   Density:			5.425	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.925	Earth atmospheres
   Surface temperature:		-82.79	degrees Celcius
   Normal daytime temperature:	-79.76	degrees Celcius
   Normal night temperature:	-85.99	degrees Celcius
   Maximum temperature:   	-61.87	degrees Celcius
   Minimum temperature:   	-105.22	degrees Celcius
   Escape Velocity:		10.92	km/sec
   Molecular weight retained:	6.66 and above
   Surface acceleration:	950.43	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.667
   Length of year:		1016.35	days
   Length of day:		15.56	hours
   Boiling point of water:	97.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 77
				Chlorine     melts at -101  boils at -35
   gasses in atmosphere:
				Oxygen            2.0%  PP   18.4 mb
				Nitrogen         97.9%  PP  905.2 mb
				Ozone             0.1%  PP    0.5 mb


Planet 6	
   Distance from primary:	3.060	AU
   Mass:			0.295	Earth masses
   Equatorial radius:		4288.9	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.097
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.077	Earth atmospheres
   Surface temperature:		-114.76	degrees Celcius
   Normal daytime temperature:	-106.29	degrees Celcius
   Normal night temperature:	-123.50	degrees Celcius
   Maximum temperature:   	-84.53	degrees Celcius
   Minimum temperature:   	-146.74	degrees Celcius
   Escape Velocity:		7.40	km/sec
   Molecular weight retained:	14.49 and above
   Surface acceleration:	638.67	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.522
   Length of year:		1864.94	days
   Length of day:		18.97	hours
   Boiling point of water:	40.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	61.64
   gasses in atmosphere:
				Oxygen           99.9%  PP   77.0 mb
				Methane           0.1%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	4.657	AU
   Mass:			666.629	Earth masses
   Equatorial radius:		78725.4	km
   Density:			1.950	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		82.18	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4289.38	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.464
   Length of year:		3498.98	days
   Length of day:		6.24	hours


Planet 8	*gas giant*
   Distance from primary:	8.772	AU
   Mass:			103.370	Earth masses
   Equatorial radius:		48186.6	km
   Density:			1.318	grams/cc
   Eccentricity of orbit:	0.138
   Escape Velocity:		41.36	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1775.34	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.542
   Length of year:		9051.08	days
   Length of day:		9.70	hours


Planet 9	*gas giant*
   Distance from primary:	14.360	AU
   Mass:			0.928	Earth masses
   Equatorial radius:		12699.2	km
   Density:			0.647	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		7.63	km/sec
   Molecular weight retained:	13.62 and above
   Surface acceleration:	229.49	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.484
   Length of year:		18960.94	days
   Length of day:		26.98	hours


Planet 10	*gas giant*
   Distance from primary:	21.285	AU
   Mass:			102.207	Earth masses
   Equatorial radius:		51710.2	km
   Density:			1.055	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		39.70	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	1524.29	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.451
   Length of year:		34213.93	days
   Length of day:		10.47	hours


Planet 11	
   Distance from primary:	44.771	AU
   Mass:			0.339	Earth masses
   Equatorial radius:		5998.3	km
   Density:			2.242	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.40	degrees Celcius
   Normal daytime temperature:	-222.39	degrees Celcius
   Normal night temperature:	-232.32	degrees Celcius
   Maximum temperature:   	-206.58	degrees Celcius
   Minimum temperature:   	-248.50	degrees Celcius
   Escape Velocity:		6.72	km/sec
   Molecular weight retained:	17.60 and above
   Surface acceleration:	375.87	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.148
   Length of year:		104386.94	days
   Length of day:		24.72	hours
   Boiling point of water:	-39.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   gasses in atmosphere:
				Neon             100.0%  PP    0.3 mb


