                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048433
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6351 K
Stellar class: F7
Age: 3.851 billion years  (3.066 billion left on main sequence)
Habitable ecosphere radius: 1.261 AU

Planets present at:
1	  0.372 AU	no atmosphere
2	  0.646 AU	no atmosphere
3	  0.994 AU	greenhouse
4	  1.884 AU	cold
5	  2.744 AU	gas giant
6	  6.703 AU	gas giant
7	 10.489 AU	gas giant
8	 19.726 AU	gas giant
9	 42.467 AU	gas giant



Planet 1	
   Distance from primary:	0.372	AU
   Mass:			0.196	Earth masses
   Equatorial radius:		3747.5	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.18	degrees Celcius
   Maximum temperature:   	444.99	degrees Celcius
   Minimum temperature:   	-197.25	degrees Celcius
   Escape Velocity:		6.46	km/sec
   Molecular weight retained:	19.05 and above
   Surface acceleration:	555.98	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.082
   Length of year:		79.15	days
   Length of day:		1899.50	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.646	AU
   Mass:			0.120	Earth masses
   Equatorial radius:		3189.9	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.232
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		111.24	degrees Celcius
   Normal daytime temperature:	296.42	degrees Celcius
   Normal night temperature:	-211.35	degrees Celcius
   Maximum temperature:   	300.20	degrees Celcius
   Minimum temperature:   	-221.62	degrees Celcius
   Escape Velocity:		5.49	km/sec
   Molecular weight retained:	26.38 and above
   Surface acceleration:	471.71	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.054
   Length of year:		180.64	days
   Length of day:		2704.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	0.994	AU
   Mass:			3.217	Earth masses
   Equatorial radius:		9325.8	km
   Density:			5.659	grams/cc
   Eccentricity of orbit:	0.214
   Surface gravity:		1.50	Earth gees
   Surface pressure:		1124.978	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		672.66	degrees Celcius
   Maximum temperature:   	673.03	degrees Celcius
   Minimum temperature:   	667.86	degrees Celcius
   Escape Velocity:		16.59	km/sec
   Molecular weight retained:	2.89 and above
   Surface acceleration:	1475.02	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.589
   Length of year:		344.91	days
   Length of day:		12.75	hours
   Boiling point of water:	502.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1701
				Cesium       melts at 28    boils at 1760
				Gallium      melts at 30    boils at 5289
				Rubidium     melts at 39    boils at 1724
				Potassium    melts at 63    boils at 1886
				Sodium       melts at 98    boils at 2127
				Indium       melts at 157   boils at 4617
				Lithium      melts at 181   boils at 3094
				Selenium     melts at 217   boils at 1718
				Tin          melts at 232   boils at 5746
				Polonium     melts at 254   boils at 2294
				Bismuth      melts at 271   boils at 3545
				Thallium     melts at 304   boils at 3323
				Cadmium      melts at 321   boils at 1884
				Lead         melts at 328   boils at 3934
				Zinc         melts at 420   boils at 2179
				Tellurium    melts at 450   boils at 2352
				Antimony     melts at 631   boils at 3593
				Neptunium    melts at 640   boils at 8404
				Plutonium    melts at 641   boils at 7008
				Magnesium    melts at 649   boils at 2591
				Aluminum     melts at 660   boils at 5422
   gasses in atmosphere:
				Sulfur            0.1%  PP 1054.3 mb
				Nitrogen          0.4%  PP 4944.7 mb
				Helium           99.5%  PP 1118949.4 mb


Planet 4	
   Distance from primary:	1.884	AU
   Mass:			0.518	Earth masses
   Equatorial radius:		5164.8	km
   Density:			5.366	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.245	Earth atmospheres
   Surface temperature:		-64.86	degrees Celcius
   Normal daytime temperature:	-58.20	degrees Celcius
   Normal night temperature:	-71.84	degrees Celcius
   Maximum temperature:   	-37.15	degrees Celcius
   Minimum temperature:   	-94.25	degrees Celcius
   Escape Velocity:		8.94	km/sec
   Molecular weight retained:	9.92 and above
   Surface acceleration:	774.57	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.533
   Length of year:		900.62	days
   Length of day:		17.26	hours
   Boiling point of water:	64.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.13
   Ice cover percentage:	76.69
   liquids at surface:
				Ethanol      melts at -114  boils at 45
				Chlorine     melts at -101  boils at -56
				Ammonia      melts at -78   boils at -56
   gasses in atmosphere:
				Oxygen           11.4%  PP   27.9 mb
				Nitrogen         88.4%  PP  216.0 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.744	AU
   Mass:			65.221	Earth masses
   Equatorial radius:		38229.2	km
   Density:			1.666	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		36.89	km/sec
   Molecular weight retained:	0.58 and above
   Surface acceleration:	1779.66	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.537
   Length of year:		1582.30	days
   Length of day:		9.69	hours


Planet 6	*gas giant*
   Distance from primary:	6.703	AU
   Mass:			1723.021	Earth masses
   Equatorial radius:		107014.9	km
   Density:			2.006	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		113.32	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5999.87	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.549
   Length of year:		6028.43	days
   Length of day:		5.28	hours


Planet 7	*gas giant*
   Distance from primary:	10.489	AU
   Mass:			5.909	Earth masses
   Equatorial radius:		21220.5	km
   Density:			0.882	grams/cc
   Eccentricity of orbit:	0.097
   Escape Velocity:		14.90	km/sec
   Molecular weight retained:	3.57 and above
   Surface acceleration:	523.29	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.490
   Length of year:		11828.21	days
   Length of day:		17.87	hours


Planet 8	*gas giant*
   Distance from primary:	19.726	AU
   Mass:			87.877	Earth masses
   Equatorial radius:		49153.3	km
   Density:			1.056	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		37.76	km/sec
   Molecular weight retained:	0.56 and above
   Surface acceleration:	1450.48	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.514
   Length of year:		30500.22	days
   Length of day:		10.73	hours


Planet 9	*gas giant*
   Distance from primary:	42.467	AU
   Mass:			0.768	Earth masses
   Equatorial radius:		13149.1	km
   Density:			0.482	grams/cc
   Eccentricity of orbit:	0.111
   Escape Velocity:		6.82	km/sec
   Molecular weight retained:	17.04 and above
   Surface acceleration:	177.12	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.490
   Length of year:		96357.62	days
   Length of day:		30.71	hours


