                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048b22
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6258 K
Stellar class: F8
Age: 1.859 billion years  (4.832 billion left on main sequence)
Habitable ecosphere radius: 1.288 AU

Planets present at:
1	  0.410 AU	no atmosphere
2	  0.457 AU	no atmosphere
3	  0.654 AU	no atmosphere
4	  0.888 AU	greenhouse
5	  2.013 AU	gas giant
6	  6.093 AU	gas giant
7	  7.983 AU	no atmosphere
8	 14.349 AU	gas giant
9	 23.571 AU	gas giant
10	 30.739 AU	gas giant
11	 41.729 AU	gas giant
12	 51.506 AU	no atmosphere



Planet 1	
   Distance from primary:	0.410	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1951.0	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		211.31	degrees Celcius
   Maximum temperature:   	423.35	degrees Celcius
   Minimum temperature:   	-202.56	degrees Celcius
   Escape Velocity:		3.35	km/sec
   Molecular weight retained:	70.90 and above
   Surface acceleration:	286.95	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.076
   Length of year:		91.08	days
   Length of day:		2185.97	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.457	AU
   Mass:			0.280	Earth masses
   Equatorial radius:		4218.7	km
   Density:			5.326	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		189.02	degrees Celcius
   Maximum temperature:   	396.23	degrees Celcius
   Minimum temperature:   	-208.46	degrees Celcius
   Escape Velocity:		7.28	km/sec
   Molecular weight retained:	14.98 and above
   Surface acceleration:	627.90	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.051
   Length of year:		107.08	days
   Length of day:		2570.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.654	AU
   Mass:			0.118	Earth masses
   Equatorial radius:		3168.0	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.152
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		109.86	degrees Celcius
   Maximum temperature:   	298.46	degrees Celcius
   Minimum temperature:   	-222.98	degrees Celcius
   Escape Velocity:		5.45	km/sec
   Molecular weight retained:	26.75 and above
   Surface acceleration:	468.42	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.083
   Length of year:		183.32	days
   Length of day:		3238.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.888	AU
   Mass:			0.237	Earth masses
   Equatorial radius:		3990.7	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.60	Earth gees
   Surface pressure:		4.533	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		43.92	degrees Celcius
   Normal daytime temperature:	47.25	degrees Celcius
   Normal night temperature:	40.20	degrees Celcius
   Maximum temperature:   	59.27	degrees Celcius
   Minimum temperature:   	27.63	degrees Celcius
   Escape Velocity:		6.88	km/sec
   Molecular weight retained:	16.77 and above
   Surface acceleration:	593.02	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.591
   Length of year:		290.32	days
   Length of day:		23.83	hours
   Boiling point of water:	146.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 123
				Mercury      melts at -39   boils at 436
				Bromine      melts at -7    boils at 101
				Water        melts at 0     boils at 147
				Francium     melts at 27    boils at 796
				Cesium       melts at 28    boils at 828
				Gallium      melts at 30    boils at 2739
				Rubidium     melts at 39    boils at 809
   gasses in atmosphere:
				CarbonDioxide    46.4%  PP 2102.9 mb
				Ammonia           0.9%  PP   39.2 mb
				Ozone            49.1%  PP 2224.0 mb
				Argon             0.1%  PP    2.9 mb
				Neon              0.4%  PP   17.5 mb
				Krypton           2.9%  PP  131.3 mb
				Xenon             0.3%  PP   15.5 mb


Planet 5	*gas giant*
   Distance from primary:	2.013	AU
   Mass:			305.200	Earth masses
   Equatorial radius:		58329.7	km
   Density:			2.194	grams/cc
   Eccentricity of orbit:	0.334
   Escape Velocity:		64.60	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3577.21	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.473
   Length of year:		989.34	days
   Length of day:		6.83	hours


Planet 6	*gas giant*
   Distance from primary:	6.093	AU
   Mass:			1034.563	Earth masses
   Equatorial radius:		91330.0	km
   Density:			1.938	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		95.05	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4946.17	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.511
   Length of year:		5206.40	days
   Length of day:		5.81	hours


Planet 7	
   Distance from primary:	7.983	AU
   Mass:			0.120	Earth masses
   Equatorial radius:		4265.5	km
   Density:			2.214	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.010	Earth atmospheres
   Surface temperature:		-168.35	degrees Celcius
   Normal daytime temperature:	-156.11	degrees Celcius
   Normal night temperature:	-180.71	degrees Celcius
   Maximum temperature:   	-137.42	degrees Celcius
   Minimum temperature:   	-200.40	degrees Celcius
   Escape Velocity:		4.75	km/sec
   Molecular weight retained:	35.26 and above
   Surface acceleration:	263.92	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.248
   Length of year:		7819.02	days
   Length of day:		29.50	hours
   Boiling point of water:	5.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	19.42
   liquids at surface:
				Ozone        melts at -193  boils at -152
   gasses in atmosphere:
				Argon            100.0%  PP    9.8 mb


Planet 8	*gas giant*
   Distance from primary:	14.349	AU
   Mass:			128.504	Earth masses
   Equatorial radius:		53383.9	km
   Density:			1.205	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		43.82	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1798.19	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.526
   Length of year:		18839.39	days
   Length of day:		9.64	hours


Planet 9	*gas giant*
   Distance from primary:	23.571	AU
   Mass:			3.261	Earth masses
   Equatorial radius:		19055.4	km
   Density:			0.673	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		11.68	km/sec
   Molecular weight retained:	5.82 and above
   Surface acceleration:	358.19	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.474
   Length of year:		39671.35	days
   Length of day:		21.60	hours


Planet 10	*gas giant*
   Distance from primary:	30.739	AU
   Mass:			0.567	Earth masses
   Equatorial radius:		11694.6	km
   Density:			0.506	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		6.22	km/sec
   Molecular weight retained:	20.53 and above
   Surface acceleration:	165.30	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.534
   Length of year:		59079.10	days
   Length of day:		31.79	hours


Planet 11	*gas giant*
   Distance from primary:	41.729	AU
   Mass:			0.997	Earth masses
   Equatorial radius:		14143.4	km
   Density:			0.503	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		7.50	km/sec
   Molecular weight retained:	14.12 and above
   Surface acceleration:	198.75	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.484
   Length of year:		93444.10	days
   Length of day:		28.99	hours


Planet 12	
   Distance from primary:	51.506	AU
   Mass:			1/378.7	Earth masses
   Equatorial radius:		1198.6	km
   Density:			2.188	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.07	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.65	degrees Celcius
   Normal daytime temperature:	-221.38	degrees Celcius
   Normal night temperature:	-239.68	degrees Celcius
   Maximum temperature:   	-211.17	degrees Celcius
   Minimum temperature:   	-249.73	degrees Celcius
   Escape Velocity:		1.33	km/sec
   Molecular weight retained:	451.77 and above
   Surface acceleration:	73.30	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.148
   Length of year:		128141.38	days
   Length of day:		55.98	hours
   Boiling point of water:	-113.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.02


