                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048863
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6385 K
Stellar class: F7
Age: 5.191 billion years  (1.588 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.381 AU	no atmosphere
2	  0.858 AU	greenhouse
3	  1.186 AU	greenhouse
4	  2.940 AU	gas giant
5	  5.323 AU	cold
6	  6.867 AU	gas giant
7	 13.216 AU	gas giant
8	 27.022 AU	gas giant
9	 43.893 AU	gas giant
10	 51.601 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.381	AU
   Mass:			0.273	Earth masses
   Equatorial radius:		4180.8	km
   Density:			5.324	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.63	degrees Celcius
   Normal daytime temperature:	441.99	degrees Celcius
   Normal night temperature:	-182.41	degrees Celcius
   Maximum temperature:   	445.29	degrees Celcius
   Minimum temperature:   	-193.53	degrees Celcius
   Escape Velocity:		7.21	km/sec
   Molecular weight retained:	15.26 and above
   Surface acceleration:	622.09	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.058
   Length of year:		81.78	days
   Length of day:		1592.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.858	AU
   Mass:			0.593	Earth masses
   Equatorial radius:		5397.7	km
   Density:			5.378	grams/cc
   Eccentricity of orbit:	0.258
   Surface gravity:		0.83	Earth gees
   Surface pressure:		30.874	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		217.45	degrees Celcius
   Maximum temperature:   	225.67	degrees Celcius
   Minimum temperature:   	208.41	degrees Celcius
   Escape Velocity:		9.36	km/sec
   Molecular weight retained:	9.06 and above
   Surface acceleration:	811.22	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.503
   Length of year:		275.89	days
   Length of day:		23.33	hours
   Boiling point of water:	226.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 571
				Francium     melts at 27    boils at 999
				Cesium       melts at 28    boils at 1037
				Gallium      melts at 30    boils at 3311
				Rubidium     melts at 39    boils at 1014
				Phosphorus   melts at 44    boils at 468
				Potassium    melts at 63    boils at 1118
				Sodium       melts at 98    boils at 1273
				Sulfur       melts at 113   boils at 688
				Indium       melts at 157   boils at 2878
				Lithium      melts at 181   boils at 1896
				Selenium     melts at 217   boils at 1010
   gasses in atmosphere:
				Nitrogen         99.5%  PP 30730.1 mb
				CarbonDioxide     0.1%  PP   33.3 mb
				Ozone             0.1%  PP   32.1 mb
				Ethanol           0.1%  PP   34.1 mb


Planet 3	
   Distance from primary:	1.186	AU
   Mass:			1.701	Earth masses
   Equatorial radius:		7606.6	km
   Density:			5.514	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		1.19	Earth gees
   Surface pressure:		306.241	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		407.96	degrees Celcius
   Maximum temperature:   	410.58	degrees Celcius
   Minimum temperature:   	403.78	degrees Celcius
   Escape Velocity:		13.35	km/sec
   Molecular weight retained:	4.45 and above
   Surface acceleration:	1172.18	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.618
   Length of year:		448.66	days
   Length of day:		14.24	hours
   Boiling point of water:	373.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1373
				Cesium       melts at 28    boils at 1421
				Gallium      melts at 30    boils at 4363
				Rubidium     melts at 39    boils at 1392
				Potassium    melts at 63    boils at 1526
				Sodium       melts at 98    boils at 1727
				Sulfur       melts at 113   boils at 971
				Indium       melts at 157   boils at 3803
				Lithium      melts at 181   boils at 2533
				Selenium     melts at 217   boils at 1386
				Tin          melts at 232   boils at 4744
				Polonium     melts at 254   boils at 1866
				Bismuth      melts at 271   boils at 2909
				Thallium     melts at 304   boils at 2724
				Cadmium      melts at 321   boils at 1525
				Lead         melts at 328   boils at 3233
   gasses in atmosphere:
				Nitrogen         99.3%  PP 304063.9 mb
				Phosphorus        0.5%  PP 1497.9 mb
				CarbonDioxide     0.1%  PP  160.0 mb
				Ethanol           0.1%  PP  161.8 mb


Planet 4	*gas giant*
   Distance from primary:	2.940	AU
   Mass:			206.011	Earth masses
   Equatorial radius:		53718.7	km
   Density:			1.896	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		55.31	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2846.95	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.491
   Length of year:		1750.34	days
   Length of day:		7.66	hours


Planet 5	
   Distance from primary:	5.323	AU
   Mass:			0.537	Earth masses
   Equatorial radius:		6968.5	km
   Density:			2.263	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.199	Earth atmospheres
   Surface temperature:		-140.64	degrees Celcius
   Normal daytime temperature:	-134.73	degrees Celcius
   Normal night temperature:	-146.90	degrees Celcius
   Maximum temperature:   	-117.28	degrees Celcius
   Minimum temperature:   	-165.81	degrees Celcius
   Escape Velocity:		7.84	km/sec
   Molecular weight retained:	12.93 and above
   Surface acceleration:	440.64	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.358
   Length of year:		4264.68	days
   Length of day:		22.83	hours
   Boiling point of water:	60.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	33.11
   liquids at surface:
				Ozone        melts at -193  boils at -129
   gasses in atmosphere:
				Oxygen            6.6%  PP   13.2 mb
				Nitrogen         93.3%  PP  185.6 mb
				Methane           0.1%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	6.867	AU
   Mass:			333.133	Earth masses
   Equatorial radius:		66328.9	km
   Density:			1.629	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		63.29	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	3019.62	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.524
   Length of year:		6246.18	days
   Length of day:		7.44	hours


Planet 7	*gas giant*
   Distance from primary:	13.216	AU
   Mass:			484.339	Earth masses
   Equatorial radius:		78127.2	km
   Density:			1.449	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		70.32	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3164.34	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.460
   Length of year:		16673.82	days
   Length of day:		7.27	hours


Planet 8	*gas giant*
   Distance from primary:	27.022	AU
   Mass:			10.832	Earth masses
   Equatorial radius:		27372.0	km
   Density:			0.754	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		17.77	km/sec
   Molecular weight retained:	2.52 and above
   Surface acceleration:	576.54	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.455
   Length of year:		48777.95	days
   Length of day:		17.02	hours


Planet 9	*gas giant*
   Distance from primary:	43.893	AU
   Mass:			0.631	Earth masses
   Equatorial radius:		12436.0	km
   Density:			0.468	grams/cc
   Eccentricity of orbit:	0.044
   Escape Velocity:		6.36	km/sec
   Molecular weight retained:	19.63 and above
   Surface acceleration:	162.62	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.547
   Length of year:		100980.77	days
   Length of day:		32.05	hours


Planet 10	
   Distance from primary:	51.601	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2716.5	km
   Density:			2.197	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.90	degrees Celcius
   Normal daytime temperature:	-224.31	degrees Celcius
   Normal night temperature:	-237.35	degrees Celcius
   Maximum temperature:   	-208.70	degrees Celcius
   Minimum temperature:   	-252.57	degrees Celcius
   Escape Velocity:		3.01	km/sec
   Molecular weight retained:	87.59 and above
   Surface acceleration:	166.81	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.152
   Length of year:		128718.70	days
   Length of day:		37.11	hours
   Boiling point of water:	-84.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


