                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048718
Stellar mass: 1.10 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6228 K
Stellar class: F8
Age: 5.864 billion years  (0.958 billion left on main sequence)
Habitable ecosphere radius: 1.272 AU

Planets present at:
1	  0.342 AU	no atmosphere
2	  0.754 AU	no atmosphere
3	  0.940 AU	greenhouse
4	  1.306 AU	
5	  2.716 AU	gas giant
6	  4.662 AU	gas giant
7	  6.621 AU	gas giant
8	  9.986 AU	gas giant
9	 19.274 AU	gas giant
10	 38.288 AU	gas giant
11	 46.810 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.342	AU
   Mass:			0.320	Earth masses
   Equatorial radius:		4405.6	km
   Density:			5.333	grams/cc
   Eccentricity of orbit:	0.108
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.46	degrees Celcius
   Normal daytime temperature:	472.90	degrees Celcius
   Normal night temperature:	-172.33	degrees Celcius
   Maximum temperature:   	476.43	degrees Celcius
   Minimum temperature:   	-184.90	degrees Celcius
   Escape Velocity:		7.61	km/sec
   Molecular weight retained:	13.72 and above
   Surface acceleration:	656.62	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.068
   Length of year:		69.49	days
   Length of day:		1343.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.754	AU
   Mass:			0.219	Earth masses
   Equatorial radius:		3889.7	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		82.69	degrees Celcius
   Maximum temperature:   	264.21	degrees Celcius
   Minimum temperature:   	-227.26	degrees Celcius
   Escape Velocity:		6.70	km/sec
   Molecular weight retained:	17.67 and above
   Surface acceleration:	577.62	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.070
   Length of year:		227.49	days
   Length of day:		5459.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	0.940	AU
   Mass:			0.552	Earth masses
   Equatorial radius:		5272.2	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.81	Earth gees
   Surface pressure:		32.476	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		177.10	degrees Celcius
   Maximum temperature:   	184.08	degrees Celcius
   Minimum temperature:   	169.54	degrees Celcius
   Escape Velocity:		9.14	km/sec
   Molecular weight retained:	9.51 and above
   Surface acceleration:	791.44	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.583
   Length of year:		316.51	days
   Length of day:		21.10	hours
   Boiling point of water:	229.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 575
				Francium     melts at 27    boils at 1006
				Cesium       melts at 28    boils at 1043
				Gallium      melts at 30    boils at 3329
				Rubidium     melts at 39    boils at 1020
				Phosphorus   melts at 44    boils at 472
				Potassium    melts at 63    boils at 1125
				Sodium       melts at 98    boils at 1281
				Sulfur       melts at 113   boils at 693
				Iodine       melts at 114   boils at 344
				Indium       melts at 157   boils at 2894
   gasses in atmosphere:
				Nitrogen         99.5%  PP 32311.0 mb
				Water             0.1%  PP   17.0 mb
				CarbonDioxide     0.1%  PP   39.0 mb
				Ozone             0.1%  PP   37.2 mb
				Ethanol           0.1%  PP   40.0 mb


Planet 4	
   Distance from primary:	1.306	AU
   Mass:			1.418	Earth masses
   Equatorial radius:		7173.4	km
   Density:			5.483	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		1.12	Earth gees
   Surface pressure:		1.849	Earth atmospheres
   Surface temperature:		16.36	degrees Celcius
   Normal daytime temperature:	19.46	degrees Celcius
   Normal night temperature:	13.06	degrees Celcius
   Maximum temperature:   	36.19	degrees Celcius
   Minimum temperature:   	-4.60	degrees Celcius
   Escape Velocity:		12.56	km/sec
   Molecular weight retained:	5.03 and above
   Surface acceleration:	1099.20	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.352
   Length of year:		518.61	days
   Length of day:		14.63	hours
   Boiling point of water:	117.7	degrees Celcius
   Hydrosphere percentage:	73.20
   Cloud cover percentage:	58.75
   Ice cover percentage:	1.36
   liquids at surface:
				Ethanol      melts at -114  boils at 95
				Mercury      melts at -39   boils at 387
				Bromine      melts at -7    boils at 75
				Water        melts at 0     boils at 118
   gasses in atmosphere:
				Oxygen            4.9%  PP   90.5 mb
				Nitrogen         94.9%  PP 1754.8 mb
				CarbonDioxide     0.1%  PP    1.0 mb
				Ozone             0.1%  PP    1.0 mb


Planet 5	*gas giant*
   Distance from primary:	2.716	AU
   Mass:			294.851	Earth masses
   Equatorial radius:		59266.0	km
   Density:			2.021	grams/cc
   Eccentricity of orbit:	0.094
   Escape Velocity:		62.99	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	3347.57	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.530
   Length of year:		1554.62	days
   Length of day:		7.06	hours


Planet 6	*gas giant*
   Distance from primary:	4.662	AU
   Mass:			1.910	Earth masses
   Equatorial radius:		14257.2	km
   Density:			0.940	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		10.34	km/sec
   Molecular weight retained:	7.43 and above
   Surface acceleration:	374.72	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.478
   Length of year:		3498.38	days
   Length of day:		21.11	hours


Planet 7	*gas giant*
   Distance from primary:	6.621	AU
   Mass:			2.039	Earth masses
   Equatorial radius:		14963.3	km
   Density:			0.869	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		10.43	km/sec
   Molecular weight retained:	7.30 and above
   Surface acceleration:	363.22	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.526
   Length of year:		5920.89	days
   Length of day:		21.45	hours


Planet 8	*gas giant*
   Distance from primary:	9.986	AU
   Mass:			733.525	Earth masses
   Equatorial radius:		86174.6	km
   Density:			1.636	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		82.40	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3939.09	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.536
   Length of year:		10956.38	days
   Length of day:		6.51	hours


Planet 9	*gas giant*
   Distance from primary:	19.274	AU
   Mass:			44.828	Earth masses
   Equatorial radius:		40284.2	km
   Density:			0.978	grams/cc
   Eccentricity of orbit:	0.189
   Escape Velocity:		29.79	km/sec
   Molecular weight retained:	0.89 and above
   Surface acceleration:	1101.60	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.486
   Length of year:		29407.03	days
   Length of day:		12.31	hours


Planet 10	*gas giant*
   Distance from primary:	38.288	AU
   Mass:			1.937	Earth masses
   Equatorial radius:		17062.3	km
   Density:			0.557	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		9.52	km/sec
   Molecular weight retained:	8.77 and above
   Surface acceleration:	265.38	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.468
   Length of year:		82339.94	days
   Length of day:		25.09	hours


Planet 11	
   Distance from primary:	46.810	AU
   Mass:			0.088	Earth masses
   Equatorial radius:		3845.3	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.98	degrees Celcius
   Normal daytime temperature:	-223.06	degrees Celcius
   Normal night temperature:	-234.80	degrees Celcius
   Maximum temperature:   	-212.66	degrees Celcius
   Minimum temperature:   	-245.70	degrees Celcius
   Escape Velocity:		4.27	km/sec
   Molecular weight retained:	43.49 and above
   Surface acceleration:	237.36	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.162
   Length of year:		111307.06	days
   Length of day:		31.11	hours
   Boiling point of water:	-67.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


