                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486b1
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6401 K
Stellar class: F7
Age: 2.781 billion years  (4.053 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.373 AU	no atmosphere
2	  0.541 AU	no atmosphere
3	  0.943 AU	greenhouse
4	  1.277 AU	
5	  1.857 AU	gas giant
6	  5.524 AU	gas giant
7	 12.676 AU	gas giant
8	 25.321 AU	gas giant
9	 39.611 AU	no atmosphere
10	 47.136 AU	gas giant



Planet 1	
   Distance from primary:	0.373	AU
   Mass:			0.079	Earth masses
   Equatorial radius:		2778.2	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		230.38	degrees Celcius
   Normal daytime temperature:	443.47	degrees Celcius
   Normal night temperature:	-187.19	degrees Celcius
   Maximum temperature:   	446.58	degrees Celcius
   Minimum temperature:   	-197.56	degrees Celcius
   Escape Velocity:		4.77	km/sec
   Molecular weight retained:	34.85 and above
   Surface acceleration:	409.97	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.084
   Length of year:		79.22	days
   Length of day:		1901.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.541	AU
   Mass:			0.448	Earth masses
   Equatorial radius:		4922.9	km
   Density:			5.355	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		145.27	degrees Celcius
   Maximum temperature:   	342.41	degrees Celcius
   Minimum temperature:   	-217.63	degrees Celcius
   Escape Velocity:		8.52	km/sec
   Molecular weight retained:	10.94 and above
   Surface acceleration:	736.76	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.083
   Length of year:		138.26	days
   Length of day:		3318.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.943	AU
   Mass:			0.377	Earth masses
   Equatorial radius:		4652.9	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		0.71	Earth gees
   Surface pressure:		14.714	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		104.65	degrees Celcius
   Maximum temperature:   	114.55	degrees Celcius
   Minimum temperature:   	94.18	degrees Celcius
   Escape Velocity:		8.04	km/sec
   Molecular weight retained:	12.28 and above
   Surface acceleration:	694.81	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.496
   Length of year:		318.51	days
   Length of day:		20.71	hours
   Boiling point of water:	192.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 513
				Francium     melts at 27    boils at 912
				Cesium       melts at 28    boils at 947
				Gallium      melts at 30    boils at 3066
				Rubidium     melts at 39    boils at 926
				Phosphorus   melts at 44    boils at 418
				Potassium    melts at 63    boils at 1023
				Sodium       melts at 98    boils at 1168
   gasses in atmosphere:
				Nitrogen         99.1%  PP 14574.6 mb
				Water             0.1%  PP   12.7 mb
				CarbonDioxide     0.2%  PP   34.2 mb
				Methane           0.1%  PP    9.1 mb
				Ammonia           0.1%  PP   10.7 mb
				Ozone             0.2%  PP   35.0 mb
				Ethanol           0.2%  PP   35.0 mb


Planet 4	
   Distance from primary:	1.277	AU
   Mass:			0.872	Earth masses
   Equatorial radius:		6125.0	km
   Density:			5.417	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.689	Earth atmospheres
   Surface temperature:		16.90	degrees Celcius
   Normal daytime temperature:	22.29	degrees Celcius
   Normal night temperature:	11.19	degrees Celcius
   Maximum temperature:   	46.05	degrees Celcius
   Minimum temperature:   	-13.91	degrees Celcius
   Escape Velocity:		10.66	km/sec
   Molecular weight retained:	6.99 and above
   Surface acceleration:	927.21	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.287
   Length of year:		501.45	days
   Length of day:		15.90	hours
   Boiling point of water:	90.0	degrees Celcius
   Hydrosphere percentage:	60.86
   Cloud cover percentage:	47.21
   Ice cover percentage:	1.45
   liquids at surface:
				Ethanol      melts at -114  boils at 69
				Mercury      melts at -39   boils at 340
				Bromine      melts at -7    boils at 51
				Water        melts at 0     boils at 90
   gasses in atmosphere:
				Oxygen           36.4%  PP  251.1 mb
				Nitrogen         63.4%  PP  437.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.857	AU
   Mass:			18.675	Earth masses
   Equatorial radius:		25678.6	km
   Density:			1.574	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		24.08	km/sec
   Molecular weight retained:	1.37 and above
   Surface acceleration:	1129.41	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.479
   Length of year:		879.45	days
   Length of day:		12.16	hours


Planet 6	*gas giant*
   Distance from primary:	5.524	AU
   Mass:			892.869	Earth masses
   Equatorial radius:		86874.9	km
   Density:			1.943	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		90.54	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4717.78	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.504
   Length of year:		4507.73	days
   Length of day:		5.95	hours


Planet 7	*gas giant*
   Distance from primary:	12.676	AU
   Mass:			453.154	Earth masses
   Equatorial radius:		76392.2	km
   Density:			1.450	grams/cc
   Eccentricity of orbit:	0.095
   Escape Velocity:		68.78	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3096.61	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.512
   Length of year:		15679.91	days
   Length of day:		7.34	hours


Planet 8	*gas giant*
   Distance from primary:	25.321	AU
   Mass:			3.133	Earth masses
   Equatorial radius:		18967.6	km
   Density:			0.655	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		11.48	km/sec
   Molecular weight retained:	6.03 and above
   Surface acceleration:	347.29	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.493
   Length of year:		44293.13	days
   Length of day:		21.93	hours


Planet 9	
   Distance from primary:	39.611	AU
   Mass:			0.309	Earth masses
   Equatorial radius:		5815.1	km
   Density:			2.239	grams/cc
   Eccentricity of orbit:	0.067
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-224.40	degrees Celcius
   Normal daytime temperature:	-218.99	degrees Celcius
   Normal night temperature:	-229.74	degrees Celcius
   Maximum temperature:   	-208.22	degrees Celcius
   Minimum temperature:   	-241.28	degrees Celcius
   Escape Velocity:		6.50	km/sec
   Molecular weight retained:	18.76 and above
   Surface acceleration:	363.83	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.157
   Length of year:		86665.35	days
   Length of day:		25.13	hours
   Boiling point of water:	-42.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 10	*gas giant*
   Distance from primary:	47.136	AU
   Mass:			0.292	Earth masses
   Equatorial radius:		9996.9	km
   Density:			0.417	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		4.83	km/sec
   Molecular weight retained:	34.09 and above
   Surface acceleration:	116.48	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.517
   Length of year:		112500.78	days
   Length of day:		37.87	hours


