                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e23
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6350 K
Stellar class: F7
Age: 2.850 billion years  (4.274 billion left on main sequence)
Habitable ecosphere radius: 1.238 AU

Planets present at:
1	  0.377 AU	no atmosphere
2	  0.408 AU	no atmosphere
3	  0.546 AU	no atmosphere
4	  0.707 AU	no atmosphere
5	  0.817 AU	no atmosphere
6	  1.079 AU	greenhouse
7	  1.587 AU	gas giant
8	  2.783 AU	cold
9	  4.026 AU	high pressure
10	  7.176 AU	gas giant
11	 16.108 AU	gas giant
12	 44.709 AU	no atmosphere



Planet 1	
   Distance from primary:	0.377	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1484.8	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.055
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		223.30	degrees Celcius
   Maximum temperature:   	437.89	degrees Celcius
   Minimum temperature:   	-198.82	degrees Celcius
   Escape Velocity:		2.54	km/sec
   Molecular weight retained:	122.57 and above
   Surface acceleration:	218.09	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.067
   Length of year:		81.04	days
   Length of day:		1944.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.408	AU
   Mass:			0.098	Earth masses
   Equatorial radius:		2979.3	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		205.35	degrees Celcius
   Maximum temperature:   	416.04	degrees Celcius
   Minimum temperature:   	-203.49	degrees Celcius
   Escape Velocity:		5.12	km/sec
   Molecular weight retained:	30.27 and above
   Surface acceleration:	440.08	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.057
   Length of year:		91.19	days
   Length of day:		2188.46	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.546	AU
   Mass:			0.380	Earth masses
   Equatorial radius:		4662.4	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		137.61	degrees Celcius
   Maximum temperature:   	332.77	degrees Celcius
   Minimum temperature:   	-218.44	degrees Celcius
   Escape Velocity:		8.06	km/sec
   Molecular weight retained:	12.23 and above
   Surface acceleration:	696.27	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.083
   Length of year:		141.19	days
   Length of day:		3388.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.707	AU
   Mass:			0.399	Earth masses
   Equatorial radius:		4740.1	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		88.15	degrees Celcius
   Normal daytime temperature:	160.76	degrees Celcius
   Normal night temperature:	12.46	degrees Celcius
   Maximum temperature:   	189.23	degrees Celcius
   Minimum temperature:   	-17.61	degrees Celcius
   Escape Velocity:		8.19	km/sec
   Molecular weight retained:	11.82 and above
   Surface acceleration:	708.32	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.082
   Length of year:		207.72	days
   Length of day:		53.03	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.817	AU
   Mass:			0.155	Earth masses
   Equatorial radius:		3471.1	km
   Density:			5.300	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		64.09	degrees Celcius
   Normal daytime temperature:	132.67	degrees Celcius
   Normal night temperature:	-6.97	degrees Celcius
   Maximum temperature:   	159.56	degrees Celcius
   Minimum temperature:   	-34.96	degrees Celcius
   Escape Velocity:		5.97	km/sec
   Molecular weight retained:	22.24 and above
   Surface acceleration:	514.11	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.068
   Length of year:		258.33	days
   Length of day:		53.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 6	
   Distance from primary:	1.079	AU
   Mass:			0.314	Earth masses
   Equatorial radius:		4378.2	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.67	Earth gees
   Surface pressure:		9.658	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		34.77	degrees Celcius
   Maximum temperature:   	45.10	degrees Celcius
   Minimum temperature:   	23.88	degrees Celcius
   Escape Velocity:		7.56	km/sec
   Molecular weight retained:	13.90 and above
   Surface acceleration:	652.40	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.591
   Length of year:		391.61	days
   Length of day:		20.04	hours
   Boiling point of water:	175.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.05
   liquids at surface:
				Ethanol      melts at -114  boils at 149
				Mercury      melts at -39   boils at 484
				Bromine      melts at -7    boils at 126
				Water        melts at 0     boils at 175
				Francium     melts at 27    boils at 868
				Cesium       melts at 28    boils at 902
				Gallium      melts at 30    boils at 2941
   gasses in atmosphere:
				Nitrogen         92.1%  PP 8895.6 mb
				CarbonDioxide     3.2%  PP  305.0 mb
				Methane           0.5%  PP   48.6 mb
				Ammonia           0.7%  PP   67.3 mb
				Ozone             3.3%  PP  316.0 mb
				Krypton           0.2%  PP   18.2 mb


Planet 7	*gas giant*
   Distance from primary:	1.587	AU
   Mass:			6.310	Earth masses
   Equatorial radius:		18510.3	km
   Density:			1.420	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		16.49	km/sec
   Molecular weight retained:	2.92 and above
   Surface acceleration:	734.45	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.547
   Length of year:		699.01	days
   Length of day:		15.09	hours


Planet 8	
   Distance from primary:	2.783	AU
   Mass:			1.175	Earth masses
   Equatorial radius:		6748.6	km
   Density:			5.455	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		1.05	Earth gees
   Surface pressure:		1.117	Earth atmospheres
   Surface temperature:		-111.11	degrees Celcius
   Normal daytime temperature:	-108.84	degrees Celcius
   Normal night temperature:	-113.50	degrees Celcius
   Maximum temperature:   	-92.69	degrees Celcius
   Minimum temperature:   	-131.00	degrees Celcius
   Escape Velocity:		11.78	km/sec
   Molecular weight retained:	5.72 and above
   Surface acceleration:	1028.78	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.673
   Length of year:		1623.05	days
   Length of day:		14.94	hours
   Boiling point of water:	103.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	90.46
   liquids at surface:
				Ethanol      melts at -114  boils at 81
				Xenon        melts at -112  boils at -107
   gasses in atmosphere:
				Oxygen            1.6%  PP   18.4 mb
				Nitrogen         98.3%  PP 1097.2 mb


Planet 9	
   Distance from primary:	4.026	AU
   Mass:			1.685	Earth masses
   Equatorial radius:		7583.4	km
   Density:			5.512	grams/cc
   Eccentricity of orbit:	0.109
   Surface gravity:		1.19	Earth gees
   Surface pressure:		2.311	Earth atmospheres
   Surface temperature:		-144.00	degrees Celcius
   Normal daytime temperature:	-142.80	degrees Celcius
   Normal night temperature:	-145.26	degrees Celcius
   Maximum temperature:   	-129.62	degrees Celcius
   Minimum temperature:   	-159.63	degrees Celcius
   Escape Velocity:		13.31	km/sec
   Molecular weight retained:	4.48 and above
   Surface acceleration:	1168.25	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.751
   Length of year:		2823.90	days
   Length of day:		14.02	hours
   Boiling point of water:	124.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -101
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2309.6 mb


Planet 10	*gas giant*
   Distance from primary:	7.176	AU
   Mass:			1960.461	Earth masses
   Equatorial radius:		111927.7	km
   Density:			1.995	grams/cc
   Eccentricity of orbit:	0.180
   Escape Velocity:		118.19	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	6240.54	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.486
   Length of year:		6700.96	days
   Length of day:		5.17	hours


Planet 11	*gas giant*
   Distance from primary:	16.108	AU
   Mass:			299.475	Earth masses
   Equatorial radius:		69215.3	km
   Density:			1.289	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		58.74	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2492.84	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.541
   Length of year:		22588.03	days
   Length of day:		8.19	hours


Planet 12	
   Distance from primary:	44.709	AU
   Mass:			0.343	Earth masses
   Equatorial radius:		6022.7	km
   Density:			2.243	grams/cc
   Eccentricity of orbit:	0.128
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.72	degrees Celcius
   Normal daytime temperature:	-222.76	degrees Celcius
   Normal night temperature:	-232.59	degrees Celcius
   Maximum temperature:   	-209.78	degrees Celcius
   Minimum temperature:   	-246.20	degrees Celcius
   Escape Velocity:		6.74	km/sec
   Molecular weight retained:	17.46 and above
   Surface acceleration:	377.48	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.150
   Length of year:		104492.42	days
   Length of day:		24.67	hours
   Boiling point of water:	-39.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   gasses in atmosphere:
				Neon             100.0%  PP    0.3 mb


