                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a43
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6356 K
Stellar class: F7
Age: 1.437 billion years  (5.281 billion left on main sequence)
Habitable ecosphere radius: 1.285 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.456 AU	no atmosphere
3	  0.701 AU	no atmosphere
4	  0.932 AU	greenhouse
5	  1.454 AU	
6	  2.474 AU	gas giant
7	  5.472 AU	gas giant
8	 11.039 AU	gas giant
9	 18.359 AU	no atmosphere
10	 27.735 AU	gas giant
11	 50.146 AU	no atmosphere



Planet 1	
   Distance from primary:	0.358	AU
   Mass:			0.042	Earth masses
   Equatorial radius:		2256.2	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		245.89	degrees Celcius
   Normal daytime temperature:	462.25	degrees Celcius
   Normal night temperature:	-183.09	degrees Celcius
   Maximum temperature:   	465.32	degrees Celcius
   Minimum temperature:   	-193.60	degrees Celcius
   Escape Velocity:		3.87	km/sec
   Molecular weight retained:	52.95 and above
   Surface acceleration:	332.21	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.068
   Length of year:		74.32	days
   Length of day:		1783.70	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.456	AU
   Mass:			0.326	Earth masses
   Equatorial radius:		4435.1	km
   Density:			5.334	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		186.54	degrees Celcius
   Maximum temperature:   	393.25	degrees Celcius
   Minimum temperature:   	-209.05	degrees Celcius
   Escape Velocity:		7.66	km/sec
   Molecular weight retained:	13.54 and above
   Surface acceleration:	661.15	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.070
   Length of year:		106.80	days
   Length of day:		2563.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.701	AU
   Mass:			1/142.5	Earth masses
   Equatorial radius:		1240.1	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		96.37	degrees Celcius
   Maximum temperature:   	281.44	degrees Celcius
   Minimum temperature:   	-225.64	degrees Celcius
   Escape Velocity:		2.12	km/sec
   Molecular weight retained:	175.82 and above
   Surface acceleration:	182.04	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.082
   Length of year:		203.59	days
   Length of day:		4886.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.932	AU
   Mass:			1.090	Earth masses
   Equatorial radius:		6586.4	km
   Density:			5.444	grams/cc
   Eccentricity of orbit:	0.156
   Surface gravity:		1.02	Earth gees
   Surface pressure:		106.127	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		420.58	degrees Celcius
   Maximum temperature:   	424.90	degrees Celcius
   Minimum temperature:   	414.51	degrees Celcius
   Escape Velocity:		11.49	km/sec
   Molecular weight retained:	6.01 and above
   Surface acceleration:	1002.16	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.507
   Length of year:		312.18	days
   Length of day:		15.58	hours
   Boiling point of water:	296.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1176
				Cesium       melts at 28    boils at 1219
				Gallium      melts at 30    boils at 3809
				Rubidium     melts at 39    boils at 1193
				Potassium    melts at 63    boils at 1311
				Sodium       melts at 98    boils at 1488
				Sulfur       melts at 113   boils at 822
				Indium       melts at 157   boils at 3316
				Lithium      melts at 181   boils at 2198
				Selenium     melts at 217   boils at 1188
				Tin          melts at 232   boils at 4145
				Polonium     melts at 254   boils at 1611
				Bismuth      melts at 271   boils at 2529
				Thallium     melts at 304   boils at 2366
				Cadmium      melts at 321   boils at 1310
				Lead         melts at 328   boils at 2815
				Zinc         melts at 420   boils at 1527
   gasses in atmosphere:
				Nitrogen         99.2%  PP 105317.5 mb
				Phosphorus        0.5%  PP  527.4 mb
				CarbonDioxide     0.1%  PP   55.6 mb
				Ethanol           0.1%  PP   56.1 mb


Planet 5	
   Distance from primary:	1.454	AU
   Mass:			1.067	Earth masses
   Equatorial radius:		6541.3	km
   Density:			5.441	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		1.01	Earth gees
   Surface pressure:		1.197	Earth atmospheres
   Surface temperature:		10.18	degrees Celcius
   Normal daytime temperature:	14.07	degrees Celcius
   Normal night temperature:	6.05	degrees Celcius
   Maximum temperature:   	34.13	degrees Celcius
   Minimum temperature:   	-15.16	degrees Celcius
   Escape Velocity:		11.41	km/sec
   Molecular weight retained:	6.10 and above
   Surface acceleration:	994.78	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.232
   Length of year:		607.94	days
   Length of day:		15.23	hours
   Boiling point of water:	105.0	degrees Celcius
   Hydrosphere percentage:	75.75
   Cloud cover percentage:	39.11
   Ice cover percentage:	2.94
   liquids at surface:
				Ethanol      melts at -114  boils at 83
				Mercury      melts at -39   boils at 365
				Bromine      melts at -7    boils at 64
				Water        melts at 0     boils at 105
   gasses in atmosphere:
				Oxygen           24.2%  PP  289.6 mb
				Nitrogen         75.7%  PP  905.8 mb


Planet 6	*gas giant*
   Distance from primary:	2.474	AU
   Mass:			29.057	Earth masses
   Equatorial radius:		29893.3	km
   Density:			1.552	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		27.84	km/sec
   Molecular weight retained:	1.02 and above
   Surface acceleration:	1296.73	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.497
   Length of year:		1349.93	days
   Length of day:		11.35	hours


Planet 7	*gas giant*
   Distance from primary:	5.472	AU
   Mass:			1471.825	Earth masses
   Equatorial radius:		100339.1	km
   Density:			2.079	grams/cc
   Eccentricity of orbit:	0.120
   Escape Velocity:		108.16	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5829.82	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.538
   Length of year:		4430.50	days
   Length of day:		5.35	hours


Planet 8	*gas giant*
   Distance from primary:	11.039	AU
   Mass:			581.656	Earth masses
   Equatorial radius:		81147.4	km
   Density:			1.553	grams/cc
   Eccentricity of orbit:	0.124
   Escape Velocity:		75.61	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3522.54	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.456
   Length of year:		12711.79	days
   Length of day:		6.89	hours


Planet 9	
   Distance from primary:	18.359	AU
   Mass:			0.301	Earth masses
   Equatorial radius:		5766.2	km
   Density:			2.238	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.065	Earth atmospheres
   Surface temperature:		-201.32	degrees Celcius
   Normal daytime temperature:	-196.12	degrees Celcius
   Normal night temperature:	-206.72	degrees Celcius
   Maximum temperature:   	-178.85	degrees Celcius
   Minimum temperature:   	-225.52	degrees Celcius
   Escape Velocity:		6.45	km/sec
   Molecular weight retained:	19.09 and above
   Surface acceleration:	360.62	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.300
   Length of year:		27285.12	days
   Length of day:		25.24	hours
   Boiling point of water:	37.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	28.13
   liquids at surface:
				Oxygen       melts at -218  boils at -198
   gasses in atmosphere:
				Neon             100.0%  PP   64.9 mb


Planet 10	*gas giant*
   Distance from primary:	27.735	AU
   Mass:			25.280	Earth masses
   Equatorial radius:		35107.4	km
   Density:			0.834	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		23.96	km/sec
   Molecular weight retained:	1.38 and above
   Surface acceleration:	817.94	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.497
   Length of year:		50659.24	days
   Length of day:		14.29	hours


Planet 11	
   Distance from primary:	50.146	AU
   Mass:			0.243	Earth masses
   Equatorial radius:		5373.3	km
   Density:			2.231	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.92	degrees Celcius
   Normal daytime temperature:	-224.94	degrees Celcius
   Normal night temperature:	-234.81	degrees Celcius
   Maximum temperature:   	-208.36	degrees Celcius
   Minimum temperature:   	-251.38	degrees Celcius
   Escape Velocity:		6.00	km/sec
   Molecular weight retained:	22.05 and above
   Surface acceleration:	335.00	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.155
   Length of year:		123166.36	days
   Length of day:		26.18	hours
   Boiling point of water:	-48.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


