                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a1d
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6355 K
Stellar class: F7
Age: 1.811 billion years  (4.912 billion left on main sequence)
Habitable ecosphere radius: 1.284 AU

Planets present at:
1	  0.355 AU	no atmosphere
2	  0.480 AU	no atmosphere
3	  0.752 AU	greenhouse
4	  1.881 AU	gas giant
5	  3.846 AU	gas giant
6	  7.665 AU	gas giant
7	 16.392 AU	gas giant
8	 37.399 AU	no atmosphere
9	 42.489 AU	gas giant
10	 49.563 AU	no atmosphere



Planet 1	
   Distance from primary:	0.355	AU
   Mass:			0.173	Earth masses
   Equatorial radius:		3594.2	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		246.84	degrees Celcius
   Normal daytime temperature:	463.38	degrees Celcius
   Normal night temperature:	-182.59	degrees Celcius
   Maximum temperature:   	466.36	degrees Celcius
   Minimum temperature:   	-192.78	degrees Celcius
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.73 and above
   Surface acceleration:	532.73	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.076
   Length of year:		73.40	days
   Length of day:		1761.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.480	AU
   Mass:			0.021	Earth masses
   Equatorial radius:		1796.3	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		174.84	degrees Celcius
   Maximum temperature:   	378.80	degrees Celcius
   Minimum temperature:   	-211.36	degrees Celcius
   Escape Velocity:		3.08	km/sec
   Molecular weight retained:	83.67 and above
   Surface acceleration:	264.08	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.068
   Length of year:		115.48	days
   Length of day:		2771.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.752	AU
   Mass:			1.408	Earth masses
   Equatorial radius:		7156.3	km
   Density:			5.482	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		1.12	Earth gees
   Surface pressure:		153.002	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		522.22	degrees Celcius
   Maximum temperature:   	525.51	degrees Celcius
   Minimum temperature:   	516.18	degrees Celcius
   Escape Velocity:		12.53	km/sec
   Molecular weight retained:	5.06 and above
   Surface acceleration:	1096.35	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.558
   Length of year:		226.03	days
   Length of day:		16.18	hours
   Boiling point of water:	320.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1238
				Cesium       melts at 28    boils at 1283
				Gallium      melts at 30    boils at 3985
				Rubidium     melts at 39    boils at 1256
				Potassium    melts at 63    boils at 1380
				Sodium       melts at 98    boils at 1564
				Indium       melts at 157   boils at 3471
				Lithium      melts at 181   boils at 2304
				Selenium     melts at 217   boils at 1251
				Tin          melts at 232   boils at 4335
				Polonium     melts at 254   boils at 1692
				Bismuth      melts at 271   boils at 2650
				Thallium     melts at 304   boils at 2480
				Cadmium      melts at 321   boils at 1378
				Lead         melts at 328   boils at 2947
				Zinc         melts at 420   boils at 1604
				Tellurium    melts at 450   boils at 1736
   gasses in atmosphere:
				Sulfur           19.2%  PP 29322.0 mb
				Nitrogen         80.2%  PP 122783.9 mb
				Phosphorus        0.4%  PP  586.0 mb


Planet 4	*gas giant*
   Distance from primary:	1.881	AU
   Mass:			32.816	Earth masses
   Equatorial radius:		30274.0	km
   Density:			1.688	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		29.40	km/sec
   Molecular weight retained:	0.92 and above
   Surface acceleration:	1427.87	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.467
   Length of year:		894.58	days
   Length of day:		10.82	hours


Planet 5	*gas giant*
   Distance from primary:	3.846	AU
   Mass:			79.631	Earth masses
   Equatorial radius:		41615.0	km
   Density:			1.577	grams/cc
   Eccentricity of orbit:	0.150
   Escape Velocity:		39.07	km/sec
   Molecular weight retained:	0.52 and above
   Surface acceleration:	1833.66	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.523
   Length of year:		2615.96	days
   Length of day:		9.54	hours


Planet 6	*gas giant*
   Distance from primary:	7.665	AU
   Mass:			472.480	Earth masses
   Equatorial radius:		74089.1	km
   Density:			1.658	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		71.32	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3432.53	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.526
   Length of year:		7355.86	days
   Length of day:		6.98	hours


Planet 7	*gas giant*
   Distance from primary:	16.392	AU
   Mass:			408.664	Earth masses
   Equatorial radius:		75663.6	km
   Density:			1.346	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		65.63	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	2846.63	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.479
   Length of year:		23009.03	days
   Length of day:		7.66	hours


Planet 8	
   Distance from primary:	37.399	AU
   Mass:			0.154	Earth masses
   Equatorial radius:		4630.6	km
   Density:			2.219	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-222.99	degrees Celcius
   Normal daytime temperature:	-216.79	degrees Celcius
   Normal night temperature:	-229.10	degrees Celcius
   Maximum temperature:   	-205.60	degrees Celcius
   Minimum temperature:   	-240.99	degrees Celcius
   Escape Velocity:		5.16	km/sec
   Molecular weight retained:	29.85 and above
   Surface acceleration:	287.18	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.141
   Length of year:		79336.75	days
   Length of day:		28.28	hours
   Boiling point of water:	-55.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 9	*gas giant*
   Distance from primary:	42.489	AU
   Mass:			1.420	Earth masses
   Equatorial radius:		15707.6	km
   Density:			0.523	grams/cc
   Eccentricity of orbit:	0.089
   Escape Velocity:		8.49	km/sec
   Molecular weight retained:	11.01 and above
   Surface acceleration:	229.49	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.549
   Length of year:		96070.27	days
   Length of day:		26.98	hours


Planet 10	
   Distance from primary:	49.563	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2725.6	km
   Density:			2.197	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.80	degrees Celcius
   Normal daytime temperature:	-223.05	degrees Celcius
   Normal night temperature:	-236.42	degrees Celcius
   Maximum temperature:   	-207.03	degrees Celcius
   Minimum temperature:   	-252.05	degrees Celcius
   Escape Velocity:		3.02	km/sec
   Molecular weight retained:	87.00 and above
   Surface acceleration:	167.37	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.142
   Length of year:		121037.53	days
   Length of day:		37.04	hours
   Boiling point of water:	-83.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


