                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485d6
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6329 K
Stellar class: F7
Age: 5.378 billion years  (1.485 billion left on main sequence)
Habitable ecosphere radius: 1.268 AU

Planets present at:
1	  0.314 AU	no atmosphere
2	  0.433 AU	no atmosphere
3	  0.774 AU	greenhouse
4	  1.179 AU	no atmosphere
5	  1.442 AU	gas giant
6	  2.899 AU	gas giant
7	  4.582 AU	gas giant
8	 10.910 AU	gas giant
9	 13.611 AU	gas giant
10	 22.501 AU	gas giant
11	 41.425 AU	gas giant



Planet 1	
   Distance from primary:	0.314	AU
   Mass:			0.152	Earth masses
   Equatorial radius:		3447.9	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		276.01	degrees Celcius
   Normal daytime temperature:	498.27	degrees Celcius
   Normal night temperature:	-172.07	degrees Celcius
   Maximum temperature:   	501.45	degrees Celcius
   Minimum temperature:   	-183.54	degrees Celcius
   Escape Velocity:		5.93	km/sec
   Molecular weight retained:	22.55 and above
   Surface acceleration:	510.60	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.077
   Length of year:		61.20	days
   Length of day:		1468.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.433	AU
   Mass:			0.173	Earth masses
   Equatorial radius:		3597.5	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		197.38	degrees Celcius
   Maximum temperature:   	406.48	degrees Celcius
   Minimum temperature:   	-206.36	degrees Celcius
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.69 and above
   Surface acceleration:	533.22	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.056
   Length of year:		99.01	days
   Length of day:		2376.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.774	AU
   Mass:			0.864	Earth masses
   Equatorial radius:		6106.1	km
   Density:			5.416	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.94	Earth gees
   Surface pressure:		67.237	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		390.76	degrees Celcius
   Maximum temperature:   	396.40	degrees Celcius
   Minimum temperature:   	383.25	degrees Celcius
   Escape Velocity:		10.62	km/sec
   Molecular weight retained:	7.03 and above
   Surface acceleration:	924.16	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.517
   Length of year:		236.82	days
   Length of day:		25.81	hours
   Boiling point of water:	268.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1105
				Cesium       melts at 28    boils at 1146
				Gallium      melts at 30    boils at 3610
				Rubidium     melts at 39    boils at 1121
				Potassium    melts at 63    boils at 1234
				Sodium       melts at 98    boils at 1402
				Sulfur       melts at 113   boils at 768
				Indium       melts at 157   boils at 3141
				Lithium      melts at 181   boils at 2077
				Selenium     melts at 217   boils at 1117
				Tin          melts at 232   boils at 3929
				Polonium     melts at 254   boils at 1519
				Bismuth      melts at 271   boils at 2392
				Thallium     melts at 304   boils at 2237
				Cadmium      melts at 321   boils at 1233
				Lead         melts at 328   boils at 2664
   gasses in atmosphere:
				Nitrogen         98.9%  PP 66531.2 mb
				Phosphorus        0.7%  PP  467.3 mb
				CarbonDioxide     0.1%  PP   54.3 mb
				Ozone             0.1%  PP   47.1 mb
				Ethanol           0.1%  PP   55.5 mb


Planet 4	
   Distance from primary:	1.179	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		3179.2	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.014	Earth atmospheres
   Surface temperature:		11.45	degrees Celcius
   Normal daytime temperature:	40.33	degrees Celcius
   Normal night temperature:	-18.02	degrees Celcius
   Maximum temperature:   	67.50	degrees Celcius
   Minimum temperature:   	-45.71	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.56 and above
   Surface acceleration:	470.09	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.141
   Length of year:		445.43	days
   Length of day:		26.34	hours
   Boiling point of water:	10.6	degrees Celcius
   Hydrosphere percentage:	33.60
   Cloud cover percentage:	0.00
   Ice cover percentage:	2.95
   liquids at surface:
				Mercury      melts at -39   boils at 208
				Water        melts at 0     boils at 12
   gasses in atmosphere:
				CarbonDioxide    44.0%  PP    6.2 mb
				Ozone            51.0%  PP    7.1 mb
				Chlorine          0.2%  PP    0.0 mb
				Argon             0.2%  PP    0.0 mb
				Krypton           4.1%  PP    0.6 mb
				Xenon             0.6%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.442	AU
   Mass:			3.172	Earth masses
   Equatorial radius:		14995.2	km
   Density:			1.342	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		12.99	km/sec
   Molecular weight retained:	4.71 and above
   Surface acceleration:	562.50	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.483
   Length of year:		602.47	days
   Length of day:		17.26	hours


Planet 6	*gas giant*
   Distance from primary:	2.899	AU
   Mass:			266.494	Earth masses
   Equatorial radius:		57876.6	km
   Density:			1.961	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		60.60	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	3172.63	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.469
   Length of year:		1716.34	days
   Length of day:		7.26	hours


Planet 7	*gas giant*
   Distance from primary:	4.582	AU
   Mass:			264.406	Earth masses
   Equatorial radius:		59989.0	km
   Density:			1.748	grams/cc
   Eccentricity of orbit:	0.089
   Escape Velocity:		59.29	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2929.99	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.544
   Length of year:		3410.11	days
   Length of day:		7.55	hours


Planet 8	*gas giant*
   Distance from primary:	10.910	AU
   Mass:			14.264	Earth masses
   Equatorial radius:		27518.5	km
   Density:			0.977	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		20.33	km/sec
   Molecular weight retained:	1.92 and above
   Surface acceleration:	751.13	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.548
   Length of year:		12534.29	days
   Length of day:		14.91	hours


Planet 9	*gas giant*
   Distance from primary:	13.611	AU
   Mass:			1.329	Earth masses
   Equatorial radius:		14027.7	km
   Density:			0.687	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		8.69	km/sec
   Molecular weight retained:	10.51 and above
   Surface acceleration:	269.29	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.467
   Length of year:		17465.17	days
   Length of day:		24.91	hours


Planet 10	*gas giant*
   Distance from primary:	22.501	AU
   Mass:			230.617	Earth masses
   Equatorial radius:		65818.8	km
   Density:			1.154	grams/cc
   Eccentricity of orbit:	0.180
   Escape Velocity:		52.86	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2122.91	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.458
   Length of year:		37113.80	days
   Length of day:		8.87	hours


Planet 11	*gas giant*
   Distance from primary:	41.425	AU
   Mass:			1.585	Earth masses
   Equatorial radius:		16204.3	km
   Density:			0.532	grams/cc
   Eccentricity of orbit:	0.222
   Escape Velocity:		8.83	km/sec
   Molecular weight retained:	10.17 and above
   Surface acceleration:	240.77	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.459
   Length of year:		92735.79	days
   Length of day:		26.34	hours


