                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504840a
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6161 K
Stellar class: F8
Age: 5.965 billion years  (0.957 billion left on main sequence)
Habitable ecosphere radius: 1.261 AU

Planets present at:
1	  0.393 AU	no atmosphere
2	  0.448 AU	no atmosphere
3	  0.518 AU	no atmosphere
4	  0.877 AU	no atmosphere
5	  1.168 AU	greenhouse
6	  1.935 AU	gas giant
7	  2.544 AU	cold
8	  3.871 AU	gas giant
9	  6.932 AU	gas giant
10	  8.429 AU	gas giant
11	 14.735 AU	gas giant
12	 29.688 AU	no atmosphere
13	 44.170 AU	gas giant



Planet 1	
   Distance from primary:	0.393	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		1739.4	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.097
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		215.09	degrees Celcius
   Normal daytime temperature:	424.93	degrees Celcius
   Normal night temperature:	-191.42	degrees Celcius
   Maximum temperature:   	428.06	degrees Celcius
   Minimum temperature:   	-201.55	degrees Celcius
   Escape Velocity:		2.98	km/sec
   Molecular weight retained:	89.25 and above
   Surface acceleration:	255.67	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.087
   Length of year:		85.77	days
   Length of day:		2058.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.448	AU
   Mass:			0.371	Earth masses
   Equatorial radius:		4626.9	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		185.00	degrees Celcius
   Maximum temperature:   	391.37	degrees Celcius
   Minimum temperature:   	-209.07	degrees Celcius
   Escape Velocity:		8.00	km/sec
   Molecular weight retained:	12.42 and above
   Surface acceleration:	690.77	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.080
   Length of year:		104.43	days
   Length of day:		2506.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.518	AU
   Mass:			0.104	Earth masses
   Equatorial radius:		3035.4	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		155.45	degrees Celcius
   Maximum temperature:   	355.08	degrees Celcius
   Minimum temperature:   	-215.88	degrees Celcius
   Escape Velocity:		5.22	km/sec
   Molecular weight retained:	29.15 and above
   Surface acceleration:	448.50	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.058
   Length of year:		129.88	days
   Length of day:		3117.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.877	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		3425.6	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		55.55	degrees Celcius
   Normal daytime temperature:	181.79	degrees Celcius
   Normal night temperature:	-92.37	degrees Celcius
   Maximum temperature:   	199.06	degrees Celcius
   Minimum temperature:   	-117.18	degrees Celcius
   Escape Velocity:		5.89	km/sec
   Molecular weight retained:	22.84 and above
   Surface acceleration:	507.23	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.067
   Length of year:		285.98	days
   Length of day:		164.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 5	
   Distance from primary:	1.168	AU
   Mass:			1.299	Earth masses
   Equatorial radius:		6972.2	km
   Density:			5.469	grams/cc
   Eccentricity of orbit:	0.110
   Surface gravity:		1.09	Earth gees
   Surface pressure:		174.616	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		380.37	degrees Celcius
   Maximum temperature:   	383.84	degrees Celcius
   Minimum temperature:   	375.51	degrees Celcius
   Escape Velocity:		12.19	km/sec
   Molecular weight retained:	5.34 and above
   Surface acceleration:	1065.72	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.535
   Length of year:		439.68	days
   Length of day:		15.07	hours
   Boiling point of water:	329.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1262
				Cesium       melts at 28    boils at 1308
				Gallium      melts at 30    boils at 4052
				Rubidium     melts at 39    boils at 1280
				Potassium    melts at 63    boils at 1406
				Sodium       melts at 98    boils at 1593
				Sulfur       melts at 113   boils at 887
				Indium       melts at 157   boils at 3530
				Lithium      melts at 181   boils at 2345
				Selenium     melts at 217   boils at 1275
				Tin          melts at 232   boils at 4407
				Polonium     melts at 254   boils at 1723
				Bismuth      melts at 271   boils at 2696
				Thallium     melts at 304   boils at 2523
				Cadmium      melts at 321   boils at 1405
				Lead         melts at 328   boils at 2998
   gasses in atmosphere:
				Nitrogen         99.2%  PP 173215.2 mb
				Phosphorus        0.5%  PP  949.7 mb
				CarbonDioxide     0.1%  PP  104.1 mb
				Ethanol           0.1%  PP  105.6 mb


Planet 6	*gas giant*
   Distance from primary:	1.935	AU
   Mass:			50.190	Earth masses
   Equatorial radius:		34402.4	km
   Density:			1.759	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		34.11	km/sec
   Molecular weight retained:	0.68 and above
   Surface acceleration:	1691.14	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.452
   Length of year:		937.13	days
   Length of day:		9.94	hours


Planet 7	
   Distance from primary:	2.544	AU
   Mass:			1.304	Earth masses
   Equatorial radius:		6980.9	km
   Density:			5.470	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.321	Earth atmospheres
   Surface temperature:		-101.90	degrees Celcius
   Normal daytime temperature:	-99.73	degrees Celcius
   Normal night temperature:	-104.20	degrees Celcius
   Maximum temperature:   	-85.34	degrees Celcius
   Minimum temperature:   	-119.74	degrees Celcius
   Escape Velocity:		12.21	km/sec
   Molecular weight retained:	5.33 and above
   Surface acceleration:	1067.17	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.679
   Length of year:		1412.85	days
   Length of day:		14.67	hours
   Boiling point of water:	107.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	90.12
   liquids at surface:
				Ethanol      melts at -114  boils at 86
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1319.9 mb
				Ozone             0.1%  PP    0.7 mb


Planet 8	*gas giant*
   Distance from primary:	3.871	AU
   Mass:			43.225	Earth masses
   Equatorial radius:		34894.5	km
   Density:			1.452	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		31.43	km/sec
   Molecular weight retained:	0.80 and above
   Surface acceleration:	1415.66	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.512
   Length of year:		2651.43	days
   Length of day:		10.86	hours


Planet 9	*gas giant*
   Distance from primary:	6.932	AU
   Mass:			7.937	Earth masses
   Equatorial radius:		22344.2	km
   Density:			1.015	grams/cc
   Eccentricity of orbit:	0.095
   Escape Velocity:		16.83	km/sec
   Molecular weight retained:	2.80 and above
   Surface acceleration:	634.00	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.535
   Length of year:		6355.33	days
   Length of day:		16.23	hours


Planet 10	*gas giant*
   Distance from primary:	8.429	AU
   Mass:			27.127	Earth masses
   Equatorial radius:		32502.2	km
   Density:			1.127	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		25.80	km/sec
   Molecular weight retained:	1.19 and above
   Surface acceleration:	1024.04	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.462
   Length of year:		8521.77	days
   Length of day:		12.77	hours


Planet 11	*gas giant*
   Distance from primary:	14.735	AU
   Mass:			725.459	Earth masses
   Equatorial radius:		88796.2	km
   Density:			1.479	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		80.72	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3669.13	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.452
   Length of year:		19675.72	days
   Length of day:		6.75	hours


Planet 12	
   Distance from primary:	29.688	AU
   Mass:			0.225	Earth masses
   Equatorial radius:		5240.6	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.24	degrees Celcius
   Normal daytime temperature:	-210.71	degrees Celcius
   Normal night temperature:	-223.71	degrees Celcius
   Maximum temperature:   	-196.89	degrees Celcius
   Minimum temperature:   	-238.35	degrees Celcius
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.20 and above
   Surface acceleration:	326.40	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.136
   Length of year:		56328.57	days
   Length of day:		26.53	hours
   Boiling point of water:	-49.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   liquids at surface:
				Fluorine     melts at -220  boils at -217
				Oxygen       melts at -218  boils at -213


Planet 13	*gas giant*
   Distance from primary:	44.170	AU
   Mass:			1.905	Earth masses
   Equatorial radius:		17196.4	km
   Density:			0.535	grams/cc
   Eccentricity of orbit:	0.164
   Escape Velocity:		9.40	km/sec
   Molecular weight retained:	8.98 and above
   Surface acceleration:	256.94	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.528
   Length of year:		102220.55	days
   Length of day:		25.50	hours


