                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f43
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6085 K
Stellar class: F9
Age: 2.018 billion years  (5.068 billion left on main sequence)
Habitable ecosphere radius: 1.242 AU

Planets present at:
1	  0.342 AU	no atmosphere
2	  0.513 AU	no atmosphere
3	  0.889 AU	no atmosphere
4	  1.002 AU	no atmosphere
5	  1.181 AU	
6	  1.474 AU	
7	  1.924 AU	cold
8	  3.256 AU	gas giant
9	  8.279 AU	gas giant
10	 13.965 AU	gas giant
11	 33.243 AU	no atmosphere
12	 38.627 AU	gas giant
13	 48.285 AU	no atmosphere



Planet 1	
   Distance from primary:	0.342	AU
   Mass:			0.053	Earth masses
   Equatorial radius:		2426.3	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		249.59	degrees Celcius
   Normal daytime temperature:	466.58	degrees Celcius
   Normal night temperature:	-180.78	degrees Celcius
   Maximum temperature:   	469.56	degrees Celcius
   Minimum temperature:   	-191.01	degrees Celcius
   Escape Velocity:		4.17	km/sec
   Molecular weight retained:	45.76 and above
   Surface acceleration:	357.49	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.062
   Length of year:		70.01	days
   Length of day:		1680.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.513	AU
   Mass:			0.456	Earth masses
   Equatorial radius:		4953.2	km
   Density:			5.356	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		155.02	degrees Celcius
   Maximum temperature:   	354.44	degrees Celcius
   Minimum temperature:   	-215.53	degrees Celcius
   Escape Velocity:		8.57	km/sec
   Molecular weight retained:	10.81 and above
   Surface acceleration:	741.48	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.052
   Length of year:		128.43	days
   Length of day:		3082.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.889	AU
   Mass:			0.067	Earth masses
   Equatorial radius:		2629.0	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		51.53	degrees Celcius
   Normal daytime temperature:	115.17	degrees Celcius
   Normal night temperature:	-14.05	degrees Celcius
   Maximum temperature:   	144.77	degrees Celcius
   Minimum temperature:   	-44.75	degrees Celcius
   Escape Velocity:		4.51	km/sec
   Molecular weight retained:	38.94 and above
   Surface acceleration:	387.69	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.059
   Length of year:		292.94	days
   Length of day:		50.64	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	1.002	AU
   Mass:			0.096	Earth masses
   Equatorial radius:		2964.4	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		32.51	degrees Celcius
   Normal daytime temperature:	69.87	degrees Celcius
   Normal night temperature:	-5.25	degrees Celcius
   Maximum temperature:   	99.46	degrees Celcius
   Minimum temperature:   	-35.35	degrees Celcius
   Escape Velocity:		5.09	km/sec
   Molecular weight retained:	30.58 and above
   Surface acceleration:	437.84	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.062
   Length of year:		350.29	days
   Length of day:		28.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 5	
   Distance from primary:	1.181	AU
   Mass:			0.566	Earth masses
   Equatorial radius:		5317.3	km
   Density:			5.374	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.343	Earth atmospheres
   Surface temperature:		18.03	degrees Celcius
   Normal daytime temperature:	26.04	degrees Celcius
   Normal night temperature:	9.57	degrees Celcius
   Maximum temperature:   	52.65	degrees Celcius
   Minimum temperature:   	-18.46	degrees Celcius
   Escape Velocity:		9.22	km/sec
   Molecular weight retained:	9.35 and above
   Surface acceleration:	798.54	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.300
   Length of year:		448.34	days
   Length of day:		17.24	hours
   Boiling point of water:	72.7	degrees Celcius
   Hydrosphere percentage:	61.87
   Cloud cover percentage:	53.91
   Ice cover percentage:	1.17
   liquids at surface:
				Ethanol      melts at -114  boils at 53
				Mercury      melts at -39   boils at 311
				Bromine      melts at -7    boils at 35
				Water        melts at 0     boils at 73
   gasses in atmosphere:
				Oxygen           54.3%  PP  186.1 mb
				Nitrogen         45.6%  PP  156.2 mb


Planet 6	
   Distance from primary:	1.474	AU
   Mass:			1.081	Earth masses
   Equatorial radius:		6567.7	km
   Density:			5.443	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		1.02	Earth gees
   Surface pressure:		1.126	Earth atmospheres
   Surface temperature:		6.77	degrees Celcius
   Normal daytime temperature:	10.72	degrees Celcius
   Normal night temperature:	2.57	degrees Celcius
   Maximum temperature:   	29.87	degrees Celcius
   Minimum temperature:   	-17.68	degrees Celcius
   Escape Velocity:		11.46	km/sec
   Molecular weight retained:	6.05 and above
   Surface acceleration:	999.10	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.188
   Length of year:		625.37	days
   Length of day:		15.20	hours
   Boiling point of water:	103.3	degrees Celcius
   Hydrosphere percentage:	69.82
   Cloud cover percentage:	29.65
   Ice cover percentage:	3.99
   liquids at surface:
				Ethanol      melts at -114  boils at 82
				Mercury      melts at -39   boils at 362
				Bromine      melts at -7    boils at 63
				Water        melts at 0     boils at 103
   gasses in atmosphere:
				Oxygen           28.8%  PP  324.0 mb
				Nitrogen         71.1%  PP  800.7 mb


Planet 7	
   Distance from primary:	1.924	AU
   Mass:			1.076	Earth masses
   Equatorial radius:		6557.9	km
   Density:			5.443	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		1.02	Earth gees
   Surface pressure:		0.962	Earth atmospheres
   Surface temperature:		-70.43	degrees Celcius
   Normal daytime temperature:	-67.34	degrees Celcius
   Normal night temperature:	-73.70	degrees Celcius
   Maximum temperature:   	-50.58	degrees Celcius
   Minimum temperature:   	-91.67	degrees Celcius
   Escape Velocity:		11.44	km/sec
   Molecular weight retained:	6.07 and above
   Surface acceleration:	997.49	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.612
   Length of year:		931.84	days
   Length of day:		15.18	hours
   Boiling point of water:	98.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.11
   Ice cover percentage:	90.14
   liquids at surface:
				Ethanol      melts at -114  boils at 78
				Chlorine     melts at -101  boils at -35
				Ammonia      melts at -78   boils at -34
				Radon        melts at -71   boils at -63
   gasses in atmosphere:
				Oxygen           13.1%  PP  125.9 mb
				Nitrogen         86.8%  PP  834.8 mb


Planet 8	*gas giant*
   Distance from primary:	3.256	AU
   Mass:			561.724	Earth masses
   Equatorial radius:		72758.4	km
   Density:			2.081	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		78.47	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	4231.51	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.525
   Length of year:		2050.33	days
   Length of day:		6.28	hours


Planet 9	*gas giant*
   Distance from primary:	8.279	AU
   Mass:			15.653	Earth masses
   Equatorial radius:		27678.6	km
   Density:			1.053	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		21.24	km/sec
   Molecular weight retained:	1.76 and above
   Surface acceleration:	814.82	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.537
   Length of year:		8319.99	days
   Length of day:		14.32	hours


Planet 10	*gas giant*
   Distance from primary:	13.965	AU
   Mass:			538.119	Earth masses
   Equatorial radius:		81123.2	km
   Density:			1.438	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		72.74	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3260.82	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.493
   Length of year:		18215.28	days
   Length of day:		7.16	hours


Planet 11	
   Distance from primary:	33.243	AU
   Mass:			0.213	Earth masses
   Equatorial radius:		5149.6	km
   Density:			2.227	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-220.87	degrees Celcius
   Normal daytime temperature:	-214.72	degrees Celcius
   Normal night temperature:	-226.95	degrees Celcius
   Maximum temperature:   	-199.41	degrees Celcius
   Minimum temperature:   	-242.92	degrees Celcius
   Escape Velocity:		5.75	km/sec
   Molecular weight retained:	24.05 and above
   Surface acceleration:	320.51	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.147
   Length of year:		66947.86	days
   Length of day:		26.77	hours
   Boiling point of water:	-50.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	*gas giant*
   Distance from primary:	38.627	AU
   Mass:			4.890	Earth masses
   Equatorial radius:		22413.7	km
   Density:			0.620	grams/cc
   Eccentricity of orbit:	0.127
   Escape Velocity:		13.19	km/sec
   Molecular weight retained:	4.56 and above
   Surface acceleration:	388.19	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.510
   Length of year:		83850.44	days
   Length of day:		20.74	hours


Planet 13	
   Distance from primary:	48.285	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		3069.7	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.89	degrees Celcius
   Normal daytime temperature:	-223.49	degrees Celcius
   Normal night temperature:	-236.17	degrees Celcius
   Maximum temperature:   	-211.63	degrees Celcius
   Minimum temperature:   	-248.30	degrees Celcius
   Escape Velocity:		3.40	km/sec
   Molecular weight retained:	68.50 and above
   Surface acceleration:	188.77	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.137
   Length of year:		117193.35	days
   Length of day:		34.88	hours
   Boiling point of water:	-77.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


