                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048026
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6133 K
Stellar class: F9
Age: 3.910 billion years  (3.145 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.387 AU	no atmosphere
2	  0.412 AU	no atmosphere
3	  0.749 AU	greenhouse
4	  1.233 AU	
5	  1.806 AU	gas giant
6	  2.606 AU	cold
7	  3.666 AU	gas giant
8	  8.755 AU	gas giant
9	 14.186 AU	gas giant
10	 33.392 AU	gas giant
11	 48.863 AU	no atmosphere



Planet 1	
   Distance from primary:	0.387	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1445.6	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		219.87	degrees Celcius
   Maximum temperature:   	433.71	degrees Celcius
   Minimum temperature:   	-199.91	degrees Celcius
   Escape Velocity:		2.48	km/sec
   Molecular weight retained:	129.32 and above
   Surface acceleration:	212.31	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.056
   Length of year:		84.11	days
   Length of day:		2018.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.412	AU
   Mass:			0.117	Earth masses
   Equatorial radius:		3160.0	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.26	degrees Celcius
   Maximum temperature:   	410.93	degrees Celcius
   Minimum temperature:   	-203.92	degrees Celcius
   Escape Velocity:		5.43	km/sec
   Molecular weight retained:	26.88 and above
   Surface acceleration:	467.21	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.082
   Length of year:		92.43	days
   Length of day:		2218.30	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.749	AU
   Mass:			0.448	Earth masses
   Equatorial radius:		4925.6	km
   Density:			5.355	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.75	Earth gees
   Surface pressure:		16.759	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		156.17	degrees Celcius
   Maximum temperature:   	167.42	degrees Celcius
   Minimum temperature:   	143.69	degrees Celcius
   Escape Velocity:		8.52	km/sec
   Molecular weight retained:	10.93 and above
   Surface acceleration:	737.17	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.468
   Length of year:		226.21	days
   Length of day:		42.51	hours
   Boiling point of water:	198.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 522
				Francium     melts at 27    boils at 927
				Cesium       melts at 28    boils at 962
				Gallium      melts at 30    boils at 3106
				Rubidium     melts at 39    boils at 941
				Phosphorus   melts at 44    boils at 426
				Potassium    melts at 63    boils at 1039
				Sodium       melts at 98    boils at 1185
				Sulfur       melts at 113   boils at 634
				Iodine       melts at 114   boils at 306
   gasses in atmosphere:
				Nitrogen         99.3%  PP 16648.8 mb
				Water             0.1%  PP   10.5 mb
				CarbonDioxide     0.2%  PP   26.4 mb
				Ammonia           0.1%  PP    9.0 mb
				Ozone             0.2%  PP   26.8 mb
				Ethanol           0.2%  PP   27.1 mb


Planet 4	
   Distance from primary:	1.233	AU
   Mass:			0.984	Earth masses
   Equatorial radius:		6369.8	km
   Density:			5.431	grams/cc
   Eccentricity of orbit:	0.177
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.937	Earth atmospheres
   Surface temperature:		17.18	degrees Celcius
   Normal daytime temperature:	21.77	degrees Celcius
   Normal night temperature:	12.30	degrees Celcius
   Maximum temperature:   	45.13	degrees Celcius
   Minimum temperature:   	-12.39	degrees Celcius
   Escape Velocity:		11.10	km/sec
   Molecular weight retained:	6.44 and above
   Surface acceleration:	966.83	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.331
   Length of year:		478.06	days
   Length of day:		15.65	hours
   Boiling point of water:	98.2	degrees Celcius
   Hydrosphere percentage:	67.88
   Cloud cover percentage:	55.40
   Ice cover percentage:	1.32
   liquids at surface:
				Ethanol      melts at -114  boils at 77
				Mercury      melts at -39   boils at 354
				Bromine      melts at -7    boils at 58
				Water        melts at 0     boils at 98
   gasses in atmosphere:
				Oxygen           23.9%  PP  223.9 mb
				Nitrogen         76.0%  PP  712.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.806	AU
   Mass:			2.960	Earth masses
   Equatorial radius:		14995.8	km
   Density:			1.252	grams/cc
   Eccentricity of orbit:	0.135
   Escape Velocity:		12.55	km/sec
   Molecular weight retained:	5.04 and above
   Surface acceleration:	524.90	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.538
   Length of year:		847.30	days
   Length of day:		17.85	hours


Planet 6	
   Distance from primary:	2.606	AU
   Mass:			0.500	Earth masses
   Equatorial radius:		5103.9	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.246	Earth atmospheres
   Surface temperature:		-101.77	degrees Celcius
   Normal daytime temperature:	-96.28	degrees Celcius
   Normal night temperature:	-107.52	degrees Celcius
   Maximum temperature:   	-75.08	degrees Celcius
   Minimum temperature:   	-130.32	degrees Celcius
   Escape Velocity:		8.84	km/sec
   Molecular weight retained:	10.17 and above
   Surface acceleration:	765.03	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.554
   Length of year:		1468.79	days
   Length of day:		17.33	hours
   Boiling point of water:	65.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	82.00
   liquids at surface:
				Ethanol      melts at -114  boils at 46
   gasses in atmosphere:
				Oxygen           10.8%  PP   26.7 mb
				Nitrogen         89.0%  PP  219.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.666	AU
   Mass:			494.249	Earth masses
   Equatorial radius:		70773.1	km
   Density:			1.989	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		74.63	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3935.03	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.487
   Length of year:		2448.54	days
   Length of day:		6.52	hours


Planet 8	*gas giant*
   Distance from primary:	8.755	AU
   Mass:			36.549	Earth masses
   Equatorial radius:		35602.5	km
   Density:			1.156	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		28.61	km/sec
   Molecular weight retained:	0.97 and above
   Surface acceleration:	1149.90	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.456
   Length of year:		9042.54	days
   Length of day:		12.05	hours


Planet 9	*gas giant*
   Distance from primary:	14.186	AU
   Mass:			654.412	Earth masses
   Equatorial radius:		85980.2	km
   Density:			1.469	grams/cc
   Eccentricity of orbit:	0.093
   Escape Velocity:		77.91	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3530.15	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.495
   Length of year:		18635.84	days
   Length of day:		6.88	hours


Planet 10	*gas giant*
   Distance from primary:	33.392	AU
   Mass:			18.481	Earth masses
   Equatorial radius:		32625.2	km
   Density:			0.759	grams/cc
   Eccentricity of orbit:	0.177
   Escape Velocity:		21.26	km/sec
   Molecular weight retained:	1.76 and above
   Surface acceleration:	692.41	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.462
   Length of year:		67357.12	days
   Length of day:		15.53	hours


Planet 11	
   Distance from primary:	48.863	AU
   Mass:			0.094	Earth masses
   Equatorial radius:		3933.8	km
   Density:			2.210	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.08	degrees Celcius
   Normal daytime temperature:	-224.36	degrees Celcius
   Normal night temperature:	-235.69	degrees Celcius
   Maximum temperature:   	-212.31	degrees Celcius
   Minimum temperature:   	-248.13	degrees Celcius
   Escape Velocity:		4.37	km/sec
   Molecular weight retained:	41.53 and above
   Surface acceleration:	242.93	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.138
   Length of year:		119235.75	days
   Length of day:		30.75	hours
   Boiling point of water:	-66.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


