                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504829c
Stellar mass: 1.10 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6192 K
Stellar class: F8
Age: 4.039 billion years  (2.931 billion left on main sequence)
Habitable ecosphere radius: 1.255 AU

Planets present at:
1	  0.423 AU	no atmosphere
2	  0.507 AU	no atmosphere
3	  0.776 AU	no atmosphere
4	  1.006 AU	greenhouse
5	  1.254 AU	high pressure
6	  1.651 AU	cold
7	  2.901 AU	gas giant
8	  5.004 AU	gas giant
9	  7.685 AU	no atmosphere
10	 15.800 AU	gas giant
11	 36.724 AU	no atmosphere
12	 48.506 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.423	AU
   Mass:			0.397	Earth masses
   Equatorial radius:		4733.1	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.137
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		200.09	degrees Celcius
   Normal daytime temperature:	405.99	degrees Celcius
   Normal night temperature:	-189.71	degrees Celcius
   Maximum temperature:   	409.40	degrees Celcius
   Minimum temperature:   	-200.68	degrees Celcius
   Escape Velocity:		8.18	km/sec
   Molecular weight retained:	11.86 and above
   Surface acceleration:	707.24	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.059
   Length of year:		95.84	days
   Length of day:		1744.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.507	AU
   Mass:			1/1177	Earth masses
   Equatorial radius:		613.6	km
   Density:			5.248	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.09	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.86	degrees Celcius
   Maximum temperature:   	356.63	degrees Celcius
   Minimum temperature:   	-214.79	degrees Celcius
   Escape Velocity:		1.05	km/sec
   Molecular weight retained:	718.78 and above
   Surface acceleration:	89.99	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.078
   Length of year:		125.77	days
   Length of day:		3018.44	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.776	AU
   Mass:			0.108	Earth masses
   Equatorial radius:		3081.7	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		74.32	degrees Celcius
   Maximum temperature:   	253.60	degrees Celcius
   Minimum temperature:   	-228.21	degrees Celcius
   Escape Velocity:		5.30	km/sec
   Molecular weight retained:	28.28 and above
   Surface acceleration:	455.44	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.079
   Length of year:		238.20	days
   Length of day:		5716.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.006	AU
   Mass:			0.418	Earth masses
   Equatorial radius:		4814.5	km
   Density:			5.350	grams/cc
   Eccentricity of orbit:	0.124
   Surface gravity:		0.73	Earth gees
   Surface pressure:		16.523	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		90.75	degrees Celcius
   Maximum temperature:   	99.83	degrees Celcius
   Minimum temperature:   	81.16	degrees Celcius
   Escape Velocity:		8.33	km/sec
   Molecular weight retained:	11.45 and above
   Surface acceleration:	719.87	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.511
   Length of year:		351.51	days
   Length of day:		20.06	hours
   Boiling point of water:	197.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 521
				Water        melts at 0     boils at 198
				Francium     melts at 27    boils at 925
				Cesium       melts at 28    boils at 960
				Gallium      melts at 30    boils at 3102
				Rubidium     melts at 39    boils at 939
				Phosphorus   melts at 44    boils at 425
				Potassium    melts at 63    boils at 1037
   gasses in atmosphere:
				Nitrogen         99.3%  PP 16415.2 mb
				CarbonDioxide     0.2%  PP   28.9 mb
				Methane           0.1%  PP    8.5 mb
				Ammonia           0.1%  PP    9.6 mb
				Ozone             0.2%  PP   29.2 mb
				Ethanol           0.2%  PP   29.6 mb


Planet 5	
   Distance from primary:	1.254	AU
   Mass:			2.633	Earth masses
   Equatorial radius:		8751.0	km
   Density:			5.607	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		1.40	Earth gees
   Surface pressure:		5.293	Earth atmospheres
   Surface temperature:		27.42	degrees Celcius
   Normal daytime temperature:	29.13	degrees Celcius
   Normal night temperature:	25.58	degrees Celcius
   Maximum temperature:   	40.21	degrees Celcius
   Minimum temperature:   	13.97	degrees Celcius
   Escape Velocity:		15.49	km/sec
   Molecular weight retained:	3.31 and above
   Surface acceleration:	1371.20	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.516
   Length of year:		489.34	days
   Length of day:		13.03	hours
   Boiling point of water:	152.3	degrees Celcius
   Hydrosphere percentage:	75.86
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.27
   liquids at surface:
				Ethanol      melts at -114  boils at 128
				Mercury      melts at -39   boils at 445
				Bromine      melts at -7    boils at 106
				Water        melts at 0     boils at 152
				Francium     melts at 27    boils at 810
   gasses in atmosphere:
				Nitrogen          0.7%  PP   34.9 mb
				Helium           99.3%  PP 5257.6 mb


Planet 6	
   Distance from primary:	1.651	AU
   Mass:			1.099	Earth masses
   Equatorial radius:		6604.7	km
   Density:			5.445	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		1.02	Earth gees
   Surface pressure:		1.189	Earth atmospheres
   Surface temperature:		-56.12	degrees Celcius
   Normal daytime temperature:	-53.14	degrees Celcius
   Normal night temperature:	-59.28	degrees Celcius
   Maximum temperature:   	-35.25	degrees Celcius
   Minimum temperature:   	-78.38	degrees Celcius
   Escape Velocity:		11.52	km/sec
   Molecular weight retained:	5.98 and above
   Surface acceleration:	1005.14	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.642
   Length of year:		739.44	days
   Length of day:		15.15	hours
   Boiling point of water:	104.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.36
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 83
				Chlorine     melts at -101  boils at -31
				Ammonia      melts at -78   boils at -30
   gasses in atmosphere:
				Oxygen            0.1%  PP    1.1 mb
				Nitrogen         99.8%  PP 1186.3 mb
				CarbonDioxide     0.1%  PP    0.7 mb
				Ozone             0.1%  PP    0.7 mb


Planet 7	*gas giant*
   Distance from primary:	2.901	AU
   Mass:			11.060	Earth masses
   Equatorial radius:		22899.6	km
   Density:			1.314	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		19.63	km/sec
   Molecular weight retained:	2.06 and above
   Surface acceleration:	841.11	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.462
   Length of year:		1722.44	days
   Length of day:		14.09	hours


Planet 8	*gas giant*
   Distance from primary:	5.004	AU
   Mass:			849.054	Earth masses
   Equatorial radius:		84994.9	km
   Density:			1.973	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		89.26	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4686.94	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.456
   Length of year:		3896.56	days
   Length of day:		5.97	hours


Planet 9	
   Distance from primary:	7.685	AU
   Mass:			0.122	Earth masses
   Equatorial radius:		4278.9	km
   Density:			2.214	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.010	Earth atmospheres
   Surface temperature:		-168.36	degrees Celcius
   Normal daytime temperature:	-156.22	degrees Celcius
   Normal night temperature:	-180.64	degrees Celcius
   Maximum temperature:   	-137.23	degrees Celcius
   Minimum temperature:   	-200.65	degrees Celcius
   Escape Velocity:		4.76	km/sec
   Molecular weight retained:	35.03 and above
   Surface acceleration:	264.78	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.267
   Length of year:		7424.69	days
   Length of day:		29.45	hours
   Boiling point of water:	6.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	20.45
   liquids at surface:
				Ozone        melts at -193  boils at -152
   gasses in atmosphere:
				Argon            100.0%  PP   10.5 mb


Planet 10	*gas giant*
   Distance from primary:	15.800	AU
   Mass:			540.885	Earth masses
   Equatorial radius:		82014.2	km
   Density:			1.399	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		72.53	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3206.76	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.515
   Length of year:		21873.00	days
   Length of day:		7.22	hours


Planet 11	
   Distance from primary:	36.724	AU
   Mass:			0.270	Earth masses
   Equatorial radius:		5568.1	km
   Density:			2.234	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-223.02	degrees Celcius
   Normal daytime temperature:	-217.34	degrees Celcius
   Normal night temperature:	-228.64	degrees Celcius
   Maximum temperature:   	-203.00	degrees Celcius
   Minimum temperature:   	-243.65	degrees Celcius
   Escape Velocity:		6.22	km/sec
   Molecular weight retained:	20.50 and above
   Surface acceleration:	347.68	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.140
   Length of year:		77568.12	days
   Length of day:		25.70	hours
   Boiling point of water:	-47.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 12	*gas giant*
   Distance from primary:	48.506	AU
   Mass:			0.323	Earth masses
   Equatorial radius:		10328.3	km
   Density:			0.418	grams/cc
   Eccentricity of orbit:	0.090
   Escape Velocity:		4.99	km/sec
   Molecular weight retained:	31.86 and above
   Surface acceleration:	120.60	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.527
   Length of year:		117744.53	days
   Length of day:		37.22	hours


