                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048339
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6307 K
Stellar class: F7
Age: 5.189 billion years  (1.762 billion left on main sequence)
Habitable ecosphere radius: 1.258 AU

Planets present at:
1	  0.320 AU	no atmosphere
2	  0.410 AU	no atmosphere
3	  0.593 AU	no atmosphere
4	  0.976 AU	greenhouse
5	  2.119 AU	gas giant
6	  4.175 AU	high pressure
7	  7.378 AU	gas giant
8	 17.027 AU	gas giant
9	 30.309 AU	gas giant
10	 48.179 AU	gas giant



Planet 1	
   Distance from primary:	0.320	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		2308.8	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		269.43	degrees Celcius
   Normal daytime temperature:	490.39	degrees Celcius
   Normal night temperature:	-174.28	degrees Celcius
   Maximum temperature:   	493.53	degrees Celcius
   Minimum temperature:   	-185.52	degrees Celcius
   Escape Velocity:		3.96	km/sec
   Molecular weight retained:	50.56 and above
   Surface acceleration:	340.02	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.070
   Length of year:		63.18	days
   Length of day:		1516.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.410	AU
   Mass:			0.194	Earth masses
   Equatorial radius:		3738.2	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		206.00	degrees Celcius
   Maximum temperature:   	416.81	degrees Celcius
   Minimum temperature:   	-203.33	degrees Celcius
   Escape Velocity:		6.44	km/sec
   Molecular weight retained:	19.15 and above
   Surface acceleration:	554.57	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.072
   Length of year:		91.55	days
   Length of day:		2197.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.593	AU
   Mass:			0.202	Earth masses
   Equatorial radius:		3788.2	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.45	degrees Celcius
   Maximum temperature:   	316.42	degrees Celcius
   Minimum temperature:   	-221.15	degrees Celcius
   Escape Velocity:		6.53	km/sec
   Molecular weight retained:	18.64 and above
   Surface acceleration:	562.16	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.081
   Length of year:		159.12	days
   Length of day:		3818.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.976	AU
   Mass:			2.203	Earth masses
   Equatorial radius:		8265.7	km
   Density:			5.565	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		1.31	Earth gees
   Surface pressure:		437.382	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		565.82	degrees Celcius
   Maximum temperature:   	567.49	degrees Celcius
   Minimum temperature:   	561.04	degrees Celcius
   Escape Velocity:		14.58	km/sec
   Molecular weight retained:	3.74 and above
   Surface acceleration:	1285.62	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.517
   Length of year:		335.68	days
   Length of day:		13.97	hours
   Boiling point of water:	404.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1451
				Cesium       melts at 28    boils at 1502
				Gallium      melts at 30    boils at 4584
				Rubidium     melts at 39    boils at 1471
				Potassium    melts at 63    boils at 1612
				Sodium       melts at 98    boils at 1823
				Indium       melts at 157   boils at 3998
				Lithium      melts at 181   boils at 2667
				Selenium     melts at 217   boils at 1466
				Tin          melts at 232   boils at 4984
				Polonium     melts at 254   boils at 1969
				Bismuth      melts at 271   boils at 3061
				Thallium     melts at 304   boils at 2867
				Cadmium      melts at 321   boils at 1611
				Lead         melts at 328   boils at 3401
				Zinc         melts at 420   boils at 1869
				Tellurium    melts at 450   boils at 2019
   gasses in atmosphere:
				Sulfur            0.5%  PP 2042.0 mb
				Nitrogen          1.9%  PP 8522.8 mb
				Helium           97.6%  PP 426759.1 mb


Planet 5	*gas giant*
   Distance from primary:	2.119	AU
   Mass:			23.013	Earth masses
   Equatorial radius:		27618.8	km
   Density:			1.559	grams/cc
   Eccentricity of orbit:	0.251
   Escape Velocity:		25.78	km/sec
   Molecular weight retained:	1.19 and above
   Surface acceleration:	1203.12	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.489
   Length of year:		1074.90	days
   Length of day:		11.78	hours


Planet 6	
   Distance from primary:	4.175	AU
   Mass:			3.637	Earth masses
   Equatorial radius:		9694.8	km
   Density:			5.696	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		1.57	Earth gees
   Surface pressure:		10.552	Earth atmospheres
   Surface temperature:		-112.66	degrees Celcius
   Maximum temperature:   	-104.71	degrees Celcius
   Minimum temperature:   	-121.10	degrees Celcius
   Escape Velocity:		17.30	km/sec
   Molecular weight retained:	2.65 and above
   Surface acceleration:	1543.20	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.696
   Length of year:		2972.58	days
   Length of day:		12.20	hours
   Boiling point of water:	178.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -78
				Ethanol      melts at -114  boils at 153
   gasses in atmosphere:
				Nitrogen          0.3%  PP   32.2 mb
				Helium           99.7%  PP 10519.3 mb


Planet 7	*gas giant*
   Distance from primary:	7.378	AU
   Mass:			1075.360	Earth masses
   Equatorial radius:		94039.2	km
   Density:			1.845	grams/cc
   Eccentricity of orbit:	0.120
   Escape Velocity:		95.50	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4849.26	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.503
   Length of year:		6971.83	days
   Length of day:		5.87	hours


Planet 8	*gas giant*
   Distance from primary:	17.027	AU
   Mass:			233.406	Earth masses
   Equatorial radius:		64576.1	km
   Density:			1.237	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		53.69	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2232.07	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.515
   Length of year:		24470.86	days
   Length of day:		8.65	hours


Planet 9	*gas giant*
   Distance from primary:	30.309	AU
   Mass:			1.344	Earth masses
   Equatorial radius:		15055.0	km
   Density:			0.562	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		8.44	km/sec
   Molecular weight retained:	11.15 and above
   Surface acceleration:	236.45	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.494
   Length of year:		58133.99	days
   Length of day:		26.58	hours


Planet 10	*gas giant*
   Distance from primary:	48.179	AU
   Mass:			0.439	Earth masses
   Equatorial radius:		11288.3	km
   Density:			0.435	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		5.57	km/sec
   Molecular weight retained:	25.61 and above
   Surface acceleration:	137.27	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.468
   Length of year:		116511.50	days
   Length of day:		34.88	hours


