                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d96
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6201 K
Stellar class: F8
Age: 3.619 billion years  (3.524 billion left on main sequence)
Habitable ecosphere radius: 1.236 AU

Planets present at:
1	  0.369 AU	no atmosphere
2	  0.530 AU	no atmosphere
3	  0.766 AU	no atmosphere
4	  0.910 AU	greenhouse
5	  1.202 AU	
6	  2.133 AU	cold
7	  2.949 AU	gas giant
8	  7.967 AU	gas giant
9	 16.137 AU	gas giant
10	 29.999 AU	gas giant
11	 46.760 AU	no atmosphere



Planet 1	
   Distance from primary:	0.369	AU
   Mass:			0.085	Earth masses
   Equatorial radius:		2845.9	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		227.27	degrees Celcius
   Maximum temperature:   	442.57	degrees Celcius
   Minimum temperature:   	-197.11	degrees Celcius
   Escape Velocity:		4.89	km/sec
   Molecular weight retained:	33.20 and above
   Surface acceleration:	420.10	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.074
   Length of year:		78.47	days
   Length of day:		1883.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.530	AU
   Mass:			0.134	Earth masses
   Equatorial radius:		3308.6	km
   Density:			5.295	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		142.86	degrees Celcius
   Maximum temperature:   	339.30	degrees Celcius
   Minimum temperature:   	-217.38	degrees Celcius
   Escape Velocity:		5.69	km/sec
   Molecular weight retained:	24.50 and above
   Surface acceleration:	489.58	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.090
   Length of year:		134.85	days
   Length of day:		3236.30	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.766	AU
   Mass:			0.153	Earth masses
   Equatorial radius:		3450.2	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.132
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		75.23	degrees Celcius
   Maximum temperature:   	254.95	degrees Celcius
   Minimum temperature:   	-227.76	degrees Celcius
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.51 and above
   Surface acceleration:	510.95	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.065
   Length of year:		234.42	days
   Length of day:		4318.05	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.910	AU
   Mass:			1.683	Earth masses
   Equatorial radius:		7580.4	km
   Density:			5.512	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		1.19	Earth gees
   Surface pressure:		237.660	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		467.06	degrees Celcius
   Maximum temperature:   	469.85	degrees Celcius
   Minimum temperature:   	462.17	degrees Celcius
   Escape Velocity:		13.31	km/sec
   Molecular weight retained:	4.48 and above
   Surface acceleration:	1167.74	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.604
   Length of year:		303.34	days
   Length of day:		14.86	hours
   Boiling point of water:	352.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1321
				Cesium       melts at 28    boils at 1368
				Gallium      melts at 30    boils at 4217
				Rubidium     melts at 39    boils at 1339
				Potassium    melts at 63    boils at 1470
				Sodium       melts at 98    boils at 1664
				Indium       melts at 157   boils at 3675
				Lithium      melts at 181   boils at 2445
				Selenium     melts at 217   boils at 1334
				Tin          melts at 232   boils at 4586
				Polonium     melts at 254   boils at 1799
				Bismuth      melts at 271   boils at 2809
				Thallium     melts at 304   boils at 2630
				Cadmium      melts at 321   boils at 1469
				Lead         melts at 328   boils at 3123
				Zinc         melts at 420   boils at 1707
				Tellurium    melts at 450   boils at 1846
   gasses in atmosphere:
				Sulfur           19.4%  PP 46077.8 mb
				Nitrogen         80.0%  PP 190211.4 mb
				Phosphorus        0.4%  PP  919.9 mb


Planet 5	
   Distance from primary:	1.202	AU
   Mass:			0.617	Earth masses
   Equatorial radius:		5469.2	km
   Density:			5.381	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.360	Earth atmospheres
   Surface temperature:		17.22	degrees Celcius
   Normal daytime temperature:	24.99	degrees Celcius
   Normal night temperature:	9.01	degrees Celcius
   Maximum temperature:   	50.68	degrees Celcius
   Minimum temperature:   	-18.07	degrees Celcius
   Escape Velocity:		9.49	km/sec
   Molecular weight retained:	8.82 and above
   Surface acceleration:	822.51	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.279
   Length of year:		460.78	days
   Length of day:		17.12	hours
   Boiling point of water:	73.8	degrees Celcius
   Hydrosphere percentage:	56.33
   Cloud cover percentage:	48.35
   Ice cover percentage:	1.20
   liquids at surface:
				Ethanol      melts at -114  boils at 54
				Mercury      melts at -39   boils at 313
				Bromine      melts at -7    boils at 36
				Water        melts at 0     boils at 74
   gasses in atmosphere:
				Oxygen           45.0%  PP  162.0 mb
				Nitrogen         54.8%  PP  197.1 mb


Planet 6	
   Distance from primary:	2.133	AU
   Mass:			0.524	Earth masses
   Equatorial radius:		5185.2	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.270	Earth atmospheres
   Surface temperature:		-80.95	degrees Celcius
   Normal daytime temperature:	-75.08	degrees Celcius
   Normal night temperature:	-87.12	degrees Celcius
   Maximum temperature:   	-51.70	degrees Celcius
   Minimum temperature:   	-112.13	degrees Celcius
   Escape Velocity:		8.98	km/sec
   Molecular weight retained:	9.84 and above
   Surface acceleration:	777.77	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.552
   Length of year:		1089.47	days
   Length of day:		17.20	hours
   Boiling point of water:	67.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	83.03
   liquids at surface:
				Ethanol      melts at -114  boils at 48
				Chlorine     melts at -101  boils at -55
   gasses in atmosphere:
				Oxygen           12.9%  PP   35.0 mb
				Nitrogen         86.9%  PP  234.7 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	2.949	AU
   Mass:			275.389	Earth masses
   Equatorial radius:		58640.7	km
   Density:			1.949	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		61.20	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	3193.64	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.541
   Length of year:		1770.36	days
   Length of day:		7.23	hours


Planet 8	*gas giant*
   Distance from primary:	7.967	AU
   Mass:			1156.433	Earth masses
   Equatorial radius:		96810.3	km
   Density:			1.819	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		97.61	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4920.59	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.491
   Length of year:		7849.98	days
   Length of day:		5.83	hours


Planet 9	*gas giant*
   Distance from primary:	16.137	AU
   Mass:			3.357	Earth masses
   Equatorial radius:		18682.8	km
   Density:			0.734	grams/cc
   Eccentricity of orbit:	0.146
   Escape Velocity:		11.97	km/sec
   Molecular weight retained:	5.54 and above
   Surface acceleration:	383.48	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.536
   Length of year:		22666.25	days
   Length of day:		20.87	hours


Planet 10	*gas giant*
   Distance from primary:	29.999	AU
   Mass:			19.447	Earth masses
   Equatorial radius:		32840.8	km
   Density:			0.783	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		21.73	km/sec
   Molecular weight retained:	1.68 and above
   Surface acceleration:	719.06	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.529
   Length of year:		57451.03	days
   Length of day:		15.24	hours


Planet 11	
   Distance from primary:	46.760	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		4578.8	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.62	degrees Celcius
   Normal daytime temperature:	-224.22	degrees Celcius
   Normal night temperature:	-234.92	degrees Celcius
   Maximum temperature:   	-207.50	degrees Celcius
   Minimum temperature:   	-251.53	degrees Celcius
   Escape Velocity:		5.10	km/sec
   Molecular weight retained:	30.54 and above
   Surface acceleration:	283.87	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.164
   Length of year:		111805.12	days
   Length of day:		28.45	hours
   Boiling point of water:	-57.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


