                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048ac5
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6327 K
Stellar class: F7
Age: 2.852 billion years  (3.850 billion left on main sequence)
Habitable ecosphere radius: 1.287 AU

Planets present at:
1	  0.336 AU	no atmosphere
2	  0.482 AU	no atmosphere
3	  0.600 AU	no atmosphere
4	  0.873 AU	greenhouse
5	  1.316 AU	high pressure
6	  1.676 AU	high pressure
7	  3.595 AU	gas giant
8	 12.527 AU	gas giant
9	 37.123 AU	gas giant



Planet 1	
   Distance from primary:	0.336	AU
   Mass:			0.095	Earth masses
   Equatorial radius:		2950.6	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		265.31	degrees Celcius
   Normal daytime temperature:	485.62	degrees Celcius
   Normal night temperature:	-177.16	degrees Celcius
   Maximum temperature:   	488.71	degrees Celcius
   Minimum temperature:   	-188.10	degrees Celcius
   Escape Velocity:		5.07	km/sec
   Molecular weight retained:	30.87 and above
   Surface acceleration:	435.78	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.051
   Length of year:		67.57	days
   Length of day:		1621.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.482	AU
   Mass:			0.287	Earth masses
   Equatorial radius:		4252.7	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		173.21	degrees Celcius
   Maximum temperature:   	376.78	degrees Celcius
   Minimum temperature:   	-211.61	degrees Celcius
   Escape Velocity:		7.34	km/sec
   Molecular weight retained:	14.74 and above
   Surface acceleration:	633.11	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.079
   Length of year:		116.03	days
   Length of day:		2784.79	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.600	AU
   Mass:			0.057	Earth masses
   Equatorial radius:		2489.8	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		127.39	degrees Celcius
   Maximum temperature:   	320.30	degrees Celcius
   Minimum temperature:   	-221.48	degrees Celcius
   Escape Velocity:		4.27	km/sec
   Molecular weight retained:	43.45 and above
   Surface acceleration:	366.94	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.076
   Length of year:		160.97	days
   Length of day:		3863.36	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.873	AU
   Mass:			1.183	Earth masses
   Equatorial radius:		6764.1	km
   Density:			5.456	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		1.05	Earth gees
   Surface pressure:		118.235	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		484.30	degrees Celcius
   Maximum temperature:   	488.02	degrees Celcius
   Minimum temperature:   	478.21	degrees Celcius
   Escape Velocity:		11.81	km/sec
   Molecular weight retained:	5.69 and above
   Surface acceleration:	1031.32	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.426
   Length of year:		282.90	days
   Length of day:		16.19	hours
   Boiling point of water:	303.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1194
				Cesium       melts at 28    boils at 1237
				Gallium      melts at 30    boils at 3860
				Rubidium     melts at 39    boils at 1211
				Potassium    melts at 63    boils at 1331
				Sodium       melts at 98    boils at 1510
				Indium       melts at 157   boils at 3361
				Lithium      melts at 181   boils at 2229
				Selenium     melts at 217   boils at 1206
				Tin          melts at 232   boils at 4199
				Polonium     melts at 254   boils at 1634
				Bismuth      melts at 271   boils at 2564
				Thallium     melts at 304   boils at 2399
				Cadmium      melts at 321   boils at 1330
				Lead         melts at 328   boils at 2853
				Zinc         melts at 420   boils at 1549
				Tellurium    melts at 450   boils at 1677
   gasses in atmosphere:
				Sulfur           20.6%  PP 24409.2 mb
				Nitrogen         78.7%  PP 93086.2 mb
				Phosphorus        0.4%  PP  486.6 mb


Planet 5	
   Distance from primary:	1.316	AU
   Mass:			2.124	Earth masses
   Equatorial radius:		8170.2	km
   Density:			5.558	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		1.29	Earth gees
   Surface pressure:		4.129	Earth atmospheres
   Surface temperature:		-12.26	degrees Celcius
   Normal daytime temperature:	-10.51	degrees Celcius
   Normal night temperature:	-14.12	degrees Celcius
   Maximum temperature:   	2.02	degrees Celcius
   Minimum temperature:   	-27.33	degrees Celcius
   Escape Velocity:		14.40	km/sec
   Molecular weight retained:	3.83 and above
   Surface acceleration:	1269.00	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.303
   Length of year:		523.61	days
   Length of day:		13.51	hours
   Boiling point of water:	143.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	8.84
   Ice cover percentage:	23.31
   liquids at surface:
				Ethanol      melts at -114  boils at 120
				Mercury      melts at -39   boils at 431
   gasses in atmosphere:
				Nitrogen          2.3%  PP   94.4 mb
				Helium           97.7%  PP 4034.4 mb


Planet 6	
   Distance from primary:	1.676	AU
   Mass:			1.797	Earth masses
   Equatorial radius:		7742.2	km
   Density:			5.524	grams/cc
   Eccentricity of orbit:	0.156
   Surface gravity:		1.22	Earth gees
   Surface pressure:		2.403	Earth atmospheres
   Surface temperature:		-3.97	degrees Celcius
   Normal daytime temperature:	-1.55	degrees Celcius
   Normal night temperature:	-6.53	degrees Celcius
   Maximum temperature:   	15.18	degrees Celcius
   Minimum temperature:   	-24.22	degrees Celcius
   Escape Velocity:		13.60	km/sec
   Molecular weight retained:	4.29 and above
   Surface acceleration:	1195.28	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.250
   Length of year:		752.57	days
   Length of day:		13.88	hours
   Boiling point of water:	125.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	11.58
   Ice cover percentage:	12.71
   liquids at surface:
				Ethanol      melts at -114  boils at 103
				Mercury      melts at -39   boils at 400
				Bromine      melts at -7    boils at 83
   gasses in atmosphere:
				Nitrogen         99.8%  PP 2398.6 mb


Planet 7	*gas giant*
   Distance from primary:	3.595	AU
   Mass:			435.493	Earth masses
   Equatorial radius:		67913.2	km
   Density:			1.984	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		71.52	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3765.41	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.471
   Length of year:		2361.72	days
   Length of day:		6.66	hours


Planet 8	*gas giant*
   Distance from primary:	12.527	AU
   Mass:			751.813	Earth masses
   Equatorial radius:		88369.0	km
   Density:			1.555	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		82.37	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3839.27	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.492
   Length of year:		15358.23	days
   Length of day:		6.60	hours


Planet 9	*gas giant*
   Distance from primary:	37.123	AU
   Mass:			3.438	Earth masses
   Equatorial radius:		20098.2	km
   Density:			0.604	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		11.68	km/sec
   Molecular weight retained:	5.82 and above
   Surface acceleration:	339.37	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.484
   Length of year:		78427.36	days
   Length of day:		22.19	hours


