                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048889
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6387 K
Stellar class: F7
Age: 2.177 billion years  (4.597 billion left on main sequence)
Habitable ecosphere radius: 1.278 AU

Planets present at:
1	  0.369 AU	no atmosphere
2	  0.514 AU	no atmosphere
3	  0.831 AU	no atmosphere
4	  1.083 AU	greenhouse
5	  1.506 AU	gas giant
6	  1.778 AU	cold
7	  3.763 AU	gas giant
8	  8.273 AU	gas giant
9	 13.032 AU	cold
10	 28.793 AU	gas giant
11	 49.275 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.369	AU
   Mass:			0.100	Earth masses
   Equatorial radius:		2995.7	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.159
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		234.21	degrees Celcius
   Normal daytime temperature:	446.97	degrees Celcius
   Normal night temperature:	-176.31	degrees Celcius
   Maximum temperature:   	450.72	degrees Celcius
   Minimum temperature:   	-189.34	degrees Celcius
   Escape Velocity:		5.15	km/sec
   Molecular weight retained:	29.94 and above
   Surface acceleration:	442.54	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.088
   Length of year:		77.75	days
   Length of day:		1353.43	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.514	AU
   Mass:			0.438	Earth masses
   Equatorial radius:		4887.8	km
   Density:			5.353	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.82	degrees Celcius
   Maximum temperature:   	356.67	degrees Celcius
   Minimum temperature:   	-215.20	degrees Celcius
   Escape Velocity:		8.46	km/sec
   Molecular weight retained:	11.10 and above
   Surface acceleration:	731.28	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.087
   Length of year:		127.85	days
   Length of day:		3068.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.831	AU
   Mass:			0.186	Earth masses
   Equatorial radius:		3686.2	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.153
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		66.23	degrees Celcius
   Normal daytime temperature:	112.87	degrees Celcius
   Normal night temperature:	18.74	degrees Celcius
   Maximum temperature:   	146.98	degrees Celcius
   Minimum temperature:   	-16.33	degrees Celcius
   Escape Velocity:		6.35	km/sec
   Molecular weight retained:	19.70 and above
   Surface acceleration:	546.68	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.074
   Length of year:		262.85	days
   Length of day:		32.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.083	AU
   Mass:			0.801	Earth masses
   Equatorial radius:		5957.6	km
   Density:			5.407	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.92	Earth gees
   Surface pressure:		67.277	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		313.88	degrees Celcius
   Maximum temperature:   	319.07	degrees Celcius
   Minimum temperature:   	307.65	degrees Celcius
   Escape Velocity:		10.36	km/sec
   Molecular weight retained:	7.40 and above
   Surface acceleration:	900.29	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.431
   Length of year:		391.23	days
   Length of day:		16.34	hours
   Boiling point of water:	268.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 641
				Francium     melts at 27    boils at 1105
				Cesium       melts at 28    boils at 1146
				Gallium      melts at 30    boils at 3610
				Rubidium     melts at 39    boils at 1121
				Potassium    melts at 63    boils at 1234
				Sodium       melts at 98    boils at 1402
				Sulfur       melts at 113   boils at 769
				Indium       melts at 157   boils at 3141
				Lithium      melts at 181   boils at 2078
				Selenium     melts at 217   boils at 1117
				Tin          melts at 232   boils at 3929
				Polonium     melts at 254   boils at 1519
				Bismuth      melts at 271   boils at 2392
				Astatine     melts at 302   boils at 612
				Thallium     melts at 304   boils at 2237
   gasses in atmosphere:
				Nitrogen         99.1%  PP 66677.7 mb
				Phosphorus        0.6%  PP  393.1 mb
				CarbonDioxide     0.1%  PP   42.7 mb
				Ozone             0.1%  PP   40.6 mb
				Ethanol           0.1%  PP   43.2 mb


Planet 5	*gas giant*
   Distance from primary:	1.506	AU
   Mass:			4.209	Earth masses
   Equatorial radius:		16332.5	km
   Density:			1.378	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		14.34	km/sec
   Molecular weight retained:	3.86 and above
   Surface acceleration:	629.20	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.472
   Length of year:		641.67	days
   Length of day:		16.30	hours


Planet 6	
   Distance from primary:	1.778	AU
   Mass:			1.161	Earth masses
   Equatorial radius:		6723.1	km
   Density:			5.453	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		1.04	Earth gees
   Surface pressure:		1.264	Earth atmospheres
   Surface temperature:		-73.48	degrees Celcius
   Normal daytime temperature:	-70.84	degrees Celcius
   Normal night temperature:	-76.27	degrees Celcius
   Maximum temperature:   	-54.14	degrees Celcius
   Minimum temperature:   	-94.17	degrees Celcius
   Escape Velocity:		11.74	km/sec
   Molecular weight retained:	5.76 and above
   Surface acceleration:	1024.59	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.716
   Length of year:		823.54	days
   Length of day:		14.99	hours
   Boiling point of water:	106.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.10
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 85
				Chlorine     melts at -101  boils at -30
				Ammonia      melts at -78   boils at -29
   gasses in atmosphere:
				Oxygen            4.7%  PP   59.6 mb
				Nitrogen         95.1%  PP 1203.1 mb


Planet 7	*gas giant*
   Distance from primary:	3.763	AU
   Mass:			457.953	Earth masses
   Equatorial radius:		69218.6	km
   Density:			1.970	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		72.64	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3811.66	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.518
   Length of year:		2532.80	days
   Length of day:		6.62	hours


Planet 8	*gas giant*
   Distance from primary:	8.273	AU
   Mass:			163.201	Earth masses
   Equatorial radius:		54706.5	km
   Density:			1.422	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		48.78	km/sec
   Molecular weight retained:	0.33 and above
   Surface acceleration:	2174.62	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.454
   Length of year:		8259.90	days
   Length of day:		8.76	hours


Planet 9	
   Distance from primary:	13.032	AU
   Mass:			0.511	Earth masses
   Equatorial radius:		6858.1	km
   Density:			2.260	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.207	Earth atmospheres
   Surface temperature:		-188.73	degrees Celcius
   Normal daytime temperature:	-184.99	degrees Celcius
   Normal night temperature:	-192.68	degrees Celcius
   Maximum temperature:   	-168.94	degrees Celcius
   Minimum temperature:   	-210.45	degrees Celcius
   Escape Velocity:		7.71	km/sec
   Molecular weight retained:	13.36 and above
   Surface acceleration:	433.18	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.370
   Length of year:		16335.75	days
   Length of day:		23.03	hours
   Boiling point of water:	61.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	37.31
   liquids at surface:
				Ozone        melts at -193  boils at -129
   gasses in atmosphere:
				Nitrogen         100.0%  PP  206.7 mb


Planet 10	*gas giant*
   Distance from primary:	28.793	AU
   Mass:			140.140	Earth masses
   Equatorial radius:		58060.4	km
   Density:			1.022	grams/cc
   Eccentricity of orbit:	0.363
   Escape Velocity:		43.88	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1657.84	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.452
   Length of year:		53637.38	days
   Length of day:		10.04	hours


Planet 11	
   Distance from primary:	49.275	AU
   Mass:			0.096	Earth masses
   Equatorial radius:		3961.7	km
   Density:			2.210	grams/cc
   Eccentricity of orbit:	0.108
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.95	degrees Celcius
   Normal daytime temperature:	-224.23	degrees Celcius
   Normal night temperature:	-235.56	degrees Celcius
   Maximum temperature:   	-210.36	degrees Celcius
   Minimum temperature:   	-249.64	degrees Celcius
   Escape Velocity:		4.40	km/sec
   Molecular weight retained:	40.94 and above
   Surface acceleration:	244.70	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.158
   Length of year:		120101.72	days
   Length of day:		30.64	hours
   Boiling point of water:	-63.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


