                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d0a
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6329 K
Stellar class: F7
Age: 1.273 billion years  (5.890 billion left on main sequence)
Habitable ecosphere radius: 1.234 AU

Planets present at:
1	  0.318 AU	no atmosphere
2	  0.559 AU	no atmosphere
3	  0.661 AU	no atmosphere
4	  0.833 AU	greenhouse
5	  1.533 AU	gas giant
6	  3.072 AU	gas giant
7	  5.368 AU	gas giant
8	 10.252 AU	no atmosphere
9	 12.269 AU	gas giant
10	 19.837 AU	gas giant
11	 30.260 AU	gas giant
12	 41.739 AU	gas giant
13	 50.886 AU	no atmosphere



Planet 1	
   Distance from primary:	0.318	AU
   Mass:			0.091	Earth masses
   Equatorial radius:		2912.5	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		268.56	degrees Celcius
   Normal daytime temperature:	489.30	degrees Celcius
   Normal night temperature:	-174.14	degrees Celcius
   Maximum temperature:   	492.36	degrees Celcius
   Minimum temperature:   	-185.05	degrees Celcius
   Escape Velocity:		5.01	km/sec
   Molecular weight retained:	31.69 and above
   Surface acceleration:	430.07	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.056
   Length of year:		62.65	days
   Length of day:		1503.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.559	AU
   Mass:			0.128	Earth masses
   Equatorial radius:		3254.8	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.130
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		132.85	degrees Celcius
   Maximum temperature:   	326.95	degrees Celcius
   Minimum temperature:   	-217.72	degrees Celcius
   Escape Velocity:		5.60	km/sec
   Molecular weight retained:	25.33 and above
   Surface acceleration:	481.47	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.078
   Length of year:		146.14	days
   Length of day:		2698.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.661	AU
   Mass:			0.110	Earth masses
   Equatorial radius:		3092.3	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		101.54	degrees Celcius
   Maximum temperature:   	287.84	degrees Celcius
   Minimum temperature:   	-224.97	degrees Celcius
   Escape Velocity:		5.32	km/sec
   Molecular weight retained:	28.08 and above
   Surface acceleration:	457.04	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.065
   Length of year:		187.93	days
   Length of day:		4510.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.833	AU
   Mass:			0.964	Earth masses
   Equatorial radius:		6328.0	km
   Density:			5.429	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.98	Earth gees
   Surface pressure:		92.173	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		426.53	degrees Celcius
   Maximum temperature:   	430.99	degrees Celcius
   Minimum temperature:   	420.24	degrees Celcius
   Escape Velocity:		11.02	km/sec
   Molecular weight retained:	6.53 and above
   Surface acceleration:	960.04	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.519
   Length of year:		266.14	days
   Length of day:		16.33	hours
   Boiling point of water:	287.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1153
				Cesium       melts at 28    boils at 1196
				Gallium      melts at 30    boils at 3745
				Rubidium     melts at 39    boils at 1170
				Potassium    melts at 63    boils at 1287
				Sodium       melts at 98    boils at 1461
				Sulfur       melts at 113   boils at 805
				Indium       melts at 157   boils at 3260
				Lithium      melts at 181   boils at 2160
				Selenium     melts at 217   boils at 1165
				Tin          melts at 232   boils at 4076
				Polonium     melts at 254   boils at 1581
				Bismuth      melts at 271   boils at 2485
				Thallium     melts at 304   boils at 2325
				Cadmium      melts at 321   boils at 1286
				Lead         melts at 328   boils at 2766
				Zinc         melts at 420   boils at 1499
   gasses in atmosphere:
				Nitrogen         99.2%  PP 91437.5 mb
				Phosphorus        0.5%  PP  479.4 mb
				CarbonDioxide     0.1%  PP   50.9 mb
				Ozone             0.1%  PP   48.9 mb
				Ethanol           0.1%  PP   51.4 mb


Planet 5	*gas giant*
   Distance from primary:	1.533	AU
   Mass:			9.229	Earth masses
   Equatorial radius:		20626.7	km
   Density:			1.501	grams/cc
   Eccentricity of orbit:	0.114
   Escape Velocity:		18.89	km/sec
   Molecular weight retained:	2.22 and above
   Surface acceleration:	865.03	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.455
   Length of year:		663.89	days
   Length of day:		13.90	hours


Planet 6	*gas giant*
   Distance from primary:	3.072	AU
   Mass:			196.708	Earth masses
   Equatorial radius:		53348.2	km
   Density:			1.849	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		54.23	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2756.27	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.455
   Length of year:		1883.11	days
   Length of day:		7.78	hours


Planet 7	*gas giant*
   Distance from primary:	5.368	AU
   Mass:			353.771	Earth masses
   Equatorial radius:		66322.3	km
   Density:			1.730	grams/cc
   Eccentricity of orbit:	0.154
   Escape Velocity:		65.23	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3207.33	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.486
   Length of year:		4347.82	days
   Length of day:		7.22	hours


Planet 8	
   Distance from primary:	10.252	AU
   Mass:			0.310	Earth masses
   Equatorial radius:		5824.4	km
   Density:			2.239	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.058	Earth atmospheres
   Surface temperature:		-178.77	degrees Celcius
   Normal daytime temperature:	-171.75	degrees Celcius
   Normal night temperature:	-186.03	degrees Celcius
   Maximum temperature:   	-154.58	degrees Celcius
   Minimum temperature:   	-204.67	degrees Celcius
   Escape Velocity:		6.52	km/sec
   Molecular weight retained:	18.70 and above
   Surface acceleration:	364.44	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.289
   Length of year:		11481.43	days
   Length of day:		25.10	hours
   Boiling point of water:	35.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.09
   liquids at surface:
				Ozone        melts at -193  boils at -140
   gasses in atmosphere:
				Fluorine         42.0%  PP   24.6 mb
				Argon            10.2%  PP    6.0 mb
				Neon             47.7%  PP   27.9 mb


Planet 9	*gas giant*
   Distance from primary:	12.269	AU
   Mass:			29.834	Earth masses
   Equatorial radius:		34540.3	km
   Density:			1.033	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		26.25	km/sec
   Molecular weight retained:	1.15 and above
   Surface acceleration:	997.25	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.460
   Length of year:		15030.82	days
   Length of day:		12.94	hours


Planet 10	*gas giant*
   Distance from primary:	19.837	AU
   Mass:			8.919	Earth masses
   Equatorial radius:		25279.6	km
   Density:			0.788	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		16.78	km/sec
   Molecular weight retained:	2.82 and above
   Surface acceleration:	556.59	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.529
   Length of year:		30903.22	days
   Length of day:		17.32	hours


Planet 11	*gas giant*
   Distance from primary:	30.260	AU
   Mass:			0.435	Earth masses
   Equatorial radius:		10852.7	km
   Density:			0.486	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		5.66	km/sec
   Molecular weight retained:	24.81 and above
   Surface acceleration:	147.41	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.472
   Length of year:		58223.12	days
   Length of day:		33.66	hours


Planet 12	*gas giant*
   Distance from primary:	41.739	AU
   Mass:			2.117	Earth masses
   Equatorial radius:		17681.3	km
   Density:			0.546	grams/cc
   Eccentricity of orbit:	0.118
   Escape Velocity:		9.77	km/sec
   Molecular weight retained:	8.31 and above
   Surface acceleration:	270.05	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.545
   Length of year:		94320.27	days
   Length of day:		24.87	hours


Planet 13	
   Distance from primary:	50.886	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		2026.2	km
   Density:			2.192	grams/cc
   Eccentricity of orbit:	0.145
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.27	degrees Celcius
   Normal daytime temperature:	-223.88	degrees Celcius
   Normal night temperature:	-238.49	degrees Celcius
   Maximum temperature:   	-208.06	degrees Celcius
   Minimum temperature:   	-253.59	degrees Celcius
   Escape Velocity:		2.24	km/sec
   Molecular weight retained:	157.81 and above
   Surface acceleration:	124.13	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.146
   Length of year:		126968.44	days
   Length of day:		43.02	hours
   Boiling point of water:	-94.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


