                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048703
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6154 K
Stellar class: F8
Age: 5.629 billion years  (1.195 billion left on main sequence)
Habitable ecosphere radius: 1.272 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.484 AU	no atmosphere
3	  0.590 AU	no atmosphere
4	  1.426 AU	high pressure
5	  2.372 AU	gas giant
6	  3.499 AU	gas giant
7	  7.236 AU	gas giant
8	 14.438 AU	gas giant
9	 25.550 AU	gas giant
10	 45.156 AU	gas giant



Planet 1	
   Distance from primary:	0.370	AU
   Mass:			0.017	Earth masses
   Equatorial radius:		1667.0	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		235.11	degrees Celcius
   Maximum temperature:   	452.18	degrees Celcius
   Minimum temperature:   	-196.02	degrees Celcius
   Escape Velocity:		2.86	km/sec
   Molecular weight retained:	97.19 and above
   Surface acceleration:	244.98	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.066
   Length of year:		78.29	days
   Length of day:		1878.91	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.484	AU
   Mass:			0.447	Earth masses
   Equatorial radius:		4920.9	km
   Density:			5.355	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		171.86	degrees Celcius
   Maximum temperature:   	375.18	degrees Celcius
   Minimum temperature:   	-212.08	degrees Celcius
   Escape Velocity:		8.51	km/sec
   Molecular weight retained:	10.95 and above
   Surface acceleration:	736.43	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.062
   Length of year:		116.99	days
   Length of day:		2807.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.590	AU
   Mass:			0.077	Earth masses
   Equatorial radius:		2752.2	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		129.05	degrees Celcius
   Maximum temperature:   	322.32	degrees Celcius
   Minimum temperature:   	-220.98	degrees Celcius
   Escape Velocity:		4.73	km/sec
   Molecular weight retained:	35.51 and above
   Surface acceleration:	406.09	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.069
   Length of year:		157.65	days
   Length of day:		3783.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.426	AU
   Mass:			3.191	Earth masses
   Equatorial radius:		9302.0	km
   Density:			5.657	grams/cc
   Eccentricity of orbit:	0.325
   Surface gravity:		1.50	Earth gees
   Surface pressure:		10.950	Earth atmospheres
   Surface temperature:		41.34	degrees Celcius
   Normal daytime temperature:	42.54	degrees Celcius
   Normal night temperature:	40.04	degrees Celcius
   Maximum temperature:   	52.60	degrees Celcius
   Minimum temperature:   	29.56	degrees Celcius
   Escape Velocity:		16.54	km/sec
   Molecular weight retained:	2.90 and above
   Surface acceleration:	1470.67	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.495
   Length of year:		591.71	days
   Length of day:		12.54	hours
   Boiling point of water:	180.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.01
   liquids at surface:
				Ethanol      melts at -114  boils at 154
				Mercury      melts at -39   boils at 492
				Bromine      melts at -7    boils at 131
				Water        melts at 0     boils at 180
				Francium     melts at 27    boils at 881
				Cesium       melts at 28    boils at 915
				Gallium      melts at 30    boils at 2977
				Rubidium     melts at 39    boils at 894
   gasses in atmosphere:
				Nitrogen          0.5%  PP   49.8 mb
				Helium           99.5%  PP 10900.4 mb


Planet 5	*gas giant*
   Distance from primary:	2.372	AU
   Mass:			3.330	Earth masses
   Equatorial radius:		15849.5	km
   Density:			1.194	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		12.95	km/sec
   Molecular weight retained:	4.74 and above
   Surface acceleration:	528.71	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.505
   Length of year:		1269.70	days
   Length of day:		17.78	hours


Planet 6	*gas giant*
   Distance from primary:	3.499	AU
   Mass:			2.173	Earth masses
   Equatorial radius:		14454.7	km
   Density:			1.027	grams/cc
   Eccentricity of orbit:	0.097
   Escape Velocity:		10.95	km/sec
   Molecular weight retained:	6.62 and above
   Surface acceleration:	414.78	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.521
   Length of year:		2274.79	days
   Length of day:		20.07	hours


Planet 7	*gas giant*
   Distance from primary:	7.236	AU
   Mass:			2513.832	Earth masses
   Equatorial radius:		120157.6	km
   Density:			2.068	grams/cc
   Eccentricity of orbit:	0.251
   Escape Velocity:		129.17	km/sec
   Molecular weight retained:	0.05 and above
   Surface acceleration:	6943.41	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.505
   Length of year:		6742.86	days
   Length of day:		4.90	hours


Planet 8	*gas giant*
   Distance from primary:	14.438	AU
   Mass:			56.216	Earth masses
   Equatorial radius:		42010.6	km
   Density:			1.082	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		32.67	km/sec
   Molecular weight retained:	0.74 and above
   Surface acceleration:	1270.22	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.468
   Length of year:		19065.11	days
   Length of day:		11.47	hours


Planet 9	*gas giant*
   Distance from primary:	25.550	AU
   Mass:			1.707	Earth masses
   Equatorial radius:		15899.6	km
   Density:			0.606	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		9.25	km/sec
   Molecular weight retained:	9.27 and above
   Surface acceleration:	269.30	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.487
   Length of year:		44886.63	days
   Length of day:		24.91	hours


Planet 10	*gas giant*
   Distance from primary:	45.156	AU
   Mass:			1.464	Earth masses
   Equatorial radius:		15943.0	km
   Density:			0.516	grams/cc
   Eccentricity of orbit:	0.150
   Escape Velocity:		8.56	km/sec
   Molecular weight retained:	10.84 and above
   Surface acceleration:	229.75	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.496
   Length of year:		105464.68	days
   Length of day:		26.96	hours


