                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048447
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6155 K
Stellar class: F8
Age: 4.928 billion years  (1.987 billion left on main sequence)
Habitable ecosphere radius: 1.262 AU

Planets present at:
1	  0.327 AU	no atmosphere
2	  0.413 AU	no atmosphere
3	  0.483 AU	no atmosphere
4	  0.762 AU	no atmosphere
5	  1.037 AU	greenhouse
6	  1.745 AU	gas giant
7	  2.429 AU	gas giant
8	  5.459 AU	gas giant
9	 14.376 AU	gas giant
10	 29.703 AU	no atmosphere
11	 35.376 AU	no atmosphere
12	 48.822 AU	gas giant



Planet 1	
   Distance from primary:	0.327	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2234.5	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		262.80	degrees Celcius
   Normal daytime temperature:	482.43	degrees Celcius
   Normal night temperature:	-176.32	degrees Celcius
   Maximum temperature:   	485.55	degrees Celcius
   Minimum temperature:   	-187.33	degrees Celcius
   Escape Velocity:		3.83	km/sec
   Molecular weight retained:	53.99 and above
   Surface acceleration:	328.98	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.085
   Length of year:		64.99	days
   Length of day:		1559.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.413	AU
   Mass:			0.213	Earth masses
   Equatorial radius:		3851.8	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		204.73	degrees Celcius
   Maximum temperature:   	415.23	degrees Celcius
   Minimum temperature:   	-203.54	degrees Celcius
   Escape Velocity:		6.64	km/sec
   Molecular weight retained:	18.02 and above
   Surface acceleration:	571.85	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.076
   Length of year:		92.42	days
   Length of day:		2218.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.483	AU
   Mass:			0.077	Earth masses
   Equatorial radius:		2748.1	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		168.33	degrees Celcius
   Maximum temperature:   	370.73	degrees Celcius
   Minimum temperature:   	-212.28	degrees Celcius
   Escape Velocity:		4.72	km/sec
   Molecular weight retained:	35.62 and above
   Surface acceleration:	405.48	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.078
   Length of year:		117.01	days
   Length of day:		2808.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.762	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		1837.7	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.291
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		77.62	degrees Celcius
   Maximum temperature:   	258.08	degrees Celcius
   Minimum temperature:   	-226.97	degrees Celcius
   Escape Velocity:		3.15	km/sec
   Molecular weight retained:	79.94 and above
   Surface acceleration:	270.19	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.088
   Length of year:		231.42	days
   Length of day:		3047.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.037	AU
   Mass:			1.084	Earth masses
   Equatorial radius:		6574.5	km
   Density:			5.444	grams/cc
   Eccentricity of orbit:	0.208
   Surface gravity:		1.02	Earth gees
   Surface pressure:		96.268	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		380.80	degrees Celcius
   Maximum temperature:   	385.38	degrees Celcius
   Minimum temperature:   	374.77	degrees Celcius
   Escape Velocity:		11.47	km/sec
   Molecular weight retained:	6.04 and above
   Surface acceleration:	1000.21	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.471
   Length of year:		367.41	days
   Length of day:		15.97	hours
   Boiling point of water:	289.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1160
				Cesium       melts at 28    boils at 1203
				Gallium      melts at 30    boils at 3765
				Rubidium     melts at 39    boils at 1177
				Potassium    melts at 63    boils at 1294
				Sodium       melts at 98    boils at 1469
				Sulfur       melts at 113   boils at 810
				Indium       melts at 157   boils at 3277
				Lithium      melts at 181   boils at 2171
				Selenium     melts at 217   boils at 1172
				Tin          melts at 232   boils at 4097
				Polonium     melts at 254   boils at 1590
				Bismuth      melts at 271   boils at 2499
				Thallium     melts at 304   boils at 2337
				Cadmium      melts at 321   boils at 1293
				Lead         melts at 328   boils at 2781
   gasses in atmosphere:
				Nitrogen         99.1%  PP 95439.3 mb
				Phosphorus        0.6%  PP  550.2 mb
				CarbonDioxide     0.1%  PP   60.8 mb
				Ozone             0.1%  PP   49.3 mb
				Ethanol           0.1%  PP   61.7 mb


Planet 6	*gas giant*
   Distance from primary:	1.745	AU
   Mass:			44.409	Earth masses
   Equatorial radius:		32910.1	km
   Density:			1.778	grams/cc
   Eccentricity of orbit:	0.127
   Escape Velocity:		32.81	km/sec
   Molecular weight retained:	0.74 and above
   Surface acceleration:	1635.15	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.519
   Length of year:		802.66	days
   Length of day:		10.11	hours


Planet 7	*gas giant*
   Distance from primary:	2.429	AU
   Mass:			2.917	Earth masses
   Equatorial radius:		15289.7	km
   Density:			1.165	grams/cc
   Eccentricity of orbit:	0.101
   Escape Velocity:		12.34	km/sec
   Molecular weight retained:	5.22 and above
   Surface acceleration:	497.62	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.548
   Length of year:		1318.32	days
   Length of day:		18.32	hours


Planet 8	*gas giant*
   Distance from primary:	5.459	AU
   Mass:			923.486	Earth masses
   Equatorial radius:		87701.2	km
   Density:			1.953	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		91.64	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4788.05	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.462
   Length of year:		4435.37	days
   Length of day:		5.91	hours


Planet 9	*gas giant*
   Distance from primary:	14.376	AU
   Mass:			587.006	Earth masses
   Equatorial radius:		83301.4	km
   Density:			1.449	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		74.97	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3373.48	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.549
   Length of year:		18962.90	days
   Length of day:		7.04	hours


Planet 10	
   Distance from primary:	29.703	AU
   Mass:			0.346	Earth masses
   Equatorial radius:		6039.0	km
   Density:			2.243	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.09	degrees Celcius
   Normal daytime temperature:	-210.97	degrees Celcius
   Normal night temperature:	-223.15	degrees Celcius
   Maximum temperature:   	-199.76	degrees Celcius
   Minimum temperature:   	-235.23	degrees Celcius
   Escape Velocity:		6.76	km/sec
   Molecular weight retained:	17.36 and above
   Surface acceleration:	378.56	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.160
   Length of year:		56361.53	days
   Length of day:		24.63	hours
   Boiling point of water:	-39.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   liquids at surface:
				Fluorine     melts at -220  boils at -216
				Oxygen       melts at -218  boils at -213
   gasses in atmosphere:
				Neon             100.0%  PP    0.3 mb


Planet 11	
   Distance from primary:	35.376	AU
   Mass:			0.081	Earth masses
   Equatorial radius:		3739.1	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-222.37	degrees Celcius
   Normal daytime temperature:	-215.47	degrees Celcius
   Normal night temperature:	-229.19	degrees Celcius
   Maximum temperature:   	-200.02	degrees Celcius
   Minimum temperature:   	-245.02	degrees Celcius
   Escape Velocity:		4.15	km/sec
   Molecular weight retained:	46.02 and above
   Surface acceleration:	230.67	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.146
   Length of year:		73256.56	days
   Length of day:		31.56	hours
   Boiling point of water:	-67.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 12	*gas giant*
   Distance from primary:	48.822	AU
   Mass:			0.729	Earth masses
   Equatorial radius:		13101.8	km
   Density:			0.462	grams/cc
   Eccentricity of orbit:	0.181
   Escape Velocity:		6.66	km/sec
   Molecular weight retained:	17.89 and above
   Surface acceleration:	169.34	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.539
   Length of year:		118769.77	days
   Length of day:		31.41	hours


