                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048ae7
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6182 K
Stellar class: F8
Age: 2.447 billion years  (4.251 billion left on main sequence)
Habitable ecosphere radius: 1.287 AU

Planets present at:
1	  0.403 AU	no atmosphere
2	  0.475 AU	no atmosphere
3	  0.790 AU	greenhouse
4	  1.201 AU	no atmosphere
5	  1.543 AU	gas giant
6	  2.300 AU	no atmosphere
7	  3.052 AU	gas giant
8	  5.605 AU	gas giant
9	  9.672 AU	gas giant
10	 15.726 AU	no atmosphere
11	 18.484 AU	gas giant
12	 23.588 AU	gas giant
13	 42.677 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.403	AU
   Mass:			0.049	Earth masses
   Equatorial radius:		2374.4	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		216.29	degrees Celcius
   Normal daytime temperature:	425.92	degrees Celcius
   Normal night temperature:	-187.06	degrees Celcius
   Maximum temperature:   	429.16	degrees Celcius
   Minimum temperature:   	-197.72	degrees Celcius
   Escape Velocity:		4.08	km/sec
   Molecular weight retained:	47.79 and above
   Surface acceleration:	349.76	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.069
   Length of year:		88.77	days
   Length of day:		1739.28	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.475	AU
   Mass:			0.326	Earth masses
   Equatorial radius:		4433.6	km
   Density:			5.334	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		177.33	degrees Celcius
   Maximum temperature:   	381.89	degrees Celcius
   Minimum temperature:   	-210.92	degrees Celcius
   Escape Velocity:		7.66	km/sec
   Molecular weight retained:	13.55 and above
   Surface acceleration:	660.93	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.073
   Length of year:		113.49	days
   Length of day:		2723.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.790	AU
   Mass:			0.968	Earth masses
   Equatorial radius:		6337.3	km
   Density:			5.429	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.98	Earth gees
   Surface pressure:		97.779	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		437.53	degrees Celcius
   Maximum temperature:   	441.88	degrees Celcius
   Minimum temperature:   	431.18	degrees Celcius
   Escape Velocity:		11.04	km/sec
   Molecular weight retained:	6.51 and above
   Surface acceleration:	961.56	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.592
   Length of year:		243.53	days
   Length of day:		18.06	hours
   Boiling point of water:	290.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1163
				Cesium       melts at 28    boils at 1205
				Gallium      melts at 30    boils at 3772
				Rubidium     melts at 39    boils at 1180
				Potassium    melts at 63    boils at 1297
				Sodium       melts at 98    boils at 1472
				Sulfur       melts at 113   boils at 812
				Indium       melts at 157   boils at 3284
				Lithium      melts at 181   boils at 2176
				Selenium     melts at 217   boils at 1175
				Tin          melts at 232   boils at 4104
				Polonium     melts at 254   boils at 1594
				Bismuth      melts at 271   boils at 2504
				Thallium     melts at 304   boils at 2342
				Cadmium      melts at 321   boils at 1296
				Lead         melts at 328   boils at 2786
				Zinc         melts at 420   boils at 1511
   gasses in atmosphere:
				Nitrogen         99.2%  PP 96951.5 mb
				Phosphorus        0.6%  PP  543.6 mb
				CarbonDioxide     0.1%  PP   59.1 mb
				Ozone             0.1%  PP   53.7 mb
				Ethanol           0.1%  PP   59.8 mb


Planet 4	
   Distance from primary:	1.201	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		3542.0	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.028	Earth atmospheres
   Surface temperature:		13.60	degrees Celcius
   Normal daytime temperature:	35.98	degrees Celcius
   Normal night temperature:	-9.35	degrees Celcius
   Maximum temperature:   	61.88	degrees Celcius
   Minimum temperature:   	-35.96	degrees Celcius
   Escape Velocity:		6.10	km/sec
   Molecular weight retained:	21.35 and above
   Surface acceleration:	524.83	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.124
   Length of year:		456.57	days
   Length of day:		22.03	hours
   Boiling point of water:	22.4	degrees Celcius
   Hydrosphere percentage:	39.70
   Cloud cover percentage:	0.00
   Ice cover percentage:	2.18
   liquids at surface:
				Mercury      melts at -39   boils at 227
				Water        melts at 0     boils at 23
   gasses in atmosphere:
				CarbonDioxide    42.5%  PP   12.1 mb
				Ozone            46.3%  PP   13.2 mb
				Chlorine          7.8%  PP    2.2 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           3.0%  PP    0.9 mb
				Xenon             0.4%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.543	AU
   Mass:			5.301	Earth masses
   Equatorial radius:		17494.9	km
   Density:			1.413	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		15.55	km/sec
   Molecular weight retained:	3.28 and above
   Surface acceleration:	690.69	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.472
   Length of year:		664.73	days
   Length of day:		15.56	hours


Planet 6	
   Distance from primary:	2.300	AU
   Mass:			0.289	Earth masses
   Equatorial radius:		4260.2	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.065	Earth atmospheres
   Surface temperature:		-82.42	degrees Celcius
   Normal daytime temperature:	-71.67	degrees Celcius
   Normal night temperature:	-93.50	degrees Celcius
   Maximum temperature:   	-48.50	degrees Celcius
   Minimum temperature:   	-117.96	degrees Celcius
   Escape Velocity:		7.35	km/sec
   Molecular weight retained:	14.69 and above
   Surface acceleration:	634.27	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.453
   Length of year:		1209.65	days
   Length of day:		19.04	hours
   Boiling point of water:	37.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	54.04
   liquids at surface:
				Ethanol      melts at -114  boils at 20
				Chlorine     melts at -101  boils at -74
   gasses in atmosphere:
				Oxygen           99.6%  PP   65.0 mb
				Ozone             0.4%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.052	AU
   Mass:			13.779	Earth masses
   Equatorial radius:		24467.8	km
   Density:			1.342	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		21.19	km/sec
   Molecular weight retained:	1.77 and above
   Surface acceleration:	917.87	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.546
   Length of year:		1848.86	days
   Length of day:		13.49	hours


Planet 8	*gas giant*
   Distance from primary:	5.605	AU
   Mass:			1217.066	Earth masses
   Equatorial radius:		95104.0	km
   Density:			2.019	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		101.03	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5366.07	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.461
   Length of year:		4593.55	days
   Length of day:		5.58	hours


Planet 9	*gas giant*
   Distance from primary:	9.672	AU
   Mass:			236.861	Earth masses
   Equatorial radius:		61747.5	km
   Density:			1.436	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		55.31	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2477.39	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.533
   Length of year:		10425.58	days
   Length of day:		8.21	hours


Planet 10	
   Distance from primary:	15.726	AU
   Mass:			1/155.8	Earth masses
   Equatorial radius:		1611.2	km
   Density:			2.190	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.10	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-197.60	degrees Celcius
   Normal daytime temperature:	-182.95	degrees Celcius
   Normal night temperature:	-212.19	degrees Celcius
   Maximum temperature:   	-168.96	degrees Celcius
   Minimum temperature:   	-226.43	degrees Celcius
   Escape Velocity:		1.78	km/sec
   Molecular weight retained:	249.82 and above
   Surface acceleration:	98.61	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.202
   Length of year:		21621.66	days
   Length of day:		48.26	hours
   Boiling point of water:	-62.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	7.57


Planet 11	*gas giant*
   Distance from primary:	18.484	AU
   Mass:			1.001	Earth masses
   Equatorial radius:		13231.5	km
   Density:			0.617	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		7.77	km/sec
   Molecular weight retained:	13.16 and above
   Surface acceleration:	227.98	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.544
   Length of year:		27552.62	days
   Length of day:		27.07	hours


Planet 12	*gas giant*
   Distance from primary:	23.588	AU
   Mass:			54.832	Earth masses
   Equatorial radius:		43405.2	km
   Density:			0.957	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		31.74	km/sec
   Molecular weight retained:	0.79 and above
   Surface acceleration:	1160.62	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.469
   Length of year:		39716.62	days
   Length of day:		12.00	hours


Planet 13	*gas giant*
   Distance from primary:	42.677	AU
   Mass:			0.941	Earth masses
   Equatorial radius:		13934.2	km
   Density:			0.496	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		7.34	km/sec
   Molecular weight retained:	14.74 and above
   Surface acceleration:	193.28	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.472
   Length of year:		96660.27	days
   Length of day:		29.40	hours


