                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a95
Stellar mass: 1.11 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6429 K
Stellar class: F7
Age: 4.957 billion years  (1.751 billion left on main sequence)
Habitable ecosphere radius: 1.286 AU

Planets present at:
1	  0.335 AU	no atmosphere
2	  0.614 AU	no atmosphere
3	  1.012 AU	greenhouse
4	  1.713 AU	no atmosphere
5	  2.443 AU	gas giant
6	  6.836 AU	gas giant
7	 13.222 AU	gas giant
8	 18.035 AU	gas giant
9	 25.662 AU	gas giant
10	 40.240 AU	no atmosphere
11	 49.599 AU	no atmosphere



Planet 1	
   Distance from primary:	0.335	AU
   Mass:			0.118	Earth masses
   Equatorial radius:		3171.9	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		264.44	degrees Celcius
   Normal daytime temperature:	484.55	degrees Celcius
   Normal night temperature:	-177.15	degrees Celcius
   Maximum temperature:   	487.52	degrees Celcius
   Minimum temperature:   	-187.60	degrees Celcius
   Escape Velocity:		5.45	km/sec
   Molecular weight retained:	26.68 and above
   Surface acceleration:	469.00	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.063
   Length of year:		67.23	days
   Length of day:		1613.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.614	AU
   Mass:			0.392	Earth masses
   Equatorial radius:		4711.8	km
   Density:			5.346	grams/cc
   Eccentricity of orbit:	0.133
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.10	degrees Celcius
   Maximum temperature:   	316.20	degrees Celcius
   Minimum temperature:   	-220.42	degrees Celcius
   Escape Velocity:		8.14	km/sec
   Molecular weight retained:	11.97 and above
   Surface acceleration:	703.93	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.061
   Length of year:		166.89	days
   Length of day:		3066.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.012	AU
   Mass:			2.525	Earth masses
   Equatorial radius:		8635.2	km
   Density:			5.596	grams/cc
   Eccentricity of orbit:	0.129
   Surface gravity:		1.38	Earth gees
   Surface pressure:		546.692	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		584.38	degrees Celcius
   Maximum temperature:   	585.74	degrees Celcius
   Minimum temperature:   	579.71	degrees Celcius
   Escape Velocity:		15.27	km/sec
   Molecular weight retained:	3.40 and above
   Surface acceleration:	1350.61	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.535
   Length of year:		353.09	days
   Length of day:		13.44	hours
   Boiling point of water:	424.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1504
				Cesium       melts at 28    boils at 1557
				Gallium      melts at 30    boils at 4734
				Rubidium     melts at 39    boils at 1525
				Potassium    melts at 63    boils at 1670
				Sodium       melts at 98    boils at 1887
				Indium       melts at 157   boils at 4130
				Lithium      melts at 181   boils at 2758
				Selenium     melts at 217   boils at 1519
				Tin          melts at 232   boils at 5146
				Polonium     melts at 254   boils at 2038
				Bismuth      melts at 271   boils at 3164
				Thallium     melts at 304   boils at 2964
				Cadmium      melts at 321   boils at 1669
				Lead         melts at 328   boils at 3514
				Zinc         melts at 420   boils at 1935
				Tellurium    melts at 450   boils at 2090
   gasses in atmosphere:
				Sulfur            0.2%  PP 1093.0 mb
				Nitrogen          0.9%  PP 4749.2 mb
				Helium           98.9%  PP 540818.5 mb


Planet 4	
   Distance from primary:	1.713	AU
   Mass:			1/202.8	Earth masses
   Equatorial radius:		1102.5	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.098
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-34.85	degrees Celcius
   Normal daytime temperature:	11.25	degrees Celcius
   Normal night temperature:	-81.47	degrees Celcius
   Maximum temperature:   	39.64	degrees Celcius
   Minimum temperature:   	-110.03	degrees Celcius
   Escape Velocity:		1.89	km/sec
   Molecular weight retained:	222.49 and above
   Surface acceleration:	161.81	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.055
   Length of year:		777.76	days
   Length of day:		48.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	*gas giant*
   Distance from primary:	2.443	AU
   Mass:			228.248	Earth masses
   Equatorial radius:		54471.0	km
   Density:			2.015	grams/cc
   Eccentricity of orbit:	0.114
   Escape Velocity:		57.81	km/sec
   Molecular weight retained:	0.24 and above
   Surface acceleration:	3067.72	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.462
   Length of year:		1323.88	days
   Length of day:		7.38	hours


Planet 6	*gas giant*
   Distance from primary:	6.836	AU
   Mass:			1045.947	Earth masses
   Equatorial radius:		92517.7	km
   Density:			1.885	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		94.96	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4873.04	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.475
   Length of year:		6189.38	days
   Length of day:		5.85	hours


Planet 7	*gas giant*
   Distance from primary:	13.222	AU
   Mass:			15.986	Earth masses
   Equatorial radius:		28873.7	km
   Density:			0.948	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		21.01	km/sec
   Molecular weight retained:	1.80 and above
   Surface acceleration:	764.68	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.534
   Length of year:		16672.72	days
   Length of day:		14.78	hours


Planet 8	*gas giant*
   Distance from primary:	18.035	AU
   Mass:			2.027	Earth masses
   Equatorial radius:		16224.5	km
   Density:			0.677	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		9.98	km/sec
   Molecular weight retained:	7.96 and above
   Surface acceleration:	307.15	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.499
   Length of year:		26559.28	days
   Length of day:		23.32	hours


Planet 9	*gas giant*
   Distance from primary:	25.662	AU
   Mass:			68.680	Earth masses
   Equatorial radius:		46682.0	km
   Density:			0.963	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		34.26	km/sec
   Molecular weight retained:	0.68 and above
   Surface acceleration:	1256.81	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.549
   Length of year:		45075.32	days
   Length of day:		11.53	hours


Planet 10	
   Distance from primary:	40.240	AU
   Mass:			0.248	Earth masses
   Equatorial radius:		5414.9	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.02	degrees Celcius
   Normal daytime temperature:	-219.49	degrees Celcius
   Normal night temperature:	-230.47	degrees Celcius
   Maximum temperature:   	-205.93	degrees Celcius
   Minimum temperature:   	-244.67	degrees Celcius
   Escape Velocity:		6.05	km/sec
   Molecular weight retained:	21.71 and above
   Surface acceleration:	337.70	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.165
   Length of year:		88520.65	days
   Length of day:		26.08	hours
   Boiling point of water:	-47.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 11	
   Distance from primary:	49.599	AU
   Mass:			0.107	Earth masses
   Equatorial radius:		4096.2	km
   Density:			2.212	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.82	degrees Celcius
   Normal daytime temperature:	-224.17	degrees Celcius
   Normal night temperature:	-235.36	degrees Celcius
   Maximum temperature:   	-209.75	degrees Celcius
   Minimum temperature:   	-249.94	degrees Celcius
   Escape Velocity:		4.55	km/sec
   Molecular weight retained:	38.27 and above
   Surface acceleration:	253.20	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.147
   Length of year:		121132.85	days
   Length of day:		30.12	hours
   Boiling point of water:	-63.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


