                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950483a0
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6140 K
Stellar class: F9
Age: 5.330 billion years  (1.607 billion left on main sequence)
Habitable ecosphere radius: 1.259 AU

Planets present at:
1	  0.337 AU	no atmosphere
2	  0.513 AU	no atmosphere
3	  0.583 AU	no atmosphere
4	  0.951 AU	greenhouse
5	  1.023 AU	no atmosphere
6	  1.903 AU	cold
7	  2.658 AU	high pressure
8	  3.897 AU	gas giant
9	  9.109 AU	gas giant
10	 20.369 AU	cold
11	 39.349 AU	gas giant
12	 47.534 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.337	AU
   Mass:			0.144	Earth masses
   Equatorial radius:		3381.3	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.232
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		257.53	degrees Celcius
   Normal daytime temperature:	474.05	degrees Celcius
   Normal night temperature:	-160.19	degrees Celcius
   Maximum temperature:   	478.40	degrees Celcius
   Minimum temperature:   	-176.21	degrees Celcius
   Escape Velocity:		5.82	km/sec
   Molecular weight retained:	23.45 and above
   Surface acceleration:	500.55	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.059
   Length of year:		68.21	days
   Length of day:		1020.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.513	AU
   Mass:			0.029	Earth masses
   Equatorial radius:		1997.8	km
   Density:			5.264	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.03	degrees Celcius
   Maximum temperature:   	355.61	degrees Celcius
   Minimum temperature:   	-215.07	degrees Celcius
   Escape Velocity:		3.43	km/sec
   Molecular weight retained:	67.60 and above
   Surface acceleration:	293.88	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.068
   Length of year:		128.10	days
   Length of day:		3074.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.583	AU
   Mass:			0.541	Earth masses
   Equatorial radius:		5238.1	km
   Density:			5.370	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.80	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		128.20	degrees Celcius
   Maximum temperature:   	321.20	degrees Celcius
   Minimum temperature:   	-220.82	degrees Celcius
   Escape Velocity:		9.07	km/sec
   Molecular weight retained:	9.64 and above
   Surface acceleration:	786.08	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.080
   Length of year:		155.12	days
   Length of day:		3722.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.951	AU
   Mass:			1.149	Earth masses
   Equatorial radius:		6699.9	km
   Density:			5.451	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		1.04	Earth gees
   Surface pressure:		138.549	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		400.84	degrees Celcius
   Maximum temperature:   	404.52	degrees Celcius
   Minimum temperature:   	395.56	degrees Celcius
   Escape Velocity:		11.70	km/sec
   Molecular weight retained:	5.80 and above
   Surface acceleration:	1020.76	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.596
   Length of year:		322.80	days
   Length of day:		16.45	hours
   Boiling point of water:	313.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1221
				Cesium       melts at 28    boils at 1265
				Gallium      melts at 30    boils at 3936
				Rubidium     melts at 39    boils at 1238
				Potassium    melts at 63    boils at 1361
				Sodium       melts at 98    boils at 1543
				Sulfur       melts at 113   boils at 856
				Indium       melts at 157   boils at 3428
				Lithium      melts at 181   boils at 2275
				Selenium     melts at 217   boils at 1234
				Tin          melts at 232   boils at 4282
				Polonium     melts at 254   boils at 1669
				Bismuth      melts at 271   boils at 2616
				Thallium     melts at 304   boils at 2448
				Cadmium      melts at 321   boils at 1359
				Lead         melts at 328   boils at 2910
   gasses in atmosphere:
				Nitrogen         99.1%  PP 137356.2 mb
				Phosphorus        0.6%  PP  800.4 mb
				CarbonDioxide     0.1%  PP   89.1 mb
				Ethanol           0.1%  PP   90.5 mb


Planet 5	
   Distance from primary:	1.023	AU
   Mass:			0.060	Earth masses
   Equatorial radius:		2525.1	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		30.50	degrees Celcius
   Normal daytime temperature:	108.58	degrees Celcius
   Normal night temperature:	-51.17	degrees Celcius
   Maximum temperature:   	134.25	degrees Celcius
   Minimum temperature:   	-78.54	degrees Celcius
   Escape Velocity:		4.34	km/sec
   Molecular weight retained:	42.23 and above
   Surface acceleration:	372.21	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.073
   Length of year:		360.37	days
   Length of day:		73.64	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 6	
   Distance from primary:	1.903	AU
   Mass:			1.261	Earth masses
   Equatorial radius:		6905.3	km
   Density:			5.465	grams/cc
   Eccentricity of orbit:	0.150
   Surface gravity:		1.08	Earth gees
   Surface pressure:		1.271	Earth atmospheres
   Surface temperature:		-78.67	degrees Celcius
   Normal daytime temperature:	-76.14	degrees Celcius
   Normal night temperature:	-81.35	degrees Celcius
   Maximum temperature:   	-57.16	degrees Celcius
   Minimum temperature:   	-101.73	degrees Celcius
   Escape Velocity:		12.07	km/sec
   Molecular weight retained:	5.45 and above
   Surface acceleration:	1054.63	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.698
   Length of year:		914.59	days
   Length of day:		14.78	hours
   Boiling point of water:	106.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	91.67
   liquids at surface:
				Ethanol      melts at -114  boils at 85
				Chlorine     melts at -101  boils at -30
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1270.2 mb
				Ozone             0.1%  PP    0.7 mb


Planet 7	
   Distance from primary:	2.658	AU
   Mass:			1.683	Earth masses
   Equatorial radius:		7580.6	km
   Density:			5.512	grams/cc
   Eccentricity of orbit:	0.110
   Surface gravity:		1.19	Earth gees
   Surface pressure:		3.042	Earth atmospheres
   Surface temperature:		-99.36	degrees Celcius
   Normal daytime temperature:	-97.95	degrees Celcius
   Normal night temperature:	-100.85	degrees Celcius
   Maximum temperature:   	-85.57	degrees Celcius
   Minimum temperature:   	-114.14	degrees Celcius
   Escape Velocity:		13.31	km/sec
   Molecular weight retained:	4.48 and above
   Surface acceleration:	1167.76	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.671
   Length of year:		1509.38	days
   Length of day:		14.03	hours
   Boiling point of water:	133.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 110
				Chlorine     melts at -101  boils at -13
   gasses in atmosphere:
				Nitrogen         99.9%  PP 3039.5 mb


Planet 8	*gas giant*
   Distance from primary:	3.897	AU
   Mass:			440.376	Earth masses
   Equatorial radius:		68719.5	km
   Density:			1.936	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		71.49	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3718.80	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.461
   Length of year:		2678.43	days
   Length of day:		6.70	hours


Planet 9	*gas giant*
   Distance from primary:	9.109	AU
   Mass:			851.909	Earth masses
   Equatorial radius:		89409.9	km
   Density:			1.701	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		87.17	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4249.73	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.527
   Length of year:		9564.11	days
   Length of day:		6.27	hours


Planet 10	
   Distance from primary:	20.369	AU
   Mass:			11.196	Earth masses
   Equatorial radius:		17842.1	km
   Density:			2.813	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		1.43	Earth gees
   Surface pressure:		0.318	Earth atmospheres
   Surface temperature:		-199.10	degrees Celcius
   Normal daytime temperature:	-197.49	degrees Celcius
   Normal night temperature:	-200.77	degrees Celcius
   Maximum temperature:   	-180.88	degrees Celcius
   Minimum temperature:   	-219.36	degrees Celcius
   Escape Velocity:		22.37	km/sec
   Molecular weight retained:	1.59 and above
   Surface acceleration:	1402.53	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.151
   Length of year:		32018.71	days
   Length of day:		12.80	hours
   Boiling point of water:	70.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.39
   liquids at surface:
				Fluorine     melts at -220  boils at -195
				Oxygen       melts at -218  boils at -190
   gasses in atmosphere:
				Helium           100.0%  PP  317.6 mb


Planet 11	*gas giant*
   Distance from primary:	39.349	AU
   Mass:			2.181	Earth masses
   Equatorial radius:		17717.5	km
   Density:			0.559	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		9.91	km/sec
   Molecular weight retained:	8.09 and above
   Surface acceleration:	277.04	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.501
   Length of year:		85973.41	days
   Length of day:		24.56	hours


Planet 12	
   Distance from primary:	47.534	AU
   Mass:			0.037	Earth masses
   Equatorial radius:		2877.8	km
   Density:			2.199	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.18	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.44	degrees Celcius
   Normal daytime temperature:	-222.79	degrees Celcius
   Normal night temperature:	-235.96	degrees Celcius
   Maximum temperature:   	-212.02	degrees Celcius
   Minimum temperature:   	-247.07	degrees Celcius
   Escape Velocity:		3.19	km/sec
   Molecular weight retained:	78.00 and above
   Surface acceleration:	176.82	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.151
   Length of year:		114149.32	days
   Length of day:		36.04	hours
   Boiling point of water:	-80.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


