                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048759
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6372 K
Stellar class: F7
Age: 4.303 billion years  (2.511 billion left on main sequence)
Habitable ecosphere radius: 1.273 AU

Planets present at:
1	  0.380 AU	no atmosphere
2	  0.472 AU	no atmosphere
3	  0.569 AU	no atmosphere
4	  0.900 AU	greenhouse
5	  1.512 AU	cold
6	  1.875 AU	cold
7	  3.123 AU	gas giant
8	 10.643 AU	gas giant
9	 27.798 AU	gas giant
10	 44.333 AU	gas giant
11	 51.374 AU	no atmosphere



Planet 1	
   Distance from primary:	0.380	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		2457.2	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		227.02	degrees Celcius
   Maximum temperature:   	442.42	degrees Celcius
   Minimum temperature:   	-198.23	degrees Celcius
   Escape Velocity:		4.22	km/sec
   Molecular weight retained:	44.61 and above
   Surface acceleration:	362.10	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.081
   Length of year:		81.25	days
   Length of day:		1950.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.472	AU
   Mass:			0.051	Earth masses
   Equatorial radius:		2404.8	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		178.22	degrees Celcius
   Maximum temperature:   	382.91	degrees Celcius
   Minimum temperature:   	-210.42	degrees Celcius
   Escape Velocity:		4.13	km/sec
   Molecular weight retained:	46.58 and above
   Surface acceleration:	354.30	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.058
   Length of year:		112.66	days
   Length of day:		2703.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.569	AU
   Mass:			0.473	Earth masses
   Equatorial radius:		5013.8	km
   Density:			5.359	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.77	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		135.06	degrees Celcius
   Maximum temperature:   	329.72	degrees Celcius
   Minimum temperature:   	-219.53	degrees Celcius
   Escape Velocity:		8.68	km/sec
   Molecular weight retained:	10.54 and above
   Surface acceleration:	750.94	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.083
   Length of year:		149.24	days
   Length of day:		3581.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.900	AU
   Mass:			1.033	Earth masses
   Equatorial radius:		6472.8	km
   Density:			5.437	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		1.00	Earth gees
   Surface pressure:		96.030	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		378.75	degrees Celcius
   Maximum temperature:   	383.08	degrees Celcius
   Minimum temperature:   	372.95	degrees Celcius
   Escape Velocity:		11.28	km/sec
   Molecular weight retained:	6.23 and above
   Surface acceleration:	983.60	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.613
   Length of year:		296.59	days
   Length of day:		17.15	hours
   Boiling point of water:	289.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1160
				Cesium       melts at 28    boils at 1202
				Gallium      melts at 30    boils at 3764
				Rubidium     melts at 39    boils at 1177
				Potassium    melts at 63    boils at 1294
				Sodium       melts at 98    boils at 1469
				Sulfur       melts at 113   boils at 810
				Indium       melts at 157   boils at 3277
				Lithium      melts at 181   boils at 2171
				Selenium     melts at 217   boils at 1172
				Tin          melts at 232   boils at 4096
				Polonium     melts at 254   boils at 1590
				Bismuth      melts at 271   boils at 2498
				Thallium     melts at 304   boils at 2337
				Cadmium      melts at 321   boils at 1293
				Lead         melts at 328   boils at 2780
   gasses in atmosphere:
				Nitrogen         99.1%  PP 95185.5 mb
				Phosphorus        0.6%  PP  559.2 mb
				CarbonDioxide     0.1%  PP   62.0 mb
				Ozone             0.1%  PP   51.9 mb
				Ethanol           0.1%  PP   63.0 mb


Planet 5	
   Distance from primary:	1.512	AU
   Mass:			0.730	Earth masses
   Equatorial radius:		5778.6	km
   Density:			5.397	grams/cc
   Eccentricity of orbit:	0.186
   Surface gravity:		0.89	Earth gees
   Surface pressure:		0.571	Earth atmospheres
   Surface temperature:		-0.72	degrees Celcius
   Normal daytime temperature:	4.95	degrees Celcius
   Normal night temperature:	-6.72	degrees Celcius
   Maximum temperature:   	31.39	degrees Celcius
   Minimum temperature:   	-34.72	degrees Celcius
   Escape Velocity:		10.04	km/sec
   Molecular weight retained:	7.88 and above
   Surface acceleration:	871.66	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.208
   Length of year:		645.91	days
   Length of day:		16.34	hours
   Boiling point of water:	85.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	15.83
   Ice cover percentage:	9.16
   liquids at surface:
				Ethanol      melts at -114  boils at 65
				Mercury      melts at -39   boils at 332
				Bromine      melts at -7    boils at 46
   gasses in atmosphere:
				Oxygen           34.1%  PP  194.7 mb
				Nitrogen         65.8%  PP  375.6 mb


Planet 6	
   Distance from primary:	1.875	AU
   Mass:			0.400	Earth masses
   Equatorial radius:		4742.6	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.119	Earth atmospheres
   Surface temperature:		-60.91	degrees Celcius
   Normal daytime temperature:	-51.54	degrees Celcius
   Normal night temperature:	-70.66	degrees Celcius
   Maximum temperature:   	-27.91	degrees Celcius
   Minimum temperature:   	-95.62	degrees Celcius
   Escape Velocity:		8.20	km/sec
   Molecular weight retained:	11.81 and above
   Surface acceleration:	708.71	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.452
   Length of year:		892.29	days
   Length of day:		18.06	hours
   Boiling point of water:	49.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.13
   Ice cover percentage:	57.32
   liquids at surface:
				Ethanol      melts at -114  boils at 31
   gasses in atmosphere:
				Oxygen           16.0%  PP   19.0 mb
				Nitrogen         83.7%  PP   99.4 mb
				CarbonDioxide     0.2%  PP    0.2 mb
				Ozone             0.2%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.123	AU
   Mass:			399.810	Earth masses
   Equatorial radius:		65525.2	km
   Density:			2.028	grams/cc
   Eccentricity of orbit:	0.202
   Escape Velocity:		69.76	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3713.44	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.541
   Length of year:		1916.55	days
   Length of day:		6.71	hours


Planet 8	*gas giant*
   Distance from primary:	10.643	AU
   Mass:			1834.038	Earth masses
   Equatorial radius:		113171.9	km
   Density:			1.805	grams/cc
   Eccentricity of orbit:	0.238
   Escape Velocity:		113.69	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5710.45	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.506
   Length of year:		12035.44	days
   Length of day:		5.41	hours


Planet 9	*gas giant*
   Distance from primary:	27.798	AU
   Mass:			8.082	Earth masses
   Equatorial radius:		25196.7	km
   Density:			0.721	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		15.99	km/sec
   Molecular weight retained:	3.10 and above
   Surface acceleration:	507.63	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.505
   Length of year:		50928.14	days
   Length of day:		18.14	hours


Planet 10	*gas giant*
   Distance from primary:	44.333	AU
   Mass:			0.562	Earth masses
   Equatorial radius:		12039.0	km
   Density:			0.460	grams/cc
   Eccentricity of orbit:	0.044
   Escape Velocity:		6.10	km/sec
   Molecular weight retained:	21.32 and above
   Surface acceleration:	154.67	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.528
   Length of year:		102571.65	days
   Length of day:		32.86	hours


Planet 11	
   Distance from primary:	51.374	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2711.6	km
   Density:			2.197	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.78	degrees Celcius
   Normal daytime temperature:	-224.17	degrees Celcius
   Normal night temperature:	-237.25	degrees Celcius
   Maximum temperature:   	-212.96	degrees Celcius
   Minimum temperature:   	-248.69	degrees Celcius
   Escape Velocity:		3.00	km/sec
   Molecular weight retained:	87.91 and above
   Surface acceleration:	166.50	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.144
   Length of year:		127954.35	days
   Length of day:		37.14	hours
   Boiling point of water:	-84.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


