                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048646
Stellar mass: 1.10 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6420 K
Stellar class: F7
Age: 3.101 billion years  (3.747 billion left on main sequence)
Habitable ecosphere radius: 1.269 AU

Planets present at:
1	  0.335 AU	no atmosphere
2	  0.511 AU	no atmosphere
3	  0.779 AU	no atmosphere
4	  0.844 AU	greenhouse
5	  1.293 AU	no atmosphere
6	  1.543 AU	gas giant
7	  3.396 AU	gas giant
8	  6.398 AU	gas giant
9	 20.098 AU	gas giant
10	 33.843 AU	gas giant
11	 41.602 AU	no atmosphere
12	 47.742 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.335	AU
   Mass:			0.229	Earth masses
   Equatorial radius:		3946.9	km
   Density:			5.315	grams/cc
   Eccentricity of orbit:	0.143
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		258.11	degrees Celcius
   Normal daytime temperature:	475.66	degrees Celcius
   Normal night temperature:	-167.83	degrees Celcius
   Maximum temperature:   	479.44	degrees Celcius
   Minimum temperature:   	-181.50	degrees Celcius
   Escape Velocity:		6.80	km/sec
   Molecular weight retained:	17.15 and above
   Surface acceleration:	586.33	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.083
   Length of year:		67.38	days
   Length of day:		1212.45	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.511	AU
   Mass:			0.112	Earth masses
   Equatorial radius:		3113.8	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		160.09	degrees Celcius
   Maximum temperature:   	360.72	degrees Celcius
   Minimum temperature:   	-214.70	degrees Celcius
   Escape Velocity:		5.35	km/sec
   Molecular weight retained:	27.69 and above
   Surface acceleration:	460.27	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.057
   Length of year:		126.95	days
   Length of day:		3046.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.779	AU
   Mass:			0.075	Earth masses
   Equatorial radius:		2728.7	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		76.69	degrees Celcius
   Maximum temperature:   	256.79	degrees Celcius
   Minimum temperature:   	-227.96	degrees Celcius
   Escape Velocity:		4.69	km/sec
   Molecular weight retained:	36.13 and above
   Surface acceleration:	402.57	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.067
   Length of year:		239.11	days
   Length of day:		5738.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.844	AU
   Mass:			0.790	Earth masses
   Equatorial radius:		5930.2	km
   Density:			5.406	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.91	Earth gees
   Surface pressure:		52.501	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		343.25	degrees Celcius
   Maximum temperature:   	349.15	degrees Celcius
   Minimum temperature:   	336.03	degrees Celcius
   Escape Velocity:		10.31	km/sec
   Molecular weight retained:	7.47 and above
   Surface acceleration:	895.90	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.512
   Length of year:		269.81	days
   Length of day:		18.69	hours
   Boiling point of water:	254.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 617
				Francium     melts at 27    boils at 1070
				Cesium       melts at 28    boils at 1109
				Gallium      melts at 30    boils at 3509
				Rubidium     melts at 39    boils at 1085
				Potassium    melts at 63    boils at 1195
				Sodium       melts at 98    boils at 1359
				Sulfur       melts at 113   boils at 742
				Indium       melts at 157   boils at 3053
				Lithium      melts at 181   boils at 2017
				Selenium     melts at 217   boils at 1081
				Tin          melts at 232   boils at 3820
				Polonium     melts at 254   boils at 1472
				Bismuth      melts at 271   boils at 2323
				Thallium     melts at 304   boils at 2172
				Cadmium      melts at 321   boils at 1194
				Lead         melts at 328   boils at 2588
   gasses in atmosphere:
				Nitrogen         99.0%  PP 51994.3 mb
				Phosphorus        0.6%  PP  332.7 mb
				CarbonDioxide     0.1%  PP   37.1 mb
				Ozone             0.1%  PP   35.2 mb
				Ethanol           0.1%  PP   37.7 mb


Planet 5	
   Distance from primary:	1.293	AU
   Mass:			0.127	Earth masses
   Equatorial radius:		3243.5	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.014	Earth atmospheres
   Surface temperature:		-15.05	degrees Celcius
   Normal daytime temperature:	8.32	degrees Celcius
   Normal night temperature:	-38.80	degrees Celcius
   Maximum temperature:   	35.14	degrees Celcius
   Minimum temperature:   	-66.28	degrees Celcius
   Escape Velocity:		5.58	km/sec
   Molecular weight retained:	25.51 and above
   Surface acceleration:	479.77	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.303
   Length of year:		511.43	days
   Length of day:		23.05	hours
   Boiling point of water:	10.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	28.03
   liquids at surface:
				Ethanol      melts at -114  boils at -5
				Mercury      melts at -39   boils at 207
   gasses in atmosphere:
				CarbonDioxide    43.5%  PP    6.0 mb
				Ozone            49.2%  PP    6.8 mb
				Chlorine          3.3%  PP    0.5 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           3.6%  PP    0.5 mb
				Xenon             0.5%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	1.543	AU
   Mass:			8.427	Earth masses
   Equatorial radius:		20049.9	km
   Density:			1.492	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		18.31	km/sec
   Molecular weight retained:	2.37 and above
   Surface acceleration:	835.92	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.510
   Length of year:		666.26	days
   Length of day:		14.14	hours


Planet 7	*gas giant*
   Distance from primary:	3.396	AU
   Mass:			471.592	Earth masses
   Equatorial radius:		69258.5	km
   Density:			2.026	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		73.69	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3920.66	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.510
   Length of year:		2174.30	days
   Length of day:		6.53	hours


Planet 8	*gas giant*
   Distance from primary:	6.398	AU
   Mass:			456.590	Earth masses
   Equatorial radius:		72328.0	km
   Density:			1.722	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		70.96	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3480.59	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.528
   Length of year:		5623.89	days
   Length of day:		6.93	hours


Planet 9	*gas giant*
   Distance from primary:	20.098	AU
   Mass:			111.849	Earth masses
   Equatorial radius:		52790.4	km
   Density:			1.085	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		41.11	km/sec
   Molecular weight retained:	0.47 and above
   Surface acceleration:	1600.52	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.468
   Length of year:		31326.28	days
   Length of day:		10.22	hours


Planet 10	*gas giant*
   Distance from primary:	33.843	AU
   Mass:			2.316	Earth masses
   Equatorial radius:		17793.3	km
   Density:			0.587	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		10.19	km/sec
   Molecular weight retained:	7.65 and above
   Surface acceleration:	291.67	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.508
   Length of year:		68458.72	days
   Length of day:		23.93	hours


Planet 11	
   Distance from primary:	41.602	AU
   Mass:			0.091	Earth masses
   Equatorial radius:		3884.8	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.07	degrees Celcius
   Normal daytime temperature:	-219.78	degrees Celcius
   Normal night temperature:	-232.26	degrees Celcius
   Maximum temperature:   	-205.32	degrees Celcius
   Minimum temperature:   	-247.06	degrees Celcius
   Escape Velocity:		4.32	km/sec
   Molecular weight retained:	42.60 and above
   Surface acceleration:	239.85	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.140
   Length of year:		93304.71	days
   Length of day:		30.95	hours
   Boiling point of water:	-65.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 12	
   Distance from primary:	47.742	AU
   Mass:			0.105	Earth masses
   Equatorial radius:		4077.1	km
   Density:			2.211	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.20	degrees Celcius
   Normal daytime temperature:	-223.45	degrees Celcius
   Normal night temperature:	-234.83	degrees Celcius
   Maximum temperature:   	-208.98	degrees Celcius
   Minimum temperature:   	-249.51	degrees Celcius
   Escape Velocity:		4.53	km/sec
   Molecular weight retained:	38.63 and above
   Surface acceleration:	251.99	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.141
   Length of year:		114704.72	days
   Length of day:		30.19	hours
   Boiling point of water:	-64.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


