                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e6b
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6200 K
Stellar class: F8
Age: 3.644 billion years  (3.471 billion left on main sequence)
Habitable ecosphere radius: 1.239 AU

Planets present at:
1	  0.362 AU	no atmosphere
2	  0.518 AU	no atmosphere
3	  0.773 AU	no atmosphere
4	  0.952 AU	greenhouse
5	  1.283 AU	high pressure
6	  2.727 AU	gas giant
7	  4.933 AU	gas giant
8	 10.677 AU	gas giant
9	 13.370 AU	gas giant
10	 17.176 AU	gas giant
11	 27.840 AU	gas giant
12	 50.504 AU	no atmosphere



Planet 1	
   Distance from primary:	0.362	AU
   Mass:			0.214	Earth masses
   Equatorial radius:		3860.0	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.080
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.00	degrees Celcius
   Normal daytime temperature:	444.11	degrees Celcius
   Normal night temperature:	-186.03	degrees Celcius
   Maximum temperature:   	447.20	degrees Celcius
   Minimum temperature:   	-196.32	degrees Celcius
   Escape Velocity:		6.65	km/sec
   Molecular weight retained:	17.94 and above
   Surface acceleration:	573.10	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.089
   Length of year:		76.04	days
   Length of day:		1825.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.518	AU
   Mass:			0.083	Earth masses
   Equatorial radius:		2819.8	km
   Density:			5.281	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.35	degrees Celcius
   Maximum temperature:   	348.68	degrees Celcius
   Minimum temperature:   	-216.33	degrees Celcius
   Escape Velocity:		4.84	km/sec
   Molecular weight retained:	33.82 and above
   Surface acceleration:	416.19	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.072
   Length of year:		130.16	days
   Length of day:		3123.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.773	AU
   Mass:			0.205	Earth masses
   Equatorial radius:		3802.8	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		73.38	degrees Celcius
   Normal daytime temperature:	197.47	degrees Celcius
   Normal night temperature:	-70.20	degrees Celcius
   Maximum temperature:   	217.33	degrees Celcius
   Minimum temperature:   	-97.93	degrees Celcius
   Escape Velocity:		6.55	km/sec
   Molecular weight retained:	18.49 and above
   Surface acceleration:	564.39	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.072
   Length of year:		237.64	days
   Length of day:		141.88	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.952	AU
   Mass:			0.311	Earth masses
   Equatorial radius:		4364.3	km
   Density:			5.331	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.66	Earth gees
   Surface pressure:		7.732	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		66.55	degrees Celcius
   Normal daytime temperature:	69.16	degrees Celcius
   Normal night temperature:	63.60	degrees Celcius
   Maximum temperature:   	78.78	degrees Celcius
   Minimum temperature:   	53.59	degrees Celcius
   Escape Velocity:		7.53	km/sec
   Molecular weight retained:	13.99 and above
   Surface acceleration:	650.26	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.505
   Length of year:		324.68	days
   Length of day:		22.76	hours
   Boiling point of water:	166.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 141
				Mercury      melts at -39   boils at 469
				Water        melts at 0     boils at 166
				Francium     melts at 27    boils at 846
				Cesium       melts at 28    boils at 879
				Gallium      melts at 30    boils at 2879
				Rubidium     melts at 39    boils at 859
				Phosphorus   melts at 44    boils at 379
				Potassium    melts at 63    boils at 950
   gasses in atmosphere:
				Oxygen            0.1%  PP   10.4 mb
				Nitrogen         67.0%  PP 5176.7 mb
				CarbonDioxide    13.3%  PP 1031.8 mb
				Methane           1.9%  PP  145.5 mb
				Ammonia           2.7%  PP  205.8 mb
				Ozone            13.9%  PP 1074.8 mb
				Neon              0.2%  PP   13.1 mb
				Krypton           0.8%  PP   63.8 mb
				Xenon             0.1%  PP    7.6 mb


Planet 5	
   Distance from primary:	1.283	AU
   Mass:			3.072	Earth masses
   Equatorial radius:		9190.8	km
   Density:			5.647	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		1.48	Earth gees
   Surface pressure:		7.368	Earth atmospheres
   Surface temperature:		30.84	degrees Celcius
   Normal daytime temperature:	32.27	degrees Celcius
   Normal night temperature:	29.31	degrees Celcius
   Maximum temperature:   	42.13	degrees Celcius
   Minimum temperature:   	19.01	degrees Celcius
   Escape Velocity:		16.33	km/sec
   Molecular weight retained:	2.98 and above
   Surface acceleration:	1450.39	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.496
   Length of year:		508.12	days
   Length of day:		12.64	hours
   Boiling point of water:	164.5	degrees Celcius
   Hydrosphere percentage:	82.06
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.17
   liquids at surface:
				Ethanol      melts at -114  boils at 139
				Mercury      melts at -39   boils at 466
				Bromine      melts at -7    boils at 117
				Water        melts at 0     boils at 165
				Francium     melts at 27    boils at 841
				Cesium       melts at 28    boils at 874
				Gallium      melts at 30    boils at 2866
   gasses in atmosphere:
				Nitrogen          0.4%  PP   32.6 mb
				Helium           99.6%  PP 7335.8 mb


Planet 6	*gas giant*
   Distance from primary:	2.727	AU
   Mass:			135.878	Earth masses
   Equatorial radius:		47400.4	km
   Density:			1.821	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		47.82	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2411.70	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.535
   Length of year:		1573.14	days
   Length of day:		8.32	hours


Planet 7	*gas giant*
   Distance from primary:	4.933	AU
   Mass:			366.717	Earth masses
   Equatorial radius:		66527.0	km
   Density:			1.777	grams/cc
   Eccentricity of orbit:	0.118
   Escape Velocity:		66.31	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3304.26	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.504
   Length of year:		3826.56	days
   Length of day:		7.11	hours


Planet 8	*gas giant*
   Distance from primary:	10.677	AU
   Mass:			21.938	Earth masses
   Equatorial radius:		31203.0	km
   Density:			1.030	grams/cc
   Eccentricity of orbit:	0.083
   Escape Velocity:		23.68	km/sec
   Molecular weight retained:	1.42 and above
   Surface acceleration:	898.54	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.503
   Length of year:		12191.56	days
   Length of day:		13.63	hours


Planet 9	*gas giant*
   Distance from primary:	13.370	AU
   Mass:			1.754	Earth masses
   Equatorial radius:		15216.9	km
   Density:			0.710	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		9.59	km/sec
   Molecular weight retained:	8.64 and above
   Surface acceleration:	302.06	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.549
   Length of year:		17084.87	days
   Length of day:		23.52	hours


Planet 10	*gas giant*
   Distance from primary:	17.176	AU
   Mass:			9.886	Earth masses
   Equatorial radius:		25730.0	km
   Density:			0.828	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		17.51	km/sec
   Molecular weight retained:	2.59 and above
   Surface acceleration:	595.51	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.546
   Length of year:		24876.15	days
   Length of day:		16.75	hours


Planet 11	*gas giant*
   Distance from primary:	27.840	AU
   Mass:			70.455	Earth masses
   Equatorial radius:		47498.2	km
   Density:			0.938	grams/cc
   Eccentricity of orbit:	0.163
   Escape Velocity:		34.40	km/sec
   Molecular weight retained:	0.67 and above
   Surface acceleration:	1245.38	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.525
   Length of year:		51331.50	days
   Length of day:		11.58	hours


Planet 12	
   Distance from primary:	50.504	AU
   Mass:			0.218	Earth masses
   Equatorial radius:		5188.3	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.188
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.86	degrees Celcius
   Normal daytime temperature:	-225.90	degrees Celcius
   Normal night temperature:	-235.71	degrees Celcius
   Maximum temperature:   	-210.61	degrees Celcius
   Minimum temperature:   	-251.11	degrees Celcius
   Escape Velocity:		5.79	km/sec
   Molecular weight retained:	23.68 and above
   Surface acceleration:	323.02	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.155
   Length of year:		125430.03	days
   Length of day:		26.67	hours
   Boiling point of water:	-50.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


