                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504879b
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6160 K
Stellar class: F8
Age: 2.591 billion years  (4.214 billion left on main sequence)
Habitable ecosphere radius: 1.274 AU

Planets present at:
1	  0.391 AU	no atmosphere
2	  0.479 AU	no atmosphere
3	  0.676 AU	greenhouse
4	  1.145 AU	greenhouse
5	  1.808 AU	no atmosphere
6	  2.092 AU	gas giant
7	  3.200 AU	cold
8	  5.962 AU	gas giant
9	 15.197 AU	gas giant
10	 22.259 AU	gas giant
11	 37.864 AU	gas giant
12	 51.539 AU	no atmosphere



Planet 1	
   Distance from primary:	0.391	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1947.6	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		222.06	degrees Celcius
   Normal daytime temperature:	433.46	degrees Celcius
   Normal night temperature:	-190.15	degrees Celcius
   Maximum temperature:   	436.54	degrees Celcius
   Minimum temperature:   	-200.23	degrees Celcius
   Escape Velocity:		3.34	km/sec
   Molecular weight retained:	71.14 and above
   Surface acceleration:	286.46	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.064
   Length of year:		84.94	days
   Length of day:		2038.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.479	AU
   Mass:			0.192	Earth masses
   Equatorial radius:		3721.9	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		175.54	degrees Celcius
   Maximum temperature:   	379.62	degrees Celcius
   Minimum temperature:   	-209.07	degrees Celcius
   Escape Velocity:		6.41	km/sec
   Molecular weight retained:	19.32 and above
   Surface acceleration:	552.10	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.053
   Length of year:		115.21	days
   Length of day:		2257.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.676	AU
   Mass:			0.699	Earth masses
   Equatorial radius:		5698.2	km
   Density:			5.393	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.88	Earth gees
   Surface pressure:		40.935	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		303.45	degrees Celcius
   Maximum temperature:   	310.85	degrees Celcius
   Minimum temperature:   	294.55	degrees Celcius
   Escape Velocity:		9.89	km/sec
   Molecular weight retained:	8.11 and above
   Surface acceleration:	858.84	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.475
   Length of year:		193.22	days
   Length of day:		32.97	hours
   Boiling point of water:	240.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 595
				Francium     melts at 27    boils at 1036
				Cesium       melts at 28    boils at 1074
				Gallium      melts at 30    boils at 3414
				Rubidium     melts at 39    boils at 1051
				Potassium    melts at 63    boils at 1158
				Sodium       melts at 98    boils at 1318
				Sulfur       melts at 113   boils at 716
				Indium       melts at 157   boils at 2969
				Lithium      melts at 181   boils at 1959
				Selenium     melts at 217   boils at 1047
				Tin          melts at 232   boils at 3717
				Polonium     melts at 254   boils at 1428
				Bismuth      melts at 271   boils at 2258
				Astatine     melts at 302   boils at 567
   gasses in atmosphere:
				Nitrogen         99.0%  PP 40505.3 mb
				Phosphorus        0.7%  PP  281.6 mb
				CarbonDioxide     0.1%  PP   31.8 mb
				Ozone             0.1%  PP   31.2 mb
				Ethanol           0.1%  PP   32.4 mb


Planet 4	
   Distance from primary:	1.145	AU
   Mass:			1.640	Earth masses
   Equatorial radius:		7518.2	km
   Density:			5.507	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		1.18	Earth gees
   Surface pressure:		276.545	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		407.39	degrees Celcius
   Maximum temperature:   	410.10	degrees Celcius
   Minimum temperature:   	403.12	degrees Celcius
   Escape Velocity:		13.19	km/sec
   Molecular weight retained:	4.56 and above
   Surface acceleration:	1157.19	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.619
   Length of year:		425.46	days
   Length of day:		14.24	hours
   Boiling point of water:	364.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1351
				Cesium       melts at 28    boils at 1399
				Gallium      melts at 30    boils at 4303
				Rubidium     melts at 39    boils at 1370
				Potassium    melts at 63    boils at 1503
				Sodium       melts at 98    boils at 1701
				Sulfur       melts at 113   boils at 955
				Indium       melts at 157   boils at 3751
				Lithium      melts at 181   boils at 2497
				Selenium     melts at 217   boils at 1365
				Tin          melts at 232   boils at 4679
				Polonium     melts at 254   boils at 1839
				Bismuth      melts at 271   boils at 2868
				Thallium     melts at 304   boils at 2685
				Cadmium      melts at 321   boils at 1502
				Lead         melts at 328   boils at 3188
   gasses in atmosphere:
				Nitrogen         99.3%  PP 274657.0 mb
				Phosphorus        0.5%  PP 1258.0 mb


Planet 5	
   Distance from primary:	1.808	AU
   Mass:			0.066	Earth masses
   Equatorial radius:		2616.6	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.005	Earth atmospheres
   Surface temperature:		-66.78	degrees Celcius
   Normal daytime temperature:	-45.19	degrees Celcius
   Normal night temperature:	-88.49	degrees Celcius
   Maximum temperature:   	-20.29	degrees Celcius
   Minimum temperature:   	-114.03	degrees Celcius
   Escape Velocity:		4.49	km/sec
   Molecular weight retained:	39.31 and above
   Surface acceleration:	385.84	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.405
   Length of year:		844.71	days
   Length of day:		24.64	hours
   Boiling point of water:	-6.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	43.13
   liquids at surface:
				Ethanol      melts at -114  boils at -19
   gasses in atmosphere:
				CarbonDioxide    33.4%  PP    1.5 mb
				Ozone            57.4%  PP    2.6 mb
				Krypton           8.1%  PP    0.4 mb
				Xenon             1.2%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.092	AU
   Mass:			44.755	Earth masses
   Equatorial radius:		33457.9	km
   Density:			1.705	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		32.66	km/sec
   Molecular weight retained:	0.74 and above
   Surface acceleration:	1594.35	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.507
   Length of year:		1051.03	days
   Length of day:		10.24	hours


Planet 7	
   Distance from primary:	3.200	AU
   Mass:			1.469	Earth masses
   Equatorial radius:		7255.8	km
   Density:			5.489	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		1.13	Earth gees
   Surface pressure:		1.821	Earth atmospheres
   Surface temperature:		-113.38	degrees Celcius
   Normal daytime temperature:	-111.68	degrees Celcius
   Normal night temperature:	-115.18	degrees Celcius
   Maximum temperature:   	-97.02	degrees Celcius
   Minimum temperature:   	-131.03	degrees Celcius
   Escape Velocity:		12.71	km/sec
   Molecular weight retained:	4.91 and above
   Surface acceleration:	1113.00	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.640
   Length of year:		1989.04	days
   Length of day:		14.37	hours
   Boiling point of water:	117.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -105
				Ethanol      melts at -114  boils at 95
   gasses in atmosphere:
				Oxygen            0.3%  PP    5.9 mb
				Nitrogen         99.6%  PP 1814.8 mb


Planet 8	*gas giant*
   Distance from primary:	5.962	AU
   Mass:			1051.601	Earth masses
   Equatorial radius:		91681.6	km
   Density:			1.947	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		95.65	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4989.14	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.538
   Length of year:		5050.34	days
   Length of day:		5.79	hours


Planet 9	*gas giant*
   Distance from primary:	15.197	AU
   Mass:			70.606	Earth masses
   Equatorial radius:		45083.7	km
   Density:			1.099	grams/cc
   Eccentricity of orbit:	0.182
   Escape Velocity:		35.34	km/sec
   Molecular weight retained:	0.64 and above
   Surface acceleration:	1385.30	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.467
   Length of year:		20580.61	days
   Length of day:		10.98	hours


Planet 10	*gas giant*
   Distance from primary:	22.259	AU
   Mass:			5.500	Earth masses
   Equatorial radius:		22107.1	km
   Density:			0.726	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		14.09	km/sec
   Molecular weight retained:	4.00 and above
   Surface acceleration:	448.81	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.529
   Length of year:		36486.19	days
   Length of day:		19.29	hours


Planet 11	*gas giant*
   Distance from primary:	37.864	AU
   Mass:			2.240	Earth masses
   Equatorial radius:		17780.8	km
   Density:			0.569	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		10.02	km/sec
   Molecular weight retained:	7.90 and above
   Surface acceleration:	282.51	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.550
   Length of year:		80946.60	days
   Length of day:		24.32	hours


Planet 12	
   Distance from primary:	51.539	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		3296.8	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.80	degrees Celcius
   Normal daytime temperature:	-224.72	degrees Celcius
   Normal night temperature:	-236.75	degrees Celcius
   Maximum temperature:   	-211.22	degrees Celcius
   Minimum temperature:   	-250.35	degrees Celcius
   Escape Velocity:		3.66	km/sec
   Molecular weight retained:	59.33 and above
   Surface acceleration:	202.94	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.142
   Length of year:		128548.34	days
   Length of day:		33.64	hours
   Boiling point of water:	-75.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


