                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ebd
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6270 K
Stellar class: F8
Age: 4.125 billion years  (2.979 billion left on main sequence)
Habitable ecosphere radius: 1.240 AU

Planets present at:
1	  0.347 AU	no atmosphere
2	  0.412 AU	no atmosphere
3	  0.836 AU	greenhouse
4	  1.941 AU	gas giant
5	  4.181 AU	cold
6	  5.872 AU	gas giant
7	  9.851 AU	gas giant
8	 16.486 AU	gas giant
9	 25.772 AU	gas giant
10	 46.296 AU	gas giant



Planet 1	
   Distance from primary:	0.347	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1459.2	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		246.05	degrees Celcius
   Normal daytime temperature:	462.32	degrees Celcius
   Normal night temperature:	-181.89	degrees Celcius
   Maximum temperature:   	465.39	degrees Celcius
   Minimum temperature:   	-192.43	degrees Celcius
   Escape Velocity:		2.50	km/sec
   Molecular weight retained:	126.91 and above
   Surface acceleration:	214.32	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.061
   Length of year:		71.32	days
   Length of day:		1711.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.412	AU
   Mass:			0.360	Earth masses
   Equatorial radius:		4582.6	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.19	degrees Celcius
   Normal daytime temperature:	407.40	degrees Celcius
   Normal night temperature:	-189.95	degrees Celcius
   Maximum temperature:   	410.75	degrees Celcius
   Minimum temperature:   	-200.72	degrees Celcius
   Escape Velocity:		7.92	km/sec
   Molecular weight retained:	12.66 and above
   Surface acceleration:	683.93	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.076
   Length of year:		92.47	days
   Length of day:		1772.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.836	AU
   Mass:			0.970	Earth masses
   Equatorial radius:		6340.0	km
   Density:			5.429	grams/cc
   Eccentricity of orbit:	0.129
   Surface gravity:		0.98	Earth gees
   Surface pressure:		103.108	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		429.90	degrees Celcius
   Maximum temperature:   	434.34	degrees Celcius
   Minimum temperature:   	423.52	degrees Celcius
   Escape Velocity:		11.04	km/sec
   Molecular weight retained:	6.51 and above
   Surface acceleration:	961.99	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.543
   Length of year:		267.29	days
   Length of day:		18.55	hours
   Boiling point of water:	294.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1171
				Cesium       melts at 28    boils at 1214
				Gallium      melts at 30    boils at 3796
				Rubidium     melts at 39    boils at 1188
				Potassium    melts at 63    boils at 1306
				Sodium       melts at 98    boils at 1483
				Sulfur       melts at 113   boils at 819
				Indium       melts at 157   boils at 3305
				Lithium      melts at 181   boils at 2190
				Selenium     melts at 217   boils at 1184
				Tin          melts at 232   boils at 4131
				Polonium     melts at 254   boils at 1605
				Bismuth      melts at 271   boils at 2520
				Thallium     melts at 304   boils at 2358
				Cadmium      melts at 321   boils at 1305
				Lead         melts at 328   boils at 2805
				Zinc         melts at 420   boils at 1521
   gasses in atmosphere:
				Nitrogen         99.1%  PP 102174.7 mb
				Phosphorus        0.6%  PP  619.1 mb
				CarbonDioxide     0.1%  PP   69.1 mb
				Ozone             0.1%  PP   57.5 mb
				Ethanol           0.1%  PP   70.2 mb


Planet 4	*gas giant*
   Distance from primary:	1.941	AU
   Mass:			25.119	Earth masses
   Equatorial radius:		28158.9	km
   Density:			1.605	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		26.67	km/sec
   Molecular weight retained:	1.12 and above
   Surface acceleration:	1263.29	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.490
   Length of year:		945.02	days
   Length of day:		11.50	hours


Planet 5	
   Distance from primary:	4.181	AU
   Mass:			0.349	Earth masses
   Equatorial radius:		4533.8	km
   Density:			5.338	grams/cc
   Eccentricity of orbit:	0.166
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.122	Earth atmospheres
   Surface temperature:		-143.23	degrees Celcius
   Normal daytime temperature:	-137.45	degrees Celcius
   Normal night temperature:	-149.25	degrees Celcius
   Maximum temperature:   	-115.58	degrees Celcius
   Minimum temperature:   	-172.99	degrees Celcius
   Escape Velocity:		7.83	km/sec
   Molecular weight retained:	12.94 and above
   Surface acceleration:	676.38	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.598
   Length of year:		2986.66	days
   Length of day:		18.43	hours
   Boiling point of water:	49.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	74.03
   liquids at surface:
				Ozone        melts at -193  boils at -134
   gasses in atmosphere:
				Oxygen           24.9%  PP   30.5 mb
				Nitrogen         75.0%  PP   91.8 mb
				Methane           0.1%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	5.872	AU
   Mass:			296.944	Earth masses
   Equatorial radius:		63465.3	km
   Density:			1.658	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		61.09	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	2939.96	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.499
   Length of year:		4969.15	days
   Length of day:		7.54	hours


Planet 7	*gas giant*
   Distance from primary:	9.851	AU
   Mass:			10.779	Earth masses
   Equatorial radius:		25190.1	km
   Density:			0.962	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		18.47	km/sec
   Molecular weight retained:	2.33 and above
   Surface acceleration:	677.40	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.536
   Length of year:		10802.57	days
   Length of day:		15.70	hours


Planet 8	*gas giant*
   Distance from primary:	16.486	AU
   Mass:			65.998	Earth masses
   Equatorial radius:		44606.6	km
   Density:			1.061	grams/cc
   Eccentricity of orbit:	0.227
   Escape Velocity:		34.35	km/sec
   Molecular weight retained:	0.67 and above
   Surface acceleration:	1322.73	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.547
   Length of year:		23385.81	days
   Length of day:		11.24	hours


Planet 9	*gas giant*
   Distance from primary:	25.772	AU
   Mass:			38.519	Earth masses
   Equatorial radius:		39569.6	km
   Density:			0.887	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		27.86	km/sec
   Molecular weight retained:	1.02 and above
   Surface acceleration:	981.06	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.456
   Length of year:		45710.76	days
   Length of day:		13.05	hours


Planet 10	*gas giant*
   Distance from primary:	46.296	AU
   Mass:			0.298	Earth masses
   Equatorial radius:		10059.8	km
   Density:			0.417	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		4.86	km/sec
   Molecular weight retained:	33.63 and above
   Surface acceleration:	117.31	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.509
   Length of year:		110063.83	days
   Length of day:		37.74	hours


