                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048880
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6131 K
Stellar class: F9
Age: 4.733 billion years  (2.043 billion left on main sequence)
Habitable ecosphere radius: 1.278 AU

Planets present at:
1	  0.311 AU	no atmosphere
2	  0.430 AU	no atmosphere
3	  0.556 AU	no atmosphere
4	  1.011 AU	greenhouse
5	  1.847 AU	gas giant
6	  2.862 AU	gas giant
7	  6.257 AU	gas giant
8	  8.635 AU	gas giant
9	 13.115 AU	gas giant
10	 24.421 AU	no atmosphere
11	 40.057 AU	gas giant
12	 51.281 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.311	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		2466.6	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.141
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		282.94	degrees Celcius
   Normal daytime temperature:	505.30	degrees Celcius
   Normal night temperature:	-158.25	degrees Celcius
   Maximum temperature:   	509.12	degrees Celcius
   Minimum temperature:   	-172.64	degrees Celcius
   Escape Velocity:		4.23	km/sec
   Molecular weight retained:	44.27 and above
   Surface acceleration:	363.49	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.065
   Length of year:		60.14	days
   Length of day:		1085.94	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.430	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1636.7	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		197.45	degrees Celcius
   Maximum temperature:   	406.66	degrees Celcius
   Minimum temperature:   	-206.58	degrees Celcius
   Escape Velocity:		2.81	km/sec
   Molecular weight retained:	100.83 and above
   Surface acceleration:	240.51	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.080
   Length of year:		98.07	days
   Length of day:		2353.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.556	AU
   Mass:			0.347	Earth masses
   Equatorial radius:		4528.1	km
   Density:			5.338	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		140.89	degrees Celcius
   Maximum temperature:   	336.99	degrees Celcius
   Minimum temperature:   	-218.55	degrees Celcius
   Escape Velocity:		7.82	km/sec
   Molecular weight retained:	12.98 and above
   Surface acceleration:	675.51	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.082
   Length of year:		143.81	days
   Length of day:		3451.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.011	AU
   Mass:			1.816	Earth masses
   Equatorial radius:		7769.1	km
   Density:			5.526	grams/cc
   Eccentricity of orbit:	0.192
   Surface gravity:		1.22	Earth gees
   Surface pressure:		246.665	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		498.77	degrees Celcius
   Maximum temperature:   	501.42	degrees Celcius
   Minimum temperature:   	493.71	degrees Celcius
   Escape Velocity:		13.65	km/sec
   Molecular weight retained:	4.26 and above
   Surface acceleration:	1199.86	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.472
   Length of year:		352.92	days
   Length of day:		14.38	hours
   Boiling point of water:	355.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1328
				Cesium       melts at 28    boils at 1376
				Gallium      melts at 30    boils at 4238
				Rubidium     melts at 39    boils at 1347
				Potassium    melts at 63    boils at 1478
				Sodium       melts at 98    boils at 1673
				Indium       melts at 157   boils at 3693
				Lithium      melts at 181   boils at 2458
				Selenium     melts at 217   boils at 1342
				Tin          melts at 232   boils at 4609
				Polonium     melts at 254   boils at 1809
				Bismuth      melts at 271   boils at 2824
				Thallium     melts at 304   boils at 2643
				Cadmium      melts at 321   boils at 1477
				Lead         melts at 328   boils at 3139
				Zinc         melts at 420   boils at 1716
				Tellurium    melts at 450   boils at 1856
   gasses in atmosphere:
				Sulfur           19.6%  PP 48286.8 mb
				Nitrogen         79.8%  PP 196958.8 mb
				Phosphorus        0.4%  PP  963.4 mb


Planet 5	*gas giant*
   Distance from primary:	1.847	AU
   Mass:			30.431	Earth masses
   Equatorial radius:		29582.7	km
   Density:			1.677	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		28.64	km/sec
   Molecular weight retained:	0.97 and above
   Surface acceleration:	1386.68	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.493
   Length of year:		871.72	days
   Length of day:		10.98	hours


Planet 6	*gas giant*
   Distance from primary:	2.862	AU
   Mass:			99.350	Earth masses
   Equatorial radius:		43326.9	km
   Density:			1.743	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		42.77	km/sec
   Molecular weight retained:	0.43 and above
   Surface acceleration:	2110.54	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.474
   Length of year:		1680.89	days
   Length of day:		8.90	hours


Planet 7	*gas giant*
   Distance from primary:	6.257	AU
   Mass:			46.030	Earth masses
   Equatorial radius:		36949.7	km
   Density:			1.302	grams/cc
   Eccentricity of orbit:	0.144
   Escape Velocity:		31.52	km/sec
   Molecular weight retained:	0.80 and above
   Surface acceleration:	1344.50	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.536
   Length of year:		5433.70	days
   Length of day:		11.15	hours


Planet 8	*gas giant*
   Distance from primary:	8.635	AU
   Mass:			12.360	Earth masses
   Equatorial radius:		25865.6	km
   Density:			1.019	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		19.52	km/sec
   Molecular weight retained:	2.08 and above
   Surface acceleration:	736.72	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.538
   Length of year:		8811.32	days
   Length of day:		15.06	hours


Planet 9	*gas giant*
   Distance from primary:	13.115	AU
   Mass:			475.873	Earth masses
   Equatorial radius:		77674.6	km
   Density:			1.449	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		69.90	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3145.37	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.457
   Length of year:		16482.32	days
   Length of day:		7.29	hours


Planet 10	
   Distance from primary:	24.421	AU
   Mass:			0.502	Earth masses
   Equatorial radius:		6817.4	km
   Density:			2.259	grams/cc
   Eccentricity of orbit:	0.135
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-210.60	degrees Celcius
   Normal daytime temperature:	-204.17	degrees Celcius
   Normal night temperature:	-216.99	degrees Celcius
   Maximum temperature:   	-185.88	degrees Celcius
   Minimum temperature:   	-236.29	degrees Celcius
   Escape Velocity:		7.66	km/sec
   Molecular weight retained:	13.53 and above
   Surface acceleration:	430.44	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.149
   Length of year:		41904.80	days
   Length of day:		23.10	hours
   Boiling point of water:	-33.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.5 mb


Planet 11	*gas giant*
   Distance from primary:	40.057	AU
   Mass:			1.473	Earth masses
   Equatorial radius:		15805.0	km
   Density:			0.532	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		8.62	km/sec
   Molecular weight retained:	10.68 and above
   Surface acceleration:	235.12	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.500
   Length of year:		88032.42	days
   Length of day:		26.65	hours


Planet 12	
   Distance from primary:	51.281	AU
   Mass:			1/261.5	Earth masses
   Equatorial radius:		1356.0	km
   Density:			2.189	grams/cc
   Eccentricity of orbit:	0.161
   Surface gravity:		0.08	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.66	degrees Celcius
   Normal daytime temperature:	-221.84	degrees Celcius
   Normal night temperature:	-239.27	degrees Celcius
   Maximum temperature:   	-203.73	degrees Celcius
   Minimum temperature:   	-255.66	degrees Celcius
   Escape Velocity:		1.50	km/sec
   Molecular weight retained:	352.88 and above
   Surface acceleration:	82.94	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.143
   Length of year:		127515.31	days
   Length of day:		52.62	hours
   Boiling point of water:	-108.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.02


