                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047fc9
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6201 K
Stellar class: F8
Age: 5.600 billion years  (1.467 billion left on main sequence)
Habitable ecosphere radius: 1.244 AU

Planets present at:
1	  0.343 AU	no atmosphere
2	  0.529 AU	no atmosphere
3	  1.051 AU	no atmosphere
4	  1.241 AU	high pressure
5	  2.071 AU	cold
6	  2.630 AU	cold
7	  3.251 AU	gas giant
8	  5.309 AU	gas giant
9	  9.209 AU	gas giant
10	 21.386 AU	no atmosphere
11	 34.241 AU	gas giant
12	 51.206 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.343	AU
   Mass:			0.352	Earth masses
   Equatorial radius:		4548.1	km
   Density:			5.339	grams/cc
   Eccentricity of orbit:	0.261
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		250.01	degrees Celcius
   Normal daytime temperature:	464.66	degrees Celcius
   Normal night temperature:	-159.94	degrees Celcius
   Maximum temperature:   	469.21	degrees Celcius
   Minimum temperature:   	-176.58	degrees Celcius
   Escape Velocity:		7.86	km/sec
   Molecular weight retained:	12.86 and above
   Surface acceleration:	678.59	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.060
   Length of year:		70.06	days
   Length of day:		985.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.529	AU
   Mass:			0.588	Earth masses
   Equatorial radius:		5382.5	km
   Density:			5.377	grams/cc
   Eccentricity of orbit:	0.299
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		147.59	degrees Celcius
   Normal daytime temperature:	340.87	degrees Celcius
   Normal night temperature:	-197.96	degrees Celcius
   Maximum temperature:   	344.95	degrees Celcius
   Minimum temperature:   	-210.18	degrees Celcius
   Escape Velocity:		9.33	km/sec
   Molecular weight retained:	9.12 and above
   Surface acceleration:	808.81	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.065
   Length of year:		134.18	days
   Length of day:		1737.05	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.051	AU
   Mass:			0.112	Earth masses
   Equatorial radius:		3116.5	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		26.47	degrees Celcius
   Normal daytime temperature:	69.55	degrees Celcius
   Normal night temperature:	-17.17	degrees Celcius
   Maximum temperature:   	98.38	degrees Celcius
   Minimum temperature:   	-46.42	degrees Celcius
   Escape Velocity:		5.36	km/sec
   Molecular weight retained:	27.65 and above
   Surface acceleration:	460.67	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.050
   Length of year:		376.33	days
   Length of day:		34.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 4	
   Distance from primary:	1.241	AU
   Mass:			2.142	Earth masses
   Equatorial radius:		8191.9	km
   Density:			5.559	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		1.30	Earth gees
   Surface pressure:		4.509	Earth atmospheres
   Surface temperature:		18.93	degrees Celcius
   Normal daytime temperature:	20.81	degrees Celcius
   Normal night temperature:	16.92	degrees Celcius
   Maximum temperature:   	32.48	degrees Celcius
   Minimum temperature:   	4.66	degrees Celcius
   Escape Velocity:		14.44	km/sec
   Molecular weight retained:	3.81 and above
   Surface acceleration:	1272.77	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.451
   Length of year:		482.80	days
   Length of day:		13.58	hours
   Boiling point of water:	146.7	degrees Celcius
   Hydrosphere percentage:	90.68
   Cloud cover percentage:	85.23
   Ice cover percentage:	1.01
   liquids at surface:
				Ethanol      melts at -114  boils at 123
				Mercury      melts at -39   boils at 436
				Bromine      melts at -7    boils at 101
				Water        melts at 0     boils at 147
   gasses in atmosphere:
				Nitrogen          2.5%  PP  112.7 mb
				Helium           97.5%  PP 4396.5 mb


Planet 5	
   Distance from primary:	2.071	AU
   Mass:			0.919	Earth masses
   Equatorial radius:		6230.6	km
   Density:			5.423	grams/cc
   Eccentricity of orbit:	0.175
   Surface gravity:		0.96	Earth gees
   Surface pressure:		0.752	Earth atmospheres
   Surface temperature:		-83.73	degrees Celcius
   Normal daytime temperature:	-80.39	degrees Celcius
   Normal night temperature:	-87.25	degrees Celcius
   Maximum temperature:   	-58.38	degrees Celcius
   Minimum temperature:   	-110.92	degrees Celcius
   Escape Velocity:		10.85	km/sec
   Molecular weight retained:	6.75 and above
   Surface acceleration:	944.26	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.648
   Length of year:		1040.43	days
   Length of day:		15.61	hours
   Boiling point of water:	92.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	91.35
   liquids at surface:
				Ethanol      melts at -114  boils at 71
				Chlorine     melts at -101  boils at -39
   gasses in atmosphere:
				Oxygen            0.1%  PP    0.4 mb
				Nitrogen         99.8%  PP  750.7 mb
				Ozone             0.1%  PP    0.5 mb


Planet 6	
   Distance from primary:	2.630	AU
   Mass:			0.550	Earth masses
   Equatorial radius:		5268.0	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.259	Earth atmospheres
   Surface temperature:		-100.04	degrees Celcius
   Normal daytime temperature:	-94.70	degrees Celcius
   Normal night temperature:	-105.63	degrees Celcius
   Maximum temperature:   	-73.29	degrees Celcius
   Minimum temperature:   	-128.66	degrees Celcius
   Escape Velocity:		9.13	km/sec
   Molecular weight retained:	9.53 and above
   Surface acceleration:	790.78	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.556
   Length of year:		1489.21	days
   Length of day:		17.05	hours
   Boiling point of water:	66.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	73.60
   liquids at surface:
				Ethanol      melts at -114  boils at 47
				Chlorine     melts at -101  boils at -56
   gasses in atmosphere:
				Oxygen            1.5%  PP    4.0 mb
				Nitrogen         98.3%  PP  254.9 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.251	AU
   Mass:			11.879	Earth masses
   Equatorial radius:		23621.1	km
   Density:			1.286	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		20.03	km/sec
   Molecular weight retained:	1.98 and above
   Surface acceleration:	849.01	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.490
   Length of year:		2046.45	days
   Length of day:		14.03	hours


Planet 8	*gas giant*
   Distance from primary:	5.309	AU
   Mass:			827.934	Earth masses
   Equatorial radius:		84851.3	km
   Density:			1.934	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		88.22	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4585.84	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.467
   Length of year:		4266.17	days
   Length of day:		6.04	hours


Planet 9	*gas giant*
   Distance from primary:	9.209	AU
   Mass:			308.372	Earth masses
   Equatorial radius:		66602.8	km
   Density:			1.489	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		60.77	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	2772.23	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.466
   Length of year:		9754.38	days
   Length of day:		7.76	hours


Planet 10	
   Distance from primary:	21.386	AU
   Mass:			0.772	Earth masses
   Equatorial radius:		7843.3	km
   Density:			2.284	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-206.64	degrees Celcius
   Normal daytime temperature:	-200.31	degrees Celcius
   Normal night temperature:	-212.95	degrees Celcius
   Maximum temperature:   	-185.40	degrees Celcius
   Minimum temperature:   	-229.02	degrees Celcius
   Escape Velocity:		8.86	km/sec
   Molecular weight retained:	10.11 and above
   Surface acceleration:	500.65	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.137
   Length of year:		34533.36	days
   Length of day:		21.42	hours
   Boiling point of water:	-22.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.12
   gasses in atmosphere:
				Neon             100.0%  PP    1.4 mb


Planet 11	*gas giant*
   Distance from primary:	34.241	AU
   Mass:			0.918	Earth masses
   Equatorial radius:		13618.6	km
   Density:			0.518	grams/cc
   Eccentricity of orbit:	0.150
   Escape Velocity:		7.33	km/sec
   Molecular weight retained:	14.77 and above
   Surface acceleration:	197.28	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.484
   Length of year:		69960.47	days
   Length of day:		29.10	hours


Planet 12	
   Distance from primary:	51.206	AU
   Mass:			0.148	Earth masses
   Equatorial radius:		4568.6	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.09	degrees Celcius
   Normal daytime temperature:	-225.86	degrees Celcius
   Normal night temperature:	-236.20	degrees Celcius
   Maximum temperature:   	-210.24	degrees Celcius
   Minimum temperature:   	-251.78	degrees Celcius
   Escape Velocity:		5.09	km/sec
   Molecular weight retained:	30.68 and above
   Surface acceleration:	283.22	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.138
   Length of year:		127941.94	days
   Length of day:		28.48	hours
   Boiling point of water:	-56.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


