                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488b2
Stellar mass: 1.11 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6261 K
Stellar class: F8
Age: 2.335 billion years  (4.434 billion left on main sequence)
Habitable ecosphere radius: 1.279 AU

Planets present at:
1	  0.337 AU	no atmosphere
2	  0.389 AU	no atmosphere
3	  0.470 AU	no atmosphere
4	  0.740 AU	no atmosphere
5	  1.012 AU	greenhouse
6	  2.018 AU	gas giant
7	  4.020 AU	gas giant
8	  7.734 AU	gas giant
9	 12.414 AU	gas giant
10	 17.774 AU	gas giant
11	 27.859 AU	gas giant
12	 47.377 AU	gas giant



Planet 1	
   Distance from primary:	0.337	AU
   Mass:			0.022	Earth masses
   Equatorial radius:		1806.0	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		260.79	degrees Celcius
   Normal daytime temperature:	480.13	degrees Celcius
   Normal night temperature:	-178.02	degrees Celcius
   Maximum temperature:   	483.22	degrees Celcius
   Minimum temperature:   	-188.88	degrees Celcius
   Escape Velocity:		3.10	km/sec
   Molecular weight retained:	82.78 and above
   Surface acceleration:	265.50	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.068
   Length of year:		67.83	days
   Length of day:		1627.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.389	AU
   Mass:			1/264.8	Earth masses
   Equatorial radius:		1008.7	km
   Density:			5.250	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		223.91	degrees Celcius
   Maximum temperature:   	438.68	degrees Celcius
   Minimum temperature:   	-199.40	degrees Celcius
   Escape Velocity:		1.73	km/sec
   Molecular weight retained:	265.84 and above
   Surface acceleration:	148.02	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.066
   Length of year:		84.20	days
   Length of day:		2020.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.470	AU
   Mass:			0.292	Earth masses
   Equatorial radius:		4274.4	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.132
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		180.58	degrees Celcius
   Normal daytime temperature:	382.37	degrees Celcius
   Normal night temperature:	-196.61	degrees Celcius
   Maximum temperature:   	385.72	degrees Celcius
   Minimum temperature:   	-206.93	degrees Celcius
   Escape Velocity:		7.38	km/sec
   Molecular weight retained:	14.59 and above
   Surface acceleration:	636.44	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.052
   Length of year:		111.95	days
   Length of day:		2060.09	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.740	AU
   Mass:			0.236	Earth masses
   Equatorial radius:		3986.7	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		88.08	degrees Celcius
   Normal daytime temperature:	163.92	degrees Celcius
   Normal night temperature:	8.74	degrees Celcius
   Maximum temperature:   	192.10	degrees Celcius
   Minimum temperature:   	-21.25	degrees Celcius
   Escape Velocity:		6.87	km/sec
   Molecular weight retained:	16.81 and above
   Surface acceleration:	592.40	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.056
   Length of year:		221.21	days
   Length of day:		56.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.012	AU
   Mass:			2.079	Earth masses
   Equatorial radius:		8113.9	km
   Density:			5.553	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		1.28	Earth gees
   Surface pressure:		352.145	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		509.83	degrees Celcius
   Maximum temperature:   	512.00	degrees Celcius
   Minimum temperature:   	505.19	degrees Celcius
   Escape Velocity:		14.29	km/sec
   Molecular weight retained:	3.88 and above
   Surface acceleration:	1259.22	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.558
   Length of year:		353.36	days
   Length of day:		13.73	hours
   Boiling point of water:	384.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1403
				Cesium       melts at 28    boils at 1452
				Gallium      melts at 30    boils at 4447
				Rubidium     melts at 39    boils at 1422
				Potassium    melts at 63    boils at 1559
				Sodium       melts at 98    boils at 1763
				Indium       melts at 157   boils at 3877
				Lithium      melts at 181   boils at 2584
				Selenium     melts at 217   boils at 1417
				Tin          melts at 232   boils at 4835
				Polonium     melts at 254   boils at 1905
				Bismuth      melts at 271   boils at 2967
				Thallium     melts at 304   boils at 2778
				Cadmium      melts at 321   boils at 1558
				Lead         melts at 328   boils at 3297
				Zinc         melts at 420   boils at 1808
				Tellurium    melts at 450   boils at 1955
   gasses in atmosphere:
				Sulfur            0.7%  PP 2549.1 mb
				Nitrogen          3.3%  PP 11709.6 mb
				Helium           95.9%  PP 337810.0 mb


Planet 6	*gas giant*
   Distance from primary:	2.018	AU
   Mass:			28.498	Earth masses
   Equatorial radius:		29234.7	km
   Density:			1.627	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		27.88	km/sec
   Molecular weight retained:	1.02 and above
   Surface acceleration:	1329.70	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.456
   Length of year:		995.03	days
   Length of day:		11.21	hours


Planet 7	*gas giant*
   Distance from primary:	4.020	AU
   Mass:			204.701	Earth masses
   Equatorial radius:		55030.6	km
   Density:			1.753	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		54.47	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2695.57	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.487
   Length of year:		2797.78	days
   Length of day:		7.87	hours


Planet 8	*gas giant*
   Distance from primary:	7.734	AU
   Mass:			327.719	Earth masses
   Equatorial radius:		66664.4	km
   Density:			1.578	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		62.62	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2940.72	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.452
   Length of year:		7463.61	days
   Length of day:		7.54	hours


Planet 9	*gas giant*
   Distance from primary:	12.414	AU
   Mass:			1.717	Earth masses
   Equatorial radius:		14990.8	km
   Density:			0.727	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		9.56	km/sec
   Molecular weight retained:	8.69 and above
   Surface acceleration:	304.73	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.515
   Length of year:		15185.55	days
   Length of day:		23.41	hours


Planet 10	*gas giant*
   Distance from primary:	17.774	AU
   Mass:			59.044	Earth masses
   Equatorial radius:		43342.7	km
   Density:			1.035	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		32.96	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1253.39	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.454
   Length of year:		26013.26	days
   Length of day:		11.54	hours


Planet 11	*gas giant*
   Distance from primary:	27.859	AU
   Mass:			22.346	Earth masses
   Equatorial radius:		33892.6	km
   Density:			0.819	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		22.93	km/sec
   Molecular weight retained:	1.51 and above
   Surface acceleration:	775.77	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.494
   Length of year:		51050.79	days
   Length of day:		14.67	hours


Planet 12	*gas giant*
   Distance from primary:	47.377	AU
   Mass:			0.318	Earth masses
   Equatorial radius:		10246.7	km
   Density:			0.421	grams/cc
   Eccentricity of orbit:	0.098
   Escape Velocity:		4.97	km/sec
   Molecular weight retained:	32.10 and above
   Surface acceleration:	120.69	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.517
   Length of year:		113220.17	days
   Length of day:		37.20	hours


