                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485f8
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6182 K
Stellar class: F8
Age: 3.636 billion years  (3.222 billion left on main sequence)
Habitable ecosphere radius: 1.268 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.438 AU	no atmosphere
3	  0.536 AU	no atmosphere
4	  0.882 AU	greenhouse
5	  1.119 AU	greenhouse
6	  1.254 AU	high pressure
7	  2.105 AU	cold
8	  2.817 AU	gas giant
9	  4.321 AU	gas giant
10	  6.618 AU	gas giant
11	 11.089 AU	gas giant
12	 15.882 AU	gas giant
13	 24.342 AU	gas giant
14	 38.730 AU	gas giant
15	 50.668 AU	no atmosphere



Planet 1	
   Distance from primary:	0.358	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2231.4	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		241.73	degrees Celcius
   Maximum temperature:   	460.09	degrees Celcius
   Minimum temperature:   	-193.66	degrees Celcius
   Escape Velocity:		3.83	km/sec
   Molecular weight retained:	54.14 and above
   Surface acceleration:	328.52	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.073
   Length of year:		74.54	days
   Length of day:		1788.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.438	AU
   Mass:			0.066	Earth masses
   Equatorial radius:		2612.8	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		190.70	degrees Celcius
   Maximum temperature:   	398.18	degrees Celcius
   Minimum temperature:   	-207.18	degrees Celcius
   Escape Velocity:		4.49	km/sec
   Molecular weight retained:	39.43 and above
   Surface acceleration:	385.28	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.087
   Length of year:		100.84	days
   Length of day:		2420.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.536	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1942.0	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		146.93	degrees Celcius
   Maximum temperature:   	344.29	degrees Celcius
   Minimum temperature:   	-216.73	degrees Celcius
   Escape Velocity:		3.33	km/sec
   Molecular weight retained:	71.55 and above
   Surface acceleration:	285.63	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.080
   Length of year:		136.48	days
   Length of day:		3275.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.882	AU
   Mass:			0.632	Earth masses
   Equatorial radius:		5511.8	km
   Density:			5.383	grams/cc
   Eccentricity of orbit:	0.139
   Surface gravity:		0.85	Earth gees
   Surface pressure:		34.336	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		194.57	degrees Celcius
   Maximum temperature:   	201.77	degrees Celcius
   Minimum temperature:   	186.74	degrees Celcius
   Escape Velocity:		9.56	km/sec
   Molecular weight retained:	8.68 and above
   Surface acceleration:	829.25	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.578
   Length of year:		288.33	days
   Length of day:		19.70	hours
   Boiling point of water:	231.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 580
				Francium     melts at 27    boils at 1013
				Cesium       melts at 28    boils at 1051
				Gallium      melts at 30    boils at 3349
				Rubidium     melts at 39    boils at 1028
				Phosphorus   melts at 44    boils at 476
				Potassium    melts at 63    boils at 1133
				Sodium       melts at 98    boils at 1290
				Sulfur       melts at 113   boils at 699
				Indium       melts at 157   boils at 2912
				Lithium      melts at 181   boils at 1919
   gasses in atmosphere:
				Nitrogen         99.6%  PP 34199.2 mb
				CarbonDioxide     0.1%  PP   30.4 mb
				Ozone             0.1%  PP   29.5 mb
				Ethanol           0.1%  PP   30.9 mb


Planet 5	
   Distance from primary:	1.119	AU
   Mass:			0.157	Earth masses
   Equatorial radius:		3482.0	km
   Density:			5.300	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.53	Earth gees
   Surface pressure:		2.451	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		44.20	degrees Celcius
   Normal daytime temperature:	48.75	degrees Celcius
   Normal night temperature:	39.16	degrees Celcius
   Maximum temperature:   	64.40	degrees Celcius
   Minimum temperature:   	22.75	degrees Celcius
   Escape Velocity:		5.99	km/sec
   Molecular weight retained:	22.10 and above
   Surface acceleration:	515.76	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.044
   Length of year:		411.70	days
   Length of day:		23.94	hours
   Boiling point of water:	126.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 103
				Mercury      melts at -39   boils at 402
				Bromine      melts at -7    boils at 83
				Water        melts at 0     boils at 126
				Francium     melts at 27    boils at 744
				Cesium       melts at 28    boils at 774
				Gallium      melts at 30    boils at 2593
				Rubidium     melts at 39    boils at 756
				Phosphorus   melts at 44    boils at 320
   gasses in atmosphere:
				CarbonDioxide    45.7%  PP 1120.7 mb
				Ozone            50.3%  PP 1231.7 mb
				Argon             0.1%  PP    2.8 mb
				Krypton           3.5%  PP   84.7 mb
				Xenon             0.4%  PP   10.7 mb


Planet 6	
   Distance from primary:	1.254	AU
   Mass:			2.051	Earth masses
   Equatorial radius:		8078.9	km
   Density:			5.550	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		1.28	Earth gees
   Surface pressure:		4.480	Earth atmospheres
   Surface temperature:		16.43	degrees Celcius
   Normal daytime temperature:	18.31	degrees Celcius
   Normal night temperature:	14.43	degrees Celcius
   Maximum temperature:   	30.04	degrees Celcius
   Minimum temperature:   	2.11	degrees Celcius
   Escape Velocity:		14.23	km/sec
   Molecular weight retained:	3.92 and above
   Surface acceleration:	1253.16	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.478
   Length of year:		488.40	days
   Length of day:		13.64	hours
   Boiling point of water:	146.5	degrees Celcius
   Hydrosphere percentage:	96.73
   Cloud cover percentage:	77.41
   Ice cover percentage:	1.37
   liquids at surface:
				Ethanol      melts at -114  boils at 122
				Mercury      melts at -39   boils at 435
				Bromine      melts at -7    boils at 101
				Water        melts at 0     boils at 146
   gasses in atmosphere:
				Nitrogen          5.0%  PP  223.9 mb
				Helium           95.0%  PP 4255.7 mb


Planet 7	
   Distance from primary:	2.105	AU
   Mass:			0.936	Earth masses
   Equatorial radius:		6266.6	km
   Density:			5.425	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.827	Earth atmospheres
   Surface temperature:		-83.89	degrees Celcius
   Normal daytime temperature:	-80.71	degrees Celcius
   Normal night temperature:	-87.24	degrees Celcius
   Maximum temperature:   	-62.06	degrees Celcius
   Minimum temperature:   	-107.30	degrees Celcius
   Escape Velocity:		10.91	km/sec
   Molecular weight retained:	6.67 and above
   Surface acceleration:	950.09	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.655
   Length of year:		1061.83	days
   Length of day:		15.56	hours
   Boiling point of water:	94.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	97.62
   liquids at surface:
				Ethanol      melts at -114  boils at 74
				Chlorine     melts at -101  boils at -37
   gasses in atmosphere:
				Oxygen            1.1%  PP    9.0 mb
				Nitrogen         98.8%  PP  817.5 mb
				Ozone             0.1%  PP    0.5 mb


Planet 8	*gas giant*
   Distance from primary:	2.817	AU
   Mass:			31.401	Earth masses
   Equatorial radius:		30943.2	km
   Density:			1.512	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		28.45	km/sec
   Molecular weight retained:	0.98 and above
   Surface acceleration:	1307.84	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.518
   Length of year:		1644.24	days
   Length of day:		11.30	hours


Planet 9	*gas giant*
   Distance from primary:	4.321	AU
   Mass:			3.269	Earth masses
   Equatorial radius:		16576.3	km
   Density:			1.024	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		12.54	km/sec
   Molecular weight retained:	5.05 and above
   Surface acceleration:	474.47	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.534
   Length of year:		3123.97	days
   Length of day:		18.76	hours


Planet 10	*gas giant*
   Distance from primary:	6.618	AU
   Mass:			1012.838	Earth masses
   Equatorial radius:		91513.4	km
   Density:			1.886	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		93.95	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4822.92	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.536
   Length of year:		5913.19	days
   Length of day:		5.89	hours


Planet 11	*gas giant*
   Distance from primary:	11.089	AU
   Mass:			4.242	Earth masses
   Equatorial radius:		19346.6	km
   Density:			0.836	grams/cc
   Eccentricity of orbit:	0.129
   Escape Velocity:		13.22	km/sec
   Molecular weight retained:	4.54 and above
   Surface acceleration:	452.01	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.529
   Length of year:		12843.56	days
   Length of day:		19.22	hours


Planet 12	*gas giant*
   Distance from primary:	15.882	AU
   Mass:			0.714	Earth masses
   Equatorial radius:		11852.1	km
   Density:			0.612	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		6.93	km/sec
   Molecular weight retained:	16.53 and above
   Surface acceleration:	202.56	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.463
   Length of year:		22012.35	days
   Length of day:		28.72	hours


Planet 13	*gas giant*
   Distance from primary:	24.342	AU
   Mass:			90.247	Earth masses
   Equatorial radius:		50389.4	km
   Density:			1.006	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		37.79	km/sec
   Molecular weight retained:	0.56 and above
   Surface acceleration:	1417.40	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.482
   Length of year:		41765.12	days
   Length of day:		10.86	hours


Planet 14	*gas giant*
   Distance from primary:	38.730	AU
   Mass:			0.698	Earth masses
   Equatorial radius:		12683.2	km
   Density:			0.488	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		6.62	km/sec
   Molecular weight retained:	18.09 and above
   Surface acceleration:	172.98	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.510
   Length of year:		83829.41	days
   Length of day:		31.08	hours


Planet 15	
   Distance from primary:	50.668	AU
   Mass:			0.077	Earth masses
   Equatorial radius:		3684.0	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.080
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.78	degrees Celcius
   Normal daytime temperature:	-224.99	degrees Celcius
   Normal night temperature:	-236.45	degrees Celcius
   Maximum temperature:   	-212.93	degrees Celcius
   Minimum temperature:   	-248.83	degrees Celcius
   Escape Velocity:		4.09	km/sec
   Molecular weight retained:	47.42 and above
   Surface acceleration:	227.20	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.161
   Length of year:		125436.01	days
   Length of day:		31.80	hours
   Boiling point of water:	-69.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


