                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486c7
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6121 K
Stellar class: F9
Age: 5.297 billion years  (1.535 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.348 AU	no atmosphere
2	  0.532 AU	no atmosphere
3	  0.620 AU	greenhouse
4	  0.887 AU	greenhouse
5	  1.534 AU	gas giant
6	  1.965 AU	gas giant
7	  4.485 AU	gas giant
8	  7.323 AU	gas giant
9	 16.391 AU	gas giant
10	 27.740 AU	gas giant
11	 40.419 AU	no atmosphere
12	 48.740 AU	no atmosphere



Planet 1	
   Distance from primary:	0.348	AU
   Mass:			0.121	Earth masses
   Equatorial radius:		3198.8	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		247.42	degrees Celcius
   Normal daytime temperature:	464.00	degrees Celcius
   Normal night temperature:	-181.73	degrees Celcius
   Maximum temperature:   	467.10	degrees Celcius
   Minimum temperature:   	-192.38	degrees Celcius
   Escape Velocity:		5.50	km/sec
   Molecular weight retained:	26.23 and above
   Surface acceleration:	473.05	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.088
   Length of year:		71.45	days
   Length of day:		1714.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.532	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		1848.7	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		152.04	degrees Celcius
   Maximum temperature:   	350.76	degrees Celcius
   Minimum temperature:   	-216.35	degrees Celcius
   Escape Velocity:		3.17	km/sec
   Molecular weight retained:	78.99 and above
   Surface acceleration:	271.82	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.052
   Length of year:		135.03	days
   Length of day:		3240.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.620	AU
   Mass:			0.703	Earth masses
   Equatorial radius:		5708.8	km
   Density:			5.394	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.88	Earth gees
   Surface pressure:		49.512	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		316.00	degrees Celcius
   Maximum temperature:   	331.96	degrees Celcius
   Minimum temperature:   	256.08	degrees Celcius
   Escape Velocity:		9.91	km/sec
   Molecular weight retained:	8.08 and above
   Surface acceleration:	860.53	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.555
   Length of year:		169.83	days
   Length of day:		4075.84	hours
   Boiling point of water:	251.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 612
				Francium     melts at 27    boils at 1061
				Cesium       melts at 28    boils at 1101
				Gallium      melts at 30    boils at 3486
				Rubidium     melts at 39    boils at 1077
				Potassium    melts at 63    boils at 1186
				Sodium       melts at 98    boils at 1349
				Sulfur       melts at 113   boils at 735
				Indium       melts at 157   boils at 3033
				Lithium      melts at 181   boils at 2003
				Selenium     melts at 217   boils at 1073
				Tin          melts at 232   boils at 3795
				Polonium     melts at 254   boils at 1462
				Bismuth      melts at 271   boils at 2308
				Astatine     melts at 302   boils at 584
				Thallium     melts at 304   boils at 2157
   gasses in atmosphere:
				Nitrogen         98.7%  PP 48877.1 mb
				Phosphorus        0.8%  PP  418.2 mb
				CarbonDioxide     0.1%  PP   50.8 mb
				Ozone             0.1%  PP   46.8 mb
				Ethanol           0.1%  PP   52.2 mb


Planet 4	
   Distance from primary:	0.887	AU
   Mass:			0.593	Earth masses
   Equatorial radius:		5397.9	km
   Density:			5.378	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.83	Earth gees
   Surface pressure:		28.528	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		164.56	degrees Celcius
   Maximum temperature:   	172.03	degrees Celcius
   Minimum temperature:   	156.51	degrees Celcius
   Escape Velocity:		9.36	km/sec
   Molecular weight retained:	9.06 and above
   Surface acceleration:	811.25	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.459
   Length of year:		290.18	days
   Length of day:		21.92	hours
   Boiling point of water:	222.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 564
				Francium     melts at 27    boils at 989
				Cesium       melts at 28    boils at 1026
				Gallium      melts at 30    boils at 3283
				Rubidium     melts at 39    boils at 1004
				Phosphorus   melts at 44    boils at 463
				Potassium    melts at 63    boils at 1107
				Sodium       melts at 98    boils at 1261
				Sulfur       melts at 113   boils at 681
				Iodine       melts at 114   boils at 336
				Indium       melts at 157   boils at 2854
   gasses in atmosphere:
				Nitrogen         99.5%  PP 28395.9 mb
				CarbonDioxide     0.1%  PP   30.6 mb
				Ozone             0.1%  PP   29.7 mb
				Ethanol           0.1%  PP   31.4 mb


Planet 5	*gas giant*
   Distance from primary:	1.534	AU
   Mass:			8.021	Earth masses
   Equatorial radius:		19751.9	km
   Density:			1.485	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		18.00	km/sec
   Molecular weight retained:	2.45 and above
   Surface acceleration:	819.86	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.541
   Length of year:		660.64	days
   Length of day:		14.28	hours


Planet 6	*gas giant*
   Distance from primary:	1.965	AU
   Mass:			2.333	Earth masses
   Equatorial radius:		14065.4	km
   Density:			1.197	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		11.50	km/sec
   Molecular weight retained:	6.00 and above
   Surface acceleration:	470.34	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.467
   Length of year:		957.20	days
   Length of day:		18.85	hours


Planet 7	*gas giant*
   Distance from primary:	4.485	AU
   Mass:			15.982	Earth masses
   Equatorial radius:		26409.1	km
   Density:			1.238	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		21.97	km/sec
   Molecular weight retained:	1.64 and above
   Surface acceleration:	913.82	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.502
   Length of year:		3301.28	days
   Length of day:		13.52	hours


Planet 8	*gas giant*
   Distance from primary:	7.323	AU
   Mass:			1044.551	Earth masses
   Equatorial radius:		93103.2	km
   Density:			1.847	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		94.59	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4805.51	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.504
   Length of year:		6879.17	days
   Length of day:		5.90	hours


Planet 9	*gas giant*
   Distance from primary:	16.391	AU
   Mass:			85.679	Earth masses
   Equatorial radius:		48012.8	km
   Density:			1.105	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		37.73	km/sec
   Molecular weight retained:	0.56 and above
   Surface acceleration:	1482.17	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.465
   Length of year:		23065.10	days
   Length of day:		10.62	hours


Planet 10	*gas giant*
   Distance from primary:	27.740	AU
   Mass:			28.878	Earth masses
   Equatorial radius:		36529.3	km
   Density:			0.845	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		25.11	km/sec
   Molecular weight retained:	1.26 and above
   Surface acceleration:	863.01	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.502
   Length of year:		50785.97	days
   Length of day:		13.91	hours


Planet 11	
   Distance from primary:	40.419	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		5354.8	km
   Density:			2.230	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.35	degrees Celcius
   Normal daytime temperature:	-219.83	degrees Celcius
   Normal night temperature:	-230.79	degrees Celcius
   Maximum temperature:   	-204.91	degrees Celcius
   Minimum temperature:   	-246.23	degrees Celcius
   Escape Velocity:		5.98	km/sec
   Molecular weight retained:	22.21 and above
   Surface acceleration:	333.80	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.160
   Length of year:		89325.13	days
   Length of day:		26.23	hours
   Boiling point of water:	-48.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	
   Distance from primary:	48.740	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		2456.7	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.91	degrees Celcius
   Normal daytime temperature:	-222.88	degrees Celcius
   Normal night temperature:	-236.81	degrees Celcius
   Maximum temperature:   	-212.68	degrees Celcius
   Minimum temperature:   	-247.29	degrees Celcius
   Escape Velocity:		2.72	km/sec
   Molecular weight retained:	107.20 and above
   Surface acceleration:	150.71	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.161
   Length of year:		118283.21	days
   Length of day:		39.04	hours
   Boiling point of water:	-88.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


