                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486a1
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6120 K
Stellar class: F9
Age: 2.300 billion years  (4.537 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.424 AU	no atmosphere
2	  0.747 AU	greenhouse
3	  1.047 AU	greenhouse
4	  1.761 AU	no atmosphere
5	  2.262 AU	gas giant
6	  3.464 AU	gas giant
7	  6.188 AU	gas giant
8	 11.121 AU	gas giant
9	 18.228 AU	gas giant
10	 26.291 AU	gas giant
11	 42.477 AU	gas giant
12	 50.361 AU	no atmosphere



Planet 1	
   Distance from primary:	0.424	AU
   Mass:			0.161	Earth masses
   Equatorial radius:		3509.0	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.100
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.43	degrees Celcius
   Maximum temperature:   	411.51	degrees Celcius
   Minimum temperature:   	-205.63	degrees Celcius
   Escape Velocity:		6.04	km/sec
   Molecular weight retained:	21.76 and above
   Surface acceleration:	519.83	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.067
   Length of year:		95.95	days
   Length of day:		2302.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.747	AU
   Mass:			0.386	Earth masses
   Equatorial radius:		4689.5	km
   Density:			5.345	grams/cc
   Eccentricity of orbit:	0.200
   Surface gravity:		0.71	Earth gees
   Surface pressure:		15.831	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		157.58	degrees Celcius
   Maximum temperature:   	168.68	degrees Celcius
   Minimum temperature:   	145.54	degrees Celcius
   Escape Velocity:		8.11	km/sec
   Molecular weight retained:	12.08 and above
   Surface acceleration:	700.47	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.476
   Length of year:		224.56	days
   Length of day:		30.22	hours
   Boiling point of water:	195.6	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 518
				Francium     melts at 27    boils at 920
				Cesium       melts at 28    boils at 955
				Gallium      melts at 30    boils at 3089
				Rubidium     melts at 39    boils at 934
				Phosphorus   melts at 44    boils at 422
				Potassium    melts at 63    boils at 1032
				Sodium       melts at 98    boils at 1177
				Sulfur       melts at 113   boils at 629
				Iodine       melts at 114   boils at 303
				Indium       melts at 157   boils at 2683
   gasses in atmosphere:
				Nitrogen         99.1%  PP 15693.6 mb
				Water             0.1%  PP   12.7 mb
				CarbonDioxide     0.2%  PP   33.3 mb
				Methane           0.1%  PP    9.2 mb
				Ammonia           0.1%  PP   10.8 mb
				Ozone             0.2%  PP   34.2 mb
				Ethanol           0.2%  PP   34.1 mb


Planet 3	
   Distance from primary:	1.047	AU
   Mass:			2.477	Earth masses
   Equatorial radius:		8581.9	km
   Density:			5.592	grams/cc
   Eccentricity of orbit:	0.108
   Surface gravity:		1.37	Earth gees
   Surface pressure:		525.462	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		566.08	degrees Celcius
   Maximum temperature:   	567.59	degrees Celcius
   Minimum temperature:   	561.50	degrees Celcius
   Escape Velocity:		15.17	km/sec
   Molecular weight retained:	3.45 and above
   Surface acceleration:	1341.18	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.519
   Length of year:		372.58	days
   Length of day:		13.24	hours
   Boiling point of water:	421.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1495
				Cesium       melts at 28    boils at 1547
				Gallium      melts at 30    boils at 4707
				Rubidium     melts at 39    boils at 1515
				Potassium    melts at 63    boils at 1660
				Sodium       melts at 98    boils at 1876
				Indium       melts at 157   boils at 4106
				Lithium      melts at 181   boils at 2742
				Selenium     melts at 217   boils at 1510
				Tin          melts at 232   boils at 5116
				Polonium     melts at 254   boils at 2025
				Bismuth      melts at 271   boils at 3145
				Thallium     melts at 304   boils at 2946
				Cadmium      melts at 321   boils at 1659
				Lead         melts at 328   boils at 3493
				Zinc         melts at 420   boils at 1923
				Tellurium    melts at 450   boils at 2077
   gasses in atmosphere:
				Sulfur            0.2%  PP  825.3 mb
				Nitrogen          0.7%  PP 3927.3 mb
				Helium           99.1%  PP 520684.9 mb


Planet 4	
   Distance from primary:	1.761	AU
   Mass:			0.208	Earth masses
   Equatorial radius:		3820.9	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.038	Earth atmospheres
   Surface temperature:		-53.99	degrees Celcius
   Normal daytime temperature:	-39.01	degrees Celcius
   Normal night temperature:	-69.33	degrees Celcius
   Maximum temperature:   	-14.70	degrees Celcius
   Minimum temperature:   	-94.63	degrees Celcius
   Escape Velocity:		6.58	km/sec
   Molecular weight retained:	18.32 and above
   Surface acceleration:	567.15	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.409
   Length of year:		812.22	days
   Length of day:		20.20	hours
   Boiling point of water:	27.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	54.10
   liquids at surface:
				Ethanol      melts at -114  boils at 10
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP   17.6 mb
				Ozone            49.7%  PP   18.8 mb
				Fluorine          0.1%  PP    0.0 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.2%  PP    0.1 mb
				Krypton           2.9%  PP    1.1 mb
				Xenon             0.3%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	2.262	AU
   Mass:			59.991	Earth masses
   Equatorial radius:		36690.7	km
   Density:			1.733	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		36.11	km/sec
   Molecular weight retained:	0.61 and above
   Surface acceleration:	1777.09	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.511
   Length of year:		1182.91	days
   Length of day:		9.70	hours


Planet 6	*gas giant*
   Distance from primary:	3.464	AU
   Mass:			19.371	Earth masses
   Equatorial radius:		27339.4	km
   Density:			1.353	grams/cc
   Eccentricity of orbit:	0.223
   Escape Velocity:		23.77	km/sec
   Molecular weight retained:	1.40 and above
   Surface acceleration:	1033.53	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.483
   Length of year:		2241.36	days
   Length of day:		12.71	hours


Planet 7	*gas giant*
   Distance from primary:	6.188	AU
   Mass:			11.233	Earth masses
   Equatorial radius:		24476.8	km
   Density:			1.093	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		19.13	km/sec
   Molecular weight retained:	2.17 and above
   Surface acceleration:	747.67	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.480
   Length of year:		5351.53	days
   Length of day:		14.95	hours


Planet 8	*gas giant*
   Distance from primary:	11.121	AU
   Mass:			277.730	Earth masses
   Equatorial radius:		65509.2	km
   Density:			1.410	grams/cc
   Eccentricity of orbit:	0.211
   Escape Velocity:		58.15	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2580.81	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.515
   Length of year:		12887.67	days
   Length of day:		8.05	hours


Planet 9	*gas giant*
   Distance from primary:	18.228	AU
   Mass:			8.805	Earth masses
   Equatorial radius:		24946.3	km
   Density:			0.809	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		16.78	km/sec
   Molecular weight retained:	2.82 and above
   Surface acceleration:	564.22	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.531
   Length of year:		27053.93	days
   Length of day:		17.21	hours


Planet 10	*gas giant*
   Distance from primary:	26.291	AU
   Mass:			5.572	Earth masses
   Equatorial radius:		22506.6	km
   Density:			0.697	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		14.05	km/sec
   Molecular weight retained:	4.02 and above
   Surface acceleration:	438.68	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.513
   Length of year:		46865.35	days
   Length of day:		19.51	hours


Planet 11	*gas giant*
   Distance from primary:	42.477	AU
   Mass:			1.992	Earth masses
   Equatorial radius:		17354.2	km
   Density:			0.544	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		9.57	km/sec
   Molecular weight retained:	8.67 and above
   Surface acceleration:	263.83	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.488
   Length of year:		96243.20	days
   Length of day:		25.16	hours


Planet 12	
   Distance from primary:	50.361	AU
   Mass:			1/114.3	Earth masses
   Equatorial radius:		1786.0	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.48	degrees Celcius
   Normal daytime temperature:	-222.56	degrees Celcius
   Normal night temperature:	-238.23	degrees Celcius
   Maximum temperature:   	-206.13	degrees Celcius
   Minimum temperature:   	-253.74	degrees Celcius
   Escape Velocity:		1.98	km/sec
   Molecular weight retained:	203.23 and above
   Surface acceleration:	109.35	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.150
   Length of year:		124245.91	days
   Length of day:		45.83	hours
   Boiling point of water:	-100.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.02


