                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504808c
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6319 K
Stellar class: F7
Age: 5.477 billion years  (1.564 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.550 AU	no atmosphere
3	  0.756 AU	greenhouse
4	  1.425 AU	
5	  1.914 AU	gas giant
6	  2.783 AU	cold
7	  3.435 AU	gas giant
8	  5.451 AU	gas giant
9	  7.631 AU	gas giant
10	 17.864 AU	gas giant
11	 28.121 AU	no atmosphere
12	 50.885 AU	no atmosphere



Planet 1	
   Distance from primary:	0.370	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2071.5	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		228.64	degrees Celcius
   Maximum temperature:   	444.30	degrees Celcius
   Minimum temperature:   	-197.07	degrees Celcius
   Escape Velocity:		3.55	km/sec
   Molecular weight retained:	62.86 and above
   Surface acceleration:	304.80	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.080
   Length of year:		78.40	days
   Length of day:		1881.49	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.550	AU
   Mass:			0.221	Earth masses
   Equatorial radius:		3898.1	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		139.00	degrees Celcius
   Maximum temperature:   	334.68	degrees Celcius
   Minimum temperature:   	-218.85	degrees Celcius
   Escape Velocity:		6.72	km/sec
   Molecular weight retained:	17.59 and above
   Surface acceleration:	578.90	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.072
   Length of year:		142.43	days
   Length of day:		3418.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.756	AU
   Mass:			0.930	Earth masses
   Equatorial radius:		6254.6	km
   Density:			5.424	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.97	Earth gees
   Surface pressure:		70.872	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		421.14	degrees Celcius
   Maximum temperature:   	426.67	degrees Celcius
   Minimum temperature:   	413.43	degrees Celcius
   Escape Velocity:		10.89	km/sec
   Molecular weight retained:	6.69 and above
   Surface acceleration:	948.15	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.561
   Length of year:		229.52	days
   Length of day:		26.96	hours
   Boiling point of water:	271.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1113
				Cesium       melts at 28    boils at 1154
				Gallium      melts at 30    boils at 3632
				Rubidium     melts at 39    boils at 1129
				Potassium    melts at 63    boils at 1243
				Sodium       melts at 98    boils at 1412
				Sulfur       melts at 113   boils at 774
				Indium       melts at 157   boils at 3160
				Lithium      melts at 181   boils at 2091
				Selenium     melts at 217   boils at 1125
				Tin          melts at 232   boils at 3953
				Polonium     melts at 254   boils at 1529
				Bismuth      melts at 271   boils at 2407
				Thallium     melts at 304   boils at 2251
				Cadmium      melts at 321   boils at 1241
				Lead         melts at 328   boils at 2680
				Zinc         melts at 420   boils at 1449
   gasses in atmosphere:
				Nitrogen         99.0%  PP 70149.8 mb
				Phosphorus        0.7%  PP  478.0 mb
				CarbonDioxide     0.1%  PP   55.4 mb
				Ozone             0.1%  PP   47.3 mb
				Ethanol           0.1%  PP   56.5 mb


Planet 4	
   Distance from primary:	1.425	AU
   Mass:			1.027	Earth masses
   Equatorial radius:		6459.8	km
   Density:			5.436	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		1.00	Earth gees
   Surface pressure:		1.150	Earth atmospheres
   Surface temperature:		8.77	degrees Celcius
   Normal daytime temperature:	12.77	degrees Celcius
   Normal night temperature:	4.53	degrees Celcius
   Maximum temperature:   	33.90	degrees Celcius
   Minimum temperature:   	-17.82	degrees Celcius
   Escape Velocity:		11.26	km/sec
   Molecular weight retained:	6.26 and above
   Surface acceleration:	981.48	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.228
   Length of year:		593.96	days
   Length of day:		15.43	hours
   Boiling point of water:	103.9	degrees Celcius
   Hydrosphere percentage:	77.59
   Cloud cover percentage:	36.57
   Ice cover percentage:	3.40
   liquids at surface:
				Ethanol      melts at -114  boils at 82
				Mercury      melts at -39   boils at 363
				Bromine      melts at -7    boils at 63
				Water        melts at 0     boils at 104
   gasses in atmosphere:
				Oxygen           14.5%  PP  166.3 mb
				Nitrogen         85.4%  PP  982.1 mb
				CarbonDioxide     0.1%  PP    0.6 mb
				Ozone             0.1%  PP    0.6 mb


Planet 5	*gas giant*
   Distance from primary:	1.914	AU
   Mass:			2.176	Earth masses
   Equatorial radius:		13773.6	km
   Density:			1.188	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		11.22	km/sec
   Molecular weight retained:	6.30 and above
   Surface acceleration:	457.38	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.526
   Length of year:		924.18	days
   Length of day:		19.12	hours


Planet 6	
   Distance from primary:	2.783	AU
   Mass:			0.843	Earth masses
   Equatorial radius:		6056.4	km
   Density:			5.413	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.530	Earth atmospheres
   Surface temperature:		-97.41	degrees Celcius
   Normal daytime temperature:	-93.72	degrees Celcius
   Normal night temperature:	-101.30	degrees Celcius
   Maximum temperature:   	-75.32	degrees Celcius
   Minimum temperature:   	-121.15	degrees Celcius
   Escape Velocity:		10.53	km/sec
   Molecular weight retained:	7.15 and above
   Surface acceleration:	916.17	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.512
   Length of year:		1620.21	days
   Length of day:		15.84	hours
   Boiling point of water:	83.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	74.27
   liquids at surface:
				Ethanol      melts at -114  boils at 63
				Chlorine     melts at -101  boils at -45
   gasses in atmosphere:
				Oxygen            0.3%  PP    1.4 mb
				Nitrogen         99.6%  PP  527.5 mb
				Ozone             0.1%  PP    0.3 mb


Planet 7	*gas giant*
   Distance from primary:	3.435	AU
   Mass:			11.032	Earth masses
   Equatorial radius:		23218.8	km
   Density:			1.258	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		19.47	km/sec
   Molecular weight retained:	2.09 and above
   Surface acceleration:	816.03	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.455
   Length of year:		2221.82	days
   Length of day:		14.31	hours


Planet 8	*gas giant*
   Distance from primary:	5.451	AU
   Mass:			778.729	Earth masses
   Equatorial radius:		83516.1	km
   Density:			1.908	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		86.24	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4452.31	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.541
   Length of year:		4437.06	days
   Length of day:		6.13	hours


Planet 9	*gas giant*
   Distance from primary:	7.631	AU
   Mass:			5.386	Earth masses
   Equatorial radius:		20133.4	km
   Density:			0.942	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		14.61	km/sec
   Molecular weight retained:	3.72 and above
   Surface acceleration:	529.91	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.458
   Length of year:		7356.56	days
   Length of day:		17.75	hours


Planet 10	*gas giant*
   Distance from primary:	17.864	AU
   Mass:			548.781	Earth masses
   Equatorial radius:		83252.7	km
   Density:			1.357	grams/cc
   Eccentricity of orbit:	0.191
   Escape Velocity:		72.51	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3157.49	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.545
   Length of year:		26331.37	days
   Length of day:		7.27	hours


Planet 11	
   Distance from primary:	28.121	AU
   Mass:			0.320	Earth masses
   Equatorial radius:		5883.7	km
   Density:			2.240	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-215.83	degrees Celcius
   Normal daytime temperature:	-209.50	degrees Celcius
   Normal night temperature:	-222.11	degrees Celcius
   Maximum temperature:   	-193.99	degrees Celcius
   Minimum temperature:   	-238.49	degrees Celcius
   Escape Velocity:		6.58	km/sec
   Molecular weight retained:	18.31 and above
   Surface acceleration:	368.33	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.155
   Length of year:		52043.58	days
   Length of day:		24.97	hours
   Boiling point of water:	-41.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   liquids at surface:
				Oxygen       melts at -218  boils at -213
   gasses in atmosphere:
				Neon             100.0%  PP    0.3 mb


Planet 12	
   Distance from primary:	50.885	AU
   Mass:			0.180	Earth masses
   Equatorial radius:		4875.2	km
   Density:			2.223	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.71	degrees Celcius
   Normal daytime temperature:	-225.59	degrees Celcius
   Normal night temperature:	-235.72	degrees Celcius
   Maximum temperature:   	-209.86	degrees Celcius
   Minimum temperature:   	-251.46	degrees Celcius
   Escape Velocity:		5.43	km/sec
   Molecular weight retained:	26.88 and above
   Surface acceleration:	302.85	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.138
   Length of year:		126678.01	days
   Length of day:		27.54	hours
   Boiling point of water:	-55.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


