                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047dd8
Stellar mass: 1.09 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6302 K
Stellar class: F7
Age: 4.583 billion years  (2.551 billion left on main sequence)
Habitable ecosphere radius: 1.237 AU

Planets present at:
1	  0.322 AU	no atmosphere
2	  0.511 AU	no atmosphere
3	  1.134 AU	greenhouse
4	  2.141 AU	high pressure
5	  3.146 AU	gas giant
6	  4.882 AU	gas giant
7	 12.038 AU	gas giant
8	 16.319 AU	gas giant
9	 24.174 AU	gas giant
10	 48.404 AU	no atmosphere



Planet 1	
   Distance from primary:	0.322	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		2694.7	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		265.12	degrees Celcius
   Normal daytime temperature:	485.19	degrees Celcius
   Normal night temperature:	-175.43	degrees Celcius
   Maximum temperature:   	488.41	degrees Celcius
   Minimum temperature:   	-186.87	degrees Celcius
   Escape Velocity:		4.63	km/sec
   Molecular weight retained:	37.06 and above
   Surface acceleration:	397.50	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.057
   Length of year:		64.00	days
   Length of day:		1535.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.511	AU
   Mass:			0.521	Earth masses
   Equatorial radius:		5173.9	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		152.44	degrees Celcius
   Maximum temperature:   	351.31	degrees Celcius
   Minimum temperature:   	-216.04	degrees Celcius
   Escape Velocity:		8.96	km/sec
   Molecular weight retained:	9.89 and above
   Surface acceleration:	776.01	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.075
   Length of year:		127.59	days
   Length of day:		3062.17	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.134	AU
   Mass:			2.975	Earth masses
   Equatorial radius:		9097.4	km
   Density:			5.638	grams/cc
   Eccentricity of orbit:	0.240
   Surface gravity:		1.46	Earth gees
   Surface pressure:		926.993	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		589.02	degrees Celcius
   Maximum temperature:   	590.04	degrees Celcius
   Minimum temperature:   	584.68	degrees Celcius
   Escape Velocity:		16.15	km/sec
   Molecular weight retained:	3.04 and above
   Surface acceleration:	1433.42	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.557
   Length of year:		422.23	days
   Length of day:		12.81	hours
   Boiling point of water:	479.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1644
				Cesium       melts at 28    boils at 1701
				Gallium      melts at 30    boils at 5128
				Rubidium     melts at 39    boils at 1667
				Potassium    melts at 63    boils at 1823
				Sodium       melts at 98    boils at 2057
				Indium       melts at 157   boils at 4476
				Lithium      melts at 181   boils at 2997
				Selenium     melts at 217   boils at 1661
				Tin          melts at 232   boils at 5572
				Polonium     melts at 254   boils at 2220
				Bismuth      melts at 271   boils at 3435
				Thallium     melts at 304   boils at 3219
				Cadmium      melts at 321   boils at 1822
				Lead         melts at 328   boils at 3812
				Zinc         melts at 420   boils at 2109
				Tellurium    melts at 450   boils at 2276
   gasses in atmosphere:
				Sulfur            0.1%  PP 1037.7 mb
				Nitrogen          0.5%  PP 4782.1 mb
				Helium           99.4%  PP 921144.4 mb


Planet 4	
   Distance from primary:	2.141	AU
   Mass:			1.620	Earth masses
   Equatorial radius:		7487.9	km
   Density:			5.505	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		1.17	Earth gees
   Surface pressure:		2.641	Earth atmospheres
   Surface temperature:		-84.62	degrees Celcius
   Normal daytime temperature:	-82.97	degrees Celcius
   Normal night temperature:	-86.37	degrees Celcius
   Maximum temperature:   	-70.32	degrees Celcius
   Minimum temperature:   	-99.91	degrees Celcius
   Escape Velocity:		13.14	km/sec
   Molecular weight retained:	4.60 and above
   Surface acceleration:	1152.06	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.686
   Length of year:		1095.01	days
   Length of day:		14.13	hours
   Boiling point of water:	128.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 106
				Chlorine     melts at -101  boils at -15
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2639.0 mb


Planet 5	*gas giant*
   Distance from primary:	3.146	AU
   Mass:			215.745	Earth masses
   Equatorial radius:		54902.7	km
   Density:			1.860	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		55.98	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2854.25	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.483
   Length of year:		1950.62	days
   Length of day:		7.65	hours


Planet 6	*gas giant*
   Distance from primary:	4.882	AU
   Mass:			160.517	Earth masses
   Equatorial radius:		52243.9	km
   Density:			1.606	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		49.50	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2345.26	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.502
   Length of year:		3770.09	days
   Length of day:		8.44	hours


Planet 7	*gas giant*
   Distance from primary:	12.038	AU
   Mass:			1.130	Earth masses
   Equatorial radius:		13271.3	km
   Density:			0.690	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		8.24	km/sec
   Molecular weight retained:	11.69 and above
   Surface acceleration:	255.87	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.505
   Length of year:		14601.18	days
   Length of day:		25.55	hours


Planet 8	*gas giant*
   Distance from primary:	16.319	AU
   Mass:			17.437	Earth masses
   Equatorial radius:		30236.5	km
   Density:			0.900	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		21.45	km/sec
   Molecular weight retained:	1.73 and above
   Surface acceleration:	760.59	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.474
   Length of year:		23046.76	days
   Length of day:		14.82	hours


Planet 9	*gas giant*
   Distance from primary:	24.174	AU
   Mass:			61.631	Earth masses
   Equatorial radius:		45152.3	km
   Density:			0.955	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		32.99	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1205.54	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.499
   Length of year:		41547.78	days
   Length of day:		11.77	hours


Planet 10	
   Distance from primary:	48.404	AU
   Mass:			0.242	Earth masses
   Equatorial radius:		5369.7	km
   Density:			2.231	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.74	degrees Celcius
   Normal daytime temperature:	-224.74	degrees Celcius
   Normal night temperature:	-234.65	degrees Celcius
   Maximum temperature:   	-208.24	degrees Celcius
   Minimum temperature:   	-251.17	degrees Celcius
   Escape Velocity:		6.00	km/sec
   Molecular weight retained:	22.08 and above
   Surface acceleration:	334.77	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.136
   Length of year:		117734.17	days
   Length of day:		26.19	hours
   Boiling point of water:	-48.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


