                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a29
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6175 K
Stellar class: F8
Age: 4.960 billion years  (1.761 billion left on main sequence)
Habitable ecosphere radius: 1.284 AU

Planets present at:
1	  0.372 AU	no atmosphere
2	  0.448 AU	no atmosphere
3	  0.724 AU	no atmosphere
4	  1.000 AU	greenhouse
5	  1.483 AU	gas giant
6	  3.085 AU	gas giant
7	  4.044 AU	gas giant
8	  6.864 AU	gas giant
9	 15.461 AU	gas giant
10	 27.282 AU	gas giant
11	 46.726 AU	gas giant
12	 51.418 AU	no atmosphere



Planet 1	
   Distance from primary:	0.372	AU
   Mass:			0.036	Earth masses
   Equatorial radius:		2131.7	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		236.81	degrees Celcius
   Maximum temperature:   	454.22	degrees Celcius
   Minimum temperature:   	-195.68	degrees Celcius
   Escape Velocity:		3.66	km/sec
   Molecular weight retained:	59.35 and above
   Surface acceleration:	313.73	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.064
   Length of year:		78.59	days
   Length of day:		1886.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.448	AU
   Mass:			0.137	Earth masses
   Equatorial radius:		3333.5	km
   Density:			5.295	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		188.08	degrees Celcius
   Maximum temperature:   	394.99	degrees Celcius
   Minimum temperature:   	-208.02	degrees Celcius
   Escape Velocity:		5.74	km/sec
   Molecular weight retained:	24.13 and above
   Surface acceleration:	493.34	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.089
   Length of year:		104.05	days
   Length of day:		2497.17	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.724	AU
   Mass:			0.317	Earth masses
   Equatorial radius:		4395.6	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.139
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		91.52	degrees Celcius
   Maximum temperature:   	275.40	degrees Celcius
   Minimum temperature:   	-225.83	degrees Celcius
   Escape Velocity:		7.59	km/sec
   Molecular weight retained:	13.78 and above
   Surface acceleration:	655.08	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.071
   Length of year:		213.75	days
   Length of day:		3880.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.000	AU
   Mass:			2.144	Earth masses
   Equatorial radius:		8194.3	km
   Density:			5.559	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		1.30	Earth gees
   Surface pressure:		379.466	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		580.64	degrees Celcius
   Maximum temperature:   	582.37	degrees Celcius
   Minimum temperature:   	575.61	degrees Celcius
   Escape Velocity:		14.44	km/sec
   Molecular weight retained:	3.80 and above
   Surface acceleration:	1273.18	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.425
   Length of year:		346.88	days
   Length of day:		13.95	hours
   Boiling point of water:	391.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1419
				Cesium       melts at 28    boils at 1469
				Gallium      melts at 30    boils at 4494
				Rubidium     melts at 39    boils at 1439
				Potassium    melts at 63    boils at 1577
				Sodium       melts at 98    boils at 1784
				Indium       melts at 157   boils at 3918
				Lithium      melts at 181   boils at 2613
				Selenium     melts at 217   boils at 1433
				Tin          melts at 232   boils at 4885
				Polonium     melts at 254   boils at 1927
				Bismuth      melts at 271   boils at 2999
				Thallium     melts at 304   boils at 2808
				Cadmium      melts at 321   boils at 1576
				Lead         melts at 328   boils at 3332
				Zinc         melts at 420   boils at 1829
				Tellurium    melts at 450   boils at 1977
   gasses in atmosphere:
				Sulfur            0.6%  PP 2295.4 mb
				Nitrogen          2.5%  PP 9627.3 mb
				Helium           96.8%  PP 367477.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.483	AU
   Mass:			4.592	Earth masses
   Equatorial radius:		16724.1	km
   Density:			1.401	grams/cc
   Eccentricity of orbit:	0.206
   Escape Velocity:		14.80	km/sec
   Molecular weight retained:	3.63 and above
   Surface acceleration:	654.65	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.478
   Length of year:		626.38	days
   Length of day:		15.99	hours


Planet 6	*gas giant*
   Distance from primary:	3.085	AU
   Mass:			7.711	Earth masses
   Equatorial radius:		20679.3	km
   Density:			1.244	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		17.25	km/sec
   Molecular weight retained:	2.67 and above
   Surface acceleration:	719.11	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.486
   Length of year:		1879.94	days
   Length of day:		15.24	hours


Planet 7	*gas giant*
   Distance from primary:	4.044	AU
   Mass:			2.493	Earth masses
   Equatorial radius:		15216.5	km
   Density:			1.010	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		11.43	km/sec
   Molecular weight retained:	6.07 and above
   Surface acceleration:	429.43	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.538
   Length of year:		2821.35	days
   Length of day:		19.72	hours


Planet 8	*gas giant*
   Distance from primary:	6.864	AU
   Mass:			1456.714	Earth masses
   Equatorial radius:		101948.4	km
   Density:			1.962	grams/cc
   Eccentricity of orbit:	0.095
   Escape Velocity:		106.75	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5589.24	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.476
   Length of year:		6225.93	days
   Length of day:		5.47	hours


Planet 9	*gas giant*
   Distance from primary:	15.461	AU
   Mass:			800.020	Earth masses
   Equatorial radius:		91591.3	km
   Density:			1.486	grams/cc
   Eccentricity of orbit:	0.308
   Escape Velocity:		83.47	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	3803.05	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.503
   Length of year:		21064.52	days
   Length of day:		6.63	hours


Planet 10	*gas giant*
   Distance from primary:	27.282	AU
   Mass:			0.305	Earth masses
   Equatorial radius:		9666.2	km
   Density:			0.482	grams/cc
   Eccentricity of orbit:	0.090
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.54 and above
   Surface acceleration:	130.17	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.479
   Length of year:		49429.56	days
   Length of day:		35.82	hours


Planet 11	*gas giant*
   Distance from primary:	46.726	AU
   Mass:			0.320	Earth masses
   Equatorial radius:		10256.5	km
   Density:			0.424	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		4.99	km/sec
   Molecular weight retained:	31.85 and above
   Surface acceleration:	121.49	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.511
   Length of year:		110791.09	days
   Length of day:		37.08	hours


Planet 12	
   Distance from primary:	51.418	AU
   Mass:			1/119.9	Earth masses
   Equatorial radius:		1758.2	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.71	degrees Celcius
   Normal daytime temperature:	-222.77	degrees Celcius
   Normal night temperature:	-238.46	degrees Celcius
   Maximum temperature:   	-211.24	degrees Celcius
   Minimum temperature:   	-249.94	degrees Celcius
   Escape Velocity:		1.95	km/sec
   Molecular weight retained:	209.74 and above
   Surface acceleration:	107.64	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.151
   Length of year:		127889.54	days
   Length of day:		46.19	hours
   Boiling point of water:	-99.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


