                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047be5
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6172 K
Stellar class: F8
Age: 5.111 billion years  (2.092 billion left on main sequence)
Habitable ecosphere radius: 1.229 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.399 AU	no atmosphere
3	  0.671 AU	no atmosphere
4	  0.951 AU	greenhouse
5	  1.674 AU	cold
6	  2.500 AU	cold
7	  3.899 AU	gas giant
8	  7.107 AU	gas giant
9	  9.709 AU	cold
10	 12.765 AU	gas giant
11	 21.628 AU	gas giant
12	 36.487 AU	gas giant
13	 46.799 AU	no atmosphere



Planet 1	
   Distance from primary:	0.358	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		1841.6	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		233.25	degrees Celcius
   Normal daytime temperature:	446.83	degrees Celcius
   Normal night temperature:	-185.34	degrees Celcius
   Maximum temperature:   	449.99	degrees Celcius
   Minimum temperature:   	-195.96	degrees Celcius
   Escape Velocity:		3.16	km/sec
   Molecular weight retained:	79.60 and above
   Surface acceleration:	270.77	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.077
   Length of year:		75.06	days
   Length of day:		1801.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.399	AU
   Mass:			0.204	Earth masses
   Equatorial radius:		3797.5	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		208.65	degrees Celcius
   Maximum temperature:   	420.02	degrees Celcius
   Minimum temperature:   	-202.35	degrees Celcius
   Escape Velocity:		6.54	km/sec
   Molecular weight retained:	18.55 and above
   Surface acceleration:	563.58	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.061
   Length of year:		88.27	days
   Length of day:		2118.38	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.671	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		1967.7	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.137
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		96.75	degrees Celcius
   Maximum temperature:   	281.93	degrees Celcius
   Minimum temperature:   	-225.05	degrees Celcius
   Escape Velocity:		3.37	km/sec
   Molecular weight retained:	69.69 and above
   Surface acceleration:	289.43	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.078
   Length of year:		192.44	days
   Length of day:		3507.79	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.951	AU
   Mass:			1.983	Earth masses
   Equatorial radius:		7991.3	km
   Density:			5.543	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		1.26	Earth gees
   Surface pressure:		376.879	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		552.93	degrees Celcius
   Maximum temperature:   	554.78	degrees Celcius
   Minimum temperature:   	548.10	degrees Celcius
   Escape Velocity:		14.07	km/sec
   Molecular weight retained:	4.01 and above
   Surface acceleration:	1238.02	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.500
   Length of year:		324.81	days
   Length of day:		14.38	hours
   Boiling point of water:	390.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1418
				Cesium       melts at 28    boils at 1467
				Gallium      melts at 30    boils at 4489
				Rubidium     melts at 39    boils at 1437
				Potassium    melts at 63    boils at 1575
				Sodium       melts at 98    boils at 1782
				Indium       melts at 157   boils at 3914
				Lithium      melts at 181   boils at 2610
				Selenium     melts at 217   boils at 1432
				Tin          melts at 232   boils at 4881
				Polonium     melts at 254   boils at 1925
				Bismuth      melts at 271   boils at 2996
				Thallium     melts at 304   boils at 2806
				Cadmium      melts at 321   boils at 1574
				Lead         melts at 328   boils at 3329
				Zinc         melts at 420   boils at 1827
				Tellurium    melts at 450   boils at 1975
   gasses in atmosphere:
				Sulfur           19.6%  PP 73804.2 mb
				Nitrogen         79.9%  PP 300952.4 mb
				Phosphorus        0.4%  PP 1472.2 mb


Planet 5	
   Distance from primary:	1.674	AU
   Mass:			1.330	Earth masses
   Equatorial radius:		7025.0	km
   Density:			5.473	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		1.10	Earth gees
   Surface pressure:		1.712	Earth atmospheres
   Surface temperature:		-78.89	degrees Celcius
   Normal daytime temperature:	-76.71	degrees Celcius
   Normal night temperature:	-81.18	degrees Celcius
   Maximum temperature:   	-61.12	degrees Celcius
   Minimum temperature:   	-97.90	degrees Celcius
   Escape Velocity:		12.29	km/sec
   Molecular weight retained:	5.26 and above
   Surface acceleration:	1074.48	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.766
   Length of year:		757.89	days
   Length of day:		14.66	hours
   Boiling point of water:	115.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.08
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 93
				Chlorine     melts at -101  boils at -24
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1710.0 mb
				Ozone             0.1%  PP    0.9 mb


Planet 6	
   Distance from primary:	2.500	AU
   Mass:			1.361	Earth masses
   Equatorial radius:		7078.6	km
   Density:			5.476	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		1.10	Earth gees
   Surface pressure:		1.890	Earth atmospheres
   Surface temperature:		-107.90	degrees Celcius
   Normal daytime temperature:	-106.15	degrees Celcius
   Normal night temperature:	-109.75	degrees Celcius
   Maximum temperature:   	-91.56	degrees Celcius
   Minimum temperature:   	-125.51	degrees Celcius
   Escape Velocity:		12.38	km/sec
   Molecular weight retained:	5.18 and above
   Surface acceleration:	1083.41	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.731
   Length of year:		1383.60	days
   Length of day:		14.56	hours
   Boiling point of water:	118.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 96
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1888.0 mb
				Ozone             0.1%  PP    1.0 mb


Planet 7	*gas giant*
   Distance from primary:	3.899	AU
   Mass:			719.113	Earth masses
   Equatorial radius:		79446.9	km
   Density:			2.046	grams/cc
   Eccentricity of orbit:	0.083
   Escape Velocity:		84.97	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4543.42	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.534
   Length of year:		2692.68	days
   Length of day:		6.06	hours


Planet 8	*gas giant*
   Distance from primary:	7.107	AU
   Mass:			10.358	Earth masses
   Equatorial radius:		24248.7	km
   Density:			1.037	grams/cc
   Eccentricity of orbit:	0.019
   Escape Velocity:		18.46	km/sec
   Molecular weight retained:	2.33 and above
   Surface acceleration:	702.47	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.516
   Length of year:		6632.31	days
   Length of day:		15.42	hours


Planet 9	
   Distance from primary:	9.709	AU
   Mass:			0.589	Earth masses
   Equatorial radius:		7183.8	km
   Density:			2.268	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.242	Earth atmospheres
   Surface temperature:		-174.86	degrees Celcius
   Normal daytime temperature:	-170.88	degrees Celcius
   Normal night temperature:	-179.09	degrees Celcius
   Maximum temperature:   	-154.89	degrees Celcius
   Minimum temperature:   	-196.73	degrees Celcius
   Escape Velocity:		8.09	km/sec
   Molecular weight retained:	12.14 and above
   Surface acceleration:	455.26	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.314
   Length of year:		10589.55	days
   Length of day:		22.46	hours
   Boiling point of water:	64.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	34.48
   liquids at surface:
				Ozone        melts at -193  boils at -127
				Methane      melts at -183  boils at -174
   gasses in atmosphere:
				Oxygen            4.1%  PP   10.0 mb
				Nitrogen         95.9%  PP  231.8 mb


Planet 10	*gas giant*
   Distance from primary:	12.765	AU
   Mass:			149.087	Earth masses
   Equatorial radius:		55422.0	km
   Density:			1.250	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		46.32	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	1935.59	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.514
   Length of year:		15960.81	days
   Length of day:		9.29	hours


Planet 11	*gas giant*
   Distance from primary:	21.628	AU
   Mass:			89.737	Earth masses
   Equatorial radius:		49941.5	km
   Density:			1.028	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		37.86	km/sec
   Molecular weight retained:	0.55 and above
   Surface acceleration:	1434.78	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.459
   Length of year:		35203.32	days
   Length of day:		10.79	hours


Planet 12	*gas giant*
   Distance from primary:	36.487	AU
   Mass:			0.461	Earth masses
   Equatorial radius:		11213.0	km
   Density:			0.467	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		5.73	km/sec
   Molecular weight retained:	24.20 and above
   Surface acceleration:	146.26	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.485
   Length of year:		77146.86	days
   Length of day:		33.80	hours


Planet 13	
   Distance from primary:	46.799	AU
   Mass:			0.143	Earth masses
   Equatorial radius:		4514.1	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.53	degrees Celcius
   Normal daytime temperature:	-224.09	degrees Celcius
   Normal night temperature:	-234.88	degrees Celcius
   Maximum temperature:   	-208.58	degrees Celcius
   Minimum temperature:   	-250.48	degrees Celcius
   Escape Velocity:		5.03	km/sec
   Molecular weight retained:	31.43 and above
   Surface acceleration:	279.74	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.147
   Length of year:		112067.13	days
   Length of day:		28.65	hours
   Boiling point of water:	-59.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


