                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e45
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6198 K
Stellar class: F8
Age: 4.055 billion years  (3.065 billion left on main sequence)
Habitable ecosphere radius: 1.239 AU

Planets present at:
1	  0.339 AU	no atmosphere
2	  0.527 AU	no atmosphere
3	  0.979 AU	greenhouse
4	  1.652 AU	high pressure
5	  2.871 AU	gas giant
6	  7.251 AU	gas giant
7	 11.755 AU	gas giant
8	 19.959 AU	gas giant
9	 42.343 AU	gas giant



Planet 1	
   Distance from primary:	0.339	AU
   Mass:			0.089	Earth masses
   Equatorial radius:		2884.2	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		249.34	degrees Celcius
   Normal daytime temperature:	466.23	degrees Celcius
   Normal night temperature:	-180.42	degrees Celcius
   Maximum temperature:   	469.19	degrees Celcius
   Minimum temperature:   	-190.59	degrees Celcius
   Escape Velocity:		4.96	km/sec
   Molecular weight retained:	32.32 and above
   Surface acceleration:	425.83	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.075
   Length of year:		69.08	days
   Length of day:		1657.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.527	AU
   Mass:			0.303	Earth masses
   Equatorial radius:		4329.6	km
   Density:			5.330	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		145.59	degrees Celcius
   Maximum temperature:   	342.81	degrees Celcius
   Minimum temperature:   	-217.33	degrees Celcius
   Escape Velocity:		7.47	km/sec
   Molecular weight retained:	14.21 and above
   Surface acceleration:	644.93	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.081
   Length of year:		133.58	days
   Length of day:		3205.96	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.979	AU
   Mass:			1.586	Earth masses
   Equatorial radius:		7436.9	km
   Density:			5.501	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		1.17	Earth gees
   Surface pressure:		192.202	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		416.23	degrees Celcius
   Maximum temperature:   	419.37	degrees Celcius
   Minimum temperature:   	411.45	degrees Celcius
   Escape Velocity:		13.04	km/sec
   Molecular weight retained:	4.67 and above
   Surface acceleration:	1143.45	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.606
   Length of year:		338.66	days
   Length of day:		14.80	hours
   Boiling point of water:	336.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1280
				Cesium       melts at 28    boils at 1326
				Gallium      melts at 30    boils at 4102
				Rubidium     melts at 39    boils at 1298
				Potassium    melts at 63    boils at 1425
				Sodium       melts at 98    boils at 1615
				Sulfur       melts at 113   boils at 901
				Indium       melts at 157   boils at 3574
				Lithium      melts at 181   boils at 2375
				Selenium     melts at 217   boils at 1293
				Tin          melts at 232   boils at 4462
				Polonium     melts at 254   boils at 1746
				Bismuth      melts at 271   boils at 2730
				Thallium     melts at 304   boils at 2555
				Cadmium      melts at 321   boils at 1424
				Lead         melts at 328   boils at 3036
   gasses in atmosphere:
				Nitrogen         99.3%  PP 190791.8 mb
				Phosphorus        0.5%  PP  943.7 mb
				CarbonDioxide     0.1%  PP  100.7 mb
				Ethanol           0.1%  PP  101.9 mb


Planet 4	
   Distance from primary:	1.652	AU
   Mass:			1.658	Earth masses
   Equatorial radius:		7544.8	km
   Density:			5.509	grams/cc
   Eccentricity of orbit:	0.171
   Surface gravity:		1.18	Earth gees
   Surface pressure:		2.433	Earth atmospheres
   Surface temperature:		-8.46	degrees Celcius
   Normal daytime temperature:	-6.07	degrees Celcius
   Normal night temperature:	-11.01	degrees Celcius
   Maximum temperature:   	11.11	degrees Celcius
   Minimum temperature:   	-29.17	degrees Celcius
   Escape Velocity:		13.24	km/sec
   Molecular weight retained:	4.53 and above
   Surface acceleration:	1161.69	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.266
   Length of year:		742.24	days
   Length of day:		14.09	hours
   Boiling point of water:	126.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	10.20
   Ice cover percentage:	17.44
   liquids at surface:
				Ethanol      melts at -114  boils at 103
				Mercury      melts at -39   boils at 401
   gasses in atmosphere:
				Nitrogen         99.8%  PP 2428.9 mb


Planet 5	*gas giant*
   Distance from primary:	2.871	AU
   Mass:			260.777	Earth masses
   Equatorial radius:		57576.9	km
   Density:			1.949	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		60.10	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	3136.98	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.509
   Length of year:		1699.97	days
   Length of day:		7.30	hours


Planet 6	*gas giant*
   Distance from primary:	7.251	AU
   Mass:			31.838	Earth masses
   Equatorial radius:		33681.2	km
   Density:			1.189	grams/cc
   Eccentricity of orbit:	0.126
   Escape Velocity:		27.46	km/sec
   Molecular weight retained:	1.05 and above
   Surface acceleration:	1119.20	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.466
   Length of year:		6824.15	days
   Length of day:		12.22	hours


Planet 7	*gas giant*
   Distance from primary:	11.755	AU
   Mass:			150.117	Earth masses
   Equatorial radius:		55119.5	km
   Density:			1.279	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		46.61	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	1970.42	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.492
   Length of year:		14082.78	days
   Length of day:		9.21	hours


Planet 8	*gas giant*
   Distance from primary:	19.959	AU
   Mass:			136.150	Earth masses
   Equatorial radius:		55988.1	km
   Density:			1.107	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		44.04	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1732.07	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.497
   Length of year:		31159.89	days
   Length of day:		9.82	hours


Planet 9	*gas giant*
   Distance from primary:	42.343	AU
   Mass:			0.792	Earth masses
   Equatorial radius:		13283.8	km
   Density:			0.482	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		6.89	km/sec
   Molecular weight retained:	16.70 and above
   Surface acceleration:	178.94	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.546
   Length of year:		96300.62	days
   Length of day:		30.55	hours


