                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504825d
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6280 K
Stellar class: F8
Age: 4.401 billion years  (2.578 billion left on main sequence)
Habitable ecosphere radius: 1.254 AU

Planets present at:
1	  0.312 AU	no atmosphere
2	  0.385 AU	no atmosphere
3	  0.509 AU	no atmosphere
4	  0.616 AU	no atmosphere
5	  0.690 AU	no atmosphere
6	  0.942 AU	no atmosphere
7	  1.367 AU	
8	  1.943 AU	cold
9	  3.142 AU	gas giant
10	  6.640 AU	gas giant
11	 13.200 AU	gas giant
12	 16.831 AU	gas giant
13	 21.787 AU	gas giant
14	 36.225 AU	gas giant
15	 50.442 AU	no atmosphere



Planet 1	
   Distance from primary:	0.312	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2038.6	km
   Density:			5.264	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		278.24	degrees Celcius
   Normal daytime temperature:	500.94	degrees Celcius
   Normal night temperature:	-171.36	degrees Celcius
   Maximum temperature:   	504.00	degrees Celcius
   Minimum temperature:   	-182.42	degrees Celcius
   Escape Velocity:		3.50	km/sec
   Molecular weight retained:	64.91 and above
   Surface acceleration:	299.93	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.057
   Length of year:		60.63	days
   Length of day:		1455.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.385	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2235.6	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		218.63	degrees Celcius
   Maximum temperature:   	432.06	degrees Celcius
   Minimum temperature:   	-199.43	degrees Celcius
   Escape Velocity:		3.84	km/sec
   Molecular weight retained:	53.94 and above
   Surface acceleration:	329.15	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.087
   Length of year:		83.37	days
   Length of day:		2000.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.509	AU
   Mass:			0.088	Earth masses
   Equatorial radius:		2878.2	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		155.65	degrees Celcius
   Maximum temperature:   	355.34	degrees Celcius
   Minimum temperature:   	-215.69	degrees Celcius
   Escape Velocity:		4.95	km/sec
   Molecular weight retained:	32.45 and above
   Surface acceleration:	424.93	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.081
   Length of year:		126.45	days
   Length of day:		3034.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.616	AU
   Mass:			0.620	Earth masses
   Equatorial radius:		5476.9	km
   Density:			5.382	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		116.31	degrees Celcius
   Maximum temperature:   	306.42	degrees Celcius
   Minimum temperature:   	-223.11	degrees Celcius
   Escape Velocity:		9.50	km/sec
   Molecular weight retained:	8.80 and above
   Surface acceleration:	823.72	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.082
   Length of year:		168.68	days
   Length of day:		4048.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	0.690	AU
   Mass:			0.085	Earth masses
   Equatorial radius:		2843.1	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		96.56	degrees Celcius
   Maximum temperature:   	281.70	degrees Celcius
   Minimum temperature:   	-225.59	degrees Celcius
   Escape Velocity:		4.89	km/sec
   Molecular weight retained:	33.26 and above
   Surface acceleration:	419.68	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.066
   Length of year:		199.78	days
   Length of day:		4794.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 6	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.942	AU
   Mass:			1/705.5	Earth masses
   Equatorial radius:		727.7	km
   Density:			5.248	grams/cc
   Eccentricity of orbit:	0.123
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		43.72	degrees Celcius
   Maximum temperature:   	214.84	degrees Celcius
   Minimum temperature:   	-231.57	degrees Celcius
   Escape Velocity:		1.25	km/sec
   Molecular weight retained:	510.99 and above
   Surface acceleration:	106.74	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.061
   Length of year:		318.47	days
   Length of day:		5974.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363


Planet 7	
   Distance from primary:	1.367	AU
   Mass:			1.241	Earth masses
   Equatorial radius:		6869.2	km
   Density:			5.462	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		1.07	Earth gees
   Surface pressure:		1.562	Earth atmospheres
   Surface temperature:		14.21	degrees Celcius
   Normal daytime temperature:	17.61	degrees Celcius
   Normal night temperature:	10.59	degrees Celcius
   Maximum temperature:   	35.71	degrees Celcius
   Minimum temperature:   	-8.53	degrees Celcius
   Escape Velocity:		12.00	km/sec
   Molecular weight retained:	5.51 and above
   Surface acceleration:	1048.66	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.273
   Length of year:		557.01	days
   Length of day:		14.91	hours
   Boiling point of water:	112.7	degrees Celcius
   Hydrosphere percentage:	77.09
   Cloud cover percentage:	50.24
   Ice cover percentage:	1.99
   liquids at surface:
				Ethanol      melts at -114  boils at 90
				Mercury      melts at -39   boils at 378
				Bromine      melts at -7    boils at 71
				Water        melts at 0     boils at 113
   gasses in atmosphere:
				Oxygen           10.0%  PP  156.6 mb
				Nitrogen         89.8%  PP 1402.4 mb
				Ozone             0.1%  PP    0.8 mb


Planet 8	
   Distance from primary:	1.943	AU
   Mass:			1.214	Earth masses
   Equatorial radius:		6820.5	km
   Density:			5.459	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		1.06	Earth gees
   Surface pressure:		1.591	Earth atmospheres
   Surface temperature:		-72.79	degrees Celcius
   Normal daytime temperature:	-70.44	degrees Celcius
   Normal night temperature:	-75.29	degrees Celcius
   Maximum temperature:   	-55.18	degrees Celcius
   Minimum temperature:   	-91.63	degrees Celcius
   Escape Velocity:		11.91	km/sec
   Molecular weight retained:	5.59 and above
   Surface acceleration:	1040.62	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.654
   Length of year:		944.00	days
   Length of day:		14.87	hours
   Boiling point of water:	113.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.13
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 91
				Chlorine     melts at -101  boils at -25
				Ammonia      melts at -78   boils at -25
   gasses in atmosphere:
				Nitrogen         99.8%  PP 1589.0 mb
				CarbonDioxide     0.1%  PP    0.8 mb
				Ozone             0.1%  PP    0.9 mb


Planet 9	*gas giant*
   Distance from primary:	3.142	AU
   Mass:			78.058	Earth masses
   Equatorial radius:		40762.5	km
   Density:			1.644	grams/cc
   Eccentricity of orbit:	0.127
   Escape Velocity:		39.08	km/sec
   Molecular weight retained:	0.52 and above
   Surface acceleration:	1873.41	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.521
   Length of year:		1941.17	days
   Length of day:		9.44	hours


Planet 10	*gas giant*
   Distance from primary:	6.640	AU
   Mass:			746.910	Earth masses
   Equatorial radius:		83834.8	km
   Density:			1.809	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		84.30	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4237.98	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.482
   Length of year:		5958.57	days
   Length of day:		6.28	hours


Planet 11	*gas giant*
   Distance from primary:	13.200	AU
   Mass:			18.697	Earth masses
   Equatorial radius:		30282.5	km
   Density:			0.961	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		22.19	km/sec
   Molecular weight retained:	1.61 and above
   Surface acceleration:	813.09	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.542
   Length of year:		16718.03	days
   Length of day:		14.33	hours


Planet 12	*gas giant*
   Distance from primary:	16.831	AU
   Mass:			0.491	Earth masses
   Equatorial radius:		10692.0	km
   Density:			0.574	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		6.05	km/sec
   Molecular weight retained:	21.65 and above
   Surface acceleration:	171.43	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.503
   Length of year:		24070.01	days
   Length of day:		31.22	hours


Planet 13	*gas giant*
   Distance from primary:	21.787	AU
   Mass:			26.351	Earth masses
   Equatorial radius:		34897.1	km
   Density:			0.885	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		24.54	km/sec
   Molecular weight retained:	1.32 and above
   Surface acceleration:	862.90	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.483
   Length of year:		35448.15	days
   Length of day:		13.91	hours


Planet 14	*gas giant*
   Distance from primary:	36.225	AU
   Mass:			5.732	Earth masses
   Equatorial radius:		23332.5	km
   Density:			0.644	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		14.00	km/sec
   Molecular weight retained:	4.05 and above
   Surface acceleration:	419.87	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.543
   Length of year:		76003.21	days
   Length of day:		19.95	hours


Planet 15	
   Distance from primary:	50.442	AU
   Mass:			0.104	Earth masses
   Equatorial radius:		4064.7	km
   Density:			2.211	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.80	degrees Celcius
   Normal daytime temperature:	-225.26	degrees Celcius
   Normal night temperature:	-236.23	degrees Celcius
   Maximum temperature:   	-210.42	degrees Celcius
   Minimum temperature:   	-251.11	degrees Celcius
   Escape Velocity:		4.52	km/sec
   Molecular weight retained:	38.87 and above
   Surface acceleration:	251.20	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.153
   Length of year:		124882.82	days
   Length of day:		30.24	hours
   Boiling point of water:	-63.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


