                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504828b
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6266 K
Stellar class: F8
Age: 5.874 billion years  (1.099 billion left on main sequence)
Habitable ecosphere radius: 1.255 AU

Planets present at:
1	  0.332 AU	no atmosphere
2	  0.388 AU	no atmosphere
3	  0.562 AU	no atmosphere
4	  0.678 AU	no atmosphere
5	  0.881 AU	no atmosphere
6	  0.974 AU	greenhouse
7	  1.746 AU	cold
8	  2.727 AU	gas giant
9	  4.450 AU	gas giant
10	  7.497 AU	gas giant
11	 12.169 AU	gas giant
12	 23.741 AU	gas giant
13	 36.259 AU	gas giant
14	 45.360 AU	no atmosphere



Planet 1	
   Distance from primary:	0.332	AU
   Mass:			0.184	Earth masses
   Equatorial radius:		3670.2	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		259.12	degrees Celcius
   Normal daytime temperature:	478.03	degrees Celcius
   Normal night temperature:	-177.71	degrees Celcius
   Maximum temperature:   	481.22	degrees Celcius
   Minimum temperature:   	-188.96	degrees Celcius
   Escape Velocity:		6.32	km/sec
   Molecular weight retained:	19.87 and above
   Surface acceleration:	544.25	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.073
   Length of year:		66.59	days
   Length of day:		1598.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.388	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		1858.1	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		216.91	degrees Celcius
   Maximum temperature:   	430.03	degrees Celcius
   Minimum temperature:   	-200.13	degrees Celcius
   Escape Velocity:		3.19	km/sec
   Molecular weight retained:	78.19 and above
   Surface acceleration:	273.21	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.089
   Length of year:		84.19	days
   Length of day:		2020.52	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.562	AU
   Mass:			0.026	Earth masses
   Equatorial radius:		1919.5	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		137.26	degrees Celcius
   Maximum temperature:   	332.52	degrees Celcius
   Minimum temperature:   	-219.34	degrees Celcius
   Escape Velocity:		3.29	km/sec
   Molecular weight retained:	73.25 and above
   Surface acceleration:	282.30	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.061
   Length of year:		146.66	days
   Length of day:		3519.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.678	AU
   Mass:			0.174	Earth masses
   Equatorial radius:		3606.6	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		101.39	degrees Celcius
   Maximum temperature:   	287.63	degrees Celcius
   Minimum temperature:   	-225.04	degrees Celcius
   Escape Velocity:		6.21	km/sec
   Molecular weight retained:	20.58 and above
   Surface acceleration:	534.61	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.050
   Length of year:		194.67	days
   Length of day:		4672.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.881	AU
   Mass:			0.124	Earth masses
   Equatorial radius:		3220.3	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		52.91	degrees Celcius
   Normal daytime temperature:	215.01	degrees Celcius
   Normal night temperature:	-186.51	degrees Celcius
   Maximum temperature:   	221.04	degrees Celcius
   Minimum temperature:   	-200.37	degrees Celcius
   Escape Velocity:		5.54	km/sec
   Molecular weight retained:	25.88 and above
   Surface acceleration:	476.29	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.079
   Length of year:		288.42	days
   Length of day:		678.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 6	
   Distance from primary:	0.974	AU
   Mass:			1.364	Earth masses
   Equatorial radius:		7084.0	km
   Density:			5.477	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		1.11	Earth gees
   Surface pressure:		181.262	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		463.14	degrees Celcius
   Maximum temperature:   	466.26	degrees Celcius
   Minimum temperature:   	457.91	degrees Celcius
   Escape Velocity:		12.39	km/sec
   Molecular weight retained:	5.17 and above
   Surface acceleration:	1084.30	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.486
   Length of year:		335.16	days
   Length of day:		15.70	hours
   Boiling point of water:	332.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1269
				Cesium       melts at 28    boils at 1315
				Gallium      melts at 30    boils at 4071
				Rubidium     melts at 39    boils at 1287
				Potassium    melts at 63    boils at 1413
				Sodium       melts at 98    boils at 1601
				Indium       melts at 157   boils at 3547
				Lithium      melts at 181   boils at 2357
				Selenium     melts at 217   boils at 1282
				Tin          melts at 232   boils at 4428
				Polonium     melts at 254   boils at 1732
				Bismuth      melts at 271   boils at 2709
				Thallium     melts at 304   boils at 2535
				Cadmium      melts at 321   boils at 1412
				Lead         melts at 328   boils at 3013
				Zinc         melts at 420   boils at 1643
				Tellurium    melts at 450   boils at 1777
   gasses in atmosphere:
				Sulfur           21.8%  PP 39448.0 mb
				Nitrogen         77.6%  PP 140658.9 mb
				Phosphorus        0.4%  PP  784.0 mb


Planet 7	
   Distance from primary:	1.746	AU
   Mass:			1.328	Earth masses
   Equatorial radius:		7022.2	km
   Density:			5.473	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.492	Earth atmospheres
   Surface temperature:		-79.95	degrees Celcius
   Normal daytime temperature:	-77.64	degrees Celcius
   Normal night temperature:	-82.40	degrees Celcius
   Maximum temperature:   	-61.67	degrees Celcius
   Minimum temperature:   	-99.53	degrees Celcius
   Escape Velocity:		12.28	km/sec
   Molecular weight retained:	5.26 and above
   Surface acceleration:	1074.02	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.756
   Length of year:		804.36	days
   Length of day:		14.66	hours
   Boiling point of water:	111.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	98.74
   liquids at surface:
				Ethanol      melts at -114  boils at 89
				Chlorine     melts at -101  boils at -27
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1490.2 mb
				Ozone             0.1%  PP    0.8 mb


Planet 8	*gas giant*
   Distance from primary:	2.727	AU
   Mass:			218.499	Earth masses
   Equatorial radius:		54387.8	km
   Density:			1.938	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		56.61	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2945.67	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.463
   Length of year:		1569.30	days
   Length of day:		7.53	hours


Planet 9	*gas giant*
   Distance from primary:	4.450	AU
   Mass:			19.624	Earth masses
   Equatorial radius:		28050.6	km
   Density:			1.269	grams/cc
   Eccentricity of orbit:	0.150
   Escape Velocity:		23.62	km/sec
   Molecular weight retained:	1.42 and above
   Surface acceleration:	994.56	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.466
   Length of year:		3271.72	days
   Length of day:		12.96	hours


Planet 10	*gas giant*
   Distance from primary:	7.497	AU
   Mass:			39.309	Earth masses
   Equatorial radius:		35877.2	km
   Density:			1.215	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		29.56	km/sec
   Molecular weight retained:	0.91 and above
   Surface acceleration:	1217.85	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.524
   Length of year:		7153.78	days
   Length of day:		11.71	hours


Planet 11	*gas giant*
   Distance from primary:	12.169	AU
   Mass:			315.758	Earth masses
   Equatorial radius:		68591.4	km
   Density:			1.396	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		60.59	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2676.42	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.541
   Length of year:		14789.88	days
   Length of day:		7.90	hours


Planet 12	*gas giant*
   Distance from primary:	23.741	AU
   Mass:			86.762	Earth masses
   Equatorial radius:		49753.7	km
   Density:			1.005	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		37.29	km/sec
   Molecular weight retained:	0.57 and above
   Surface acceleration:	1397.72	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.512
   Length of year:		40315.52	days
   Length of day:		10.93	hours


Planet 13	*gas giant*
   Distance from primary:	36.259	AU
   Mass:			1.211	Earth masses
   Equatorial radius:		14827.7	km
   Density:			0.530	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		8.07	km/sec
   Molecular weight retained:	12.18 and above
   Surface acceleration:	219.69	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.454
   Length of year:		76100.64	days
   Length of day:		27.58	hours


Planet 14	
   Distance from primary:	45.360	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1909.1	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.12	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.34	degrees Celcius
   Normal daytime temperature:	-220.24	degrees Celcius
   Normal night temperature:	-236.28	degrees Celcius
   Maximum temperature:   	-208.90	degrees Celcius
   Minimum temperature:   	-247.72	degrees Celcius
   Escape Velocity:		2.11	km/sec
   Molecular weight retained:	177.81 and above
   Surface acceleration:	116.92	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.139
   Length of year:		106482.25	days
   Length of day:		44.32	hours
   Boiling point of water:	-96.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


