                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485cf
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6304 K
Stellar class: F7
Age: 1.866 billion years  (4.998 billion left on main sequence)
Habitable ecosphere radius: 1.268 AU

Planets present at:
1	  0.361 AU	no atmosphere
2	  0.394 AU	no atmosphere
3	  0.572 AU	no atmosphere
4	  1.141 AU	gas giant
5	  2.492 AU	gas giant
6	  5.201 AU	gas giant
7	  7.654 AU	gas giant
8	 12.308 AU	gas giant
9	 31.923 AU	gas giant
10	 49.440 AU	no atmosphere



Planet 1	
   Distance from primary:	0.361	AU
   Mass:			1/100.2	Earth masses
   Equatorial radius:		1394.2	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		239.53	degrees Celcius
   Normal daytime temperature:	454.52	degrees Celcius
   Normal night temperature:	-184.47	degrees Celcius
   Maximum temperature:   	457.56	degrees Celcius
   Minimum temperature:   	-194.74	degrees Celcius
   Escape Velocity:		2.39	km/sec
   Molecular weight retained:	139.05 and above
   Surface acceleration:	204.74	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.074
   Length of year:		75.38	days
   Length of day:		1809.09	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.394	AU
   Mass:			0.113	Earth masses
   Equatorial radius:		3126.5	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		217.46	degrees Celcius
   Maximum temperature:   	430.77	degrees Celcius
   Minimum temperature:   	-200.56	degrees Celcius
   Escape Velocity:		5.38	km/sec
   Molecular weight retained:	27.47 and above
   Surface acceleration:	462.18	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.072
   Length of year:		86.17	days
   Length of day:		2068.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.572	AU
   Mass:			0.368	Earth masses
   Equatorial radius:		4615.5	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.16	degrees Celcius
   Maximum temperature:   	327.36	degrees Celcius
   Minimum temperature:   	-219.85	degrees Celcius
   Escape Velocity:		7.98	km/sec
   Molecular weight retained:	12.48 and above
   Surface acceleration:	689.01	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.084
   Length of year:		150.33	days
   Length of day:		3608.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	*gas giant*
   Distance from primary:	1.141	AU
   Mass:			5.502	Earth masses
   Equatorial radius:		17268.6	km
   Density:			1.525	grams/cc
   Eccentricity of orbit:	0.215
   Escape Velocity:		15.94	km/sec
   Molecular weight retained:	3.12 and above
   Surface acceleration:	735.80	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.529
   Length of year:		423.95	days
   Length of day:		15.09	hours


Planet 5	*gas giant*
   Distance from primary:	2.492	AU
   Mass:			130.968	Earth masses
   Equatorial radius:		46456.6	km
   Density:			1.864	grams/cc
   Eccentricity of orbit:	0.083
   Escape Velocity:		47.42	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2419.96	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.545
   Length of year:		1368.28	days
   Length of day:		8.31	hours


Planet 6	*gas giant*
   Distance from primary:	5.201	AU
   Mass:			3.359	Earth masses
   Equatorial radius:		16969.1	km
   Density:			0.981	grams/cc
   Eccentricity of orbit:	0.255
   Escape Velocity:		12.57	km/sec
   Molecular weight retained:	5.03 and above
   Surface acceleration:	465.24	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.518
   Length of year:		4125.86	days
   Length of day:		18.95	hours


Planet 7	*gas giant*
   Distance from primary:	7.654	AU
   Mass:			901.235	Earth masses
   Equatorial radius:		89531.7	km
   Density:			1.792	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		89.60	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4483.57	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.521
   Length of year:		7356.27	days
   Length of day:		6.10	hours


Planet 8	*gas giant*
   Distance from primary:	12.308	AU
   Mass:			130.774	Earth masses
   Equatorial radius:		53046.8	km
   Density:			1.250	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		44.34	km/sec
   Molecular weight retained:	0.40 and above
   Surface acceleration:	1853.28	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.456
   Length of year:		15016.47	days
   Length of day:		9.49	hours


Planet 9	*gas giant*
   Distance from primary:	31.923	AU
   Mass:			14.658	Earth masses
   Equatorial radius:		30334.9	km
   Density:			0.749	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		19.63	km/sec
   Molecular weight retained:	2.06 and above
   Surface acceleration:	635.24	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.498
   Length of year:		62736.30	days
   Length of day:		16.22	hours


Planet 10	
   Distance from primary:	49.440	AU
   Mass:			0.135	Earth masses
   Equatorial radius:		4425.6	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.98	degrees Celcius
   Normal daytime temperature:	-224.54	degrees Celcius
   Normal night temperature:	-235.31	degrees Celcius
   Maximum temperature:   	-212.77	degrees Celcius
   Minimum temperature:   	-247.55	degrees Celcius
   Escape Velocity:		4.93	km/sec
   Molecular weight retained:	32.72 and above
   Surface acceleration:	274.10	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.140
   Length of year:		120914.18	days
   Length of day:		28.95	hours
   Boiling point of water:	-60.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


