                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504867f
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6262 K
Stellar class: F8
Age: 5.508 billion years  (1.333 billion left on main sequence)
Habitable ecosphere radius: 1.270 AU

Planets present at:
1	  0.446 AU	no atmosphere
2	  0.556 AU	no atmosphere
3	  0.651 AU	greenhouse
4	  0.704 AU	no atmosphere
5	  0.833 AU	greenhouse
6	  1.553 AU	gas giant
7	  2.614 AU	no atmosphere
8	  3.030 AU	gas giant
9	  6.964 AU	gas giant
10	 11.442 AU	gas giant
11	 20.432 AU	gas giant
12	 39.727 AU	gas giant



Planet 1	
   Distance from primary:	0.446	AU
   Mass:			0.094	Earth masses
   Equatorial radius:		2941.7	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		187.57	degrees Celcius
   Maximum temperature:   	394.52	degrees Celcius
   Minimum temperature:   	-208.59	degrees Celcius
   Escape Velocity:		5.06	km/sec
   Molecular weight retained:	31.06 and above
   Surface acceleration:	434.45	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.080
   Length of year:		103.69	days
   Length of day:		2488.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.556	AU
   Mass:			0.076	Earth masses
   Equatorial radius:		2740.7	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		141.25	degrees Celcius
   Maximum temperature:   	337.49	degrees Celcius
   Minimum temperature:   	-218.66	degrees Celcius
   Escape Velocity:		4.71	km/sec
   Molecular weight retained:	35.81 and above
   Surface acceleration:	404.37	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.066
   Length of year:		144.14	days
   Length of day:		3459.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.651	AU
   Mass:			0.645	Earth masses
   Equatorial radius:		5549.9	km
   Density:			5.385	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.85	Earth gees
   Surface pressure:		35.325	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		283.54	degrees Celcius
   Maximum temperature:   	301.80	degrees Celcius
   Minimum temperature:   	215.91	degrees Celcius
   Escape Velocity:		9.63	km/sec
   Molecular weight retained:	8.56 and above
   Surface acceleration:	835.29	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.546
   Length of year:		182.83	days
   Length of day:		4387.88	hours
   Boiling point of water:	233.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 582
				Francium     melts at 27    boils at 1016
				Cesium       melts at 28    boils at 1054
				Gallium      melts at 30    boils at 3359
				Rubidium     melts at 39    boils at 1031
				Potassium    melts at 63    boils at 1137
				Sodium       melts at 98    boils at 1294
				Sulfur       melts at 113   boils at 701
				Indium       melts at 157   boils at 2921
				Lithium      melts at 181   boils at 1926
				Selenium     melts at 217   boils at 1027
				Tin          melts at 232   boils at 3658
				Polonium     melts at 254   boils at 1403
				Bismuth      melts at 271   boils at 2220
   gasses in atmosphere:
				Nitrogen         98.6%  PP 34837.7 mb
				Phosphorus        0.9%  PP  320.5 mb
				CarbonDioxide     0.1%  PP   39.4 mb
				Ozone             0.1%  PP   37.5 mb
				Ethanol           0.1%  PP   40.4 mb


Planet 4	
   Distance from primary:	0.704	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		2298.9	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		93.09	degrees Celcius
   Maximum temperature:   	277.28	degrees Celcius
   Minimum temperature:   	-226.00	degrees Celcius
   Escape Velocity:		3.95	km/sec
   Molecular weight retained:	51.00 and above
   Surface acceleration:	338.55	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.087
   Length of year:		205.24	days
   Length of day:		4925.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.833	AU
   Mass:			0.577	Earth masses
   Equatorial radius:		5350.4	km
   Density:			5.375	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		0.82	Earth gees
   Surface pressure:		26.914	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		177.50	degrees Celcius
   Maximum temperature:   	185.85	degrees Celcius
   Minimum temperature:   	168.39	degrees Celcius
   Escape Velocity:		9.27	km/sec
   Molecular weight retained:	9.23 and above
   Surface acceleration:	803.76	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.451
   Length of year:		264.43	days
   Length of day:		26.34	hours
   Boiling point of water:	219.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 559
				Francium     melts at 27    boils at 982
				Cesium       melts at 28    boils at 1019
				Gallium      melts at 30    boils at 3263
				Rubidium     melts at 39    boils at 997
				Phosphorus   melts at 44    boils at 458
				Potassium    melts at 63    boils at 1099
				Sodium       melts at 98    boils at 1252
				Sulfur       melts at 113   boils at 675
				Iodine       melts at 114   boils at 333
				Indium       melts at 157   boils at 2836
   gasses in atmosphere:
				Nitrogen         99.5%  PP 26781.9 mb
				Water             0.1%  PP   13.7 mb
				CarbonDioxide     0.1%  PP   31.1 mb
				Ozone             0.1%  PP   30.2 mb
				Ethanol           0.1%  PP   31.8 mb


Planet 6	*gas giant*
   Distance from primary:	1.553	AU
   Mass:			5.629	Earth masses
   Equatorial radius:		17832.7	km
   Density:			1.416	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		15.87	km/sec
   Molecular weight retained:	3.15 and above
   Surface acceleration:	705.86	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.493
   Length of year:		672.86	days
   Length of day:		15.39	hours


Planet 7	
   Distance from primary:	2.614	AU
   Mass:			0.218	Earth masses
   Equatorial radius:		3880.4	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.035	Earth atmospheres
   Surface temperature:		-90.74	degrees Celcius
   Normal daytime temperature:	-78.15	degrees Celcius
   Normal night temperature:	-103.60	degrees Celcius
   Maximum temperature:   	-55.14	degrees Celcius
   Minimum temperature:   	-127.78	degrees Celcius
   Escape Velocity:		6.69	km/sec
   Molecular weight retained:	17.75 and above
   Surface acceleration:	576.20	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.372
   Length of year:		1469.11	days
   Length of day:		19.98	hours
   Boiling point of water:	25.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	45.88
   liquids at surface:
				Ethanol      melts at -114  boils at 9
				Chlorine     melts at -101  boils at -81
   gasses in atmosphere:
				Ozone            92.9%  PP   32.2 mb
				Argon             0.3%  PP    0.1 mb
				Neon              0.5%  PP    0.2 mb
				Krypton           5.6%  PP    1.9 mb
				Xenon             0.7%  PP    0.2 mb


Planet 8	*gas giant*
   Distance from primary:	3.030	AU
   Mass:			77.238	Earth masses
   Equatorial radius:		40471.6	km
   Density:			1.663	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		39.01	km/sec
   Molecular weight retained:	0.52 and above
   Surface acceleration:	1880.47	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.523
   Length of year:		1833.37	days
   Length of day:		9.43	hours


Planet 9	*gas giant*
   Distance from primary:	6.964	AU
   Mass:			1085.256	Earth masses
   Equatorial radius:		93759.9	km
   Density:			1.879	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		96.08	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4923.08	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.537
   Length of year:		6379.83	days
   Length of day:		5.83	hours


Planet 10	*gas giant*
   Distance from primary:	11.442	AU
   Mass:			10.519	Earth masses
   Equatorial radius:		25275.8	km
   Density:			0.930	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		18.22	km/sec
   Molecular weight retained:	2.39 and above
   Surface acceleration:	656.62	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.466
   Length of year:		13456.86	days
   Length of day:		15.95	hours


Planet 11	*gas giant*
   Distance from primary:	20.432	AU
   Mass:			115.285	Earth masses
   Equatorial radius:		53328.5	km
   Density:			1.085	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		41.52	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1616.56	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.489
   Length of year:		32106.01	days
   Length of day:		10.17	hours


Planet 12	*gas giant*
   Distance from primary:	39.727	AU
   Mass:			1.772	Earth masses
   Equatorial radius:		16677.6	km
   Density:			0.545	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		9.21	km/sec
   Molecular weight retained:	9.37 and above
   Surface acceleration:	254.04	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.466
   Length of year:		87056.53	days
   Length of day:		25.64	hours


