                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048658
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6300 K
Stellar class: F8
Age: 1.518 billion years  (5.328 billion left on main sequence)
Habitable ecosphere radius: 1.270 AU

Planets present at:
1	  0.313 AU	no atmosphere
2	  0.411 AU	no atmosphere
3	  0.520 AU	no atmosphere
4	  0.645 AU	no atmosphere
5	  0.842 AU	greenhouse
6	  1.405 AU	cold
7	  1.800 AU	gas giant
8	  2.898 AU	cold
9	  3.341 AU	no atmosphere
10	  4.209 AU	gas giant
11	  8.423 AU	gas giant
12	 19.186 AU	gas giant
13	 31.012 AU	no atmosphere
14	 34.284 AU	gas giant
15	 47.712 AU	no atmosphere



Planet 1	
   Distance from primary:	0.313	AU
   Mass:			0.100	Earth masses
   Equatorial radius:		2996.0	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		279.93	degrees Celcius
   Normal daytime temperature:	503.01	degrees Celcius
   Normal night temperature:	-171.22	degrees Celcius
   Maximum temperature:   	506.01	degrees Celcius
   Minimum temperature:   	-182.05	degrees Celcius
   Escape Velocity:		5.15	km/sec
   Molecular weight retained:	29.93 and above
   Surface acceleration:	442.58	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.060
   Length of year:		60.87	days
   Length of day:		1461.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.411	AU
   Mass:			1/123	Earth masses
   Equatorial radius:		1302.1	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		211.03	degrees Celcius
   Maximum temperature:   	422.97	degrees Celcius
   Minimum temperature:   	-202.57	degrees Celcius
   Escape Velocity:		2.23	km/sec
   Molecular weight retained:	159.45 and above
   Surface acceleration:	191.17	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.050
   Length of year:		91.49	days
   Length of day:		2195.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.520	AU
   Mass:			0.085	Earth masses
   Equatorial radius:		2845.8	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		155.92	degrees Celcius
   Maximum temperature:   	355.42	degrees Celcius
   Minimum temperature:   	-215.06	degrees Celcius
   Escape Velocity:		4.89	km/sec
   Molecular weight retained:	33.20 and above
   Surface acceleration:	420.08	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.058
   Length of year:		130.56	days
   Length of day:		3133.43	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.645	AU
   Mass:			0.218	Earth masses
   Equatorial radius:		3885.5	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		109.73	degrees Celcius
   Maximum temperature:   	298.11	degrees Celcius
   Minimum temperature:   	-224.03	degrees Celcius
   Escape Velocity:		6.70	km/sec
   Molecular weight retained:	17.70 and above
   Surface acceleration:	576.98	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.082
   Length of year:		180.23	days
   Length of day:		4325.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.842	AU
   Mass:			0.995	Earth masses
   Equatorial radius:		6393.0	km
   Density:			5.432	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.99	Earth gees
   Surface pressure:		85.438	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		407.31	degrees Celcius
   Maximum temperature:   	411.78	degrees Celcius
   Minimum temperature:   	401.16	degrees Celcius
   Escape Velocity:		11.14	km/sec
   Molecular weight retained:	6.40 and above
   Surface acceleration:	970.61	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.567
   Length of year:		268.43	days
   Length of day:		16.35	hours
   Boiling point of water:	282.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1142
				Cesium       melts at 28    boils at 1183
				Gallium      melts at 30    boils at 3712
				Rubidium     melts at 39    boils at 1158
				Potassium    melts at 63    boils at 1274
				Sodium       melts at 98    boils at 1446
				Sulfur       melts at 113   boils at 796
				Indium       melts at 157   boils at 3231
				Lithium      melts at 181   boils at 2139
				Selenium     melts at 217   boils at 1153
				Tin          melts at 232   boils at 4040
				Polonium     melts at 254   boils at 1566
				Bismuth      melts at 271   boils at 2462
				Thallium     melts at 304   boils at 2303
				Cadmium      melts at 321   boils at 1273
				Lead         melts at 328   boils at 2741
   gasses in atmosphere:
				Nitrogen         99.2%  PP 84756.8 mb
				Phosphorus        0.5%  PP  444.2 mb
				CarbonDioxide     0.1%  PP   47.3 mb
				Ozone             0.1%  PP   45.2 mb
				Ethanol           0.1%  PP   47.8 mb


Planet 6	
   Distance from primary:	1.405	AU
   Mass:			0.492	Earth masses
   Equatorial radius:		5079.1	km
   Density:			5.362	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.248	Earth atmospheres
   Surface temperature:		-1.42	degrees Celcius
   Normal daytime temperature:	7.29	degrees Celcius
   Normal night temperature:	-10.58	degrees Celcius
   Maximum temperature:   	32.89	degrees Celcius
   Minimum temperature:   	-37.55	degrees Celcius
   Escape Velocity:		8.79	km/sec
   Molecular weight retained:	10.27 and above
   Surface acceleration:	761.14	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.212
   Length of year:		578.98	days
   Length of day:		17.46	hours
   Boiling point of water:	65.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	13.51
   Ice cover percentage:	8.86
   liquids at surface:
				Ethanol      melts at -114  boils at 46
				Mercury      melts at -39   boils at 298
				Bromine      melts at -7    boils at 29
   gasses in atmosphere:
				Oxygen           64.7%  PP  160.2 mb
				Nitrogen         35.2%  PP   87.1 mb


Planet 7	*gas giant*
   Distance from primary:	1.800	AU
   Mass:			7.782	Earth masses
   Equatorial radius:		19843.2	km
   Density:			1.421	grams/cc
   Eccentricity of orbit:	0.044
   Escape Velocity:		17.69	km/sec
   Molecular weight retained:	2.54 and above
   Surface acceleration:	788.19	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.452
   Length of year:		839.60	days
   Length of day:		14.56	hours


Planet 8	
   Distance from primary:	2.898	AU
   Mass:			1.075	Earth masses
   Equatorial radius:		6556.1	km
   Density:			5.442	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		1.02	Earth gees
   Surface pressure:		1.074	Earth atmospheres
   Surface temperature:		-120.48	degrees Celcius
   Normal daytime temperature:	-118.27	degrees Celcius
   Normal night temperature:	-122.82	degrees Celcius
   Maximum temperature:   	-102.36	degrees Celcius
   Minimum temperature:   	-140.10	degrees Celcius
   Escape Velocity:		11.43	km/sec
   Molecular weight retained:	6.07 and above
   Surface acceleration:	997.21	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.733
   Length of year:		1715.13	days
   Length of day:		15.18	hours
   Boiling point of water:	102.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -111
   gasses in atmosphere:
				Oxygen           24.9%  PP  267.4 mb
				Nitrogen         75.1%  PP  806.3 mb


Planet 9	
   Distance from primary:	3.341	AU
   Mass:			0.154	Earth masses
   Equatorial radius:		3458.2	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.022	Earth atmospheres
   Surface temperature:		-122.01	degrees Celcius
   Normal daytime temperature:	-110.09	degrees Celcius
   Normal night temperature:	-134.13	degrees Celcius
   Maximum temperature:   	-88.03	degrees Celcius
   Minimum temperature:   	-157.41	degrees Celcius
   Escape Velocity:		5.95	km/sec
   Molecular weight retained:	22.41 and above
   Surface acceleration:	512.16	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.460
   Length of year:		2123.71	days
   Length of day:		21.18	hours
   Boiling point of water:	18.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	52.80
   gasses in atmosphere:
				Argon             1.5%  PP    0.3 mb
				Krypton          98.5%  PP   22.0 mb


Planet 10	*gas giant*
   Distance from primary:	4.209	AU
   Mass:			495.644	Earth masses
   Equatorial radius:		71538.5	km
   Density:			1.932	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		74.34	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3862.15	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.528
   Length of year:		3000.65	days
   Length of day:		6.58	hours


Planet 11	*gas giant*
   Distance from primary:	8.423	AU
   Mass:			491.668	Earth masses
   Equatorial radius:		75618.4	km
   Density:			1.623	grams/cc
   Eccentricity of orbit:	0.191
   Escape Velocity:		72.01	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3428.92	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.533
   Length of year:		8494.67	days
   Length of day:		6.98	hours


Planet 12	*gas giant*
   Distance from primary:	19.186	AU
   Mass:			22.707	Earth masses
   Equatorial radius:		33029.0	km
   Density:			0.899	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		23.42	km/sec
   Molecular weight retained:	1.45 and above
   Surface acceleration:	830.06	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.497
   Length of year:		29219.89	days
   Length of day:		14.19	hours


Planet 13	
   Distance from primary:	31.012	AU
   Mass:			0.139	Earth masses
   Equatorial radius:		4474.2	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-218.83	degrees Celcius
   Normal daytime temperature:	-212.01	degrees Celcius
   Normal night temperature:	-225.58	degrees Celcius
   Maximum temperature:   	-196.81	degrees Celcius
   Minimum temperature:   	-241.42	degrees Celcius
   Escape Velocity:		4.98	km/sec
   Molecular weight retained:	32.00 and above
   Surface acceleration:	277.20	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.152
   Length of year:		60049.66	days
   Length of day:		28.79	hours
   Boiling point of water:	-59.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06
   liquids at surface:
				Fluorine     melts at -220  boils at -217


Planet 14	*gas giant*
   Distance from primary:	34.284	AU
   Mass:			5.093	Earth masses
   Equatorial radius:		22416.2	km
   Density:			0.645	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		13.46	km/sec
   Molecular weight retained:	4.38 and above
   Surface acceleration:	404.21	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.532
   Length of year:		69798.37	days
   Length of day:		20.33	hours


Planet 15	
   Distance from primary:	47.712	AU
   Mass:			0.161	Earth masses
   Equatorial radius:		4696.9	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.23	degrees Celcius
   Normal daytime temperature:	-223.84	degrees Celcius
   Normal night temperature:	-234.52	degrees Celcius
   Maximum temperature:   	-208.44	degrees Celcius
   Minimum temperature:   	-250.08	degrees Celcius
   Escape Velocity:		5.23	km/sec
   Molecular weight retained:	29.00 and above
   Surface acceleration:	291.42	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.161
   Length of year:		114593.34	days
   Length of day:		28.07	hours
   Boiling point of water:	-55.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


