                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486c3
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6279 K
Stellar class: F8
Age: 5.467 billion years  (1.365 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.353 AU	no atmosphere
2	  0.431 AU	no atmosphere
3	  0.479 AU	no atmosphere
4	  0.650 AU	no atmosphere
5	  0.962 AU	greenhouse
6	  1.597 AU	gas giant
7	  2.514 AU	cold
8	  3.103 AU	cold
9	  5.137 AU	gas giant
10	 10.531 AU	gas giant
11	 16.062 AU	gas giant
12	 26.545 AU	gas giant
13	 32.153 AU	no atmosphere
14	 49.139 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.353	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		2475.4	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.172
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		245.86	degrees Celcius
   Normal daytime temperature:	460.82	degrees Celcius
   Normal night temperature:	-170.86	degrees Celcius
   Maximum temperature:   	464.55	degrees Celcius
   Minimum temperature:   	-184.07	degrees Celcius
   Escape Velocity:		4.25	km/sec
   Molecular weight retained:	43.95 and above
   Surface acceleration:	364.81	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.074
   Length of year:		72.94	days
   Length of day:		1236.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.431	AU
   Mass:			0.011	Earth masses
   Equatorial radius:		1439.9	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		196.96	degrees Celcius
   Maximum temperature:   	405.83	degrees Celcius
   Minimum temperature:   	-205.89	degrees Celcius
   Escape Velocity:		2.47	km/sec
   Molecular weight retained:	130.35 and above
   Surface acceleration:	211.47	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.072
   Length of year:		98.30	days
   Length of day:		2359.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.479	AU
   Mass:			0.406	Earth masses
   Equatorial radius:		4768.8	km
   Density:			5.348	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		171.65	degrees Celcius
   Maximum temperature:   	374.91	degrees Celcius
   Minimum temperature:   	-211.96	degrees Celcius
   Escape Velocity:		8.25	km/sec
   Molecular weight retained:	11.68 and above
   Surface acceleration:	712.78	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.080
   Length of year:		115.37	days
   Length of day:		2768.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.650	AU
   Mass:			1/145.9	Earth masses
   Equatorial radius:		1230.2	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.171
   Surface gravity:		0.18	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		110.10	degrees Celcius
   Maximum temperature:   	298.64	degrees Celcius
   Minimum temperature:   	-222.29	degrees Celcius
   Escape Velocity:		2.11	km/sec
   Molecular weight retained:	178.64 and above
   Surface acceleration:	180.60	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.069
   Length of year:		181.99	days
   Length of day:		3091.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.962	AU
   Mass:			1.529	Earth masses
   Equatorial radius:		7349.4	km
   Density:			5.495	grams/cc
   Eccentricity of orbit:	0.118
   Surface gravity:		1.15	Earth gees
   Surface pressure:		176.345	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		492.83	degrees Celcius
   Maximum temperature:   	495.99	degrees Celcius
   Minimum temperature:   	487.29	degrees Celcius
   Escape Velocity:		12.88	km/sec
   Molecular weight retained:	4.78 and above
   Surface acceleration:	1128.71	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.419
   Length of year:		327.82	days
   Length of day:		15.29	hours
   Boiling point of water:	330.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1264
				Cesium       melts at 28    boils at 1309
				Gallium      melts at 30    boils at 4057
				Rubidium     melts at 39    boils at 1282
				Potassium    melts at 63    boils at 1408
				Sodium       melts at 98    boils at 1595
				Indium       melts at 157   boils at 3534
				Lithium      melts at 181   boils at 2348
				Selenium     melts at 217   boils at 1277
				Tin          melts at 232   boils at 4413
				Polonium     melts at 254   boils at 1725
				Bismuth      melts at 271   boils at 2699
				Thallium     melts at 304   boils at 2526
				Cadmium      melts at 321   boils at 1406
				Lead         melts at 328   boils at 3002
				Zinc         melts at 420   boils at 1636
				Tellurium    melts at 450   boils at 1771
   gasses in atmosphere:
				Sulfur           20.9%  PP 36923.2 mb
				Nitrogen         78.4%  PP 138333.0 mb
				Phosphorus        0.4%  PP  734.8 mb


Planet 6	*gas giant*
   Distance from primary:	1.597	AU
   Mass:			2.929	Earth masses
   Equatorial radius:		14772.1	km
   Density:			1.296	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		12.58	km/sec
   Molecular weight retained:	5.02 and above
   Surface acceleration:	535.25	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.520
   Length of year:		701.31	days
   Length of day:		17.68	hours


Planet 7	
   Distance from primary:	2.514	AU
   Mass:			1.063	Earth masses
   Equatorial radius:		6532.3	km
   Density:			5.441	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		1.01	Earth gees
   Surface pressure:		0.870	Earth atmospheres
   Surface temperature:		-97.98	degrees Celcius
   Normal daytime temperature:	-95.18	degrees Celcius
   Normal night temperature:	-100.95	degrees Celcius
   Maximum temperature:   	-78.14	degrees Celcius
   Minimum temperature:   	-119.33	degrees Celcius
   Escape Velocity:		11.39	km/sec
   Molecular weight retained:	6.12 and above
   Surface acceleration:	993.32	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.643
   Length of year:		1385.23	days
   Length of day:		15.21	hours
   Boiling point of water:	96.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	83.16
   liquids at surface:
				Ethanol      melts at -114  boils at 75
				Chlorine     melts at -101  boils at -36
   gasses in atmosphere:
				Nitrogen         99.9%  PP  868.9 mb
				Ozone             0.1%  PP    0.5 mb


Planet 8	
   Distance from primary:	3.103	AU
   Mass:			1.184	Earth masses
   Equatorial radius:		6765.3	km
   Density:			5.456	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		1.05	Earth gees
   Surface pressure:		1.279	Earth atmospheres
   Surface temperature:		-117.56	degrees Celcius
   Normal daytime temperature:	-115.52	degrees Celcius
   Normal night temperature:	-119.71	degrees Celcius
   Maximum temperature:   	-100.60	degrees Celcius
   Minimum temperature:   	-135.91	degrees Celcius
   Escape Velocity:		11.81	km/sec
   Molecular weight retained:	5.69 and above
   Surface acceleration:	1031.53	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.678
   Length of year:		1899.72	days
   Length of day:		14.92	hours
   Boiling point of water:	106.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -109
   gasses in atmosphere:
				Nitrogen         100.0%  PP 1278.9 mb


Planet 9	*gas giant*
   Distance from primary:	5.137	AU
   Mass:			1269.562	Earth masses
   Equatorial radius:		95684.8	km
   Density:			2.068	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		102.87	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5529.77	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.511
   Length of year:		4040.00	days
   Length of day:		5.50	hours


Planet 10	*gas giant*
   Distance from primary:	10.531	AU
   Mass:			18.966	Earth masses
   Equatorial radius:		29808.1	km
   Density:			1.022	grams/cc
   Eccentricity of orbit:	0.134
   Escape Velocity:		22.53	km/sec
   Molecular weight retained:	1.56 and above
   Surface acceleration:	851.22	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.493
   Length of year:		11879.11	days
   Length of day:		14.01	hours


Planet 11	*gas giant*
   Distance from primary:	16.062	AU
   Mass:			87.016	Earth masses
   Equatorial radius:		48148.9	km
   Density:			1.112	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		37.97	km/sec
   Molecular weight retained:	0.55 and above
   Surface acceleration:	1496.81	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.492
   Length of year:		22373.74	days
   Length of day:		10.56	hours


Planet 12	*gas giant*
   Distance from primary:	26.545	AU
   Mass:			31.211	Earth masses
   Equatorial radius:		37230.0	km
   Density:			0.863	grams/cc
   Eccentricity of orbit:	0.019
   Escape Velocity:		25.86	km/sec
   Molecular weight retained:	1.19 and above
   Surface acceleration:	897.98	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.498
   Length of year:		47538.98	days
   Length of day:		13.64	hours


Planet 13	
   Distance from primary:	32.153	AU
   Mass:			0.142	Earth masses
   Equatorial radius:		4508.7	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-219.78	degrees Celcius
   Normal daytime temperature:	-213.11	degrees Celcius
   Normal night temperature:	-226.38	degrees Celcius
   Maximum temperature:   	-199.12	degrees Celcius
   Minimum temperature:   	-241.05	degrees Celcius
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.51 and above
   Surface acceleration:	279.40	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.153
   Length of year:		63377.38	days
   Length of day:		28.67	hours
   Boiling point of water:	-60.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 14	
   Distance from primary:	49.139	AU
   Mass:			0.182	Earth masses
   Equatorial radius:		4891.8	km
   Density:			2.223	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.53	degrees Celcius
   Normal daytime temperature:	-224.28	degrees Celcius
   Normal night temperature:	-234.68	degrees Celcius
   Maximum temperature:   	-209.87	degrees Celcius
   Minimum temperature:   	-249.39	degrees Celcius
   Escape Velocity:		5.45	km/sec
   Molecular weight retained:	26.70 and above
   Surface acceleration:	303.91	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.137
   Length of year:		119739.90	days
   Length of day:		27.49	hours
   Boiling point of water:	-54.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


