                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481e8
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6090 K
Stellar class: F9
Age: 5.760 billion years  (1.235 billion left on main sequence)
Habitable ecosphere radius: 1.252 AU

Planets present at:
1	  0.335 AU	no atmosphere
2	  0.382 AU	no atmosphere
3	  0.865 AU	greenhouse
4	  2.184 AU	gas giant
5	  3.089 AU	no atmosphere
6	  4.079 AU	no atmosphere
7	  5.399 AU	gas giant
8	  8.527 AU	gas giant
9	 15.345 AU	gas giant
10	 23.681 AU	gas giant
11	 48.558 AU	gas giant



Planet 1	
   Distance from primary:	0.335	AU
   Mass:			0.170	Earth masses
   Equatorial radius:		3576.0	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		253.96	degrees Celcius
   Normal daytime temperature:	471.79	degrees Celcius
   Normal night temperature:	-179.02	degrees Celcius
   Maximum temperature:   	475.00	degrees Celcius
   Minimum temperature:   	-190.22	degrees Celcius
   Escape Velocity:		6.16	km/sec
   Molecular weight retained:	20.94 and above
   Surface acceleration:	529.98	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.087
   Length of year:		67.61	days
   Length of day:		1622.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.382	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1501.1	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		223.40	degrees Celcius
   Maximum temperature:   	438.01	degrees Celcius
   Minimum temperature:   	-198.96	degrees Celcius
   Escape Velocity:		2.57	km/sec
   Molecular weight retained:	119.92 and above
   Surface acceleration:	220.49	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.067
   Length of year:		82.17	days
   Length of day:		1972.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.865	AU
   Mass:			2.891	Earth masses
   Equatorial radius:		9015.2	km
   Density:			5.630	grams/cc
   Eccentricity of orbit:	0.185
   Surface gravity:		1.45	Earth gees
   Surface pressure:		893.069	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		777.71	degrees Celcius
   Maximum temperature:   	777.41	degrees Celcius
   Minimum temperature:   	771.84	degrees Celcius
   Escape Velocity:		15.99	km/sec
   Molecular weight retained:	3.10 and above
   Surface acceleration:	1418.57	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.430
   Length of year:		280.60	days
   Length of day:		13.81	hours
   Boiling point of water:	475.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Gallium      melts at 30    boils at 5098
				Sodium       melts at 98    boils at 2044
				Indium       melts at 157   boils at 4450
				Lithium      melts at 181   boils at 2979
				Tin          melts at 232   boils at 5540
				Polonium     melts at 254   boils at 2206
				Bismuth      melts at 271   boils at 3414
				Thallium     melts at 304   boils at 3199
				Lead         melts at 328   boils at 3790
				Zinc         melts at 420   boils at 2095
				Tellurium    melts at 450   boils at 2262
				Antimony     melts at 631   boils at 3460
				Neptunium    melts at 640   boils at 8107
				Plutonium    melts at 641   boils at 6758
				Magnesium    melts at 649   boils at 2493
				Aluminum     melts at 660   boils at 5227
				Radium       melts at 700   boils at 3687
				Barium       melts at 725   boils at 3988
				Strontium    melts at 769   boils at 3047
   gasses in atmosphere:
				Sulfur            0.2%  PP 1407.3 mb
				Nitrogen          0.7%  PP 5943.0 mb
				Helium           99.2%  PP 885668.8 mb


Planet 4	*gas giant*
   Distance from primary:	2.184	AU
   Mass:			58.029	Earth masses
   Equatorial radius:		36274.0	km
   Density:			1.735	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		35.72	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	1758.72	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.546
   Length of year:		1125.49	days
   Length of day:		9.75	hours


Planet 5	
   Distance from primary:	3.089	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		3410.1	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.023	Earth atmospheres
   Surface temperature:		-120.06	degrees Celcius
   Normal daytime temperature:	-107.99	degrees Celcius
   Normal night temperature:	-132.33	degrees Celcius
   Maximum temperature:   	-84.95	degrees Celcius
   Minimum temperature:   	-156.64	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.05 and above
   Surface acceleration:	504.89	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.501
   Length of year:		1893.46	days
   Length of day:		21.34	hours
   Boiling point of water:	19.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	59.39
   gasses in atmosphere:
				Argon             5.1%  PP    1.2 mb
				Krypton          94.9%  PP   22.3 mb


Planet 6	
   Distance from primary:	4.079	AU
   Mass:			0.233	Earth masses
   Equatorial radius:		3969.0	km
   Density:			5.316	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.046	Earth atmospheres
   Surface temperature:		-133.94	degrees Celcius
   Normal daytime temperature:	-125.03	degrees Celcius
   Normal night temperature:	-143.08	degrees Celcius
   Maximum temperature:   	-103.53	degrees Celcius
   Minimum temperature:   	-166.08	degrees Celcius
   Escape Velocity:		6.84	km/sec
   Molecular weight retained:	16.96 and above
   Surface acceleration:	589.70	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.475
   Length of year:		2872.12	days
   Length of day:		19.74	hours
   Boiling point of water:	30.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	54.23
   gasses in atmosphere:
				Fluorine          0.1%  PP    0.0 mb
				Argon             5.7%  PP    2.6 mb
				Neon             11.0%  PP    5.1 mb
				Krypton          83.2%  PP   38.2 mb


Planet 7	*gas giant*
   Distance from primary:	5.399	AU
   Mass:			848.371	Earth masses
   Equatorial radius:		85531.1	km
   Density:			1.935	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		88.94	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4624.63	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.504
   Length of year:		4369.89	days
   Length of day:		6.01	hours


Planet 8	*gas giant*
   Distance from primary:	8.527	AU
   Mass:			4.604	Earth masses
   Equatorial radius:		19404.7	km
   Density:			0.899	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		13.76	km/sec
   Molecular weight retained:	4.19 and above
   Surface acceleration:	487.60	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.469
   Length of year:		8682.78	days
   Length of day:		18.51	hours


Planet 9	*gas giant*
   Distance from primary:	15.345	AU
   Mass:			371.603	Earth masses
   Equatorial radius:		73343.4	km
   Density:			1.344	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		63.57	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2754.84	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.536
   Length of year:		20949.48	days
   Length of day:		7.79	hours


Planet 10	*gas giant*
   Distance from primary:	23.681	AU
   Mass:			16.416	Earth masses
   Equatorial radius:		30613.2	km
   Density:			0.816	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		20.68	km/sec
   Molecular weight retained:	1.86 and above
   Surface acceleration:	698.53	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.513
   Length of year:		40183.32	days
   Length of day:		15.46	hours


Planet 11	*gas giant*
   Distance from primary:	48.558	AU
   Mass:			1.159	Earth masses
   Equatorial radius:		15002.4	km
   Density:			0.490	grams/cc
   Eccentricity of orbit:	0.373
   Escape Velocity:		7.85	km/sec
   Molecular weight retained:	12.88 and above
   Surface acceleration:	205.39	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.529
   Length of year:		117985.62	days
   Length of day:		28.52	hours


