                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047fb4
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6126 K
Stellar class: F9
Age: 1.774 billion years  (5.296 billion left on main sequence)
Habitable ecosphere radius: 1.244 AU

Planets present at:
1	  0.419 AU	no atmosphere
2	  0.601 AU	no atmosphere
3	  0.725 AU	greenhouse
4	  1.230 AU	no atmosphere
5	  1.512 AU	gas giant
6	  2.330 AU	cold
7	  3.546 AU	gas giant
8	  5.005 AU	gas giant
9	  7.065 AU	gas giant
10	 11.692 AU	gas giant
11	 22.578 AU	gas giant
12	 31.162 AU	gas giant
13	 47.224 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.419	AU
   Mass:			0.196	Earth masses
   Equatorial radius:		3750.1	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.214
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		197.09	degrees Celcius
   Normal daytime temperature:	401.70	degrees Celcius
   Normal night temperature:	-185.42	degrees Celcius
   Maximum temperature:   	405.63	degrees Celcius
   Minimum temperature:   	-198.33	degrees Celcius
   Escape Velocity:		6.46	km/sec
   Molecular weight retained:	19.02 and above
   Surface acceleration:	556.38	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.083
   Length of year:		94.69	days
   Length of day:		1471.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.601	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		2666.9	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		119.02	degrees Celcius
   Maximum temperature:   	309.68	degrees Celcius
   Minimum temperature:   	-222.13	degrees Celcius
   Escape Velocity:		4.58	km/sec
   Molecular weight retained:	37.84 and above
   Surface acceleration:	393.35	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.087
   Length of year:		162.71	days
   Length of day:		3905.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.725	AU
   Mass:			0.909	Earth masses
   Equatorial radius:		6207.0	km
   Density:			5.421	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.96	Earth gees
   Surface pressure:		69.096	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		386.06	degrees Celcius
   Maximum temperature:   	391.36	degrees Celcius
   Minimum temperature:   	379.14	degrees Celcius
   Escape Velocity:		10.81	km/sec
   Molecular weight retained:	6.80 and above
   Surface acceleration:	940.46	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.578
   Length of year:		215.64	days
   Length of day:		19.04	hours
   Boiling point of water:	269.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1109
				Cesium       melts at 28    boils at 1150
				Gallium      melts at 30    boils at 3621
				Rubidium     melts at 39    boils at 1125
				Potassium    melts at 63    boils at 1238
				Sodium       melts at 98    boils at 1407
				Sulfur       melts at 113   boils at 772
				Indium       melts at 157   boils at 3151
				Lithium      melts at 181   boils at 2084
				Selenium     melts at 217   boils at 1121
				Tin          melts at 232   boils at 3941
				Polonium     melts at 254   boils at 1524
				Bismuth      melts at 271   boils at 2400
				Thallium     melts at 304   boils at 2244
				Cadmium      melts at 321   boils at 1237
				Lead         melts at 328   boils at 2672
   gasses in atmosphere:
				Nitrogen         99.2%  PP 68508.6 mb
				Phosphorus        0.6%  PP  383.3 mb
				CarbonDioxide     0.1%  PP   41.4 mb
				Ozone             0.1%  PP   39.8 mb
				Ethanol           0.1%  PP   41.9 mb


Planet 4	
   Distance from primary:	1.230	AU
   Mass:			0.233	Earth masses
   Equatorial radius:		3971.0	km
   Density:			5.316	grams/cc
   Eccentricity of orbit:	0.179
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.040	Earth atmospheres
   Surface temperature:		8.45	degrees Celcius
   Normal daytime temperature:	27.44	degrees Celcius
   Normal night temperature:	-11.05	degrees Celcius
   Maximum temperature:   	59.73	degrees Celcius
   Minimum temperature:   	-44.54	degrees Celcius
   Escape Velocity:		6.85	km/sec
   Molecular weight retained:	16.94 and above
   Surface acceleration:	590.01	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.182
   Length of year:		476.11	days
   Length of day:		20.20	hours
   Boiling point of water:	28.3	degrees Celcius
   Hydrosphere percentage:	31.26
   Cloud cover percentage:	14.59
   Ice cover percentage:	3.45
   liquids at surface:
				Ethanol      melts at -114  boils at 11
				Mercury      melts at -39   boils at 236
				Water        melts at 0     boils at 29
   gasses in atmosphere:
				CarbonDioxide    38.3%  PP   15.2 mb
				Ammonia           0.2%  PP    0.1 mb
				Ozone            40.6%  PP   16.1 mb
				Chlorine         17.5%  PP    7.0 mb
				Fluorine          0.5%  PP    0.2 mb
				Neon              0.3%  PP    0.1 mb
				Krypton           2.3%  PP    0.9 mb
				Xenon             0.3%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.512	AU
   Mass:			6.468	Earth masses
   Equatorial radius:		18561.0	km
   Density:			1.443	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		16.67	km/sec
   Molecular weight retained:	2.86 and above
   Surface acceleration:	748.74	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.536
   Length of year:		648.90	days
   Length of day:		14.94	hours


Planet 6	
   Distance from primary:	2.330	AU
   Mass:			0.821	Earth masses
   Equatorial radius:		6005.0	km
   Density:			5.410	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.518	Earth atmospheres
   Surface temperature:		-84.72	degrees Celcius
   Normal daytime temperature:	-80.71	degrees Celcius
   Normal night temperature:	-88.95	degrees Celcius
   Maximum temperature:   	-60.07	degrees Celcius
   Minimum temperature:   	-111.13	degrees Celcius
   Escape Velocity:		10.44	km/sec
   Molecular weight retained:	7.28 and above
   Surface acceleration:	907.90	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.544
   Length of year:		1242.04	days
   Length of day:		15.91	hours
   Boiling point of water:	82.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	75.89
   liquids at surface:
				Ethanol      melts at -114  boils at 62
				Chlorine     melts at -101  boils at -45
   gasses in atmosphere:
				Oxygen           39.4%  PP  204.2 mb
				Nitrogen         60.5%  PP  313.7 mb


Planet 7	*gas giant*
   Distance from primary:	3.546	AU
   Mass:			41.982	Earth masses
   Equatorial radius:		34385.5	km
   Density:			1.473	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		31.21	km/sec
   Molecular weight retained:	0.82 and above
   Surface acceleration:	1415.95	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.470
   Length of year:		2331.77	days
   Length of day:		10.86	hours


Planet 8	*gas giant*
   Distance from primary:	5.005	AU
   Mass:			1.317	Earth masses
   Equatorial radius:		12891.0	km
   Density:			0.877	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		9.03	km/sec
   Molecular weight retained:	9.75 and above
   Surface acceleration:	315.94	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.505
   Length of year:		3909.29	days
   Length of day:		22.99	hours


Planet 9	*gas giant*
   Distance from primary:	7.065	AU
   Mass:			821.310	Earth masses
   Equatorial radius:		86694.4	km
   Density:			1.799	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		86.92	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4357.77	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.546
   Length of year:		6549.42	days
   Length of day:		6.19	hours


Planet 10	*gas giant*
   Distance from primary:	11.692	AU
   Mass:			106.247	Earth masses
   Equatorial radius:		49793.2	km
   Density:			1.228	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		41.25	km/sec
   Molecular weight retained:	0.47 and above
   Surface acceleration:	1708.90	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.484
   Length of year:		13958.87	days
   Length of day:		9.89	hours


Planet 11	*gas giant*
   Distance from primary:	22.578	AU
   Mass:			2.534	Earth masses
   Equatorial radius:		17690.5	km
   Density:			0.653	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		10.69	km/sec
   Molecular weight retained:	6.95 and above
   Surface acceleration:	322.87	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.549
   Length of year:		37462.23	days
   Length of day:		22.75	hours


Planet 12	*gas giant*
   Distance from primary:	31.162	AU
   Mass:			0.600	Earth masses
   Equatorial radius:		11935.7	km
   Density:			0.503	grams/cc
   Eccentricity of orbit:	0.118
   Escape Velocity:		6.33	km/sec
   Molecular weight retained:	19.81 and above
   Surface acceleration:	167.84	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.453
   Length of year:		60742.98	days
   Length of day:		31.55	hours


Planet 13	*gas giant*
   Distance from primary:	47.224	AU
   Mass:			0.948	Earth masses
   Equatorial radius:		14122.1	km
   Density:			0.480	grams/cc
   Eccentricity of orbit:	0.160
   Escape Velocity:		7.32	km/sec
   Molecular weight retained:	14.83 and above
   Surface acceleration:	189.53	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.549
   Length of year:		113318.84	days
   Length of day:		29.69	hours


