                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504885a
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6130 K
Stellar class: F9
Age: 2.945 billion years  (3.835 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.457 AU	no atmosphere
2	  0.762 AU	greenhouse
3	  1.248 AU	no atmosphere
4	  1.481 AU	cold
5	  1.957 AU	cold
6	  2.474 AU	gas giant
7	  5.220 AU	gas giant
8	 10.187 AU	gas giant
9	 23.752 AU	gas giant
10	 40.971 AU	gas giant
11	 50.222 AU	no atmosphere



Planet 1	
   Distance from primary:	0.457	AU
   Mass:			0.412	Earth masses
   Equatorial radius:		4790.4	km
   Density:			5.349	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		185.57	degrees Celcius
   Maximum temperature:   	392.11	degrees Celcius
   Minimum temperature:   	-209.43	degrees Celcius
   Escape Velocity:		8.28	km/sec
   Molecular weight retained:	11.57 and above
   Surface acceleration:	716.13	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.064
   Length of year:		107.23	days
   Length of day:		2573.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.762	AU
   Mass:			0.772	Earth masses
   Equatorial radius:		5885.0	km
   Density:			5.403	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.91	Earth gees
   Surface pressure:		48.009	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		290.85	degrees Celcius
   Maximum temperature:   	297.05	degrees Celcius
   Minimum temperature:   	283.58	degrees Celcius
   Escape Velocity:		10.23	km/sec
   Molecular weight retained:	7.59 and above
   Surface acceleration:	888.65	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.433
   Length of year:		231.08	days
   Length of day:		21.67	hours
   Boiling point of water:	249.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 609
				Francium     melts at 27    boils at 1057
				Cesium       melts at 28    boils at 1096
				Gallium      melts at 30    boils at 3474
				Rubidium     melts at 39    boils at 1073
				Potassium    melts at 63    boils at 1181
				Sodium       melts at 98    boils at 1344
				Sulfur       melts at 113   boils at 732
				Indium       melts at 157   boils at 3022
				Lithium      melts at 181   boils at 1996
				Selenium     melts at 217   boils at 1068
				Tin          melts at 232   boils at 3782
				Polonium     melts at 254   boils at 1456
				Bismuth      melts at 271   boils at 2299
   gasses in atmosphere:
				Nitrogen         99.0%  PP 47535.6 mb
				Phosphorus        0.6%  PP  310.7 mb
				CarbonDioxide     0.1%  PP   34.8 mb
				Ozone             0.1%  PP   33.4 mb
				Ethanol           0.1%  PP   35.4 mb


Planet 3	
   Distance from primary:	1.248	AU
   Mass:			0.046	Earth masses
   Equatorial radius:		2313.4	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		3.67	degrees Celcius
   Normal daytime temperature:	39.67	degrees Celcius
   Normal night temperature:	-32.63	degrees Celcius
   Maximum temperature:   	68.33	degrees Celcius
   Minimum temperature:   	-61.68	degrees Celcius
   Escape Velocity:		3.97	km/sec
   Molecular weight retained:	50.36 and above
   Surface acceleration:	340.71	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.075
   Length of year:		483.88	days
   Length of day:		30.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 4	
   Distance from primary:	1.481	AU
   Mass:			0.464	Earth masses
   Equatorial radius:		4980.2	km
   Density:			5.358	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.212	Earth atmospheres
   Surface temperature:		-45.11	degrees Celcius
   Normal daytime temperature:	-37.21	degrees Celcius
   Normal night temperature:	-53.39	degrees Celcius
   Maximum temperature:   	-12.41	degrees Celcius
   Minimum temperature:   	-79.65	degrees Celcius
   Escape Velocity:		8.62	km/sec
   Molecular weight retained:	10.69 and above
   Surface acceleration:	745.68	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.565
   Length of year:		626.12	days
   Length of day:		17.68	hours
   Boiling point of water:	61.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.55
   Ice cover percentage:	79.95
   liquids at surface:
				Ethanol      melts at -114  boils at 42
   gasses in atmosphere:
				Oxygen           30.2%  PP   64.1 mb
				Nitrogen         69.6%  PP  147.5 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	
   Distance from primary:	1.957	AU
   Mass:			0.611	Earth masses
   Equatorial radius:		5451.7	km
   Density:			5.380	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.299	Earth atmospheres
   Surface temperature:		-70.02	degrees Celcius
   Normal daytime temperature:	-64.21	degrees Celcius
   Normal night temperature:	-76.11	degrees Celcius
   Maximum temperature:   	-40.52	degrees Celcius
   Minimum temperature:   	-101.42	degrees Celcius
   Escape Velocity:		9.45	km/sec
   Molecular weight retained:	8.88 and above
   Surface acceleration:	819.74	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.564
   Length of year:		950.86	days
   Length of day:		16.76	hours
   Boiling point of water:	69.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.09
   Ice cover percentage:	71.30
   liquids at surface:
				Ethanol      melts at -114  boils at 50
				Chlorine     melts at -101  boils at -54
				Ammonia      melts at -78   boils at -53
   gasses in atmosphere:
				Oxygen           21.6%  PP   64.5 mb
				Nitrogen         78.2%  PP  233.6 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 6	*gas giant*
   Distance from primary:	2.474	AU
   Mass:			153.782	Earth masses
   Equatorial radius:		48622.9	km
   Density:			1.909	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		50.22	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2593.95	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.547
   Length of year:		1350.97	days
   Length of day:		8.02	hours


Planet 7	*gas giant*
   Distance from primary:	5.220	AU
   Mass:			920.807	Earth masses
   Equatorial radius:		87209.6	km
   Density:			1.981	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		91.77	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4828.13	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.540
   Length of year:		4136.01	days
   Length of day:		5.88	hours


Planet 8	*gas giant*
   Distance from primary:	10.187	AU
   Mass:			339.287	Earth masses
   Equatorial radius:		68912.2	km
   Density:			1.479	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		62.66	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2849.14	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.486
   Length of year:		11285.12	days
   Length of day:		7.66	hours


Planet 9	*gas giant*
   Distance from primary:	23.752	AU
   Mass:			54.484	Earth masses
   Equatorial radius:		43377.6	km
   Density:			0.953	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		31.65	km/sec
   Molecular weight retained:	0.79 and above
   Surface acceleration:	1154.72	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.461
   Length of year:		40196.32	days
   Length of day:		12.03	hours


Planet 10	*gas giant*
   Distance from primary:	40.971	AU
   Mass:			1.539	Earth masses
   Equatorial radius:		16039.3	km
   Density:			0.532	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		8.75	km/sec
   Molecular weight retained:	10.37 and above
   Surface acceleration:	238.55	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.503
   Length of year:		91069.40	days
   Length of day:		26.46	hours


Planet 11	
   Distance from primary:	50.222	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2722.6	km
   Density:			2.197	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.14	degrees Celcius
   Normal daytime temperature:	-223.43	degrees Celcius
   Normal night temperature:	-236.70	degrees Celcius
   Maximum temperature:   	-212.38	degrees Celcius
   Minimum temperature:   	-248.03	degrees Celcius
   Escape Velocity:		3.02	km/sec
   Molecular weight retained:	87.20 and above
   Surface acceleration:	167.18	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.137
   Length of year:		123596.64	days
   Length of day:		37.07	hours
   Boiling point of water:	-82.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


