                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a15
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6370 K
Stellar class: F7
Age: 2.311 billion years  (4.413 billion left on main sequence)
Habitable ecosphere radius: 1.284 AU

Planets present at:
1	  0.445 AU	no atmosphere
2	  0.814 AU	greenhouse
3	  1.385 AU	high pressure
4	  2.055 AU	cold
5	  2.700 AU	gas giant
6	  4.156 AU	gas giant
7	  7.988 AU	gas giant
8	 16.244 AU	gas giant
9	 24.593 AU	gas giant
10	 40.393 AU	gas giant
11	 48.982 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.445	AU
   Mass:			0.384	Earth masses
   Equatorial radius:		4680.8	km
   Density:			5.344	grams/cc
   Eccentricity of orbit:	0.220
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		193.57	degrees Celcius
   Normal daytime temperature:	397.62	degrees Celcius
   Normal night temperature:	-188.11	degrees Celcius
   Maximum temperature:   	401.45	degrees Celcius
   Minimum temperature:   	-200.57	degrees Celcius
   Escape Velocity:		8.09	km/sec
   Molecular weight retained:	12.13 and above
   Surface acceleration:	699.12	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.057
   Length of year:		103.07	days
   Length of day:		1581.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.814	AU
   Mass:			1.304	Earth masses
   Equatorial radius:		6980.5	km
   Density:			5.470	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		1.09	Earth gees
   Surface pressure:		183.079	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		531.75	degrees Celcius
   Maximum temperature:   	534.61	degrees Celcius
   Minimum temperature:   	526.04	degrees Celcius
   Escape Velocity:		12.21	km/sec
   Molecular weight retained:	5.33 and above
   Surface acceleration:	1067.09	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.514
   Length of year:		254.58	days
   Length of day:		16.11	hours
   Boiling point of water:	333.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1271
				Cesium       melts at 28    boils at 1317
				Gallium      melts at 30    boils at 4076
				Rubidium     melts at 39    boils at 1289
				Potassium    melts at 63    boils at 1415
				Sodium       melts at 98    boils at 1604
				Indium       melts at 157   boils at 3551
				Lithium      melts at 181   boils at 2360
				Selenium     melts at 217   boils at 1284
				Tin          melts at 232   boils at 4434
				Polonium     melts at 254   boils at 1734
				Bismuth      melts at 271   boils at 2713
				Thallium     melts at 304   boils at 2539
				Cadmium      melts at 321   boils at 1414
				Lead         melts at 328   boils at 3017
				Zinc         melts at 420   boils at 1645
				Tellurium    melts at 450   boils at 1780
   gasses in atmosphere:
				Sulfur           19.8%  PP 36276.1 mb
				Nitrogen         79.6%  PP 145705.6 mb
				Phosphorus        0.4%  PP  724.1 mb


Planet 3	
   Distance from primary:	1.385	AU
   Mass:			1.488	Earth masses
   Equatorial radius:		7284.7	km
   Density:			5.491	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		1.14	Earth gees
   Surface pressure:		2.137	Earth atmospheres
   Surface temperature:		14.05	degrees Celcius
   Normal daytime temperature:	16.87	degrees Celcius
   Normal night temperature:	11.05	degrees Celcius
   Maximum temperature:   	33.04	degrees Celcius
   Minimum temperature:   	-6.01	degrees Celcius
   Escape Velocity:		12.76	km/sec
   Molecular weight retained:	4.87 and above
   Surface acceleration:	1117.84	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.322
   Length of year:		565.13	days
   Length of day:		14.38	hours
   Boiling point of water:	122.2	degrees Celcius
   Hydrosphere percentage:	78.23
   Cloud cover percentage:	50.34
   Ice cover percentage:	2.03
   liquids at surface:
				Ethanol      melts at -114  boils at 99
				Mercury      melts at -39   boils at 394
				Bromine      melts at -7    boils at 79
				Water        melts at 0     boils at 122
   gasses in atmosphere:
				Oxygen            9.2%  PP  196.1 mb
				Nitrogen         90.7%  PP 1937.2 mb


Planet 4	
   Distance from primary:	2.055	AU
   Mass:			0.566	Earth masses
   Equatorial radius:		5316.7	km
   Density:			5.374	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.322	Earth atmospheres
   Surface temperature:		-87.28	degrees Celcius
   Normal daytime temperature:	-82.08	degrees Celcius
   Normal night temperature:	-92.74	degrees Celcius
   Maximum temperature:   	-61.10	degrees Celcius
   Minimum temperature:   	-115.25	degrees Celcius
   Escape Velocity:		9.21	km/sec
   Molecular weight retained:	9.35 and above
   Surface acceleration:	798.45	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.669
   Length of year:		1021.78	days
   Length of day:		16.97	hours
   Boiling point of water:	71.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	87.21
   liquids at surface:
				Ethanol      melts at -114  boils at 51
				Chlorine     melts at -101  boils at -52
   gasses in atmosphere:
				Oxygen           36.1%  PP  116.3 mb
				Nitrogen         63.8%  PP  205.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.700	AU
   Mass:			150.828	Earth masses
   Equatorial radius:		48681.3	km
   Density:			1.865	grams/cc
   Eccentricity of orbit:	0.019
   Escape Velocity:		49.71	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2538.04	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.460
   Length of year:		1538.80	days
   Length of day:		8.11	hours


Planet 6	*gas giant*
   Distance from primary:	4.156	AU
   Mass:			22.828	Earth masses
   Equatorial radius:		29093.8	km
   Density:			1.323	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		25.02	km/sec
   Molecular weight retained:	1.27 and above
   Surface acceleration:	1075.48	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.541
   Length of year:		2939.31	days
   Length of day:		12.46	hours


Planet 7	*gas giant*
   Distance from primary:	7.988	AU
   Mass:			282.563	Earth masses
   Equatorial radius:		63993.0	km
   Density:			1.539	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		59.34	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2751.62	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.463
   Length of year:		7828.20	days
   Length of day:		7.79	hours


Planet 8	*gas giant*
   Distance from primary:	16.244	AU
   Mass:			70.936	Earth masses
   Equatorial radius:		45367.9	km
   Density:			1.084	grams/cc
   Eccentricity of orbit:	0.177
   Escape Velocity:		35.31	km/sec
   Molecular weight retained:	0.64 and above
   Surface acceleration:	1374.38	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.526
   Length of year:		22708.77	days
   Length of day:		11.02	hours


Planet 9	*gas giant*
   Distance from primary:	24.593	AU
   Mass:			19.853	Earth masses
   Equatorial radius:		32393.5	km
   Density:			0.833	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		22.11	km/sec
   Molecular weight retained:	1.62 and above
   Surface acceleration:	754.50	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.530
   Length of year:		42304.99	days
   Length of day:		14.88	hours


Planet 10	*gas giant*
   Distance from primary:	40.393	AU
   Mass:			1.321	Earth masses
   Equatorial radius:		15315.5	km
   Density:			0.525	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		8.29	km/sec
   Molecular weight retained:	11.54 and above
   Surface acceleration:	224.56	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.549
   Length of year:		89052.64	days
   Length of day:		27.27	hours


Planet 11	
   Distance from primary:	48.982	AU
   Mass:			0.052	Earth masses
   Equatorial radius:		3222.7	km
   Density:			2.202	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.84	degrees Celcius
   Normal daytime temperature:	-223.56	degrees Celcius
   Normal night temperature:	-235.99	degrees Celcius
   Maximum temperature:   	-208.96	degrees Celcius
   Minimum temperature:   	-250.59	degrees Celcius
   Escape Velocity:		3.58	km/sec
   Molecular weight retained:	62.11 and above
   Surface acceleration:	198.31	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.165
   Length of year:		118916.17	days
   Length of day:		34.03	hours
   Boiling point of water:	-74.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


