                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504807c
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6353 K
Stellar class: F7
Age: 3.600 billion years  (3.443 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.367 AU	no atmosphere
2	  0.815 AU	greenhouse
3	  1.813 AU	gas giant
4	  3.368 AU	gas giant
5	  4.174 AU	gas giant
6	  6.313 AU	gas giant
7	 13.269 AU	gas giant
8	 24.029 AU	gas giant
9	 37.452 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.367	AU
   Mass:			0.298	Earth masses
   Equatorial radius:		4304.5	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.205
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		228.73	degrees Celcius
   Normal daytime temperature:	439.83	degrees Celcius
   Normal night temperature:	-173.78	degrees Celcius
   Maximum temperature:   	443.85	degrees Celcius
   Minimum temperature:   	-187.77	degrees Celcius
   Escape Velocity:		7.43	km/sec
   Molecular weight retained:	14.38 and above
   Surface acceleration:	641.07	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.090
   Length of year:		77.69	days
   Length of day:		1231.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.815	AU
   Mass:			1.786	Earth masses
   Equatorial radius:		7727.0	km
   Density:			5.523	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		1.22	Earth gees
   Surface pressure:		260.716	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		517.77	degrees Celcius
   Maximum temperature:   	520.33	degrees Celcius
   Minimum temperature:   	512.56	degrees Celcius
   Escape Velocity:		13.58	km/sec
   Molecular weight retained:	4.31 and above
   Surface acceleration:	1192.68	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.617
   Length of year:		256.70	days
   Length of day:		15.48	hours
   Boiling point of water:	360.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1339
				Cesium       melts at 28    boils at 1387
				Gallium      melts at 30    boils at 4269
				Rubidium     melts at 39    boils at 1358
				Potassium    melts at 63    boils at 1490
				Sodium       melts at 98    boils at 1687
				Indium       melts at 157   boils at 3721
				Lithium      melts at 181   boils at 2477
				Selenium     melts at 217   boils at 1353
				Tin          melts at 232   boils at 4643
				Polonium     melts at 254   boils at 1823
				Bismuth      melts at 271   boils at 2845
				Thallium     melts at 304   boils at 2663
				Cadmium      melts at 321   boils at 1489
				Lead         melts at 328   boils at 3162
				Zinc         melts at 420   boils at 1730
				Tellurium    melts at 450   boils at 1871
   gasses in atmosphere:
				Sulfur           19.4%  PP 50568.5 mb
				Nitrogen         80.0%  PP 208647.3 mb
				Phosphorus        0.4%  PP 1009.3 mb


Planet 3	*gas giant*
   Distance from primary:	1.813	AU
   Mass:			19.001	Earth masses
   Equatorial radius:		25797.8	km
   Density:			1.579	grams/cc
   Eccentricity of orbit:	0.120
   Escape Velocity:		24.24	km/sec
   Molecular weight retained:	1.35 and above
   Surface acceleration:	1138.55	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.464
   Length of year:		851.66	days
   Length of day:		12.11	hours


Planet 4	*gas giant*
   Distance from primary:	3.368	AU
   Mass:			3.168	Earth masses
   Equatorial radius:		16110.5	km
   Density:			1.081	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		12.52	km/sec
   Molecular weight retained:	5.06 and above
   Surface acceleration:	486.82	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.504
   Length of year:		2157.15	days
   Length of day:		18.52	hours


Planet 5	*gas giant*
   Distance from primary:	4.174	AU
   Mass:			8.048	Earth masses
   Equatorial radius:		21525.3	km
   Density:			1.151	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		17.27	km/sec
   Molecular weight retained:	2.66 and above
   Surface acceleration:	692.64	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.526
   Length of year:		2976.38	days
   Length of day:		15.53	hours


Planet 6	*gas giant*
   Distance from primary:	6.313	AU
   Mass:			481.237	Earth masses
   Equatorial radius:		73472.5	km
   Density:			1.731	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		72.28	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3555.07	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.511
   Length of year:		5532.85	days
   Length of day:		6.85	hours


Planet 7	*gas giant*
   Distance from primary:	13.269	AU
   Mass:			509.862	Earth masses
   Equatorial radius:		79492.4	km
   Density:			1.448	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		71.52	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3217.66	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.517
   Length of year:		16857.86	days
   Length of day:		7.21	hours


Planet 8	*gas giant*
   Distance from primary:	24.029	AU
   Mass:			25.066	Earth masses
   Equatorial radius:		34690.3	km
   Density:			0.857	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		24.01	km/sec
   Molecular weight retained:	1.38 and above
   Surface acceleration:	830.62	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.541
   Length of year:		41108.87	days
   Length of day:		14.18	hours


Planet 9	*gas giant*
   Distance from primary:	37.452	AU
   Mass:			1.290	Earth masses
   Equatorial radius:		15152.3	km
   Density:			0.529	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		8.24	km/sec
   Molecular weight retained:	11.69 and above
   Surface acceleration:	224.10	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.479
   Length of year:		79993.84	days
   Length of day:		27.30	hours


