                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ede
Stellar mass: 1.09 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6165 K
Stellar class: F8
Age: 5.956 billion years  (1.143 billion left on main sequence)
Habitable ecosphere radius: 1.241 AU

Planets present at:
1	  0.381 AU	no atmosphere
2	  0.514 AU	no atmosphere
3	  0.721 AU	no atmosphere
4	  1.064 AU	greenhouse
5	  1.186 AU	no atmosphere
6	  1.788 AU	cold
7	  3.876 AU	gas giant
8	  9.930 AU	gas giant
9	 22.387 AU	gas giant
10	 46.297 AU	gas giant



Planet 1	
   Distance from primary:	0.381	AU
   Mass:			0.198	Earth masses
   Equatorial radius:		3764.2	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		219.70	degrees Celcius
   Maximum temperature:   	433.48	degrees Celcius
   Minimum temperature:   	-199.50	degrees Celcius
   Escape Velocity:		6.48	km/sec
   Molecular weight retained:	18.88 and above
   Surface acceleration:	558.53	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.081
   Length of year:		82.14	days
   Length of day:		1971.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.514	AU
   Mass:			0.277	Earth masses
   Equatorial radius:		4202.1	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		153.12	degrees Celcius
   Maximum temperature:   	352.22	degrees Celcius
   Minimum temperature:   	-216.23	degrees Celcius
   Escape Velocity:		7.25	km/sec
   Molecular weight retained:	15.10 and above
   Surface acceleration:	625.36	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.063
   Length of year:		128.77	days
   Length of day:		3090.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.721	AU
   Mass:			0.172	Earth masses
   Equatorial radius:		3589.9	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		85.23	degrees Celcius
   Maximum temperature:   	267.43	degrees Celcius
   Minimum temperature:   	-226.61	degrees Celcius
   Escape Velocity:		6.18	km/sec
   Molecular weight retained:	20.78 and above
   Surface acceleration:	532.07	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.080
   Length of year:		213.87	days
   Length of day:		4146.46	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.064	AU
   Mass:			1.540	Earth masses
   Equatorial radius:		7366.7	km
   Density:			5.496	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		1.15	Earth gees
   Surface pressure:		208.328	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		464.17	degrees Celcius
   Maximum temperature:   	467.00	degrees Celcius
   Minimum temperature:   	459.27	degrees Celcius
   Escape Velocity:		12.91	km/sec
   Molecular weight retained:	4.76 and above
   Surface acceleration:	1131.62	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.423
   Length of year:		383.63	days
   Length of day:		14.82	hours
   Boiling point of water:	342.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1295
				Cesium       melts at 28    boils at 1342
				Gallium      melts at 30    boils at 4145
				Rubidium     melts at 39    boils at 1313
				Potassium    melts at 63    boils at 1442
				Sodium       melts at 98    boils at 1633
				Indium       melts at 157   boils at 3612
				Lithium      melts at 181   boils at 2402
				Selenium     melts at 217   boils at 1309
				Tin          melts at 232   boils at 4508
				Polonium     melts at 254   boils at 1766
				Bismuth      melts at 271   boils at 2760
				Thallium     melts at 304   boils at 2583
				Cadmium      melts at 321   boils at 1441
				Lead         melts at 328   boils at 3069
				Zinc         melts at 420   boils at 1675
				Tellurium    melts at 450   boils at 1812
   gasses in atmosphere:
				Sulfur           20.8%  PP 43418.0 mb
				Nitrogen         78.6%  PP 163642.0 mb
				Phosphorus        0.4%  PP  864.3 mb


Planet 5	
   Distance from primary:	1.186	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		4009.3	km
   Density:			5.318	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.054	Earth atmospheres
   Surface temperature:		13.49	degrees Celcius
   Normal daytime temperature:	32.52	degrees Celcius
   Normal night temperature:	-6.21	degrees Celcius
   Maximum temperature:   	59.54	degrees Celcius
   Minimum temperature:   	-34.14	degrees Celcius
   Escape Velocity:		6.91	km/sec
   Molecular weight retained:	16.61 and above
   Surface acceleration:	595.86	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.192
   Length of year:		451.37	days
   Length of day:		21.68	hours
   Boiling point of water:	34.0	degrees Celcius
   Hydrosphere percentage:	40.69
   Cloud cover percentage:	24.10
   Ice cover percentage:	2.34
   liquids at surface:
				Ethanol      melts at -114  boils at 17
				Mercury      melts at -39   boils at 246
				Water        melts at 0     boils at 34
   gasses in atmosphere:
				CarbonDioxide    45.6%  PP   24.8 mb
				Ammonia           1.2%  PP    0.6 mb
				Ozone            49.1%  PP   26.7 mb
				Chlorine          0.1%  PP    0.0 mb
				Argon             0.2%  PP    0.1 mb
				Neon              0.3%  PP    0.2 mb
				Krypton           3.1%  PP    1.7 mb
				Xenon             0.4%  PP    0.2 mb


Planet 6	
   Distance from primary:	1.788	AU
   Mass:			1.111	Earth masses
   Equatorial radius:		6627.0	km
   Density:			5.447	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		1.03	Earth gees
   Surface pressure:		1.257	Earth atmospheres
   Surface temperature:		-65.11	degrees Celcius
   Normal daytime temperature:	-62.32	degrees Celcius
   Normal night temperature:	-68.05	degrees Celcius
   Maximum temperature:   	-44.63	degrees Celcius
   Minimum temperature:   	-86.98	degrees Celcius
   Escape Velocity:		11.56	km/sec
   Molecular weight retained:	5.94 and above
   Surface acceleration:	1008.80	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.640
   Length of year:		835.43	days
   Length of day:		15.12	hours
   Boiling point of water:	106.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.18
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 85
				Chlorine     melts at -101  boils at -30
				Ammonia      melts at -78   boils at -29
				Radon        melts at -71   boils at -59
   gasses in atmosphere:
				Nitrogen         99.8%  PP 1254.7 mb
				CarbonDioxide     0.1%  PP    0.7 mb
				Ozone             0.1%  PP    0.7 mb


Planet 7	*gas giant*
   Distance from primary:	3.876	AU
   Mass:			1271.375	Earth masses
   Equatorial radius:		93693.2	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.203
   Escape Velocity:		104.03	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5775.59	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.535
   Length of year:		2661.51	days
   Length of day:		5.38	hours


Planet 8	*gas giant*
   Distance from primary:	9.930	AU
   Mass:			235.677	Earth masses
   Equatorial radius:		61982.2	km
   Density:			1.412	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		55.07	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2446.37	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.458
   Length of year:		10928.89	days
   Length of day:		8.26	hours


Planet 9	*gas giant*
   Distance from primary:	22.387	AU
   Mass:			74.228	Earth masses
   Equatorial radius:		47352.5	km
   Density:			0.998	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		35.36	km/sec
   Molecular weight retained:	0.63 and above
   Surface acceleration:	1320.14	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.545
   Length of year:		37002.06	days
   Length of day:		11.25	hours


Planet 10	*gas giant*
   Distance from primary:	46.297	AU
   Mass:			0.617	Earth masses
   Equatorial radius:		12439.3	km
   Density:			0.457	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		6.29	km/sec
   Molecular weight retained:	20.08 and above
   Surface acceleration:	158.89	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.498
   Length of year:		110058.91	days
   Length of day:		32.42	hours


