                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048222
Stellar mass: 1.10 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6202 K
Stellar class: F8
Age: 4.401 billion years  (2.586 billion left on main sequence)
Habitable ecosphere radius: 1.253 AU

Planets present at:
1	  0.332 AU	no atmosphere
2	  0.448 AU	no atmosphere
3	  0.792 AU	greenhouse
4	  1.144 AU	greenhouse
5	  2.579 AU	gas giant
6	  4.086 AU	gas giant
7	  6.380 AU	gas giant
8	 15.215 AU	gas giant
9	 32.028 AU	gas giant
10	 49.453 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.332	AU
   Mass:			0.062	Earth masses
   Equatorial radius:		2556.6	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		257.37	degrees Celcius
   Normal daytime temperature:	475.05	degrees Celcius
   Normal night temperature:	-170.44	degrees Celcius
   Maximum temperature:   	478.59	degrees Celcius
   Minimum temperature:   	-183.08	degrees Celcius
   Escape Velocity:		4.39	km/sec
   Molecular weight retained:	41.19 and above
   Surface acceleration:	376.89	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.084
   Length of year:		66.55	days
   Length of day:		1289.52	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.448	AU
   Mass:			0.257	Earth masses
   Equatorial radius:		4098.6	km
   Density:			5.321	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		185.08	degrees Celcius
   Maximum temperature:   	391.41	degrees Celcius
   Minimum temperature:   	-208.93	degrees Celcius
   Escape Velocity:		7.07	km/sec
   Molecular weight retained:	15.89 and above
   Surface acceleration:	609.50	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.067
   Length of year:		104.68	days
   Length of day:		2512.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.792	AU
   Mass:			1.341	Earth masses
   Equatorial radius:		7044.4	km
   Density:			5.474	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		1.10	Earth gees
   Surface pressure:		180.840	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		547.91	degrees Celcius
   Maximum temperature:   	550.84	degrees Celcius
   Minimum temperature:   	541.87	degrees Celcius
   Escape Velocity:		12.32	km/sec
   Molecular weight retained:	5.23 and above
   Surface acceleration:	1077.70	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.473
   Length of year:		245.87	days
   Length of day:		18.04	hours
   Boiling point of water:	332.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1269
				Cesium       melts at 28    boils at 1314
				Gallium      melts at 30    boils at 4070
				Rubidium     melts at 39    boils at 1287
				Potassium    melts at 63    boils at 1413
				Sodium       melts at 98    boils at 1601
				Indium       melts at 157   boils at 3546
				Lithium      melts at 181   boils at 2356
				Selenium     melts at 217   boils at 1282
				Tin          melts at 232   boils at 4427
				Polonium     melts at 254   boils at 1731
				Bismuth      melts at 271   boils at 2708
				Thallium     melts at 304   boils at 2535
				Cadmium      melts at 321   boils at 1412
				Lead         melts at 328   boils at 3012
				Zinc         melts at 420   boils at 1642
				Tellurium    melts at 450   boils at 1777
   gasses in atmosphere:
				Sulfur           21.4%  PP 38766.0 mb
				Nitrogen         77.9%  PP 140925.2 mb
				Phosphorus        0.4%  PP  771.0 mb


Planet 4	
   Distance from primary:	1.144	AU
   Mass:			1.103	Earth masses
   Equatorial radius:		6610.7	km
   Density:			5.446	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		1.03	Earth gees
   Surface pressure:		126.364	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		374.46	degrees Celcius
   Maximum temperature:   	378.32	degrees Celcius
   Minimum temperature:   	369.24	degrees Celcius
   Escape Velocity:		11.53	km/sec
   Molecular weight retained:	5.97 and above
   Surface acceleration:	1006.14	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.467
   Length of year:		426.65	days
   Length of day:		15.49	hours
   Boiling point of water:	307.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1205
				Cesium       melts at 28    boils at 1249
				Gallium      melts at 30    boils at 3891
				Rubidium     melts at 39    boils at 1222
				Potassium    melts at 63    boils at 1343
				Sodium       melts at 98    boils at 1524
				Sulfur       melts at 113   boils at 844
				Indium       melts at 157   boils at 3388
				Lithium      melts at 181   boils at 2248
				Selenium     melts at 217   boils at 1218
				Tin          melts at 232   boils at 4233
				Polonium     melts at 254   boils at 1649
				Bismuth      melts at 271   boils at 2586
				Thallium     melts at 304   boils at 2419
				Cadmium      melts at 321   boils at 1342
				Lead         melts at 328   boils at 2877
   gasses in atmosphere:
				Nitrogen         99.2%  PP 125326.4 mb
				Phosphorus        0.5%  PP  691.0 mb
				CarbonDioxide     0.1%  PP   75.3 mb
				Ethanol           0.1%  PP   76.3 mb


Planet 5	*gas giant*
   Distance from primary:	2.579	AU
   Mass:			9.736	Earth masses
   Equatorial radius:		21850.4	km
   Density:			1.332	grams/cc
   Eccentricity of orbit:	0.286
   Escape Velocity:		18.85	km/sec
   Molecular weight retained:	2.23 and above
   Surface acceleration:	813.18	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.488
   Length of year:		1443.89	days
   Length of day:		14.33	hours


Planet 6	*gas giant*
   Distance from primary:	4.086	AU
   Mass:			3.034	Earth masses
   Equatorial radius:		16159.9	km
   Density:			1.026	grams/cc
   Eccentricity of orbit:	0.143
   Escape Velocity:		12.24	km/sec
   Molecular weight retained:	5.30 and above
   Surface acceleration:	463.35	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.488
   Length of year:		2879.72	days
   Length of day:		18.99	hours


Planet 7	*gas giant*
   Distance from primary:	6.380	AU
   Mass:			1388.972	Earth masses
   Equatorial radius:		100135.5	km
   Density:			1.974	grams/cc
   Eccentricity of orbit:	0.095
   Escape Velocity:		105.18	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5524.03	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.457
   Length of year:		5608.28	days
   Length of day:		5.50	hours


Planet 8	*gas giant*
   Distance from primary:	15.215	AU
   Mass:			403.696	Earth masses
   Equatorial radius:		75079.3	km
   Density:			1.361	grams/cc
   Eccentricity of orbit:	0.086
   Escape Velocity:		65.49	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2855.97	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.502
   Length of year:		20679.76	days
   Length of day:		7.65	hours


Planet 9	*gas giant*
   Distance from primary:	32.028	AU
   Mass:			6.623	Earth masses
   Equatorial radius:		24090.1	km
   Density:			0.676	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		14.81	km/sec
   Molecular weight retained:	3.62 and above
   Surface acceleration:	455.13	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.480
   Length of year:		63193.87	days
   Length of day:		19.16	hours


Planet 10	
   Distance from primary:	49.453	AU
   Mass:			0.053	Earth masses
   Equatorial radius:		3246.6	km
   Density:			2.202	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.23	degrees Celcius
   Normal daytime temperature:	-224.03	degrees Celcius
   Normal night temperature:	-236.31	degrees Celcius
   Maximum temperature:   	-213.17	degrees Celcius
   Minimum temperature:   	-247.54	degrees Celcius
   Escape Velocity:		3.60	km/sec
   Molecular weight retained:	61.19 and above
   Surface acceleration:	199.80	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.138
   Length of year:		121247.10	days
   Length of day:		33.91	hours
   Boiling point of water:	-76.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


