                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950489ab
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6347 K
Stellar class: F7
Age: 1.869 billion years  (4.868 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.412 AU	no atmosphere
2	  0.530 AU	no atmosphere
3	  0.972 AU	greenhouse
4	  1.677 AU	gas giant
5	  2.597 AU	cold
6	  3.669 AU	gas giant
7	  5.371 AU	gas giant
8	 12.007 AU	gas giant
9	 35.382 AU	gas giant
10	 51.676 AU	no atmosphere



Planet 1	
   Distance from primary:	0.412	AU
   Mass:			0.092	Earth masses
   Equatorial radius:		2919.3	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		208.65	degrees Celcius
   Maximum temperature:   	420.19	degrees Celcius
   Minimum temperature:   	-203.45	degrees Celcius
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.54 and above
   Surface acceleration:	431.08	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.079
   Length of year:		91.90	days
   Length of day:		2205.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.530	AU
   Mass:			0.375	Earth masses
   Equatorial radius:		4645.3	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		153.67	degrees Celcius
   Maximum temperature:   	352.76	degrees Celcius
   Minimum temperature:   	-216.01	degrees Celcius
   Escape Velocity:		8.03	km/sec
   Molecular weight retained:	12.32 and above
   Surface acceleration:	693.62	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.061
   Length of year:		134.05	days
   Length of day:		3217.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.972	AU
   Mass:			1.470	Earth masses
   Equatorial radius:		7256.1	km
   Density:			5.489	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		1.13	Earth gees
   Surface pressure:		200.792	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		487.49	degrees Celcius
   Maximum temperature:   	490.42	degrees Celcius
   Minimum temperature:   	482.25	degrees Celcius
   Escape Velocity:		12.71	km/sec
   Molecular weight retained:	4.91 and above
   Surface acceleration:	1113.04	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.478
   Length of year:		332.51	days
   Length of day:		14.70	hours
   Boiling point of water:	340.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1288
				Cesium       melts at 28    boils at 1334
				Gallium      melts at 30    boils at 4125
				Rubidium     melts at 39    boils at 1306
				Potassium    melts at 63    boils at 1434
				Sodium       melts at 98    boils at 1625
				Indium       melts at 157   boils at 3594
				Lithium      melts at 181   boils at 2390
				Selenium     melts at 217   boils at 1301
				Tin          melts at 232   boils at 4487
				Polonium     melts at 254   boils at 1757
				Bismuth      melts at 271   boils at 2746
				Thallium     melts at 304   boils at 2570
				Cadmium      melts at 321   boils at 1433
				Lead         melts at 328   boils at 3054
				Zinc         melts at 420   boils at 1666
				Tellurium    melts at 450   boils at 1803
   gasses in atmosphere:
				Sulfur           18.7%  PP 37595.6 mb
				Nitrogen         80.7%  PP 162050.6 mb
				Phosphorus        0.4%  PP  752.0 mb


Planet 4	*gas giant*
   Distance from primary:	1.677	AU
   Mass:			11.958	Earth masses
   Equatorial radius:		22341.2	km
   Density:			1.530	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		20.66	km/sec
   Molecular weight retained:	1.86 and above
   Surface acceleration:	955.42	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.455
   Length of year:		753.77	days
   Length of day:		13.22	hours


Planet 5	
   Distance from primary:	2.597	AU
   Mass:			1.127	Earth masses
   Equatorial radius:		6657.8	km
   Density:			5.449	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		1.03	Earth gees
   Surface pressure:		1.071	Earth atmospheres
   Surface temperature:		-94.84	degrees Celcius
   Normal daytime temperature:	-92.28	degrees Celcius
   Normal night temperature:	-97.55	degrees Celcius
   Maximum temperature:   	-73.89	degrees Celcius
   Minimum temperature:   	-117.38	degrees Celcius
   Escape Velocity:		11.62	km/sec
   Molecular weight retained:	5.88 and above
   Surface acceleration:	1013.86	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.609
   Length of year:		1452.29	days
   Length of day:		15.05	hours
   Boiling point of water:	101.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	92.92
   liquids at surface:
				Ethanol      melts at -114  boils at 80
				Chlorine     melts at -101  boils at -33
   gasses in atmosphere:
				Oxygen           13.6%  PP  145.7 mb
				Nitrogen         86.3%  PP  924.1 mb


Planet 6	*gas giant*
   Distance from primary:	3.669	AU
   Mass:			5.647	Earth masses
   Equatorial radius:		19160.1	km
   Density:			1.146	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		15.33	km/sec
   Molecular weight retained:	3.38 and above
   Surface acceleration:	613.43	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.547
   Length of year:		2438.72	days
   Length of day:		16.50	hours


Planet 7	*gas giant*
   Distance from primary:	5.371	AU
   Mass:			432.827	Earth masses
   Equatorial radius:		70118.5	km
   Density:			1.791	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		70.17	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3510.66	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.507
   Length of year:		4316.93	days
   Length of day:		6.90	hours


Planet 8	*gas giant*
   Distance from primary:	12.007	AU
   Mass:			702.835	Earth masses
   Equatorial radius:		86368.1	km
   Density:			1.557	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		80.56	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3757.39	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.490
   Length of year:		14422.96	days
   Length of day:		6.67	hours


Planet 9	*gas giant*
   Distance from primary:	35.382	AU
   Mass:			29.864	Earth masses
   Equatorial radius:		37617.1	km
   Density:			0.801	grams/cc
   Eccentricity of orbit:	0.291
   Escape Velocity:		25.16	km/sec
   Molecular weight retained:	1.25 and above
   Surface acceleration:	841.63	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.513
   Length of year:		73023.37	days
   Length of day:		14.09	hours


Planet 10	
   Distance from primary:	51.676	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		2053.2	km
   Density:			2.192	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.89	degrees Celcius
   Normal daytime temperature:	-223.48	degrees Celcius
   Normal night temperature:	-238.14	degrees Celcius
   Maximum temperature:   	-210.68	degrees Celcius
   Minimum temperature:   	-250.81	degrees Celcius
   Escape Velocity:		2.27	km/sec
   Molecular weight retained:	153.66 and above
   Surface acceleration:	125.80	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.155
   Length of year:		128893.36	days
   Length of day:		42.73	hours
   Boiling point of water:	-94.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


