                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048413
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6107 K
Stellar class: F9
Age: 5.350 billion years  (1.572 billion left on main sequence)
Habitable ecosphere radius: 1.261 AU

Planets present at:
1	  0.427 AU	no atmosphere
2	  0.757 AU	greenhouse
3	  1.426 AU	cold
4	  1.685 AU	high pressure
5	  2.431 AU	cold
6	  4.212 AU	gas giant
7	  8.660 AU	gas giant
8	 14.936 AU	gas giant
9	 33.974 AU	gas giant
10	 49.198 AU	no atmosphere



Planet 1	
   Distance from primary:	0.427	AU
   Mass:			0.371	Earth masses
   Equatorial radius:		4625.8	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		197.45	degrees Celcius
   Maximum temperature:   	406.48	degrees Celcius
   Minimum temperature:   	-205.89	degrees Celcius
   Escape Velocity:		7.99	km/sec
   Molecular weight retained:	12.42 and above
   Surface acceleration:	690.60	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.068
   Length of year:		97.28	days
   Length of day:		2334.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.757	AU
   Mass:			0.913	Earth masses
   Equatorial radius:		6216.3	km
   Density:			5.422	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.96	Earth gees
   Surface pressure:		65.739	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		409.63	degrees Celcius
   Maximum temperature:   	415.37	degrees Celcius
   Minimum temperature:   	401.80	degrees Celcius
   Escape Velocity:		10.82	km/sec
   Molecular weight retained:	6.78 and above
   Surface acceleration:	941.94	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.470
   Length of year:		229.46	days
   Length of day:		26.91	hours
   Boiling point of water:	266.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1102
				Cesium       melts at 28    boils at 1142
				Gallium      melts at 30    boils at 3600
				Rubidium     melts at 39    boils at 1118
				Potassium    melts at 63    boils at 1230
				Sodium       melts at 98    boils at 1398
				Sulfur       melts at 113   boils at 766
				Indium       melts at 157   boils at 3133
				Lithium      melts at 181   boils at 2072
				Selenium     melts at 217   boils at 1114
				Tin          melts at 232   boils at 3919
				Polonium     melts at 254   boils at 1514
				Bismuth      melts at 271   boils at 2386
				Thallium     melts at 304   boils at 2231
				Cadmium      melts at 321   boils at 1229
				Lead         melts at 328   boils at 2656
   gasses in atmosphere:
				Nitrogen         99.0%  PP 65065.8 mb
				Phosphorus        0.7%  PP  445.0 mb
				CarbonDioxide     0.1%  PP   51.5 mb
				Ozone             0.1%  PP   44.8 mb
				Ethanol           0.1%  PP   52.6 mb


Planet 3	
   Distance from primary:	1.426	AU
   Mass:			0.445	Earth masses
   Equatorial radius:		4912.1	km
   Density:			5.354	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.189	Earth atmospheres
   Surface temperature:		-14.05	degrees Celcius
   Normal daytime temperature:	-4.51	degrees Celcius
   Normal night temperature:	-24.04	degrees Celcius
   Maximum temperature:   	21.56	degrees Celcius
   Minimum temperature:   	-51.48	degrees Celcius
   Escape Velocity:		8.50	km/sec
   Molecular weight retained:	10.99 and above
   Surface acceleration:	735.06	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.304
   Length of year:		593.09	days
   Length of day:		17.98	hours
   Boiling point of water:	59.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	4.87
   Ice cover percentage:	25.79
   liquids at surface:
				Ethanol      melts at -114  boils at 40
				Mercury      melts at -39   boils at 288
   gasses in atmosphere:
				Oxygen            3.7%  PP    7.0 mb
				Nitrogen         95.9%  PP  181.5 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ammonia           0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.3 mb


Planet 4	
   Distance from primary:	1.685	AU
   Mass:			1.933	Earth masses
   Equatorial radius:		7926.4	km
   Density:			5.538	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		1.25	Earth gees
   Surface pressure:		3.418	Earth atmospheres
   Surface temperature:		-1.47	degrees Celcius
   Normal daytime temperature:	0.56	degrees Celcius
   Normal night temperature:	-3.63	degrees Celcius
   Maximum temperature:   	13.58	degrees Celcius
   Minimum temperature:   	-17.35	degrees Celcius
   Escape Velocity:		13.95	km/sec
   Molecular weight retained:	4.08 and above
   Surface acceleration:	1226.84	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.225
   Length of year:		761.97	days
   Length of day:		13.71	hours
   Boiling point of water:	137.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	19.30
   Ice cover percentage:	8.99
   liquids at surface:
				Ethanol      melts at -114  boils at 114
				Mercury      melts at -39   boils at 420
				Bromine      melts at -7    boils at 93
   gasses in atmosphere:
				Oxygen            0.5%  PP   17.2 mb
				Nitrogen         99.3%  PP 3395.4 mb


Planet 5	
   Distance from primary:	2.431	AU
   Mass:			0.749	Earth masses
   Equatorial radius:		5828.9	km
   Density:			5.400	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.90	Earth gees
   Surface pressure:		0.559	Earth atmospheres
   Surface temperature:		-98.34	degrees Celcius
   Normal daytime temperature:	-94.69	degrees Celcius
   Normal night temperature:	-102.18	degrees Celcius
   Maximum temperature:   	-76.04	degrees Celcius
   Minimum temperature:   	-122.30	degrees Celcius
   Escape Velocity:		10.13	km/sec
   Molecular weight retained:	7.74 and above
   Surface acceleration:	879.68	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.646
   Length of year:		1319.60	days
   Length of day:		16.17	hours
   Boiling point of water:	84.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	95.24
   liquids at surface:
				Ethanol      melts at -114  boils at 64
				Chlorine     melts at -101  boils at -44
   gasses in atmosphere:
				Oxygen            0.3%  PP    1.6 mb
				Nitrogen         99.6%  PP  557.3 mb
				Ozone             0.1%  PP    0.4 mb


Planet 6	*gas giant*
   Distance from primary:	4.212	AU
   Mass:			1173.980	Earth masses
   Equatorial radius:		92053.0	km
   Density:			2.148	grams/cc
   Eccentricity of orbit:	0.144
   Escape Velocity:		100.85	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5524.90	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.518
   Length of year:		3004.74	days
   Length of day:		5.50	hours


Planet 7	*gas giant*
   Distance from primary:	8.660	AU
   Mass:			41.083	Earth masses
   Equatorial radius:		36767.2	km
   Density:			1.179	grams/cc
   Eccentricity of orbit:	0.134
   Escape Velocity:		29.85	km/sec
   Molecular weight retained:	0.89 and above
   Surface acceleration:	1211.94	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.533
   Length of year:		8873.00	days
   Length of day:		11.74	hours


Planet 8	*gas giant*
   Distance from primary:	14.936	AU
   Mass:			342.672	Earth masses
   Equatorial radius:		71429.0	km
   Density:			1.342	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		61.86	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	2678.36	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.483
   Length of year:		20089.58	days
   Length of day:		7.90	hours


Planet 9	*gas giant*
   Distance from primary:	33.974	AU
   Mass:			13.042	Earth masses
   Equatorial radius:		29484.2	km
   Density:			0.726	grams/cc
   Eccentricity of orbit:	0.107
   Escape Velocity:		18.78	km/sec
   Molecular weight retained:	2.25 and above
   Surface acceleration:	598.29	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.487
   Length of year:		68953.04	days
   Length of day:		16.71	hours


Planet 10	
   Distance from primary:	49.198	AU
   Mass:			0.078	Earth masses
   Equatorial radius:		3700.0	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.10	degrees Celcius
   Normal daytime temperature:	-224.23	degrees Celcius
   Normal night temperature:	-235.86	degrees Celcius
   Maximum temperature:   	-208.80	degrees Celcius
   Minimum temperature:   	-251.22	degrees Celcius
   Escape Velocity:		4.11	km/sec
   Molecular weight retained:	47.01 and above
   Surface acceleration:	228.21	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.147
   Length of year:		120160.74	days
   Length of day:		31.73	hours
   Boiling point of water:	-68.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


