                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048910
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6154 K
Stellar class: F8
Age: 1.716 billion years  (5.042 billion left on main sequence)
Habitable ecosphere radius: 1.280 AU

Planets present at:
1	  0.367 AU	no atmosphere
2	  0.489 AU	no atmosphere
3	  0.572 AU	no atmosphere
4	  0.791 AU	greenhouse
5	  0.957 AU	no atmosphere
6	  1.320 AU	
7	  1.631 AU	gas giant
8	  1.875 AU	cold
9	  2.369 AU	high pressure
10	  6.355 AU	gas giant
11	 14.206 AU	gas giant
12	 21.906 AU	gas giant
13	 29.220 AU	gas giant
14	 39.004 AU	no atmosphere
15	 48.546 AU	no atmosphere



Planet 1	
   Distance from primary:	0.367	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		2327.2	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.97	degrees Celcius
   Normal daytime temperature:	456.35	degrees Celcius
   Normal night temperature:	-184.90	degrees Celcius
   Maximum temperature:   	459.38	degrees Celcius
   Minimum temperature:   	-195.12	degrees Celcius
   Escape Velocity:		3.99	km/sec
   Molecular weight retained:	49.76 and above
   Surface acceleration:	342.75	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.049
   Length of year:		77.24	days
   Length of day:		1853.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.489	AU
   Mass:			0.062	Earth masses
   Equatorial radius:		2554.8	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		170.55	degrees Celcius
   Maximum temperature:   	373.73	degrees Celcius
   Minimum temperature:   	-212.94	degrees Celcius
   Escape Velocity:		4.39	km/sec
   Molecular weight retained:	41.25 and above
   Surface acceleration:	376.62	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.066
   Length of year:		118.58	days
   Length of day:		2845.94	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.572	AU
   Mass:			0.251	Earth masses
   Equatorial radius:		4070.1	km
   Density:			5.320	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		135.19	degrees Celcius
   Maximum temperature:   	330.00	degrees Celcius
   Minimum temperature:   	-219.92	degrees Celcius
   Escape Velocity:		7.02	km/sec
   Molecular weight retained:	16.12 and above
   Surface acceleration:	605.14	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.082
   Length of year:		150.17	days
   Length of day:		3604.05	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.791	AU
   Mass:			0.858	Earth masses
   Equatorial radius:		6091.5	km
   Density:			5.415	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.94	Earth gees
   Surface pressure:		68.668	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		417.72	degrees Celcius
   Maximum temperature:   	422.79	degrees Celcius
   Minimum temperature:   	410.81	degrees Celcius
   Escape Velocity:		10.60	km/sec
   Molecular weight retained:	7.07 and above
   Surface acceleration:	921.82	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.427
   Length of year:		244.03	days
   Length of day:		17.75	hours
   Boiling point of water:	269.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1108
				Cesium       melts at 28    boils at 1149
				Gallium      melts at 30    boils at 3618
				Rubidium     melts at 39    boils at 1124
				Potassium    melts at 63    boils at 1237
				Sodium       melts at 98    boils at 1406
				Sulfur       melts at 113   boils at 771
				Indium       melts at 157   boils at 3149
				Lithium      melts at 181   boils at 2083
				Selenium     melts at 217   boils at 1120
				Tin          melts at 232   boils at 3938
				Polonium     melts at 254   boils at 1523
				Bismuth      melts at 271   boils at 2398
				Thallium     melts at 304   boils at 2243
				Cadmium      melts at 321   boils at 1236
				Lead         melts at 328   boils at 2670
   gasses in atmosphere:
				Nitrogen         99.1%  PP 68073.7 mb
				Phosphorus        0.6%  PP  388.1 mb
				CarbonDioxide     0.1%  PP   42.0 mb
				Ozone             0.1%  PP   40.5 mb
				Ethanol           0.1%  PP   42.5 mb


Planet 5	
   Distance from primary:	0.957	AU
   Mass:			0.025	Earth masses
   Equatorial radius:		1896.1	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		43.03	degrees Celcius
   Normal daytime temperature:	131.59	degrees Celcius
   Normal night temperature:	-51.12	degrees Celcius
   Maximum temperature:   	157.92	degrees Celcius
   Minimum temperature:   	-80.54	degrees Celcius
   Escape Velocity:		3.25	km/sec
   Molecular weight retained:	75.07 and above
   Surface acceleration:	278.83	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.077
   Length of year:		324.88	days
   Length of day:		84.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363


Planet 6	
   Distance from primary:	1.320	AU
   Mass:			0.372	Earth masses
   Equatorial radius:		4630.4	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.132	Earth atmospheres
   Surface temperature:		7.62	degrees Celcius
   Normal daytime temperature:	19.75	degrees Celcius
   Normal night temperature:	-5.05	degrees Celcius
   Maximum temperature:   	44.92	degrees Celcius
   Minimum temperature:   	-31.37	degrees Celcius
   Escape Velocity:		8.00	km/sec
   Molecular weight retained:	12.40 and above
   Surface acceleration:	691.32	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.182
   Length of year:		526.17	days
   Length of day:		18.42	hours
   Boiling point of water:	51.5	degrees Celcius
   Hydrosphere percentage:	47.85
   Cloud cover percentage:	20.83
   Ice cover percentage:	3.84
   liquids at surface:
				Ethanol      melts at -114  boils at 33
				Mercury      melts at -39   boils at 275
				Bromine      melts at -7    boils at 16
				Water        melts at 0     boils at 52
   gasses in atmosphere:
				Oxygen           73.1%  PP   96.4 mb
				Nitrogen         26.7%  PP   35.3 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	1.631	AU
   Mass:			9.016	Earth masses
   Equatorial radius:		20530.2	km
   Density:			1.487	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		18.72	km/sec
   Molecular weight retained:	2.27 and above
   Surface acceleration:	853.06	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.484
   Length of year:		723.17	days
   Length of day:		14.00	hours


Planet 8	
   Distance from primary:	1.875	AU
   Mass:			1.068	Earth masses
   Equatorial radius:		6541.9	km
   Density:			5.442	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		1.01	Earth gees
   Surface pressure:		1.146	Earth atmospheres
   Surface temperature:		-68.38	degrees Celcius
   Normal daytime temperature:	-65.50	degrees Celcius
   Normal night temperature:	-71.42	degrees Celcius
   Maximum temperature:   	-47.52	degrees Celcius
   Minimum temperature:   	-90.68	degrees Celcius
   Escape Velocity:		11.41	km/sec
   Molecular weight retained:	6.10 and above
   Surface acceleration:	994.88	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.647
   Length of year:		891.14	days
   Length of day:		15.20	hours
   Boiling point of water:	103.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.16
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 82
				Chlorine     melts at -101  boils at -31
				Ammonia      melts at -78   boils at -31
				Radon        melts at -71   boils at -60
   gasses in atmosphere:
				Oxygen           15.8%  PP  181.5 mb
				Nitrogen         84.0%  PP  963.6 mb


Planet 9	
   Distance from primary:	2.369	AU
   Mass:			1.674	Earth masses
   Equatorial radius:		7568.0	km
   Density:			5.511	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		1.19	Earth gees
   Surface pressure:		2.041	Earth atmospheres
   Surface temperature:		-87.53	degrees Celcius
   Normal daytime temperature:	-85.70	degrees Celcius
   Normal night temperature:	-89.46	degrees Celcius
   Maximum temperature:   	-72.04	degrees Celcius
   Minimum temperature:   	-104.12	degrees Celcius
   Escape Velocity:		13.28	km/sec
   Molecular weight retained:	4.50 and above
   Surface acceleration:	1165.63	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.649
   Length of year:		1265.33	days
   Length of day:		14.04	hours
   Boiling point of water:	120.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	92.30
   liquids at surface:
				Ethanol      melts at -114  boils at 98
				Chlorine     melts at -101  boils at -21
   gasses in atmosphere:
				Oxygen            2.8%  PP   57.1 mb
				Nitrogen         97.1%  PP 1982.7 mb


Planet 10	*gas giant*
   Distance from primary:	6.355	AU
   Mass:			1471.145	Earth masses
   Equatorial radius:		101615.6	km
   Density:			2.001	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		107.46	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5681.64	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.476
   Length of year:		5549.98	days
   Length of day:		5.42	hours


Planet 11	*gas giant*
   Distance from primary:	14.206	AU
   Mass:			1.956	Earth masses
   Equatorial radius:		15745.8	km
   Density:			0.715	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		9.95	km/sec
   Molecular weight retained:	8.01 and above
   Surface acceleration:	314.64	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.545
   Length of year:		18584.64	days
   Length of day:		23.04	hours


Planet 12	*gas giant*
   Distance from primary:	21.906	AU
   Mass:			3.091	Earth masses
   Equatorial radius:		18655.5	km
   Density:			0.679	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		11.50	km/sec
   Molecular weight retained:	6.01 and above
   Surface acceleration:	354.22	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.467
   Length of year:		35588.92	days
   Length of day:		21.72	hours


Planet 13	*gas giant*
   Distance from primary:	29.220	AU
   Mass:			13.958	Earth masses
   Equatorial radius:		29660.8	km
   Density:			0.763	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		19.37	km/sec
   Molecular weight retained:	2.11 and above
   Surface acceleration:	632.71	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.490
   Length of year:		54826.06	days
   Length of day:		16.25	hours


Planet 14	
   Distance from primary:	39.004	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		4849.5	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-224.42	degrees Celcius
   Normal daytime temperature:	-218.53	degrees Celcius
   Normal night temperature:	-230.23	degrees Celcius
   Maximum temperature:   	-204.95	degrees Celcius
   Minimum temperature:   	-244.41	degrees Celcius
   Escape Velocity:		5.40	km/sec
   Molecular weight retained:	27.17 and above
   Surface acceleration:	301.20	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.165
   Length of year:		84554.76	days
   Length of day:		27.62	hours
   Boiling point of water:	-52.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 15	
   Distance from primary:	48.546	AU
   Mass:			0.199	Earth masses
   Equatorial radius:		5030.7	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.155
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.27	degrees Celcius
   Normal daytime temperature:	-224.05	degrees Celcius
   Normal night temperature:	-234.39	degrees Celcius
   Maximum temperature:   	-208.25	degrees Celcius
   Minimum temperature:   	-250.32	degrees Celcius
   Escape Velocity:		5.61	km/sec
   Molecular weight retained:	25.22 and above
   Surface acceleration:	312.85	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.151
   Length of year:		117409.42	days
   Length of day:		27.10	hours
   Boiling point of water:	-51.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


