                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a75
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6178 K
Stellar class: F8
Age: 3.924 billion years  (2.788 billion left on main sequence)
Habitable ecosphere radius: 1.286 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.588 AU	no atmosphere
3	  1.115 AU	greenhouse
4	  1.542 AU	gas giant
5	  2.296 AU	cold
6	  4.551 AU	gas giant
7	  7.095 AU	gas giant
8	 12.079 AU	gas giant
9	 16.432 AU	gas giant
10	 32.758 AU	gas giant



Planet 1	
   Distance from primary:	0.370	AU
   Mass:			0.136	Earth masses
   Equatorial radius:		3320.6	km
   Density:			5.295	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		235.28	degrees Celcius
   Normal daytime temperature:	449.42	degrees Celcius
   Normal night temperature:	-186.06	degrees Celcius
   Maximum temperature:   	452.50	degrees Celcius
   Minimum temperature:   	-196.37	degrees Celcius
   Escape Velocity:		5.71	km/sec
   Molecular weight retained:	24.33 and above
   Surface acceleration:	491.39	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.084
   Length of year:		78.06	days
   Length of day:		1873.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.588	AU
   Mass:			0.605	Earth masses
   Equatorial radius:		5433.9	km
   Density:			5.379	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.41	degrees Celcius
   Maximum temperature:   	327.77	degrees Celcius
   Minimum temperature:   	-220.36	degrees Celcius
   Escape Velocity:		9.42	km/sec
   Molecular weight retained:	8.94 and above
   Surface acceleration:	816.93	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.057
   Length of year:		156.18	days
   Length of day:		3748.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.115	AU
   Mass:			0.405	Earth masses
   Equatorial radius:		4762.7	km
   Density:			5.348	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.73	Earth gees
   Surface pressure:		13.654	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		51.90	degrees Celcius
   Maximum temperature:   	61.28	degrees Celcius
   Minimum temperature:   	42.05	degrees Celcius
   Escape Velocity:		8.23	km/sec
   Molecular weight retained:	11.71 and above
   Surface acceleration:	711.83	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.615
   Length of year:		408.43	days
   Length of day:		19.11	hours
   Boiling point of water:	189.2	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 163
				Mercury      melts at -39   boils at 508
				Bromine      melts at -7    boils at 139
				Water        melts at 0     boils at 189
				Francium     melts at 27    boils at 904
				Cesium       melts at 28    boils at 939
				Gallium      melts at 30    boils at 3043
				Rubidium     melts at 39    boils at 918
				Phosphorus   melts at 44    boils at 413
   gasses in atmosphere:
				Nitrogen         99.5%  PP 13584.5 mb
				CarbonDioxide     0.2%  PP   25.6 mb
				Methane           0.1%  PP    7.4 mb
				Ammonia           0.1%  PP    8.5 mb
				Ozone             0.2%  PP   26.0 mb


Planet 4	*gas giant*
   Distance from primary:	1.542	AU
   Mass:			18.644	Earth masses
   Equatorial radius:		25247.9	km
   Density:			1.653	grams/cc
   Eccentricity of orbit:	0.111
   Escape Velocity:		24.27	km/sec
   Molecular weight retained:	1.35 and above
   Surface acceleration:	1166.37	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.478
   Length of year:		663.90	days
   Length of day:		11.97	hours


Planet 5	
   Distance from primary:	2.296	AU
   Mass:			1.063	Earth masses
   Equatorial radius:		6532.2	km
   Density:			5.441	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		1.01	Earth gees
   Surface pressure:		1.077	Earth atmospheres
   Surface temperature:		-104.41	degrees Celcius
   Normal daytime temperature:	-101.97	degrees Celcius
   Normal night temperature:	-106.99	degrees Celcius
   Maximum temperature:   	-86.12	degrees Celcius
   Minimum temperature:   	-124.12	degrees Celcius
   Escape Velocity:		11.39	km/sec
   Molecular weight retained:	6.12 and above
   Surface acceleration:	993.30	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.756
   Length of year:		1206.44	days
   Length of day:		15.21	hours
   Boiling point of water:	102.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 80
   gasses in atmosphere:
				Oxygen            0.2%  PP    2.1 mb
				Nitrogen         99.7%  PP 1074.3 mb
				Ozone             0.1%  PP    0.6 mb


Planet 6	*gas giant*
   Distance from primary:	4.551	AU
   Mass:			929.967	Earth masses
   Equatorial radius:		86422.9	km
   Density:			2.056	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		92.64	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4965.34	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.539
   Length of year:		3363.18	days
   Length of day:		5.80	hours


Planet 7	*gas giant*
   Distance from primary:	7.095	AU
   Mass:			29.493	Earth masses
   Equatorial radius:		32776.4	km
   Density:			1.195	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		26.79	km/sec
   Molecular weight retained:	1.11 and above
   Surface acceleration:	1094.79	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.484
   Length of year:		6554.17	days
   Length of day:		12.35	hours


Planet 8	*gas giant*
   Distance from primary:	12.079	AU
   Mass:			2.141	Earth masses
   Equatorial radius:		15944.1	km
   Density:			0.754	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		10.35	km/sec
   Molecular weight retained:	7.41 and above
   Surface acceleration:	335.91	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.453
   Length of year:		14559.78	days
   Length of day:		22.30	hours


Planet 9	*gas giant*
   Distance from primary:	16.432	AU
   Mass:			318.693	Earth masses
   Equatorial radius:		70378.4	km
   Density:			1.305	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		60.10	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2565.87	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.528
   Length of year:		23090.92	days
   Length of day:		8.07	hours


Planet 10	*gas giant*
   Distance from primary:	32.758	AU
   Mass:			7.053	Earth masses
   Equatorial radius:		24530.6	km
   Density:			0.682	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		15.14	km/sec
   Molecular weight retained:	3.46 and above
   Surface acceleration:	467.44	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.548
   Length of year:		65022.51	days
   Length of day:		18.90	hours


