                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048335
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6159 K
Stellar class: F8
Age: 4.881 billion years  (2.070 billion left on main sequence)
Habitable ecosphere radius: 1.257 AU

Planets present at:
1	  0.327 AU	no atmosphere
2	  0.504 AU	no atmosphere
3	  0.656 AU	greenhouse
4	  0.954 AU	no atmosphere
5	  1.585 AU	high pressure
6	  2.590 AU	gas giant
7	  7.375 AU	gas giant
8	 11.059 AU	no atmosphere
9	 18.515 AU	gas giant
10	 32.512 AU	no atmosphere
11	 46.998 AU	gas giant



Planet 1	
   Distance from primary:	0.327	AU
   Mass:			0.104	Earth masses
   Equatorial radius:		3040.1	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		265.99	degrees Celcius
   Normal daytime temperature:	486.31	degrees Celcius
   Normal night temperature:	-175.87	degrees Celcius
   Maximum temperature:   	489.31	degrees Celcius
   Minimum temperature:   	-186.46	degrees Celcius
   Escape Velocity:		5.23	km/sec
   Molecular weight retained:	29.06 and above
   Surface acceleration:	449.21	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.056
   Length of year:		65.13	days
   Length of day:		1563.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.504	AU
   Mass:			1/404.6	Earth masses
   Equatorial radius:		875.8	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		161.03	degrees Celcius
   Maximum temperature:   	361.74	degrees Celcius
   Minimum temperature:   	-213.95	degrees Celcius
   Escape Velocity:		1.50	km/sec
   Molecular weight retained:	352.72 and above
   Surface acceleration:	128.49	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.056
   Length of year:		124.68	days
   Length of day:		2992.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.656	AU
   Mass:			1.202	Earth masses
   Equatorial radius:		6798.3	km
   Density:			5.458	grams/cc
   Eccentricity of orbit:	0.159
   Surface gravity:		1.06	Earth gees
   Surface pressure:		126.817	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		529.71	degrees Celcius
   Maximum temperature:   	534.66	degrees Celcius
   Minimum temperature:   	520.40	degrees Celcius
   Escape Velocity:		11.87	km/sec
   Molecular weight retained:	5.63 and above
   Surface acceleration:	1036.96	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.591
   Length of year:		184.94	days
   Length of day:		53.77	hours
   Boiling point of water:	307.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1206
				Cesium       melts at 28    boils at 1249
				Gallium      melts at 30    boils at 3893
				Rubidium     melts at 39    boils at 1223
				Potassium    melts at 63    boils at 1344
				Sodium       melts at 98    boils at 1524
				Indium       melts at 157   boils at 3390
				Lithium      melts at 181   boils at 2249
				Selenium     melts at 217   boils at 1218
				Tin          melts at 232   boils at 4235
				Polonium     melts at 254   boils at 1649
				Bismuth      melts at 271   boils at 2587
				Thallium     melts at 304   boils at 2420
				Cadmium      melts at 321   boils at 1343
				Lead         melts at 328   boils at 2878
				Zinc         melts at 420   boils at 1564
				Tellurium    melts at 450   boils at 1693
   gasses in atmosphere:
				Sulfur           23.3%  PP 29601.6 mb
				Nitrogen         76.0%  PP 96336.7 mb
				Phosphorus        0.5%  PP  586.7 mb
				CarbonDioxide     0.1%  PP   66.5 mb
				Ethanol           0.1%  PP   67.7 mb


Planet 4	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.954	AU
   Mass:			0.022	Earth masses
   Equatorial radius:		1805.3	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.105
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		42.35	degrees Celcius
   Maximum temperature:   	213.20	degrees Celcius
   Minimum temperature:   	-231.77	degrees Celcius
   Escape Velocity:		3.10	km/sec
   Molecular weight retained:	82.84 and above
   Surface acceleration:	265.40	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.057
   Length of year:		324.76	days
   Length of day:		6316.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363


Planet 5	
   Distance from primary:	1.585	AU
   Mass:			1.845	Earth masses
   Equatorial radius:		7808.5	km
   Density:			5.529	grams/cc
   Eccentricity of orbit:	0.189
   Surface gravity:		1.23	Earth gees
   Surface pressure:		3.448	Earth atmospheres
   Surface temperature:		7.04	degrees Celcius
   Normal daytime temperature:	9.14	degrees Celcius
   Normal night temperature:	4.81	degrees Celcius
   Maximum temperature:   	24.42	degrees Celcius
   Minimum temperature:   	-11.29	degrees Celcius
   Escape Velocity:		13.73	km/sec
   Molecular weight retained:	4.21 and above
   Surface acceleration:	1206.62	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.222
   Length of year:		695.50	days
   Length of day:		13.83	hours
   Boiling point of water:	137.5	degrees Celcius
   Hydrosphere percentage:	88.60
   Cloud cover percentage:	33.53
   Ice cover percentage:	4.73
   liquids at surface:
				Ethanol      melts at -114  boils at 114
				Mercury      melts at -39   boils at 420
				Bromine      melts at -7    boils at 93
				Water        melts at 0     boils at 138
   gasses in atmosphere:
				Oxygen            0.6%  PP   19.6 mb
				Nitrogen         99.3%  PP 3422.9 mb


Planet 6	*gas giant*
   Distance from primary:	2.590	AU
   Mass:			176.944	Earth masses
   Equatorial radius:		50914.6	km
   Density:			1.913	grams/cc
   Eccentricity of orbit:	0.085
   Escape Velocity:		52.65	km/sec
   Molecular weight retained:	0.29 and above
   Surface acceleration:	2722.01	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.480
   Length of year:		1452.02	days
   Length of day:		7.83	hours


Planet 7	*gas giant*
   Distance from primary:	7.375	AU
   Mass:			1655.764	Earth masses
   Equatorial radius:		106651.4	km
   Density:			1.948	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		111.28	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5805.04	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.466
   Length of year:		6961.88	days
   Length of day:		5.36	hours


Planet 8	
   Distance from primary:	11.059	AU
   Mass:			0.304	Earth masses
   Equatorial radius:		5784.9	km
   Density:			2.238	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.055	Earth atmospheres
   Surface temperature:		-181.65	degrees Celcius
   Normal daytime temperature:	-174.71	degrees Celcius
   Normal night temperature:	-188.83	degrees Celcius
   Maximum temperature:   	-158.70	degrees Celcius
   Minimum temperature:   	-206.22	degrees Celcius
   Escape Velocity:		6.47	km/sec
   Molecular weight retained:	18.96 and above
   Surface acceleration:	361.85	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.294
   Length of year:		12813.28	days
   Length of day:		25.19	hours
   Boiling point of water:	34.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	23.41
   liquids at surface:
				Ozone        melts at -193  boils at -140
   gasses in atmosphere:
				Argon            50.2%  PP   27.5 mb
				Neon             49.7%  PP   27.3 mb


Planet 9	*gas giant*
   Distance from primary:	18.515	AU
   Mass:			13.719	Earth masses
   Equatorial radius:		28452.6	km
   Density:			0.850	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		19.61	km/sec
   Molecular weight retained:	2.06 and above
   Surface acceleration:	675.78	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.461
   Length of year:		27756.54	days
   Length of day:		15.72	hours


Planet 10	
   Distance from primary:	32.512	AU
   Mass:			1.038	Earth masses
   Equatorial radius:		8627.2	km
   Density:			2.306	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.003	Earth atmospheres
   Surface temperature:		-218.54	degrees Celcius
   Normal daytime temperature:	-213.65	degrees Celcius
   Normal night temperature:	-223.39	degrees Celcius
   Maximum temperature:   	-198.36	degrees Celcius
   Minimum temperature:   	-239.71	degrees Celcius
   Escape Velocity:		9.79	km/sec
   Molecular weight retained:	8.28 and above
   Surface acceleration:	555.92	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.147
   Length of year:		64587.85	days
   Length of day:		20.33	hours
   Boiling point of water:	-13.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.15
   liquids at surface:
				Fluorine     melts at -220  boils at -213
   gasses in atmosphere:
				Neon             100.0%  PP    2.7 mb


Planet 11	*gas giant*
   Distance from primary:	46.998	AU
   Mass:			0.358	Earth masses
   Equatorial radius:		10618.6	km
   Density:			0.427	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		5.19	km/sec
   Molecular weight retained:	29.51 and above
   Surface acceleration:	126.68	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.514
   Length of year:		112255.16	days
   Length of day:		36.31	hours


