                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504897b
Stellar mass: 1.11 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6451 K
Stellar class: F6
Age: 1.858 billion years  (4.885 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.334 AU	no atmosphere
2	  0.434 AU	no atmosphere
3	  0.686 AU	greenhouse
4	  0.999 AU	no atmosphere
5	  1.308 AU	
6	  2.667 AU	high pressure
7	  5.296 AU	gas giant
8	  8.987 AU	gas giant
9	 13.228 AU	no atmosphere
10	 21.488 AU	gas giant
11	 36.132 AU	gas giant
12	 49.833 AU	no atmosphere



Planet 1	
   Distance from primary:	0.334	AU
   Mass:			0.148	Earth masses
   Equatorial radius:		3416.9	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		262.57	degrees Celcius
   Normal daytime temperature:	482.24	degrees Celcius
   Normal night temperature:	-177.27	degrees Celcius
   Maximum temperature:   	485.32	degrees Celcius
   Minimum temperature:   	-188.12	degrees Celcius
   Escape Velocity:		5.88	km/sec
   Molecular weight retained:	22.96 and above
   Surface acceleration:	505.92	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.078
   Length of year:		66.85	days
   Length of day:		1604.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.434	AU
   Mass:			0.069	Earth masses
   Equatorial radius:		2655.1	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		199.63	degrees Celcius
   Normal daytime temperature:	405.73	degrees Celcius
   Normal night temperature:	-192.24	degrees Celcius
   Maximum temperature:   	408.96	degrees Celcius
   Minimum temperature:   	-202.50	degrees Celcius
   Escape Velocity:		4.56	km/sec
   Molecular weight retained:	38.18 and above
   Surface acceleration:	391.58	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.055
   Length of year:		99.06	days
   Length of day:		1927.98	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.686	AU
   Mass:			0.760	Earth masses
   Equatorial radius:		5856.1	km
   Density:			5.402	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.90	Earth gees
   Surface pressure:		44.926	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		307.15	degrees Celcius
   Maximum temperature:   	313.73	degrees Celcius
   Minimum temperature:   	299.35	degrees Celcius
   Escape Velocity:		10.18	km/sec
   Molecular weight retained:	7.67 and above
   Surface acceleration:	884.03	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.474
   Length of year:		197.04	days
   Length of day:		23.43	hours
   Boiling point of water:	245.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 603
				Francium     melts at 27    boils at 1048
				Cesium       melts at 28    boils at 1087
				Gallium      melts at 30    boils at 3449
				Rubidium     melts at 39    boils at 1063
				Potassium    melts at 63    boils at 1172
				Sodium       melts at 98    boils at 1333
				Sulfur       melts at 113   boils at 725
				Indium       melts at 157   boils at 3000
				Lithium      melts at 181   boils at 1980
				Selenium     melts at 217   boils at 1059
				Tin          melts at 232   boils at 3755
				Polonium     melts at 254   boils at 1445
				Bismuth      melts at 271   boils at 2282
				Astatine     melts at 302   boils at 575
				Thallium     melts at 304   boils at 2133
   gasses in atmosphere:
				Nitrogen         99.1%  PP 44501.6 mb
				Phosphorus        0.6%  PP  277.8 mb
				CarbonDioxide     0.1%  PP   30.6 mb
				Ozone             0.1%  PP   30.1 mb
				Ethanol           0.1%  PP   31.0 mb


Planet 4	
   Distance from primary:	0.999	AU
   Mass:			1/230.7	Earth masses
   Equatorial radius:		1056.1	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		37.89	degrees Celcius
   Maximum temperature:   	207.26	degrees Celcius
   Minimum temperature:   	-232.51	degrees Celcius
   Escape Velocity:		1.81	km/sec
   Molecular weight retained:	242.51 and above
   Surface acceleration:	154.98	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.061
   Length of year:		346.32	days
   Length of day:		8311.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 5	
   Distance from primary:	1.308	AU
   Mass:			0.345	Earth masses
   Equatorial radius:		4517.9	km
   Density:			5.337	grams/cc
   Eccentricity of orbit:	0.122
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.109	Earth atmospheres
   Surface temperature:		9.13	degrees Celcius
   Normal daytime temperature:	22.38	degrees Celcius
   Normal night temperature:	-4.67	degrees Celcius
   Maximum temperature:   	52.68	degrees Celcius
   Minimum temperature:   	-36.36	degrees Celcius
   Escape Velocity:		7.80	km/sec
   Molecular weight retained:	13.04 and above
   Surface acceleration:	673.93	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.170
   Length of year:		519.40	days
   Length of day:		18.69	hours
   Boiling point of water:	47.5	degrees Celcius
   Hydrosphere percentage:	44.64
   Cloud cover percentage:	21.55
   Ice cover percentage:	3.27
   liquids at surface:
				Ethanol      melts at -114  boils at 29
				Mercury      melts at -39   boils at 268
				Bromine      melts at -7    boils at 13
				Water        melts at 0     boils at 48
   gasses in atmosphere:
				Oxygen           77.1%  PP   83.9 mb
				Nitrogen         22.6%  PP   24.6 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 6	
   Distance from primary:	2.667	AU
   Mass:			8.017	Earth masses
   Equatorial radius:		12384.6	km
   Density:			6.022	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		2.12	Earth gees
   Surface pressure:		53.510	Earth atmospheres
   Surface temperature:		81.67	degrees Celcius
   Maximum temperature:   	86.78	degrees Celcius
   Minimum temperature:   	76.36	degrees Celcius
   Escape Velocity:		22.72	km/sec
   Molecular weight retained:	1.54 and above
   Surface acceleration:	2084.39	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.482
   Length of year:		1510.99	days
   Length of day:		10.50	hours
   Boiling point of water:	255.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 619
				Water        melts at 0     boils at 255
				Francium     melts at 27    boils at 1072
				Cesium       melts at 28    boils at 1112
				Gallium      melts at 30    boils at 3517
				Rubidium     melts at 39    boils at 1088
				Phosphorus   melts at 44    boils at 511
				Potassium    melts at 63    boils at 1198
   gasses in atmosphere:
				Nitrogen          0.2%  PP   92.8 mb
				Helium           99.8%  PP 53416.6 mb


Planet 7	*gas giant*
   Distance from primary:	5.296	AU
   Mass:			1142.521	Earth masses
   Equatorial radius:		92959.5	km
   Density:			2.029	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		99.01	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5272.49	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.479
   Length of year:		4222.83	days
   Length of day:		5.63	hours


Planet 8	*gas giant*
   Distance from primary:	8.987	AU
   Mass:			262.208	Earth masses
   Equatorial radius:		63240.1	km
   Density:			1.479	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		57.51	km/sec
   Molecular weight retained:	0.24 and above
   Surface acceleration:	2614.57	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.506
   Length of year:		9345.35	days
   Length of day:		7.99	hours


Planet 9	
   Distance from primary:	13.228	AU
   Mass:			0.109	Earth masses
   Equatorial radius:		4125.4	km
   Density:			2.212	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.008	Earth atmospheres
   Surface temperature:		-192.71	degrees Celcius
   Normal daytime temperature:	-183.04	degrees Celcius
   Normal night temperature:	-202.45	degrees Celcius
   Maximum temperature:   	-165.50	degrees Celcius
   Minimum temperature:   	-221.01	degrees Celcius
   Escape Velocity:		4.59	km/sec
   Molecular weight retained:	37.72 and above
   Surface acceleration:	255.04	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.277
   Length of year:		16695.76	days
   Length of day:		30.01	hours
   Boiling point of water:	2.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	19.22
   liquids at surface:
				Ozone        melts at -193  boils at -153


Planet 10	*gas giant*
   Distance from primary:	21.488	AU
   Mass:			84.967	Earth masses
   Equatorial radius:		48955.6	km
   Density:			1.033	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		37.21	km/sec
   Molecular weight retained:	0.57 and above
   Surface acceleration:	1413.78	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.541
   Length of year:		34562.62	days
   Length of day:		10.87	hours


Planet 11	*gas giant*
   Distance from primary:	36.132	AU
   Mass:			1.973	Earth masses
   Equatorial radius:		17061.6	km
   Density:			0.567	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		9.60	km/sec
   Molecular weight retained:	8.60 and above
   Surface acceleration:	270.35	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.461
   Length of year:		75368.00	days
   Length of day:		24.86	hours


Planet 12	
   Distance from primary:	49.833	AU
   Mass:			0.044	Earth masses
   Equatorial radius:		3046.4	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.00	degrees Celcius
   Normal daytime temperature:	-223.59	degrees Celcius
   Normal night temperature:	-236.28	degrees Celcius
   Maximum temperature:   	-209.16	degrees Celcius
   Minimum temperature:   	-250.68	degrees Celcius
   Escape Velocity:		3.38	km/sec
   Molecular weight retained:	69.56 and above
   Surface acceleration:	187.31	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.145
   Length of year:		122076.50	days
   Length of day:		35.02	hours
   Boiling point of water:	-77.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


