                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ef7
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6079 K
Stellar class: F9
Age: 1.285 billion years  (5.811 billion left on main sequence)
Habitable ecosphere radius: 1.241 AU

Planets present at:
1	  0.440 AU	no atmosphere
2	  0.573 AU	no atmosphere
3	  0.742 AU	no atmosphere
4	  0.853 AU	greenhouse
5	  1.008 AU	greenhouse
6	  1.713 AU	high pressure
7	  2.730 AU	gas giant
8	  6.481 AU	gas giant
9	 11.393 AU	gas giant
10	 16.820 AU	gas giant
11	 22.376 AU	gas giant
12	 38.275 AU	gas giant
13	 49.801 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.440	AU
   Mass:			0.137	Earth masses
   Equatorial radius:		3326.3	km
   Density:			5.295	grams/cc
   Eccentricity of orbit:	0.183
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		188.78	degrees Celcius
   Normal daytime temperature:	391.94	degrees Celcius
   Normal night temperature:	-190.73	degrees Celcius
   Maximum temperature:   	395.64	degrees Celcius
   Minimum temperature:   	-202.54	degrees Celcius
   Escape Velocity:		5.72	km/sec
   Molecular weight retained:	24.24 and above
   Surface acceleration:	492.25	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.053
   Length of year:		102.05	days
   Length of day:		1692.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.573	AU
   Mass:			0.187	Earth masses
   Equatorial radius:		3689.4	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		130.48	degrees Celcius
   Maximum temperature:   	324.07	degrees Celcius
   Minimum temperature:   	-220.43	degrees Celcius
   Escape Velocity:		6.35	km/sec
   Molecular weight retained:	19.66 and above
   Surface acceleration:	547.17	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.064
   Length of year:		151.58	days
   Length of day:		3637.97	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.742	AU
   Mass:			0.059	Earth masses
   Equatorial radius:		2522.0	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		80.95	degrees Celcius
   Maximum temperature:   	261.91	degrees Celcius
   Minimum temperature:   	-227.42	degrees Celcius
   Escape Velocity:		4.33	km/sec
   Molecular weight retained:	42.34 and above
   Surface acceleration:	371.74	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.072
   Length of year:		223.10	days
   Length of day:		5354.45	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.853	AU
   Mass:			1.163	Earth masses
   Equatorial radius:		6726.1	km
   Density:			5.453	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		1.04	Earth gees
   Surface pressure:		100.256	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		422.02	degrees Celcius
   Maximum temperature:   	426.17	degrees Celcius
   Minimum temperature:   	416.11	degrees Celcius
   Escape Velocity:		11.74	km/sec
   Molecular weight retained:	5.76 and above
   Surface acceleration:	1025.08	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.538
   Length of year:		275.38	days
   Length of day:		15.59	hours
   Boiling point of water:	292.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1167
				Cesium       melts at 28    boils at 1209
				Gallium      melts at 30    boils at 3783
				Rubidium     melts at 39    boils at 1184
				Potassium    melts at 63    boils at 1301
				Sodium       melts at 98    boils at 1477
				Sulfur       melts at 113   boils at 815
				Indium       melts at 157   boils at 3294
				Lithium      melts at 181   boils at 2183
				Selenium     melts at 217   boils at 1179
				Tin          melts at 232   boils at 4117
				Polonium     melts at 254   boils at 1599
				Bismuth      melts at 271   boils at 2511
				Thallium     melts at 304   boils at 2349
				Cadmium      melts at 321   boils at 1300
				Lead         melts at 328   boils at 2795
				Zinc         melts at 420   boils at 1516
   gasses in atmosphere:
				Nitrogen         99.3%  PP 99508.6 mb
				Phosphorus        0.5%  PP  485.6 mb
				CarbonDioxide     0.1%  PP   50.9 mb
				Ethanol           0.1%  PP   51.4 mb


Planet 5	
   Distance from primary:	1.008	AU
   Mass:			0.402	Earth masses
   Equatorial radius:		4751.3	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.72	Earth gees
   Surface pressure:		13.224	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		85.17	degrees Celcius
   Maximum temperature:   	94.95	degrees Celcius
   Minimum temperature:   	74.87	degrees Celcius
   Escape Velocity:		8.21	km/sec
   Molecular weight retained:	11.76 and above
   Surface acceleration:	710.06	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.497
   Length of year:		353.64	days
   Length of day:		18.64	hours
   Boiling point of water:	187.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 505
				Water        melts at 0     boils at 188
				Francium     melts at 27    boils at 901
				Cesium       melts at 28    boils at 935
				Gallium      melts at 30    boils at 3033
				Rubidium     melts at 39    boils at 914
				Phosphorus   melts at 44    boils at 411
				Potassium    melts at 63    boils at 1010
   gasses in atmosphere:
				Nitrogen         99.4%  PP 13142.5 mb
				CarbonDioxide     0.2%  PP   21.2 mb
				Methane           0.1%  PP    7.0 mb
				Ammonia           0.1%  PP    8.2 mb
				Ozone             0.2%  PP   21.7 mb
				Ethanol           0.2%  PP   21.6 mb


Planet 6	
   Distance from primary:	1.713	AU
   Mass:			1.883	Earth masses
   Equatorial radius:		7860.0	km
   Density:			5.533	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		1.24	Earth gees
   Surface pressure:		3.389	Earth atmospheres
   Surface temperature:		-10.23	degrees Celcius
   Normal daytime temperature:	-8.26	degrees Celcius
   Normal night temperature:	-12.33	degrees Celcius
   Maximum temperature:   	4.39	degrees Celcius
   Minimum temperature:   	-25.68	degrees Celcius
   Escape Velocity:		13.82	km/sec
   Molecular weight retained:	4.15 and above
   Surface acceleration:	1215.44	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.275
   Length of year:		783.22	days
   Length of day:		13.75	hours
   Boiling point of water:	136.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	10.07
   Ice cover percentage:	20.27
   liquids at surface:
				Ethanol      melts at -114  boils at 113
				Mercury      melts at -39   boils at 419
   gasses in atmosphere:
				Oxygen            1.5%  PP   49.3 mb
				Nitrogen         98.4%  PP 3334.0 mb


Planet 7	*gas giant*
   Distance from primary:	2.730	AU
   Mass:			128.359	Earth masses
   Equatorial radius:		46618.9	km
   Density:			1.808	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		46.86	km/sec
   Molecular weight retained:	0.36 and above
   Surface acceleration:	2355.27	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.467
   Length of year:		1575.97	days
   Length of day:		8.42	hours


Planet 8	*gas giant*
   Distance from primary:	6.481	AU
   Mass:			383.621	Earth masses
   Equatorial radius:		68948.4	km
   Density:			1.670	grams/cc
   Eccentricity of orbit:	0.246
   Escape Velocity:		66.62	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3218.05	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.459
   Length of year:		5760.56	days
   Length of day:		7.20	hours


Planet 9	*gas giant*
   Distance from primary:	11.393	AU
   Mass:			2.903	Earth masses
   Equatorial radius:		17389.8	km
   Density:			0.788	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		11.54	km/sec
   Molecular weight retained:	5.96 and above
   Surface acceleration:	382.80	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.463
   Length of year:		13434.91	days
   Length of day:		20.89	hours


Planet 10	*gas giant*
   Distance from primary:	16.820	AU
   Mass:			399.602	Earth masses
   Equatorial radius:		75546.1	km
   Density:			1.322	grams/cc
   Eccentricity of orbit:	0.086
   Escape Velocity:		64.95	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2792.18	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.477
   Length of year:		24086.55	days
   Length of day:		7.73	hours


Planet 11	*gas giant*
   Distance from primary:	22.376	AU
   Mass:			4.851	Earth masses
   Equatorial radius:		21367.7	km
   Density:			0.709	grams/cc
   Eccentricity of orbit:	0.124
   Escape Velocity:		13.46	km/sec
   Molecular weight retained:	4.38 and above
   Surface acceleration:	423.67	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.492
   Length of year:		36977.48	days
   Length of day:		19.86	hours


Planet 12	*gas giant*
   Distance from primary:	38.275	AU
   Mass:			0.860	Earth masses
   Equatorial radius:		13493.4	km
   Density:			0.500	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		7.13	km/sec
   Molecular weight retained:	15.61 and above
   Surface acceleration:	188.46	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.460
   Length of year:		82725.59	days
   Length of day:		29.77	hours


Planet 13	
   Distance from primary:	49.801	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		3441.0	km
   Density:			2.204	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.62	degrees Celcius
   Normal daytime temperature:	-224.63	degrees Celcius
   Normal night temperature:	-236.49	degrees Celcius
   Maximum temperature:   	-209.51	degrees Celcius
   Minimum temperature:   	-251.50	degrees Celcius
   Escape Velocity:		3.82	km/sec
   Molecular weight retained:	54.42 and above
   Surface acceleration:	211.96	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.141
   Length of year:		122778.37	days
   Length of day:		32.92	hours
   Boiling point of water:	-73.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


