                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048384
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6354 K
Stellar class: F7
Age: 1.504 billion years  (5.436 billion left on main sequence)
Habitable ecosphere radius: 1.259 AU

Planets present at:
1	  0.340 AU	no atmosphere
2	  0.956 AU	greenhouse
3	  1.469 AU	gas giant
4	  2.172 AU	gas giant
5	  3.488 AU	gas giant
6	  6.308 AU	gas giant
7	  9.759 AU	gas giant
8	 17.458 AU	gas giant
9	 23.833 AU	gas giant
10	 31.226 AU	gas giant
11	 46.707 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.340	AU
   Mass:			0.288	Earth masses
   Equatorial radius:		4256.9	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.199
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		252.80	degrees Celcius
   Normal daytime temperature:	468.74	degrees Celcius
   Normal night temperature:	-165.02	degrees Celcius
   Maximum temperature:   	472.76	degrees Celcius
   Minimum temperature:   	-179.55	degrees Celcius
   Escape Velocity:		7.35	km/sec
   Molecular weight retained:	14.71 and above
   Surface acceleration:	633.76	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.075
   Length of year:		69.16	days
   Length of day:		1109.96	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.956	AU
   Mass:			1.343	Earth masses
   Equatorial radius:		7048.2	km
   Density:			5.474	grams/cc
   Eccentricity of orbit:	0.167
   Surface gravity:		1.10	Earth gees
   Surface pressure:		170.701	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		455.64	degrees Celcius
   Maximum temperature:   	459.02	degrees Celcius
   Minimum temperature:   	450.24	degrees Celcius
   Escape Velocity:		12.33	km/sec
   Molecular weight retained:	5.22 and above
   Surface acceleration:	1078.34	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.510
   Length of year:		325.37	days
   Length of day:		14.91	hours
   Boiling point of water:	328.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1258
				Cesium       melts at 28    boils at 1303
				Gallium      melts at 30    boils at 4040
				Rubidium     melts at 39    boils at 1276
				Potassium    melts at 63    boils at 1401
				Sodium       melts at 98    boils at 1588
				Indium       melts at 157   boils at 3520
				Lithium      melts at 181   boils at 2338
				Selenium     melts at 217   boils at 1271
				Tin          melts at 232   boils at 4395
				Polonium     melts at 254   boils at 1718
				Bismuth      melts at 271   boils at 2688
				Thallium     melts at 304   boils at 2515
				Cadmium      melts at 321   boils at 1400
				Lead         melts at 328   boils at 2989
				Zinc         melts at 420   boils at 1629
				Tellurium    melts at 450   boils at 1763
   gasses in atmosphere:
				Sulfur           18.9%  PP 32216.3 mb
				Nitrogen         80.5%  PP 137498.6 mb
				Phosphorus        0.4%  PP  644.3 mb


Planet 3	*gas giant*
   Distance from primary:	1.469	AU
   Mass:			3.240	Earth masses
   Equatorial radius:		15121.4	km
   Density:			1.337	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		13.07	km/sec
   Molecular weight retained:	4.64 and above
   Surface acceleration:	565.13	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.488
   Length of year:		620.35	days
   Length of day:		17.20	hours


Planet 4	*gas giant*
   Distance from primary:	2.172	AU
   Mass:			37.507	Earth masses
   Equatorial radius:		31910.6	km
   Density:			1.647	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		30.62	km/sec
   Molecular weight retained:	0.85 and above
   Surface acceleration:	1468.87	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.486
   Length of year:		1115.03	days
   Length of day:		10.66	hours


Planet 5	*gas giant*
   Distance from primary:	3.488	AU
   Mass:			20.869	Earth masses
   Equatorial radius:		27978.1	km
   Density:			1.360	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		24.39	km/sec
   Molecular weight retained:	1.33 and above
   Surface acceleration:	1063.16	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.455
   Length of year:		2269.53	days
   Length of day:		12.53	hours


Planet 6	*gas giant*
   Distance from primary:	6.308	AU
   Mass:			6.685	Earth masses
   Equatorial radius:		21089.2	km
   Density:			1.017	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		15.90	km/sec
   Molecular weight retained:	3.14 and above
   Surface acceleration:	599.42	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.533
   Length of year:		5518.63	days
   Length of day:		16.69	hours


Planet 7	*gas giant*
   Distance from primary:	9.759	AU
   Mass:			363.631	Earth masses
   Equatorial radius:		70154.2	km
   Density:			1.503	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		64.30	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2946.41	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.546
   Length of year:		10613.53	days
   Length of day:		7.53	hours


Planet 8	*gas giant*
   Distance from primary:	17.458	AU
   Mass:			15.115	Earth masses
   Equatorial radius:		29123.2	km
   Density:			0.873	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		20.35	km/sec
   Molecular weight retained:	1.92 and above
   Surface acceleration:	710.67	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.522
   Length of year:		25408.96	days
   Length of day:		15.33	hours


Planet 9	*gas giant*
   Distance from primary:	23.833	AU
   Mass:			0.596	Earth masses
   Equatorial radius:		11641.5	km
   Density:			0.539	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		6.39	km/sec
   Molecular weight retained:	19.43 and above
   Surface acceleration:	175.45	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.465
   Length of year:		40527.89	days
   Length of day:		30.86	hours


Planet 10	*gas giant*
   Distance from primary:	31.226	AU
   Mass:			11.494	Earth masses
   Equatorial radius:		28222.6	km
   Density:			0.730	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		18.02	km/sec
   Molecular weight retained:	2.44 and above
   Surface acceleration:	575.48	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.482
   Length of year:		60781.66	days
   Length of day:		17.04	hours


Planet 11	
   Distance from primary:	46.707	AU
   Mass:			0.232	Earth masses
   Equatorial radius:		5296.8	km
   Density:			2.230	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.68	degrees Celcius
   Normal daytime temperature:	-223.52	degrees Celcius
   Normal night temperature:	-233.75	degrees Celcius
   Maximum temperature:   	-209.50	degrees Celcius
   Minimum temperature:   	-248.21	degrees Celcius
   Escape Velocity:		5.91	km/sec
   Molecular weight retained:	22.70 and above
   Surface acceleration:	330.04	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.143
   Length of year:		111191.26	days
   Length of day:		26.38	hours
   Boiling point of water:	-50.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


