                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950482ea
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6116 K
Stellar class: F9
Age: 4.565 billion years  (2.396 billion left on main sequence)
Habitable ecosphere radius: 1.256 AU

Planets present at:
1	  0.336 AU	no atmosphere
2	  0.442 AU	no atmosphere
3	  0.545 AU	no atmosphere
4	  0.752 AU	greenhouse
5	  1.371 AU	no atmosphere
6	  1.702 AU	gas giant
7	  2.956 AU	gas giant
8	  4.630 AU	gas giant
9	 12.591 AU	gas giant
10	 43.274 AU	gas giant



Planet 1	
   Distance from primary:	0.336	AU
   Mass:			0.032	Earth masses
   Equatorial radius:		2048.3	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.69	degrees Celcius
   Normal daytime temperature:	473.91	degrees Celcius
   Normal night temperature:	-178.82	degrees Celcius
   Maximum temperature:   	477.00	degrees Celcius
   Minimum temperature:   	-189.56	degrees Celcius
   Escape Velocity:		3.51	km/sec
   Molecular weight retained:	64.30 and above
   Surface acceleration:	301.37	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.077
   Length of year:		67.78	days
   Length of day:		1626.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.442	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		2327.9	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		187.40	degrees Celcius
   Normal daytime temperature:	390.73	degrees Celcius
   Normal night temperature:	-194.91	degrees Celcius
   Maximum temperature:   	394.01	degrees Celcius
   Minimum temperature:   	-205.15	degrees Celcius
   Escape Velocity:		4.00	km/sec
   Molecular weight retained:	49.73 and above
   Surface acceleration:	342.86	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.081
   Length of year:		102.23	days
   Length of day:		1996.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.545	AU
   Mass:			0.074	Earth masses
   Equatorial radius:		2709.3	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		144.47	degrees Celcius
   Maximum temperature:   	341.37	degrees Celcius
   Minimum temperature:   	-215.83	degrees Celcius
   Escape Velocity:		4.65	km/sec
   Molecular weight retained:	36.65 and above
   Surface acceleration:	399.68	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.053
   Length of year:		140.25	days
   Length of day:		2664.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.752	AU
   Mass:			1.459	Earth masses
   Equatorial radius:		7238.7	km
   Density:			5.487	grams/cc
   Eccentricity of orbit:	0.201
   Surface gravity:		1.13	Earth gees
   Surface pressure:		178.522	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		549.52	degrees Celcius
   Maximum temperature:   	552.65	degrees Celcius
   Minimum temperature:   	543.18	degrees Celcius
   Escape Velocity:		12.68	km/sec
   Molecular weight retained:	4.94 and above
   Surface acceleration:	1110.13	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.519
   Length of year:		227.32	days
   Length of day:		19.25	hours
   Boiling point of water:	331.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1266
				Cesium       melts at 28    boils at 1312
				Gallium      melts at 30    boils at 4063
				Rubidium     melts at 39    boils at 1284
				Potassium    melts at 63    boils at 1410
				Sodium       melts at 98    boils at 1598
				Indium       melts at 157   boils at 3540
				Lithium      melts at 181   boils at 2352
				Selenium     melts at 217   boils at 1279
				Tin          melts at 232   boils at 4420
				Polonium     melts at 254   boils at 1728
				Bismuth      melts at 271   boils at 2704
				Thallium     melts at 304   boils at 2530
				Cadmium      melts at 321   boils at 1409
				Lead         melts at 328   boils at 3007
				Zinc         melts at 420   boils at 1639
				Tellurium    melts at 450   boils at 1774
   gasses in atmosphere:
				Sulfur           21.3%  PP 38026.4 mb
				Nitrogen         78.1%  PP 139369.3 mb
				Phosphorus        0.4%  PP  756.3 mb


Planet 5	
   Distance from primary:	1.371	AU
   Mass:			0.105	Earth masses
   Equatorial radius:		3052.1	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.009	Earth atmospheres
   Surface temperature:		-26.76	degrees Celcius
   Normal daytime temperature:	-2.55	degrees Celcius
   Normal night temperature:	-51.25	degrees Celcius
   Maximum temperature:   	22.79	degrees Celcius
   Minimum temperature:   	-77.15	degrees Celcius
   Escape Velocity:		5.25	km/sec
   Molecular weight retained:	28.84 and above
   Surface acceleration:	451.00	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.330
   Length of year:		559.33	days
   Length of day:		24.03	hours
   Boiling point of water:	3.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	38.27
   liquids at surface:
				Ethanol      melts at -114  boils at -11
				Mercury      melts at -39   boils at 196
   gasses in atmosphere:
				CarbonDioxide    43.3%  PP    3.8 mb
				Ozone            51.2%  PP    4.4 mb
				Chlorine          0.4%  PP    0.0 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           4.3%  PP    0.4 mb
				Xenon             0.6%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	1.702	AU
   Mass:			26.432	Earth masses
   Equatorial radius:		28238.5	km
   Density:			1.675	grams/cc
   Eccentricity of orbit:	0.089
   Escape Velocity:		27.32	km/sec
   Molecular weight retained:	1.06 and above
   Surface acceleration:	1321.84	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.492
   Length of year:		773.64	days
   Length of day:		11.24	hours


Planet 7	*gas giant*
   Distance from primary:	2.956	AU
   Mass:			5.737	Earth masses
   Equatorial radius:		18937.2	km
   Density:			1.205	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		15.54	km/sec
   Molecular weight retained:	3.29 and above
   Surface acceleration:	637.95	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.540
   Length of year:		1770.79	days
   Length of day:		16.18	hours


Planet 8	*gas giant*
   Distance from primary:	4.630	AU
   Mass:			55.418	Earth masses
   Equatorial radius:		38092.5	km
   Density:			1.431	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		34.06	km/sec
   Molecular weight retained:	0.68 and above
   Surface acceleration:	1523.03	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.482
   Length of year:		3471.14	days
   Length of day:		10.47	hours


Planet 9	*gas giant*
   Distance from primary:	12.591	AU
   Mass:			1902.899	Earth masses
   Equatorial radius:		116139.6	km
   Density:			1.733	grams/cc
   Eccentricity of orbit:	0.333
   Escape Velocity:		114.31	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5625.93	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.548
   Length of year:		15528.70	days
   Length of day:		5.45	hours


Planet 10	*gas giant*
   Distance from primary:	43.274	AU
   Mass:			2.119	Earth masses
   Equatorial radius:		17713.8	km
   Density:			0.544	grams/cc
   Eccentricity of orbit:	0.153
   Escape Velocity:		9.77	km/sec
   Molecular weight retained:	8.32 and above
   Surface acceleration:	269.36	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.520
   Length of year:		99198.19	days
   Length of day:		24.90	hours


