                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048508
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6353 K
Stellar class: F7
Age: 2.188 billion years  (4.702 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.433 AU	no atmosphere
2	  0.741 AU	no atmosphere
3	  1.839 AU	gas giant
4	  3.157 AU	gas giant
5	  5.832 AU	gas giant
6	 10.125 AU	gas giant
7	 19.730 AU	gas giant
8	 32.150 AU	no atmosphere
9	 40.252 AU	gas giant
10	 46.987 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.433	AU
   Mass:			0.934	Earth masses
   Equatorial radius:		6263.2	km
   Density:			5.425	grams/cc
   Eccentricity of orbit:	0.406
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.77	degrees Celcius
   Normal daytime temperature:	394.49	degrees Celcius
   Normal night temperature:	-172.32	degrees Celcius
   Maximum temperature:   	399.66	degrees Celcius
   Minimum temperature:   	-189.81	degrees Celcius
   Escape Velocity:		10.91	km/sec
   Molecular weight retained:	6.67 and above
   Surface acceleration:	949.53	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.087
   Length of year:		99.09	days
   Length of day:		1004.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.741	AU
   Mass:			0.054	Earth masses
   Equatorial radius:		2444.8	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		85.10	degrees Celcius
   Maximum temperature:   	267.40	degrees Celcius
   Minimum temperature:   	-226.97	degrees Celcius
   Escape Velocity:		4.20	km/sec
   Molecular weight retained:	45.06 and above
   Surface acceleration:	360.25	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.064
   Length of year:		222.16	days
   Length of day:		5331.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	*gas giant*
   Distance from primary:	1.839	AU
   Mass:			4.083	Earth masses
   Equatorial radius:		16475.3	km
   Density:			1.303	grams/cc
   Eccentricity of orbit:	0.306
   Escape Velocity:		14.06	km/sec
   Molecular weight retained:	4.02 and above
   Surface acceleration:	599.90	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.484
   Length of year:		867.73	days
   Length of day:		16.69	hours


Planet 4	*gas giant*
   Distance from primary:	3.157	AU
   Mass:			11.383	Earth masses
   Equatorial radius:		23240.7	km
   Density:			1.294	grams/cc
   Eccentricity of orbit:	0.155
   Escape Velocity:		19.76	km/sec
   Molecular weight retained:	2.03 and above
   Surface acceleration:	840.39	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.515
   Length of year:		1951.62	days
   Length of day:		14.10	hours


Planet 5	*gas giant*
   Distance from primary:	5.832	AU
   Mass:			1507.756	Earth masses
   Equatorial radius:		101720.9	km
   Density:			2.044	grams/cc
   Eccentricity of orbit:	0.120
   Escape Velocity:		108.73	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5810.99	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.531
   Length of year:		4891.40	days
   Length of day:		5.36	hours


Planet 6	*gas giant*
   Distance from primary:	10.125	AU
   Mass:			97.581	Earth masses
   Equatorial radius:		47928.5	km
   Density:			1.265	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		40.30	km/sec
   Molecular weight retained:	0.49 and above
   Surface acceleration:	1694.02	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.508
   Length of year:		11210.71	days
   Length of day:		9.93	hours


Planet 7	*gas giant*
   Distance from primary:	19.730	AU
   Mass:			57.291	Earth masses
   Equatorial radius:		43379.0	km
   Density:			1.001	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		32.46	km/sec
   Molecular weight retained:	0.75 and above
   Surface acceleration:	1214.13	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.545
   Length of year:		30495.26	days
   Length of day:		11.73	hours


Planet 8	
   Distance from primary:	32.150	AU
   Mass:			0.215	Earth masses
   Equatorial radius:		5166.7	km
   Density:			2.227	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-219.72	degrees Celcius
   Normal daytime temperature:	-213.45	degrees Celcius
   Normal night temperature:	-225.93	degrees Celcius
   Maximum temperature:   	-201.71	degrees Celcius
   Minimum temperature:   	-238.45	degrees Celcius
   Escape Velocity:		5.76	km/sec
   Molecular weight retained:	23.89 and above
   Surface acceleration:	321.62	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.160
   Length of year:		63437.33	days
   Length of day:		26.72	hours
   Boiling point of water:	-50.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 9	*gas giant*
   Distance from primary:	40.252	AU
   Mass:			1.310	Earth masses
   Equatorial radius:		15292.1	km
   Density:			0.523	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		8.26	km/sec
   Molecular weight retained:	11.62 and above
   Surface acceleration:	223.31	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.470
   Length of year:		88869.91	days
   Length of day:		27.35	hours


Planet 10	
   Distance from primary:	46.987	AU
   Mass:			0.093	Earth masses
   Equatorial radius:		3911.6	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.07	degrees Celcius
   Normal daytime temperature:	-223.21	degrees Celcius
   Normal night temperature:	-234.83	degrees Celcius
   Maximum temperature:   	-212.35	degrees Celcius
   Minimum temperature:   	-246.18	degrees Celcius
   Escape Velocity:		4.35	km/sec
   Molecular weight retained:	42.01 and above
   Surface acceleration:	241.53	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.152
   Length of year:		112086.27	days
   Length of day:		30.84	hours
   Boiling point of water:	-66.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


