                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950484b3
Stellar mass: 1.10 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6411 K
Stellar class: F7
Age: 5.179 billion years  (1.721 billion left on main sequence)
Habitable ecosphere radius: 1.263 AU

Planets present at:
1	  0.344 AU	no atmosphere
2	  0.640 AU	no atmosphere
3	  0.820 AU	greenhouse
4	  0.946 AU	no atmosphere
5	  2.096 AU	gas giant
6	  3.196 AU	gas giant
7	  5.893 AU	gas giant
8	 16.658 AU	gas giant
9	 28.622 AU	gas giant
10	 49.508 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.344	AU
   Mass:			0.222	Earth masses
   Equatorial radius:		3905.1	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		250.09	degrees Celcius
   Normal daytime temperature:	466.31	degrees Celcius
   Normal night temperature:	-172.94	degrees Celcius
   Maximum temperature:   	469.79	degrees Celcius
   Minimum temperature:   	-185.22	degrees Celcius
   Escape Velocity:		6.73	km/sec
   Molecular weight retained:	17.52 and above
   Surface acceleration:	579.96	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.081
   Length of year:		70.22	days
   Length of day:		1331.46	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.640	AU
   Mass:			1/102.5	Earth masses
   Equatorial radius:		1383.6	km
   Density:			5.254	grams/cc
   Eccentricity of orbit:	0.169
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		112.45	degrees Celcius
   Maximum temperature:   	301.59	degrees Celcius
   Minimum temperature:   	-221.87	degrees Celcius
   Escape Velocity:		2.37	km/sec
   Molecular weight retained:	141.19 and above
   Surface acceleration:	203.18	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.062
   Length of year:		178.16	days
   Length of day:		3040.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	0.820	AU
   Mass:			1.514	Earth masses
   Equatorial radius:		7325.8	km
   Density:			5.494	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		1.15	Earth gees
   Surface pressure:		222.865	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		570.39	degrees Celcius
   Maximum temperature:   	572.87	degrees Celcius
   Minimum temperature:   	564.56	degrees Celcius
   Escape Velocity:		12.84	km/sec
   Molecular weight retained:	4.82 and above
   Surface acceleration:	1124.75	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.458
   Length of year:		258.44	days
   Length of day:		17.14	hours
   Boiling point of water:	347.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1308
				Cesium       melts at 28    boils at 1355
				Gallium      melts at 30    boils at 4182
				Rubidium     melts at 39    boils at 1327
				Potassium    melts at 63    boils at 1456
				Sodium       melts at 98    boils at 1649
				Indium       melts at 157   boils at 3644
				Lithium      melts at 181   boils at 2424
				Selenium     melts at 217   boils at 1322
				Tin          melts at 232   boils at 4548
				Polonium     melts at 254   boils at 1783
				Bismuth      melts at 271   boils at 2785
				Thallium     melts at 304   boils at 2607
				Cadmium      melts at 321   boils at 1455
				Lead         melts at 328   boils at 3096
				Zinc         melts at 420   boils at 1691
				Tellurium    melts at 450   boils at 1829
   gasses in atmosphere:
				Sulfur           21.3%  PP 47525.3 mb
				Nitrogen         78.1%  PP 173949.5 mb
				Phosphorus        0.4%  PP  945.1 mb


Planet 4	
   Distance from primary:	0.946	AU
   Mass:			0.151	Earth masses
   Equatorial radius:		3436.2	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.099
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		44.32	degrees Celcius
   Normal daytime temperature:	96.87	degrees Celcius
   Normal night temperature:	-9.31	degrees Celcius
   Maximum temperature:   	127.69	degrees Celcius
   Minimum temperature:   	-40.87	degrees Celcius
   Escape Velocity:		5.91	km/sec
   Molecular weight retained:	22.70 and above
   Surface acceleration:	508.83	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.059
   Length of year:		320.13	days
   Length of day:		40.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 5	*gas giant*
   Distance from primary:	2.096	AU
   Mass:			3.085	Earth masses
   Equatorial radius:		15348.8	km
   Density:			1.217	grams/cc
   Eccentricity of orbit:	0.171
   Escape Velocity:		12.66	km/sec
   Molecular weight retained:	4.95 and above
   Surface acceleration:	522.14	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.524
   Length of year:		1055.97	days
   Length of day:		17.89	hours


Planet 6	*gas giant*
   Distance from primary:	3.196	AU
   Mass:			29.102	Earth masses
   Equatorial radius:		30594.6	km
   Density:			1.450	grams/cc
   Eccentricity of orbit:	0.091
   Escape Velocity:		27.54	km/sec
   Molecular weight retained:	1.05 and above
   Surface acceleration:	1239.84	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.450
   Length of year:		1989.02	days
   Length of day:		11.61	hours


Planet 7	*gas giant*
   Distance from primary:	5.893	AU
   Mass:			1096.282	Earth masses
   Equatorial radius:		92780.2	km
   Density:			1.959	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		97.08	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5078.69	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.493
   Length of year:		4972.37	days
   Length of day:		5.74	hours


Planet 8	*gas giant*
   Distance from primary:	16.658	AU
   Mass:			114.938	Earth masses
   Equatorial radius:		52406.3	km
   Density:			1.139	grams/cc
   Eccentricity of orbit:	0.128
   Escape Velocity:		41.82	km/sec
   Molecular weight retained:	0.45 and above
   Surface acceleration:	1668.92	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.452
   Length of year:		23660.48	days
   Length of day:		10.00	hours


Planet 9	*gas giant*
   Distance from primary:	28.622	AU
   Mass:			23.091	Earth masses
   Equatorial radius:		34330.1	km
   Density:			0.814	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		23.16	km/sec
   Molecular weight retained:	1.48 and above
   Surface acceleration:	781.32	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.515
   Length of year:		53296.96	days
   Length of day:		14.62	hours


Planet 10	
   Distance from primary:	49.508	AU
   Mass:			0.180	Earth masses
   Equatorial radius:		4869.2	km
   Density:			2.223	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.84	degrees Celcius
   Normal daytime temperature:	-224.61	degrees Celcius
   Normal night temperature:	-234.96	degrees Celcius
   Maximum temperature:   	-207.92	degrees Celcius
   Minimum temperature:   	-251.57	degrees Celcius
   Escape Velocity:		5.43	km/sec
   Molecular weight retained:	26.95 and above
   Surface acceleration:	302.46	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.138
   Length of year:		121249.87	days
   Length of day:		27.56	hours
   Boiling point of water:	-53.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


