                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047afd
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.50
Stellar temperature: 6329 K
Stellar class: F7
Age: 5.544 billion years  (1.691 billion left on main sequence)
Habitable ecosphere radius: 1.226 AU

Planets present at:
1	  0.333 AU	no atmosphere
2	  0.447 AU	no atmosphere
3	  0.496 AU	no atmosphere
4	  0.521 AU	no atmosphere
5	  0.697 AU	no atmosphere
6	  0.849 AU	greenhouse
7	  1.125 AU	greenhouse
8	  1.751 AU	gas giant
9	  2.951 AU	gas giant
10	  6.252 AU	gas giant
11	  9.821 AU	gas giant
12	 16.452 AU	gas giant
13	 23.802 AU	gas giant
14	 43.461 AU	gas giant



Planet 1	
   Distance from primary:	0.333	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		2340.6	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		250.09	degrees Celcius
   Normal daytime temperature:	467.05	degrees Celcius
   Normal night temperature:	-179.46	degrees Celcius
   Maximum temperature:   	470.02	degrees Celcius
   Minimum temperature:   	-189.66	degrees Celcius
   Escape Velocity:		4.02	km/sec
   Molecular weight retained:	49.19 and above
   Surface acceleration:	344.75	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.087
   Length of year:		67.20	days
   Length of day:		1612.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.447	AU
   Mass:			0.029	Earth masses
   Equatorial radius:		1982.8	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		181.85	degrees Celcius
   Maximum temperature:   	387.30	degrees Celcius
   Minimum temperature:   	-208.94	degrees Celcius
   Escape Velocity:		3.40	km/sec
   Molecular weight retained:	68.63 and above
   Surface acceleration:	291.66	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.057
   Length of year:		104.72	days
   Length of day:		2513.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.496	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		1536.9	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.42	degrees Celcius
   Maximum temperature:   	356.03	degrees Celcius
   Minimum temperature:   	-214.46	degrees Celcius
   Escape Velocity:		2.63	km/sec
   Molecular weight retained:	114.39 and above
   Surface acceleration:	225.77	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.078
   Length of year:		122.41	days
   Length of day:		2937.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.521	AU
   Mass:			0.339	Earth masses
   Equatorial radius:		4493.2	km
   Density:			5.336	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.68	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		146.44	degrees Celcius
   Maximum temperature:   	343.74	degrees Celcius
   Minimum temperature:   	-216.71	degrees Celcius
   Escape Velocity:		7.76	km/sec
   Molecular weight retained:	13.18 and above
   Surface acceleration:	670.12	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.073
   Length of year:		131.86	days
   Length of day:		3164.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	0.697	AU
   Mass:			1/252.6	Earth masses
   Equatorial radius:		1024.7	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		88.87	degrees Celcius
   Maximum temperature:   	272.01	degrees Celcius
   Minimum temperature:   	-226.45	degrees Celcius
   Escape Velocity:		1.76	km/sec
   Molecular weight retained:	257.59 and above
   Surface acceleration:	150.37	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.082
   Length of year:		203.85	days
   Length of day:		4892.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 6	
   Distance from primary:	0.849	AU
   Mass:			0.306	Earth masses
   Equatorial radius:		4343.4	km
   Density:			5.330	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.66	Earth gees
   Surface pressure:		9.516	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		67.43	degrees Celcius
   Maximum temperature:   	80.09	degrees Celcius
   Minimum temperature:   	53.71	degrees Celcius
   Escape Velocity:		7.50	km/sec
   Molecular weight retained:	14.12 and above
   Surface acceleration:	647.04	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.611
   Length of year:		274.23	days
   Length of day:		39.83	hours
   Boiling point of water:	174.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 149
				Mercury      melts at -39   boils at 483
				Water        melts at 0     boils at 174
				Francium     melts at 27    boils at 866
				Cesium       melts at 28    boils at 900
				Gallium      melts at 30    boils at 2937
				Rubidium     melts at 39    boils at 880
				Phosphorus   melts at 44    boils at 391
				Potassium    melts at 63    boils at 973
   gasses in atmosphere:
				CarbonDioxide    41.6%  PP 3961.8 mb
				Methane           4.6%  PP  436.0 mb
				Ammonia           6.6%  PP  631.8 mb
				Ozone            43.4%  PP 4126.7 mb
				Argon             0.2%  PP   16.0 mb
				Neon              0.5%  PP   43.3 mb
				Krypton           2.8%  PP  266.5 mb
				Xenon             0.4%  PP   33.3 mb


Planet 7	
   Distance from primary:	1.125	AU
   Mass:			0.735	Earth masses
   Equatorial radius:		5791.4	km
   Density:			5.398	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.89	Earth gees
   Surface pressure:		47.743	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		183.97	degrees Celcius
   Maximum temperature:   	189.71	degrees Celcius
   Minimum temperature:   	177.74	degrees Celcius
   Escape Velocity:		10.06	km/sec
   Molecular weight retained:	7.84 and above
   Surface acceleration:	873.70	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.420
   Length of year:		418.01	days
   Length of day:		17.02	hours
   Boiling point of water:	249.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 609
				Francium     melts at 27    boils at 1056
				Cesium       melts at 28    boils at 1096
				Gallium      melts at 30    boils at 3472
				Rubidium     melts at 39    boils at 1072
				Phosphorus   melts at 44    boils at 502
				Potassium    melts at 63    boils at 1181
				Sodium       melts at 98    boils at 1343
				Sulfur       melts at 113   boils at 732
				Iodine       melts at 114   boils at 368
				Indium       melts at 157   boils at 3020
				Lithium      melts at 181   boils at 1994
   gasses in atmosphere:
				Nitrogen         99.6%  PP 47568.9 mb
				CarbonDioxide     0.1%  PP   39.0 mb
				Ozone             0.1%  PP   35.4 mb
				Ethanol           0.1%  PP   39.8 mb


Planet 8	*gas giant*
   Distance from primary:	1.751	AU
   Mass:			33.146	Earth masses
   Equatorial radius:		30298.7	km
   Density:			1.700	grams/cc
   Eccentricity of orbit:	0.101
   Escape Velocity:		29.54	km/sec
   Molecular weight retained:	0.91 and above
   Surface acceleration:	1439.88	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.484
   Length of year:		811.28	days
   Length of day:		10.77	hours


Planet 9	*gas giant*
   Distance from primary:	2.951	AU
   Mass:			14.070	Earth masses
   Equatorial radius:		24647.8	km
   Density:			1.341	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		21.34	km/sec
   Molecular weight retained:	1.74 and above
   Surface acceleration:	923.58	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.518
   Length of year:		1775.41	days
   Length of day:		13.45	hours


Planet 10	*gas giant*
   Distance from primary:	6.252	AU
   Mass:			1173.139	Earth masses
   Equatorial radius:		95336.6	km
   Density:			1.932	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		99.07	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5147.18	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.492
   Length of year:		5466.78	days
   Length of day:		5.70	hours


Planet 11	*gas giant*
   Distance from primary:	9.821	AU
   Mass:			1.870	Earth masses
   Equatorial radius:		15124.8	km
   Density:			0.771	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		9.93	km/sec
   Molecular weight retained:	8.05 and above
   Surface acceleration:	326.06	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.514
   Length of year:		10779.12	days
   Length of day:		22.63	hours


Planet 12	*gas giant*
   Distance from primary:	16.452	AU
   Mass:			20.321	Earth masses
   Equatorial radius:		31661.3	km
   Density:			0.914	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		22.63	km/sec
   Molecular weight retained:	1.55 and above
   Surface acceleration:	808.38	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.461
   Length of year:		23371.51	days
   Length of day:		14.38	hours


Planet 13	*gas giant*
   Distance from primary:	23.802	AU
   Mass:			9.368	Earth masses
   Equatorial radius:		26050.1	km
   Density:			0.756	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		16.94	km/sec
   Molecular weight retained:	2.77 and above
   Surface acceleration:	550.51	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.489
   Length of year:		40670.48	days
   Length of day:		17.42	hours


Planet 14	*gas giant*
   Distance from primary:	43.461	AU
   Mass:			0.603	Earth masses
   Equatorial radius:		12306.0	km
   Density:			0.462	grams/cc
   Eccentricity of orbit:	0.097
   Escape Velocity:		6.25	km/sec
   Molecular weight retained:	20.31 and above
   Surface acceleration:	158.77	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.488
   Length of year:		100351.39	days
   Length of day:		32.44	hours


