                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481d8
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6120 K
Stellar class: F9
Age: 2.247 billion years  (4.750 billion left on main sequence)
Habitable ecosphere radius: 1.252 AU

Planets present at:
1	  0.396 AU	no atmosphere
2	  0.569 AU	no atmosphere
3	  1.064 AU	greenhouse
4	  1.651 AU	cold
5	  2.436 AU	cold
6	  4.024 AU	gas giant
7	 10.747 AU	gas giant
8	 17.962 AU	gas giant
9	 30.208 AU	no atmosphere
10	 44.637 AU	gas giant



Planet 1	
   Distance from primary:	0.396	AU
   Mass:			0.050	Earth masses
   Equatorial radius:		2376.8	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		215.96	degrees Celcius
   Normal daytime temperature:	426.03	degrees Celcius
   Normal night temperature:	-191.57	degrees Celcius
   Maximum temperature:   	429.14	degrees Celcius
   Minimum temperature:   	-201.64	degrees Celcius
   Escape Velocity:		4.08	km/sec
   Molecular weight retained:	47.69 and above
   Surface acceleration:	350.13	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.054
   Length of year:		86.84	days
   Length of day:		2084.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.569	AU
   Mass:			0.618	Earth masses
   Equatorial radius:		5473.3	km
   Density:			5.381	grams/cc
   Eccentricity of orbit:	0.164
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		131.66	degrees Celcius
   Maximum temperature:   	325.46	degrees Celcius
   Minimum temperature:   	-217.55	degrees Celcius
   Escape Velocity:		9.49	km/sec
   Molecular weight retained:	8.81 and above
   Surface acceleration:	823.17	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.082
   Length of year:		149.81	days
   Length of day:		2582.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.064	AU
   Mass:			1.465	Earth masses
   Equatorial radius:		7249.0	km
   Density:			5.488	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		1.13	Earth gees
   Surface pressure:		175.156	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		443.24	degrees Celcius
   Maximum temperature:   	446.47	degrees Celcius
   Minimum temperature:   	438.12	degrees Celcius
   Escape Velocity:		12.70	km/sec
   Molecular weight retained:	4.92 and above
   Surface acceleration:	1111.85	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.437
   Length of year:		382.49	days
   Length of day:		14.60	hours
   Boiling point of water:	330.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1263
				Cesium       melts at 28    boils at 1308
				Gallium      melts at 30    boils at 4053
				Rubidium     melts at 39    boils at 1281
				Potassium    melts at 63    boils at 1406
				Sodium       melts at 98    boils at 1594
				Sulfur       melts at 113   boils at 888
				Indium       melts at 157   boils at 3531
				Lithium      melts at 181   boils at 2346
				Selenium     melts at 217   boils at 1276
				Tin          melts at 232   boils at 4409
				Polonium     melts at 254   boils at 1724
				Bismuth      melts at 271   boils at 2697
				Thallium     melts at 304   boils at 2524
				Cadmium      melts at 321   boils at 1405
				Lead         melts at 328   boils at 2999
				Zinc         melts at 420   boils at 1635
   gasses in atmosphere:
				Nitrogen         99.3%  PP 173918.5 mb
				Phosphorus        0.5%  PP  813.6 mb


Planet 4	
   Distance from primary:	1.651	AU
   Mass:			0.920	Earth masses
   Equatorial radius:		6231.6	km
   Density:			5.423	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.96	Earth gees
   Surface pressure:		0.727	Earth atmospheres
   Surface temperature:		-59.42	degrees Celcius
   Normal daytime temperature:	-55.59	degrees Celcius
   Normal night temperature:	-63.45	degrees Celcius
   Maximum temperature:   	-36.63	degrees Celcius
   Minimum temperature:   	-83.73	degrees Celcius
   Escape Velocity:		10.85	km/sec
   Molecular weight retained:	6.74 and above
   Surface acceleration:	944.42	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.640
   Length of year:		739.83	days
   Length of day:		15.62	hours
   Boiling point of water:	91.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.22
   Ice cover percentage:	88.23
   liquids at surface:
				Ethanol      melts at -114  boils at 70
				Chlorine     melts at -101  boils at -39
				Ammonia      melts at -78   boils at -39
   gasses in atmosphere:
				Oxygen           15.5%  PP  112.8 mb
				Nitrogen         84.4%  PP  613.1 mb


Planet 5	
   Distance from primary:	2.436	AU
   Mass:			1.008	Earth masses
   Equatorial radius:		6420.9	km
   Density:			5.434	grams/cc
   Eccentricity of orbit:	0.146
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.784	Earth atmospheres
   Surface temperature:		-97.64	degrees Celcius
   Normal daytime temperature:	-94.66	degrees Celcius
   Normal night temperature:	-100.79	degrees Celcius
   Maximum temperature:   	-74.96	degrees Celcius
   Minimum temperature:   	-122.05	degrees Celcius
   Escape Velocity:		11.19	km/sec
   Molecular weight retained:	6.34 and above
   Surface acceleration:	975.14	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.648
   Length of year:		1325.48	days
   Length of day:		15.35	hours
   Boiling point of water:	93.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	81.74
   liquids at surface:
				Ethanol      melts at -114  boils at 72
				Chlorine     melts at -101  boils at -38
   gasses in atmosphere:
				Oxygen           13.4%  PP  105.3 mb
				Nitrogen         86.5%  PP  677.7 mb


Planet 6	*gas giant*
   Distance from primary:	4.024	AU
   Mass:			629.267	Earth masses
   Equatorial radius:		76497.8	km
   Density:			2.006	grams/cc
   Eccentricity of orbit:	0.209
   Escape Velocity:		81.00	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4288.21	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.458
   Length of year:		2812.78	days
   Length of day:		6.24	hours


Planet 7	*gas giant*
   Distance from primary:	10.747	AU
   Mass:			1015.482	Earth masses
   Equatorial radius:		95459.3	km
   Density:			1.666	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		92.11	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4444.01	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.479
   Length of year:		12268.96	days
   Length of day:		6.13	hours


Planet 8	*gas giant*
   Distance from primary:	17.962	AU
   Mass:			37.266	Earth masses
   Equatorial radius:		37997.9	km
   Density:			0.969	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		27.97	km/sec
   Molecular weight retained:	1.01 and above
   Surface acceleration:	1029.28	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.473
   Length of year:		26543.34	days
   Length of day:		12.74	hours


Planet 9	
   Distance from primary:	30.208	AU
   Mass:			0.046	Earth masses
   Equatorial radius:		3104.6	km
   Density:			2.201	grams/cc
   Eccentricity of orbit:	0.141
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-218.56	degrees Celcius
   Normal daytime temperature:	-210.52	degrees Celcius
   Normal night temperature:	-226.53	degrees Celcius
   Maximum temperature:   	-193.49	degrees Celcius
   Minimum temperature:   	-243.81	degrees Celcius
   Escape Velocity:		3.44	km/sec
   Molecular weight retained:	66.96 and above
   Surface acceleration:	190.94	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.155
   Length of year:		57896.37	days
   Length of day:		34.68	hours
   Boiling point of water:	-76.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05
   liquids at surface:
				Fluorine     melts at -220  boils at -217


Planet 10	*gas giant*
   Distance from primary:	44.637	AU
   Mass:			1.594	Earth masses
   Equatorial radius:		16348.7	km
   Density:			0.521	grams/cc
   Eccentricity of orbit:	0.154
   Escape Velocity:		8.82	km/sec
   Molecular weight retained:	10.21 and above
   Surface acceleration:	237.86	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.475
   Length of year:		103992.83	days
   Length of day:		26.50	hours


