                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ee6
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6151 K
Stellar class: F8
Age: 3.116 billion years  (3.982 billion left on main sequence)
Habitable ecosphere radius: 1.241 AU

Planets present at:
1	  0.405 AU	no atmosphere
2	  0.567 AU	no atmosphere
3	  0.784 AU	no atmosphere
4	  1.137 AU	greenhouse
5	  1.488 AU	
6	  2.381 AU	gas giant
7	  8.473 AU	gas giant
8	 24.740 AU	gas giant
9	 46.226 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.405	AU
   Mass:			0.153	Earth masses
   Equatorial radius:		3455.9	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		207.29	degrees Celcius
   Normal daytime temperature:	414.58	degrees Celcius
   Normal night temperature:	-186.22	degrees Celcius
   Maximum temperature:   	418.04	degrees Celcius
   Minimum temperature:   	-197.57	degrees Celcius
   Escape Velocity:		5.95	km/sec
   Molecular weight retained:	22.44 and above
   Surface acceleration:	511.80	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.062
   Length of year:		90.03	days
   Length of day:		1601.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.567	AU
   Mass:			0.506	Earth masses
   Equatorial radius:		5125.1	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		132.85	degrees Celcius
   Maximum temperature:   	326.99	degrees Celcius
   Minimum temperature:   	-219.91	degrees Celcius
   Escape Velocity:		8.87	km/sec
   Molecular weight retained:	10.08 and above
   Surface acceleration:	768.35	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.063
   Length of year:		149.07	days
   Length of day:		3577.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.784	AU
   Mass:			0.198	Earth masses
   Equatorial radius:		3761.9	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.182
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		70.94	degrees Celcius
   Normal daytime temperature:	152.03	degrees Celcius
   Normal night temperature:	-14.37	degrees Celcius
   Maximum temperature:   	182.17	degrees Celcius
   Minimum temperature:   	-47.24	degrees Celcius
   Escape Velocity:		6.48	km/sec
   Molecular weight retained:	18.90 and above
   Surface acceleration:	558.18	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.074
   Length of year:		242.73	days
   Length of day:		65.98	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.137	AU
   Mass:			0.667	Earth masses
   Equatorial radius:		5611.4	km
   Density:			5.388	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.86	Earth gees
   Surface pressure:		35.927	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		144.16	degrees Celcius
   Maximum temperature:   	150.58	degrees Celcius
   Minimum temperature:   	137.32	degrees Celcius
   Escape Velocity:		9.74	km/sec
   Molecular weight retained:	8.37 and above
   Surface acceleration:	845.05	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.546
   Length of year:		423.53	days
   Length of day:		16.95	hours
   Boiling point of water:	234.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 583
				Francium     melts at 27    boils at 1019
				Cesium       melts at 28    boils at 1057
				Gallium      melts at 30    boils at 3365
				Rubidium     melts at 39    boils at 1033
				Phosphorus   melts at 44    boils at 480
				Potassium    melts at 63    boils at 1139
				Sodium       melts at 98    boils at 1297
				Sulfur       melts at 113   boils at 703
				Iodine       melts at 114   boils at 350
   gasses in atmosphere:
				Nitrogen         99.6%  PP 35797.9 mb
				CarbonDioxide     0.1%  PP   27.6 mb
				Ozone             0.1%  PP   26.9 mb
				Ethanol           0.1%  PP   28.1 mb


Planet 5	
   Distance from primary:	1.488	AU
   Mass:			0.858	Earth masses
   Equatorial radius:		6091.3	km
   Density:			5.415	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.94	Earth gees
   Surface pressure:		0.734	Earth atmospheres
   Surface temperature:		4.33	degrees Celcius
   Normal daytime temperature:	9.33	degrees Celcius
   Normal night temperature:	-0.96	degrees Celcius
   Maximum temperature:   	30.66	degrees Celcius
   Minimum temperature:   	-23.53	degrees Celcius
   Escape Velocity:		10.60	km/sec
   Molecular weight retained:	7.07 and above
   Surface acceleration:	921.77	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.156
   Length of year:		634.01	days
   Length of day:		15.86	hours
   Boiling point of water:	91.7	degrees Celcius
   Hydrosphere percentage:	66.68
   Cloud cover percentage:	22.70
   Ice cover percentage:	5.51
   liquids at surface:
				Ethanol      melts at -114  boils at 71
				Mercury      melts at -39   boils at 343
				Bromine      melts at -7    boils at 52
				Water        melts at 0     boils at 92
   gasses in atmosphere:
				Oxygen           33.3%  PP  244.7 mb
				Nitrogen         66.5%  PP  488.4 mb


Planet 6	*gas giant*
   Distance from primary:	2.381	AU
   Mass:			123.051	Earth masses
   Equatorial radius:		45526.5	km
   Density:			1.861	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		46.43	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	2367.53	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.479
   Length of year:		1283.39	days
   Length of day:		8.40	hours


Planet 7	*gas giant*
   Distance from primary:	8.473	AU
   Mass:			2409.594	Earth masses
   Equatorial radius:		120501.8	km
   Density:			1.965	grams/cc
   Eccentricity of orbit:	0.287
   Escape Velocity:		126.29	km/sec
   Molecular weight retained:	0.05 and above
   Surface acceleration:	6617.53	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.502
   Length of year:		8587.62	days
   Length of day:		5.02	hours


Planet 8	*gas giant*
   Distance from primary:	24.740	AU
   Mass:			61.580	Earth masses
   Equatorial radius:		45216.3	km
   Density:			0.950	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		32.96	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1201.12	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.487
   Length of year:		42988.42	days
   Length of day:		11.79	hours


Planet 9	*gas giant*
   Distance from primary:	46.226	AU
   Mass:			0.519	Earth masses
   Equatorial radius:		11830.9	km
   Density:			0.448	grams/cc
   Eccentricity of orbit:	0.100
   Escape Velocity:		5.92	km/sec
   Molecular weight retained:	22.67 and above
   Surface acceleration:	147.98	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.463
   Length of year:		109802.88	days
   Length of day:		33.60	hours


