                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048478
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6329 K
Stellar class: F7
Age: 5.386 billion years  (1.523 billion left on main sequence)
Habitable ecosphere radius: 1.262 AU

Planets present at:
1	  0.450 AU	no atmosphere
2	  0.693 AU	no atmosphere
3	  0.796 AU	no atmosphere
4	  1.056 AU	greenhouse
5	  1.378 AU	
6	  2.181 AU	no atmosphere
7	  2.457 AU	no atmosphere
8	  3.761 AU	gas giant
9	  7.361 AU	gas giant
10	 11.217 AU	gas giant
11	 17.407 AU	gas giant
12	 29.030 AU	gas giant
13	 49.462 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.450	AU
   Mass:			0.278	Earth masses
   Equatorial radius:		4205.1	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.221
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		186.68	degrees Celcius
   Normal daytime temperature:	389.17	degrees Celcius
   Normal night temperature:	-189.78	degrees Celcius
   Maximum temperature:   	393.03	degrees Celcius
   Minimum temperature:   	-202.14	degrees Celcius
   Escape Velocity:		7.25	km/sec
   Molecular weight retained:	15.08 and above
   Surface acceleration:	625.81	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.059
   Length of year:		105.21	days
   Length of day:		1612.44	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.693	AU
   Mass:			0.044	Earth masses
   Equatorial radius:		2283.7	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		97.30	degrees Celcius
   Maximum temperature:   	282.65	degrees Celcius
   Minimum temperature:   	-225.52	degrees Celcius
   Escape Velocity:		3.92	km/sec
   Molecular weight retained:	51.68 and above
   Surface acceleration:	336.29	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.061
   Length of year:		200.93	days
   Length of day:		4822.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	0.796	AU
   Mass:			0.227	Earth masses
   Equatorial radius:		3935.8	km
   Density:			5.315	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		70.35	degrees Celcius
   Maximum temperature:   	247.70	degrees Celcius
   Minimum temperature:   	-223.30	degrees Celcius
   Escape Velocity:		6.78	km/sec
   Molecular weight retained:	17.25 and above
   Surface acceleration:	584.63	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.085
   Length of year:		247.35	days
   Length of day:		2230.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.056	AU
   Mass:			2.470	Earth masses
   Equatorial radius:		8573.8	km
   Density:			5.591	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		1.37	Earth gees
   Surface pressure:		459.829	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		502.31	degrees Celcius
   Maximum temperature:   	504.26	degrees Celcius
   Minimum temperature:   	497.99	degrees Celcius
   Escape Velocity:		15.16	km/sec
   Molecular weight retained:	3.46 and above
   Surface acceleration:	1339.74	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.604
   Length of year:		377.51	days
   Length of day:		13.44	hours
   Boiling point of water:	408.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1463
				Cesium       melts at 28    boils at 1514
				Gallium      melts at 30    boils at 4617
				Rubidium     melts at 39    boils at 1483
				Potassium    melts at 63    boils at 1625
				Sodium       melts at 98    boils at 1837
				Indium       melts at 157   boils at 4027
				Lithium      melts at 181   boils at 2687
				Selenium     melts at 217   boils at 1478
				Tin          melts at 232   boils at 5019
				Polonium     melts at 254   boils at 1984
				Bismuth      melts at 271   boils at 3084
				Thallium     melts at 304   boils at 2888
				Cadmium      melts at 321   boils at 1624
				Lead         melts at 328   boils at 3426
				Zinc         melts at 420   boils at 1883
				Tellurium    melts at 450   boils at 2035
   gasses in atmosphere:
				Sulfur            0.2%  PP 1030.8 mb
				Nitrogen          1.0%  PP 4432.0 mb
				Helium           98.8%  PP 454336.4 mb


Planet 5	
   Distance from primary:	1.378	AU
   Mass:			0.654	Earth masses
   Equatorial radius:		5575.0	km
   Density:			5.387	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.86	Earth gees
   Surface pressure:		0.404	Earth atmospheres
   Surface temperature:		7.74	degrees Celcius
   Normal daytime temperature:	14.76	degrees Celcius
   Normal night temperature:	0.32	degrees Celcius
   Maximum temperature:   	38.76	degrees Celcius
   Minimum temperature:   	-25.01	degrees Celcius
   Escape Velocity:		9.67	km/sec
   Molecular weight retained:	8.48 and above
   Surface acceleration:	839.26	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.214
   Length of year:		563.16	days
   Length of day:		16.80	hours
   Boiling point of water:	76.6	degrees Celcius
   Hydrosphere percentage:	57.43
   Cloud cover percentage:	25.10
   Ice cover percentage:	3.82
   liquids at surface:
				Ethanol      melts at -114  boils at 57
				Mercury      melts at -39   boils at 317
				Bromine      melts at -7    boils at 39
				Water        melts at 0     boils at 77
   gasses in atmosphere:
				Oxygen           37.0%  PP  149.6 mb
				Nitrogen         62.8%  PP  253.7 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 6	
   Distance from primary:	2.181	AU
   Mass:			0.034	Earth masses
   Equatorial radius:		2097.3	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-79.21	degrees Celcius
   Normal daytime temperature:	-55.99	degrees Celcius
   Normal night temperature:	-102.49	degrees Celcius
   Maximum temperature:   	-32.58	degrees Celcius
   Minimum temperature:   	-126.36	degrees Celcius
   Escape Velocity:		3.60	km/sec
   Molecular weight retained:	61.32 and above
   Surface acceleration:	308.63	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.305
   Length of year:		1120.98	days
   Length of day:		27.59	hours
   Boiling point of water:	-26.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	28.60
   liquids at surface:
				Ethanol      melts at -114  boils at -32
   gasses in atmosphere:
				Krypton          81.5%  PP    0.8 mb
				Xenon            18.5%  PP    0.2 mb


Planet 7	
   Distance from primary:	2.457	AU
   Mass:			0.051	Earth masses
   Equatorial radius:		2391.6	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.002	Earth atmospheres
   Surface temperature:		-92.66	degrees Celcius
   Normal daytime temperature:	-72.62	degrees Celcius
   Normal night temperature:	-112.76	degrees Celcius
   Maximum temperature:   	-47.64	degrees Celcius
   Minimum temperature:   	-138.46	degrees Celcius
   Escape Velocity:		4.11	km/sec
   Molecular weight retained:	47.10 and above
   Surface acceleration:	352.33	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.339
   Length of year:		1340.91	days
   Length of day:		25.64	hours
   Boiling point of water:	-16.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	31.40
   liquids at surface:
				Ethanol      melts at -114  boils at -27
   gasses in atmosphere:
				Ozone            42.1%  PP    0.9 mb
				Krypton          49.7%  PP    1.0 mb
				Xenon             8.2%  PP    0.2 mb


Planet 8	*gas giant*
   Distance from primary:	3.761	AU
   Mass:			860.446	Earth masses
   Equatorial radius:		83279.6	km
   Density:			2.126	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		90.78	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4947.50	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.550
   Length of year:		2535.74	days
   Length of day:		5.81	hours


Planet 9	*gas giant*
   Distance from primary:	7.361	AU
   Mass:			7.895	Earth masses
   Equatorial radius:		22418.7	km
   Density:			1.000	grams/cc
   Eccentricity of orbit:	0.113
   Escape Velocity:		16.76	km/sec
   Molecular weight retained:	2.83 and above
   Surface acceleration:	626.43	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.474
   Length of year:		6951.78	days
   Length of day:		16.33	hours


Planet 10	*gas giant*
   Distance from primary:	11.217	AU
   Mass:			32.241	Earth masses
   Equatorial radius:		35001.2	km
   Density:			1.073	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		27.10	km/sec
   Molecular weight retained:	1.08 and above
   Surface acceleration:	1049.49	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.484
   Length of year:		13078.55	days
   Length of day:		12.62	hours


Planet 11	*gas giant*
   Distance from primary:	17.407	AU
   Mass:			317.462	Earth masses
   Equatorial radius:		70744.6	km
   Density:			1.279	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		59.83	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2529.56	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.507
   Length of year:		25270.98	days
   Length of day:		8.13	hours


Planet 12	*gas giant*
   Distance from primary:	29.030	AU
   Mass:			0.350	Earth masses
   Equatorial radius:		10128.0	km
   Density:			0.481	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		5.25	km/sec
   Molecular weight retained:	28.81 and above
   Surface acceleration:	136.03	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.477
   Length of year:		54450.71	days
   Length of day:		35.04	hours


Planet 13	
   Distance from primary:	49.462	AU
   Mass:			0.220	Earth masses
   Equatorial radius:		5200.0	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.00	degrees Celcius
   Normal daytime temperature:	-224.95	degrees Celcius
   Normal night temperature:	-234.96	degrees Celcius
   Maximum temperature:   	-213.56	degrees Celcius
   Minimum temperature:   	-246.91	degrees Celcius
   Escape Velocity:		5.80	km/sec
   Molecular weight retained:	23.57 and above
   Surface acceleration:	323.77	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.154
   Length of year:		121098.71	days
   Length of day:		26.63	hours
   Boiling point of water:	-50.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


