                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504851d
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6117 K
Stellar class: F9
Age: 3.513 billion years  (3.374 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.414 AU	no atmosphere
2	  0.835 AU	greenhouse
3	  1.873 AU	cold
4	  2.139 AU	no atmosphere
5	  2.674 AU	gas giant
6	  3.628 AU	cold
7	  5.213 AU	gas giant
8	  8.076 AU	gas giant
9	 16.830 AU	gas giant
10	 33.456 AU	gas giant
11	 45.605 AU	no atmosphere
12	 50.676 AU	no atmosphere



Planet 1	
   Distance from primary:	0.414	AU
   Mass:			0.260	Earth masses
   Equatorial radius:		4113.8	km
   Density:			5.322	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		203.41	degrees Celcius
   Maximum temperature:   	413.75	degrees Celcius
   Minimum temperature:   	-204.30	degrees Celcius
   Escape Velocity:		7.09	km/sec
   Molecular weight retained:	15.77 and above
   Surface acceleration:	611.82	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.084
   Length of year:		92.85	days
   Length of day:		2228.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.835	AU
   Mass:			2.332	Earth masses
   Equatorial radius:		8418.4	km
   Density:			5.578	grams/cc
   Eccentricity of orbit:	0.129
   Surface gravity:		1.34	Earth gees
   Surface pressure:		500.933	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		648.72	degrees Celcius
   Maximum temperature:   	649.82	degrees Celcius
   Minimum temperature:   	643.42	degrees Celcius
   Escape Velocity:		14.86	km/sec
   Molecular weight retained:	3.59 and above
   Surface acceleration:	1312.35	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.536
   Length of year:		265.34	days
   Length of day:		14.24	hours
   Boiling point of water:	416.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1483
				Cesium       melts at 28    boils at 1535
				Gallium      melts at 30    boils at 4674
				Rubidium     melts at 39    boils at 1504
				Potassium    melts at 63    boils at 1647
				Sodium       melts at 98    boils at 1861
				Indium       melts at 157   boils at 4077
				Lithium      melts at 181   boils at 2722
				Selenium     melts at 217   boils at 1498
				Tin          melts at 232   boils at 5081
				Polonium     melts at 254   boils at 2010
				Bismuth      melts at 271   boils at 3123
				Thallium     melts at 304   boils at 2925
				Cadmium      melts at 321   boils at 1646
				Lead         melts at 328   boils at 3469
				Zinc         melts at 420   boils at 1908
				Tellurium    melts at 450   boils at 2062
				Antimony     melts at 631   boils at 3166
				Neptunium    melts at 640   boils at 7446
				Plutonium    melts at 641   boils at 6203
   gasses in atmosphere:
				Sulfur            0.3%  PP 1329.2 mb
				Nitrogen          1.2%  PP 5849.0 mb
				Helium           98.6%  PP 493716.4 mb


Planet 3	
   Distance from primary:	1.873	AU
   Mass:			0.569	Earth masses
   Equatorial radius:		5324.8	km
   Density:			5.374	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.293	Earth atmospheres
   Surface temperature:		-75.94	degrees Celcius
   Normal daytime temperature:	-70.19	degrees Celcius
   Normal night temperature:	-81.98	degrees Celcius
   Maximum temperature:   	-47.91	degrees Celcius
   Minimum temperature:   	-105.80	degrees Celcius
   Escape Velocity:		9.23	km/sec
   Molecular weight retained:	9.32 and above
   Surface acceleration:	799.73	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.637
   Length of year:		891.94	days
   Length of day:		16.98	hours
   Boiling point of water:	69.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	78.74
   liquids at surface:
				Ethanol      melts at -114  boils at 49
				Chlorine     melts at -101  boils at -54
				Ammonia      melts at -78   boils at -53
   gasses in atmosphere:
				Oxygen           12.9%  PP   37.6 mb
				Nitrogen         86.9%  PP  254.6 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 4	
   Distance from primary:	2.139	AU
   Mass:			0.171	Earth masses
   Equatorial radius:		3580.3	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.025	Earth atmospheres
   Surface temperature:		-82.95	degrees Celcius
   Normal daytime temperature:	-68.44	degrees Celcius
   Normal night temperature:	-97.72	degrees Celcius
   Maximum temperature:   	-44.66	degrees Celcius
   Minimum temperature:   	-122.55	degrees Celcius
   Escape Velocity:		6.16	km/sec
   Molecular weight retained:	20.89 and above
   Surface acceleration:	530.62	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.442
   Length of year:		1088.63	days
   Length of day:		20.85	hours
   Boiling point of water:	20.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	49.84
   liquids at surface:
				Ethanol      melts at -114  boils at 4
   gasses in atmosphere:
				Ozone            93.2%  PP   23.4 mb
				Argon             0.2%  PP    0.1 mb
				Krypton           5.9%  PP    1.5 mb
				Xenon             0.7%  PP    0.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.674	AU
   Mass:			4.217	Earth masses
   Equatorial radius:		17157.7	km
   Density:			1.191	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		14.00	km/sec
   Molecular weight retained:	4.05 and above
   Surface acceleration:	571.24	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.502
   Length of year:		1521.69	days
   Length of day:		17.10	hours


Planet 6	
   Distance from primary:	3.628	AU
   Mass:			0.797	Earth masses
   Equatorial radius:		5946.8	km
   Density:			5.407	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.92	Earth gees
   Surface pressure:		0.464	Earth atmospheres
   Surface temperature:		-118.68	degrees Celcius
   Normal daytime temperature:	-115.21	degrees Celcius
   Normal night temperature:	-122.34	degrees Celcius
   Maximum temperature:   	-96.75	degrees Celcius
   Minimum temperature:   	-142.38	degrees Celcius
   Escape Velocity:		10.34	km/sec
   Molecular weight retained:	7.43 and above
   Surface acceleration:	898.56	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.512
   Length of year:		2404.66	days
   Length of day:		15.99	hours
   Boiling point of water:	80.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	71.41
   gasses in atmosphere:
				Oxygen            6.1%  PP   28.3 mb
				Nitrogen         93.9%  PP  435.7 mb


Planet 7	*gas giant*
   Distance from primary:	5.213	AU
   Mass:			1028.068	Earth masses
   Equatorial radius:		90122.5	km
   Density:			2.004	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		95.38	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	5047.71	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.542
   Length of year:		4136.19	days
   Length of day:		5.75	hours


Planet 8	*gas giant*
   Distance from primary:	8.076	AU
   Mass:			8.593	Earth masses
   Equatorial radius:		23153.8	km
   Density:			0.988	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		17.20	km/sec
   Molecular weight retained:	2.68 and above
   Surface acceleration:	639.17	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.525
   Length of year:		7986.90	days
   Length of day:		16.17	hours


Planet 9	*gas giant*
   Distance from primary:	16.830	AU
   Mass:			185.295	Earth masses
   Equatorial radius:		60284.1	km
   Density:			1.207	grams/cc
   Eccentricity of orbit:	0.160
   Escape Velocity:		49.51	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2033.28	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.510
   Length of year:		24020.38	days
   Length of day:		9.06	hours


Planet 10	*gas giant*
   Distance from primary:	33.456	AU
   Mass:			14.401	Earth masses
   Equatorial radius:		30302.2	km
   Density:			0.739	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		19.47	km/sec
   Molecular weight retained:	2.09 and above
   Surface acceleration:	625.45	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.541
   Length of year:		67336.59	days
   Length of day:		16.34	hours


Planet 11	
   Distance from primary:	45.605	AU
   Mass:			0.160	Earth masses
   Equatorial radius:		4681.4	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.09	degrees Celcius
   Normal daytime temperature:	-222.56	degrees Celcius
   Normal night temperature:	-233.53	degrees Celcius
   Maximum temperature:   	-206.53	degrees Celcius
   Minimum temperature:   	-249.70	degrees Celcius
   Escape Velocity:		5.21	km/sec
   Molecular weight retained:	29.19 and above
   Surface acceleration:	290.42	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.145
   Length of year:		107169.12	days
   Length of day:		28.12	hours
   Boiling point of water:	-54.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	
   Distance from primary:	50.676	AU
   Mass:			1/102.9	Earth masses
   Equatorial radius:		1849.8	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.12	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.73	degrees Celcius
   Maximum temperature:   	-213.30	degrees Celcius
   Minimum temperature:   	-248.12	degrees Celcius
   Escape Velocity:		2.05	km/sec
   Molecular weight retained:	189.42 and above
   Surface acceleration:	113.27	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.151
   Length of year:		125534.11	days
   Length of day:		45.03	hours
   Boiling point of water:	-97.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


