                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048826
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6390 K
Stellar class: F7
Age: 4.229 billion years  (2.557 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.345 AU	no atmosphere
2	  0.539 AU	no atmosphere
3	  0.727 AU	no atmosphere
4	  0.895 AU	greenhouse
5	  1.188 AU	high pressure
6	  1.757 AU	no atmosphere
7	  2.421 AU	cold
8	  2.899 AU	cold
9	  3.665 AU	gas giant
10	  7.106 AU	gas giant
11	 15.557 AU	gas giant
12	 23.771 AU	gas giant
13	 40.065 AU	no atmosphere
14	 38.890 AU	gas giant
15	 50.896 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.345	AU
   Mass:			0.139	Earth masses
   Equatorial radius:		3348.8	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.79	degrees Celcius
   Normal daytime temperature:	473.38	degrees Celcius
   Normal night temperature:	-172.98	degrees Celcius
   Maximum temperature:   	476.86	degrees Celcius
   Minimum temperature:   	-185.38	degrees Celcius
   Escape Velocity:		5.76	km/sec
   Molecular weight retained:	23.91 and above
   Surface acceleration:	495.65	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.057
   Length of year:		70.26	days
   Length of day:		1369.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.539	AU
   Mass:			0.107	Earth masses
   Equatorial radius:		3070.1	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.39	degrees Celcius
   Maximum temperature:   	346.23	degrees Celcius
   Minimum temperature:   	-216.96	degrees Celcius
   Escape Velocity:		5.28	km/sec
   Molecular weight retained:	28.49 and above
   Surface acceleration:	453.71	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.070
   Length of year:		137.41	days
   Length of day:		3297.79	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.727	AU
   Mass:			0.153	Earth masses
   Equatorial radius:		3451.2	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		90.40	degrees Celcius
   Maximum temperature:   	273.89	degrees Celcius
   Minimum temperature:   	-226.36	degrees Celcius
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.50 and above
   Surface acceleration:	511.10	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.064
   Length of year:		215.16	days
   Length of day:		5163.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.895	AU
   Mass:			0.221	Earth masses
   Equatorial radius:		3903.0	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.59	Earth gees
   Surface pressure:		4.988	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		56.89	degrees Celcius
   Normal daytime temperature:	61.23	degrees Celcius
   Normal night temperature:	51.89	degrees Celcius
   Maximum temperature:   	73.44	degrees Celcius
   Minimum temperature:   	39.16	degrees Celcius
   Escape Velocity:		6.73	km/sec
   Molecular weight retained:	17.54 and above
   Surface acceleration:	579.64	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.511
   Length of year:		294.31	days
   Length of day:		32.99	hours
   Boiling point of water:	150.2	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 126
				Mercury      melts at -39   boils at 442
				Bromine      melts at -7    boils at 104
				Water        melts at 0     boils at 150
				Francium     melts at 27    boils at 805
				Cesium       melts at 28    boils at 837
				Gallium      melts at 30    boils at 2763
				Rubidium     melts at 39    boils at 817
				Phosphorus   melts at 44    boils at 355
   gasses in atmosphere:
				CarbonDioxide    46.4%  PP 2313.5 mb
				Ozone            49.6%  PP 2472.8 mb
				Argon             0.1%  PP    7.0 mb
				Neon              0.3%  PP   13.2 mb
				Krypton           3.2%  PP  161.1 mb
				Xenon             0.4%  PP   20.2 mb


Planet 5	
   Distance from primary:	1.188	AU
   Mass:			2.210	Earth masses
   Equatorial radius:		8274.2	km
   Density:			5.566	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		1.31	Earth gees
   Surface pressure:		4.534	Earth atmospheres
   Surface temperature:		18.45	degrees Celcius
   Normal daytime temperature:	20.31	degrees Celcius
   Normal night temperature:	16.46	degrees Celcius
   Maximum temperature:   	31.67	degrees Celcius
   Minimum temperature:   	4.54	degrees Celcius
   Escape Velocity:		14.59	km/sec
   Molecular weight retained:	3.73 and above
   Surface acceleration:	1287.11	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.525
   Length of year:		449.82	days
   Length of day:		13.51	hours
   Boiling point of water:	146.9	degrees Celcius
   Hydrosphere percentage:	86.61
   Cloud cover percentage:	81.47
   Ice cover percentage:	1.00
   liquids at surface:
				Ethanol      melts at -114  boils at 123
				Mercury      melts at -39   boils at 436
				Bromine      melts at -7    boils at 101
				Water        melts at 0     boils at 147
   gasses in atmosphere:
				Nitrogen          1.7%  PP   75.0 mb
				Helium           98.3%  PP 4458.4 mb


Planet 6	
   Distance from primary:	1.757	AU
   Mass:			0.224	Earth masses
   Equatorial radius:		3915.6	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.052	Earth atmospheres
   Surface temperature:		-61.94	degrees Celcius
   Normal daytime temperature:	-48.70	degrees Celcius
   Normal night temperature:	-75.56	degrees Celcius
   Maximum temperature:   	-24.30	degrees Celcius
   Minimum temperature:   	-101.09	degrees Celcius
   Escape Velocity:		6.75	km/sec
   Molecular weight retained:	17.43 and above
   Surface acceleration:	581.56	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.506
   Length of year:		808.62	days
   Length of day:		20.01	hours
   Boiling point of water:	33.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.14
   Ice cover percentage:	66.04
   liquids at surface:
				Ethanol      melts at -114  boils at 16
   gasses in atmosphere:
				CarbonDioxide    46.5%  PP   24.3 mb
				Ozone            49.7%  PP   25.9 mb
				Argon             0.1%  PP    0.1 mb
				Neon              0.3%  PP    0.2 mb
				Krypton           3.0%  PP    1.6 mb
				Xenon             0.4%  PP    0.2 mb


Planet 7	
   Distance from primary:	2.421	AU
   Mass:			1.264	Earth masses
   Equatorial radius:		6910.8	km
   Density:			5.465	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		1.08	Earth gees
   Surface pressure:		1.535	Earth atmospheres
   Surface temperature:		-97.82	degrees Celcius
   Normal daytime temperature:	-95.74	degrees Celcius
   Normal night temperature:	-100.02	degrees Celcius
   Maximum temperature:   	-79.06	degrees Celcius
   Minimum temperature:   	-118.00	degrees Celcius
   Escape Velocity:		12.08	km/sec
   Molecular weight retained:	5.44 and above
   Surface acceleration:	1055.54	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.695
   Length of year:		1308.29	days
   Length of day:		14.75	hours
   Boiling point of water:	112.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 90
				Chlorine     melts at -101  boils at -26
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1533.5 mb
				Ozone             0.1%  PP    0.8 mb


Planet 8	
   Distance from primary:	2.899	AU
   Mass:			0.501	Earth masses
   Equatorial radius:		5107.3	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.194	Earth atmospheres
   Surface temperature:		-103.19	degrees Celcius
   Normal daytime temperature:	-97.19	degrees Celcius
   Normal night temperature:	-109.46	degrees Celcius
   Maximum temperature:   	-77.17	degrees Celcius
   Minimum temperature:   	-130.96	degrees Celcius
   Escape Velocity:		8.84	km/sec
   Molecular weight retained:	10.15 and above
   Surface acceleration:	765.56	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.483
   Length of year:		1714.24	days
   Length of day:		17.32	hours
   Boiling point of water:	59.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	64.36
   liquids at surface:
				Ethanol      melts at -114  boils at 41
   gasses in atmosphere:
				Oxygen            9.9%  PP   19.3 mb
				Nitrogen         89.9%  PP  174.4 mb
				Ozone             0.1%  PP    0.2 mb


Planet 9	*gas giant*
   Distance from primary:	3.665	AU
   Mass:			394.121	Earth masses
   Equatorial radius:		66114.2	km
   Density:			1.946	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		68.95	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3595.66	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.463
   Length of year:		2435.14	days
   Length of day:		6.82	hours


Planet 10	*gas giant*
   Distance from primary:	7.106	AU
   Mass:			737.115	Earth masses
   Equatorial radius:		83862.6	km
   Density:			1.783	grams/cc
   Eccentricity of orbit:	0.091
   Escape Velocity:		83.73	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4179.63	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.509
   Length of year:		6572.69	days
   Length of day:		6.32	hours


Planet 11	*gas giant*
   Distance from primary:	15.557	AU
   Mass:			14.491	Earth masses
   Equatorial radius:		28458.5	km
   Density:			0.897	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		20.15	km/sec
   Molecular weight retained:	1.95 and above
   Surface acceleration:	713.52	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.549
   Length of year:		21310.19	days
   Length of day:		15.30	hours


Planet 12	*gas giant*
   Distance from primary:	23.771	AU
   Mass:			11.127	Earth masses
   Equatorial radius:		27296.0	km
   Density:			0.781	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		18.03	km/sec
   Molecular weight retained:	2.44 and above
   Surface acceleration:	595.56	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.523
   Length of year:		40251.12	days
   Length of day:		16.75	hours


Planet 13	
   Distance from primary:	40.065	AU
   Mass:			0.112	Earth masses
   Equatorial radius:		4166.7	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.099
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.20	degrees Celcius
   Normal daytime temperature:	-218.99	degrees Celcius
   Normal night temperature:	-231.32	degrees Celcius
   Maximum temperature:   	-207.35	degrees Celcius
   Minimum temperature:   	-243.55	degrees Celcius
   Escape Velocity:		4.63	km/sec
   Molecular weight retained:	36.97 and above
   Surface acceleration:	257.66	cm/sec2
   Axial tilt:			65	degrees
   Planetary albedo:		0.152
   Length of year:		88078.12	days
   Length of day:		29.86	hours
   Boiling point of water:	-61.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 14	*gas giant*
   Distance from primary:	38.890	AU
   Mass:			1.852	Earth masses
   Equatorial radius:		16857.6	km
   Density:			0.552	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		9.36	km/sec
   Molecular weight retained:	9.06 and above
   Surface acceleration:	259.92	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.480
   Length of year:		84231.58	days
   Length of day:		25.35	hours


Planet 15	
   Distance from primary:	50.896	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		3300.8	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.50	degrees Celcius
   Normal daytime temperature:	-224.38	degrees Celcius
   Normal night temperature:	-236.49	degrees Celcius
   Maximum temperature:   	-210.28	degrees Celcius
   Minimum temperature:   	-250.63	degrees Celcius
   Escape Velocity:		3.66	km/sec
   Molecular weight retained:	59.18 and above
   Surface acceleration:	203.19	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.142
   Length of year:		126109.85	days
   Length of day:		33.62	hours
   Boiling point of water:	-73.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


