                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504845c
Stellar mass: 1.10 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6229 K
Stellar class: F8
Age: 2.325 billion years  (4.587 billion left on main sequence)
Habitable ecosphere radius: 1.262 AU

Planets present at:
1	  0.414 AU	no atmosphere
2	  0.619 AU	no atmosphere
3	  0.842 AU	greenhouse
4	  1.126 AU	greenhouse
5	  1.833 AU	cold
6	  2.810 AU	gas giant
7	  8.114 AU	gas giant
8	 13.362 AU	gas giant
9	 27.972 AU	gas giant
10	 43.380 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.414	AU
   Mass:			0.160	Earth masses
   Equatorial radius:		3508.4	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.150
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		206.42	degrees Celcius
   Normal daytime temperature:	413.60	degrees Celcius
   Normal night temperature:	-187.12	degrees Celcius
   Maximum temperature:   	417.16	degrees Celcius
   Minimum temperature:   	-198.76	degrees Celcius
   Escape Velocity:		6.04	km/sec
   Molecular weight retained:	21.77 and above
   Surface acceleration:	519.75	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.059
   Length of year:		92.72	days
   Length of day:		1645.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.619	AU
   Mass:			0.223	Earth masses
   Equatorial radius:		3909.5	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		117.84	degrees Celcius
   Maximum temperature:   	308.46	degrees Celcius
   Minimum temperature:   	-223.06	degrees Celcius
   Escape Velocity:		6.74	km/sec
   Molecular weight retained:	17.48 and above
   Surface acceleration:	580.64	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.070
   Length of year:		169.67	days
   Length of day:		4072.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.842	AU
   Mass:			0.271	Earth masses
   Equatorial radius:		4171.4	km
   Density:			5.324	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.63	Earth gees
   Surface pressure:		6.238	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		94.04	degrees Celcius
   Normal daytime temperature:	97.57	degrees Celcius
   Normal night temperature:	90.01	degrees Celcius
   Maximum temperature:   	108.87	degrees Celcius
   Minimum temperature:   	78.24	degrees Celcius
   Escape Velocity:		7.20	km/sec
   Molecular weight retained:	15.33 and above
   Surface acceleration:	620.64	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.467
   Length of year:		269.12	days
   Length of day:		26.13	hours
   Boiling point of water:	158.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 455
				Water        melts at 0     boils at 158
				Francium     melts at 27    boils at 825
				Cesium       melts at 28    boils at 858
				Gallium      melts at 30    boils at 2821
				Rubidium     melts at 39    boils at 838
				Phosphorus   melts at 44    boils at 367
				Potassium    melts at 63    boils at 928
   gasses in atmosphere:
				Oxygen            2.7%  PP  168.9 mb
				CarbonDioxide    29.1%  PP 1817.6 mb
				Methane           1.5%  PP   95.6 mb
				Ammonia           3.6%  PP  225.8 mb
				Ozone            30.6%  PP 1908.9 mb
				Ethanol          30.0%  PP 1872.8 mb
				Neon              0.3%  PP   19.9 mb
				Krypton           1.8%  PP  112.0 mb
				Xenon             0.2%  PP   13.3 mb


Planet 4	
   Distance from primary:	1.126	AU
   Mass:			2.360	Earth masses
   Equatorial radius:		8450.4	km
   Density:			5.581	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		1.34	Earth gees
   Surface pressure:		551.050	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		563.45	degrees Celcius
   Maximum temperature:   	564.91	degrees Celcius
   Minimum temperature:   	558.94	degrees Celcius
   Escape Velocity:		14.92	km/sec
   Molecular weight retained:	3.56 and above
   Surface acceleration:	1317.98	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.462
   Length of year:		415.80	days
   Length of day:		13.30	hours
   Boiling point of water:	425.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1506
				Cesium       melts at 28    boils at 1559
				Gallium      melts at 30    boils at 4740
				Rubidium     melts at 39    boils at 1527
				Potassium    melts at 63    boils at 1673
				Sodium       melts at 98    boils at 1890
				Indium       melts at 157   boils at 4134
				Lithium      melts at 181   boils at 2761
				Selenium     melts at 217   boils at 1521
				Tin          melts at 232   boils at 5152
				Polonium     melts at 254   boils at 2040
				Bismuth      melts at 271   boils at 3168
				Thallium     melts at 304   boils at 2967
				Cadmium      melts at 321   boils at 1671
				Lead         melts at 328   boils at 3518
				Zinc         melts at 420   boils at 1937
				Tellurium    melts at 450   boils at 2093
   gasses in atmosphere:
				Sulfur            0.2%  PP 1074.7 mb
				Nitrogen          0.9%  PP 5095.0 mb
				Helium           98.9%  PP 544849.0 mb


Planet 5	
   Distance from primary:	1.833	AU
   Mass:			1.312	Earth masses
   Equatorial radius:		6994.8	km
   Density:			5.471	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.856	Earth atmospheres
   Surface temperature:		-61.68	degrees Celcius
   Normal daytime temperature:	-59.41	degrees Celcius
   Normal night temperature:	-64.09	degrees Celcius
   Maximum temperature:   	-44.63	degrees Celcius
   Minimum temperature:   	-79.86	degrees Celcius
   Escape Velocity:		12.23	km/sec
   Molecular weight retained:	5.31 and above
   Surface acceleration:	1069.47	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.631
   Length of year:		863.91	days
   Length of day:		14.66	hours
   Boiling point of water:	117.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.26
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 95
				Chlorine     melts at -101  boils at -22
				Ammonia      melts at -78   boils at -22
   gasses in atmosphere:
				Oxygen            0.7%  PP   12.3 mb
				Nitrogen         99.2%  PP 1841.0 mb


Planet 6	*gas giant*
   Distance from primary:	2.810	AU
   Mass:			78.010	Earth masses
   Equatorial radius:		40357.2	km
   Density:			1.693	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		39.26	km/sec
   Molecular weight retained:	0.51 and above
   Surface acceleration:	1910.07	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.490
   Length of year:		1639.67	days
   Length of day:		9.35	hours


Planet 7	*gas giant*
   Distance from primary:	8.114	AU
   Mass:			2287.418	Earth masses
   Equatorial radius:		118094.5	km
   Density:			1.982	grams/cc
   Eccentricity of orbit:	0.231
   Escape Velocity:		124.29	km/sec
   Molecular weight retained:	0.05 and above
   Surface acceleration:	6540.71	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.496
   Length of year:		8021.41	days
   Length of day:		5.05	hours


Planet 8	*gas giant*
   Distance from primary:	13.362	AU
   Mass:			43.086	Earth masses
   Equatorial radius:		38650.6	km
   Density:			1.065	grams/cc
   Eccentricity of orbit:	0.280
   Escape Velocity:		29.82	km/sec
   Molecular weight retained:	0.89 and above
   Surface acceleration:	1150.17	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.519
   Length of year:		17004.20	days
   Length of day:		12.05	hours


Planet 9	*gas giant*
   Distance from primary:	27.972	AU
   Mass:			4.278	Earth masses
   Equatorial radius:		20956.7	km
   Density:			0.663	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		12.76	km/sec
   Molecular weight retained:	4.88 and above
   Surface acceleration:	388.44	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.488
   Length of year:		51505.67	days
   Length of day:		20.74	hours


Planet 10	*gas giant*
   Distance from primary:	43.380	AU
   Mass:			0.838	Earth masses
   Equatorial radius:		13511.9	km
   Density:			0.485	grams/cc
   Eccentricity of orbit:	0.044
   Escape Velocity:		7.03	km/sec
   Molecular weight retained:	16.05 and above
   Surface acceleration:	183.06	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.508
   Length of year:		99470.00	days
   Length of day:		30.21	hours


