                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504874c
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6278 K
Stellar class: F8
Age: 1.910 billion years  (4.905 billion left on main sequence)
Habitable ecosphere radius: 1.273 AU

Planets present at:
1	  0.442 AU	no atmosphere
2	  0.684 AU	no atmosphere
3	  0.840 AU	no atmosphere
4	  1.221 AU	no atmosphere
5	  1.393 AU	
6	  1.782 AU	gas giant
7	  3.257 AU	cold
8	  4.697 AU	gas giant
9	  7.014 AU	gas giant
10	 14.126 AU	gas giant
11	 20.526 AU	gas giant
12	 31.772 AU	gas giant
13	 44.550 AU	no atmosphere
14	 47.449 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.442	AU
   Mass:			0.497	Earth masses
   Equatorial radius:		5094.2	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.108
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		190.67	degrees Celcius
   Normal daytime temperature:	394.74	degrees Celcius
   Normal night temperature:	-194.13	degrees Celcius
   Maximum temperature:   	398.07	degrees Celcius
   Minimum temperature:   	-204.61	degrees Celcius
   Escape Velocity:		8.82	km/sec
   Molecular weight retained:	10.20 and above
   Surface acceleration:	763.51	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.080
   Length of year:		101.98	days
   Length of day:		1972.27	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.684	AU
   Mass:			0.456	Earth masses
   Equatorial radius:		4951.5	km
   Density:			5.356	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		100.21	degrees Celcius
   Normal daytime temperature:	154.20	degrees Celcius
   Normal night temperature:	44.81	degrees Celcius
   Maximum temperature:   	187.17	degrees Celcius
   Minimum temperature:   	10.68	degrees Celcius
   Escape Velocity:		8.57	km/sec
   Molecular weight retained:	10.81 and above
   Surface acceleration:	741.21	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.074
   Length of year:		196.50	days
   Length of day:		34.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	0.840	AU
   Mass:			0.020	Earth masses
   Equatorial radius:		1749.6	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		63.41	degrees Celcius
   Maximum temperature:   	239.91	degrees Celcius
   Minimum temperature:   	-229.52	degrees Celcius
   Escape Velocity:		3.00	km/sec
   Molecular weight retained:	88.21 and above
   Surface acceleration:	257.17	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.077
   Length of year:		267.67	days
   Length of day:		6424.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.221	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		1712.8	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		7.14	degrees Celcius
   Normal daytime temperature:	51.97	degrees Celcius
   Normal night temperature:	-38.26	degrees Celcius
   Maximum temperature:   	77.79	degrees Celcius
   Minimum temperature:   	-64.27	degrees Celcius
   Escape Velocity:		2.94	km/sec
   Molecular weight retained:	92.05 and above
   Surface acceleration:	251.74	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.062
   Length of year:		468.83	days
   Length of day:		38.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	
   Distance from primary:	1.393	AU
   Mass:			0.641	Earth masses
   Equatorial radius:		5538.5	km
   Density:			5.385	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.436	Earth atmospheres
   Surface temperature:		7.90	degrees Celcius
   Normal daytime temperature:	14.64	degrees Celcius
   Normal night temperature:	0.77	degrees Celcius
   Maximum temperature:   	39.62	degrees Celcius
   Minimum temperature:   	-25.61	degrees Celcius
   Escape Velocity:		9.61	km/sec
   Molecular weight retained:	8.60 and above
   Surface acceleration:	833.47	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.215
   Length of year:		571.45	days
   Length of day:		16.69	hours
   Boiling point of water:	78.5	degrees Celcius
   Hydrosphere percentage:	64.10
   Cloud cover percentage:	29.29
   Ice cover percentage:	3.56
   liquids at surface:
				Ethanol      melts at -114  boils at 58
				Mercury      melts at -39   boils at 321
				Bromine      melts at -7    boils at 40
				Water        melts at 0     boils at 79
   gasses in atmosphere:
				Oxygen           40.6%  PP  177.1 mb
				Nitrogen         59.3%  PP  258.5 mb


Planet 6	*gas giant*
   Distance from primary:	1.782	AU
   Mass:			19.981	Earth masses
   Equatorial radius:		26097.2	km
   Density:			1.604	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		24.71	km/sec
   Molecular weight retained:	1.30 and above
   Surface acceleration:	1169.97	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.522
   Length of year:		826.91	days
   Length of day:		11.95	hours


Planet 7	
   Distance from primary:	3.257	AU
   Mass:			1.047	Earth masses
   Equatorial radius:		6501.1	km
   Density:			5.439	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		1.01	Earth gees
   Surface pressure:		0.849	Earth atmospheres
   Surface temperature:		-121.25	degrees Celcius
   Normal daytime temperature:	-118.78	degrees Celcius
   Normal night temperature:	-123.86	degrees Celcius
   Maximum temperature:   	-101.85	degrees Celcius
   Minimum temperature:   	-142.27	degrees Celcius
   Escape Velocity:		11.34	km/sec
   Molecular weight retained:	6.18 and above
   Surface acceleration:	988.21	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.662
   Length of year:		2042.16	days
   Length of day:		15.25	hours
   Boiling point of water:	95.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	83.12
   liquids at surface:
				Ozone        melts at -193  boils at -114
   gasses in atmosphere:
				Oxygen           19.5%  PP  165.4 mb
				Nitrogen         80.5%  PP  683.0 mb


Planet 8	*gas giant*
   Distance from primary:	4.697	AU
   Mass:			13.014	Earth masses
   Equatorial radius:		24965.8	km
   Density:			1.193	grams/cc
   Eccentricity of orbit:	0.083
   Escape Velocity:		20.39	km/sec
   Molecular weight retained:	1.91 and above
   Surface acceleration:	832.64	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.476
   Length of year:		3536.85	days
   Length of day:		14.16	hours


Planet 9	*gas giant*
   Distance from primary:	7.014	AU
   Mass:			872.385	Earth masses
   Equatorial radius:		88009.8	km
   Density:			1.826	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		88.91	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4491.43	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.454
   Length of year:		6447.38	days
   Length of day:		6.10	hours


Planet 10	*gas giant*
   Distance from primary:	14.126	AU
   Mass:			31.462	Earth masses
   Equatorial radius:		35401.0	km
   Density:			1.012	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		26.62	km/sec
   Molecular weight retained:	1.12 and above
   Surface acceleration:	1001.13	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.505
   Length of year:		18448.89	days
   Length of day:		12.92	hours


Planet 11	*gas giant*
   Distance from primary:	20.526	AU
   Mass:			23.519	Earth masses
   Equatorial radius:		33549.5	km
   Density:			0.889	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		23.65	km/sec
   Molecular weight retained:	1.42 and above
   Surface acceleration:	833.29	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.488
   Length of year:		32314.09	days
   Length of day:		14.16	hours


Planet 12	*gas giant*
   Distance from primary:	31.772	AU
   Mass:			9.121	Earth masses
   Equatorial radius:		26393.9	km
   Density:			0.708	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		16.60	km/sec
   Molecular weight retained:	2.88 and above
   Surface acceleration:	522.10	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.456
   Length of year:		62231.11	days
   Length of day:		17.89	hours


Planet 13	
   Distance from primary:	44.550	AU
   Mass:			0.225	Earth masses
   Equatorial radius:		5240.1	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.62	degrees Celcius
   Normal daytime temperature:	-222.31	degrees Celcius
   Normal night temperature:	-232.84	degrees Celcius
   Maximum temperature:   	-206.97	degrees Celcius
   Minimum temperature:   	-248.51	degrees Celcius
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.21 and above
   Surface acceleration:	326.37	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.163
   Length of year:		103328.30	days
   Length of day:		26.53	hours
   Boiling point of water:	-49.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 14	
   Distance from primary:	47.449	AU
   Mass:			1/222.6	Earth masses
   Equatorial radius:		1430.7	km
   Density:			2.189	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.09	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.18	degrees Celcius
   Normal daytime temperature:	-220.25	degrees Celcius
   Normal night temperature:	-237.93	degrees Celcius
   Maximum temperature:   	-204.67	degrees Celcius
   Minimum temperature:   	-252.67	degrees Celcius
   Escape Velocity:		1.58	km/sec
   Molecular weight retained:	316.95 and above
   Surface acceleration:	87.53	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.153
   Length of year:		113577.58	days
   Length of day:		51.23	hours
   Boiling point of water:	-106.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


