                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950489e3
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6234 K
Stellar class: F8
Age: 1.984 billion years  (4.747 billion left on main sequence)
Habitable ecosphere radius: 1.283 AU

Planets present at:
1	  0.427 AU	no atmosphere
2	  0.545 AU	no atmosphere
3	  0.681 AU	no atmosphere
4	  1.046 AU	greenhouse
5	  1.796 AU	high pressure
6	  2.779 AU	gas giant
7	  5.521 AU	gas giant
8	  8.787 AU	gas giant
9	 11.551 AU	gas giant
10	 20.491 AU	no atmosphere
11	 30.351 AU	gas giant
12	 46.218 AU	no atmosphere
13	 51.477 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.427	AU
   Mass:			0.405	Earth masses
   Equatorial radius:		4763.0	km
   Density:			5.348	grams/cc
   Eccentricity of orbit:	0.134
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.20	degrees Celcius
   Normal daytime temperature:	407.42	degrees Celcius
   Normal night temperature:	-189.98	degrees Celcius
   Maximum temperature:   	410.81	degrees Celcius
   Minimum temperature:   	-200.89	degrees Celcius
   Escape Velocity:		8.23	km/sec
   Molecular weight retained:	11.71 and above
   Surface acceleration:	711.88	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.072
   Length of year:		96.88	days
   Length of day:		1775.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.545	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		3420.7	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		146.17	degrees Celcius
   Maximum temperature:   	343.50	degrees Celcius
   Minimum temperature:   	-217.46	degrees Celcius
   Escape Velocity:		5.89	km/sec
   Molecular weight retained:	22.91 and above
   Surface acceleration:	506.49	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.078
   Length of year:		139.62	days
   Length of day:		3350.98	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.681	AU
   Mass:			1/346.6	Earth masses
   Equatorial radius:		922.2	km
   Density:			5.250	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.14	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		101.30	degrees Celcius
   Maximum temperature:   	287.56	degrees Celcius
   Minimum temperature:   	-225.05	degrees Celcius
   Escape Velocity:		1.58	km/sec
   Molecular weight retained:	318.11 and above
   Surface acceleration:	135.30	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.086
   Length of year:		194.78	days
   Length of day:		4674.61	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.046	AU
   Mass:			1.527	Earth masses
   Equatorial radius:		7346.3	km
   Density:			5.495	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		1.15	Earth gees
   Surface pressure:		193.737	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		412.82	degrees Celcius
   Maximum temperature:   	416.01	degrees Celcius
   Minimum temperature:   	408.01	degrees Celcius
   Escape Velocity:		12.87	km/sec
   Molecular weight retained:	4.79 and above
   Surface acceleration:	1128.19	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.591
   Length of year:		371.30	days
   Length of day:		14.48	hours
   Boiling point of water:	337.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1282
				Cesium       melts at 28    boils at 1327
				Gallium      melts at 30    boils at 4106
				Rubidium     melts at 39    boils at 1300
				Potassium    melts at 63    boils at 1427
				Sodium       melts at 98    boils at 1616
				Sulfur       melts at 113   boils at 902
				Indium       melts at 157   boils at 3578
				Lithium      melts at 181   boils at 2378
				Selenium     melts at 217   boils at 1295
				Tin          melts at 232   boils at 4466
				Polonium     melts at 254   boils at 1748
				Bismuth      melts at 271   boils at 2733
				Thallium     melts at 304   boils at 2558
				Cadmium      melts at 321   boils at 1426
				Lead         melts at 328   boils at 3039
   gasses in atmosphere:
				Nitrogen         99.3%  PP 192391.4 mb
				Phosphorus        0.5%  PP  883.6 mb


Planet 5	
   Distance from primary:	1.796	AU
   Mass:			1.754	Earth masses
   Equatorial radius:		7683.0	km
   Density:			5.520	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		1.21	Earth gees
   Surface pressure:		2.828	Earth atmospheres
   Surface temperature:		-69.04	degrees Celcius
   Normal daytime temperature:	-67.33	degrees Celcius
   Normal night temperature:	-70.84	degrees Celcius
   Maximum temperature:   	-53.97	degrees Celcius
   Minimum temperature:   	-85.09	degrees Celcius
   Escape Velocity:		13.49	km/sec
   Molecular weight retained:	4.36 and above
   Surface acceleration:	1185.17	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.721
   Length of year:		835.06	days
   Length of day:		13.93	hours
   Boiling point of water:	131.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.16
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 108
				Chlorine     melts at -101  boils at -14
				Ammonia      melts at -78   boils at -14
				Radon        melts at -71   boils at -45
   gasses in atmosphere:
				Oxygen            0.2%  PP    5.2 mb
				Nitrogen         99.7%  PP 2819.7 mb


Planet 6	*gas giant*
   Distance from primary:	2.779	AU
   Mass:			180.299	Earth masses
   Equatorial radius:		51408.7	km
   Density:			1.894	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		52.89	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2720.57	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.487
   Length of year:		1607.11	days
   Length of day:		7.84	hours


Planet 7	*gas giant*
   Distance from primary:	5.521	AU
   Mass:			175.803	Earth masses
   Equatorial radius:		54035.5	km
   Density:			1.590	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		50.94	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2401.08	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.531
   Length of year:		4499.81	days
   Length of day:		8.34	hours


Planet 8	*gas giant*
   Distance from primary:	8.787	AU
   Mass:			1.885	Earth masses
   Equatorial radius:		14963.0	km
   Density:			0.803	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		10.02	km/sec
   Molecular weight retained:	7.90 and above
   Surface acceleration:	335.81	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.488
   Length of year:		9036.55	days
   Length of day:		22.30	hours


Planet 9	*gas giant*
   Distance from primary:	11.551	AU
   Mass:			291.445	Earth masses
   Equatorial radius:		66592.1	km
   Density:			1.408	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		59.08	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2620.89	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.505
   Length of year:		13613.98	days
   Length of day:		7.98	hours


Planet 10	
   Distance from primary:	20.491	AU
   Mass:			0.293	Earth masses
   Equatorial radius:		5719.0	km
   Density:			2.237	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-205.27	degrees Celcius
   Normal daytime temperature:	-197.67	degrees Celcius
   Normal night temperature:	-212.84	degrees Celcius
   Maximum temperature:   	-181.35	degrees Celcius
   Minimum temperature:   	-230.19	degrees Celcius
   Escape Velocity:		6.39	km/sec
   Molecular weight retained:	19.41 and above
   Surface acceleration:	357.53	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.163
   Length of year:		32180.79	days
   Length of day:		25.35	hours
   Boiling point of water:	-43.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 11	*gas giant*
   Distance from primary:	30.351	AU
   Mass:			4.652	Earth masses
   Equatorial radius:		21591.3	km
   Density:			0.659	grams/cc
   Eccentricity of orbit:	0.260
   Escape Velocity:		13.11	km/sec
   Molecular weight retained:	4.62 and above
   Surface acceleration:	397.92	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.519
   Length of year:		58008.99	days
   Length of day:		20.49	hours


Planet 12	
   Distance from primary:	46.218	AU
   Mass:			0.074	Earth masses
   Equatorial radius:		3622.9	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.51	degrees Celcius
   Normal daytime temperature:	-222.37	degrees Celcius
   Normal night temperature:	-234.55	degrees Celcius
   Maximum temperature:   	-206.43	degrees Celcius
   Minimum temperature:   	-250.43	degrees Celcius
   Escape Velocity:		4.02	km/sec
   Molecular weight retained:	49.05 and above
   Surface acceleration:	223.36	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.160
   Length of year:		109008.29	days
   Length of day:		32.07	hours
   Boiling point of water:	-69.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 13	
   Distance from primary:	51.477	AU
   Mass:			0.138	Earth masses
   Equatorial radius:		4457.0	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.59	degrees Celcius
   Normal daytime temperature:	-225.25	degrees Celcius
   Normal night temperature:	-235.83	degrees Celcius
   Maximum temperature:   	-214.47	degrees Celcius
   Minimum temperature:   	-247.11	degrees Celcius
   Escape Velocity:		4.96	km/sec
   Molecular weight retained:	32.25 and above
   Surface acceleration:	276.10	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.142
   Length of year:		128134.11	days
   Length of day:		28.84	hours
   Boiling point of water:	-59.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


