                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048537
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6295 K
Stellar class: F8
Age: 3.611 billion years  (3.272 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.422 AU	no atmosphere
2	  0.596 AU	no atmosphere
3	  1.119 AU	greenhouse
4	  1.453 AU	
5	  1.851 AU	gas giant
6	  2.587 AU	no atmosphere
7	  3.618 AU	gas giant
8	  6.475 AU	gas giant
9	 15.249 AU	gas giant
10	 33.582 AU	gas giant



Planet 1	
   Distance from primary:	0.422	AU
   Mass:			0.388	Earth masses
   Equatorial radius:		4697.5	km
   Density:			5.345	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		200.83	degrees Celcius
   Maximum temperature:   	410.69	degrees Celcius
   Minimum temperature:   	-205.32	degrees Celcius
   Escape Velocity:		8.12	km/sec
   Molecular weight retained:	12.04 and above
   Surface acceleration:	701.70	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.074
   Length of year:		95.23	days
   Length of day:		2285.60	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.596	AU
   Mass:			0.089	Earth masses
   Equatorial radius:		2886.5	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		126.77	degrees Celcius
   Maximum temperature:   	319.52	degrees Celcius
   Minimum temperature:   	-221.49	degrees Celcius
   Escape Velocity:		4.96	km/sec
   Molecular weight retained:	32.26 and above
   Surface acceleration:	426.18	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.063
   Length of year:		159.93	days
   Length of day:		3838.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.119	AU
   Mass:			0.712	Earth masses
   Equatorial radius:		5732.6	km
   Density:			5.395	grams/cc
   Eccentricity of orbit:	0.199
   Surface gravity:		0.88	Earth gees
   Surface pressure:		53.253	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		281.44	degrees Celcius
   Maximum temperature:   	287.51	degrees Celcius
   Minimum temperature:   	274.49	degrees Celcius
   Escape Velocity:		9.95	km/sec
   Molecular weight retained:	8.01 and above
   Surface acceleration:	864.31	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.439
   Length of year:		412.12	days
   Length of day:		16.87	hours
   Boiling point of water:	255.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 619
				Francium     melts at 27    boils at 1072
				Cesium       melts at 28    boils at 1111
				Gallium      melts at 30    boils at 3515
				Rubidium     melts at 39    boils at 1087
				Potassium    melts at 63    boils at 1197
				Sodium       melts at 98    boils at 1361
				Sulfur       melts at 113   boils at 743
				Indium       melts at 157   boils at 3058
				Lithium      melts at 181   boils at 2020
				Selenium     melts at 217   boils at 1083
				Tin          melts at 232   boils at 3826
				Polonium     melts at 254   boils at 1475
				Bismuth      melts at 271   boils at 2327
   gasses in atmosphere:
				Nitrogen         99.0%  PP 52713.5 mb
				Phosphorus        0.7%  PP  355.4 mb
				CarbonDioxide     0.1%  PP   39.8 mb
				Ozone             0.1%  PP   37.2 mb
				Ethanol           0.1%  PP   40.4 mb


Planet 4	
   Distance from primary:	1.453	AU
   Mass:			0.645	Earth masses
   Equatorial radius:		5549.6	km
   Density:			5.385	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.417	Earth atmospheres
   Surface temperature:		5.18	degrees Celcius
   Normal daytime temperature:	12.00	degrees Celcius
   Normal night temperature:	-2.03	degrees Celcius
   Maximum temperature:   	37.74	degrees Celcius
   Minimum temperature:   	-29.22	degrees Celcius
   Escape Velocity:		9.63	km/sec
   Molecular weight retained:	8.56 and above
   Surface acceleration:	835.25	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.164
   Length of year:		609.53	days
   Length of day:		16.71	hours
   Boiling point of water:	77.4	degrees Celcius
   Hydrosphere percentage:	60.71
   Cloud cover percentage:	22.31
   Ice cover percentage:	4.94
   liquids at surface:
				Ethanol      melts at -114  boils at 57
				Mercury      melts at -39   boils at 319
				Bromine      melts at -7    boils at 39
				Water        melts at 0     boils at 77
   gasses in atmosphere:
				Oxygen           42.7%  PP  178.0 mb
				Nitrogen         57.2%  PP  238.7 mb


Planet 5	*gas giant*
   Distance from primary:	1.851	AU
   Mass:			23.708	Earth masses
   Equatorial radius:		27533.1	km
   Density:			1.621	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		26.21	km/sec
   Molecular weight retained:	1.16 and above
   Surface acceleration:	1247.15	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.520
   Length of year:		876.38	days
   Length of day:		11.57	hours


Planet 6	
   Distance from primary:	2.587	AU
   Mass:			0.244	Earth masses
   Equatorial radius:		4029.7	km
   Density:			5.318	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.060	Earth atmospheres
   Surface temperature:		-98.77	degrees Celcius
   Normal daytime temperature:	-88.42	degrees Celcius
   Normal night temperature:	-109.42	degrees Celcius
   Maximum temperature:   	-66.41	degrees Celcius
   Minimum temperature:   	-132.71	degrees Celcius
   Escape Velocity:		6.95	km/sec
   Molecular weight retained:	16.44 and above
   Surface acceleration:	598.98	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.497
   Length of year:		1447.93	days
   Length of day:		19.59	hours
   Boiling point of water:	35.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	65.41
   liquids at surface:
				Ethanol      melts at -114  boils at 18
				Chlorine     melts at -101  boils at -75
   gasses in atmosphere:
				Ozone            92.9%  PP   55.5 mb
				Fluorine          0.1%  PP    0.1 mb
				Argon             0.2%  PP    0.1 mb
				Neon              0.8%  PP    0.5 mb
				Krypton           5.3%  PP    3.2 mb
				Xenon             0.6%  PP    0.4 mb


Planet 7	*gas giant*
   Distance from primary:	3.618	AU
   Mass:			18.836	Earth masses
   Equatorial radius:		27224.6	km
   Density:			1.332	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		23.49	km/sec
   Molecular weight retained:	1.44 and above
   Surface acceleration:	1013.43	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.534
   Length of year:		2394.12	days
   Length of day:		12.84	hours


Planet 8	*gas giant*
   Distance from primary:	6.475	AU
   Mass:			433.737	Earth masses
   Equatorial radius:		71342.9	km
   Density:			1.704	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		69.63	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3398.32	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.459
   Length of year:		5729.40	days
   Length of day:		7.01	hours


Planet 9	*gas giant*
   Distance from primary:	15.249	AU
   Mass:			686.322	Earth masses
   Equatorial radius:		87595.4	km
   Density:			1.457	grams/cc
   Eccentricity of orbit:	0.136
   Escape Velocity:		79.05	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3567.01	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.469
   Length of year:		20700.50	days
   Length of day:		6.84	hours


Planet 10	*gas giant*
   Distance from primary:	33.582	AU
   Mass:			14.958	Earth masses
   Equatorial radius:		30647.9	km
   Density:			0.741	grams/cc
   Eccentricity of orbit:	0.183
   Escape Velocity:		19.73	km/sec
   Molecular weight retained:	2.04 and above
   Surface acceleration:	635.04	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.499
   Length of year:		67714.32	days
   Length of day:		16.22	hours


