                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048519
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6279 K
Stellar class: F8
Age: 1.797 billion years  (5.090 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.604 AU	no atmosphere
3	  1.183 AU	high pressure
4	  1.718 AU	high pressure
5	  2.093 AU	no atmosphere
6	  3.054 AU	cold
7	  5.125 AU	gas giant
8	  8.340 AU	gas giant
9	 11.542 AU	gas giant
10	 21.448 AU	gas giant
11	 32.282 AU	gas giant
12	 48.332 AU	no atmosphere
13	 51.537 AU	no atmosphere



Planet 1	
   Distance from primary:	0.370	AU
   Mass:			0.129	Earth masses
   Equatorial radius:		3266.1	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		234.86	degrees Celcius
   Maximum temperature:   	451.81	degrees Celcius
   Minimum temperature:   	-195.81	degrees Celcius
   Escape Velocity:		5.62	km/sec
   Molecular weight retained:	25.15 and above
   Surface acceleration:	483.18	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.057
   Length of year:		78.34	days
   Length of day:		1880.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.604	AU
   Mass:			0.564	Earth masses
   Equatorial radius:		5311.5	km
   Density:			5.373	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.15	degrees Celcius
   Normal daytime temperature:	236.60	degrees Celcius
   Normal night temperature:	-1.06	degrees Celcius
   Maximum temperature:   	260.84	degrees Celcius
   Minimum temperature:   	-31.03	degrees Celcius
   Escape Velocity:		9.20	km/sec
   Molecular weight retained:	9.37 and above
   Surface acceleration:	797.62	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.060
   Length of year:		163.42	days
   Length of day:		92.09	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.183	AU
   Mass:			2.529	Earth masses
   Equatorial radius:		8639.0	km
   Density:			5.597	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		1.38	Earth gees
   Surface pressure:		4.691	Earth atmospheres
   Surface temperature:		25.22	degrees Celcius
   Normal daytime temperature:	27.04	degrees Celcius
   Normal night temperature:	23.27	degrees Celcius
   Maximum temperature:   	39.33	degrees Celcius
   Minimum temperature:   	10.38	degrees Celcius
   Escape Velocity:		15.28	km/sec
   Molecular weight retained:	3.40 and above
   Surface acceleration:	1351.29	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.477
   Length of year:		447.83	days
   Length of day:		13.09	hours
   Boiling point of water:	148.1	degrees Celcius
   Hydrosphere percentage:	71.83
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.37
   liquids at surface:
				Ethanol      melts at -114  boils at 124
				Mercury      melts at -39   boils at 438
				Bromine      melts at -7    boils at 102
				Water        melts at 0     boils at 148
   gasses in atmosphere:
				Nitrogen          0.7%  PP   30.7 mb
				Helium           99.3%  PP 4660.4 mb


Planet 4	
   Distance from primary:	1.718	AU
   Mass:			1.998	Earth masses
   Equatorial radius:		8010.7	km
   Density:			5.545	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		1.27	Earth gees
   Surface pressure:		4.081	Earth atmospheres
   Surface temperature:		-2.06	degrees Celcius
   Normal daytime temperature:	-0.22	degrees Celcius
   Normal night temperature:	-4.02	degrees Celcius
   Maximum temperature:   	11.82	degrees Celcius
   Minimum temperature:   	-16.69	degrees Celcius
   Escape Velocity:		14.10	km/sec
   Molecular weight retained:	3.99 and above
   Surface acceleration:	1241.37	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.231
   Length of year:		783.45	days
   Length of day:		13.61	hours
   Boiling point of water:	143.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	19.56
   Ice cover percentage:	10.34
   liquids at surface:
				Ethanol      melts at -114  boils at 119
				Mercury      melts at -39   boils at 430
				Bromine      melts at -7    boils at 98
   gasses in atmosphere:
				Nitrogen         24.4%  PP  997.0 mb
				Helium           75.5%  PP 3082.1 mb


Planet 5	
   Distance from primary:	2.093	AU
   Mass:			0.152	Earth masses
   Equatorial radius:		3449.1	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.017	Earth atmospheres
   Surface temperature:		-74.07	degrees Celcius
   Normal daytime temperature:	-57.72	degrees Celcius
   Normal night temperature:	-90.65	degrees Celcius
   Maximum temperature:   	-33.80	degrees Celcius
   Minimum temperature:   	-115.48	degrees Celcius
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.53 and above
   Surface acceleration:	510.78	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.352
   Length of year:		1054.03	days
   Length of day:		21.24	hours
   Boiling point of water:	13.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	41.19
   liquids at surface:
				Ethanol      melts at -114  boils at -2
   gasses in atmosphere:
				CarbonDioxide    46.0%  PP    7.9 mb
				Ozone            50.3%  PP    8.7 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           3.2%  PP    0.6 mb
				Xenon             0.4%  PP    0.1 mb


Planet 6	
   Distance from primary:	3.054	AU
   Mass:			0.876	Earth masses
   Equatorial radius:		6134.6	km
   Density:			5.417	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.818	Earth atmospheres
   Surface temperature:		-116.97	degrees Celcius
   Normal daytime temperature:	-114.31	degrees Celcius
   Normal night temperature:	-119.78	degrees Celcius
   Maximum temperature:   	-96.77	degrees Celcius
   Minimum temperature:   	-138.82	degrees Celcius
   Escape Velocity:		10.67	km/sec
   Molecular weight retained:	6.97 and above
   Surface acceleration:	928.76	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.661
   Length of year:		1857.48	days
   Length of day:		15.73	hours
   Boiling point of water:	94.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -114
   gasses in atmosphere:
				Oxygen           24.6%  PP  201.2 mb
				Nitrogen         75.4%  PP  616.5 mb


Planet 7	*gas giant*
   Distance from primary:	5.125	AU
   Mass:			151.851	Earth masses
   Equatorial radius:		51517.8	km
   Density:			1.585	grams/cc
   Eccentricity of orbit:	0.227
   Escape Velocity:		48.49	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2281.62	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.512
   Length of year:		4036.37	days
   Length of day:		8.56	hours


Planet 8	*gas giant*
   Distance from primary:	8.340	AU
   Mass:			3.083	Earth masses
   Equatorial radius:		17216.2	km
   Density:			0.862	grams/cc
   Eccentricity of orbit:	0.111
   Escape Velocity:		11.95	km/sec
   Molecular weight retained:	5.56 and above
   Surface acceleration:	414.76	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.531
   Length of year:		8381.05	days
   Length of day:		20.07	hours


Planet 9	*gas giant*
   Distance from primary:	11.542	AU
   Mass:			790.917	Earth masses
   Equatorial radius:		89203.2	km
   Density:			1.590	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		84.09	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	3963.78	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.520
   Length of year:		13629.73	days
   Length of day:		6.49	hours


Planet 10	*gas giant*
   Distance from primary:	21.448	AU
   Mass:			1.366	Earth masses
   Equatorial radius:		14688.7	km
   Density:			0.615	grams/cc
   Eccentricity of orbit:	0.145
   Escape Velocity:		8.61	km/sec
   Molecular weight retained:	10.71 and above
   Surface acceleration:	252.39	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.519
   Length of year:		34565.36	days
   Length of day:		25.73	hours


Planet 11	*gas giant*
   Distance from primary:	32.282	AU
   Mass:			13.220	Earth masses
   Equatorial radius:		29467.8	km
   Density:			0.737	grams/cc
   Eccentricity of orbit:	0.070
   Escape Velocity:		18.92	km/sec
   Molecular weight retained:	2.22 and above
   Surface acceleration:	607.14	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.468
   Length of year:		63825.10	days
   Length of day:		16.59	hours


Planet 12	
   Distance from primary:	48.332	AU
   Mass:			0.213	Earth masses
   Equatorial radius:		5149.2	km
   Density:			2.227	grams/cc
   Eccentricity of orbit:	0.153
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.41	degrees Celcius
   Normal daytime temperature:	-224.27	degrees Celcius
   Normal night temperature:	-234.45	degrees Celcius
   Maximum temperature:   	-206.57	degrees Celcius
   Minimum temperature:   	-251.95	degrees Celcius
   Escape Velocity:		5.74	km/sec
   Molecular weight retained:	24.05 and above
   Surface acceleration:	320.49	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.150
   Length of year:		116924.69	days
   Length of day:		26.77	hours
   Boiling point of water:	-50.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 13	
   Distance from primary:	51.537	AU
   Mass:			1/142.7	Earth masses
   Equatorial radius:		1658.9	km
   Density:			2.190	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.10	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.01	degrees Celcius
   Normal daytime temperature:	-222.94	degrees Celcius
   Normal night temperature:	-238.89	degrees Celcius
   Maximum temperature:   	-209.84	degrees Celcius
   Minimum temperature:   	-251.65	degrees Celcius
   Escape Velocity:		1.84	km/sec
   Molecular weight retained:	235.65 and above
   Surface acceleration:	101.53	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.145
   Length of year:		128747.78	days
   Length of day:		47.56	hours
   Boiling point of water:	-101.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


