                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481dc
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6266 K
Stellar class: F8
Age: 5.372 billion years  (1.624 billion left on main sequence)
Habitable ecosphere radius: 1.252 AU

Planets present at:
1	  0.432 AU	no atmosphere
2	  0.800 AU	no atmosphere
3	  0.858 AU	no atmosphere
4	  1.067 AU	greenhouse
5	  1.794 AU	gas giant
6	  3.308 AU	gas giant
7	  4.964 AU	gas giant
8	  6.856 AU	gas giant
9	 11.897 AU	gas giant
10	 18.523 AU	gas giant
11	 41.725 AU	no atmosphere
12	 47.534 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.432	AU
   Mass:			0.547	Earth masses
   Equatorial radius:		5256.5	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.218
   Surface gravity:		0.80	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.97	degrees Celcius
   Normal daytime temperature:	396.74	degrees Celcius
   Normal night temperature:	-187.14	degrees Celcius
   Maximum temperature:   	400.53	degrees Celcius
   Minimum temperature:   	-199.41	degrees Celcius
   Escape Velocity:		9.11	km/sec
   Molecular weight retained:	9.57 and above
   Surface acceleration:	788.97	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.073
   Length of year:		98.85	days
   Length of day:		1523.05	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.800	AU
   Mass:			0.014	Earth masses
   Equatorial radius:		1577.6	km
   Density:			5.257	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		68.56	degrees Celcius
   Maximum temperature:   	246.37	degrees Celcius
   Minimum temperature:   	-228.88	degrees Celcius
   Escape Velocity:		2.70	km/sec
   Molecular weight retained:	108.55 and above
   Surface acceleration:	231.78	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.081
   Length of year:		249.39	days
   Length of day:		5985.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	0.858	AU
   Mass:			0.076	Earth masses
   Equatorial radius:		2742.1	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		57.86	degrees Celcius
   Maximum temperature:   	232.79	degrees Celcius
   Minimum temperature:   	-230.15	degrees Celcius
   Escape Velocity:		4.71	km/sec
   Molecular weight retained:	35.78 and above
   Surface acceleration:	404.57	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.068
   Length of year:		277.32	days
   Length of day:		6655.79	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	1.067	AU
   Mass:			1.586	Earth masses
   Equatorial radius:		7437.0	km
   Density:			5.502	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		1.17	Earth gees
   Surface pressure:		220.579	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		427.16	degrees Celcius
   Maximum temperature:   	430.16	degrees Celcius
   Minimum temperature:   	422.43	degrees Celcius
   Escape Velocity:		13.04	km/sec
   Molecular weight retained:	4.67 and above
   Surface acceleration:	1143.47	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.554
   Length of year:		384.10	days
   Length of day:		14.67	hours
   Boiling point of water:	347.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1306
				Cesium       melts at 28    boils at 1353
				Gallium      melts at 30    boils at 4176
				Rubidium     melts at 39    boils at 1325
				Potassium    melts at 63    boils at 1454
				Sodium       melts at 98    boils at 1646
				Sulfur       melts at 113   boils at 920
				Indium       melts at 157   boils at 3639
				Lithium      melts at 181   boils at 2420
				Selenium     melts at 217   boils at 1320
				Tin          melts at 232   boils at 4542
				Polonium     melts at 254   boils at 1780
				Bismuth      melts at 271   boils at 2781
				Thallium     melts at 304   boils at 2603
				Cadmium      melts at 321   boils at 1453
				Lead         melts at 328   boils at 3092
				Zinc         melts at 420   boils at 1689
   gasses in atmosphere:
				Nitrogen         99.3%  PP 218928.0 mb
				Phosphorus        0.5%  PP 1123.2 mb
				CarbonDioxide     0.1%  PP  121.4 mb
				Ethanol           0.1%  PP  122.9 mb


Planet 5	*gas giant*
   Distance from primary:	1.794	AU
   Mass:			16.289	Earth masses
   Equatorial radius:		24635.3	km
   Density:			1.555	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		22.96	km/sec
   Molecular weight retained:	1.51 and above
   Surface acceleration:	1070.33	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.498
   Length of year:		838.13	days
   Length of day:		12.49	hours


Planet 6	*gas giant*
   Distance from primary:	3.308	AU
   Mass:			27.204	Earth masses
   Equatorial radius:		30106.7	km
   Density:			1.422	grams/cc
   Eccentricity of orbit:	0.107
   Escape Velocity:		26.85	km/sec
   Molecular weight retained:	1.10 and above
   Surface acceleration:	1196.87	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.495
   Length of year:		2098.13	days
   Length of day:		11.81	hours


Planet 7	*gas giant*
   Distance from primary:	4.964	AU
   Mass:			4.476	Earth masses
   Equatorial radius:		18397.8	km
   Density:			1.026	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		13.93	km/sec
   Molecular weight retained:	4.09 and above
   Surface acceleration:	527.39	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.465
   Length of year:		3856.16	days
   Length of day:		17.80	hours


Planet 8	*gas giant*
   Distance from primary:	6.856	AU
   Mass:			24.954	Earth masses
   Equatorial radius:		31196.0	km
   Density:			1.173	grams/cc
   Eccentricity of orbit:	0.087
   Escape Velocity:		25.26	km/sec
   Molecular weight retained:	1.24 and above
   Surface acceleration:	1022.55	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.491
   Length of year:		6259.01	days
   Length of day:		12.78	hours


Planet 9	*gas giant*
   Distance from primary:	11.897	AU
   Mass:			1085.491	Earth masses
   Equatorial radius:		98161.0	km
   Density:			1.638	grams/cc
   Eccentricity of orbit:	0.128
   Escape Velocity:		93.91	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4492.50	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.508
   Length of year:		14287.38	days
   Length of day:		6.10	hours


Planet 10	*gas giant*
   Distance from primary:	18.523	AU
   Mass:			19.723	Earth masses
   Equatorial radius:		31642.6	km
   Density:			0.888	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		22.30	km/sec
   Molecular weight retained:	1.60 and above
   Surface acceleration:	785.54	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.544
   Length of year:		27797.36	days
   Length of day:		14.58	hours


Planet 11	
   Distance from primary:	41.725	AU
   Mass:			0.073	Earth masses
   Equatorial radius:		3621.6	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.211
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.47	degrees Celcius
   Normal daytime temperature:	-220.04	degrees Celcius
   Normal night temperature:	-232.80	degrees Celcius
   Maximum temperature:   	-206.32	degrees Celcius
   Minimum temperature:   	-246.87	degrees Celcius
   Escape Velocity:		4.02	km/sec
   Molecular weight retained:	49.08 and above
   Surface acceleration:	223.28	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.139
   Length of year:		93983.20	days
   Length of day:		32.07	hours
   Boiling point of water:	-70.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


Planet 12	
   Distance from primary:	47.534	AU
   Mass:			0.196	Earth masses
   Equatorial radius:		5005.5	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.43	degrees Celcius
   Normal daytime temperature:	-224.23	degrees Celcius
   Normal night temperature:	-234.54	degrees Celcius
   Maximum temperature:   	-212.75	degrees Celcius
   Minimum temperature:   	-246.58	degrees Celcius
   Escape Velocity:		5.58	km/sec
   Molecular weight retained:	25.48 and above
   Surface acceleration:	311.23	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.161
   Length of year:		114276.60	days
   Length of day:		27.17	hours
   Boiling point of water:	-53.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


