                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a81
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6306 K
Stellar class: F7
Age: 1.997 billion years  (4.713 billion left on main sequence)
Habitable ecosphere radius: 1.286 AU

Planets present at:
1	  0.320 AU	no atmosphere
2	  0.893 AU	greenhouse
3	  1.237 AU	high pressure
4	  2.138 AU	cold
5	  4.046 AU	gas giant
6	  5.780 AU	gas giant
7	  9.365 AU	cold
8	 13.481 AU	gas giant
9	 19.893 AU	gas giant
10	 34.548 AU	no atmosphere
11	 51.068 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.320	AU
   Mass:			0.140	Earth masses
   Equatorial radius:		3357.1	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.124
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		272.44	degrees Celcius
   Normal daytime temperature:	492.97	degrees Celcius
   Normal night temperature:	-163.90	degrees Celcius
   Maximum temperature:   	496.55	degrees Celcius
   Minimum temperature:   	-177.03	degrees Celcius
   Escape Velocity:		5.78	km/sec
   Molecular weight retained:	23.79 and above
   Surface acceleration:	496.89	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.091
   Length of year:		62.86	days
   Length of day:		1176.15	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.893	AU
   Mass:			1.590	Earth masses
   Equatorial radius:		7442.7	km
   Density:			5.502	grams/cc
   Eccentricity of orbit:	0.148
   Surface gravity:		1.17	Earth gees
   Surface pressure:		271.252	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		556.13	degrees Celcius
   Maximum temperature:   	558.44	degrees Celcius
   Minimum temperature:   	550.78	degrees Celcius
   Escape Velocity:		13.05	km/sec
   Molecular weight retained:	4.66 and above
   Surface acceleration:	1144.44	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.491
   Length of year:		292.59	days
   Length of day:		14.72	hours
   Boiling point of water:	363.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1347
				Cesium       melts at 28    boils at 1395
				Gallium      melts at 30    boils at 4292
				Rubidium     melts at 39    boils at 1366
				Potassium    melts at 63    boils at 1499
				Sodium       melts at 98    boils at 1697
				Indium       melts at 157   boils at 3741
				Lithium      melts at 181   boils at 2490
				Selenium     melts at 217   boils at 1361
				Tin          melts at 232   boils at 4667
				Polonium     melts at 254   boils at 1834
				Bismuth      melts at 271   boils at 2861
				Thallium     melts at 304   boils at 2678
				Cadmium      melts at 321   boils at 1498
				Lead         melts at 328   boils at 3180
				Zinc         melts at 420   boils at 1740
				Tellurium    melts at 450   boils at 1881
   gasses in atmosphere:
				Sulfur           18.6%  PP 50450.7 mb
				Nitrogen         80.8%  PP 219275.8 mb
				Phosphorus        0.4%  PP 1009.1 mb


Planet 3	
   Distance from primary:	1.237	AU
   Mass:			2.795	Earth masses
   Equatorial radius:		8918.9	km
   Density:			5.622	grams/cc
   Eccentricity of orbit:	0.127
   Surface gravity:		1.43	Earth gees
   Surface pressure:		6.046	Earth atmospheres
   Surface temperature:		42.58	degrees Celcius
   Normal daytime temperature:	44.24	degrees Celcius
   Normal night temperature:	40.79	degrees Celcius
   Maximum temperature:   	55.76	degrees Celcius
   Minimum temperature:   	28.74	degrees Celcius
   Escape Velocity:		15.81	km/sec
   Molecular weight retained:	3.18 and above
   Surface acceleration:	1401.24	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.469
   Length of year:		477.35	days
   Length of day:		12.85	hours
   Boiling point of water:	157.2	degrees Celcius
   Hydrosphere percentage:	78.59
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 132
				Mercury      melts at -39   boils at 453
				Bromine      melts at -7    boils at 111
				Water        melts at 0     boils at 157
				Francium     melts at 27    boils at 822
				Cesium       melts at 28    boils at 855
				Gallium      melts at 30    boils at 2813
				Rubidium     melts at 39    boils at 835
   gasses in atmosphere:
				Nitrogen          0.5%  PP   29.7 mb
				Helium           99.5%  PP 6015.9 mb


Planet 4	
   Distance from primary:	2.138	AU
   Mass:			0.604	Earth masses
   Equatorial radius:		5431.7	km
   Density:			5.379	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.302	Earth atmospheres
   Surface temperature:		-73.55	degrees Celcius
   Normal daytime temperature:	-67.87	degrees Celcius
   Normal night temperature:	-79.51	degrees Celcius
   Maximum temperature:   	-47.87	degrees Celcius
   Minimum temperature:   	-100.89	degrees Celcius
   Escape Velocity:		9.42	km/sec
   Molecular weight retained:	8.95 and above
   Surface acceleration:	816.59	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.522
   Length of year:		1083.81	days
   Length of day:		16.78	hours
   Boiling point of water:	69.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	73.48
   liquids at surface:
				Ethanol      melts at -114  boils at 50
				Chlorine     melts at -101  boils at -53
				Ammonia      melts at -78   boils at -53
   gasses in atmosphere:
				Oxygen           45.9%  PP  138.7 mb
				Nitrogen         54.0%  PP  163.1 mb


Planet 5	*gas giant*
   Distance from primary:	4.046	AU
   Mass:			901.537	Earth masses
   Equatorial radius:		84806.8	km
   Density:			2.109	grams/cc
   Eccentricity of orbit:	0.098
   Escape Velocity:		92.08	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4998.75	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.490
   Length of year:		2818.85	days
   Length of day:		5.78	hours


Planet 6	*gas giant*
   Distance from primary:	5.780	AU
   Mass:			10.068	Earth masses
   Equatorial radius:		23550.4	km
   Density:			1.100	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		18.47	km/sec
   Molecular weight retained:	2.33 and above
   Surface acceleration:	723.93	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.460
   Length of year:		4819.01	days
   Length of day:		15.19	hours


Planet 7	
   Distance from primary:	9.365	AU
   Mass:			0.579	Earth masses
   Equatorial radius:		7144.6	km
   Density:			2.267	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.184	Earth atmospheres
   Surface temperature:		-171.01	degrees Celcius
   Normal daytime temperature:	-166.36	degrees Celcius
   Normal night temperature:	-175.92	degrees Celcius
   Maximum temperature:   	-149.95	degrees Celcius
   Minimum temperature:   	-193.95	degrees Celcius
   Escape Velocity:		8.04	km/sec
   Molecular weight retained:	12.27 and above
   Surface acceleration:	452.59	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.305
   Length of year:		9938.00	days
   Length of day:		22.53	hours
   Boiling point of water:	58.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	26.97
   liquids at surface:
				Ozone        melts at -193  boils at -130
   gasses in atmosphere:
				Oxygen           63.3%  PP  116.6 mb
				Nitrogen         36.7%  PP   67.4 mb


Planet 8	*gas giant*
   Distance from primary:	13.481	AU
   Mass:			2.379	Earth masses
   Equatorial radius:		16592.5	km
   Density:			0.743	grams/cc
   Eccentricity of orbit:	0.101
   Escape Velocity:		10.69	km/sec
   Molecular weight retained:	6.94 and above
   Surface acceleration:	344.63	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.544
   Length of year:		17165.67	days
   Length of day:		22.02	hours


Planet 9	*gas giant*
   Distance from primary:	19.893	AU
   Mass:			301.417	Earth masses
   Equatorial radius:		70354.4	km
   Density:			1.235	grams/cc
   Eccentricity of orbit:	0.131
   Escape Velocity:		58.46	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2428.42	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.463
   Length of year:		30757.46	days
   Length of day:		8.29	hours


Planet 10	
   Distance from primary:	34.548	AU
   Mass:			0.117	Earth masses
   Equatorial radius:		4229.6	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-221.41	degrees Celcius
   Normal daytime temperature:	-214.75	degrees Celcius
   Normal night temperature:	-227.99	degrees Celcius
   Maximum temperature:   	-198.39	degrees Celcius
   Minimum temperature:   	-244.77	degrees Celcius
   Escape Velocity:		4.70	km/sec
   Molecular weight retained:	35.86 and above
   Surface acceleration:	261.65	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.156
   Length of year:		70421.94	days
   Length of day:		29.63	hours
   Boiling point of water:	-62.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 11	
   Distance from primary:	51.068	AU
   Mass:			0.187	Earth masses
   Equatorial radius:		4928.2	km
   Density:			2.224	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.24	degrees Celcius
   Normal daytime temperature:	-225.10	degrees Celcius
   Normal night temperature:	-235.29	degrees Celcius
   Maximum temperature:   	-211.23	degrees Celcius
   Minimum temperature:   	-249.48	degrees Celcius
   Escape Velocity:		5.49	km/sec
   Molecular weight retained:	26.30 and above
   Surface acceleration:	306.25	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.148
   Length of year:		126558.06	days
   Length of day:		27.39	hours
   Boiling point of water:	-52.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


