                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048227
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6312 K
Stellar class: F7
Age: 5.260 billion years  (1.726 billion left on main sequence)
Habitable ecosphere radius: 1.253 AU

Planets present at:
1	  0.420 AU	no atmosphere
2	  0.737 AU	greenhouse
3	  1.238 AU	high pressure
4	  2.129 AU	high pressure
5	  2.648 AU	no atmosphere
6	  3.295 AU	gas giant
7	  4.942 AU	gas giant
8	  9.401 AU	gas giant
9	 11.318 AU	gas giant
10	 22.553 AU	gas giant
11	 44.613 AU	no atmosphere
12	 46.415 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.420	AU
   Mass:			0.260	Earth masses
   Equatorial radius:		4115.2	km
   Density:			5.322	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		200.83	degrees Celcius
   Normal daytime temperature:	407.01	degrees Celcius
   Normal night temperature:	-190.43	degrees Celcius
   Maximum temperature:   	410.41	degrees Celcius
   Minimum temperature:   	-201.40	degrees Celcius
   Escape Velocity:		7.10	km/sec
   Molecular weight retained:	15.76 and above
   Surface acceleration:	612.04	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.064
   Length of year:		94.86	days
   Length of day:		1803.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.737	AU
   Mass:			0.604	Earth masses
   Equatorial radius:		5429.8	km
   Density:			5.379	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.83	Earth gees
   Surface pressure:		35.086	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		254.33	degrees Celcius
   Maximum temperature:   	263.31	degrees Celcius
   Minimum temperature:   	243.57	degrees Celcius
   Escape Velocity:		9.42	km/sec
   Molecular weight retained:	8.95 and above
   Surface acceleration:	816.29	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.518
   Length of year:		220.54	days
   Length of day:		52.59	hours
   Boiling point of water:	232.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 581
				Francium     melts at 27    boils at 1015
				Cesium       melts at 28    boils at 1053
				Gallium      melts at 30    boils at 3357
				Rubidium     melts at 39    boils at 1030
				Phosphorus   melts at 44    boils at 478
				Potassium    melts at 63    boils at 1136
				Sodium       melts at 98    boils at 1293
				Sulfur       melts at 113   boils at 701
				Indium       melts at 157   boils at 2918
				Lithium      melts at 181   boils at 1924
				Selenium     melts at 217   boils at 1026
				Tin          melts at 232   boils at 3655
				Polonium     melts at 254   boils at 1402
   gasses in atmosphere:
				Nitrogen         99.5%  PP 34918.8 mb
				Water             0.1%  PP   17.6 mb
				CarbonDioxide     0.1%  PP   39.3 mb
				Ozone             0.1%  PP   37.5 mb
				Ethanol           0.1%  PP   40.3 mb


Planet 3	
   Distance from primary:	1.238	AU
   Mass:			2.114	Earth masses
   Equatorial radius:		8157.8	km
   Density:			5.557	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		1.29	Earth gees
   Surface pressure:		4.330	Earth atmospheres
   Surface temperature:		17.53	degrees Celcius
   Normal daytime temperature:	19.45	degrees Celcius
   Normal night temperature:	15.49	degrees Celcius
   Maximum temperature:   	32.08	degrees Celcius
   Minimum temperature:   	2.22	degrees Celcius
   Escape Velocity:		14.38	km/sec
   Molecular weight retained:	3.84 and above
   Surface acceleration:	1266.84	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.468
   Length of year:		479.96	days
   Length of day:		13.61	hours
   Boiling point of water:	145.3	degrees Celcius
   Hydrosphere percentage:	88.95
   Cloud cover percentage:	75.46
   Ice cover percentage:	1.23
   liquids at surface:
				Ethanol      melts at -114  boils at 121
				Mercury      melts at -39   boils at 433
				Bromine      melts at -7    boils at 100
				Water        melts at 0     boils at 145
   gasses in atmosphere:
				Nitrogen          2.9%  PP  127.1 mb
				Helium           97.1%  PP 4202.6 mb


Planet 4	
   Distance from primary:	2.129	AU
   Mass:			1.500	Earth masses
   Equatorial radius:		7303.7	km
   Density:			5.492	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		1.14	Earth gees
   Surface pressure:		2.075	Earth atmospheres
   Surface temperature:		-80.61	degrees Celcius
   Normal daytime temperature:	-78.69	degrees Celcius
   Normal night temperature:	-82.64	degrees Celcius
   Maximum temperature:   	-64.35	degrees Celcius
   Minimum temperature:   	-98.00	degrees Celcius
   Escape Velocity:		12.80	km/sec
   Molecular weight retained:	4.85 and above
   Surface acceleration:	1121.03	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.659
   Length of year:		1082.73	days
   Length of day:		14.32	hours
   Boiling point of water:	121.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 99
				Chlorine     melts at -101  boils at -20
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2073.3 mb
				Ozone             0.1%  PP    1.0 mb


Planet 5	
   Distance from primary:	2.648	AU
   Mass:			0.273	Earth masses
   Equatorial radius:		4183.0	km
   Density:			5.324	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.063	Earth atmospheres
   Surface temperature:		-98.06	degrees Celcius
   Normal daytime temperature:	-88.00	degrees Celcius
   Normal night temperature:	-108.42	degrees Celcius
   Maximum temperature:   	-66.14	degrees Celcius
   Minimum temperature:   	-131.57	degrees Celcius
   Escape Velocity:		7.22	km/sec
   Molecular weight retained:	15.24 and above
   Surface acceleration:	622.43	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.456
   Length of year:		1502.66	days
   Length of day:		19.22	hours
   Boiling point of water:	36.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	57.11
   liquids at surface:
				Ethanol      melts at -114  boils at 19
				Chlorine     melts at -101  boils at -74
   gasses in atmosphere:
				Oxygen           90.9%  PP   57.2 mb
				Methane           0.5%  PP    0.3 mb
				Ozone             8.0%  PP    5.1 mb
				Neon              0.1%  PP    0.1 mb
				Krypton           0.5%  PP    0.3 mb
				Xenon             0.1%  PP    0.0 mb


Planet 6	*gas giant*
   Distance from primary:	3.295	AU
   Mass:			278.544	Earth masses
   Equatorial radius:		59312.8	km
   Density:			1.905	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		61.20	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	3157.44	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.542
   Length of year:		2084.78	days
   Length of day:		7.27	hours


Planet 7	*gas giant*
   Distance from primary:	4.942	AU
   Mass:			131.588	Earth masses
   Equatorial radius:		49297.8	km
   Density:			1.567	grams/cc
   Eccentricity of orbit:	0.019
   Escape Velocity:		46.14	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	2159.23	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.483
   Length of year:		3829.87	days
   Length of day:		8.80	hours


Planet 8	*gas giant*
   Distance from primary:	9.401	AU
   Mass:			1.007	Earth masses
   Equatorial radius:		12558.5	km
   Density:			0.726	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		8.00	km/sec
   Molecular weight retained:	12.41 and above
   Surface acceleration:	254.74	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.465
   Length of year:		10049.21	days
   Length of day:		25.61	hours


Planet 9	*gas giant*
   Distance from primary:	11.318	AU
   Mass:			68.381	Earth masses
   Equatorial radius:		43641.4	km
   Density:			1.174	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		35.35	km/sec
   Molecular weight retained:	0.64 and above
   Surface acceleration:	1431.78	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.468
   Length of year:		13272.97	days
   Length of day:		10.80	hours


Planet 10	*gas giant*
   Distance from primary:	22.553	AU
   Mass:			71.110	Earth masses
   Equatorial radius:		46753.1	km
   Density:			0.993	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		34.83	km/sec
   Molecular weight retained:	0.65 and above
   Surface acceleration:	1297.33	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.452
   Length of year:		37337.77	days
   Length of day:		11.35	hours


Planet 11	
   Distance from primary:	44.613	AU
   Mass:			0.154	Earth masses
   Equatorial radius:		4630.8	km
   Density:			2.219	grams/cc
   Eccentricity of orbit:	0.201
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.02	degrees Celcius
   Normal daytime temperature:	-222.45	degrees Celcius
   Normal night temperature:	-233.50	degrees Celcius
   Maximum temperature:   	-209.23	degrees Celcius
   Minimum temperature:   	-247.18	degrees Celcius
   Escape Velocity:		5.16	km/sec
   Molecular weight retained:	29.85 and above
   Surface acceleration:	287.19	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.159
   Length of year:		103887.96	days
   Length of day:		28.28	hours
   Boiling point of water:	-58.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 12	*gas giant*
   Distance from primary:	46.415	AU
   Mass:			0.318	Earth masses
   Equatorial radius:		10248.5	km
   Density:			0.422	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		4.97	km/sec
   Molecular weight retained:	32.08 and above
   Surface acceleration:	120.74	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.485
   Length of year:		110245.09	days
   Length of day:		37.20	hours


