                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048460
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6382 K
Stellar class: F7
Age: 5.338 billion years  (1.574 billion left on main sequence)
Habitable ecosphere radius: 1.262 AU

Planets present at:
1	  0.408 AU	no atmosphere
2	  0.566 AU	no atmosphere
3	  0.904 AU	no atmosphere
4	  0.966 AU	greenhouse
5	  1.035 AU	greenhouse
6	  1.446 AU	
7	  2.525 AU	gas giant
8	  5.396 AU	gas giant
9	 10.783 AU	gas giant
10	 21.088 AU	gas giant
11	 42.410 AU	gas giant
12	 51.006 AU	no atmosphere



Planet 1	
   Distance from primary:	0.408	AU
   Mass:			0.224	Earth masses
   Equatorial radius:		3915.2	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		209.12	degrees Celcius
   Maximum temperature:   	420.69	degrees Celcius
   Minimum temperature:   	-202.93	degrees Celcius
   Escape Velocity:		6.75	km/sec
   Molecular weight retained:	17.43 and above
   Surface acceleration:	581.50	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.063
   Length of year:		90.85	days
   Length of day:		2180.38	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.566	AU
   Mass:			0.246	Earth masses
   Equatorial radius:		4043.6	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		137.17	degrees Celcius
   Maximum temperature:   	332.19	degrees Celcius
   Minimum temperature:   	-218.75	degrees Celcius
   Escape Velocity:		6.97	km/sec
   Molecular weight retained:	16.33 and above
   Surface acceleration:	601.09	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.057
   Length of year:		148.30	days
   Length of day:		3559.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.904	AU
   Mass:			0.037	Earth masses
   Equatorial radius:		2149.6	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		52.23	degrees Celcius
   Maximum temperature:   	225.59	degrees Celcius
   Minimum temperature:   	-230.83	degrees Celcius
   Escape Velocity:		3.69	km/sec
   Molecular weight retained:	58.36 and above
   Surface acceleration:	316.39	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.049
   Length of year:		299.33	days
   Length of day:		7183.86	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	0.966	AU
   Mass:			1.395	Earth masses
   Equatorial radius:		7134.4	km
   Density:			5.480	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		1.11	Earth gees
   Surface pressure:		170.749	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		470.59	degrees Celcius
   Maximum temperature:   	473.75	degrees Celcius
   Minimum temperature:   	465.24	degrees Celcius
   Escape Velocity:		12.49	km/sec
   Molecular weight retained:	5.09 and above
   Surface acceleration:	1092.69	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.461
   Length of year:		330.33	days
   Length of day:		15.57	hours
   Boiling point of water:	328.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1258
				Cesium       melts at 28    boils at 1303
				Gallium      melts at 30    boils at 4040
				Rubidium     melts at 39    boils at 1276
				Potassium    melts at 63    boils at 1401
				Sodium       melts at 98    boils at 1588
				Indium       melts at 157   boils at 3520
				Lithium      melts at 181   boils at 2338
				Selenium     melts at 217   boils at 1271
				Tin          melts at 232   boils at 4395
				Polonium     melts at 254   boils at 1718
				Bismuth      melts at 271   boils at 2688
				Thallium     melts at 304   boils at 2515
				Cadmium      melts at 321   boils at 1400
				Lead         melts at 328   boils at 2989
				Zinc         melts at 420   boils at 1629
				Tellurium    melts at 450   boils at 1763
   gasses in atmosphere:
				Sulfur           21.3%  PP 36367.7 mb
				Nitrogen         78.1%  PP 133308.4 mb
				Phosphorus        0.4%  PP  723.5 mb


Planet 5	
   Distance from primary:	1.035	AU
   Mass:			0.183	Earth masses
   Equatorial radius:		3663.8	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.55	Earth gees
   Surface pressure:		2.958	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		80.53	degrees Celcius
   Normal daytime temperature:	85.65	degrees Celcius
   Normal night temperature:	74.74	degrees Celcius
   Maximum temperature:   	101.16	degrees Celcius
   Minimum temperature:   	58.53	degrees Celcius
   Escape Velocity:		6.31	km/sec
   Molecular weight retained:	19.94 and above
   Surface acceleration:	543.28	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.048
   Length of year:		366.58	days
   Length of day:		27.19	hours
   Boiling point of water:	132.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 412
				Water        melts at 0     boils at 133
				Francium     melts at 27    boils at 760
				Cesium       melts at 28    boils at 790
				Gallium      melts at 30    boils at 2636
				Rubidium     melts at 39    boils at 772
				Phosphorus   melts at 44    boils at 329
				Potassium    melts at 63    boils at 856
   gasses in atmosphere:
				CarbonDioxide    30.9%  PP  915.2 mb
				Ozone            33.7%  PP  997.5 mb
				Ethanol          32.5%  PP  962.5 mb
				Argon             0.1%  PP    3.4 mb
				Krypton           2.3%  PP   69.4 mb
				Xenon             0.3%  PP    9.0 mb


Planet 6	
   Distance from primary:	1.446	AU
   Mass:			0.928	Earth masses
   Equatorial radius:		6249.9	km
   Density:			5.424	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.650	Earth atmospheres
   Surface temperature:		7.92	degrees Celcius
   Normal daytime temperature:	13.23	degrees Celcius
   Normal night temperature:	2.30	degrees Celcius
   Maximum temperature:   	36.49	degrees Celcius
   Minimum temperature:   	-22.30	degrees Celcius
   Escape Velocity:		10.88	km/sec
   Molecular weight retained:	6.70 and above
   Surface acceleration:	947.39	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.176
   Length of year:		605.48	days
   Length of day:		15.70	hours
   Boiling point of water:	88.5	degrees Celcius
   Hydrosphere percentage:	51.84
   Cloud cover percentage:	23.76
   Ice cover percentage:	3.55
   liquids at surface:
				Ethanol      melts at -114  boils at 68
				Mercury      melts at -39   boils at 338
				Bromine      melts at -7    boils at 49
				Water        melts at 0     boils at 89
   gasses in atmosphere:
				Oxygen           27.4%  PP  178.3 mb
				Nitrogen         72.4%  PP  471.0 mb


Planet 7	*gas giant*
   Distance from primary:	2.525	AU
   Mass:			89.534	Earth masses
   Equatorial radius:		41639.0	km
   Density:			1.770	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		41.41	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	2059.33	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.505
   Length of year:		1396.61	days
   Length of day:		9.01	hours


Planet 8	*gas giant*
   Distance from primary:	5.396	AU
   Mass:			720.998	Earth masses
   Equatorial radius:		81512.3	km
   Density:			1.900	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		83.99	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4327.41	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.515
   Length of year:		4360.02	days
   Length of day:		6.21	hours


Planet 9	*gas giant*
   Distance from primary:	10.783	AU
   Mass:			850.440	Earth masses
   Equatorial radius:		90613.3	km
   Density:			1.631	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		86.52	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4130.47	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.486
   Length of year:		12313.47	days
   Length of day:		6.36	hours


Planet 10	*gas giant*
   Distance from primary:	21.088	AU
   Mass:			8.921	Earth masses
   Equatorial radius:		25362.4	km
   Density:			0.780	grams/cc
   Eccentricity of orbit:	0.091
   Escape Velocity:		16.75	km/sec
   Molecular weight retained:	2.83 and above
   Surface acceleration:	553.06	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.528
   Length of year:		33713.27	days
   Length of day:		17.38	hours


Planet 11	*gas giant*
   Distance from primary:	42.410	AU
   Mass:			0.814	Earth masses
   Equatorial radius:		13371.7	km
   Density:			0.486	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		6.97	km/sec
   Molecular weight retained:	16.35 and above
   Surface acceleration:	181.52	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.461
   Length of year:		96152.62	days
   Length of day:		30.34	hours


Planet 12	
   Distance from primary:	51.006	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2786.7	km
   Density:			2.198	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.96	degrees Celcius
   Normal daytime temperature:	-224.45	degrees Celcius
   Normal night temperature:	-237.33	degrees Celcius
   Maximum temperature:   	-211.97	degrees Celcius
   Minimum temperature:   	-249.92	degrees Celcius
   Escape Velocity:		3.09	km/sec
   Molecular weight retained:	83.21 and above
   Surface acceleration:	171.16	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.156
   Length of year:		126822.82	days
   Length of day:		36.63	hours
   Boiling point of water:	-83.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


