                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504852f
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6314 K
Stellar class: F7
Age: 5.511 billion years  (1.374 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.380 AU	no atmosphere
2	  0.525 AU	no atmosphere
3	  0.884 AU	greenhouse
4	  1.818 AU	cold
5	  3.019 AU	gas giant
6	  5.257 AU	gas giant
7	  9.400 AU	gas giant
8	 12.947 AU	gas giant
9	 19.916 AU	gas giant
10	 33.977 AU	no atmosphere
11	 48.278 AU	no atmosphere



Planet 1	
   Distance from primary:	0.380	AU
   Mass:			0.067	Earth masses
   Equatorial radius:		2630.0	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		225.77	degrees Celcius
   Maximum temperature:   	440.82	degrees Celcius
   Minimum temperature:   	-198.18	degrees Celcius
   Escape Velocity:		4.52	km/sec
   Molecular weight retained:	38.91 and above
   Surface acceleration:	387.85	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.075
   Length of year:		81.53	days
   Length of day:		1956.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.525	AU
   Mass:			0.181	Earth masses
   Equatorial radius:		3650.3	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.67	degrees Celcius
   Maximum temperature:   	347.81	degrees Celcius
   Minimum temperature:   	-216.49	degrees Celcius
   Escape Velocity:		6.29	km/sec
   Molecular weight retained:	20.09 and above
   Surface acceleration:	541.23	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.089
   Length of year:		132.43	days
   Length of day:		3178.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.884	AU
   Mass:			2.428	Earth masses
   Equatorial radius:		8526.8	km
   Density:			5.587	grams/cc
   Eccentricity of orbit:	0.194
   Surface gravity:		1.36	Earth gees
   Surface pressure:		434.251	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		568.83	degrees Celcius
   Maximum temperature:   	570.59	degrees Celcius
   Minimum temperature:   	563.91	degrees Celcius
   Escape Velocity:		15.07	km/sec
   Molecular weight retained:	3.50 and above
   Surface acceleration:	1331.44	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.600
   Length of year:		289.33	days
   Length of day:		14.22	hours
   Boiling point of water:	403.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1450
				Cesium       melts at 28    boils at 1500
				Gallium      melts at 30    boils at 4580
				Rubidium     melts at 39    boils at 1470
				Potassium    melts at 63    boils at 1610
				Sodium       melts at 98    boils at 1821
				Indium       melts at 157   boils at 3994
				Lithium      melts at 181   boils at 2665
				Selenium     melts at 217   boils at 1464
				Tin          melts at 232   boils at 4979
				Polonium     melts at 254   boils at 1966
				Bismuth      melts at 271   boils at 3058
				Thallium     melts at 304   boils at 2864
				Cadmium      melts at 321   boils at 1609
				Lead         melts at 328   boils at 3397
				Zinc         melts at 420   boils at 1867
				Tellurium    melts at 450   boils at 2017
   gasses in atmosphere:
				Sulfur            0.3%  PP 1184.7 mb
				Nitrogen          1.1%  PP 4895.2 mb
				Helium           98.6%  PP 428137.0 mb


Planet 4	
   Distance from primary:	1.818	AU
   Mass:			0.700	Earth masses
   Equatorial radius:		5699.7	km
   Density:			5.393	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.457	Earth atmospheres
   Surface temperature:		-76.75	degrees Celcius
   Normal daytime temperature:	-72.19	degrees Celcius
   Normal night temperature:	-81.55	degrees Celcius
   Maximum temperature:   	-53.03	degrees Celcius
   Minimum temperature:   	-102.08	degrees Celcius
   Escape Velocity:		9.90	km/sec
   Molecular weight retained:	8.11 and above
   Surface acceleration:	859.09	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.679
   Length of year:		853.07	days
   Length of day:		16.40	hours
   Boiling point of water:	79.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	87.06
   liquids at surface:
				Ethanol      melts at -114  boils at 59
				Chlorine     melts at -101  boils at -47
				Ammonia      melts at -78   boils at -47
   gasses in atmosphere:
				Oxygen            0.4%  PP    2.0 mb
				Nitrogen         99.4%  PP  453.7 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ozone             0.1%  PP    0.4 mb


Planet 5	*gas giant*
   Distance from primary:	3.019	AU
   Mass:			554.141	Earth masses
   Equatorial radius:		71907.9	km
   Density:			2.127	grams/cc
   Eccentricity of orbit:	0.142
   Escape Velocity:		78.40	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	4273.72	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.483
   Length of year:		1824.28	days
   Length of day:		6.25	hours


Planet 6	*gas giant*
   Distance from primary:	5.257	AU
   Mass:			38.955	Earth masses
   Equatorial radius:		34716.6	km
   Density:			1.328	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		29.92	km/sec
   Molecular weight retained:	0.89 and above
   Surface acceleration:	1288.92	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.528
   Length of year:		4194.20	days
   Length of day:		11.38	hours


Planet 7	*gas giant*
   Distance from primary:	9.400	AU
   Mass:			2.000	Earth masses
   Equatorial radius:		15327.3	km
   Density:			0.793	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		10.20	km/sec
   Molecular weight retained:	7.63 and above
   Surface acceleration:	339.52	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.459
   Length of year:		10028.73	days
   Length of day:		22.18	hours


Planet 8	*gas giant*
   Distance from primary:	12.947	AU
   Mass:			659.694	Earth masses
   Equatorial radius:		85418.0	km
   Density:			1.510	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		78.48	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3605.65	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.500
   Length of year:		16195.37	days
   Length of day:		6.81	hours


Planet 9	*gas giant*
   Distance from primary:	19.916	AU
   Mass:			36.171	Earth masses
   Equatorial radius:		37962.1	km
   Density:			0.943	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		27.57	km/sec
   Molecular weight retained:	1.04 and above
   Surface acceleration:	1000.92	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.504
   Length of year:		30925.97	days
   Length of day:		12.92	hours


Planet 10	
   Distance from primary:	33.977	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		3301.0	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-221.14	degrees Celcius
   Normal daytime temperature:	-213.68	degrees Celcius
   Normal night temperature:	-228.52	degrees Celcius
   Maximum temperature:   	-201.12	degrees Celcius
   Minimum temperature:   	-241.61	degrees Celcius
   Escape Velocity:		3.66	km/sec
   Molecular weight retained:	59.17 and above
   Surface acceleration:	203.20	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.137
   Length of year:		68914.52	days
   Length of day:		33.62	hours
   Boiling point of water:	-75.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


Planet 11	
   Distance from primary:	48.278	AU
   Mass:			0.225	Earth masses
   Equatorial radius:		5244.2	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.30	degrees Celcius
   Normal daytime temperature:	-224.19	degrees Celcius
   Normal night temperature:	-234.32	degrees Celcius
   Maximum temperature:   	-208.34	degrees Celcius
   Minimum temperature:   	-250.32	degrees Celcius
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.17 and above
   Surface acceleration:	326.64	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.143
   Length of year:		116723.65	days
   Length of day:		26.52	hours
   Boiling point of water:	-51.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


