                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e49
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6351 K
Stellar class: F7
Age: 1.745 billion years  (5.374 billion left on main sequence)
Habitable ecosphere radius: 1.239 AU

Planets present at:
1	  0.371 AU	no atmosphere
2	  0.427 AU	no atmosphere
3	  0.508 AU	no atmosphere
4	  0.943 AU	greenhouse
5	  1.183 AU	
6	  1.428 AU	gas giant
7	  2.137 AU	no atmosphere
8	  2.625 AU	cold
9	  3.746 AU	gas giant
10	  5.759 AU	cold
11	 12.249 AU	gas giant
12	 20.331 AU	no atmosphere
13	 26.668 AU	gas giant
14	 44.425 AU	gas giant



Planet 1	
   Distance from primary:	0.371	AU
   Mass:			0.038	Earth masses
   Equatorial radius:		2175.5	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		225.16	degrees Celcius
   Normal daytime temperature:	437.06	degrees Celcius
   Normal night temperature:	-187.89	degrees Celcius
   Maximum temperature:   	440.16	degrees Celcius
   Minimum temperature:   	-198.15	degrees Celcius
   Escape Velocity:		3.73	km/sec
   Molecular weight retained:	56.97 and above
   Surface acceleration:	320.23	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.086
   Length of year:		78.90	days
   Length of day:		1893.60	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.427	AU
   Mass:			0.239	Earth masses
   Equatorial radius:		4002.5	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.25	degrees Celcius
   Maximum temperature:   	400.05	degrees Celcius
   Minimum temperature:   	-206.51	degrees Celcius
   Escape Velocity:		6.90	km/sec
   Molecular weight retained:	16.67 and above
   Surface acceleration:	594.81	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.078
   Length of year:		97.52	days
   Length of day:		2340.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.508	AU
   Mass:			0.133	Earth masses
   Equatorial radius:		3294.6	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		152.62	degrees Celcius
   Maximum temperature:   	351.47	degrees Celcius
   Minimum temperature:   	-215.72	degrees Celcius
   Escape Velocity:		5.67	km/sec
   Molecular weight retained:	24.71 and above
   Surface acceleration:	487.46	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.086
   Length of year:		126.50	days
   Length of day:		3036.11	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.943	AU
   Mass:			0.209	Earth masses
   Equatorial radius:		3830.1	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		0.58	Earth gees
   Surface pressure:		3.690	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		97.78	degrees Celcius
   Normal daytime temperature:	101.92	degrees Celcius
   Normal night temperature:	93.12	degrees Celcius
   Maximum temperature:   	116.92	degrees Celcius
   Minimum temperature:   	77.45	degrees Celcius
   Escape Velocity:		6.60	km/sec
   Molecular weight retained:	18.23 and above
   Surface acceleration:	568.54	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.038
   Length of year:		320.09	days
   Length of day:		22.91	hours
   Boiling point of water:	139.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 424
				Water        melts at 0     boils at 140
				Francium     melts at 27    boils at 778
				Cesium       melts at 28    boils at 809
				Gallium      melts at 30    boils at 2688
				Rubidium     melts at 39    boils at 790
				Phosphorus   melts at 44    boils at 340
				Potassium    melts at 63    boils at 876
   gasses in atmosphere:
				CarbonDioxide    31.5%  PP 1160.4 mb
				Ozone            33.5%  PP 1236.2 mb
				Ethanol          32.6%  PP 1202.1 mb
				Neon              0.2%  PP    5.9 mb
				Krypton           2.0%  PP   74.4 mb
				Xenon             0.2%  PP    8.9 mb


Planet 5	
   Distance from primary:	1.183	AU
   Mass:			0.339	Earth masses
   Equatorial radius:		4492.1	km
   Density:			5.336	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.68	Earth gees
   Surface pressure:		0.120	Earth atmospheres
   Surface temperature:		12.61	degrees Celcius
   Normal daytime temperature:	25.71	degrees Celcius
   Normal night temperature:	-1.07	degrees Celcius
   Maximum temperature:   	52.16	degrees Celcius
   Minimum temperature:   	-28.69	degrees Celcius
   Escape Velocity:		7.76	km/sec
   Molecular weight retained:	13.19 and above
   Surface acceleration:	669.94	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.242
   Length of year:		449.42	days
   Length of day:		18.92	hours
   Boiling point of water:	49.4	degrees Celcius
   Hydrosphere percentage:	50.56
   Cloud cover percentage:	31.40
   Ice cover percentage:	2.16
   liquids at surface:
				Ethanol      melts at -114  boils at 31
				Mercury      melts at -39   boils at 272
				Bromine      melts at -7    boils at 15
				Water        melts at 0     boils at 50
   gasses in atmosphere:
				Oxygen           80.5%  PP   96.3 mb
				Nitrogen         19.2%  PP   23.0 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	1.428	AU
   Mass:			5.235	Earth masses
   Equatorial radius:		17374.5	km
   Density:			1.424	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		15.50	km/sec
   Molecular weight retained:	3.30 and above
   Surface acceleration:	691.59	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.528
   Length of year:		596.45	days
   Length of day:		15.55	hours


Planet 7	
   Distance from primary:	2.137	AU
   Mass:			0.050	Earth masses
   Equatorial radius:		2386.7	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.002	Earth atmospheres
   Surface temperature:		-79.31	degrees Celcius
   Normal daytime temperature:	-57.80	degrees Celcius
   Normal night temperature:	-100.90	degrees Celcius
   Maximum temperature:   	-31.06	degrees Celcius
   Minimum temperature:   	-128.35	degrees Celcius
   Escape Velocity:		4.10	km/sec
   Molecular weight retained:	47.30 and above
   Surface acceleration:	351.61	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.309
   Length of year:		1091.84	days
   Length of day:		25.63	hours
   Boiling point of water:	-16.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	31.82
   liquids at surface:
				Ethanol      melts at -114  boils at -27
   gasses in atmosphere:
				Ozone            38.3%  PP    0.8 mb
				Krypton          53.3%  PP    1.1 mb
				Xenon             8.4%  PP    0.2 mb


Planet 8	
   Distance from primary:	2.625	AU
   Mass:			0.873	Earth masses
   Equatorial radius:		6125.8	km
   Density:			5.417	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.830	Earth atmospheres
   Surface temperature:		-107.60	degrees Celcius
   Normal daytime temperature:	-104.80	degrees Celcius
   Normal night temperature:	-110.56	degrees Celcius
   Maximum temperature:   	-88.21	degrees Celcius
   Minimum temperature:   	-128.51	degrees Celcius
   Escape Velocity:		10.66	km/sec
   Molecular weight retained:	6.99 and above
   Surface acceleration:	927.34	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.671
   Length of year:		1486.83	days
   Length of day:		15.74	hours
   Boiling point of water:	94.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 74
   gasses in atmosphere:
				Oxygen           25.9%  PP  215.0 mb
				Nitrogen         74.0%  PP  614.4 mb


Planet 9	*gas giant*
   Distance from primary:	3.746	AU
   Mass:			503.259	Earth masses
   Equatorial radius:		71309.1	km
   Density:			1.980	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		75.03	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3946.76	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.496
   Length of year:		2532.05	days
   Length of day:		6.51	hours


Planet 10	
   Distance from primary:	5.759	AU
   Mass:			0.905	Earth masses
   Equatorial radius:		8256.3	km
   Density:			2.295	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.621	Earth atmospheres
   Surface temperature:		-144.26	degrees Celcius
   Normal daytime temperature:	-141.06	degrees Celcius
   Normal night temperature:	-147.70	degrees Celcius
   Maximum temperature:   	-123.78	degrees Celcius
   Minimum temperature:   	-166.59	degrees Celcius
   Escape Velocity:		9.35	km/sec
   Molecular weight retained:	9.08 and above
   Surface acceleration:	529.58	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.399
   Length of year:		4830.20	days
   Length of day:		20.83	hours
   Boiling point of water:	87.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	43.66
   liquids at surface:
				Ozone        melts at -193  boils at -117
   gasses in atmosphere:
				Oxygen           37.1%  PP  230.6 mb
				Nitrogen         62.9%  PP  390.6 mb


Planet 11	*gas giant*
   Distance from primary:	12.249	AU
   Mass:			679.666	Earth masses
   Equatorial radius:		85918.5	km
   Density:			1.529	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		79.43	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3671.65	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.512
   Length of year:		14968.32	days
   Length of day:		6.75	hours


Planet 12	
   Distance from primary:	20.331	AU
   Mass:			0.026	Earth masses
   Equatorial radius:		2566.3	km
   Density:			2.196	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-207.03	degrees Celcius
   Normal daytime temperature:	-196.46	degrees Celcius
   Normal night temperature:	-217.55	degrees Celcius
   Maximum temperature:   	-179.13	degrees Celcius
   Minimum temperature:   	-235.30	degrees Celcius
   Escape Velocity:		2.84	km/sec
   Molecular weight retained:	98.20 and above
   Surface acceleration:	157.50	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.156
   Length of year:		32039.13	days
   Length of day:		38.19	hours
   Boiling point of water:	-86.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


Planet 13	*gas giant*
   Distance from primary:	26.668	AU
   Mass:			12.004	Earth masses
   Equatorial radius:		28246.1	km
   Density:			0.760	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		18.41	km/sec
   Molecular weight retained:	2.34 and above
   Surface acceleration:	599.97	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.486
   Length of year:		48131.45	days
   Length of day:		16.69	hours


Planet 14	*gas giant*
   Distance from primary:	44.425	AU
   Mass:			0.739	Earth masses
   Equatorial radius:		13072.7	km
   Density:			0.472	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		6.72	km/sec
   Molecular weight retained:	17.60 and above
   Surface acceleration:	172.51	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.453
   Length of year:		103489.42	days
   Length of day:		31.12	hours


