                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488d6
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6346 K
Stellar class: F7
Age: 4.574 billion years  (2.190 billion left on main sequence)
Habitable ecosphere radius: 1.279 AU

Planets present at:
1	  0.380 AU	no atmosphere
2	  0.604 AU	no atmosphere
3	  0.777 AU	no atmosphere
4	  0.981 AU	greenhouse
5	  1.449 AU	high pressure
6	  1.978 AU	gas giant
7	  4.254 AU	gas giant
8	  6.466 AU	gas giant
9	  9.250 AU	cold
10	 12.150 AU	gas giant
11	 27.009 AU	gas giant
12	 38.240 AU	gas giant
13	 48.267 AU	no atmosphere



Planet 1	
   Distance from primary:	0.380	AU
   Mass:			0.195	Earth masses
   Equatorial radius:		3742.9	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		227.19	degrees Celcius
   Maximum temperature:   	442.55	degrees Celcius
   Minimum temperature:   	-197.87	degrees Celcius
   Escape Velocity:		6.45	km/sec
   Molecular weight retained:	19.10 and above
   Surface acceleration:	555.29	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.088
   Length of year:		81.18	days
   Length of day:		1948.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.604	AU
   Mass:			0.127	Earth masses
   Equatorial radius:		3248.2	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		123.99	degrees Celcius
   Maximum temperature:   	315.83	degrees Celcius
   Minimum temperature:   	-221.30	degrees Celcius
   Escape Velocity:		5.59	km/sec
   Molecular weight retained:	25.43 and above
   Surface acceleration:	480.49	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.084
   Length of year:		162.84	days
   Length of day:		3908.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.777	AU
   Mass:			0.058	Earth masses
   Equatorial radius:		2502.7	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		78.75	degrees Celcius
   Maximum temperature:   	259.30	degrees Celcius
   Minimum temperature:   	-227.73	degrees Celcius
   Escape Velocity:		4.30	km/sec
   Molecular weight retained:	43.00 and above
   Surface acceleration:	368.86	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.064
   Length of year:		237.91	days
   Length of day:		5709.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.981	AU
   Mass:			2.447	Earth masses
   Equatorial radius:		8549.1	km
   Density:			5.589	grams/cc
   Eccentricity of orbit:	0.137
   Surface gravity:		1.36	Earth gees
   Surface pressure:		628.213	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		626.46	degrees Celcius
   Maximum temperature:   	627.49	degrees Celcius
   Minimum temperature:   	621.57	degrees Celcius
   Escape Velocity:		15.11	km/sec
   Molecular weight retained:	3.48 and above
   Surface acceleration:	1335.36	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.515
   Length of year:		337.16	days
   Length of day:		13.58	hours
   Boiling point of water:	438.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1539
				Cesium       melts at 28    boils at 1593
				Gallium      melts at 30    boils at 4832
				Rubidium     melts at 39    boils at 1560
				Potassium    melts at 63    boils at 1708
				Sodium       melts at 98    boils at 1930
				Indium       melts at 157   boils at 4216
				Lithium      melts at 181   boils at 2817
				Selenium     melts at 217   boils at 1555
				Tin          melts at 232   boils at 5252
				Polonium     melts at 254   boils at 2083
				Bismuth      melts at 271   boils at 3231
				Thallium     melts at 304   boils at 3027
				Cadmium      melts at 321   boils at 1707
				Lead         melts at 328   boils at 3588
				Zinc         melts at 420   boils at 1978
				Tellurium    melts at 450   boils at 2136
   gasses in atmosphere:
				Sulfur            0.2%  PP 1389.7 mb
				Nitrogen          1.0%  PP 6056.1 mb
				Helium           98.8%  PP 620727.8 mb


Planet 5	
   Distance from primary:	1.449	AU
   Mass:			1.881	Earth masses
   Equatorial radius:		7857.1	km
   Density:			5.533	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		1.24	Earth gees
   Surface pressure:		3.620	Earth atmospheres
   Surface temperature:		11.35	degrees Celcius
   Normal daytime temperature:	13.43	degrees Celcius
   Normal night temperature:	9.14	degrees Celcius
   Maximum temperature:   	27.19	degrees Celcius
   Minimum temperature:   	-5.34	degrees Celcius
   Escape Velocity:		13.82	km/sec
   Molecular weight retained:	4.16 and above
   Surface acceleration:	1214.93	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.337
   Length of year:		605.75	days
   Length of day:		13.81	hours
   Boiling point of water:	139.2	degrees Celcius
   Hydrosphere percentage:	90.12
   Cloud cover percentage:	50.11
   Ice cover percentage:	2.60
   liquids at surface:
				Ethanol      melts at -114  boils at 115
				Mercury      melts at -39   boils at 423
				Bromine      melts at -7    boils at 94
				Water        melts at 0     boils at 139
   gasses in atmosphere:
				Oxygen            0.5%  PP   18.0 mb
				Nitrogen         99.3%  PP 3596.2 mb


Planet 6	*gas giant*
   Distance from primary:	1.978	AU
   Mass:			2.570	Earth masses
   Equatorial radius:		14467.8	km
   Density:			1.211	grams/cc
   Eccentricity of orbit:	0.093
   Escape Velocity:		11.90	km/sec
   Molecular weight retained:	5.60 and above
   Surface acceleration:	489.58	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.517
   Length of year:		966.01	days
   Length of day:		18.48	hours


Planet 7	*gas giant*
   Distance from primary:	4.254	AU
   Mass:			15.633	Earth masses
   Equatorial radius:		26110.9	km
   Density:			1.253	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		21.85	km/sec
   Molecular weight retained:	1.66 and above
   Surface acceleration:	914.39	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.516
   Length of year:		3046.26	days
   Length of day:		13.52	hours


Planet 8	*gas giant*
   Distance from primary:	6.466	AU
   Mass:			125.617	Earth masses
   Equatorial radius:		49651.7	km
   Density:			1.464	grams/cc
   Eccentricity of orbit:	0.091
   Escape Velocity:		44.92	km/sec
   Molecular weight retained:	0.39 and above
   Surface acceleration:	2031.99	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.468
   Length of year:		5706.90	days
   Length of day:		9.07	hours


Planet 9	
   Distance from primary:	9.250	AU
   Mass:			0.605	Earth masses
   Equatorial radius:		7245.1	km
   Density:			2.269	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.199	Earth atmospheres
   Surface temperature:		-171.02	degrees Celcius
   Normal daytime temperature:	-166.54	degrees Celcius
   Normal night temperature:	-175.74	degrees Celcius
   Maximum temperature:   	-148.83	degrees Celcius
   Minimum temperature:   	-195.21	degrees Celcius
   Escape Velocity:		8.16	km/sec
   Molecular weight retained:	11.92 and above
   Surface acceleration:	459.44	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.319
   Length of year:		9767.34	days
   Length of day:		22.36	hours
   Boiling point of water:	60.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	27.18
   liquids at surface:
				Ozone        melts at -193  boils at -129
   gasses in atmosphere:
				Oxygen            8.6%  PP   17.2 mb
				Nitrogen         91.3%  PP  181.8 mb


Planet 10	*gas giant*
   Distance from primary:	12.150	AU
   Mass:			374.834	Earth masses
   Equatorial radius:		71985.4	km
   Density:			1.434	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		64.44	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2884.63	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.504
   Length of year:		14695.91	days
   Length of day:		7.61	hours


Planet 11	*gas giant*
   Distance from primary:	27.009	AU
   Mass:			2.606	Earth masses
   Equatorial radius:		18062.3	km
   Density:			0.631	grams/cc
   Eccentricity of orbit:	0.213
   Escape Velocity:		10.73	km/sec
   Molecular weight retained:	6.90 and above
   Surface acceleration:	318.53	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.483
   Length of year:		48730.28	days
   Length of day:		22.90	hours


Planet 12	*gas giant*
   Distance from primary:	38.240	AU
   Mass:			3.778	Earth masses
   Equatorial radius:		20720.6	km
   Density:			0.606	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		12.06	km/sec
   Molecular weight retained:	5.46 and above
   Surface acceleration:	350.91	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.495
   Length of year:		82092.05	days
   Length of day:		21.82	hours


Planet 13	
   Distance from primary:	48.267	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		3442.8	km
   Density:			2.204	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.55	degrees Celcius
   Normal daytime temperature:	-223.42	degrees Celcius
   Normal night temperature:	-235.58	degrees Celcius
   Maximum temperature:   	-210.68	degrees Celcius
   Minimum temperature:   	-248.59	degrees Celcius
   Escape Velocity:		3.82	km/sec
   Molecular weight retained:	54.36 and above
   Surface acceleration:	212.07	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.161
   Length of year:		116413.92	days
   Length of day:		32.91	hours
   Boiling point of water:	-72.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


