                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047dfe
Stellar mass: 1.09 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6304 K
Stellar class: F7
Age: 1.195 billion years  (5.935 billion left on main sequence)
Habitable ecosphere radius: 1.237 AU

Planets present at:
1	  0.381 AU	no atmosphere
2	  0.553 AU	no atmosphere
3	  1.068 AU	greenhouse
4	  1.650 AU	gas giant
5	  2.752 AU	cold
6	  4.402 AU	gas giant
7	  9.356 AU	gas giant
8	 17.360 AU	gas giant
9	 28.837 AU	gas giant
10	 48.533 AU	no atmosphere



Planet 1	
   Distance from primary:	0.381	AU
   Mass:			0.074	Earth masses
   Equatorial radius:		2716.1	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		219.31	degrees Celcius
   Maximum temperature:   	433.05	degrees Celcius
   Minimum temperature:   	-199.73	degrees Celcius
   Escape Velocity:		4.67	km/sec
   Molecular weight retained:	36.47 and above
   Surface acceleration:	400.69	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.080
   Length of year:		82.10	days
   Length of day:		1970.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.553	AU
   Mass:			0.637	Earth masses
   Equatorial radius:		5526.8	km
   Density:			5.384	grams/cc
   Eccentricity of orbit:	0.099
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		138.14	degrees Celcius
   Normal daytime temperature:	252.74	degrees Celcius
   Normal night temperature:	9.97	degrees Celcius
   Maximum temperature:   	278.84	degrees Celcius
   Minimum temperature:   	-22.88	degrees Celcius
   Escape Velocity:		9.59	km/sec
   Molecular weight retained:	8.64 and above
   Surface acceleration:	831.63	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.054
   Length of year:		143.87	days
   Length of day:		90.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.068	AU
   Mass:			1.038	Earth masses
   Equatorial radius:		6482.6	km
   Density:			5.438	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		1.00	Earth gees
   Surface pressure:		114.454	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		365.44	degrees Celcius
   Maximum temperature:   	369.61	degrees Celcius
   Minimum temperature:   	359.96	degrees Celcius
   Escape Velocity:		11.30	km/sec
   Molecular weight retained:	6.21 and above
   Surface acceleration:	985.19	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.522
   Length of year:		385.72	days
   Length of day:		15.43	hours
   Boiling point of water:	300.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1189
				Cesium       melts at 28    boils at 1232
				Gallium      melts at 30    boils at 3844
				Rubidium     melts at 39    boils at 1205
				Potassium    melts at 63    boils at 1325
				Sodium       melts at 98    boils at 1503
				Sulfur       melts at 113   boils at 831
				Indium       melts at 157   boils at 3347
				Lithium      melts at 181   boils at 2219
				Selenium     melts at 217   boils at 1201
				Tin          melts at 232   boils at 4183
				Polonium     melts at 254   boils at 1627
				Bismuth      melts at 271   boils at 2553
				Thallium     melts at 304   boils at 2389
				Cadmium      melts at 321   boils at 1324
				Lead         melts at 328   boils at 2841
   gasses in atmosphere:
				Nitrogen         99.2%  PP 113580.5 mb
				Phosphorus        0.5%  PP  568.7 mb
				CarbonDioxide     0.1%  PP   59.7 mb
				Ethanol           0.1%  PP   60.3 mb


Planet 4	*gas giant*
   Distance from primary:	1.650	AU
   Mass:			11.896	Earth masses
   Equatorial radius:		22343.5	km
   Density:			1.522	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		20.61	km/sec
   Molecular weight retained:	1.87 and above
   Surface acceleration:	950.25	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.456
   Length of year:		741.18	days
   Length of day:		13.26	hours


Planet 5	
   Distance from primary:	2.752	AU
   Mass:			0.440	Earth masses
   Equatorial radius:		4895.4	km
   Density:			5.354	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.203	Earth atmospheres
   Surface temperature:		-110.06	degrees Celcius
   Normal daytime temperature:	-104.29	degrees Celcius
   Normal night temperature:	-116.09	degrees Celcius
   Maximum temperature:   	-81.81	degrees Celcius
   Minimum temperature:   	-140.30	degrees Celcius
   Escape Velocity:		8.47	km/sec
   Molecular weight retained:	11.07 and above
   Surface acceleration:	732.47	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.581
   Length of year:		1595.76	days
   Length of day:		17.71	hours
   Boiling point of water:	60.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	83.43
   liquids at surface:
				Ethanol      melts at -114  boils at 42
   gasses in atmosphere:
				Oxygen           75.5%  PP  153.2 mb
				Nitrogen         24.5%  PP   49.7 mb


Planet 6	*gas giant*
   Distance from primary:	4.402	AU
   Mass:			51.276	Earth masses
   Equatorial radius:		37129.4	km
   Density:			1.429	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		33.19	km/sec
   Molecular weight retained:	0.72 and above
   Surface acceleration:	1483.25	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.451
   Length of year:		3227.92	days
   Length of day:		10.61	hours


Planet 7	*gas giant*
   Distance from primary:	9.356	AU
   Mass:			1617.583	Earth masses
   Equatorial radius:		108193.7	km
   Density:			1.822	grams/cc
   Eccentricity of orbit:	0.159
   Escape Velocity:		109.20	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5510.64	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.493
   Length of year:		9981.18	days
   Length of day:		5.51	hours


Planet 8	*gas giant*
   Distance from primary:	17.360	AU
   Mass:			0.437	Earth masses
   Equatorial radius:		10371.0	km
   Density:			0.559	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		5.80	km/sec
   Molecular weight retained:	23.62 and above
   Surface acceleration:	162.06	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.549
   Length of year:		25284.85	days
   Length of day:		32.11	hours


Planet 9	*gas giant*
   Distance from primary:	28.837	AU
   Mass:			40.387	Earth masses
   Equatorial radius:		40505.1	km
   Density:			0.867	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		28.20	km/sec
   Molecular weight retained:	1.00 and above
   Surface acceleration:	981.66	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.546
   Length of year:		54130.64	days
   Length of day:		13.04	hours


Planet 10	
   Distance from primary:	48.533	AU
   Mass:			0.229	Earth masses
   Equatorial radius:		5269.5	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.127
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.06	degrees Celcius
   Normal daytime temperature:	-225.05	degrees Celcius
   Normal night temperature:	-234.98	degrees Celcius
   Maximum temperature:   	-209.27	degrees Celcius
   Minimum temperature:   	-250.87	degrees Celcius
   Escape Velocity:		5.88	km/sec
   Molecular weight retained:	22.95 and above
   Surface acceleration:	328.27	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.157
   Length of year:		118191.29	days
   Length of day:		26.45	hours
   Boiling point of water:	-50.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


