                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b8f
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6267 K
Stellar class: F8
Age: 2.446 billion years  (4.768 billion left on main sequence)
Habitable ecosphere radius: 1.228 AU

Planets present at:
1	  0.366 AU	no atmosphere
2	  0.551 AU	no atmosphere
3	  0.708 AU	greenhouse
4	  1.130 AU	greenhouse
5	  1.556 AU	gas giant
6	  2.320 AU	cold
7	  4.631 AU	gas giant
8	  7.418 AU	gas giant
9	 12.896 AU	no atmosphere
10	 16.495 AU	gas giant
11	 22.530 AU	gas giant
12	 36.442 AU	gas giant
13	 51.341 AU	no atmosphere



Planet 1	
   Distance from primary:	0.366	AU
   Mass:			0.106	Earth masses
   Equatorial radius:		3055.0	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.30	degrees Celcius
   Maximum temperature:   	447.53	degrees Celcius
   Minimum temperature:   	-196.43	degrees Celcius
   Escape Velocity:		5.25	km/sec
   Molecular weight retained:	28.78 and above
   Surface acceleration:	451.43	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.051
   Length of year:		77.42	days
   Length of day:		1858.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.551	AU
   Mass:			0.069	Earth masses
   Equatorial radius:		2648.1	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		136.26	degrees Celcius
   Maximum temperature:   	331.19	degrees Celcius
   Minimum temperature:   	-219.03	degrees Celcius
   Escape Velocity:		4.55	km/sec
   Molecular weight retained:	38.38 and above
   Surface acceleration:	390.54	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.067
   Length of year:		143.02	days
   Length of day:		3432.44	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.708	AU
   Mass:			1.124	Earth masses
   Equatorial radius:		6651.3	km
   Density:			5.448	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		1.03	Earth gees
   Surface pressure:		121.028	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		471.20	degrees Celcius
   Maximum temperature:   	475.18	degrees Celcius
   Minimum temperature:   	464.87	degrees Celcius
   Escape Velocity:		11.61	km/sec
   Molecular weight retained:	5.89 and above
   Surface acceleration:	1012.79	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.620
   Length of year:		208.47	days
   Length of day:		19.75	hours
   Boiling point of water:	304.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1198
				Cesium       melts at 28    boils at 1241
				Gallium      melts at 30    boils at 3871
				Rubidium     melts at 39    boils at 1215
				Potassium    melts at 63    boils at 1335
				Sodium       melts at 98    boils at 1515
				Indium       melts at 157   boils at 3370
				Lithium      melts at 181   boils at 2235
				Selenium     melts at 217   boils at 1210
				Tin          melts at 232   boils at 4211
				Polonium     melts at 254   boils at 1639
				Bismuth      melts at 271   boils at 2571
				Thallium     melts at 304   boils at 2406
				Cadmium      melts at 321   boils at 1334
				Lead         melts at 328   boils at 2861
				Zinc         melts at 420   boils at 1554
				Tellurium    melts at 450   boils at 1683
   gasses in atmosphere:
				Sulfur           21.0%  PP 25387.7 mb
				Nitrogen         78.4%  PP 94870.4 mb
				Phosphorus        0.4%  PP  505.8 mb


Planet 4	
   Distance from primary:	1.130	AU
   Mass:			0.382	Earth masses
   Equatorial radius:		4671.6	km
   Density:			5.344	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.71	Earth gees
   Surface pressure:		12.532	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		47.69	degrees Celcius
   Maximum temperature:   	57.09	degrees Celcius
   Minimum temperature:   	37.81	degrees Celcius
   Escape Velocity:		8.07	km/sec
   Molecular weight retained:	12.18 and above
   Surface acceleration:	697.69	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.579
   Length of year:		420.42	days
   Length of day:		18.80	hours
   Boiling point of water:	185.6	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 159
				Mercury      melts at -39   boils at 501
				Bromine      melts at -7    boils at 136
				Water        melts at 0     boils at 186
				Francium     melts at 27    boils at 895
				Cesium       melts at 28    boils at 929
				Gallium      melts at 30    boils at 3017
				Rubidium     melts at 39    boils at 908
				Phosphorus   melts at 44    boils at 408
   gasses in atmosphere:
				Nitrogen         99.4%  PP 12460.2 mb
				CarbonDioxide     0.2%  PP   26.1 mb
				Methane           0.1%  PP    7.5 mb
				Ammonia           0.1%  PP    8.8 mb
				Ozone             0.2%  PP   26.8 mb


Planet 5	*gas giant*
   Distance from primary:	1.556	AU
   Mass:			4.484	Earth masses
   Equatorial radius:		16737.9	km
   Density:			1.365	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		14.62	km/sec
   Molecular weight retained:	3.71 and above
   Surface acceleration:	638.32	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.462
   Length of year:		679.25	days
   Length of day:		16.18	hours


Planet 6	
   Distance from primary:	2.320	AU
   Mass:			0.986	Earth masses
   Equatorial radius:		6373.8	km
   Density:			5.431	grams/cc
   Eccentricity of orbit:	0.144
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.865	Earth atmospheres
   Surface temperature:		-89.23	degrees Celcius
   Normal daytime temperature:	-86.23	degrees Celcius
   Normal night temperature:	-92.39	degrees Celcius
   Maximum temperature:   	-66.61	degrees Celcius
   Minimum temperature:   	-113.52	degrees Celcius
   Escape Velocity:		11.11	km/sec
   Molecular weight retained:	6.44 and above
   Surface acceleration:	967.48	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.604
   Length of year:		1236.88	days
   Length of day:		15.41	hours
   Boiling point of water:	96.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	93.66
   liquids at surface:
				Ethanol      melts at -114  boils at 75
				Chlorine     melts at -101  boils at -36
   gasses in atmosphere:
				Oxygen            7.9%  PP   68.5 mb
				Nitrogen         92.0%  PP  795.8 mb
				Ozone             0.1%  PP    0.4 mb


Planet 7	*gas giant*
   Distance from primary:	4.631	AU
   Mass:			1322.670	Earth masses
   Equatorial radius:		96278.8	km
   Density:			2.115	grams/cc
   Eccentricity of orbit:	0.147
   Escape Velocity:		104.68	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5690.23	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.491
   Length of year:		3483.16	days
   Length of day:		5.42	hours


Planet 8	*gas giant*
   Distance from primary:	7.418	AU
   Mass:			183.583	Earth masses
   Equatorial radius:		56291.1	km
   Density:			1.469	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		51.00	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2310.42	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.476
   Length of year:		7071.67	days
   Length of day:		8.50	hours


Planet 9	
   Distance from primary:	12.896	AU
   Mass:			0.145	Earth masses
   Equatorial radius:		4532.8	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.017	Earth atmospheres
   Surface temperature:		-193.01	degrees Celcius
   Normal daytime temperature:	-184.43	degrees Celcius
   Normal night temperature:	-201.73	degrees Celcius
   Maximum temperature:   	-168.23	degrees Celcius
   Minimum temperature:   	-219.05	degrees Celcius
   Escape Velocity:		5.05	km/sec
   Molecular weight retained:	31.17 and above
   Surface acceleration:	280.93	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.265
   Length of year:		16214.69	days
   Length of day:		28.59	hours
   Boiling point of water:	13.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.55


Planet 10	*gas giant*
   Distance from primary:	16.495	AU
   Mass:			1.563	Earth masses
   Equatorial radius:		14984.8	km
   Density:			0.663	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		9.12	km/sec
   Molecular weight retained:	9.54 and above
   Surface acceleration:	277.59	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.451
   Length of year:		23455.34	days
   Length of day:		24.53	hours


Planet 11	*gas giant*
   Distance from primary:	22.530	AU
   Mass:			118.842	Earth masses
   Equatorial radius:		54395.3	km
   Density:			1.054	grams/cc
   Eccentricity of orbit:	0.074
   Escape Velocity:		41.74	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1601.72	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.464
   Length of year:		37434.57	days
   Length of day:		10.21	hours


Planet 12	*gas giant*
   Distance from primary:	36.442	AU
   Mass:			0.760	Earth masses
   Equatorial radius:		12970.9	km
   Density:			0.497	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		6.84	km/sec
   Molecular weight retained:	16.99 and above
   Surface acceleration:	180.09	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.544
   Length of year:		77022.32	days
   Length of day:		30.46	hours


Planet 13	
   Distance from primary:	51.341	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		3570.1	km
   Density:			2.205	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.71	degrees Celcius
   Normal daytime temperature:	-225.97	degrees Celcius
   Normal night temperature:	-237.33	degrees Celcius
   Maximum temperature:   	-211.88	degrees Celcius
   Minimum temperature:   	-251.43	degrees Celcius
   Escape Velocity:		3.96	km/sec
   Molecular weight retained:	50.52 and above
   Surface acceleration:	220.05	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.160
   Length of year:		128799.27	days
   Length of day:		32.31	hours
   Boiling point of water:	-72.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


