                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950484d4
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6301 K
Stellar class: F7
Age: 4.380 billion years  (2.516 billion left on main sequence)
Habitable ecosphere radius: 1.264 AU

Planets present at:
1	  0.382 AU	no atmosphere
2	  0.503 AU	no atmosphere
3	  0.946 AU	greenhouse
4	  1.267 AU	
5	  1.874 AU	no atmosphere
6	  3.129 AU	gas giant
7	  7.638 AU	gas giant
8	 16.901 AU	gas giant
9	 25.259 AU	gas giant
10	 46.862 AU	gas giant



Planet 1	
   Distance from primary:	0.382	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		1859.4	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		226.89	degrees Celcius
   Maximum temperature:   	442.23	degrees Celcius
   Minimum temperature:   	-198.28	degrees Celcius
   Escape Velocity:		3.19	km/sec
   Molecular weight retained:	78.08 and above
   Surface acceleration:	273.40	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.054
   Length of year:		82.25	days
   Length of day:		1974.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.503	AU
   Mass:			0.594	Earth masses
   Equatorial radius:		5402.0	km
   Density:			5.378	grams/cc
   Eccentricity of orbit:	0.135
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		161.12	degrees Celcius
   Normal daytime temperature:	358.48	degrees Celcius
   Normal night temperature:	-201.38	degrees Celcius
   Maximum temperature:   	361.88	degrees Celcius
   Minimum temperature:   	-211.51	degrees Celcius
   Escape Velocity:		9.37	km/sec
   Molecular weight retained:	9.05 and above
   Surface acceleration:	811.89	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.070
   Length of year:		124.04	days
   Length of day:		2267.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.946	AU
   Mass:			1.638	Earth masses
   Equatorial radius:		7514.7	km
   Density:			5.507	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		1.18	Earth gees
   Surface pressure:		287.506	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		541.87	degrees Celcius
   Maximum temperature:   	544.12	degrees Celcius
   Minimum temperature:   	536.74	degrees Celcius
   Escape Velocity:		13.18	km/sec
   Molecular weight retained:	4.57 and above
   Surface acceleration:	1156.59	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.469
   Length of year:		320.27	days
   Length of day:		14.93	hours
   Boiling point of water:	368.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1359
				Cesium       melts at 28    boils at 1408
				Gallium      melts at 30    boils at 4326
				Rubidium     melts at 39    boils at 1378
				Potassium    melts at 63    boils at 1512
				Sodium       melts at 98    boils at 1711
				Indium       melts at 157   boils at 3771
				Lithium      melts at 181   boils at 2511
				Selenium     melts at 217   boils at 1373
				Tin          melts at 232   boils at 4704
				Polonium     melts at 254   boils at 1849
				Bismuth      melts at 271   boils at 2884
				Thallium     melts at 304   boils at 2700
				Cadmium      melts at 321   boils at 1511
				Lead         melts at 328   boils at 3205
				Zinc         melts at 420   boils at 1755
				Tellurium    melts at 450   boils at 1897
   gasses in atmosphere:
				Sulfur           19.9%  PP 57307.6 mb
				Nitrogen         79.5%  PP 228521.2 mb
				Phosphorus        0.4%  PP 1142.8 mb


Planet 4	
   Distance from primary:	1.267	AU
   Mass:			1.086	Earth masses
   Equatorial radius:		6578.1	km
   Density:			5.444	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		1.02	Earth gees
   Surface pressure:		0.923	Earth atmospheres
   Surface temperature:		17.63	degrees Celcius
   Normal daytime temperature:	22.19	degrees Celcius
   Normal night temperature:	12.79	degrees Celcius
   Maximum temperature:   	43.14	degrees Celcius
   Minimum temperature:   	-9.35	degrees Celcius
   Escape Velocity:		11.47	km/sec
   Molecular weight retained:	6.03 and above
   Surface acceleration:	1000.80	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.308
   Length of year:		496.51	days
   Length of day:		15.36	hours
   Boiling point of water:	97.8	degrees Celcius
   Hydrosphere percentage:	56.77
   Cloud cover percentage:	51.20
   Ice cover percentage:	1.09
   liquids at surface:
				Ethanol      melts at -114  boils at 76
				Mercury      melts at -39   boils at 353
				Bromine      melts at -7    boils at 58
				Water        melts at 0     boils at 98
   gasses in atmosphere:
				Oxygen           22.4%  PP  206.8 mb
				Nitrogen         77.4%  PP  714.7 mb


Planet 5	
   Distance from primary:	1.874	AU
   Mass:			0.087	Earth masses
   Equatorial radius:		2869.5	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.088
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.008	Earth atmospheres
   Surface temperature:		-74.48	degrees Celcius
   Normal daytime temperature:	-55.18	degrees Celcius
   Normal night temperature:	-93.94	degrees Celcius
   Maximum temperature:   	-30.45	degrees Celcius
   Minimum temperature:   	-119.43	degrees Celcius
   Escape Velocity:		4.93	km/sec
   Molecular weight retained:	32.65 and above
   Surface acceleration:	423.63	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.442
   Length of year:		893.08	days
   Length of day:		23.53	hours
   Boiling point of water:	2.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	48.68
   liquids at surface:
				Ethanol      melts at -114  boils at -12
   gasses in atmosphere:
				CarbonDioxide    41.7%  PP    3.4 mb
				Ozone            52.5%  PP    4.2 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           5.0%  PP    0.4 mb
				Xenon             0.7%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	3.129	AU
   Mass:			589.259	Earth masses
   Equatorial radius:		73432.6	km
   Density:			2.123	grams/cc
   Eccentricity of orbit:	0.135
   Escape Velocity:		80.00	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4357.80	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.524
   Length of year:		1924.78	days
   Length of day:		6.19	hours


Planet 7	*gas giant*
   Distance from primary:	7.638	AU
   Mass:			1022.820	Earth masses
   Equatorial radius:		92905.4	km
   Density:			1.820	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		93.71	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4725.59	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.464
   Length of year:		7337.02	days
   Length of day:		5.95	hours


Planet 8	*gas giant*
   Distance from primary:	16.901	AU
   Mass:			1.498	Earth masses
   Equatorial radius:		14794.2	km
   Density:			0.660	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		8.99	km/sec
   Molecular weight retained:	9.83 and above
   Surface acceleration:	272.89	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.527
   Length of year:		24181.61	days
   Length of day:		24.74	hours


Planet 9	*gas giant*
   Distance from primary:	25.259	AU
   Mass:			43.378	Earth masses
   Equatorial radius:		40832.3	km
   Density:			0.909	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		29.11	km/sec
   Molecular weight retained:	0.94 and above
   Surface acceleration:	1037.53	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.479
   Length of year:		44179.75	days
   Length of day:		12.69	hours


Planet 10	*gas giant*
   Distance from primary:	46.862	AU
   Mass:			0.413	Earth masses
   Equatorial radius:		11065.2	km
   Density:			0.435	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		5.46	km/sec
   Molecular weight retained:	26.64 and above
   Surface acceleration:	134.66	cm/sec2
   Axial tilt:			69	degrees
   Planetary albedo:		0.531
   Length of year:		111650.63	days
   Length of day:		35.22	hours


