                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504809c
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6285 K
Stellar class: F8
Age: 2.530 billion years  (4.509 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.337 AU	no atmosphere
2	  0.428 AU	no atmosphere
3	  0.976 AU	greenhouse
4	  1.711 AU	cold
5	  2.361 AU	gas giant
6	  4.052 AU	gas giant
7	  7.712 AU	gas giant
8	 11.519 AU	gas giant
9	 22.460 AU	gas giant
10	 47.270 AU	no atmosphere
11	 44.712 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.337	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1618.5	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.205
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		256.35	degrees Celcius
   Normal daytime temperature:	472.93	degrees Celcius
   Normal night temperature:	-163.13	degrees Celcius
   Maximum temperature:   	477.11	degrees Celcius
   Minimum temperature:   	-178.42	degrees Celcius
   Escape Velocity:		2.77	km/sec
   Molecular weight retained:	103.12 and above
   Surface acceleration:	237.81	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.052
   Length of year:		68.23	days
   Length of day:		1080.88	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.428	AU
   Mass:			0.602	Earth masses
   Equatorial radius:		5426.4	km
   Density:			5.379	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		195.52	degrees Celcius
   Normal daytime temperature:	400.57	degrees Celcius
   Normal night temperature:	-192.15	degrees Celcius
   Maximum temperature:   	403.84	degrees Celcius
   Minimum temperature:   	-202.50	degrees Celcius
   Escape Velocity:		9.41	km/sec
   Molecular weight retained:	8.97 and above
   Surface acceleration:	815.75	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.061
   Length of year:		97.73	days
   Length of day:		1869.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.976	AU
   Mass:			1.463	Earth masses
   Equatorial radius:		7245.1	km
   Density:			5.488	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		1.13	Earth gees
   Surface pressure:		163.925	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		437.72	degrees Celcius
   Maximum temperature:   	441.00	degrees Celcius
   Minimum temperature:   	432.59	degrees Celcius
   Escape Velocity:		12.69	km/sec
   Molecular weight retained:	4.93 and above
   Surface acceleration:	1111.21	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.517
   Length of year:		336.52	days
   Length of day:		14.81	hours
   Boiling point of water:	325.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1251
				Cesium       melts at 28    boils at 1296
				Gallium      melts at 30    boils at 4020
				Rubidium     melts at 39    boils at 1268
				Potassium    melts at 63    boils at 1393
				Sodium       melts at 98    boils at 1579
				Sulfur       melts at 113   boils at 878
				Indium       melts at 157   boils at 3501
				Lithium      melts at 181   boils at 2326
				Selenium     melts at 217   boils at 1264
				Tin          melts at 232   boils at 4372
				Polonium     melts at 254   boils at 1708
				Bismuth      melts at 271   boils at 2674
				Thallium     melts at 304   boils at 2502
				Cadmium      melts at 321   boils at 1392
				Lead         melts at 328   boils at 2974
				Zinc         melts at 420   boils at 1620
   gasses in atmosphere:
				Nitrogen         99.3%  PP 162746.9 mb
				Phosphorus        0.5%  PP  775.4 mb
				Ethanol           0.1%  PP   82.3 mb


Planet 4	
   Distance from primary:	1.711	AU
   Mass:			0.704	Earth masses
   Equatorial radius:		5710.7	km
   Density:			5.394	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.507	Earth atmospheres
   Surface temperature:		-71.31	degrees Celcius
   Normal daytime temperature:	-66.86	degrees Celcius
   Normal night temperature:	-76.01	degrees Celcius
   Maximum temperature:   	-46.92	degrees Celcius
   Minimum temperature:   	-97.36	degrees Celcius
   Escape Velocity:		9.92	km/sec
   Molecular weight retained:	8.07 and above
   Surface acceleration:	860.84	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.678
   Length of year:		780.74	days
   Length of day:		16.36	hours
   Boiling point of water:	82.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.11
   Ice cover percentage:	95.71
   liquids at surface:
				Ethanol      melts at -114  boils at 62
				Chlorine     melts at -101  boils at -45
				Ammonia      melts at -78   boils at -45
   gasses in atmosphere:
				Oxygen           18.8%  PP   95.3 mb
				Nitrogen         81.0%  PP  410.8 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ozone             0.1%  PP    0.3 mb


Planet 5	*gas giant*
   Distance from primary:	2.361	AU
   Mass:			9.124	Earth masses
   Equatorial radius:		21291.7	km
   Density:			1.349	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		18.49	km/sec
   Molecular weight retained:	2.32 and above
   Surface acceleration:	802.63	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.537
   Length of year:		1265.74	days
   Length of day:		14.43	hours


Planet 6	*gas giant*
   Distance from primary:	4.052	AU
   Mass:			485.048	Earth masses
   Equatorial radius:		70968.0	km
   Density:			1.936	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		73.83	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3840.60	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.505
   Length of year:		2844.79	days
   Length of day:		6.60	hours


Planet 7	*gas giant*
   Distance from primary:	7.712	AU
   Mass:			1.951	Earth masses
   Equatorial radius:		14984.1	km
   Density:			0.827	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		10.19	km/sec
   Molecular weight retained:	7.65 and above
   Surface acceleration:	346.45	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.487
   Length of year:		7474.02	days
   Length of day:		21.96	hours


Planet 8	*gas giant*
   Distance from primary:	11.519	AU
   Mass:			311.855	Earth masses
   Equatorial radius:		68064.5	km
   Density:			1.411	grams/cc
   Eccentricity of orbit:	0.104
   Escape Velocity:		60.45	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2684.42	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.462
   Length of year:		13637.14	days
   Length of day:		7.89	hours


Planet 9	*gas giant*
   Distance from primary:	22.460	AU
   Mass:			117.946	Earth masses
   Equatorial radius:		54190.9	km
   Density:			1.058	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		41.66	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1601.66	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.482
   Length of year:		37139.65	days
   Length of day:		10.21	hours


Planet 10	
   Distance from primary:	47.270	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		4572.3	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.295
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.38	degrees Celcius
   Normal daytime temperature:	-223.94	degrees Celcius
   Normal night temperature:	-234.71	degrees Celcius
   Maximum temperature:   	-204.74	degrees Celcius
   Minimum temperature:   	-253.26	degrees Celcius
   Escape Velocity:		5.09	km/sec
   Molecular weight retained:	30.63 and above
   Surface acceleration:	283.45	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.143
   Length of year:		113418.41	days
   Length of day:		28.47	hours
   Boiling point of water:	-56.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 11	*gas giant*
   Distance from primary:	44.712	AU
   Mass:			0.471	Earth masses
   Equatorial radius:		11463.8	km
   Density:			0.446	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		5.73	km/sec
   Molecular weight retained:	24.21 and above
   Surface acceleration:	143.03	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.480
   Length of year:		104337.70	days
   Length of day:		34.17	hours


