                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f0b
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6190 K
Stellar class: F8
Age: 4.823 billion years  (2.270 billion left on main sequence)
Habitable ecosphere radius: 1.241 AU

Planets present at:
1	  0.395 AU	no atmosphere
2	  0.595 AU	no atmosphere
3	  0.748 AU	no atmosphere
4	  1.177 AU	high pressure
5	  1.396 AU	
6	  2.056 AU	cold
7	  2.810 AU	gas giant
8	  6.978 AU	gas giant
9	 22.471 AU	gas giant
10	 44.947 AU	gas giant



Planet 1	
   Distance from primary:	0.395	AU
   Mass:			0.257	Earth masses
   Equatorial radius:		4101.0	km
   Density:			5.321	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		210.35	degrees Celcius
   Maximum temperature:   	422.24	degrees Celcius
   Minimum temperature:   	-202.40	degrees Celcius
   Escape Velocity:		7.07	km/sec
   Molecular weight retained:	15.87 and above
   Surface acceleration:	609.87	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.083
   Length of year:		86.89	days
   Length of day:		2085.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.595	AU
   Mass:			0.339	Earth masses
   Equatorial radius:		4490.4	km
   Density:			5.336	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.68	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		120.51	degrees Celcius
   Maximum temperature:   	311.62	degrees Celcius
   Minimum temperature:   	-222.07	degrees Celcius
   Escape Velocity:		7.76	km/sec
   Molecular weight retained:	13.20 and above
   Surface acceleration:	669.69	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.088
   Length of year:		160.32	days
   Length of day:		3847.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.748	AU
   Mass:			0.219	Earth masses
   Equatorial radius:		3886.7	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		80.75	degrees Celcius
   Maximum temperature:   	261.73	degrees Celcius
   Minimum temperature:   	-227.45	degrees Celcius
   Escape Velocity:		6.70	km/sec
   Molecular weight retained:	17.69 and above
   Surface acceleration:	577.16	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.060
   Length of year:		225.84	days
   Length of day:		5420.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.177	AU
   Mass:			1.928	Earth masses
   Equatorial radius:		7920.2	km
   Density:			5.538	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		1.25	Earth gees
   Surface pressure:		3.387	Earth atmospheres
   Surface temperature:		22.22	degrees Celcius
   Normal daytime temperature:	24.45	degrees Celcius
   Normal night temperature:	19.83	degrees Celcius
   Maximum temperature:   	38.06	degrees Celcius
   Minimum temperature:   	5.51	degrees Celcius
   Escape Velocity:		13.93	km/sec
   Molecular weight retained:	4.09 and above
   Surface acceleration:	1225.78	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.455
   Length of year:		445.99	days
   Length of day:		13.89	hours
   Boiling point of water:	136.9	degrees Celcius
   Hydrosphere percentage:	80.94
   Cloud cover percentage:	93.86
   Ice cover percentage:	0.65
   liquids at surface:
				Ethanol      melts at -114  boils at 113
				Mercury      melts at -39   boils at 419
				Bromine      melts at -7    boils at 93
				Water        melts at 0     boils at 137
   gasses in atmosphere:
				Oxygen            0.6%  PP   21.6 mb
				Nitrogen         99.2%  PP 3359.7 mb


Planet 5	
   Distance from primary:	1.396	AU
   Mass:			0.656	Earth masses
   Equatorial radius:		5580.9	km
   Density:			5.387	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.86	Earth gees
   Surface pressure:		0.451	Earth atmospheres
   Surface temperature:		6.37	degrees Celcius
   Normal daytime temperature:	13.00	degrees Celcius
   Normal night temperature:	-0.64	degrees Celcius
   Maximum temperature:   	36.13	degrees Celcius
   Minimum temperature:   	-25.06	degrees Celcius
   Escape Velocity:		9.68	km/sec
   Molecular weight retained:	8.46 and above
   Surface acceleration:	840.21	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.192
   Length of year:		576.28	days
   Length of day:		16.74	hours
   Boiling point of water:	79.3	degrees Celcius
   Hydrosphere percentage:	63.79
   Cloud cover percentage:	25.53
   Ice cover percentage:	4.36
   liquids at surface:
				Ethanol      melts at -114  boils at 59
				Mercury      melts at -39   boils at 322
				Bromine      melts at -7    boils at 41
				Water        melts at 0     boils at 79
   gasses in atmosphere:
				Oxygen           37.0%  PP  167.0 mb
				Nitrogen         62.8%  PP  283.4 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 6	
   Distance from primary:	2.056	AU
   Mass:			0.361	Earth masses
   Equatorial radius:		4585.0	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.141	Earth atmospheres
   Surface temperature:		-81.00	degrees Celcius
   Normal daytime temperature:	-72.91	degrees Celcius
   Normal night temperature:	-89.44	degrees Celcius
   Maximum temperature:   	-49.55	degrees Celcius
   Minimum temperature:   	-114.28	degrees Celcius
   Escape Velocity:		7.92	km/sec
   Molecular weight retained:	12.65 and above
   Surface acceleration:	684.29	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.540
   Length of year:		1029.94	days
   Length of day:		18.36	hours
   Boiling point of water:	52.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	80.64
   liquids at surface:
				Ethanol      melts at -114  boils at 34
				Chlorine     melts at -101  boils at -64
   gasses in atmosphere:
				Oxygen           11.5%  PP   16.3 mb
				Nitrogen         88.1%  PP  124.3 mb
				Methane           0.1%  PP    0.1 mb
				Ozone             0.3%  PP    0.4 mb


Planet 7	*gas giant*
   Distance from primary:	2.810	AU
   Mass:			92.918	Earth masses
   Equatorial radius:		42526.3	km
   Density:			1.724	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		41.75	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	2048.91	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.490
   Length of year:		1644.90	days
   Length of day:		9.03	hours


Planet 8	*gas giant*
   Distance from primary:	6.978	AU
   Mass:			1542.466	Earth masses
   Equatorial radius:		104099.7	km
   Density:			1.951	grams/cc
   Eccentricity of orbit:	0.117
   Escape Velocity:		108.71	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5676.18	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.461
   Length of year:		6425.64	days
   Length of day:		5.42	hours


Planet 9	*gas giant*
   Distance from primary:	22.471	AU
   Mass:			104.996	Earth masses
   Equatorial radius:		52406.6	km
   Density:			1.041	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		39.97	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	1524.55	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.498
   Length of year:		37205.23	days
   Length of day:		10.47	hours


Planet 10	*gas giant*
   Distance from primary:	44.947	AU
   Mass:			0.990	Earth masses
   Equatorial radius:		14244.2	km
   Density:			0.489	grams/cc
   Eccentricity of orbit:	0.154
   Escape Velocity:		7.44	km/sec
   Molecular weight retained:	14.33 and above
   Surface acceleration:	194.49	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.547
   Length of year:		105265.40	days
   Length of day:		29.31	hours


