                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d7e
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6249 K
Stellar class: F8
Age: 4.330 billion years  (2.817 billion left on main sequence)
Habitable ecosphere radius: 1.236 AU

Planets present at:
1	  0.340 AU	no atmosphere
2	  0.465 AU	no atmosphere
3	  0.635 AU	greenhouse
4	  0.934 AU	greenhouse
5	  1.374 AU	no atmosphere
6	  2.328 AU	gas giant
7	  3.257 AU	no atmosphere
8	  5.857 AU	gas giant
9	 11.827 AU	gas giant
10	 18.895 AU	gas giant
11	 23.818 AU	gas giant
12	 35.145 AU	no atmosphere
13	 49.088 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.340	AU
   Mass:			0.071	Earth masses
   Equatorial radius:		2676.1	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.165
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		250.85	degrees Celcius
   Normal daytime temperature:	466.73	degrees Celcius
   Normal night temperature:	-168.40	degrees Celcius
   Maximum temperature:   	470.51	degrees Celcius
   Minimum temperature:   	-181.92	degrees Celcius
   Escape Velocity:		4.60	km/sec
   Molecular weight retained:	37.57 and above
   Surface acceleration:	394.72	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.058
   Length of year:		69.20	days
   Length of day:		1190.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.465	AU
   Mass:			0.053	Earth masses
   Equatorial radius:		2426.5	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.080
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		175.40	degrees Celcius
   Maximum temperature:   	379.61	degrees Celcius
   Minimum temperature:   	-211.30	degrees Celcius
   Escape Velocity:		4.17	km/sec
   Molecular weight retained:	45.75 and above
   Surface acceleration:	357.53	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.052
   Length of year:		110.93	days
   Length of day:		2662.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.635	AU
   Mass:			1.119	Earth masses
   Equatorial radius:		6642.7	km
   Density:			5.448	grams/cc
   Eccentricity of orbit:	0.168
   Surface gravity:		1.03	Earth gees
   Surface pressure:		107.907	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		513.75	degrees Celcius
   Maximum temperature:   	520.09	degrees Celcius
   Minimum temperature:   	502.23	degrees Celcius
   Escape Velocity:		11.59	km/sec
   Molecular weight retained:	5.91 and above
   Surface acceleration:	1011.38	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.595
   Length of year:		176.88	days
   Length of day:		80.57	hours
   Boiling point of water:	297.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1179
				Cesium       melts at 28    boils at 1222
				Gallium      melts at 30    boils at 3817
				Rubidium     melts at 39    boils at 1196
				Potassium    melts at 63    boils at 1314
				Sodium       melts at 98    boils at 1492
				Indium       melts at 157   boils at 3323
				Lithium      melts at 181   boils at 2203
				Selenium     melts at 217   boils at 1191
				Tin          melts at 232   boils at 4153
				Polonium     melts at 254   boils at 1614
				Bismuth      melts at 271   boils at 2535
				Thallium     melts at 304   boils at 2371
				Cadmium      melts at 321   boils at 1313
				Lead         melts at 328   boils at 2820
				Zinc         melts at 420   boils at 1530
				Tellurium    melts at 450   boils at 1657
   gasses in atmosphere:
				Sulfur           23.3%  PP 25182.7 mb
				Nitrogen         76.0%  PP 81971.1 mb
				Phosphorus        0.5%  PP  499.3 mb
				CarbonDioxide     0.1%  PP   56.4 mb
				Ethanol           0.1%  PP   57.4 mb


Planet 4	
   Distance from primary:	0.934	AU
   Mass:			0.875	Earth masses
   Equatorial radius:		6131.1	km
   Density:			5.417	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.95	Earth gees
   Surface pressure:		71.738	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		376.89	degrees Celcius
   Maximum temperature:   	382.08	degrees Celcius
   Minimum temperature:   	370.21	degrees Celcius
   Escape Velocity:		10.67	km/sec
   Molecular weight retained:	6.97 and above
   Surface acceleration:	928.19	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.480
   Length of year:		315.51	days
   Length of day:		17.45	hours
   Boiling point of water:	272.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1115
				Cesium       melts at 28    boils at 1156
				Gallium      melts at 30    boils at 3637
				Rubidium     melts at 39    boils at 1131
				Potassium    melts at 63    boils at 1244
				Sodium       melts at 98    boils at 1414
				Sulfur       melts at 113   boils at 776
				Indium       melts at 157   boils at 3165
				Lithium      melts at 181   boils at 2094
				Selenium     melts at 217   boils at 1127
				Tin          melts at 232   boils at 3958
				Polonium     melts at 254   boils at 1531
				Bismuth      melts at 271   boils at 2411
				Thallium     melts at 304   boils at 2255
				Cadmium      melts at 321   boils at 1243
				Lead         melts at 328   boils at 2684
   gasses in atmosphere:
				Nitrogen         99.1%  PP 71059.0 mb
				Phosphorus        0.6%  PP  448.5 mb
				CarbonDioxide     0.1%  PP   50.3 mb
				Ozone             0.1%  PP   44.4 mb
				Ethanol           0.1%  PP   51.1 mb


Planet 5	
   Distance from primary:	1.374	AU
   Mass:			0.112	Earth masses
   Equatorial radius:		3115.8	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.013	Earth atmospheres
   Surface temperature:		-39.17	degrees Celcius
   Normal daytime temperature:	-17.40	degrees Celcius
   Normal night temperature:	-61.24	degrees Celcius
   Maximum temperature:   	7.18	degrees Celcius
   Minimum temperature:   	-86.45	degrees Celcius
   Escape Velocity:		5.36	km/sec
   Molecular weight retained:	27.66 and above
   Surface acceleration:	460.56	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.439
   Length of year:		563.03	days
   Length of day:		23.59	hours
   Boiling point of water:	9.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	52.66
   liquids at surface:
				Ethanol      melts at -114  boils at -6
   gasses in atmosphere:
				CarbonDioxide    44.0%  PP    5.8 mb
				Ozone            51.2%  PP    6.8 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           4.1%  PP    0.5 mb
				Xenon             0.5%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.328	AU
   Mass:			128.769	Earth masses
   Equatorial radius:		46063.4	km
   Density:			1.880	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		47.22	km/sec
   Molecular weight retained:	0.36 and above
   Surface acceleration:	2420.13	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.457
   Length of year:		1241.69	days
   Length of day:		8.31	hours


Planet 7	
   Distance from primary:	3.257	AU
   Mass:			0.067	Earth masses
   Equatorial radius:		2623.4	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.005	Earth atmospheres
   Surface temperature:		-119.29	degrees Celcius
   Normal daytime temperature:	-103.38	degrees Celcius
   Normal night temperature:	-135.28	degrees Celcius
   Maximum temperature:   	-82.01	degrees Celcius
   Minimum temperature:   	-157.51	degrees Celcius
   Escape Velocity:		4.51	km/sec
   Molecular weight retained:	39.11 and above
   Surface acceleration:	386.86	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.366
   Length of year:		2055.37	days
   Length of day:		24.38	hours
   Boiling point of water:	-5.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	45.35
   gasses in atmosphere:
				Argon             0.3%  PP    0.0 mb
				Krypton          99.7%  PP    4.8 mb


Planet 8	*gas giant*
   Distance from primary:	5.857	AU
   Mass:			933.623	Earth masses
   Equatorial radius:		88652.6	km
   Density:			1.912	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		91.65	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4737.27	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.455
   Length of year:		4950.87	days
   Length of day:		5.94	hours


Planet 9	*gas giant*
   Distance from primary:	11.827	AU
   Mass:			47.678	Earth masses
   Equatorial radius:		39475.8	km
   Density:			1.106	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		31.04	km/sec
   Molecular weight retained:	0.82 and above
   Surface acceleration:	1220.11	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.473
   Length of year:		14221.26	days
   Length of day:		11.70	hours


Planet 10	*gas giant*
   Distance from primary:	18.895	AU
   Mass:			0.474	Earth masses
   Equatorial radius:		10693.3	km
   Density:			0.553	grams/cc
   Eccentricity of orbit:	0.121
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.47 and above
   Surface acceleration:	165.18	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.489
   Length of year:		28719.77	days
   Length of day:		31.80	hours


Planet 11	*gas giant*
   Distance from primary:	23.818	AU
   Mass:			87.556	Earth masses
   Equatorial radius:		49964.1	km
   Density:			1.002	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		37.39	km/sec
   Molecular weight retained:	0.57 and above
   Surface acceleration:	1398.65	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.502
   Length of year:		40642.82	days
   Length of day:		10.93	hours


Planet 12	
   Distance from primary:	35.145	AU
   Mass:			0.483	Earth masses
   Equatorial radius:		6734.8	km
   Density:			2.257	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-221.64	degrees Celcius
   Normal daytime temperature:	-216.32	degrees Celcius
   Normal night temperature:	-226.90	degrees Celcius
   Maximum temperature:   	-200.51	degrees Celcius
   Minimum temperature:   	-243.46	degrees Celcius
   Escape Velocity:		7.56	km/sec
   Molecular weight retained:	13.87 and above
   Surface acceleration:	424.88	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.138
   Length of year:		72857.86	days
   Length of day:		23.25	hours
   Boiling point of water:	-31.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.13
   gasses in atmosphere:
				Neon             100.0%  PP    0.6 mb


Planet 13	
   Distance from primary:	49.088	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		3594.5	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.140
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.39	degrees Celcius
   Normal daytime temperature:	-224.48	degrees Celcius
   Normal night temperature:	-236.18	degrees Celcius
   Maximum temperature:   	-209.26	degrees Celcius
   Minimum temperature:   	-251.33	degrees Celcius
   Escape Velocity:		3.99	km/sec
   Molecular weight retained:	49.83 and above
   Surface acceleration:	221.58	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.139
   Length of year:		120262.34	days
   Length of day:		32.20	hours
   Boiling point of water:	-70.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


