                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048769
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6338 K
Stellar class: F7
Age: 5.135 billion years  (1.676 billion left on main sequence)
Habitable ecosphere radius: 1.274 AU

Planets present at:
1	  0.319 AU	no atmosphere
2	  0.537 AU	no atmosphere
3	  0.848 AU	greenhouse
4	  0.978 AU	greenhouse
5	  1.864 AU	cold
6	  3.355 AU	gas giant
7	 13.260 AU	gas giant
8	 41.873 AU	no atmosphere
9	 44.156 AU	no atmosphere



Planet 1	
   Distance from primary:	0.319	AU
   Mass:			0.058	Earth masses
   Equatorial radius:		2509.8	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		274.83	degrees Celcius
   Normal daytime temperature:	496.93	degrees Celcius
   Normal night temperature:	-173.11	degrees Celcius
   Maximum temperature:   	499.88	degrees Celcius
   Minimum temperature:   	-183.65	degrees Celcius
   Escape Velocity:		4.31	km/sec
   Molecular weight retained:	42.75 and above
   Surface acceleration:	369.93	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.063
   Length of year:		62.68	days
   Length of day:		1504.25	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.537	AU
   Mass:			0.779	Earth masses
   Equatorial radius:		5902.0	km
   Density:			5.404	grams/cc
   Eccentricity of orbit:	0.169
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.99	degrees Celcius
   Maximum temperature:   	348.10	degrees Celcius
   Minimum temperature:   	-213.49	degrees Celcius
   Escape Velocity:		10.26	km/sec
   Molecular weight retained:	7.54 and above
   Surface acceleration:	891.38	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.059
   Length of year:		136.60	days
   Length of day:		2332.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.848	AU
   Mass:			0.602	Earth masses
   Equatorial radius:		5425.8	km
   Density:			5.379	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.83	Earth gees
   Surface pressure:		31.075	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		205.90	degrees Celcius
   Maximum temperature:   	213.41	degrees Celcius
   Minimum temperature:   	197.62	degrees Celcius
   Escape Velocity:		9.41	km/sec
   Molecular weight retained:	8.97 and above
   Surface acceleration:	815.64	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.557
   Length of year:		271.28	days
   Length of day:		23.67	hours
   Boiling point of water:	226.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 571
				Francium     melts at 27    boils at 1000
				Cesium       melts at 28    boils at 1037
				Gallium      melts at 30    boils at 3313
				Rubidium     melts at 39    boils at 1015
				Phosphorus   melts at 44    boils at 469
				Potassium    melts at 63    boils at 1119
				Sodium       melts at 98    boils at 1274
				Sulfur       melts at 113   boils at 689
				Indium       melts at 157   boils at 2880
				Lithium      melts at 181   boils at 1898
   gasses in atmosphere:
				Nitrogen         99.5%  PP 30932.6 mb
				CarbonDioxide     0.1%  PP   32.9 mb
				Ozone             0.1%  PP   31.7 mb
				Ethanol           0.1%  PP   33.7 mb


Planet 4	
   Distance from primary:	0.978	AU
   Mass:			0.463	Earth masses
   Equatorial radius:		4975.8	km
   Density:			5.357	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.76	Earth gees
   Surface pressure:		16.361	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		114.12	degrees Celcius
   Maximum temperature:   	123.37	degrees Celcius
   Minimum temperature:   	104.31	degrees Celcius
   Escape Velocity:		8.61	km/sec
   Molecular weight retained:	10.71 and above
   Surface acceleration:	745.00	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.422
   Length of year:		336.14	days
   Length of day:		20.74	hours
   Boiling point of water:	197.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 521
				Francium     melts at 27    boils at 924
				Cesium       melts at 28    boils at 959
				Gallium      melts at 30    boils at 3099
				Rubidium     melts at 39    boils at 938
				Phosphorus   melts at 44    boils at 425
				Potassium    melts at 63    boils at 1036
				Sodium       melts at 98    boils at 1182
				Sulfur       melts at 113   boils at 631
				Iodine       melts at 114   boils at 304
   gasses in atmosphere:
				Nitrogen         99.4%  PP 16258.2 mb
				Water             0.1%  PP    9.9 mb
				CarbonDioxide     0.2%  PP   24.6 mb
				Ammonia           0.1%  PP    8.5 mb
				Ozone             0.2%  PP   24.7 mb
				Ethanol           0.2%  PP   25.3 mb


Planet 5	
   Distance from primary:	1.864	AU
   Mass:			1.441	Earth masses
   Equatorial radius:		7209.8	km
   Density:			5.485	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		1.13	Earth gees
   Surface pressure:		1.884	Earth atmospheres
   Surface temperature:		-65.02	degrees Celcius
   Normal daytime temperature:	-62.83	degrees Celcius
   Normal night temperature:	-67.34	degrees Celcius
   Maximum temperature:   	-45.81	degrees Celcius
   Minimum temperature:   	-85.53	degrees Celcius
   Escape Velocity:		12.62	km/sec
   Molecular weight retained:	4.98 and above
   Surface acceleration:	1105.29	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.649
   Length of year:		883.99	days
   Length of day:		14.43	hours
   Boiling point of water:	118.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.20
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 96
				Chlorine     melts at -101  boils at -22
				Ammonia      melts at -78   boils at -22
				Radon        melts at -71   boils at -52
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1881.0 mb
				CarbonDioxide     0.1%  PP    1.0 mb
				Ozone             0.1%  PP    1.0 mb


Planet 6	*gas giant*
   Distance from primary:	3.355	AU
   Mass:			768.519	Earth masses
   Equatorial radius:		79758.5	km
   Density:			2.161	grams/cc
   Eccentricity of orbit:	0.148
   Escape Velocity:		87.66	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4817.70	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.508
   Length of year:		2133.51	days
   Length of day:		5.89	hours


Planet 7	*gas giant*
   Distance from primary:	13.260	AU
   Mass:			1750.660	Earth masses
   Equatorial radius:		113709.1	km
   Density:			1.699	grams/cc
   Eccentricity of orbit:	0.347
   Escape Velocity:		110.81	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5399.47	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.528
   Length of year:		16738.54	days
   Length of day:		5.56	hours


Planet 8	
   Distance from primary:	41.873	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		4853.7	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.87	degrees Celcius
   Normal daytime temperature:	-220.16	degrees Celcius
   Normal night temperature:	-231.50	degrees Celcius
   Maximum temperature:   	-206.66	degrees Celcius
   Minimum temperature:   	-245.56	degrees Celcius
   Escape Velocity:		5.41	km/sec
   Molecular weight retained:	27.13 and above
   Surface acceleration:	301.47	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.138
   Length of year:		94149.26	days
   Length of day:		27.60	hours
   Boiling point of water:	-54.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 9	
   Distance from primary:	44.156	AU
   Mass:			0.270	Earth masses
   Equatorial radius:		5568.2	km
   Density:			2.234	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.15	degrees Celcius
   Normal daytime temperature:	-221.93	degrees Celcius
   Normal night temperature:	-232.28	degrees Celcius
   Maximum temperature:   	-206.44	degrees Celcius
   Minimum temperature:   	-248.16	degrees Celcius
   Escape Velocity:		6.22	km/sec
   Molecular weight retained:	20.50 and above
   Surface acceleration:	347.68	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.145
   Length of year:		101954.77	days
   Length of day:		25.70	hours
   Boiling point of water:	-47.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


