                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047be9
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6325 K
Stellar class: F7
Age: 1.524 billion years  (5.679 billion left on main sequence)
Habitable ecosphere radius: 1.230 AU

Planets present at:
1	  0.351 AU	no atmosphere
2	  0.564 AU	no atmosphere
3	  0.870 AU	greenhouse
4	  1.153 AU	high pressure
5	  1.572 AU	no atmosphere
6	  2.377 AU	gas giant
7	  5.274 AU	gas giant
8	 13.521 AU	gas giant
9	 22.762 AU	gas giant
10	 31.385 AU	gas giant
11	 48.262 AU	no atmosphere



Planet 1	
   Distance from primary:	0.351	AU
   Mass:			0.143	Earth masses
   Equatorial radius:		3379.1	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		239.20	degrees Celcius
   Maximum temperature:   	456.97	degrees Celcius
   Minimum temperature:   	-193.48	degrees Celcius
   Escape Velocity:		5.81	km/sec
   Molecular weight retained:	23.48 and above
   Surface acceleration:	500.21	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.073
   Length of year:		72.67	days
   Length of day:		1744.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.564	AU
   Mass:			0.102	Earth masses
   Equatorial radius:		3017.5	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.176
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		129.92	degrees Celcius
   Maximum temperature:   	323.28	degrees Celcius
   Minimum temperature:   	-217.49	degrees Celcius
   Escape Velocity:		5.19	km/sec
   Molecular weight retained:	29.51 and above
   Surface acceleration:	445.81	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.081
   Length of year:		148.43	days
   Length of day:		2495.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.870	AU
   Mass:			0.517	Earth masses
   Equatorial radius:		5160.8	km
   Density:			5.366	grams/cc
   Eccentricity of orbit:	0.175
   Surface gravity:		0.79	Earth gees
   Surface pressure:		21.422	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		119.27	degrees Celcius
   Maximum temperature:   	127.85	degrees Celcius
   Minimum temperature:   	110.20	degrees Celcius
   Escape Velocity:		8.94	km/sec
   Molecular weight retained:	9.94 and above
   Surface acceleration:	773.95	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.603
   Length of year:		284.26	days
   Length of day:		18.75	hours
   Boiling point of water:	209.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 541
				Francium     melts at 27    boils at 955
				Cesium       melts at 28    boils at 991
				Gallium      melts at 30    boils at 3186
				Rubidium     melts at 39    boils at 969
				Phosphorus   melts at 44    boils at 443
				Potassium    melts at 63    boils at 1069
				Sodium       melts at 98    boils at 1219
				Sulfur       melts at 113   boils at 655
				Iodine       melts at 114   boils at 319
   gasses in atmosphere:
				Nitrogen         99.6%  PP 21329.0 mb
				Water             0.1%  PP   10.8 mb
				CarbonDioxide     0.1%  PP   20.5 mb
				Ozone             0.1%  PP   20.8 mb
				Ethanol           0.1%  PP   20.8 mb


Planet 4	
   Distance from primary:	1.153	AU
   Mass:			2.256	Earth masses
   Equatorial radius:		8329.4	km
   Density:			5.571	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		1.32	Earth gees
   Surface pressure:		4.708	Earth atmospheres
   Surface temperature:		21.68	degrees Celcius
   Normal daytime temperature:	23.51	degrees Celcius
   Normal night temperature:	19.72	degrees Celcius
   Maximum temperature:   	35.39	degrees Celcius
   Minimum temperature:   	7.26	degrees Celcius
   Escape Velocity:		14.70	km/sec
   Molecular weight retained:	3.67 and above
   Surface acceleration:	1296.75	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.500
   Length of year:		433.32	days
   Length of day:		13.37	hours
   Boiling point of water:	148.2	degrees Celcius
   Hydrosphere percentage:	86.94
   Cloud cover percentage:	92.59
   Ice cover percentage:	0.78
   liquids at surface:
				Ethanol      melts at -114  boils at 124
				Mercury      melts at -39   boils at 438
				Bromine      melts at -7    boils at 103
				Water        melts at 0     boils at 148
   gasses in atmosphere:
				Nitrogen          1.1%  PP   54.1 mb
				Helium           98.8%  PP 4654.3 mb


Planet 5	
   Distance from primary:	1.572	AU
   Mass:			0.307	Earth masses
   Equatorial radius:		4347.1	km
   Density:			5.331	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.092	Earth atmospheres
   Surface temperature:		-51.23	degrees Celcius
   Normal daytime temperature:	-40.08	degrees Celcius
   Normal night temperature:	-62.78	degrees Celcius
   Maximum temperature:   	-15.42	degrees Celcius
   Minimum temperature:   	-88.71	degrees Celcius
   Escape Velocity:		7.50	km/sec
   Molecular weight retained:	14.10 and above
   Surface acceleration:	647.62	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.497
   Length of year:		690.15	days
   Length of day:		18.90	hours
   Boiling point of water:	44.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.31
   Ice cover percentage:	69.00
   liquids at surface:
				Ethanol      melts at -114  boils at 26
   gasses in atmosphere:
				Oxygen           99.7%  PP   92.1 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.377	AU
   Mass:			39.783	Earth masses
   Equatorial radius:		32771.9	km
   Density:			1.613	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		31.12	km/sec
   Molecular weight retained:	0.82 and above
   Surface acceleration:	1477.17	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.518
   Length of year:		1282.49	days
   Length of day:		10.63	hours


Planet 7	*gas giant*
   Distance from primary:	5.274	AU
   Mass:			564.831	Earth masses
   Equatorial radius:		75930.4	km
   Density:			1.841	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		77.03	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3906.85	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.454
   Length of year:		4236.60	days
   Length of day:		6.54	hours


Planet 8	*gas giant*
   Distance from primary:	13.521	AU
   Mass:			141.505	Earth masses
   Equatorial radius:		54846.9	km
   Density:			1.224	grams/cc
   Eccentricity of orbit:	0.216
   Escape Velocity:		45.36	km/sec
   Molecular weight retained:	0.39 and above
   Surface acceleration:	1875.89	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.543
   Length of year:		17399.84	days
   Length of day:		9.44	hours


Planet 9	*gas giant*
   Distance from primary:	22.762	AU
   Mass:			81.165	Earth masses
   Equatorial radius:		48707.2	km
   Density:			1.002	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		36.46	km/sec
   Molecular weight retained:	0.60 and above
   Surface acceleration:	1364.34	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.478
   Length of year:		38008.69	days
   Length of day:		11.07	hours


Planet 10	*gas giant*
   Distance from primary:	31.385	AU
   Mass:			0.790	Earth masses
   Equatorial radius:		12956.1	km
   Density:			0.518	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		6.97	km/sec
   Molecular weight retained:	16.32 and above
   Surface acceleration:	187.70	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.538
   Length of year:		61546.35	days
   Length of day:		29.83	hours


Planet 11	
   Distance from primary:	48.262	AU
   Mass:			0.176	Earth masses
   Equatorial radius:		4832.8	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.90	degrees Celcius
   Normal daytime temperature:	-224.67	degrees Celcius
   Normal night temperature:	-235.03	degrees Celcius
   Maximum temperature:   	-210.84	degrees Celcius
   Minimum temperature:   	-249.20	degrees Celcius
   Escape Velocity:		5.39	km/sec
   Molecular weight retained:	27.36 and above
   Surface acceleration:	300.12	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.141
   Length of year:		117359.94	days
   Length of day:		27.66	hours
   Boiling point of water:	-53.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


