                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950482e2
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6133 K
Stellar class: F9
Age: 1.213 billion years  (5.748 billion left on main sequence)
Habitable ecosphere radius: 1.256 AU

Planets present at:
1	  0.381 AU	no atmosphere
2	  0.564 AU	no atmosphere
3	  0.648 AU	no atmosphere
4	  0.970 AU	greenhouse
5	  1.560 AU	gas giant
6	  1.927 AU	no atmosphere
7	  4.499 AU	gas giant
8	 10.291 AU	gas giant
9	 30.850 AU	gas giant



Planet 1	
   Distance from primary:	0.381	AU
   Mass:			0.111	Earth masses
   Equatorial radius:		3105.0	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.066
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		225.06	degrees Celcius
   Normal daytime temperature:	437.04	degrees Celcius
   Normal night temperature:	-188.84	degrees Celcius
   Maximum temperature:   	440.14	degrees Celcius
   Minimum temperature:   	-199.07	degrees Celcius
   Escape Velocity:		5.34	km/sec
   Molecular weight retained:	27.85 and above
   Surface acceleration:	458.94	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.063
   Length of year:		81.95	days
   Length of day:		1966.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.564	AU
   Mass:			0.090	Earth masses
   Equatorial radius:		2901.4	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.066
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		134.31	degrees Celcius
   Maximum temperature:   	328.92	degrees Celcius
   Minimum temperature:   	-219.97	degrees Celcius
   Escape Velocity:		4.99	km/sec
   Molecular weight retained:	31.93 and above
   Surface acceleration:	428.41	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.081
   Length of year:		147.63	days
   Length of day:		3543.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.648	AU
   Mass:			0.304	Earth masses
   Equatorial radius:		4332.2	km
   Density:			5.330	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		109.32	degrees Celcius
   Normal daytime temperature:	179.45	degrees Celcius
   Normal night temperature:	36.28	degrees Celcius
   Maximum temperature:   	208.16	degrees Celcius
   Minimum temperature:   	6.09	degrees Celcius
   Escape Velocity:		7.48	km/sec
   Molecular weight retained:	14.20 and above
   Surface acceleration:	645.32	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.058
   Length of year:		181.83	days
   Length of day:		47.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.970	AU
   Mass:			1.736	Earth masses
   Equatorial radius:		7657.0	km
   Density:			5.518	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		1.20	Earth gees
   Surface pressure:		317.096	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		560.25	degrees Celcius
   Maximum temperature:   	562.23	degrees Celcius
   Minimum temperature:   	555.21	degrees Celcius
   Escape Velocity:		13.45	km/sec
   Molecular weight retained:	4.39 and above
   Surface acceleration:	1180.75	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.421
   Length of year:		332.92	days
   Length of day:		14.13	hours
   Boiling point of water:	376.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1380
				Cesium       melts at 28    boils at 1429
				Gallium      melts at 30    boils at 4384
				Rubidium     melts at 39    boils at 1399
				Potassium    melts at 63    boils at 1534
				Sodium       melts at 98    boils at 1736
				Indium       melts at 157   boils at 3821
				Lithium      melts at 181   boils at 2546
				Selenium     melts at 217   boils at 1394
				Tin          melts at 232   boils at 4766
				Polonium     melts at 254   boils at 1876
				Bismuth      melts at 271   boils at 2924
				Thallium     melts at 304   boils at 2737
				Cadmium      melts at 321   boils at 1533
				Lead         melts at 328   boils at 3249
				Zinc         melts at 420   boils at 1780
				Tellurium    melts at 450   boils at 1925
   gasses in atmosphere:
				Sulfur           17.7%  PP 56209.5 mb
				Nitrogen         81.7%  PP 259167.3 mb
				Phosphorus        0.4%  PP 1126.3 mb


Planet 5	*gas giant*
   Distance from primary:	1.560	AU
   Mass:			3.179	Earth masses
   Equatorial radius:		15114.9	km
   Density:			1.314	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		12.95	km/sec
   Molecular weight retained:	4.73 and above
   Surface acceleration:	554.93	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.503
   Length of year:		678.68	days
   Length of day:		17.35	hours


Planet 6	
   Distance from primary:	1.927	AU
   Mass:			0.107	Earth masses
   Equatorial radius:		3068.7	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.122
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.009	Earth atmospheres
   Surface temperature:		-67.23	degrees Celcius
   Normal daytime temperature:	-48.17	degrees Celcius
   Normal night temperature:	-86.48	degrees Celcius
   Maximum temperature:   	-21.18	degrees Celcius
   Minimum temperature:   	-114.35	degrees Celcius
   Escape Velocity:		5.28	km/sec
   Molecular weight retained:	28.52 and above
   Surface acceleration:	453.49	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.355
   Length of year:		932.38	days
   Length of day:		22.55	hours
   Boiling point of water:	4.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	39.62
   liquids at surface:
				Ethanol      melts at -114  boils at -10
   gasses in atmosphere:
				CarbonDioxide    44.3%  PP    4.1 mb
				Ozone            51.3%  PP    4.7 mb
				Krypton           3.8%  PP    0.4 mb
				Xenon             0.5%  PP    0.0 mb


Planet 7	*gas giant*
   Distance from primary:	4.499	AU
   Mass:			327.315	Earth masses
   Equatorial radius:		63793.1	km
   Density:			1.799	grams/cc
   Eccentricity of orbit:	0.290
   Escape Velocity:		63.97	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3207.44	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.538
   Length of year:		3323.94	days
   Length of day:		7.22	hours


Planet 8	*gas giant*
   Distance from primary:	10.291	AU
   Mass:			1073.914	Earth masses
   Equatorial radius:		96654.2	km
   Density:			1.697	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		94.14	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4584.24	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.495
   Length of year:		11487.96	days
   Length of day:		6.04	hours


Planet 9	*gas giant*
   Distance from primary:	30.850	AU
   Mass:			25.514	Earth masses
   Equatorial radius:		35581.9	km
   Density:			0.808	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		23.91	km/sec
   Molecular weight retained:	1.39 and above
   Surface acceleration:	803.62	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.515
   Length of year:		59709.86	days
   Length of day:		14.42	hours


