                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c5d
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6244 K
Stellar class: F8
Age: 4.988 billion years  (2.198 billion left on main sequence)
Habitable ecosphere radius: 1.231 AU

Planets present at:
1	  0.368 AU	no atmosphere
2	  0.516 AU	no atmosphere
3	  0.622 AU	no atmosphere
4	  0.864 AU	greenhouse
5	  1.312 AU	high pressure
6	  1.606 AU	cold
7	  2.157 AU	no atmosphere
8	  3.247 AU	gas giant
9	  4.879 AU	gas giant
10	  7.179 AU	gas giant
11	 20.410 AU	gas giant
12	 37.208 AU	gas giant
13	 49.337 AU	no atmosphere



Planet 1	
   Distance from primary:	0.368	AU
   Mass:			0.018	Earth masses
   Equatorial radius:		1683.2	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		228.21	degrees Celcius
   Maximum temperature:   	443.75	degrees Celcius
   Minimum temperature:   	-197.05	degrees Celcius
   Escape Velocity:		2.89	km/sec
   Molecular weight retained:	95.33 and above
   Surface acceleration:	247.37	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.065
   Length of year:		78.25	days
   Length of day:		1877.96	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.516	AU
   Mass:			0.141	Earth masses
   Equatorial radius:		3358.9	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.108
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.35	degrees Celcius
   Maximum temperature:   	348.54	degrees Celcius
   Minimum temperature:   	-214.10	degrees Celcius
   Escape Velocity:		5.78	km/sec
   Molecular weight retained:	23.77 and above
   Surface acceleration:	497.16	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.066
   Length of year:		129.71	days
   Length of day:		2508.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.622	AU
   Mass:			0.223	Earth masses
   Equatorial radius:		3912.0	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		113.75	degrees Celcius
   Maximum temperature:   	303.20	degrees Celcius
   Minimum temperature:   	-223.48	degrees Celcius
   Escape Velocity:		6.74	km/sec
   Molecular weight retained:	17.46 and above
   Surface acceleration:	581.02	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.056
   Length of year:		171.49	days
   Length of day:		4115.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.864	AU
   Mass:			0.722	Earth masses
   Equatorial radius:		5757.9	km
   Density:			5.396	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.89	Earth gees
   Surface pressure:		54.089	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		301.68	degrees Celcius
   Maximum temperature:   	307.68	degrees Celcius
   Minimum temperature:   	294.60	degrees Celcius
   Escape Velocity:		10.00	km/sec
   Molecular weight retained:	7.94 and above
   Surface acceleration:	868.35	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.596
   Length of year:		281.12	days
   Length of day:		20.61	hours
   Boiling point of water:	255.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 620
				Francium     melts at 27    boils at 1074
				Cesium       melts at 28    boils at 1114
				Gallium      melts at 30    boils at 3521
				Rubidium     melts at 39    boils at 1089
				Potassium    melts at 63    boils at 1200
				Sodium       melts at 98    boils at 1364
				Sulfur       melts at 113   boils at 745
				Indium       melts at 157   boils at 3063
				Lithium      melts at 181   boils at 2024
				Selenium     melts at 217   boils at 1085
				Tin          melts at 232   boils at 3833
				Polonium     melts at 254   boils at 1478
				Bismuth      melts at 271   boils at 2332
   gasses in atmosphere:
				Nitrogen         98.9%  PP 53483.7 mb
				Phosphorus        0.7%  PP  400.0 mb
				CarbonDioxide     0.1%  PP   46.5 mb
				Ozone             0.1%  PP   42.2 mb
				Ethanol           0.1%  PP   47.5 mb


Planet 5	
   Distance from primary:	1.312	AU
   Mass:			2.571	Earth masses
   Equatorial radius:		8685.0	km
   Density:			5.601	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		1.39	Earth gees
   Surface pressure:		5.665	Earth atmospheres
   Surface temperature:		24.49	degrees Celcius
   Normal daytime temperature:	26.14	degrees Celcius
   Normal night temperature:	22.72	degrees Celcius
   Maximum temperature:   	37.27	degrees Celcius
   Minimum temperature:   	11.06	degrees Celcius
   Escape Velocity:		15.37	km/sec
   Molecular weight retained:	3.36 and above
   Surface acceleration:	1359.45	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.478
   Length of year:		525.77	days
   Length of day:		13.08	hours
   Boiling point of water:	154.8	degrees Celcius
   Hydrosphere percentage:	84.41
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.41
   liquids at surface:
				Ethanol      melts at -114  boils at 130
				Mercury      melts at -39   boils at 449
				Bromine      melts at -7    boils at 108
				Water        melts at 0     boils at 155
   gasses in atmosphere:
				Nitrogen          0.7%  PP   42.4 mb
				Helium           99.3%  PP 5622.4 mb


Planet 6	
   Distance from primary:	1.606	AU
   Mass:			1.331	Earth masses
   Equatorial radius:		7027.6	km
   Density:			5.473	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		1.10	Earth gees
   Surface pressure:		1.811	Earth atmospheres
   Surface temperature:		-10.87	degrees Celcius
   Normal daytime temperature:	-8.02	degrees Celcius
   Normal night temperature:	-13.89	degrees Celcius
   Maximum temperature:   	8.33	degrees Celcius
   Minimum temperature:   	-31.21	degrees Celcius
   Escape Velocity:		12.29	km/sec
   Molecular weight retained:	5.25 and above
   Surface acceleration:	1074.92	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.293
   Length of year:		711.97	days
   Length of day:		14.66	hours
   Boiling point of water:	117.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	8.80
   Ice cover percentage:	22.08
   liquids at surface:
				Ethanol      melts at -114  boils at 95
				Mercury      melts at -39   boils at 386
   gasses in atmosphere:
				Nitrogen         99.8%  PP 1807.5 mb
				CarbonDioxide     0.1%  PP    1.0 mb
				Ozone             0.1%  PP    1.0 mb


Planet 7	
   Distance from primary:	2.157	AU
   Mass:			0.316	Earth masses
   Equatorial radius:		4391.0	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.077	Earth atmospheres
   Surface temperature:		-80.25	degrees Celcius
   Normal daytime temperature:	-70.05	degrees Celcius
   Normal night temperature:	-90.78	degrees Celcius
   Maximum temperature:   	-45.63	degrees Celcius
   Minimum temperature:   	-116.59	degrees Celcius
   Escape Velocity:		7.58	km/sec
   Molecular weight retained:	13.81 and above
   Surface acceleration:	654.37	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.456
   Length of year:		1108.44	days
   Length of day:		18.77	hours
   Boiling point of water:	40.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	55.06
   liquids at surface:
				Ethanol      melts at -114  boils at 23
				Chlorine     melts at -101  boils at -72
   gasses in atmosphere:
				Oxygen           42.0%  PP   32.5 mb
				Nitrogen         56.6%  PP   43.8 mb
				Methane           0.2%  PP    0.1 mb
				Ozone             1.2%  PP    0.9 mb
				Krypton           0.1%  PP    0.1 mb


Planet 8	*gas giant*
   Distance from primary:	3.247	AU
   Mass:			2.929	Earth masses
   Equatorial radius:		15713.6	km
   Density:			1.077	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		12.19	km/sec
   Molecular weight retained:	5.34 and above
   Surface acceleration:	472.99	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.462
   Length of year:		2047.32	days
   Length of day:		18.79	hours


Planet 9	*gas giant*
   Distance from primary:	4.879	AU
   Mass:			670.879	Earth masses
   Equatorial radius:		79311.7	km
   Density:			1.919	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		82.14	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4253.14	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.482
   Length of year:		3767.19	days
   Length of day:		6.27	hours


Planet 10	*gas giant*
   Distance from primary:	7.179	AU
   Mass:			623.109	Earth masses
   Equatorial radius:		80161.2	km
   Density:			1.726	grams/cc
   Eccentricity of orbit:	0.197
   Escape Velocity:		78.74	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3867.01	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.465
   Length of year:		6725.99	days
   Length of day:		6.57	hours


Planet 11	*gas giant*
   Distance from primary:	20.410	AU
   Mass:			107.856	Earth masses
   Equatorial radius:		52433.4	km
   Density:			1.068	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		40.50	km/sec
   Molecular weight retained:	0.48 and above
   Surface acceleration:	1564.47	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.531
   Length of year:		32261.43	days
   Length of day:		10.33	hours


Planet 12	*gas giant*
   Distance from primary:	37.208	AU
   Mass:			2.073	Earth masses
   Equatorial radius:		17409.4	km
   Density:			0.561	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		9.75	km/sec
   Molecular weight retained:	8.36 and above
   Surface acceleration:	272.78	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.463
   Length of year:		79422.86	days
   Length of day:		24.75	hours


Planet 13	
   Distance from primary:	49.337	AU
   Mass:			0.049	Earth masses
   Equatorial radius:		3173.5	km
   Density:			2.201	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.63	degrees Celcius
   Normal daytime temperature:	-224.42	degrees Celcius
   Normal night temperature:	-236.70	degrees Celcius
   Maximum temperature:   	-214.49	degrees Celcius
   Minimum temperature:   	-247.03	degrees Celcius
   Escape Velocity:		3.52	km/sec
   Molecular weight retained:	64.06 and above
   Surface acceleration:	195.24	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.144
   Length of year:		121267.35	days
   Length of day:		34.30	hours
   Boiling point of water:	-77.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


