                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950487c4
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6351 K
Stellar class: F7
Age: 2.492 billion years  (4.307 billion left on main sequence)
Habitable ecosphere radius: 1.275 AU

Planets present at:
1	  0.478 AU	no atmosphere
2	  0.608 AU	no atmosphere
3	  0.834 AU	greenhouse
4	  1.430 AU	
5	  2.305 AU	gas giant
6	  3.207 AU	high pressure
7	  8.056 AU	gas giant
8	 12.319 AU	gas giant
9	 28.388 AU	gas giant
10	 36.832 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.478	AU
   Mass:			0.137	Earth masses
   Equatorial radius:		3333.1	km
   Density:			5.295	grams/cc
   Eccentricity of orbit:	0.224
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		172.47	degrees Celcius
   Normal daytime temperature:	371.85	degrees Celcius
   Normal night temperature:	-194.14	degrees Celcius
   Maximum temperature:   	375.57	degrees Celcius
   Minimum temperature:   	-205.67	degrees Celcius
   Escape Velocity:		5.73	km/sec
   Molecular weight retained:	24.14 and above
   Surface acceleration:	493.27	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.082
   Length of year:		114.98	days
   Length of day:		1747.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 2	
   Distance from primary:	0.608	AU
   Mass:			0.667	Earth masses
   Equatorial radius:		5610.0	km
   Density:			5.388	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.86	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		121.49	degrees Celcius
   Normal daytime temperature:	292.45	degrees Celcius
   Normal night temperature:	-126.93	degrees Celcius
   Maximum temperature:   	301.41	degrees Celcius
   Minimum temperature:   	-148.45	degrees Celcius
   Escape Velocity:		9.74	km/sec
   Molecular weight retained:	8.37 and above
   Surface acceleration:	844.82	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.088
   Length of year:		164.76	days
   Length of day:		356.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.834	AU
   Mass:			0.329	Earth masses
   Equatorial radius:		4449.8	km
   Density:			5.335	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.68	Earth gees
   Surface pressure:		11.601	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		114.88	degrees Celcius
   Maximum temperature:   	126.43	degrees Celcius
   Minimum temperature:   	102.58	degrees Celcius
   Escape Velocity:		7.68	km/sec
   Molecular weight retained:	13.45 and above
   Surface acceleration:	663.42	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.535
   Length of year:		264.54	days
   Length of day:		25.06	hours
   Boiling point of water:	182.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 496
				Francium     melts at 27    boils at 887
				Cesium       melts at 28    boils at 921
				Gallium      melts at 30    boils at 2994
				Rubidium     melts at 39    boils at 900
				Phosphorus   melts at 44    boils at 403
				Potassium    melts at 63    boils at 995
				Sodium       melts at 98    boils at 1137
				Sulfur       melts at 113   boils at 603
				Iodine       melts at 114   boils at 287
   gasses in atmosphere:
				Nitrogen         97.3%  PP 11293.6 mb
				Water             0.2%  PP   24.2 mb
				CarbonDioxide     0.7%  PP   79.3 mb
				Methane           0.1%  PP   14.9 mb
				Ammonia           0.2%  PP   19.4 mb
				Ozone             0.7%  PP   82.1 mb
				Ethanol           0.7%  PP   81.4 mb


Planet 4	
   Distance from primary:	1.430	AU
   Mass:			1.453	Earth masses
   Equatorial radius:		7229.1	km
   Density:			5.487	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		1.13	Earth gees
   Surface pressure:		1.530	Earth atmospheres
   Surface temperature:		11.40	degrees Celcius
   Normal daytime temperature:	14.70	degrees Celcius
   Normal night temperature:	7.89	degrees Celcius
   Maximum temperature:   	33.72	degrees Celcius
   Minimum temperature:   	-12.22	degrees Celcius
   Escape Velocity:		12.66	km/sec
   Molecular weight retained:	4.95 and above
   Surface acceleration:	1108.52	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.258
   Length of year:		594.09	days
   Length of day:		14.44	hours
   Boiling point of water:	112.1	degrees Celcius
   Hydrosphere percentage:	58.26
   Cloud cover percentage:	32.33
   Ice cover percentage:	2.61
   liquids at surface:
				Ethanol      melts at -114  boils at 90
				Mercury      melts at -39   boils at 377
				Bromine      melts at -7    boils at 70
				Water        melts at 0     boils at 112
   gasses in atmosphere:
				Oxygen           16.7%  PP  255.9 mb
				Nitrogen         83.1%  PP 1272.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.305	AU
   Mass:			119.579	Earth masses
   Equatorial radius:		44924.3	km
   Density:			1.882	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		46.08	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	2362.83	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.451
   Length of year:		1215.49	days
   Length of day:		8.41	hours


Planet 6	
   Distance from primary:	3.207	AU
   Mass:			3.240	Earth masses
   Equatorial radius:		9346.9	km
   Density:			5.661	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		1.51	Earth gees
   Surface pressure:		7.765	Earth atmospheres
   Surface temperature:		-92.87	degrees Celcius
   Maximum temperature:   	-83.70	degrees Celcius
   Minimum temperature:   	-102.60	degrees Celcius
   Escape Velocity:		16.63	km/sec
   Molecular weight retained:	2.87 and above
   Surface acceleration:	1478.89	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.637
   Length of year:		1994.77	days
   Length of day:		12.46	hours
   Boiling point of water:	166.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 141
				Chlorine     melts at -101  boils at 9
   gasses in atmosphere:
				Nitrogen          0.3%  PP   26.8 mb
				Helium           99.7%  PP 7738.6 mb


Planet 7	*gas giant*
   Distance from primary:	8.056	AU
   Mass:			1413.719	Earth masses
   Equatorial radius:		102480.6	km
   Density:			1.874	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		104.89	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5368.08	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.547
   Length of year:		7928.04	days
   Length of day:		5.58	hours


Planet 8	*gas giant*
   Distance from primary:	12.319	AU
   Mass:			43.367	Earth masses
   Equatorial radius:		38429.2	km
   Density:			1.090	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		30.00	km/sec
   Molecular weight retained:	0.88 and above
   Surface acceleration:	1171.04	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.530
   Length of year:		15019.61	days
   Length of day:		11.94	hours


Planet 9	*gas giant*
   Distance from primary:	28.388	AU
   Mass:			1.359	Earth masses
   Equatorial radius:		15003.8	km
   Density:			0.574	grams/cc
   Eccentricity of orbit:	0.206
   Escape Velocity:		8.50	km/sec
   Molecular weight retained:	10.99 and above
   Surface acceleration:	240.70	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.514
   Length of year:		52543.39	days
   Length of day:		26.34	hours


Planet 10	*gas giant*
   Distance from primary:	36.832	AU
   Mass:			3.438	Earth masses
   Equatorial radius:		20101.5	km
   Density:			0.604	grams/cc
   Eccentricity of orbit:	0.019
   Escape Velocity:		11.68	km/sec
   Molecular weight retained:	5.82 and above
   Surface acceleration:	339.33	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.550
   Length of year:		77653.86	days
   Length of day:		22.19	hours


