                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481ae
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6280 K
Stellar class: F8
Age: 1.573 billion years  (5.430 billion left on main sequence)
Habitable ecosphere radius: 1.252 AU

Planets present at:
1	  0.362 AU	no atmosphere
2	  0.543 AU	no atmosphere
3	  0.741 AU	no atmosphere
4	  1.124 AU	greenhouse
5	  2.578 AU	gas giant
6	  8.310 AU	gas giant
7	 24.310 AU	gas giant
8	 37.934 AU	no atmosphere
9	 47.983 AU	no atmosphere



Planet 1	
   Distance from primary:	0.362	AU
   Mass:			0.112	Earth masses
   Equatorial radius:		3117.7	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		236.01	degrees Celcius
   Normal daytime temperature:	450.24	degrees Celcius
   Normal night temperature:	-185.27	degrees Celcius
   Maximum temperature:   	453.30	degrees Celcius
   Minimum temperature:   	-195.54	degrees Celcius
   Escape Velocity:		5.36	km/sec
   Molecular weight retained:	27.62 and above
   Surface acceleration:	460.85	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.068
   Length of year:		76.08	days
   Length of day:		1825.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.543	AU
   Mass:			0.465	Earth masses
   Equatorial radius:		4984.2	km
   Density:			5.358	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		142.88	degrees Celcius
   Maximum temperature:   	339.39	degrees Celcius
   Minimum temperature:   	-217.83	degrees Celcius
   Escape Velocity:		8.63	km/sec
   Molecular weight retained:	10.67 and above
   Surface acceleration:	746.32	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.068
   Length of year:		139.54	days
   Length of day:		3348.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.741	AU
   Mass:			0.059	Earth masses
   Equatorial radius:		2510.9	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		82.92	degrees Celcius
   Maximum temperature:   	264.63	degrees Celcius
   Minimum temperature:   	-227.20	degrees Celcius
   Escape Velocity:		4.31	km/sec
   Molecular weight retained:	42.71 and above
   Surface acceleration:	370.09	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.070
   Length of year:		222.30	days
   Length of day:		5335.30	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.124	AU
   Mass:			0.584	Earth masses
   Equatorial radius:		5370.6	km
   Density:			5.376	grams/cc
   Eccentricity of orbit:	0.131
   Surface gravity:		0.82	Earth gees
   Surface pressure:		27.156	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		111.38	degrees Celcius
   Maximum temperature:   	118.78	degrees Celcius
   Minimum temperature:   	103.57	degrees Celcius
   Escape Velocity:		9.31	km/sec
   Molecular weight retained:	9.16 and above
   Surface acceleration:	806.93	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.456
   Length of year:		415.67	days
   Length of day:		17.16	hours
   Boiling point of water:	220.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 560
				Francium     melts at 27    boils at 983
				Cesium       melts at 28    boils at 1020
				Gallium      melts at 30    boils at 3266
				Rubidium     melts at 39    boils at 998
				Phosphorus   melts at 44    boils at 459
				Potassium    melts at 63    boils at 1100
				Sodium       melts at 98    boils at 1254
   gasses in atmosphere:
				Nitrogen         99.6%  PP 27053.1 mb
				CarbonDioxide     0.1%  PP   21.8 mb
				Ozone             0.1%  PP   21.9 mb
				Ethanol           0.1%  PP   22.1 mb


Planet 5	*gas giant*
   Distance from primary:	2.578	AU
   Mass:			541.685	Earth masses
   Equatorial radius:		70560.7	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.312
   Escape Velocity:		78.25	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	4338.71	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.520
   Length of year:		1442.33	days
   Length of day:		6.20	hours


Planet 6	*gas giant*
   Distance from primary:	8.310	AU
   Mass:			1201.794	Earth masses
   Equatorial radius:		98144.5	km
   Density:			1.814	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		98.82	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4975.50	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.495
   Length of year:		8340.57	days
   Length of day:		5.79	hours


Planet 7	*gas giant*
   Distance from primary:	24.310	AU
   Mass:			162.629	Earth masses
   Equatorial radius:		59891.3	km
   Density:			1.080	grams/cc
   Eccentricity of orbit:	0.183
   Escape Velocity:		46.54	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	1808.05	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.541
   Length of year:		41791.85	days
   Length of day:		9.61	hours


Planet 8	
   Distance from primary:	37.934	AU
   Mass:			0.315	Earth masses
   Equatorial radius:		5853.9	km
   Density:			2.239	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-223.79	degrees Celcius
   Normal daytime temperature:	-218.33	degrees Celcius
   Normal night temperature:	-229.19	degrees Celcius
   Maximum temperature:   	-205.35	degrees Celcius
   Minimum temperature:   	-242.91	degrees Celcius
   Escape Velocity:		6.55	km/sec
   Molecular weight retained:	18.51 and above
   Surface acceleration:	366.37	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.161
   Length of year:		81480.46	days
   Length of day:		25.04	hours
   Boiling point of water:	-42.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 9	
   Distance from primary:	47.983	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		3316.6	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.95	degrees Celcius
   Normal daytime temperature:	-223.76	degrees Celcius
   Normal night temperature:	-236.01	degrees Celcius
   Maximum temperature:   	-213.27	degrees Celcius
   Minimum temperature:   	-246.91	degrees Celcius
   Escape Velocity:		3.68	km/sec
   Molecular weight retained:	58.61 and above
   Surface acceleration:	204.18	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.165
   Length of year:		115914.47	days
   Length of day:		33.54	hours
   Boiling point of water:	-73.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


