                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048331
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6322 K
Stellar class: F7
Age: 3.426 billion years  (3.525 billion left on main sequence)
Habitable ecosphere radius: 1.257 AU

Planets present at:
1	  0.322 AU	no atmosphere
2	  0.536 AU	no atmosphere
3	  0.646 AU	greenhouse
4	  0.820 AU	greenhouse
5	  1.417 AU	no atmosphere
6	  1.679 AU	high pressure
7	  3.889 AU	gas giant
8	  9.268 AU	gas giant
9	 22.288 AU	gas giant
10	 38.511 AU	no atmosphere
11	 45.962 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.322	AU
   Mass:			0.122	Earth masses
   Equatorial radius:		3207.8	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.140
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		268.43	degrees Celcius
   Normal daytime temperature:	487.99	degrees Celcius
   Normal night temperature:	-163.80	degrees Celcius
   Maximum temperature:   	491.77	degrees Celcius
   Minimum temperature:   	-177.71	degrees Celcius
   Escape Velocity:		5.52	km/sec
   Molecular weight retained:	26.08 and above
   Surface acceleration:	474.40	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.066
   Length of year:		63.73	days
   Length of day:		1153.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.536	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		2579.7	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.25	degrees Celcius
   Maximum temperature:   	346.15	degrees Celcius
   Minimum temperature:   	-217.27	degrees Celcius
   Escape Velocity:		4.43	km/sec
   Molecular weight retained:	40.45 and above
   Surface acceleration:	380.33	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.051
   Length of year:		136.87	days
   Length of day:		3284.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.646	AU
   Mass:			0.836	Earth masses
   Equatorial radius:		6040.8	km
   Density:			5.412	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.93	Earth gees
   Surface pressure:		60.840	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		466.31	degrees Celcius
   Maximum temperature:   	474.06	degrees Celcius
   Minimum temperature:   	454.42	degrees Celcius
   Escape Velocity:		10.51	km/sec
   Molecular weight retained:	7.19 and above
   Surface acceleration:	913.65	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.443
   Length of year:		181.03	days
   Length of day:		62.47	hours
   Boiling point of water:	262.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1091
				Cesium       melts at 28    boils at 1131
				Gallium      melts at 30    boils at 3568
				Rubidium     melts at 39    boils at 1106
				Potassium    melts at 63    boils at 1218
				Sodium       melts at 98    boils at 1384
				Indium       melts at 157   boils at 3105
				Lithium      melts at 181   boils at 2052
				Selenium     melts at 217   boils at 1102
				Tin          melts at 232   boils at 3884
				Polonium     melts at 254   boils at 1500
				Bismuth      melts at 271   boils at 2364
				Thallium     melts at 304   boils at 2210
				Cadmium      melts at 321   boils at 1217
				Lead         melts at 328   boils at 2632
				Zinc         melts at 420   boils at 1421
				Tellurium    melts at 450   boils at 1540
   gasses in atmosphere:
				Sulfur           24.8%  PP 15087.6 mb
				Nitrogen         74.5%  PP 45297.9 mb
				Phosphorus        0.5%  PP  298.9 mb
				CarbonDioxide     0.1%  PP   33.9 mb
				Ozone             0.1%  PP   31.6 mb
				Ethanol           0.1%  PP   34.5 mb


Planet 4	
   Distance from primary:	0.820	AU
   Mass:			0.418	Earth masses
   Equatorial radius:		4812.7	km
   Density:			5.350	grams/cc
   Eccentricity of orbit:	0.088
   Surface gravity:		0.73	Earth gees
   Surface pressure:		15.461	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		116.81	degrees Celcius
   Maximum temperature:   	126.84	degrees Celcius
   Minimum temperature:   	106.08	degrees Celcius
   Escape Velocity:		8.32	km/sec
   Molecular weight retained:	11.46 and above
   Surface acceleration:	719.60	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.564
   Length of year:		258.78	days
   Length of day:		26.17	hours
   Boiling point of water:	194.6	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 517
				Francium     melts at 27    boils at 918
				Cesium       melts at 28    boils at 953
				Gallium      melts at 30    boils at 3081
				Rubidium     melts at 39    boils at 931
				Phosphorus   melts at 44    boils at 421
				Potassium    melts at 63    boils at 1029
				Sodium       melts at 98    boils at 1174
				Sulfur       melts at 113   boils at 627
				Iodine       melts at 114   boils at 301
   gasses in atmosphere:
				Nitrogen         99.3%  PP 15348.8 mb
				Water             0.1%  PP   10.6 mb
				CarbonDioxide     0.2%  PP   27.2 mb
				Methane           0.1%  PP    8.0 mb
				Ammonia           0.1%  PP    9.1 mb
				Ozone             0.2%  PP   27.7 mb
				Ethanol           0.2%  PP   27.8 mb


Planet 5	
   Distance from primary:	1.417	AU
   Mass:			0.299	Earth masses
   Equatorial radius:		4308.8	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.097	Earth atmospheres
   Surface temperature:		-17.09	degrees Celcius
   Normal daytime temperature:	-4.27	degrees Celcius
   Normal night temperature:	-30.41	degrees Celcius
   Maximum temperature:   	21.89	degrees Celcius
   Minimum temperature:   	-57.75	degrees Celcius
   Escape Velocity:		7.44	km/sec
   Molecular weight retained:	14.35 and above
   Surface acceleration:	641.73	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.310
   Length of year:		587.55	days
   Length of day:		19.22	hours
   Boiling point of water:	45.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	4.07
   Ice cover percentage:	30.84
   liquids at surface:
				Ethanol      melts at -114  boils at 27
				Mercury      melts at -39   boils at 265
   gasses in atmosphere:
				Oxygen           97.9%  PP   95.3 mb
				CarbonDioxide     0.9%  PP    0.8 mb
				Methane           0.1%  PP    0.1 mb
				Ammonia           0.2%  PP    0.2 mb
				Ozone             0.9%  PP    0.9 mb
				Krypton           0.1%  PP    0.0 mb


Planet 6	
   Distance from primary:	1.679	AU
   Mass:			1.782	Earth masses
   Equatorial radius:		7722.2	km
   Density:			5.523	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		1.21	Earth gees
   Surface pressure:		3.104	Earth atmospheres
   Surface temperature:		-1.99	degrees Celcius
   Normal daytime temperature:	0.16	degrees Celcius
   Normal night temperature:	-4.28	degrees Celcius
   Maximum temperature:   	13.93	degrees Celcius
   Minimum temperature:   	-18.80	degrees Celcius
   Escape Velocity:		13.57	km/sec
   Molecular weight retained:	4.31 and above
   Surface acceleration:	1191.86	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.221
   Length of year:		757.70	days
   Length of day:		13.90	hours
   Boiling point of water:	134.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	17.85
   Ice cover percentage:	10.41
   liquids at surface:
				Ethanol      melts at -114  boils at 111
				Mercury      melts at -39   boils at 414
				Bromine      melts at -7    boils at 90
   gasses in atmosphere:
				Oxygen            1.7%  PP   51.5 mb
				Nitrogen         98.2%  PP 3047.9 mb


Planet 7	*gas giant*
   Distance from primary:	3.889	AU
   Mass:			1429.897	Earth masses
   Equatorial radius:		96880.1	km
   Density:			2.244	grams/cc
   Eccentricity of orbit:	0.229
   Escape Velocity:		108.50	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	6075.40	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.531
   Length of year:		2667.17	days
   Length of day:		5.24	hours


Planet 8	*gas giant*
   Distance from primary:	9.268	AU
   Mass:			482.267	Earth masses
   Equatorial radius:		75855.8	km
   Density:			1.577	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		71.21	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3342.33	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.462
   Length of year:		9823.66	days
   Length of day:		7.07	hours


Planet 9	*gas giant*
   Distance from primary:	22.288	AU
   Mass:			27.053	Earth masses
   Equatorial radius:		35224.8	km
   Density:			0.883	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		24.75	km/sec
   Molecular weight retained:	1.30 and above
   Surface acceleration:	869.47	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.517
   Length of year:		36657.89	days
   Length of day:		13.86	hours


Planet 10	
   Distance from primary:	38.511	AU
   Mass:			0.309	Earth masses
   Equatorial radius:		5819.2	km
   Density:			2.239	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-223.85	degrees Celcius
   Normal daytime temperature:	-218.38	degrees Celcius
   Normal night temperature:	-229.25	degrees Celcius
   Maximum temperature:   	-204.57	degrees Celcius
   Minimum temperature:   	-243.77	degrees Celcius
   Escape Velocity:		6.51	km/sec
   Molecular weight retained:	18.73 and above
   Surface acceleration:	364.10	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.149
   Length of year:		83266.99	days
   Length of day:		25.12	hours
   Boiling point of water:	-41.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   gasses in atmosphere:
				Neon             100.0%  PP    0.3 mb


Planet 11	*gas giant*
   Distance from primary:	45.962	AU
   Mass:			0.353	Earth masses
   Equatorial radius:		10556.4	km
   Density:			0.429	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		5.17	km/sec
   Molecular weight retained:	29.74 and above
   Surface acceleration:	126.42	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.498
   Length of year:		108564.64	days
   Length of day:		36.35	hours


