                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047cd4
Stellar mass: 1.09 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6048 K
Stellar class: F9
Age: 4.208 billion years  (2.963 billion left on main sequence)
Habitable ecosphere radius: 1.233 AU

Planets present at:
1	  0.385 AU	no atmosphere
2	  0.721 AU	greenhouse
3	  1.188 AU	
4	  1.730 AU	cold
5	  2.732 AU	gas giant
6	  5.377 AU	gas giant
7	 10.928 AU	gas giant
8	 16.364 AU	gas giant
9	 25.694 AU	gas giant
10	 41.881 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.385	AU
   Mass:			0.180	Earth masses
   Equatorial radius:		3642.7	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		217.54	degrees Celcius
   Normal daytime temperature:	427.16	degrees Celcius
   Normal night temperature:	-184.39	degrees Celcius
   Maximum temperature:   	430.54	degrees Celcius
   Minimum temperature:   	-195.62	degrees Celcius
   Escape Velocity:		6.27	km/sec
   Molecular weight retained:	20.17 and above
   Surface acceleration:	540.08	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.063
   Length of year:		83.72	days
   Length of day:		1592.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.721	AU
   Mass:			1.662	Earth masses
   Equatorial radius:		7550.9	km
   Density:			5.510	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		1.19	Earth gees
   Surface pressure:		213.409	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		624.60	degrees Celcius
   Maximum temperature:   	626.89	degrees Celcius
   Minimum temperature:   	618.13	degrees Celcius
   Escape Velocity:		13.25	km/sec
   Molecular weight retained:	4.52 and above
   Surface acceleration:	1162.72	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.420
   Length of year:		214.13	days
   Length of day:		19.14	hours
   Boiling point of water:	344.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1300
				Cesium       melts at 28    boils at 1346
				Gallium      melts at 30    boils at 4158
				Rubidium     melts at 39    boils at 1318
				Potassium    melts at 63    boils at 1447
				Sodium       melts at 98    boils at 1639
				Indium       melts at 157   boils at 3623
				Lithium      melts at 181   boils at 2409
				Selenium     melts at 217   boils at 1313
				Tin          melts at 232   boils at 4522
				Polonium     melts at 254   boils at 1772
				Bismuth      melts at 271   boils at 2769
				Thallium     melts at 304   boils at 2592
				Cadmium      melts at 321   boils at 1446
				Lead         melts at 328   boils at 3078
				Zinc         melts at 420   boils at 1681
				Tellurium    melts at 450   boils at 1818
   gasses in atmosphere:
				Sulfur           20.5%  PP 43686.4 mb
				Nitrogen         78.9%  PP 168428.9 mb
				Phosphorus        0.4%  PP  870.1 mb


Planet 3	
   Distance from primary:	1.188	AU
   Mass:			0.654	Earth masses
   Equatorial radius:		5575.1	km
   Density:			5.387	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.86	Earth gees
   Surface pressure:		0.360	Earth atmospheres
   Surface temperature:		15.99	degrees Celcius
   Normal daytime temperature:	23.69	degrees Celcius
   Normal night temperature:	7.86	degrees Celcius
   Maximum temperature:   	47.11	degrees Celcius
   Minimum temperature:   	-16.80	degrees Celcius
   Escape Velocity:		9.67	km/sec
   Molecular weight retained:	8.48 and above
   Surface acceleration:	839.29	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.304
   Length of year:		453.15	days
   Length of day:		17.03	hours
   Boiling point of water:	73.8	degrees Celcius
   Hydrosphere percentage:	51.20
   Cloud cover percentage:	39.79
   Ice cover percentage:	1.45
   liquids at surface:
				Ethanol      melts at -114  boils at 54
				Mercury      melts at -39   boils at 313
				Bromine      melts at -7    boils at 36
				Water        melts at 0     boils at 74
   gasses in atmosphere:
				Oxygen           42.4%  PP  152.8 mb
				Nitrogen         57.4%  PP  206.9 mb


Planet 4	
   Distance from primary:	1.730	AU
   Mass:			0.543	Earth masses
   Equatorial radius:		5244.4	km
   Density:			5.370	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.80	Earth gees
   Surface pressure:		0.261	Earth atmospheres
   Surface temperature:		-63.56	degrees Celcius
   Normal daytime temperature:	-57.08	degrees Celcius
   Normal night temperature:	-70.35	degrees Celcius
   Maximum temperature:   	-36.11	degrees Celcius
   Minimum temperature:   	-92.68	degrees Celcius
   Escape Velocity:		9.09	km/sec
   Molecular weight retained:	9.62 and above
   Surface acceleration:	787.07	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.580
   Length of year:		795.82	days
   Length of day:		17.14	hours
   Boiling point of water:	66.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.14
   Ice cover percentage:	75.79
   liquids at surface:
				Ethanol      melts at -114  boils at 47
				Chlorine     melts at -101  boils at -55
				Ammonia      melts at -78   boils at -55
   gasses in atmosphere:
				Oxygen            7.2%  PP   18.8 mb
				Nitrogen         92.6%  PP  241.6 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.732	AU
   Mass:			20.259	Earth masses
   Equatorial radius:		27224.3	km
   Density:			1.433	grams/cc
   Eccentricity of orbit:	0.144
   Escape Velocity:		24.36	km/sec
   Molecular weight retained:	1.34 and above
   Surface acceleration:	1090.05	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.506
   Length of year:		1579.42	days
   Length of day:		12.38	hours


Planet 6	*gas giant*
   Distance from primary:	5.377	AU
   Mass:			1226.955	Earth masses
   Equatorial radius:		95340.1	km
   Density:			2.020	grams/cc
   Eccentricity of orbit:	0.094
   Escape Velocity:		101.31	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5382.91	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.469
   Length of year:		4354.29	days
   Length of day:		5.57	hours


Planet 7	*gas giant*
   Distance from primary:	10.928	AU
   Mass:			2.101	Earth masses
   Equatorial radius:		15779.7	km
   Density:			0.763	grams/cc
   Eccentricity of orbit:	0.151
   Escape Velocity:		10.31	km/sec
   Molecular weight retained:	7.47 and above
   Surface acceleration:	336.55	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.471
   Length of year:		12636.89	days
   Length of day:		22.28	hours


Planet 8	*gas giant*
   Distance from primary:	16.364	AU
   Mass:			326.656	Earth masses
   Equatorial radius:		71109.0	km
   Density:			1.296	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		60.53	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2576.21	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.523
   Length of year:		23148.05	days
   Length of day:		8.05	hours


Planet 9	*gas giant*
   Distance from primary:	25.694	AU
   Mass:			2.084	Earth masses
   Equatorial radius:		16903.4	km
   Density:			0.616	grams/cc
   Eccentricity of orbit:	0.168
   Escape Velocity:		9.92	km/sec
   Molecular weight retained:	8.07 and above
   Surface acceleration:	290.83	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.534
   Length of year:		45562.26	days
   Length of day:		23.97	hours


Planet 10	*gas giant*
   Distance from primary:	41.881	AU
   Mass:			0.723	Earth masses
   Equatorial radius:		12926.7	km
   Density:			0.477	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		6.68	km/sec
   Molecular weight retained:	17.81 and above
   Surface acceleration:	172.43	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.487
   Length of year:		94815.18	days
   Length of day:		31.13	hours


