                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504812f
Stellar mass: 1.10 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6184 K
Stellar class: F8
Age: 2.196 billion years  (4.823 billion left on main sequence)
Habitable ecosphere radius: 1.250 AU

Planets present at:
1	  0.411 AU	no atmosphere
2	  0.784 AU	no atmosphere
3	  0.958 AU	greenhouse
4	  1.122 AU	greenhouse
5	  1.888 AU	no atmosphere
6	  2.127 AU	cold
7	  2.712 AU	gas giant
8	  4.253 AU	cold
9	  5.742 AU	gas giant
10	 14.216 AU	gas giant
11	 26.256 AU	gas giant
12	 43.288 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.411	AU
   Mass:			0.348	Earth masses
   Equatorial radius:		4532.0	km
   Density:			5.338	grams/cc
   Eccentricity of orbit:	0.122
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		202.21	degrees Celcius
   Normal daytime temperature:	408.57	degrees Celcius
   Normal night temperature:	-189.06	degrees Celcius
   Maximum temperature:   	411.99	degrees Celcius
   Minimum temperature:   	-200.12	degrees Celcius
   Escape Velocity:		7.83	km/sec
   Molecular weight retained:	12.95 and above
   Surface acceleration:	676.10	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.089
   Length of year:		91.76	days
   Length of day:		1723.96	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.784	AU
   Mass:			0.213	Earth masses
   Equatorial radius:		3852.2	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		72.64	degrees Celcius
   Normal daytime temperature:	125.86	degrees Celcius
   Normal night temperature:	18.19	degrees Celcius
   Maximum temperature:   	156.37	degrees Celcius
   Minimum temperature:   	-13.15	degrees Celcius
   Escape Velocity:		6.64	km/sec
   Molecular weight retained:	18.02 and above
   Surface acceleration:	571.91	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.070
   Length of year:		242.17	days
   Length of day:		37.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	0.958	AU
   Mass:			0.177	Earth masses
   Equatorial radius:		3623.0	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.55	Earth gees
   Surface pressure:		2.727	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		68.61	degrees Celcius
   Normal daytime temperature:	73.37	degrees Celcius
   Normal night temperature:	63.29	degrees Celcius
   Maximum temperature:   	88.84	degrees Celcius
   Minimum temperature:   	47.10	degrees Celcius
   Escape Velocity:		6.24	km/sec
   Molecular weight retained:	20.40 and above
   Surface acceleration:	537.10	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.038
   Length of year:		326.87	days
   Length of day:		24.71	hours
   Boiling point of water:	129.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 107
				Mercury      melts at -39   boils at 407
				Water        melts at 0     boils at 130
				Francium     melts at 27    boils at 753
				Cesium       melts at 28    boils at 783
				Gallium      melts at 30    boils at 2617
				Rubidium     melts at 39    boils at 765
				Phosphorus   melts at 44    boils at 325
				Potassium    melts at 63    boils at 849
   gasses in atmosphere:
				CarbonDioxide    46.3%  PP 1261.9 mb
				Ozone            50.1%  PP 1365.2 mb
				Argon             0.1%  PP    2.0 mb
				Krypton           3.2%  PP   87.1 mb
				Xenon             0.4%  PP   10.6 mb


Planet 4	
   Distance from primary:	1.122	AU
   Mass:			1.981	Earth masses
   Equatorial radius:		7988.9	km
   Density:			5.543	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		1.26	Earth gees
   Surface pressure:		359.414	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		463.50	degrees Celcius
   Maximum temperature:   	465.75	degrees Celcius
   Minimum temperature:   	459.23	degrees Celcius
   Escape Velocity:		14.06	km/sec
   Molecular weight retained:	4.01 and above
   Surface acceleration:	1237.61	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.560
   Length of year:		414.83	days
   Length of day:		13.74	hours
   Boiling point of water:	386.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1407
				Cesium       melts at 28    boils at 1457
				Gallium      melts at 30    boils at 4460
				Rubidium     melts at 39    boils at 1427
				Potassium    melts at 63    boils at 1564
				Sodium       melts at 98    boils at 1769
				Indium       melts at 157   boils at 3888
				Lithium      melts at 181   boils at 2592
				Selenium     melts at 217   boils at 1421
				Tin          melts at 232   boils at 4849
				Polonium     melts at 254   boils at 1911
				Bismuth      melts at 271   boils at 2976
				Thallium     melts at 304   boils at 2787
				Cadmium      melts at 321   boils at 1563
				Lead         melts at 328   boils at 3307
				Zinc         melts at 420   boils at 1814
				Tellurium    melts at 450   boils at 1961
   gasses in atmosphere:
				Sulfur           17.7%  PP 63720.2 mb
				Nitrogen         81.7%  PP 293779.9 mb
				Phosphorus        0.4%  PP 1276.4 mb


Planet 5	
   Distance from primary:	1.888	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		2476.2	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.002	Earth atmospheres
   Surface temperature:		-65.16	degrees Celcius
   Normal daytime temperature:	-42.44	degrees Celcius
   Normal night temperature:	-87.98	degrees Celcius
   Maximum temperature:   	-16.90	degrees Celcius
   Minimum temperature:   	-114.12	degrees Celcius
   Escape Velocity:		4.25	km/sec
   Molecular weight retained:	43.92 and above
   Surface acceleration:	364.93	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.302
   Length of year:		905.07	days
   Length of day:		25.27	hours
   Boiling point of water:	-15.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	29.68
   liquids at surface:
				Ethanol      melts at -114  boils at -26
   gasses in atmosphere:
				CarbonDioxide     1.5%  PP    0.0 mb
				Ozone            75.4%  PP    1.8 mb
				Krypton          20.1%  PP    0.5 mb
				Xenon             3.0%  PP    0.1 mb


Planet 6	
   Distance from primary:	2.127	AU
   Mass:			1.126	Earth masses
   Equatorial radius:		6656.4	km
   Density:			5.449	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		1.03	Earth gees
   Surface pressure:		1.261	Earth atmospheres
   Surface temperature:		-97.96	degrees Celcius
   Normal daytime temperature:	-95.64	degrees Celcius
   Normal night temperature:	-100.43	degrees Celcius
   Maximum temperature:   	-80.43	degrees Celcius
   Minimum temperature:   	-116.82	degrees Celcius
   Escape Velocity:		11.62	km/sec
   Molecular weight retained:	5.88 and above
   Surface acceleration:	1013.63	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.748
   Length of year:		1082.51	days
   Length of day:		15.06	hours
   Boiling point of water:	106.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 85
				Chlorine     melts at -101  boils at -30
   gasses in atmosphere:
				Oxygen            4.6%  PP   57.5 mb
				Nitrogen         95.4%  PP 1202.9 mb


Planet 7	*gas giant*
   Distance from primary:	2.712	AU
   Mass:			26.399	Earth masses
   Equatorial radius:		29359.0	km
   Density:			1.489	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		26.78	km/sec
   Molecular weight retained:	1.11 and above
   Surface acceleration:	1221.38	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.499
   Length of year:		1557.84	days
   Length of day:		11.69	hours


Planet 8	
   Distance from primary:	4.253	AU
   Mass:			0.884	Earth masses
   Equatorial radius:		6152.8	km
   Density:			5.418	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.827	Earth atmospheres
   Surface temperature:		-149.85	degrees Celcius
   Normal daytime temperature:	-147.76	degrees Celcius
   Normal night temperature:	-152.05	degrees Celcius
   Maximum temperature:   	-131.39	degrees Celcius
   Minimum temperature:   	-170.04	degrees Celcius
   Escape Velocity:		10.71	km/sec
   Molecular weight retained:	6.92 and above
   Surface acceleration:	931.69	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.739
   Length of year:		3060.28	days
   Length of day:		15.70	hours
   Boiling point of water:	94.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -114
   gasses in atmosphere:
				Oxygen           13.3%  PP  110.1 mb
				Nitrogen         86.7%  PP  716.8 mb


Planet 9	*gas giant*
   Distance from primary:	5.742	AU
   Mass:			539.588	Earth masses
   Equatorial radius:		75354.7	km
   Density:			1.799	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		75.57	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3789.50	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.550
   Length of year:		4796.30	days
   Length of day:		6.64	hours


Planet 10	*gas giant*
   Distance from primary:	14.216	AU
   Mass:			287.217	Earth masses
   Equatorial radius:		67615.8	km
   Density:			1.326	grams/cc
   Eccentricity of orbit:	0.174
   Escape Velocity:		58.21	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2505.27	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.511
   Length of year:		18692.13	days
   Length of day:		8.17	hours


Planet 11	*gas giant*
   Distance from primary:	26.256	AU
   Mass:			30.743	Earth masses
   Equatorial radius:		37085.0	km
   Density:			0.860	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		25.71	km/sec
   Molecular weight retained:	1.20 and above
   Surface acceleration:	891.42	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.487
   Length of year:		46933.12	days
   Length of day:		13.69	hours


Planet 12	*gas giant*
   Distance from primary:	43.288	AU
   Mass:			1.128	Earth masses
   Equatorial radius:		14745.3	km
   Density:			0.502	grams/cc
   Eccentricity of orbit:	0.159
   Escape Velocity:		7.81	km/sec
   Molecular weight retained:	13.01 and above
   Surface acceleration:	206.94	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.456
   Length of year:		99354.75	days
   Length of day:		28.41	hours


