                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950480ea
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6205 K
Stellar class: F8
Age: 5.496 billion years  (1.532 billion left on main sequence)
Habitable ecosphere radius: 1.249 AU

Planets present at:
1	  0.313 AU	no atmosphere
2	  0.407 AU	no atmosphere
3	  0.640 AU	no atmosphere
4	  1.034 AU	greenhouse
5	  2.056 AU	gas giant
6	  3.760 AU	gas giant
7	  6.024 AU	no atmosphere
8	  8.951 AU	gas giant
9	 19.245 AU	gas giant
10	 29.085 AU	no atmosphere
11	 50.500 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.313	AU
   Mass:			0.175	Earth masses
   Equatorial radius:		3611.3	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.119
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		272.58	degrees Celcius
   Normal daytime temperature:	493.04	degrees Celcius
   Normal night temperature:	-163.04	degrees Celcius
   Maximum temperature:   	496.75	degrees Celcius
   Minimum temperature:   	-176.71	degrees Celcius
   Escape Velocity:		6.22	km/sec
   Molecular weight retained:	20.53 and above
   Surface acceleration:	535.32	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.079
   Length of year:		61.08	days
   Length of day:		1154.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.407	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		1968.8	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.160
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		208.05	degrees Celcius
   Normal daytime temperature:	415.46	degrees Celcius
   Normal night temperature:	-185.64	degrees Celcius
   Maximum temperature:   	418.97	degrees Celcius
   Minimum temperature:   	-197.18	degrees Celcius
   Escape Velocity:		3.38	km/sec
   Molecular weight retained:	69.62 and above
   Surface acceleration:	289.59	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.057
   Length of year:		90.65	days
   Length of day:		1576.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.640	AU
   Mass:			0.157	Earth masses
   Equatorial radius:		3485.0	km
   Density:			5.300	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		109.30	degrees Celcius
   Maximum temperature:   	297.71	degrees Celcius
   Minimum temperature:   	-224.06	degrees Celcius
   Escape Velocity:		6.00	km/sec
   Molecular weight retained:	22.06 and above
   Surface acceleration:	516.21	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.070
   Length of year:		178.71	days
   Length of day:		4289.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.034	AU
   Mass:			2.937	Earth masses
   Equatorial radius:		9060.3	km
   Density:			5.634	grams/cc
   Eccentricity of orbit:	0.162
   Surface gravity:		1.45	Earth gees
   Surface pressure:		808.116	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		659.86	degrees Celcius
   Maximum temperature:   	660.49	degrees Celcius
   Minimum temperature:   	654.95	degrees Celcius
   Escape Velocity:		16.08	km/sec
   Molecular weight retained:	3.07 and above
   Surface acceleration:	1426.73	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.453
   Length of year:		366.72	days
   Length of day:		13.02	hours
   Boiling point of water:	464.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1606
				Cesium       melts at 28    boils at 1661
				Gallium      melts at 30    boils at 5020
				Rubidium     melts at 39    boils at 1628
				Potassium    melts at 63    boils at 1781
				Sodium       melts at 98    boils at 2011
				Indium       melts at 157   boils at 4381
				Lithium      melts at 181   boils at 2931
				Selenium     melts at 217   boils at 1622
				Tin          melts at 232   boils at 5455
				Polonium     melts at 254   boils at 2170
				Bismuth      melts at 271   boils at 3360
				Thallium     melts at 304   boils at 3149
				Cadmium      melts at 321   boils at 1780
				Lead         melts at 328   boils at 3730
				Zinc         melts at 420   boils at 2061
				Tellurium    melts at 450   boils at 2225
				Antimony     melts at 631   boils at 3406
				Neptunium    melts at 640   boils at 7985
				Plutonium    melts at 641   boils at 6656
				Magnesium    melts at 649   boils at 2452
   gasses in atmosphere:
				Sulfur            0.1%  PP 1071.1 mb
				Nitrogen          0.6%  PP 4726.1 mb
				Helium           99.3%  PP 802289.3 mb


Planet 5	*gas giant*
   Distance from primary:	2.056	AU
   Mass:			10.988	Earth masses
   Equatorial radius:		22218.7	km
   Density:			1.429	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		19.86	km/sec
   Molecular weight retained:	2.01 and above
   Surface acceleration:	887.59	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.505
   Length of year:		1028.62	days
   Length of day:		13.72	hours


Planet 6	*gas giant*
   Distance from primary:	3.760	AU
   Mass:			368.991	Earth masses
   Equatorial radius:		65115.4	km
   Density:			1.907	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		67.23	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3470.47	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.516
   Length of year:		2543.06	days
   Length of day:		6.94	hours


Planet 7	
   Distance from primary:	6.024	AU
   Mass:			0.249	Earth masses
   Equatorial radius:		5421.1	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.080
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.044	Earth atmospheres
   Surface temperature:		-152.76	degrees Celcius
   Normal daytime temperature:	-142.80	degrees Celcius
   Normal night temperature:	-163.03	degrees Celcius
   Maximum temperature:   	-120.79	degrees Celcius
   Minimum temperature:   	-186.49	degrees Celcius
   Escape Velocity:		6.05	km/sec
   Molecular weight retained:	21.65 and above
   Surface acceleration:	338.11	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.283
   Length of year:		5158.31	days
   Length of day:		26.06	hours
   Boiling point of water:	30.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	26.06
   liquids at surface:
				Ozone        melts at -193  boils at -142
   gasses in atmosphere:
				Argon             5.4%  PP    2.4 mb
				Krypton          94.6%  PP   41.6 mb


Planet 8	*gas giant*
   Distance from primary:	8.951	AU
   Mass:			354.593	Earth masses
   Equatorial radius:		69187.5	km
   Density:			1.528	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		63.93	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2954.03	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.496
   Length of year:		9339.24	days
   Length of day:		7.52	hours


Planet 9	*gas giant*
   Distance from primary:	19.245	AU
   Mass:			318.191	Earth masses
   Equatorial radius:		71451.6	km
   Density:			1.245	grams/cc
   Eccentricity of orbit:	0.125
   Escape Velocity:		59.60	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2485.44	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.521
   Length of year:		29445.74	days
   Length of day:		8.20	hours


Planet 10	
   Distance from primary:	29.085	AU
   Mass:			0.403	Earth masses
   Equatorial radius:		6346.4	km
   Density:			2.249	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-216.45	degrees Celcius
   Normal daytime temperature:	-210.42	degrees Celcius
   Normal night temperature:	-222.44	degrees Celcius
   Maximum temperature:   	-194.66	degrees Celcius
   Minimum temperature:   	-239.09	degrees Celcius
   Escape Velocity:		7.12	km/sec
   Molecular weight retained:	15.68 and above
   Surface acceleration:	398.91	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.144
   Length of year:		54729.73	days
   Length of day:		24.00	hours
   Boiling point of water:	-35.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   liquids at surface:
				Fluorine     melts at -220  boils at -216
				Oxygen       melts at -218  boils at -212
   gasses in atmosphere:
				Neon             100.0%  PP    0.4 mb


Planet 11	*gas giant*
   Distance from primary:	50.500	AU
   Mass:			0.252	Earth masses
   Equatorial radius:		9648.2	km
   Density:			0.401	grams/cc
   Eccentricity of orbit:	0.178
   Escape Velocity:		4.57	km/sec
   Molecular weight retained:	38.09 and above
   Surface acceleration:	108.01	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.538
   Length of year:		125215.33	days
   Length of day:		39.33	hours


