                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504822f
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6294 K
Stellar class: F8
Age: 1.969 billion years  (5.016 billion left on main sequence)
Habitable ecosphere radius: 1.254 AU

Planets present at:
1	  0.447 AU	no atmosphere
2	  0.588 AU	no atmosphere
3	  1.014 AU	no atmosphere
4	  1.139 AU	greenhouse
5	  1.328 AU	no atmosphere
6	  2.297 AU	gas giant
7	  4.521 AU	cold
8	  6.782 AU	gas giant
9	 11.419 AU	gas giant
10	 19.099 AU	no atmosphere
11	 29.497 AU	no atmosphere
12	 47.767 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.447	AU
   Mass:			0.462	Earth masses
   Equatorial radius:		4972.6	km
   Density:			5.357	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		183.71	degrees Celcius
   Normal daytime temperature:	385.99	degrees Celcius
   Normal night temperature:	-194.11	degrees Celcius
   Maximum temperature:   	389.49	degrees Celcius
   Minimum temperature:   	-205.07	degrees Celcius
   Escape Velocity:		8.60	km/sec
   Molecular weight retained:	10.72 and above
   Surface acceleration:	744.50	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.084
   Length of year:		104.24	days
   Length of day:		1880.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.588	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		4011.0	km
   Density:			5.318	grams/cc
   Eccentricity of orbit:	0.098
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.63	degrees Celcius
   Maximum temperature:   	316.95	degrees Celcius
   Minimum temperature:   	-222.00	degrees Celcius
   Escape Velocity:		6.92	km/sec
   Molecular weight retained:	16.60 and above
   Surface acceleration:	596.12	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.090
   Length of year:		157.13	days
   Length of day:		3771.17	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.014	AU
   Mass:			0.090	Earth masses
   Equatorial radius:		2891.6	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		32.07	degrees Celcius
   Normal daytime temperature:	69.61	degrees Celcius
   Normal night temperature:	-5.87	degrees Celcius
   Maximum temperature:   	98.37	degrees Celcius
   Minimum temperature:   	-35.09	degrees Celcius
   Escape Velocity:		4.97	km/sec
   Molecular weight retained:	32.15 and above
   Surface acceleration:	426.95	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.062
   Length of year:		355.80	days
   Length of day:		28.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 4	
   Distance from primary:	1.139	AU
   Mass:			1.789	Earth masses
   Equatorial radius:		7731.8	km
   Density:			5.523	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		1.22	Earth gees
   Surface pressure:		244.812	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		458.56	degrees Celcius
   Maximum temperature:   	461.22	degrees Celcius
   Minimum temperature:   	453.91	degrees Celcius
   Escape Velocity:		13.59	km/sec
   Molecular weight retained:	4.30 and above
   Surface acceleration:	1193.50	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.435
   Length of year:		423.73	days
   Length of day:		13.98	hours
   Boiling point of water:	355.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1327
				Cesium       melts at 28    boils at 1374
				Gallium      melts at 30    boils at 4234
				Rubidium     melts at 39    boils at 1345
				Potassium    melts at 63    boils at 1476
				Sodium       melts at 98    boils at 1671
				Indium       melts at 157   boils at 3690
				Lithium      melts at 181   boils at 2455
				Selenium     melts at 217   boils at 1340
				Tin          melts at 232   boils at 4604
				Polonium     melts at 254   boils at 1807
				Bismuth      melts at 271   boils at 2821
				Thallium     melts at 304   boils at 2640
				Cadmium      melts at 321   boils at 1475
				Lead         melts at 328   boils at 3136
				Zinc         melts at 420   boils at 1714
				Tellurium    melts at 450   boils at 1854
   gasses in atmosphere:
				Sulfur           17.9%  PP 43848.1 mb
				Nitrogen         81.5%  PP 199629.6 mb
				Phosphorus        0.4%  PP  878.2 mb


Planet 5	
   Distance from primary:	1.328	AU
   Mass:			0.031	Earth masses
   Equatorial radius:		2037.5	km
   Density:			5.264	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-7.15	degrees Celcius
   Normal daytime temperature:	27.61	degrees Celcius
   Normal night temperature:	-42.15	degrees Celcius
   Maximum temperature:   	54.15	degrees Celcius
   Minimum temperature:   	-68.98	degrees Celcius
   Escape Velocity:		3.50	km/sec
   Molecular weight retained:	64.98 and above
   Surface acceleration:	299.77	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.072
   Length of year:		533.54	days
   Length of day:		30.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	*gas giant*
   Distance from primary:	2.297	AU
   Mass:			59.079	Earth masses
   Equatorial radius:		36615.3	km
   Density:			1.717	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		35.87	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	1757.31	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.535
   Length of year:		1213.83	days
   Length of day:		9.75	hours


Planet 7	
   Distance from primary:	4.521	AU
   Mass:			0.342	Earth masses
   Equatorial radius:		4507.3	km
   Density:			5.337	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.113	Earth atmospheres
   Surface temperature:		-140.14	degrees Celcius
   Normal daytime temperature:	-134.03	degrees Celcius
   Normal night temperature:	-146.49	degrees Celcius
   Maximum temperature:   	-114.06	degrees Celcius
   Minimum temperature:   	-168.12	degrees Celcius
   Escape Velocity:		7.78	km/sec
   Molecular weight retained:	13.10 and above
   Surface acceleration:	672.29	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.492
   Length of year:		3351.88	days
   Length of day:		18.48	hours
   Boiling point of water:	48.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	70.55
   liquids at surface:
				Ozone        melts at -193  boils at -134
   gasses in atmosphere:
				Oxygen           75.8%  PP   85.8 mb
				Nitrogen         24.2%  PP   27.4 mb


Planet 8	*gas giant*
   Distance from primary:	6.782	AU
   Mass:			32.305	Earth masses
   Equatorial radius:		33603.1	km
   Density:			1.215	grams/cc
   Eccentricity of orbit:	0.248
   Escape Velocity:		27.69	km/sec
   Molecular weight retained:	1.04 and above
   Surface acceleration:	1140.91	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.490
   Length of year:		6157.81	days
   Length of day:		12.10	hours


Planet 9	*gas giant*
   Distance from primary:	11.419	AU
   Mass:			1182.035	Earth masses
   Equatorial radius:		100279.9	km
   Density:			1.673	grams/cc
   Eccentricity of orbit:	0.133
   Escape Velocity:		96.96	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4687.51	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.527
   Length of year:		13431.69	days
   Length of day:		5.97	hours


Planet 10	
   Distance from primary:	19.099	AU
   Mass:			0.195	Earth masses
   Equatorial radius:		5003.8	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-204.04	degrees Celcius
   Normal daytime temperature:	-195.80	degrees Celcius
   Normal night temperature:	-212.25	degrees Celcius
   Maximum temperature:   	-179.69	degrees Celcius
   Minimum temperature:   	-229.32	degrees Celcius
   Escape Velocity:		5.58	km/sec
   Molecular weight retained:	25.50 and above
   Surface acceleration:	311.11	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.151
   Length of year:		29099.74	days
   Length of day:		27.17	hours
   Boiling point of water:	-54.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 11	
   Distance from primary:	29.497	AU
   Mass:			0.272	Earth masses
   Equatorial radius:		5580.6	km
   Density:			2.234	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.58	degrees Celcius
   Normal daytime temperature:	-211.29	degrees Celcius
   Normal night temperature:	-223.82	degrees Celcius
   Maximum temperature:   	-195.01	degrees Celcius
   Minimum temperature:   	-240.86	degrees Celcius
   Escape Velocity:		6.24	km/sec
   Molecular weight retained:	20.41 and above
   Surface acceleration:	348.49	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.160
   Length of year:		55850.42	days
   Length of day:		25.67	hours
   Boiling point of water:	-45.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09
   liquids at surface:
				Fluorine     melts at -220  boils at -216
				Oxygen       melts at -218  boils at -213


Planet 12	*gas giant*
   Distance from primary:	47.767	AU
   Mass:			0.473	Earth masses
   Equatorial radius:		11537.1	km
   Density:			0.440	grams/cc
   Eccentricity of orbit:	0.100
   Escape Velocity:		5.72	km/sec
   Molecular weight retained:	24.26 and above
   Surface acceleration:	141.83	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.521
   Length of year:		115095.89	days
   Length of day:		34.32	hours


