                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048738
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6165 K
Stellar class: F8
Age: 3.500 billion years  (3.318 billion left on main sequence)
Habitable ecosphere radius: 1.273 AU

Planets present at:
1	  0.467 AU	no atmosphere
2	  0.937 AU	no atmosphere
3	  1.055 AU	greenhouse
4	  1.512 AU	gas giant
5	  3.153 AU	gas giant
6	  7.145 AU	gas giant
7	  8.035 AU	cold
8	  8.670 AU	no atmosphere
9	 11.210 AU	gas giant
10	 23.562 AU	gas giant
11	 47.810 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.467	AU
   Mass:			0.718	Earth masses
   Equatorial radius:		5747.8	km
   Density:			5.396	grams/cc
   Eccentricity of orbit:	0.220
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		178.34	degrees Celcius
   Normal daytime temperature:	379.04	degrees Celcius
   Normal night temperature:	-192.55	degrees Celcius
   Maximum temperature:   	382.78	degrees Celcius
   Minimum temperature:   	-204.28	degrees Celcius
   Escape Velocity:		9.98	km/sec
   Molecular weight retained:	7.97 and above
   Surface acceleration:	866.74	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.074
   Length of year:		111.02	days
   Length of day:		1702.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 2	
   Distance from primary:	0.937	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2235.2	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		45.61	degrees Celcius
   Maximum temperature:   	217.14	degrees Celcius
   Minimum temperature:   	-231.60	degrees Celcius
   Escape Velocity:		3.84	km/sec
   Molecular weight retained:	53.96 and above
   Surface acceleration:	329.08	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.076
   Length of year:		315.08	days
   Length of day:		7561.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 3	
   Distance from primary:	1.055	AU
   Mass:			0.505	Earth masses
   Equatorial radius:		5120.4	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.78	Earth gees
   Surface pressure:		21.766	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		77.76	degrees Celcius
   Maximum temperature:   	85.44	degrees Celcius
   Minimum temperature:   	69.69	degrees Celcius
   Escape Velocity:		8.87	km/sec
   Molecular weight retained:	10.10 and above
   Surface acceleration:	767.62	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.582
   Length of year:		376.63	days
   Length of day:		18.44	hours
   Boiling point of water:	209.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 182
				Mercury      melts at -39   boils at 542
				Water        melts at 0     boils at 210
				Francium     melts at 27    boils at 957
				Cesium       melts at 28    boils at 993
				Gallium      melts at 30    boils at 3191
				Rubidium     melts at 39    boils at 971
				Phosphorus   melts at 44    boils at 444
				Potassium    melts at 63    boils at 1071
   gasses in atmosphere:
				Nitrogen         99.7%  PP 21695.6 mb
				CarbonDioxide     0.1%  PP   24.4 mb
				Ozone             0.1%  PP   24.3 mb


Planet 4	*gas giant*
   Distance from primary:	1.512	AU
   Mass:			7.833	Earth masses
   Equatorial radius:		19590.4	km
   Density:			1.487	grams/cc
   Eccentricity of orbit:	0.089
   Escape Velocity:		17.86	km/sec
   Molecular weight retained:	2.49 and above
   Surface acceleration:	813.95	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.517
   Length of year:		646.35	days
   Length of day:		14.33	hours


Planet 5	*gas giant*
   Distance from primary:	3.153	AU
   Mass:			304.768	Earth masses
   Equatorial radius:		60588.3	km
   Density:			1.955	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		63.34	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	3310.79	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.511
   Length of year:		1944.89	days
   Length of day:		7.10	hours


Planet 6	*gas giant*
   Distance from primary:	7.145	AU
   Mass:			2.708	Earth masses
   Equatorial radius:		16357.0	km
   Density:			0.883	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		11.49	km/sec
   Molecular weight retained:	6.01 and above
   Surface acceleration:	403.66	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.517
   Length of year:		6637.31	days
   Length of day:		20.34	hours


Planet 7	
   Distance from primary:	8.035	AU
   Mass:			0.422	Earth masses
   Equatorial radius:		6443.9	km
   Density:			2.251	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.107	Earth atmospheres
   Surface temperature:		-163.48	degrees Celcius
   Normal daytime temperature:	-157.04	degrees Celcius
   Normal night temperature:	-170.22	degrees Celcius
   Maximum temperature:   	-138.17	degrees Celcius
   Minimum temperature:   	-190.73	degrees Celcius
   Escape Velocity:		7.23	km/sec
   Molecular weight retained:	15.19 and above
   Surface acceleration:	405.40	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.278
   Length of year:		7914.46	days
   Length of day:		23.80	hours
   Boiling point of water:	47.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	26.37
   liquids at surface:
				Ozone        melts at -193  boils at -135
   gasses in atmosphere:
				Oxygen           99.8%  PP  106.5 mb
				Methane           0.1%  PP    0.1 mb


Planet 8	
   Distance from primary:	8.670	AU
   Mass:			0.333	Earth masses
   Equatorial radius:		5961.8	km
   Density:			2.241	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.079	Earth atmospheres
   Surface temperature:		-168.43	degrees Celcius
   Normal daytime temperature:	-161.39	degrees Celcius
   Normal night temperature:	-175.77	degrees Celcius
   Maximum temperature:   	-145.59	degrees Celcius
   Minimum temperature:   	-192.92	degrees Celcius
   Escape Velocity:		6.67	km/sec
   Molecular weight retained:	17.83 and above
   Surface acceleration:	373.47	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.288
   Length of year:		8872.12	days
   Length of day:		24.80	hours
   Boiling point of water:	41.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	28.92
   liquids at surface:
				Ozone        melts at -193  boils at -137
   gasses in atmosphere:
				Fluorine          5.6%  PP    4.4 mb
				Argon            26.6%  PP   21.0 mb
				Neon             67.8%  PP   53.5 mb


Planet 9	*gas giant*
   Distance from primary:	11.210	AU
   Mass:			443.945	Earth masses
   Equatorial radius:		75152.3	km
   Density:			1.492	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		68.64	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3134.62	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.490
   Length of year:		13035.70	days
   Length of day:		7.30	hours


Planet 10	*gas giant*
   Distance from primary:	23.562	AU
   Mass:			102.870	Earth masses
   Equatorial radius:		52192.2	km
   Density:			1.032	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		39.65	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	1505.98	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.494
   Length of year:		39740.38	days
   Length of day:		10.53	hours


Planet 11	*gas giant*
   Distance from primary:	47.810	AU
   Mass:			0.361	Earth masses
   Equatorial radius:		10650.7	km
   Density:			0.427	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		5.20	km/sec
   Molecular weight retained:	29.33 and above
   Surface acceleration:	127.05	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.541
   Length of year:		114882.33	days
   Length of day:		36.26	hours


