                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b04
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.50
Stellar temperature: 6045 K
Stellar class: F9
Age: 1.068 billion years  (6.166 billion left on main sequence)
Habitable ecosphere radius: 1.226 AU

Planets present at:
1	  0.409 AU	no atmosphere
2	  0.709 AU	greenhouse
3	  1.424 AU	gas giant
4	  2.285 AU	cold
5	  3.541 AU	cold
6	  4.154 AU	gas giant
7	  5.855 AU	gas giant
8	  9.265 AU	gas giant
9	 14.436 AU	gas giant
10	 21.035 AU	gas giant
11	 31.228 AU	gas giant
12	 42.462 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.409	AU
   Mass:			0.293	Earth masses
   Equatorial radius:		4282.2	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.157
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		202.34	degrees Celcius
   Normal daytime temperature:	408.48	degrees Celcius
   Normal night temperature:	-187.04	degrees Celcius
   Maximum temperature:   	412.03	degrees Celcius
   Minimum temperature:   	-198.60	degrees Celcius
   Escape Velocity:		7.39	km/sec
   Molecular weight retained:	14.54 and above
   Surface acceleration:	637.65	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.059
   Length of year:		91.68	days
   Length of day:		1602.09	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.709	AU
   Mass:			0.680	Earth masses
   Equatorial radius:		5646.6	km
   Density:			5.390	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.87	Earth gees
   Surface pressure:		35.409	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		262.74	degrees Celcius
   Maximum temperature:   	269.71	degrees Celcius
   Minimum temperature:   	254.87	degrees Celcius
   Escape Velocity:		9.80	km/sec
   Molecular weight retained:	8.26 and above
   Surface acceleration:	850.63	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.505
   Length of year:		209.12	days
   Length of day:		19.44	hours
   Boiling point of water:	233.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 582
				Francium     melts at 27    boils at 1017
				Cesium       melts at 28    boils at 1055
				Gallium      melts at 30    boils at 3360
				Rubidium     melts at 39    boils at 1032
				Phosphorus   melts at 44    boils at 479
				Potassium    melts at 63    boils at 1137
				Sodium       melts at 98    boils at 1294
				Sulfur       melts at 113   boils at 702
				Indium       melts at 157   boils at 2921
				Lithium      melts at 181   boils at 1926
				Selenium     melts at 217   boils at 1027
				Tin          melts at 232   boils at 3659
				Polonium     melts at 254   boils at 1404
   gasses in atmosphere:
				Nitrogen         99.7%  PP 35290.2 mb
				CarbonDioxide     0.1%  PP   24.5 mb
				Ozone             0.1%  PP   24.6 mb
				Ethanol           0.1%  PP   24.8 mb


Planet 3	*gas giant*
   Distance from primary:	1.424	AU
   Mass:			12.615	Earth masses
   Equatorial radius:		22469.2	km
   Density:			1.587	grams/cc
   Eccentricity of orbit:	0.137
   Escape Velocity:		21.16	km/sec
   Molecular weight retained:	1.77 and above
   Surface acceleration:	996.43	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.490
   Length of year:		595.42	days
   Length of day:		12.95	hours


Planet 4	
   Distance from primary:	2.285	AU
   Mass:			0.424	Earth masses
   Equatorial radius:		4836.0	km
   Density:			5.351	grams/cc
   Eccentricity of orbit:	0.222
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.140	Earth atmospheres
   Surface temperature:		-86.74	degrees Celcius
   Normal daytime temperature:	-79.06	degrees Celcius
   Normal night temperature:	-94.72	degrees Celcius
   Maximum temperature:   	-51.68	degrees Celcius
   Minimum temperature:   	-123.94	degrees Celcius
   Escape Velocity:		8.36	km/sec
   Molecular weight retained:	11.35 and above
   Surface acceleration:	723.23	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.483
   Length of year:		1209.99	days
   Length of day:		17.82	hours
   Boiling point of water:	52.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	61.08
   liquids at surface:
				Ethanol      melts at -114  boils at 34
				Chlorine     melts at -101  boils at -64
   gasses in atmosphere:
				Oxygen           79.9%  PP  111.7 mb
				Nitrogen         20.0%  PP   28.0 mb


Planet 5	
   Distance from primary:	3.541	AU
   Mass:			0.894	Earth masses
   Equatorial radius:		6173.2	km
   Density:			5.419	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.810	Earth atmospheres
   Surface temperature:		-133.22	degrees Celcius
   Normal daytime temperature:	-130.83	degrees Celcius
   Normal night temperature:	-135.74	degrees Celcius
   Maximum temperature:   	-113.37	degrees Celcius
   Minimum temperature:   	-154.81	degrees Celcius
   Escape Velocity:		10.74	km/sec
   Molecular weight retained:	6.88 and above
   Surface acceleration:	934.99	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.688
   Length of year:		2333.55	days
   Length of day:		15.67	hours
   Boiling point of water:	94.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -114
   gasses in atmosphere:
				Oxygen           55.3%  PP  447.4 mb
				Nitrogen         44.7%  PP  362.0 mb


Planet 6	*gas giant*
   Distance from primary:	4.154	AU
   Mass:			27.987	Earth masses
   Equatorial radius:		30992.6	km
   Density:			1.341	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		26.84	km/sec
   Molecular weight retained:	1.10 and above
   Surface acceleration:	1161.93	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.470
   Length of year:		2964.83	days
   Length of day:		11.99	hours


Planet 7	*gas giant*
   Distance from primary:	5.855	AU
   Mass:			25.192	Earth masses
   Equatorial radius:		30928.0	km
   Density:			1.215	grams/cc
   Eccentricity of orbit:	0.019
   Escape Velocity:		25.49	km/sec
   Molecular weight retained:	1.22 and above
   Surface acceleration:	1050.25	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.451
   Length of year:		4961.42	days
   Length of day:		12.61	hours


Planet 8	*gas giant*
   Distance from primary:	9.265	AU
   Mass:			185.437	Earth masses
   Equatorial radius:		57520.4	km
   Density:			1.390	grams/cc
   Eccentricity of orbit:	0.098
   Escape Velocity:		50.71	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2235.08	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.505
   Length of year:		9874.90	days
   Length of day:		8.65	hours


Planet 9	*gas giant*
   Distance from primary:	14.436	AU
   Mass:			13.890	Earth masses
   Equatorial radius:		28028.8	km
   Density:			0.900	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		19.88	km/sec
   Molecular weight retained:	2.01 and above
   Surface acceleration:	705.08	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.468
   Length of year:		19210.67	days
   Length of day:		15.39	hours


Planet 10	*gas giant*
   Distance from primary:	21.035	AU
   Mass:			121.743	Earth masses
   Equatorial radius:		54474.5	km
   Density:			1.075	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		42.22	km/sec
   Molecular weight retained:	0.45 and above
   Surface acceleration:	1636.06	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.541
   Length of year:		33783.64	days
   Length of day:		10.10	hours


Planet 11	*gas giant*
   Distance from primary:	31.228	AU
   Mass:			2.795	Earth masses
   Equatorial radius:		18726.3	km
   Density:			0.607	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		10.91	km/sec
   Molecular weight retained:	6.67 and above
   Surface acceleration:	317.89	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.462
   Length of year:		61120.92	days
   Length of day:		22.92	hours


Planet 12	
   Distance from primary:	42.462	AU
   Mass:			0.073	Earth masses
   Equatorial radius:		3614.7	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.61	degrees Celcius
   Normal daytime temperature:	-221.33	degrees Celcius
   Normal night temperature:	-233.78	degrees Celcius
   Maximum temperature:   	-208.53	degrees Celcius
   Minimum temperature:   	-246.96	degrees Celcius
   Escape Velocity:		4.01	km/sec
   Molecular weight retained:	49.27 and above
   Surface acceleration:	222.85	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.158
   Length of year:		96909.78	days
   Length of day:		32.10	hours
   Boiling point of water:	-69.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


