                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950480b1
Stellar mass: 1.10 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6362 K
Stellar class: F7
Age: 3.157 billion years  (3.879 billion left on main sequence)
Habitable ecosphere radius: 1.248 AU

Planets present at:
1	  0.315 AU	no atmosphere
2	  0.366 AU	no atmosphere
3	  0.469 AU	no atmosphere
4	  0.720 AU	greenhouse
5	  1.598 AU	gas giant
6	  2.534 AU	cold
7	  3.602 AU	cold
8	  4.824 AU	gas giant
9	  6.703 AU	gas giant
10	 15.683 AU	gas giant
11	 36.527 AU	gas giant
12	 49.702 AU	no atmosphere



Planet 1	
   Distance from primary:	0.315	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1623.1	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		271.67	degrees Celcius
   Normal daytime temperature:	493.01	degrees Celcius
   Normal night temperature:	-173.01	degrees Celcius
   Maximum temperature:   	496.14	degrees Celcius
   Minimum temperature:   	-184.23	degrees Celcius
   Escape Velocity:		2.78	km/sec
   Molecular weight retained:	102.54 and above
   Surface acceleration:	238.49	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.074
   Length of year:		61.57	days
   Length of day:		1477.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.366	AU
   Mass:			0.168	Earth masses
   Equatorial radius:		3559.0	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.45	degrees Celcius
   Maximum temperature:   	447.71	degrees Celcius
   Minimum temperature:   	-196.39	degrees Celcius
   Escape Velocity:		6.13	km/sec
   Molecular weight retained:	21.15 and above
   Surface acceleration:	527.40	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.076
   Length of year:		77.38	days
   Length of day:		1857.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.469	AU
   Mass:			0.025	Earth masses
   Equatorial radius:		1883.5	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		174.32	degrees Celcius
   Maximum temperature:   	378.29	degrees Celcius
   Minimum temperature:   	-211.57	degrees Celcius
   Escape Velocity:		3.23	km/sec
   Molecular weight retained:	76.08 and above
   Surface acceleration:	276.98	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.065
   Length of year:		111.99	days
   Length of day:		2687.70	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.720	AU
   Mass:			1.083	Earth masses
   Equatorial radius:		6571.5	km
   Density:			5.443	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		1.02	Earth gees
   Surface pressure:		104.208	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		493.03	degrees Celcius
   Maximum temperature:   	497.35	degrees Celcius
   Minimum temperature:   	486.04	degrees Celcius
   Escape Velocity:		11.46	km/sec
   Molecular weight retained:	6.04 and above
   Surface acceleration:	999.71	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.531
   Length of year:		213.16	days
   Length of day:		21.32	hours
   Boiling point of water:	294.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1173
				Cesium       melts at 28    boils at 1216
				Gallium      melts at 30    boils at 3801
				Rubidium     melts at 39    boils at 1190
				Potassium    melts at 63    boils at 1308
				Sodium       melts at 98    boils at 1485
				Indium       melts at 157   boils at 3309
				Lithium      melts at 181   boils at 2193
				Selenium     melts at 217   boils at 1185
				Tin          melts at 232   boils at 4136
				Polonium     melts at 254   boils at 1607
				Bismuth      melts at 271   boils at 2524
				Thallium     melts at 304   boils at 2361
				Cadmium      melts at 321   boils at 1307
				Lead         melts at 328   boils at 2808
				Zinc         melts at 420   boils at 1523
				Tellurium    melts at 450   boils at 1650
   gasses in atmosphere:
				Sulfur           21.9%  PP 22822.6 mb
				Nitrogen         77.4%  PP 80696.4 mb
				Phosphorus        0.4%  PP  453.9 mb


Planet 5	*gas giant*
   Distance from primary:	1.598	AU
   Mass:			5.832	Earth masses
   Equatorial radius:		18087.6	km
   Density:			1.406	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		16.04	km/sec
   Molecular weight retained:	3.09 and above
   Surface acceleration:	710.87	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.499
   Length of year:		704.82	days
   Length of day:		15.33	hours


Planet 6	
   Distance from primary:	2.534	AU
   Mass:			0.416	Earth masses
   Equatorial radius:		4806.7	km
   Density:			5.350	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.163	Earth atmospheres
   Surface temperature:		-101.28	degrees Celcius
   Normal daytime temperature:	-94.58	degrees Celcius
   Normal night temperature:	-108.26	degrees Celcius
   Maximum temperature:   	-72.91	degrees Celcius
   Minimum temperature:   	-131.49	degrees Celcius
   Escape Velocity:		8.31	km/sec
   Molecular weight retained:	11.49 and above
   Surface acceleration:	718.66	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.562
   Length of year:		1407.73	days
   Length of day:		17.88	hours
   Boiling point of water:	55.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	73.28
   liquids at surface:
				Ethanol      melts at -114  boils at 37
   gasses in atmosphere:
				Oxygen           31.6%  PP   51.3 mb
				Nitrogen         68.3%  PP  111.0 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	
   Distance from primary:	3.602	AU
   Mass:			1.505	Earth masses
   Equatorial radius:		7312.8	km
   Density:			5.493	grams/cc
   Eccentricity of orbit:	0.183
   Surface gravity:		1.14	Earth gees
   Surface pressure:		1.672	Earth atmospheres
   Surface temperature:		-122.37	degrees Celcius
   Normal daytime temperature:	-120.70	degrees Celcius
   Normal night temperature:	-124.13	degrees Celcius
   Maximum temperature:   	-105.16	degrees Celcius
   Minimum temperature:   	-141.00	degrees Celcius
   Escape Velocity:		12.81	km/sec
   Molecular weight retained:	4.84 and above
   Surface acceleration:	1122.56	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.618
   Length of year:		2385.39	days
   Length of day:		14.30	hours
   Boiling point of water:	114.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	90.04
   liquids at surface:
				Ozone        melts at -193  boils at -106
   gasses in atmosphere:
				Oxygen            0.1%  PP    1.7 mb
				Nitrogen         99.9%  PP 1669.5 mb


Planet 8	*gas giant*
   Distance from primary:	4.824	AU
   Mass:			8.107	Earth masses
   Equatorial radius:		21832.3	km
   Density:			1.112	grams/cc
   Eccentricity of orbit:	0.183
   Escape Velocity:		17.21	km/sec
   Molecular weight retained:	2.68 and above
   Surface acceleration:	678.29	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.517
   Length of year:		3697.57	days
   Length of day:		15.69	hours


Planet 9	*gas giant*
   Distance from primary:	6.703	AU
   Mass:			186.825	Earth masses
   Equatorial radius:		56029.2	km
   Density:			1.516	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		51.57	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2373.26	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.530
   Length of year:		6053.97	days
   Length of day:		8.39	hours


Planet 10	*gas giant*
   Distance from primary:	15.683	AU
   Mass:			905.782	Earth masses
   Equatorial radius:		95310.8	km
   Density:			1.493	grams/cc
   Eccentricity of orbit:	0.230
   Escape Velocity:		87.06	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	3976.29	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.472
   Length of year:		21645.65	days
   Length of day:		6.48	hours


Planet 11	*gas giant*
   Distance from primary:	36.527	AU
   Mass:			2.636	Earth masses
   Equatorial radius:		18624.0	km
   Density:			0.582	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		10.63	km/sec
   Molecular weight retained:	7.03 and above
   Surface acceleration:	303.11	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.497
   Length of year:		77038.80	days
   Length of day:		23.48	hours


Planet 12	
   Distance from primary:	49.702	AU
   Mass:			0.042	Earth masses
   Equatorial radius:		2997.5	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.41	degrees Celcius
   Normal daytime temperature:	-224.02	degrees Celcius
   Normal night temperature:	-236.67	degrees Celcius
   Maximum temperature:   	-212.58	degrees Celcius
   Minimum temperature:   	-248.40	degrees Celcius
   Escape Velocity:		3.32	km/sec
   Molecular weight retained:	71.86 and above
   Surface acceleration:	184.27	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.137
   Length of year:		122276.69	days
   Length of day:		35.31	hours
   Boiling point of water:	-79.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


