                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950480b8
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6076 K
Stellar class: F9
Age: 3.153 billion years  (3.883 billion left on main sequence)
Habitable ecosphere radius: 1.248 AU

Planets present at:
1	  0.367 AU	no atmosphere
2	  0.600 AU	no atmosphere
3	  0.754 AU	no atmosphere
4	  1.188 AU	hot
5	  1.763 AU	high pressure
6	  3.042 AU	gas giant
7	  6.112 AU	gas giant
8	  9.036 AU	gas giant
9	 22.289 AU	gas giant
10	 30.502 AU	gas giant
11	 44.905 AU	no atmosphere



Planet 1	
   Distance from primary:	0.367	AU
   Mass:			0.092	Earth masses
   Equatorial radius:		2923.1	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		234.07	degrees Celcius
   Maximum temperature:   	450.80	degrees Celcius
   Minimum temperature:   	-195.59	degrees Celcius
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.46 and above
   Surface acceleration:	431.66	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.055
   Length of year:		77.46	days
   Length of day:		1859.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.600	AU
   Mass:			0.523	Earth masses
   Equatorial radius:		5179.5	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		122.21	degrees Celcius
   Maximum temperature:   	313.74	degrees Celcius
   Minimum temperature:   	-221.93	degrees Celcius
   Escape Velocity:		8.97	km/sec
   Molecular weight retained:	9.86 and above
   Surface acceleration:	776.87	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.067
   Length of year:		162.13	days
   Length of day:		3891.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.754	AU
   Mass:			0.327	Earth masses
   Equatorial radius:		4440.9	km
   Density:			5.334	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		79.44	degrees Celcius
   Normal daytime temperature:	142.35	degrees Celcius
   Normal night temperature:	14.54	degrees Celcius
   Maximum temperature:   	171.40	degrees Celcius
   Minimum temperature:   	-15.57	degrees Celcius
   Escape Velocity:		7.67	km/sec
   Molecular weight retained:	13.50 and above
   Surface acceleration:	662.05	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.067
   Length of year:		228.55	days
   Length of day:		45.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.188	AU
   Mass:			1.028	Earth masses
   Equatorial radius:		6460.8	km
   Density:			5.437	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		1.00	Earth gees
   Surface pressure:		1.111	Earth atmospheres
   Surface temperature:		34.95	degrees Celcius
   Normal daytime temperature:	39.41	degrees Celcius
   Normal night temperature:	30.20	degrees Celcius
   Maximum temperature:   	61.43	degrees Celcius
   Minimum temperature:   	6.96	degrees Celcius
   Escape Velocity:		11.26	km/sec
   Molecular weight retained:	6.26 and above
   Surface acceleration:	981.65	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.495
   Length of year:		451.65	days
   Length of day:		15.53	hours
   Boiling point of water:	102.9	degrees Celcius
   Hydrosphere percentage:	74.84
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.05
   liquids at surface:
				Ethanol      melts at -114  boils at 81
				Mercury      melts at -39   boils at 362
				Bromine      melts at -7    boils at 62
				Water        melts at 0     boils at 103
				Francium     melts at 27    boils at 684
				Cesium       melts at 28    boils at 713
				Gallium      melts at 30    boils at 2424
   gasses in atmosphere:
				Oxygen           22.7%  PP  251.7 mb
				Nitrogen         77.2%  PP  857.3 mb


Planet 5	
   Distance from primary:	1.763	AU
   Mass:			1.894	Earth masses
   Equatorial radius:		7874.9	km
   Density:			5.534	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		1.24	Earth gees
   Surface pressure:		3.245	Earth atmospheres
   Surface temperature:		-16.79	degrees Celcius
   Normal daytime temperature:	-14.82	degrees Celcius
   Normal night temperature:	-18.88	degrees Celcius
   Maximum temperature:   	-2.02	degrees Celcius
   Minimum temperature:   	-32.41	degrees Celcius
   Escape Velocity:		13.85	km/sec
   Molecular weight retained:	4.14 and above
   Surface acceleration:	1217.99	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.308
   Length of year:		816.91	days
   Length of day:		13.74	hours
   Boiling point of water:	135.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	6.45
   Ice cover percentage:	30.63
   liquids at surface:
				Ethanol      melts at -114  boils at 112
				Mercury      melts at -39   boils at 417
   gasses in atmosphere:
				Nitrogen         99.8%  PP 3240.0 mb


Planet 6	*gas giant*
   Distance from primary:	3.042	AU
   Mass:			304.857	Earth masses
   Equatorial radius:		60513.1	km
   Density:			1.963	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		63.39	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	3319.98	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.471
   Length of year:		1850.89	days
   Length of day:		7.09	hours


Planet 7	*gas giant*
   Distance from primary:	6.112	AU
   Mass:			3.928	Earth masses
   Equatorial radius:		18024.8	km
   Density:			0.957	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		13.18	km/sec
   Molecular weight retained:	4.57 and above
   Surface acceleration:	482.13	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.480
   Length of year:		5273.17	days
   Length of day:		18.61	hours


Planet 8	*gas giant*
   Distance from primary:	9.036	AU
   Mass:			818.452	Earth masses
   Equatorial radius:		88378.0	km
   Density:			1.692	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		85.94	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4178.73	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.513
   Length of year:		9468.16	days
   Length of day:		6.32	hours


Planet 9	*gas giant*
   Distance from primary:	22.289	AU
   Mass:			2.447	Earth masses
   Equatorial radius:		17488.2	km
   Density:			0.653	grams/cc
   Eccentricity of orbit:	0.209
   Escape Velocity:		10.56	km/sec
   Molecular weight retained:	7.11 and above
   Surface acceleration:	319.06	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.481
   Length of year:		36720.18	days
   Length of day:		22.88	hours


Planet 10	*gas giant*
   Distance from primary:	30.502	AU
   Mass:			26.289	Earth masses
   Equatorial radius:		35879.8	km
   Density:			0.812	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		24.17	km/sec
   Molecular weight retained:	1.36 and above
   Surface acceleration:	814.35	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.464
   Length of year:		58783.01	days
   Length of day:		14.32	hours


Planet 11	
   Distance from primary:	44.905	AU
   Mass:			0.276	Earth masses
   Equatorial radius:		5603.7	km
   Density:			2.235	grams/cc
   Eccentricity of orbit:	0.135
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.19	degrees Celcius
   Normal daytime temperature:	-223.11	degrees Celcius
   Normal night temperature:	-233.18	degrees Celcius
   Maximum temperature:   	-209.61	degrees Celcius
   Minimum temperature:   	-247.22	degrees Celcius
   Escape Velocity:		6.26	km/sec
   Molecular weight retained:	20.24 and above
   Surface acceleration:	350.00	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.162
   Length of year:		105008.09	days
   Length of day:		25.62	hours
   Boiling point of water:	-44.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10


