                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047fc5
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6369 K
Stellar class: F7
Age: 5.997 billion years  (1.071 billion left on main sequence)
Habitable ecosphere radius: 1.244 AU

Planets present at:
1	  0.399 AU	no atmosphere
2	  0.481 AU	no atmosphere
3	  0.772 AU	no atmosphere
4	  1.109 AU	greenhouse
5	  1.422 AU	
6	  1.848 AU	gas giant
7	  2.418 AU	no atmosphere
8	  3.198 AU	cold
9	  6.556 AU	gas giant
10	 19.058 AU	gas giant
11	 29.053 AU	no atmosphere
12	 40.327 AU	no atmosphere
13	 50.447 AU	no atmosphere



Planet 1	
   Distance from primary:	0.399	AU
   Mass:			0.265	Earth masses
   Equatorial radius:		4139.3	km
   Density:			5.323	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		211.73	degrees Celcius
   Maximum temperature:   	423.82	degrees Celcius
   Minimum temperature:   	-201.97	degrees Celcius
   Escape Velocity:		7.14	km/sec
   Molecular weight retained:	15.57 and above
   Surface acceleration:	615.73	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.059
   Length of year:		88.11	days
   Length of day:		2114.72	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.481	AU
   Mass:			0.091	Earth masses
   Equatorial radius:		2903.8	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		166.70	degrees Celcius
   Maximum temperature:   	368.94	degrees Celcius
   Minimum temperature:   	-213.21	degrees Celcius
   Escape Velocity:		4.99	km/sec
   Molecular weight retained:	31.88 and above
   Surface acceleration:	428.77	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.076
   Length of year:		116.40	days
   Length of day:		2793.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.772	AU
   Mass:			0.285	Earth masses
   Equatorial radius:		4242.8	km
   Density:			5.326	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		76.39	degrees Celcius
   Maximum temperature:   	256.24	degrees Celcius
   Minimum temperature:   	-227.98	degrees Celcius
   Escape Velocity:		7.32	km/sec
   Molecular weight retained:	14.81 and above
   Surface acceleration:	631.59	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.051
   Length of year:		236.75	days
   Length of day:		5682.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.109	AU
   Mass:			0.377	Earth masses
   Equatorial radius:		4653.4	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.71	Earth gees
   Surface pressure:		12.940	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		51.27	degrees Celcius
   Maximum temperature:   	60.83	degrees Celcius
   Minimum temperature:   	41.20	degrees Celcius
   Escape Velocity:		8.04	km/sec
   Molecular weight retained:	12.27 and above
   Surface acceleration:	694.88	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.591
   Length of year:		407.75	days
   Length of day:		20.16	hours
   Boiling point of water:	187.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 161
				Mercury      melts at -39   boils at 504
				Bromine      melts at -7    boils at 137
				Water        melts at 0     boils at 187
				Francium     melts at 27    boils at 898
				Cesium       melts at 28    boils at 933
				Gallium      melts at 30    boils at 3027
				Rubidium     melts at 39    boils at 912
				Phosphorus   melts at 44    boils at 410
   gasses in atmosphere:
				Nitrogen         99.3%  PP 12844.5 mb
				CarbonDioxide     0.3%  PP   36.7 mb
				Methane           0.1%  PP    8.2 mb
				Ammonia           0.1%  PP    9.7 mb
				Ozone             0.3%  PP   37.3 mb


Planet 5	
   Distance from primary:	1.422	AU
   Mass:			0.890	Earth masses
   Equatorial radius:		6164.3	km
   Density:			5.419	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.663	Earth atmospheres
   Surface temperature:		7.57	degrees Celcius
   Normal daytime temperature:	12.87	degrees Celcius
   Normal night temperature:	1.95	degrees Celcius
   Maximum temperature:   	36.48	degrees Celcius
   Minimum temperature:   	-23.02	degrees Celcius
   Escape Velocity:		10.73	km/sec
   Molecular weight retained:	6.90 and above
   Surface acceleration:	933.56	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.186
   Length of year:		592.30	days
   Length of day:		15.86	hours
   Boiling point of water:	89.0	degrees Celcius
   Hydrosphere percentage:	56.66
   Cloud cover percentage:	23.74
   Ice cover percentage:	4.07
   liquids at surface:
				Ethanol      melts at -114  boils at 68
				Mercury      melts at -39   boils at 338
				Bromine      melts at -7    boils at 50
				Water        melts at 0     boils at 89
   gasses in atmosphere:
				Oxygen           25.4%  PP  168.6 mb
				Nitrogen         74.4%  PP  493.1 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ozone             0.1%  PP    0.3 mb


Planet 6	*gas giant*
   Distance from primary:	1.848	AU
   Mass:			15.258	Earth masses
   Equatorial radius:		24242.2	km
   Density:			1.528	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		22.41	km/sec
   Molecular weight retained:	1.58 and above
   Surface acceleration:	1035.39	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.544
   Length of year:		876.99	days
   Length of day:		12.70	hours


Planet 7	
   Distance from primary:	2.418	AU
   Mass:			0.026	Earth masses
   Equatorial radius:		1926.3	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.145
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-90.79	degrees Celcius
   Normal daytime temperature:	-68.10	degrees Celcius
   Normal night temperature:	-113.51	degrees Celcius
   Maximum temperature:   	-41.46	degrees Celcius
   Minimum temperature:   	-140.76	degrees Celcius
   Escape Velocity:		3.30	km/sec
   Molecular weight retained:	72.73 and above
   Surface acceleration:	283.29	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.312
   Length of year:		1313.06	days
   Length of day:		28.71	hours
   Boiling point of water:	-30.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	31.20
   liquids at surface:
				Ethanol      melts at -114  boils at -34
   gasses in atmosphere:
				Krypton          72.0%  PP    0.5 mb
				Xenon            28.0%  PP    0.2 mb


Planet 8	
   Distance from primary:	3.198	AU
   Mass:			0.853	Earth masses
   Equatorial radius:		6080.0	km
   Density:			5.414	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.94	Earth gees
   Surface pressure:		0.780	Earth atmospheres
   Surface temperature:		-129.87	degrees Celcius
   Normal daytime temperature:	-127.37	degrees Celcius
   Normal night temperature:	-132.52	degrees Celcius
   Maximum temperature:   	-111.29	degrees Celcius
   Minimum temperature:   	-150.05	degrees Celcius
   Escape Velocity:		10.58	km/sec
   Molecular weight retained:	7.10 and above
   Surface acceleration:	919.96	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.727
   Length of year:		1996.59	days
   Length of day:		15.80	hours
   Boiling point of water:	93.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -115
   gasses in atmosphere:
				Nitrogen         99.9%  PP  779.5 mb


Planet 9	*gas giant*
   Distance from primary:	6.556	AU
   Mass:			2402.208	Earth masses
   Equatorial radius:		117822.0	km
   Density:			2.096	grams/cc
   Eccentricity of orbit:	0.246
   Escape Velocity:		127.52	km/sec
   Molecular weight retained:	0.05 and above
   Surface acceleration:	6900.76	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.549
   Length of year:		5842.16	days
   Length of day:		4.92	hours


Planet 10	*gas giant*
   Distance from primary:	19.058	AU
   Mass:			170.873	Earth masses
   Equatorial radius:		59570.4	km
   Density:			1.153	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		47.83	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	1920.22	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.490
   Length of year:		29043.56	days
   Length of day:		9.33	hours


Planet 11	
   Distance from primary:	29.053	AU
   Mass:			0.075	Earth masses
   Equatorial radius:		3646.8	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.73	degrees Celcius
   Normal daytime temperature:	-210.11	degrees Celcius
   Normal night temperature:	-225.27	degrees Celcius
   Maximum temperature:   	-193.47	degrees Celcius
   Minimum temperature:   	-242.36	degrees Celcius
   Escape Velocity:		4.05	km/sec
   Molecular weight retained:	48.40 and above
   Surface acceleration:	224.87	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.158
   Length of year:		54679.82	days
   Length of day:		31.96	hours
   Boiling point of water:	-68.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06
   liquids at surface:
				Fluorine     melts at -220  boils at -217
				Oxygen       melts at -218  boils at -213


Planet 12	
   Distance from primary:	40.327	AU
   Mass:			0.204	Earth masses
   Equatorial radius:		5077.3	km
   Density:			2.226	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.52	degrees Celcius
   Normal daytime temperature:	-219.89	degrees Celcius
   Normal night temperature:	-231.08	degrees Celcius
   Maximum temperature:   	-208.04	degrees Celcius
   Minimum temperature:   	-243.59	degrees Celcius
   Escape Velocity:		5.66	km/sec
   Molecular weight retained:	24.75 and above
   Surface acceleration:	315.85	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.139
   Length of year:		89420.38	days
   Length of day:		26.97	hours
   Boiling point of water:	-49.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 13	
   Distance from primary:	50.447	AU
   Mass:			0.161	Earth masses
   Equatorial radius:		4694.0	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.82	degrees Celcius
   Normal daytime temperature:	-225.62	degrees Celcius
   Normal night temperature:	-235.90	degrees Celcius
   Maximum temperature:   	-214.17	degrees Celcius
   Minimum temperature:   	-247.84	degrees Celcius
   Escape Velocity:		5.23	km/sec
   Molecular weight retained:	29.03 and above
   Surface acceleration:	291.23	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.158
   Length of year:		125109.96	days
   Length of day:		28.08	hours
   Boiling point of water:	-54.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


