                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f8d
Stellar mass: 1.09 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6166 K
Stellar class: F8
Age: 1.979 billion years  (5.096 billion left on main sequence)
Habitable ecosphere radius: 1.243 AU

Planets present at:
1	  0.331 AU	no atmosphere
2	  0.396 AU	no atmosphere
3	  0.475 AU	no atmosphere
4	  0.768 AU	no atmosphere
5	  0.877 AU	greenhouse
6	  1.696 AU	gas giant
7	  2.632 AU	gas giant
8	  5.133 AU	no atmosphere
9	  7.047 AU	gas giant
10	 16.977 AU	gas giant
11	 34.338 AU	gas giant
12	 47.844 AU	no atmosphere



Planet 1	
   Distance from primary:	0.331	AU
   Mass:			0.177	Earth masses
   Equatorial radius:		3627.6	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.088
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.84	degrees Celcius
   Normal daytime temperature:	474.03	degrees Celcius
   Normal night temperature:	-178.25	degrees Celcius
   Maximum temperature:   	477.28	degrees Celcius
   Minimum temperature:   	-189.65	degrees Celcius
   Escape Velocity:		6.25	km/sec
   Molecular weight retained:	20.35 and above
   Surface acceleration:	537.79	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.080
   Length of year:		66.61	days
   Length of day:		1598.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.396	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2233.0	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		213.30	degrees Celcius
   Maximum temperature:   	425.72	degrees Celcius
   Minimum temperature:   	-201.48	degrees Celcius
   Escape Velocity:		3.83	km/sec
   Molecular weight retained:	54.06 and above
   Surface acceleration:	328.77	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.060
   Length of year:		87.11	days
   Length of day:		2090.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.475	AU
   Mass:			0.071	Earth masses
   Equatorial radius:		2676.5	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		167.65	degrees Celcius
   Maximum temperature:   	369.91	degrees Celcius
   Minimum temperature:   	-212.21	degrees Celcius
   Escape Velocity:		4.60	km/sec
   Molecular weight retained:	37.56 and above
   Surface acceleration:	394.77	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.088
   Length of year:		114.41	days
   Length of day:		2745.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.768	AU
   Mass:			0.066	Earth masses
   Equatorial radius:		2616.2	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		74.86	degrees Celcius
   Maximum temperature:   	254.28	degrees Celcius
   Minimum temperature:   	-228.14	degrees Celcius
   Escape Velocity:		4.49	km/sec
   Molecular weight retained:	39.33 and above
   Surface acceleration:	385.79	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.075
   Length of year:		235.08	days
   Length of day:		5641.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.877	AU
   Mass:			1.345	Earth masses
   Equatorial radius:		7051.0	km
   Density:			5.475	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		1.10	Earth gees
   Surface pressure:		186.585	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		474.56	degrees Celcius
   Maximum temperature:   	477.60	degrees Celcius
   Minimum temperature:   	469.32	degrees Celcius
   Escape Velocity:		12.33	km/sec
   Molecular weight retained:	5.22 and above
   Surface acceleration:	1078.81	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.557
   Length of year:		287.05	days
   Length of day:		15.30	hours
   Boiling point of water:	334.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1275
				Cesium       melts at 28    boils at 1320
				Gallium      melts at 30    boils at 4086
				Rubidium     melts at 39    boils at 1292
				Potassium    melts at 63    boils at 1419
				Sodium       melts at 98    boils at 1608
				Indium       melts at 157   boils at 3560
				Lithium      melts at 181   boils at 2366
				Selenium     melts at 217   boils at 1288
				Tin          melts at 232   boils at 4445
				Polonium     melts at 254   boils at 1739
				Bismuth      melts at 271   boils at 2720
				Thallium     melts at 304   boils at 2545
				Cadmium      melts at 321   boils at 1418
				Lead         melts at 328   boils at 3024
				Zinc         melts at 420   boils at 1649
				Tellurium    melts at 450   boils at 1784
   gasses in atmosphere:
				Sulfur           19.3%  PP 35975.2 mb
				Nitrogen         80.1%  PP 149515.9 mb
				Phosphorus        0.4%  PP  718.9 mb


Planet 6	*gas giant*
   Distance from primary:	1.696	AU
   Mass:			9.574	Earth masses
   Equatorial radius:		21011.3	km
   Density:			1.473	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		19.06	km/sec
   Molecular weight retained:	2.18 and above
   Surface acceleration:	864.85	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.504
   Length of year:		771.06	days
   Length of day:		13.90	hours


Planet 7	*gas giant*
   Distance from primary:	2.632	AU
   Mass:			36.911	Earth masses
   Equatorial radius:		32306.5	km
   Density:			1.562	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		30.19	km/sec
   Molecular weight retained:	0.87 and above
   Surface acceleration:	1410.31	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.490
   Length of year:		1490.70	days
   Length of day:		10.88	hours


Planet 8	
   Distance from primary:	5.133	AU
   Mass:			0.291	Earth masses
   Equatorial radius:		5707.7	km
   Density:			2.237	grams/cc
   Eccentricity of orbit:	0.111
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.050	Earth atmospheres
   Surface temperature:		-139.31	degrees Celcius
   Normal daytime temperature:	-128.84	degrees Celcius
   Normal night temperature:	-150.13	degrees Celcius
   Maximum temperature:   	-106.60	degrees Celcius
   Minimum temperature:   	-173.78	degrees Celcius
   Escape Velocity:		6.38	km/sec
   Molecular weight retained:	19.49 and above
   Surface acceleration:	356.79	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.283
   Length of year:		4061.33	days
   Length of day:		25.37	hours
   Boiling point of water:	32.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	22.87
   gasses in atmosphere:
				Argon             2.2%  PP    1.1 mb
				Neon              3.1%  PP    1.5 mb
				Krypton          94.8%  PP   47.5 mb


Planet 9	*gas giant*
   Distance from primary:	7.047	AU
   Mass:			1064.518	Earth masses
   Equatorial radius:		93491.8	km
   Density:			1.859	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		95.30	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4856.74	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.539
   Length of year:		6523.66	days
   Length of day:		5.86	hours


Planet 10	*gas giant*
   Distance from primary:	16.977	AU
   Mass:			124.205	Earth masses
   Equatorial radius:		53760.8	km
   Density:			1.141	grams/cc
   Eccentricity of orbit:	0.071
   Escape Velocity:		42.93	km/sec
   Molecular weight retained:	0.43 and above
   Surface acceleration:	1713.76	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.452
   Length of year:		24424.17	days
   Length of day:		9.87	hours


Planet 11	*gas giant*
   Distance from primary:	34.338	AU
   Mass:			16.907	Earth masses
   Equatorial radius:		31867.8	km
   Density:			0.745	grams/cc
   Eccentricity of orbit:	0.156
   Escape Velocity:		20.57	km/sec
   Molecular weight retained:	1.88 and above
   Surface acceleration:	663.89	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.530
   Length of year:		70268.37	days
   Length of day:		15.86	hours


Planet 12	
   Distance from primary:	47.844	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		2465.3	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.78	degrees Celcius
   Normal daytime temperature:	-222.73	degrees Celcius
   Normal night temperature:	-236.69	degrees Celcius
   Maximum temperature:   	-206.99	degrees Celcius
   Minimum temperature:   	-252.02	degrees Celcius
   Escape Velocity:		2.73	km/sec
   Molecular weight retained:	106.45 and above
   Surface acceleration:	151.24	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.145
   Length of year:		115568.82	days
   Length of day:		38.97	hours
   Boiling point of water:	-86.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


