                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504802e
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6116 K
Stellar class: F9
Age: 2.214 billion years  (4.839 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.372 AU	no atmosphere
2	  0.450 AU	no atmosphere
3	  0.522 AU	no atmosphere
4	  0.847 AU	greenhouse
5	  1.581 AU	gas giant
6	  2.297 AU	gas giant
7	  4.303 AU	cold
8	  6.260 AU	gas giant
9	  9.298 AU	gas giant
10	 16.484 AU	gas giant
11	 39.605 AU	no atmosphere



Planet 1	
   Distance from primary:	0.372	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1616.1	km
   Density:			5.257	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.93	degrees Celcius
   Maximum temperature:   	445.89	degrees Celcius
   Minimum temperature:   	-197.13	degrees Celcius
   Escape Velocity:		2.77	km/sec
   Molecular weight retained:	103.43 and above
   Surface acceleration:	237.46	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.054
   Length of year:		79.33	days
   Length of day:		1903.88	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.450	AU
   Mass:			0.064	Earth masses
   Equatorial radius:		2582.6	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.099
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		183.97	degrees Celcius
   Maximum temperature:   	390.09	degrees Celcius
   Minimum temperature:   	-209.30	degrees Celcius
   Escape Velocity:		4.43	km/sec
   Molecular weight retained:	40.36 and above
   Surface acceleration:	380.78	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.057
   Length of year:		105.44	days
   Length of day:		2530.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.522	AU
   Mass:			0.294	Earth masses
   Equatorial radius:		4288.0	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.85	degrees Celcius
   Maximum temperature:   	349.21	degrees Celcius
   Minimum temperature:   	-216.09	degrees Celcius
   Escape Velocity:		7.40	km/sec
   Molecular weight retained:	14.50 and above
   Surface acceleration:	638.53	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.062
   Length of year:		131.68	days
   Length of day:		3160.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.847	AU
   Mass:			1.263	Earth masses
   Equatorial radius:		6909.3	km
   Density:			5.465	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		1.08	Earth gees
   Surface pressure:		150.546	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		486.66	degrees Celcius
   Maximum temperature:   	490.00	degrees Celcius
   Minimum temperature:   	480.97	degrees Celcius
   Escape Velocity:		12.08	km/sec
   Molecular weight retained:	5.44 and above
   Surface acceleration:	1055.30	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.498
   Length of year:		272.21	days
   Length of day:		15.81	hours
   Boiling point of water:	319.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1236
				Cesium       melts at 28    boils at 1280
				Gallium      melts at 30    boils at 3977
				Rubidium     melts at 39    boils at 1253
				Potassium    melts at 63    boils at 1376
				Sodium       melts at 98    boils at 1560
				Indium       melts at 157   boils at 3464
				Lithium      melts at 181   boils at 2300
				Selenium     melts at 217   boils at 1248
				Tin          melts at 232   boils at 4326
				Polonium     melts at 254   boils at 1688
				Bismuth      melts at 271   boils at 2644
				Thallium     melts at 304   boils at 2474
				Cadmium      melts at 321   boils at 1375
				Lead         melts at 328   boils at 2941
				Zinc         melts at 420   boils at 1601
				Tellurium    melts at 450   boils at 1733
   gasses in atmosphere:
				Sulfur           19.8%  PP 29822.2 mb
				Nitrogen         79.6%  PP 119817.3 mb
				Phosphorus        0.4%  PP  595.4 mb


Planet 5	*gas giant*
   Distance from primary:	1.581	AU
   Mass:			9.212	Earth masses
   Equatorial radius:		20651.8	km
   Density:			1.492	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		18.86	km/sec
   Molecular weight retained:	2.23 and above
   Surface acceleration:	861.39	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.493
   Length of year:		693.61	days
   Length of day:		13.93	hours


Planet 6	*gas giant*
   Distance from primary:	2.297	AU
   Mass:			3.607	Earth masses
   Equatorial radius:		16208.2	km
   Density:			1.209	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		13.32	km/sec
   Molecular weight retained:	4.47 and above
   Surface acceleration:	547.60	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.524
   Length of year:		1215.57	days
   Length of day:		17.47	hours


Planet 7	
   Distance from primary:	4.303	AU
   Mass:			0.934	Earth masses
   Equatorial radius:		6262.2	km
   Density:			5.425	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.758	Earth atmospheres
   Surface temperature:		-143.44	degrees Celcius
   Normal daytime temperature:	-141.17	degrees Celcius
   Normal night temperature:	-145.83	degrees Celcius
   Maximum temperature:   	-125.20	degrees Celcius
   Minimum temperature:   	-163.35	degrees Celcius
   Escape Velocity:		10.90	km/sec
   Molecular weight retained:	6.68 and above
   Surface acceleration:	949.37	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.668
   Length of year:		3116.00	days
   Length of day:		15.55	hours
   Boiling point of water:	92.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	89.80
   liquids at surface:
				Ozone        melts at -193  boils at -115
   gasses in atmosphere:
				Oxygen           15.0%  PP  114.1 mb
				Nitrogen         84.9%  PP  644.0 mb


Planet 8	*gas giant*
   Distance from primary:	6.260	AU
   Mass:			971.633	Earth masses
   Equatorial radius:		90126.7	km
   Density:			1.894	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		92.73	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4770.18	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.498
   Length of year:		5460.56	days
   Length of day:		5.92	hours


Planet 9	*gas giant*
   Distance from primary:	9.298	AU
   Mass:			5.383	Earth masses
   Equatorial radius:		20466.2	km
   Density:			0.896	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		14.48	km/sec
   Molecular weight retained:	3.78 and above
   Surface acceleration:	512.52	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.459
   Length of year:		9897.28	days
   Length of day:		18.05	hours


Planet 10	*gas giant*
   Distance from primary:	16.484	AU
   Mass:			243.580	Earth masses
   Equatorial radius:		65259.0	km
   Density:			1.251	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		54.56	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2280.87	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.520
   Length of year:		23353.65	days
   Length of day:		8.56	hours


Planet 11	
   Distance from primary:	39.605	AU
   Mass:			0.658	Earth masses
   Equatorial radius:		7448.1	km
   Density:			2.274	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-224.43	degrees Celcius
   Normal daytime temperature:	-219.65	degrees Celcius
   Normal night temperature:	-229.14	degrees Celcius
   Maximum temperature:   	-206.14	degrees Celcius
   Minimum temperature:   	-243.47	degrees Celcius
   Escape Velocity:		8.40	km/sec
   Molecular weight retained:	11.26 and above
   Surface acceleration:	473.33	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.145
   Length of year:		87004.69	days
   Length of day:		22.03	hours
   Boiling point of water:	-27.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   gasses in atmosphere:
				Neon             100.0%  PP    0.9 mb


