                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c2f
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6258 K
Stellar class: F8
Age: 2.495 billion years  (4.698 billion left on main sequence)
Habitable ecosphere radius: 1.231 AU

Planets present at:
1	  0.343 AU	no atmosphere
2	  0.510 AU	no atmosphere
3	  0.693 AU	greenhouse
4	  1.084 AU	greenhouse
5	  1.550 AU	gas giant
6	  2.078 AU	no atmosphere
7	  3.738 AU	gas giant
8	  8.680 AU	gas giant
9	 12.515 AU	gas giant
10	 17.261 AU	gas giant
11	 28.512 AU	gas giant
12	 46.203 AU	gas giant



Planet 1	
   Distance from primary:	0.343	AU
   Mass:			0.203	Earth masses
   Equatorial radius:		3792.6	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.099
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		248.42	degrees Celcius
   Normal daytime temperature:	465.16	degrees Celcius
   Normal night temperature:	-181.08	degrees Celcius
   Maximum temperature:   	468.37	degrees Celcius
   Minimum temperature:   	-192.17	degrees Celcius
   Escape Velocity:		6.53	km/sec
   Molecular weight retained:	18.59 and above
   Surface acceleration:	562.84	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.050
   Length of year:		70.28	days
   Length of day:		1686.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.510	AU
   Mass:			1/688.7	Earth masses
   Equatorial radius:		733.6	km
   Density:			5.248	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.19	degrees Celcius
   Maximum temperature:   	348.32	degrees Celcius
   Minimum temperature:   	-213.98	degrees Celcius
   Escape Velocity:		1.26	km/sec
   Molecular weight retained:	502.83 and above
   Surface acceleration:	107.60	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.087
   Length of year:		127.56	days
   Length of day:		2498.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.693	AU
   Mass:			1.112	Earth masses
   Equatorial radius:		6628.2	km
   Density:			5.447	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		1.03	Earth gees
   Surface pressure:		123.342	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		537.63	degrees Celcius
   Maximum temperature:   	541.40	degrees Celcius
   Minimum temperature:   	530.69	degrees Celcius
   Escape Velocity:		11.57	km/sec
   Molecular weight retained:	5.93 and above
   Surface acceleration:	1008.99	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.495
   Length of year:		201.75	days
   Length of day:		20.91	hours
   Boiling point of water:	305.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1201
				Cesium       melts at 28    boils at 1245
				Gallium      melts at 30    boils at 3880
				Rubidium     melts at 39    boils at 1218
				Potassium    melts at 63    boils at 1339
				Sodium       melts at 98    boils at 1519
				Indium       melts at 157   boils at 3378
				Lithium      melts at 181   boils at 2241
				Selenium     melts at 217   boils at 1214
				Tin          melts at 232   boils at 4221
				Polonium     melts at 254   boils at 1643
				Bismuth      melts at 271   boils at 2578
				Thallium     melts at 304   boils at 2412
				Cadmium      melts at 321   boils at 1338
				Lead         melts at 328   boils at 2868
				Zinc         melts at 420   boils at 1558
				Tellurium    melts at 450   boils at 1687
   gasses in atmosphere:
				Sulfur           21.1%  PP 26073.1 mb
				Nitrogen         78.2%  PP 96478.7 mb
				Phosphorus        0.4%  PP  519.3 mb


Planet 4	
   Distance from primary:	1.084	AU
   Mass:			0.398	Earth masses
   Equatorial radius:		4733.9	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.72	Earth gees
   Surface pressure:		11.636	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		68.25	degrees Celcius
   Maximum temperature:   	78.08	degrees Celcius
   Minimum temperature:   	57.89	degrees Celcius
   Escape Velocity:		8.18	km/sec
   Molecular weight retained:	11.85 and above
   Surface acceleration:	707.37	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.496
   Length of year:		394.84	days
   Length of day:		18.86	hours
   Boiling point of water:	182.6	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 156
				Mercury      melts at -39   boils at 496
				Water        melts at 0     boils at 183
				Francium     melts at 27    boils at 887
				Cesium       melts at 28    boils at 921
				Gallium      melts at 30    boils at 2995
				Rubidium     melts at 39    boils at 901
				Phosphorus   melts at 44    boils at 403
				Potassium    melts at 63    boils at 995
   gasses in atmosphere:
				Nitrogen         99.5%  PP 11577.7 mb
				CarbonDioxide     0.2%  PP   21.0 mb
				Methane           0.1%  PP    6.4 mb
				Ammonia           0.1%  PP    7.4 mb
				Ozone             0.2%  PP   21.5 mb


Planet 5	*gas giant*
   Distance from primary:	1.550	AU
   Mass:			4.468	Earth masses
   Equatorial radius:		16712.0	km
   Density:			1.366	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		14.60	km/sec
   Molecular weight retained:	3.72 and above
   Surface acceleration:	637.93	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.498
   Length of year:		675.24	days
   Length of day:		16.19	hours


Planet 6	
   Distance from primary:	2.078	AU
   Mass:			0.125	Earth masses
   Equatorial radius:		3227.1	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.016	Earth atmospheres
   Surface temperature:		-83.79	degrees Celcius
   Normal daytime temperature:	-67.59	degrees Celcius
   Normal night temperature:	-100.21	degrees Celcius
   Maximum temperature:   	-43.49	degrees Celcius
   Minimum temperature:   	-125.25	degrees Celcius
   Escape Velocity:		5.55	km/sec
   Molecular weight retained:	25.77 and above
   Surface acceleration:	477.30	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.447
   Length of year:		1048.41	days
   Length of day:		21.99	hours
   Boiling point of water:	12.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	53.59
   liquids at surface:
				Ethanol      melts at -114  boils at -3
   gasses in atmosphere:
				Ozone            92.5%  PP   14.8 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           6.5%  PP    1.0 mb
				Xenon             0.8%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	3.738	AU
   Mass:			795.087	Earth masses
   Equatorial radius:		81515.2	km
   Density:			2.095	grams/cc
   Eccentricity of orbit:	0.116
   Escape Velocity:		88.20	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4771.74	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.478
   Length of year:		2526.76	days
   Length of day:		5.92	hours


Planet 8	*gas giant*
   Distance from primary:	8.680	AU
   Mass:			92.211	Earth masses
   Equatorial radius:		46648.4	km
   Density:			1.296	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		39.71	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	1689.86	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.514
   Length of year:		8949.52	days
   Length of day:		9.94	hours


Planet 9	*gas giant*
   Distance from primary:	12.515	AU
   Mass:			3.871	Earth masses
   Equatorial radius:		19075.6	km
   Density:			0.796	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		12.72	km/sec
   Molecular weight retained:	4.90 and above
   Surface acceleration:	424.28	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.499
   Length of year:		15494.89	days
   Length of day:		19.84	hours


Planet 10	*gas giant*
   Distance from primary:	17.261	AU
   Mass:			236.964	Earth masses
   Equatorial radius:		65052.9	km
   Density:			1.228	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		53.90	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2233.00	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.468
   Length of year:		25089.79	days
   Length of day:		8.65	hours


Planet 11	*gas giant*
   Distance from primary:	28.512	AU
   Mass:			3.107	Earth masses
   Equatorial radius:		19160.3	km
   Density:			0.630	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		11.37	km/sec
   Molecular weight retained:	6.14 and above
   Surface acceleration:	337.47	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.539
   Length of year:		53281.28	days
   Length of day:		22.25	hours


Planet 12	*gas giant*
   Distance from primary:	46.203	AU
   Mass:			0.283	Earth masses
   Equatorial radius:		9918.1	km
   Density:			0.414	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		4.77	km/sec
   Molecular weight retained:	34.87 and above
   Surface acceleration:	114.76	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.511
   Length of year:		109913.14	days
   Length of day:		38.15	hours


