                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048b0d
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6184 K
Stellar class: F8
Age: 4.768 billion years  (1.925 billion left on main sequence)
Habitable ecosphere radius: 1.288 AU

Planets present at:
1	  0.439 AU	no atmosphere
2	  0.685 AU	no atmosphere
3	  0.900 AU	greenhouse
4	  1.249 AU	no atmosphere
5	  1.644 AU	cold
6	  2.547 AU	gas giant
7	  5.036 AU	gas giant
8	  8.821 AU	gas giant
9	 12.839 AU	no atmosphere
10	 20.337 AU	gas giant
11	 31.114 AU	gas giant
12	 50.004 AU	no atmosphere



Planet 1	
   Distance from primary:	0.439	AU
   Mass:			0.400	Earth masses
   Equatorial radius:		4745.1	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		193.63	degrees Celcius
   Maximum temperature:   	401.92	degrees Celcius
   Minimum temperature:   	-207.25	degrees Celcius
   Escape Velocity:		8.20	km/sec
   Molecular weight retained:	11.80 and above
   Surface acceleration:	709.09	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.089
   Length of year:		100.75	days
   Length of day:		2417.91	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.685	AU
   Mass:			1/241.9	Earth masses
   Equatorial radius:		1039.5	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		100.93	degrees Celcius
   Maximum temperature:   	287.36	degrees Celcius
   Minimum temperature:   	-225.10	degrees Celcius
   Escape Velocity:		1.78	km/sec
   Molecular weight retained:	250.29 and above
   Surface acceleration:	152.55	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.084
   Length of year:		196.55	days
   Length of day:		4717.25	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	0.900	AU
   Mass:			1.397	Earth masses
   Equatorial radius:		7138.3	km
   Density:			5.480	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		1.11	Earth gees
   Surface pressure:		171.940	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		501.54	degrees Celcius
   Maximum temperature:   	504.64	degrees Celcius
   Minimum temperature:   	495.94	degrees Celcius
   Escape Velocity:		12.49	km/sec
   Molecular weight retained:	5.09 and above
   Surface acceleration:	1093.34	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.472
   Length of year:		296.05	days
   Length of day:		16.02	hours
   Boiling point of water:	328.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1259
				Cesium       melts at 28    boils at 1305
				Gallium      melts at 30    boils at 4044
				Rubidium     melts at 39    boils at 1277
				Potassium    melts at 63    boils at 1403
				Sodium       melts at 98    boils at 1590
				Indium       melts at 157   boils at 3523
				Lithium      melts at 181   boils at 2340
				Selenium     melts at 217   boils at 1272
				Tin          melts at 232   boils at 4399
				Polonium     melts at 254   boils at 1719
				Bismuth      melts at 271   boils at 2690
				Thallium     melts at 304   boils at 2518
				Cadmium      melts at 321   boils at 1401
				Lead         melts at 328   boils at 2992
				Zinc         melts at 420   boils at 1631
				Tellurium    melts at 450   boils at 1764
   gasses in atmosphere:
				Sulfur           21.1%  PP 36343.5 mb
				Nitrogen         78.2%  PP 134520.4 mb
				Phosphorus        0.4%  PP  723.2 mb


Planet 4	
   Distance from primary:	1.249	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2071.2	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		6.25	degrees Celcius
   Normal daytime temperature:	51.44	degrees Celcius
   Normal night temperature:	-39.53	degrees Celcius
   Maximum temperature:   	80.25	degrees Celcius
   Minimum temperature:   	-68.67	degrees Celcius
   Escape Velocity:		3.55	km/sec
   Molecular weight retained:	62.88 and above
   Surface acceleration:	304.76	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.053
   Length of year:		483.78	days
   Length of day:		39.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	
   Distance from primary:	1.644	AU
   Mass:			1.187	Earth masses
   Equatorial radius:		6770.2	km
   Density:			5.456	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		1.05	Earth gees
   Surface pressure:		1.415	Earth atmospheres
   Surface temperature:		-9.17	degrees Celcius
   Normal daytime temperature:	-5.87	degrees Celcius
   Normal night temperature:	-12.66	degrees Celcius
   Maximum temperature:   	12.64	degrees Celcius
   Minimum temperature:   	-32.28	degrees Celcius
   Escape Velocity:		11.82	km/sec
   Molecular weight retained:	5.68 and above
   Surface acceleration:	1032.33	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.280
   Length of year:		730.94	days
   Length of day:		14.96	hours
   Boiling point of water:	109.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	9.31
   Ice cover percentage:	19.50
   liquids at surface:
				Ethanol      melts at -114  boils at 88
				Mercury      melts at -39   boils at 373
   gasses in atmosphere:
				Nitrogen         99.8%  PP 1412.3 mb
				CarbonDioxide     0.1%  PP    0.8 mb
				Ozone             0.1%  PP    0.8 mb


Planet 6	*gas giant*
   Distance from primary:	2.547	AU
   Mass:			182.471	Earth masses
   Equatorial radius:		51199.7	km
   Density:			1.940	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		53.31	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2775.86	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.451
   Length of year:		1408.90	days
   Length of day:		7.76	hours


Planet 7	*gas giant*
   Distance from primary:	5.036	AU
   Mass:			14.919	Earth masses
   Equatorial radius:		26107.6	km
   Density:			1.196	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		21.35	km/sec
   Molecular weight retained:	1.74 and above
   Surface acceleration:	872.87	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.532
   Length of year:		3918.22	days
   Length of day:		13.83	hours


Planet 8	*gas giant*
   Distance from primary:	8.821	AU
   Mass:			1224.933	Earth masses
   Equatorial radius:		98948.0	km
   Density:			1.804	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		99.37	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4989.28	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.457
   Length of year:		9066.78	days
   Length of day:		5.79	hours


Planet 9	
   Distance from primary:	12.839	AU
   Mass:			0.221	Earth masses
   Equatorial radius:		5214.1	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.038	Earth atmospheres
   Surface temperature:		-190.28	degrees Celcius
   Normal daytime temperature:	-183.08	degrees Celcius
   Normal night temperature:	-197.68	degrees Celcius
   Maximum temperature:   	-166.13	degrees Celcius
   Minimum temperature:   	-216.00	degrees Celcius
   Escape Velocity:		5.82	km/sec
   Molecular weight retained:	23.45 and above
   Surface acceleration:	324.68	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.312
   Length of year:		15948.97	days
   Length of day:		26.60	hours
   Boiling point of water:	27.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	27.70
   liquids at surface:
				Ozone        melts at -193  boils at -143


Planet 10	*gas giant*
   Distance from primary:	20.337	AU
   Mass:			4.848	Earth masses
   Equatorial radius:		21129.6	km
   Density:			0.733	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		13.53	km/sec
   Molecular weight retained:	4.34 and above
   Surface acceleration:	433.02	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.494
   Length of year:		31794.52	days
   Length of day:		19.64	hours


Planet 11	*gas giant*
   Distance from primary:	31.114	AU
   Mass:			27.619	Earth masses
   Equatorial radius:		36364.9	km
   Density:			0.820	grams/cc
   Eccentricity of orbit:	0.118
   Escape Velocity:		24.61	km/sec
   Molecular weight retained:	1.31 and above
   Surface acceleration:	832.88	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.544
   Length of year:		60165.58	days
   Length of day:		14.16	hours


Planet 12	
   Distance from primary:	50.004	AU
   Mass:			0.130	Earth masses
   Equatorial radius:		4379.7	km
   Density:			2.215	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.98	degrees Celcius
   Normal daytime temperature:	-224.52	degrees Celcius
   Normal night temperature:	-235.34	degrees Celcius
   Maximum temperature:   	-210.16	degrees Celcius
   Minimum temperature:   	-249.91	degrees Celcius
   Escape Velocity:		4.87	km/sec
   Molecular weight retained:	33.42 and above
   Surface acceleration:	271.18	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.148
   Length of year:		122583.25	days
   Length of day:		29.10	hours
   Boiling point of water:	-61.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


