                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b62
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6241 K
Stellar class: F8
Age: 4.493 billion years  (2.728 billion left on main sequence)
Habitable ecosphere radius: 1.228 AU

Planets present at:
1	  0.320 AU	no atmosphere
2	  0.481 AU	no atmosphere
3	  0.970 AU	greenhouse
4	  1.497 AU	gas giant
5	  1.941 AU	no atmosphere
6	  3.525 AU	gas giant
7	 11.125 AU	gas giant
8	 22.413 AU	gas giant
9	 35.058 AU	gas giant
10	 46.805 AU	no atmosphere



Planet 1	
   Distance from primary:	0.320	AU
   Mass:			0.127	Earth masses
   Equatorial radius:		3243.8	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		260.80	degrees Celcius
   Normal daytime temperature:	479.90	degrees Celcius
   Normal night temperature:	-175.75	degrees Celcius
   Maximum temperature:   	482.98	degrees Celcius
   Minimum temperature:   	-186.62	degrees Celcius
   Escape Velocity:		5.58	km/sec
   Molecular weight retained:	25.50 and above
   Surface acceleration:	479.82	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.089
   Length of year:		63.25	days
   Length of day:		1517.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.481	AU
   Mass:			0.268	Earth masses
   Equatorial radius:		4156.3	km
   Density:			5.323	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		165.27	degrees Celcius
   Maximum temperature:   	367.02	degrees Celcius
   Minimum temperature:   	-212.91	degrees Celcius
   Escape Velocity:		7.17	km/sec
   Molecular weight retained:	15.44 and above
   Surface acceleration:	618.34	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.064
   Length of year:		116.66	days
   Length of day:		2799.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.970	AU
   Mass:			0.960	Earth masses
   Equatorial radius:		6319.7	km
   Density:			5.428	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.98	Earth gees
   Surface pressure:		86.625	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		361.46	degrees Celcius
   Maximum temperature:   	366.18	degrees Celcius
   Minimum temperature:   	355.40	degrees Celcius
   Escape Velocity:		11.01	km/sec
   Molecular weight retained:	6.55 and above
   Surface acceleration:	958.71	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.538
   Length of year:		334.63	days
   Length of day:		16.73	hours
   Boiling point of water:	283.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1144
				Cesium       melts at 28    boils at 1185
				Gallium      melts at 30    boils at 3718
				Rubidium     melts at 39    boils at 1160
				Potassium    melts at 63    boils at 1276
				Sodium       melts at 98    boils at 1449
				Sulfur       melts at 113   boils at 798
				Indium       melts at 157   boils at 3236
				Lithium      melts at 181   boils at 2143
				Selenium     melts at 217   boils at 1156
				Tin          melts at 232   boils at 4046
				Polonium     melts at 254   boils at 1569
				Bismuth      melts at 271   boils at 2467
				Thallium     melts at 304   boils at 2307
				Cadmium      melts at 321   boils at 1275
				Lead         melts at 328   boils at 2746
   gasses in atmosphere:
				Nitrogen         99.1%  PP 85844.1 mb
				Phosphorus        0.6%  PP  517.2 mb
				CarbonDioxide     0.1%  PP   57.5 mb
				Ozone             0.1%  PP   48.7 mb
				Ethanol           0.1%  PP   58.4 mb


Planet 4	*gas giant*
   Distance from primary:	1.497	AU
   Mass:			5.794	Earth masses
   Equatorial radius:		17979.5	km
   Density:			1.422	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		16.03	km/sec
   Molecular weight retained:	3.09 and above
   Surface acceleration:	714.76	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.483
   Length of year:		641.07	days
   Length of day:		15.30	hours


Planet 5	
   Distance from primary:	1.941	AU
   Mass:			0.277	Earth masses
   Equatorial radius:		4200.3	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.075	Earth atmospheres
   Surface temperature:		-74.38	degrees Celcius
   Normal daytime temperature:	-63.53	degrees Celcius
   Normal night temperature:	-85.59	degrees Celcius
   Maximum temperature:   	-40.42	degrees Celcius
   Minimum temperature:   	-109.94	degrees Celcius
   Escape Velocity:		7.25	km/sec
   Molecular weight retained:	15.12 and above
   Surface acceleration:	625.08	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.499
   Length of year:		946.96	days
   Length of day:		19.23	hours
   Boiling point of water:	40.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	66.62
   liquids at surface:
				Ethanol      melts at -114  boils at 22
				Chlorine     melts at -101  boils at -72
				Ammonia      melts at -78   boils at -72
   gasses in atmosphere:
				Oxygen           92.1%  PP   69.0 mb
				CarbonDioxide     3.6%  PP    2.7 mb
				Methane           0.3%  PP    0.2 mb
				Ozone             3.8%  PP    2.8 mb
				Krypton           0.2%  PP    0.2 mb


Planet 6	*gas giant*
   Distance from primary:	3.525	AU
   Mass:			499.741	Earth masses
   Equatorial radius:		70856.5	km
   Density:			2.004	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		75.00	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3969.40	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.543
   Length of year:		2315.55	days
   Length of day:		6.49	hours


Planet 7	*gas giant*
   Distance from primary:	11.125	AU
   Mass:			158.946	Earth masses
   Equatorial radius:		55831.0	km
   Density:			1.303	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		47.65	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2033.47	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.509
   Length of year:		12990.63	days
   Length of day:		9.06	hours


Planet 8	*gas giant*
   Distance from primary:	22.413	AU
   Mass:			80.562	Earth masses
   Equatorial radius:		48545.5	km
   Density:			1.005	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		36.38	km/sec
   Molecular weight retained:	0.60 and above
   Surface acceleration:	1363.24	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.473
   Length of year:		37151.55	days
   Length of day:		11.07	hours


Planet 9	*gas giant*
   Distance from primary:	35.058	AU
   Mass:			0.831	Earth masses
   Equatorial radius:		13271.7	km
   Density:			0.507	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		7.07	km/sec
   Molecular weight retained:	15.90 and above
   Surface acceleration:	188.13	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.494
   Length of year:		72683.39	days
   Length of day:		29.80	hours


Planet 10	
   Distance from primary:	46.805	AU
   Mass:			0.163	Earth masses
   Equatorial radius:		4718.3	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.51	degrees Celcius
   Normal daytime temperature:	-224.17	degrees Celcius
   Normal night temperature:	-234.75	degrees Celcius
   Maximum temperature:   	-208.04	degrees Celcius
   Minimum temperature:   	-250.90	degrees Celcius
   Escape Velocity:		5.26	km/sec
   Molecular weight retained:	28.73 and above
   Surface acceleration:	292.79	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.158
   Length of year:		112124.98	days
   Length of day:		28.01	hours
   Boiling point of water:	-56.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


