                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950482d5
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6354 K
Stellar class: F7
Age: 5.565 billion years  (1.399 billion left on main sequence)
Habitable ecosphere radius: 1.256 AU

Planets present at:
1	  0.368 AU	no atmosphere
2	  0.515 AU	no atmosphere
3	  0.589 AU	no atmosphere
4	  0.953 AU	greenhouse
5	  1.565 AU	cold
6	  2.264 AU	gas giant
7	  2.593 AU	no atmosphere
8	  3.247 AU	cold
9	  5.040 AU	gas giant
10	  7.753 AU	gas giant
11	 12.441 AU	no atmosphere
12	 19.375 AU	gas giant
13	 34.316 AU	gas giant
14	 48.576 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.368	AU
   Mass:			0.114	Earth masses
   Equatorial radius:		3134.2	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.244
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.81	degrees Celcius
   Normal daytime temperature:	443.20	degrees Celcius
   Normal night temperature:	-169.86	degrees Celcius
   Maximum temperature:   	447.41	degrees Celcius
   Minimum temperature:   	-184.70	degrees Celcius
   Escape Velocity:		5.39	km/sec
   Molecular weight retained:	27.33 and above
   Surface acceleration:	463.33	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.079
   Length of year:		77.67	days
   Length of day:		1132.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.515	AU
   Mass:			0.453	Earth masses
   Equatorial radius:		4943.4	km
   Density:			5.356	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.26	degrees Celcius
   Maximum temperature:   	355.93	degrees Celcius
   Minimum temperature:   	-215.22	degrees Celcius
   Escape Velocity:		8.55	km/sec
   Molecular weight retained:	10.85 and above
   Surface acceleration:	739.94	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.054
   Length of year:		128.94	days
   Length of day:		3094.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.589	AU
   Mass:			0.050	Earth masses
   Equatorial radius:		2381.0	km
   Density:			5.271	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		127.20	degrees Celcius
   Maximum temperature:   	319.99	degrees Celcius
   Minimum temperature:   	-221.14	degrees Celcius
   Escape Velocity:		4.09	km/sec
   Molecular weight retained:	47.53 and above
   Surface acceleration:	350.75	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.066
   Length of year:		157.53	days
   Length of day:		3780.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.953	AU
   Mass:			1.246	Earth masses
   Equatorial radius:		6877.6	km
   Density:			5.463	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		1.07	Earth gees
   Surface pressure:		116.052	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		385.14	degrees Celcius
   Maximum temperature:   	389.16	degrees Celcius
   Minimum temperature:   	379.65	degrees Celcius
   Escape Velocity:		12.02	km/sec
   Molecular weight retained:	5.50 and above
   Surface acceleration:	1050.05	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.586
   Length of year:		324.36	days
   Length of day:		16.16	hours
   Boiling point of water:	301.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1191
				Cesium       melts at 28    boils at 1234
				Gallium      melts at 30    boils at 3851
				Rubidium     melts at 39    boils at 1208
				Potassium    melts at 63    boils at 1328
				Sodium       melts at 98    boils at 1506
				Sulfur       melts at 113   boils at 833
				Indium       melts at 157   boils at 3353
				Lithium      melts at 181   boils at 2223
				Selenium     melts at 217   boils at 1203
				Tin          melts at 232   boils at 4190
				Polonium     melts at 254   boils at 1630
				Bismuth      melts at 271   boils at 2558
				Thallium     melts at 304   boils at 2393
				Cadmium      melts at 321   boils at 1326
				Lead         melts at 328   boils at 2846
   gasses in atmosphere:
				Nitrogen         99.2%  PP 115068.7 mb
				Phosphorus        0.6%  PP  656.6 mb
				CarbonDioxide     0.1%  PP   72.9 mb
				Ethanol           0.1%  PP   74.0 mb


Planet 5	
   Distance from primary:	1.565	AU
   Mass:			1.121	Earth masses
   Equatorial radius:		6646.9	km
   Density:			5.448	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		1.03	Earth gees
   Surface pressure:		0.963	Earth atmospheres
   Surface temperature:		-8.29	degrees Celcius
   Normal daytime temperature:	-4.27	degrees Celcius
   Normal night temperature:	-12.54	degrees Celcius
   Maximum temperature:   	15.60	degrees Celcius
   Minimum temperature:   	-33.60	degrees Celcius
   Escape Velocity:		11.60	km/sec
   Molecular weight retained:	5.90 and above
   Surface acceleration:	1012.06	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.268
   Length of year:		682.19	days
   Length of day:		15.14	hours
   Boiling point of water:	99.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	7.45
   Ice cover percentage:	18.10
   liquids at surface:
				Ethanol      melts at -114  boils at 78
				Mercury      melts at -39   boils at 355
   gasses in atmosphere:
				Nitrogen         99.8%  PP  961.4 mb
				CarbonDioxide     0.1%  PP    0.6 mb
				Ozone             0.1%  PP    0.6 mb


Planet 6	*gas giant*
   Distance from primary:	2.264	AU
   Mass:			53.057	Earth masses
   Equatorial radius:		35436.4	km
   Density:			1.701	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		34.56	km/sec
   Molecular weight retained:	0.66 and above
   Surface acceleration:	1684.94	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.485
   Length of year:		1187.31	days
   Length of day:		9.96	hours


Planet 7	
   Distance from primary:	2.593	AU
   Mass:			0.152	Earth masses
   Equatorial radius:		3449.3	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.021	Earth atmospheres
   Surface temperature:		-97.55	degrees Celcius
   Normal daytime temperature:	-83.48	degrees Celcius
   Normal night temperature:	-111.84	degrees Celcius
   Maximum temperature:   	-61.52	degrees Celcius
   Minimum temperature:   	-134.81	degrees Celcius
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.53 and above
   Surface acceleration:	510.81	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.393
   Length of year:		1455.42	days
   Length of day:		21.23	hours
   Boiling point of water:	16.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	49.13
   liquids at surface:
				Ethanol      melts at -114  boils at 1
				Chlorine     melts at -101  boils at -87
   gasses in atmosphere:
				Ozone            92.7%  PP   19.0 mb
				Argon             0.3%  PP    0.1 mb
				Krypton           6.2%  PP    1.3 mb
				Xenon             0.8%  PP    0.2 mb


Planet 8	
   Distance from primary:	3.247	AU
   Mass:			0.345	Earth masses
   Equatorial radius:		4518.2	km
   Density:			5.337	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.126	Earth atmospheres
   Surface temperature:		-120.59	degrees Celcius
   Normal daytime temperature:	-113.85	degrees Celcius
   Normal night temperature:	-127.60	degrees Celcius
   Maximum temperature:   	-94.02	degrees Celcius
   Minimum temperature:   	-148.93	degrees Celcius
   Escape Velocity:		7.80	km/sec
   Molecular weight retained:	13.03 and above
   Surface acceleration:	673.98	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.551
   Length of year:		2038.97	days
   Length of day:		18.46	hours
   Boiling point of water:	50.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	77.51
   gasses in atmosphere:
				Oxygen            7.7%  PP    9.7 mb
				Nitrogen         92.2%  PP  116.0 mb
				Methane           0.1%  PP    0.1 mb


Planet 9	*gas giant*
   Distance from primary:	5.040	AU
   Mass:			7.095	Earth masses
   Equatorial radius:		21064.3	km
   Density:			1.083	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		16.39	km/sec
   Molecular weight retained:	2.95 and above
   Surface acceleration:	637.67	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.521
   Length of year:		3942.45	days
   Length of day:		16.19	hours


Planet 10	*gas giant*
   Distance from primary:	7.753	AU
   Mass:			1004.146	Earth masses
   Equatorial radius:		92569.9	km
   Density:			1.806	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		93.01	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4673.01	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.545
   Length of year:		7513.43	days
   Length of day:		5.98	hours


Planet 11	
   Distance from primary:	12.441	AU
   Mass:			0.052	Earth masses
   Equatorial radius:		3225.3	km
   Density:			2.202	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.002	Earth atmospheres
   Surface temperature:		-189.99	degrees Celcius
   Normal daytime temperature:	-178.14	degrees Celcius
   Normal night temperature:	-201.85	degrees Celcius
   Maximum temperature:   	-159.57	degrees Celcius
   Minimum temperature:   	-221.18	degrees Celcius
   Escape Velocity:		3.58	km/sec
   Molecular weight retained:	62.00 and above
   Surface acceleration:	198.47	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.231
   Length of year:		15291.97	days
   Length of day:		34.02	hours
   Boiling point of water:	-19.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	13.55
   liquids at surface:
				Ozone        melts at -193  boils at -161


Planet 12	*gas giant*
   Distance from primary:	19.375	AU
   Mass:			231.592	Earth masses
   Equatorial radius:		65133.1	km
   Density:			1.196	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		53.25	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2177.01	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.491
   Length of year:		29709.93	days
   Length of day:		8.76	hours


Planet 13	*gas giant*
   Distance from primary:	34.316	AU
   Mass:			2.729	Earth masses
   Equatorial radius:		18703.7	km
   Density:			0.595	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		10.79	km/sec
   Molecular weight retained:	6.82 and above
   Surface acceleration:	311.04	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.511
   Length of year:		70055.14	days
   Length of day:		23.17	hours


Planet 14	
   Distance from primary:	48.576	AU
   Mass:			0.133	Earth masses
   Equatorial radius:		4405.2	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.76	degrees Celcius
   Normal daytime temperature:	-224.29	degrees Celcius
   Normal night temperature:	-235.14	degrees Celcius
   Maximum temperature:   	-209.91	degrees Celcius
   Minimum temperature:   	-249.74	degrees Celcius
   Escape Velocity:		4.90	km/sec
   Molecular weight retained:	33.03 and above
   Surface acceleration:	272.80	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.138
   Length of year:		117982.38	days
   Length of day:		29.02	hours
   Boiling point of water:	-61.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


