                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504819a
Stellar mass: 1.10 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6164 K
Stellar class: F8
Age: 3.021 billion years  (3.984 billion left on main sequence)
Habitable ecosphere radius: 1.251 AU

Planets present at:
1	  0.351 AU	no atmosphere
2	  0.503 AU	no atmosphere
3	  0.877 AU	greenhouse
4	  1.058 AU	greenhouse
5	  1.746 AU	no atmosphere
6	  2.288 AU	gas giant
7	  6.506 AU	gas giant
8	 18.345 AU	gas giant
9	 23.919 AU	no atmosphere
10	 43.913 AU	gas giant



Planet 1	
   Distance from primary:	0.351	AU
   Mass:			0.144	Earth masses
   Equatorial radius:		3388.5	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		245.09	degrees Celcius
   Normal daytime temperature:	461.20	degrees Celcius
   Normal night temperature:	-182.59	degrees Celcius
   Maximum temperature:   	464.20	degrees Celcius
   Minimum temperature:   	-192.82	degrees Celcius
   Escape Velocity:		5.83	km/sec
   Molecular weight retained:	23.35 and above
   Surface acceleration:	501.62	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.059
   Length of year:		72.68	days
   Length of day:		1744.30	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.503	AU
   Mass:			0.195	Earth masses
   Equatorial radius:		3739.9	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		157.46	degrees Celcius
   Maximum temperature:   	357.53	degrees Celcius
   Minimum temperature:   	-215.13	degrees Celcius
   Escape Velocity:		6.44	km/sec
   Molecular weight retained:	19.13 and above
   Surface acceleration:	554.83	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.082
   Length of year:		124.34	days
   Length of day:		2984.11	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.877	AU
   Mass:			0.232	Earth masses
   Equatorial radius:		3963.7	km
   Density:			5.316	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		0.60	Earth gees
   Surface pressure:		4.274	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		56.92	degrees Celcius
   Normal daytime temperature:	61.05	degrees Celcius
   Normal night temperature:	52.23	degrees Celcius
   Maximum temperature:   	74.36	degrees Celcius
   Minimum temperature:   	38.34	degrees Celcius
   Escape Velocity:		6.83	km/sec
   Molecular weight retained:	17.00 and above
   Surface acceleration:	588.89	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.500
   Length of year:		286.54	days
   Length of day:		28.34	hours
   Boiling point of water:	144.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 121
				Mercury      melts at -39   boils at 433
				Bromine      melts at -7    boils at 100
				Water        melts at 0     boils at 145
				Francium     melts at 27    boils at 791
				Cesium       melts at 28    boils at 822
				Gallium      melts at 30    boils at 2724
				Rubidium     melts at 39    boils at 803
				Phosphorus   melts at 44    boils at 347
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP 1991.4 mb
				Ozone            49.5%  PP 2117.3 mb
				Argon             0.1%  PP    4.4 mb
				Neon              0.3%  PP   14.5 mb
				Krypton           3.1%  PP  130.7 mb
				Xenon             0.4%  PP   15.9 mb


Planet 4	
   Distance from primary:	1.058	AU
   Mass:			2.089	Earth masses
   Equatorial radius:		8127.0	km
   Density:			5.554	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		1.29	Earth gees
   Surface pressure:		423.826	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		506.06	degrees Celcius
   Maximum temperature:   	508.04	degrees Celcius
   Minimum temperature:   	501.65	degrees Celcius
   Escape Velocity:		14.32	km/sec
   Molecular weight retained:	3.87 and above
   Surface acceleration:	1261.49	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.564
   Length of year:		379.44	days
   Length of day:		13.71	hours
   Boiling point of water:	401.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1444
				Cesium       melts at 28    boils at 1495
				Gallium      melts at 30    boils at 4564
				Rubidium     melts at 39    boils at 1464
				Potassium    melts at 63    boils at 1604
				Sodium       melts at 98    boils at 1814
				Indium       melts at 157   boils at 3980
				Lithium      melts at 181   boils at 2655
				Selenium     melts at 217   boils at 1458
				Tin          melts at 232   boils at 4962
				Polonium     melts at 254   boils at 1959
				Bismuth      melts at 271   boils at 3047
				Thallium     melts at 304   boils at 2854
				Cadmium      melts at 321   boils at 1603
				Lead         melts at 328   boils at 3385
				Zinc         melts at 420   boils at 1860
				Tellurium    melts at 450   boils at 2010
   gasses in atmosphere:
				Sulfur            0.7%  PP 2956.1 mb
				Nitrogen          3.1%  PP 13330.0 mb
				Helium           96.1%  PP 407452.6 mb


Planet 5	
   Distance from primary:	1.746	AU
   Mass:			0.194	Earth masses
   Equatorial radius:		3735.0	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.032	Earth atmospheres
   Surface temperature:		-56.07	degrees Celcius
   Normal daytime temperature:	-40.54	degrees Celcius
   Normal night temperature:	-71.93	degrees Celcius
   Maximum temperature:   	-17.25	degrees Celcius
   Minimum temperature:   	-96.14	degrees Celcius
   Escape Velocity:		6.43	km/sec
   Molecular weight retained:	19.18 and above
   Surface acceleration:	554.08	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.419
   Length of year:		804.40	days
   Length of day:		20.48	hours
   Boiling point of water:	24.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	51.91
   liquids at surface:
				Ethanol      melts at -114  boils at 8
   gasses in atmosphere:
				CarbonDioxide    46.5%  PP   15.0 mb
				Ozone            49.9%  PP   16.2 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.1%  PP    0.0 mb
				Krypton           3.1%  PP    1.0 mb
				Xenon             0.4%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.288	AU
   Mass:			88.109	Earth masses
   Equatorial radius:		41134.9	km
   Density:			1.806	grams/cc
   Eccentricity of orbit:	0.046
   Escape Velocity:		41.33	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	2076.54	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.495
   Length of year:		1206.88	days
   Length of day:		8.97	hours


Planet 7	*gas giant*
   Distance from primary:	6.506	AU
   Mass:			422.896	Earth masses
   Equatorial radius:		70911.5	km
   Density:			1.692	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		68.97	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3353.81	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.503
   Length of year:		5783.89	days
   Length of day:		7.06	hours


Planet 8	*gas giant*
   Distance from primary:	18.345	AU
   Mass:			174.782	Earth masses
   Equatorial radius:		59746.4	km
   Density:			1.169	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		48.30	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	1952.60	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.508
   Length of year:		27396.26	days
   Length of day:		9.25	hours


Planet 9	
   Distance from primary:	23.919	AU
   Mass:			0.060	Earth masses
   Equatorial radius:		3380.8	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-211.76	degrees Celcius
   Normal daytime temperature:	-203.04	degrees Celcius
   Normal night temperature:	-220.42	degrees Celcius
   Maximum temperature:   	-190.91	degrees Celcius
   Minimum temperature:   	-233.22	degrees Celcius
   Escape Velocity:		3.75	km/sec
   Molecular weight retained:	56.39 and above
   Surface acceleration:	208.19	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.150
   Length of year:		40798.51	days
   Length of day:		33.22	hours
   Boiling point of water:	-72.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 10	*gas giant*
   Distance from primary:	43.913	AU
   Mass:			0.894	Earth masses
   Equatorial radius:		13791.9	km
   Density:			0.486	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		7.19	km/sec
   Molecular weight retained:	15.36 and above
   Surface acceleration:	187.39	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.471
   Length of year:		101488.52	days
   Length of day:		29.86	hours


