                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048283
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6282 K
Stellar class: F8
Age: 5.895 billion years  (1.079 billion left on main sequence)
Habitable ecosphere radius: 1.255 AU

Planets present at:
1	  0.396 AU	no atmosphere
2	  0.567 AU	no atmosphere
3	  0.786 AU	greenhouse
4	  1.225 AU	no atmosphere
5	  1.590 AU	cold
6	  2.068 AU	high pressure
7	  3.391 AU	gas giant
8	  5.996 AU	gas giant
9	 12.213 AU	gas giant
10	 21.442 AU	gas giant
11	 44.272 AU	no atmosphere
12	 50.003 AU	no atmosphere



Planet 1	
   Distance from primary:	0.396	AU
   Mass:			0.105	Earth masses
   Equatorial radius:		3044.8	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.055
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		215.17	degrees Celcius
   Maximum temperature:   	428.05	degrees Celcius
   Minimum temperature:   	-201.34	degrees Celcius
   Escape Velocity:		5.23	km/sec
   Molecular weight retained:	28.97 and above
   Surface acceleration:	449.90	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.064
   Length of year:		86.81	days
   Length of day:		2083.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.567	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		3632.7	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		134.07	degrees Celcius
   Maximum temperature:   	328.49	degrees Celcius
   Minimum temperature:   	-218.19	degrees Celcius
   Escape Velocity:		6.26	km/sec
   Molecular weight retained:	20.29 and above
   Surface acceleration:	538.56	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.073
   Length of year:		148.62	days
   Length of day:		2899.11	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.786	AU
   Mass:			1.326	Earth masses
   Equatorial radius:		7019.3	km
   Density:			5.472	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		1.09	Earth gees
   Surface pressure:		161.189	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		526.58	degrees Celcius
   Maximum temperature:   	529.87	degrees Celcius
   Minimum temperature:   	520.32	degrees Celcius
   Escape Velocity:		12.28	km/sec
   Molecular weight retained:	5.27 and above
   Surface acceleration:	1073.54	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.498
   Length of year:		243.03	days
   Length of day:		20.04	hours
   Boiling point of water:	324.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1248
				Cesium       melts at 28    boils at 1293
				Gallium      melts at 30    boils at 4011
				Rubidium     melts at 39    boils at 1265
				Potassium    melts at 63    boils at 1390
				Sodium       melts at 98    boils at 1575
				Indium       melts at 157   boils at 3494
				Lithium      melts at 181   boils at 2320
				Selenium     melts at 217   boils at 1261
				Tin          melts at 232   boils at 4363
				Polonium     melts at 254   boils at 1704
				Bismuth      melts at 271   boils at 2668
				Thallium     melts at 304   boils at 2496
				Cadmium      melts at 321   boils at 1389
				Lead         melts at 328   boils at 2967
				Zinc         melts at 420   boils at 1616
				Tellurium    melts at 450   boils at 1749
   gasses in atmosphere:
				Sulfur           22.9%  PP 36834.2 mb
				Nitrogen         76.5%  PP 123274.2 mb
				Phosphorus        0.5%  PP  730.5 mb
				CarbonDioxide     0.1%  PP   82.4 mb
				Ethanol           0.1%  PP   83.9 mb


Planet 4	
   Distance from primary:	1.225	AU
   Mass:			0.123	Earth masses
   Equatorial radius:		3210.9	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.164
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.015	Earth atmospheres
   Surface temperature:		-1.53	degrees Celcius
   Normal daytime temperature:	25.07	degrees Celcius
   Normal night temperature:	-28.63	degrees Celcius
   Maximum temperature:   	56.44	degrees Celcius
   Minimum temperature:   	-60.78	degrees Celcius
   Escape Velocity:		5.52	km/sec
   Molecular weight retained:	26.03 and above
   Surface acceleration:	474.87	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.216
   Length of year:		472.61	days
   Length of day:		25.45	hours
   Boiling point of water:	11.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	9.39
   liquids at surface:
				Mercury      melts at -39   boils at 209
   gasses in atmosphere:
				CarbonDioxide    44.1%  PP    6.6 mb
				Ozone            50.9%  PP    7.6 mb
				Chlorine          0.1%  PP    0.0 mb
				Argon             0.2%  PP    0.0 mb
				Krypton           4.1%  PP    0.6 mb
				Xenon             0.6%  PP    0.1 mb


Planet 5	
   Distance from primary:	1.590	AU
   Mass:			0.583	Earth masses
   Equatorial radius:		5367.3	km
   Density:			5.376	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.313	Earth atmospheres
   Surface temperature:		-49.11	degrees Celcius
   Normal daytime temperature:	-42.76	degrees Celcius
   Normal night temperature:	-55.79	degrees Celcius
   Maximum temperature:   	-20.29	degrees Celcius
   Minimum temperature:   	-79.68	degrees Celcius
   Escape Velocity:		9.30	km/sec
   Molecular weight retained:	9.17 and above
   Surface acceleration:	806.41	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.560
   Length of year:		699.09	days
   Length of day:		17.01	hours
   Boiling point of water:	70.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.44
   Ice cover percentage:	80.88
   liquids at surface:
				Ethanol      melts at -114  boils at 51
   gasses in atmosphere:
				Oxygen            0.8%  PP    2.4 mb
				Nitrogen         99.0%  PP  310.0 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ozone             0.1%  PP    0.3 mb


Planet 6	
   Distance from primary:	2.068	AU
   Mass:			1.983	Earth masses
   Equatorial radius:		7991.5	km
   Density:			5.543	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		1.26	Earth gees
   Surface pressure:		3.614	Earth atmospheres
   Surface temperature:		-82.64	degrees Celcius
   Normal daytime temperature:	-81.26	degrees Celcius
   Normal night temperature:	-84.10	degrees Celcius
   Maximum temperature:   	-68.82	degrees Celcius
   Minimum temperature:   	-97.38	degrees Celcius
   Escape Velocity:		14.07	km/sec
   Molecular weight retained:	4.01 and above
   Surface acceleration:	1238.05	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.718
   Length of year:		1036.29	days
   Length of day:		13.63	hours
   Boiling point of water:	139.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 115
				Chlorine     melts at -101  boils at -9
   gasses in atmosphere:
				Nitrogen         99.9%  PP 3610.8 mb


Planet 7	*gas giant*
   Distance from primary:	3.391	AU
   Mass:			4.075	Earth masses
   Equatorial radius:		17337.6	km
   Density:			1.116	grams/cc
   Eccentricity of orbit:	0.193
   Escape Velocity:		13.69	km/sec
   Molecular weight retained:	4.24 and above
   Surface acceleration:	540.55	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.534
   Length of year:		2176.53	days
   Length of day:		17.58	hours


Planet 8	*gas giant*
   Distance from primary:	5.996	AU
   Mass:			622.943	Earth masses
   Equatorial radius:		78836.5	km
   Density:			1.814	grams/cc
   Eccentricity of orbit:	0.227
   Escape Velocity:		79.39	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3996.98	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.491
   Length of year:		5113.66	days
   Length of day:		6.46	hours


Planet 9	*gas giant*
   Distance from primary:	12.213	AU
   Mass:			185.474	Earth masses
   Equatorial radius:		58750.1	km
   Density:			1.305	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		50.18	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2142.92	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.542
   Length of year:		14873.69	days
   Length of day:		8.83	hours


Planet 10	*gas giant*
   Distance from primary:	21.442	AU
   Mass:			100.428	Earth masses
   Equatorial radius:		51483.7	km
   Density:			1.050	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		39.44	km/sec
   Molecular weight retained:	0.51 and above
   Surface acceleration:	1510.97	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.533
   Length of year:		34602.26	days
   Length of day:		10.51	hours


Planet 11	
   Distance from primary:	44.272	AU
   Mass:			0.228	Earth masses
   Equatorial radius:		5262.5	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.177
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.71	degrees Celcius
   Normal daytime temperature:	-222.43	degrees Celcius
   Normal night temperature:	-232.91	degrees Celcius
   Maximum temperature:   	-206.02	degrees Celcius
   Minimum temperature:   	-249.51	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.01 and above
   Surface acceleration:	327.82	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.156
   Length of year:		102676.60	days
   Length of day:		26.47	hours
   Boiling point of water:	-49.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	
   Distance from primary:	50.003	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		4728.8	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.43	degrees Celcius
   Normal daytime temperature:	-225.21	degrees Celcius
   Normal night temperature:	-235.55	degrees Celcius
   Maximum temperature:   	-211.15	degrees Celcius
   Minimum temperature:   	-249.88	degrees Celcius
   Escape Velocity:		5.27	km/sec
   Molecular weight retained:	28.60 and above
   Surface acceleration:	293.46	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.155
   Length of year:		123243.77	days
   Length of day:		27.98	hours
   Boiling point of water:	-57.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


