                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950484ab
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6113 K
Stellar class: F9
Age: 2.937 billion years  (3.964 billion left on main sequence)
Habitable ecosphere radius: 1.263 AU

Planets present at:
1	  0.366 AU	no atmosphere
2	  0.460 AU	no atmosphere
3	  0.523 AU	no atmosphere
4	  0.795 AU	no atmosphere
5	  0.871 AU	greenhouse
6	  0.995 AU	no atmosphere
7	  1.540 AU	no atmosphere
8	  1.717 AU	no atmosphere
9	  2.033 AU	high pressure
10	  3.218 AU	gas giant
11	  5.937 AU	gas giant
12	 10.768 AU	gas giant
13	 18.885 AU	no atmosphere
14	 26.958 AU	gas giant
15	 49.109 AU	no atmosphere



Planet 1	
   Distance from primary:	0.366	AU
   Mass:			0.032	Earth masses
   Equatorial radius:		2049.5	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		236.46	degrees Celcius
   Normal daytime temperature:	450.83	degrees Celcius
   Normal night temperature:	-185.57	degrees Celcius
   Maximum temperature:   	453.89	degrees Celcius
   Minimum temperature:   	-195.87	degrees Celcius
   Escape Velocity:		3.52	km/sec
   Molecular weight retained:	64.22 and above
   Surface acceleration:	301.55	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.062
   Length of year:		77.15	days
   Length of day:		1851.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.460	AU
   Mass:			0.388	Earth masses
   Equatorial radius:		4697.5	km
   Density:			5.345	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		182.08	degrees Celcius
   Maximum temperature:   	387.79	degrees Celcius
   Minimum temperature:   	-209.97	degrees Celcius
   Escape Velocity:		8.12	km/sec
   Molecular weight retained:	12.04 and above
   Surface acceleration:	701.72	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.057
   Length of year:		108.75	days
   Length of day:		2610.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.523	AU
   Mass:			0.032	Earth masses
   Equatorial radius:		2063.2	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		152.22	degrees Celcius
   Maximum temperature:   	350.99	degrees Celcius
   Minimum temperature:   	-216.15	degrees Celcius
   Escape Velocity:		3.54	km/sec
   Molecular weight retained:	63.37 and above
   Surface acceleration:	303.58	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.074
   Length of year:		131.48	days
   Length of day:		3155.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.795	AU
   Mass:			1/1694	Earth masses
   Equatorial radius:		543.5	km
   Density:			5.247	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.08	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		72.70	degrees Celcius
   Maximum temperature:   	251.49	degrees Celcius
   Minimum temperature:   	-228.43	degrees Celcius
   Escape Velocity:		0.93	km/sec
   Molecular weight retained:	916.28 and above
   Surface acceleration:	79.70	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.064
   Length of year:		246.61	days
   Length of day:		5918.72	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.871	AU
   Mass:			1.114	Earth masses
   Equatorial radius:		6632.3	km
   Density:			5.447	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		1.03	Earth gees
   Surface pressure:		100.857	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		430.53	degrees Celcius
   Maximum temperature:   	434.65	degrees Celcius
   Minimum temperature:   	424.54	degrees Celcius
   Escape Velocity:		11.57	km/sec
   Molecular weight retained:	5.93 and above
   Surface acceleration:	1009.68	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.514
   Length of year:		283.04	days
   Length of day:		16.47	hours
   Boiling point of water:	292.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1168
				Cesium       melts at 28    boils at 1210
				Gallium      melts at 30    boils at 3786
				Rubidium     melts at 39    boils at 1185
				Potassium    melts at 63    boils at 1302
				Sodium       melts at 98    boils at 1478
				Sulfur       melts at 113   boils at 816
				Indium       melts at 157   boils at 3296
				Lithium      melts at 181   boils at 2184
				Selenium     melts at 217   boils at 1180
				Tin          melts at 232   boils at 4120
				Polonium     melts at 254   boils at 1600
				Bismuth      melts at 271   boils at 2513
				Thallium     melts at 304   boils at 2351
				Cadmium      melts at 321   boils at 1301
				Lead         melts at 328   boils at 2797
				Zinc         melts at 420   boils at 1517
   gasses in atmosphere:
				Nitrogen         99.2%  PP 100040.9 mb
				Phosphorus        0.5%  PP  536.3 mb
				CarbonDioxide     0.1%  PP   57.9 mb
				Ozone             0.1%  PP   51.1 mb
				Ethanol           0.1%  PP   58.6 mb


Planet 6	
   Distance from primary:	0.995	AU
   Mass:			0.098	Earth masses
   Equatorial radius:		2983.2	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		36.33	degrees Celcius
   Normal daytime temperature:	78.38	degrees Celcius
   Normal night temperature:	-6.28	degrees Celcius
   Maximum temperature:   	109.39	degrees Celcius
   Minimum temperature:   	-37.87	degrees Celcius
   Escape Velocity:		5.13	km/sec
   Molecular weight retained:	30.19 and above
   Surface acceleration:	440.67	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.060
   Length of year:		345.30	days
   Length of day:		31.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 7	
   Distance from primary:	1.540	AU
   Mass:			0.231	Earth masses
   Equatorial radius:		3960.0	km
   Density:			5.316	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.049	Earth atmospheres
   Surface temperature:		-48.64	degrees Celcius
   Normal daytime temperature:	-34.34	degrees Celcius
   Normal night temperature:	-63.34	degrees Celcius
   Maximum temperature:   	-8.80	degrees Celcius
   Minimum temperature:   	-89.98	degrees Celcius
   Escape Velocity:		6.83	km/sec
   Molecular weight retained:	17.04 and above
   Surface acceleration:	588.33	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.503
   Length of year:		664.97	days
   Length of day:		19.96	hours
   Boiling point of water:	31.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.32
   Ice cover percentage:	58.08
   liquids at surface:
				Ethanol      melts at -114  boils at 15
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP   22.7 mb
				Ozone            49.5%  PP   24.1 mb
				Fluorine          0.1%  PP    0.0 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.4%  PP    0.2 mb
				Krypton           2.9%  PP    1.4 mb
				Xenon             0.3%  PP    0.2 mb


Planet 8	
   Distance from primary:	1.717	AU
   Mass:			0.298	Earth masses
   Equatorial radius:		4303.5	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.071	Earth atmospheres
   Surface temperature:		-55.40	degrees Celcius
   Normal daytime temperature:	-43.46	degrees Celcius
   Normal night temperature:	-67.71	degrees Celcius
   Maximum temperature:   	-19.60	degrees Celcius
   Minimum temperature:   	-92.76	degrees Celcius
   Escape Velocity:		7.43	km/sec
   Molecular weight retained:	14.39 and above
   Surface acceleration:	640.92	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.465
   Length of year:		782.79	days
   Length of day:		19.01	hours
   Boiling point of water:	39.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.20
   Ice cover percentage:	56.17
   liquids at surface:
				Ethanol      melts at -114  boils at 21
   gasses in atmosphere:
				Oxygen           98.9%  PP   70.6 mb
				CarbonDioxide     0.5%  PP    0.3 mb
				Methane           0.1%  PP    0.0 mb
				Ozone             0.5%  PP    0.4 mb


Planet 9	
   Distance from primary:	2.033	AU
   Mass:			1.533	Earth masses
   Equatorial radius:		7356.3	km
   Density:			5.496	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		1.15	Earth gees
   Surface pressure:		2.311	Earth atmospheres
   Surface temperature:		-87.42	degrees Celcius
   Normal daytime temperature:	-85.67	degrees Celcius
   Normal night temperature:	-89.27	degrees Celcius
   Maximum temperature:   	-71.99	degrees Celcius
   Minimum temperature:   	-103.94	degrees Celcius
   Escape Velocity:		12.89	km/sec
   Molecular weight retained:	4.78 and above
   Surface acceleration:	1129.87	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.739
   Length of year:		1009.10	days
   Length of day:		14.26	hours
   Boiling point of water:	124.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 102
				Chlorine     melts at -101  boils at -18
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2308.1 mb


Planet 10	*gas giant*
   Distance from primary:	3.218	AU
   Mass:			414.327	Earth masses
   Equatorial radius:		66421.6	km
   Density:			2.017	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		70.53	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3745.11	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.541
   Length of year:		2008.30	days
   Length of day:		6.68	hours


Planet 11	*gas giant*
   Distance from primary:	5.937	AU
   Mass:			48.011	Earth masses
   Equatorial radius:		37279.8	km
   Density:			1.322	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		32.05	km/sec
   Molecular weight retained:	0.77 and above
   Surface acceleration:	1377.63	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.519
   Length of year:		5035.17	days
   Length of day:		11.01	hours


Planet 12	*gas giant*
   Distance from primary:	10.768	AU
   Mass:			700.827	Earth masses
   Equatorial radius:		85624.6	km
   Density:			1.593	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		80.80	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3812.00	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.531
   Length of year:		12287.32	days
   Length of day:		6.62	hours


Planet 13	
   Distance from primary:	18.885	AU
   Mass:			0.039	Earth masses
   Equatorial radius:		2945.4	km
   Density:			2.199	grams/cc
   Eccentricity of orbit:	0.157
   Surface gravity:		0.18	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-205.22	degrees Celcius
   Normal daytime temperature:	-195.07	degrees Celcius
   Normal night temperature:	-215.33	degrees Celcius
   Maximum temperature:   	-176.10	degrees Celcius
   Minimum temperature:   	-234.79	degrees Celcius
   Escape Velocity:		3.27	km/sec
   Molecular weight retained:	74.44 and above
   Surface acceleration:	181.03	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.221
   Length of year:		28566.68	days
   Length of day:		35.62	hours
   Boiling point of water:	-27.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	11.59


Planet 14	*gas giant*
   Distance from primary:	26.958	AU
   Mass:			30.449	Earth masses
   Equatorial radius:		37029.6	km
   Density:			0.856	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		25.61	km/sec
   Molecular weight retained:	1.21 and above
   Surface acceleration:	885.54	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.457
   Length of year:		48717.47	days
   Length of day:		13.73	hours


Planet 15	
   Distance from primary:	49.109	AU
   Mass:			0.078	Earth masses
   Equatorial radius:		3697.8	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.18	degrees Celcius
   Normal daytime temperature:	-224.32	degrees Celcius
   Normal night temperature:	-235.93	degrees Celcius
   Maximum temperature:   	-214.04	degrees Celcius
   Minimum temperature:   	-246.67	degrees Celcius
   Escape Velocity:		4.11	km/sec
   Molecular weight retained:	47.06 and above
   Surface acceleration:	228.07	cm/sec2
   Axial tilt:			70	degrees
   Planetary albedo:		0.160
   Length of year:		119790.19	days
   Length of day:		31.73	hours
   Boiling point of water:	-67.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


