                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950483ac
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6271 K
Stellar class: F8
Age: 1.389 billion years  (5.547 billion left on main sequence)
Habitable ecosphere radius: 1.259 AU

Planets present at:
1	  0.375 AU	no atmosphere
2	  0.444 AU	no atmosphere
3	  0.541 AU	no atmosphere
4	  0.904 AU	greenhouse
5	  1.195 AU	
6	  1.553 AU	
7	  2.283 AU	gas giant
8	  4.091 AU	cold
9	  5.369 AU	gas giant
10	 10.621 AU	gas giant
11	 22.998 AU	gas giant
12	 42.704 AU	gas giant



Planet 1	
   Distance from primary:	0.375	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1491.5	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.16	degrees Celcius
   Maximum temperature:   	445.02	degrees Celcius
   Minimum temperature:   	-197.59	degrees Celcius
   Escape Velocity:		2.56	km/sec
   Molecular weight retained:	121.46 and above
   Surface acceleration:	219.09	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.067
   Length of year:		79.94	days
   Length of day:		1918.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.444	AU
   Mass:			0.077	Earth masses
   Equatorial radius:		2754.5	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.067
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		189.61	degrees Celcius
   Maximum temperature:   	397.02	degrees Celcius
   Minimum temperature:   	-208.24	degrees Celcius
   Escape Velocity:		4.73	km/sec
   Molecular weight retained:	35.45 and above
   Surface acceleration:	406.43	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.056
   Length of year:		103.15	days
   Length of day:		2475.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.541	AU
   Mass:			0.251	Earth masses
   Equatorial radius:		4069.3	km
   Density:			5.320	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		143.83	degrees Celcius
   Maximum temperature:   	340.56	degrees Celcius
   Minimum temperature:   	-217.64	degrees Celcius
   Escape Velocity:		7.02	km/sec
   Molecular weight retained:	16.12 and above
   Surface acceleration:	605.03	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.079
   Length of year:		138.46	days
   Length of day:		3323.15	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.904	AU
   Mass:			0.298	Earth masses
   Equatorial radius:		4307.5	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.65	Earth gees
   Surface pressure:		9.567	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		94.51	degrees Celcius
   Maximum temperature:   	106.11	degrees Celcius
   Minimum temperature:   	82.25	degrees Celcius
   Escape Velocity:		7.43	km/sec
   Molecular weight retained:	14.36 and above
   Surface acceleration:	641.52	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.434
   Length of year:		299.51	days
   Length of day:		20.90	hours
   Boiling point of water:	174.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 483
				Water        melts at 0     boils at 175
				Francium     melts at 27    boils at 867
				Cesium       melts at 28    boils at 901
				Gallium      melts at 30    boils at 2939
				Rubidium     melts at 39    boils at 880
				Phosphorus   melts at 44    boils at 391
				Potassium    melts at 63    boils at 973
   gasses in atmosphere:
				CarbonDioxide    28.7%  PP 2742.8 mb
				Methane           3.9%  PP  373.4 mb
				Ammonia           5.9%  PP  566.7 mb
				Ozone            29.8%  PP 2854.3 mb
				Ethanol          29.4%  PP 2811.3 mb
				Neon              0.4%  PP   37.3 mb
				Krypton           1.7%  PP  159.3 mb
				Xenon             0.2%  PP   18.4 mb


Planet 5	
   Distance from primary:	1.195	AU
   Mass:			0.633	Earth masses
   Equatorial radius:		5514.3	km
   Density:			5.383	grams/cc
   Eccentricity of orbit:	0.128
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.423	Earth atmospheres
   Surface temperature:		16.30	degrees Celcius
   Normal daytime temperature:	23.38	degrees Celcius
   Normal night temperature:	8.81	degrees Celcius
   Maximum temperature:   	49.04	degrees Celcius
   Minimum temperature:   	-18.26	degrees Celcius
   Escape Velocity:		9.57	km/sec
   Molecular weight retained:	8.68 and above
   Surface acceleration:	829.65	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.333
   Length of year:		455.19	days
   Length of day:		16.80	hours
   Boiling point of water:	77.7	degrees Celcius
   Hydrosphere percentage:	63.57
   Cloud cover percentage:	46.68
   Ice cover percentage:	1.61
   liquids at surface:
				Ethanol      melts at -114  boils at 58
				Mercury      melts at -39   boils at 319
				Bromine      melts at -7    boils at 40
				Water        melts at 0     boils at 78
   gasses in atmosphere:
				Oxygen           58.7%  PP  248.4 mb
				Nitrogen         41.2%  PP  174.2 mb


Planet 6	
   Distance from primary:	1.553	AU
   Mass:			1.269	Earth masses
   Equatorial radius:		6919.4	km
   Density:			5.466	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		1.08	Earth gees
   Surface pressure:		1.294	Earth atmospheres
   Surface temperature:		3.48	degrees Celcius
   Normal daytime temperature:	7.04	degrees Celcius
   Normal night temperature:	-0.29	degrees Celcius
   Maximum temperature:   	25.86	degrees Celcius
   Minimum temperature:   	-20.21	degrees Celcius
   Escape Velocity:		12.09	km/sec
   Molecular weight retained:	5.43 and above
   Surface acceleration:	1056.97	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.179
   Length of year:		674.06	days
   Length of day:		14.76	hours
   Boiling point of water:	107.2	degrees Celcius
   Hydrosphere percentage:	61.55
   Cloud cover percentage:	19.35
   Ice cover percentage:	6.17
   liquids at surface:
				Ethanol      melts at -114  boils at 85
				Mercury      melts at -39   boils at 369
				Bromine      melts at -7    boils at 66
				Water        melts at 0     boils at 107
   gasses in atmosphere:
				Oxygen           23.0%  PP  297.4 mb
				Nitrogen         76.9%  PP  994.9 mb


Planet 7	*gas giant*
   Distance from primary:	2.283	AU
   Mass:			81.224	Earth masses
   Equatorial radius:		40142.1	km
   Density:			1.792	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		40.17	km/sec
   Molecular weight retained:	0.49 and above
   Surface acceleration:	2010.14	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.533
   Length of year:		1201.57	days
   Length of day:		9.12	hours


Planet 8	
   Distance from primary:	4.091	AU
   Mass:			0.995	Earth masses
   Equatorial radius:		6392.7	km
   Density:			5.432	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.759	Earth atmospheres
   Surface temperature:		-131.04	degrees Celcius
   Normal daytime temperature:	-128.59	degrees Celcius
   Normal night temperature:	-133.63	degrees Celcius
   Maximum temperature:   	-111.73	degrees Celcius
   Minimum temperature:   	-152.04	degrees Celcius
   Escape Velocity:		11.14	km/sec
   Molecular weight retained:	6.40 and above
   Surface acceleration:	970.55	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.576
   Length of year:		2882.09	days
   Length of day:		15.38	hours
   Boiling point of water:	92.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	80.96
   liquids at surface:
				Ozone        melts at -193  boils at -115
   gasses in atmosphere:
				Oxygen           42.6%  PP  323.4 mb
				Nitrogen         57.4%  PP  435.5 mb


Planet 9	*gas giant*
   Distance from primary:	5.369	AU
   Mass:			76.469	Earth masses
   Equatorial radius:		42355.0	km
   Density:			1.436	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		37.95	km/sec
   Molecular weight retained:	0.55 and above
   Surface acceleration:	1699.86	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.531
   Length of year:		4333.20	days
   Length of day:		9.91	hours


Planet 10	*gas giant*
   Distance from primary:	10.621	AU
   Mass:			839.754	Earth masses
   Equatorial radius:		90181.7	km
   Density:			1.634	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		86.18	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4117.70	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.499
   Length of year:		12041.52	days
   Length of day:		6.37	hours


Planet 11	*gas giant*
   Distance from primary:	22.998	AU
   Mass:			14.824	Earth masses
   Equatorial radius:		29630.1	km
   Density:			0.813	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		19.98	km/sec
   Molecular weight retained:	1.99 and above
   Surface acceleration:	673.34	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.517
   Length of year:		38414.31	days
   Length of day:		15.75	hours


Planet 12	*gas giant*
   Distance from primary:	42.704	AU
   Mass:			0.582	Earth masses
   Equatorial radius:		12136.7	km
   Density:			0.465	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.74 and above
   Surface acceleration:	157.65	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.516
   Length of year:		97198.78	days
   Length of day:		32.55	hours


