                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048398
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6157 K
Stellar class: F8
Age: 1.172 billion years  (5.766 billion left on main sequence)
Habitable ecosphere radius: 1.259 AU

Planets present at:
1	  0.450 AU	no atmosphere
2	  0.908 AU	no atmosphere
3	  1.005 AU	no atmosphere
4	  1.299 AU	gas giant
5	  2.941 AU	high pressure
6	  4.225 AU	gas giant
7	  6.057 AU	cold
8	 10.909 AU	gas giant
9	 20.689 AU	gas giant
10	 28.302 AU	gas giant
11	 37.484 AU	gas giant
12	 47.081 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.450	AU
   Mass:			0.495	Earth masses
   Equatorial radius:		5088.2	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		186.48	degrees Celcius
   Normal daytime temperature:	389.61	degrees Celcius
   Normal night temperature:	-195.22	degrees Celcius
   Maximum temperature:   	392.91	degrees Celcius
   Minimum temperature:   	-205.50	degrees Celcius
   Escape Velocity:		8.81	km/sec
   Molecular weight retained:	10.23 and above
   Surface acceleration:	762.57	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.057
   Length of year:		105.17	days
   Length of day:		2012.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.908	AU
   Mass:			0.096	Earth masses
   Equatorial radius:		2956.4	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		48.33	degrees Celcius
   Normal daytime temperature:	88.16	degrees Celcius
   Normal night temperature:	7.99	degrees Celcius
   Maximum temperature:   	117.14	degrees Celcius
   Minimum temperature:   	-21.50	degrees Celcius
   Escape Velocity:		5.08	km/sec
   Molecular weight retained:	30.75 and above
   Surface acceleration:	436.65	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.083
   Length of year:		301.14	days
   Length of day:		28.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 3	
   Distance from primary:	1.005	AU
   Mass:			0.116	Earth masses
   Equatorial radius:		3148.4	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		33.18	degrees Celcius
   Normal daytime temperature:	66.30	degrees Celcius
   Normal night temperature:	-0.23	degrees Celcius
   Maximum temperature:   	95.61	degrees Celcius
   Minimum temperature:   	-30.11	degrees Celcius
   Escape Velocity:		5.41	km/sec
   Molecular weight retained:	27.08 and above
   Surface acceleration:	465.47	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.073
   Length of year:		350.81	days
   Length of day:		24.50	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 4	*gas giant*
   Distance from primary:	1.299	AU
   Mass:			6.565	Earth masses
   Equatorial radius:		18389.7	km
   Density:			1.506	grams/cc
   Eccentricity of orbit:	0.128
   Escape Velocity:		16.87	km/sec
   Molecular weight retained:	2.79 and above
   Surface acceleration:	774.20	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.491
   Length of year:		515.73	days
   Length of day:		14.69	hours


Planet 5	
   Distance from primary:	2.941	AU
   Mass:			1.574	Earth masses
   Equatorial radius:		7419.5	km
   Density:			5.500	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		1.16	Earth gees
   Surface pressure:		2.289	Earth atmospheres
   Surface temperature:		-111.89	degrees Celcius
   Normal daytime temperature:	-110.37	degrees Celcius
   Normal night temperature:	-113.50	degrees Celcius
   Maximum temperature:   	-97.53	degrees Celcius
   Minimum temperature:   	-127.35	degrees Celcius
   Escape Velocity:		13.01	km/sec
   Molecular weight retained:	4.69 and above
   Surface acceleration:	1140.52	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.687
   Length of year:		1756.55	days
   Length of day:		14.19	hours
   Boiling point of water:	124.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 101
   gasses in atmosphere:
				Oxygen           10.8%  PP  248.2 mb
				Nitrogen         89.1%  PP 2039.3 mb


Planet 6	*gas giant*
   Distance from primary:	4.225	AU
   Mass:			630.013	Earth masses
   Equatorial radius:		76800.2	km
   Density:			1.985	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		80.89	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4259.56	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.453
   Length of year:		3021.88	days
   Length of day:		6.26	hours


Planet 7	
   Distance from primary:	6.057	AU
   Mass:			0.691	Earth masses
   Equatorial radius:		7565.3	km
   Density:			2.277	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.316	Earth atmospheres
   Surface temperature:		-148.71	degrees Celcius
   Normal daytime temperature:	-144.32	degrees Celcius
   Normal night temperature:	-153.38	degrees Celcius
   Maximum temperature:   	-128.35	degrees Celcius
   Minimum temperature:   	-170.83	degrees Celcius
   Escape Velocity:		8.53	km/sec
   Molecular weight retained:	10.90 and above
   Surface acceleration:	481.40	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.359
   Length of year:		5192.05	days
   Length of day:		21.84	hours
   Boiling point of water:	70.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	34.65
   liquids at surface:
				Ozone        melts at -193  boils at -125
   gasses in atmosphere:
				Oxygen           72.4%  PP  228.9 mb
				Nitrogen         27.6%  PP   87.1 mb


Planet 8	*gas giant*
   Distance from primary:	10.909	AU
   Mass:			588.450	Earth masses
   Equatorial radius:		81480.1	km
   Density:			1.552	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		75.90	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3534.64	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.456
   Length of year:		12540.76	days
   Length of day:		6.87	hours


Planet 9	*gas giant*
   Distance from primary:	20.689	AU
   Mass:			1.222	Earth masses
   Equatorial radius:		14182.4	km
   Density:			0.611	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		8.29	km/sec
   Molecular weight retained:	11.55 and above
   Surface acceleration:	242.22	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.475
   Length of year:		32777.16	days
   Length of day:		26.26	hours


Planet 10	*gas giant*
   Distance from primary:	28.302	AU
   Mass:			1.182	Earth masses
   Equatorial radius:		14417.7	km
   Density:			0.563	grams/cc
   Eccentricity of orbit:	0.116
   Escape Velocity:		8.09	km/sec
   Molecular weight retained:	12.14 and above
   Surface acceleration:	226.75	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.460
   Length of year:		52444.73	days
   Length of day:		27.14	hours


Planet 11	*gas giant*
   Distance from primary:	37.484	AU
   Mass:			2.326	Earth masses
   Equatorial radius:		17982.2	km
   Density:			0.571	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		10.16	km/sec
   Molecular weight retained:	7.69 and above
   Surface acceleration:	286.91	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.458
   Length of year:		79936.53	days
   Length of day:		24.13	hours


Planet 12	
   Distance from primary:	47.081	AU
   Mass:			0.015	Earth masses
   Equatorial radius:		2137.5	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.33	degrees Celcius
   Normal daytime temperature:	-221.77	degrees Celcius
   Normal night temperature:	-236.74	degrees Celcius
   Maximum temperature:   	-206.66	degrees Celcius
   Minimum temperature:   	-251.47	degrees Celcius
   Escape Velocity:		2.37	km/sec
   Molecular weight retained:	141.75 and above
   Surface acceleration:	131.00	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.158
   Length of year:		112525.46	days
   Length of day:		41.87	hours
   Boiling point of water:	-92.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


