                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504881e
Stellar mass: 1.11 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6409 K
Stellar class: F7
Age: 5.925 billion years  (0.863 billion left on main sequence)
Habitable ecosphere radius: 1.276 AU

Planets present at:
1	  0.331 AU	no atmosphere
2	  0.496 AU	no atmosphere
3	  0.550 AU	no atmosphere
4	  0.654 AU	no atmosphere
5	  0.897 AU	no atmosphere
6	  1.466 AU	gas giant
7	  1.986 AU	cold
8	  2.505 AU	gas giant
9	  4.882 AU	gas giant
10	 11.118 AU	gas giant
11	 14.333 AU	gas giant
12	 25.792 AU	gas giant
13	 36.585 AU	gas giant
14	 51.139 AU	no atmosphere



Planet 1	
   Distance from primary:	0.331	AU
   Mass:			0.118	Earth masses
   Equatorial radius:		3167.1	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		266.12	degrees Celcius
   Normal daytime temperature:	486.53	degrees Celcius
   Normal night temperature:	-176.41	degrees Celcius
   Maximum temperature:   	489.52	degrees Celcius
   Minimum temperature:   	-186.95	degrees Celcius
   Escape Velocity:		5.45	km/sec
   Molecular weight retained:	26.76 and above
   Surface acceleration:	468.27	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.057
   Length of year:		66.27	days
   Length of day:		1590.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.496	AU
   Mass:			0.295	Earth masses
   Equatorial radius:		4290.5	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		167.47	degrees Celcius
   Maximum temperature:   	369.73	degrees Celcius
   Minimum temperature:   	-212.94	degrees Celcius
   Escape Velocity:		7.40	km/sec
   Molecular weight retained:	14.48 and above
   Surface acceleration:	638.92	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.060
   Length of year:		121.24	days
   Length of day:		2909.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.550	AU
   Mass:			0.098	Earth masses
   Equatorial radius:		2980.4	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		141.83	degrees Celcius
   Maximum temperature:   	338.24	degrees Celcius
   Minimum temperature:   	-218.55	degrees Celcius
   Escape Velocity:		5.12	km/sec
   Molecular weight retained:	30.25 and above
   Surface acceleration:	440.24	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.090
   Length of year:		141.69	days
   Length of day:		3400.48	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.654	AU
   Mass:			0.173	Earth masses
   Equatorial radius:		3599.9	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		110.77	degrees Celcius
   Maximum temperature:   	299.55	degrees Celcius
   Minimum temperature:   	-223.95	degrees Celcius
   Escape Velocity:		6.20	km/sec
   Molecular weight retained:	20.66 and above
   Surface acceleration:	533.60	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.056
   Length of year:		183.88	days
   Length of day:		4413.14	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.897	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		1742.5	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		53.70	degrees Celcius
   Maximum temperature:   	227.55	degrees Celcius
   Minimum temperature:   	-230.66	degrees Celcius
   Escape Velocity:		2.99	km/sec
   Molecular weight retained:	88.94 and above
   Surface acceleration:	256.12	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.069
   Length of year:		294.97	days
   Length of day:		7079.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 6	*gas giant*
   Distance from primary:	1.466	AU
   Mass:			15.828	Earth masses
   Equatorial radius:		23983.4	km
   Density:			1.637	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		22.94	km/sec
   Molecular weight retained:	1.51 and above
   Surface acceleration:	1097.38	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.457
   Length of year:		616.29	days
   Length of day:		12.34	hours


Planet 7	
   Distance from primary:	1.986	AU
   Mass:			0.967	Earth masses
   Equatorial radius:		6333.9	km
   Density:			5.429	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.98	Earth gees
   Surface pressure:		0.877	Earth atmospheres
   Surface temperature:		-87.47	degrees Celcius
   Normal daytime temperature:	-84.46	degrees Celcius
   Normal night temperature:	-90.66	degrees Celcius
   Maximum temperature:   	-66.37	degrees Celcius
   Minimum temperature:   	-110.12	degrees Celcius
   Escape Velocity:		11.03	km/sec
   Molecular weight retained:	6.52 and above
   Surface acceleration:	961.00	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.721
   Length of year:		971.90	days
   Length of day:		15.48	hours
   Boiling point of water:	96.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	98.03
   liquids at surface:
				Ethanol      melts at -114  boils at 75
				Chlorine     melts at -101  boils at -36
   gasses in atmosphere:
				Nitrogen         99.9%  PP  876.0 mb
				Ozone             0.1%  PP    0.5 mb


Planet 8	*gas giant*
   Distance from primary:	2.505	AU
   Mass:			2.369	Earth masses
   Equatorial radius:		14412.1	km
   Density:			1.129	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		11.45	km/sec
   Molecular weight retained:	6.05 and above
   Surface acceleration:	454.84	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.454
   Length of year:		1377.37	days
   Length of day:		19.17	hours


Planet 9	*gas giant*
   Distance from primary:	4.882	AU
   Mass:			558.010	Earth masses
   Equatorial radius:		74941.7	km
   Density:			1.892	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		77.06	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3962.19	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.527
   Length of year:		3743.44	days
   Length of day:		6.49	hours


Planet 10	*gas giant*
   Distance from primary:	11.118	AU
   Mass:			5.536	Earth masses
   Equatorial radius:		20900.8	km
   Density:			0.865	grams/cc
   Eccentricity of orbit:	0.175
   Escape Velocity:		14.53	km/sec
   Molecular weight retained:	3.76 and above
   Surface acceleration:	505.34	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.502
   Length of year:		12874.95	days
   Length of day:		18.18	hours


Planet 11	*gas giant*
   Distance from primary:	14.333	AU
   Mass:			256.054	Earth masses
   Equatorial radius:		65317.4	km
   Density:			1.311	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		55.92	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2393.39	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.478
   Length of year:		18839.98	days
   Length of day:		8.35	hours


Planet 12	*gas giant*
   Distance from primary:	25.792	AU
   Mass:			5.826	Earth masses
   Equatorial radius:		22756.4	km
   Density:			0.705	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		14.29	km/sec
   Molecular weight retained:	3.89 and above
   Surface acceleration:	448.68	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.475
   Length of year:		45495.02	days
   Length of day:		19.30	hours


Planet 13	*gas giant*
   Distance from primary:	36.585	AU
   Mass:			2.063	Earth masses
   Equatorial radius:		17307.1	km
   Density:			0.568	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		9.75	km/sec
   Molecular weight retained:	8.35 and above
   Surface acceleration:	274.62	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.514
   Length of year:		76855.71	days
   Length of day:		24.66	hours


Planet 14	
   Distance from primary:	51.139	AU
   Mass:			0.090	Earth masses
   Equatorial radius:		3868.4	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.105
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.76	degrees Celcius
   Normal daytime temperature:	-225.08	degrees Celcius
   Normal night temperature:	-236.31	degrees Celcius
   Maximum temperature:   	-209.10	degrees Celcius
   Minimum temperature:   	-252.10	degrees Celcius
   Escape Velocity:		4.30	km/sec
   Molecular weight retained:	42.96 and above
   Surface acceleration:	238.81	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.156
   Length of year:		127014.76	days
   Length of day:		31.01	hours
   Boiling point of water:	-67.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


