                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a4a
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6382 K
Stellar class: F7
Age: 1.946 billion years  (4.771 billion left on main sequence)
Habitable ecosphere radius: 1.285 AU

Planets present at:
1	  0.339 AU	no atmosphere
2	  0.702 AU	no atmosphere
3	  1.058 AU	greenhouse
4	  1.278 AU	
5	  1.951 AU	gas giant
6	  3.285 AU	gas giant
7	  5.750 AU	gas giant
8	  9.418 AU	gas giant
9	 18.363 AU	no atmosphere
10	 22.413 AU	gas giant
11	 42.038 AU	no atmosphere
12	 42.615 AU	gas giant
13	 49.672 AU	no atmosphere



Planet 1	
   Distance from primary:	0.339	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		3410.4	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.098
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		257.25	degrees Celcius
   Normal daytime temperature:	475.85	degrees Celcius
   Normal night temperature:	-178.86	degrees Celcius
   Maximum temperature:   	479.06	degrees Celcius
   Minimum temperature:   	-190.13	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.05 and above
   Surface acceleration:	504.93	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.090
   Length of year:		68.42	days
   Length of day:		1642.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.702	AU
   Mass:			0.217	Earth masses
   Equatorial radius:		3874.9	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.234
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		96.91	degrees Celcius
   Normal daytime temperature:	208.48	degrees Celcius
   Normal night temperature:	-27.25	degrees Celcius
   Maximum temperature:   	236.28	degrees Celcius
   Minimum temperature:   	-62.78	degrees Celcius
   Escape Velocity:		6.68	km/sec
   Molecular weight retained:	17.80 and above
   Surface acceleration:	575.35	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.074
   Length of year:		204.18	days
   Length of day:		101.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	1.058	AU
   Mass:			2.151	Earth masses
   Equatorial radius:		8202.6	km
   Density:			5.560	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		1.30	Earth gees
   Surface pressure:		499.259	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		512.24	degrees Celcius
   Maximum temperature:   	513.98	degrees Celcius
   Minimum temperature:   	508.02	degrees Celcius
   Escape Velocity:		14.46	km/sec
   Molecular weight retained:	3.80 and above
   Surface acceleration:	1274.63	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.618
   Length of year:		377.50	days
   Length of day:		13.56	hours
   Boiling point of water:	416.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1482
				Cesium       melts at 28    boils at 1534
				Gallium      melts at 30    boils at 4672
				Rubidium     melts at 39    boils at 1503
				Potassium    melts at 63    boils at 1646
				Sodium       melts at 98    boils at 1861
				Indium       melts at 157   boils at 4075
				Lithium      melts at 181   boils at 2721
				Selenium     melts at 217   boils at 1497
				Tin          melts at 232   boils at 5079
				Polonium     melts at 254   boils at 2009
				Bismuth      melts at 271   boils at 3122
				Thallium     melts at 304   boils at 2924
				Cadmium      melts at 321   boils at 1645
				Lead         melts at 328   boils at 3467
				Zinc         melts at 420   boils at 1907
				Tellurium    melts at 450   boils at 2061
   gasses in atmosphere:
				Sulfur            0.4%  PP 1987.7 mb
				Nitrogen          1.9%  PP 9343.9 mb
				Helium           97.7%  PP 487868.4 mb


Planet 4	
   Distance from primary:	1.278	AU
   Mass:			0.441	Earth masses
   Equatorial radius:		4898.8	km
   Density:			5.354	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.178	Earth atmospheres
   Surface temperature:		10.60	degrees Celcius
   Normal daytime temperature:	21.26	degrees Celcius
   Normal night temperature:	-0.57	degrees Celcius
   Maximum temperature:   	46.12	degrees Celcius
   Minimum temperature:   	-26.63	degrees Celcius
   Escape Velocity:		8.47	km/sec
   Molecular weight retained:	11.05 and above
   Surface acceleration:	732.99	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.223
   Length of year:		500.84	days
   Length of day:		17.92	hours
   Boiling point of water:	57.8	degrees Celcius
   Hydrosphere percentage:	48.59
   Cloud cover percentage:	23.98
   Ice cover percentage:	3.16
   liquids at surface:
				Ethanol      melts at -114  boils at 39
				Mercury      melts at -39   boils at 286
				Bromine      melts at -7    boils at 22
				Water        melts at 0     boils at 58
   gasses in atmosphere:
				Oxygen           59.3%  PP  105.5 mb
				Nitrogen         40.6%  PP   72.2 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.951	AU
   Mass:			4.822	Earth masses
   Equatorial radius:		17356.3	km
   Density:			1.316	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		14.89	km/sec
   Molecular weight retained:	3.58 and above
   Surface acceleration:	638.35	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.467
   Length of year:		944.91	days
   Length of day:		16.18	hours


Planet 6	*gas giant*
   Distance from primary:	3.285	AU
   Mass:			9.958	Earth masses
   Equatorial radius:		22396.4	km
   Density:			1.265	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		18.83	km/sec
   Molecular weight retained:	2.24 and above
   Surface acceleration:	791.72	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.499
   Length of year:		2064.65	days
   Length of day:		14.53	hours


Planet 7	*gas giant*
   Distance from primary:	5.750	AU
   Mass:			59.706	Earth masses
   Equatorial radius:		39564.8	km
   Density:			1.376	grams/cc
   Eccentricity of orbit:	0.199
   Escape Velocity:		34.69	km/sec
   Molecular weight retained:	0.66 and above
   Surface acceleration:	1521.03	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.532
   Length of year:		4781.68	days
   Length of day:		10.48	hours


Planet 8	*gas giant*
   Distance from primary:	9.418	AU
   Mass:			887.588	Earth masses
   Equatorial radius:		90585.3	km
   Density:			1.704	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		88.40	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4313.55	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.499
   Length of year:		10012.80	days
   Length of day:		6.22	hours


Planet 9	
   Distance from primary:	18.363	AU
   Mass:			0.361	Earth masses
   Equatorial radius:		6121.0	km
   Density:			2.245	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.082	Earth atmospheres
   Surface temperature:		-201.30	degrees Celcius
   Normal daytime temperature:	-196.59	degrees Celcius
   Normal night temperature:	-206.21	degrees Celcius
   Maximum temperature:   	-179.76	degrees Celcius
   Minimum temperature:   	-224.63	degrees Celcius
   Escape Velocity:		6.86	km/sec
   Molecular weight retained:	16.89 and above
   Surface acceleration:	383.97	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.309
   Length of year:		27293.18	days
   Length of day:		24.46	hours
   Boiling point of water:	41.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	26.28
   liquids at surface:
				Fluorine     melts at -220  boils at -201
				Oxygen       melts at -218  boils at -197
   gasses in atmosphere:
				Neon             100.0%  PP   81.9 mb


Planet 10	*gas giant*
   Distance from primary:	22.413	AU
   Mass:			33.475	Earth masses
   Equatorial radius:		37432.7	km
   Density:			0.911	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		26.71	km/sec
   Molecular weight retained:	1.11 and above
   Surface acceleration:	952.71	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.540
   Length of year:		36800.74	days
   Length of day:		13.24	hours


Planet 11	
   Distance from primary:	42.038	AU
   Mass:			0.235	Earth masses
   Equatorial radius:		5315.9	km
   Density:			2.230	grams/cc
   Eccentricity of orbit:	0.202
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.06	degrees Celcius
   Normal daytime temperature:	-220.61	degrees Celcius
   Normal night temperature:	-231.44	degrees Celcius
   Maximum temperature:   	-203.19	degrees Celcius
   Minimum temperature:   	-249.02	degrees Celcius
   Escape Velocity:		5.93	km/sec
   Molecular weight retained:	22.54 and above
   Surface acceleration:	331.28	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.162
   Length of year:		94534.23	days
   Length of day:		26.33	hours
   Boiling point of water:	-49.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 12	*gas giant*
   Distance from primary:	42.615	AU
   Mass:			0.443	Earth masses
   Equatorial radius:		11186.1	km
   Density:			0.452	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		5.62	km/sec
   Molecular weight retained:	25.13 and above
   Surface acceleration:	141.20	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.462
   Length of year:		96486.59	days
   Length of day:		34.40	hours


Planet 13	
   Distance from primary:	49.672	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		3442.5	km
   Density:			2.204	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.77	degrees Celcius
   Normal daytime temperature:	-223.67	degrees Celcius
   Normal night temperature:	-235.76	degrees Celcius
   Maximum temperature:   	-209.79	degrees Celcius
   Minimum temperature:   	-249.78	degrees Celcius
   Escape Velocity:		3.82	km/sec
   Molecular weight retained:	54.37 and above
   Surface acceleration:	212.05	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.137
   Length of year:		121423.76	days
   Length of day:		32.91	hours
   Boiling point of water:	-73.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


