                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048084
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6335 K
Stellar class: F7
Age: 3.527 billion years  (3.515 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.450 AU	no atmosphere
2	  0.860 AU	greenhouse
3	  1.202 AU	high pressure
4	  1.894 AU	gas giant
5	  6.026 AU	gas giant
6	 15.575 AU	gas giant
7	 34.730 AU	no atmosphere
8	 37.977 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.450	AU
   Mass:			0.500	Earth masses
   Equatorial radius:		5103.5	km
   Density:			5.363	grams/cc
   Eccentricity of orbit:	0.206
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		181.78	degrees Celcius
   Normal daytime temperature:	383.22	degrees Celcius
   Normal night temperature:	-191.39	degrees Celcius
   Maximum temperature:   	387.00	degrees Celcius
   Minimum temperature:   	-203.35	degrees Celcius
   Escape Velocity:		8.84	km/sec
   Molecular weight retained:	10.17 and above
   Surface acceleration:	764.96	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.080
   Length of year:		105.22	days
   Length of day:		1662.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.860	AU
   Mass:			0.558	Earth masses
   Equatorial radius:		5290.7	km
   Density:			5.372	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.81	Earth gees
   Surface pressure:		32.746	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		229.98	degrees Celcius
   Maximum temperature:   	237.15	degrees Celcius
   Minimum temperature:   	222.02	degrees Celcius
   Escape Velocity:		9.17	km/sec
   Molecular weight retained:	9.44 and above
   Surface acceleration:	794.35	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.435
   Length of year:		278.25	days
   Length of day:		21.06	hours
   Boiling point of water:	229.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 576
				Francium     melts at 27    boils at 1007
				Cesium       melts at 28    boils at 1044
				Gallium      melts at 30    boils at 3332
				Rubidium     melts at 39    boils at 1021
				Phosphorus   melts at 44    boils at 473
				Potassium    melts at 63    boils at 1126
				Sodium       melts at 98    boils at 1282
				Sulfur       melts at 113   boils at 694
				Indium       melts at 157   boils at 2897
				Lithium      melts at 181   boils at 1909
				Selenium     melts at 217   boils at 1017
   gasses in atmosphere:
				Nitrogen         99.6%  PP 32598.8 mb
				CarbonDioxide     0.1%  PP   33.2 mb
				Ozone             0.1%  PP   32.6 mb
				Ethanol           0.1%  PP   33.9 mb


Planet 3	
   Distance from primary:	1.202	AU
   Mass:			1.942	Earth masses
   Equatorial radius:		7938.9	km
   Density:			5.539	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		1.25	Earth gees
   Surface pressure:		3.800	Earth atmospheres
   Surface temperature:		19.10	degrees Celcius
   Normal daytime temperature:	21.18	degrees Celcius
   Normal night temperature:	16.88	degrees Celcius
   Maximum temperature:   	33.65	degrees Celcius
   Minimum temperature:   	3.78	degrees Celcius
   Escape Velocity:		13.97	km/sec
   Molecular weight retained:	4.07 and above
   Surface acceleration:	1228.99	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.470
   Length of year:		460.03	days
   Length of day:		13.80	hours
   Boiling point of water:	140.8	degrees Celcius
   Hydrosphere percentage:	89.71
   Cloud cover percentage:	87.86
   Ice cover percentage:	0.93
   liquids at surface:
				Ethanol      melts at -114  boils at 117
				Mercury      melts at -39   boils at 426
				Bromine      melts at -7    boils at 96
				Water        melts at 0     boils at 141
   gasses in atmosphere:
				Oxygen            0.6%  PP   23.3 mb
				Nitrogen         99.2%  PP 3770.1 mb


Planet 4	*gas giant*
   Distance from primary:	1.894	AU
   Mass:			10.295	Earth masses
   Equatorial radius:		21654.7	km
   Density:			1.447	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		19.47	km/sec
   Molecular weight retained:	2.09 and above
   Surface acceleration:	875.53	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.472
   Length of year:		909.96	days
   Length of day:		13.81	hours


Planet 5	*gas giant*
   Distance from primary:	6.026	AU
   Mass:			1081.769	Earth masses
   Equatorial radius:		92691.0	km
   Density:			1.938	grams/cc
   Eccentricity of orbit:	0.100
   Escape Velocity:		96.48	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	5021.10	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.511
   Length of year:		5155.24	days
   Length of day:		5.77	hours


Planet 6	*gas giant*
   Distance from primary:	15.575	AU
   Mass:			457.113	Earth masses
   Equatorial radius:		78034.5	km
   Density:			1.373	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		68.35	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	2993.57	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.454
   Length of year:		21437.85	days
   Length of day:		7.47	hours


Planet 7	
   Distance from primary:	34.730	AU
   Mass:			0.100	Earth masses
   Equatorial radius:		4017.4	km
   Density:			2.211	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-222.33	degrees Celcius
   Normal daytime temperature:	-215.64	degrees Celcius
   Normal night temperature:	-228.93	degrees Celcius
   Maximum temperature:   	-200.06	degrees Celcius
   Minimum temperature:   	-244.93	degrees Celcius
   Escape Velocity:		4.47	km/sec
   Molecular weight retained:	39.80 and above
   Surface acceleration:	248.21	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.156
   Length of year:		71429.88	days
   Length of day:		30.42	hours
   Boiling point of water:	-63.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 8	*gas giant*
   Distance from primary:	37.977	AU
   Mass:			2.398	Earth masses
   Equatorial radius:		18175.4	km
   Density:			0.570	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		10.26	km/sec
   Molecular weight retained:	7.54 and above
   Surface acceleration:	289.46	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.469
   Length of year:		81677.56	days
   Length of day:		24.02	hours


