                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048394
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6320 K
Stellar class: F7
Age: 5.379 billion years  (1.559 billion left on main sequence)
Habitable ecosphere radius: 1.259 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.624 AU	no atmosphere
3	  0.906 AU	greenhouse
4	  1.382 AU	cold
5	  2.182 AU	gas giant
6	  3.122 AU	gas giant
7	  4.319 AU	gas giant
8	  6.318 AU	gas giant
9	 12.507 AU	gas giant
10	 21.558 AU	gas giant
11	 35.874 AU	gas giant
12	 45.349 AU	no atmosphere



Planet 1	
   Distance from primary:	0.370	AU
   Mass:			0.162	Earth masses
   Equatorial radius:		3523.2	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		232.55	degrees Celcius
   Maximum temperature:   	448.98	degrees Celcius
   Minimum temperature:   	-196.16	degrees Celcius
   Escape Velocity:		6.06	km/sec
   Molecular weight retained:	21.58 and above
   Surface acceleration:	521.99	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.065
   Length of year:		78.45	days
   Length of day:		1882.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.624	AU
   Mass:			0.194	Earth masses
   Equatorial radius:		3733.0	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.158
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		116.65	degrees Celcius
   Maximum temperature:   	306.88	degrees Celcius
   Minimum temperature:   	-221.29	degrees Celcius
   Escape Velocity:		6.43	km/sec
   Molecular weight retained:	19.20 and above
   Surface acceleration:	553.79	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.061
   Length of year:		171.84	days
   Length of day:		2996.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.906	AU
   Mass:			1.875	Earth masses
   Equatorial radius:		7849.3	km
   Density:			5.532	grams/cc
   Eccentricity of orbit:	0.108
   Surface gravity:		1.24	Earth gees
   Surface pressure:		334.099	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		529.52	degrees Celcius
   Maximum temperature:   	531.64	degrees Celcius
   Minimum temperature:   	524.66	degrees Celcius
   Escape Velocity:		13.80	km/sec
   Molecular weight retained:	4.17 and above
   Surface acceleration:	1213.60	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.582
   Length of year:		300.14	days
   Length of day:		14.95	hours
   Boiling point of water:	380.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1391
				Cesium       melts at 28    boils at 1440
				Gallium      melts at 30    boils at 4415
				Rubidium     melts at 39    boils at 1410
				Potassium    melts at 63    boils at 1547
				Sodium       melts at 98    boils at 1750
				Indium       melts at 157   boils at 3849
				Lithium      melts at 181   boils at 2565
				Selenium     melts at 217   boils at 1405
				Tin          melts at 232   boils at 4800
				Polonium     melts at 254   boils at 1890
				Bismuth      melts at 271   boils at 2945
				Thallium     melts at 304   boils at 2758
				Cadmium      melts at 321   boils at 1545
				Lead         melts at 328   boils at 3273
				Zinc         melts at 420   boils at 1794
				Tellurium    melts at 450   boils at 1940
   gasses in atmosphere:
				Sulfur           20.1%  PP 67316.7 mb
				Nitrogen         79.3%  PP 264843.8 mb
				Phosphorus        0.4%  PP 1341.3 mb


Planet 4	
   Distance from primary:	1.382	AU
   Mass:			0.379	Earth masses
   Equatorial radius:		4658.2	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.152	Earth atmospheres
   Surface temperature:		-3.89	degrees Celcius
   Normal daytime temperature:	7.25	degrees Celcius
   Normal night temperature:	-15.54	degrees Celcius
   Maximum temperature:   	34.20	degrees Celcius
   Minimum temperature:   	-43.81	degrees Celcius
   Escape Velocity:		8.05	km/sec
   Molecular weight retained:	12.25 and above
   Surface acceleration:	695.63	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.223
   Length of year:		566.01	days
   Length of day:		18.61	hours
   Boiling point of water:	54.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	9.99
   Ice cover percentage:	12.11
   liquids at surface:
				Ethanol      melts at -114  boils at 36
				Mercury      melts at -39   boils at 280
				Bromine      melts at -7    boils at 19
   gasses in atmosphere:
				Oxygen            5.7%  PP    8.7 mb
				Nitrogen         93.6%  PP  142.3 mb
				CarbonDioxide     0.2%  PP    0.4 mb
				Methane           0.1%  PP    0.1 mb
				Ammonia           0.1%  PP    0.1 mb
				Ozone             0.2%  PP    0.4 mb


Planet 5	*gas giant*
   Distance from primary:	2.182	AU
   Mass:			80.050	Earth masses
   Equatorial radius:		39822.1	km
   Density:			1.809	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		40.04	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	2013.05	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.490
   Length of year:		1122.60	days
   Length of day:		9.11	hours


Planet 6	*gas giant*
   Distance from primary:	3.122	AU
   Mass:			16.163	Earth masses
   Equatorial radius:		25729.0	km
   Density:			1.354	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		22.38	km/sec
   Molecular weight retained:	1.58 and above
   Surface acceleration:	973.65	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.521
   Length of year:		1921.40	days
   Length of day:		13.10	hours


Planet 7	*gas giant*
   Distance from primary:	4.319	AU
   Mass:			62.051	Earth masses
   Equatorial radius:		39135.4	km
   Density:			1.477	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		35.56	km/sec
   Molecular weight retained:	0.63 and above
   Surface acceleration:	1615.65	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.466
   Length of year:		3125.94	days
   Length of day:		10.17	hours


Planet 8	*gas giant*
   Distance from primary:	6.318	AU
   Mass:			52.068	Earth masses
   Equatorial radius:		38381.1	km
   Density:			1.314	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		32.89	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1409.54	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.455
   Length of year:		5530.65	days
   Length of day:		10.89	hours


Planet 9	*gas giant*
   Distance from primary:	12.507	AU
   Mass:			21.585	Earth masses
   Equatorial radius:		31426.5	km
   Density:			0.992	grams/cc
   Eccentricity of orbit:	0.121
   Escape Velocity:		23.41	km/sec
   Molecular weight retained:	1.45 and above
   Surface acceleration:	871.57	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.486
   Length of year:		15405.79	days
   Length of day:		13.84	hours


Planet 10	*gas giant*
   Distance from primary:	21.558	AU
   Mass:			60.025	Earth masses
   Equatorial radius:		44315.2	km
   Density:			0.984	grams/cc
   Eccentricity of orbit:	0.080
   Escape Velocity:		32.87	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1218.89	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.470
   Length of year:		34862.81	days
   Length of day:		11.71	hours


Planet 11	*gas giant*
   Distance from primary:	35.874	AU
   Mass:			2.513	Earth masses
   Equatorial radius:		18324.3	km
   Density:			0.583	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		10.46	km/sec
   Molecular weight retained:	7.26 and above
   Surface acceleration:	298.46	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.455
   Length of year:		74841.74	days
   Length of day:		23.66	hours


Planet 12	
   Distance from primary:	45.349	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		3123.0	km
   Density:			2.201	grams/cc
   Eccentricity of orbit:	0.066
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.21	degrees Celcius
   Normal daytime temperature:	-221.60	degrees Celcius
   Normal night temperature:	-234.69	degrees Celcius
   Maximum temperature:   	-210.24	degrees Celcius
   Minimum temperature:   	-246.44	degrees Celcius
   Escape Velocity:		3.46	km/sec
   Molecular weight retained:	66.16 and above
   Surface acceleration:	192.09	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.136
   Length of year:		106372.95	days
   Length of day:		34.58	hours
   Boiling point of water:	-76.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


