                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504899f
Stellar mass: 1.11 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6217 K
Stellar class: F8
Age: 2.663 billion years  (4.076 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.721 AU	greenhouse
2	  1.167 AU	greenhouse
3	  1.619 AU	gas giant
4	  1.941 AU	cold
5	  3.365 AU	cold
6	  4.866 AU	gas giant
7	  6.673 AU	gas giant
8	 13.484 AU	gas giant
9	 16.470 AU	gas giant
10	 20.111 AU	gas giant
11	 31.871 AU	gas giant
12	 51.126 AU	no atmosphere



Planet 1	
   Distance from primary:	0.721	AU
   Mass:			1.034	Earth masses
   Equatorial radius:		6473.5	km
   Density:			5.437	grams/cc
   Eccentricity of orbit:	0.218
   Surface gravity:		1.00	Earth gees
   Surface pressure:		83.767	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		507.06	degrees Celcius
   Maximum temperature:   	511.97	degrees Celcius
   Minimum temperature:   	499.31	degrees Celcius
   Escape Velocity:		11.29	km/sec
   Molecular weight retained:	6.23 and above
   Surface acceleration:	983.71	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.455
   Length of year:		212.38	days
   Length of day:		20.56	hours
   Boiling point of water:	281.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1139
				Cesium       melts at 28    boils at 1180
				Gallium      melts at 30    boils at 3703
				Rubidium     melts at 39    boils at 1155
				Potassium    melts at 63    boils at 1270
				Sodium       melts at 98    boils at 1443
				Indium       melts at 157   boils at 3223
				Lithium      melts at 181   boils at 2134
				Selenium     melts at 217   boils at 1150
				Tin          melts at 232   boils at 4030
				Polonium     melts at 254   boils at 1562
				Bismuth      melts at 271   boils at 2457
				Thallium     melts at 304   boils at 2298
				Cadmium      melts at 321   boils at 1269
				Lead         melts at 328   boils at 2734
				Zinc         melts at 420   boils at 1480
				Tellurium    melts at 450   boils at 1604
   gasses in atmosphere:
				Sulfur           21.8%  PP 18224.5 mb
				Nitrogen         77.6%  PP 64989.4 mb
				Phosphorus        0.4%  PP  362.7 mb


Planet 2	
   Distance from primary:	1.167	AU
   Mass:			0.713	Earth masses
   Equatorial radius:		5733.8	km
   Density:			5.395	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.88	Earth gees
   Surface pressure:		49.736	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		177.03	degrees Celcius
   Maximum temperature:   	182.67	degrees Celcius
   Minimum temperature:   	170.93	degrees Celcius
   Escape Velocity:		9.96	km/sec
   Molecular weight retained:	8.01 and above
   Surface acceleration:	864.51	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.474
   Length of year:		437.32	days
   Length of day:		16.62	hours
   Boiling point of water:	251.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 612
				Francium     melts at 27    boils at 1062
				Cesium       melts at 28    boils at 1101
				Gallium      melts at 30    boils at 3488
				Rubidium     melts at 39    boils at 1078
				Phosphorus   melts at 44    boils at 505
				Potassium    melts at 63    boils at 1187
				Sodium       melts at 98    boils at 1350
				Sulfur       melts at 113   boils at 736
				Iodine       melts at 114   boils at 371
				Indium       melts at 157   boils at 3034
   gasses in atmosphere:
				Nitrogen         99.7%  PP 49569.6 mb
				CarbonDioxide     0.1%  PP   35.2 mb
				Ozone             0.1%  PP   33.8 mb
				Ethanol           0.1%  PP   35.7 mb


Planet 3	*gas giant*
   Distance from primary:	1.619	AU
   Mass:			8.721	Earth masses
   Equatorial radius:		20316.8	km
   Density:			1.484	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		18.50	km/sec
   Molecular weight retained:	2.32 and above
   Surface acceleration:	842.59	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.548
   Length of year:		715.03	days
   Length of day:		14.08	hours


Planet 4	
   Distance from primary:	1.941	AU
   Mass:			0.713	Earth masses
   Equatorial radius:		5733.9	km
   Density:			5.395	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.410	Earth atmospheres
   Surface temperature:		-70.66	degrees Celcius
   Normal daytime temperature:	-65.76	degrees Celcius
   Normal night temperature:	-75.83	degrees Celcius
   Maximum temperature:   	-44.49	degrees Celcius
   Minimum temperature:   	-98.58	degrees Celcius
   Escape Velocity:		9.96	km/sec
   Molecular weight retained:	8.01 and above
   Surface acceleration:	864.52	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.593
   Length of year:		938.40	days
   Length of day:		16.31	hours
   Boiling point of water:	76.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.09
   Ice cover percentage:	75.82
   liquids at surface:
				Ethanol      melts at -114  boils at 57
				Chlorine     melts at -101  boils at -49
				Ammonia      melts at -78   boils at -48
   gasses in atmosphere:
				Oxygen           20.6%  PP   84.5 mb
				Nitrogen         79.2%  PP  324.8 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	
   Distance from primary:	3.365	AU
   Mass:			1.019	Earth masses
   Equatorial radius:		6442.6	km
   Density:			5.435	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		1.00	Earth gees
   Surface pressure:		1.099	Earth atmospheres
   Surface temperature:		-128.56	degrees Celcius
   Normal daytime temperature:	-126.47	degrees Celcius
   Normal night temperature:	-130.77	degrees Celcius
   Maximum temperature:   	-111.54	degrees Celcius
   Minimum temperature:   	-147.03	degrees Celcius
   Escape Velocity:		11.23	km/sec
   Molecular weight retained:	6.29 and above
   Surface acceleration:	978.68	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.717
   Length of year:		2141.48	days
   Length of day:		15.32	hours
   Boiling point of water:	102.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -111
   gasses in atmosphere:
				Oxygen            2.6%  PP   28.9 mb
				Nitrogen         97.3%  PP 1069.5 mb


Planet 6	*gas giant*
   Distance from primary:	4.866	AU
   Mass:			833.682	Earth masses
   Equatorial radius:		84196.2	km
   Density:			1.993	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		88.87	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4689.80	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.510
   Length of year:		3719.91	days
   Length of day:		5.97	hours


Planet 7	*gas giant*
   Distance from primary:	6.673	AU
   Mass:			13.201	Earth masses
   Equatorial radius:		25799.3	km
   Density:			1.097	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		20.20	km/sec
   Molecular weight retained:	1.95 and above
   Surface acceleration:	790.92	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.507
   Length of year:		5980.56	days
   Length of day:		14.53	hours


Planet 8	*gas giant*
   Distance from primary:	13.484	AU
   Mass:			7.095	Earth masses
   Equatorial radius:		22825.4	km
   Density:			0.851	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		15.75	km/sec
   Molecular weight retained:	3.20 and above
   Surface acceleration:	543.07	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.510
   Length of year:		17180.68	days
   Length of day:		17.54	hours


Planet 9	*gas giant*
   Distance from primary:	16.470	AU
   Mass:			1.770	Earth masses
   Equatorial radius:		15480.9	km
   Density:			0.681	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		9.55	km/sec
   Molecular weight retained:	8.70 and above
   Surface acceleration:	294.54	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.536
   Length of year:		23193.43	days
   Length of day:		23.81	hours


Planet 10	*gas giant*
   Distance from primary:	20.111	AU
   Mass:			3.977	Earth masses
   Equatorial radius:		19933.1	km
   Density:			0.717	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		12.62	km/sec
   Molecular weight retained:	4.99 and above
   Surface acceleration:	399.20	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.492
   Length of year:		31294.73	days
   Length of day:		20.46	hours


Planet 11	*gas giant*
   Distance from primary:	31.871	AU
   Mass:			12.542	Earth masses
   Equatorial radius:		28954.2	km
   Density:			0.737	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		18.59	km/sec
   Molecular weight retained:	2.30 and above
   Surface acceleration:	596.59	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.505
   Length of year:		62432.24	days
   Length of day:		16.73	hours


Planet 12	
   Distance from primary:	51.126	AU
   Mass:			0.134	Earth masses
   Equatorial radius:		4424.1	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.70	degrees Celcius
   Normal daytime temperature:	-225.35	degrees Celcius
   Normal night temperature:	-235.94	degrees Celcius
   Maximum temperature:   	-213.79	degrees Celcius
   Minimum temperature:   	-247.96	degrees Celcius
   Escape Velocity:		4.92	km/sec
   Molecular weight retained:	32.74 and above
   Surface acceleration:	274.01	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.161
   Length of year:		126847.79	days
   Length of day:		28.95	hours
   Boiling point of water:	-58.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


