                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048579
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6402 K
Stellar class: F7
Age: 1.823 billion years  (5.052 billion left on main sequence)
Habitable ecosphere radius: 1.266 AU

Planets present at:
1	  0.380 AU	no atmosphere
2	  0.527 AU	no atmosphere
3	  0.705 AU	greenhouse
4	  1.413 AU	
5	  2.107 AU	gas giant
6	  3.115 AU	gas giant
7	  8.574 AU	gas giant
8	 14.800 AU	no atmosphere
9	 22.059 AU	gas giant
10	 42.204 AU	gas giant



Planet 1	
   Distance from primary:	0.380	AU
   Mass:			0.092	Earth masses
   Equatorial radius:		2920.9	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		226.04	degrees Celcius
   Maximum temperature:   	441.08	degrees Celcius
   Minimum temperature:   	-197.86	degrees Celcius
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.50 and above
   Surface acceleration:	431.33	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.077
   Length of year:		81.36	days
   Length of day:		1952.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.527	AU
   Mass:			0.356	Earth masses
   Equatorial radius:		4564.4	km
   Density:			5.339	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		152.52	degrees Celcius
   Maximum temperature:   	351.30	degrees Celcius
   Minimum temperature:   	-215.97	degrees Celcius
   Escape Velocity:		7.89	km/sec
   Molecular weight retained:	12.77 and above
   Surface acceleration:	681.11	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.061
   Length of year:		132.97	days
   Length of day:		3191.38	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.705	AU
   Mass:			0.649	Earth masses
   Equatorial radius:		5559.8	km
   Density:			5.386	grams/cc
   Eccentricity of orbit:	0.105
   Surface gravity:		0.85	Earth gees
   Surface pressure:		31.230	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		274.55	degrees Celcius
   Maximum temperature:   	282.45	degrees Celcius
   Minimum temperature:   	265.55	degrees Celcius
   Escape Velocity:		9.65	km/sec
   Molecular weight retained:	8.53 and above
   Surface acceleration:	836.85	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.472
   Length of year:		205.79	days
   Length of day:		23.44	hours
   Boiling point of water:	227.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 572
				Francium     melts at 27    boils at 1001
				Cesium       melts at 28    boils at 1038
				Gallium      melts at 30    boils at 3315
				Rubidium     melts at 39    boils at 1015
				Phosphorus   melts at 44    boils at 469
				Potassium    melts at 63    boils at 1120
				Sodium       melts at 98    boils at 1275
				Sulfur       melts at 113   boils at 689
				Indium       melts at 157   boils at 2882
				Lithium      melts at 181   boils at 1899
				Selenium     melts at 217   boils at 1011
				Tin          melts at 232   boils at 3610
				Polonium     melts at 254   boils at 1383
				Bismuth      melts at 271   boils at 2190
   gasses in atmosphere:
				Nitrogen         99.6%  PP 31116.5 mb
				CarbonDioxide     0.1%  PP   24.2 mb
				Ozone             0.1%  PP   24.2 mb
				Ethanol           0.1%  PP   24.5 mb


Planet 4	
   Distance from primary:	1.413	AU
   Mass:			1.034	Earth masses
   Equatorial radius:		6474.1	km
   Density:			5.437	grams/cc
   Eccentricity of orbit:	0.138
   Surface gravity:		1.00	Earth gees
   Surface pressure:		0.795	Earth atmospheres
   Surface temperature:		9.40	degrees Celcius
   Normal daytime temperature:	14.14	degrees Celcius
   Normal night temperature:	4.36	degrees Celcius
   Maximum temperature:   	37.69	degrees Celcius
   Minimum temperature:   	-20.56	degrees Celcius
   Escape Velocity:		11.29	km/sec
   Molecular weight retained:	6.23 and above
   Surface acceleration:	983.81	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.221
   Length of year:		584.39	days
   Length of day:		15.33	hours
   Boiling point of water:	93.8	degrees Celcius
   Hydrosphere percentage:	53.01
   Cloud cover percentage:	26.16
   Ice cover percentage:	3.16
   liquids at surface:
				Ethanol      melts at -114  boils at 73
				Mercury      melts at -39   boils at 346
				Bromine      melts at -7    boils at 54
				Water        melts at 0     boils at 94
   gasses in atmosphere:
				Oxygen           24.3%  PP  193.6 mb
				Nitrogen         75.5%  PP  600.3 mb


Planet 5	*gas giant*
   Distance from primary:	2.107	AU
   Mass:			78.134	Earth masses
   Equatorial radius:		39407.8	km
   Density:			1.822	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		39.77	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	2006.39	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.543
   Length of year:		1064.04	days
   Length of day:		9.12	hours


Planet 6	*gas giant*
   Distance from primary:	3.115	AU
   Mass:			34.647	Earth masses
   Equatorial radius:		32115.4	km
   Density:			1.493	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		29.33	km/sec
   Molecular weight retained:	0.92 and above
   Surface acceleration:	1339.60	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.520
   Length of year:		1912.18	days
   Length of day:		11.17	hours


Planet 7	*gas giant*
   Distance from primary:	8.574	AU
   Mass:			1171.219	Earth masses
   Equatorial radius:		97569.4	km
   Density:			1.799	grams/cc
   Eccentricity of orbit:	0.064
   Escape Velocity:		97.85	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4906.26	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.498
   Length of year:		8720.44	days
   Length of day:		5.84	hours


Planet 8	
   Distance from primary:	14.800	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		4850.5	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.019	Earth atmospheres
   Surface temperature:		-195.69	degrees Celcius
   Normal daytime temperature:	-187.76	degrees Celcius
   Normal night temperature:	-203.75	degrees Celcius
   Maximum temperature:   	-170.71	degrees Celcius
   Minimum temperature:   	-222.01	degrees Celcius
   Escape Velocity:		5.41	km/sec
   Molecular weight retained:	27.16 and above
   Surface acceleration:	301.26	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.265
   Length of year:		19807.90	days
   Length of day:		27.61	hours
   Boiling point of water:	15.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	19.36


Planet 9	*gas giant*
   Distance from primary:	22.059	AU
   Mass:			78.690	Earth masses
   Equatorial radius:		48025.4	km
   Density:			1.014	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		36.15	km/sec
   Molecular weight retained:	0.61 and above
   Surface acceleration:	1360.56	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.508
   Length of year:		36039.63	days
   Length of day:		11.08	hours


Planet 10	*gas giant*
   Distance from primary:	42.204	AU
   Mass:			1.117	Earth masses
   Equatorial radius:		14656.2	km
   Density:			0.506	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		7.80	km/sec
   Molecular weight retained:	13.06 and above
   Surface acceleration:	207.42	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.451
   Length of year:		95385.96	days
   Length of day:		28.38	hours


