                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486a5
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6263 K
Stellar class: F8
Age: 2.176 billion years  (4.660 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.315 AU	no atmosphere
2	  0.476 AU	no atmosphere
3	  0.593 AU	no atmosphere
4	  0.952 AU	greenhouse
5	  1.394 AU	
6	  2.198 AU	gas giant
7	  4.708 AU	gas giant
8	  9.913 AU	gas giant
9	 23.925 AU	no atmosphere
10	 43.657 AU	gas giant



Planet 1	
   Distance from primary:	0.315	AU
   Mass:			0.059	Earth masses
   Equatorial radius:		2520.6	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		279.34	degrees Celcius
   Normal daytime temperature:	502.34	degrees Celcius
   Normal night temperature:	-171.73	degrees Celcius
   Maximum temperature:   	505.35	degrees Celcius
   Minimum temperature:   	-182.61	degrees Celcius
   Escape Velocity:		4.33	km/sec
   Molecular weight retained:	42.38 and above
   Surface acceleration:	371.54	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.051
   Length of year:		61.57	days
   Length of day:		1477.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.476	AU
   Mass:			0.101	Earth masses
   Equatorial radius:		3005.2	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		174.97	degrees Celcius
   Maximum temperature:   	379.15	degrees Celcius
   Minimum temperature:   	-211.88	degrees Celcius
   Escape Velocity:		5.17	km/sec
   Molecular weight retained:	29.75 and above
   Surface acceleration:	443.96	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.065
   Length of year:		114.15	days
   Length of day:		2739.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.593	AU
   Mass:			0.531	Earth masses
   Equatorial radius:		5205.4	km
   Density:			5.368	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.80	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		128.33	degrees Celcius
   Maximum temperature:   	321.36	degrees Celcius
   Minimum temperature:   	-220.93	degrees Celcius
   Escape Velocity:		9.02	km/sec
   Molecular weight retained:	9.76 and above
   Surface acceleration:	780.94	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.063
   Length of year:		158.92	days
   Length of day:		3814.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.952	AU
   Mass:			1.715	Earth masses
   Equatorial radius:		7626.7	km
   Density:			5.515	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		1.20	Earth gees
   Surface pressure:		292.137	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		562.14	degrees Celcius
   Maximum temperature:   	564.25	degrees Celcius
   Minimum temperature:   	556.94	degrees Celcius
   Escape Velocity:		13.39	km/sec
   Molecular weight retained:	4.43 and above
   Surface acceleration:	1175.59	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.418
   Length of year:		323.14	days
   Length of day:		14.35	hours
   Boiling point of water:	369.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1363
				Cesium       melts at 28    boils at 1411
				Gallium      melts at 30    boils at 4335
				Rubidium     melts at 39    boils at 1382
				Potassium    melts at 63    boils at 1516
				Sodium       melts at 98    boils at 1715
				Indium       melts at 157   boils at 3779
				Lithium      melts at 181   boils at 2517
				Selenium     melts at 217   boils at 1377
				Tin          melts at 232   boils at 4714
				Polonium     melts at 254   boils at 1854
				Bismuth      melts at 271   boils at 2890
				Thallium     melts at 304   boils at 2706
				Cadmium      melts at 321   boils at 1514
				Lead         melts at 328   boils at 3212
				Zinc         melts at 420   boils at 1759
				Tellurium    melts at 450   boils at 1902
   gasses in atmosphere:
				Sulfur           18.4%  PP 53628.0 mb
				Nitrogen         81.1%  PP 236891.8 mb
				Phosphorus        0.4%  PP 1073.0 mb


Planet 5	
   Distance from primary:	1.394	AU
   Mass:			0.598	Earth masses
   Equatorial radius:		5414.2	km
   Density:			5.378	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.315	Earth atmospheres
   Surface temperature:		7.81	degrees Celcius
   Normal daytime temperature:	15.71	degrees Celcius
   Normal night temperature:	-0.50	degrees Celcius
   Maximum temperature:   	39.20	degrees Celcius
   Minimum temperature:   	-25.25	degrees Celcius
   Escape Velocity:		9.39	km/sec
   Molecular weight retained:	9.01 and above
   Surface acceleration:	813.81	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.184
   Length of year:		572.48	days
   Length of day:		16.91	hours
   Boiling point of water:	70.7	degrees Celcius
   Hydrosphere percentage:	51.86
   Cloud cover percentage:	21.48
   Ice cover percentage:	4.14
   liquids at surface:
				Ethanol      melts at -114  boils at 51
				Mercury      melts at -39   boils at 307
				Bromine      melts at -7    boils at 33
				Water        melts at 0     boils at 71
   gasses in atmosphere:
				Oxygen           53.6%  PP  168.7 mb
				Nitrogen         46.3%  PP  145.5 mb


Planet 6	*gas giant*
   Distance from primary:	2.198	AU
   Mass:			6.933	Earth masses
   Equatorial radius:		19506.0	km
   Density:			1.333	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		16.84	km/sec
   Molecular weight retained:	2.80 and above
   Surface acceleration:	726.67	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.505
   Length of year:		1132.56	days
   Length of day:		15.16	hours


Planet 7	*gas giant*
   Distance from primary:	4.708	AU
   Mass:			1233.338	Earth masses
   Equatorial radius:		94197.2	km
   Density:			2.106	grams/cc
   Eccentricity of orbit:	0.117
   Escape Velocity:		102.19	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5543.01	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.537
   Length of year:		3545.78	days
   Length of day:		5.49	hours


Planet 8	*gas giant*
   Distance from primary:	9.913	AU
   Mass:			741.294	Earth masses
   Equatorial radius:		86396.8	km
   Density:			1.640	grams/cc
   Eccentricity of orbit:	0.124
   Escape Velocity:		82.72	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3960.36	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.461
   Length of year:		10839.42	days
   Length of day:		6.49	hours


Planet 9	
   Distance from primary:	23.925	AU
   Mass:			0.722	Earth masses
   Equatorial radius:		7675.6	km
   Density:			2.280	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-209.87	degrees Celcius
   Normal daytime temperature:	-203.76	degrees Celcius
   Normal night temperature:	-215.94	degrees Celcius
   Maximum temperature:   	-188.00	degrees Celcius
   Minimum temperature:   	-232.84	degrees Celcius
   Escape Velocity:		8.66	km/sec
   Molecular weight retained:	10.57 and above
   Surface acceleration:	489.01	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.148
   Length of year:		40682.49	days
   Length of day:		21.67	hours
   Boiling point of water:	-24.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.11
   gasses in atmosphere:
				Neon             100.0%  PP    1.1 mb


Planet 10	*gas giant*
   Distance from primary:	43.657	AU
   Mass:			4.507	Earth masses
   Equatorial radius:		22069.0	km
   Density:			0.598	grams/cc
   Eccentricity of orbit:	0.271
   Escape Velocity:		12.76	km/sec
   Molecular weight retained:	4.87 and above
   Surface acceleration:	369.01	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.509
   Length of year:		100278.50	days
   Length of day:		21.28	hours


