                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048779
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6305 K
Stellar class: F7
Age: 3.621 billion years  (3.188 billion left on main sequence)
Habitable ecosphere radius: 1.274 AU

Planets present at:
1	  0.342 AU	no atmosphere
2	  0.413 AU	no atmosphere
3	  0.458 AU	no atmosphere
4	  0.682 AU	greenhouse
5	  0.890 AU	no atmosphere
6	  1.160 AU	greenhouse
7	  1.898 AU	gas giant
8	  3.415 AU	gas giant
9	  6.246 AU	no atmosphere
10	  7.526 AU	gas giant
11	  9.520 AU	gas giant
12	 11.866 AU	gas giant
13	 20.250 AU	gas giant
14	 30.317 AU	gas giant
15	 49.456 AU	no atmosphere



Planet 1	
   Distance from primary:	0.342	AU
   Mass:			0.039	Earth masses
   Equatorial radius:		2200.7	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		253.27	degrees Celcius
   Normal daytime temperature:	471.04	degrees Celcius
   Normal night temperature:	-179.95	degrees Celcius
   Maximum temperature:   	474.14	degrees Celcius
   Minimum temperature:   	-190.70	degrees Celcius
   Escape Velocity:		3.78	km/sec
   Molecular weight retained:	55.67 and above
   Surface acceleration:	323.97	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.086
   Length of year:		69.44	days
   Length of day:		1666.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.413	AU
   Mass:			1/120.5	Earth masses
   Equatorial radius:		1311.3	km
   Density:			5.254	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		208.75	degrees Celcius
   Maximum temperature:   	420.26	degrees Celcius
   Minimum temperature:   	-203.27	degrees Celcius
   Escape Velocity:		2.25	km/sec
   Molecular weight retained:	157.23 and above
   Surface acceleration:	192.52	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.062
   Length of year:		92.26	days
   Length of day:		2214.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.458	AU
   Mass:			0.194	Earth masses
   Equatorial radius:		3733.4	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		181.83	degrees Celcius
   Maximum temperature:   	387.40	degrees Celcius
   Minimum temperature:   	-209.62	degrees Celcius
   Escape Velocity:		6.43	km/sec
   Molecular weight retained:	19.20 and above
   Surface acceleration:	553.85	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.083
   Length of year:		107.79	days
   Length of day:		2586.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 4	
   Distance from primary:	0.682	AU
   Mass:			0.729	Earth masses
   Equatorial radius:		5776.6	km
   Density:			5.397	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.89	Earth gees
   Surface pressure:		48.043	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		284.87	degrees Celcius
   Maximum temperature:   	292.32	degrees Celcius
   Minimum temperature:   	275.75	degrees Celcius
   Escape Velocity:		10.03	km/sec
   Molecular weight retained:	7.89 and above
   Surface acceleration:	871.34	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.563
   Length of year:		195.79	days
   Length of day:		45.78	hours
   Boiling point of water:	249.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 609
				Francium     melts at 27    boils at 1057
				Cesium       melts at 28    boils at 1097
				Gallium      melts at 30    boils at 3475
				Rubidium     melts at 39    boils at 1073
				Potassium    melts at 63    boils at 1182
				Sodium       melts at 98    boils at 1344
				Sulfur       melts at 113   boils at 732
				Indium       melts at 157   boils at 3022
				Lithium      melts at 181   boils at 1996
				Selenium     melts at 217   boils at 1069
				Tin          melts at 232   boils at 3783
				Polonium     melts at 254   boils at 1456
				Bismuth      melts at 271   boils at 2300
   gasses in atmosphere:
				Nitrogen         98.9%  PP 47520.4 mb
				Phosphorus        0.7%  PP  343.3 mb
				CarbonDioxide     0.1%  PP   39.6 mb
				Ozone             0.1%  PP   37.6 mb
				Ethanol           0.1%  PP   40.3 mb


Planet 5	
   Distance from primary:	0.890	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1488.9	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		53.39	degrees Celcius
   Maximum temperature:   	227.15	degrees Celcius
   Minimum temperature:   	-230.68	degrees Celcius
   Escape Velocity:		2.55	km/sec
   Molecular weight retained:	121.89 and above
   Surface acceleration:	218.70	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.084
   Length of year:		291.54	days
   Length of day:		6996.88	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 6	
   Distance from primary:	1.160	AU
   Mass:			0.811	Earth masses
   Equatorial radius:		5981.6	km
   Density:			5.408	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.92	Earth gees
   Surface pressure:		66.605	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		279.79	degrees Celcius
   Maximum temperature:   	284.92	degrees Celcius
   Minimum temperature:   	273.82	degrees Celcius
   Escape Velocity:		10.40	km/sec
   Molecular weight retained:	7.34 and above
   Surface acceleration:	904.14	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.480
   Length of year:		434.06	days
   Length of day:		16.34	hours
   Boiling point of water:	267.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 640
				Francium     melts at 27    boils at 1104
				Cesium       melts at 28    boils at 1144
				Gallium      melts at 30    boils at 3606
				Rubidium     melts at 39    boils at 1120
				Phosphorus   melts at 44    boils at 529
				Potassium    melts at 63    boils at 1232
				Sodium       melts at 98    boils at 1400
				Sulfur       melts at 113   boils at 767
				Indium       melts at 157   boils at 3137
				Lithium      melts at 181   boils at 2075
				Selenium     melts at 217   boils at 1115
				Tin          melts at 232   boils at 3925
				Polonium     melts at 254   boils at 1517
				Bismuth      melts at 271   boils at 2390
   gasses in atmosphere:
				Nitrogen         99.7%  PP 66393.1 mb
				CarbonDioxide     0.1%  PP   45.3 mb
				Ozone             0.1%  PP   41.3 mb
				Ethanol           0.1%  PP   46.0 mb


Planet 7	*gas giant*
   Distance from primary:	1.898	AU
   Mass:			58.486	Earth masses
   Equatorial radius:		35882.6	km
   Density:			1.806	grams/cc
   Eccentricity of orbit:	0.101
   Escape Velocity:		36.06	km/sec
   Molecular weight retained:	0.61 and above
   Surface acceleration:	1811.45	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.550
   Length of year:		908.21	days
   Length of day:		9.60	hours


Planet 8	*gas giant*
   Distance from primary:	3.415	AU
   Mass:			149.985	Earth masses
   Equatorial radius:		49595.6	km
   Density:			1.754	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		49.11	km/sec
   Molecular weight retained:	0.33 and above
   Surface acceleration:	2431.65	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.501
   Length of year:		2192.73	days
   Length of day:		8.29	hours


Planet 9	
   Distance from primary:	6.246	AU
   Mass:			0.273	Earth masses
   Equatorial radius:		5587.6	km
   Density:			2.235	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.055	Earth atmospheres
   Surface temperature:		-154.56	degrees Celcius
   Normal daytime temperature:	-145.44	degrees Celcius
   Normal night temperature:	-164.01	degrees Celcius
   Maximum temperature:   	-127.74	degrees Celcius
   Minimum temperature:   	-182.98	degrees Celcius
   Escape Velocity:		6.24	km/sec
   Molecular weight retained:	20.36 and above
   Surface acceleration:	348.95	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.308
   Length of year:		5424.45	days
   Length of day:		25.66	hours
   Boiling point of water:	34.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	28.11
   liquids at surface:
				Ozone        melts at -193  boils at -140
   gasses in atmosphere:
				Argon            100.0%  PP   55.3 mb


Planet 10	*gas giant*
   Distance from primary:	7.526	AU
   Mass:			21.475	Earth masses
   Equatorial radius:		30049.3	km
   Density:			1.129	grams/cc
   Eccentricity of orbit:	0.074
   Escape Velocity:		23.87	km/sec
   Molecular weight retained:	1.39 and above
   Surface acceleration:	948.40	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.498
   Length of year:		7174.10	days
   Length of day:		13.27	hours


Planet 11	*gas giant*
   Distance from primary:	9.520	AU
   Mass:			2.184	Earth masses
   Equatorial radius:		15732.6	km
   Density:			0.800	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		10.52	km/sec
   Molecular weight retained:	7.17 and above
   Surface acceleration:	351.85	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.523
   Length of year:		10206.30	days
   Length of day:		21.79	hours


Planet 12	*gas giant*
   Distance from primary:	11.866	AU
   Mass:			164.069	Earth masses
   Equatorial radius:		56478.7	km
   Density:			1.299	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		48.13	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2051.15	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.545
   Length of year:		14200.00	days
   Length of day:		9.02	hours


Planet 13	*gas giant*
   Distance from primary:	20.250	AU
   Mass:			6.453	Earth masses
   Equatorial radius:		22980.1	km
   Density:			0.759	grams/cc
   Eccentricity of orbit:	0.085
   Escape Velocity:		14.97	km/sec
   Molecular weight retained:	3.54 and above
   Surface acceleration:	487.28	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.510
   Length of year:		31662.87	days
   Length of day:		18.52	hours


Planet 14	*gas giant*
   Distance from primary:	30.317	AU
   Mass:			15.205	Earth masses
   Equatorial radius:		30516.0	km
   Density:			0.763	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		19.93	km/sec
   Molecular weight retained:	2.00 and above
   Surface acceleration:	651.13	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.498
   Length of year:		58000.36	days
   Length of day:		16.02	hours


Planet 15	
   Distance from primary:	49.456	AU
   Mass:			0.199	Earth masses
   Equatorial radius:		5031.6	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.132
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.67	degrees Celcius
   Normal daytime temperature:	-224.50	degrees Celcius
   Normal night temperature:	-234.73	degrees Celcius
   Maximum temperature:   	-209.76	degrees Celcius
   Minimum temperature:   	-249.73	degrees Celcius
   Escape Velocity:		5.61	km/sec
   Molecular weight retained:	25.21 and above
   Surface acceleration:	312.90	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.143
   Length of year:		120846.22	days
   Length of day:		27.09	hours
   Boiling point of water:	-50.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


