                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048591
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6352 K
Stellar class: F7
Age: 2.881 billion years  (3.991 billion left on main sequence)
Habitable ecosphere radius: 1.267 AU

Planets present at:
1	  0.318 AU	no atmosphere
2	  0.447 AU	no atmosphere
3	  0.520 AU	no atmosphere
4	  0.659 AU	greenhouse
5	  1.457 AU	gas giant
6	  1.788 AU	cold
7	  4.929 AU	gas giant
8	 15.481 AU	gas giant
9	 31.034 AU	gas giant
10	 49.179 AU	no atmosphere



Planet 1	
   Distance from primary:	0.318	AU
   Mass:			0.068	Earth masses
   Equatorial radius:		2636.2	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		271.08	degrees Celcius
   Normal daytime temperature:	492.36	degrees Celcius
   Normal night temperature:	-173.64	degrees Celcius
   Maximum temperature:   	495.43	degrees Celcius
   Minimum temperature:   	-184.63	degrees Celcius
   Escape Velocity:		4.53	km/sec
   Molecular weight retained:	38.73 and above
   Surface acceleration:	388.77	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.083
   Length of year:		62.51	days
   Length of day:		1500.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.447	AU
   Mass:			0.037	Earth masses
   Equatorial radius:		2153.3	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		188.85	degrees Celcius
   Maximum temperature:   	395.84	degrees Celcius
   Minimum temperature:   	-207.59	degrees Celcius
   Escape Velocity:		3.69	km/sec
   Molecular weight retained:	58.16 and above
   Surface acceleration:	316.94	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.061
   Length of year:		104.05	days
   Length of day:		2497.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.520	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		2465.4	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		151.89	degrees Celcius
   Maximum temperature:   	350.47	degrees Celcius
   Minimum temperature:   	-215.77	degrees Celcius
   Escape Velocity:		4.23	km/sec
   Molecular weight retained:	44.31 and above
   Surface acceleration:	363.31	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.090
   Length of year:		130.48	days
   Length of day:		3131.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.659	AU
   Mass:			0.888	Earth masses
   Equatorial radius:		6161.6	km
   Density:			5.419	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.95	Earth gees
   Surface pressure:		81.874	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		507.79	degrees Celcius
   Maximum temperature:   	513.21	degrees Celcius
   Minimum temperature:   	498.96	degrees Celcius
   Escape Velocity:		10.72	km/sec
   Molecular weight retained:	6.90 and above
   Surface acceleration:	933.12	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.525
   Length of year:		186.16	days
   Length of day:		33.65	hours
   Boiling point of water:	279.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1135
				Cesium       melts at 28    boils at 1176
				Gallium      melts at 30    boils at 3693
				Rubidium     melts at 39    boils at 1151
				Potassium    melts at 63    boils at 1266
				Sodium       melts at 98    boils at 1438
				Indium       melts at 157   boils at 3215
				Lithium      melts at 181   boils at 2128
				Selenium     melts at 217   boils at 1147
				Tin          melts at 232   boils at 4019
				Polonium     melts at 254   boils at 1557
				Bismuth      melts at 271   boils at 2450
				Thallium     melts at 304   boils at 2291
				Cadmium      melts at 321   boils at 1265
				Lead         melts at 328   boils at 2727
				Zinc         melts at 420   boils at 1476
				Tellurium    melts at 450   boils at 1599
   gasses in atmosphere:
				Sulfur           23.5%  PP 19205.3 mb
				Nitrogen         75.8%  PP 62088.8 mb
				Phosphorus        0.5%  PP  381.3 mb
				CarbonDioxide     0.1%  PP   42.5 mb
				Ethanol           0.1%  PP   43.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.457	AU
   Mass:			5.126	Earth masses
   Equatorial radius:		17264.9	km
   Density:			1.421	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		15.39	km/sec
   Molecular weight retained:	3.35 and above
   Surface acceleration:	685.86	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.538
   Length of year:		611.61	days
   Length of day:		15.62	hours


Planet 6	
   Distance from primary:	1.788	AU
   Mass:			0.651	Earth masses
   Equatorial radius:		5565.7	km
   Density:			5.386	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.347	Earth atmospheres
   Surface temperature:		-61.66	degrees Celcius
   Normal daytime temperature:	-56.06	degrees Celcius
   Normal night temperature:	-67.55	degrees Celcius
   Maximum temperature:   	-35.34	degrees Celcius
   Minimum temperature:   	-89.64	degrees Celcius
   Escape Velocity:		9.66	km/sec
   Molecular weight retained:	8.51 and above
   Surface acceleration:	837.79	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.571
   Length of year:		831.75	days
   Length of day:		16.59	hours
   Boiling point of water:	73.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.16
   Ice cover percentage:	74.69
   liquids at surface:
				Ethanol      melts at -114  boils at 53
				Chlorine     melts at -101  boils at -51
				Ammonia      melts at -78   boils at -51
   gasses in atmosphere:
				Oxygen           19.8%  PP   68.8 mb
				Nitrogen         80.0%  PP  278.0 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	4.929	AU
   Mass:			2020.549	Earth masses
   Equatorial radius:		109230.1	km
   Density:			2.212	grams/cc
   Eccentricity of orbit:	0.234
   Escape Velocity:		121.46	km/sec
   Molecular weight retained:	0.05 and above
   Surface acceleration:	6753.42	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.484
   Length of year:		3796.22	days
   Length of day:		4.97	hours


Planet 8	*gas giant*
   Distance from primary:	15.481	AU
   Mass:			455.531	Earth masses
   Equatorial radius:		77816.2	km
   Density:			1.379	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		68.33	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	2999.97	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.492
   Length of year:		21177.10	days
   Length of day:		7.46	hours


Planet 9	*gas giant*
   Distance from primary:	31.034	AU
   Mass:			8.862	Earth masses
   Equatorial radius:		26133.7	km
   Density:			0.708	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		16.45	km/sec
   Molecular weight retained:	2.94 and above
   Surface acceleration:	517.45	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.472
   Length of year:		60141.67	days
   Length of day:		17.97	hours


Planet 10	
   Distance from primary:	49.179	AU
   Mass:			0.146	Earth masses
   Equatorial radius:		4548.9	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.197
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.05	degrees Celcius
   Normal daytime temperature:	-224.68	degrees Celcius
   Normal night temperature:	-235.30	degrees Celcius
   Maximum temperature:   	-207.46	degrees Celcius
   Minimum temperature:   	-252.27	degrees Celcius
   Escape Velocity:		5.06	km/sec
   Molecular weight retained:	30.95 and above
   Surface acceleration:	281.96	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.153
   Length of year:		119977.76	days
   Length of day:		28.54	hours
   Boiling point of water:	-59.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


