                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047dfa
Stellar mass: 1.09 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6157 K
Stellar class: F8
Age: 4.619 billion years  (2.511 billion left on main sequence)
Habitable ecosphere radius: 1.237 AU

Planets present at:
1	  0.337 AU	no atmosphere
2	  0.476 AU	no atmosphere
3	  0.732 AU	no atmosphere
4	  1.144 AU	greenhouse
5	  1.604 AU	gas giant
6	  4.073 AU	high pressure
7	  5.146 AU	gas giant
8	  8.209 AU	gas giant
9	 22.138 AU	gas giant
10	 46.828 AU	gas giant



Planet 1	
   Distance from primary:	0.337	AU
   Mass:			0.186	Earth masses
   Equatorial radius:		3682.0	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.088
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		252.86	degrees Celcius
   Normal daytime temperature:	470.49	degrees Celcius
   Normal night temperature:	-179.58	degrees Celcius
   Maximum temperature:   	473.70	degrees Celcius
   Minimum temperature:   	-190.76	degrees Celcius
   Escape Velocity:		6.34	km/sec
   Molecular weight retained:	19.74 and above
   Surface acceleration:	546.05	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.060
   Length of year:		68.46	days
   Length of day:		1643.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.476	AU
   Mass:			0.105	Earth masses
   Equatorial radius:		3049.0	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		167.80	degrees Celcius
   Maximum temperature:   	369.99	degrees Celcius
   Minimum temperature:   	-211.90	degrees Celcius
   Escape Velocity:		5.24	km/sec
   Molecular weight retained:	28.89 and above
   Surface acceleration:	450.54	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.075
   Length of year:		114.81	days
   Length of day:		2755.48	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.732	AU
   Mass:			0.324	Earth masses
   Equatorial radius:		4426.4	km
   Density:			5.334	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		82.05	degrees Celcius
   Maximum temperature:   	263.31	degrees Celcius
   Minimum temperature:   	-227.27	degrees Celcius
   Escape Velocity:		7.64	km/sec
   Molecular weight retained:	13.59 and above
   Surface acceleration:	659.82	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.080
   Length of year:		218.76	days
   Length of day:		5250.22	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.144	AU
   Mass:			0.625	Earth masses
   Equatorial radius:		5492.8	km
   Density:			5.382	grams/cc
   Eccentricity of orbit:	0.147
   Surface gravity:		0.84	Earth gees
   Surface pressure:		41.873	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		166.01	degrees Celcius
   Maximum temperature:   	172.28	degrees Celcius
   Minimum temperature:   	159.27	degrees Celcius
   Escape Velocity:		9.53	km/sec
   Molecular weight retained:	8.75 and above
   Surface acceleration:	826.24	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.469
   Length of year:		427.51	days
   Length of day:		17.39	hours
   Boiling point of water:	242.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 597
				Francium     melts at 27    boils at 1039
				Cesium       melts at 28    boils at 1077
				Gallium      melts at 30    boils at 3422
				Rubidium     melts at 39    boils at 1054
				Phosphorus   melts at 44    boils at 491
				Potassium    melts at 63    boils at 1161
				Sodium       melts at 98    boils at 1321
				Sulfur       melts at 113   boils at 718
				Iodine       melts at 114   boils at 360
				Indium       melts at 157   boils at 2976
   gasses in atmosphere:
				Nitrogen         99.6%  PP 41706.4 mb
				CarbonDioxide     0.1%  PP   37.4 mb
				Ozone             0.1%  PP   35.2 mb
				Ethanol           0.1%  PP   38.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.604	AU
   Mass:			20.701	Earth masses
   Equatorial radius:		26199.2	km
   Density:			1.643	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		25.10	km/sec
   Molecular weight retained:	1.26 and above
   Surface acceleration:	1202.71	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.508
   Length of year:		709.92	days
   Length of day:		11.79	hours


Planet 6	
   Distance from primary:	4.073	AU
   Mass:			8.133	Earth masses
   Equatorial radius:		12438.7	km
   Density:			6.030	grams/cc
   Eccentricity of orbit:	0.157
   Surface gravity:		2.14	Earth gees
   Surface pressure:		60.106	Earth atmospheres
   Surface temperature:		16.19	degrees Celcius
   Maximum temperature:   	20.90	degrees Celcius
   Minimum temperature:   	11.32	degrees Celcius
   Escape Velocity:		22.84	km/sec
   Molecular weight retained:	1.52 and above
   Surface acceleration:	2096.22	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.462
   Length of year:		2873.25	days
   Length of day:		10.47	hours
   Boiling point of water:	261.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	71.65
   Ice cover percentage:	1.68
   liquids at surface:
				Ethanol      melts at -114  boils at 231
				Mercury      melts at -39   boils at 630
				Bromine      melts at -7    boils at 204
				Water        melts at 0     boils at 262
   gasses in atmosphere:
				Nitrogen          0.2%  PP  106.6 mb
				Helium           99.8%  PP 59999.0 mb


Planet 7	*gas giant*
   Distance from primary:	5.146	AU
   Mass:			1.634	Earth masses
   Equatorial radius:		13768.3	km
   Density:			0.894	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		9.73	km/sec
   Molecular weight retained:	8.38 and above
   Surface acceleration:	343.82	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.509
   Length of year:		4080.85	days
   Length of day:		22.04	hours


Planet 8	*gas giant*
   Distance from primary:	8.209	AU
   Mass:			1356.133	Earth masses
   Equatorial radius:		101657.3	km
   Density:			1.842	grams/cc
   Eccentricity of orbit:	0.095
   Escape Velocity:		103.15	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5233.17	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.524
   Length of year:		8205.91	days
   Length of day:		5.65	hours


Planet 9	*gas giant*
   Distance from primary:	22.138	AU
   Mass:			136.439	Earth masses
   Equatorial radius:		56512.7	km
   Density:			1.079	grams/cc
   Eccentricity of orbit:	0.080
   Escape Velocity:		43.88	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1703.67	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.487
   Length of year:		36404.46	days
   Length of day:		9.90	hours


Planet 10	*gas giant*
   Distance from primary:	46.828	AU
   Mass:			0.489	Earth masses
   Equatorial radius:		11637.5	km
   Density:			0.442	grams/cc
   Eccentricity of orbit:	0.162
   Escape Velocity:		5.79	km/sec
   Molecular weight retained:	23.70 and above
   Surface acceleration:	143.88	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.509
   Length of year:		112020.95	days
   Length of day:		34.07	hours


