                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048665
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6395 K
Stellar class: F7
Age: 2.322 billion years  (4.523 billion left on main sequence)
Habitable ecosphere radius: 1.270 AU

Planets present at:
1	  0.370 AU	no atmosphere
2	  0.403 AU	no atmosphere
3	  0.702 AU	greenhouse
4	  1.030 AU	no atmosphere
5	  1.512 AU	cold
6	  1.752 AU	no atmosphere
7	  2.438 AU	gas giant
8	  5.793 AU	gas giant
9	 12.297 AU	gas giant
10	 25.162 AU	gas giant
11	 47.169 AU	no atmosphere



Planet 1	
   Distance from primary:	0.370	AU
   Mass:			1/188	Earth masses
   Equatorial radius:		1130.7	km
   Density:			5.252	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		232.06	degrees Celcius
   Maximum temperature:   	448.46	degrees Celcius
   Minimum temperature:   	-196.51	degrees Celcius
   Escape Velocity:		1.94	km/sec
   Molecular weight retained:	211.52 and above
   Surface acceleration:	165.95	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.083
   Length of year:		78.39	days
   Length of day:		1881.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.403	AU
   Mass:			0.036	Earth masses
   Equatorial radius:		2130.2	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		213.83	degrees Celcius
   Maximum temperature:   	426.46	degrees Celcius
   Minimum temperature:   	-202.03	degrees Celcius
   Escape Velocity:		3.65	km/sec
   Molecular weight retained:	59.43 and above
   Surface acceleration:	313.51	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.062
   Length of year:		89.04	days
   Length of day:		2137.03	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.702	AU
   Mass:			1.227	Earth masses
   Equatorial radius:		6843.9	km
   Density:			5.461	grams/cc
   Eccentricity of orbit:	0.080
   Surface gravity:		1.06	Earth gees
   Surface pressure:		119.432	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		561.50	degrees Celcius
   Maximum temperature:   	565.18	degrees Celcius
   Minimum temperature:   	554.43	degrees Celcius
   Escape Velocity:		11.96	km/sec
   Molecular weight retained:	5.55 and above
   Surface acceleration:	1044.49	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.442
   Length of year:		204.46	days
   Length of day:		19.17	hours
   Boiling point of water:	303.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1196
				Cesium       melts at 28    boils at 1239
				Gallium      melts at 30    boils at 3864
				Rubidium     melts at 39    boils at 1213
				Potassium    melts at 63    boils at 1333
				Sodium       melts at 98    boils at 1512
				Indium       melts at 157   boils at 3365
				Lithium      melts at 181   boils at 2232
				Selenium     melts at 217   boils at 1208
				Tin          melts at 232   boils at 4204
				Polonium     melts at 254   boils at 1636
				Bismuth      melts at 271   boils at 2567
				Thallium     melts at 304   boils at 2402
				Cadmium      melts at 321   boils at 1332
				Lead         melts at 328   boils at 2856
				Zinc         melts at 420   boils at 1551
				Tellurium    melts at 450   boils at 1680
   gasses in atmosphere:
				Sulfur           20.4%  PP 24352.3 mb
				Nitrogen         79.0%  PP 94338.6 mb
				Phosphorus        0.4%  PP  485.6 mb


Planet 4	
   Distance from primary:	1.030	AU
   Mass:			0.090	Earth masses
   Equatorial radius:		2895.6	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		29.69	degrees Celcius
   Normal daytime temperature:	67.49	degrees Celcius
   Normal night temperature:	-8.51	degrees Celcius
   Maximum temperature:   	96.16	degrees Celcius
   Minimum temperature:   	-37.62	degrees Celcius
   Escape Velocity:		4.98	km/sec
   Molecular weight retained:	32.06 and above
   Surface acceleration:	427.54	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.085
   Length of year:		363.63	days
   Length of day:		28.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374


Planet 5	
   Distance from primary:	1.512	AU
   Mass:			0.762	Earth masses
   Equatorial radius:		5861.0	km
   Density:			5.402	grams/cc
   Eccentricity of orbit:	0.105
   Surface gravity:		0.90	Earth gees
   Surface pressure:		0.552	Earth atmospheres
   Surface temperature:		-2.87	degrees Celcius
   Normal daytime temperature:	2.79	degrees Celcius
   Normal night temperature:	-8.86	degrees Celcius
   Maximum temperature:   	26.53	degrees Celcius
   Minimum temperature:   	-33.98	degrees Celcius
   Escape Velocity:		10.18	km/sec
   Molecular weight retained:	7.65 and above
   Surface acceleration:	884.81	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.226
   Length of year:		646.23	days
   Length of day:		16.17	hours
   Boiling point of water:	84.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	11.79
   Ice cover percentage:	11.61
   liquids at surface:
				Ethanol      melts at -114  boils at 64
				Mercury      melts at -39   boils at 330
				Bromine      melts at -7    boils at 46
   gasses in atmosphere:
				Oxygen           43.8%  PP  241.8 mb
				Nitrogen         56.0%  PP  309.1 mb


Planet 6	
   Distance from primary:	1.752	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		2667.7	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.005	Earth atmospheres
   Surface temperature:		-63.85	degrees Celcius
   Normal daytime temperature:	-42.29	degrees Celcius
   Normal night temperature:	-85.56	degrees Celcius
   Maximum temperature:   	-17.04	degrees Celcius
   Minimum temperature:   	-111.45	degrees Celcius
   Escape Velocity:		4.58	km/sec
   Molecular weight retained:	37.81 and above
   Surface acceleration:	393.47	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.404
   Length of year:		806.24	days
   Length of day:		24.41	hours
   Boiling point of water:	-4.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	45.10
   liquids at surface:
				Ethanol      melts at -114  boils at -17
   gasses in atmosphere:
				CarbonDioxide    36.5%  PP    1.9 mb
				Ozone            55.6%  PP    2.9 mb
				Krypton           6.9%  PP    0.4 mb
				Xenon             1.0%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	2.438	AU
   Mass:			89.856	Earth masses
   Equatorial radius:		41539.5	km
   Density:			1.789	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		41.54	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	2076.66	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.507
   Length of year:		1323.22	days
   Length of day:		8.97	hours


Planet 8	*gas giant*
   Distance from primary:	5.793	AU
   Mass:			574.916	Earth masses
   Equatorial radius:		76715.9	km
   Density:			1.817	grams/cc
   Eccentricity of orbit:	0.121
   Escape Velocity:		77.31	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3895.58	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.464
   Length of year:		4843.84	days
   Length of day:		6.55	hours


Planet 9	*gas giant*
   Distance from primary:	12.297	AU
   Mass:			303.659	Earth masses
   Equatorial radius:		67806.8	km
   Density:			1.390	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		59.76	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2633.77	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.489
   Length of year:		14987.41	days
   Length of day:		7.96	hours


Planet 10	*gas giant*
   Distance from primary:	25.162	AU
   Mass:			49.293	Earth masses
   Equatorial radius:		42353.2	km
   Density:			0.926	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		30.47	km/sec
   Molecular weight retained:	0.86 and above
   Surface acceleration:	1095.86	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.460
   Length of year:		43883.54	days
   Length of day:		12.35	hours


Planet 11	
   Distance from primary:	47.169	AU
   Mass:			0.300	Earth masses
   Equatorial radius:		5763.1	km
   Density:			2.238	grams/cc
   Eccentricity of orbit:	0.111
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.35	degrees Celcius
   Normal daytime temperature:	-223.35	degrees Celcius
   Normal night temperature:	-233.26	degrees Celcius
   Maximum temperature:   	-212.79	degrees Celcius
   Minimum temperature:   	-244.50	degrees Celcius
   Escape Velocity:		6.45	km/sec
   Molecular weight retained:	19.11 and above
   Surface acceleration:	360.42	cm/sec2
   Axial tilt:			69	degrees
   Planetary albedo:		0.142
   Length of year:		112638.39	days
   Length of day:		25.24	hours
   Boiling point of water:	-45.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


