                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488de
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6330 K
Stellar class: F7
Age: 5.606 billion years  (1.157 billion left on main sequence)
Habitable ecosphere radius: 1.279 AU

Planets present at:
1	  0.337 AU	no atmosphere
2	  0.426 AU	no atmosphere
3	  0.715 AU	no atmosphere
4	  1.010 AU	greenhouse
5	  1.381 AU	no atmosphere
6	  1.566 AU	gas giant
7	  2.263 AU	no atmosphere
8	  2.924 AU	cold
9	  3.958 AU	gas giant
10	  6.803 AU	gas giant
11	 16.012 AU	gas giant
12	 23.313 AU	gas giant
13	 41.362 AU	gas giant
14	 51.279 AU	no atmosphere



Planet 1	
   Distance from primary:	0.337	AU
   Mass:			0.048	Earth masses
   Equatorial radius:		2352.2	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		261.24	degrees Celcius
   Normal daytime temperature:	480.68	degrees Celcius
   Normal night temperature:	-177.95	degrees Celcius
   Maximum temperature:   	483.79	degrees Celcius
   Minimum temperature:   	-188.88	degrees Celcius
   Escape Velocity:		4.04	km/sec
   Molecular weight retained:	48.70 and above
   Surface acceleration:	346.47	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.066
   Length of year:		67.84	days
   Length of day:		1628.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.426	AU
   Mass:			0.220	Earth masses
   Equatorial radius:		3895.3	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		202.22	degrees Celcius
   Maximum temperature:   	412.26	degrees Celcius
   Minimum temperature:   	-204.78	degrees Celcius
   Escape Velocity:		6.71	km/sec
   Molecular weight retained:	17.61 and above
   Surface acceleration:	578.46	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.062
   Length of year:		96.65	days
   Length of day:		2319.62	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.715	AU
   Mass:			0.404	Earth masses
   Equatorial radius:		4757.9	km
   Density:			5.348	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		92.90	degrees Celcius
   Maximum temperature:   	277.15	degrees Celcius
   Minimum temperature:   	-226.05	degrees Celcius
   Escape Velocity:		8.23	km/sec
   Molecular weight retained:	11.73 and above
   Surface acceleration:	711.09	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.073
   Length of year:		209.93	days
   Length of day:		5038.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.010	AU
   Mass:			0.759	Earth masses
   Equatorial radius:		5853.9	km
   Density:			5.401	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.90	Earth gees
   Surface pressure:		50.501	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		281.63	degrees Celcius
   Maximum temperature:   	287.41	degrees Celcius
   Minimum temperature:   	274.94	degrees Celcius
   Escape Velocity:		10.17	km/sec
   Molecular weight retained:	7.67 and above
   Surface acceleration:	883.68	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.540
   Length of year:		352.51	days
   Length of day:		17.75	hours
   Boiling point of water:	252.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 614
				Francium     melts at 27    boils at 1064
				Cesium       melts at 28    boils at 1104
				Gallium      melts at 30    boils at 3494
				Rubidium     melts at 39    boils at 1080
				Potassium    melts at 63    boils at 1189
				Sodium       melts at 98    boils at 1352
				Sulfur       melts at 113   boils at 737
				Indium       melts at 157   boils at 3039
				Lithium      melts at 181   boils at 2007
				Selenium     melts at 217   boils at 1075
				Tin          melts at 232   boils at 3804
				Polonium     melts at 254   boils at 1465
				Bismuth      melts at 271   boils at 2313
   gasses in atmosphere:
				Nitrogen         98.9%  PP 49955.5 mb
				Phosphorus        0.7%  PP  360.3 mb
				CarbonDioxide     0.1%  PP   41.7 mb
				Ozone             0.1%  PP   37.5 mb
				Ethanol           0.1%  PP   42.5 mb


Planet 5	
   Distance from primary:	1.381	AU
   Mass:			0.037	Earth masses
   Equatorial radius:		2155.1	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-8.88	degrees Celcius
   Normal daytime temperature:	27.82	degrees Celcius
   Normal night temperature:	-45.86	degrees Celcius
   Maximum temperature:   	53.18	degrees Celcius
   Minimum temperature:   	-71.41	degrees Celcius
   Escape Velocity:		3.70	km/sec
   Molecular weight retained:	58.06 and above
   Surface acceleration:	317.20	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.061
   Length of year:		563.32	days
   Length of day:		32.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	*gas giant*
   Distance from primary:	1.566	AU
   Mass:			9.399	Earth masses
   Equatorial radius:		20711.4	km
   Density:			1.510	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		19.02	km/sec
   Molecular weight retained:	2.19 and above
   Surface acceleration:	873.78	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.497
   Length of year:		680.48	days
   Length of day:		13.83	hours


Planet 7	
   Distance from primary:	2.263	AU
   Mass:			0.078	Earth masses
   Equatorial radius:		2768.1	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.006	Earth atmospheres
   Surface temperature:		-88.34	degrees Celcius
   Normal daytime temperature:	-69.88	degrees Celcius
   Normal night temperature:	-106.93	degrees Celcius
   Maximum temperature:   	-46.14	degrees Celcius
   Minimum temperature:   	-131.44	degrees Celcius
   Escape Velocity:		4.76	km/sec
   Molecular weight retained:	35.10 and above
   Surface acceleration:	408.47	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.405
   Length of year:		1181.94	days
   Length of day:		23.83	hours
   Boiling point of water:	-1.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	45.09
   liquids at surface:
				Ethanol      melts at -114  boils at -15
   gasses in atmosphere:
				Ozone            88.8%  PP    5.6 mb
				Argon             0.2%  PP    0.0 mb
				Krypton           9.6%  PP    0.6 mb
				Xenon             1.4%  PP    0.1 mb


Planet 8	
   Distance from primary:	2.924	AU
   Mass:			0.504	Earth masses
   Equatorial radius:		5116.7	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.223	Earth atmospheres
   Surface temperature:		-110.69	degrees Celcius
   Normal daytime temperature:	-105.28	degrees Celcius
   Normal night temperature:	-116.35	degrees Celcius
   Maximum temperature:   	-84.19	degrees Celcius
   Minimum temperature:   	-139.09	degrees Celcius
   Escape Velocity:		8.86	km/sec
   Molecular weight retained:	10.11 and above
   Surface acceleration:	767.04	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.567
   Length of year:		1736.16	days
   Length of day:		17.31	hours
   Boiling point of water:	62.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	73.39
   liquids at surface:
				Ethanol      melts at -114  boils at 44
   gasses in atmosphere:
				Oxygen            2.0%  PP    4.5 mb
				Nitrogen         97.8%  PP  218.3 mb
				Ozone             0.1%  PP    0.2 mb


Planet 9	*gas giant*
   Distance from primary:	3.958	AU
   Mass:			614.829	Earth masses
   Equatorial radius:		75741.8	km
   Density:			2.019	grams/cc
   Eccentricity of orbit:	0.044
   Escape Velocity:		80.46	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4273.89	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.471
   Length of year:		2731.75	days
   Length of day:		6.25	hours


Planet 10	*gas giant*
   Distance from primary:	6.803	AU
   Mass:			469.350	Earth masses
   Equatorial radius:		73237.3	km
   Density:			1.705	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		71.49	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3489.57	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.474
   Length of year:		6155.63	days
   Length of day:		6.92	hours


Planet 11	*gas giant*
   Distance from primary:	16.012	AU
   Mass:			300.111	Earth masses
   Equatorial radius:		69034.4	km
   Density:			1.302	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		58.88	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2511.25	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.500
   Length of year:		22233.41	days
   Length of day:		8.16	hours


Planet 12	*gas giant*
   Distance from primary:	23.313	AU
   Mass:			9.586	Earth masses
   Equatorial radius:		26087.4	km
   Density:			0.770	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		17.12	km/sec
   Molecular weight retained:	2.71 and above
   Surface acceleration:	561.70	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.468
   Length of year:		39077.15	days
   Length of day:		17.25	hours


Planet 13	*gas giant*
   Distance from primary:	41.362	AU
   Mass:			0.823	Earth masses
   Equatorial radius:		13372.4	km
   Density:			0.491	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		7.01	km/sec
   Molecular weight retained:	16.17 and above
   Surface acceleration:	183.56	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.514
   Length of year:		92345.85	days
   Length of day:		30.17	hours


Planet 14	
   Distance from primary:	51.279	AU
   Mass:			0.015	Earth masses
   Equatorial radius:		2123.8	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.84	degrees Celcius
   Normal daytime temperature:	-223.52	degrees Celcius
   Normal night temperature:	-238.00	degrees Celcius
   Maximum temperature:   	-211.25	degrees Celcius
   Minimum temperature:   	-250.24	degrees Celcius
   Escape Velocity:		2.35	km/sec
   Molecular weight retained:	143.59 and above
   Surface acceleration:	130.15	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.159
   Length of year:		127474.86	days
   Length of day:		42.01	hours
   Boiling point of water:	-92.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


