                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f58
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6155 K
Stellar class: F8
Age: 5.443 billion years  (1.639 billion left on main sequence)
Habitable ecosphere radius: 1.243 AU

Planets present at:
1	  0.354 AU	no atmosphere
2	  0.564 AU	no atmosphere
3	  1.064 AU	greenhouse
4	  1.624 AU	cold
5	  2.176 AU	gas giant
6	  3.392 AU	gas giant
7	  6.002 AU	gas giant
8	 11.522 AU	gas giant
9	 16.837 AU	gas giant
10	 31.863 AU	gas giant
11	 48.291 AU	no atmosphere



Planet 1	
   Distance from primary:	0.354	AU
   Mass:			0.048	Earth masses
   Equatorial radius:		2348.6	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.78	degrees Celcius
   Normal daytime temperature:	455.97	degrees Celcius
   Normal night temperature:	-183.56	degrees Celcius
   Maximum temperature:   	459.09	degrees Celcius
   Minimum temperature:   	-194.17	degrees Celcius
   Escape Velocity:		4.03	km/sec
   Molecular weight retained:	48.85 and above
   Surface acceleration:	345.94	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.066
   Length of year:		73.45	days
   Length of day:		1762.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.564	AU
   Mass:			0.711	Earth masses
   Equatorial radius:		5729.6	km
   Density:			5.395	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.37	degrees Celcius
   Maximum temperature:   	327.54	degrees Celcius
   Minimum temperature:   	-217.90	degrees Celcius
   Escape Velocity:		9.95	km/sec
   Molecular weight retained:	8.02 and above
   Surface acceleration:	863.83	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.069
   Length of year:		148.07	days
   Length of day:		2840.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.064	AU
   Mass:			0.944	Earth masses
   Equatorial radius:		6285.8	km
   Density:			5.426	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.97	Earth gees
   Surface pressure:		74.588	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		336.97	degrees Celcius
   Maximum temperature:   	341.92	degrees Celcius
   Minimum temperature:   	330.84	degrees Celcius
   Escape Velocity:		10.95	km/sec
   Molecular weight retained:	6.62 and above
   Surface acceleration:	953.21	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.494
   Length of year:		383.40	days
   Length of day:		16.40	hours
   Boiling point of water:	274.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 651
				Francium     melts at 27    boils at 1121
				Cesium       melts at 28    boils at 1162
				Gallium      melts at 30    boils at 3653
				Rubidium     melts at 39    boils at 1137
				Potassium    melts at 63    boils at 1251
				Sodium       melts at 98    boils at 1421
				Sulfur       melts at 113   boils at 780
				Indium       melts at 157   boils at 3179
				Lithium      melts at 181   boils at 2104
				Selenium     melts at 217   boils at 1132
				Tin          melts at 232   boils at 3976
				Polonium     melts at 254   boils at 1539
				Bismuth      melts at 271   boils at 2422
				Astatine     melts at 302   boils at 622
				Thallium     melts at 304   boils at 2265
				Cadmium      melts at 321   boils at 1250
				Lead         melts at 328   boils at 2697
   gasses in atmosphere:
				Nitrogen         99.1%  PP 73893.4 mb
				Phosphorus        0.6%  PP  460.1 mb
				CarbonDioxide     0.1%  PP   51.7 mb
				Ozone             0.1%  PP   43.5 mb
				Ethanol           0.1%  PP   52.5 mb


Planet 4	
   Distance from primary:	1.624	AU
   Mass:			1.006	Earth masses
   Equatorial radius:		6416.7	km
   Density:			5.434	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.978	Earth atmospheres
   Surface temperature:		-55.72	degrees Celcius
   Normal daytime temperature:	-52.38	degrees Celcius
   Normal night temperature:	-59.25	degrees Celcius
   Maximum temperature:   	-34.37	degrees Celcius
   Minimum temperature:   	-78.48	degrees Celcius
   Escape Velocity:		11.18	km/sec
   Molecular weight retained:	6.35 and above
   Surface acceleration:	974.46	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.635
   Length of year:		722.58	days
   Length of day:		15.41	hours
   Boiling point of water:	99.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.33
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 78
				Chlorine     melts at -101  boils at -34
				Ammonia      melts at -78   boils at -34
   gasses in atmosphere:
				Nitrogen         99.8%  PP  976.2 mb
				CarbonDioxide     0.1%  PP    0.6 mb
				Ozone             0.1%  PP    0.6 mb


Planet 5	*gas giant*
   Distance from primary:	2.176	AU
   Mass:			41.644	Earth masses
   Equatorial radius:		32940.0	km
   Density:			1.663	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		31.75	km/sec
   Molecular weight retained:	0.79 and above
   Surface acceleration:	1530.54	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.538
   Length of year:		1121.35	days
   Length of day:		10.45	hours


Planet 6	*gas giant*
   Distance from primary:	3.392	AU
   Mass:			3.513	Earth masses
   Equatorial radius:		16618.2	km
   Density:			1.092	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		12.99	km/sec
   Molecular weight retained:	4.71 and above
   Surface acceleration:	507.34	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.483
   Length of year:		2181.90	days
   Length of day:		18.15	hours


Planet 7	*gas giant*
   Distance from primary:	6.002	AU
   Mass:			934.782	Earth masses
   Equatorial radius:		88823.2	km
   Density:			1.903	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		91.62	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4724.95	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.504
   Length of year:		5129.60	days
   Length of day:		5.95	hours


Planet 8	*gas giant*
   Distance from primary:	11.522	AU
   Mass:			6.149	Earth masses
   Equatorial radius:		21663.9	km
   Density:			0.863	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		15.05	km/sec
   Molecular weight retained:	3.51 and above
   Surface acceleration:	522.48	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.461
   Length of year:		13659.84	days
   Length of day:		17.88	hours


Planet 9	*gas giant*
   Distance from primary:	16.837	AU
   Mass:			217.603	Earth masses
   Equatorial radius:		63272.7	km
   Density:			1.226	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		52.37	km/sec
   Molecular weight retained:	0.29 and above
   Surface acceleration:	2167.56	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.535
   Length of year:		24122.25	days
   Length of day:		8.78	hours


Planet 10	*gas giant*
   Distance from primary:	31.863	AU
   Mass:			7.695	Earth masses
   Equatorial radius:		25174.8	km
   Density:			0.688	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		15.61	km/sec
   Molecular weight retained:	3.26 and above
   Surface acceleration:	484.21	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.510
   Length of year:		62817.49	days
   Length of day:		18.57	hours


Planet 11	
   Distance from primary:	48.291	AU
   Mass:			0.229	Earth masses
   Equatorial radius:		5269.0	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.94	degrees Celcius
   Normal daytime temperature:	-224.92	degrees Celcius
   Normal night temperature:	-234.87	degrees Celcius
   Maximum temperature:   	-211.17	degrees Celcius
   Minimum temperature:   	-249.00	degrees Celcius
   Escape Velocity:		5.88	km/sec
   Molecular weight retained:	22.95 and above
   Surface acceleration:	328.24	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.163
   Length of year:		117206.23	days
   Length of day:		26.45	hours
   Boiling point of water:	-51.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


