                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504878a
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6232 K
Stellar class: F8
Age: 4.962 billion years  (1.845 billion left on main sequence)
Habitable ecosphere radius: 1.274 AU

Planets present at:
1	  0.363 AU	no atmosphere
2	  0.590 AU	no atmosphere
3	  0.704 AU	no atmosphere
4	  0.972 AU	greenhouse
5	  1.116 AU	greenhouse
6	  1.559 AU	gas giant
7	  2.168 AU	no atmosphere
8	  2.993 AU	gas giant
9	  4.837 AU	gas giant
10	  6.420 AU	cold
11	 16.251 AU	gas giant
12	 40.934 AU	no atmosphere
13	 45.332 AU	gas giant



Planet 1	
   Distance from primary:	0.363	AU
   Mass:			0.156	Earth masses
   Equatorial radius:		3478.2	km
   Density:			5.300	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.47	degrees Celcius
   Normal daytime temperature:	455.70	degrees Celcius
   Normal night temperature:	-184.58	degrees Celcius
   Maximum temperature:   	458.81	degrees Celcius
   Minimum temperature:   	-195.15	degrees Celcius
   Escape Velocity:		5.99	km/sec
   Molecular weight retained:	22.15 and above
   Surface acceleration:	515.18	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.064
   Length of year:		76.09	days
   Length of day:		1826.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.590	AU
   Mass:			0.113	Earth masses
   Equatorial radius:		3124.5	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		128.51	degrees Celcius
   Maximum temperature:   	321.68	degrees Celcius
   Minimum temperature:   	-221.15	degrees Celcius
   Escape Velocity:		5.37	km/sec
   Molecular weight retained:	27.50 and above
   Surface acceleration:	461.88	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.077
   Length of year:		157.49	days
   Length of day:		3779.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.704	AU
   Mass:			0.267	Earth masses
   Equatorial radius:		4151.7	km
   Density:			5.323	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		95.12	degrees Celcius
   Maximum temperature:   	279.87	degrees Celcius
   Minimum temperature:   	-225.78	degrees Celcius
   Escape Velocity:		7.16	km/sec
   Molecular weight retained:	15.48 and above
   Surface acceleration:	617.63	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.071
   Length of year:		205.31	days
   Length of day:		4927.34	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.972	AU
   Mass:			0.176	Earth masses
   Equatorial radius:		3616.6	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.55	Earth gees
   Surface pressure:		2.996	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		70.34	degrees Celcius
   Normal daytime temperature:	75.94	degrees Celcius
   Normal night temperature:	63.93	degrees Celcius
   Maximum temperature:   	91.43	degrees Celcius
   Minimum temperature:   	47.75	degrees Celcius
   Escape Velocity:		6.23	km/sec
   Molecular weight retained:	20.47 and above
   Surface acceleration:	536.12	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.034
   Length of year:		332.89	days
   Length of day:		31.56	hours
   Boiling point of water:	132.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 110
				Mercury      melts at -39   boils at 412
				Water        melts at 0     boils at 133
				Francium     melts at 27    boils at 761
				Cesium       melts at 28    boils at 791
				Gallium      melts at 30    boils at 2639
				Rubidium     melts at 39    boils at 773
				Phosphorus   melts at 44    boils at 329
				Potassium    melts at 63    boils at 857
   gasses in atmosphere:
				CarbonDioxide    45.8%  PP 1371.7 mb
				Ozone            50.1%  PP 1500.5 mb
				Argon             0.2%  PP    4.7 mb
				Krypton           3.5%  PP  105.5 mb
				Xenon             0.5%  PP   13.7 mb


Planet 5	
   Distance from primary:	1.116	AU
   Mass:			0.651	Earth masses
   Equatorial radius:		5567.3	km
   Density:			5.386	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.85	Earth gees
   Surface pressure:		36.887	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		164.86	degrees Celcius
   Maximum temperature:   	171.30	degrees Celcius
   Minimum temperature:   	157.95	degrees Celcius
   Escape Velocity:		9.66	km/sec
   Molecular weight retained:	8.51 and above
   Surface acceleration:	838.05	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.502
   Length of year:		409.59	days
   Length of day:		17.44	hours
   Boiling point of water:	235.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 586
				Francium     melts at 27    boils at 1022
				Cesium       melts at 28    boils at 1060
				Gallium      melts at 30    boils at 3375
				Rubidium     melts at 39    boils at 1037
				Phosphorus   melts at 44    boils at 482
				Potassium    melts at 63    boils at 1143
				Sodium       melts at 98    boils at 1301
				Sulfur       melts at 113   boils at 706
				Iodine       melts at 114   boils at 352
				Indium       melts at 157   boils at 2935
   gasses in atmosphere:
				Nitrogen         99.6%  PP 36741.0 mb
				CarbonDioxide     0.1%  PP   32.6 mb
				Ozone             0.1%  PP   30.9 mb
				Ethanol           0.1%  PP   33.3 mb


Planet 6	*gas giant*
   Distance from primary:	1.559	AU
   Mass:			9.505	Earth masses
   Equatorial radius:		20778.2	km
   Density:			1.512	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		19.10	km/sec
   Molecular weight retained:	2.18 and above
   Surface acceleration:	877.93	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.526
   Length of year:		676.44	days
   Length of day:		13.80	hours


Planet 7	
   Distance from primary:	2.168	AU
   Mass:			0.154	Earth masses
   Equatorial radius:		3460.1	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.021	Earth atmospheres
   Surface temperature:		-82.34	degrees Celcius
   Normal daytime temperature:	-67.09	degrees Celcius
   Normal night temperature:	-97.82	degrees Celcius
   Maximum temperature:   	-43.51	degrees Celcius
   Minimum temperature:   	-122.39	degrees Celcius
   Escape Velocity:		5.95	km/sec
   Molecular weight retained:	22.39 and above
   Surface acceleration:	512.44	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.425
   Length of year:		1109.46	days
   Length of day:		21.24	hours
   Boiling point of water:	17.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	49.29
   liquids at surface:
				Ethanol      melts at -114  boils at 1
   gasses in atmosphere:
				Ozone            92.7%  PP   19.4 mb
				Argon             0.3%  PP    0.1 mb
				Krypton           6.2%  PP    1.3 mb
				Xenon             0.8%  PP    0.2 mb


Planet 8	*gas giant*
   Distance from primary:	2.993	AU
   Mass:			3.067	Earth masses
   Equatorial radius:		15774.3	km
   Density:			1.115	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		12.45	km/sec
   Molecular weight retained:	5.12 and above
   Surface acceleration:	491.57	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.453
   Length of year:		1799.46	days
   Length of day:		18.43	hours


Planet 9	*gas giant*
   Distance from primary:	4.837	AU
   Mass:			884.533	Earth masses
   Equatorial radius:		85665.2	km
   Density:			2.008	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		90.75	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4806.67	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.519
   Length of year:		3691.28	days
   Length of day:		5.90	hours


Planet 10	
   Distance from primary:	6.420	AU
   Mass:			0.607	Earth masses
   Equatorial radius:		7253.6	km
   Density:			2.269	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.227	Earth atmospheres
   Surface temperature:		-150.24	degrees Celcius
   Normal daytime temperature:	-145.15	degrees Celcius
   Normal night temperature:	-155.64	degrees Celcius
   Maximum temperature:   	-127.87	degrees Celcius
   Minimum temperature:   	-174.48	degrees Celcius
   Escape Velocity:		8.17	km/sec
   Molecular weight retained:	11.90 and above
   Surface acceleration:	460.01	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.313
   Length of year:		5652.27	days
   Length of day:		22.35	hours
   Boiling point of water:	63.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	30.85
   liquids at surface:
				Ozone        melts at -193  boils at -128
   gasses in atmosphere:
				Oxygen            5.0%  PP   11.3 mb
				Nitrogen         94.9%  PP  215.8 mb
				Methane           0.1%  PP    0.1 mb


Planet 11	*gas giant*
   Distance from primary:	16.251	AU
   Mass:			378.425	Earth masses
   Equatorial radius:		73980.7	km
   Density:			1.334	grams/cc
   Eccentricity of orbit:	0.254
   Escape Velocity:		63.87	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	2757.28	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.506
   Length of year:		22750.25	days
   Length of day:		7.78	hours


Planet 12	
   Distance from primary:	40.934	AU
   Mass:			0.152	Earth masses
   Equatorial radius:		4601.9	km
   Density:			2.219	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.59	degrees Celcius
   Normal daytime temperature:	-219.70	degrees Celcius
   Normal night temperature:	-231.39	degrees Celcius
   Maximum temperature:   	-203.05	degrees Celcius
   Minimum temperature:   	-248.25	degrees Celcius
   Escape Velocity:		5.12	km/sec
   Molecular weight retained:	30.23 and above
   Surface acceleration:	285.34	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.140
   Length of year:		90994.75	days
   Length of day:		28.37	hours
   Boiling point of water:	-55.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 13	*gas giant*
   Distance from primary:	45.332	AU
   Mass:			2.047	Earth masses
   Equatorial radius:		17582.1	km
   Density:			0.537	grams/cc
   Eccentricity of orbit:	0.210
   Escape Velocity:		9.64	km/sec
   Molecular weight retained:	8.55 and above
   Surface acceleration:	264.05	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.518
   Length of year:		106046.72	days
   Length of day:		25.15	hours


