                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486cb
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6264 K
Stellar class: F8
Age: 3.977 billion years  (2.854 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.348 AU	no atmosphere
2	  0.543 AU	no atmosphere
3	  0.695 AU	no atmosphere
4	  1.072 AU	greenhouse
5	  1.339 AU	high pressure
6	  1.762 AU	high pressure
7	  3.445 AU	gas giant
8	  7.427 AU	gas giant
9	 16.990 AU	gas giant
10	 28.919 AU	gas giant
11	 45.823 AU	no atmosphere



Planet 1	
   Distance from primary:	0.348	AU
   Mass:			0.179	Earth masses
   Equatorial radius:		3636.9	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		252.12	degrees Celcius
   Normal daytime temperature:	469.73	degrees Celcius
   Normal night temperature:	-180.96	degrees Celcius
   Maximum temperature:   	472.85	degrees Celcius
   Minimum temperature:   	-191.74	degrees Celcius
   Escape Velocity:		6.26	km/sec
   Molecular weight retained:	20.24 and above
   Surface acceleration:	539.20	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.056
   Length of year:		71.39	days
   Length of day:		1713.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.543	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		2665.8	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		145.82	degrees Celcius
   Maximum temperature:   	343.05	degrees Celcius
   Minimum temperature:   	-215.67	degrees Celcius
   Escape Velocity:		4.58	km/sec
   Molecular weight retained:	37.87 and above
   Surface acceleration:	393.19	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.071
   Length of year:		139.08	days
   Length of day:		2652.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.695	AU
   Mass:			0.387	Earth masses
   Equatorial radius:		4694.2	km
   Density:			5.345	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		97.66	degrees Celcius
   Maximum temperature:   	283.10	degrees Celcius
   Minimum temperature:   	-225.48	degrees Celcius
   Escape Velocity:		8.11	km/sec
   Molecular weight retained:	12.06 and above
   Surface acceleration:	701.20	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.067
   Length of year:		201.25	days
   Length of day:		4830.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.072	AU
   Mass:			0.469	Earth masses
   Equatorial radius:		4996.8	km
   Density:			5.358	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		0.76	Earth gees
   Surface pressure:		21.314	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		101.43	degrees Celcius
   Maximum temperature:   	109.40	degrees Celcius
   Minimum temperature:   	93.00	degrees Celcius
   Escape Velocity:		8.65	km/sec
   Molecular weight retained:	10.62 and above
   Surface acceleration:	748.29	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.435
   Length of year:		385.83	days
   Length of day:		18.79	hours
   Boiling point of water:	208.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 541
				Francium     melts at 27    boils at 954
				Cesium       melts at 28    boils at 990
				Gallium      melts at 30    boils at 3184
				Rubidium     melts at 39    boils at 968
				Phosphorus   melts at 44    boils at 442
				Potassium    melts at 63    boils at 1069
				Sodium       melts at 98    boils at 1218
   gasses in atmosphere:
				Nitrogen         99.4%  PP 21194.1 mb
				Water             0.1%  PP   12.3 mb
				CarbonDioxide     0.1%  PP   28.0 mb
				Ozone             0.1%  PP   27.9 mb
				Ethanol           0.1%  PP   28.6 mb


Planet 5	
   Distance from primary:	1.339	AU
   Mass:			2.682	Earth masses
   Equatorial radius:		8802.7	km
   Density:			5.611	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		1.41	Earth gees
   Surface pressure:		5.969	Earth atmospheres
   Surface temperature:		24.67	degrees Celcius
   Normal daytime temperature:	26.26	degrees Celcius
   Normal night temperature:	22.96	degrees Celcius
   Maximum temperature:   	36.59	degrees Celcius
   Minimum temperature:   	12.15	degrees Celcius
   Escape Velocity:		15.59	km/sec
   Molecular weight retained:	3.27 and above
   Surface acceleration:	1380.43	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.495
   Length of year:		538.63	days
   Length of day:		12.95	hours
   Boiling point of water:	156.7	degrees Celcius
   Hydrosphere percentage:	82.99
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.47
   liquids at surface:
				Ethanol      melts at -114  boils at 132
				Mercury      melts at -39   boils at 453
				Bromine      melts at -7    boils at 110
				Water        melts at 0     boils at 157
   gasses in atmosphere:
				Nitrogen          0.6%  PP   36.6 mb
				Helium           99.4%  PP 5931.8 mb


Planet 6	
   Distance from primary:	1.762	AU
   Mass:			1.964	Earth masses
   Equatorial radius:		7967.2	km
   Density:			5.541	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		1.26	Earth gees
   Surface pressure:		2.810	Earth atmospheres
   Surface temperature:		-14.64	degrees Celcius
   Normal daytime temperature:	-12.52	degrees Celcius
   Normal night temperature:	-16.89	degrees Celcius
   Maximum temperature:   	2.81	degrees Celcius
   Minimum temperature:   	-33.11	degrees Celcius
   Escape Velocity:		14.02	km/sec
   Molecular weight retained:	4.04 and above
   Surface acceleration:	1233.86	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.295
   Length of year:		813.35	days
   Length of day:		13.66	hours
   Boiling point of water:	130.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	5.61
   Ice cover percentage:	28.68
   liquids at surface:
				Ethanol      melts at -114  boils at 108
				Mercury      melts at -39   boils at 409
   gasses in atmosphere:
				Nitrogen         99.8%  PP 2805.7 mb


Planet 7	*gas giant*
   Distance from primary:	3.445	AU
   Mass:			161.432	Earth masses
   Equatorial radius:		50716.5	km
   Density:			1.766	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		50.39	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2502.82	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.547
   Length of year:		2222.50	days
   Length of day:		8.17	hours


Planet 8	*gas giant*
   Distance from primary:	7.427	AU
   Mass:			915.406	Earth masses
   Equatorial radius:		89692.3	km
   Density:			1.810	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		90.22	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4537.77	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.520
   Length of year:		7027.08	days
   Length of day:		6.07	hours


Planet 9	*gas giant*
   Distance from primary:	16.990	AU
   Mass:			76.908	Earth masses
   Equatorial radius:		46663.1	km
   Density:			1.080	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		36.26	km/sec
   Molecular weight retained:	0.60 and above
   Surface acceleration:	1408.52	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.493
   Length of year:		24340.19	days
   Length of day:		10.89	hours


Planet 10	*gas giant*
   Distance from primary:	28.919	AU
   Mass:			27.688	Earth masses
   Equatorial radius:		36209.2	km
   Density:			0.832	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		24.70	km/sec
   Molecular weight retained:	1.30 and above
   Surface acceleration:	842.17	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.519
   Length of year:		54057.89	days
   Length of day:		14.08	hours


Planet 11	
   Distance from primary:	45.823	AU
   Mass:			0.177	Earth masses
   Equatorial radius:		4840.1	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.01	degrees Celcius
   Normal daytime temperature:	-222.55	degrees Celcius
   Normal night temperature:	-233.38	degrees Celcius
   Maximum temperature:   	-208.22	degrees Celcius
   Minimum temperature:   	-248.09	degrees Celcius
   Escape Velocity:		5.39	km/sec
   Molecular weight retained:	27.28 and above
   Surface acceleration:	300.59	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.139
   Length of year:		107824.81	days
   Length of day:		27.64	hours
   Boiling point of water:	-53.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


