                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048628
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6402 K
Stellar class: F7
Age: 1.810 billion years  (5.042 billion left on main sequence)
Habitable ecosphere radius: 1.269 AU

Planets present at:
1	  0.329 AU	no atmosphere
2	  0.518 AU	no atmosphere
3	  0.662 AU	greenhouse
4	  1.116 AU	greenhouse
5	  1.437 AU	
6	  2.415 AU	gas giant
7	  4.439 AU	gas giant
8	  7.904 AU	gas giant
9	 20.436 AU	gas giant
10	 34.543 AU	gas giant
11	 48.800 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.329	AU
   Mass:			0.185	Earth masses
   Equatorial radius:		3679.6	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.100
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		264.29	degrees Celcius
   Normal daytime temperature:	483.48	degrees Celcius
   Normal night temperature:	-169.17	degrees Celcius
   Maximum temperature:   	486.99	degrees Celcius
   Minimum temperature:   	-181.86	degrees Celcius
   Escape Velocity:		6.34	km/sec
   Molecular weight retained:	19.77 and above
   Surface acceleration:	545.68	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.072
   Length of year:		65.65	days
   Length of day:		1288.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.518	AU
   Mass:			1/203	Earth masses
   Equatorial radius:		1102.1	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.111
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.21	degrees Celcius
   Maximum temperature:   	355.85	degrees Celcius
   Minimum temperature:   	-213.32	degrees Celcius
   Escape Velocity:		1.89	km/sec
   Molecular weight retained:	222.67 and above
   Surface acceleration:	161.74	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.062
   Length of year:		129.81	days
   Length of day:		2493.77	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.662	AU
   Mass:			0.771	Earth masses
   Equatorial radius:		5882.6	km
   Density:			5.403	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		0.91	Earth gees
   Surface pressure:		52.181	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		391.82	degrees Celcius
   Maximum temperature:   	398.34	degrees Celcius
   Minimum temperature:   	383.37	degrees Celcius
   Escape Velocity:		10.22	km/sec
   Molecular weight retained:	7.60 and above
   Surface acceleration:	888.28	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.592
   Length of year:		187.36	days
   Length of day:		25.42	hours
   Boiling point of water:	253.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1069
				Cesium       melts at 28    boils at 1108
				Gallium      melts at 30    boils at 3507
				Rubidium     melts at 39    boils at 1084
				Potassium    melts at 63    boils at 1194
				Sodium       melts at 98    boils at 1358
				Sulfur       melts at 113   boils at 741
				Indium       melts at 157   boils at 3051
				Lithium      melts at 181   boils at 2015
				Selenium     melts at 217   boils at 1080
				Tin          melts at 232   boils at 3818
				Polonium     melts at 254   boils at 1471
				Bismuth      melts at 271   boils at 2322
				Thallium     melts at 304   boils at 2171
				Cadmium      melts at 321   boils at 1193
				Lead         melts at 328   boils at 2586
   gasses in atmosphere:
				Nitrogen         99.1%  PP 51691.7 mb
				Phosphorus        0.6%  PP  319.9 mb
				CarbonDioxide     0.1%  PP   35.2 mb
				Ozone             0.1%  PP   34.5 mb
				Ethanol           0.1%  PP   35.7 mb


Planet 4	
   Distance from primary:	1.116	AU
   Mass:			1.704	Earth masses
   Equatorial radius:		7611.8	km
   Density:			5.514	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		1.20	Earth gees
   Surface pressure:		226.095	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		449.74	degrees Celcius
   Maximum temperature:   	452.56	degrees Celcius
   Minimum temperature:   	445.01	degrees Celcius
   Escape Velocity:		13.36	km/sec
   Molecular weight retained:	4.45 and above
   Surface acceleration:	1173.06	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.468
   Length of year:		410.25	days
   Length of day:		14.11	hours
   Boiling point of water:	349.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1311
				Cesium       melts at 28    boils at 1358
				Gallium      melts at 30    boils at 4190
				Rubidium     melts at 39    boils at 1329
				Potassium    melts at 63    boils at 1459
				Sodium       melts at 98    boils at 1652
				Indium       melts at 157   boils at 3651
				Lithium      melts at 181   boils at 2428
				Selenium     melts at 217   boils at 1324
				Tin          melts at 232   boils at 4556
				Polonium     melts at 254   boils at 1786
				Bismuth      melts at 271   boils at 2790
				Thallium     melts at 304   boils at 2612
				Cadmium      melts at 321   boils at 1458
				Lead         melts at 328   boils at 3102
				Zinc         melts at 420   boils at 1695
				Tellurium    melts at 450   boils at 1833
   gasses in atmosphere:
				Sulfur           18.0%  PP 40719.4 mb
				Nitrogen         81.4%  PP 184133.5 mb
				Phosphorus        0.4%  PP  815.4 mb


Planet 5	
   Distance from primary:	1.437	AU
   Mass:			0.645	Earth masses
   Equatorial radius:		5548.3	km
   Density:			5.385	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.431	Earth atmospheres
   Surface temperature:		6.48	degrees Celcius
   Normal daytime temperature:	13.22	degrees Celcius
   Normal night temperature:	-0.63	degrees Celcius
   Maximum temperature:   	36.38	degrees Celcius
   Minimum temperature:   	-25.09	degrees Celcius
   Escape Velocity:		9.63	km/sec
   Molecular weight retained:	8.57 and above
   Surface acceleration:	835.03	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.175
   Length of year:		599.16	days
   Length of day:		16.65	hours
   Boiling point of water:	78.2	degrees Celcius
   Hydrosphere percentage:	62.80
   Cloud cover percentage:	23.81
   Ice cover percentage:	4.72
   liquids at surface:
				Ethanol      melts at -114  boils at 58
				Mercury      melts at -39   boils at 320
				Bromine      melts at -7    boils at 40
				Water        melts at 0     boils at 78
   gasses in atmosphere:
				Oxygen           44.1%  PP  190.2 mb
				Nitrogen         55.7%  PP  240.4 mb


Planet 6	*gas giant*
   Distance from primary:	2.415	AU
   Mass:			82.382	Earth masses
   Equatorial radius:		40470.9	km
   Density:			1.773	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		40.29	km/sec
   Molecular weight retained:	0.49 and above
   Surface acceleration:	2005.78	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.451
   Length of year:		1304.75	days
   Length of day:		9.13	hours


Planet 7	*gas giant*
   Distance from primary:	4.439	AU
   Mass:			8.396	Earth masses
   Equatorial radius:		21873.3	km
   Density:			1.145	grams/cc
   Eccentricity of orbit:	0.053
   Escape Velocity:		17.50	km/sec
   Molecular weight retained:	2.59 and above
   Surface acceleration:	699.79	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.475
   Length of year:		3252.85	days
   Length of day:		15.45	hours


Planet 8	*gas giant*
   Distance from primary:	7.904	AU
   Mass:			1415.537	Earth masses
   Equatorial radius:		102398.4	km
   Density:			1.881	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		105.00	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5383.62	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.510
   Length of year:		7712.79	days
   Length of day:		5.57	hours


Planet 9	*gas giant*
   Distance from primary:	20.436	AU
   Mass:			136.739	Earth masses
   Equatorial radius:		56055.9	km
   Density:			1.108	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		44.11	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1735.36	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.516
   Length of year:		32119.84	days
   Length of day:		9.81	hours


Planet 10	*gas giant*
   Distance from primary:	34.543	AU
   Mass:			2.338	Earth masses
   Equatorial radius:		17873.5	km
   Density:			0.584	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		10.21	km/sec
   Molecular weight retained:	7.61 and above
   Surface acceleration:	291.81	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.527
   Length of year:		70600.00	days
   Length of day:		23.93	hours


Planet 11	
   Distance from primary:	48.800	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		3599.2	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.88	degrees Celcius
   Normal daytime temperature:	-223.90	degrees Celcius
   Normal night temperature:	-235.74	degrees Celcius
   Maximum temperature:   	-213.46	degrees Celcius
   Minimum temperature:   	-246.64	degrees Celcius
   Escape Velocity:		4.00	km/sec
   Molecular weight retained:	49.70 and above
   Surface acceleration:	221.88	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.154
   Length of year:		118548.83	days
   Length of day:		32.17	hours
   Boiling point of water:	-71.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


