                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488ee
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6297 K
Stellar class: F8
Age: 4.729 billion years  (2.032 billion left on main sequence)
Habitable ecosphere radius: 1.280 AU

Planets present at:
1	  0.360 AU	no atmosphere
2	  0.419 AU	no atmosphere
3	  0.557 AU	no atmosphere
4	  0.715 AU	no atmosphere
5	  0.954 AU	greenhouse
6	  1.296 AU	gas giant
7	  2.029 AU	cold
8	  3.298 AU	gas giant
9	  6.502 AU	gas giant
10	  9.307 AU	gas giant
11	 16.091 AU	gas giant
12	 45.811 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.360	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2076.3	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.125
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		243.45	degrees Celcius
   Normal daytime temperature:	458.41	degrees Celcius
   Normal night temperature:	-175.86	degrees Celcius
   Maximum temperature:   	461.97	degrees Celcius
   Minimum temperature:   	-188.34	degrees Celcius
   Escape Velocity:		3.56	km/sec
   Molecular weight retained:	62.57 and above
   Surface acceleration:	305.51	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.069
   Length of year:		74.93	days
   Length of day:		1398.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.419	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		2296.7	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		207.90	degrees Celcius
   Maximum temperature:   	419.16	degrees Celcius
   Minimum temperature:   	-203.43	degrees Celcius
   Escape Velocity:		3.94	km/sec
   Molecular weight retained:	51.10 and above
   Surface acceleration:	338.22	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.052
   Length of year:		94.03	days
   Length of day:		2256.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.557	AU
   Mass:			0.127	Earth masses
   Equatorial radius:		3251.2	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.067
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		141.90	degrees Celcius
   Maximum temperature:   	338.27	degrees Celcius
   Minimum temperature:   	-218.53	degrees Celcius
   Escape Velocity:		5.59	km/sec
   Molecular weight retained:	25.38 and above
   Surface acceleration:	480.93	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.070
   Length of year:		144.32	days
   Length of day:		3463.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.715	AU
   Mass:			0.211	Earth masses
   Equatorial radius:		3843.9	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		93.33	degrees Celcius
   Maximum temperature:   	277.72	degrees Celcius
   Minimum temperature:   	-226.01	degrees Celcius
   Escape Velocity:		6.62	km/sec
   Molecular weight retained:	18.09 and above
   Surface acceleration:	570.65	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.070
   Length of year:		209.75	days
   Length of day:		5033.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.954	AU
   Mass:			0.396	Earth masses
   Equatorial radius:		4729.6	km
   Density:			5.346	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.72	Earth gees
   Surface pressure:		12.203	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		94.01	degrees Celcius
   Maximum temperature:   	104.86	degrees Celcius
   Minimum temperature:   	82.52	degrees Celcius
   Escape Velocity:		8.18	km/sec
   Molecular weight retained:	11.87 and above
   Surface acceleration:	706.70	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.523
   Length of year:		323.28	days
   Length of day:		22.20	hours
   Boiling point of water:	184.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 500
				Water        melts at 0     boils at 185
				Francium     melts at 27    boils at 892
				Cesium       melts at 28    boils at 927
				Gallium      melts at 30    boils at 3009
				Rubidium     melts at 39    boils at 906
				Phosphorus   melts at 44    boils at 406
				Potassium    melts at 63    boils at 1001
   gasses in atmosphere:
				Nitrogen         99.2%  PP 12103.0 mb
				CarbonDioxide     0.2%  PP   27.2 mb
				Methane           0.1%  PP    6.9 mb
				Ammonia           0.1%  PP    8.0 mb
				Ozone             0.2%  PP   27.8 mb
				Ethanol           0.2%  PP   28.0 mb


Planet 6	*gas giant*
   Distance from primary:	1.296	AU
   Mass:			4.814	Earth masses
   Equatorial radius:		16772.3	km
   Density:			1.456	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		15.13	km/sec
   Molecular weight retained:	3.47 and above
   Surface acceleration:	682.38	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.492
   Length of year:		512.29	days
   Length of day:		15.68	hours


Planet 7	
   Distance from primary:	2.029	AU
   Mass:			0.788	Earth masses
   Equatorial radius:		5924.6	km
   Density:			5.405	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.660	Earth atmospheres
   Surface temperature:		-83.01	degrees Celcius
   Normal daytime temperature:	-79.36	degrees Celcius
   Normal night temperature:	-86.85	degrees Celcius
   Maximum temperature:   	-60.23	degrees Celcius
   Minimum temperature:   	-107.42	degrees Celcius
   Escape Velocity:		10.30	km/sec
   Molecular weight retained:	7.49 and above
   Surface acceleration:	895.01	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.671
   Length of year:		1003.54	days
   Length of day:		16.04	hours
   Boiling point of water:	88.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 68
				Chlorine     melts at -101  boils at -41
   gasses in atmosphere:
				Oxygen            0.4%  PP    2.6 mb
				Nitrogen         99.5%  PP  656.7 mb
				Ozone             0.1%  PP    0.4 mb


Planet 8	*gas giant*
   Distance from primary:	3.298	AU
   Mass:			338.209	Earth masses
   Equatorial radius:		62663.8	km
   Density:			1.961	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		65.61	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3434.72	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.479
   Length of year:		2078.33	days
   Length of day:		6.97	hours


Planet 9	*gas giant*
   Distance from primary:	6.502	AU
   Mass:			23.950	Earth masses
   Equatorial radius:		30633.8	km
   Density:			1.189	grams/cc
   Eccentricity of orbit:	0.160
   Escape Velocity:		24.97	km/sec
   Molecular weight retained:	1.27 and above
   Surface acceleration:	1017.75	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.489
   Length of year:		5755.60	days
   Length of day:		12.81	hours


Planet 10	*gas giant*
   Distance from primary:	9.307	AU
   Mass:			57.998	Earth masses
   Equatorial radius:		40851.6	km
   Density:			1.214	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		33.65	km/sec
   Molecular weight retained:	0.70 and above
   Surface acceleration:	1385.89	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.463
   Length of year:		9855.35	days
   Length of day:		10.98	hours


Planet 11	*gas giant*
   Distance from primary:	16.091	AU
   Mass:			490.676	Earth masses
   Equatorial radius:		79709.6	km
   Density:			1.382	grams/cc
   Eccentricity of orbit:	0.083
   Escape Velocity:		70.07	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3079.73	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.507
   Length of year:		22390.80	days
   Length of day:		7.36	hours


Planet 12	*gas giant*
   Distance from primary:	45.811	AU
   Mass:			0.820	Earth masses
   Equatorial radius:		13470.1	km
   Density:			0.479	grams/cc
   Eccentricity of orbit:	0.109
   Escape Velocity:		6.97	km/sec
   Molecular weight retained:	16.36 and above
   Surface acceleration:	180.15	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.485
   Length of year:		107635.12	days
   Length of day:		30.45	hours


