                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047bb3
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6043 K
Stellar class: F9
Age: 2.940 billion years  (4.270 billion left on main sequence)
Habitable ecosphere radius: 1.229 AU

Planets present at:
1	  0.376 AU	no atmosphere
2	  0.581 AU	no atmosphere
3	  0.639 AU	greenhouse
4	  1.022 AU	greenhouse
5	  2.654 AU	gas giant
6	  6.422 AU	gas giant
7	  8.926 AU	gas giant
8	 22.562 AU	no atmosphere
9	 27.877 AU	no atmosphere
10	 32.848 AU	gas giant
11	 44.348 AU	no atmosphere
12	 49.491 AU	no atmosphere



Planet 1	
   Distance from primary:	0.376	AU
   Mass:			0.141	Earth masses
   Equatorial radius:		3362.5	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		220.93	degrees Celcius
   Normal daytime temperature:	431.94	degrees Celcius
   Normal night temperature:	-189.14	degrees Celcius
   Maximum temperature:   	435.09	degrees Celcius
   Minimum temperature:   	-199.51	degrees Celcius
   Escape Velocity:		5.79	km/sec
   Molecular weight retained:	23.72 and above
   Surface acceleration:	497.71	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.075
   Length of year:		80.85	days
   Length of day:		1940.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.581	AU
   Mass:			0.035	Earth masses
   Equatorial radius:		2120.6	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		125.34	degrees Celcius
   Maximum temperature:   	317.71	degrees Celcius
   Minimum temperature:   	-221.43	degrees Celcius
   Escape Velocity:		3.64	km/sec
   Molecular weight retained:	59.97 and above
   Surface acceleration:	312.09	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.069
   Length of year:		154.94	days
   Length of day:		3718.64	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.639	AU
   Mass:			0.659	Earth masses
   Equatorial radius:		5589.5	km
   Density:			5.387	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.86	Earth gees
   Surface pressure:		41.199	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		302.28	degrees Celcius
   Maximum temperature:   	312.30	degrees Celcius
   Minimum temperature:   	288.86	degrees Celcius
   Escape Velocity:		9.70	km/sec
   Molecular weight retained:	8.44 and above
   Surface acceleration:	841.56	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.501
   Length of year:		178.82	days
   Length of day:		90.87	hours
   Boiling point of water:	241.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 595
				Francium     melts at 27    boils at 1037
				Cesium       melts at 28    boils at 1075
				Gallium      melts at 30    boils at 3416
				Rubidium     melts at 39    boils at 1052
				Potassium    melts at 63    boils at 1159
				Sodium       melts at 98    boils at 1319
				Sulfur       melts at 113   boils at 717
				Indium       melts at 157   boils at 2971
				Lithium      melts at 181   boils at 1960
				Selenium     melts at 217   boils at 1048
				Tin          melts at 232   boils at 3719
				Polonium     melts at 254   boils at 1429
				Bismuth      melts at 271   boils at 2259
				Astatine     melts at 302   boils at 568
   gasses in atmosphere:
				Nitrogen         98.9%  PP 40733.9 mb
				Phosphorus        0.7%  PP  305.7 mb
				CarbonDioxide     0.1%  PP   35.1 mb
				Ozone             0.1%  PP   34.3 mb
				Ethanol           0.1%  PP   35.8 mb


Planet 4	
   Distance from primary:	1.022	AU
   Mass:			0.794	Earth masses
   Equatorial radius:		5940.1	km
   Density:			5.406	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.91	Earth gees
   Surface pressure:		54.606	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		301.86	degrees Celcius
   Maximum temperature:   	307.58	degrees Celcius
   Minimum temperature:   	295.15	degrees Celcius
   Escape Velocity:		10.33	km/sec
   Molecular weight retained:	7.45 and above
   Surface acceleration:	897.49	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.434
   Length of year:		361.96	days
   Length of day:		16.70	hours
   Boiling point of water:	256.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 621
				Francium     melts at 27    boils at 1075
				Cesium       melts at 28    boils at 1115
				Gallium      melts at 30    boils at 3525
				Rubidium     melts at 39    boils at 1091
				Potassium    melts at 63    boils at 1201
				Sodium       melts at 98    boils at 1366
				Sulfur       melts at 113   boils at 746
				Indium       melts at 157   boils at 3066
				Lithium      melts at 181   boils at 2026
				Selenium     melts at 217   boils at 1087
				Tin          melts at 232   boils at 3837
				Polonium     melts at 254   boils at 1480
				Bismuth      melts at 271   boils at 2334
   gasses in atmosphere:
				Nitrogen         99.1%  PP 54098.8 mb
				Phosphorus        0.6%  PP  333.0 mb
				CarbonDioxide     0.1%  PP   36.7 mb
				Ozone             0.1%  PP   34.7 mb
				Ethanol           0.1%  PP   37.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.654	AU
   Mass:			719.754	Earth masses
   Equatorial radius:		76963.7	km
   Density:			2.253	grams/cc
   Eccentricity of orbit:	0.307
   Escape Velocity:		86.36	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4845.64	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.467
   Length of year:		1512.11	days
   Length of day:		5.87	hours


Planet 6	*gas giant*
   Distance from primary:	6.422	AU
   Mass:			444.147	Earth masses
   Equatorial radius:		71964.7	km
   Density:			1.700	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		70.16	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3420.00	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.460
   Length of year:		5694.48	days
   Length of day:		6.99	hours


Planet 7	*gas giant*
   Distance from primary:	8.926	AU
   Mass:			48.721	Earth masses
   Equatorial radius:		38823.0	km
   Density:			1.188	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		31.64	km/sec
   Molecular weight retained:	0.79 and above
   Surface acceleration:	1289.07	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.472
   Length of year:		9335.77	days
   Length of day:		11.38	hours


Planet 8	
   Distance from primary:	22.562	AU
   Mass:			3.978	Earth masses
   Equatorial radius:		13166.5	km
   Density:			2.487	grams/cc
   Eccentricity of orbit:	0.218
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.043	Earth atmospheres
   Surface temperature:		-206.65	degrees Celcius
   Normal daytime temperature:	-203.10	degrees Celcius
   Normal night temperature:	-210.25	degrees Celcius
   Maximum temperature:   	-184.11	degrees Celcius
   Minimum temperature:   	-230.97	degrees Celcius
   Escape Velocity:		15.52	km/sec
   Molecular weight retained:	3.29 and above
   Surface acceleration:	915.20	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.165
   Length of year:		37516.83	days
   Length of day:		15.84	hours
   Boiling point of water:	29.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.27
   liquids at surface:
				Fluorine     melts at -220  boils at -204
				Oxygen       melts at -218  boils at -200
   gasses in atmosphere:
				Helium           100.0%  PP   42.6 mb


Planet 9	
   Distance from primary:	27.877	AU
   Mass:			0.142	Earth masses
   Equatorial radius:		4504.7	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-216.92	degrees Celcius
   Normal daytime temperature:	-209.89	degrees Celcius
   Normal night temperature:	-223.90	degrees Celcius
   Maximum temperature:   	-194.59	degrees Celcius
   Minimum temperature:   	-239.90	degrees Celcius
   Escape Velocity:		5.01	km/sec
   Molecular weight retained:	31.57 and above
   Surface acceleration:	279.14	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.161
   Length of year:		51527.64	days
   Length of day:		28.69	hours
   Boiling point of water:	-56.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   liquids at surface:
				Fluorine     melts at -220  boils at -217
				Oxygen       melts at -218  boils at -213


Planet 10	*gas giant*
   Distance from primary:	32.848	AU
   Mass:			5.271	Earth masses
   Equatorial radius:		22622.9	km
   Density:			0.650	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		13.63	km/sec
   Molecular weight retained:	4.27 and above
   Surface acceleration:	410.72	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.462
   Length of year:		65906.51	days
   Length of day:		20.17	hours


Planet 11	
   Distance from primary:	44.348	AU
   Mass:			0.226	Earth masses
   Equatorial radius:		5246.2	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.26	degrees Celcius
   Normal daytime temperature:	-223.03	degrees Celcius
   Normal night temperature:	-233.40	degrees Celcius
   Maximum temperature:   	-212.65	degrees Celcius
   Minimum temperature:   	-244.43	degrees Celcius
   Escape Velocity:		5.86	km/sec
   Molecular weight retained:	23.15 and above
   Surface acceleration:	326.76	cm/sec2
   Axial tilt:			69	degrees
   Planetary albedo:		0.158
   Length of year:		103392.54	days
   Length of day:		26.51	hours
   Boiling point of water:	-50.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 12	
   Distance from primary:	49.491	AU
   Mass:			0.017	Earth masses
   Equatorial radius:		2208.7	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		0.14	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.85	degrees Celcius
   Normal daytime temperature:	-223.65	degrees Celcius
   Normal night temperature:	-237.89	degrees Celcius
   Maximum temperature:   	-212.05	degrees Celcius
   Minimum temperature:   	-249.57	degrees Celcius
   Escape Velocity:		2.45	km/sec
   Molecular weight retained:	132.74 and above
   Surface acceleration:	135.38	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.152
   Length of year:		121887.64	days
   Length of day:		41.19	hours
   Boiling point of water:	-91.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


