                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048966
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6370 K
Stellar class: F7
Age: 2.708 billion years  (4.038 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.475 AU	no atmosphere
2	  0.551 AU	no atmosphere
3	  0.925 AU	greenhouse
4	  1.600 AU	gas giant
5	  3.912 AU	gas giant
6	  6.336 AU	gas giant
7	 12.539 AU	gas giant
8	 28.408 AU	gas giant
9	 47.746 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.475	AU
   Mass:			0.025	Earth masses
   Equatorial radius:		1897.5	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.163
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		178.85	degrees Celcius
   Normal daytime temperature:	380.10	degrees Celcius
   Normal night temperature:	-195.84	degrees Celcius
   Maximum temperature:   	383.61	degrees Celcius
   Minimum temperature:   	-206.73	degrees Celcius
   Escape Velocity:		3.25	km/sec
   Molecular weight retained:	74.97 and above
   Surface acceleration:	279.03	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.052
   Length of year:		113.61	days
   Length of day:		1963.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.551	AU
   Mass:			0.549	Earth masses
   Equatorial radius:		5263.3	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.177
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		145.90	degrees Celcius
   Normal daytime temperature:	339.63	degrees Celcius
   Normal night temperature:	-204.46	degrees Celcius
   Maximum temperature:   	343.16	degrees Celcius
   Minimum temperature:   	-214.72	degrees Celcius
   Escape Velocity:		9.12	km/sec
   Molecular weight retained:	9.55 and above
   Surface acceleration:	790.05	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.058
   Length of year:		141.86	days
   Length of day:		2380.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.925	AU
   Mass:			0.976	Earth masses
   Equatorial radius:		6353.2	km
   Density:			5.430	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.98	Earth gees
   Surface pressure:		102.714	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		416.83	degrees Celcius
   Maximum temperature:   	421.05	degrees Celcius
   Minimum temperature:   	410.87	degrees Celcius
   Escape Velocity:		11.07	km/sec
   Molecular weight retained:	6.48 and above
   Surface acceleration:	964.14	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.514
   Length of year:		308.56	days
   Length of day:		16.45	hours
   Boiling point of water:	293.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1171
				Cesium       melts at 28    boils at 1213
				Gallium      melts at 30    boils at 3794
				Rubidium     melts at 39    boils at 1188
				Potassium    melts at 63    boils at 1306
				Sodium       melts at 98    boils at 1482
				Sulfur       melts at 113   boils at 818
				Indium       melts at 157   boils at 3303
				Lithium      melts at 181   boils at 2189
				Selenium     melts at 217   boils at 1183
				Tin          melts at 232   boils at 4129
				Polonium     melts at 254   boils at 1604
				Bismuth      melts at 271   boils at 2519
				Thallium     melts at 304   boils at 2356
				Cadmium      melts at 321   boils at 1305
				Lead         melts at 328   boils at 2803
   gasses in atmosphere:
				Nitrogen         99.2%  PP 101852.8 mb
				Phosphorus        0.6%  PP  566.3 mb
				CarbonDioxide     0.1%  PP   61.4 mb
				Ozone             0.1%  PP   54.7 mb
				Ethanol           0.1%  PP   62.2 mb


Planet 4	*gas giant*
   Distance from primary:	1.600	AU
   Mass:			11.686	Earth masses
   Equatorial radius:		22105.4	km
   Density:			1.544	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		20.53	km/sec
   Molecular weight retained:	1.88 and above
   Surface acceleration:	953.68	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.455
   Length of year:		702.08	days
   Length of day:		13.24	hours


Planet 5	*gas giant*
   Distance from primary:	3.912	AU
   Mass:			897.866	Earth masses
   Equatorial radius:		84492.9	km
   Density:			2.124	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		92.06	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	5015.46	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.540
   Length of year:		2682.29	days
   Length of day:		5.77	hours


Planet 6	*gas giant*
   Distance from primary:	6.336	AU
   Mass:			11.168	Earth masses
   Equatorial radius:		24466.9	km
   Density:			1.088	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		19.08	km/sec
   Molecular weight retained:	2.18 and above
   Surface acceleration:	743.98	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.522
   Length of year:		5535.25	days
   Length of day:		14.98	hours


Planet 7	*gas giant*
   Distance from primary:	12.539	AU
   Mass:			636.389	Earth masses
   Equatorial radius:		84211.3	km
   Density:			1.521	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		77.64	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3578.66	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.525
   Length of year:		15395.16	days
   Length of day:		6.83	hours


Planet 8	*gas giant*
   Distance from primary:	28.408	AU
   Mass:			36.570	Earth masses
   Equatorial radius:		39185.7	km
   Density:			0.867	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		27.28	km/sec
   Molecular weight retained:	1.07 and above
   Surface acceleration:	949.75	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.457
   Length of year:		52542.78	days
   Length of day:		13.26	hours


Planet 9	
   Distance from primary:	47.746	AU
   Mass:			0.051	Earth masses
   Equatorial radius:		3208.1	km
   Density:			2.202	grams/cc
   Eccentricity of orbit:	0.134
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.05	degrees Celcius
   Normal daytime temperature:	-222.64	degrees Celcius
   Normal night temperature:	-235.33	degrees Celcius
   Maximum temperature:   	-205.05	degrees Celcius
   Minimum temperature:   	-252.41	degrees Celcius
   Escape Velocity:		3.56	km/sec
   Molecular weight retained:	62.68 and above
   Surface acceleration:	197.40	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.143
   Length of year:		114494.07	days
   Length of day:		34.11	hours
   Boiling point of water:	-74.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


