                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b8b
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6119 K
Stellar class: F9
Age: 4.570 billion years  (2.646 billion left on main sequence)
Habitable ecosphere radius: 1.228 AU

Planets present at:
1	  0.354 AU	no atmosphere
2	  0.706 AU	greenhouse
3	  1.426 AU	gas giant
4	  2.252 AU	cold
5	  3.600 AU	gas giant
6	  9.139 AU	gas giant
7	 21.383 AU	gas giant
8	 36.375 AU	no atmosphere
9	 43.058 AU	gas giant



Planet 1	
   Distance from primary:	0.354	AU
   Mass:			0.118	Earth masses
   Equatorial radius:		3169.9	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		235.88	degrees Celcius
   Maximum temperature:   	452.93	degrees Celcius
   Minimum temperature:   	-194.24	degrees Celcius
   Escape Velocity:		5.45	km/sec
   Molecular weight retained:	26.71 and above
   Surface acceleration:	468.70	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.079
   Length of year:		73.65	days
   Length of day:		1767.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.706	AU
   Mass:			1.010	Earth masses
   Equatorial radius:		6425.2	km
   Density:			5.434	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.99	Earth gees
   Surface pressure:		94.952	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		516.43	degrees Celcius
   Maximum temperature:   	521.19	degrees Celcius
   Minimum temperature:   	508.33	degrees Celcius
   Escape Velocity:		11.20	km/sec
   Molecular weight retained:	6.33 and above
   Surface acceleration:	975.84	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.445
   Length of year:		207.80	days
   Length of day:		30.09	hours
   Boiling point of water:	289.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1158
				Cesium       melts at 28    boils at 1200
				Gallium      melts at 30    boils at 3759
				Rubidium     melts at 39    boils at 1175
				Potassium    melts at 63    boils at 1292
				Sodium       melts at 98    boils at 1466
				Indium       melts at 157   boils at 3272
				Lithium      melts at 181   boils at 2168
				Selenium     melts at 217   boils at 1170
				Tin          melts at 232   boils at 4090
				Polonium     melts at 254   boils at 1588
				Bismuth      melts at 271   boils at 2495
				Thallium     melts at 304   boils at 2333
				Cadmium      melts at 321   boils at 1291
				Lead         melts at 328   boils at 2776
				Zinc         melts at 420   boils at 1505
				Tellurium    melts at 450   boils at 1630
   gasses in atmosphere:
				Sulfur           24.0%  PP 22747.2 mb
				Nitrogen         75.3%  PP 71524.7 mb
				Phosphorus        0.5%  PP  450.8 mb
				CarbonDioxide     0.1%  PP   51.2 mb
				Ethanol           0.1%  PP   52.1 mb


Planet 3	*gas giant*
   Distance from primary:	1.426	AU
   Mass:			4.978	Earth masses
   Equatorial radius:		17130.5	km
   Density:			1.413	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		15.22	km/sec
   Molecular weight retained:	3.43 and above
   Surface acceleration:	676.43	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.508
   Length of year:		596.08	days
   Length of day:		15.73	hours


Planet 4	
   Distance from primary:	2.252	AU
   Mass:			0.785	Earth masses
   Equatorial radius:		5916.6	km
   Density:			5.405	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.655	Earth atmospheres
   Surface temperature:		-99.62	degrees Celcius
   Normal daytime temperature:	-96.28	degrees Celcius
   Normal night temperature:	-103.14	degrees Celcius
   Maximum temperature:   	-78.04	degrees Celcius
   Minimum temperature:   	-122.83	degrees Celcius
   Escape Velocity:		10.28	km/sec
   Molecular weight retained:	7.51 and above
   Surface acceleration:	893.72	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.694
   Length of year:		1183.04	days
   Length of day:		16.04	hours
   Boiling point of water:	88.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 68
				Chlorine     melts at -101  boils at -41
   gasses in atmosphere:
				Oxygen            0.5%  PP    3.5 mb
				Nitrogen         99.4%  PP  650.4 mb
				Ozone             0.1%  PP    0.4 mb


Planet 5	*gas giant*
   Distance from primary:	3.600	AU
   Mass:			84.387	Earth masses
   Equatorial radius:		42249.9	km
   Density:			1.597	grams/cc
   Eccentricity of orbit:	0.119
   Escape Velocity:		39.91	km/sec
   Molecular weight retained:	0.50 and above
   Surface acceleration:	1885.22	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.547
   Length of year:		2391.54	days
   Length of day:		9.41	hours


Planet 6	*gas giant*
   Distance from primary:	9.139	AU
   Mass:			976.483	Earth masses
   Equatorial radius:		93259.6	km
   Density:			1.718	grams/cc
   Eccentricity of orbit:	0.269
   Escape Velocity:		91.38	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4477.31	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.516
   Length of year:		9659.69	days
   Length of day:		6.11	hours


Planet 7	*gas giant*
   Distance from primary:	21.383	AU
   Mass:			123.518	Earth masses
   Equatorial radius:		54772.3	km
   Density:			1.073	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		42.41	km/sec
   Molecular weight retained:	0.44 and above
   Surface acceleration:	1641.90	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.482
   Length of year:		34614.18	days
   Length of day:		10.09	hours


Planet 8	
   Distance from primary:	36.375	AU
   Mass:			0.302	Earth masses
   Equatorial radius:		5774.2	km
   Density:			2.238	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-223.14	degrees Celcius
   Normal daytime temperature:	-217.57	degrees Celcius
   Normal night temperature:	-228.64	degrees Celcius
   Maximum temperature:   	-202.30	degrees Celcius
   Minimum temperature:   	-244.54	degrees Celcius
   Escape Velocity:		6.46	km/sec
   Molecular weight retained:	19.03 and above
   Surface acceleration:	361.15	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.154
   Length of year:		76809.99	days
   Length of day:		25.22	hours
   Boiling point of water:	-43.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 9	*gas giant*
   Distance from primary:	43.058	AU
   Mass:			0.881	Earth masses
   Equatorial radius:		13730.6	km
   Density:			0.485	grams/cc
   Eccentricity of orbit:	0.107
   Escape Velocity:		7.15	km/sec
   Molecular weight retained:	15.52 and above
   Surface acceleration:	186.26	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.507
   Length of year:		98921.84	days
   Length of day:		29.95	hours


