                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f75
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6212 K
Stellar class: F8
Age: 3.037 billion years  (4.042 billion left on main sequence)
Habitable ecosphere radius: 1.243 AU

Planets present at:
1	  0.326 AU	no atmosphere
2	  0.387 AU	no atmosphere
3	  0.504 AU	no atmosphere
4	  0.662 AU	no atmosphere
5	  0.932 AU	greenhouse
6	  1.457 AU	gas giant
7	  1.973 AU	cold
8	  4.611 AU	gas giant
9	 15.010 AU	gas giant
10	 27.387 AU	gas giant
11	 50.003 AU	no atmosphere



Planet 1	
   Distance from primary:	0.326	AU
   Mass:			0.132	Earth masses
   Equatorial radius:		3289.3	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		259.85	degrees Celcius
   Normal daytime temperature:	478.84	degrees Celcius
   Normal night temperature:	-176.85	degrees Celcius
   Maximum temperature:   	481.92	degrees Celcius
   Minimum temperature:   	-187.63	degrees Celcius
   Escape Velocity:		5.66	km/sec
   Molecular weight retained:	24.79 and above
   Surface acceleration:	486.67	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.081
   Length of year:		65.09	days
   Length of day:		1562.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.387	AU
   Mass:			0.058	Earth masses
   Equatorial radius:		2504.0	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		218.50	degrees Celcius
   Maximum temperature:   	432.02	degrees Celcius
   Minimum temperature:   	-200.01	degrees Celcius
   Escape Velocity:		4.30	km/sec
   Molecular weight retained:	42.95 and above
   Surface acceleration:	369.07	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.063
   Length of year:		84.10	days
   Length of day:		2018.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.504	AU
   Mass:			0.010	Earth masses
   Equatorial radius:		1405.3	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.68	degrees Celcius
   Maximum temperature:   	356.41	degrees Celcius
   Minimum temperature:   	-214.80	degrees Celcius
   Escape Velocity:		2.41	km/sec
   Molecular weight retained:	136.86 and above
   Surface acceleration:	206.37	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.073
   Length of year:		124.85	days
   Length of day:		2996.46	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.662	AU
   Mass:			0.193	Earth masses
   Equatorial radius:		3728.5	km
   Density:			5.308	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		101.00	degrees Celcius
   Maximum temperature:   	287.24	degrees Celcius
   Minimum temperature:   	-225.03	degrees Celcius
   Escape Velocity:		6.42	km/sec
   Molecular weight retained:	19.25 and above
   Surface acceleration:	553.10	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.081
   Length of year:		188.20	days
   Length of day:		4516.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.932	AU
   Mass:			1.120	Earth masses
   Equatorial radius:		6644.0	km
   Density:			5.448	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		1.03	Earth gees
   Surface pressure:		118.846	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		390.37	degrees Celcius
   Maximum temperature:   	394.40	degrees Celcius
   Minimum temperature:   	384.83	degrees Celcius
   Escape Velocity:		11.59	km/sec
   Molecular weight retained:	5.91 and above
   Surface acceleration:	1011.60	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.589
   Length of year:		313.99	days
   Length of day:		15.99	hours
   Boiling point of water:	303.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1195
				Cesium       melts at 28    boils at 1238
				Gallium      melts at 30    boils at 3862
				Rubidium     melts at 39    boils at 1212
				Potassium    melts at 63    boils at 1332
				Sodium       melts at 98    boils at 1511
				Sulfur       melts at 113   boils at 836
				Indium       melts at 157   boils at 3363
				Lithium      melts at 181   boils at 2230
				Selenium     melts at 217   boils at 1207
				Tin          melts at 232   boils at 4202
				Polonium     melts at 254   boils at 1635
				Bismuth      melts at 271   boils at 2566
				Thallium     melts at 304   boils at 2400
				Cadmium      melts at 321   boils at 1331
				Lead         melts at 328   boils at 2854
   gasses in atmosphere:
				Nitrogen         99.2%  PP 117893.8 mb
				Phosphorus        0.5%  PP  627.8 mb
				CarbonDioxide     0.1%  PP   67.7 mb
				Ethanol           0.1%  PP   68.5 mb


Planet 6	*gas giant*
   Distance from primary:	1.457	AU
   Mass:			2.989	Earth masses
   Equatorial radius:		14775.5	km
   Density:			1.322	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		12.70	km/sec
   Molecular weight retained:	4.92 and above
   Surface acceleration:	546.07	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.487
   Length of year:		614.48	days
   Length of day:		17.51	hours


Planet 7	
   Distance from primary:	1.973	AU
   Mass:			0.462	Earth masses
   Equatorial radius:		4975.7	km
   Density:			5.357	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.195	Earth atmospheres
   Surface temperature:		-72.56	degrees Celcius
   Normal daytime temperature:	-65.39	degrees Celcius
   Normal night temperature:	-80.05	degrees Celcius
   Maximum temperature:   	-42.75	degrees Celcius
   Minimum temperature:   	-104.16	degrees Celcius
   Escape Velocity:		8.61	km/sec
   Molecular weight retained:	10.71 and above
   Surface acceleration:	744.98	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.510
   Length of year:		967.56	days
   Length of day:		17.58	hours
   Boiling point of water:	59.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	73.67
   liquids at surface:
				Ethanol      melts at -114  boils at 41
				Chlorine     melts at -101  boils at -60
				Ammonia      melts at -78   boils at -59
   gasses in atmosphere:
				Oxygen           29.4%  PP   57.3 mb
				Nitrogen         70.4%  PP  136.9 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 8	*gas giant*
   Distance from primary:	4.611	AU
   Mass:			1727.635	Earth masses
   Equatorial radius:		103937.5	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.215
   Escape Velocity:		115.14	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	6377.45	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.549
   Length of year:		3450.16	days
   Length of day:		5.12	hours


Planet 9	*gas giant*
   Distance from primary:	15.010	AU
   Mass:			10.900	Earth masses
   Equatorial radius:		26170.4	km
   Density:			0.868	grams/cc
   Eccentricity of orbit:	0.151
   Escape Velocity:		18.23	km/sec
   Molecular weight retained:	2.39 and above
   Surface acceleration:	634.67	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.542
   Length of year:		20308.80	days
   Length of day:		16.22	hours


Planet 10	*gas giant*
   Distance from primary:	27.387	AU
   Mass:			77.378	Earth masses
   Equatorial radius:		48734.6	km
   Density:			0.954	grams/cc
   Eccentricity of orbit:	0.163
   Escape Velocity:		35.59	km/sec
   Molecular weight retained:	0.63 and above
   Surface acceleration:	1299.21	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.542
   Length of year:		50047.80	days
   Length of day:		11.34	hours


Planet 11	
   Distance from primary:	50.003	AU
   Mass:			0.170	Earth masses
   Equatorial radius:		4776.8	km
   Density:			2.221	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.38	degrees Celcius
   Normal daytime temperature:	-225.17	degrees Celcius
   Normal night temperature:	-235.48	degrees Celcius
   Maximum temperature:   	-211.37	degrees Celcius
   Minimum temperature:   	-249.58	degrees Celcius
   Escape Velocity:		5.32	km/sec
   Molecular weight retained:	28.02 and above
   Surface acceleration:	296.53	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.135
   Length of year:		123485.73	days
   Length of day:		27.83	hours
   Boiling point of water:	-56.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


