                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048036
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6102 K
Stellar class: F9
Age: 4.235 billion years  (2.818 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.377 AU	no atmosphere
2	  0.508 AU	no atmosphere
3	  1.001 AU	greenhouse
4	  1.605 AU	cold
5	  2.122 AU	cold
6	  3.102 AU	gas giant
7	  6.394 AU	cold
8	  8.979 AU	gas giant
9	 18.787 AU	gas giant
10	 42.592 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.377	AU
   Mass:			0.042	Earth masses
   Equatorial radius:		2245.2	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		222.33	degrees Celcius
   Normal daytime temperature:	432.98	degrees Celcius
   Normal night temperature:	-183.15	degrees Celcius
   Maximum temperature:   	436.38	degrees Celcius
   Minimum temperature:   	-194.52	degrees Celcius
   Escape Velocity:		3.85	km/sec
   Molecular weight retained:	53.48 and above
   Surface acceleration:	330.57	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.088
   Length of year:		80.79	days
   Length of day:		1568.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.508	AU
   Mass:			0.580	Earth masses
   Equatorial radius:		5359.1	km
   Density:			5.376	grams/cc
   Eccentricity of orbit:	0.148
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		157.50	degrees Celcius
   Maximum temperature:   	357.33	degrees Celcius
   Minimum temperature:   	-211.73	degrees Celcius
   Escape Velocity:		9.29	km/sec
   Molecular weight retained:	9.20 and above
   Surface acceleration:	805.12	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.056
   Length of year:		126.27	days
   Length of day:		2247.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	1.001	AU
   Mass:			2.053	Earth masses
   Equatorial radius:		8081.7	km
   Density:			5.550	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		1.28	Earth gees
   Surface pressure:		459.515	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		572.89	degrees Celcius
   Maximum temperature:   	574.43	degrees Celcius
   Minimum temperature:   	568.15	degrees Celcius
   Escape Velocity:		14.23	km/sec
   Molecular weight retained:	3.92 and above
   Surface acceleration:	1253.65	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.482
   Length of year:		349.61	days
   Length of day:		13.98	hours
   Boiling point of water:	408.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1463
				Cesium       melts at 28    boils at 1514
				Gallium      melts at 30    boils at 4617
				Rubidium     melts at 39    boils at 1483
				Potassium    melts at 63    boils at 1625
				Sodium       melts at 98    boils at 1837
				Indium       melts at 157   boils at 4026
				Lithium      melts at 181   boils at 2687
				Selenium     melts at 217   boils at 1477
				Tin          melts at 232   boils at 5019
				Polonium     melts at 254   boils at 1984
				Bismuth      melts at 271   boils at 3084
				Thallium     melts at 304   boils at 2888
				Cadmium      melts at 321   boils at 1624
				Lead         melts at 328   boils at 3425
				Zinc         melts at 420   boils at 1883
				Tellurium    melts at 450   boils at 2035
   gasses in atmosphere:
				Sulfur            1.2%  PP 5679.6 mb
				Nitrogen          5.3%  PP 24291.7 mb
				Helium           93.4%  PP 429380.5 mb


Planet 4	
   Distance from primary:	1.605	AU
   Mass:			0.329	Earth masses
   Equatorial radius:		4446.3	km
   Density:			5.335	grams/cc
   Eccentricity of orbit:	0.196
   Surface gravity:		0.68	Earth gees
   Surface pressure:		0.111	Earth atmospheres
   Surface temperature:		-55.00	degrees Celcius
   Normal daytime temperature:	-44.78	degrees Celcius
   Normal night temperature:	-65.62	degrees Celcius
   Maximum temperature:   	-17.26	degrees Celcius
   Minimum temperature:   	-94.66	degrees Celcius
   Escape Velocity:		7.68	km/sec
   Molecular weight retained:	13.47 and above
   Surface acceleration:	662.88	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.530
   Length of year:		709.59	days
   Length of day:		18.77	hours
   Boiling point of water:	48.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.26
   Ice cover percentage:	74.30
   liquids at surface:
				Ethanol      melts at -114  boils at 30
   gasses in atmosphere:
				Oxygen           34.0%  PP   37.9 mb
				Nitrogen         64.9%  PP   72.2 mb
				CarbonDioxide     0.5%  PP    0.5 mb
				Methane           0.1%  PP    0.1 mb
				Ozone             0.5%  PP    0.5 mb


Planet 5	
   Distance from primary:	2.122	AU
   Mass:			0.884	Earth masses
   Equatorial radius:		6152.1	km
   Density:			5.418	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.801	Earth atmospheres
   Surface temperature:		-99.90	degrees Celcius
   Normal daytime temperature:	-96.93	degrees Celcius
   Normal night temperature:	-103.05	degrees Celcius
   Maximum temperature:   	-80.16	degrees Celcius
   Minimum temperature:   	-121.16	degrees Celcius
   Escape Velocity:		10.71	km/sec
   Molecular weight retained:	6.93 and above
   Surface acceleration:	931.58	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.744
   Length of year:		1078.90	days
   Length of day:		15.71	hours
   Boiling point of water:	94.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 73
				Chlorine     melts at -101  boils at -38
   gasses in atmosphere:
				Oxygen            0.4%  PP    3.4 mb
				Nitrogen         99.5%  PP  797.2 mb
				Ozone             0.1%  PP    0.5 mb


Planet 6	*gas giant*
   Distance from primary:	3.102	AU
   Mass:			336.116	Earth masses
   Equatorial radius:		62370.6	km
   Density:			1.977	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		65.56	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3445.62	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.479
   Length of year:		1906.64	days
   Length of day:		6.96	hours


Planet 7	
   Distance from primary:	6.394	AU
   Mass:			1.017	Earth masses
   Equatorial radius:		8570.5	km
   Density:			2.304	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.597	Earth atmospheres
   Surface temperature:		-146.54	degrees Celcius
   Normal daytime temperature:	-143.38	degrees Celcius
   Normal night temperature:	-149.90	degrees Celcius
   Maximum temperature:   	-128.52	degrees Celcius
   Minimum temperature:   	-166.18	degrees Celcius
   Escape Velocity:		9.73	km/sec
   Molecular weight retained:	8.39 and above
   Surface acceleration:	551.87	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.315
   Length of year:		5643.65	days
   Length of day:		20.40	hours
   Boiling point of water:	86.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	34.65
   liquids at surface:
				Ozone        melts at -193  boils at -118
   gasses in atmosphere:
				Oxygen            1.2%  PP    7.4 mb
				Nitrogen         98.7%  PP  589.1 mb


Planet 8	*gas giant*
   Distance from primary:	8.979	AU
   Mass:			571.400	Earth masses
   Equatorial radius:		79552.8	km
   Density:			1.619	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		75.69	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3600.55	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.529
   Length of year:		9384.54	days
   Length of day:		6.81	hours


Planet 9	*gas giant*
   Distance from primary:	18.787	AU
   Mass:			199.290	Earth masses
   Equatorial radius:		62222.9	km
   Density:			1.180	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		50.54	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2052.70	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.461
   Length of year:		28417.06	days
   Length of day:		9.02	hours


Planet 10	*gas giant*
   Distance from primary:	42.592	AU
   Mass:			0.942	Earth masses
   Equatorial radius:		13975.5	km
   Density:			0.493	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		7.33	km/sec
   Molecular weight retained:	14.76 and above
   Surface acceleration:	192.40	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.532
   Length of year:		97029.62	days
   Length of day:		29.47	hours


