                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a01
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6253 K
Stellar class: F8
Age: 1.092 billion years  (5.635 billion left on main sequence)
Habitable ecosphere radius: 1.284 AU

Planets present at:
1	  0.322 AU	no atmosphere
2	  0.424 AU	no atmosphere
3	  0.701 AU	greenhouse
4	  0.931 AU	greenhouse
5	  1.835 AU	gas giant
6	  3.658 AU	gas giant
7	  4.821 AU	cold
8	  6.620 AU	gas giant
9	  9.965 AU	gas giant
10	 19.622 AU	gas giant
11	 34.498 AU	gas giant
12	 42.868 AU	no atmosphere
13	 51.511 AU	no atmosphere



Planet 1	
   Distance from primary:	0.322	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		2303.4	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		270.85	degrees Celcius
   Normal daytime temperature:	492.13	degrees Celcius
   Normal night temperature:	-174.22	degrees Celcius
   Maximum temperature:   	495.09	degrees Celcius
   Minimum temperature:   	-184.71	degrees Celcius
   Escape Velocity:		3.95	km/sec
   Molecular weight retained:	50.80 and above
   Surface acceleration:	339.22	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.086
   Length of year:		63.51	days
   Length of day:		1524.27	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.424	AU
   Mass:			0.217	Earth masses
   Equatorial radius:		3877.7	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		203.48	degrees Celcius
   Maximum temperature:   	413.72	degrees Celcius
   Minimum temperature:   	-204.21	degrees Celcius
   Escape Velocity:		6.68	km/sec
   Molecular weight retained:	17.78 and above
   Surface acceleration:	575.79	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.071
   Length of year:		95.61	days
   Length of day:		2294.61	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.701	AU
   Mass:			0.800	Earth masses
   Equatorial radius:		5954.3	km
   Density:			5.407	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.92	Earth gees
   Surface pressure:		51.347	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		421.64	degrees Celcius
   Maximum temperature:   	427.56	degrees Celcius
   Minimum temperature:   	413.77	degrees Celcius
   Escape Velocity:		10.35	km/sec
   Molecular weight retained:	7.41 and above
   Surface acceleration:	899.76	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.463
   Length of year:		203.61	days
   Length of day:		18.89	hours
   Boiling point of water:	253.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1067
				Cesium       melts at 28    boils at 1106
				Gallium      melts at 30    boils at 3501
				Rubidium     melts at 39    boils at 1082
				Potassium    melts at 63    boils at 1192
				Sodium       melts at 98    boils at 1355
				Sulfur       melts at 113   boils at 739
				Indium       melts at 157   boils at 3045
				Lithium      melts at 181   boils at 2011
				Selenium     melts at 217   boils at 1078
				Tin          melts at 232   boils at 3811
				Polonium     melts at 254   boils at 1468
				Bismuth      melts at 271   boils at 2317
				Thallium     melts at 304   boils at 2167
				Cadmium      melts at 321   boils at 1191
				Lead         melts at 328   boils at 2581
				Zinc         melts at 420   boils at 1391
   gasses in atmosphere:
				Nitrogen         99.1%  PP 50898.2 mb
				Phosphorus        0.6%  PP  292.7 mb
				CarbonDioxide     0.1%  PP   31.5 mb
				Ozone             0.1%  PP   31.3 mb
				Ethanol           0.1%  PP   31.9 mb


Planet 4	
   Distance from primary:	0.931	AU
   Mass:			0.481	Earth masses
   Equatorial radius:		5039.3	km
   Density:			5.360	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.77	Earth gees
   Surface pressure:		24.296	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		113.07	degrees Celcius
   Maximum temperature:   	120.49	degrees Celcius
   Minimum temperature:   	105.22	degrees Celcius
   Escape Velocity:		8.72	km/sec
   Molecular weight retained:	10.43 and above
   Surface acceleration:	754.93	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.546
   Length of year:		311.54	days
   Length of day:		18.22	hours
   Boiling point of water:	215.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 551
				Francium     melts at 27    boils at 970
				Cesium       melts at 28    boils at 1006
				Gallium      melts at 30    boils at 3228
				Rubidium     melts at 39    boils at 984
				Phosphorus   melts at 44    boils at 451
				Potassium    melts at 63    boils at 1086
				Sodium       melts at 98    boils at 1237
				Sulfur       melts at 113   boils at 666
   gasses in atmosphere:
				Nitrogen         99.5%  PP 24182.1 mb
				Water             0.1%  PP   13.0 mb
				CarbonDioxide     0.1%  PP   25.1 mb
				Ozone             0.1%  PP   25.6 mb
				Ethanol           0.1%  PP   25.6 mb


Planet 5	*gas giant*
   Distance from primary:	1.835	AU
   Mass:			60.408	Earth masses
   Equatorial radius:		36098.6	km
   Density:			1.832	grams/cc
   Eccentricity of orbit:	0.125
   Escape Velocity:		36.53	km/sec
   Molecular weight retained:	0.59 and above
   Surface acceleration:	1848.66	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.533
   Length of year:		862.35	days
   Length of day:		9.51	hours


Planet 6	*gas giant*
   Distance from primary:	3.658	AU
   Mass:			8.878	Earth masses
   Equatorial radius:		21856.0	km
   Density:			1.213	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		18.00	km/sec
   Molecular weight retained:	2.45 and above
   Surface acceleration:	741.20	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.514
   Length of year:		2427.47	days
   Length of day:		15.01	hours


Planet 7	
   Distance from primary:	4.821	AU
   Mass:			0.377	Earth masses
   Equatorial radius:		4651.5	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.106	Earth atmospheres
   Surface temperature:		-140.08	degrees Celcius
   Normal daytime temperature:	-133.93	degrees Celcius
   Normal night temperature:	-146.46	degrees Celcius
   Maximum temperature:   	-114.81	degrees Celcius
   Minimum temperature:   	-167.17	degrees Celcius
   Escape Velocity:		8.04	km/sec
   Molecular weight retained:	12.28 and above
   Surface acceleration:	694.59	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.446
   Length of year:		3671.84	days
   Length of day:		18.18	hours
   Boiling point of water:	47.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	56.61
   liquids at surface:
				Ozone        melts at -193  boils at -135
   gasses in atmosphere:
				Oxygen           83.4%  PP   88.8 mb
				Nitrogen         16.6%  PP   17.7 mb


Planet 8	*gas giant*
   Distance from primary:	6.620	AU
   Mass:			1064.102	Earth masses
   Equatorial radius:		92748.3	km
   Density:			1.903	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		95.66	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4933.00	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.500
   Length of year:		5900.35	days
   Length of day:		5.82	hours


Planet 9	*gas giant*
   Distance from primary:	9.965	AU
   Mass:			77.439	Earth masses
   Equatorial radius:		44687.3	km
   Density:			1.238	grams/cc
   Eccentricity of orbit:	0.036
   Escape Velocity:		37.18	km/sec
   Molecular weight retained:	0.57 and above
   Surface acceleration:	1546.43	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.532
   Length of year:		10911.68	days
   Length of day:		10.39	hours


Planet 10	*gas giant*
   Distance from primary:	19.622	AU
   Mass:			67.023	Earth masses
   Equatorial radius:		45332.1	km
   Density:			1.027	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		34.34	km/sec
   Molecular weight retained:	0.67 and above
   Surface acceleration:	1300.61	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.529
   Length of year:		30148.89	days
   Length of day:		11.33	hours


Planet 11	*gas giant*
   Distance from primary:	34.498	AU
   Mass:			7.332	Earth masses
   Equatorial radius:		24919.5	km
   Density:			0.676	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		15.32	km/sec
   Molecular weight retained:	3.38 and above
   Surface acceleration:	470.86	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.450
   Length of year:		70291.75	days
   Length of day:		18.84	hours


Planet 12	
   Distance from primary:	42.868	AU
   Mass:			0.087	Earth masses
   Equatorial radius:		3833.3	km
   Density:			2.208	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.70	degrees Celcius
   Normal daytime temperature:	-220.46	degrees Celcius
   Normal night temperature:	-232.84	degrees Celcius
   Maximum temperature:   	-207.78	degrees Celcius
   Minimum temperature:   	-245.97	degrees Celcius
   Escape Velocity:		4.26	km/sec
   Molecular weight retained:	43.76 and above
   Surface acceleration:	236.60	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.154
   Length of year:		97365.13	days
   Length of day:		31.16	hours
   Boiling point of water:	-66.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 13	
   Distance from primary:	51.511	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		3298.8	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.91	degrees Celcius
   Normal daytime temperature:	-224.85	degrees Celcius
   Normal night temperature:	-236.84	degrees Celcius
   Maximum temperature:   	-209.40	degrees Celcius
   Minimum temperature:   	-252.08	degrees Celcius
   Escape Velocity:		3.66	km/sec
   Molecular weight retained:	59.25 and above
   Surface acceleration:	203.06	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.164
   Length of year:		128249.35	days
   Length of day:		33.63	hours
   Boiling point of water:	-73.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


