                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048039
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6287 K
Stellar class: F8
Age: 3.991 billion years  (3.061 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.383 AU	no atmosphere
2	  0.470 AU	no atmosphere
3	  0.817 AU	greenhouse
4	  1.422 AU	gas giant
5	  1.771 AU	high pressure
6	  2.241 AU	no atmosphere
7	  2.792 AU	gas giant
8	  6.193 AU	gas giant
9	 10.332 AU	gas giant
10	 22.029 AU	gas giant
11	 32.440 AU	gas giant
12	 39.847 AU	no atmosphere
13	 49.504 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.383	AU
   Mass:			0.287	Earth masses
   Equatorial radius:		4254.4	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		220.87	degrees Celcius
   Normal daytime temperature:	431.20	degrees Celcius
   Normal night temperature:	-183.44	degrees Celcius
   Maximum temperature:   	434.56	degrees Celcius
   Minimum temperature:   	-194.67	degrees Celcius
   Escape Velocity:		7.34	km/sec
   Molecular weight retained:	14.73 and above
   Surface acceleration:	633.37	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.070
   Length of year:		82.73	days
   Length of day:		1571.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.470	AU
   Mass:			0.043	Earth masses
   Equatorial radius:		2271.3	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		173.08	degrees Celcius
   Maximum temperature:   	376.57	degrees Celcius
   Minimum temperature:   	-211.16	degrees Celcius
   Escape Velocity:		3.90	km/sec
   Molecular weight retained:	52.25 and above
   Surface acceleration:	334.45	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.067
   Length of year:		112.47	days
   Length of day:		2699.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.817	AU
   Mass:			0.796	Earth masses
   Equatorial radius:		5943.7	km
   Density:			5.406	grams/cc
   Eccentricity of orbit:	0.055
   Surface gravity:		0.92	Earth gees
   Surface pressure:		58.298	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		357.34	degrees Celcius
   Maximum temperature:   	363.05	degrees Celcius
   Minimum temperature:   	350.16	degrees Celcius
   Escape Velocity:		10.33	km/sec
   Molecular weight retained:	7.44 and above
   Surface acceleration:	898.06	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.510
   Length of year:		257.59	days
   Length of day:		20.53	hours
   Boiling point of water:	260.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1084
				Cesium       melts at 28    boils at 1125
				Gallium      melts at 30    boils at 3551
				Rubidium     melts at 39    boils at 1100
				Potassium    melts at 63    boils at 1211
				Sodium       melts at 98    boils at 1377
				Sulfur       melts at 113   boils at 753
				Indium       melts at 157   boils at 3090
				Lithium      melts at 181   boils at 2042
				Selenium     melts at 217   boils at 1096
				Tin          melts at 232   boils at 3866
				Polonium     melts at 254   boils at 1492
				Bismuth      melts at 271   boils at 2352
				Thallium     melts at 304   boils at 2199
				Cadmium      melts at 321   boils at 1210
				Lead         melts at 328   boils at 2619
   gasses in atmosphere:
				Nitrogen         99.0%  PP 57709.0 mb
				Phosphorus        0.7%  PP  387.9 mb
				CarbonDioxide     0.1%  PP   44.0 mb
				Ozone             0.1%  PP   40.5 mb
				Ethanol           0.1%  PP   44.8 mb


Planet 4	*gas giant*
   Distance from primary:	1.422	AU
   Mass:			4.479	Earth masses
   Equatorial radius:		16587.8	km
   Density:			1.400	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		14.68	km/sec
   Molecular weight retained:	3.69 and above
   Surface acceleration:	649.14	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.509
   Length of year:		592.14	days
   Length of day:		16.06	hours


Planet 5	
   Distance from primary:	1.771	AU
   Mass:			1.829	Earth masses
   Equatorial radius:		7787.3	km
   Density:			5.527	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		1.23	Earth gees
   Surface pressure:		3.632	Earth atmospheres
   Surface temperature:		-16.39	degrees Celcius
   Normal daytime temperature:	-14.51	degrees Celcius
   Normal night temperature:	-18.38	degrees Celcius
   Maximum temperature:   	-2.25	degrees Celcius
   Minimum temperature:   	-31.33	degrees Celcius
   Escape Velocity:		13.69	km/sec
   Molecular weight retained:	4.24 and above
   Surface acceleration:	1202.97	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.309
   Length of year:		822.59	days
   Length of day:		13.83	hours
   Boiling point of water:	139.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	7.88
   Ice cover percentage:	29.68
   liquids at surface:
				Ethanol      melts at -114  boils at 116
				Mercury      melts at -39   boils at 423
   gasses in atmosphere:
				Nitrogen         99.8%  PP 3626.3 mb


Planet 6	
   Distance from primary:	2.241	AU
   Mass:			0.220	Earth masses
   Equatorial radius:		3896.8	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.047	Earth atmospheres
   Surface temperature:		-83.09	degrees Celcius
   Normal daytime temperature:	-70.90	degrees Celcius
   Normal night temperature:	-95.59	degrees Celcius
   Maximum temperature:   	-48.62	degrees Celcius
   Minimum temperature:   	-119.00	degrees Celcius
   Escape Velocity:		6.72	km/sec
   Molecular weight retained:	17.60 and above
   Surface acceleration:	578.70	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.444
   Length of year:		1171.09	days
   Length of day:		19.95	hours
   Boiling point of water:	31.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	61.44
   liquids at surface:
				Ethanol      melts at -114  boils at 14
				Chlorine     melts at -101  boils at -78
   gasses in atmosphere:
				Ozone            93.0%  PP   44.1 mb
				Argon             0.3%  PP    0.1 mb
				Neon              0.6%  PP    0.3 mb
				Krypton           5.5%  PP    2.6 mb
				Xenon             0.7%  PP    0.3 mb


Planet 7	*gas giant*
   Distance from primary:	2.792	AU
   Mass:			15.542	Earth masses
   Equatorial radius:		25222.7	km
   Density:			1.382	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		22.17	km/sec
   Molecular weight retained:	1.62 and above
   Surface acceleration:	974.25	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.514
   Length of year:		1628.15	days
   Length of day:		13.09	hours


Planet 8	*gas giant*
   Distance from primary:	6.193	AU
   Mass:			40.286	Earth masses
   Equatorial radius:		35585.5	km
   Density:			1.276	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		30.05	km/sec
   Molecular weight retained:	0.88 and above
   Surface acceleration:	1268.67	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.541
   Length of year:		5379.35	days
   Length of day:		11.47	hours


Planet 9	*gas giant*
   Distance from primary:	10.332	AU
   Mass:			906.435	Earth masses
   Equatorial radius:		92083.6	km
   Density:			1.656	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		88.61	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4262.96	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.541
   Length of year:		11578.20	days
   Length of day:		6.26	hours


Planet 10	*gas giant*
   Distance from primary:	22.029	AU
   Mass:			5.042	Earth masses
   Equatorial radius:		21574.8	km
   Density:			0.716	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		13.65	km/sec
   Molecular weight retained:	4.26 and above
   Surface acceleration:	431.94	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.452
   Length of year:		36092.18	days
   Length of day:		19.67	hours


Planet 11	*gas giant*
   Distance from primary:	32.440	AU
   Mass:			5.294	Earth masses
   Equatorial radius:		22601.2	km
   Density:			0.654	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		13.67	km/sec
   Molecular weight retained:	4.25 and above
   Surface acceleration:	413.27	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.549
   Length of year:		64496.87	days
   Length of day:		20.10	hours


Planet 12	
   Distance from primary:	39.847	AU
   Mass:			0.221	Earth masses
   Equatorial radius:		5211.4	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.58	degrees Celcius
   Normal daytime temperature:	-220.02	degrees Celcius
   Normal night temperature:	-231.06	degrees Celcius
   Maximum temperature:   	-209.15	degrees Celcius
   Minimum temperature:   	-242.63	degrees Celcius
   Escape Velocity:		5.82	km/sec
   Molecular weight retained:	23.47 and above
   Surface acceleration:	324.51	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.165
   Length of year:		87801.47	days
   Length of day:		26.60	hours
   Boiling point of water:	-52.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 13	
   Distance from primary:	49.504	AU
   Mass:			0.050	Earth masses
   Equatorial radius:		3192.5	km
   Density:			2.201	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.44	degrees Celcius
   Normal daytime temperature:	-224.22	degrees Celcius
   Normal night temperature:	-236.53	degrees Celcius
   Maximum temperature:   	-211.08	degrees Celcius
   Minimum temperature:   	-249.81	degrees Celcius
   Escape Velocity:		3.54	km/sec
   Molecular weight retained:	63.29 and above
   Surface acceleration:	196.42	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.143
   Length of year:		121583.87	days
   Length of day:		34.20	hours
   Boiling point of water:	-75.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


