                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f63
Stellar mass: 1.09 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6330 K
Stellar class: F7
Age: 3.963 billion years  (3.118 billion left on main sequence)
Habitable ecosphere radius: 1.243 AU

Planets present at:
1	  0.347 AU	no atmosphere
2	  0.430 AU	no atmosphere
3	  0.674 AU	greenhouse
4	  1.170 AU	high pressure
5	  2.269 AU	gas giant
6	  3.584 AU	gas giant
7	  6.869 AU	gas giant
8	 12.693 AU	gas giant
9	 28.334 AU	no atmosphere
10	 47.989 AU	no atmosphere



Planet 1	
   Distance from primary:	0.347	AU
   Mass:			0.039	Earth masses
   Equatorial radius:		2189.0	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		242.75	degrees Celcius
   Normal daytime temperature:	458.29	degrees Celcius
   Normal night temperature:	-182.48	degrees Celcius
   Maximum temperature:   	461.40	degrees Celcius
   Minimum temperature:   	-193.08	degrees Celcius
   Escape Velocity:		3.76	km/sec
   Molecular weight retained:	56.27 and above
   Surface acceleration:	322.23	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.086
   Length of year:		71.47	days
   Length of day:		1715.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.430	AU
   Mass:			0.146	Earth masses
   Equatorial radius:		3401.4	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.74	degrees Celcius
   Maximum temperature:   	400.59	degrees Celcius
   Minimum temperature:   	-206.32	degrees Celcius
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.17 and above
   Surface acceleration:	503.58	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.068
   Length of year:		98.48	days
   Length of day:		2363.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.674	AU
   Mass:			0.679	Earth masses
   Equatorial radius:		5644.8	km
   Density:			5.390	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.87	Earth gees
   Surface pressure:		41.935	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		311.05	degrees Celcius
   Maximum temperature:   	320.60	degrees Celcius
   Minimum temperature:   	298.45	degrees Celcius
   Escape Velocity:		9.80	km/sec
   Molecular weight retained:	8.27 and above
   Surface acceleration:	850.35	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.429
   Length of year:		193.11	days
   Length of day:		78.69	hours
   Boiling point of water:	242.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 597
				Francium     melts at 27    boils at 1039
				Cesium       melts at 28    boils at 1078
				Gallium      melts at 30    boils at 3423
				Rubidium     melts at 39    boils at 1054
				Potassium    melts at 63    boils at 1161
				Sodium       melts at 98    boils at 1321
				Sulfur       melts at 113   boils at 718
				Indium       melts at 157   boils at 2977
				Lithium      melts at 181   boils at 1964
				Selenium     melts at 217   boils at 1050
				Tin          melts at 232   boils at 3726
				Polonium     melts at 254   boils at 1432
				Bismuth      melts at 271   boils at 2264
				Astatine     melts at 302   boils at 570
				Thallium     melts at 304   boils at 2116
   gasses in atmosphere:
				Nitrogen         98.8%  PP 41443.5 mb
				Phosphorus        0.8%  PP  323.2 mb
				CarbonDioxide     0.1%  PP   37.8 mb
				Ozone             0.1%  PP   36.2 mb
				Ethanol           0.1%  PP   38.6 mb


Planet 4	
   Distance from primary:	1.170	AU
   Mass:			2.349	Earth masses
   Equatorial radius:		8438.0	km
   Density:			5.580	grams/cc
   Eccentricity of orbit:	0.055
   Surface gravity:		1.34	Earth gees
   Surface pressure:		5.634	Earth atmospheres
   Surface temperature:		39.18	degrees Celcius
   Normal daytime temperature:	40.95	degrees Celcius
   Normal night temperature:	37.29	degrees Celcius
   Maximum temperature:   	52.41	degrees Celcius
   Minimum temperature:   	25.30	degrees Celcius
   Escape Velocity:		14.90	km/sec
   Molecular weight retained:	3.57 and above
   Surface acceleration:	1315.80	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.506
   Length of year:		441.85	days
   Length of day:		13.35	hours
   Boiling point of water:	154.6	degrees Celcius
   Hydrosphere percentage:	97.36
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.02
   liquids at surface:
				Ethanol      melts at -114  boils at 130
				Mercury      melts at -39   boils at 449
				Bromine      melts at -7    boils at 108
				Water        melts at 0     boils at 155
				Francium     melts at 27    boils at 816
				Cesium       melts at 28    boils at 848
				Gallium      melts at 30    boils at 2795
				Rubidium     melts at 39    boils at 829
   gasses in atmosphere:
				Nitrogen          1.1%  PP   59.9 mb
				Helium           98.9%  PP 5574.4 mb


Planet 5	*gas giant*
   Distance from primary:	2.269	AU
   Mass:			15.134	Earth masses
   Equatorial radius:		24604.6	km
   Density:			1.450	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		22.15	km/sec
   Molecular weight retained:	1.62 and above
   Surface acceleration:	996.92	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.487
   Length of year:		1193.96	days
   Length of day:		12.94	hours


Planet 6	*gas giant*
   Distance from primary:	3.584	AU
   Mass:			15.259	Earth masses
   Equatorial radius:		25621.1	km
   Density:			1.295	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		21.79	km/sec
   Molecular weight retained:	1.67 and above
   Surface acceleration:	926.98	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.476
   Length of year:		2369.83	days
   Length of day:		13.42	hours


Planet 7	*gas giant*
   Distance from primary:	6.869	AU
   Mass:			1475.137	Earth masses
   Equatorial radius:		102610.1	km
   Density:			1.948	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		107.08	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5587.16	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.504
   Length of year:		6275.47	days
   Length of day:		5.47	hours


Planet 8	*gas giant*
   Distance from primary:	12.693	AU
   Mass:			16.789	Earth masses
   Equatorial radius:		29273.0	km
   Density:			0.955	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		21.39	km/sec
   Molecular weight retained:	1.74 and above
   Surface acceleration:	781.32	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.477
   Length of year:		15794.05	days
   Length of day:		14.62	hours


Planet 9	
   Distance from primary:	28.334	AU
   Mass:			2.065	Earth masses
   Equatorial radius:		10742.2	km
   Density:			2.377	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.008	Earth atmospheres
   Surface temperature:		-214.71	degrees Celcius
   Normal daytime temperature:	-210.28	degrees Celcius
   Normal night temperature:	-219.13	degrees Celcius
   Maximum temperature:   	-196.52	degrees Celcius
   Minimum temperature:   	-234.12	degrees Celcius
   Escape Velocity:		12.38	km/sec
   Molecular weight retained:	5.18 and above
   Surface acceleration:	713.76	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.166
   Length of year:		52676.46	days
   Length of day:		17.94	hours
   Boiling point of water:	2.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.15
   liquids at surface:
				Fluorine     melts at -220  boils at -210
				Oxygen       melts at -218  boils at -206
   gasses in atmosphere:
				Neon             100.0%  PP    8.4 mb


Planet 10	
   Distance from primary:	47.989	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		5351.9	km
   Density:			2.230	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.64	degrees Celcius
   Normal daytime temperature:	-224.62	degrees Celcius
   Normal night temperature:	-234.57	degrees Celcius
   Maximum temperature:   	-208.66	degrees Celcius
   Minimum temperature:   	-250.66	degrees Celcius
   Escape Velocity:		5.98	km/sec
   Molecular weight retained:	22.23 and above
   Surface acceleration:	333.61	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.152
   Length of year:		116107.38	days
   Length of day:		26.24	hours
   Boiling point of water:	-47.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


