                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047be0
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6070 K
Stellar class: F9
Age: 5.049 billion years  (2.155 billion left on main sequence)
Habitable ecosphere radius: 1.229 AU

Planets present at:
1	  0.382 AU	no atmosphere
2	  0.611 AU	no atmosphere
3	  0.693 AU	no atmosphere
4	  0.778 AU	no atmosphere
5	  0.986 AU	greenhouse
6	  1.616 AU	gas giant
7	  2.047 AU	cold
8	  2.588 AU	cold
9	  4.395 AU	cold
10	  5.808 AU	gas giant
11	  9.398 AU	no atmosphere
12	 12.714 AU	gas giant
13	 22.232 AU	gas giant
14	 32.975 AU	gas giant
15	 42.896 AU	no atmosphere
16	 49.622 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.382	AU
   Mass:			0.171	Earth masses
   Equatorial radius:		3583.6	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		217.05	degrees Celcius
   Normal daytime temperature:	426.58	degrees Celcius
   Normal night temperature:	-184.64	degrees Celcius
   Maximum temperature:   	429.96	degrees Celcius
   Minimum temperature:   	-195.87	degrees Celcius
   Escape Velocity:		6.17	km/sec
   Molecular weight retained:	20.85 and above
   Surface acceleration:	531.13	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.077
   Length of year:		82.76	days
   Length of day:		1602.27	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.611	AU
   Mass:			0.061	Earth masses
   Equatorial radius:		2539.7	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.055
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		117.27	degrees Celcius
   Maximum temperature:   	307.56	degrees Celcius
   Minimum temperature:   	-222.77	degrees Celcius
   Escape Velocity:		4.36	km/sec
   Molecular weight retained:	41.74 and above
   Surface acceleration:	374.39	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.051
   Length of year:		167.28	days
   Length of day:		4014.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.693	AU
   Mass:			0.044	Earth masses
   Equatorial radius:		2281.5	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		91.94	degrees Celcius
   Maximum temperature:   	275.84	degrees Celcius
   Minimum temperature:   	-226.11	degrees Celcius
   Escape Velocity:		3.92	km/sec
   Molecular weight retained:	51.78 and above
   Surface acceleration:	335.96	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.066
   Length of year:		202.13	days
   Length of day:		4851.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.778	AU
   Mass:			0.260	Earth masses
   Equatorial radius:		4115.2	km
   Density:			5.322	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		71.81	degrees Celcius
   Normal daytime temperature:	223.18	degrees Celcius
   Normal night temperature:	-127.87	degrees Celcius
   Maximum temperature:   	234.85	degrees Celcius
   Minimum temperature:   	-150.59	degrees Celcius
   Escape Velocity:		7.10	km/sec
   Molecular weight retained:	15.76 and above
   Surface acceleration:	612.04	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.062
   Length of year:		240.35	days
   Length of day:		282.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.986	AU
   Mass:			1.571	Earth masses
   Equatorial radius:		7414.2	km
   Density:			5.500	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		1.16	Earth gees
   Surface pressure:		270.999	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		513.64	degrees Celcius
   Maximum temperature:   	516.03	degrees Celcius
   Minimum temperature:   	508.69	degrees Celcius
   Escape Velocity:		13.00	km/sec
   Molecular weight retained:	4.70 and above
   Surface acceleration:	1139.62	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.449
   Length of year:		342.69	days
   Length of day:		14.96	hours
   Boiling point of water:	363.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1347
				Cesium       melts at 28    boils at 1395
				Gallium      melts at 30    boils at 4291
				Rubidium     melts at 39    boils at 1366
				Potassium    melts at 63    boils at 1499
				Sodium       melts at 98    boils at 1696
				Indium       melts at 157   boils at 3740
				Lithium      melts at 181   boils at 2490
				Selenium     melts at 217   boils at 1361
				Tin          melts at 232   boils at 4667
				Polonium     melts at 254   boils at 1833
				Bismuth      melts at 271   boils at 2860
				Thallium     melts at 304   boils at 2678
				Cadmium      melts at 321   boils at 1497
				Lead         melts at 328   boils at 3179
				Zinc         melts at 420   boils at 1740
				Tellurium    melts at 450   boils at 1881
   gasses in atmosphere:
				Sulfur           20.4%  PP 55287.6 mb
				Nitrogen         79.0%  PP 214102.1 mb
				Phosphorus        0.4%  PP 1101.5 mb


Planet 6	*gas giant*
   Distance from primary:	1.616	AU
   Mass:			5.020	Earth masses
   Equatorial radius:		17351.1	km
   Density:			1.371	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		15.19	km/sec
   Molecular weight retained:	3.44 and above
   Surface acceleration:	664.90	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.484
   Length of year:		719.04	days
   Length of day:		15.86	hours


Planet 7	
   Distance from primary:	2.047	AU
   Mass:			0.764	Earth masses
   Equatorial radius:		5865.3	km
   Density:			5.402	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.90	Earth gees
   Surface pressure:		0.607	Earth atmospheres
   Surface temperature:		-99.42	degrees Celcius
   Normal daytime temperature:	-95.94	degrees Celcius
   Normal night temperature:	-103.10	degrees Celcius
   Maximum temperature:   	-76.08	degrees Celcius
   Minimum temperature:   	-124.53	degrees Celcius
   Escape Velocity:		10.19	km/sec
   Molecular weight retained:	7.64 and above
   Surface acceleration:	885.51	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.745
   Length of year:		1025.12	days
   Length of day:		16.12	hours
   Boiling point of water:	86.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 66
				Chlorine     melts at -101  boils at -42
   gasses in atmosphere:
				Oxygen            0.3%  PP    2.0 mb
				Nitrogen         99.6%  PP  604.1 mb
				Ozone             0.1%  PP    0.4 mb


Planet 8	
   Distance from primary:	2.588	AU
   Mass:			0.418	Earth masses
   Equatorial radius:		4814.6	km
   Density:			5.350	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.150	Earth atmospheres
   Surface temperature:		-99.11	degrees Celcius
   Normal daytime temperature:	-92.13	degrees Celcius
   Normal night temperature:	-106.39	degrees Celcius
   Maximum temperature:   	-68.38	degrees Celcius
   Minimum temperature:   	-131.82	degrees Celcius
   Escape Velocity:		8.33	km/sec
   Molecular weight retained:	11.45 and above
   Surface acceleration:	719.89	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.502
   Length of year:		1457.62	days
   Length of day:		17.87	hours
   Boiling point of water:	54.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	67.25
   liquids at surface:
				Ethanol      melts at -114  boils at 35
				Chlorine     melts at -101  boils at -63
   gasses in atmosphere:
				Oxygen            6.6%  PP    9.9 mb
				Nitrogen         93.2%  PP  140.3 mb
				Ozone             0.1%  PP    0.2 mb


Planet 9	
   Distance from primary:	4.395	AU
   Mass:			1.232	Earth masses
   Equatorial radius:		6853.4	km
   Density:			5.461	grams/cc
   Eccentricity of orbit:	0.132
   Surface gravity:		1.07	Earth gees
   Surface pressure:		1.272	Earth atmospheres
   Surface temperature:		-147.05	degrees Celcius
   Normal daytime temperature:	-145.41	degrees Celcius
   Normal night temperature:	-148.79	degrees Celcius
   Maximum temperature:   	-130.29	degrees Celcius
   Minimum temperature:   	-165.38	degrees Celcius
   Escape Velocity:		11.97	km/sec
   Molecular weight retained:	5.54 and above
   Surface acceleration:	1046.06	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.702
   Length of year:		3224.94	days
   Length of day:		14.82	hours
   Boiling point of water:	106.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	95.29
   liquids at surface:
				Ozone        melts at -193  boils at -109
   gasses in atmosphere:
				Nitrogen         100.0%  PP 1271.4 mb


Planet 10	*gas giant*
   Distance from primary:	5.808	AU
   Mass:			815.518	Earth masses
   Equatorial radius:		85199.3	km
   Density:			1.882	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		87.37	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4480.24	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.508
   Length of year:		4894.58	days
   Length of day:		6.11	hours


Planet 11	
   Distance from primary:	9.398	AU
   Mass:			1/1388	Earth masses
   Equatorial radius:		777.5	km
   Density:			2.187	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.05	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-176.52	degrees Celcius
   Normal daytime temperature:	-151.63	degrees Celcius
   Normal night temperature:	-201.31	degrees Celcius
   Maximum temperature:   	-132.72	degrees Celcius
   Minimum temperature:   	-219.58	degrees Celcius
   Escape Velocity:		0.86	km/sec
   Molecular weight retained:	1074.36 and above
   Surface acceleration:	47.52	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.162
   Length of year:		10085.77	days
   Length of day:		69.53	hours
   Boiling point of water:	-96.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	2.87
   liquids at surface:
				Ozone        melts at -193  boils at -166


Planet 12	*gas giant*
   Distance from primary:	12.714	AU
   Mass:			105.459	Earth masses
   Equatorial radius:		50082.4	km
   Density:			1.198	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		40.98	km/sec
   Molecular weight retained:	0.47 and above
   Surface acceleration:	1676.68	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.527
   Length of year:		15866.34	days
   Length of day:		9.98	hours


Planet 13	*gas giant*
   Distance from primary:	22.232	AU
   Mass:			3.162	Earth masses
   Equatorial radius:		18865.3	km
   Density:			0.672	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		11.56	km/sec
   Molecular weight retained:	5.94 and above
   Surface acceleration:	354.29	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.542
   Length of year:		36693.85	days
   Length of day:		21.71	hours


Planet 14	*gas giant*
   Distance from primary:	32.975	AU
   Mass:			8.496	Earth masses
   Equatorial radius:		26009.3	km
   Density:			0.689	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		16.14	km/sec
   Molecular weight retained:	3.05 and above
   Surface acceleration:	500.82	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.478
   Length of year:		66283.69	days
   Length of day:		18.26	hours


Planet 15	
   Distance from primary:	42.896	AU
   Mass:			0.136	Earth masses
   Equatorial radius:		4444.5	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.47	degrees Celcius
   Normal daytime temperature:	-221.72	degrees Celcius
   Normal night temperature:	-233.12	degrees Celcius
   Maximum temperature:   	-207.39	degrees Celcius
   Minimum temperature:   	-247.81	degrees Celcius
   Escape Velocity:		4.95	km/sec
   Molecular weight retained:	32.44 and above
   Surface acceleration:	275.31	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.137
   Length of year:		98345.27	days
   Length of day:		28.88	hours
   Boiling point of water:	-59.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 16	
   Distance from primary:	49.622	AU
   Mass:			0.038	Earth masses
   Equatorial radius:		2921.6	km
   Density:			2.199	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.18	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.75	degrees Celcius
   Normal daytime temperature:	-224.34	degrees Celcius
   Normal night temperature:	-237.03	degrees Celcius
   Maximum temperature:   	-210.71	degrees Celcius
   Minimum temperature:   	-250.67	degrees Celcius
   Escape Velocity:		3.24	km/sec
   Molecular weight retained:	75.67 and above
   Surface acceleration:	179.54	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.141
   Length of year:		122360.02	days
   Length of day:		35.77	hours
   Boiling point of water:	-81.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


