                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950484d8
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6137 K
Stellar class: F9
Age: 4.371 billion years  (2.525 billion left on main sequence)
Habitable ecosphere radius: 1.264 AU

Planets present at:
1	  0.352 AU	no atmosphere
2	  0.413 AU	no atmosphere
3	  0.610 AU	no atmosphere
4	  0.804 AU	greenhouse
5	  1.256 AU	
6	  1.911 AU	gas giant
7	  3.248 AU	cold
8	  5.288 AU	gas giant
9	 10.552 AU	gas giant
10	 15.254 AU	gas giant
11	 26.410 AU	gas giant
12	 44.114 AU	gas giant
13	 50.877 AU	no atmosphere



Planet 1	
   Distance from primary:	0.352	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		1835.3	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		242.89	degrees Celcius
   Maximum temperature:   	461.46	degrees Celcius
   Minimum temperature:   	-192.89	degrees Celcius
   Escape Velocity:		3.15	km/sec
   Molecular weight retained:	80.15 and above
   Surface acceleration:	269.84	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.091
   Length of year:		72.65	days
   Length of day:		1743.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.413	AU
   Mass:			0.220	Earth masses
   Equatorial radius:		3891.8	km
   Density:			5.314	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		204.63	degrees Celcius
   Maximum temperature:   	415.09	degrees Celcius
   Minimum temperature:   	-203.48	degrees Celcius
   Escape Velocity:		6.71	km/sec
   Molecular weight retained:	17.65 and above
   Surface acceleration:	577.94	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.080
   Length of year:		92.36	days
   Length of day:		2216.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.610	AU
   Mass:			0.101	Earth masses
   Equatorial radius:		3011.0	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		122.79	degrees Celcius
   Maximum temperature:   	314.55	degrees Celcius
   Minimum temperature:   	-222.23	degrees Celcius
   Escape Velocity:		5.18	km/sec
   Molecular weight retained:	29.63 and above
   Surface acceleration:	444.83	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.053
   Length of year:		165.90	days
   Length of day:		3981.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.804	AU
   Mass:			0.581	Earth masses
   Equatorial radius:		5362.8	km
   Density:			5.376	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.82	Earth gees
   Surface pressure:		35.703	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		245.68	degrees Celcius
   Maximum temperature:   	252.96	degrees Celcius
   Minimum temperature:   	237.43	degrees Celcius
   Escape Velocity:		9.30	km/sec
   Molecular weight retained:	9.19 and above
   Surface acceleration:	805.71	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.475
   Length of year:		250.88	days
   Length of day:		25.92	hours
   Boiling point of water:	233.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 583
				Francium     melts at 27    boils at 1018
				Cesium       melts at 28    boils at 1056
				Gallium      melts at 30    boils at 3363
				Rubidium     melts at 39    boils at 1033
				Phosphorus   melts at 44    boils at 479
				Potassium    melts at 63    boils at 1138
				Sodium       melts at 98    boils at 1296
				Sulfur       melts at 113   boils at 702
				Indium       melts at 157   boils at 2924
				Lithium      melts at 181   boils at 1928
				Selenium     melts at 217   boils at 1029
				Tin          melts at 232   boils at 3662
   gasses in atmosphere:
				Nitrogen         99.5%  PP 35540.0 mb
				CarbonDioxide     0.1%  PP   37.6 mb
				Ozone             0.1%  PP   36.3 mb
				Ethanol           0.1%  PP   38.5 mb


Planet 5	
   Distance from primary:	1.256	AU
   Mass:			0.749	Earth masses
   Equatorial radius:		5826.7	km
   Density:			5.400	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.90	Earth gees
   Surface pressure:		0.471	Earth atmospheres
   Surface temperature:		17.95	degrees Celcius
   Normal daytime temperature:	24.61	degrees Celcius
   Normal night temperature:	10.89	degrees Celcius
   Maximum temperature:   	48.36	degrees Celcius
   Minimum temperature:   	-14.15	degrees Celcius
   Escape Velocity:		10.12	km/sec
   Molecular weight retained:	7.75 and above
   Surface acceleration:	879.33	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.261
   Length of year:		489.81	days
   Length of day:		16.48	hours
   Boiling point of water:	80.4	degrees Celcius
   Hydrosphere percentage:	53.56
   Cloud cover percentage:	47.60
   Ice cover percentage:	1.12
   liquids at surface:
				Ethanol      melts at -114  boils at 60
				Mercury      melts at -39   boils at 324
				Bromine      melts at -7    boils at 42
				Water        melts at 0     boils at 80
   gasses in atmosphere:
				Oxygen           37.2%  PP  175.1 mb
				Nitrogen         62.7%  PP  295.2 mb


Planet 6	*gas giant*
   Distance from primary:	1.911	AU
   Mass:			57.003	Earth masses
   Equatorial radius:		35659.1	km
   Density:			1.794	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		35.71	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	1787.71	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.474
   Length of year:		919.25	days
   Length of day:		9.67	hours


Planet 7	
   Distance from primary:	3.248	AU
   Mass:			0.636	Earth masses
   Equatorial radius:		5523.6	km
   Density:			5.384	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.422	Earth atmospheres
   Surface temperature:		-124.50	degrees Celcius
   Normal daytime temperature:	-120.88	degrees Celcius
   Normal night temperature:	-128.30	degrees Celcius
   Maximum temperature:   	-101.80	degrees Celcius
   Minimum temperature:   	-149.05	degrees Celcius
   Escape Velocity:		9.58	km/sec
   Molecular weight retained:	8.65 and above
   Surface acceleration:	831.13	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.660
   Length of year:		2037.68	days
   Length of day:		16.63	hours
   Boiling point of water:	77.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	94.38
   liquids at surface:
				Ozone        melts at -193  boils at -122
   gasses in atmosphere:
				Oxygen            2.5%  PP   10.6 mb
				Nitrogen         97.4%  PP  411.6 mb


Planet 8	*gas giant*
   Distance from primary:	5.288	AU
   Mass:			139.739	Earth masses
   Equatorial radius:		50418.5	km
   Density:			1.556	grams/cc
   Eccentricity of orbit:	0.144
   Escape Velocity:		47.02	km/sec
   Molecular weight retained:	0.36 and above
   Surface acceleration:	2192.18	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.472
   Length of year:		4231.35	days
   Length of day:		8.73	hours


Planet 9	*gas giant*
   Distance from primary:	10.552	AU
   Mass:			72.524	Earth masses
   Equatorial radius:		44108.1	km
   Density:			1.206	grams/cc
   Eccentricity of orbit:	0.225
   Escape Velocity:		36.21	km/sec
   Molecular weight retained:	0.61 and above
   Surface acceleration:	1486.57	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.521
   Length of year:		11929.37	days
   Length of day:		10.60	hours


Planet 10	*gas giant*
   Distance from primary:	15.254	AU
   Mass:			115.237	Earth masses
   Equatorial radius:		52060.9	km
   Density:			1.165	grams/cc
   Eccentricity of orbit:	0.022
   Escape Velocity:		42.02	km/sec
   Molecular weight retained:	0.45 and above
   Surface acceleration:	1695.53	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.535
   Length of year:		20732.78	days
   Length of day:		9.93	hours


Planet 11	*gas giant*
   Distance from primary:	26.410	AU
   Mass:			40.019	Earth masses
   Equatorial radius:		40031.9	km
   Density:			0.890	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		28.24	km/sec
   Molecular weight retained:	1.00 and above
   Surface acceleration:	995.85	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.520
   Length of year:		47233.34	days
   Length of day:		12.95	hours


Planet 12	*gas giant*
   Distance from primary:	44.114	AU
   Mass:			0.278	Earth masses
   Equatorial radius:		9808.7	km
   Density:			0.421	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		4.76	km/sec
   Molecular weight retained:	35.08 and above
   Surface acceleration:	115.34	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.481
   Length of year:		101974.82	days
   Length of day:		38.06	hours


Planet 13	
   Distance from primary:	50.877	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		2591.1	km
   Density:			2.196	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.71	degrees Celcius
   Normal daytime temperature:	-223.95	degrees Celcius
   Normal night temperature:	-237.32	degrees Celcius
   Maximum temperature:   	-212.34	degrees Celcius
   Minimum temperature:   	-249.11	degrees Celcius
   Escape Velocity:		2.87	km/sec
   Molecular weight retained:	96.32 and above
   Surface acceleration:	159.03	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.142
   Length of year:		126303.60	days
   Length of day:		38.00	hours
   Boiling point of water:	-84.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


