                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048b27
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6365 K
Stellar class: F7
Age: 5.564 billion years  (1.126 billion left on main sequence)
Habitable ecosphere radius: 1.288 AU

Planets present at:
1	  0.379 AU	no atmosphere
2	  0.416 AU	no atmosphere
3	  0.535 AU	no atmosphere
4	  0.689 AU	greenhouse
5	  1.109 AU	no atmosphere
6	  1.310 AU	gas giant
7	  2.434 AU	cold
8	  2.756 AU	no atmosphere
9	  3.203 AU	gas giant
10	  6.742 AU	gas giant
11	  9.416 AU	gas giant
12	 16.410 AU	gas giant
13	 23.411 AU	gas giant
14	 42.492 AU	gas giant
15	 51.478 AU	no atmosphere



Planet 1	
   Distance from primary:	0.379	AU
   Mass:			0.015	Earth masses
   Equatorial radius:		1606.6	km
   Density:			5.257	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.65	degrees Celcius
   Normal daytime temperature:	445.08	degrees Celcius
   Normal night temperature:	-187.54	degrees Celcius
   Maximum temperature:   	448.19	degrees Celcius
   Minimum temperature:   	-197.92	degrees Celcius
   Escape Velocity:		2.75	km/sec
   Molecular weight retained:	104.65 and above
   Surface acceleration:	236.06	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.070
   Length of year:		80.94	days
   Length of day:		1942.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.416	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2072.0	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		210.15	degrees Celcius
   Maximum temperature:   	422.06	degrees Celcius
   Minimum temperature:   	-203.49	degrees Celcius
   Escape Velocity:		3.55	km/sec
   Molecular weight retained:	62.83 and above
   Surface acceleration:	304.88	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.058
   Length of year:		93.09	days
   Length of day:		2234.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.535	AU
   Mass:			0.168	Earth masses
   Equatorial radius:		3562.4	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.135
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.01	degrees Celcius
   Maximum temperature:   	348.23	degrees Celcius
   Minimum temperature:   	-214.38	degrees Celcius
   Escape Velocity:		6.13	km/sec
   Molecular weight retained:	21.10 and above
   Surface acceleration:	527.92	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.087
   Length of year:		135.51	days
   Length of day:		2479.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.689	AU
   Mass:			0.776	Earth masses
   Equatorial radius:		5896.6	km
   Density:			5.404	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.91	Earth gees
   Surface pressure:		53.409	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		402.08	degrees Celcius
   Maximum temperature:   	412.86	degrees Celcius
   Minimum temperature:   	384.55	degrees Celcius
   Escape Velocity:		10.25	km/sec
   Molecular weight retained:	7.56 and above
   Surface acceleration:	890.52	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.550
   Length of year:		198.34	days
   Length of day:		151.57	hours
   Boiling point of water:	255.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1072
				Cesium       melts at 28    boils at 1112
				Gallium      melts at 30    boils at 3516
				Rubidium     melts at 39    boils at 1088
				Potassium    melts at 63    boils at 1198
				Sodium       melts at 98    boils at 1362
				Sulfur       melts at 113   boils at 743
				Indium       melts at 157   boils at 3059
				Lithium      melts at 181   boils at 2021
				Selenium     melts at 217   boils at 1083
				Tin          melts at 232   boils at 3828
				Polonium     melts at 254   boils at 1476
				Bismuth      melts at 271   boils at 2328
				Thallium     melts at 304   boils at 2177
				Cadmium      melts at 321   boils at 1197
				Lead         melts at 328   boils at 2593
   gasses in atmosphere:
				Nitrogen         98.8%  PP 52780.3 mb
				Phosphorus        0.8%  PP  415.2 mb
				CarbonDioxide     0.1%  PP   49.6 mb
				Ozone             0.1%  PP   44.7 mb
				Ethanol           0.1%  PP   50.8 mb


Planet 5	
   Distance from primary:	1.109	AU
   Mass:			1/2.312e+05	Earth masses
   Equatorial radius:		105.6	km
   Density:			5.246	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.02	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		21.99	degrees Celcius
   Maximum temperature:   	186.92	degrees Celcius
   Minimum temperature:   	-234.36	degrees Celcius
   Escape Velocity:		0.18	km/sec
   Molecular weight retained:	24290.13 and above
   Surface acceleration:	15.48	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.071
   Length of year:		404.79	days
   Length of day:		9714.98	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	*gas giant*
   Distance from primary:	1.310	AU
   Mass:			5.206	Earth masses
   Equatorial radius:		17165.0	km
   Density:			1.469	grams/cc
   Eccentricity of orbit:	0.095
   Escape Velocity:		15.55	km/sec
   Molecular weight retained:	3.28 and above
   Surface acceleration:	704.59	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.525
   Length of year:		519.57	days
   Length of day:		15.43	hours


Planet 7	
   Distance from primary:	2.434	AU
   Mass:			0.619	Earth masses
   Equatorial radius:		5476.2	km
   Density:			5.381	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.404	Earth atmospheres
   Surface temperature:		-97.57	degrees Celcius
   Normal daytime temperature:	-93.19	degrees Celcius
   Normal night temperature:	-102.18	degrees Celcius
   Maximum temperature:   	-72.65	degrees Celcius
   Minimum temperature:   	-124.30	degrees Celcius
   Escape Velocity:		9.50	km/sec
   Molecular weight retained:	8.80 and above
   Surface acceleration:	823.63	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.641
   Length of year:		1316.38	days
   Length of day:		16.71	hours
   Boiling point of water:	76.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	94.29
   liquids at surface:
				Ethanol      melts at -114  boils at 57
				Chlorine     melts at -101  boils at -49
   gasses in atmosphere:
				Oxygen            0.6%  PP    2.4 mb
				Nitrogen         99.3%  PP  401.1 mb
				Ozone             0.1%  PP    0.3 mb


Planet 8	
   Distance from primary:	2.756	AU
   Mass:			0.089	Earth masses
   Equatorial radius:		2891.4	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.008	Earth atmospheres
   Surface temperature:		-103.00	degrees Celcius
   Normal daytime temperature:	-86.68	degrees Celcius
   Normal night temperature:	-119.46	degrees Celcius
   Maximum temperature:   	-64.42	degrees Celcius
   Minimum temperature:   	-142.58	degrees Celcius
   Escape Velocity:		4.97	km/sec
   Molecular weight retained:	32.16 and above
   Surface acceleration:	426.91	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.376
   Length of year:		1586.25	days
   Length of day:		23.23	hours
   Boiling point of water:	2.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	47.77
   liquids at surface:
				Ethanol      melts at -114  boils at -12
   gasses in atmosphere:
				Ozone            90.4%  PP    7.4 mb
				Argon             0.2%  PP    0.0 mb
				Krypton           8.3%  PP    0.7 mb
				Xenon             1.1%  PP    0.1 mb


Planet 9	*gas giant*
   Distance from primary:	3.203	AU
   Mass:			66.827	Earth masses
   Equatorial radius:		38932.9	km
   Density:			1.616	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		37.00	km/sec
   Molecular weight retained:	0.58 and above
   Surface acceleration:	1758.17	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.531
   Length of year:		1987.24	days
   Length of day:		9.75	hours


Planet 10	*gas giant*
   Distance from primary:	6.742	AU
   Mass:			958.335	Earth masses
   Equatorial radius:		90070.3	km
   Density:			1.871	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		92.12	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4710.79	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.542
   Length of year:		6061.04	days
   Length of day:		5.95	hours


Planet 11	*gas giant*
   Distance from primary:	9.416	AU
   Mass:			23.556	Earth masses
   Equatorial radius:		31423.4	km
   Density:			1.083	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		24.45	km/sec
   Molecular weight retained:	1.33 and above
   Surface acceleration:	951.32	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.507
   Length of year:		10015.10	days
   Length of day:		13.25	hours


Planet 12	*gas giant*
   Distance from primary:	16.410	AU
   Mass:			0.611	Earth masses
   Equatorial radius:		11341.8	km
   Density:			0.597	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		6.55	km/sec
   Molecular weight retained:	18.49 and above
   Surface acceleration:	189.30	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.504
   Length of year:		23043.02	days
   Length of day:		29.71	hours


Planet 13	*gas giant*
   Distance from primary:	23.411	AU
   Mass:			33.482	Earth masses
   Equatorial radius:		37562.9	km
   Density:			0.901	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		26.66	km/sec
   Molecular weight retained:	1.12 and above
   Surface acceleration:	946.30	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.500
   Length of year:		39265.81	days
   Length of day:		13.29	hours


Planet 14	*gas giant*
   Distance from primary:	42.492	AU
   Mass:			1.691	Earth masses
   Equatorial radius:		16524.9	km
   Density:			0.535	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		9.03	km/sec
   Molecular weight retained:	9.73 and above
   Surface acceleration:	246.95	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.492
   Length of year:		96017.58	days
   Length of day:		26.01	hours


Planet 15	
   Distance from primary:	51.478	AU
   Mass:			0.029	Earth masses
   Equatorial radius:		2672.8	km
   Density:			2.197	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.49	degrees Celcius
   Normal daytime temperature:	-223.80	degrees Celcius
   Normal night temperature:	-237.05	degrees Celcius
   Maximum temperature:   	-210.29	degrees Celcius
   Minimum temperature:   	-250.54	degrees Celcius
   Escape Velocity:		2.96	km/sec
   Molecular weight retained:	90.50 and above
   Surface acceleration:	164.10	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.138
   Length of year:		128034.14	days
   Length of day:		37.41	hours
   Boiling point of water:	-84.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


