                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486b6
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6192 K
Stellar class: F8
Age: 1.161 billion years  (5.673 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.340 AU	no atmosphere
2	  0.356 AU	no atmosphere
3	  0.535 AU	no atmosphere
4	  0.745 AU	no atmosphere
5	  1.221 AU	
6	  1.242 AU	high pressure
7	  1.582 AU	high pressure
8	  2.124 AU	no atmosphere
9	  3.470 AU	gas giant
10	  5.585 AU	gas giant
11	  9.898 AU	gas giant
12	 17.609 AU	gas giant
13	 35.695 AU	gas giant
14	 50.048 AU	no atmosphere



Planet 1	
   Distance from primary:	0.340	AU
   Mass:			1/387.1	Earth masses
   Equatorial radius:		888.8	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.70	degrees Celcius
   Normal daytime temperature:	473.99	degrees Celcius
   Normal night temperature:	-179.37	degrees Celcius
   Maximum temperature:   	476.99	degrees Celcius
   Minimum temperature:   	-189.77	degrees Celcius
   Escape Velocity:		1.52	km/sec
   Molecular weight retained:	342.44 and above
   Surface acceleration:	130.40	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.073
   Length of year:		69.01	days
   Length of day:		1656.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.356	AU
   Mass:			0.140	Earth masses
   Equatorial radius:		3349.8	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		242.98	degrees Celcius
   Normal daytime temperature:	458.67	degrees Celcius
   Normal night temperature:	-183.33	degrees Celcius
   Maximum temperature:   	461.64	degrees Celcius
   Minimum temperature:   	-193.41	degrees Celcius
   Escape Velocity:		5.76	km/sec
   Molecular weight retained:	23.90 and above
   Surface acceleration:	495.79	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.081
   Length of year:		73.76	days
   Length of day:		1770.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 3	
   Distance from primary:	0.535	AU
   Mass:			0.364	Earth masses
   Equatorial radius:		4598.7	km
   Density:			5.341	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.19	degrees Celcius
   Maximum temperature:   	348.52	degrees Celcius
   Minimum temperature:   	-216.83	degrees Celcius
   Escape Velocity:		7.95	km/sec
   Molecular weight retained:	12.57 and above
   Surface acceleration:	686.42	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.059
   Length of year:		136.05	days
   Length of day:		3265.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.745	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1502.3	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.133
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		86.09	degrees Celcius
   Maximum temperature:   	268.63	degrees Celcius
   Minimum temperature:   	-226.50	degrees Celcius
   Escape Velocity:		2.57	km/sec
   Molecular weight retained:	119.73 and above
   Surface acceleration:	220.67	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.055
   Length of year:		223.32	days
   Length of day:		4099.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.221	AU
   Mass:			0.362	Earth masses
   Equatorial radius:		4589.9	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.176
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.114	Earth atmospheres
   Surface temperature:		13.49	degrees Celcius
   Normal daytime temperature:	26.61	degrees Celcius
   Normal night temperature:	-0.19	degrees Celcius
   Maximum temperature:   	57.74	degrees Celcius
   Minimum temperature:   	-32.75	degrees Celcius
   Escape Velocity:		7.93	km/sec
   Molecular weight retained:	12.62 and above
   Surface acceleration:	685.05	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.221
   Length of year:		468.76	days
   Length of day:		18.52	hours
   Boiling point of water:	48.4	degrees Celcius
   Hydrosphere percentage:	43.18
   Cloud cover percentage:	29.26
   Ice cover percentage:	1.86
   liquids at surface:
				Ethanol      melts at -114  boils at 30
				Mercury      melts at -39   boils at 270
				Bromine      melts at -7    boils at 14
				Water        melts at 0     boils at 49
   gasses in atmosphere:
				Oxygen           84.0%  PP   95.6 mb
				Nitrogen         15.9%  PP   18.1 mb


Planet 6	
   Distance from primary:	1.242	AU
   Mass:			2.095	Earth masses
   Equatorial radius:		8133.8	km
   Density:			5.555	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		1.29	Earth gees
   Surface pressure:		4.191	Earth atmospheres
   Surface temperature:		22.43	degrees Celcius
   Normal daytime temperature:	24.40	degrees Celcius
   Normal night temperature:	20.34	degrees Celcius
   Maximum temperature:   	36.72	degrees Celcius
   Minimum temperature:   	7.40	degrees Celcius
   Escape Velocity:		14.33	km/sec
   Molecular weight retained:	3.86 and above
   Surface acceleration:	1262.68	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.440
   Length of year:		481.13	days
   Length of day:		13.52	hours
   Boiling point of water:	144.1	degrees Celcius
   Hydrosphere percentage:	87.40
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.53
   liquids at surface:
				Ethanol      melts at -114  boils at 120
				Mercury      melts at -39   boils at 431
				Bromine      melts at -7    boils at 99
				Water        melts at 0     boils at 144
   gasses in atmosphere:
				Nitrogen          2.6%  PP  107.4 mb
				Helium           97.4%  PP 4082.5 mb


Planet 7	
   Distance from primary:	1.582	AU
   Mass:			2.410	Earth masses
   Equatorial radius:		8507.5	km
   Density:			5.586	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		1.35	Earth gees
   Surface pressure:		5.539	Earth atmospheres
   Surface temperature:		13.97	degrees Celcius
   Normal daytime temperature:	15.59	degrees Celcius
   Normal night temperature:	12.24	degrees Celcius
   Maximum temperature:   	27.36	degrees Celcius
   Minimum temperature:   	-0.11	degrees Celcius
   Escape Velocity:		15.03	km/sec
   Molecular weight retained:	3.51 and above
   Surface acceleration:	1328.04	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.380
   Length of year:		691.75	days
   Length of day:		13.16	hours
   Boiling point of water:	154.0	degrees Celcius
   Hydrosphere percentage:	91.76
   Cloud cover percentage:	62.22
   Ice cover percentage:	1.86
   liquids at surface:
				Ethanol      melts at -114  boils at 129
				Mercury      melts at -39   boils at 448
				Bromine      melts at -7    boils at 108
				Water        melts at 0     boils at 154
   gasses in atmosphere:
				Nitrogen          0.7%  PP   41.4 mb
				Helium           99.3%  PP 5497.2 mb


Planet 8	
   Distance from primary:	2.124	AU
   Mass:			0.089	Earth masses
   Equatorial radius:		2883.4	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.006	Earth atmospheres
   Surface temperature:		-79.07	degrees Celcius
   Normal daytime temperature:	-60.10	degrees Celcius
   Normal night temperature:	-98.17	degrees Celcius
   Maximum temperature:   	-33.88	degrees Celcius
   Minimum temperature:   	-125.24	degrees Celcius
   Escape Velocity:		4.95	km/sec
   Molecular weight retained:	32.33 and above
   Surface acceleration:	425.71	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.355
   Length of year:		1075.80	days
   Length of day:		23.26	hours
   Boiling point of water:	-1.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	37.05
   liquids at surface:
				Ethanol      melts at -114  boils at -15
   gasses in atmosphere:
				Ozone            91.0%  PP    5.7 mb
				Krypton           7.9%  PP    0.5 mb
				Xenon             1.0%  PP    0.1 mb


Planet 9	*gas giant*
   Distance from primary:	3.470	AU
   Mass:			308.298	Earth masses
   Equatorial radius:		61287.4	km
   Density:			1.911	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		63.34	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	3273.16	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.499
   Length of year:		2246.23	days
   Length of day:		7.14	hours


Planet 10	*gas giant*
   Distance from primary:	5.585	AU
   Mass:			8.747	Earth masses
   Equatorial radius:		22560.7	km
   Density:			1.087	grams/cc
   Eccentricity of orbit:	0.191
   Escape Velocity:		17.58	km/sec
   Molecular weight retained:	2.57 and above
   Surface acceleration:	685.31	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.524
   Length of year:		4588.63	days
   Length of day:		15.61	hours


Planet 11	*gas giant*
   Distance from primary:	9.898	AU
   Mass:			59.763	Earth masses
   Equatorial radius:		41445.8	km
   Density:			1.198	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		33.91	km/sec
   Molecular weight retained:	0.69 and above
   Surface acceleration:	1387.43	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.493
   Length of year:		10824.13	days
   Length of day:		10.97	hours


Planet 12	*gas giant*
   Distance from primary:	17.609	AU
   Mass:			336.452	Earth masses
   Equatorial radius:		71981.7	km
   Density:			1.287	grams/cc
   Eccentricity of orbit:	0.161
   Escape Velocity:		61.06	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	2589.51	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.494
   Length of year:		25674.81	days
   Length of day:		8.03	hours


Planet 13	*gas giant*
   Distance from primary:	35.695	AU
   Mass:			3.179	Earth masses
   Equatorial radius:		19601.5	km
   Density:			0.602	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		11.37	km/sec
   Molecular weight retained:	6.14 and above
   Surface acceleration:	329.98	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.457
   Length of year:		74136.10	days
   Length of day:		22.50	hours


Planet 14	
   Distance from primary:	50.048	AU
   Mass:			0.074	Earth masses
   Equatorial radius:		3638.0	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.49	degrees Celcius
   Normal daytime temperature:	-224.63	degrees Celcius
   Normal night temperature:	-236.24	degrees Celcius
   Maximum temperature:   	-210.25	degrees Celcius
   Minimum temperature:   	-250.67	degrees Celcius
   Escape Velocity:		4.04	km/sec
   Molecular weight retained:	48.64 and above
   Surface acceleration:	224.31	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.163
   Length of year:		123082.78	days
   Length of day:		32.00	hours
   Boiling point of water:	-70.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


