                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504893a
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6300 K
Stellar class: F8
Age: 5.636 billion years  (1.115 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.315 AU	no atmosphere
2	  0.352 AU	no atmosphere
3	  0.573 AU	no atmosphere
4	  0.840 AU	greenhouse
5	  1.488 AU	gas giant
6	  2.340 AU	cold
7	  3.868 AU	cold
8	  4.940 AU	gas giant
9	  6.028 AU	gas giant
10	  9.747 AU	gas giant
11	 15.618 AU	gas giant
12	 40.422 AU	gas giant



Planet 1	
   Distance from primary:	0.315	AU
   Mass:			0.142	Earth masses
   Equatorial radius:		3371.5	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.066
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		280.03	degrees Celcius
   Normal daytime temperature:	503.15	degrees Celcius
   Normal night temperature:	-171.44	degrees Celcius
   Maximum temperature:   	506.27	degrees Celcius
   Minimum temperature:   	-182.74	degrees Celcius
   Escape Velocity:		5.80	km/sec
   Molecular weight retained:	23.59 and above
   Surface acceleration:	499.06	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.065
   Length of year:		61.27	days
   Length of day:		1470.59	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.352	AU
   Mass:			0.018	Earth masses
   Equatorial radius:		1689.5	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		249.44	degrees Celcius
   Normal daytime temperature:	466.51	degrees Celcius
   Normal night temperature:	-181.79	degrees Celcius
   Maximum temperature:   	469.56	degrees Celcius
   Minimum temperature:   	-192.28	degrees Celcius
   Escape Velocity:		2.90	km/sec
   Molecular weight retained:	94.61 and above
   Surface acceleration:	248.30	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.070
   Length of year:		72.39	days
   Length of day:		1737.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 3	
   Distance from primary:	0.573	AU
   Mass:			0.112	Earth masses
   Equatorial radius:		3116.9	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		138.04	degrees Celcius
   Maximum temperature:   	333.40	degrees Celcius
   Minimum temperature:   	-219.14	degrees Celcius
   Escape Velocity:		5.36	km/sec
   Molecular weight retained:	27.64 and above
   Surface acceleration:	460.73	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.053
   Length of year:		150.71	days
   Length of day:		3616.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.840	AU
   Mass:			1.882	Earth masses
   Equatorial radius:		7858.8	km
   Density:			5.533	grams/cc
   Eccentricity of orbit:	0.147
   Surface gravity:		1.24	Earth gees
   Surface pressure:		256.809	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		524.58	degrees Celcius
   Maximum temperature:   	527.13	degrees Celcius
   Minimum temperature:   	519.29	degrees Celcius
   Escape Velocity:		13.82	km/sec
   Molecular weight retained:	4.16 and above
   Surface acceleration:	1215.22	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.597
   Length of year:		267.23	days
   Length of day:		15.85	hours
   Boiling point of water:	359.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1336
				Cesium       melts at 28    boils at 1384
				Gallium      melts at 30    boils at 4261
				Rubidium     melts at 39    boils at 1355
				Potassium    melts at 63    boils at 1487
				Sodium       melts at 98    boils at 1683
				Indium       melts at 157   boils at 3713
				Lithium      melts at 181   boils at 2472
				Selenium     melts at 217   boils at 1350
				Tin          melts at 232   boils at 4633
				Polonium     melts at 254   boils at 1819
				Bismuth      melts at 271   boils at 2839
				Thallium     melts at 304   boils at 2658
				Cadmium      melts at 321   boils at 1485
				Lead         melts at 328   boils at 3156
				Zinc         melts at 420   boils at 1726
				Tellurium    melts at 450   boils at 1867
   gasses in atmosphere:
				Sulfur           20.6%  PP 52885.8 mb
				Nitrogen         78.8%  PP 202387.3 mb
				Phosphorus        0.4%  PP 1052.7 mb


Planet 5	*gas giant*
   Distance from primary:	1.488	AU
   Mass:			26.310	Earth masses
   Equatorial radius:		27842.5	km
   Density:			1.739	grams/cc
   Eccentricity of orbit:	0.341
   Escape Velocity:		27.45	km/sec
   Molecular weight retained:	1.05 and above
   Surface acceleration:	1353.45	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.507
   Length of year:		630.15	days
   Length of day:		11.11	hours


Planet 6	
   Distance from primary:	2.340	AU
   Mass:			0.693	Earth masses
   Equatorial radius:		5682.5	km
   Density:			5.392	grams/cc
   Eccentricity of orbit:	0.100
   Surface gravity:		0.87	Earth gees
   Surface pressure:		0.491	Earth atmospheres
   Surface temperature:		-89.84	degrees Celcius
   Normal daytime temperature:	-85.73	degrees Celcius
   Normal night temperature:	-94.17	degrees Celcius
   Maximum temperature:   	-65.37	degrees Celcius
   Minimum temperature:   	-116.07	degrees Celcius
   Escape Velocity:		9.87	km/sec
   Molecular weight retained:	8.16 and above
   Surface acceleration:	856.35	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.610
   Length of year:		1242.05	days
   Length of day:		16.39	hours
   Boiling point of water:	81.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	95.09
   liquids at surface:
				Ethanol      melts at -114  boils at 61
				Chlorine     melts at -101  boils at -46
   gasses in atmosphere:
				Oxygen            0.3%  PP    1.4 mb
				Nitrogen         99.6%  PP  489.1 mb
				Ozone             0.1%  PP    0.4 mb


Planet 7	
   Distance from primary:	3.868	AU
   Mass:			0.793	Earth masses
   Equatorial radius:		5938.1	km
   Density:			5.406	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.673	Earth atmospheres
   Surface temperature:		-138.64	degrees Celcius
   Normal daytime temperature:	-136.09	degrees Celcius
   Normal night temperature:	-141.33	degrees Celcius
   Maximum temperature:   	-118.95	degrees Celcius
   Minimum temperature:   	-160.10	degrees Celcius
   Escape Velocity:		10.32	km/sec
   Molecular weight retained:	7.45 and above
   Surface acceleration:	897.17	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.702
   Length of year:		2639.90	days
   Length of day:		16.00	hours
   Boiling point of water:	89.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -117
   gasses in atmosphere:
				Oxygen            0.1%  PP    0.6 mb
				Nitrogen         99.9%  PP  672.1 mb


Planet 8	*gas giant*
   Distance from primary:	4.940	AU
   Mass:			1.728	Earth masses
   Equatorial radius:		13905.2	km
   Density:			0.917	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		9.95	km/sec
   Molecular weight retained:	8.01 and above
   Surface acceleration:	356.30	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.515
   Length of year:		3810.65	days
   Length of day:		21.65	hours


Planet 9	*gas giant*
   Distance from primary:	6.028	AU
   Mass:			145.590	Earth masses
   Equatorial radius:		51527.7	km
   Density:			1.518	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		47.47	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2186.70	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.516
   Length of year:		5135.12	days
   Length of day:		8.74	hours


Planet 10	*gas giant*
   Distance from primary:	9.747	AU
   Mass:			12.956	Earth masses
   Equatorial radius:		26484.6	km
   Density:			0.995	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		19.75	km/sec
   Molecular weight retained:	2.03 and above
   Surface acceleration:	736.59	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.541
   Length of year:		10561.34	days
   Length of day:		15.06	hours


Planet 11	*gas giant*
   Distance from primary:	15.618	AU
   Mass:			615.672	Earth masses
   Equatorial radius:		84946.2	km
   Density:			1.433	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		76.03	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3402.52	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.521
   Length of year:		21403.32	days
   Length of day:		7.01	hours


Planet 12	*gas giant*
   Distance from primary:	40.422	AU
   Mass:			0.972	Earth masses
   Equatorial radius:		14009.9	km
   Density:			0.505	grams/cc
   Eccentricity of orbit:	0.071
   Escape Velocity:		7.44	km/sec
   Molecular weight retained:	14.34 and above
   Surface acceleration:	197.54	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.476
   Length of year:		89197.82	days
   Length of day:		29.08	hours


