                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481bb
Stellar mass: 1.10 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6375 K
Stellar class: F7
Age: 2.198 billion years  (4.802 billion left on main sequence)
Habitable ecosphere radius: 1.252 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.707 AU	no atmosphere
3	  0.821 AU	no atmosphere
4	  0.943 AU	greenhouse
5	  1.908 AU	cold
6	  2.587 AU	gas giant
7	  6.119 AU	gas giant
8	 15.229 AU	gas giant
9	 33.706 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.358	AU
   Mass:			0.130	Earth masses
   Equatorial radius:		3269.3	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.318
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.50	degrees Celcius
   Normal daytime temperature:	452.67	degrees Celcius
   Normal night temperature:	-158.92	degrees Celcius
   Maximum temperature:   	457.45	degrees Celcius
   Minimum temperature:   	-176.23	degrees Celcius
   Escape Velocity:		5.62	km/sec
   Molecular weight retained:	25.10 and above
   Surface acceleration:	483.65	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.057
   Length of year:		74.77	days
   Length of day:		929.11	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.707	AU
   Mass:			0.196	Earth masses
   Equatorial radius:		3751.7	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.194
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		91.34	degrees Celcius
   Normal daytime temperature:	246.25	degrees Celcius
   Normal night temperature:	-114.38	degrees Celcius
   Maximum temperature:   	259.36	degrees Celcius
   Minimum temperature:   	-140.81	degrees Celcius
   Escape Velocity:		6.46	km/sec
   Molecular weight retained:	19.01 and above
   Surface acceleration:	556.62	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.069
   Length of year:		207.38	days
   Length of day:		264.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	0.821	AU
   Mass:			0.186	Earth masses
   Equatorial radius:		3686.0	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		66.55	degrees Celcius
   Normal daytime temperature:	114.75	degrees Celcius
   Normal night temperature:	17.42	degrees Celcius
   Maximum temperature:   	145.78	degrees Celcius
   Minimum temperature:   	-14.35	degrees Celcius
   Escape Velocity:		6.35	km/sec
   Molecular weight retained:	19.70 and above
   Surface acceleration:	546.65	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.053
   Length of year:		259.43	days
   Length of day:		33.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.943	AU
   Mass:			1.238	Earth masses
   Equatorial radius:		6864.2	km
   Density:			5.462	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		1.07	Earth gees
   Surface pressure:		159.541	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		426.03	degrees Celcius
   Maximum temperature:   	429.37	degrees Celcius
   Minimum temperature:   	420.93	degrees Celcius
   Escape Velocity:		11.99	km/sec
   Molecular weight retained:	5.52 and above
   Surface acceleration:	1047.84	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.574
   Length of year:		319.12	days
   Length of day:		15.36	hours
   Boiling point of water:	323.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1246
				Cesium       melts at 28    boils at 1291
				Gallium      melts at 30    boils at 4006
				Rubidium     melts at 39    boils at 1263
				Potassium    melts at 63    boils at 1388
				Sodium       melts at 98    boils at 1573
				Sulfur       melts at 113   boils at 875
				Indium       melts at 157   boils at 3489
				Lithium      melts at 181   boils at 2317
				Selenium     melts at 217   boils at 1259
				Tin          melts at 232   boils at 4358
				Polonium     melts at 254   boils at 1702
				Bismuth      melts at 271   boils at 2664
				Thallium     melts at 304   boils at 2493
				Cadmium      melts at 321   boils at 1387
				Lead         melts at 328   boils at 2963
				Zinc         melts at 420   boils at 1614
   gasses in atmosphere:
				Nitrogen         99.3%  PP 158348.3 mb
				Phosphorus        0.5%  PP  784.1 mb
				CarbonDioxide     0.1%  PP   82.9 mb
				Ethanol           0.1%  PP   83.7 mb


Planet 5	
   Distance from primary:	1.908	AU
   Mass:			1.390	Earth masses
   Equatorial radius:		7125.9	km
   Density:			5.480	grams/cc
   Eccentricity of orbit:	0.176
   Surface gravity:		1.11	Earth gees
   Surface pressure:		1.800	Earth atmospheres
   Surface temperature:		-82.23	degrees Celcius
   Normal daytime temperature:	-80.16	degrees Celcius
   Normal night temperature:	-84.41	degrees Celcius
   Maximum temperature:   	-63.87	degrees Celcius
   Minimum temperature:   	-101.89	degrees Celcius
   Escape Velocity:		12.47	km/sec
   Molecular weight retained:	5.10 and above
   Surface acceleration:	1091.28	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.729
   Length of year:		918.90	days
   Length of day:		14.51	hours
   Boiling point of water:	116.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 94
				Chlorine     melts at -101  boils at -23
   gasses in atmosphere:
				Oxygen            1.1%  PP   20.1 mb
				Nitrogen         98.8%  PP 1778.4 mb


Planet 6	*gas giant*
   Distance from primary:	2.587	AU
   Mass:			47.384	Earth masses
   Equatorial radius:		34679.3	km
   Density:			1.621	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		33.01	km/sec
   Molecular weight retained:	0.73 and above
   Surface acceleration:	1571.21	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.542
   Length of year:		1450.99	days
   Length of day:		10.31	hours


Planet 7	*gas giant*
   Distance from primary:	6.119	AU
   Mass:			289.869	Earth masses
   Equatorial radius:		63189.4	km
   Density:			1.639	grams/cc
   Eccentricity of orbit:	0.208
   Escape Velocity:		60.49	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2895.02	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.472
   Length of year:		5276.95	days
   Length of day:		7.60	hours


Planet 8	*gas giant*
   Distance from primary:	15.229	AU
   Mass:			970.430	Earth masses
   Equatorial radius:		96983.4	km
   Density:			1.518	grams/cc
   Eccentricity of orbit:	0.229
   Escape Velocity:		89.33	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4114.42	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.511
   Length of year:		20697.88	days
   Length of day:		6.37	hours


Planet 9	*gas giant*
   Distance from primary:	33.706	AU
   Mass:			2.996	Earth masses
   Equatorial radius:		19197.5	km
   Density:			0.604	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		11.16	km/sec
   Molecular weight retained:	6.38 and above
   Surface acceleration:	324.19	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.511
   Length of year:		68241.45	days
   Length of day:		22.70	hours


