                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047ed9
Stellar mass: 1.09 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6064 K
Stellar class: F9
Age: 4.164 billion years  (2.935 billion left on main sequence)
Habitable ecosphere radius: 1.241 AU

Planets present at:
1	  0.350 AU	no atmosphere
2	  0.464 AU	no atmosphere
3	  0.527 AU	no atmosphere
4	  0.830 AU	greenhouse
5	  1.073 AU	no atmosphere
6	  1.778 AU	cold
7	  2.978 AU	gas giant
8	  4.505 AU	cold
9	  7.269 AU	gas giant
10	 12.262 AU	gas giant
11	 29.548 AU	no atmosphere
12	 33.806 AU	gas giant
13	 51.051 AU	no atmosphere



Planet 1	
   Distance from primary:	0.350	AU
   Mass:			0.075	Earth masses
   Equatorial radius:		2730.7	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		243.33	degrees Celcius
   Normal daytime temperature:	459.04	degrees Celcius
   Normal night temperature:	-182.68	degrees Celcius
   Maximum temperature:   	462.26	degrees Celcius
   Minimum temperature:   	-193.75	degrees Celcius
   Escape Velocity:		4.69	km/sec
   Molecular weight retained:	36.08 and above
   Surface acceleration:	402.87	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.066
   Length of year:		72.20	days
   Length of day:		1732.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.464	AU
   Mass:			1/179.5	Earth masses
   Equatorial radius:		1148.2	km
   Density:			5.252	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		174.24	degrees Celcius
   Maximum temperature:   	378.03	degrees Celcius
   Minimum temperature:   	-210.95	degrees Celcius
   Escape Velocity:		1.97	km/sec
   Molecular weight retained:	205.11 and above
   Surface acceleration:	168.53	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.075
   Length of year:		110.31	days
   Length of day:		2647.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.527	AU
   Mass:			0.476	Earth masses
   Equatorial radius:		5022.3	km
   Density:			5.359	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		0.77	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.06	degrees Celcius
   Maximum temperature:   	345.87	degrees Celcius
   Minimum temperature:   	-216.95	degrees Celcius
   Escape Velocity:		8.69	km/sec
   Molecular weight retained:	10.51 and above
   Surface acceleration:	752.26	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.062
   Length of year:		133.57	days
   Length of day:		3205.77	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.830	AU
   Mass:			0.785	Earth masses
   Equatorial radius:		5917.2	km
   Density:			5.405	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.91	Earth gees
   Surface pressure:		65.721	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		386.76	degrees Celcius
   Maximum temperature:   	392.04	degrees Celcius
   Minimum temperature:   	379.82	degrees Celcius
   Escape Velocity:		10.28	km/sec
   Molecular weight retained:	7.50 and above
   Surface acceleration:	893.82	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.427
   Length of year:		264.03	days
   Length of day:		20.32	hours
   Boiling point of water:	266.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1102
				Cesium       melts at 28    boils at 1142
				Gallium      melts at 30    boils at 3600
				Rubidium     melts at 39    boils at 1118
				Potassium    melts at 63    boils at 1230
				Sodium       melts at 98    boils at 1398
				Sulfur       melts at 113   boils at 766
				Indium       melts at 157   boils at 3133
				Lithium      melts at 181   boils at 2072
				Selenium     melts at 217   boils at 1113
				Tin          melts at 232   boils at 3919
				Polonium     melts at 254   boils at 1514
				Bismuth      melts at 271   boils at 2386
				Thallium     melts at 304   boils at 2231
				Cadmium      melts at 321   boils at 1229
				Lead         melts at 328   boils at 2656
   gasses in atmosphere:
				Nitrogen         99.0%  PP 65048.9 mb
				Phosphorus        0.7%  PP  443.7 mb
				CarbonDioxide     0.1%  PP   50.5 mb
				Ozone             0.1%  PP   45.6 mb
				Ethanol           0.1%  PP   51.5 mb


Planet 5	
   Distance from primary:	1.073	AU
   Mass:			1/129.2	Earth masses
   Equatorial radius:		1281.2	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		19.88	degrees Celcius
   Maximum temperature:   	183.99	degrees Celcius
   Minimum temperature:   	-234.55	degrees Celcius
   Escape Velocity:		2.20	km/sec
   Molecular weight retained:	164.70 and above
   Surface acceleration:	188.10	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.088
   Length of year:		388.54	days
   Length of day:		9325.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	
   Distance from primary:	1.778	AU
   Mass:			1.434	Earth masses
   Equatorial radius:		7198.8	km
   Density:			5.485	grams/cc
   Eccentricity of orbit:	0.145
   Surface gravity:		1.12	Earth gees
   Surface pressure:		1.669	Earth atmospheres
   Surface temperature:		-77.91	degrees Celcius
   Normal daytime temperature:	-75.72	degrees Celcius
   Normal night temperature:	-80.21	degrees Celcius
   Maximum temperature:   	-59.51	degrees Celcius
   Minimum temperature:   	-97.59	degrees Celcius
   Escape Velocity:		12.60	km/sec
   Molecular weight retained:	5.00 and above
   Surface acceleration:	1103.45	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.735
   Length of year:		828.19	days
   Length of day:		14.45	hours
   Boiling point of water:	114.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.07
   Ice cover percentage:	97.35
   liquids at surface:
				Ethanol      melts at -114  boils at 92
				Chlorine     melts at -101  boils at -25
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1666.1 mb
				Ozone             0.1%  PP    0.8 mb


Planet 7	*gas giant*
   Distance from primary:	2.978	AU
   Mass:			513.129	Earth masses
   Equatorial radius:		70345.7	km
   Density:			2.103	grams/cc
   Eccentricity of orbit:	0.142
   Escape Velocity:		76.27	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	4135.14	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.501
   Length of year:		1794.01	days
   Length of day:		6.36	hours


Planet 8	
   Distance from primary:	4.505	AU
   Mass:			1.132	Earth masses
   Equatorial radius:		6667.1	km
   Density:			5.449	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		1.04	Earth gees
   Surface pressure:		0.995	Earth atmospheres
   Surface temperature:		-137.69	degrees Celcius
   Normal daytime temperature:	-135.67	degrees Celcius
   Normal night temperature:	-139.82	degrees Celcius
   Maximum temperature:   	-119.26	degrees Celcius
   Minimum temperature:   	-157.77	degrees Celcius
   Escape Velocity:		11.64	km/sec
   Molecular weight retained:	5.86 and above
   Surface acceleration:	1015.38	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.578
   Length of year:		3340.66	days
   Length of day:		15.04	hours
   Boiling point of water:	99.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	85.75
   liquids at surface:
				Ozone        melts at -193  boils at -112
   gasses in atmosphere:
				Oxygen            0.2%  PP    1.8 mb
				Nitrogen         99.8%  PP  993.0 mb


Planet 9	*gas giant*
   Distance from primary:	7.269	AU
   Mass:			5.258	Earth masses
   Equatorial radius:		19919.7	km
   Density:			0.949	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		14.51	km/sec
   Molecular weight retained:	3.77 and above
   Surface acceleration:	528.39	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.468
   Length of year:		6847.12	days
   Length of day:		17.78	hours


Planet 10	*gas giant*
   Distance from primary:	12.262	AU
   Mass:			1028.735	Earth masses
   Equatorial radius:		96954.2	km
   Density:			1.611	grams/cc
   Eccentricity of orbit:	0.129
   Escape Velocity:		91.99	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4364.25	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.513
   Length of year:		14980.69	days
   Length of day:		6.19	hours


Planet 11	
   Distance from primary:	29.548	AU
   Mass:			0.600	Earth masses
   Equatorial radius:		7227.2	km
   Density:			2.269	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-216.93	degrees Celcius
   Normal daytime temperature:	-211.34	degrees Celcius
   Normal night temperature:	-222.48	degrees Celcius
   Maximum temperature:   	-196.45	degrees Celcius
   Minimum temperature:   	-238.36	degrees Celcius
   Escape Velocity:		8.14	km/sec
   Molecular weight retained:	11.99 and above
   Surface acceleration:	458.22	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.149
   Length of year:		56116.57	days
   Length of day:		22.39	hours
   Boiling point of water:	-26.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.13
   liquids at surface:
				Fluorine     melts at -220  boils at -215
				Oxygen       melts at -218  boils at -211
   gasses in atmosphere:
				Neon             100.0%  PP    0.9 mb


Planet 12	*gas giant*
   Distance from primary:	33.806	AU
   Mass:			6.670	Earth masses
   Equatorial radius:		24268.7	km
   Density:			0.666	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		14.81	km/sec
   Molecular weight retained:	3.62 and above
   Surface acceleration:	451.60	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.510
   Length of year:		68671.97	days
   Length of day:		19.23	hours


Planet 13	
   Distance from primary:	51.051	AU
   Mass:			0.076	Earth masses
   Equatorial radius:		3664.2	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.127
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.14	degrees Celcius
   Normal daytime temperature:	-225.38	degrees Celcius
   Normal night temperature:	-236.77	degrees Celcius
   Maximum temperature:   	-207.99	degrees Celcius
   Minimum temperature:   	-253.59	degrees Celcius
   Escape Velocity:		4.07	km/sec
   Molecular weight retained:	47.94 and above
   Surface acceleration:	225.96	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.140
   Length of year:		127440.02	days
   Length of day:		31.88	hours
   Boiling point of water:	-69.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


