                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481f3
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6258 K
Stellar class: F8
Age: 5.136 billion years  (1.858 billion left on main sequence)
Habitable ecosphere radius: 1.253 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.478 AU	no atmosphere
3	  0.729 AU	no atmosphere
4	  0.805 AU	no atmosphere
5	  0.976 AU	greenhouse
6	  1.505 AU	cold
7	  2.230 AU	gas giant
8	  3.303 AU	cold
9	  4.080 AU	gas giant
10	  5.976 AU	cold
11	  6.263 AU	gas giant
12	 13.159 AU	gas giant
13	 31.409 AU	gas giant
14	 51.028 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.358	AU
   Mass:			0.087	Earth masses
   Equatorial radius:		2862.1	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.212
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.43	degrees Celcius
   Normal daytime temperature:	453.90	degrees Celcius
   Normal night temperature:	-169.52	degrees Celcius
   Maximum temperature:   	457.98	degrees Celcius
   Minimum temperature:   	-184.04	degrees Celcius
   Escape Velocity:		4.92	km/sec
   Molecular weight retained:	32.82 and above
   Surface acceleration:	422.52	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.058
   Length of year:		74.81	days
   Length of day:		1167.52	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.478	AU
   Mass:			0.206	Earth masses
   Equatorial radius:		3810.7	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		172.03	degrees Celcius
   Maximum temperature:   	375.34	degrees Celcius
   Minimum temperature:   	-211.73	degrees Celcius
   Escape Velocity:		6.57	km/sec
   Molecular weight retained:	18.42 and above
   Surface acceleration:	565.59	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.054
   Length of year:		115.26	days
   Length of day:		2766.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.729	AU
   Mass:			0.058	Earth masses
   Equatorial radius:		2500.0	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		85.56	degrees Celcius
   Maximum temperature:   	267.87	degrees Celcius
   Minimum temperature:   	-226.89	degrees Celcius
   Escape Velocity:		4.29	km/sec
   Molecular weight retained:	43.09 and above
   Surface acceleration:	368.46	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.074
   Length of year:		216.87	days
   Length of day:		5204.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.805	AU
   Mass:			0.136	Earth masses
   Equatorial radius:		3322.8	km
   Density:			5.295	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		69.79	degrees Celcius
   Maximum temperature:   	247.97	degrees Celcius
   Minimum temperature:   	-228.76	degrees Celcius
   Escape Velocity:		5.72	km/sec
   Molecular weight retained:	24.29 and above
   Surface acceleration:	491.72	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.056
   Length of year:		251.82	days
   Length of day:		6043.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.976	AU
   Mass:			1.832	Earth masses
   Equatorial radius:		7790.4	km
   Density:			5.528	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		1.23	Earth gees
   Surface pressure:		337.900	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		516.94	degrees Celcius
   Maximum temperature:   	519.11	degrees Celcius
   Minimum temperature:   	512.18	degrees Celcius
   Escape Velocity:		13.69	km/sec
   Molecular weight retained:	4.23 and above
   Surface acceleration:	1203.51	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.544
   Length of year:		335.98	days
   Length of day:		14.53	hours
   Boiling point of water:	381.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1394
				Cesium       melts at 28    boils at 1443
				Gallium      melts at 30    boils at 4422
				Rubidium     melts at 39    boils at 1413
				Potassium    melts at 63    boils at 1549
				Sodium       melts at 98    boils at 1753
				Indium       melts at 157   boils at 3855
				Lithium      melts at 181   boils at 2569
				Selenium     melts at 217   boils at 1408
				Tin          melts at 232   boils at 4808
				Polonium     melts at 254   boils at 1894
				Bismuth      melts at 271   boils at 2950
				Thallium     melts at 304   boils at 2762
				Cadmium      melts at 321   boils at 1548
				Lead         melts at 328   boils at 3278
				Zinc         melts at 420   boils at 1797
				Tellurium    melts at 450   boils at 1943
   gasses in atmosphere:
				Sulfur           19.9%  PP 67093.3 mb
				Nitrogen         79.6%  PP 268869.9 mb
				Phosphorus        0.4%  PP 1337.7 mb


Planet 6	
   Distance from primary:	1.505	AU
   Mass:			0.809	Earth masses
   Equatorial radius:		5975.5	km
   Density:			5.408	grams/cc
   Eccentricity of orbit:	0.150
   Surface gravity:		0.92	Earth gees
   Surface pressure:		0.533	Earth atmospheres
   Surface temperature:		-10.65	degrees Celcius
   Normal daytime temperature:	-5.09	degrees Celcius
   Normal night temperature:	-16.52	degrees Celcius
   Maximum temperature:   	19.00	degrees Celcius
   Minimum temperature:   	-42.04	degrees Celcius
   Escape Velocity:		10.39	km/sec
   Molecular weight retained:	7.35 and above
   Surface acceleration:	903.17	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.295
   Length of year:		644.05	days
   Length of day:		16.06	hours
   Boiling point of water:	83.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	6.08
   Ice cover percentage:	21.38
   liquids at surface:
				Ethanol      melts at -114  boils at 63
				Mercury      melts at -39   boils at 329
   gasses in atmosphere:
				Oxygen            0.4%  PP    2.4 mb
				Nitrogen         99.3%  PP  529.6 mb
				CarbonDioxide     0.1%  PP    0.4 mb
				Ozone             0.1%  PP    0.4 mb


Planet 7	*gas giant*
   Distance from primary:	2.230	AU
   Mass:			5.048	Earth masses
   Equatorial radius:		17825.1	km
   Density:			1.272	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		15.03	km/sec
   Molecular weight retained:	3.51 and above
   Surface acceleration:	633.62	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.488
   Length of year:		1161.16	days
   Length of day:		16.24	hours


Planet 8	
   Distance from primary:	3.303	AU
   Mass:			0.950	Earth masses
   Equatorial radius:		6296.9	km
   Density:			5.427	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.660	Earth atmospheres
   Surface temperature:		-118.52	degrees Celcius
   Normal daytime temperature:	-115.64	degrees Celcius
   Normal night temperature:	-121.55	degrees Celcius
   Maximum temperature:   	-98.94	degrees Celcius
   Minimum temperature:   	-139.70	degrees Celcius
   Escape Velocity:		10.97	km/sec
   Molecular weight retained:	6.60 and above
   Surface acceleration:	954.99	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.602
   Length of year:		2093.12	days
   Length of day:		15.51	hours
   Boiling point of water:	88.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	76.01
   liquids at surface:
				Ozone        melts at -193  boils at -117
   gasses in atmosphere:
				Oxygen            0.2%  PP    1.3 mb
				Nitrogen         99.8%  PP  658.5 mb


Planet 9	*gas giant*
   Distance from primary:	4.080	AU
   Mass:			1.424	Earth masses
   Equatorial radius:		12958.5	km
   Density:			0.934	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		9.36	km/sec
   Molecular weight retained:	9.06 and above
   Surface acceleration:	338.10	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.495
   Length of year:		2873.68	days
   Length of day:		22.23	hours


Planet 10	
   Distance from primary:	5.976	AU
   Mass:			1.230	Earth masses
   Equatorial radius:		9111.1	km
   Density:			2.320	grams/cc
   Eccentricity of orbit:	0.158
   Surface gravity:		0.60	Earth gees
   Surface pressure:		1.171	Earth atmospheres
   Surface temperature:		-145.13	degrees Celcius
   Normal daytime temperature:	-142.89	degrees Celcius
   Normal night temperature:	-147.54	degrees Celcius
   Maximum temperature:   	-127.54	degrees Celcius
   Minimum temperature:   	-164.33	degrees Celcius
   Escape Velocity:		10.38	km/sec
   Molecular weight retained:	7.37 and above
   Surface acceleration:	590.84	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.431
   Length of year:		5093.96	days
   Length of day:		19.72	hours
   Boiling point of water:	104.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	49.72
   liquids at surface:
				Ozone        melts at -193  boils at -110
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1170.3 mb


Planet 11	*gas giant*
   Distance from primary:	6.263	AU
   Mass:			19.677	Earth masses
   Equatorial radius:		28888.1	km
   Density:			1.165	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		23.31	km/sec
   Molecular weight retained:	1.46 and above
   Surface acceleration:	940.28	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.514
   Length of year:		5464.71	days
   Length of day:		13.33	hours


Planet 12	*gas giant*
   Distance from primary:	13.159	AU
   Mass:			1024.812	Earth masses
   Equatorial radius:		97340.4	km
   Density:			1.585	grams/cc
   Eccentricity of orbit:	0.261
   Escape Velocity:		91.63	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4313.17	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.481
   Length of year:		16621.85	days
   Length of day:		6.22	hours


Planet 13	*gas giant*
   Distance from primary:	31.409	AU
   Mass:			10.039	Earth masses
   Equatorial radius:		27154.1	km
   Density:			0.715	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		17.17	km/sec
   Molecular weight retained:	2.69 and above
   Surface acceleration:	542.96	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.510
   Length of year:		61376.09	days
   Length of day:		17.54	hours


Planet 14	
   Distance from primary:	51.028	AU
   Mass:			0.126	Earth masses
   Equatorial radius:		4326.7	km
   Density:			2.215	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.98	degrees Celcius
   Normal daytime temperature:	-225.62	degrees Celcius
   Normal night temperature:	-236.24	degrees Celcius
   Maximum temperature:   	-212.23	degrees Celcius
   Minimum temperature:   	-249.89	degrees Celcius
   Escape Velocity:		4.81	km/sec
   Molecular weight retained:	34.25 and above
   Surface acceleration:	267.81	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.147
   Length of year:		127098.72	days
   Length of day:		29.29	hours
   Boiling point of water:	-60.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


