                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048521
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6261 K
Stellar class: F8
Age: 2.636 billion years  (4.250 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.346 AU	no atmosphere
2	  0.497 AU	no atmosphere
3	  0.598 AU	no atmosphere
4	  0.870 AU	greenhouse
5	  1.062 AU	greenhouse
6	  1.836 AU	gas giant
7	  2.858 AU	no atmosphere
8	  4.002 AU	cold
9	  5.559 AU	gas giant
10	 14.872 AU	gas giant
11	 34.627 AU	gas giant
12	 47.699 AU	no atmosphere



Planet 1	
   Distance from primary:	0.346	AU
   Mass:			0.064	Earth masses
   Equatorial radius:		2590.5	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		248.46	degrees Celcius
   Normal daytime temperature:	465.24	degrees Celcius
   Normal night temperature:	-181.36	degrees Celcius
   Maximum temperature:   	468.23	degrees Celcius
   Minimum temperature:   	-191.61	degrees Celcius
   Escape Velocity:		4.45	km/sec
   Molecular weight retained:	40.11 and above
   Surface acceleration:	381.95	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.082
   Length of year:		70.94	days
   Length of day:		1702.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.497	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		2332.7	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.066
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		164.25	degrees Celcius
   Maximum temperature:   	365.89	degrees Celcius
   Minimum temperature:   	-213.91	degrees Celcius
   Escape Velocity:		4.00	km/sec
   Molecular weight retained:	49.52 and above
   Surface acceleration:	343.57	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.064
   Length of year:		122.07	days
   Length of day:		2929.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.598	AU
   Mass:			0.702	Earth masses
   Equatorial radius:		5706.1	km
   Density:			5.393	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		127.25	degrees Celcius
   Maximum temperature:   	320.09	degrees Celcius
   Minimum temperature:   	-221.37	degrees Celcius
   Escape Velocity:		9.91	km/sec
   Molecular weight retained:	8.09 and above
   Surface acceleration:	860.10	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.050
   Length of year:		160.91	days
   Length of day:		3861.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.870	AU
   Mass:			0.827	Earth masses
   Equatorial radius:		6018.8	km
   Density:			5.411	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.93	Earth gees
   Surface pressure:		59.754	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		305.41	degrees Celcius
   Maximum temperature:   	311.02	degrees Celcius
   Minimum temperature:   	298.77	degrees Celcius
   Escape Velocity:		10.47	km/sec
   Molecular weight retained:	7.25 and above
   Surface acceleration:	910.11	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.623
   Length of year:		282.43	days
   Length of day:		17.61	hours
   Boiling point of water:	261.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 630
				Francium     melts at 27    boils at 1088
				Cesium       melts at 28    boils at 1128
				Gallium      melts at 30    boils at 3561
				Rubidium     melts at 39    boils at 1104
				Potassium    melts at 63    boils at 1215
				Sodium       melts at 98    boils at 1381
				Sulfur       melts at 113   boils at 755
				Indium       melts at 157   boils at 3098
				Lithium      melts at 181   boils at 2048
				Selenium     melts at 217   boils at 1100
				Tin          melts at 232   boils at 3876
				Polonium     melts at 254   boils at 1496
				Bismuth      melts at 271   boils at 2359
				Astatine     melts at 302   boils at 601
				Thallium     melts at 304   boils at 2206
   gasses in atmosphere:
				Nitrogen         99.1%  PP 59207.7 mb
				Phosphorus        0.6%  PP  358.4 mb
				CarbonDioxide     0.1%  PP   39.4 mb
				Ozone             0.1%  PP   37.4 mb
				Ethanol           0.1%  PP   40.0 mb


Planet 5	
   Distance from primary:	1.062	AU
   Mass:			0.270	Earth masses
   Equatorial radius:		4165.9	km
   Density:			5.324	grams/cc
   Eccentricity of orbit:	0.120
   Surface gravity:		0.63	Earth gees
   Surface pressure:		5.538	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		33.11	degrees Celcius
   Normal daytime temperature:	35.71	degrees Celcius
   Normal night temperature:	30.24	degrees Celcius
   Maximum temperature:   	47.69	degrees Celcius
   Minimum temperature:   	17.71	degrees Celcius
   Escape Velocity:		7.19	km/sec
   Molecular weight retained:	15.37 and above
   Surface acceleration:	619.80	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.582
   Length of year:		380.71	days
   Length of day:		20.81	hours
   Boiling point of water:	154.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.08
   liquids at surface:
				Ethanol      melts at -114  boils at 129
				Mercury      melts at -39   boils at 448
				Bromine      melts at -7    boils at 108
				Water        melts at 0     boils at 154
				Francium     melts at 27    boils at 814
				Cesium       melts at 28    boils at 846
				Gallium      melts at 30    boils at 2790
   gasses in atmosphere:
				Oxygen            6.5%  PP  360.6 mb
				CarbonDioxide    40.6%  PP 2247.6 mb
				Methane           2.0%  PP  112.6 mb
				Ammonia           5.0%  PP  276.1 mb
				Ozone            42.6%  PP 2358.3 mb
				Argon             0.1%  PP    4.4 mb
				Neon              0.4%  PP   24.7 mb
				Krypton           2.5%  PP  137.7 mb
				Xenon             0.3%  PP   16.3 mb


Planet 6	*gas giant*
   Distance from primary:	1.836	AU
   Mass:			22.560	Earth masses
   Equatorial radius:		27119.4	km
   Density:			1.614	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		25.76	km/sec
   Molecular weight retained:	1.20 and above
   Surface acceleration:	1223.28	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.482
   Length of year:		865.55	days
   Length of day:		11.69	hours


Planet 7	
   Distance from primary:	2.858	AU
   Mass:			1/178.7	Earth masses
   Equatorial radius:		1149.9	km
   Density:			5.252	grams/cc
   Eccentricity of orbit:	0.120
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-89.95	degrees Celcius
   Normal daytime temperature:	-61.39	degrees Celcius
   Normal night temperature:	-118.58	degrees Celcius
   Maximum temperature:   	-34.31	degrees Celcius
   Minimum temperature:   	-145.93	degrees Celcius
   Escape Velocity:		1.97	km/sec
   Molecular weight retained:	204.51 and above
   Surface acceleration:	168.78	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.051
   Length of year:		1680.97	days
   Length of day:		37.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at -40


Planet 8	
   Distance from primary:	4.002	AU
   Mass:			1.359	Earth masses
   Equatorial radius:		7074.6	km
   Density:			5.476	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		1.10	Earth gees
   Surface pressure:		1.625	Earth atmospheres
   Surface temperature:		-145.04	degrees Celcius
   Normal daytime temperature:	-143.58	degrees Celcius
   Normal night temperature:	-146.59	degrees Celcius
   Maximum temperature:   	-129.67	degrees Celcius
   Minimum temperature:   	-161.82	degrees Celcius
   Escape Velocity:		12.38	km/sec
   Molecular weight retained:	5.18 and above
   Surface acceleration:	1082.73	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.760
   Length of year:		2786.24	days
   Length of day:		14.57	hours
   Boiling point of water:	113.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -106
   gasses in atmosphere:
				Oxygen            0.5%  PP    8.5 mb
				Nitrogen         99.4%  PP 1616.0 mb


Planet 9	*gas giant*
   Distance from primary:	5.559	AU
   Mass:			892.600	Earth masses
   Equatorial radius:		86947.9	km
   Density:			1.938	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		90.49	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4708.46	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.541
   Length of year:		4555.45	days
   Length of day:		5.96	hours


Planet 10	*gas giant*
   Distance from primary:	14.872	AU
   Mass:			316.073	Earth masses
   Equatorial radius:		69722.0	km
   Density:			1.331	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		60.13	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2592.91	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.518
   Length of year:		19949.30	days
   Length of day:		8.03	hours


Planet 11	*gas giant*
   Distance from primary:	34.627	AU
   Mass:			20.729	Earth masses
   Equatorial radius:		33795.0	km
   Density:			0.766	grams/cc
   Eccentricity of orbit:	0.194
   Escape Velocity:		22.12	km/sec
   Molecular weight retained:	1.62 and above
   Surface acceleration:	723.78	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.523
   Length of year:		70903.93	days
   Length of day:		15.19	hours


Planet 12	
   Distance from primary:	47.699	AU
   Mass:			0.064	Earth masses
   Equatorial radius:		3459.6	km
   Density:			2.204	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.39	degrees Celcius
   Normal daytime temperature:	-223.25	degrees Celcius
   Normal night temperature:	-235.43	degrees Celcius
   Maximum temperature:   	-210.63	degrees Celcius
   Minimum temperature:   	-248.34	degrees Celcius
   Escape Velocity:		3.84	km/sec
   Molecular weight retained:	53.83 and above
   Surface acceleration:	213.12	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.150
   Length of year:		114636.35	days
   Length of day:		32.83	hours
   Boiling point of water:	-72.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


