                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485c3
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6172 K
Stellar class: F8
Age: 1.845 billion years  (5.020 billion left on main sequence)
Habitable ecosphere radius: 1.267 AU

Planets present at:
1	  0.327 AU	no atmosphere
2	  0.411 AU	no atmosphere
3	  0.470 AU	no atmosphere
4	  0.536 AU	no atmosphere
5	  0.872 AU	greenhouse
6	  1.501 AU	high pressure
7	  2.184 AU	gas giant
8	  4.200 AU	gas giant
9	  8.981 AU	no atmosphere
10	 12.194 AU	gas giant
11	 21.196 AU	gas giant
12	 46.761 AU	gas giant



Planet 1	
   Distance from primary:	0.327	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		2298.1	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		264.90	degrees Celcius
   Normal daytime temperature:	484.99	degrees Celcius
   Normal night temperature:	-176.01	degrees Celcius
   Maximum temperature:   	488.04	degrees Celcius
   Minimum temperature:   	-186.78	degrees Celcius
   Escape Velocity:		3.94	km/sec
   Molecular weight retained:	51.03 and above
   Surface acceleration:	338.42	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.077
   Length of year:		65.06	days
   Length of day:		1561.48	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.411	AU
   Mass:			1/475.7	Earth masses
   Equatorial radius:		829.8	km
   Density:			5.249	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.12	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		208.46	degrees Celcius
   Maximum temperature:   	419.81	degrees Celcius
   Minimum temperature:   	-202.88	degrees Celcius
   Escape Velocity:		1.42	km/sec
   Molecular weight retained:	392.91 and above
   Surface acceleration:	121.73	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.067
   Length of year:		91.49	days
   Length of day:		2195.72	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.470	AU
   Mass:			0.068	Earth masses
   Equatorial radius:		2638.6	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		175.60	degrees Celcius
   Maximum temperature:   	379.55	degrees Celcius
   Minimum temperature:   	-208.24	degrees Celcius
   Escape Velocity:		4.53	km/sec
   Molecular weight retained:	38.66 and above
   Surface acceleration:	389.12	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.080
   Length of year:		111.91	days
   Length of day:		2184.45	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.536	AU
   Mass:			0.373	Earth masses
   Equatorial radius:		4634.3	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.21	degrees Celcius
   Maximum temperature:   	347.20	degrees Celcius
   Minimum temperature:   	-216.67	degrees Celcius
   Escape Velocity:		8.01	km/sec
   Molecular weight retained:	12.38 and above
   Surface acceleration:	691.93	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.059
   Length of year:		136.45	days
   Length of day:		3274.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	0.872	AU
   Mass:			0.373	Earth masses
   Equatorial radius:		4636.3	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.71	Earth gees
   Surface pressure:		13.810	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		117.19	degrees Celcius
   Maximum temperature:   	127.05	degrees Celcius
   Minimum temperature:   	106.72	degrees Celcius
   Escape Velocity:		8.01	km/sec
   Molecular weight retained:	12.37 and above
   Surface acceleration:	692.23	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.498
   Length of year:		283.01	days
   Length of day:		20.97	hours
   Boiling point of water:	189.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 508
				Francium     melts at 27    boils at 905
				Cesium       melts at 28    boils at 940
				Gallium      melts at 30    boils at 3047
				Rubidium     melts at 39    boils at 919
				Phosphorus   melts at 44    boils at 414
				Potassium    melts at 63    boils at 1015
				Sodium       melts at 98    boils at 1159
				Sulfur       melts at 113   boils at 617
				Iodine       melts at 114   boils at 296
   gasses in atmosphere:
				Nitrogen         99.1%  PP 13680.1 mb
				Water             0.1%  PP   12.2 mb
				CarbonDioxide     0.2%  PP   31.6 mb
				Methane           0.1%  PP    8.7 mb
				Ammonia           0.1%  PP   10.4 mb
				Ozone             0.2%  PP   32.5 mb
				Ethanol           0.2%  PP   32.3 mb


Planet 6	
   Distance from primary:	1.501	AU
   Mass:			1.829	Earth masses
   Equatorial radius:		7786.3	km
   Density:			5.527	grams/cc
   Eccentricity of orbit:	0.244
   Surface gravity:		1.23	Earth gees
   Surface pressure:		2.705	Earth atmospheres
   Surface temperature:		12.05	degrees Celcius
   Normal daytime temperature:	14.46	degrees Celcius
   Normal night temperature:	9.49	degrees Celcius
   Maximum temperature:   	31.80	degrees Celcius
   Minimum temperature:   	-8.79	degrees Celcius
   Escape Velocity:		13.69	km/sec
   Molecular weight retained:	4.24 and above
   Surface acceleration:	1202.81	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.232
   Length of year:		639.96	days
   Length of day:		13.84	hours
   Boiling point of water:	129.6	degrees Celcius
   Hydrosphere percentage:	70.51
   Cloud cover percentage:	38.99
   Ice cover percentage:	2.63
   liquids at surface:
				Ethanol      melts at -114  boils at 106
				Mercury      melts at -39   boils at 407
				Bromine      melts at -7    boils at 86
				Water        melts at 0     boils at 130
   gasses in atmosphere:
				Oxygen            0.4%  PP   11.6 mb
				Nitrogen         99.4%  PP 2688.8 mb


Planet 7	*gas giant*
   Distance from primary:	2.184	AU
   Mass:			8.183	Earth masses
   Equatorial radius:		20466.0	km
   Density:			1.362	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		17.86	km/sec
   Molecular weight retained:	2.49 and above
   Surface acceleration:	779.09	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.500
   Length of year:		1122.58	days
   Length of day:		14.64	hours


Planet 8	*gas giant*
   Distance from primary:	4.200	AU
   Mass:			832.435	Earth masses
   Equatorial radius:		83215.4	km
   Density:			2.061	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		89.32	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4793.82	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.505
   Length of year:		2990.68	days
   Length of day:		5.90	hours


Planet 9	
   Distance from primary:	8.981	AU
   Mass:			0.163	Earth masses
   Equatorial radius:		4710.3	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.018	Earth atmospheres
   Surface temperature:		-174.66	degrees Celcius
   Normal daytime temperature:	-164.37	degrees Celcius
   Normal night temperature:	-185.12	degrees Celcius
   Maximum temperature:   	-146.79	degrees Celcius
   Minimum temperature:   	-203.83	degrees Celcius
   Escape Velocity:		5.25	km/sec
   Molecular weight retained:	28.83 and above
   Surface acceleration:	292.27	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.292
   Length of year:		9362.06	days
   Length of day:		28.03	hours
   Boiling point of water:	14.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	21.56
   liquids at surface:
				Ozone        melts at -193  boils at -149
   gasses in atmosphere:
				Argon            100.0%  PP   17.9 mb


Planet 10	*gas giant*
   Distance from primary:	12.194	AU
   Mass:			617.075	Earth masses
   Equatorial radius:		83341.0	km
   Density:			1.521	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		76.85	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3542.91	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.472
   Length of year:		14799.55	days
   Length of day:		6.87	hours


Planet 11	*gas giant*
   Distance from primary:	21.196	AU
   Mass:			51.625	Earth masses
   Equatorial radius:		42325.5	km
   Density:			0.972	grams/cc
   Eccentricity of orbit:	0.046
   Escape Velocity:		31.19	km/sec
   Molecular weight retained:	0.82 and above
   Surface acceleration:	1149.20	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.467
   Length of year:		33940.68	days
   Length of day:		12.06	hours


Planet 12	*gas giant*
   Distance from primary:	46.761	AU
   Mass:			0.880	Earth masses
   Equatorial radius:		13787.5	km
   Density:			0.479	grams/cc
   Eccentricity of orbit:	0.141
   Escape Velocity:		7.14	km/sec
   Molecular weight retained:	15.59 and above
   Surface acceleration:	184.64	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.546
   Length of year:		111224.02	days
   Length of day:		30.08	hours


