                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048062
Stellar mass: 1.10 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6168 K
Stellar class: F8
Age: 3.676 billion years  (3.371 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.379 AU	no atmosphere
2	  0.642 AU	no atmosphere
3	  1.109 AU	greenhouse
4	  1.477 AU	high pressure
5	  1.940 AU	gas giant
6	  3.784 AU	gas giant
7	  6.687 AU	gas giant
8	 11.793 AU	no atmosphere
9	 17.307 AU	gas giant
10	 31.422 AU	gas giant
11	 46.347 AU	no atmosphere
12	 46.898 AU	no atmosphere
13	 49.620 AU	no atmosphere



Planet 1	
   Distance from primary:	0.379	AU
   Mass:			0.167	Earth masses
   Equatorial radius:		3555.9	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		220.97	degrees Celcius
   Maximum temperature:   	434.90	degrees Celcius
   Minimum temperature:   	-198.68	degrees Celcius
   Escape Velocity:		6.12	km/sec
   Molecular weight retained:	21.18 and above
   Surface acceleration:	526.94	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.089
   Length of year:		81.43	days
   Length of day:		1954.43	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.642	AU
   Mass:			0.556	Earth masses
   Equatorial radius:		5286.1	km
   Density:			5.372	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		106.65	degrees Celcius
   Maximum temperature:   	294.50	degrees Celcius
   Minimum temperature:   	-224.35	degrees Celcius
   Escape Velocity:		9.16	km/sec
   Molecular weight retained:	9.46 and above
   Surface acceleration:	793.62	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.087
   Length of year:		179.73	days
   Length of day:		4313.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	1.109	AU
   Mass:			2.199	Earth masses
   Equatorial radius:		8261.1	km
   Density:			5.565	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		1.31	Earth gees
   Surface pressure:		493.426	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		539.66	degrees Celcius
   Maximum temperature:   	541.30	degrees Celcius
   Minimum temperature:   	535.24	degrees Celcius
   Escape Velocity:		14.57	km/sec
   Molecular weight retained:	3.74 and above
   Surface acceleration:	1284.82	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.485
   Length of year:		407.73	days
   Length of day:		13.56	hours
   Boiling point of water:	415.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1480
				Cesium       melts at 28    boils at 1531
				Gallium      melts at 30    boils at 4664
				Rubidium     melts at 39    boils at 1500
				Potassium    melts at 63    boils at 1643
				Sodium       melts at 98    boils at 1857
				Indium       melts at 157   boils at 4068
				Lithium      melts at 181   boils at 2716
				Selenium     melts at 217   boils at 1494
				Tin          melts at 232   boils at 5070
				Polonium     melts at 254   boils at 2005
				Bismuth      melts at 271   boils at 3116
				Thallium     melts at 304   boils at 2919
				Cadmium      melts at 321   boils at 1642
				Lead         melts at 328   boils at 3461
				Zinc         melts at 420   boils at 1904
				Tellurium    melts at 450   boils at 2057
   gasses in atmosphere:
				Sulfur            0.4%  PP 1849.9 mb
				Nitrogen          1.7%  PP 8285.0 mb
				Helium           97.9%  PP 483237.9 mb


Planet 4	
   Distance from primary:	1.477	AU
   Mass:			2.013	Earth masses
   Equatorial radius:		8030.6	km
   Density:			5.546	grams/cc
   Eccentricity of orbit:	0.105
   Surface gravity:		1.27	Earth gees
   Surface pressure:		3.466	Earth atmospheres
   Surface temperature:		13.98	degrees Celcius
   Normal daytime temperature:	16.09	degrees Celcius
   Normal night temperature:	11.73	degrees Celcius
   Maximum temperature:   	30.54	degrees Celcius
   Minimum temperature:   	-3.48	degrees Celcius
   Escape Velocity:		14.14	km/sec
   Molecular weight retained:	3.97 and above
   Surface acceleration:	1244.80	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.242
   Length of year:		626.74	days
   Length of day:		13.62	hours
   Boiling point of water:	137.7	degrees Celcius
   Hydrosphere percentage:	77.17
   Cloud cover percentage:	51.11
   Ice cover percentage:	1.93
   liquids at surface:
				Ethanol      melts at -114  boils at 114
				Mercury      melts at -39   boils at 421
				Bromine      melts at -7    boils at 93
				Water        melts at 0     boils at 138
   gasses in atmosphere:
				Oxygen            0.1%  PP    3.6 mb
				Nitrogen         11.5%  PP  397.1 mb
				Helium           88.4%  PP 3065.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.940	AU
   Mass:			4.359	Earth masses
   Equatorial radius:		16888.0	km
   Density:			1.291	grams/cc
   Eccentricity of orbit:	0.185
   Escape Velocity:		14.35	km/sec
   Molecular weight retained:	3.86 and above
   Surface acceleration:	609.55	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.467
   Length of year:		943.22	days
   Length of day:		16.56	hours


Planet 6	*gas giant*
   Distance from primary:	3.784	AU
   Mass:			9.025	Earth masses
   Equatorial radius:		22076.6	km
   Density:			1.197	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		18.06	km/sec
   Molecular weight retained:	2.43 and above
   Surface acceleration:	738.48	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.466
   Length of year:		2569.04	days
   Length of day:		15.04	hours


Planet 7	*gas giant*
   Distance from primary:	6.687	AU
   Mass:			1298.135	Earth masses
   Equatorial radius:		98608.1	km
   Density:			1.932	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		102.47	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5323.95	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.453
   Length of year:		6024.46	days
   Length of day:		5.60	hours


Planet 8	
   Distance from primary:	11.793	AU
   Mass:			0.245	Earth masses
   Equatorial radius:		5389.7	km
   Density:			2.231	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.039	Earth atmospheres
   Surface temperature:		-187.47	degrees Celcius
   Normal daytime temperature:	-180.18	degrees Celcius
   Normal night temperature:	-194.97	degrees Celcius
   Maximum temperature:   	-162.87	degrees Celcius
   Minimum temperature:   	-213.68	degrees Celcius
   Escape Velocity:		6.02	km/sec
   Molecular weight retained:	21.91 and above
   Surface acceleration:	336.07	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.292
   Length of year:		14134.71	days
   Length of day:		26.14	hours
   Boiling point of water:	28.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.01
   liquids at surface:
				Ozone        melts at -193  boils at -143


Planet 9	*gas giant*
   Distance from primary:	17.307	AU
   Mass:			128.111	Earth masses
   Equatorial radius:		54323.9	km
   Density:			1.140	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		43.37	km/sec
   Molecular weight retained:	0.42 and above
   Surface acceleration:	1731.19	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.485
   Length of year:		25125.59	days
   Length of day:		9.82	hours


Planet 10	*gas giant*
   Distance from primary:	31.422	AU
   Mass:			8.764	Earth masses
   Equatorial radius:		26110.8	km
   Density:			0.702	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		16.36	km/sec
   Molecular weight retained:	2.97 and above
   Surface acceleration:	512.64	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.469
   Length of year:		61477.19	days
   Length of day:		18.05	hours


Planet 11	
   Distance from primary:	46.347	AU
   Mass:			0.181	Earth masses
   Equatorial radius:		4880.3	km
   Density:			2.223	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.79	degrees Celcius
   Normal daytime temperature:	-223.44	degrees Celcius
   Normal night temperature:	-234.04	degrees Celcius
   Maximum temperature:   	-209.77	degrees Celcius
   Minimum temperature:   	-248.12	degrees Celcius
   Escape Velocity:		5.44	km/sec
   Molecular weight retained:	26.83 and above
   Surface acceleration:	303.17	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.145
   Length of year:		110127.19	days
   Length of day:		27.52	hours
   Boiling point of water:	-55.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 12	
   Distance from primary:	46.898	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		2302.4	km
   Density:			2.194	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.14	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.48	degrees Celcius
   Normal daytime temperature:	-222.18	degrees Celcius
   Normal night temperature:	-236.64	degrees Celcius
   Maximum temperature:   	-207.23	degrees Celcius
   Minimum temperature:   	-251.29	degrees Celcius
   Escape Velocity:		2.55	km/sec
   Molecular weight retained:	122.11 and above
   Surface acceleration:	141.17	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.160
   Length of year:		112098.40	days
   Length of day:		40.34	hours
   Boiling point of water:	-89.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


Planet 13	
   Distance from primary:	49.620	AU
   Mass:			1/119.7	Earth masses
   Equatorial radius:		1758.9	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.54	degrees Celcius
   Normal daytime temperature:	-222.58	degrees Celcius
   Normal night temperature:	-238.33	degrees Celcius
   Maximum temperature:   	-209.98	degrees Celcius
   Minimum temperature:   	-250.74	degrees Celcius
   Escape Velocity:		1.95	km/sec
   Molecular weight retained:	209.57 and above
   Surface acceleration:	107.68	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.148
   Length of year:		121997.39	days
   Length of day:		46.19	hours
   Boiling point of water:	-99.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


