                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048b45
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6385 K
Stellar class: F7
Age: 2.271 billion years  (4.415 billion left on main sequence)
Habitable ecosphere radius: 1.289 AU

Planets present at:
1	  0.421 AU	no atmosphere
2	  0.580 AU	no atmosphere
3	  0.935 AU	no atmosphere
4	  1.192 AU	greenhouse
5	  1.354 AU	high pressure
6	  2.402 AU	cold
7	  3.085 AU	gas giant
8	  4.900 AU	gas giant
9	  8.138 AU	gas giant
10	 12.551 AU	gas giant
11	 24.976 AU	gas giant
12	 48.672 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.421	AU
   Mass:			0.379	Earth masses
   Equatorial radius:		4658.5	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.125
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		207.34	degrees Celcius
   Normal daytime temperature:	414.97	degrees Celcius
   Normal night temperature:	-188.96	degrees Celcius
   Maximum temperature:   	418.30	degrees Celcius
   Minimum temperature:   	-199.77	degrees Celcius
   Escape Velocity:		8.05	km/sec
   Molecular weight retained:	12.25 and above
   Surface acceleration:	695.67	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.058
   Length of year:		94.83	days
   Length of day:		1771.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.580	AU
   Mass:			0.505	Earth masses
   Equatorial radius:		5121.9	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.137
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		137.00	degrees Celcius
   Maximum temperature:   	332.06	degrees Celcius
   Minimum temperature:   	-217.22	degrees Celcius
   Escape Velocity:		8.87	km/sec
   Molecular weight retained:	10.09 and above
   Surface acceleration:	767.84	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.051
   Length of year:		153.25	days
   Length of day:		2790.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.935	AU
   Mass:			1/176.6	Earth masses
   Equatorial radius:		1154.5	km
   Density:			5.252	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		47.41	degrees Celcius
   Maximum temperature:   	219.48	degrees Celcius
   Minimum temperature:   	-231.40	degrees Celcius
   Escape Velocity:		1.98	km/sec
   Molecular weight retained:	202.87 and above
   Surface acceleration:	169.46	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.081
   Length of year:		313.50	days
   Length of day:		7523.97	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	1.192	AU
   Mass:			0.160	Earth masses
   Equatorial radius:		3505.8	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.53	Earth gees
   Surface pressure:		1.988	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		35.56	degrees Celcius
   Normal daytime temperature:	40.15	degrees Celcius
   Normal night temperature:	30.51	degrees Celcius
   Maximum temperature:   	57.19	degrees Celcius
   Minimum temperature:   	12.61	degrees Celcius
   Escape Velocity:		6.03	km/sec
   Molecular weight retained:	21.80 and above
   Surface acceleration:	519.35	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.044
   Length of year:		451.20	days
   Length of day:		22.15	hours
   Boiling point of water:	119.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04
   liquids at surface:
				Ethanol      melts at -114  boils at 97
				Mercury      melts at -39   boils at 391
				Bromine      melts at -7    boils at 77
				Water        melts at 0     boils at 120
				Francium     melts at 27    boils at 728
				Cesium       melts at 28    boils at 757
				Gallium      melts at 30    boils at 2546
   gasses in atmosphere:
				CarbonDioxide    46.0%  PP  915.1 mb
				Ozone            50.2%  PP  998.3 mb
				Argon             0.1%  PP    1.5 mb
				Krypton           3.3%  PP   65.1 mb
				Xenon             0.4%  PP    8.0 mb


Planet 5	
   Distance from primary:	1.354	AU
   Mass:			2.509	Earth masses
   Equatorial radius:		8617.2	km
   Density:			5.595	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		1.37	Earth gees
   Surface pressure:		6.103	Earth atmospheres
   Surface temperature:		25.48	degrees Celcius
   Normal daytime temperature:	27.08	degrees Celcius
   Normal night temperature:	23.77	degrees Celcius
   Maximum temperature:   	37.18	degrees Celcius
   Minimum temperature:   	13.20	degrees Celcius
   Escape Velocity:		15.24	km/sec
   Molecular weight retained:	3.42 and above
   Surface acceleration:	1347.42	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.494
   Length of year:		546.35	days
   Length of day:		13.09	hours
   Boiling point of water:	157.5	degrees Celcius
   Hydrosphere percentage:	94.67
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.42
   liquids at surface:
				Ethanol      melts at -114  boils at 133
				Mercury      melts at -39   boils at 454
				Bromine      melts at -7    boils at 111
				Water        melts at 0     boils at 158
   gasses in atmosphere:
				Nitrogen          0.7%  PP   41.8 mb
				Helium           99.3%  PP 6060.7 mb


Planet 6	
   Distance from primary:	2.402	AU
   Mass:			1.205	Earth masses
   Equatorial radius:		6804.6	km
   Density:			5.458	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		1.06	Earth gees
   Surface pressure:		1.082	Earth atmospheres
   Surface temperature:		-83.15	degrees Celcius
   Normal daytime temperature:	-80.46	degrees Celcius
   Normal night temperature:	-85.99	degrees Celcius
   Maximum temperature:   	-62.99	degrees Celcius
   Minimum temperature:   	-104.76	degrees Celcius
   Escape Velocity:		11.89	km/sec
   Molecular weight retained:	5.62 and above
   Surface acceleration:	1038.00	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.573
   Length of year:		1290.49	days
   Length of day:		14.88	hours
   Boiling point of water:	102.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	84.04
   liquids at surface:
				Ethanol      melts at -114  boils at 81
				Chlorine     melts at -101  boils at -33
   gasses in atmosphere:
				Oxygen            6.1%  PP   65.9 mb
				Nitrogen         93.8%  PP 1015.0 mb


Planet 7	*gas giant*
   Distance from primary:	3.085	AU
   Mass:			33.355	Earth masses
   Equatorial radius:		31689.2	km
   Density:			1.496	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		28.97	km/sec
   Molecular weight retained:	0.95 and above
   Surface acceleration:	1324.57	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.454
   Length of year:		1877.67	days
   Length of day:		11.23	hours


Planet 8	*gas giant*
   Distance from primary:	4.900	AU
   Mass:			48.366	Earth masses
   Equatorial radius:		36705.7	km
   Density:			1.396	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		32.42	km/sec
   Molecular weight retained:	0.76 and above
   Surface acceleration:	1431.57	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.468
   Length of year:		3759.70	days
   Length of day:		10.80	hours


Planet 9	*gas giant*
   Distance from primary:	8.138	AU
   Mass:			73.635	Earth masses
   Equatorial radius:		43284.7	km
   Density:			1.296	grams/cc
   Eccentricity of orbit:	0.121
   Escape Velocity:		36.83	km/sec
   Molecular weight retained:	0.59 and above
   Surface acceleration:	1567.31	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.543
   Length of year:		8046.32	days
   Length of day:		10.32	hours


Planet 10	*gas giant*
   Distance from primary:	12.551	AU
   Mass:			107.465	Earth masses
   Equatorial radius:		50107.3	km
   Density:			1.219	grams/cc
   Eccentricity of orbit:	0.080
   Escape Velocity:		41.36	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1706.88	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.530
   Length of year:		15410.50	days
   Length of day:		9.89	hours


Planet 11	*gas giant*
   Distance from primary:	24.976	AU
   Mass:			158.548	Earth masses
   Equatorial radius:		59438.2	km
   Density:			1.077	grams/cc
   Eccentricity of orbit:	0.197
   Escape Velocity:		46.12	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	1789.65	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.463
   Length of year:		43257.35	days
   Length of day:		9.66	hours


Planet 12	
   Distance from primary:	48.672	AU
   Mass:			0.208	Earth masses
   Equatorial radius:		5104.7	km
   Density:			2.226	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.15	degrees Celcius
   Normal daytime temperature:	-223.95	degrees Celcius
   Normal night temperature:	-234.25	degrees Celcius
   Maximum temperature:   	-210.04	degrees Celcius
   Minimum temperature:   	-248.55	degrees Celcius
   Escape Velocity:		5.69	km/sec
   Molecular weight retained:	24.48 and above
   Surface acceleration:	317.61	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.148
   Length of year:		117699.96	days
   Length of day:		26.89	hours
   Boiling point of water:	-53.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


