                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048748
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6134 K
Stellar class: F9
Age: 5.309 billion years  (1.506 billion left on main sequence)
Habitable ecosphere radius: 1.273 AU

Planets present at:
1	  0.360 AU	no atmosphere
2	  0.547 AU	no atmosphere
3	  0.630 AU	no atmosphere
4	  1.054 AU	greenhouse
5	  1.616 AU	gas giant
6	  3.095 AU	cold
7	  4.719 AU	gas giant
8	 10.857 AU	gas giant
9	 25.255 AU	gas giant
10	 49.177 AU	no atmosphere



Planet 1	
   Distance from primary:	0.360	AU
   Mass:			0.123	Earth masses
   Equatorial radius:		3208.7	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.080
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		241.71	degrees Celcius
   Normal daytime temperature:	457.17	degrees Celcius
   Normal night temperature:	-184.02	degrees Celcius
   Maximum temperature:   	460.33	degrees Celcius
   Minimum temperature:   	-194.80	degrees Celcius
   Escape Velocity:		5.52	km/sec
   Molecular weight retained:	26.07 and above
   Surface acceleration:	474.53	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.071
   Length of year:		75.09	days
   Length of day:		1802.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.547	AU
   Mass:			0.062	Earth masses
   Equatorial radius:		2560.2	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		146.50	degrees Celcius
   Maximum temperature:   	343.92	degrees Celcius
   Minimum temperature:   	-217.50	degrees Celcius
   Escape Velocity:		4.40	km/sec
   Molecular weight retained:	41.08 and above
   Surface acceleration:	377.43	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.053
   Length of year:		140.66	days
   Length of day:		3375.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.630	AU
   Mass:			0.589	Earth masses
   Equatorial radius:		5385.4	km
   Density:			5.377	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		117.28	degrees Celcius
   Maximum temperature:   	307.52	degrees Celcius
   Minimum temperature:   	-222.82	degrees Celcius
   Escape Velocity:		9.34	km/sec
   Molecular weight retained:	9.11 and above
   Surface acceleration:	809.28	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.058
   Length of year:		173.95	days
   Length of day:		4174.70	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.054	AU
   Mass:			2.116	Earth masses
   Equatorial radius:		8159.8	km
   Density:			5.557	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		1.29	Earth gees
   Surface pressure:		477.744	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		566.83	degrees Celcius
   Maximum temperature:   	568.40	degrees Celcius
   Minimum temperature:   	562.14	degrees Celcius
   Escape Velocity:		14.38	km/sec
   Molecular weight retained:	3.84 and above
   Surface acceleration:	1267.18	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.480
   Length of year:		375.88	days
   Length of day:		13.86	hours
   Boiling point of water:	412.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1472
				Cesium       melts at 28    boils at 1523
				Gallium      melts at 30    boils at 4642
				Rubidium     melts at 39    boils at 1492
				Potassium    melts at 63    boils at 1635
				Sodium       melts at 98    boils at 1848
				Indium       melts at 157   boils at 4049
				Lithium      melts at 181   boils at 2703
				Selenium     melts at 217   boils at 1487
				Tin          melts at 232   boils at 5047
				Polonium     melts at 254   boils at 1995
				Bismuth      melts at 271   boils at 3101
				Thallium     melts at 304   boils at 2905
				Cadmium      melts at 321   boils at 1634
				Lead         melts at 328   boils at 3445
				Zinc         melts at 420   boils at 1894
				Tellurium    melts at 450   boils at 2047
   gasses in atmosphere:
				Sulfur            0.7%  PP 3512.1 mb
				Nitrogen          3.1%  PP 14644.4 mb
				Helium           96.2%  PP 459487.9 mb


Planet 5	*gas giant*
   Distance from primary:	1.616	AU
   Mass:			6.154	Earth masses
   Equatorial radius:		18359.4	km
   Density:			1.419	grams/cc
   Eccentricity of orbit:	0.183
   Escape Velocity:		16.35	km/sec
   Molecular weight retained:	2.97 and above
   Surface acceleration:	728.05	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.515
   Length of year:		713.66	days
   Length of day:		15.15	hours


Planet 6	
   Distance from primary:	3.095	AU
   Mass:			0.999	Earth masses
   Equatorial radius:		6402.0	km
   Density:			5.433	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.929	Earth atmospheres
   Surface temperature:		-117.27	degrees Celcius
   Normal daytime temperature:	-114.82	degrees Celcius
   Normal night temperature:	-119.85	degrees Celcius
   Maximum temperature:   	-99.54	degrees Celcius
   Minimum temperature:   	-136.45	degrees Celcius
   Escape Velocity:		11.16	km/sec
   Molecular weight retained:	6.38 and above
   Surface acceleration:	972.07	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.665
   Length of year:		1891.83	days
   Length of day:		15.37	hours
   Boiling point of water:	98.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	98.37
   liquids at surface:
				Ozone        melts at -193  boils at -113
   gasses in atmosphere:
				Nitrogen         99.9%  PP  928.5 mb


Planet 7	*gas giant*
   Distance from primary:	4.719	AU
   Mass:			288.422	Earth masses
   Equatorial radius:		61658.3	km
   Density:			1.756	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		61.08	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	3025.42	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.486
   Length of year:		3560.82	days
   Length of day:		7.43	hours


Planet 8	*gas giant*
   Distance from primary:	10.857	AU
   Mass:			1093.055	Earth masses
   Equatorial radius:		97478.9	km
   Density:			1.684	grams/cc
   Eccentricity of orbit:	0.111
   Escape Velocity:		94.57	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4587.33	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.452
   Length of year:		12413.68	days
   Length of day:		6.03	hours


Planet 9	*gas giant*
   Distance from primary:	25.255	AU
   Mass:			43.883	Earth masses
   Equatorial radius:		40944.4	km
   Density:			0.912	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		29.24	km/sec
   Molecular weight retained:	0.93 and above
   Surface acceleration:	1043.87	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.515
   Length of year:		44100.66	days
   Length of day:		12.65	hours


Planet 10	
   Distance from primary:	49.177	AU
   Mass:			0.235	Earth masses
   Equatorial radius:		5317.0	km
   Density:			2.230	grams/cc
   Eccentricity of orbit:	0.234
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.54	degrees Celcius
   Normal daytime temperature:	-224.49	degrees Celcius
   Normal night temperature:	-234.50	degrees Celcius
   Maximum temperature:   	-207.86	degrees Celcius
   Minimum temperature:   	-251.14	degrees Celcius
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.53 and above
   Surface acceleration:	331.35	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.142
   Length of year:		119839.15	days
   Length of day:		26.33	hours
   Boiling point of water:	-50.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


