                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504861a
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6351 K
Stellar class: F7
Age: 2.669 billion years  (4.186 billion left on main sequence)
Habitable ecosphere radius: 1.269 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.434 AU	no atmosphere
3	  0.725 AU	no atmosphere
4	  1.497 AU	high pressure
5	  3.405 AU	cold
6	  4.193 AU	gas giant
7	  8.293 AU	gas giant
8	 18.720 AU	gas giant
9	 26.272 AU	no atmosphere
10	 30.210 AU	no atmosphere
11	 42.140 AU	gas giant
12	 51.551 AU	no atmosphere



Planet 1	
   Distance from primary:	0.358	AU
   Mass:			0.025	Earth masses
   Equatorial radius:		1903.6	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.67	degrees Celcius
   Normal daytime temperature:	455.88	degrees Celcius
   Normal night temperature:	-183.95	degrees Celcius
   Maximum temperature:   	458.87	degrees Celcius
   Minimum temperature:   	-194.08	degrees Celcius
   Escape Velocity:		3.26	km/sec
   Molecular weight retained:	74.48 and above
   Surface acceleration:	279.94	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.083
   Length of year:		74.45	days
   Length of day:		1786.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.434	AU
   Mass:			0.300	Earth masses
   Equatorial radius:		4315.5	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		194.10	degrees Celcius
   Maximum temperature:   	402.33	degrees Celcius
   Minimum temperature:   	-206.47	degrees Celcius
   Escape Velocity:		7.45	km/sec
   Molecular weight retained:	14.31 and above
   Surface acceleration:	642.75	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.078
   Length of year:		99.43	days
   Length of day:		2386.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.725	AU
   Mass:			0.141	Earth masses
   Equatorial radius:		3360.8	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		87.25	degrees Celcius
   Maximum temperature:   	269.94	degrees Celcius
   Minimum temperature:   	-226.69	degrees Celcius
   Escape Velocity:		5.78	km/sec
   Molecular weight retained:	23.74 and above
   Surface acceleration:	497.45	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.090
   Length of year:		214.53	days
   Length of day:		5148.67	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.497	AU
   Mass:			16.470	Earth masses
   Equatorial radius:		15319.4	km
   Density:			6.537	grams/cc
   Eccentricity of orbit:	0.264
   Surface gravity:		2.85	Earth gees
   Surface pressure:		255.437	Earth atmospheres
   Surface temperature:		345.65	degrees Celcius
   Maximum temperature:   	348.72	degrees Celcius
   Minimum temperature:   	341.61	degrees Celcius
   Escape Velocity:		29.28	km/sec
   Molecular weight retained:	0.93 and above
   Surface acceleration:	2798.56	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.526
   Length of year:		637.20	days
   Length of day:		9.06	hours
   Boiling point of water:	358.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 794
				Francium     melts at 27    boils at 1335
				Cesium       melts at 28    boils at 1383
				Gallium      melts at 30    boils at 4258
				Rubidium     melts at 39    boils at 1354
				Potassium    melts at 63    boils at 1485
				Sodium       melts at 98    boils at 1682
				Sulfur       melts at 113   boils at 942
				Indium       melts at 157   boils at 3711
				Lithium      melts at 181   boils at 2470
				Selenium     melts at 217   boils at 1349
				Tin          melts at 232   boils at 4630
				Polonium     melts at 254   boils at 1818
				Bismuth      melts at 271   boils at 2837
				Thallium     melts at 304   boils at 2656
				Cadmium      melts at 321   boils at 1484
				Lead         melts at 328   boils at 3154
   gasses in atmosphere:
				Nitrogen          0.2%  PP  388.3 mb
				Helium           99.8%  PP 255047.0 mb


Planet 5	
   Distance from primary:	3.405	AU
   Mass:			0.503	Earth masses
   Equatorial radius:		5113.4	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.254	Earth atmospheres
   Surface temperature:		-129.53	degrees Celcius
   Normal daytime temperature:	-125.01	degrees Celcius
   Normal night temperature:	-134.28	degrees Celcius
   Maximum temperature:   	-105.21	degrees Celcius
   Minimum temperature:   	-155.79	degrees Celcius
   Escape Velocity:		8.85	km/sec
   Molecular weight retained:	10.13 and above
   Surface acceleration:	766.52	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.640
   Length of year:		2184.71	days
   Length of day:		17.31	hours
   Boiling point of water:	65.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	83.85
   liquids at surface:
				Ozone        melts at -193  boils at -127
   gasses in atmosphere:
				Oxygen           32.4%  PP   82.4 mb
				Nitrogen         67.5%  PP  171.7 mb


Planet 6	*gas giant*
   Distance from primary:	4.193	AU
   Mass:			164.608	Earth masses
   Equatorial radius:		51856.6	km
   Density:			1.684	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		50.32	km/sec
   Molecular weight retained:	0.31 and above
   Surface acceleration:	2441.08	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.501
   Length of year:		2985.56	days
   Length of day:		8.27	hours


Planet 7	*gas giant*
   Distance from primary:	8.293	AU
   Mass:			888.712	Earth masses
   Equatorial radius:		89758.6	km
   Density:			1.754	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		88.86	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4398.95	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.451
   Length of year:		8295.78	days
   Length of day:		6.16	hours


Planet 8	*gas giant*
   Distance from primary:	18.720	AU
   Mass:			4.408	Earth masses
   Equatorial radius:		20435.9	km
   Density:			0.737	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		13.12	km/sec
   Molecular weight retained:	4.61 and above
   Surface acceleration:	420.93	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.483
   Length of year:		28166.35	days
   Length of day:		19.92	hours


Planet 9	
   Distance from primary:	26.272	AU
   Mass:			0.160	Earth masses
   Equatorial radius:		4681.6	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-213.96	degrees Celcius
   Normal daytime temperature:	-206.68	degrees Celcius
   Normal night temperature:	-221.18	degrees Celcius
   Maximum temperature:   	-194.11	degrees Celcius
   Minimum temperature:   	-234.57	degrees Celcius
   Escape Velocity:		5.21	km/sec
   Molecular weight retained:	29.19 and above
   Surface acceleration:	290.44	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.156
   Length of year:		46829.17	days
   Length of day:		28.12	hours
   Boiling point of water:	-57.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 10	
   Distance from primary:	30.210	AU
   Mass:			0.249	Earth masses
   Equatorial radius:		5421.4	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.93	degrees Celcius
   Normal daytime temperature:	-211.59	degrees Celcius
   Normal night temperature:	-224.21	degrees Celcius
   Maximum temperature:   	-196.92	degrees Celcius
   Minimum temperature:   	-239.69	degrees Celcius
   Escape Velocity:		6.05	km/sec
   Molecular weight retained:	21.65 and above
   Surface acceleration:	338.12	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.161
   Length of year:		57744.16	days
   Length of day:		26.06	hours
   Boiling point of water:	-46.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   liquids at surface:
				Fluorine     melts at -220  boils at -216
				Oxygen       melts at -218  boils at -213


Planet 11	*gas giant*
   Distance from primary:	42.140	AU
   Mass:			1.677	Earth masses
   Equatorial radius:		16495.7	km
   Density:			0.533	grams/cc
   Eccentricity of orbit:	0.097
   Escape Velocity:		9.01	km/sec
   Molecular weight retained:	9.79 and above
   Surface acceleration:	245.83	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.524
   Length of year:		95132.71	days
   Length of day:		26.07	hours


Planet 12	
   Distance from primary:	51.551	AU
   Mass:			0.054	Earth masses
   Equatorial radius:		3269.0	km
   Density:			2.202	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.06	degrees Celcius
   Normal daytime temperature:	-224.99	degrees Celcius
   Normal night temperature:	-236.99	degrees Celcius
   Maximum temperature:   	-215.28	degrees Celcius
   Minimum temperature:   	-247.11	degrees Celcius
   Escape Velocity:		3.63	km/sec
   Molecular weight retained:	60.34 and above
   Surface acceleration:	201.20	cm/sec2
   Axial tilt:			72	degrees
   Planetary albedo:		0.155
   Length of year:		128716.13	days
   Length of day:		33.79	hours
   Boiling point of water:	-73.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


