                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c1f
Stellar mass: 1.09 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6292 K
Stellar class: F8
Age: 5.973 billion years  (1.222 billion left on main sequence)
Habitable ecosphere radius: 1.230 AU

Planets present at:
1	  0.324 AU	no atmosphere
2	  0.362 AU	no atmosphere
3	  0.616 AU	no atmosphere
4	  0.787 AU	no atmosphere
5	  1.043 AU	no atmosphere
6	  1.218 AU	high pressure
7	  2.326 AU	gas giant
8	  5.960 AU	gas giant
9	 12.675 AU	gas giant
10	 18.855 AU	gas giant
11	 41.902 AU	gas giant



Planet 1	
   Distance from primary:	0.324	AU
   Mass:			0.110	Earth masses
   Equatorial radius:		3100.1	km
   Density:			5.289	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		262.33	degrees Celcius
   Normal daytime temperature:	481.83	degrees Celcius
   Normal night temperature:	-176.11	degrees Celcius
   Maximum temperature:   	484.86	degrees Celcius
   Minimum temperature:   	-186.77	degrees Celcius
   Escape Velocity:		5.33	km/sec
   Molecular weight retained:	27.94 and above
   Surface acceleration:	458.22	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.059
   Length of year:		64.43	days
   Length of day:		1546.27	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.362	AU
   Mass:			0.045	Earth masses
   Equatorial radius:		2304.9	km
   Density:			5.269	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.69	degrees Celcius
   Normal daytime temperature:	444.96	degrees Celcius
   Normal night temperature:	-185.97	degrees Celcius
   Maximum temperature:   	448.04	degrees Celcius
   Minimum temperature:   	-196.24	degrees Celcius
   Escape Velocity:		3.96	km/sec
   Molecular weight retained:	50.73 and above
   Surface acceleration:	339.43	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.071
   Length of year:		76.17	days
   Length of day:		1828.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.616	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		2693.2	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.247
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		112.14	degrees Celcius
   Normal daytime temperature:	297.34	degrees Celcius
   Normal night temperature:	-209.80	degrees Celcius
   Maximum temperature:   	301.13	degrees Celcius
   Minimum temperature:   	-220.13	degrees Celcius
   Escape Velocity:		4.63	km/sec
   Molecular weight retained:	37.10 and above
   Surface acceleration:	397.27	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.087
   Length of year:		169.22	days
   Length of day:		2450.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.787	AU
   Mass:			0.279	Earth masses
   Equatorial radius:		4213.4	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		68.05	degrees Celcius
   Normal daytime temperature:	234.49	degrees Celcius
   Normal night temperature:	-182.68	degrees Celcius
   Maximum temperature:   	240.73	degrees Celcius
   Minimum temperature:   	-197.81	degrees Celcius
   Escape Velocity:		7.27	km/sec
   Molecular weight retained:	15.02 and above
   Surface acceleration:	627.09	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.083
   Length of year:		244.37	days
   Length of day:		677.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.043	AU
   Mass:			0.064	Earth masses
   Equatorial radius:		2590.3	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.113
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		25.63	degrees Celcius
   Normal daytime temperature:	94.68	degrees Celcius
   Normal night temperature:	-45.77	degrees Celcius
   Maximum temperature:   	124.33	degrees Celcius
   Minimum temperature:   	-76.91	degrees Celcius
   Escape Velocity:		4.45	km/sec
   Molecular weight retained:	40.12 and above
   Surface acceleration:	381.92	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.055
   Length of year:		372.56	days
   Length of day:		62.85	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	
   Distance from primary:	1.218	AU
   Mass:			1.518	Earth masses
   Equatorial radius:		7332.3	km
   Density:			5.494	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		1.15	Earth gees
   Surface pressure:		2.200	Earth atmospheres
   Surface temperature:		0.28	degrees Celcius
   Normal daytime temperature:	2.96	degrees Celcius
   Normal night temperature:	-2.56	degrees Celcius
   Maximum temperature:   	19.41	degrees Celcius
   Minimum temperature:   	-19.94	degrees Celcius
   Escape Velocity:		12.85	km/sec
   Molecular weight retained:	4.81 and above
   Surface acceleration:	1125.84	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.131
   Length of year:		470.68	days
   Length of day:		14.54	hours
   Boiling point of water:	123.1	degrees Celcius
   Hydrosphere percentage:	77.91
   Cloud cover percentage:	19.64
   Ice cover percentage:	8.31
   liquids at surface:
				Ethanol      melts at -114  boils at 100
				Mercury      melts at -39   boils at 396
				Bromine      melts at -7    boils at 80
				Water        melts at 0     boils at 123
   gasses in atmosphere:
				Oxygen            2.8%  PP   61.6 mb
				Nitrogen         97.0%  PP 2134.1 mb
				CarbonDioxide     0.1%  PP    1.2 mb
				Ozone             0.1%  PP    1.2 mb


Planet 7	*gas giant*
   Distance from primary:	2.326	AU
   Mass:			197.571	Earth masses
   Equatorial radius:		52204.7	km
   Density:			1.981	grams/cc
   Eccentricity of orbit:	0.138
   Escape Velocity:		54.94	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2890.96	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.453
   Length of year:		1241.44	days
   Length of day:		7.60	hours


Planet 8	*gas giant*
   Distance from primary:	5.960	AU
   Mass:			354.675	Earth masses
   Equatorial radius:		66968.9	km
   Density:			1.685	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		64.99	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3153.73	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.537
   Length of year:		5089.79	days
   Length of day:		7.28	hours


Planet 9	*gas giant*
   Distance from primary:	12.675	AU
   Mass:			707.507	Earth masses
   Equatorial radius:		87227.1	km
   Density:			1.521	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		80.43	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3708.23	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.499
   Length of year:		15777.23	days
   Length of day:		6.71	hours


Planet 10	*gas giant*
   Distance from primary:	18.855	AU
   Mass:			26.737	Earth masses
   Equatorial radius:		34681.1	km
   Density:			0.915	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		24.80	km/sec
   Molecular weight retained:	1.29 and above
   Surface acceleration:	886.46	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.494
   Length of year:		28652.67	days
   Length of day:		13.73	hours


Planet 11	*gas giant*
   Distance from primary:	41.902	AU
   Mass:			0.956	Earth masses
   Equatorial radius:		14029.7	km
   Density:			0.494	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		7.37	km/sec
   Molecular weight retained:	14.61 and above
   Surface acceleration:	193.68	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.549
   Length of year:		94932.44	days
   Length of day:		29.37	hours


