                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c7d
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6178 K
Stellar class: F8
Age: 3.476 billion years  (3.706 billion left on main sequence)
Habitable ecosphere radius: 1.232 AU

Planets present at:
1	  0.385 AU	no atmosphere
2	  0.686 AU	no atmosphere
3	  1.109 AU	greenhouse
4	  2.186 AU	gas giant
5	  4.249 AU	gas giant
6	  5.471 AU	no atmosphere
7	 10.378 AU	gas giant
8	 14.052 AU	gas giant
9	 22.918 AU	gas giant
10	 39.426 AU	gas giant
11	 50.440 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.385	AU
   Mass:			0.288	Earth masses
   Equatorial radius:		4255.0	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.136
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		216.95	degrees Celcius
   Normal daytime temperature:	426.28	degrees Celcius
   Normal night temperature:	-183.25	degrees Celcius
   Maximum temperature:   	429.84	degrees Celcius
   Minimum temperature:   	-195.14	degrees Celcius
   Escape Velocity:		7.34	km/sec
   Molecular weight retained:	14.73 and above
   Surface acceleration:	633.47	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.067
   Length of year:		83.67	days
   Length of day:		1528.27	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.686	AU
   Mass:			0.283	Earth masses
   Equatorial radius:		4233.7	km
   Density:			5.326	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		93.31	degrees Celcius
   Maximum temperature:   	277.54	degrees Celcius
   Minimum temperature:   	-225.94	degrees Celcius
   Escape Velocity:		7.30	km/sec
   Molecular weight retained:	14.88 and above
   Surface acceleration:	630.20	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.075
   Length of year:		198.88	days
   Length of day:		4773.05	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 3	
   Distance from primary:	1.109	AU
   Mass:			3.214	Earth masses
   Equatorial radius:		9323.4	km
   Density:			5.659	grams/cc
   Eccentricity of orbit:	0.153
   Surface gravity:		1.50	Earth gees
   Surface pressure:		805.485	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		627.56	degrees Celcius
   Maximum temperature:   	628.42	degrees Celcius
   Minimum temperature:   	622.90	degrees Celcius
   Escape Velocity:		16.58	km/sec
   Molecular weight retained:	2.89 and above
   Surface acceleration:	1474.59	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.437
   Length of year:		408.84	days
   Length of day:		12.60	hours
   Boiling point of water:	464.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1605
				Cesium       melts at 28    boils at 1660
				Gallium      melts at 30    boils at 5017
				Rubidium     melts at 39    boils at 1627
				Potassium    melts at 63    boils at 1780
				Sodium       melts at 98    boils at 2010
				Indium       melts at 157   boils at 4379
				Lithium      melts at 181   boils at 2930
				Selenium     melts at 217   boils at 1621
				Tin          melts at 232   boils at 5452
				Polonium     melts at 254   boils at 2168
				Bismuth      melts at 271   boils at 3359
				Thallium     melts at 304   boils at 3147
				Cadmium      melts at 321   boils at 1779
				Lead         melts at 328   boils at 3728
				Zinc         melts at 420   boils at 2060
				Tellurium    melts at 450   boils at 2224
   gasses in atmosphere:
				Sulfur            0.1%  PP  697.6 mb
				Nitrogen          0.4%  PP 3350.6 mb
				Helium           99.5%  PP 801416.8 mb


Planet 4	*gas giant*
   Distance from primary:	2.186	AU
   Mass:			35.952	Earth masses
   Equatorial radius:		31592.2	km
   Density:			1.627	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		30.13	km/sec
   Molecular weight retained:	0.87 and above
   Surface acceleration:	1436.50	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.452
   Length of year:		1130.57	days
   Length of day:		10.78	hours


Planet 5	*gas giant*
   Distance from primary:	4.249	AU
   Mass:			423.346	Earth masses
   Equatorial radius:		68549.4	km
   Density:			1.875	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		70.18	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3592.76	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.454
   Length of year:		3062.71	days
   Length of day:		6.82	hours


Planet 6	
   Distance from primary:	5.471	AU
   Mass:			0.327	Earth masses
   Equatorial radius:		5930.1	km
   Density:			2.241	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.072	Earth atmospheres
   Surface temperature:		-144.11	degrees Celcius
   Normal daytime temperature:	-135.17	degrees Celcius
   Normal night temperature:	-153.41	degrees Celcius
   Maximum temperature:   	-115.32	degrees Celcius
   Minimum temperature:   	-174.67	degrees Celcius
   Escape Velocity:		6.64	km/sec
   Molecular weight retained:	18.02 and above
   Surface acceleration:	371.38	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.297
   Length of year:		4478.10	days
   Length of day:		24.87	hours
   Boiling point of water:	39.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	27.26
   liquids at surface:
				Ozone        melts at -193  boils at -138
   gasses in atmosphere:
				Fluorine          0.7%  PP    0.5 mb
				Argon             3.6%  PP    2.6 mb
				Neon              8.5%  PP    6.1 mb
				Krypton          87.2%  PP   63.2 mb


Planet 7	*gas giant*
   Distance from primary:	10.378	AU
   Mass:			3.745	Earth masses
   Equatorial radius:		18597.4	km
   Density:			0.831	grams/cc
   Eccentricity of orbit:	0.125
   Escape Velocity:		12.67	km/sec
   Molecular weight retained:	4.94 and above
   Surface acceleration:	431.77	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.508
   Length of year:		11699.01	days
   Length of day:		19.67	hours


Planet 8	*gas giant*
   Distance from primary:	14.052	AU
   Mass:			513.629	Earth masses
   Equatorial radius:		80127.1	km
   Density:			1.425	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		71.50	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3190.28	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.521
   Length of year:		18419.03	days
   Length of day:		7.24	hours


Planet 9	*gas giant*
   Distance from primary:	22.918	AU
   Mass:			11.940	Earth masses
   Equatorial radius:		27861.0	km
   Density:			0.788	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		18.49	km/sec
   Molecular weight retained:	2.32 and above
   Surface acceleration:	613.38	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.475
   Length of year:		38388.40	days
   Length of day:		16.50	hours


Planet 10	*gas giant*
   Distance from primary:	39.426	AU
   Mass:			1.437	Earth masses
   Equatorial radius:		15720.9	km
   Density:			0.528	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		8.54	km/sec
   Molecular weight retained:	10.89 and above
   Surface acceleration:	231.95	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.524
   Length of year:		86621.56	days
   Length of day:		26.84	hours


Planet 11	
   Distance from primary:	50.440	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		3305.2	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.14	degrees Celcius
   Normal daytime temperature:	-225.12	degrees Celcius
   Normal night temperature:	-237.04	degrees Celcius
   Maximum temperature:   	-212.29	degrees Celcius
   Minimum temperature:   	-250.04	degrees Celcius
   Escape Velocity:		3.67	km/sec
   Molecular weight retained:	59.02 and above
   Surface acceleration:	203.46	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.149
   Length of year:		125349.54	days
   Length of day:		33.60	hours
   Boiling point of water:	-74.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


