                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048932
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6318 K
Stellar class: F7
Age: 1.064 billion years  (5.689 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.381 AU	no atmosphere
2	  0.504 AU	no atmosphere
3	  0.722 AU	greenhouse
4	  1.244 AU	high pressure
5	  2.586 AU	high pressure
6	  3.009 AU	no atmosphere
7	  3.877 AU	gas giant
8	  7.246 AU	gas giant
9	 13.312 AU	gas giant
10	 27.833 AU	gas giant
11	 49.770 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.381	AU
   Mass:			0.071	Earth masses
   Equatorial radius:		2674.8	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.172
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.51	degrees Celcius
   Normal daytime temperature:	441.31	degrees Celcius
   Normal night temperature:	-177.90	degrees Celcius
   Maximum temperature:   	445.07	degrees Celcius
   Minimum temperature:   	-190.89	degrees Celcius
   Escape Velocity:		4.59	km/sec
   Molecular weight retained:	37.61 and above
   Surface acceleration:	394.53	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.066
   Length of year:		81.63	days
   Length of day:		1383.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.504	AU
   Mass:			0.514	Earth masses
   Equatorial radius:		5150.6	km
   Density:			5.365	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		163.91	degrees Celcius
   Maximum temperature:   	365.60	degrees Celcius
   Minimum temperature:   	-214.51	degrees Celcius
   Escape Velocity:		8.92	km/sec
   Molecular weight retained:	9.98 and above
   Surface acceleration:	772.35	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.066
   Length of year:		124.17	days
   Length of day:		2980.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.722	AU
   Mass:			0.463	Earth masses
   Equatorial radius:		4977.7	km
   Density:			5.357	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.76	Earth gees
   Surface pressure:		16.846	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		174.98	degrees Celcius
   Maximum temperature:   	184.48	degrees Celcius
   Minimum temperature:   	164.74	degrees Celcius
   Escape Velocity:		8.61	km/sec
   Molecular weight retained:	10.70 and above
   Surface acceleration:	745.30	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.446
   Length of year:		212.99	days
   Length of day:		21.87	hours
   Boiling point of water:	198.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 523
				Francium     melts at 27    boils at 927
				Cesium       melts at 28    boils at 963
				Gallium      melts at 30    boils at 3108
				Rubidium     melts at 39    boils at 941
				Phosphorus   melts at 44    boils at 426
				Potassium    melts at 63    boils at 1039
				Sodium       melts at 98    boils at 1186
				Sulfur       melts at 113   boils at 634
				Iodine       melts at 114   boils at 306
				Indium       melts at 157   boils at 2700
   gasses in atmosphere:
				Nitrogen         99.5%  PP 16760.8 mb
				Water             0.1%  PP    9.4 mb
				CarbonDioxide     0.1%  PP   19.0 mb
				Ammonia           0.1%  PP    8.5 mb
				Ozone             0.1%  PP   19.5 mb
				Ethanol           0.1%  PP   19.4 mb


Planet 4	
   Distance from primary:	1.244	AU
   Mass:			1.737	Earth masses
   Equatorial radius:		7658.5	km
   Density:			5.518	grams/cc
   Eccentricity of orbit:	0.097
   Surface gravity:		1.20	Earth gees
   Surface pressure:		2.629	Earth atmospheres
   Surface temperature:		21.70	degrees Celcius
   Normal daytime temperature:	24.25	degrees Celcius
   Normal night temperature:	18.99	degrees Celcius
   Maximum temperature:   	40.51	degrees Celcius
   Minimum temperature:   	1.86	degrees Celcius
   Escape Velocity:		13.45	km/sec
   Molecular weight retained:	4.39 and above
   Surface acceleration:	1181.00	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.407
   Length of year:		481.76	days
   Length of day:		13.98	hours
   Boiling point of water:	128.7	degrees Celcius
   Hydrosphere percentage:	74.59
   Cloud cover percentage:	82.89
   Ice cover percentage:	0.71
   liquids at surface:
				Ethanol      melts at -114  boils at 106
				Mercury      melts at -39   boils at 405
				Bromine      melts at -7    boils at 85
				Water        melts at 0     boils at 129
   gasses in atmosphere:
				Oxygen           10.4%  PP  272.3 mb
				Nitrogen         89.5%  PP 2353.1 mb


Planet 5	
   Distance from primary:	2.586	AU
   Mass:			1.928	Earth masses
   Equatorial radius:		7919.6	km
   Density:			5.538	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		1.25	Earth gees
   Surface pressure:		3.416	Earth atmospheres
   Surface temperature:		-91.93	degrees Celcius
   Normal daytime temperature:	-90.57	degrees Celcius
   Normal night temperature:	-93.36	degrees Celcius
   Maximum temperature:   	-78.44	degrees Celcius
   Minimum temperature:   	-106.35	degrees Celcius
   Escape Velocity:		13.93	km/sec
   Molecular weight retained:	4.09 and above
   Surface acceleration:	1225.67	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.650
   Length of year:		1443.68	days
   Length of day:		13.69	hours
   Boiling point of water:	137.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 114
				Chlorine     melts at -101  boils at -10
   gasses in atmosphere:
				Oxygen            4.0%  PP  137.7 mb
				Nitrogen         95.9%  PP 3276.0 mb


Planet 6	
   Distance from primary:	3.009	AU
   Mass:			0.248	Earth masses
   Equatorial radius:		4050.6	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.047	Earth atmospheres
   Surface temperature:		-103.70	degrees Celcius
   Normal daytime temperature:	-93.01	degrees Celcius
   Normal night temperature:	-114.67	degrees Celcius
   Maximum temperature:   	-71.15	degrees Celcius
   Minimum temperature:   	-137.80	degrees Celcius
   Escape Velocity:		6.98	km/sec
   Molecular weight retained:	16.27 and above
   Surface acceleration:	602.17	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.400
   Length of year:		1811.23	days
   Length of day:		19.53	hours
   Boiling point of water:	31.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	49.93
   liquids at surface:
				Ethanol      melts at -114  boils at 14
   gasses in atmosphere:
				Ozone            89.8%  PP   42.1 mb
				Fluorine          3.7%  PP    1.7 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.9%  PP    0.4 mb
				Krypton           5.0%  PP    2.3 mb
				Xenon             0.6%  PP    0.3 mb


Planet 7	*gas giant*
   Distance from primary:	3.877	AU
   Mass:			474.729	Earth masses
   Equatorial radius:		70111.9	km
   Density:			1.965	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		73.49	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3851.25	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.461
   Length of year:		2648.02	days
   Length of day:		6.59	hours


Planet 8	*gas giant*
   Distance from primary:	7.246	AU
   Mass:			72.062	Earth masses
   Equatorial radius:		42621.0	km
   Density:			1.328	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		36.72	km/sec
   Molecular weight retained:	0.59 and above
   Surface acceleration:	1581.98	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.466
   Length of year:		6768.60	days
   Length of day:		10.28	hours


Planet 9	*gas giant*
   Distance from primary:	13.312	AU
   Mass:			614.511	Earth masses
   Equatorial radius:		83777.2	km
   Density:			1.491	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		76.49	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3491.54	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.496
   Length of year:		16842.76	days
   Length of day:		6.92	hours


Planet 10	*gas giant*
   Distance from primary:	27.833	AU
   Mass:			39.801	Earth masses
   Equatorial radius:		40099.0	km
   Density:			0.881	grams/cc
   Eccentricity of orbit:	0.118
   Escape Velocity:		28.14	km/sec
   Molecular weight retained:	1.00 and above
   Surface acceleration:	987.11	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.504
   Length of year:		50960.91	days
   Length of day:		13.01	hours


Planet 11	
   Distance from primary:	49.770	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		3592.0	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.219
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.16	degrees Celcius
   Normal daytime temperature:	-224.22	degrees Celcius
   Normal night temperature:	-235.99	degrees Celcius
   Maximum temperature:   	-205.75	degrees Celcius
   Minimum temperature:   	-253.71	degrees Celcius
   Escape Velocity:		3.99	km/sec
   Molecular weight retained:	49.90 and above
   Surface acceleration:	221.43	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.159
   Length of year:		121864.57	days
   Length of day:		32.21	hours
   Boiling point of water:	-71.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


