                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950486fb
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6171 K
Stellar class: F8
Age: 1.884 billion years  (4.941 billion left on main sequence)
Habitable ecosphere radius: 1.272 AU

Planets present at:
1	  0.388 AU	no atmosphere
2	  0.519 AU	no atmosphere
3	  0.914 AU	greenhouse
4	  1.366 AU	cold
5	  1.850 AU	high pressure
6	  4.314 AU	gas giant
7	  7.810 AU	cold
8	 15.349 AU	gas giant
9	 23.668 AU	gas giant
10	 43.025 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.388	AU
   Mass:			0.069	Earth masses
   Equatorial radius:		2657.9	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.110
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		221.22	degrees Celcius
   Normal daytime temperature:	431.73	degrees Celcius
   Normal night temperature:	-184.25	degrees Celcius
   Maximum temperature:   	435.14	degrees Celcius
   Minimum temperature:   	-195.65	degrees Celcius
   Escape Velocity:		4.56	km/sec
   Molecular weight retained:	38.10 and above
   Surface acceleration:	392.00	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.080
   Length of year:		84.06	days
   Length of day:		1617.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.519	AU
   Mass:			0.441	Earth masses
   Equatorial radius:		4899.7	km
   Density:			5.354	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		157.34	degrees Celcius
   Maximum temperature:   	357.47	degrees Celcius
   Minimum temperature:   	-215.78	degrees Celcius
   Escape Velocity:		8.48	km/sec
   Molecular weight retained:	11.05 and above
   Surface acceleration:	733.13	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.055
   Length of year:		129.89	days
   Length of day:		3117.46	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.914	AU
   Mass:			1.499	Earth masses
   Equatorial radius:		7303.4	km
   Density:			5.492	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		1.14	Earth gees
   Surface pressure:		209.228	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		482.51	degrees Celcius
   Maximum temperature:   	485.38	degrees Celcius
   Minimum temperature:   	477.40	degrees Celcius
   Escape Velocity:		12.80	km/sec
   Molecular weight retained:	4.85 and above
   Surface acceleration:	1120.99	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.555
   Length of year:		303.60	days
   Length of day:		14.79	hours
   Boiling point of water:	343.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1296
				Cesium       melts at 28    boils at 1342
				Gallium      melts at 30    boils at 4147
				Rubidium     melts at 39    boils at 1314
				Potassium    melts at 63    boils at 1443
				Sodium       melts at 98    boils at 1634
				Indium       melts at 157   boils at 3614
				Lithium      melts at 181   boils at 2403
				Selenium     melts at 217   boils at 1309
				Tin          melts at 232   boils at 4511
				Polonium     melts at 254   boils at 1767
				Bismuth      melts at 271   boils at 2761
				Thallium     melts at 304   boils at 2585
				Cadmium      melts at 321   boils at 1442
				Lead         melts at 328   boils at 3070
				Zinc         melts at 420   boils at 1676
				Tellurium    melts at 450   boils at 1813
   gasses in atmosphere:
				Sulfur           18.7%  PP 39158.8 mb
				Nitrogen         80.7%  PP 168877.2 mb
				Phosphorus        0.4%  PP  783.2 mb


Planet 4	
   Distance from primary:	1.366	AU
   Mass:			0.381	Earth masses
   Equatorial radius:		4670.3	km
   Density:			5.344	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.138	Earth atmospheres
   Surface temperature:		-0.54	degrees Celcius
   Normal daytime temperature:	10.99	degrees Celcius
   Normal night temperature:	-12.59	degrees Celcius
   Maximum temperature:   	36.98	degrees Celcius
   Minimum temperature:   	-39.81	degrees Celcius
   Escape Velocity:		8.07	km/sec
   Molecular weight retained:	12.18 and above
   Surface acceleration:	697.50	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.214
   Length of year:		554.80	days
   Length of day:		18.31	hours
   Boiling point of water:	52.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	10.76
   Ice cover percentage:	9.62
   liquids at surface:
				Ethanol      melts at -114  boils at 34
				Mercury      melts at -39   boils at 277
				Bromine      melts at -7    boils at 17
   gasses in atmosphere:
				Oxygen           68.0%  PP   93.6 mb
				Nitrogen         31.8%  PP   43.9 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 5	
   Distance from primary:	1.850	AU
   Mass:			1.883	Earth masses
   Equatorial radius:		7860.2	km
   Density:			5.533	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		1.24	Earth gees
   Surface pressure:		3.649	Earth atmospheres
   Surface temperature:		-71.50	degrees Celcius
   Normal daytime temperature:	-70.04	degrees Celcius
   Normal night temperature:	-73.06	degrees Celcius
   Maximum temperature:   	-58.78	degrees Celcius
   Minimum temperature:   	-85.04	degrees Celcius
   Escape Velocity:		13.82	km/sec
   Molecular weight retained:	4.15 and above
   Surface acceleration:	1215.46	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.725
   Length of year:		874.59	days
   Length of day:		13.75	hours
   Boiling point of water:	139.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.15
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 116
				Chlorine     melts at -101  boils at -9
				Ammonia      melts at -78   boils at -8
   gasses in atmosphere:
				Nitrogen         99.8%  PP 3642.8 mb


Planet 6	*gas giant*
   Distance from primary:	4.314	AU
   Mass:			826.301	Earth masses
   Equatorial radius:		83195.7	km
   Density:			2.048	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		89.00	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4760.75	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.531
   Length of year:		3110.77	days
   Length of day:		5.92	hours


Planet 7	
   Distance from primary:	7.810	AU
   Mass:			0.486	Earth masses
   Equatorial radius:		6748.8	km
   Density:			2.258	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.156	Earth atmospheres
   Surface temperature:		-161.90	degrees Celcius
   Normal daytime temperature:	-156.35	degrees Celcius
   Normal night temperature:	-167.76	degrees Celcius
   Maximum temperature:   	-139.93	degrees Celcius
   Minimum temperature:   	-185.69	degrees Celcius
   Escape Velocity:		7.58	km/sec
   Molecular weight retained:	13.81 and above
   Surface acceleration:	425.82	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.296
   Length of year:		7585.70	days
   Length of day:		23.23	hours
   Boiling point of water:	55.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	30.52
   liquids at surface:
				Ozone        melts at -193  boils at -131
   gasses in atmosphere:
				Oxygen           91.5%  PP  142.7 mb
				Nitrogen          8.5%  PP   13.2 mb


Planet 8	*gas giant*
   Distance from primary:	15.349	AU
   Mass:			2.860	Earth masses
   Equatorial radius:		17713.1	km
   Density:			0.734	grams/cc
   Eccentricity of orbit:	0.206
   Escape Velocity:		11.35	km/sec
   Molecular weight retained:	6.16 and above
   Surface acceleration:	363.47	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.533
   Length of year:		20899.95	days
   Length of day:		21.44	hours


Planet 9	*gas giant*
   Distance from primary:	23.668	AU
   Mass:			56.823	Earth masses
   Equatorial radius:		43914.8	km
   Density:			0.957	grams/cc
   Eccentricity of orbit:	0.221
   Escape Velocity:		32.12	km/sec
   Molecular weight retained:	0.77 and above
   Surface acceleration:	1175.00	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.478
   Length of year:		40016.80	days
   Length of day:		11.92	hours


Planet 10	*gas giant*
   Distance from primary:	43.025	AU
   Mass:			0.979	Earth masses
   Equatorial radius:		14120.3	km
   Density:			0.496	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		7.44	km/sec
   Molecular weight retained:	14.35 and above
   Surface acceleration:	195.85	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.532
   Length of year:		98087.79	days
   Length of day:		29.21	hours


