                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048599
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6333 K
Stellar class: F7
Age: 2.323 billion years  (4.548 billion left on main sequence)
Habitable ecosphere radius: 1.267 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.391 AU	no atmosphere
3	  0.599 AU	no atmosphere
4	  0.728 AU	greenhouse
5	  1.314 AU	high pressure
6	  2.213 AU	cold
7	  4.315 AU	gas giant
8	  6.787 AU	gas giant
9	 17.784 AU	gas giant
10	 26.887 AU	no atmosphere
11	 44.743 AU	gas giant
12	 51.513 AU	no atmosphere



Planet 1	
   Distance from primary:	0.358	AU
   Mass:			1/246	Earth masses
   Equatorial radius:		1033.8	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		239.83	degrees Celcius
   Maximum temperature:   	457.82	degrees Celcius
   Minimum temperature:   	-194.14	degrees Celcius
   Escape Velocity:		1.77	km/sec
   Molecular weight retained:	253.09 and above
   Surface acceleration:	151.70	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.084
   Length of year:		74.62	days
   Length of day:		1790.80	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.391	AU
   Mass:			0.216	Earth masses
   Equatorial radius:		3870.8	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		219.91	degrees Celcius
   Maximum temperature:   	433.80	degrees Celcius
   Minimum temperature:   	-200.15	degrees Celcius
   Escape Velocity:		6.67	km/sec
   Molecular weight retained:	17.84 and above
   Surface acceleration:	574.74	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.068
   Length of year:		85.09	days
   Length of day:		2042.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.599	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		2457.0	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.45	degrees Celcius
   Maximum temperature:   	316.51	degrees Celcius
   Minimum temperature:   	-221.49	degrees Celcius
   Escape Velocity:		4.22	km/sec
   Molecular weight retained:	44.62 and above
   Surface acceleration:	362.05	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.077
   Length of year:		161.15	days
   Length of day:		3867.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.728	AU
   Mass:			0.723	Earth masses
   Equatorial radius:		5761.8	km
   Density:			5.396	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.89	Earth gees
   Surface pressure:		48.426	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		290.71	degrees Celcius
   Maximum temperature:   	296.91	degrees Celcius
   Minimum temperature:   	283.42	degrees Celcius
   Escape Velocity:		10.01	km/sec
   Molecular weight retained:	7.93 and above
   Surface acceleration:	868.97	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.476
   Length of year:		216.25	days
   Length of day:		22.58	hours
   Boiling point of water:	249.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 610
				Francium     melts at 27    boils at 1058
				Cesium       melts at 28    boils at 1098
				Gallium      melts at 30    boils at 3478
				Rubidium     melts at 39    boils at 1074
				Potassium    melts at 63    boils at 1183
				Sodium       melts at 98    boils at 1345
				Sulfur       melts at 113   boils at 733
				Indium       melts at 157   boils at 3025
				Lithium      melts at 181   boils at 1998
				Selenium     melts at 217   boils at 1070
				Tin          melts at 232   boils at 3786
				Polonium     melts at 254   boils at 1458
				Bismuth      melts at 271   boils at 2302
   gasses in atmosphere:
				Nitrogen         99.0%  PP 47944.0 mb
				Phosphorus        0.7%  PP  316.3 mb
				CarbonDioxide     0.1%  PP   35.3 mb
				Ozone             0.1%  PP   34.3 mb
				Ethanol           0.1%  PP   35.8 mb


Planet 5	
   Distance from primary:	1.314	AU
   Mass:			2.561	Earth masses
   Equatorial radius:		8674.1	km
   Density:			5.600	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		1.38	Earth gees
   Surface pressure:		5.007	Earth atmospheres
   Surface temperature:		30.70	degrees Celcius
   Normal daytime temperature:	32.49	degrees Celcius
   Normal night temperature:	28.79	degrees Celcius
   Maximum temperature:   	44.07	degrees Celcius
   Minimum temperature:   	16.66	degrees Celcius
   Escape Velocity:		15.35	km/sec
   Molecular weight retained:	3.37 and above
   Surface acceleration:	1357.51	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.447
   Length of year:		524.16	days
   Length of day:		13.05	hours
   Boiling point of water:	150.4	degrees Celcius
   Hydrosphere percentage:	75.10
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.17
   liquids at surface:
				Ethanol      melts at -114  boils at 126
				Mercury      melts at -39   boils at 442
				Bromine      melts at -7    boils at 104
				Water        melts at 0     boils at 150
				Francium     melts at 27    boils at 805
				Cesium       melts at 28    boils at 837
				Gallium      melts at 30    boils at 2764
   gasses in atmosphere:
				Nitrogen          0.6%  PP   32.1 mb
				Helium           99.4%  PP 4975.0 mb


Planet 6	
   Distance from primary:	2.213	AU
   Mass:			1.035	Earth masses
   Equatorial radius:		6476.2	km
   Density:			5.437	grams/cc
   Eccentricity of orbit:	0.216
   Surface gravity:		1.00	Earth gees
   Surface pressure:		0.778	Earth atmospheres
   Surface temperature:		-79.30	degrees Celcius
   Normal daytime temperature:	-76.01	degrees Celcius
   Normal night temperature:	-82.77	degrees Celcius
   Maximum temperature:   	-54.95	degrees Celcius
   Minimum temperature:   	-105.39	degrees Celcius
   Escape Velocity:		11.29	km/sec
   Molecular weight retained:	6.23 and above
   Surface acceleration:	984.15	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.576
   Length of year:		1145.37	days
   Length of day:		15.28	hours
   Boiling point of water:	93.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	77.67
   liquids at surface:
				Ethanol      melts at -114  boils at 72
				Chlorine     melts at -101  boils at -38
   gasses in atmosphere:
				Oxygen           12.1%  PP   94.1 mb
				Nitrogen         87.8%  PP  683.0 mb


Planet 7	*gas giant*
   Distance from primary:	4.315	AU
   Mass:			1006.375	Earth masses
   Equatorial radius:		88151.9	km
   Density:			2.096	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		95.42	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	5164.59	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.489
   Length of year:		3113.38	days
   Length of day:		5.69	hours


Planet 8	*gas giant*
   Distance from primary:	6.787	AU
   Mass:			102.055	Earth masses
   Equatorial radius:		46960.3	km
   Density:			1.406	grams/cc
   Eccentricity of orbit:	0.091
   Escape Velocity:		41.63	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1845.48	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.538
   Length of year:		6150.02	days
   Length of day:		9.51	hours


Planet 9	*gas giant*
   Distance from primary:	17.784	AU
   Mass:			505.772	Earth masses
   Equatorial radius:		81159.1	km
   Density:			1.350	grams/cc
   Eccentricity of orbit:	0.164
   Escape Velocity:		70.50	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3062.10	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.456
   Length of year:		26070.85	days
   Length of day:		7.39	hours


Planet 10	
   Distance from primary:	26.887	AU
   Mass:			0.152	Earth masses
   Equatorial radius:		4610.7	km
   Density:			2.219	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-214.64	degrees Celcius
   Normal daytime temperature:	-207.40	degrees Celcius
   Normal night temperature:	-221.82	degrees Celcius
   Maximum temperature:   	-190.37	degrees Celcius
   Minimum temperature:   	-239.54	degrees Celcius
   Escape Velocity:		5.13	km/sec
   Molecular weight retained:	30.11 and above
   Surface acceleration:	285.91	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.138
   Length of year:		48500.68	days
   Length of day:		28.34	hours
   Boiling point of water:	-58.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 11	*gas giant*
   Distance from primary:	44.743	AU
   Mass:			0.617	Earth masses
   Equatorial radius:		12384.3	km
   Density:			0.463	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		6.30	km/sec
   Molecular weight retained:	19.98 and above
   Surface acceleration:	160.38	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.533
   Length of year:		104114.84	days
   Length of day:		32.27	hours


Planet 12	
   Distance from primary:	51.513	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		2291.7	km
   Density:			2.194	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.14	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.98	degrees Celcius
   Normal daytime temperature:	-223.91	degrees Celcius
   Normal night temperature:	-237.89	degrees Celcius
   Maximum temperature:   	-208.81	degrees Celcius
   Minimum temperature:   	-252.56	degrees Celcius
   Escape Velocity:		2.54	km/sec
   Molecular weight retained:	123.26 and above
   Surface acceleration:	140.51	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.146
   Length of year:		128616.42	days
   Length of day:		40.43	hours
   Boiling point of water:	-89.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


