                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f68
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6123 K
Stellar class: F9
Age: 2.116 billion years  (4.964 billion left on main sequence)
Habitable ecosphere radius: 1.243 AU

Planets present at:
1	  0.367 AU	no atmosphere
2	  0.513 AU	no atmosphere
3	  0.731 AU	greenhouse
4	  1.092 AU	greenhouse
5	  1.533 AU	gas giant
6	  1.953 AU	no atmosphere
7	  4.178 AU	gas giant
8	  7.882 AU	cold
9	 10.116 AU	gas giant
10	 18.915 AU	no atmosphere
11	 21.775 AU	gas giant
12	 36.521 AU	gas giant
13	 50.429 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.367	AU
   Mass:			0.034	Earth masses
   Equatorial radius:		2091.8	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.187
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.74	degrees Celcius
   Normal daytime temperature:	441.25	degrees Celcius
   Normal night temperature:	-174.96	degrees Celcius
   Maximum temperature:   	445.18	degrees Celcius
   Minimum temperature:   	-188.64	degrees Celcius
   Escape Velocity:		3.59	km/sec
   Molecular weight retained:	61.65 and above
   Surface acceleration:	307.81	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.077
   Length of year:		77.71	days
   Length of day:		1276.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.513	AU
   Mass:			0.432	Earth masses
   Equatorial radius:		4865.2	km
   Density:			5.352	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		153.98	degrees Celcius
   Maximum temperature:   	353.13	degrees Celcius
   Minimum temperature:   	-215.58	degrees Celcius
   Escape Velocity:		8.42	km/sec
   Molecular weight retained:	11.21 and above
   Surface acceleration:	727.76	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.061
   Length of year:		128.48	days
   Length of day:		3083.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.731	AU
   Mass:			0.576	Earth masses
   Equatorial radius:		5346.3	km
   Density:			5.375	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.82	Earth gees
   Surface pressure:		29.438	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		179.90	degrees Celcius
   Maximum temperature:   	187.58	degrees Celcius
   Minimum temperature:   	171.54	degrees Celcius
   Escape Velocity:		9.27	km/sec
   Molecular weight retained:	9.24 and above
   Surface acceleration:	803.11	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.563
   Length of year:		218.33	days
   Length of day:		24.04	hours
   Boiling point of water:	224.2	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 567
				Francium     melts at 27    boils at 993
				Cesium       melts at 28    boils at 1031
				Gallium      melts at 30    boils at 3294
				Rubidium     melts at 39    boils at 1008
				Phosphorus   melts at 44    boils at 465
				Potassium    melts at 63    boils at 1111
				Sodium       melts at 98    boils at 1266
				Sulfur       melts at 113   boils at 684
				Iodine       melts at 114   boils at 338
				Indium       melts at 157   boils at 2863
   gasses in atmosphere:
				Nitrogen         99.6%  PP 29318.1 mb
				CarbonDioxide     0.1%  PP   26.3 mb
				Ozone             0.1%  PP   26.4 mb
				Ethanol           0.1%  PP   26.8 mb


Planet 4	
   Distance from primary:	1.092	AU
   Mass:			0.334	Earth masses
   Equatorial radius:		4469.7	km
   Density:			5.335	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.68	Earth gees
   Surface pressure:		9.380	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		43.44	degrees Celcius
   Maximum temperature:   	54.27	degrees Celcius
   Minimum temperature:   	32.04	degrees Celcius
   Escape Velocity:		7.72	km/sec
   Molecular weight retained:	13.32 and above
   Surface acceleration:	666.50	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.532
   Length of year:		398.39	days
   Length of day:		19.38	hours
   Boiling point of water:	173.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 148
				Mercury      melts at -39   boils at 482
				Bromine      melts at -7    boils at 125
				Water        melts at 0     boils at 174
				Francium     melts at 27    boils at 865
				Cesium       melts at 28    boils at 899
				Gallium      melts at 30    boils at 2933
				Rubidium     melts at 39    boils at 878
   gasses in atmosphere:
				Nitrogen         98.6%  PP 9251.1 mb
				CarbonDioxide     0.5%  PP   49.5 mb
				Methane           0.1%  PP   10.4 mb
				Ammonia           0.1%  PP   13.4 mb
				Ozone             0.5%  PP   51.2 mb


Planet 5	*gas giant*
   Distance from primary:	1.533	AU
   Mass:			5.597	Earth masses
   Equatorial radius:		17816.4	km
   Density:			1.412	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		15.83	km/sec
   Molecular weight retained:	3.17 and above
   Surface acceleration:	703.16	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.550
   Length of year:		662.97	days
   Length of day:		15.42	hours


Planet 6	
   Distance from primary:	1.953	AU
   Mass:			0.189	Earth masses
   Equatorial radius:		3703.3	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.032	Earth atmospheres
   Surface temperature:		-72.29	degrees Celcius
   Normal daytime temperature:	-57.85	degrees Celcius
   Normal night temperature:	-87.04	degrees Celcius
   Maximum temperature:   	-32.30	degrees Celcius
   Minimum temperature:   	-113.72	degrees Celcius
   Escape Velocity:		6.38	km/sec
   Molecular weight retained:	19.51 and above
   Surface acceleration:	549.28	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.459
   Length of year:		953.08	days
   Length of day:		20.49	hours
   Boiling point of water:	24.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	53.09
   liquids at surface:
				Ethanol      melts at -114  boils at 8
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP   14.8 mb
				Ozone            49.9%  PP   15.8 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.1%  PP    0.0 mb
				Krypton           3.0%  PP    1.0 mb
				Xenon             0.4%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	4.178	AU
   Mass:			456.861	Earth masses
   Equatorial radius:		69938.5	km
   Density:			1.906	grams/cc
   Eccentricity of orbit:	0.109
   Escape Velocity:		72.18	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3724.70	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.494
   Length of year:		2980.27	days
   Length of day:		6.70	hours


Planet 8	
   Distance from primary:	7.882	AU
   Mass:			0.423	Earth masses
   Equatorial radius:		6448.5	km
   Density:			2.251	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.109	Earth atmospheres
   Surface temperature:		-163.98	degrees Celcius
   Normal daytime temperature:	-157.63	degrees Celcius
   Normal night temperature:	-170.63	degrees Celcius
   Maximum temperature:   	-137.92	degrees Celcius
   Minimum temperature:   	-192.05	degrees Celcius
   Escape Velocity:		7.23	km/sec
   Molecular weight retained:	15.17 and above
   Surface acceleration:	405.71	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.286
   Length of year:		7728.51	days
   Length of day:		23.79	hours
   Boiling point of water:	47.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	26.90
   liquids at surface:
				Ozone        melts at -193  boils at -135
   gasses in atmosphere:
				Oxygen           100.0%  PP  109.1 mb


Planet 9	*gas giant*
   Distance from primary:	10.116	AU
   Mass:			594.882	Earth masses
   Equatorial radius:		81313.3	km
   Density:			1.579	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		76.39	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3587.95	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.528
   Length of year:		11227.89	days
   Length of day:		6.82	hours


Planet 10	
   Distance from primary:	18.915	AU
   Mass:			0.117	Earth masses
   Equatorial radius:		4228.6	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-204.04	degrees Celcius
   Normal daytime temperature:	-195.14	degrees Celcius
   Normal night temperature:	-212.90	degrees Celcius
   Maximum temperature:   	-177.68	degrees Celcius
   Minimum temperature:   	-231.19	degrees Celcius
   Escape Velocity:		4.70	km/sec
   Molecular weight retained:	35.88 and above
   Surface acceleration:	261.58	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.136
   Length of year:		28729.77	days
   Length of day:		29.63	hours
   Boiling point of water:	-61.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 11	*gas giant*
   Distance from primary:	21.775	AU
   Mass:			12.328	Earth masses
   Equatorial radius:		27982.1	km
   Density:			0.803	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		18.75	km/sec
   Molecular weight retained:	2.26 and above
   Surface acceleration:	627.90	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.517
   Length of year:		35486.93	days
   Length of day:		16.31	hours


Planet 12	*gas giant*
   Distance from primary:	36.521	AU
   Mass:			9.078	Earth masses
   Equatorial radius:		26719.8	km
   Density:			0.679	grams/cc
   Eccentricity of orbit:	0.141
   Escape Velocity:		16.46	km/sec
   Molecular weight retained:	2.93 and above
   Surface acceleration:	507.09	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.495
   Length of year:		77080.20	days
   Length of day:		18.15	hours


Planet 13	
   Distance from primary:	50.429	AU
   Mass:			0.078	Earth masses
   Equatorial radius:		3692.7	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.95	degrees Celcius
   Normal daytime temperature:	-225.18	degrees Celcius
   Normal night temperature:	-236.59	degrees Celcius
   Maximum temperature:   	-214.33	degrees Celcius
   Minimum temperature:   	-247.85	degrees Celcius
   Escape Velocity:		4.10	km/sec
   Molecular weight retained:	47.19 and above
   Surface acceleration:	227.75	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.148
   Length of year:		125071.54	days
   Length of day:		31.76	hours
   Boiling point of water:	-68.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


