                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504863d
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6162 K
Stellar class: F8
Age: 4.870 billion years  (1.979 billion left on main sequence)
Habitable ecosphere radius: 1.269 AU

Planets present at:
1	  0.371 AU	no atmosphere
2	  0.677 AU	no atmosphere
3	  1.032 AU	greenhouse
4	  1.436 AU	high pressure
5	  2.611 AU	gas giant
6	  4.395 AU	gas giant
7	  6.803 AU	cold
8	 13.641 AU	gas giant
9	 33.376 AU	gas giant
10	 49.298 AU	no atmosphere



Planet 1	
   Distance from primary:	0.371	AU
   Mass:			0.126	Earth masses
   Equatorial radius:		3236.9	km
   Density:			5.293	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		234.08	degrees Celcius
   Maximum temperature:   	450.80	degrees Celcius
   Minimum temperature:   	-195.79	degrees Celcius
   Escape Velocity:		5.57	km/sec
   Molecular weight retained:	25.61 and above
   Surface acceleration:	478.78	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.065
   Length of year:		78.56	days
   Length of day:		1885.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.677	AU
   Mass:			0.414	Earth masses
   Equatorial radius:		4798.8	km
   Density:			5.349	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		100.55	degrees Celcius
   Maximum temperature:   	286.72	degrees Celcius
   Minimum temperature:   	-225.12	degrees Celcius
   Escape Velocity:		8.30	km/sec
   Molecular weight retained:	11.53 and above
   Surface acceleration:	717.44	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.084
   Length of year:		193.54	days
   Length of day:		4644.96	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	1.032	AU
   Mass:			2.141	Earth masses
   Equatorial radius:		8190.8	km
   Density:			5.559	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		1.30	Earth gees
   Surface pressure:		382.713	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		482.15	degrees Celcius
   Maximum temperature:   	484.34	degrees Celcius
   Minimum temperature:   	477.76	degrees Celcius
   Escape Velocity:		14.44	km/sec
   Molecular weight retained:	3.81 and above
   Surface acceleration:	1272.58	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.618
   Length of year:		364.64	days
   Length of day:		13.85	hours
   Boiling point of water:	392.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1421
				Cesium       melts at 28    boils at 1471
				Gallium      melts at 30    boils at 4499
				Rubidium     melts at 39    boils at 1441
				Potassium    melts at 63    boils at 1579
				Sodium       melts at 98    boils at 1786
				Indium       melts at 157   boils at 3923
				Lithium      melts at 181   boils at 2616
				Selenium     melts at 217   boils at 1435
				Tin          melts at 232   boils at 4891
				Polonium     melts at 254   boils at 1929
				Bismuth      melts at 271   boils at 3003
				Thallium     melts at 304   boils at 2812
				Cadmium      melts at 321   boils at 1578
				Lead         melts at 328   boils at 3336
				Zinc         melts at 420   boils at 1831
				Tellurium    melts at 450   boils at 1979
   gasses in atmosphere:
				Sulfur            0.6%  PP 2284.3 mb
				Nitrogen          2.5%  PP 9667.3 mb
				Helium           96.9%  PP 370695.5 mb


Planet 4	
   Distance from primary:	1.436	AU
   Mass:			1.689	Earth masses
   Equatorial radius:		7589.0	km
   Density:			5.513	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		1.19	Earth gees
   Surface pressure:		2.144	Earth atmospheres
   Surface temperature:		11.76	degrees Celcius
   Normal daytime temperature:	14.50	degrees Celcius
   Normal night temperature:	8.85	degrees Celcius
   Maximum temperature:   	31.17	degrees Celcius
   Minimum temperature:   	-8.74	degrees Celcius
   Escape Velocity:		13.32	km/sec
   Molecular weight retained:	4.47 and above
   Surface acceleration:	1169.20	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.277
   Length of year:		598.22	days
   Length of day:		14.09	hours
   Boiling point of water:	122.3	degrees Celcius
   Hydrosphere percentage:	63.73
   Cloud cover percentage:	36.83
   Ice cover percentage:	2.44
   liquids at surface:
				Ethanol      melts at -114  boils at 100
				Mercury      melts at -39   boils at 394
				Bromine      melts at -7    boils at 79
				Water        melts at 0     boils at 122
   gasses in atmosphere:
				Oxygen            3.9%  PP   84.0 mb
				Nitrogen         95.9%  PP 2056.8 mb


Planet 5	*gas giant*
   Distance from primary:	2.611	AU
   Mass:			6.184	Earth masses
   Equatorial radius:		19141.2	km
   Density:			1.258	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		16.05	km/sec
   Molecular weight retained:	3.08 and above
   Surface acceleration:	673.12	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.529
   Length of year:		1466.94	days
   Length of day:		15.75	hours


Planet 6	*gas giant*
   Distance from primary:	4.395	AU
   Mass:			648.069	Earth masses
   Equatorial radius:		77638.4	km
   Density:			1.976	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		81.59	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4287.53	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.541
   Length of year:		3200.61	days
   Length of day:		6.24	hours


Planet 7	
   Distance from primary:	6.803	AU
   Mass:			0.901	Earth masses
   Equatorial radius:		8244.2	km
   Density:			2.295	grams/cc
   Eccentricity of orbit:	0.256
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.559	Earth atmospheres
   Surface temperature:		-152.11	degrees Celcius
   Normal daytime temperature:	-148.94	degrees Celcius
   Normal night temperature:	-155.49	degrees Celcius
   Maximum temperature:   	-127.74	degrees Celcius
   Minimum temperature:   	-178.74	degrees Celcius
   Escape Velocity:		9.34	km/sec
   Molecular weight retained:	9.11 and above
   Surface acceleration:	528.73	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.371
   Length of year:		6170.52	days
   Length of day:		20.84	hours
   Boiling point of water:	84.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	39.53
   liquids at surface:
				Ozone        melts at -193  boils at -119
   gasses in atmosphere:
				Oxygen            0.6%  PP    3.4 mb
				Nitrogen         99.4%  PP  554.9 mb


Planet 8	*gas giant*
   Distance from primary:	13.641	AU
   Mass:			699.329	Earth masses
   Equatorial radius:		87239.7	km
   Density:			1.503	grams/cc
   Eccentricity of orbit:	0.085
   Escape Velocity:		79.96	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3664.31	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.513
   Length of year:		17502.77	days
   Length of day:		6.75	hours


Planet 9	*gas giant*
   Distance from primary:	33.376	AU
   Mass:			5.021	Earth masses
   Equatorial radius:		22273.9	km
   Density:			0.648	grams/cc
   Eccentricity of orbit:	0.046
   Escape Velocity:		13.41	km/sec
   Molecular weight retained:	4.42 and above
   Surface acceleration:	403.59	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.477
   Length of year:		67049.89	days
   Length of day:		20.34	hours


Planet 10	
   Distance from primary:	49.298	AU
   Mass:			0.090	Earth masses
   Equatorial radius:		3876.7	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.07	degrees Celcius
   Normal daytime temperature:	-224.32	degrees Celcius
   Normal night temperature:	-235.72	degrees Celcius
   Maximum temperature:   	-213.35	degrees Celcius
   Minimum temperature:   	-247.14	degrees Celcius
   Escape Velocity:		4.31	km/sec
   Molecular weight retained:	42.78 and above
   Surface acceleration:	239.33	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.154
   Length of year:		120362.31	days
   Length of day:		30.98	hours
   Boiling point of water:	-66.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


