                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d1b
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6251 K
Stellar class: F8
Age: 3.931 billion years  (3.229 billion left on main sequence)
Habitable ecosphere radius: 1.234 AU

Planets present at:
1	  0.404 AU	no atmosphere
2	  0.486 AU	no atmosphere
3	  0.640 AU	no atmosphere
4	  0.780 AU	greenhouse
5	  1.162 AU	high pressure
6	  2.237 AU	gas giant
7	  4.705 AU	gas giant
8	  7.942 AU	gas giant
9	 15.248 AU	gas giant
10	 39.461 AU	no atmosphere
11	 34.106 AU	gas giant
12	 46.622 AU	no atmosphere



Planet 1	
   Distance from primary:	0.404	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		1851.1	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		203.19	degrees Celcius
   Maximum temperature:   	413.44	degrees Celcius
   Minimum temperature:   	-203.80	degrees Celcius
   Escape Velocity:		3.17	km/sec
   Molecular weight retained:	78.78 and above
   Surface acceleration:	272.17	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.086
   Length of year:		89.93	days
   Length of day:		2158.22	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.486	AU
   Mass:			0.102	Earth masses
   Equatorial radius:		3017.7	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.112
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		165.42	degrees Celcius
   Maximum temperature:   	367.15	degrees Celcius
   Minimum temperature:   	-210.75	degrees Celcius
   Escape Velocity:		5.19	km/sec
   Molecular weight retained:	29.50 and above
   Surface acceleration:	445.84	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.051
   Length of year:		118.50	days
   Length of day:		2271.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.640	AU
   Mass:			0.160	Earth masses
   Equatorial radius:		3503.9	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		105.68	degrees Celcius
   Maximum temperature:   	293.14	degrees Celcius
   Minimum temperature:   	-224.45	degrees Celcius
   Escape Velocity:		6.03	km/sec
   Molecular weight retained:	21.82 and above
   Surface acceleration:	519.06	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.086
   Length of year:		178.92	days
   Length of day:		4294.10	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.780	AU
   Mass:			0.915	Earth masses
   Equatorial radius:		6220.6	km
   Density:			5.422	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.96	Earth gees
   Surface pressure:		63.326	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		387.86	degrees Celcius
   Maximum temperature:   	393.32	degrees Celcius
   Minimum temperature:   	380.70	degrees Celcius
   Escape Velocity:		10.83	km/sec
   Molecular weight retained:	6.77 and above
   Surface acceleration:	942.65	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.474
   Length of year:		240.91	days
   Length of day:		20.91	hours
   Boiling point of water:	264.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1096
				Cesium       melts at 28    boils at 1137
				Gallium      melts at 30    boils at 3585
				Rubidium     melts at 39    boils at 1112
				Potassium    melts at 63    boils at 1224
				Sodium       melts at 98    boils at 1391
				Sulfur       melts at 113   boils at 762
				Indium       melts at 157   boils at 3119
				Lithium      melts at 181   boils at 2062
				Selenium     melts at 217   boils at 1108
				Tin          melts at 232   boils at 3902
				Polonium     melts at 254   boils at 1507
				Bismuth      melts at 271   boils at 2375
				Thallium     melts at 304   boils at 2221
				Cadmium      melts at 321   boils at 1223
				Lead         melts at 328   boils at 2645
   gasses in atmosphere:
				Nitrogen         99.1%  PP 62729.8 mb
				Phosphorus        0.6%  PP  391.9 mb
				CarbonDioxide     0.1%  PP   44.0 mb
				Ozone             0.1%  PP   40.0 mb
				Ethanol           0.1%  PP   44.7 mb


Planet 5	
   Distance from primary:	1.162	AU
   Mass:			1.600	Earth masses
   Equatorial radius:		7458.2	km
   Density:			5.503	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		1.17	Earth gees
   Surface pressure:		2.601	Earth atmospheres
   Surface temperature:		21.18	degrees Celcius
   Normal daytime temperature:	23.80	degrees Celcius
   Normal night temperature:	18.39	degrees Celcius
   Maximum temperature:   	39.36	degrees Celcius
   Minimum temperature:   	2.00	degrees Celcius
   Escape Velocity:		13.08	km/sec
   Molecular weight retained:	4.64 and above
   Surface acceleration:	1147.05	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.446
   Length of year:		438.21	days
   Length of day:		14.36	hours
   Boiling point of water:	128.3	degrees Celcius
   Hydrosphere percentage:	84.47
   Cloud cover percentage:	90.44
   Ice cover percentage:	0.77
   liquids at surface:
				Ethanol      melts at -114  boils at 105
				Mercury      melts at -39   boils at 405
				Bromine      melts at -7    boils at 85
				Water        melts at 0     boils at 128
   gasses in atmosphere:
				Oxygen            2.7%  PP   71.3 mb
				Nitrogen         97.1%  PP 2525.4 mb


Planet 6	*gas giant*
   Distance from primary:	2.237	AU
   Mass:			14.815	Earth masses
   Equatorial radius:		24436.9	km
   Density:			1.449	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		21.99	km/sec
   Molecular weight retained:	1.64 and above
   Surface acceleration:	989.35	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.472
   Length of year:		1169.91	days
   Length of day:		12.99	hours


Planet 7	*gas giant*
   Distance from primary:	4.705	AU
   Mass:			1076.787	Earth masses
   Equatorial radius:		90755.9	km
   Density:			2.055	grams/cc
   Eccentricity of orbit:	0.097
   Escape Velocity:		97.28	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5213.38	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.512
   Length of year:		3564.08	days
   Length of day:		5.66	hours


Planet 8	*gas giant*
   Distance from primary:	7.942	AU
   Mass:			9.628	Earth masses
   Equatorial radius:		23950.7	km
   Density:			1.000	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		17.91	km/sec
   Molecular weight retained:	2.48 and above
   Surface acceleration:	669.32	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.515
   Length of year:		7828.73	days
   Length of day:		15.80	hours


Planet 9	*gas giant*
   Distance from primary:	15.248	AU
   Mass:			363.087	Earth masses
   Equatorial radius:		72900.3	km
   Density:			1.337	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		63.03	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2724.53	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.524
   Length of year:		20815.00	days
   Length of day:		7.83	hours


Planet 10	
   Distance from primary:	39.461	AU
   Mass:			0.137	Earth masses
   Equatorial radius:		4450.5	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.70	degrees Celcius
   Normal daytime temperature:	-219.73	degrees Celcius
   Normal night temperature:	-231.57	degrees Celcius
   Maximum temperature:   	-204.40	degrees Celcius
   Minimum temperature:   	-247.26	degrees Celcius
   Escape Velocity:		4.95	km/sec
   Molecular weight retained:	32.35 and above
   Surface acceleration:	275.69	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.156
   Length of year:		86703.13	days
   Length of day:		28.86	hours
   Boiling point of water:	-59.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 11	*gas giant*
   Distance from primary:	34.106	AU
   Mass:			3.875	Earth masses
   Equatorial radius:		20738.9	km
   Density:			0.620	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		12.21	km/sec
   Molecular weight retained:	5.33 and above
   Surface acceleration:	359.32	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.541
   Length of year:		69666.05	days
   Length of day:		21.56	hours


Planet 12	
   Distance from primary:	46.622	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		3594.2	km
   Density:			2.206	grams/cc
   Eccentricity of orbit:	0.135
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.34	degrees Celcius
   Normal daytime temperature:	-223.29	degrees Celcius
   Normal night temperature:	-235.28	degrees Celcius
   Maximum temperature:   	-211.66	degrees Celcius
   Minimum temperature:   	-247.31	degrees Celcius
   Escape Velocity:		3.99	km/sec
   Molecular weight retained:	49.84 and above
   Surface acceleration:	221.56	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.143
   Length of year:		111343.96	days
   Length of day:		32.20	hours
   Boiling point of water:	-69.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


