                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b3a
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6325 K
Stellar class: F7
Age: 2.000 billion years  (5.226 billion left on main sequence)
Habitable ecosphere radius: 1.227 AU

Planets present at:
1	  0.407 AU	no atmosphere
2	  0.508 AU	no atmosphere
3	  0.784 AU	no atmosphere
4	  1.001 AU	greenhouse
5	  1.259 AU	no atmosphere
6	  1.616 AU	gas giant
7	  3.138 AU	gas giant
8	  4.728 AU	gas giant
9	  5.882 AU	gas giant
10	 10.951 AU	gas giant
11	 18.621 AU	gas giant
12	 29.803 AU	gas giant
13	 41.618 AU	no atmosphere
14	 44.201 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.407	AU
   Mass:			0.067	Earth masses
   Equatorial radius:		2620.4	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		204.15	degrees Celcius
   Normal daytime temperature:	411.05	degrees Celcius
   Normal night temperature:	-189.47	degrees Celcius
   Maximum temperature:   	414.33	degrees Celcius
   Minimum temperature:   	-200.05	degrees Celcius
   Escape Velocity:		4.50	km/sec
   Molecular weight retained:	39.20 and above
   Surface acceleration:	386.41	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.058
   Length of year:		90.80	days
   Length of day:		1772.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.508	AU
   Mass:			0.401	Earth masses
   Equatorial radius:		4746.7	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		151.65	degrees Celcius
   Maximum temperature:   	350.23	degrees Celcius
   Minimum temperature:   	-215.76	degrees Celcius
   Escape Velocity:		8.21	km/sec
   Molecular weight retained:	11.79 and above
   Surface acceleration:	709.34	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.077
   Length of year:		126.79	days
   Length of day:		3043.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.784	AU
   Mass:			0.114	Earth masses
   Equatorial radius:		3137.4	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.055
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		68.21	degrees Celcius
   Normal daytime temperature:	154.20	degrees Celcius
   Normal night temperature:	-22.90	degrees Celcius
   Maximum temperature:   	180.96	degrees Celcius
   Minimum temperature:   	-52.31	degrees Celcius
   Escape Velocity:		5.39	km/sec
   Molecular weight retained:	27.28 and above
   Surface acceleration:	463.81	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.083
   Length of year:		243.30	days
   Length of day:		72.86	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.001	AU
   Mass:			0.351	Earth masses
   Equatorial radius:		4543.3	km
   Density:			5.338	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.69	Earth gees
   Surface pressure:		12.765	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		63.14	degrees Celcius
   Maximum temperature:   	72.62	degrees Celcius
   Minimum temperature:   	53.16	degrees Celcius
   Escape Velocity:		7.85	km/sec
   Molecular weight retained:	12.89 and above
   Surface acceleration:	677.85	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.603
   Length of year:		350.55	days
   Length of day:		19.66	hours
   Boiling point of water:	186.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 160
				Mercury      melts at -39   boils at 503
				Water        melts at 0     boils at 186
				Francium     melts at 27    boils at 897
				Cesium       melts at 28    boils at 931
				Gallium      melts at 30    boils at 3023
				Rubidium     melts at 39    boils at 910
				Phosphorus   melts at 44    boils at 409
   gasses in atmosphere:
				Nitrogen         99.1%  PP 12653.8 mb
				CarbonDioxide     0.3%  PP   41.9 mb
				Methane           0.1%  PP   10.1 mb
				Ammonia           0.1%  PP   12.5 mb
				Ozone             0.3%  PP   43.2 mb


Planet 5	
   Distance from primary:	1.259	AU
   Mass:			0.104	Earth masses
   Equatorial radius:		3036.3	km
   Density:			5.287	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.010	Earth atmospheres
   Surface temperature:		-23.99	degrees Celcius
   Normal daytime temperature:	-0.14	degrees Celcius
   Normal night temperature:	-48.14	degrees Celcius
   Maximum temperature:   	26.32	degrees Celcius
   Minimum temperature:   	-75.22	degrees Celcius
   Escape Velocity:		5.22	km/sec
   Molecular weight retained:	29.14 and above
   Surface acceleration:	448.63	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.382
   Length of year:		494.61	days
   Length of day:		23.67	hours
   Boiling point of water:	5.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	45.87
   liquids at surface:
				Ethanol      melts at -114  boils at -9
				Mercury      melts at -39   boils at 200
   gasses in atmosphere:
				CarbonDioxide    39.8%  PP    4.0 mb
				Ozone            46.7%  PP    4.7 mb
				Chlorine          9.3%  PP    0.9 mb
				Krypton           3.7%  PP    0.4 mb
				Xenon             0.5%  PP    0.0 mb


Planet 6	*gas giant*
   Distance from primary:	1.616	AU
   Mass:			20.951	Earth masses
   Equatorial radius:		26326.5	km
   Density:			1.638	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		25.19	km/sec
   Molecular weight retained:	1.25 and above
   Surface acceleration:	1205.47	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.497
   Length of year:		719.46	days
   Length of day:		11.77	hours


Planet 7	*gas giant*
   Distance from primary:	3.138	AU
   Mass:			10.538	Earth masses
   Equatorial radius:		22769.8	km
   Density:			1.274	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		19.21	km/sec
   Molecular weight retained:	2.15 and above
   Surface acceleration:	810.54	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.524
   Length of year:		1946.58	days
   Length of day:		14.36	hours


Planet 8	*gas giant*
   Distance from primary:	4.728	AU
   Mass:			1.317	Earth masses
   Equatorial radius:		12845.1	km
   Density:			0.886	grams/cc
   Eccentricity of orbit:	0.086
   Escape Velocity:		9.04	km/sec
   Molecular weight retained:	9.71 and above
   Surface acceleration:	318.21	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.453
   Length of year:		3600.73	days
   Length of day:		22.91	hours


Planet 9	*gas giant*
   Distance from primary:	5.882	AU
   Mass:			87.069	Earth masses
   Equatorial radius:		44420.9	km
   Density:			1.417	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		39.54	km/sec
   Molecular weight retained:	0.51 and above
   Surface acceleration:	1759.66	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.530
   Length of year:		4994.55	days
   Length of day:		9.74	hours


Planet 10	*gas giant*
   Distance from primary:	10.951	AU
   Mass:			923.062	Earth masses
   Equatorial radius:		93143.0	km
   Density:			1.630	grams/cc
   Eccentricity of orbit:	0.071
   Escape Velocity:		88.90	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4242.97	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.464
   Length of year:		12675.00	days
   Length of day:		6.27	hours


Planet 11	*gas giant*
   Distance from primary:	18.621	AU
   Mass:			99.793	Earth masses
   Equatorial radius:		50883.1	km
   Density:			1.081	grams/cc
   Eccentricity of orbit:	0.120
   Escape Velocity:		39.55	km/sec
   Molecular weight retained:	0.51 and above
   Surface acceleration:	1537.07	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.507
   Length of year:		28134.88	days
   Length of day:		10.42	hours


Planet 12	*gas giant*
   Distance from primary:	29.803	AU
   Mass:			1.422	Earth masses
   Equatorial radius:		15316.7	km
   Density:			0.565	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		8.61	km/sec
   Molecular weight retained:	10.72 and above
   Surface acceleration:	241.80	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.516
   Length of year:		56976.10	days
   Length of day:		26.28	hours


Planet 13	
   Distance from primary:	41.618	AU
   Mass:			0.288	Earth masses
   Equatorial radius:		5688.0	km
   Density:			2.236	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.20	degrees Celcius
   Normal daytime temperature:	-220.94	degrees Celcius
   Normal night temperature:	-231.39	degrees Celcius
   Maximum temperature:   	-204.79	degrees Celcius
   Minimum temperature:   	-247.92	degrees Celcius
   Escape Velocity:		6.36	km/sec
   Molecular weight retained:	19.63 and above
   Surface acceleration:	355.51	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.137
   Length of year:		94022.08	days
   Length of day:		25.42	hours
   Boiling point of water:	-45.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 14	
   Distance from primary:	44.201	AU
   Mass:			0.142	Earth masses
   Equatorial radius:		4506.2	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.25	degrees Celcius
   Normal daytime temperature:	-222.64	degrees Celcius
   Normal night temperature:	-233.76	degrees Celcius
   Maximum temperature:   	-208.99	degrees Celcius
   Minimum temperature:   	-247.81	degrees Celcius
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.54 and above
   Surface acceleration:	279.24	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.142
   Length of year:		102908.61	days
   Length of day:		28.68	hours
   Boiling point of water:	-58.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


