                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048052
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6200 K
Stellar class: F8
Age: 4.381 billion years  (2.668 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.353 AU	no atmosphere
2	  0.463 AU	no atmosphere
3	  0.592 AU	no atmosphere
4	  0.950 AU	greenhouse
5	  1.675 AU	gas giant
6	  3.099 AU	gas giant
7	  4.752 AU	gas giant
8	  7.923 AU	gas giant
9	 19.354 AU	gas giant
10	 26.822 AU	gas giant
11	 40.517 AU	no atmosphere
12	 50.256 AU	no atmosphere



Planet 1	
   Distance from primary:	0.353	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		1878.4	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		239.76	degrees Celcius
   Normal daytime temperature:	454.71	degrees Celcius
   Normal night temperature:	-183.61	degrees Celcius
   Maximum temperature:   	457.81	degrees Celcius
   Minimum temperature:   	-194.14	degrees Celcius
   Escape Velocity:		3.22	km/sec
   Molecular weight retained:	76.50 and above
   Surface acceleration:	276.22	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.083
   Length of year:		73.16	days
   Length of day:		1755.76	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.463	AU
   Mass:			0.323	Earth masses
   Equatorial radius:		4421.2	km
   Density:			5.334	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		177.67	degrees Celcius
   Maximum temperature:   	382.31	degrees Celcius
   Minimum temperature:   	-210.54	degrees Celcius
   Escape Velocity:		7.63	km/sec
   Molecular weight retained:	13.62 and above
   Surface acceleration:	659.02	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.057
   Length of year:		109.98	days
   Length of day:		2639.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.592	AU
   Mass:			0.092	Earth masses
   Equatorial radius:		2920.3	km
   Density:			5.284	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		124.09	degrees Celcius
   Maximum temperature:   	316.09	degrees Celcius
   Minimum temperature:   	-221.56	degrees Celcius
   Escape Velocity:		5.02	km/sec
   Molecular weight retained:	31.52 and above
   Surface acceleration:	431.24	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.071
   Length of year:		159.01	days
   Length of day:		3816.36	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.950	AU
   Mass:			0.740	Earth masses
   Equatorial radius:		5805.4	km
   Density:			5.399	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.89	Earth gees
   Surface pressure:		56.590	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		315.22	degrees Celcius
   Maximum temperature:   	321.03	degrees Celcius
   Minimum temperature:   	308.29	degrees Celcius
   Escape Velocity:		10.08	km/sec
   Molecular weight retained:	7.81 and above
   Surface acceleration:	875.93	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.489
   Length of year:		323.35	days
   Length of day:		18.07	hours
   Boiling point of water:	258.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 624
				Francium     melts at 27    boils at 1080
				Cesium       melts at 28    boils at 1120
				Gallium      melts at 30    boils at 3539
				Rubidium     melts at 39    boils at 1096
				Potassium    melts at 63    boils at 1207
				Sodium       melts at 98    boils at 1372
				Sulfur       melts at 113   boils at 750
				Indium       melts at 157   boils at 3079
				Lithium      melts at 181   boils at 2035
				Selenium     melts at 217   boils at 1092
				Tin          melts at 232   boils at 3853
				Polonium     melts at 254   boils at 1486
				Bismuth      melts at 271   boils at 2344
				Astatine     melts at 302   boils at 596
				Thallium     melts at 304   boils at 2191
   gasses in atmosphere:
				Nitrogen         99.0%  PP 55997.5 mb
				Phosphorus        0.7%  PP  391.1 mb
				CarbonDioxide     0.1%  PP   44.6 mb
				Ozone             0.1%  PP   40.7 mb
				Ethanol           0.1%  PP   45.4 mb


Planet 5	*gas giant*
   Distance from primary:	1.675	AU
   Mass:			12.717	Earth masses
   Equatorial radius:		22796.9	km
   Density:			1.532	grams/cc
   Eccentricity of orbit:	0.189
   Escape Velocity:		21.09	km/sec
   Molecular weight retained:	1.78 and above
   Surface acceleration:	975.81	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.460
   Length of year:		756.59	days
   Length of day:		13.09	hours


Planet 6	*gas giant*
   Distance from primary:	3.099	AU
   Mass:			3.567	Earth masses
   Equatorial radius:		16562.2	km
   Density:			1.120	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		13.11	km/sec
   Molecular weight retained:	4.62 and above
   Surface acceleration:	518.53	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.527
   Length of year:		1904.55	days
   Length of day:		17.95	hours


Planet 7	*gas giant*
   Distance from primary:	4.752	AU
   Mass:			723.284	Earth masses
   Equatorial radius:		80811.5	km
   Density:			1.956	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		84.49	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4416.73	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.526
   Length of year:		3612.47	days
   Length of day:		6.15	hours


Planet 8	*gas giant*
   Distance from primary:	7.923	AU
   Mass:			350.899	Earth masses
   Equatorial radius:		68288.9	km
   Density:			1.572	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		64.02	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3000.69	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.505
   Length of year:		7779.89	days
   Length of day:		7.46	hours


Planet 9	*gas giant*
   Distance from primary:	19.354	AU
   Mass:			3.294	Earth masses
   Equatorial radius:		18851.0	km
   Density:			0.702	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		11.81	km/sec
   Molecular weight retained:	5.70 and above
   Surface acceleration:	369.65	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.484
   Length of year:		29719.96	days
   Length of day:		21.26	hours


Planet 10	*gas giant*
   Distance from primary:	26.822	AU
   Mass:			41.392	Earth masses
   Equatorial radius:		40526.8	km
   Density:			0.887	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		28.54	km/sec
   Molecular weight retained:	0.97 and above
   Surface acceleration:	1005.02	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.470
   Length of year:		48483.00	days
   Length of day:		12.89	hours


Planet 11	
   Distance from primary:	40.517	AU
   Mass:			0.550	Earth masses
   Equatorial radius:		7026.0	km
   Density:			2.264	grams/cc
   Eccentricity of orbit:	0.142
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-225.24	degrees Celcius
   Normal daytime temperature:	-220.40	degrees Celcius
   Normal night temperature:	-230.01	degrees Celcius
   Maximum temperature:   	-204.74	degrees Celcius
   Minimum temperature:   	-246.28	degrees Celcius
   Escape Velocity:		7.90	km/sec
   Molecular weight retained:	12.71 and above
   Surface acceleration:	444.53	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.160
   Length of year:		90021.25	days
   Length of day:		22.73	hours
   Boiling point of water:	-29.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.12
   gasses in atmosphere:
				Neon             100.0%  PP    0.7 mb


Planet 12	
   Distance from primary:	50.256	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		2330.7	km
   Density:			2.194	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.80	degrees Celcius
   Normal daytime temperature:	-223.75	degrees Celcius
   Normal night temperature:	-237.69	degrees Celcius
   Maximum temperature:   	-210.57	degrees Celcius
   Minimum temperature:   	-250.79	degrees Celcius
   Escape Velocity:		2.58	km/sec
   Molecular weight retained:	119.16 and above
   Surface acceleration:	142.92	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.146
   Length of year:		124354.59	days
   Length of day:		40.09	hours
   Boiling point of water:	-88.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


