                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048771
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6323 K
Stellar class: F7
Age: 1.409 billion years  (5.401 billion left on main sequence)
Habitable ecosphere radius: 1.274 AU

Planets present at:
1	  0.329 AU	no atmosphere
2	  0.641 AU	greenhouse
3	  0.814 AU	no atmosphere
4	  1.288 AU	no atmosphere
5	  1.464 AU	gas giant
6	  1.672 AU	no atmosphere
7	  3.551 AU	gas giant
8	  7.201 AU	gas giant
9	 16.825 AU	gas giant
10	 26.232 AU	gas giant
11	 50.519 AU	no atmosphere
12	 50.976 AU	no atmosphere



Planet 1	
   Distance from primary:	0.329	AU
   Mass:			0.174	Earth masses
   Equatorial radius:		3603.5	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		262.88	degrees Celcius
   Normal daytime temperature:	482.56	degrees Celcius
   Normal night temperature:	-176.67	degrees Celcius
   Maximum temperature:   	485.79	degrees Celcius
   Minimum temperature:   	-188.11	degrees Celcius
   Escape Velocity:		6.20	km/sec
   Molecular weight retained:	20.62 and above
   Surface acceleration:	534.15	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.087
   Length of year:		65.71	days
   Length of day:		1577.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.641	AU
   Mass:			1.133	Earth masses
   Equatorial radius:		6669.7	km
   Density:			5.450	grams/cc
   Eccentricity of orbit:	0.192
   Surface gravity:		1.04	Earth gees
   Surface pressure:		109.982	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		595.29	degrees Celcius
   Maximum temperature:   	599.16	degrees Celcius
   Minimum temperature:   	587.52	degrees Celcius
   Escape Velocity:		11.64	km/sec
   Molecular weight retained:	5.86 and above
   Surface acceleration:	1015.80	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.431
   Length of year:		178.12	days
   Length of day:		20.18	hours
   Boiling point of water:	298.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1182
				Cesium       melts at 28    boils at 1225
				Gallium      melts at 30    boils at 3826
				Rubidium     melts at 39    boils at 1199
				Potassium    melts at 63    boils at 1318
				Sodium       melts at 98    boils at 1495
				Indium       melts at 157   boils at 3331
				Lithium      melts at 181   boils at 2208
				Selenium     melts at 217   boils at 1194
				Tin          melts at 232   boils at 4163
				Polonium     melts at 254   boils at 1619
				Bismuth      melts at 271   boils at 2541
				Thallium     melts at 304   boils at 2377
				Cadmium      melts at 321   boils at 1317
				Lead         melts at 328   boils at 2827
				Zinc         melts at 420   boils at 1534
				Tellurium    melts at 450   boils at 1661
   gasses in atmosphere:
				Sulfur           20.1%  PP 22082.1 mb
				Nitrogen         79.3%  PP 87223.3 mb
				Phosphorus        0.4%  PP  440.8 mb


Planet 3	
   Distance from primary:	0.814	AU
   Mass:			0.038	Earth masses
   Equatorial radius:		2167.2	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		69.47	degrees Celcius
   Maximum temperature:   	247.52	degrees Celcius
   Minimum temperature:   	-228.81	degrees Celcius
   Escape Velocity:		3.72	km/sec
   Molecular weight retained:	57.41 and above
   Surface acceleration:	319.00	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.071
   Length of year:		254.95	days
   Length of day:		6118.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.288	AU
   Mass:			0.065	Earth masses
   Equatorial radius:		2598.8	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		0.60	degrees Celcius
   Normal daytime temperature:	31.39	degrees Celcius
   Normal night temperature:	-30.38	degrees Celcius
   Maximum temperature:   	59.60	degrees Celcius
   Minimum temperature:   	-59.07	degrees Celcius
   Escape Velocity:		4.46	km/sec
   Molecular weight retained:	39.86 and above
   Surface acceleration:	383.20	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.052
   Length of year:		507.80	days
   Length of day:		25.54	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	*gas giant*
   Distance from primary:	1.464	AU
   Mass:			6.483	Earth masses
   Equatorial radius:		18487.3	km
   Density:			1.464	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		16.72	km/sec
   Molecular weight retained:	2.84 and above
   Surface acceleration:	756.38	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.545
   Length of year:		615.66	days
   Length of day:		14.86	hours


Planet 6	
   Distance from primary:	1.672	AU
   Mass:			0.107	Earth masses
   Equatorial radius:		3064.6	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.011	Earth atmospheres
   Surface temperature:		-57.35	degrees Celcius
   Normal daytime temperature:	-37.69	degrees Celcius
   Normal night temperature:	-77.24	degrees Celcius
   Maximum temperature:   	-12.12	degrees Celcius
   Minimum temperature:   	-103.57	degrees Celcius
   Escape Velocity:		5.27	km/sec
   Molecular weight retained:	28.60 and above
   Surface acceleration:	452.87	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.432
   Length of year:		751.43	days
   Length of day:		22.65	hours
   Boiling point of water:	7.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	49.66
   liquids at surface:
				Ethanol      melts at -114  boils at -8
   gasses in atmosphere:
				CarbonDioxide    44.2%  PP    5.1 mb
				Ozone            51.3%  PP    5.9 mb
				Krypton           3.9%  PP    0.4 mb
				Xenon             0.5%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	3.551	AU
   Mass:			25.097	Earth masses
   Equatorial radius:		29539.1	km
   Density:			1.389	grams/cc
   Eccentricity of orbit:	0.211
   Escape Velocity:		26.03	km/sec
   Molecular weight retained:	1.17 and above
   Surface acceleration:	1147.01	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.489
   Length of year:		2324.93	days
   Length of day:		12.07	hours


Planet 8	*gas giant*
   Distance from primary:	7.201	AU
   Mass:			1134.134	Earth masses
   Equatorial radius:		95215.2	km
   Density:			1.875	grams/cc
   Eccentricity of orbit:	0.205
   Escape Velocity:		97.47	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4988.75	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.465
   Length of year:		6704.29	days
   Length of day:		5.79	hours


Planet 9	*gas giant*
   Distance from primary:	16.825	AU
   Mass:			247.753	Earth masses
   Equatorial radius:		65573.7	km
   Density:			1.254	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		54.89	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2297.73	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.543
   Length of year:		23971.12	days
   Length of day:		8.53	hours


Planet 10	*gas giant*
   Distance from primary:	26.232	AU
   Mass:			12.634	Earth masses
   Equatorial radius:		28565.1	km
   Density:			0.773	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		18.78	km/sec
   Molecular weight retained:	2.25 and above
   Surface acceleration:	617.48	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.544
   Length of year:		46682.26	days
   Length of day:		16.45	hours


Planet 11	
   Distance from primary:	50.519	AU
   Mass:			0.068	Earth masses
   Equatorial radius:		3536.1	km
   Density:			2.205	grams/cc
   Eccentricity of orbit:	0.160
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.57	degrees Celcius
   Normal daytime temperature:	-224.64	degrees Celcius
   Normal night temperature:	-236.37	degrees Celcius
   Maximum temperature:   	-207.46	degrees Celcius
   Minimum temperature:   	-253.06	degrees Celcius
   Escape Velocity:		3.93	km/sec
   Molecular weight retained:	51.51 and above
   Surface acceleration:	217.92	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.157
   Length of year:		124767.56	days
   Length of day:		32.47	hours
   Boiling point of water:	-71.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


Planet 12	
   Distance from primary:	50.976	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		4574.6	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.51	degrees Celcius
   Normal daytime temperature:	-225.22	degrees Celcius
   Normal night temperature:	-235.69	degrees Celcius
   Maximum temperature:   	-210.03	degrees Celcius
   Minimum temperature:   	-250.96	degrees Celcius
   Escape Velocity:		5.09	km/sec
   Molecular weight retained:	30.59 and above
   Surface acceleration:	283.60	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.139
   Length of year:		126461.25	days
   Length of day:		28.46	hours
   Boiling point of water:	-57.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


