                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c0e
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6055 K
Stellar class: F9
Age: 4.245 billion years  (2.953 billion left on main sequence)
Habitable ecosphere radius: 1.230 AU

Planets present at:
1	  0.365 AU	no atmosphere
2	  0.457 AU	no atmosphere
3	  0.666 AU	no atmosphere
4	  0.841 AU	greenhouse
5	  1.377 AU	
6	  2.357 AU	gas giant
7	  3.791 AU	gas giant
8	  5.221 AU	gas giant
9	  8.479 AU	gas giant
10	 15.900 AU	gas giant
11	 20.587 AU	gas giant
12	 36.152 AU	no atmosphere
13	 51.292 AU	gas giant



Planet 1	
   Distance from primary:	0.365	AU
   Mass:			0.185	Earth masses
   Equatorial radius:		3678.4	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.72	degrees Celcius
   Normal daytime temperature:	442.58	degrees Celcius
   Normal night temperature:	-186.63	degrees Celcius
   Maximum temperature:   	445.65	degrees Celcius
   Minimum temperature:   	-196.84	degrees Celcius
   Escape Velocity:		6.33	km/sec
   Molecular weight retained:	19.78 and above
   Surface acceleration:	545.50	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.069
   Length of year:		77.21	days
   Length of day:		1852.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.457	AU
   Mass:			0.108	Earth masses
   Equatorial radius:		3074.0	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		176.15	degrees Celcius
   Maximum temperature:   	380.28	degrees Celcius
   Minimum temperature:   	-210.09	degrees Celcius
   Escape Velocity:		5.28	km/sec
   Molecular weight retained:	28.42 and above
   Surface acceleration:	454.29	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.072
   Length of year:		107.99	days
   Length of day:		2591.84	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.666	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		2573.9	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		98.30	degrees Celcius
   Maximum temperature:   	283.87	degrees Celcius
   Minimum temperature:   	-225.34	degrees Celcius
   Escape Velocity:		4.42	km/sec
   Molecular weight retained:	40.64 and above
   Surface acceleration:	379.47	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.078
   Length of year:		190.14	days
   Length of day:		4563.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.841	AU
   Mass:			0.992	Earth masses
   Equatorial radius:		6386.3	km
   Density:			5.432	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.99	Earth gees
   Surface pressure:		89.549	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		383.19	degrees Celcius
   Maximum temperature:   	387.73	degrees Celcius
   Minimum temperature:   	377.10	degrees Celcius
   Escape Velocity:		11.13	km/sec
   Molecular weight retained:	6.41 and above
   Surface acceleration:	969.52	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.612
   Length of year:		269.87	days
   Length of day:		18.38	hours
   Boiling point of water:	285.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1149
				Cesium       melts at 28    boils at 1191
				Gallium      melts at 30    boils at 3733
				Rubidium     melts at 39    boils at 1165
				Potassium    melts at 63    boils at 1282
				Sodium       melts at 98    boils at 1455
				Sulfur       melts at 113   boils at 801
				Indium       melts at 157   boils at 3249
				Lithium      melts at 181   boils at 2152
				Selenium     melts at 217   boils at 1161
				Tin          melts at 232   boils at 4062
				Polonium     melts at 254   boils at 1576
				Bismuth      melts at 271   boils at 2477
				Thallium     melts at 304   boils at 2317
				Cadmium      melts at 321   boils at 1281
				Lead         melts at 328   boils at 2757
   gasses in atmosphere:
				Nitrogen         99.1%  PP 88741.3 mb
				Phosphorus        0.6%  PP  534.5 mb
				CarbonDioxide     0.1%  PP   59.6 mb
				Ozone             0.1%  PP   50.8 mb
				Ethanol           0.1%  PP   60.6 mb


Planet 5	
   Distance from primary:	1.377	AU
   Mass:			1.235	Earth masses
   Equatorial radius:		6858.6	km
   Density:			5.462	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		1.07	Earth gees
   Surface pressure:		1.587	Earth atmospheres
   Surface temperature:		10.64	degrees Celcius
   Normal daytime temperature:	13.97	degrees Celcius
   Normal night temperature:	7.09	degrees Celcius
   Maximum temperature:   	32.46	degrees Celcius
   Minimum temperature:   	-12.44	degrees Celcius
   Escape Velocity:		11.98	km/sec
   Molecular weight retained:	5.53 and above
   Surface acceleration:	1046.91	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.272
   Length of year:		565.65	days
   Length of day:		14.92	hours
   Boiling point of water:	113.2	degrees Celcius
   Hydrosphere percentage:	78.98
   Cloud cover percentage:	39.88
   Ice cover percentage:	3.05
   liquids at surface:
				Ethanol      melts at -114  boils at 91
				Mercury      melts at -39   boils at 379
				Bromine      melts at -7    boils at 71
				Water        melts at 0     boils at 113
   gasses in atmosphere:
				Oxygen           10.0%  PP  159.3 mb
				Nitrogen         89.8%  PP 1425.5 mb
				Ozone             0.1%  PP    0.8 mb


Planet 6	*gas giant*
   Distance from primary:	2.357	AU
   Mass:			18.671	Earth masses
   Equatorial radius:		26263.7	km
   Density:			1.471	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		23.81	km/sec
   Molecular weight retained:	1.40 and above
   Surface acceleration:	1079.41	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.527
   Length of year:		1266.23	days
   Length of day:		12.44	hours


Planet 7	*gas giant*
   Distance from primary:	3.791	AU
   Mass:			7.806	Earth masses
   Equatorial radius:		21188.0	km
   Density:			1.171	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		17.14	km/sec
   Molecular weight retained:	2.70 and above
   Surface acceleration:	693.38	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.509
   Length of year:		2583.21	days
   Length of day:		15.52	hours


Planet 8	*gas giant*
   Distance from primary:	5.221	AU
   Mass:			26.441	Earth masses
   Equatorial radius:		31061.3	km
   Density:			1.259	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		26.06	km/sec
   Molecular weight retained:	1.17 and above
   Surface acceleration:	1092.91	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.494
   Length of year:		4174.87	days
   Length of day:		12.36	hours


Planet 9	*gas giant*
   Distance from primary:	8.479	AU
   Mass:			655.058	Earth masses
   Equatorial radius:		82480.8	km
   Density:			1.666	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		79.59	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3839.84	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.460
   Length of year:		8633.55	days
   Length of day:		6.60	hours


Planet 10	*gas giant*
   Distance from primary:	15.900	AU
   Mass:			0.590	Earth masses
   Equatorial radius:		11244.7	km
   Density:			0.593	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		6.47	km/sec
   Molecular weight retained:	18.96 and above
   Surface acceleration:	186.21	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.477
   Length of year:		22190.03	days
   Length of day:		29.95	hours


Planet 11	*gas giant*
   Distance from primary:	20.587	AU
   Mass:			134.941	Earth masses
   Equatorial radius:		56018.8	km
   Density:			1.095	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		43.83	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1714.80	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.544
   Length of year:		32687.29	days
   Length of day:		9.87	hours


Planet 12	
   Distance from primary:	36.152	AU
   Mass:			0.015	Earth masses
   Equatorial radius:		2119.0	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-223.57	degrees Celcius
   Normal daytime temperature:	-214.99	degrees Celcius
   Normal night temperature:	-232.04	degrees Celcius
   Maximum temperature:   	-202.40	degrees Celcius
   Minimum temperature:   	-244.83	degrees Celcius
   Escape Velocity:		2.35	km/sec
   Molecular weight retained:	144.25 and above
   Surface acceleration:	129.85	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.147
   Length of year:		76080.38	days
   Length of day:		42.06	hours
   Boiling point of water:	-93.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


Planet 13	*gas giant*
   Distance from primary:	51.292	AU
   Mass:			0.250	Earth masses
   Equatorial radius:		9652.6	km
   Density:			0.397	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		4.55	km/sec
   Molecular weight retained:	38.38 and above
   Surface acceleration:	107.14	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.530
   Length of year:		128572.13	days
   Length of day:		39.49	hours


