                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048878
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6148 K
Stellar class: F9
Age: 4.434 billion years  (2.343 billion left on main sequence)
Habitable ecosphere radius: 1.278 AU

Planets present at:
1	  0.339 AU	no atmosphere
2	  0.626 AU	no atmosphere
3	  1.015 AU	greenhouse
4	  1.464 AU	cold
5	  2.228 AU	gas giant
6	  3.347 AU	gas giant
7	  4.533 AU	gas giant
8	  8.493 AU	gas giant
9	 13.135 AU	gas giant
10	 22.887 AU	gas giant
11	 37.039 AU	gas giant



Planet 1	
   Distance from primary:	0.339	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		3412.1	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		256.61	degrees Celcius
   Normal daytime temperature:	475.08	degrees Celcius
   Normal night temperature:	-179.08	degrees Celcius
   Maximum temperature:   	478.13	degrees Celcius
   Minimum temperature:   	-189.70	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.03 and above
   Surface acceleration:	505.19	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.081
   Length of year:		68.68	days
   Length of day:		1648.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.626	AU
   Mass:			0.518	Earth masses
   Equatorial radius:		5162.9	km
   Density:			5.366	grams/cc
   Eccentricity of orbit:	0.118
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		119.27	degrees Celcius
   Maximum temperature:   	310.09	degrees Celcius
   Minimum temperature:   	-221.29	degrees Celcius
   Escape Velocity:		8.94	km/sec
   Molecular weight retained:	9.93 and above
   Surface acceleration:	774.27	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.059
   Length of year:		171.95	days
   Length of day:		3256.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.015	AU
   Mass:			1.853	Earth masses
   Equatorial radius:		7819.1	km
   Density:			5.530	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		1.23	Earth gees
   Surface pressure:		337.560	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		511.20	degrees Celcius
   Maximum temperature:   	513.39	degrees Celcius
   Minimum temperature:   	506.51	degrees Celcius
   Escape Velocity:		13.75	km/sec
   Molecular weight retained:	4.20 and above
   Surface acceleration:	1208.43	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.539
   Length of year:		355.21	days
   Length of day:		14.27	hours
   Boiling point of water:	381.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1393
				Cesium       melts at 28    boils at 1443
				Gallium      melts at 30    boils at 4421
				Rubidium     melts at 39    boils at 1413
				Potassium    melts at 63    boils at 1549
				Sodium       melts at 98    boils at 1752
				Indium       melts at 157   boils at 3855
				Lithium      melts at 181   boils at 2569
				Selenium     melts at 217   boils at 1407
				Tin          melts at 232   boils at 4807
				Polonium     melts at 254   boils at 1893
				Bismuth      melts at 271   boils at 2949
				Thallium     melts at 304   boils at 2762
				Cadmium      melts at 321   boils at 1548
				Lead         melts at 328   boils at 3277
				Zinc         melts at 420   boils at 1797
				Tellurium    melts at 450   boils at 1942
   gasses in atmosphere:
				Sulfur           19.3%  PP 65200.3 mb
				Nitrogen         80.1%  PP 270460.9 mb
				Phosphorus        0.4%  PP 1301.5 mb


Planet 4	
   Distance from primary:	1.464	AU
   Mass:			0.375	Earth masses
   Equatorial radius:		4644.6	km
   Density:			5.343	grams/cc
   Eccentricity of orbit:	0.144
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.129	Earth atmospheres
   Surface temperature:		-45.02	degrees Celcius
   Normal daytime temperature:	-35.03	degrees Celcius
   Normal night temperature:	-55.42	degrees Celcius
   Maximum temperature:   	-7.38	degrees Celcius
   Minimum temperature:   	-84.58	degrees Celcius
   Escape Velocity:		8.03	km/sec
   Molecular weight retained:	12.32 and above
   Surface acceleration:	693.52	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.559
   Length of year:		614.94	days
   Length of day:		18.46	hours
   Boiling point of water:	50.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.47
   Ice cover percentage:	68.95
   liquids at surface:
				Ethanol      melts at -114  boils at 32
   gasses in atmosphere:
				Oxygen           15.5%  PP   19.9 mb
				Nitrogen         84.0%  PP  108.2 mb
				CarbonDioxide     0.2%  PP    0.3 mb
				Methane           0.1%  PP    0.1 mb
				Ozone             0.2%  PP    0.3 mb


Planet 5	*gas giant*
   Distance from primary:	2.228	AU
   Mass:			10.502	Earth masses
   Equatorial radius:		22032.5	km
   Density:			1.401	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		19.50	km/sec
   Molecular weight retained:	2.09 and above
   Surface acceleration:	862.76	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.548
   Length of year:		1154.74	days
   Length of day:		13.92	hours


Planet 6	*gas giant*
   Distance from primary:	3.347	AU
   Mass:			2.629	Earth masses
   Equatorial radius:		15218.5	km
   Density:			1.064	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		11.74	km/sec
   Molecular weight retained:	5.76 and above
   Surface acceleration:	452.72	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.490
   Length of year:		2126.35	days
   Length of day:		19.21	hours


Planet 7	*gas giant*
   Distance from primary:	4.533	AU
   Mass:			39.727	Earth masses
   Equatorial radius:		34458.6	km
   Density:			1.385	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		30.32	km/sec
   Molecular weight retained:	0.86 and above
   Surface acceleration:	1334.22	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.543
   Length of year:		3351.09	days
   Length of day:		11.19	hours


Planet 8	*gas giant*
   Distance from primary:	8.493	AU
   Mass:			1358.319	Earth masses
   Equatorial radius:		101721.2	km
   Density:			1.841	grams/cc
   Eccentricity of orbit:	0.092
   Escape Velocity:		103.20	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5235.02	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.485
   Length of year:		8578.26	days
   Length of day:		5.65	hours


Planet 9	*gas giant*
   Distance from primary:	13.135	AU
   Mass:			3.951	Earth masses
   Equatorial radius:		19205.8	km
   Density:			0.796	grams/cc
   Eccentricity of orbit:	0.002
   Escape Velocity:		12.81	km/sec
   Molecular weight retained:	4.84 and above
   Surface acceleration:	427.13	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.465
   Length of year:		16529.22	days
   Length of day:		19.78	hours


Planet 10	*gas giant*
   Distance from primary:	22.887	AU
   Mass:			9.749	Earth masses
   Equatorial radius:		26178.1	km
   Density:			0.775	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		17.23	km/sec
   Molecular weight retained:	2.67 and above
   Surface acceleration:	567.29	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.536
   Length of year:		38018.67	days
   Length of day:		17.16	hours


Planet 11	*gas giant*
   Distance from primary:	37.039	AU
   Mass:			7.184	Earth masses
   Equatorial radius:		24928.1	km
   Density:			0.662	grams/cc
   Eccentricity of orbit:	0.111
   Escape Velocity:		15.16	km/sec
   Molecular weight retained:	3.45 and above
   Surface acceleration:	461.01	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.541
   Length of year:		78273.92	days
   Length of day:		19.04	hours


