                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e34
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6274 K
Stellar class: F8
Age: 1.164 billion years  (5.958 billion left on main sequence)
Habitable ecosphere radius: 1.238 AU

Planets present at:
1	  0.355 AU	no atmosphere
2	  0.470 AU	no atmosphere
3	  0.562 AU	no atmosphere
4	  0.654 AU	greenhouse
5	  1.131 AU	greenhouse
6	  1.700 AU	no atmosphere
7	  2.483 AU	gas giant
8	  4.945 AU	gas giant
9	  8.710 AU	gas giant
10	 17.039 AU	gas giant
11	 48.568 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.355	AU
   Mass:			0.079	Earth masses
   Equatorial radius:		2768.8	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.102
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		239.50	degrees Celcius
   Normal daytime temperature:	453.72	degrees Celcius
   Normal night temperature:	-177.71	degrees Celcius
   Maximum temperature:   	457.19	degrees Celcius
   Minimum temperature:   	-189.75	degrees Celcius
   Escape Velocity:		4.76	km/sec
   Molecular weight retained:	35.09 and above
   Surface acceleration:	408.56	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.059
   Length of year:		74.04	days
   Length of day:		1446.74	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.470	AU
   Mass:			1/115.1	Earth masses
   Equatorial radius:		1331.3	km
   Density:			5.254	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		169.75	degrees Celcius
   Maximum temperature:   	372.42	degrees Celcius
   Minimum temperature:   	-211.51	degrees Celcius
   Escape Velocity:		2.28	km/sec
   Molecular weight retained:	152.51 and above
   Surface acceleration:	195.48	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.085
   Length of year:		112.46	days
   Length of day:		2699.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.562	AU
   Mass:			0.054	Earth masses
   Equatorial radius:		2437.7	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.139
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		132.00	degrees Celcius
   Maximum temperature:   	325.89	degrees Celcius
   Minimum temperature:   	-217.77	degrees Celcius
   Escape Velocity:		4.18	km/sec
   Molecular weight retained:	45.33 and above
   Surface acceleration:	359.18	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.082
   Length of year:		147.31	days
   Length of day:		2671.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.654	AU
   Mass:			0.897	Earth masses
   Equatorial radius:		6181.6	km
   Density:			5.420	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.95	Earth gees
   Surface pressure:		84.014	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		472.06	degrees Celcius
   Maximum temperature:   	476.87	degrees Celcius
   Minimum temperature:   	464.82	degrees Celcius
   Escape Velocity:		10.76	km/sec
   Molecular weight retained:	6.86 and above
   Surface acceleration:	936.35	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.600
   Length of year:		185.06	days
   Length of day:		20.05	hours
   Boiling point of water:	281.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1139
				Cesium       melts at 28    boils at 1181
				Gallium      melts at 30    boils at 3705
				Rubidium     melts at 39    boils at 1155
				Potassium    melts at 63    boils at 1271
				Sodium       melts at 98    boils at 1443
				Indium       melts at 157   boils at 3224
				Lithium      melts at 181   boils at 2135
				Selenium     melts at 217   boils at 1151
				Tin          melts at 232   boils at 4032
				Polonium     melts at 254   boils at 1563
				Bismuth      melts at 271   boils at 2457
				Thallium     melts at 304   boils at 2298
				Cadmium      melts at 321   boils at 1270
				Lead         melts at 328   boils at 2735
				Zinc         melts at 420   boils at 1481
				Tellurium    melts at 450   boils at 1604
   gasses in atmosphere:
				Sulfur           21.4%  PP 17946.7 mb
				Nitrogen         78.0%  PP 65518.6 mb
				Phosphorus        0.4%  PP  357.8 mb


Planet 5	
   Distance from primary:	1.131	AU
   Mass:			1.065	Earth masses
   Equatorial radius:		6537.6	km
   Density:			5.441	grams/cc
   Eccentricity of orbit:	0.166
   Surface gravity:		1.01	Earth gees
   Surface pressure:		102.256	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		364.61	degrees Celcius
   Maximum temperature:   	369.04	degrees Celcius
   Minimum temperature:   	358.87	degrees Celcius
   Escape Velocity:		11.40	km/sec
   Molecular weight retained:	6.11 and above
   Surface acceleration:	994.17	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.429
   Length of year:		420.64	days
   Length of day:		15.31	hours
   Boiling point of water:	293.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1170
				Cesium       melts at 28    boils at 1213
				Gallium      melts at 30    boils at 3792
				Rubidium     melts at 39    boils at 1187
				Potassium    melts at 63    boils at 1305
				Sodium       melts at 98    boils at 1481
				Sulfur       melts at 113   boils at 817
				Indium       melts at 157   boils at 3302
				Lithium      melts at 181   boils at 2188
				Selenium     melts at 217   boils at 1182
				Tin          melts at 232   boils at 4126
				Polonium     melts at 254   boils at 1603
				Bismuth      melts at 271   boils at 2518
				Thallium     melts at 304   boils at 2355
				Cadmium      melts at 321   boils at 1304
				Lead         melts at 328   boils at 2802
   gasses in atmosphere:
				Nitrogen         99.2%  PP 101485.0 mb
				Phosphorus        0.5%  PP  501.4 mb
				CarbonDioxide     0.1%  PP   52.5 mb
				Ethanol           0.1%  PP   53.0 mb


Planet 6	
   Distance from primary:	1.700	AU
   Mass:			0.293	Earth masses
   Equatorial radius:		4279.9	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.069	Earth atmospheres
   Surface temperature:		-53.22	degrees Celcius
   Normal daytime temperature:	-41.05	degrees Celcius
   Normal night temperature:	-65.78	degrees Celcius
   Maximum temperature:   	-17.34	degrees Celcius
   Minimum temperature:   	-90.64	degrees Celcius
   Escape Velocity:		7.39	km/sec
   Molecular weight retained:	14.55 and above
   Surface acceleration:	637.28	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.431
   Length of year:		774.78	days
   Length of day:		19.02	hours
   Boiling point of water:	38.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.24
   Ice cover percentage:	55.92
   liquids at surface:
				Ethanol      melts at -114  boils at 21
   gasses in atmosphere:
				Oxygen           99.8%  PP   69.0 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	2.483	AU
   Mass:			46.032	Earth masses
   Equatorial radius:		34301.7	km
   Density:			1.627	grams/cc
   Eccentricity of orbit:	0.185
   Escape Velocity:		32.72	km/sec
   Molecular weight retained:	0.74 and above
   Surface acceleration:	1560.15	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.550
   Length of year:		1367.80	days
   Length of day:		10.35	hours


Planet 8	*gas giant*
   Distance from primary:	4.945	AU
   Mass:			308.616	Earth masses
   Equatorial radius:		63279.4	km
   Density:			1.738	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		62.37	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	3073.49	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.534
   Length of year:		3841.69	days
   Length of day:		7.37	hours


Planet 9	*gas giant*
   Distance from primary:	8.710	AU
   Mass:			25.908	Earth masses
   Equatorial radius:		32204.8	km
   Density:			1.107	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		25.33	km/sec
   Molecular weight retained:	1.24 and above
   Surface acceleration:	996.15	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.504
   Length of year:		8984.33	days
   Length of day:		12.95	hours


Planet 10	*gas giant*
   Distance from primary:	17.039	AU
   Mass:			703.387	Earth masses
   Equatorial radius:		89204.9	km
   Density:			1.414	grams/cc
   Eccentricity of orbit:	0.223
   Escape Velocity:		79.30	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3524.97	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.524
   Length of year:		24560.31	days
   Length of day:		6.88	hours


Planet 11	
   Distance from primary:	48.568	AU
   Mass:			0.259	Earth masses
   Equatorial radius:		5492.5	km
   Density:			2.233	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.83	degrees Celcius
   Normal daytime temperature:	-224.89	degrees Celcius
   Normal night temperature:	-234.68	degrees Celcius
   Maximum temperature:   	-208.69	degrees Celcius
   Minimum temperature:   	-250.96	degrees Celcius
   Escape Velocity:		6.14	km/sec
   Molecular weight retained:	21.08 and above
   Surface acceleration:	342.75	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.141
   Length of year:		118303.97	days
   Length of day:		25.89	hours
   Boiling point of water:	-45.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


