                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048016
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6165 K
Stellar class: F8
Age: 5.395 billion years  (1.661 billion left on main sequence)
Habitable ecosphere radius: 1.245 AU

Planets present at:
1	  0.395 AU	no atmosphere
2	  0.581 AU	greenhouse
3	  0.995 AU	greenhouse
4	  1.356 AU	
5	  1.786 AU	cold
6	  2.368 AU	gas giant
7	  4.575 AU	gas giant
8	  6.492 AU	gas giant
9	  9.592 AU	gas giant
10	 20.238 AU	gas giant
11	 28.490 AU	gas giant
12	 43.768 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.395	AU
   Mass:			0.100	Earth masses
   Equatorial radius:		3002.2	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.125
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		214.63	degrees Celcius
   Normal daytime temperature:	423.63	degrees Celcius
   Normal night temperature:	-185.31	degrees Celcius
   Maximum temperature:   	427.01	degrees Celcius
   Minimum temperature:   	-196.46	degrees Celcius
   Escape Velocity:		5.16	km/sec
   Molecular weight retained:	29.81 and above
   Surface acceleration:	443.51	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.058
   Length of year:		86.68	days
   Length of day:		1617.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.581	AU
   Mass:			0.802	Earth masses
   Equatorial radius:		5959.8	km
   Density:			5.407	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		0.92	Earth gees
   Surface pressure:		59.785	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		438.02	degrees Celcius
   Maximum temperature:   	453.73	degrees Celcius
   Minimum temperature:   	377.97	degrees Celcius
   Escape Velocity:		10.36	km/sec
   Molecular weight retained:	7.39 and above
   Surface acceleration:	900.64	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.603
   Length of year:		154.77	days
   Length of day:		2954.83	hours
   Boiling point of water:	261.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1088
				Cesium       melts at 28    boils at 1128
				Gallium      melts at 30    boils at 3561
				Rubidium     melts at 39    boils at 1104
				Potassium    melts at 63    boils at 1215
				Sodium       melts at 98    boils at 1381
				Sulfur       melts at 113   boils at 756
				Indium       melts at 157   boils at 3098
				Lithium      melts at 181   boils at 2048
				Selenium     melts at 217   boils at 1100
				Tin          melts at 232   boils at 3877
				Polonium     melts at 254   boils at 1496
				Bismuth      melts at 271   boils at 2359
				Thallium     melts at 304   boils at 2206
				Cadmium      melts at 321   boils at 1214
				Lead         melts at 328   boils at 2627
				Zinc         melts at 420   boils at 1418
   gasses in atmosphere:
				Nitrogen         98.8%  PP 59070.4 mb
				Phosphorus        0.8%  PP  471.6 mb
				CarbonDioxide     0.1%  PP   56.9 mb
				Ozone             0.1%  PP   50.8 mb
				Ethanol           0.1%  PP   58.4 mb


Planet 3	
   Distance from primary:	0.995	AU
   Mass:			0.267	Earth masses
   Equatorial radius:		4150.8	km
   Density:			5.323	grams/cc
   Eccentricity of orbit:	0.170
   Surface gravity:		0.63	Earth gees
   Surface pressure:		6.789	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		67.05	degrees Celcius
   Normal daytime temperature:	70.07	degrees Celcius
   Normal night temperature:	63.63	degrees Celcius
   Maximum temperature:   	81.48	degrees Celcius
   Minimum temperature:   	51.74	degrees Celcius
   Escape Velocity:		7.16	km/sec
   Molecular weight retained:	15.49 and above
   Surface acceleration:	617.49	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.447
   Length of year:		346.58	days
   Length of day:		24.90	hours
   Boiling point of water:	161.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 136
				Mercury      melts at -39   boils at 461
				Water        melts at 0     boils at 161
				Francium     melts at 27    boils at 833
				Cesium       melts at 28    boils at 866
				Gallium      melts at 30    boils at 2844
				Rubidium     melts at 39    boils at 846
				Phosphorus   melts at 44    boils at 372
				Potassium    melts at 63    boils at 937
   gasses in atmosphere:
				Oxygen            0.1%  PP    8.1 mb
				CarbonDioxide    44.0%  PP 2990.4 mb
				Methane           1.5%  PP   99.3 mb
				Ammonia           4.1%  PP  277.6 mb
				Ozone            46.4%  PP 3147.2 mb
				Argon             0.2%  PP   11.7 mb
				Neon              0.4%  PP   27.5 mb
				Krypton           3.0%  PP  202.0 mb
				Xenon             0.4%  PP   25.1 mb


Planet 4	
   Distance from primary:	1.356	AU
   Mass:			0.785	Earth masses
   Equatorial radius:		5916.7	km
   Density:			5.405	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.461	Earth atmospheres
   Surface temperature:		10.65	degrees Celcius
   Normal daytime temperature:	17.14	degrees Celcius
   Normal night temperature:	3.79	degrees Celcius
   Maximum temperature:   	41.47	degrees Celcius
   Minimum temperature:   	-21.91	degrees Celcius
   Escape Velocity:		10.28	km/sec
   Molecular weight retained:	7.51 and above
   Surface acceleration:	893.74	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.196
   Length of year:		551.47	days
   Length of day:		16.27	hours
   Boiling point of water:	79.8	degrees Celcius
   Hydrosphere percentage:	48.46
   Cloud cover percentage:	25.78
   Ice cover percentage:	2.80
   liquids at surface:
				Ethanol      melts at -114  boils at 60
				Mercury      melts at -39   boils at 323
				Bromine      melts at -7    boils at 42
				Water        melts at 0     boils at 80
   gasses in atmosphere:
				Oxygen           34.1%  PP  156.8 mb
				Nitrogen         65.8%  PP  303.0 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	
   Distance from primary:	1.786	AU
   Mass:			0.615	Earth masses
   Equatorial radius:		5463.0	km
   Density:			5.381	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.369	Earth atmospheres
   Surface temperature:		-70.49	degrees Celcius
   Normal daytime temperature:	-65.20	degrees Celcius
   Normal night temperature:	-76.05	degrees Celcius
   Maximum temperature:   	-43.71	degrees Celcius
   Minimum temperature:   	-99.02	degrees Celcius
   Escape Velocity:		9.47	km/sec
   Molecular weight retained:	8.84 and above
   Surface acceleration:	821.53	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.629
   Length of year:		833.17	days
   Length of day:		16.78	hours
   Boiling point of water:	74.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.11
   Ice cover percentage:	87.14
   liquids at surface:
				Ethanol      melts at -114  boils at 54
				Chlorine     melts at -101  boils at -50
				Ammonia      melts at -78   boils at -50
   gasses in atmosphere:
				Oxygen            0.9%  PP    3.4 mb
				Nitrogen         98.8%  PP  364.6 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ozone             0.1%  PP    0.3 mb


Planet 6	*gas giant*
   Distance from primary:	2.368	AU
   Mass:			86.995	Earth masses
   Equatorial radius:		41115.8	km
   Density:			1.786	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		41.08	km/sec
   Molecular weight retained:	0.47 and above
   Surface acceleration:	2052.18	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.531
   Length of year:		1271.86	days
   Length of day:		9.02	hours


Planet 7	*gas giant*
   Distance from primary:	4.575	AU
   Mass:			25.232	Earth masses
   Equatorial radius:		30273.7	km
   Density:			1.298	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		25.78	km/sec
   Molecular weight retained:	1.19 and above
   Surface acceleration:	1097.90	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.492
   Length of year:		3416.55	days
   Length of day:		12.33	hours


Planet 8	*gas giant*
   Distance from primary:	6.492	AU
   Mass:			15.455	Earth masses
   Equatorial radius:		27016.8	km
   Density:			1.118	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		21.36	km/sec
   Molecular weight retained:	1.74 and above
   Surface acceleration:	844.38	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.460
   Length of year:		5773.84	days
   Length of day:		14.07	hours


Planet 9	*gas giant*
   Distance from primary:	9.592	AU
   Mass:			739.071	Earth masses
   Equatorial radius:		86228.8	km
   Density:			1.645	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		82.68	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3963.88	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.502
   Length of year:		10360.56	days
   Length of day:		6.49	hours


Planet 10	*gas giant*
   Distance from primary:	20.238	AU
   Mass:			8.619	Earth masses
   Equatorial radius:		25050.2	km
   Density:			0.782	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		16.57	km/sec
   Molecular weight retained:	2.89 and above
   Surface acceleration:	547.72	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.472
   Length of year:		31783.81	days
   Length of day:		17.46	hours


Planet 11	*gas giant*
   Distance from primary:	28.490	AU
   Mass:			19.564	Earth masses
   Equatorial radius:		32735.9	km
   Density:			0.796	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		21.83	km/sec
   Molecular weight retained:	1.67 and above
   Surface acceleration:	728.02	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.451
   Length of year:		53086.69	days
   Length of day:		15.15	hours


Planet 12	
   Distance from primary:	43.768	AU
   Mass:			0.287	Earth masses
   Equatorial radius:		5679.6	km
   Density:			2.236	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.20	degrees Celcius
   Normal daytime temperature:	-222.04	degrees Celcius
   Normal night temperature:	-232.28	degrees Celcius
   Maximum temperature:   	-208.67	degrees Celcius
   Minimum temperature:   	-246.23	degrees Celcius
   Escape Velocity:		6.35	km/sec
   Molecular weight retained:	19.69 and above
   Surface acceleration:	354.95	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.149
   Length of year:		101083.82	days
   Length of day:		25.44	hours
   Boiling point of water:	-46.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


