                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047cee
Stellar mass: 1.09 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6225 K
Stellar class: F8
Age: 4.178 billion years  (2.989 billion left on main sequence)
Habitable ecosphere radius: 1.233 AU

Planets present at:
1	  0.377 AU	no atmosphere
2	  0.554 AU	no atmosphere
3	  0.917 AU	greenhouse
4	  2.275 AU	gas giant
5	  5.697 AU	gas giant
6	  9.814 AU	gas giant
7	 16.471 AU	gas giant
8	 27.686 AU	no atmosphere
9	 33.667 AU	gas giant
10	 47.140 AU	no atmosphere



Planet 1	
   Distance from primary:	0.377	AU
   Mass:			0.096	Earth masses
   Equatorial radius:		2963.5	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		219.87	degrees Celcius
   Maximum temperature:   	433.60	degrees Celcius
   Minimum temperature:   	-198.97	degrees Celcius
   Escape Velocity:		5.09	km/sec
   Molecular weight retained:	30.60 and above
   Surface acceleration:	437.72	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.085
   Length of year:		81.12	days
   Length of day:		1946.97	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.554	AU
   Mass:			0.526	Earth masses
   Equatorial radius:		5190.1	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		137.30	degrees Celcius
   Maximum temperature:   	332.48	degrees Celcius
   Minimum temperature:   	-218.91	degrees Celcius
   Escape Velocity:		8.99	km/sec
   Molecular weight retained:	9.82 and above
   Surface acceleration:	778.54	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.055
   Length of year:		144.13	days
   Length of day:		3459.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.917	AU
   Mass:			0.871	Earth masses
   Equatorial radius:		6121.5	km
   Density:			5.416	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.94	Earth gees
   Surface pressure:		63.259	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		346.85	degrees Celcius
   Maximum temperature:   	352.15	degrees Celcius
   Minimum temperature:   	340.26	degrees Celcius
   Escape Velocity:		10.65	km/sec
   Molecular weight retained:	7.00 and above
   Surface acceleration:	926.64	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.437
   Length of year:		306.93	days
   Length of day:		17.62	hours
   Boiling point of water:	264.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 635
				Francium     melts at 27    boils at 1096
				Cesium       melts at 28    boils at 1137
				Gallium      melts at 30    boils at 3584
				Rubidium     melts at 39    boils at 1112
				Potassium    melts at 63    boils at 1224
				Sodium       melts at 98    boils at 1391
				Sulfur       melts at 113   boils at 762
				Indium       melts at 157   boils at 3119
				Lithium      melts at 181   boils at 2062
				Selenium     melts at 217   boils at 1108
				Tin          melts at 232   boils at 3902
				Polonium     melts at 254   boils at 1507
				Bismuth      melts at 271   boils at 2375
				Thallium     melts at 304   boils at 2221
				Cadmium      melts at 321   boils at 1223
				Lead         melts at 328   boils at 2645
   gasses in atmosphere:
				Nitrogen         99.1%  PP 62659.7 mb
				Phosphorus        0.6%  PP  394.9 mb
				CarbonDioxide     0.1%  PP   44.2 mb
				Ozone             0.1%  PP   40.0 mb
				Ethanol           0.1%  PP   45.0 mb


Planet 4	*gas giant*
   Distance from primary:	2.275	AU
   Mass:			303.989	Earth masses
   Equatorial radius:		59072.8	km
   Density:			2.104	grams/cc
   Eccentricity of orbit:	0.228
   Escape Velocity:		64.06	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3473.94	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.493
   Length of year:		1199.53	days
   Length of day:		6.93	hours


Planet 5	*gas giant*
   Distance from primary:	5.697	AU
   Mass:			911.314	Earth masses
   Equatorial radius:		87838.1	km
   Density:			1.919	grams/cc
   Eccentricity of orbit:	0.098
   Escape Velocity:		90.97	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4710.22	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.501
   Length of year:		4750.19	days
   Length of day:		5.96	hours


Planet 6	*gas giant*
   Distance from primary:	9.814	AU
   Mass:			5.061	Earth masses
   Equatorial radius:		20208.4	km
   Density:			0.875	grams/cc
   Eccentricity of orbit:	0.162
   Escape Velocity:		14.13	km/sec
   Molecular weight retained:	3.97 and above
   Surface acceleration:	494.20	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.502
   Length of year:		10754.68	days
   Length of day:		18.39	hours


Planet 7	*gas giant*
   Distance from primary:	16.471	AU
   Mass:			68.385	Earth masses
   Equatorial radius:		45088.9	km
   Density:			1.065	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		34.78	km/sec
   Molecular weight retained:	0.66 and above
   Surface acceleration:	1341.41	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.464
   Length of year:		23381.67	days
   Length of day:		11.16	hours


Planet 8	
   Distance from primary:	27.686	AU
   Mass:			0.188	Earth masses
   Equatorial radius:		4937.7	km
   Density:			2.224	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-216.24	degrees Celcius
   Normal daytime temperature:	-209.41	degrees Celcius
   Normal night temperature:	-223.01	degrees Celcius
   Maximum temperature:   	-195.02	degrees Celcius
   Minimum temperature:   	-238.21	degrees Celcius
   Escape Velocity:		5.50	km/sec
   Molecular weight retained:	26.20 and above
   Surface acceleration:	306.86	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.154
   Length of year:		50959.05	days
   Length of day:		27.36	hours
   Boiling point of water:	-54.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 9	*gas giant*
   Distance from primary:	33.667	AU
   Mass:			9.654	Earth masses
   Equatorial radius:		27036.8	km
   Density:			0.697	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		16.88	km/sec
   Molecular weight retained:	2.79 and above
   Surface acceleration:	526.68	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.515
   Length of year:		68332.89	days
   Length of day:		17.81	hours


Planet 10	
   Distance from primary:	47.140	AU
   Mass:			0.174	Earth masses
   Equatorial radius:		4817.1	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.45	degrees Celcius
   Normal daytime temperature:	-224.16	degrees Celcius
   Normal night temperature:	-234.65	degrees Celcius
   Maximum temperature:   	-210.01	degrees Celcius
   Minimum temperature:   	-249.12	degrees Celcius
   Escape Velocity:		5.37	km/sec
   Molecular weight retained:	27.55 and above
   Surface acceleration:	299.12	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.150
   Length of year:		113216.16	days
   Length of day:		27.71	hours
   Boiling point of water:	-54.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


