                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048adb
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6362 K
Stellar class: F7
Age: 3.122 billion years  (3.578 billion left on main sequence)
Habitable ecosphere radius: 1.287 AU

Planets present at:
1	  0.368 AU	no atmosphere
2	  0.414 AU	no atmosphere
3	  0.637 AU	no atmosphere
4	  1.027 AU	greenhouse
5	  1.721 AU	gas giant
6	  3.464 AU	gas giant
7	  6.187 AU	gas giant
8	 11.079 AU	cold
9	 13.232 AU	gas giant
10	 20.127 AU	gas giant
11	 26.084 AU	gas giant
12	 49.691 AU	gas giant



Planet 1	
   Distance from primary:	0.368	AU
   Mass:			0.017	Earth masses
   Equatorial radius:		1661.0	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.56	degrees Celcius
   Maximum temperature:   	458.76	degrees Celcius
   Minimum temperature:   	-194.76	degrees Celcius
   Escape Velocity:		2.85	km/sec
   Molecular weight retained:	97.90 and above
   Surface acceleration:	244.09	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.059
   Length of year:		77.38	days
   Length of day:		1857.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.414	AU
   Mass:			0.172	Earth masses
   Equatorial radius:		3588.9	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		211.13	degrees Celcius
   Maximum temperature:   	423.17	degrees Celcius
   Minimum temperature:   	-202.95	degrees Celcius
   Escape Velocity:		6.18	km/sec
   Molecular weight retained:	20.79 and above
   Surface acceleration:	531.93	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.059
   Length of year:		92.36	days
   Length of day:		2216.63	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.637	AU
   Mass:			0.216	Earth masses
   Equatorial radius:		3871.5	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		115.91	degrees Celcius
   Maximum temperature:   	305.89	degrees Celcius
   Minimum temperature:   	-223.29	degrees Celcius
   Escape Velocity:		6.67	km/sec
   Molecular weight retained:	17.83 and above
   Surface acceleration:	574.85	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.071
   Length of year:		176.48	days
   Length of day:		4235.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.027	AU
   Mass:			1.941	Earth masses
   Equatorial radius:		7937.1	km
   Density:			5.539	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		1.25	Earth gees
   Surface pressure:		312.255	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		513.78	degrees Celcius
   Maximum temperature:   	516.00	degrees Celcius
   Minimum temperature:   	509.03	degrees Celcius
   Escape Velocity:		13.97	km/sec
   Molecular weight retained:	4.07 and above
   Surface acceleration:	1228.69	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.503
   Length of year:		360.99	days
   Length of day:		13.97	hours
   Boiling point of water:	374.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1377
				Cesium       melts at 28    boils at 1425
				Gallium      melts at 30    boils at 4374
				Rubidium     melts at 39    boils at 1396
				Potassium    melts at 63    boils at 1531
				Sodium       melts at 98    boils at 1732
				Indium       melts at 157   boils at 3813
				Lithium      melts at 181   boils at 2540
				Selenium     melts at 217   boils at 1391
				Tin          melts at 232   boils at 4756
				Polonium     melts at 254   boils at 1872
				Bismuth      melts at 271   boils at 2917
				Thallium     melts at 304   boils at 2731
				Cadmium      melts at 321   boils at 1530
				Lead         melts at 328   boils at 3242
				Zinc         melts at 420   boils at 1776
				Tellurium    melts at 450   boils at 1920
   gasses in atmosphere:
				Sulfur           18.4%  PP 57442.7 mb
				Nitrogen         81.1%  PP 253104.2 mb
				Phosphorus        0.4%  PP 1148.9 mb


Planet 5	*gas giant*
   Distance from primary:	1.721	AU
   Mass:			2.814	Earth masses
   Equatorial radius:		14676.3	km
   Density:			1.270	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		12.37	km/sec
   Molecular weight retained:	5.19 and above
   Surface acceleration:	520.91	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.477
   Length of year:		782.74	days
   Length of day:		17.91	hours


Planet 6	*gas giant*
   Distance from primary:	3.464	AU
   Mass:			61.380	Earth masses
   Equatorial radius:		38230.8	km
   Density:			1.567	grams/cc
   Eccentricity of orbit:	0.167
   Escape Velocity:		35.78	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	1674.71	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.550
   Length of year:		2235.47	days
   Length of day:		9.99	hours


Planet 7	*gas giant*
   Distance from primary:	6.187	AU
   Mass:			452.110	Earth masses
   Equatorial radius:		71835.9	km
   Density:			1.740	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		70.85	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3493.82	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.450
   Length of year:		5332.81	days
   Length of day:		6.91	hours


Planet 8	
   Distance from primary:	11.079	AU
   Mass:			0.508	Earth masses
   Equatorial radius:		6847.5	km
   Density:			2.260	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.180	Earth atmospheres
   Surface temperature:		-179.93	degrees Celcius
   Normal daytime temperature:	-175.57	degrees Celcius
   Normal night temperature:	-184.54	degrees Celcius
   Maximum temperature:   	-157.51	degrees Celcius
   Minimum temperature:   	-204.42	degrees Celcius
   Escape Velocity:		7.70	km/sec
   Molecular weight retained:	13.40 and above
   Surface acceleration:	432.46	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.325
   Length of year:		12786.43	days
   Length of day:		23.05	hours
   Boiling point of water:	58.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	32.74
   liquids at surface:
				Ozone        melts at -193  boils at -130
				Methane      melts at -183  boils at -176
   gasses in atmosphere:
				Oxygen           51.6%  PP   92.9 mb
				Nitrogen         48.4%  PP   87.1 mb


Planet 9	*gas giant*
   Distance from primary:	13.232	AU
   Mass:			26.817	Earth masses
   Equatorial radius:		33575.6	km
   Density:			1.011	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		25.24	km/sec
   Molecular weight retained:	1.25 and above
   Surface acceleration:	948.63	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.498
   Length of year:		16687.15	days
   Length of day:		13.27	hours


Planet 10	*gas giant*
   Distance from primary:	20.127	AU
   Mass:			190.753	Earth masses
   Equatorial radius:		61620.0	km
   Density:			1.163	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		49.69	km/sec
   Molecular weight retained:	0.32 and above
   Surface acceleration:	2003.39	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.490
   Length of year:		31298.13	days
   Length of day:		9.13	hours


Planet 11	*gas giant*
   Distance from primary:	26.084	AU
   Mass:			0.617	Earth masses
   Equatorial radius:		11825.8	km
   Density:			0.532	grams/cc
   Eccentricity of orbit:	0.146
   Escape Velocity:		6.45	km/sec
   Molecular weight retained:	19.07 and above
   Surface acceleration:	175.98	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.467
   Length of year:		46187.40	days
   Length of day:		30.81	hours


Planet 12	*gas giant*
   Distance from primary:	49.691	AU
   Mass:			0.350	Earth masses
   Equatorial radius:		10573.9	km
   Density:			0.422	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		5.14	km/sec
   Molecular weight retained:	30.09 and above
   Surface acceleration:	124.76	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.452
   Length of year:		121448.28	days
   Length of day:		36.59	hours


