                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048233
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6132 K
Stellar class: F9
Age: 4.060 billion years  (2.925 billion left on main sequence)
Habitable ecosphere radius: 1.254 AU

Planets present at:
1	  0.322 AU	no atmosphere
2	  0.619 AU	no atmosphere
3	  1.033 AU	greenhouse
4	  2.022 AU	cold
5	  2.787 AU	gas giant
6	  6.618 AU	gas giant
7	 18.139 AU	gas giant
8	 49.717 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.322	AU
   Mass:			0.316	Earth masses
   Equatorial radius:		4387.6	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.279
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		268.29	degrees Celcius
   Normal daytime temperature:	486.03	degrees Celcius
   Normal night temperature:	-148.88	degrees Celcius
   Maximum temperature:   	490.90	degrees Celcius
   Minimum temperature:   	-167.30	degrees Celcius
   Escape Velocity:		7.57	km/sec
   Molecular weight retained:	13.84 and above
   Surface acceleration:	653.85	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.064
   Length of year:		63.61	days
   Length of day:		860.99	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.619	AU
   Mass:			0.552	Earth masses
   Equatorial radius:		5273.6	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		116.01	degrees Celcius
   Maximum temperature:   	306.09	degrees Celcius
   Minimum temperature:   	-223.26	degrees Celcius
   Escape Velocity:		9.14	km/sec
   Molecular weight retained:	9.51 and above
   Surface acceleration:	791.66	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.076
   Length of year:		169.73	days
   Length of day:		4073.50	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.033	AU
   Mass:			1.894	Earth masses
   Equatorial radius:		7874.8	km
   Density:			5.534	grams/cc
   Eccentricity of orbit:	0.101
   Surface gravity:		1.24	Earth gees
   Surface pressure:		290.547	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		522.94	degrees Celcius
   Maximum temperature:   	525.24	degrees Celcius
   Minimum temperature:   	518.00	degrees Celcius
   Escape Velocity:		13.85	km/sec
   Molecular weight retained:	4.14 and above
   Surface acceleration:	1217.97	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.418
   Length of year:		366.12	days
   Length of day:		14.11	hours
   Boiling point of water:	368.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1362
				Cesium       melts at 28    boils at 1410
				Gallium      melts at 30    boils at 4332
				Rubidium     melts at 39    boils at 1381
				Potassium    melts at 63    boils at 1514
				Sodium       melts at 98    boils at 1714
				Indium       melts at 157   boils at 3776
				Lithium      melts at 181   boils at 2515
				Selenium     melts at 217   boils at 1375
				Tin          melts at 232   boils at 4710
				Polonium     melts at 254   boils at 1852
				Bismuth      melts at 271   boils at 2888
				Thallium     melts at 304   boils at 2704
				Cadmium      melts at 321   boils at 1513
				Lead         melts at 328   boils at 3210
				Zinc         melts at 420   boils at 1757
				Tellurium    melts at 450   boils at 1900
   gasses in atmosphere:
				Sulfur           19.0%  PP 55095.7 mb
				Nitrogen         80.5%  PP 233828.5 mb
				Phosphorus        0.4%  PP 1100.6 mb


Planet 4	
   Distance from primary:	2.022	AU
   Mass:			0.908	Earth masses
   Equatorial radius:		6206.8	km
   Density:			5.421	grams/cc
   Eccentricity of orbit:	0.083
   Surface gravity:		0.96	Earth gees
   Surface pressure:		0.658	Earth atmospheres
   Surface temperature:		-81.31	degrees Celcius
   Normal daytime temperature:	-77.71	degrees Celcius
   Normal night temperature:	-85.11	degrees Celcius
   Maximum temperature:   	-58.00	degrees Celcius
   Minimum temperature:   	-106.29	degrees Celcius
   Escape Velocity:		10.80	km/sec
   Molecular weight retained:	6.80 and above
   Surface acceleration:	940.42	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.647
   Length of year:		1002.17	days
   Length of day:		15.64	hours
   Boiling point of water:	88.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	81.45
   liquids at surface:
				Ethanol      melts at -114  boils at 68
				Chlorine     melts at -101  boils at -41
   gasses in atmosphere:
				Oxygen            1.2%  PP    7.6 mb
				Nitrogen         98.7%  PP  649.3 mb
				Ozone             0.1%  PP    0.4 mb


Planet 5	*gas giant*
   Distance from primary:	2.787	AU
   Mass:			3.138	Earth masses
   Equatorial radius:		15806.0	km
   Density:			1.134	grams/cc
   Eccentricity of orbit:	0.151
   Escape Velocity:		12.58	km/sec
   Molecular weight retained:	5.01 and above
   Surface acceleration:	500.83	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.458
   Length of year:		1621.84	days
   Length of day:		18.26	hours


Planet 6	*gas giant*
   Distance from primary:	6.618	AU
   Mass:			612.258	Earth masses
   Equatorial radius:		79093.5	km
   Density:			1.766	grams/cc
   Eccentricity of orbit:	0.185
   Escape Velocity:		78.57	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3902.95	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.533
   Length of year:		5930.38	days
   Length of day:		6.54	hours


Planet 7	*gas giant*
   Distance from primary:	18.139	AU
   Mass:			538.800	Earth masses
   Equatorial radius:		82878.6	km
   Density:			1.351	grams/cc
   Eccentricity of orbit:	0.231
   Escape Velocity:		72.01	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3128.11	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.465
   Length of year:		26913.30	days
   Length of day:		7.31	hours


Planet 8	*gas giant*
   Distance from primary:	49.717	AU
   Mass:			0.594	Earth masses
   Equatorial radius:		12370.0	km
   Density:			0.448	grams/cc
   Eccentricity of orbit:	0.183
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.71 and above
   Surface acceleration:	154.91	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.522
   Length of year:		122213.35	days
   Length of day:		32.84	hours


