                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048a8d
Stellar mass: 1.11 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6445 K
Stellar class: F7
Age: 1.561 billion years  (5.148 billion left on main sequence)
Habitable ecosphere radius: 1.286 AU

Planets present at:
1	  0.339 AU	no atmosphere
2	  0.407 AU	no atmosphere
3	  0.635 AU	no atmosphere
4	  0.903 AU	greenhouse
5	  1.204 AU	no atmosphere
6	  1.628 AU	gas giant
7	  3.692 AU	gas giant
8	  6.511 AU	gas giant
9	  8.806 AU	cold
10	 11.844 AU	gas giant
11	 23.350 AU	gas giant
12	 30.235 AU	gas giant
13	 45.718 AU	no atmosphere
14	 50.726 AU	no atmosphere



Planet 1	
   Distance from primary:	0.339	AU
   Mass:			0.032	Earth masses
   Equatorial radius:		2059.6	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.085
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		262.28	degrees Celcius
   Normal daytime temperature:	481.97	degrees Celcius
   Normal night temperature:	-178.07	degrees Celcius
   Maximum temperature:   	485.17	degrees Celcius
   Minimum temperature:   	-189.40	degrees Celcius
   Escape Velocity:		3.53	km/sec
   Molecular weight retained:	63.60 and above
   Surface acceleration:	303.03	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.055
   Length of year:		68.47	days
   Length of day:		1643.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.407	AU
   Mass:			0.237	Earth masses
   Equatorial radius:		3994.1	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		215.95	degrees Celcius
   Maximum temperature:   	429.10	degrees Celcius
   Minimum temperature:   	-202.02	degrees Celcius
   Escape Velocity:		6.89	km/sec
   Molecular weight retained:	16.74 and above
   Surface acceleration:	593.54	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.051
   Length of year:		90.14	days
   Length of day:		2163.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.635	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		3633.9	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.167
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		117.95	degrees Celcius
   Maximum temperature:   	308.53	degrees Celcius
   Minimum temperature:   	-221.21	degrees Celcius
   Escape Velocity:		6.26	km/sec
   Molecular weight retained:	20.27 and above
   Surface acceleration:	538.74	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.056
   Length of year:		175.62	days
   Length of day:		3009.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.903	AU
   Mass:			0.525	Earth masses
   Equatorial radius:		5188.0	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.79	Earth gees
   Surface pressure:		28.441	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		165.06	degrees Celcius
   Maximum temperature:   	172.41	degrees Celcius
   Minimum temperature:   	157.17	degrees Celcius
   Escape Velocity:		8.99	km/sec
   Molecular weight retained:	9.83 and above
   Surface acceleration:	778.21	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.448
   Length of year:		297.52	days
   Length of day:		18.44	hours
   Boiling point of water:	222.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 564
				Francium     melts at 27    boils at 989
				Cesium       melts at 28    boils at 1026
				Gallium      melts at 30    boils at 3282
				Rubidium     melts at 39    boils at 1004
				Phosphorus   melts at 44    boils at 462
				Potassium    melts at 63    boils at 1107
				Sodium       melts at 98    boils at 1261
				Sulfur       melts at 113   boils at 681
				Iodine       melts at 114   boils at 336
				Indium       melts at 157   boils at 2853
   gasses in atmosphere:
				Nitrogen         99.6%  PP 28319.2 mb
				CarbonDioxide     0.1%  PP   26.6 mb
				Ozone             0.1%  PP   26.8 mb
				Ethanol           0.1%  PP   27.1 mb


Planet 5	
   Distance from primary:	1.204	AU
   Mass:			0.263	Earth masses
   Equatorial radius:		4133.4	km
   Density:			5.322	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.069	Earth atmospheres
   Surface temperature:		13.26	degrees Celcius
   Normal daytime temperature:	29.64	degrees Celcius
   Normal night temperature:	-3.71	degrees Celcius
   Maximum temperature:   	55.85	degrees Celcius
   Minimum temperature:   	-30.91	degrees Celcius
   Escape Velocity:		7.13	km/sec
   Molecular weight retained:	15.62 and above
   Surface acceleration:	614.83	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.239
   Length of year:		457.98	days
   Length of day:		19.76	hours
   Boiling point of water:	38.4	degrees Celcius
   Hydrosphere percentage:	44.20
   Cloud cover percentage:	26.64
   Ice cover percentage:	2.27
   liquids at surface:
				Ethanol      melts at -114  boils at 21
				Mercury      melts at -39   boils at 253
				Water        melts at 0     boils at 39
   gasses in atmosphere:
				Oxygen           98.5%  PP   67.8 mb
				CarbonDioxide     0.5%  PP    0.4 mb
				Ammonia           0.1%  PP    0.0 mb
				Ozone             0.5%  PP    0.4 mb
				Chlorine          0.3%  PP    0.2 mb


Planet 6	*gas giant*
   Distance from primary:	1.628	AU
   Mass:			25.437	Earth masses
   Equatorial radius:		27766.8	km
   Density:			1.695	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		27.03	km/sec
   Molecular weight retained:	1.09 and above
   Surface acceleration:	1315.69	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.531
   Length of year:		720.04	days
   Length of day:		11.27	hours


Planet 7	*gas giant*
   Distance from primary:	3.692	AU
   Mass:			467.547	Earth masses
   Equatorial radius:		69493.0	km
   Density:			1.988	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		73.25	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3860.84	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.457
   Length of year:		2458.52	days
   Length of day:		6.58	hours


Planet 8	*gas giant*
   Distance from primary:	6.511	AU
   Mass:			3.087	Earth masses
   Equatorial radius:		16849.0	km
   Density:			0.921	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		12.09	km/sec
   Molecular weight retained:	5.43 and above
   Surface acceleration:	433.70	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.516
   Length of year:		5761.50	days
   Length of day:		19.63	hours


Planet 9	
   Distance from primary:	8.806	AU
   Mass:			0.772	Earth masses
   Equatorial radius:		7840.8	km
   Density:			2.284	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.424	Earth atmospheres
   Surface temperature:		-168.96	degrees Celcius
   Normal daytime temperature:	-165.79	degrees Celcius
   Normal night temperature:	-172.34	degrees Celcius
   Maximum temperature:   	-151.31	degrees Celcius
   Minimum temperature:   	-188.34	degrees Celcius
   Escape Velocity:		8.86	km/sec
   Molecular weight retained:	10.11 and above
   Surface acceleration:	500.48	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.379
   Length of year:		9062.32	days
   Length of day:		21.42	hours
   Boiling point of water:	77.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	38.74
   liquids at surface:
				Ozone        melts at -193  boils at -122
   gasses in atmosphere:
				Oxygen           55.2%  PP  233.8 mb
				Nitrogen         44.8%  PP  190.0 mb


Planet 10	*gas giant*
   Distance from primary:	11.844	AU
   Mass:			239.141	Earth masses
   Equatorial radius:		62979.8	km
   Density:			1.366	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		55.03	km/sec
   Molecular weight retained:	0.26 and above
   Surface acceleration:	2404.31	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.515
   Length of year:		14130.00	days
   Length of day:		8.34	hours


Planet 11	*gas giant*
   Distance from primary:	23.350	AU
   Mass:			75.386	Earth masses
   Equatorial radius:		47592.2	km
   Density:			0.998	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		35.54	km/sec
   Molecular weight retained:	0.63 and above
   Surface acceleration:	1327.26	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.503
   Length of year:		39122.93	days
   Length of day:		11.22	hours


Planet 12	*gas giant*
   Distance from primary:	30.235	AU
   Mass:			0.659	Earth masses
   Equatorial radius:		12206.7	km
   Density:			0.517	grams/cc
   Eccentricity of orbit:	0.063
   Escape Velocity:		6.56	km/sec
   Molecular weight retained:	18.42 and above
   Surface acceleration:	176.48	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.478
   Length of year:		57653.51	days
   Length of day:		30.77	hours


Planet 13	
   Distance from primary:	45.718	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		4736.0	km
   Density:			2.221	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.72	degrees Celcius
   Normal daytime temperature:	-222.17	degrees Celcius
   Normal night temperature:	-233.18	degrees Celcius
   Maximum temperature:   	-206.89	degrees Celcius
   Minimum temperature:   	-248.74	degrees Celcius
   Escape Velocity:		5.28	km/sec
   Molecular weight retained:	28.51 and above
   Surface acceleration:	293.92	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.140
   Length of year:		107196.96	days
   Length of day:		27.95	hours
   Boiling point of water:	-56.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 14	
   Distance from primary:	50.726	AU
   Mass:			0.043	Earth masses
   Equatorial radius:		3038.6	km
   Density:			2.200	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.34	degrees Celcius
   Normal daytime temperature:	-223.97	degrees Celcius
   Normal night temperature:	-236.57	degrees Celcius
   Maximum temperature:   	-208.95	degrees Celcius
   Minimum temperature:   	-251.44	degrees Celcius
   Escape Velocity:		3.37	km/sec
   Molecular weight retained:	69.92 and above
   Surface acceleration:	186.83	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.147
   Length of year:		125287.68	days
   Length of day:		35.06	hours
   Boiling point of water:	-78.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


