                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485b2
Stellar mass: 1.10 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6245 K
Stellar class: F8
Age: 1.672 billion years  (5.195 billion left on main sequence)
Habitable ecosphere radius: 1.267 AU

Planets present at:
1	  0.439 AU	no atmosphere
2	  0.867 AU	greenhouse
3	  1.384 AU	gas giant
4	  2.312 AU	no atmosphere
5	  2.627 AU	cold
6	  3.120 AU	no atmosphere
7	  3.461 AU	cold
8	  4.215 AU	gas giant
9	  5.324 AU	cold
10	 12.061 AU	gas giant
11	 26.761 AU	gas giant
12	 44.956 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.439	AU
   Mass:			0.448	Earth masses
   Equatorial radius:		4924.9	km
   Density:			5.355	grams/cc
   Eccentricity of orbit:	0.168
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.27	degrees Celcius
   Normal daytime temperature:	396.32	degrees Celcius
   Normal night temperature:	-190.71	degrees Celcius
   Maximum temperature:   	399.85	degrees Celcius
   Minimum temperature:   	-201.98	degrees Celcius
   Escape Velocity:		8.52	km/sec
   Molecular weight retained:	10.93 and above
   Surface acceleration:	737.06	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.071
   Length of year:		101.01	days
   Length of day:		1728.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.867	AU
   Mass:			0.934	Earth masses
   Equatorial radius:		6262.0	km
   Density:			5.425	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.97	Earth gees
   Surface pressure:		78.507	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		430.22	degrees Celcius
   Maximum temperature:   	435.07	degrees Celcius
   Minimum temperature:   	423.49	degrees Celcius
   Escape Velocity:		10.90	km/sec
   Molecular weight retained:	6.68 and above
   Surface acceleration:	949.35	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.446
   Length of year:		280.87	days
   Length of day:		16.50	hours
   Boiling point of water:	277.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1129
				Cesium       melts at 28    boils at 1170
				Gallium      melts at 30    boils at 3675
				Rubidium     melts at 39    boils at 1145
				Potassium    melts at 63    boils at 1259
				Sodium       melts at 98    boils at 1430
				Sulfur       melts at 113   boils at 786
				Indium       melts at 157   boils at 3199
				Lithium      melts at 181   boils at 2117
				Selenium     melts at 217   boils at 1140
				Tin          melts at 232   boils at 4000
				Polonium     melts at 254   boils at 1549
				Bismuth      melts at 271   boils at 2437
				Thallium     melts at 304   boils at 2279
				Cadmium      melts at 321   boils at 1258
				Lead         melts at 328   boils at 2713
				Zinc         melts at 420   boils at 1468
   gasses in atmosphere:
				Nitrogen         99.2%  PP 77860.8 mb
				Phosphorus        0.5%  PP  421.9 mb
				CarbonDioxide     0.1%  PP   45.2 mb
				Ozone             0.1%  PP   43.2 mb
				Ethanol           0.1%  PP   45.7 mb


Planet 3	*gas giant*
   Distance from primary:	1.384	AU
   Mass:			3.146	Earth masses
   Equatorial radius:		14909.2	km
   Density:			1.355	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		12.97	km/sec
   Molecular weight retained:	4.72 and above
   Surface acceleration:	564.41	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.478
   Length of year:		566.55	days
   Length of day:		17.22	hours


Planet 4	
   Distance from primary:	2.312	AU
   Mass:			0.198	Earth masses
   Equatorial radius:		3759.9	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.068
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.038	Earth atmospheres
   Surface temperature:		-84.30	degrees Celcius
   Normal daytime temperature:	-71.33	degrees Celcius
   Normal night temperature:	-97.56	degrees Celcius
   Maximum temperature:   	-46.09	degrees Celcius
   Minimum temperature:   	-124.05	degrees Celcius
   Escape Velocity:		6.48	km/sec
   Molecular weight retained:	18.92 and above
   Surface acceleration:	557.87	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.435
   Length of year:		1222.96	days
   Length of day:		20.30	hours
   Boiling point of water:	27.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	58.82
   liquids at surface:
				Ethanol      melts at -114  boils at 11
				Chlorine     melts at -101  boils at -80
   gasses in atmosphere:
				Ozone            93.4%  PP   35.4 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.3%  PP    0.1 mb
				Krypton           5.5%  PP    2.1 mb
				Xenon             0.6%  PP    0.2 mb


Planet 5	
   Distance from primary:	2.627	AU
   Mass:			1.305	Earth masses
   Equatorial radius:		6981.6	km
   Density:			5.470	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.686	Earth atmospheres
   Surface temperature:		-106.13	degrees Celcius
   Normal daytime temperature:	-104.25	degrees Celcius
   Normal night temperature:	-108.12	degrees Celcius
   Maximum temperature:   	-89.44	degrees Celcius
   Minimum temperature:   	-124.11	degrees Celcius
   Escape Velocity:		12.21	km/sec
   Molecular weight retained:	5.33 and above
   Surface acceleration:	1067.28	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.703
   Length of year:		1481.30	days
   Length of day:		14.67	hours
   Boiling point of water:	115.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 93
   gasses in atmosphere:
				Oxygen            6.4%  PP  108.5 mb
				Nitrogen         93.5%  PP 1576.2 mb


Planet 6	
   Distance from primary:	3.120	AU
   Mass:			0.219	Earth masses
   Equatorial radius:		3889.1	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.042	Earth atmospheres
   Surface temperature:		-114.00	degrees Celcius
   Normal daytime temperature:	-103.52	degrees Celcius
   Normal night temperature:	-124.74	degrees Celcius
   Maximum temperature:   	-82.38	degrees Celcius
   Minimum temperature:   	-147.15	degrees Celcius
   Escape Velocity:		6.70	km/sec
   Molecular weight retained:	17.67 and above
   Surface acceleration:	577.52	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.485
   Length of year:		1916.99	days
   Length of day:		19.94	hours
   Boiling point of water:	29.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	55.44
   liquids at surface:
				Ethanol      melts at -114  boils at 12
   gasses in atmosphere:
				Fluorine         12.1%  PP    5.1 mb
				Argon             1.6%  PP    0.7 mb
				Neon              8.8%  PP    3.7 mb
				Krypton          77.5%  PP   32.8 mb


Planet 7	
   Distance from primary:	3.461	AU
   Mass:			0.905	Earth masses
   Equatorial radius:		6198.2	km
   Density:			5.421	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.96	Earth gees
   Surface pressure:		0.834	Earth atmospheres
   Surface temperature:		-123.71	degrees Celcius
   Normal daytime temperature:	-121.20	degrees Celcius
   Normal night temperature:	-126.36	degrees Celcius
   Maximum temperature:   	-103.49	degrees Celcius
   Minimum temperature:   	-145.63	degrees Celcius
   Escape Velocity:		10.79	km/sec
   Molecular weight retained:	6.82 and above
   Surface acceleration:	939.02	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.638
   Length of year:		2239.85	days
   Length of day:		15.64	hours
   Boiling point of water:	95.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -114
   gasses in atmosphere:
				Oxygen           28.3%  PP  235.8 mb
				Nitrogen         71.7%  PP  597.8 mb


Planet 8	*gas giant*
   Distance from primary:	4.215	AU
   Mass:			4.697	Earth masses
   Equatorial radius:		18387.8	km
   Density:			1.078	grams/cc
   Eccentricity of orbit:	0.074
   Escape Velocity:		14.27	km/sec
   Molecular weight retained:	3.90 and above
   Surface acceleration:	554.03	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.545
   Length of year:		3010.42	days
   Length of day:		17.36	hours


Planet 9	
   Distance from primary:	5.324	AU
   Mass:			0.465	Earth masses
   Equatorial radius:		6651.3	km
   Density:			2.256	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.159	Earth atmospheres
   Surface temperature:		-140.12	degrees Celcius
   Normal daytime temperature:	-133.48	degrees Celcius
   Normal night temperature:	-147.12	degrees Celcius
   Maximum temperature:   	-113.61	degrees Celcius
   Minimum temperature:   	-168.59	degrees Celcius
   Escape Velocity:		7.47	km/sec
   Molecular weight retained:	14.23 and above
   Surface acceleration:	419.27	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.326
   Length of year:		4273.20	days
   Length of day:		23.41	hours
   Boiling point of water:	55.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	33.46
   liquids at surface:
				Ozone        melts at -193  boils at -131
   gasses in atmosphere:
				Oxygen           100.0%  PP  158.7 mb


Planet 10	*gas giant*
   Distance from primary:	12.061	AU
   Mass:			712.554	Earth masses
   Equatorial radius:		86834.6	km
   Density:			1.553	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		80.90	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3768.53	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.471
   Length of year:		14556.90	days
   Length of day:		6.66	hours


Planet 11	*gas giant*
   Distance from primary:	26.761	AU
   Mass:			17.726	Earth masses
   Equatorial radius:		31596.9	km
   Density:			0.802	grams/cc
   Eccentricity of orbit:	0.065
   Escape Velocity:		21.15	km/sec
   Molecular weight retained:	1.77 and above
   Surface acceleration:	708.07	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.524
   Length of year:		48154.01	days
   Length of day:		15.36	hours


Planet 12	*gas giant*
   Distance from primary:	44.956	AU
   Mass:			0.478	Earth masses
   Equatorial radius:		11502.3	km
   Density:			0.448	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		5.76	km/sec
   Molecular weight retained:	23.94 and above
   Surface acceleration:	144.13	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.453
   Length of year:		104852.76	days
   Length of day:		34.04	hours


