                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485e3
Stellar mass: 1.10 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6113 K
Stellar class: F9
Age: 5.656 billion years  (1.206 billion left on main sequence)
Habitable ecosphere radius: 1.268 AU

Planets present at:
1	  0.341 AU	no atmosphere
2	  0.624 AU	no atmosphere
3	  0.914 AU	no atmosphere
4	  1.044 AU	greenhouse
5	  1.253 AU	high pressure
6	  1.691 AU	high pressure
7	  3.781 AU	gas giant
8	  7.717 AU	cold
9	 13.411 AU	gas giant
10	 21.994 AU	no atmosphere
11	 35.653 AU	gas giant
12	 46.939 AU	no atmosphere
13	 50.835 AU	no atmosphere



Planet 1	
   Distance from primary:	0.341	AU
   Mass:			0.108	Earth masses
   Equatorial radius:		3074.0	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		256.65	degrees Celcius
   Normal daytime temperature:	475.16	degrees Celcius
   Normal night temperature:	-179.38	degrees Celcius
   Maximum temperature:   	478.37	degrees Celcius
   Minimum temperature:   	-190.64	degrees Celcius
   Escape Velocity:		5.28	km/sec
   Molecular weight retained:	28.42 and above
   Surface acceleration:	454.29	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.055
   Length of year:		69.37	days
   Length of day:		1664.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.624	AU
   Mass:			0.426	Earth masses
   Equatorial radius:		4841.5	km
   Density:			5.351	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		116.46	degrees Celcius
   Maximum temperature:   	306.73	degrees Celcius
   Minimum temperature:   	-223.23	degrees Celcius
   Escape Velocity:		8.37	km/sec
   Molecular weight retained:	11.32 and above
   Surface acceleration:	724.08	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.077
   Length of year:		171.55	days
   Length of day:		4117.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.914	AU
   Mass:			0.074	Earth masses
   Equatorial radius:		2718.6	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		49.03	degrees Celcius
   Maximum temperature:   	221.66	degrees Celcius
   Minimum temperature:   	-231.19	degrees Celcius
   Escape Velocity:		4.67	km/sec
   Molecular weight retained:	36.40 and above
   Surface acceleration:	401.07	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.075
   Length of year:		303.73	days
   Length of day:		7289.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 4	
   Distance from primary:	1.044	AU
   Mass:			0.316	Earth masses
   Equatorial radius:		4388.3	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.67	Earth gees
   Surface pressure:		8.945	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		32.97	degrees Celcius
   Maximum temperature:   	44.45	degrees Celcius
   Minimum temperature:   	20.86	degrees Celcius
   Escape Velocity:		7.58	km/sec
   Molecular weight retained:	13.83 and above
   Surface acceleration:	653.95	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.637
   Length of year:		371.15	days
   Length of day:		22.21	hours
   Boiling point of water:	172.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.08
   liquids at surface:
				Ethanol      melts at -114  boils at 146
				Mercury      melts at -39   boils at 478
				Bromine      melts at -7    boils at 124
				Water        melts at 0     boils at 172
				Francium     melts at 27    boils at 860
				Cesium       melts at 28    boils at 894
				Gallium      melts at 30    boils at 2920
   gasses in atmosphere:
				Nitrogen         93.7%  PP 8383.4 mb
				CarbonDioxide     2.6%  PP  229.6 mb
				Methane           0.3%  PP   30.8 mb
				Ammonia           0.5%  PP   42.4 mb
				Ozone             2.7%  PP  238.1 mb
				Krypton           0.2%  PP   14.9 mb


Planet 5	
   Distance from primary:	1.253	AU
   Mass:			2.452	Earth masses
   Equatorial radius:		8553.9	km
   Density:			5.589	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		1.36	Earth gees
   Surface pressure:		4.740	Earth atmospheres
   Surface temperature:		21.68	degrees Celcius
   Normal daytime temperature:	23.49	degrees Celcius
   Normal night temperature:	19.75	degrees Celcius
   Maximum temperature:   	35.20	degrees Celcius
   Minimum temperature:   	7.47	degrees Celcius
   Escape Velocity:		15.12	km/sec
   Molecular weight retained:	3.47 and above
   Surface acceleration:	1336.22	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.445
   Length of year:		487.76	days
   Length of day:		13.24	hours
   Boiling point of water:	148.4	degrees Celcius
   Hydrosphere percentage:	76.36
   Cloud cover percentage:	86.54
   Ice cover percentage:	0.68
   liquids at surface:
				Ethanol      melts at -114  boils at 124
				Mercury      melts at -39   boils at 439
				Bromine      melts at -7    boils at 103
				Water        melts at 0     boils at 148
   gasses in atmosphere:
				Nitrogen          1.0%  PP   45.3 mb
				Helium           99.0%  PP 4694.2 mb


Planet 6	
   Distance from primary:	1.691	AU
   Mass:			1.517	Earth masses
   Equatorial radius:		7330.8	km
   Density:			5.494	grams/cc
   Eccentricity of orbit:	0.201
   Surface gravity:		1.15	Earth gees
   Surface pressure:		2.055	Earth atmospheres
   Surface temperature:		-13.35	degrees Celcius
   Normal daytime temperature:	-10.75	degrees Celcius
   Normal night temperature:	-16.10	degrees Celcius
   Maximum temperature:   	6.59	degrees Celcius
   Minimum temperature:   	-34.47	degrees Celcius
   Escape Velocity:		12.85	km/sec
   Molecular weight retained:	4.81 and above
   Surface acceleration:	1125.58	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.301
   Length of year:		764.85	days
   Length of day:		14.32	hours
   Boiling point of water:	121.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	7.14
   Ice cover percentage:	25.08
   liquids at surface:
				Ethanol      melts at -114  boils at 98
				Mercury      melts at -39   boils at 392
   gasses in atmosphere:
				Nitrogen         99.8%  PP 2051.5 mb
				CarbonDioxide     0.1%  PP    1.1 mb
				Ozone             0.1%  PP    1.1 mb


Planet 7	*gas giant*
   Distance from primary:	3.781	AU
   Mass:			529.957	Earth masses
   Equatorial radius:		72308.4	km
   Density:			2.000	grams/cc
   Eccentricity of orbit:	0.128
   Escape Velocity:		76.46	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	4042.06	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.513
   Length of year:		2555.43	days
   Length of day:		6.43	hours


Planet 8	
   Distance from primary:	7.717	AU
   Mass:			0.683	Earth masses
   Equatorial radius:		7535.8	km
   Density:			2.276	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.333	Earth atmospheres
   Surface temperature:		-161.45	degrees Celcius
   Normal daytime temperature:	-157.60	degrees Celcius
   Normal night temperature:	-165.56	degrees Celcius
   Maximum temperature:   	-140.36	degrees Celcius
   Minimum temperature:   	-184.50	degrees Celcius
   Escape Velocity:		8.50	km/sec
   Molecular weight retained:	10.99 and above
   Surface acceleration:	479.36	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.338
   Length of year:		7456.27	days
   Length of day:		21.89	hours
   Boiling point of water:	72.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	37.29
   liquids at surface:
				Ozone        melts at -193  boils at -124
   gasses in atmosphere:
				Oxygen            1.0%  PP    3.3 mb
				Nitrogen         99.0%  PP  329.9 mb


Planet 9	*gas giant*
   Distance from primary:	13.411	AU
   Mass:			1264.401	Earth masses
   Equatorial radius:		103550.9	km
   Density:			1.625	grams/cc
   Eccentricity of orbit:	0.223
   Escape Velocity:		98.68	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4702.37	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.470
   Length of year:		17051.82	days
   Length of day:		5.96	hours


Planet 10	
   Distance from primary:	21.994	AU
   Mass:			0.266	Earth masses
   Equatorial radius:		5537.6	km
   Density:			2.234	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-208.54	degrees Celcius
   Normal daytime temperature:	-201.19	degrees Celcius
   Normal night temperature:	-215.85	degrees Celcius
   Maximum temperature:   	-184.27	degrees Celcius
   Minimum temperature:   	-233.74	degrees Celcius
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.73 and above
   Surface acceleration:	345.69	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.165
   Length of year:		35875.22	days
   Length of day:		25.78	hours
   Boiling point of water:	-45.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 11	*gas giant*
   Distance from primary:	35.653	AU
   Mass:			4.229	Earth masses
   Equatorial radius:		21305.5	km
   Density:			0.624	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		12.58	km/sec
   Molecular weight retained:	5.01 and above
   Surface acceleration:	371.57	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.476
   Length of year:		74042.44	days
   Length of day:		21.20	hours


Planet 12	
   Distance from primary:	46.939	AU
   Mass:			0.088	Earth masses
   Equatorial radius:		3848.5	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.12	degrees Celcius
   Normal daytime temperature:	-223.22	degrees Celcius
   Normal night temperature:	-234.92	degrees Celcius
   Maximum temperature:   	-211.13	degrees Celcius
   Minimum temperature:   	-247.42	degrees Celcius
   Escape Velocity:		4.28	km/sec
   Molecular weight retained:	43.41 and above
   Surface acceleration:	237.56	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.161
   Length of year:		111853.02	days
   Length of day:		31.09	hours
   Boiling point of water:	-67.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


Planet 13	
   Distance from primary:	50.835	AU
   Mass:			0.039	Earth masses
   Equatorial radius:		2942.1	km
   Density:			2.199	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.18	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.56	degrees Celcius
   Normal daytime temperature:	-224.15	degrees Celcius
   Normal night temperature:	-236.85	degrees Celcius
   Maximum temperature:   	-210.28	degrees Celcius
   Minimum temperature:   	-250.71	degrees Celcius
   Escape Velocity:		3.26	km/sec
   Molecular weight retained:	74.61 and above
   Surface acceleration:	180.82	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.137
   Length of year:		126064.51	days
   Length of day:		35.64	hours
   Boiling point of water:	-80.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


