                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048846
Stellar mass: 1.11 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6325 K
Stellar class: F7
Age: 4.926 billion years  (1.857 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.420 AU	no atmosphere
2	  0.619 AU	no atmosphere
3	  0.750 AU	no atmosphere
4	  1.227 AU	
5	  1.719 AU	cold
6	  2.253 AU	cold
7	  3.202 AU	gas giant
8	  4.716 AU	no atmosphere
9	  8.258 AU	gas giant
10	 17.507 AU	gas giant
11	 29.814 AU	no atmosphere
12	 48.199 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.420	AU
   Mass:			0.211	Earth masses
   Equatorial radius:		3844.1	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.234
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		205.46	degrees Celcius
   Normal daytime temperature:	411.85	degrees Celcius
   Normal night temperature:	-182.69	degrees Celcius
   Maximum temperature:   	415.86	degrees Celcius
   Minimum temperature:   	-196.07	degrees Celcius
   Escape Velocity:		6.62	km/sec
   Molecular weight retained:	18.09 and above
   Surface acceleration:	570.67	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.060
   Length of year:		94.68	days
   Length of day:		1410.65	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.619	AU
   Mass:			0.559	Earth masses
   Equatorial radius:		5295.7	km
   Density:			5.372	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		119.59	degrees Celcius
   Maximum temperature:   	310.39	degrees Celcius
   Minimum temperature:   	-222.28	degrees Celcius
   Escape Velocity:		9.18	km/sec
   Molecular weight retained:	9.43 and above
   Surface acceleration:	795.14	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.077
   Length of year:		168.93	days
   Length of day:		4054.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.750	AU
   Mass:			0.293	Earth masses
   Equatorial radius:		4279.4	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		85.90	degrees Celcius
   Maximum temperature:   	268.26	degrees Celcius
   Minimum temperature:   	-226.90	degrees Celcius
   Escape Velocity:		7.39	km/sec
   Molecular weight retained:	14.56 and above
   Surface acceleration:	637.22	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.053
   Length of year:		225.43	days
   Length of day:		5410.22	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.227	AU
   Mass:			0.874	Earth masses
   Equatorial radius:		6128.9	km
   Density:			5.417	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.598	Earth atmospheres
   Surface temperature:		20.99	degrees Celcius
   Normal daytime temperature:	26.89	degrees Celcius
   Normal night temperature:	14.73	degrees Celcius
   Maximum temperature:   	49.13	degrees Celcius
   Minimum temperature:   	-8.74	degrees Celcius
   Escape Velocity:		10.66	km/sec
   Molecular weight retained:	6.98 and above
   Surface acceleration:	927.84	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.299
   Length of year:		472.00	days
   Length of day:		16.09	hours
   Boiling point of water:	86.3	degrees Celcius
   Hydrosphere percentage:	52.61
   Cloud cover percentage:	55.77
   Ice cover percentage:	0.79
   liquids at surface:
				Ethanol      melts at -114  boils at 66
				Mercury      melts at -39   boils at 334
				Bromine      melts at -7    boils at 47
				Water        melts at 0     boils at 86
   gasses in atmosphere:
				Oxygen           30.6%  PP  182.6 mb
				Nitrogen         69.3%  PP  414.1 mb


Planet 5	
   Distance from primary:	1.719	AU
   Mass:			0.599	Earth masses
   Equatorial radius:		5415.1	km
   Density:			5.378	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.260	Earth atmospheres
   Surface temperature:		-50.95	degrees Celcius
   Normal daytime temperature:	-44.18	degrees Celcius
   Normal night temperature:	-58.05	degrees Celcius
   Maximum temperature:   	-20.50	degrees Celcius
   Minimum temperature:   	-83.21	degrees Celcius
   Escape Velocity:		9.39	km/sec
   Molecular weight retained:	9.00 and above
   Surface acceleration:	813.96	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.511
   Length of year:		782.84	days
   Length of day:		16.87	hours
   Boiling point of water:	66.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.29
   Ice cover percentage:	64.34
   liquids at surface:
				Ethanol      melts at -114  boils at 47
   gasses in atmosphere:
				Oxygen            3.2%  PP    8.3 mb
				Nitrogen         96.6%  PP  251.6 mb
				CarbonDioxide     0.1%  PP    0.2 mb
				Ozone             0.1%  PP    0.2 mb


Planet 6	
   Distance from primary:	2.253	AU
   Mass:			1.000	Earth masses
   Equatorial radius:		6403.9	km
   Density:			5.433	grams/cc
   Eccentricity of orbit:	0.111
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.970	Earth atmospheres
   Surface temperature:		-89.84	degrees Celcius
   Normal daytime temperature:	-87.02	degrees Celcius
   Normal night temperature:	-92.82	degrees Celcius
   Maximum temperature:   	-68.15	degrees Celcius
   Minimum temperature:   	-113.15	degrees Celcius
   Escape Velocity:		11.16	km/sec
   Molecular weight retained:	6.37 and above
   Surface acceleration:	972.37	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.664
   Length of year:		1174.36	days
   Length of day:		15.38	hours
   Boiling point of water:	99.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 78
				Chlorine     melts at -101  boils at -34
   gasses in atmosphere:
				Nitrogen         99.9%  PP  968.2 mb
				Ozone             0.1%  PP    0.6 mb


Planet 7	*gas giant*
   Distance from primary:	3.202	AU
   Mass:			429.393	Earth masses
   Equatorial radius:		67026.9	km
   Density:			2.035	grams/cc
   Eccentricity of orbit:	0.070
   Escape Velocity:		71.48	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3811.50	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.461
   Length of year:		1988.22	days
   Length of day:		6.62	hours


Planet 8	
   Distance from primary:	4.716	AU
   Mass:			1/1.016e+04	Earth masses
   Equatorial radius:		299.1	km
   Density:			5.246	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.04	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-130.25	degrees Celcius
   Normal daytime temperature:	-92.10	degrees Celcius
   Normal night temperature:	-168.51	degrees Celcius
   Maximum temperature:   	-70.51	degrees Celcius
   Minimum temperature:   	-189.43	degrees Celcius
   Escape Velocity:		0.51	km/sec
   Molecular weight retained:	3025.67 and above
   Surface acceleration:	43.86	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.063
   Length of year:		3556.70	days
   Length of day:		73.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00


Planet 9	*gas giant*
   Distance from primary:	8.258	AU
   Mass:			1014.766	Earth masses
   Equatorial radius:		93214.8	km
   Density:			1.788	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		93.18	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4657.31	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.545
   Length of year:		8230.56	days
   Length of day:		5.99	hours


Planet 10	*gas giant*
   Distance from primary:	17.507	AU
   Mass:			7.033	Earth masses
   Equatorial radius:		23275.6	km
   Density:			0.796	grams/cc
   Eccentricity of orbit:	0.305
   Escape Velocity:		15.52	km/sec
   Molecular weight retained:	3.29 and above
   Surface acceleration:	517.69	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.505
   Length of year:		25438.66	days
   Length of day:		17.96	hours


Planet 11	
   Distance from primary:	29.814	AU
   Mass:			2.540	Earth masses
   Equatorial radius:		11462.6	km
   Density:			2.407	grams/cc
   Eccentricity of orbit:	0.127
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.016	Earth atmospheres
   Surface temperature:		-214.49	degrees Celcius
   Normal daytime temperature:	-210.48	degrees Celcius
   Normal night temperature:	-218.52	degrees Celcius
   Maximum temperature:   	-193.93	degrees Celcius
   Minimum temperature:   	-236.42	degrees Celcius
   Escape Velocity:		13.29	km/sec
   Molecular weight retained:	4.49 and above
   Surface acceleration:	771.01	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.139
   Length of year:		56535.37	days
   Length of day:		17.26	hours
   Boiling point of water:	13.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.21
   liquids at surface:
				Fluorine     melts at -220  boils at -208
				Oxygen       melts at -218  boils at -204
   gasses in atmosphere:
				Neon             100.0%  PP   16.5 mb


Planet 12	*gas giant*
   Distance from primary:	48.199	AU
   Mass:			0.421	Earth masses
   Equatorial radius:		11140.6	km
   Density:			0.435	grams/cc
   Eccentricity of orbit:	0.098
   Escape Velocity:		5.49	km/sec
   Molecular weight retained:	26.33 and above
   Surface acceleration:	135.29	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.462
   Length of year:		116207.84	days
   Length of day:		35.14	hours


