                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504892d
Stellar mass: 1.11 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6210 K
Stellar class: F8
Age: 4.678 billion years  (2.075 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.383 AU	no atmosphere
2	  0.543 AU	no atmosphere
3	  0.478 AU	no atmosphere
4	  1.144 AU	greenhouse
5	  1.438 AU	gas giant
6	  2.451 AU	gas giant
7	  4.010 AU	no atmosphere
8	  6.060 AU	gas giant
9	 12.504 AU	gas giant
10	 24.725 AU	gas giant
11	 45.563 AU	gas giant



Planet 1	
   Distance from primary:	0.383	AU
   Mass:			0.032	Earth masses
   Equatorial radius:		2052.1	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		227.38	degrees Celcius
   Normal daytime temperature:	439.91	degrees Celcius
   Normal night temperature:	-188.63	degrees Celcius
   Maximum temperature:   	442.98	degrees Celcius
   Minimum temperature:   	-198.79	degrees Celcius
   Escape Velocity:		3.52	km/sec
   Molecular weight retained:	64.06 and above
   Surface acceleration:	301.93	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.069
   Length of year:		82.41	days
   Length of day:		1977.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.543	AU
   Mass:			0.238	Earth masses
   Equatorial radius:		3995.8	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.40	degrees Celcius
   Maximum temperature:   	347.38	degrees Celcius
   Minimum temperature:   	-214.13	degrees Celcius
   Escape Velocity:		6.89	km/sec
   Molecular weight retained:	16.73 and above
   Surface acceleration:	593.79	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.052
   Length of year:		138.90	days
   Length of day:		2468.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.478	AU
   Mass:			0.292	Earth masses
   Equatorial radius:		4275.6	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		173.00	degrees Celcius
   Maximum temperature:   	376.50	degrees Celcius
   Minimum temperature:   	-211.45	degrees Celcius
   Escape Velocity:		7.38	km/sec
   Molecular weight retained:	14.58 and above
   Surface acceleration:	636.62	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.086
   Length of year:		114.85	days
   Length of day:		2756.36	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	1.144	AU
   Mass:			0.488	Earth masses
   Equatorial radius:		5063.4	km
   Density:			5.361	grams/cc
   Eccentricity of orbit:	0.090
   Surface gravity:		0.77	Earth gees
   Surface pressure:		22.961	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		76.82	degrees Celcius
   Maximum temperature:   	84.42	degrees Celcius
   Minimum temperature:   	68.84	degrees Celcius
   Escape Velocity:		8.77	km/sec
   Molecular weight retained:	10.33 and above
   Surface acceleration:	758.68	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.528
   Length of year:		424.53	days
   Length of day:		18.37	hours
   Boiling point of water:	212.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 184
				Mercury      melts at -39   boils at 547
				Water        melts at 0     boils at 212
				Francium     melts at 27    boils at 963
				Cesium       melts at 28    boils at 999
				Gallium      melts at 30    boils at 3209
				Rubidium     melts at 39    boils at 977
				Phosphorus   melts at 44    boils at 447
				Potassium    melts at 63    boils at 1078
   gasses in atmosphere:
				Nitrogen         99.6%  PP 22880.1 mb
				CarbonDioxide     0.1%  PP   28.9 mb
				Ozone             0.1%  PP   28.6 mb


Planet 5	*gas giant*
   Distance from primary:	1.438	AU
   Mass:			6.280	Earth masses
   Equatorial radius:		18280.8	km
   Density:			1.467	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		16.55	km/sec
   Molecular weight retained:	2.90 and above
   Surface acceleration:	749.38	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.545
   Length of year:		598.31	days
   Length of day:		14.94	hours


Planet 6	*gas giant*
   Distance from primary:	2.451	AU
   Mass:			57.882	Earth masses
   Equatorial radius:		36529.0	km
   Density:			1.694	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		35.55	km/sec
   Molecular weight retained:	0.63 and above
   Surface acceleration:	1729.84	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.539
   Length of year:		1331.51	days
   Length of day:		9.83	hours


Planet 7	
   Distance from primary:	4.010	AU
   Mass:			0.054	Earth masses
   Equatorial radius:		2450.5	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.098
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.002	Earth atmospheres
   Surface temperature:		-128.34	degrees Celcius
   Normal daytime temperature:	-112.52	degrees Celcius
   Normal night temperature:	-144.21	degrees Celcius
   Maximum temperature:   	-88.28	degrees Celcius
   Minimum temperature:   	-169.44	degrees Celcius
   Escape Velocity:		4.21	km/sec
   Molecular weight retained:	44.85 and above
   Surface acceleration:	361.10	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.296
   Length of year:		2787.13	days
   Length of day:		25.23	hours
   Boiling point of water:	-15.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	30.03
   gasses in atmosphere:
				Krypton          100.0%  PP    2.3 mb


Planet 8	*gas giant*
   Distance from primary:	6.060	AU
   Mass:			1154.553	Earth masses
   Equatorial radius:		94304.9	km
   Density:			1.964	grams/cc
   Eccentricity of orbit:	0.057
   Escape Velocity:		98.82	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5177.08	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.487
   Length of year:		5170.31	days
   Length of day:		5.68	hours


Planet 9	*gas giant*
   Distance from primary:	12.504	AU
   Mass:			122.991	Earth masses
   Equatorial radius:		52130.0	km
   Density:			1.239	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		43.38	km/sec
   Molecular weight retained:	0.42 and above
   Surface acceleration:	1804.84	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.469
   Length of year:		15343.32	days
   Length of day:		9.62	hours


Planet 10	*gas giant*
   Distance from primary:	24.725	AU
   Mass:			102.162	Earth masses
   Equatorial radius:		52270.9	km
   Density:			1.021	grams/cc
   Eccentricity of orbit:	0.110
   Escape Velocity:		39.48	km/sec
   Molecular weight retained:	0.51 and above
   Surface acceleration:	1491.12	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.484
   Length of year:		42666.63	days
   Length of day:		10.58	hours


Planet 11	*gas giant*
   Distance from primary:	45.563	AU
   Mass:			0.724	Earth masses
   Equatorial radius:		12984.0	km
   Density:			0.472	grams/cc
   Eccentricity of orbit:	0.169
   Escape Velocity:		6.67	km/sec
   Molecular weight retained:	17.85 and above
   Surface acceleration:	171.23	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.508
   Length of year:		106745.62	days
   Length of day:		31.23	hours


