                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048929
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6377 K
Stellar class: F7
Age: 2.451 billion years  (4.303 billion left on main sequence)
Habitable ecosphere radius: 1.280 AU

Planets present at:
1	  0.505 AU	no atmosphere
2	  0.581 AU	no atmosphere
3	  0.685 AU	no atmosphere
4	  0.932 AU	greenhouse
5	  1.267 AU	
6	  1.818 AU	cold
7	  3.445 AU	gas giant
8	  5.841 AU	gas giant
9	 10.694 AU	gas giant
10	 23.579 AU	gas giant
11	 38.842 AU	gas giant
12	 46.145 AU	no atmosphere
13	 51.372 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.505	AU
   Mass:			0.086	Earth masses
   Equatorial radius:		2849.7	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.145
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		162.25	degrees Celcius
   Normal daytime temperature:	359.84	degrees Celcius
   Normal night temperature:	-200.97	degrees Celcius
   Maximum temperature:   	363.28	degrees Celcius
   Minimum temperature:   	-211.25	degrees Celcius
   Escape Velocity:		4.90	km/sec
   Molecular weight retained:	33.11 and above
   Surface acceleration:	420.66	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.074
   Length of year:		124.74	days
   Length of day:		2236.91	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 2	
   Distance from primary:	0.581	AU
   Mass:			0.064	Earth masses
   Equatorial radius:		2590.4	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		131.67	degrees Celcius
   Maximum temperature:   	325.69	degrees Celcius
   Minimum temperature:   	-220.77	degrees Celcius
   Escape Velocity:		4.45	km/sec
   Molecular weight retained:	40.12 and above
   Surface acceleration:	381.94	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.087
   Length of year:		153.56	days
   Length of day:		3685.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.685	AU
   Mass:			0.146	Earth masses
   Equatorial radius:		3398.3	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		102.86	degrees Celcius
   Maximum temperature:   	289.78	degrees Celcius
   Minimum temperature:   	-224.89	degrees Celcius
   Escape Velocity:		5.85	km/sec
   Molecular weight retained:	23.21 and above
   Surface acceleration:	503.12	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.056
   Length of year:		196.58	days
   Length of day:		4717.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.932	AU
   Mass:			2.319	Earth masses
   Equatorial radius:		8402.7	km
   Density:			5.577	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		1.33	Earth gees
   Surface pressure:		549.604	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		577.47	degrees Celcius
   Maximum temperature:   	578.91	degrees Celcius
   Minimum temperature:   	572.81	degrees Celcius
   Escape Velocity:		14.84	km/sec
   Molecular weight retained:	3.61 and above
   Surface acceleration:	1309.59	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.617
   Length of year:		312.20	days
   Length of day:		13.60	hours
   Boiling point of water:	425.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1506
				Cesium       melts at 28    boils at 1558
				Gallium      melts at 30    boils at 4738
				Rubidium     melts at 39    boils at 1526
				Potassium    melts at 63    boils at 1672
				Sodium       melts at 98    boils at 1889
				Indium       melts at 157   boils at 4133
				Lithium      melts at 181   boils at 2760
				Selenium     melts at 217   boils at 1521
				Tin          melts at 232   boils at 5150
				Polonium     melts at 254   boils at 2039
				Bismuth      melts at 271   boils at 3167
				Thallium     melts at 304   boils at 2966
				Cadmium      melts at 321   boils at 1671
				Lead         melts at 328   boils at 3517
				Zinc         melts at 420   boils at 1936
				Tellurium    melts at 450   boils at 2092
   gasses in atmosphere:
				Sulfur            0.2%  PP 1264.7 mb
				Nitrogen          1.1%  PP 5863.6 mb
				Helium           98.7%  PP 542438.9 mb


Planet 5	
   Distance from primary:	1.267	AU
   Mass:			0.694	Earth masses
   Equatorial radius:		5684.6	km
   Density:			5.392	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.87	Earth gees
   Surface pressure:		0.419	Earth atmospheres
   Surface temperature:		14.83	degrees Celcius
   Normal daytime temperature:	21.82	degrees Celcius
   Normal night temperature:	7.44	degrees Celcius
   Maximum temperature:   	45.21	degrees Celcius
   Minimum temperature:   	-17.23	degrees Celcius
   Escape Velocity:		9.87	km/sec
   Molecular weight retained:	8.15 and above
   Surface acceleration:	856.68	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.289
   Length of year:		495.00	days
   Length of day:		16.56	hours
   Boiling point of water:	77.5	degrees Celcius
   Hydrosphere percentage:	53.95
   Cloud cover percentage:	39.10
   Ice cover percentage:	1.65
   liquids at surface:
				Ethanol      melts at -114  boils at 57
				Mercury      melts at -39   boils at 319
				Bromine      melts at -7    boils at 40
				Water        melts at 0     boils at 78
   gasses in atmosphere:
				Oxygen           47.8%  PP  200.0 mb
				Nitrogen         52.1%  PP  218.2 mb


Planet 6	
   Distance from primary:	1.818	AU
   Mass:			1.222	Earth masses
   Equatorial radius:		6835.2	km
   Density:			5.460	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		1.06	Earth gees
   Surface pressure:		1.182	Earth atmospheres
   Surface temperature:		-60.34	degrees Celcius
   Normal daytime temperature:	-57.46	degrees Celcius
   Normal night temperature:	-63.39	degrees Celcius
   Maximum temperature:   	-41.25	degrees Celcius
   Minimum temperature:   	-80.72	degrees Celcius
   Escape Velocity:		11.94	km/sec
   Molecular weight retained:	5.57 and above
   Surface acceleration:	1043.04	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.615
   Length of year:		850.96	days
   Length of day:		14.85	hours
   Boiling point of water:	104.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.21
   Ice cover percentage:	89.79
   liquids at surface:
				Ethanol      melts at -114  boils at 83
				Chlorine     melts at -101  boils at -31
				Ammonia      melts at -78   boils at -30
   gasses in atmosphere:
				Oxygen            3.2%  PP   37.7 mb
				Nitrogen         96.7%  PP 1143.1 mb


Planet 7	*gas giant*
   Distance from primary:	3.445	AU
   Mass:			384.308	Earth masses
   Equatorial radius:		65275.6	km
   Density:			1.972	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		68.52	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3596.80	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.457
   Length of year:		2217.96	days
   Length of day:		6.81	hours


Planet 8	*gas giant*
   Distance from primary:	5.841	AU
   Mass:			43.594	Earth masses
   Equatorial radius:		36154.4	km
   Density:			1.316	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		31.01	km/sec
   Molecular weight retained:	0.83 and above
   Surface acceleration:	1329.99	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.470
   Length of year:		4898.81	days
   Length of day:		11.21	hours


Planet 9	*gas giant*
   Distance from primary:	10.694	AU
   Mass:			603.032	Earth masses
   Equatorial radius:		81811.9	km
   Density:			1.571	grams/cc
   Eccentricity of orbit:	0.006
   Escape Velocity:		76.67	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3592.91	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.530
   Length of year:		12127.79	days
   Length of day:		6.82	hours


Planet 10	*gas giant*
   Distance from primary:	23.579	AU
   Mass:			99.169	Earth masses
   Equatorial radius:		51615.1	km
   Density:			1.029	grams/cc
   Eccentricity of orbit:	0.070
   Escape Velocity:		39.15	km/sec
   Molecular weight retained:	0.52 and above
   Surface acceleration:	1484.44	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.500
   Length of year:		39735.05	days
   Length of day:		10.61	hours


Planet 11	*gas giant*
   Distance from primary:	38.842	AU
   Mass:			1.343	Earth masses
   Equatorial radius:		15342.4	km
   Density:			0.531	grams/cc
   Eccentricity of orbit:	0.099
   Escape Velocity:		8.35	km/sec
   Molecular weight retained:	11.37 and above
   Surface acceleration:	227.47	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.530
   Length of year:		84022.92	days
   Length of day:		27.10	hours


Planet 12	
   Distance from primary:	46.145	AU
   Mass:			1/119.4	Earth masses
   Equatorial radius:		1760.2	km
   Density:			2.191	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.23	degrees Celcius
   Normal daytime temperature:	-219.84	degrees Celcius
   Normal night temperature:	-236.47	degrees Celcius
   Maximum temperature:   	-206.48	degrees Celcius
   Minimum temperature:   	-249.64	degrees Celcius
   Escape Velocity:		1.95	km/sec
   Molecular weight retained:	209.24 and above
   Surface acceleration:	107.76	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.136
   Length of year:		108799.86	days
   Length of day:		46.17	hours
   Boiling point of water:	-99.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


Planet 13	
   Distance from primary:	51.372	AU
   Mass:			0.014	Earth masses
   Equatorial radius:		2097.0	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.71	degrees Celcius
   Normal daytime temperature:	-223.32	degrees Celcius
   Normal night temperature:	-237.93	degrees Celcius
   Maximum temperature:   	-208.57	degrees Celcius
   Minimum temperature:   	-252.25	degrees Celcius
   Escape Velocity:		2.32	km/sec
   Molecular weight retained:	147.29 and above
   Surface acceleration:	128.50	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.147
   Length of year:		127799.27	days
   Length of day:		42.28	hours
   Boiling point of water:	-94.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


