                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048821
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6280 K
Stellar class: F8
Age: 2.213 billion years  (4.575 billion left on main sequence)
Habitable ecosphere radius: 1.276 AU

Planets present at:
1	  0.360 AU	no atmosphere
2	  0.748 AU	greenhouse
3	  1.238 AU	no atmosphere
4	  1.743 AU	gas giant
5	  3.487 AU	high pressure
6	  4.856 AU	gas giant
7	  8.585 AU	gas giant
8	 21.587 AU	gas giant
9	 42.299 AU	no atmosphere
10	 42.272 AU	no atmosphere
11	 50.298 AU	gas giant



Planet 1	
   Distance from primary:	0.360	AU
   Mass:			0.153	Earth masses
   Equatorial radius:		3454.0	km
   Density:			5.299	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		241.55	degrees Celcius
   Normal daytime temperature:	456.98	degrees Celcius
   Normal night temperature:	-184.04	degrees Celcius
   Maximum temperature:   	460.07	degrees Celcius
   Minimum temperature:   	-194.56	degrees Celcius
   Escape Velocity:		5.94	km/sec
   Molecular weight retained:	22.47 and above
   Surface acceleration:	511.52	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.076
   Length of year:		75.06	days
   Length of day:		1801.44	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.748	AU
   Mass:			1.981	Earth masses
   Equatorial radius:		7989.9	km
   Density:			5.543	grams/cc
   Eccentricity of orbit:	0.238
   Surface gravity:		1.26	Earth gees
   Surface pressure:		386.278	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		674.46	degrees Celcius
   Maximum temperature:   	675.76	degrees Celcius
   Minimum temperature:   	668.51	degrees Celcius
   Escape Velocity:		14.06	km/sec
   Molecular weight retained:	4.01 and above
   Surface acceleration:	1237.77	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.512
   Length of year:		224.52	days
   Length of day:		15.14	hours
   Boiling point of water:	393.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1423
				Cesium       melts at 28    boils at 1473
				Gallium      melts at 30    boils at 4505
				Rubidium     melts at 39    boils at 1443
				Potassium    melts at 63    boils at 1581
				Sodium       melts at 98    boils at 1788
				Indium       melts at 157   boils at 3928
				Lithium      melts at 181   boils at 2619
				Selenium     melts at 217   boils at 1437
				Tin          melts at 232   boils at 4898
				Polonium     melts at 254   boils at 1932
				Bismuth      melts at 271   boils at 3007
				Thallium     melts at 304   boils at 2816
				Cadmium      melts at 321   boils at 1580
				Lead         melts at 328   boils at 3341
				Zinc         melts at 420   boils at 1834
				Tellurium    melts at 450   boils at 1982
				Antimony     melts at 631   boils at 3048
				Neptunium    melts at 640   boils at 7181
				Plutonium    melts at 641   boils at 5981
				Magnesium    melts at 649   boils at 2187
				Aluminum     melts at 660   boils at 4619
   gasses in atmosphere:
				Sulfur           18.2%  PP 70408.0 mb
				Nitrogen         81.2%  PP 313764.2 mb
				Phosphorus        0.4%  PP 1408.7 mb


Planet 3	
   Distance from primary:	1.238	AU
   Mass:			0.188	Earth masses
   Equatorial radius:		3697.0	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.029	Earth atmospheres
   Surface temperature:		14.84	degrees Celcius
   Normal daytime temperature:	36.45	degrees Celcius
   Normal night temperature:	-7.30	degrees Celcius
   Maximum temperature:   	65.25	degrees Celcius
   Minimum temperature:   	-36.98	degrees Celcius
   Escape Velocity:		6.37	km/sec
   Molecular weight retained:	19.58 and above
   Surface acceleration:	548.31	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.125
   Length of year:		478.29	days
   Length of day:		21.19	hours
   Boiling point of water:	22.8	degrees Celcius
   Hydrosphere percentage:	32.80
   Cloud cover percentage:	0.00
   Ice cover percentage:	1.67
   liquids at surface:
				Mercury      melts at -39   boils at 227
				Water        melts at 0     boils at 23
   gasses in atmosphere:
				CarbonDioxide    41.5%  PP   12.1 mb
				Ozone            44.6%  PP   13.0 mb
				Chlorine         10.7%  PP    3.1 mb
				Argon             0.1%  PP    0.0 mb
				Neon              0.1%  PP    0.0 mb
				Krypton           2.8%  PP    0.8 mb
				Xenon             0.3%  PP    0.1 mb


Planet 4	*gas giant*
   Distance from primary:	1.743	AU
   Mass:			3.422	Earth masses
   Equatorial radius:		15565.9	km
   Density:			1.295	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		13.24	km/sec
   Molecular weight retained:	4.53 and above
   Surface acceleration:	563.17	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.512
   Length of year:		799.49	days
   Length of day:		17.23	hours


Planet 5	
   Distance from primary:	3.487	AU
   Mass:			1.503	Earth masses
   Equatorial radius:		7309.7	km
   Density:			5.492	grams/cc
   Eccentricity of orbit:	0.165
   Surface gravity:		1.14	Earth gees
   Surface pressure:		2.096	Earth atmospheres
   Surface temperature:		-131.28	degrees Celcius
   Normal daytime temperature:	-129.88	degrees Celcius
   Normal night temperature:	-132.77	degrees Celcius
   Maximum temperature:   	-116.05	degrees Celcius
   Minimum temperature:   	-147.80	degrees Celcius
   Escape Velocity:		12.81	km/sec
   Molecular weight retained:	4.84 and above
   Surface acceleration:	1122.04	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.741
   Length of year:		2261.55	days
   Length of day:		14.31	hours
   Boiling point of water:	121.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -103
   gasses in atmosphere:
				Oxygen            0.5%  PP   10.2 mb
				Nitrogen         99.5%  PP 2084.8 mb


Planet 6	*gas giant*
   Distance from primary:	4.856	AU
   Mass:			991.492	Earth masses
   Equatorial radius:		88581.4	km
   Density:			2.035	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		94.48	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	5038.99	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.504
   Length of year:		3711.35	days
   Length of day:		5.76	hours


Planet 7	*gas giant*
   Distance from primary:	8.585	AU
   Mass:			366.295	Earth masses
   Equatorial radius:		69475.2	km
   Density:			1.559	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		64.85	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3026.29	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.506
   Length of year:		8731.35	days
   Length of day:		7.43	hours


Planet 8	*gas giant*
   Distance from primary:	21.587	AU
   Mass:			126.052	Earth masses
   Equatorial radius:		54964.1	km
   Density:			1.083	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		42.77	km/sec
   Molecular weight retained:	0.43 and above
   Surface acceleration:	1663.91	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.525
   Length of year:		34828.55	days
   Length of day:		10.02	hours


Planet 9	
   Distance from primary:	42.299	AU
   Mass:			0.069	Earth masses
   Equatorial radius:		3551.4	km
   Density:			2.205	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.56	degrees Celcius
   Normal daytime temperature:	-220.08	degrees Celcius
   Normal night temperature:	-232.93	degrees Celcius
   Maximum temperature:   	-208.39	degrees Celcius
   Minimum temperature:   	-245.10	degrees Celcius
   Escape Velocity:		3.94	km/sec
   Molecular weight retained:	51.06 and above
   Surface acceleration:	218.88	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.155
   Length of year:		95546.73	days
   Length of day:		32.39	hours
   Boiling point of water:	-71.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


Planet 10	
   Distance from primary:	42.272	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		2626.3	km
   Density:			2.196	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.62	degrees Celcius
   Normal daytime temperature:	-219.26	degrees Celcius
   Normal night temperature:	-233.86	degrees Celcius
   Maximum temperature:   	-203.84	degrees Celcius
   Minimum temperature:   	-249.19	degrees Celcius
   Escape Velocity:		2.91	km/sec
   Molecular weight retained:	93.74 and above
   Surface acceleration:	161.21	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.160
   Length of year:		95455.59	days
   Length of day:		37.75	hours
   Boiling point of water:	-83.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


Planet 11	*gas giant*
   Distance from primary:	50.298	AU
   Mass:			0.216	Earth masses
   Equatorial radius:		9204.6	km
   Density:			0.395	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		4.33	km/sec
   Molecular weight retained:	42.38 and above
   Surface acceleration:	101.74	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.462
   Length of year:		123895.75	days
   Length of day:		40.52	hours


