                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048595
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6187 K
Stellar class: F8
Age: 2.663 billion years  (4.209 billion left on main sequence)
Habitable ecosphere radius: 1.267 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.473 AU	no atmosphere
3	  0.768 AU	greenhouse
4	  1.386 AU	no atmosphere
5	  1.667 AU	cold
6	  2.244 AU	gas giant
7	  4.047 AU	gas giant
8	  8.480 AU	gas giant
9	 16.632 AU	gas giant
10	 37.645 AU	gas giant
11	 51.433 AU	no atmosphere



Planet 1	
   Distance from primary:	0.358	AU
   Mass:			0.021	Earth masses
   Equatorial radius:		1797.0	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		242.82	degrees Celcius
   Normal daytime temperature:	458.50	degrees Celcius
   Normal night temperature:	-183.60	degrees Celcius
   Maximum temperature:   	461.51	degrees Celcius
   Minimum temperature:   	-193.78	degrees Celcius
   Escape Velocity:		3.08	km/sec
   Molecular weight retained:	83.61 and above
   Surface acceleration:	264.18	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.065
   Length of year:		74.41	days
   Length of day:		1785.90	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.473	AU
   Mass:			0.459	Earth masses
   Equatorial radius:		4962.6	km
   Density:			5.357	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		173.98	degrees Celcius
   Maximum temperature:   	377.57	degrees Celcius
   Minimum temperature:   	-208.63	degrees Celcius
   Escape Velocity:		8.59	km/sec
   Molecular weight retained:	10.77 and above
   Surface acceleration:	742.95	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.079
   Length of year:		113.09	days
   Length of day:		2205.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.768	AU
   Mass:			1.226	Earth masses
   Equatorial radius:		6842.8	km
   Density:			5.461	grams/cc
   Eccentricity of orbit:	0.175
   Surface gravity:		1.06	Earth gees
   Surface pressure:		111.465	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		472.58	degrees Celcius
   Maximum temperature:   	476.70	degrees Celcius
   Minimum temperature:   	466.16	degrees Celcius
   Escape Velocity:		11.95	km/sec
   Molecular weight retained:	5.55 and above
   Surface acceleration:	1044.31	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.553
   Length of year:		234.31	days
   Length of day:		17.46	hours
   Boiling point of water:	299.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1184
				Cesium       melts at 28    boils at 1227
				Gallium      melts at 30    boils at 3832
				Rubidium     melts at 39    boils at 1201
				Potassium    melts at 63    boils at 1320
				Sodium       melts at 98    boils at 1498
				Indium       melts at 157   boils at 3336
				Lithium      melts at 181   boils at 2212
				Selenium     melts at 217   boils at 1196
				Tin          melts at 232   boils at 4169
				Polonium     melts at 254   boils at 1621
				Bismuth      melts at 271   boils at 2545
				Thallium     melts at 304   boils at 2381
				Cadmium      melts at 321   boils at 1319
				Lead         melts at 328   boils at 2832
				Zinc         melts at 420   boils at 1537
				Tellurium    melts at 450   boils at 1664
   gasses in atmosphere:
				Sulfur           20.5%  PP 22877.5 mb
				Nitrogen         78.9%  PP 87892.7 mb
				Phosphorus        0.4%  PP  456.1 mb


Planet 4	
   Distance from primary:	1.386	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		2662.8	km
   Density:			5.277	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.005	Earth atmospheres
   Surface temperature:		-34.42	degrees Celcius
   Normal daytime temperature:	-8.83	degrees Celcius
   Normal night temperature:	-60.21	degrees Celcius
   Maximum temperature:   	19.45	degrees Celcius
   Minimum temperature:   	-89.10	degrees Celcius
   Escape Velocity:		4.57	km/sec
   Molecular weight retained:	37.95 and above
   Surface acceleration:	392.74	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.365
   Length of year:		567.72	days
   Length of day:		25.38	hours
   Boiling point of water:	-6.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	39.52
   liquids at surface:
				Ethanol      melts at -114  boils at -19
				Mercury      melts at -39   boils at 182
   gasses in atmosphere:
				CarbonDioxide    36.1%  PP    1.6 mb
				Ozone            55.7%  PP    2.5 mb
				Krypton           7.1%  PP    0.3 mb
				Xenon             1.0%  PP    0.0 mb


Planet 5	
   Distance from primary:	1.667	AU
   Mass:			0.431	Earth masses
   Equatorial radius:		4862.8	km
   Density:			5.352	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.157	Earth atmospheres
   Surface temperature:		-51.00	degrees Celcius
   Normal daytime temperature:	-42.25	degrees Celcius
   Normal night temperature:	-60.12	degrees Celcius
   Maximum temperature:   	-17.90	degrees Celcius
   Minimum temperature:   	-85.88	degrees Celcius
   Escape Velocity:		8.41	km/sec
   Molecular weight retained:	11.22 and above
   Surface acceleration:	727.39	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.484
   Length of year:		748.89	days
   Length of day:		17.83	hours
   Boiling point of water:	55.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.32
   Ice cover percentage:	66.81
   liquids at surface:
				Ethanol      melts at -114  boils at 36
   gasses in atmosphere:
				Oxygen           42.9%  PP   67.4 mb
				Nitrogen         56.9%  PP   89.4 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.244	AU
   Mass:			136.794	Earth masses
   Equatorial radius:		46643.8	km
   Density:			1.923	grams/cc
   Eccentricity of orbit:	0.101
   Escape Velocity:		48.36	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2507.37	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.470
   Length of year:		1169.45	days
   Length of day:		8.16	hours


Planet 7	*gas giant*
   Distance from primary:	4.047	AU
   Mass:			126.449	Earth masses
   Equatorial radius:		47881.3	km
   Density:			1.644	grams/cc
   Eccentricity of orbit:	0.107
   Escape Velocity:		45.89	km/sec
   Molecular weight retained:	0.38 and above
   Surface acceleration:	2199.49	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.481
   Length of year:		2831.32	days
   Length of day:		8.71	hours


Planet 8	*gas giant*
   Distance from primary:	8.480	AU
   Mass:			218.174	Earth masses
   Equatorial radius:		59708.2	km
   Density:			1.462	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		53.98	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2440.47	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.514
   Length of year:		8588.09	days
   Length of day:		8.27	hours


Planet 9	*gas giant*
   Distance from primary:	16.632	AU
   Mass:			451.362	Earth masses
   Equatorial radius:		78072.7	km
   Density:			1.353	grams/cc
   Eccentricity of orbit:	0.098
   Escape Velocity:		67.90	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	2953.01	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.462
   Length of year:		23582.63	days
   Length of day:		7.52	hours


Planet 10	*gas giant*
   Distance from primary:	37.645	AU
   Mass:			2.463	Earth masses
   Equatorial radius:		18281.5	km
   Density:			0.575	grams/cc
   Eccentricity of orbit:	0.047
   Escape Velocity:		10.37	km/sec
   Molecular weight retained:	7.39 and above
   Surface acceleration:	293.91	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.488
   Length of year:		80350.63	days
   Length of day:		23.84	hours


Planet 11	
   Distance from primary:	51.433	AU
   Mass:			0.089	Earth masses
   Equatorial radius:		3860.8	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.05	degrees Celcius
   Normal daytime temperature:	-225.42	degrees Celcius
   Normal night temperature:	-236.57	degrees Celcius
   Maximum temperature:   	-213.93	degrees Celcius
   Minimum temperature:   	-248.44	degrees Celcius
   Escape Velocity:		4.29	km/sec
   Molecular weight retained:	43.13 and above
   Surface acceleration:	238.33	cm/sec2
   Axial tilt:			63	degrees
   Planetary albedo:		0.157
   Length of year:		128317.91	days
   Length of day:		31.04	hours
   Boiling point of water:	-67.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


