                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950483fa
Stellar mass: 1.10 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6193 K
Stellar class: F8
Age: 2.663 billion years  (4.261 billion left on main sequence)
Habitable ecosphere radius: 1.260 AU

Planets present at:
1	  0.385 AU	no atmosphere
2	  0.460 AU	no atmosphere
3	  0.630 AU	no atmosphere
4	  1.165 AU	greenhouse
5	  1.474 AU	gas giant
6	  2.538 AU	gas giant
7	  4.975 AU	gas giant
8	  8.196 AU	gas giant
9	 21.103 AU	gas giant
10	 39.574 AU	gas giant
11	 50.056 AU	no atmosphere



Planet 1	
   Distance from primary:	0.385	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		1739.9	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		221.33	degrees Celcius
   Maximum temperature:   	435.48	degrees Celcius
   Minimum temperature:   	-199.44	degrees Celcius
   Escape Velocity:		2.98	km/sec
   Molecular weight retained:	89.20 and above
   Surface acceleration:	255.74	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.078
   Length of year:		83.16	days
   Length of day:		1995.92	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.460	AU
   Mass:			0.380	Earth masses
   Equatorial radius:		4664.4	km
   Density:			5.344	grams/cc
   Eccentricity of orbit:	0.076
   Surface gravity:		0.71	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		182.39	degrees Celcius
   Maximum temperature:   	388.10	degrees Celcius
   Minimum temperature:   	-209.70	degrees Celcius
   Escape Velocity:		8.06	km/sec
   Molecular weight retained:	12.22 and above
   Surface acceleration:	696.58	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.050
   Length of year:		108.77	days
   Length of day:		2610.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.630	AU
   Mass:			0.037	Earth masses
   Equatorial radius:		2149.0	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.229
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		113.34	degrees Celcius
   Maximum temperature:   	302.64	degrees Celcius
   Minimum temperature:   	-220.50	degrees Celcius
   Escape Velocity:		3.69	km/sec
   Molecular weight retained:	58.39 and above
   Surface acceleration:	316.30	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.078
   Length of year:		174.27	days
   Length of day:		2621.38	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.165	AU
   Mass:			0.514	Earth masses
   Equatorial radius:		5151.0	km
   Density:			5.366	grams/cc
   Eccentricity of orbit:	0.132
   Surface gravity:		0.79	Earth gees
   Surface pressure:		24.928	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		78.42	degrees Celcius
   Maximum temperature:   	85.99	degrees Celcius
   Minimum temperature:   	70.47	degrees Celcius
   Escape Velocity:		8.92	km/sec
   Molecular weight retained:	9.98 and above
   Surface acceleration:	772.40	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.586
   Length of year:		437.96	days
   Length of day:		17.69	hours
   Boiling point of water:	216.2	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 188
				Mercury      melts at -39   boils at 553
				Water        melts at 0     boils at 216
				Francium     melts at 27    boils at 973
				Cesium       melts at 28    boils at 1010
				Gallium      melts at 30    boils at 3236
				Rubidium     melts at 39    boils at 987
				Phosphorus   melts at 44    boils at 453
				Potassium    melts at 63    boils at 1089
   gasses in atmosphere:
				Nitrogen         99.7%  PP 24853.7 mb
				CarbonDioxide     0.1%  PP   25.2 mb
				Ozone             0.1%  PP   25.2 mb


Planet 5	*gas giant*
   Distance from primary:	1.474	AU
   Mass:			10.885	Earth masses
   Equatorial radius:		21534.3	km
   Density:			1.555	grams/cc
   Eccentricity of orbit:	0.093
   Escape Velocity:		20.08	km/sec
   Molecular weight retained:	1.97 and above
   Surface acceleration:	936.03	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.460
   Length of year:		622.95	days
   Length of day:		13.36	hours


Planet 6	*gas giant*
   Distance from primary:	2.538	AU
   Mass:			14.661	Earth masses
   Equatorial radius:		24577.1	km
   Density:			1.409	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		21.81	km/sec
   Molecular weight retained:	1.67 and above
   Surface acceleration:	967.93	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.474
   Length of year:		1407.83	days
   Length of day:		13.14	hours


Planet 7	*gas giant*
   Distance from primary:	4.975	AU
   Mass:			28.404	Earth masses
   Equatorial radius:		31525.4	km
   Density:			1.294	grams/cc
   Eccentricity of orbit:	0.148
   Escape Velocity:		26.81	km/sec
   Molecular weight retained:	1.10 and above
   Surface acceleration:	1139.73	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.518
   Length of year:		3863.59	days
   Length of day:		12.11	hours


Planet 8	*gas giant*
   Distance from primary:	8.196	AU
   Mass:			1175.601	Earth masses
   Equatorial radius:		97346.6	km
   Density:			1.818	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		98.14	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4947.18	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.538
   Length of year:		8158.11	days
   Length of day:		5.81	hours


Planet 9	*gas giant*
   Distance from primary:	21.103	AU
   Mass:			97.238	Earth masses
   Equatorial radius:		50914.5	km
   Density:			1.051	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		39.03	km/sec
   Molecular weight retained:	0.52 and above
   Surface acceleration:	1495.86	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.474
   Length of year:		33754.09	days
   Length of day:		10.57	hours


Planet 10	*gas giant*
   Distance from primary:	39.574	AU
   Mass:			1.206	Earth masses
   Equatorial radius:		14912.0	km
   Density:			0.519	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		8.03	km/sec
   Molecular weight retained:	12.31 and above
   Surface acceleration:	216.28	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.522
   Length of year:		86691.93	days
   Length of day:		27.79	hours


Planet 11	
   Distance from primary:	50.056	AU
   Mass:			0.085	Earth masses
   Equatorial radius:		3806.4	km
   Density:			2.208	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.46	degrees Celcius
   Normal daytime temperature:	-224.71	degrees Celcius
   Normal night temperature:	-236.10	degrees Celcius
   Maximum temperature:   	-209.66	degrees Celcius
   Minimum temperature:   	-251.14	degrees Celcius
   Escape Velocity:		4.23	km/sec
   Molecular weight retained:	44.39 and above
   Surface acceleration:	234.90	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.148
   Length of year:		123326.05	days
   Length of day:		31.27	hours
   Boiling point of water:	-67.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


