                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504805e
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6333 K
Stellar class: F7
Age: 4.142 billion years  (2.905 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.358 AU	no atmosphere
2	  0.454 AU	no atmosphere
3	  0.631 AU	no atmosphere
4	  0.801 AU	greenhouse
5	  1.546 AU	gas giant
6	  3.603 AU	gas giant
7	  5.587 AU	gas giant
8	  8.719 AU	gas giant
9	 15.596 AU	gas giant
10	 30.062 AU	gas giant
11	 30.268 AU	gas giant
12	 48.275 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.358	AU
   Mass:			0.060	Earth masses
   Equatorial radius:		2528.6	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.174
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		238.28	degrees Celcius
   Normal daytime temperature:	451.65	degrees Celcius
   Normal night temperature:	-173.04	degrees Celcius
   Maximum temperature:   	455.40	degrees Celcius
   Minimum temperature:   	-186.16	degrees Celcius
   Escape Velocity:		4.34	km/sec
   Molecular weight retained:	42.11 and above
   Surface acceleration:	372.72	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.066
   Length of year:		74.84	days
   Length of day:		1263.03	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.454	AU
   Mass:			0.139	Earth masses
   Equatorial radius:		3344.7	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		179.56	degrees Celcius
   Maximum temperature:   	384.62	degrees Celcius
   Minimum temperature:   	-209.96	degrees Celcius
   Escape Velocity:		5.75	km/sec
   Molecular weight retained:	23.97 and above
   Surface acceleration:	495.02	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.080
   Length of year:		106.66	days
   Length of day:		2559.87	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.631	AU
   Mass:			0.083	Earth masses
   Equatorial radius:		2825.4	km
   Density:			5.281	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		111.91	degrees Celcius
   Maximum temperature:   	301.00	degrees Celcius
   Minimum temperature:   	-223.75	degrees Celcius
   Escape Velocity:		4.85	km/sec
   Molecular weight retained:	33.69 and above
   Surface acceleration:	417.03	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.069
   Length of year:		174.90	days
   Length of day:		4197.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.801	AU
   Mass:			1.253	Earth masses
   Equatorial radius:		6890.8	km
   Density:			5.464	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		1.07	Earth gees
   Surface pressure:		152.720	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		519.91	degrees Celcius
   Maximum temperature:   	523.23	degrees Celcius
   Minimum temperature:   	513.79	degrees Celcius
   Escape Velocity:		12.04	km/sec
   Molecular weight retained:	5.47 and above
   Surface acceleration:	1052.23	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.473
   Length of year:		250.06	days
   Length of day:		17.96	hours
   Boiling point of water:	320.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1238
				Cesium       melts at 28    boils at 1283
				Gallium      melts at 30    boils at 3984
				Rubidium     melts at 39    boils at 1256
				Potassium    melts at 63    boils at 1379
				Sodium       melts at 98    boils at 1564
				Indium       melts at 157   boils at 3470
				Lithium      melts at 181   boils at 2304
				Selenium     melts at 217   boils at 1251
				Tin          melts at 232   boils at 4334
				Polonium     melts at 254   boils at 1691
				Bismuth      melts at 271   boils at 2649
				Thallium     melts at 304   boils at 2479
				Cadmium      melts at 321   boils at 1378
				Lead         melts at 328   boils at 2947
				Zinc         melts at 420   boils at 1604
				Tellurium    melts at 450   boils at 1736
   gasses in atmosphere:
				Sulfur           21.6%  PP 32936.1 mb
				Nitrogen         77.8%  PP 118801.7 mb
				Phosphorus        0.4%  PP  655.1 mb


Planet 5	*gas giant*
   Distance from primary:	1.546	AU
   Mass:			10.929	Earth masses
   Equatorial radius:		21666.5	km
   Density:			1.533	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		20.06	km/sec
   Molecular weight retained:	1.97 and above
   Surface acceleration:	928.45	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.520
   Length of year:		671.00	days
   Length of day:		13.42	hours


Planet 6	*gas giant*
   Distance from primary:	3.603	AU
   Mass:			430.180	Earth masses
   Equatorial radius:		67862.9	km
   Density:			1.964	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		71.10	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3724.99	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.506
   Length of year:		2385.76	days
   Length of day:		6.70	hours


Planet 7	*gas giant*
   Distance from primary:	5.587	AU
   Mass:			262.158	Earth masses
   Equatorial radius:		60921.6	km
   Density:			1.654	grams/cc
   Eccentricity of orbit:	0.069
   Escape Velocity:		58.58	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2816.83	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.451
   Length of year:		4607.13	days
   Length of day:		7.70	hours


Planet 8	*gas giant*
   Distance from primary:	8.719	AU
   Mass:			14.881	Earth masses
   Equatorial radius:		27383.4	km
   Density:			1.034	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		20.82	km/sec
   Molecular weight retained:	1.83 and above
   Surface acceleration:	791.41	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.454
   Length of year:		8986.31	days
   Length of day:		14.53	hours


Planet 9	*gas giant*
   Distance from primary:	15.596	AU
   Mass:			73.920	Earth masses
   Equatorial radius:		45874.2	km
   Density:			1.093	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		35.85	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	1400.76	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.503
   Length of year:		21496.10	days
   Length of day:		10.92	hours


Planet 10	*gas giant*
   Distance from primary:	30.062	AU
   Mass:			0.742	Earth masses
   Equatorial radius:		12663.1	km
   Density:			0.522	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		6.84	km/sec
   Molecular weight retained:	16.98 and above
   Surface acceleration:	184.64	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.473
   Length of year:		57530.89	days
   Length of day:		30.08	hours


Planet 11	*gas giant*
   Distance from primary:	30.268	AU
   Mass:			9.579	Earth masses
   Equatorial radius:		26713.4	km
   Density:			0.717	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		16.91	km/sec
   Molecular weight retained:	2.78 and above
   Surface acceleration:	535.31	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.473
   Length of year:		58122.21	days
   Length of day:		17.67	hours


Planet 12	
   Distance from primary:	48.275	AU
   Mass:			0.155	Earth masses
   Equatorial radius:		4638.0	km
   Density:			2.219	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.79	degrees Celcius
   Normal daytime temperature:	-224.44	degrees Celcius
   Normal night temperature:	-235.04	degrees Celcius
   Maximum temperature:   	-210.20	degrees Celcius
   Minimum temperature:   	-249.55	degrees Celcius
   Escape Velocity:		5.17	km/sec
   Molecular weight retained:	29.75 and above
   Surface acceleration:	287.65	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.154
   Length of year:		117071.25	days
   Length of day:		28.26	hours
   Boiling point of water:	-55.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


