                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e56
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6128 K
Stellar class: F9
Age: 2.605 billion years  (4.512 billion left on main sequence)
Habitable ecosphere radius: 1.239 AU

Planets present at:
1	  0.350 AU	no atmosphere
2	  0.513 AU	no atmosphere
3	  0.658 AU	greenhouse
4	  0.846 AU	greenhouse
5	  1.608 AU	cold
6	  2.078 AU	gas giant
7	  3.600 AU	gas giant
8	  7.090 AU	gas giant
9	 14.927 AU	gas giant
10	 22.760 AU	gas giant
11	 34.635 AU	gas giant
12	 48.671 AU	no atmosphere



Planet 1	
   Distance from primary:	0.350	AU
   Mass:			0.190	Earth masses
   Equatorial radius:		3708.3	km
   Density:			5.307	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.56	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		244.02	degrees Celcius
   Normal daytime temperature:	459.87	degrees Celcius
   Normal night temperature:	-182.60	degrees Celcius
   Maximum temperature:   	463.02	degrees Celcius
   Minimum temperature:   	-193.36	degrees Celcius
   Escape Velocity:		6.39	km/sec
   Molecular weight retained:	19.46 and above
   Surface acceleration:	550.03	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.057
   Length of year:		72.27	days
   Length of day:		1734.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.513	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		1525.3	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.188
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.66	degrees Celcius
   Normal daytime temperature:	345.26	degrees Celcius
   Normal night temperature:	-201.54	degrees Celcius
   Maximum temperature:   	348.93	degrees Celcius
   Minimum temperature:   	-212.39	degrees Celcius
   Escape Velocity:		2.61	km/sec
   Molecular weight retained:	116.13 and above
   Surface acceleration:	224.07	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.085
   Length of year:		128.49	days
   Length of day:		2105.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.658	AU
   Mass:			0.722	Earth masses
   Equatorial radius:		5757.7	km
   Density:			5.396	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.89	Earth gees
   Surface pressure:		56.776	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		411.10	degrees Celcius
   Maximum temperature:   	417.89	degrees Celcius
   Minimum temperature:   	401.79	degrees Celcius
   Escape Velocity:		10.00	km/sec
   Molecular weight retained:	7.94 and above
   Surface acceleration:	868.32	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.547
   Length of year:		186.49	days
   Length of day:		37.71	hours
   Boiling point of water:	258.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1081
				Cesium       melts at 28    boils at 1121
				Gallium      melts at 30    boils at 3540
				Rubidium     melts at 39    boils at 1096
				Potassium    melts at 63    boils at 1207
				Sodium       melts at 98    boils at 1372
				Sulfur       melts at 113   boils at 750
				Indium       melts at 157   boils at 3080
				Lithium      melts at 181   boils at 2036
				Selenium     melts at 217   boils at 1092
				Tin          melts at 232   boils at 3854
				Polonium     melts at 254   boils at 1487
				Bismuth      melts at 271   boils at 2345
				Thallium     melts at 304   boils at 2192
				Cadmium      melts at 321   boils at 1206
				Lead         melts at 328   boils at 2611
   gasses in atmosphere:
				Nitrogen         99.0%  PP 56193.3 mb
				Phosphorus        0.7%  PP  383.0 mb
				CarbonDioxide     0.1%  PP   43.2 mb
				Ozone             0.1%  PP   41.4 mb
				Ethanol           0.1%  PP   43.9 mb


Planet 4	
   Distance from primary:	0.846	AU
   Mass:			0.552	Earth masses
   Equatorial radius:		5273.1	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.81	Earth gees
   Surface pressure:		25.288	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		156.15	degrees Celcius
   Maximum temperature:   	163.91	degrees Celcius
   Minimum temperature:   	147.85	degrees Celcius
   Escape Velocity:		9.14	km/sec
   Molecular weight retained:	9.51 and above
   Surface acceleration:	791.58	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.499
   Length of year:		272.04	days
   Length of day:		20.20	hours
   Boiling point of water:	216.9	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 554
				Francium     melts at 27    boils at 975
				Cesium       melts at 28    boils at 1011
				Gallium      melts at 30    boils at 3241
				Rubidium     melts at 39    boils at 989
				Phosphorus   melts at 44    boils at 454
				Potassium    melts at 63    boils at 1091
				Sodium       melts at 98    boils at 1243
				Sulfur       melts at 113   boils at 670
				Iodine       melts at 114   boils at 329
   gasses in atmosphere:
				Nitrogen         99.6%  PP 25179.2 mb
				CarbonDioxide     0.1%  PP   24.2 mb
				Ozone             0.1%  PP   24.2 mb
				Ethanol           0.1%  PP   24.7 mb


Planet 5	
   Distance from primary:	1.608	AU
   Mass:			0.930	Earth masses
   Equatorial radius:		6253.6	km
   Density:			5.424	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.926	Earth atmospheres
   Surface temperature:		-19.68	degrees Celcius
   Normal daytime temperature:	-15.65	degrees Celcius
   Normal night temperature:	-23.95	degrees Celcius
   Maximum temperature:   	4.55	degrees Celcius
   Minimum temperature:   	-45.39	degrees Celcius
   Escape Velocity:		10.89	km/sec
   Molecular weight retained:	6.70 and above
   Surface acceleration:	947.98	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.331
   Length of year:		712.51	days
   Length of day:		15.60	hours
   Boiling point of water:	97.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	4.87
   Ice cover percentage:	37.30
   liquids at surface:
				Ethanol      melts at -114  boils at 77
				Mercury      melts at -39   boils at 353
   gasses in atmosphere:
				Oxygen            5.1%  PP   47.0 mb
				Nitrogen         94.7%  PP  877.2 mb
				CarbonDioxide     0.1%  PP    0.5 mb
				Ozone             0.1%  PP    0.5 mb


Planet 6	*gas giant*
   Distance from primary:	2.078	AU
   Mass:			4.060	Earth masses
   Equatorial radius:		16645.2	km
   Density:			1.256	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		13.95	km/sec
   Molecular weight retained:	4.08 and above
   Surface acceleration:	584.43	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.521
   Length of year:		1046.79	days
   Length of day:		16.91	hours


Planet 7	*gas giant*
   Distance from primary:	3.600	AU
   Mass:			411.830	Earth masses
   Equatorial radius:		67035.8	km
   Density:			1.951	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		70.00	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3654.64	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.530
   Length of year:		2385.92	days
   Length of day:		6.76	hours


Planet 8	*gas giant*
   Distance from primary:	7.090	AU
   Mass:			662.636	Earth masses
   Equatorial radius:		81485.2	km
   Density:			1.748	grams/cc
   Eccentricity of orbit:	0.044
   Escape Velocity:		80.53	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	3979.76	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.485
   Length of year:		6591.40	days
   Length of day:		6.48	hours


Planet 9	*gas giant*
   Distance from primary:	14.927	AU
   Mass:			4.349	Earth masses
   Equatorial radius:		20015.0	km
   Density:			0.774	grams/cc
   Eccentricity of orbit:	0.117
   Escape Velocity:		13.16	km/sec
   Molecular weight retained:	4.58 and above
   Surface acceleration:	432.95	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.550
   Length of year:		20156.14	days
   Length of day:		19.64	hours


Planet 10	*gas giant*
   Distance from primary:	22.760	AU
   Mass:			9.682	Earth masses
   Equatorial radius:		26181.5	km
   Density:			0.770	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		17.17	km/sec
   Molecular weight retained:	2.69 and above
   Surface acceleration:	563.28	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.456
   Length of year:		37949.20	days
   Length of day:		17.22	hours


Planet 11	*gas giant*
   Distance from primary:	34.635	AU
   Mass:			6.281	Earth masses
   Equatorial radius:		23898.5	km
   Density:			0.657	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		14.48	km/sec
   Molecular weight retained:	3.79 and above
   Surface acceleration:	438.55	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.503
   Length of year:		71237.11	days
   Length of day:		19.52	hours


Planet 12	
   Distance from primary:	48.671	AU
   Mass:			0.113	Earth masses
   Equatorial radius:		4177.6	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.45	degrees Celcius
   Maximum temperature:   	-215.73	degrees Celcius
   Minimum temperature:   	-245.60	degrees Celcius
   Escape Velocity:		4.65	km/sec
   Molecular weight retained:	36.78 and above
   Surface acceleration:	258.35	cm/sec2
   Axial tilt:			71	degrees
   Planetary albedo:		0.165
   Length of year:		118669.72	days
   Length of day:		29.82	hours
   Boiling point of water:	-64.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


