                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950489d4
Stellar mass: 1.11 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6227 K
Stellar class: F8
Age: 1.313 billion years  (5.419 billion left on main sequence)
Habitable ecosphere radius: 1.283 AU

Planets present at:
1	  0.409 AU	no atmosphere
2	  0.900 AU	greenhouse
3	  1.722 AU	gas giant
4	  3.664 AU	gas giant
5	  5.641 AU	no atmosphere
6	  9.241 AU	gas giant
7	 15.587 AU	gas giant
8	 32.146 AU	no atmosphere
9	 34.303 AU	gas giant
10	 44.881 AU	no atmosphere
11	 48.349 AU	no atmosphere
12	 51.076 AU	no atmosphere



Planet 1	
   Distance from primary:	0.409	AU
   Mass:			0.304	Earth masses
   Equatorial radius:		4334.7	km
   Density:			5.330	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		210.04	degrees Celcius
   Maximum temperature:   	421.85	degrees Celcius
   Minimum temperature:   	-202.89	degrees Celcius
   Escape Velocity:		7.48	km/sec
   Molecular weight retained:	14.18 and above
   Surface acceleration:	645.71	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.086
   Length of year:		90.59	days
   Length of day:		2174.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.900	AU
   Mass:			0.902	Earth masses
   Equatorial radius:		6192.1	km
   Density:			5.420	grams/cc
   Eccentricity of orbit:	0.121
   Surface gravity:		0.96	Earth gees
   Surface pressure:		82.586	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		420.35	degrees Celcius
   Maximum temperature:   	425.15	degrees Celcius
   Minimum temperature:   	413.74	degrees Celcius
   Escape Velocity:		10.78	km/sec
   Molecular weight retained:	6.83 and above
   Surface acceleration:	938.03	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.466
   Length of year:		296.28	days
   Length of day:		16.26	hours
   Boiling point of water:	280.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1136
				Cesium       melts at 28    boils at 1178
				Gallium      melts at 30    boils at 3697
				Rubidium     melts at 39    boils at 1153
				Potassium    melts at 63    boils at 1268
				Sodium       melts at 98    boils at 1440
				Sulfur       melts at 113   boils at 792
				Indium       melts at 157   boils at 3218
				Lithium      melts at 181   boils at 2130
				Selenium     melts at 217   boils at 1148
				Tin          melts at 232   boils at 4023
				Polonium     melts at 254   boils at 1559
				Bismuth      melts at 271   boils at 2452
				Thallium     melts at 304   boils at 2294
				Cadmium      melts at 321   boils at 1267
				Lead         melts at 328   boils at 2730
				Zinc         melts at 420   boils at 1478
   gasses in atmosphere:
				Nitrogen         99.2%  PP 81908.0 mb
				Phosphorus        0.5%  PP  441.9 mb
				CarbonDioxide     0.1%  PP   47.1 mb
				Ozone             0.1%  PP   45.5 mb
				Ethanol           0.1%  PP   47.6 mb


Planet 3	*gas giant*
   Distance from primary:	1.722	AU
   Mass:			15.782	Earth masses
   Equatorial radius:		24276.4	km
   Density:			1.574	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		22.77	km/sec
   Molecular weight retained:	1.53 and above
   Surface acceleration:	1067.87	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.485
   Length of year:		784.14	days
   Length of day:		12.51	hours


Planet 4	*gas giant*
   Distance from primary:	3.664	AU
   Mass:			394.998	Earth masses
   Equatorial radius:		66128.1	km
   Density:			1.949	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		69.02	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3602.15	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.459
   Length of year:		2431.99	days
   Length of day:		6.81	hours


Planet 5	
   Distance from primary:	5.641	AU
   Mass:			0.115	Earth masses
   Equatorial radius:		4202.5	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.010	Earth atmospheres
   Surface temperature:		-150.03	degrees Celcius
   Normal daytime temperature:	-135.55	degrees Celcius
   Normal night temperature:	-164.66	degrees Celcius
   Maximum temperature:   	-115.03	degrees Celcius
   Minimum temperature:   	-186.10	degrees Celcius
   Escape Velocity:		4.67	km/sec
   Molecular weight retained:	36.34 and above
   Surface acceleration:	259.93	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.279
   Length of year:		4648.69	days
   Length of day:		29.73	hours
   Boiling point of water:	5.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	20.83
   gasses in atmosphere:
				Argon             0.4%  PP    0.0 mb
				Krypton          99.6%  PP    9.7 mb


Planet 6	*gas giant*
   Distance from primary:	9.241	AU
   Mass:			169.348	Earth masses
   Equatorial radius:		55794.0	km
   Density:			1.391	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		49.20	km/sec
   Molecular weight retained:	0.33 and above
   Surface acceleration:	2169.43	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.507
   Length of year:		9743.91	days
   Length of day:		8.77	hours


Planet 7	*gas giant*
   Distance from primary:	15.587	AU
   Mass:			268.935	Earth masses
   Equatorial radius:		66695.0	km
   Density:			1.293	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		56.71	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2411.02	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.463
   Length of year:		21342.00	days
   Length of day:		8.32	hours


Planet 8	
   Distance from primary:	32.146	AU
   Mass:			0.231	Earth masses
   Equatorial radius:		5289.8	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-219.20	degrees Celcius
   Normal daytime temperature:	-212.94	degrees Celcius
   Normal night temperature:	-225.41	degrees Celcius
   Maximum temperature:   	-197.12	degrees Celcius
   Minimum temperature:   	-241.93	degrees Celcius
   Escape Velocity:		5.91	km/sec
   Molecular weight retained:	22.77 and above
   Surface acceleration:	329.59	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.152
   Length of year:		63232.56	days
   Length of day:		26.40	hours
   Boiling point of water:	-50.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07
   liquids at surface:
				Fluorine     melts at -220  boils at -217


Planet 9	*gas giant*
   Distance from primary:	34.303	AU
   Mass:			4.344	Earth masses
   Equatorial radius:		21382.3	km
   Density:			0.634	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		12.73	km/sec
   Molecular weight retained:	4.90 and above
   Surface acceleration:	378.92	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.502
   Length of year:		69704.35	days
   Length of day:		21.00	hours


Planet 10	
   Distance from primary:	44.881	AU
   Mass:			0.135	Earth masses
   Equatorial radius:		4432.0	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.59	degrees Celcius
   Normal daytime temperature:	-221.85	degrees Celcius
   Normal night temperature:	-233.23	degrees Celcius
   Maximum temperature:   	-211.09	degrees Celcius
   Minimum temperature:   	-244.57	degrees Celcius
   Escape Velocity:		4.93	km/sec
   Molecular weight retained:	32.62 and above
   Surface acceleration:	274.51	cm/sec2
   Axial tilt:			65	degrees
   Planetary albedo:		0.142
   Length of year:		104317.39	days
   Length of day:		28.93	hours
   Boiling point of water:	-58.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 11	
   Distance from primary:	48.349	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		2495.0	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.54	degrees Celcius
   Normal daytime temperature:	-222.49	degrees Celcius
   Normal night temperature:	-236.45	degrees Celcius
   Maximum temperature:   	-209.19	degrees Celcius
   Minimum temperature:   	-249.77	degrees Celcius
   Escape Velocity:		2.76	km/sec
   Molecular weight retained:	103.92 and above
   Surface acceleration:	153.08	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.161
   Length of year:		116638.95	days
   Length of day:		38.74	hours
   Boiling point of water:	-87.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


Planet 12	
   Distance from primary:	51.076	AU
   Mass:			1/154	Earth masses
   Equatorial radius:		1617.4	km
   Density:			2.190	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		0.10	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.49	degrees Celcius
   Normal daytime temperature:	-222.24	degrees Celcius
   Normal night temperature:	-238.56	degrees Celcius
   Maximum temperature:   	-209.76	degrees Celcius
   Minimum temperature:   	-250.80	degrees Celcius
   Escape Velocity:		1.79	km/sec
   Molecular weight retained:	247.93 and above
   Surface acceleration:	98.98	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.143
   Length of year:		126644.68	days
   Length of day:		48.17	hours
   Boiling point of water:	-103.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.02


