                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c12
Stellar mass: 1.09 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6198 K
Stellar class: F8
Age: 2.935 billion years  (4.262 billion left on main sequence)
Habitable ecosphere radius: 1.230 AU

Planets present at:
1	  0.312 AU	no atmosphere
2	  0.447 AU	no atmosphere
3	  0.651 AU	no atmosphere
4	  0.844 AU	no atmosphere
5	  0.917 AU	greenhouse
6	  1.609 AU	high pressure
7	  2.501 AU	gas giant
8	  4.010 AU	gas giant
9	  6.687 AU	no atmosphere
10	  9.883 AU	gas giant
11	 21.732 AU	gas giant
12	 49.059 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.312	AU
   Mass:			0.163	Earth masses
   Equatorial radius:		3524.4	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		271.61	degrees Celcius
   Normal daytime temperature:	492.02	degrees Celcius
   Normal night temperature:	-164.67	degrees Celcius
   Maximum temperature:   	495.53	degrees Celcius
   Minimum temperature:   	-177.51	degrees Celcius
   Escape Velocity:		6.07	km/sec
   Molecular weight retained:	21.57 and above
   Surface acceleration:	522.16	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.061
   Length of year:		61.12	days
   Length of day:		1193.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.447	AU
   Mass:			1/138.6	Earth masses
   Equatorial radius:		1251.5	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		182.08	degrees Celcius
   Maximum temperature:   	387.73	degrees Celcius
   Minimum temperature:   	-209.40	degrees Celcius
   Escape Velocity:		2.14	km/sec
   Molecular weight retained:	172.61 and above
   Surface acceleration:	183.73	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.063
   Length of year:		104.52	days
   Length of day:		2508.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.651	AU
   Mass:			0.277	Earth masses
   Equatorial radius:		4203.6	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		103.46	degrees Celcius
   Maximum temperature:   	290.32	degrees Celcius
   Minimum temperature:   	-224.73	degrees Celcius
   Escape Velocity:		7.25	km/sec
   Molecular weight retained:	15.09 and above
   Surface acceleration:	625.59	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.069
   Length of year:		183.88	days
   Length of day:		4413.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	0.844	AU
   Mass:			0.051	Earth masses
   Equatorial radius:		2403.2	km
   Density:			5.272	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		59.14	degrees Celcius
   Maximum temperature:   	234.44	degrees Celcius
   Minimum temperature:   	-229.99	degrees Celcius
   Escape Velocity:		4.13	km/sec
   Molecular weight retained:	46.65 and above
   Surface acceleration:	354.06	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.053
   Length of year:		271.17	days
   Length of day:		6508.03	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 5	
   Distance from primary:	0.917	AU
   Mass:			1.077	Earth masses
   Equatorial radius:		6559.8	km
   Density:			5.443	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		1.02	Earth gees
   Surface pressure:		91.682	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		401.58	degrees Celcius
   Maximum temperature:   	406.01	degrees Celcius
   Minimum temperature:   	395.53	degrees Celcius
   Escape Velocity:		11.44	km/sec
   Molecular weight retained:	6.06 and above
   Surface acceleration:	997.80	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.492
   Length of year:		307.26	days
   Length of day:		16.18	hours
   Boiling point of water:	286.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1153
				Cesium       melts at 28    boils at 1195
				Gallium      melts at 30    boils at 3743
				Rubidium     melts at 39    boils at 1169
				Potassium    melts at 63    boils at 1286
				Sodium       melts at 98    boils at 1460
				Sulfur       melts at 113   boils at 804
				Indium       melts at 157   boils at 3258
				Lithium      melts at 181   boils at 2158
				Selenium     melts at 217   boils at 1165
				Tin          melts at 232   boils at 4073
				Polonium     melts at 254   boils at 1580
				Bismuth      melts at 271   boils at 2484
				Thallium     melts at 304   boils at 2323
				Cadmium      melts at 321   boils at 1285
				Lead         melts at 328   boils at 2765
   gasses in atmosphere:
				Nitrogen         99.2%  PP 90935.3 mb
				Phosphorus        0.5%  PP  489.9 mb
				CarbonDioxide     0.1%  PP   52.9 mb
				Ozone             0.1%  PP   47.3 mb
				Ethanol           0.1%  PP   53.5 mb


Planet 6	
   Distance from primary:	1.609	AU
   Mass:			2.492	Earth masses
   Equatorial radius:		8598.8	km
   Density:			5.593	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		1.37	Earth gees
   Surface pressure:		6.426	Earth atmospheres
   Surface temperature:		13.77	degrees Celcius
   Normal daytime temperature:	15.26	degrees Celcius
   Normal night temperature:	12.17	degrees Celcius
   Maximum temperature:   	26.08	degrees Celcius
   Minimum temperature:   	0.83	degrees Celcius
   Escape Velocity:		15.20	km/sec
   Molecular weight retained:	3.43 and above
   Surface acceleration:	1344.17	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.341
   Length of year:		714.22	days
   Length of day:		13.09	hours
   Boiling point of water:	159.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	67.55
   Ice cover percentage:	1.87
   liquids at surface:
				Ethanol      melts at -114  boils at 135
				Mercury      melts at -39   boils at 457
				Bromine      melts at -7    boils at 113
				Water        melts at 0     boils at 159
   gasses in atmosphere:
				Nitrogen          0.7%  PP   45.7 mb
				Helium           99.3%  PP 6380.1 mb


Planet 7	*gas giant*
   Distance from primary:	2.501	AU
   Mass:			1.894	Earth masses
   Equatorial radius:		13541.8	km
   Density:			1.088	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		10.56	km/sec
   Molecular weight retained:	7.12 and above
   Surface acceleration:	411.94	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.511
   Length of year:		1384.59	days
   Length of day:		20.14	hours


Planet 8	*gas giant*
   Distance from primary:	4.010	AU
   Mass:			587.532	Earth masses
   Equatorial radius:		75070.7	km
   Density:			1.982	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		79.01	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	4157.47	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.526
   Length of year:		2808.20	days
   Length of day:		6.34	hours


Planet 9	
   Distance from primary:	6.687	AU
   Mass:			0.121	Earth masses
   Equatorial radius:		4268.6	km
   Density:			2.214	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.009	Earth atmospheres
   Surface temperature:		-161.58	degrees Celcius
   Normal daytime temperature:	-148.45	degrees Celcius
   Normal night temperature:	-174.83	degrees Celcius
   Maximum temperature:   	-127.08	degrees Celcius
   Minimum temperature:   	-197.24	degrees Celcius
   Escape Velocity:		4.75	km/sec
   Molecular weight retained:	35.20 and above
   Surface acceleration:	264.12	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.257
   Length of year:		6051.64	days
   Length of day:		29.49	hours
   Boiling point of water:	3.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	17.61
   liquids at surface:
				Ozone        melts at -193  boils at -153
   gasses in atmosphere:
				Argon            100.0%  PP    8.9 mb


Planet 10	*gas giant*
   Distance from primary:	9.883	AU
   Mass:			626.802	Earth masses
   Equatorial radius:		82472.8	km
   Density:			1.594	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		77.86	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3674.92	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.525
   Length of year:		10864.53	days
   Length of day:		6.74	hours


Planet 11	*gas giant*
   Distance from primary:	21.732	AU
   Mass:			126.485	Earth masses
   Equatorial radius:		55219.8	km
   Density:			1.072	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		42.74	km/sec
   Molecular weight retained:	0.43 and above
   Surface acceleration:	1654.20	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.476
   Length of year:		35452.87	days
   Length of day:		10.05	hours


Planet 12	*gas giant*
   Distance from primary:	49.059	AU
   Mass:			0.632	Earth masses
   Equatorial radius:		12599.3	km
   Density:			0.451	grams/cc
   Eccentricity of orbit:	0.186
   Escape Velocity:		6.33	km/sec
   Molecular weight retained:	19.84 and above
   Surface acceleration:	158.77	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.521
   Length of year:		120266.47	days
   Length of day:		32.44	hours


