                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048303
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6340 K
Stellar class: F7
Age: 3.546 billion years  (3.411 billion left on main sequence)
Habitable ecosphere radius: 1.257 AU

Planets present at:
1	  0.387 AU	no atmosphere
2	  0.510 AU	no atmosphere
3	  0.645 AU	no atmosphere
4	  1.234 AU	gas giant
5	  2.168 AU	gas giant
6	  4.062 AU	gas giant
7	  6.957 AU	gas giant
8	  9.649 AU	gas giant
9	 13.771 AU	no atmosphere
10	 22.296 AU	gas giant
11	 40.786 AU	gas giant
12	 47.902 AU	no atmosphere



Planet 1	
   Distance from primary:	0.387	AU
   Mass:			0.080	Earth masses
   Equatorial radius:		2782.1	km
   Density:			5.280	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		221.93	degrees Celcius
   Normal daytime temperature:	433.27	degrees Celcius
   Normal night temperature:	-189.85	degrees Celcius
   Maximum temperature:   	436.40	degrees Celcius
   Minimum temperature:   	-200.12	degrees Celcius
   Escape Velocity:		4.78	km/sec
   Molecular weight retained:	34.75 and above
   Surface acceleration:	410.55	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.059
   Length of year:		83.80	days
   Length of day:		2011.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.510	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		3179.7	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		154.88	degrees Celcius
   Maximum temperature:   	354.26	degrees Celcius
   Minimum temperature:   	-215.40	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.55 and above
   Surface acceleration:	470.17	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.087
   Length of year:		126.78	days
   Length of day:		3042.69	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.645	AU
   Mass:			0.273	Earth masses
   Equatorial radius:		4184.0	km
   Density:			5.324	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		110.62	degrees Celcius
   Maximum temperature:   	299.28	degrees Celcius
   Minimum temperature:   	-223.93	degrees Celcius
   Escape Velocity:		7.22	km/sec
   Molecular weight retained:	15.24 and above
   Surface acceleration:	622.58	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.056
   Length of year:		180.43	days
   Length of day:		4330.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	*gas giant*
   Distance from primary:	1.234	AU
   Mass:			12.380	Earth masses
   Equatorial radius:		22035.8	km
   Density:			1.651	grams/cc
   Eccentricity of orbit:	0.258
   Escape Velocity:		21.17	km/sec
   Molecular weight retained:	1.77 and above
   Surface acceleration:	1016.73	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.486
   Length of year:		477.77	days
   Length of day:		12.83	hours


Planet 5	*gas giant*
   Distance from primary:	2.168	AU
   Mass:			6.013	Earth masses
   Equatorial radius:		18708.2	km
   Density:			1.310	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		16.01	km/sec
   Molecular weight retained:	3.10 and above
   Surface acceleration:	685.11	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.515
   Length of year:		1111.94	days
   Length of day:		15.62	hours


Planet 6	*gas giant*
   Distance from primary:	4.062	AU
   Mass:			14.561	Earth masses
   Equatorial radius:		25514.9	km
   Density:			1.251	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		21.33	km/sec
   Molecular weight retained:	1.74 and above
   Surface acceleration:	891.97	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.470
   Length of year:		2852.32	days
   Length of day:		13.68	hours


Planet 7	*gas giant*
   Distance from primary:	6.957	AU
   Mass:			1170.882	Earth masses
   Equatorial radius:		95937.0	km
   Density:			1.892	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		98.66	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5073.18	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.474
   Length of year:		6383.85	days
   Length of day:		5.74	hours


Planet 8	*gas giant*
   Distance from primary:	9.649	AU
   Mass:			27.795	Earth masses
   Equatorial radius:		33112.9	km
   Density:			1.092	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		25.87	km/sec
   Molecular weight retained:	1.19 and above
   Surface acceleration:	1010.91	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.514
   Length of year:		10442.80	days
   Length of day:		12.85	hours


Planet 9	
   Distance from primary:	13.771	AU
   Mass:			0.089	Earth masses
   Equatorial radius:		3853.4	km
   Density:			2.209	grams/cc
   Eccentricity of orbit:	0.051
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.006	Earth atmospheres
   Surface temperature:		-195.08	degrees Celcius
   Normal daytime temperature:	-185.22	degrees Celcius
   Normal night temperature:	-204.99	degrees Celcius
   Maximum temperature:   	-167.97	degrees Celcius
   Minimum temperature:   	-223.18	degrees Celcius
   Escape Velocity:		4.28	km/sec
   Molecular weight retained:	43.30 and above
   Surface acceleration:	237.87	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.277
   Length of year:		17806.89	days
   Length of day:		31.07	hours
   Boiling point of water:	-2.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	19.90


Planet 10	*gas giant*
   Distance from primary:	22.296	AU
   Mass:			46.663	Earth masses
   Equatorial radius:		41298.8	km
   Density:			0.945	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		30.02	km/sec
   Molecular weight retained:	0.88 and above
   Surface acceleration:	1091.04	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.542
   Length of year:		36681.00	days
   Length of day:		12.37	hours


Planet 11	*gas giant*
   Distance from primary:	40.786	AU
   Mass:			2.723	Earth masses
   Equatorial radius:		18962.0	km
   Density:			0.570	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		10.70	km/sec
   Molecular weight retained:	6.93 and above
   Surface acceleration:	301.97	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.504
   Length of year:		90761.20	days
   Length of day:		23.52	hours


Planet 12	
   Distance from primary:	47.902	AU
   Mass:			1/135.1	Earth masses
   Equatorial radius:		1689.6	km
   Density:			2.190	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.64	degrees Celcius
   Normal daytime temperature:	-221.37	degrees Celcius
   Normal night temperature:	-237.73	degrees Celcius
   Maximum temperature:   	-209.17	degrees Celcius
   Minimum temperature:   	-249.80	degrees Celcius
   Escape Velocity:		1.87	km/sec
   Molecular weight retained:	227.15 and above
   Surface acceleration:	103.42	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.149
   Length of year:		115524.36	days
   Length of day:		47.13	hours
   Boiling point of water:	-101.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


