                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481a2
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6150 K
Stellar class: F9
Age: 2.713 billion years  (4.291 billion left on main sequence)
Habitable ecosphere radius: 1.251 AU

Planets present at:
1	  0.426 AU	no atmosphere
2	  0.506 AU	no atmosphere
3	  0.571 AU	no atmosphere
4	  0.797 AU	no atmosphere
5	  1.121 AU	greenhouse
6	  1.892 AU	gas giant
7	  2.999 AU	gas giant
8	  5.257 AU	gas giant
9	  9.472 AU	gas giant
10	 20.860 AU	gas giant
11	 27.370 AU	no atmosphere
12	 48.515 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.426	AU
   Mass:			0.063	Earth masses
   Equatorial radius:		2574.5	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.138
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		195.14	degrees Celcius
   Normal daytime temperature:	399.92	degrees Celcius
   Normal night temperature:	-190.72	degrees Celcius
   Maximum temperature:   	403.36	degrees Celcius
   Minimum temperature:   	-201.72	degrees Celcius
   Escape Velocity:		4.42	km/sec
   Molecular weight retained:	40.62 and above
   Surface acceleration:	379.57	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.080
   Length of year:		96.87	days
   Length of day:		1760.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.506	AU
   Mass:			0.042	Earth masses
   Equatorial radius:		2246.1	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		157.95	degrees Celcius
   Maximum temperature:   	358.01	degrees Celcius
   Minimum temperature:   	-214.71	degrees Celcius
   Escape Velocity:		3.85	km/sec
   Molecular weight retained:	53.43 and above
   Surface acceleration:	330.71	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.066
   Length of year:		125.53	days
   Length of day:		3012.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.571	AU
   Mass:			0.492	Earth masses
   Equatorial radius:		5079.2	km
   Density:			5.362	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.34	degrees Celcius
   Maximum temperature:   	327.57	degrees Celcius
   Minimum temperature:   	-219.78	degrees Celcius
   Escape Velocity:		8.79	km/sec
   Molecular weight retained:	10.27 and above
   Surface acceleration:	761.17	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.061
   Length of year:		150.36	days
   Length of day:		3608.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.797	AU
   Mass:			0.026	Earth masses
   Equatorial radius:		1922.3	km
   Density:			5.262	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		70.17	degrees Celcius
   Maximum temperature:   	248.34	degrees Celcius
   Minimum temperature:   	-228.70	degrees Celcius
   Escape Velocity:		3.30	km/sec
   Molecular weight retained:	73.03 and above
   Surface acceleration:	282.72	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.069
   Length of year:		248.11	days
   Length of day:		5954.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.121	AU
   Mass:			1.634	Earth masses
   Equatorial radius:		7508.9	km
   Density:			5.507	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		1.18	Earth gees
   Surface pressure:		270.643	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		456.31	degrees Celcius
   Maximum temperature:   	458.98	degrees Celcius
   Minimum temperature:   	451.66	degrees Celcius
   Escape Velocity:		13.17	km/sec
   Molecular weight retained:	4.57 and above
   Surface acceleration:	1155.61	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.492
   Length of year:		414.06	days
   Length of day:		14.28	hours
   Boiling point of water:	363.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1347
				Cesium       melts at 28    boils at 1395
				Gallium      melts at 30    boils at 4291
				Rubidium     melts at 39    boils at 1366
				Potassium    melts at 63    boils at 1498
				Sodium       melts at 98    boils at 1696
				Indium       melts at 157   boils at 3740
				Lithium      melts at 181   boils at 2490
				Selenium     melts at 217   boils at 1361
				Tin          melts at 232   boils at 4666
				Polonium     melts at 254   boils at 1833
				Bismuth      melts at 271   boils at 2860
				Thallium     melts at 304   boils at 2677
				Cadmium      melts at 321   boils at 1497
				Lead         melts at 328   boils at 3179
				Zinc         melts at 420   boils at 1739
				Tellurium    melts at 450   boils at 1881
   gasses in atmosphere:
				Sulfur           18.6%  PP 50394.6 mb
				Nitrogen         80.8%  PP 218737.3 mb
				Phosphorus        0.4%  PP 1007.9 mb


Planet 6	*gas giant*
   Distance from primary:	1.892	AU
   Mass:			6.344	Earth masses
   Equatorial radius:		18795.7	km
   Density:			1.363	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		16.41	km/sec
   Molecular weight retained:	2.95 and above
   Surface acceleration:	716.12	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.505
   Length of year:		907.81	days
   Length of day:		15.27	hours


Planet 7	*gas giant*
   Distance from primary:	2.999	AU
   Mass:			3.053	Earth masses
   Equatorial radius:		15779.5	km
   Density:			1.109	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		12.42	km/sec
   Molecular weight retained:	5.14 and above
   Surface acceleration:	489.04	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.516
   Length of year:		1810.85	days
   Length of day:		18.48	hours


Planet 8	*gas giant*
   Distance from primary:	5.257	AU
   Mass:			1213.395	Earth masses
   Equatorial radius:		94736.0	km
   Density:			2.036	grams/cc
   Eccentricity of orbit:	0.092
   Escape Velocity:		101.07	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5391.53	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.474
   Length of year:		4196.45	days
   Length of day:		5.57	hours


Planet 9	*gas giant*
   Distance from primary:	9.472	AU
   Mass:			265.630	Earth masses
   Equatorial radius:		63886.1	km
   Density:			1.454	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		57.59	km/sec
   Molecular weight retained:	0.24 and above
   Surface acceleration:	2595.40	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.500
   Length of year:		10163.59	days
   Length of day:		8.02	hours


Planet 10	*gas giant*
   Distance from primary:	20.860	AU
   Mass:			136.954	Earth masses
   Equatorial radius:		56242.5	km
   Density:			1.098	grams/cc
   Eccentricity of orbit:	0.043
   Escape Velocity:		44.07	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1726.58	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.543
   Length of year:		33220.11	days
   Length of day:		9.84	hours


Planet 11	
   Distance from primary:	27.370	AU
   Mass:			0.242	Earth masses
   Equatorial radius:		5371.2	km
   Density:			2.231	grams/cc
   Eccentricity of orbit:	0.072
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-215.14	degrees Celcius
   Normal daytime temperature:	-208.45	degrees Celcius
   Normal night temperature:	-221.78	degrees Celcius
   Maximum temperature:   	-190.67	degrees Celcius
   Minimum temperature:   	-240.29	degrees Celcius
   Escape Velocity:		6.00	km/sec
   Molecular weight retained:	22.07 and above
   Surface acceleration:	334.87	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.137
   Length of year:		49938.52	days
   Length of day:		26.19	hours
   Boiling point of water:	-48.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 12	*gas giant*
   Distance from primary:	48.515	AU
   Mass:			0.421	Earth masses
   Equatorial radius:		11168.4	km
   Density:			0.432	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		5.49	km/sec
   Molecular weight retained:	26.38 and above
   Surface acceleration:	134.74	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.473
   Length of year:		117849.56	days
   Length of day:		35.21	hours


