                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504898e
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6288 K
Stellar class: F8
Age: 5.789 billion years  (0.952 billion left on main sequence)
Habitable ecosphere radius: 1.282 AU

Planets present at:
1	  0.355 AU	no atmosphere
2	  0.494 AU	no atmosphere
3	  1.091 AU	gas giant
4	  1.934 AU	no atmosphere
5	  2.740 AU	cold
6	  3.555 AU	gas giant
7	  6.967 AU	gas giant
8	 10.249 AU	gas giant
9	 17.937 AU	gas giant
10	 28.518 AU	gas giant
11	 40.192 AU	gas giant
12	 51.258 AU	no atmosphere



Planet 1	
   Distance from primary:	0.355	AU
   Mass:			0.039	Earth masses
   Equatorial radius:		2189.4	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.065
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		248.53	degrees Celcius
   Normal daytime temperature:	465.43	degrees Celcius
   Normal night temperature:	-182.27	degrees Celcius
   Maximum temperature:   	468.48	degrees Celcius
   Minimum temperature:   	-192.74	degrees Celcius
   Escape Velocity:		3.76	km/sec
   Molecular weight retained:	56.25 and above
   Surface acceleration:	322.28	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.063
   Length of year:		73.26	days
   Length of day:		1758.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.494	AU
   Mass:			0.595	Earth masses
   Equatorial radius:		5403.8	km
   Density:			5.378	grams/cc
   Eccentricity of orbit:	0.145
   Surface gravity:		0.83	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		167.71	degrees Celcius
   Normal daytime temperature:	366.55	degrees Celcius
   Normal night temperature:	-199.52	degrees Celcius
   Maximum temperature:   	369.91	degrees Celcius
   Minimum temperature:   	-209.63	degrees Celcius
   Escape Velocity:		9.37	km/sec
   Molecular weight retained:	9.04 and above
   Surface acceleration:	812.18	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.071
   Length of year:		120.64	days
   Length of day:		2162.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	*gas giant*
   Distance from primary:	1.091	AU
   Mass:			4.146	Earth masses
   Equatorial radius:		15826.2	km
   Density:			1.493	grams/cc
   Eccentricity of orbit:	0.260
   Escape Velocity:		14.46	km/sec
   Molecular weight retained:	3.80 and above
   Surface acceleration:	660.17	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.465
   Length of year:		395.30	days
   Length of day:		16.04	hours


Planet 4	
   Distance from primary:	1.934	AU
   Mass:			0.071	Earth masses
   Equatorial radius:		2678.5	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.004	Earth atmospheres
   Surface temperature:		-65.83	degrees Celcius
   Normal daytime temperature:	-44.17	degrees Celcius
   Normal night temperature:	-87.61	degrees Celcius
   Maximum temperature:   	-18.81	degrees Celcius
   Minimum temperature:   	-113.62	degrees Celcius
   Escape Velocity:		4.60	km/sec
   Molecular weight retained:	37.51 and above
   Surface acceleration:	395.07	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.314
   Length of year:		933.55	days
   Length of day:		24.45	hours
   Boiling point of water:	-8.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	33.22
   liquids at surface:
				Ethanol      melts at -114  boils at -21
   gasses in atmosphere:
				CarbonDioxide    36.5%  PP    1.4 mb
				Ozone            55.2%  PP    2.2 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           7.2%  PP    0.3 mb
				Xenon             1.1%  PP    0.0 mb


Planet 5	
   Distance from primary:	2.740	AU
   Mass:			1.105	Earth masses
   Equatorial radius:		6614.8	km
   Density:			5.446	grams/cc
   Eccentricity of orbit:	0.144
   Surface gravity:		1.03	Earth gees
   Surface pressure:		1.181	Earth atmospheres
   Surface temperature:		-119.87	degrees Celcius
   Normal daytime temperature:	-117.76	degrees Celcius
   Normal night temperature:	-122.10	degrees Celcius
   Maximum temperature:   	-101.47	degrees Celcius
   Minimum temperature:   	-139.79	degrees Celcius
   Escape Velocity:		11.54	km/sec
   Molecular weight retained:	5.96 and above
   Surface acceleration:	1006.81	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.765
   Length of year:		1574.18	days
   Length of day:		15.11	hours
   Boiling point of water:	104.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -110
   gasses in atmosphere:
				Nitrogen         100.0%  PP 1180.4 mb


Planet 6	*gas giant*
   Distance from primary:	3.555	AU
   Mass:			63.379	Earth masses
   Equatorial radius:		38685.4	km
   Density:			1.562	grams/cc
   Eccentricity of orbit:	0.100
   Escape Velocity:		36.15	km/sec
   Molecular weight retained:	0.61 and above
   Surface acceleration:	1688.84	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.543
   Length of year:		2325.43	days
   Length of day:		9.95	hours


Planet 7	*gas giant*
   Distance from primary:	6.967	AU
   Mass:			1262.259	Earth masses
   Equatorial radius:		97911.8	km
   Density:			1.919	grams/cc
   Eccentricity of orbit:	0.066
   Escape Velocity:		101.40	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5250.70	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.515
   Length of year:		6370.30	days
   Length of day:		5.64	hours


Planet 8	*gas giant*
   Distance from primary:	10.249	AU
   Mass:			23.007	Earth masses
   Equatorial radius:		31442.1	km
   Density:			1.056	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		24.16	km/sec
   Molecular weight retained:	1.36 and above
   Surface acceleration:	928.06	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.458
   Length of year:		11384.84	days
   Length of day:		13.42	hours


Planet 9	*gas giant*
   Distance from primary:	17.937	AU
   Mass:			24.954	Earth masses
   Equatorial radius:		33733.3	km
   Density:			0.928	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		24.29	km/sec
   Molecular weight retained:	1.35 and above
   Surface acceleration:	874.51	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.470
   Length of year:		26360.16	days
   Length of day:		13.82	hours


Planet 10	*gas giant*
   Distance from primary:	28.518	AU
   Mass:			2.232	Earth masses
   Equatorial radius:		17340.3	km
   Density:			0.611	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		10.13	km/sec
   Molecular weight retained:	7.73 and above
   Surface acceleration:	296.05	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.469
   Length of year:		52845.02	days
   Length of day:		23.75	hours


Planet 11	*gas giant*
   Distance from primary:	40.192	AU
   Mass:			1.344	Earth masses
   Equatorial radius:		15389.6	km
   Density:			0.526	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		8.35	km/sec
   Molecular weight retained:	11.40 and above
   Surface acceleration:	226.33	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.471
   Length of year:		88418.72	days
   Length of day:		27.17	hours


Planet 12	
   Distance from primary:	51.258	AU
   Mass:			0.020	Earth masses
   Equatorial radius:		2353.9	km
   Density:			2.194	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.67	degrees Celcius
   Normal daytime temperature:	-223.63	degrees Celcius
   Normal night temperature:	-237.56	degrees Celcius
   Maximum temperature:   	-213.03	degrees Celcius
   Minimum temperature:   	-248.37	degrees Celcius
   Escape Velocity:		2.61	km/sec
   Molecular weight retained:	116.80 and above
   Surface acceleration:	144.36	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.151
   Length of year:		127344.05	days
   Length of day:		39.89	hours
   Boiling point of water:	-88.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


