                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950484cb
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6360 K
Stellar class: F7
Age: 2.670 billion years  (4.228 billion left on main sequence)
Habitable ecosphere radius: 1.264 AU

Planets present at:
1	  0.423 AU	no atmosphere
2	  0.608 AU	no atmosphere
3	  0.740 AU	no atmosphere
4	  1.148 AU	no atmosphere
5	  1.461 AU	gas giant
6	  2.192 AU	no atmosphere
7	  2.940 AU	cold
8	  3.500 AU	gas giant
9	  5.710 AU	gas giant
10	 12.522 AU	gas giant
11	 26.206 AU	gas giant
12	 35.500 AU	gas giant
13	 49.222 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.423	AU
   Mass:			0.184	Earth masses
   Equatorial radius:		3669.6	km
   Density:			5.306	grams/cc
   Eccentricity of orbit:	0.225
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		200.42	degrees Celcius
   Normal daytime temperature:	405.75	degrees Celcius
   Normal night temperature:	-184.49	degrees Celcius
   Maximum temperature:   	409.71	degrees Celcius
   Minimum temperature:   	-197.58	degrees Celcius
   Escape Velocity:		6.32	km/sec
   Molecular weight retained:	19.88 and above
   Surface acceleration:	544.16	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.068
   Length of year:		95.72	days
   Length of day:		1453.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.608	AU
   Mass:			0.588	Earth masses
   Equatorial radius:		5383.5	km
   Density:			5.377	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.82	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		119.49	degrees Celcius
   Maximum temperature:   	310.41	degrees Celcius
   Minimum temperature:   	-222.56	degrees Celcius
   Escape Velocity:		9.33	km/sec
   Molecular weight retained:	9.11 and above
   Surface acceleration:	808.98	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.090
   Length of year:		164.99	days
   Length of day:		3959.70	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.740	AU
   Mass:			0.209	Earth masses
   Equatorial radius:		3829.4	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		84.87	degrees Celcius
   Normal daytime temperature:	198.05	degrees Celcius
   Normal night temperature:	-41.72	degrees Celcius
   Maximum temperature:   	219.45	degrees Celcius
   Minimum temperature:   	-68.56	degrees Celcius
   Escape Velocity:		6.60	km/sec
   Molecular weight retained:	18.23 and above
   Surface acceleration:	568.43	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.068
   Length of year:		221.64	days
   Length of day:		109.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	1.148	AU
   Mass:			0.081	Earth masses
   Equatorial radius:		2802.9	km
   Density:			5.281	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		12.95	degrees Celcius
   Normal daytime temperature:	46.72	degrees Celcius
   Normal night temperature:	-21.08	degrees Celcius
   Maximum temperature:   	75.02	degrees Celcius
   Minimum temperature:   	-49.82	degrees Celcius
   Escape Velocity:		4.82	km/sec
   Molecular weight retained:	34.23 and above
   Surface acceleration:	413.67	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.086
   Length of year:		428.39	days
   Length of day:		27.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	*gas giant*
   Distance from primary:	1.461	AU
   Mass:			7.307	Earth masses
   Equatorial radius:		19153.9	km
   Density:			1.484	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		17.44	km/sec
   Molecular weight retained:	2.61 and above
   Surface acceleration:	794.28	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.474
   Length of year:		614.77	days
   Length of day:		14.51	hours


Planet 6	
   Distance from primary:	2.192	AU
   Mass:			0.198	Earth masses
   Equatorial radius:		3763.8	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.041	Earth atmospheres
   Surface temperature:		-84.05	degrees Celcius
   Normal daytime temperature:	-71.30	degrees Celcius
   Normal night temperature:	-97.11	degrees Celcius
   Maximum temperature:   	-48.05	degrees Celcius
   Minimum temperature:   	-121.50	degrees Celcius
   Escape Velocity:		6.48	km/sec
   Molecular weight retained:	18.88 and above
   Surface acceleration:	558.47	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.489
   Length of year:		1129.73	days
   Length of day:		20.31	hours
   Boiling point of water:	28.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	63.47
   liquids at surface:
				Ethanol      melts at -114  boils at 12
				Chlorine     melts at -101  boils at -79
   gasses in atmosphere:
				Ozone            93.3%  PP   38.4 mb
				Argon             0.2%  PP    0.1 mb
				Neon              0.3%  PP    0.1 mb
				Krypton           5.6%  PP    2.3 mb
				Xenon             0.7%  PP    0.3 mb


Planet 7	
   Distance from primary:	2.940	AU
   Mass:			0.813	Earth masses
   Equatorial radius:		5986.2	km
   Density:			5.409	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.92	Earth gees
   Surface pressure:		0.697	Earth atmospheres
   Surface temperature:		-128.13	degrees Celcius
   Normal daytime temperature:	-125.44	degrees Celcius
   Normal night temperature:	-130.98	degrees Celcius
   Maximum temperature:   	-108.22	degrees Celcius
   Minimum temperature:   	-149.75	degrees Celcius
   Escape Velocity:		10.41	km/sec
   Molecular weight retained:	7.33 and above
   Surface acceleration:	904.89	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.762
   Length of year:		1754.65	days
   Length of day:		15.93	hours
   Boiling point of water:	90.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -116
   gasses in atmosphere:
				Oxygen            9.0%  PP   63.1 mb
				Nitrogen         90.9%  PP  634.1 mb


Planet 8	*gas giant*
   Distance from primary:	3.500	AU
   Mass:			3.972	Earth masses
   Equatorial radius:		17244.3	km
   Density:			1.105	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		13.55	km/sec
   Molecular weight retained:	4.32 and above
   Surface acceleration:	532.66	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.512
   Length of year:		2278.56	days
   Length of day:		17.71	hours


Planet 9	*gas giant*
   Distance from primary:	5.710	AU
   Mass:			1137.710	Earth masses
   Equatorial radius:		93540.7	km
   Density:			1.983	grams/cc
   Eccentricity of orbit:	0.064
   Escape Velocity:		98.49	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5185.25	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.464
   Length of year:		4741.78	days
   Length of day:		5.68	hours


Planet 10	*gas giant*
   Distance from primary:	12.522	AU
   Mass:			404.122	Earth masses
   Equatorial radius:		73843.1	km
   Density:			1.432	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		66.07	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	2955.50	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.493
   Length of year:		15414.45	days
   Length of day:		7.52	hours


Planet 11	*gas giant*
   Distance from primary:	26.206	AU
   Mass:			0.617	Earth masses
   Equatorial radius:		11847.8	km
   Density:			0.529	grams/cc
   Eccentricity of orbit:	0.136
   Escape Velocity:		6.44	km/sec
   Molecular weight retained:	19.11 and above
   Surface acceleration:	175.29	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.534
   Length of year:		46692.68	days
   Length of day:		30.87	hours


Planet 12	*gas giant*
   Distance from primary:	35.500	AU
   Mass:			4.106	Earth masses
   Equatorial radius:		21120.1	km
   Density:			0.622	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		12.45	km/sec
   Molecular weight retained:	5.12 and above
   Surface acceleration:	367.06	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.466
   Length of year:		73618.57	days
   Length of day:		21.33	hours


Planet 13	
   Distance from primary:	49.222	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		4729.1	km
   Density:			2.221	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.73	degrees Celcius
   Normal daytime temperature:	-224.42	degrees Celcius
   Normal night temperature:	-234.93	degrees Celcius
   Maximum temperature:   	-209.40	degrees Celcius
   Minimum temperature:   	-250.13	degrees Celcius
   Escape Velocity:		5.27	km/sec
   Molecular weight retained:	28.60 and above
   Surface acceleration:	293.48	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.139
   Length of year:		120195.84	days
   Length of day:		27.98	hours
   Boiling point of water:	-55.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


