                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d50
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6262 K
Stellar class: F8
Age: 1.701 billion years  (5.452 billion left on main sequence)
Habitable ecosphere radius: 1.235 AU

Planets present at:
1	  0.319 AU	no atmosphere
2	  0.521 AU	no atmosphere
3	  0.597 AU	no atmosphere
4	  0.729 AU	greenhouse
5	  1.091 AU	greenhouse
6	  1.828 AU	gas giant
7	  3.052 AU	gas giant
8	  4.844 AU	gas giant
9	  7.867 AU	gas giant
10	 13.129 AU	gas giant
11	 24.167 AU	gas giant
12	 36.291 AU	gas giant
13	 44.101 AU	no atmosphere



Planet 1	
   Distance from primary:	0.319	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		3538.8	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		264.54	degrees Celcius
   Normal daytime temperature:	484.43	degrees Celcius
   Normal night temperature:	-174.97	degrees Celcius
   Maximum temperature:   	487.71	degrees Celcius
   Minimum temperature:   	-186.69	degrees Celcius
   Escape Velocity:		6.09	km/sec
   Molecular weight retained:	21.39 and above
   Surface acceleration:	524.35	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.079
   Length of year:		62.95	days
   Length of day:		1510.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.521	AU
   Mass:			1/134.6	Earth masses
   Equatorial radius:		1263.8	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		150.31	degrees Celcius
   Maximum temperature:   	348.64	degrees Celcius
   Minimum temperature:   	-216.45	degrees Celcius
   Escape Velocity:		2.17	km/sec
   Molecular weight retained:	169.28 and above
   Surface acceleration:	185.53	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.055
   Length of year:		131.43	days
   Length of day:		3154.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.597	AU
   Mass:			0.566	Earth masses
   Equatorial radius:		5316.0	km
   Density:			5.373	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		122.54	degrees Celcius
   Normal daytime temperature:	233.59	degrees Celcius
   Normal night temperature:	-0.73	degrees Celcius
   Maximum temperature:   	257.81	degrees Celcius
   Minimum temperature:   	-30.41	degrees Celcius
   Escape Velocity:		9.21	km/sec
   Molecular weight retained:	9.35 and above
   Surface acceleration:	798.34	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.053
   Length of year:		161.25	days
   Length of day:		90.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.729	AU
   Mass:			0.520	Earth masses
   Equatorial radius:		5172.1	km
   Density:			5.367	grams/cc
   Eccentricity of orbit:	0.131
   Surface gravity:		0.79	Earth gees
   Surface pressure:		27.120	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		190.98	degrees Celcius
   Maximum temperature:   	199.23	degrees Celcius
   Minimum temperature:   	182.00	degrees Celcius
   Escape Velocity:		8.96	km/sec
   Molecular weight retained:	9.89 and above
   Surface acceleration:	775.72	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.500
   Length of year:		217.85	days
   Length of day:		23.30	hours
   Boiling point of water:	220.2	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 560
				Francium     melts at 27    boils at 983
				Cesium       melts at 28    boils at 1020
				Gallium      melts at 30    boils at 3265
				Rubidium     melts at 39    boils at 998
				Phosphorus   melts at 44    boils at 459
				Potassium    melts at 63    boils at 1100
				Sodium       melts at 98    boils at 1254
				Sulfur       melts at 113   boils at 676
				Indium       melts at 157   boils at 2838
				Lithium      melts at 181   boils at 1869
   gasses in atmosphere:
				Nitrogen         99.6%  PP 26999.5 mb
				Water             0.1%  PP   13.8 mb
				CarbonDioxide     0.1%  PP   26.6 mb
				Ozone             0.1%  PP   26.9 mb
				Ethanol           0.1%  PP   27.1 mb


Planet 5	
   Distance from primary:	1.091	AU
   Mass:			0.166	Earth masses
   Equatorial radius:		3549.8	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.54	Earth gees
   Surface pressure:		2.719	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		44.97	degrees Celcius
   Normal daytime temperature:	49.04	degrees Celcius
   Normal night temperature:	40.48	degrees Celcius
   Maximum temperature:   	63.82	degrees Celcius
   Minimum temperature:   	24.99	degrees Celcius
   Escape Velocity:		6.11	km/sec
   Molecular weight retained:	21.26 and above
   Surface acceleration:	526.01	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.040
   Length of year:		398.41	days
   Length of day:		22.24	hours
   Boiling point of water:	129.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 107
				Mercury      melts at -39   boils at 407
				Bromine      melts at -7    boils at 86
				Water        melts at 0     boils at 130
				Francium     melts at 27    boils at 753
				Cesium       melts at 28    boils at 783
				Gallium      melts at 30    boils at 2616
				Rubidium     melts at 39    boils at 765
				Phosphorus   melts at 44    boils at 325
   gasses in atmosphere:
				CarbonDioxide    46.2%  PP 1257.1 mb
				Ozone            50.1%  PP 1363.3 mb
				Argon             0.1%  PP    1.5 mb
				Krypton           3.2%  PP   86.6 mb
				Xenon             0.4%  PP   10.5 mb


Planet 6	*gas giant*
   Distance from primary:	1.828	AU
   Mass:			14.602	Earth masses
   Equatorial radius:		23926.6	km
   Density:			1.521	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		22.06	km/sec
   Molecular weight retained:	1.63 and above
   Surface acceleration:	1017.14	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.467
   Length of year:		864.19	days
   Length of day:		12.82	hours


Planet 7	*gas giant*
   Distance from primary:	3.052	AU
   Mass:			14.512	Earth masses
   Equatorial radius:		24926.0	km
   Density:			1.337	grams/cc
   Eccentricity of orbit:	0.144
   Escape Velocity:		21.55	km/sec
   Molecular weight retained:	1.71 and above
   Surface acceleration:	931.45	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.517
   Length of year:		1864.53	days
   Length of day:		13.39	hours


Planet 8	*gas giant*
   Distance from primary:	4.844	AU
   Mass:			21.203	Earth masses
   Equatorial radius:		28933.6	km
   Density:			1.249	grams/cc
   Eccentricity of orbit:	0.017
   Escape Velocity:		24.18	km/sec
   Molecular weight retained:	1.36 and above
   Surface acceleration:	1010.04	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.543
   Length of year:		3728.15	days
   Length of day:		12.86	hours


Planet 9	*gas giant*
   Distance from primary:	7.867	AU
   Mass:			944.516	Earth masses
   Equatorial radius:		91170.5	km
   Density:			1.778	grams/cc
   Eccentricity of orbit:	0.027
   Escape Velocity:		90.90	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4531.48	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.484
   Length of year:		7706.24	days
   Length of day:		6.07	hours


Planet 10	*gas giant*
   Distance from primary:	13.129	AU
   Mass:			4.646	Earth masses
   Equatorial radius:		20191.8	km
   Density:			0.805	grams/cc
   Eccentricity of orbit:	0.039
   Escape Velocity:		13.55	km/sec
   Molecular weight retained:	4.33 and above
   Surface acceleration:	454.39	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.534
   Length of year:		16636.83	days
   Length of day:		19.17	hours


Planet 11	*gas giant*
   Distance from primary:	24.167	AU
   Mass:			3.687	Earth masses
   Equatorial radius:		19860.2	km
   Density:			0.672	grams/cc
   Eccentricity of orbit:	0.050
   Escape Velocity:		12.17	km/sec
   Molecular weight retained:	5.36 and above
   Surface acceleration:	372.77	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.495
   Length of year:		41547.95	days
   Length of day:		21.17	hours


Planet 12	*gas giant*
   Distance from primary:	36.291	AU
   Mass:			5.954	Earth masses
   Equatorial radius:		23627.3	km
   Density:			0.644	grams/cc
   Eccentricity of orbit:	0.086
   Escape Velocity:		14.18	km/sec
   Molecular weight retained:	3.95 and above
   Surface acceleration:	425.36	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.536
   Length of year:		76456.41	days
   Length of day:		19.82	hours


Planet 13	
   Distance from primary:	44.101	AU
   Mass:			0.125	Earth masses
   Equatorial radius:		4318.1	km
   Density:			2.215	grams/cc
   Eccentricity of orbit:	0.153
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.14	degrees Celcius
   Normal daytime temperature:	-222.41	degrees Celcius
   Normal night temperature:	-233.78	degrees Celcius
   Maximum temperature:   	-206.20	degrees Celcius
   Minimum temperature:   	-250.04	degrees Celcius
   Escape Velocity:		4.80	km/sec
   Molecular weight retained:	34.39 and above
   Surface acceleration:	267.27	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.148
   Length of year:		102421.16	days
   Length of day:		29.32	hours
   Boiling point of water:	-61.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


