                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481e0
Stellar mass: 1.10 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6106 K
Stellar class: F9
Age: 1.479 billion years  (5.517 billion left on main sequence)
Habitable ecosphere radius: 1.252 AU

Planets present at:
1	  0.374 AU	no atmosphere
2	  0.585 AU	no atmosphere
3	  1.120 AU	greenhouse
4	  1.696 AU	gas giant
5	  3.226 AU	gas giant
6	  5.207 AU	gas giant
7	 13.046 AU	gas giant
8	 26.663 AU	gas giant
9	 43.151 AU	gas giant
10	 50.313 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.374	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		3423.9	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.137
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		229.97	degrees Celcius
   Normal daytime temperature:	442.07	degrees Celcius
   Normal night temperature:	-179.48	degrees Celcius
   Maximum temperature:   	445.66	degrees Celcius
   Minimum temperature:   	-191.80	degrees Celcius
   Escape Velocity:		5.89	km/sec
   Molecular weight retained:	22.87 and above
   Surface acceleration:	506.98	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.055
   Length of year:		79.73	days
   Length of day:		1453.44	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.585	AU
   Mass:			0.452	Earth masses
   Equatorial radius:		4938.7	km
   Density:			5.356	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		129.10	degrees Celcius
   Normal daytime temperature:	309.47	degrees Celcius
   Normal night temperature:	-154.99	degrees Celcius
   Maximum temperature:   	315.77	degrees Celcius
   Minimum temperature:   	-172.18	degrees Celcius
   Escape Velocity:		8.54	km/sec
   Molecular weight retained:	10.87 and above
   Surface acceleration:	739.22	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.055
   Length of year:		156.15	days
   Length of day:		544.41	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.120	AU
   Mass:			2.079	Earth masses
   Equatorial radius:		8113.8	km
   Density:			5.553	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		1.28	Earth gees
   Surface pressure:		448.826	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		465.81	degrees Celcius
   Maximum temperature:   	467.85	degrees Celcius
   Minimum temperature:   	461.76	degrees Celcius
   Escape Velocity:		14.29	km/sec
   Molecular weight retained:	3.88 and above
   Surface acceleration:	1259.20	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.621
   Length of year:		413.25	days
   Length of day:		13.58	hours
   Boiling point of water:	406.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1457
				Cesium       melts at 28    boils at 1508
				Gallium      melts at 30    boils at 4601
				Rubidium     melts at 39    boils at 1477
				Potassium    melts at 63    boils at 1619
				Sodium       melts at 98    boils at 1830
				Indium       melts at 157   boils at 4013
				Lithium      melts at 181   boils at 2678
				Selenium     melts at 217   boils at 1472
				Tin          melts at 232   boils at 5002
				Polonium     melts at 254   boils at 1976
				Bismuth      melts at 271   boils at 3073
				Thallium     melts at 304   boils at 2878
				Cadmium      melts at 321   boils at 1618
				Lead         melts at 328   boils at 3414
				Zinc         melts at 420   boils at 1876
				Tellurium    melts at 450   boils at 2027
   gasses in atmosphere:
				Sulfur            0.6%  PP 2884.6 mb
				Nitrogen          3.1%  PP 13741.4 mb
				Helium           96.3%  PP 432113.0 mb


Planet 4	*gas giant*
   Distance from primary:	1.696	AU
   Mass:			2.497	Earth masses
   Equatorial radius:		14188.6	km
   Density:			1.247	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		11.85	km/sec
   Molecular weight retained:	5.66 and above
   Surface acceleration:	494.58	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.490
   Length of year:		769.89	days
   Length of day:		18.38	hours


Planet 5	*gas giant*
   Distance from primary:	3.226	AU
   Mass:			57.175	Earth masses
   Equatorial radius:		37311.3	km
   Density:			1.571	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		34.96	km/sec
   Molecular weight retained:	0.65 and above
   Surface acceleration:	1637.83	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.541
   Length of year:		2020.69	days
   Length of day:		10.10	hours


Planet 6	*gas giant*
   Distance from primary:	5.207	AU
   Mass:			20.878	Earth masses
   Equatorial radius:		28943.5	km
   Density:			1.229	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		23.99	km/sec
   Molecular weight retained:	1.38 and above
   Surface acceleration:	993.87	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.456
   Length of year:		4142.67	days
   Length of day:		12.96	hours


Planet 7	*gas giant*
   Distance from primary:	13.046	AU
   Mass:			1828.965	Earth masses
   Equatorial radius:		115175.6	km
   Density:			1.708	grams/cc
   Eccentricity of orbit:	0.343
   Escape Velocity:		112.54	km/sec
   Molecular weight retained:	0.06 and above
   Surface acceleration:	5498.24	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.526
   Length of year:		16390.41	days
   Length of day:		5.51	hours


Planet 8	*gas giant*
   Distance from primary:	26.663	AU
   Mass:			3.308	Earth masses
   Equatorial radius:		19377.8	km
   Density:			0.649	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		11.67	km/sec
   Molecular weight retained:	5.83 and above
   Surface acceleration:	351.35	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.546
   Length of year:		48007.78	days
   Length of day:		21.80	hours


Planet 9	*gas giant*
   Distance from primary:	43.151	AU
   Mass:			0.262	Earth masses
   Equatorial radius:		9628.5	km
   Density:			0.419	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		4.66	km/sec
   Molecular weight retained:	36.56 and above
   Surface acceleration:	112.74	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.541
   Length of year:		98842.27	days
   Length of day:		38.49	hours


Planet 10	
   Distance from primary:	50.313	AU
   Mass:			0.048	Earth masses
   Equatorial radius:		3143.4	km
   Density:			2.201	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.20	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.89	degrees Celcius
   Normal daytime temperature:	-224.70	degrees Celcius
   Normal night temperature:	-236.95	degrees Celcius
   Maximum temperature:   	-214.04	degrees Celcius
   Minimum temperature:   	-247.96	degrees Celcius
   Escape Velocity:		3.49	km/sec
   Molecular weight retained:	65.30 and above
   Surface acceleration:	193.36	cm/sec2
   Axial tilt:			65	degrees
   Planetary albedo:		0.161
   Length of year:		124442.11	days
   Length of day:		34.47	hours
   Boiling point of water:	-77.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


