                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048ab2
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6172 K
Stellar class: F8
Age: 1.526 billion years  (5.178 billion left on main sequence)
Habitable ecosphere radius: 1.286 AU

Planets present at:
1	  0.431 AU	no atmosphere
2	  0.506 AU	no atmosphere
3	  0.584 AU	no atmosphere
4	  0.901 AU	greenhouse
5	  1.373 AU	gas giant
6	  3.000 AU	gas giant
7	  6.306 AU	gas giant
8	  8.999 AU	cold
9	 14.979 AU	no atmosphere
10	 21.148 AU	gas giant
11	 41.055 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.431	AU
   Mass:			0.070	Earth masses
   Equatorial radius:		2669.7	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.118
   Surface gravity:		0.40	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		197.91	degrees Celcius
   Normal daytime temperature:	403.49	degrees Celcius
   Normal night temperature:	-191.59	degrees Celcius
   Maximum temperature:   	406.83	degrees Celcius
   Minimum temperature:   	-202.23	degrees Celcius
   Escape Velocity:		4.59	km/sec
   Molecular weight retained:	37.76 and above
   Surface acceleration:	393.77	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.088
   Length of year:		97.97	days
   Length of day:		1854.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.506	AU
   Mass:			0.018	Earth masses
   Equatorial radius:		1688.2	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		163.90	degrees Celcius
   Maximum temperature:   	365.35	degrees Celcius
   Minimum temperature:   	-213.77	degrees Celcius
   Escape Velocity:		2.89	km/sec
   Molecular weight retained:	94.77 and above
   Surface acceleration:	248.10	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.068
   Length of year:		124.69	days
   Length of day:		2992.58	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.584	AU
   Mass:			0.414	Earth masses
   Equatorial radius:		4799.5	km
   Density:			5.349	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.46	degrees Celcius
   Maximum temperature:   	327.89	degrees Celcius
   Minimum temperature:   	-220.49	degrees Celcius
   Escape Velocity:		8.30	km/sec
   Molecular weight retained:	11.53 and above
   Surface acceleration:	717.55	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.068
   Length of year:		154.79	days
   Length of day:		3715.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.901	AU
   Mass:			1.197	Earth masses
   Equatorial radius:		6788.8	km
   Density:			5.457	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		1.06	Earth gees
   Surface pressure:		109.048	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		409.19	degrees Celcius
   Maximum temperature:   	413.17	degrees Celcius
   Minimum temperature:   	403.55	degrees Celcius
   Escape Velocity:		11.86	km/sec
   Molecular weight retained:	5.65 and above
   Surface acceleration:	1035.39	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.577
   Length of year:		296.54	days
   Length of day:		15.42	hours
   Boiling point of water:	297.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1181
				Cesium       melts at 28    boils at 1223
				Gallium      melts at 30    boils at 3822
				Rubidium     melts at 39    boils at 1197
				Potassium    melts at 63    boils at 1316
				Sodium       melts at 98    boils at 1494
				Sulfur       melts at 113   boils at 825
				Indium       melts at 157   boils at 3328
				Lithium      melts at 181   boils at 2206
				Selenium     melts at 217   boils at 1193
				Tin          melts at 232   boils at 4158
				Polonium     melts at 254   boils at 1617
				Bismuth      melts at 271   boils at 2538
				Thallium     melts at 304   boils at 2374
				Cadmium      melts at 321   boils at 1315
				Lead         melts at 328   boils at 2824
   gasses in atmosphere:
				Nitrogen         99.3%  PP 108236.7 mb
				Phosphorus        0.5%  PP  528.1 mb
				CarbonDioxide     0.1%  PP   55.5 mb
				Ethanol           0.1%  PP   56.0 mb


Planet 5	*gas giant*
   Distance from primary:	1.373	AU
   Mass:			4.486	Earth masses
   Equatorial radius:		16502.4	km
   Density:			1.424	grams/cc
   Eccentricity of orbit:	0.162
   Escape Velocity:		14.72	km/sec
   Molecular weight retained:	3.66 and above
   Surface acceleration:	656.85	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.499
   Length of year:		557.97	days
   Length of day:		15.96	hours


Planet 6	*gas giant*
   Distance from primary:	3.000	AU
   Mass:			42.313	Earth masses
   Equatorial radius:		33892.3	km
   Density:			1.551	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		31.56	km/sec
   Molecular weight retained:	0.80 and above
   Surface acceleration:	1468.96	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.483
   Length of year:		1801.55	days
   Length of day:		10.66	hours


Planet 7	*gas giant*
   Distance from primary:	6.306	AU
   Mass:			1436.105	Earth masses
   Equatorial radius:		100796.3	km
   Density:			2.001	grams/cc
   Eccentricity of orbit:	0.096
   Escape Velocity:		106.60	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5636.85	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.519
   Length of year:		5479.82	days
   Length of day:		5.44	hours


Planet 8	
   Distance from primary:	8.999	AU
   Mass:			0.597	Earth masses
   Equatorial radius:		7215.7	km
   Density:			2.268	grams/cc
   Eccentricity of orbit:	0.130
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.255	Earth atmospheres
   Surface temperature:		-169.92	degrees Celcius
   Normal daytime temperature:	-165.83	degrees Celcius
   Normal night temperature:	-174.26	degrees Celcius
   Maximum temperature:   	-147.26	degrees Celcius
   Minimum temperature:   	-194.68	degrees Celcius
   Escape Velocity:		8.12	km/sec
   Molecular weight retained:	12.03 and above
   Surface acceleration:	457.43	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.347
   Length of year:		9361.20	days
   Length of day:		22.41	hours
   Boiling point of water:	65.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	35.51
   liquids at surface:
				Ozone        melts at -193  boils at -127
   gasses in atmosphere:
				Oxygen           70.0%  PP  178.2 mb
				Nitrogen         30.0%  PP   76.4 mb


Planet 9	
   Distance from primary:	14.979	AU
   Mass:			0.174	Earth masses
   Equatorial radius:		4818.6	km
   Density:			2.222	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.023	Earth atmospheres
   Surface temperature:		-196.05	degrees Celcius
   Normal daytime temperature:	-188.40	degrees Celcius
   Normal night temperature:	-203.85	degrees Celcius
   Maximum temperature:   	-172.22	degrees Celcius
   Minimum temperature:   	-221.25	degrees Celcius
   Escape Velocity:		5.37	km/sec
   Molecular weight retained:	27.53 and above
   Surface acceleration:	299.21	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.288
   Length of year:		20102.80	days
   Length of day:		27.71	hours
   Boiling point of water:	19.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	25.03


Planet 10	*gas giant*
   Distance from primary:	21.148	AU
   Mass:			125.738	Earth masses
   Equatorial radius:		54794.6	km
   Density:			1.091	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		42.78	km/sec
   Molecular weight retained:	0.43 and above
   Surface acceleration:	1670.05	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.522
   Length of year:		33716.64	days
   Length of day:		10.00	hours


Planet 11	*gas giant*
   Distance from primary:	41.055	AU
   Mass:			1.036	Earth masses
   Equatorial radius:		14286.3	km
   Density:			0.507	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		7.61	km/sec
   Molecular weight retained:	13.72 and above
   Surface acceleration:	202.48	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.454
   Length of year:		91213.91	days
   Length of day:		28.72	hours


