                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504896a
Stellar mass: 1.11 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6206 K
Stellar class: F8
Age: 2.638 billion years  (4.108 billion left on main sequence)
Habitable ecosphere radius: 1.281 AU

Planets present at:
1	  0.380 AU	no atmosphere
2	  0.524 AU	no atmosphere
3	  0.860 AU	greenhouse
4	  1.218 AU	no atmosphere
5	  1.689 AU	no atmosphere
6	  1.949 AU	gas giant
7	  6.063 AU	gas giant
8	 11.350 AU	gas giant
9	 19.279 AU	gas giant
10	 29.466 AU	gas giant
11	 48.097 AU	no atmosphere



Planet 1	
   Distance from primary:	0.380	AU
   Mass:			0.088	Earth masses
   Equatorial radius:		2871.8	km
   Density:			5.283	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		228.03	degrees Celcius
   Maximum temperature:   	443.58	degrees Celcius
   Minimum temperature:   	-197.81	degrees Celcius
   Escape Velocity:		4.93	km/sec
   Molecular weight retained:	32.60 and above
   Surface acceleration:	423.98	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.082
   Length of year:		81.34	days
   Length of day:		1952.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.524	AU
   Mass:			0.368	Earth masses
   Equatorial radius:		4614.4	km
   Density:			5.341	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		154.80	degrees Celcius
   Maximum temperature:   	354.14	degrees Celcius
   Minimum temperature:   	-215.62	degrees Celcius
   Escape Velocity:		7.97	km/sec
   Molecular weight retained:	12.49 and above
   Surface acceleration:	688.84	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.072
   Length of year:		131.72	days
   Length of day:		3161.37	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.860	AU
   Mass:			1.247	Earth masses
   Equatorial radius:		6879.9	km
   Density:			5.463	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		1.07	Earth gees
   Surface pressure:		128.028	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		434.51	degrees Celcius
   Maximum temperature:   	438.30	degrees Celcius
   Minimum temperature:   	428.84	degrees Celcius
   Escape Velocity:		12.02	km/sec
   Molecular weight retained:	5.49 and above
   Surface acceleration:	1050.43	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.593
   Length of year:		276.54	days
   Length of day:		16.00	hours
   Boiling point of water:	308.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1207
				Cesium       melts at 28    boils at 1251
				Gallium      melts at 30    boils at 3897
				Rubidium     melts at 39    boils at 1225
				Potassium    melts at 63    boils at 1346
				Sodium       melts at 98    boils at 1526
				Sulfur       melts at 113   boils at 846
				Indium       melts at 157   boils at 3394
				Lithium      melts at 181   boils at 2252
				Selenium     melts at 217   boils at 1220
				Tin          melts at 232   boils at 4240
				Polonium     melts at 254   boils at 1652
				Bismuth      melts at 271   boils at 2590
				Thallium     melts at 304   boils at 2423
				Cadmium      melts at 321   boils at 1345
				Lead         melts at 328   boils at 2881
				Zinc         melts at 420   boils at 1566
   gasses in atmosphere:
				Nitrogen         99.2%  PP 127043.7 mb
				Phosphorus        0.5%  PP  646.8 mb
				CarbonDioxide     0.1%  PP   69.1 mb
				Ethanol           0.1%  PP   69.8 mb


Planet 4	
   Distance from primary:	1.218	AU
   Mass:			0.060	Earth masses
   Equatorial radius:		2538.2	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		9.06	degrees Celcius
   Normal daytime temperature:	43.44	degrees Celcius
   Normal night temperature:	-25.59	degrees Celcius
   Maximum temperature:   	72.50	degrees Celcius
   Minimum temperature:   	-55.11	degrees Celcius
   Escape Velocity:		4.36	km/sec
   Molecular weight retained:	41.80 and above
   Surface acceleration:	374.15	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.054
   Length of year:		466.38	days
   Length of day:		28.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 5	
   Distance from primary:	1.689	AU
   Mass:			0.276	Earth masses
   Equatorial radius:		4196.1	km
   Density:			5.325	grams/cc
   Eccentricity of orbit:	0.057
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.068	Earth atmospheres
   Surface temperature:		-51.97	degrees Celcius
   Normal daytime temperature:	-39.52	degrees Celcius
   Normal night temperature:	-64.81	degrees Celcius
   Maximum temperature:   	-13.69	degrees Celcius
   Minimum temperature:   	-91.89	degrees Celcius
   Escape Velocity:		7.24	km/sec
   Molecular weight retained:	15.15 and above
   Surface acceleration:	624.43	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.463
   Length of year:		761.62	days
   Length of day:		19.27	hours
   Boiling point of water:	38.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.27
   Ice cover percentage:	60.75
   liquids at surface:
				Ethanol      melts at -114  boils at 21
   gasses in atmosphere:
				Oxygen           98.6%  PP   67.0 mb
				CarbonDioxide     0.7%  PP    0.4 mb
				Ozone             0.7%  PP    0.5 mb


Planet 6	*gas giant*
   Distance from primary:	1.949	AU
   Mass:			33.752	Earth masses
   Equatorial radius:		30620.1	km
   Density:			1.678	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		29.65	km/sec
   Molecular weight retained:	0.90 and above
   Surface acceleration:	1435.58	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.527
   Length of year:		944.45	days
   Length of day:		10.79	hours


Planet 7	*gas giant*
   Distance from primary:	6.063	AU
   Mass:			150.781	Earth masses
   Equatorial radius:		52079.5	km
   Density:			1.523	grams/cc
   Eccentricity of orbit:	0.101
   Escape Velocity:		48.05	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2216.92	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.464
   Length of year:		5179.22	days
   Length of day:		8.68	hours


Planet 8	*gas giant*
   Distance from primary:	11.350	AU
   Mass:			250.914	Earth masses
   Equatorial radius:		63661.1	km
   Density:			1.388	grams/cc
   Eccentricity of orbit:	0.129
   Escape Velocity:		56.07	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2468.97	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.536
   Length of year:		13266.08	days
   Length of day:		8.23	hours


Planet 9	*gas giant*
   Distance from primary:	19.279	AU
   Mass:			6.727	Earth masses
   Equatorial radius:		23153.9	km
   Density:			0.773	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		15.22	km/sec
   Molecular weight retained:	3.43 and above
   Surface acceleration:	500.36	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.461
   Length of year:		29376.27	days
   Length of day:		18.27	hours


Planet 10	*gas giant*
   Distance from primary:	29.466	AU
   Mass:			38.938	Earth masses
   Equatorial radius:		40031.0	km
   Density:			0.866	grams/cc
   Eccentricity of orbit:	0.117
   Escape Velocity:		27.85	km/sec
   Molecular weight retained:	1.02 and above
   Surface acceleration:	968.99	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.472
   Length of year:		55503.41	days
   Length of day:		13.13	hours


Planet 11	
   Distance from primary:	48.097	AU
   Mass:			0.184	Earth masses
   Equatorial radius:		4905.2	km
   Density:			2.223	grams/cc
   Eccentricity of orbit:	0.088
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.88	degrees Celcius
   Normal daytime temperature:	-223.56	degrees Celcius
   Normal night temperature:	-234.10	degrees Celcius
   Maximum temperature:   	-208.02	degrees Celcius
   Minimum temperature:   	-249.83	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.55 and above
   Surface acceleration:	304.77	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.138
   Length of year:		115755.98	days
   Length of day:		27.45	hours
   Boiling point of water:	-52.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


