                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950487af
Stellar mass: 1.11 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6276 K
Stellar class: F8
Age: 1.759 billion years  (5.043 billion left on main sequence)
Habitable ecosphere radius: 1.275 AU

Planets present at:
1	  0.312 AU	no atmosphere
2	  0.534 AU	no atmosphere
3	  0.666 AU	no atmosphere
4	  1.099 AU	greenhouse
5	  1.323 AU	no atmosphere
6	  2.925 AU	gas giant
7	  5.304 AU	gas giant
8	 10.011 AU	gas giant
9	 14.175 AU	cold
10	 18.449 AU	gas giant
11	 43.158 AU	gas giant



Planet 1	
   Distance from primary:	0.312	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		3179.4	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		280.01	degrees Celcius
   Normal daytime temperature:	503.09	degrees Celcius
   Normal night temperature:	-171.03	degrees Celcius
   Maximum temperature:   	506.25	degrees Celcius
   Minimum temperature:   	-182.50	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.55 and above
   Surface acceleration:	470.12	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.072
   Length of year:		60.58	days
   Length of day:		1453.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.534	AU
   Mass:			0.047	Earth masses
   Equatorial radius:		2331.3	km
   Density:			5.270	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.90	degrees Celcius
   Maximum temperature:   	347.05	degrees Celcius
   Minimum temperature:   	-217.39	degrees Celcius
   Escape Velocity:		4.00	km/sec
   Molecular weight retained:	49.58 and above
   Surface acceleration:	343.37	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.079
   Length of year:		135.63	days
   Length of day:		3255.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.666	AU
   Mass:			0.358	Earth masses
   Equatorial radius:		4572.8	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.099
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		107.22	degrees Celcius
   Normal daytime temperature:	183.53	degrees Celcius
   Normal night temperature:	27.22	degrees Celcius
   Maximum temperature:   	215.15	degrees Celcius
   Minimum temperature:   	-6.80	degrees Celcius
   Escape Velocity:		7.90	km/sec
   Molecular weight retained:	12.72 and above
   Surface acceleration:	682.40	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.057
   Length of year:		188.67	days
   Length of day:		53.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.099	AU
   Mass:			2.509	Earth masses
   Equatorial radius:		8617.3	km
   Density:			5.595	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		1.37	Earth gees
   Surface pressure:		614.381	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		572.46	degrees Celcius
   Maximum temperature:   	573.79	degrees Celcius
   Minimum temperature:   	567.99	degrees Celcius
   Escape Velocity:		15.24	km/sec
   Molecular weight retained:	3.42 and above
   Surface acceleration:	1347.43	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.514
   Length of year:		400.12	days
   Length of day:		13.14	hours
   Boiling point of water:	436.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1534
				Cesium       melts at 28    boils at 1587
				Gallium      melts at 30    boils at 4816
				Rubidium     melts at 39    boils at 1555
				Potassium    melts at 63    boils at 1702
				Sodium       melts at 98    boils at 1923
				Indium       melts at 157   boils at 4202
				Lithium      melts at 181   boils at 2808
				Selenium     melts at 217   boils at 1549
				Tin          melts at 232   boils at 5235
				Polonium     melts at 254   boils at 2076
				Bismuth      melts at 271   boils at 3220
				Thallium     melts at 304   boils at 3017
				Cadmium      melts at 321   boils at 1701
				Lead         melts at 328   boils at 3576
				Zinc         melts at 420   boils at 1971
				Tellurium    melts at 450   boils at 2129
   gasses in atmosphere:
				Sulfur            0.1%  PP  854.8 mb
				Nitrogen          0.7%  PP 4159.8 mb
				Helium           99.2%  PP 609340.8 mb


Planet 5	
   Distance from primary:	1.323	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		2456.7	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-5.34	degrees Celcius
   Normal daytime temperature:	25.82	degrees Celcius
   Normal night temperature:	-36.69	degrees Celcius
   Maximum temperature:   	54.16	degrees Celcius
   Minimum temperature:   	-65.48	degrees Celcius
   Escape Velocity:		4.22	km/sec
   Molecular weight retained:	44.63 and above
   Surface acceleration:	362.01	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.084
   Length of year:		528.83	days
   Length of day:		26.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	*gas giant*
   Distance from primary:	2.925	AU
   Mass:			504.717	Earth masses
   Equatorial radius:		69745.3	km
   Density:			2.123	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		75.97	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	4137.68	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.534
   Length of year:		1736.55	days
   Length of day:		6.35	hours


Planet 7	*gas giant*
   Distance from primary:	5.304	AU
   Mass:			352.569	Earth masses
   Equatorial radius:		66011.0	km
   Density:			1.749	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		65.27	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3226.64	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.513
   Length of year:		4241.97	days
   Length of day:		7.20	hours


Planet 8	*gas giant*
   Distance from primary:	10.011	AU
   Mass:			32.738	Earth masses
   Equatorial radius:		34797.5	km
   Density:			1.109	grams/cc
   Eccentricity of orbit:	0.009
   Escape Velocity:		27.39	km/sec
   Molecular weight retained:	1.06 and above
   Surface acceleration:	1078.18	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.480
   Length of year:		11004.34	days
   Length of day:		12.45	hours


Planet 9	
   Distance from primary:	14.175	AU
   Mass:			0.435	Earth masses
   Equatorial radius:		6508.9	km
   Density:			2.252	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.121	Earth atmospheres
   Surface temperature:		-191.40	degrees Celcius
   Normal daytime temperature:	-186.84	degrees Celcius
   Normal night temperature:	-196.19	degrees Celcius
   Maximum temperature:   	-169.97	degrees Celcius
   Minimum temperature:   	-214.75	degrees Celcius
   Escape Velocity:		7.30	km/sec
   Molecular weight retained:	14.88 and above
   Surface acceleration:	409.74	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.316
   Length of year:		18541.14	days
   Length of day:		23.68	hours
   Boiling point of water:	49.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	28.41
   liquids at surface:
				Ozone        melts at -193  boils at -134
   gasses in atmosphere:
				Neon             100.0%  PP  120.8 mb


Planet 10	*gas giant*
   Distance from primary:	18.449	AU
   Mass:			118.562	Earth masses
   Equatorial radius:		53294.6	km
   Density:			1.118	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		42.12	km/sec
   Molecular weight retained:	0.45 and above
   Surface acceleration:	1664.63	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.473
   Length of year:		27524.79	days
   Length of day:		10.02	hours


Planet 11	*gas giant*
   Distance from primary:	43.158	AU
   Mass:			4.851	Earth masses
   Equatorial radius:		22519.8	km
   Density:			0.606	grams/cc
   Eccentricity of orbit:	0.269
   Escape Velocity:		13.11	km/sec
   Molecular weight retained:	4.62 and above
   Surface acceleration:	381.42	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.484
   Length of year:		98499.30	days
   Length of day:		20.93	hours


