                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b73
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6168 K
Stellar class: F8
Age: 2.308 billion years  (4.911 billion left on main sequence)
Habitable ecosphere radius: 1.228 AU

Planets present at:
1	  0.378 AU	no atmosphere
2	  0.613 AU	no atmosphere
3	  1.149 AU	high pressure
4	  2.222 AU	cold
5	  2.814 AU	cold
6	  3.593 AU	gas giant
7	  5.254 AU	cold
8	  9.551 AU	gas giant
9	 14.505 AU	gas giant
10	 26.562 AU	gas giant
11	 37.536 AU	gas giant
12	 49.696 AU	no atmosphere



Planet 1	
   Distance from primary:	0.378	AU
   Mass:			0.178	Earth masses
   Equatorial radius:		3629.3	km
   Density:			5.305	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		221.52	degrees Celcius
   Maximum temperature:   	435.66	degrees Celcius
   Minimum temperature:   	-198.89	degrees Celcius
   Escape Velocity:		6.25	km/sec
   Molecular weight retained:	20.33 and above
   Surface acceleration:	538.04	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.063
   Length of year:		81.30	days
   Length of day:		1951.15	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.613	AU
   Mass:			0.552	Earth masses
   Equatorial radius:		5274.9	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.160
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		112.57	degrees Celcius
   Normal daytime temperature:	281.43	degrees Celcius
   Normal night temperature:	-131.08	degrees Celcius
   Maximum temperature:   	290.78	degrees Celcius
   Minimum temperature:   	-153.36	degrees Celcius
   Escape Velocity:		9.14	km/sec
   Molecular weight retained:	9.50 and above
   Surface acceleration:	791.86	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.088
   Length of year:		168.07	days
   Length of day:		360.45	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	1.149	AU
   Mass:			2.685	Earth masses
   Equatorial radius:		8805.9	km
   Density:			5.611	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		1.41	Earth gees
   Surface pressure:		7.411	Earth atmospheres
   Surface temperature:		22.38	degrees Celcius
   Normal daytime temperature:	23.80	degrees Celcius
   Normal night temperature:	20.86	degrees Celcius
   Maximum temperature:   	33.66	degrees Celcius
   Minimum temperature:   	10.54	degrees Celcius
   Escape Velocity:		15.60	km/sec
   Molecular weight retained:	3.26 and above
   Surface acceleration:	1381.00	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.633
   Length of year:		431.22	days
   Length of day:		12.97	hours
   Boiling point of water:	164.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.57
   liquids at surface:
				Ethanol      melts at -114  boils at 140
				Mercury      melts at -39   boils at 466
				Bromine      melts at -7    boils at 117
				Water        melts at 0     boils at 165
   gasses in atmosphere:
				Nitrogen          0.6%  PP   41.6 mb
				Helium           99.4%  PP 7369.3 mb


Planet 4	
   Distance from primary:	2.222	AU
   Mass:			1.279	Earth masses
   Equatorial radius:		6936.6	km
   Density:			5.467	grams/cc
   Eccentricity of orbit:	0.200
   Surface gravity:		1.08	Earth gees
   Surface pressure:		1.734	Earth atmospheres
   Surface temperature:		-92.12	degrees Celcius
   Normal daytime temperature:	-90.10	degrees Celcius
   Normal night temperature:	-94.26	degrees Celcius
   Maximum temperature:   	-73.23	degrees Celcius
   Minimum temperature:   	-112.41	degrees Celcius
   Escape Velocity:		12.13	km/sec
   Molecular weight retained:	5.40 and above
   Surface acceleration:	1059.82	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.689
   Length of year:		1159.66	days
   Length of day:		14.72	hours
   Boiling point of water:	115.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 93
				Chlorine     melts at -101  boils at -24
   gasses in atmosphere:
				Oxygen            1.0%  PP   16.9 mb
				Nitrogen         98.9%  PP 1716.0 mb


Planet 5	
   Distance from primary:	2.814	AU
   Mass:			0.632	Earth masses
   Equatorial radius:		5513.7	km
   Density:			5.383	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.85	Earth gees
   Surface pressure:		0.348	Earth atmospheres
   Surface temperature:		-111.33	degrees Celcius
   Normal daytime temperature:	-107.03	degrees Celcius
   Normal night temperature:	-115.85	degrees Celcius
   Maximum temperature:   	-87.38	degrees Celcius
   Minimum temperature:   	-137.11	degrees Celcius
   Escape Velocity:		9.56	km/sec
   Molecular weight retained:	8.68 and above
   Surface acceleration:	829.55	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.613
   Length of year:		1652.41	days
   Length of day:		16.64	hours
   Boiling point of water:	73.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	78.39
   liquids at surface:
				Ethanol      melts at -114  boils at 53
   gasses in atmosphere:
				Oxygen           33.7%  PP  117.1 mb
				Nitrogen         66.2%  PP  230.3 mb


Planet 6	*gas giant*
   Distance from primary:	3.593	AU
   Mass:			325.123	Earth masses
   Equatorial radius:		62606.1	km
   Density:			1.891	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		64.36	km/sec
   Molecular weight retained:	0.19 and above
   Surface acceleration:	3307.91	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.471
   Length of year:		2383.97	days
   Length of day:		7.11	hours


Planet 7	
   Distance from primary:	5.254	AU
   Mass:			0.468	Earth masses
   Equatorial radius:		6665.1	km
   Density:			2.256	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.151	Earth atmospheres
   Surface temperature:		-141.72	degrees Celcius
   Normal daytime temperature:	-135.04	degrees Celcius
   Normal night temperature:	-148.77	degrees Celcius
   Maximum temperature:   	-117.56	degrees Celcius
   Minimum temperature:   	-167.66	degrees Celcius
   Escape Velocity:		7.48	km/sec
   Molecular weight retained:	14.17 and above
   Surface acceleration:	420.20	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.331
   Length of year:		4216.50	days
   Length of day:		23.38	hours
   Boiling point of water:	54.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	31.45
   liquids at surface:
				Ozone        melts at -193  boils at -132
   gasses in atmosphere:
				Oxygen           99.9%  PP  150.7 mb


Planet 8	*gas giant*
   Distance from primary:	9.551	AU
   Mass:			6.282	Earth masses
   Equatorial radius:		21482.7	km
   Density:			0.904	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		15.27	km/sec
   Molecular weight retained:	3.40 and above
   Surface acceleration:	542.81	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.540
   Length of year:		10334.50	days
   Length of day:		17.54	hours


Planet 9	*gas giant*
   Distance from primary:	14.505	AU
   Mass:			474.039	Earth masses
   Equatorial radius:		78502.6	km
   Density:			1.398	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		69.40	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3067.50	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.487
   Length of year:		19330.82	days
   Length of day:		7.38	hours


Planet 10	*gas giant*
   Distance from primary:	26.562	AU
   Mass:			0.682	Earth masses
   Equatorial radius:		12243.7	km
   Density:			0.530	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		6.67	km/sec
   Molecular weight retained:	17.86 and above
   Surface acceleration:	181.51	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.546
   Length of year:		47933.94	days
   Length of day:		30.34	hours


Planet 11	*gas giant*
   Distance from primary:	37.536	AU
   Mass:			2.196	Earth masses
   Equatorial radius:		17720.9	km
   Density:			0.563	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		9.94	km/sec
   Molecular weight retained:	8.03 and above
   Surface acceleration:	278.86	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.477
   Length of year:		80520.53	days
   Length of day:		24.48	hours


Planet 12	
   Distance from primary:	49.696	AU
   Mass:			0.099	Earth masses
   Equatorial radius:		3999.0	km
   Density:			2.211	grams/cc
   Eccentricity of orbit:	0.062
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.79	degrees Celcius
   Normal daytime temperature:	-225.20	degrees Celcius
   Normal night temperature:	-236.25	degrees Celcius
   Maximum temperature:   	-209.78	degrees Celcius
   Minimum temperature:   	-251.61	degrees Celcius
   Escape Velocity:		4.45	km/sec
   Molecular weight retained:	40.17 and above
   Surface acceleration:	247.05	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.141
   Length of year:		122666.60	days
   Length of day:		30.49	hours
   Boiling point of water:	-64.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


