                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047db7
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6099 K
Stellar class: F9
Age: 5.397 billion years  (1.742 billion left on main sequence)
Habitable ecosphere radius: 1.236 AU

Planets present at:
1	  0.350 AU	no atmosphere
2	  0.409 AU	no atmosphere
3	  0.486 AU	no atmosphere
4	  0.729 AU	greenhouse
5	  1.725 AU	cold
6	  3.183 AU	gas giant
7	  9.769 AU	gas giant
8	 20.771 AU	gas giant
9	 27.379 AU	gas giant
10	 40.797 AU	no atmosphere
11	 51.121 AU	no atmosphere



Planet 1	
   Distance from primary:	0.350	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1944.3	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		240.64	degrees Celcius
   Normal daytime temperature:	455.75	degrees Celcius
   Normal night temperature:	-183.12	degrees Celcius
   Maximum temperature:   	458.91	degrees Celcius
   Minimum temperature:   	-193.87	degrees Celcius
   Escape Velocity:		3.33	km/sec
   Molecular weight retained:	71.38 and above
   Surface acceleration:	285.97	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.079
   Length of year:		72.26	days
   Length of day:		1734.21	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.409	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		1533.2	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		203.57	degrees Celcius
   Maximum temperature:   	413.86	degrees Celcius
   Minimum temperature:   	-203.80	degrees Celcius
   Escape Velocity:		2.63	km/sec
   Molecular weight retained:	114.93 and above
   Surface acceleration:	225.24	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.064
   Length of year:		91.55	days
   Length of day:		2197.28	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.486	AU
   Mass:			0.493	Earth masses
   Equatorial radius:		5081.6	km
   Density:			5.362	grams/cc
   Eccentricity of orbit:	0.109
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		162.36	degrees Celcius
   Maximum temperature:   	363.34	degrees Celcius
   Minimum temperature:   	-211.16	degrees Celcius
   Escape Velocity:		8.80	km/sec
   Molecular weight retained:	10.26 and above
   Surface acceleration:	761.53	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.081
   Length of year:		118.51	days
   Length of day:		2285.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 4	
   Distance from primary:	0.729	AU
   Mass:			1.256	Earth masses
   Equatorial radius:		6897.2	km
   Density:			5.464	grams/cc
   Eccentricity of orbit:	0.265
   Surface gravity:		1.07	Earth gees
   Surface pressure:		124.969	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		512.71	degrees Celcius
   Maximum temperature:   	516.92	degrees Celcius
   Minimum temperature:   	505.46	degrees Celcius
   Escape Velocity:		12.05	km/sec
   Molecular weight retained:	5.46 and above
   Surface acceleration:	1053.29	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.515
   Length of year:		217.66	days
   Length of day:		24.68	hours
   Boiling point of water:	306.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1203
				Cesium       melts at 28    boils at 1247
				Gallium      melts at 30    boils at 3886
				Rubidium     melts at 39    boils at 1220
				Potassium    melts at 63    boils at 1341
				Sodium       melts at 98    boils at 1521
				Indium       melts at 157   boils at 3384
				Lithium      melts at 181   boils at 2245
				Selenium     melts at 217   boils at 1216
				Tin          melts at 232   boils at 4228
				Polonium     melts at 254   boils at 1646
				Bismuth      melts at 271   boils at 2582
				Thallium     melts at 304   boils at 2416
				Cadmium      melts at 321   boils at 1340
				Lead         melts at 328   boils at 2873
				Zinc         melts at 420   boils at 1561
				Tellurium    melts at 450   boils at 1690
   gasses in atmosphere:
				Sulfur           23.0%  PP 28804.2 mb
				Nitrogen         76.3%  PP 95310.4 mb
				Phosphorus        0.5%  PP  571.2 mb
				CarbonDioxide     0.1%  PP   64.5 mb
				Ethanol           0.1%  PP   65.7 mb


Planet 5	
   Distance from primary:	1.725	AU
   Mass:			1.297	Earth masses
   Equatorial radius:		6968.8	km
   Density:			5.469	grams/cc
   Eccentricity of orbit:	0.169
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.745	Earth atmospheres
   Surface temperature:		-64.99	degrees Celcius
   Normal daytime temperature:	-62.68	degrees Celcius
   Normal night temperature:	-67.44	degrees Celcius
   Maximum temperature:   	-45.77	degrees Celcius
   Minimum temperature:   	-85.51	degrees Celcius
   Escape Velocity:		12.18	km/sec
   Molecular weight retained:	5.35 and above
   Surface acceleration:	1065.15	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.677
   Length of year:		792.03	days
   Length of day:		14.72	hours
   Boiling point of water:	116.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.22
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 94
				Chlorine     melts at -101  boils at -24
				Ammonia      melts at -78   boils at -23
				Radon        melts at -71   boils at -53
   gasses in atmosphere:
				Nitrogen         99.9%  PP 1742.8 mb
				CarbonDioxide     0.1%  PP    0.9 mb
				Ozone             0.1%  PP    1.0 mb


Planet 6	*gas giant*
   Distance from primary:	3.183	AU
   Mass:			744.325	Earth masses
   Equatorial radius:		78866.6	km
   Density:			2.165	grams/cc
   Eccentricity of orbit:	0.179
   Escape Velocity:		86.76	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4772.17	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.508
   Length of year:		1983.61	days
   Length of day:		5.92	hours


Planet 7	*gas giant*
   Distance from primary:	9.769	AU
   Mass:			1085.795	Earth masses
   Equatorial radius:		96672.7	km
   Density:			1.715	grams/cc
   Eccentricity of orbit:	0.126
   Escape Velocity:		94.65	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4633.18	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.514
   Length of year:		10659.26	days
   Length of day:		6.00	hours


Planet 8	*gas giant*
   Distance from primary:	20.771	AU
   Mass:			0.623	Earth masses
   Equatorial radius:		11676.8	km
   Density:			0.559	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		6.53	km/sec
   Molecular weight retained:	18.64 and above
   Surface acceleration:	182.34	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.488
   Length of year:		33097.03	days
   Length of day:		30.27	hours


Planet 9	*gas giant*
   Distance from primary:	27.379	AU
   Mass:			32.161	Earth masses
   Equatorial radius:		37741.0	km
   Density:			0.854	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		26.07	km/sec
   Molecular weight retained:	1.17 and above
   Surface acceleration:	900.42	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.542
   Length of year:		50085.46	days
   Length of day:		13.62	hours


Planet 10	
   Distance from primary:	40.797	AU
   Mass:			0.288	Earth masses
   Equatorial radius:		5684.7	km
   Density:			2.236	grams/cc
   Eccentricity of orbit:	0.086
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-225.85	degrees Celcius
   Normal daytime temperature:	-220.54	degrees Celcius
   Normal night temperature:	-231.08	degrees Celcius
   Maximum temperature:   	-207.18	degrees Celcius
   Minimum temperature:   	-245.09	degrees Celcius
   Escape Velocity:		6.36	km/sec
   Molecular weight retained:	19.65 and above
   Surface acceleration:	355.29	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.158
   Length of year:		91106.85	days
   Length of day:		25.43	hours
   Boiling point of water:	-45.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 11	
   Distance from primary:	51.121	AU
   Mass:			0.076	Earth masses
   Equatorial radius:		3666.4	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.27	degrees Celcius
   Normal daytime temperature:	-225.53	degrees Celcius
   Normal night temperature:	-236.88	degrees Celcius
   Maximum temperature:   	-213.73	degrees Celcius
   Minimum temperature:   	-249.00	degrees Celcius
   Escape Velocity:		4.07	km/sec
   Molecular weight retained:	47.88 and above
   Surface acceleration:	226.10	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.142
   Length of year:		127795.75	days
   Length of day:		31.87	hours
   Boiling point of water:	-70.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


