                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048801
Stellar mass: 1.11 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6347 K
Stellar class: F7
Age: 2.941 billion years  (3.851 billion left on main sequence)
Habitable ecosphere radius: 1.276 AU

Planets present at:
1	  0.332 AU	no atmosphere
2	  0.536 AU	no atmosphere
3	  0.665 AU	no atmosphere
4	  1.003 AU	no atmosphere
5	  1.138 AU	greenhouse
6	  1.562 AU	cold
7	  2.360 AU	gas giant
8	  4.707 AU	gas giant
9	  8.598 AU	gas giant
10	 16.906 AU	gas giant
11	 28.287 AU	no atmosphere
12	 41.203 AU	gas giant
13	 50.967 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.332	AU
   Mass:			0.203	Earth masses
   Equatorial radius:		3793.6	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		261.13	degrees Celcius
   Normal daytime temperature:	479.54	degrees Celcius
   Normal night temperature:	-168.95	degrees Celcius
   Maximum temperature:   	483.10	degrees Celcius
   Minimum temperature:   	-181.78	degrees Celcius
   Escape Velocity:		6.54	km/sec
   Molecular weight retained:	18.58 and above
   Surface acceleration:	562.99	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.086
   Length of year:		66.52	days
   Length of day:		1263.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.536	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2224.1	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		149.77	degrees Celcius
   Maximum temperature:   	347.93	degrees Celcius
   Minimum temperature:   	-216.68	degrees Celcius
   Escape Velocity:		3.82	km/sec
   Molecular weight retained:	54.50 and above
   Surface acceleration:	327.43	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.067
   Length of year:		136.32	days
   Length of day:		3271.75	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.665	AU
   Mass:			0.440	Earth masses
   Equatorial radius:		4894.3	km
   Density:			5.354	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.75	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		106.81	degrees Celcius
   Normal daytime temperature:	265.34	degrees Celcius
   Normal night temperature:	-105.99	degrees Celcius
   Maximum temperature:   	276.42	degrees Celcius
   Minimum temperature:   	-128.15	degrees Celcius
   Escape Velocity:		8.47	km/sec
   Molecular weight retained:	11.07 and above
   Surface acceleration:	732.30	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.065
   Length of year:		188.26	days
   Length of day:		259.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.003	AU
   Mass:			0.144	Earth masses
   Equatorial radius:		3387.0	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		35.00	degrees Celcius
   Normal daytime temperature:	70.93	degrees Celcius
   Normal night temperature:	-1.29	degrees Celcius
   Maximum temperature:   	100.36	degrees Celcius
   Minimum temperature:   	-31.24	degrees Celcius
   Escape Velocity:		5.83	km/sec
   Molecular weight retained:	23.37 and above
   Surface acceleration:	501.41	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.079
   Length of year:		349.16	days
   Length of day:		26.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 5	
   Distance from primary:	1.138	AU
   Mass:			0.619	Earth masses
   Equatorial radius:		5474.0	km
   Density:			5.381	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.84	Earth gees
   Surface pressure:		40.909	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		155.11	degrees Celcius
   Maximum temperature:   	161.09	degrees Celcius
   Minimum temperature:   	148.70	degrees Celcius
   Escape Velocity:		9.49	km/sec
   Molecular weight retained:	8.81 and above
   Surface acceleration:	823.27	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.549
   Length of year:		421.70	days
   Length of day:		17.18	hours
   Boiling point of water:	240.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 595
				Francium     melts at 27    boils at 1036
				Cesium       melts at 28    boils at 1074
				Gallium      melts at 30    boils at 3413
				Rubidium     melts at 39    boils at 1051
				Phosphorus   melts at 44    boils at 490
				Potassium    melts at 63    boils at 1158
				Sodium       melts at 98    boils at 1317
				Sulfur       melts at 113   boils at 716
				Iodine       melts at 114   boils at 358
   gasses in atmosphere:
				Nitrogen         99.6%  PP 40754.7 mb
				CarbonDioxide     0.1%  PP   33.5 mb
				Ozone             0.1%  PP   32.5 mb
				Ethanol           0.1%  PP   34.1 mb


Planet 6	
   Distance from primary:	1.562	AU
   Mass:			1.088	Earth masses
   Equatorial radius:		6582.5	km
   Density:			5.444	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		1.02	Earth gees
   Surface pressure:		0.870	Earth atmospheres
   Surface temperature:		-3.07	degrees Celcius
   Normal daytime temperature:	1.25	degrees Celcius
   Normal night temperature:	-7.64	degrees Celcius
   Maximum temperature:   	22.83	degrees Celcius
   Minimum temperature:   	-30.51	degrees Celcius
   Escape Velocity:		11.48	km/sec
   Molecular weight retained:	6.02 and above
   Surface acceleration:	1001.52	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.226
   Length of year:		678.21	days
   Length of day:		15.18	hours
   Boiling point of water:	96.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	10.05
   Ice cover percentage:	11.99
   liquids at surface:
				Ethanol      melts at -114  boils at 75
				Mercury      melts at -39   boils at 350
				Bromine      melts at -7    boils at 56
   gasses in atmosphere:
				Oxygen           29.6%  PP  257.9 mb
				Nitrogen         70.2%  PP  610.9 mb


Planet 7	*gas giant*
   Distance from primary:	2.360	AU
   Mass:			131.806	Earth masses
   Equatorial radius:		46306.8	km
   Density:			1.894	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		47.65	km/sec
   Molecular weight retained:	0.35 and above
   Surface acceleration:	2451.24	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.452
   Length of year:		1259.29	days
   Length of day:		8.26	hours


Planet 8	*gas giant*
   Distance from primary:	4.707	AU
   Mass:			104.184	Earth masses
   Equatorial radius:		45797.4	km
   Density:			1.548	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		42.60	km/sec
   Molecular weight retained:	0.44 and above
   Surface acceleration:	1980.88	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.484
   Length of year:		3547.16	days
   Length of day:		9.18	hours


Planet 9	*gas giant*
   Distance from primary:	8.598	AU
   Mass:			75.361	Earth masses
   Equatorial radius:		43814.4	km
   Density:			1.278	grams/cc
   Eccentricity of orbit:	0.100
   Escape Velocity:		37.04	km/sec
   Molecular weight retained:	0.58 and above
   Surface acceleration:	1565.49	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.546
   Length of year:		8756.03	days
   Length of day:		10.33	hours


Planet 10	*gas giant*
   Distance from primary:	16.906	AU
   Mass:			676.170	Earth masses
   Equatorial radius:		87906.1	km
   Density:			1.420	grams/cc
   Eccentricity of orbit:	0.197
   Escape Velocity:		78.33	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3489.45	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.458
   Length of year:		24121.82	days
   Length of day:		6.92	hours


Planet 11	
   Distance from primary:	28.287	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		2644.4	km
   Density:			2.197	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-216.33	degrees Celcius
   Normal daytime temperature:	-207.36	degrees Celcius
   Normal night temperature:	-225.22	degrees Celcius
   Maximum temperature:   	-192.74	degrees Celcius
   Minimum temperature:   	-240.24	degrees Celcius
   Escape Velocity:		2.93	km/sec
   Molecular weight retained:	92.46 and above
   Surface acceleration:	162.34	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.162
   Length of year:		52256.20	days
   Length of day:		37.62	hours
   Boiling point of water:	-84.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04
   liquids at surface:
				Oxygen       melts at -218  boils at -213


Planet 12	*gas giant*
   Distance from primary:	41.203	AU
   Mass:			1.045	Earth masses
   Equatorial radius:		14333.2	km
   Density:			0.506	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		7.62	km/sec
   Molecular weight retained:	13.66 and above
   Surface acceleration:	202.75	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.498
   Length of year:		91865.71	days
   Length of day:		28.70	hours


Planet 13	
   Distance from primary:	50.967	AU
   Mass:			0.069	Earth masses
   Equatorial radius:		3548.4	km
   Density:			2.205	grams/cc
   Eccentricity of orbit:	0.111
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.74	degrees Celcius
   Normal daytime temperature:	-224.84	degrees Celcius
   Normal night temperature:	-236.51	degrees Celcius
   Maximum temperature:   	-211.96	degrees Celcius
   Minimum temperature:   	-249.62	degrees Celcius
   Escape Velocity:		3.94	km/sec
   Molecular weight retained:	51.15 and above
   Surface acceleration:	218.69	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.158
   Length of year:		126384.49	days
   Length of day:		32.41	hours
   Boiling point of water:	-70.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


