                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950489e7
Stellar mass: 1.11 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.65
Stellar temperature: 6384 K
Stellar class: F7
Age: 2.089 billion years  (4.641 billion left on main sequence)
Habitable ecosphere radius: 1.283 AU

Planets present at:
1	  0.364 AU	no atmosphere
2	  0.527 AU	no atmosphere
3	  0.602 AU	no atmosphere
4	  1.201 AU	high pressure
5	  1.478 AU	no atmosphere
6	  2.765 AU	gas giant
7	  4.701 AU	gas giant
8	  7.900 AU	no atmosphere
9	 11.569 AU	gas giant
10	 24.020 AU	gas giant
11	 43.334 AU	no atmosphere
12	 49.940 AU	no atmosphere



Planet 1	
   Distance from primary:	0.364	AU
   Mass:			0.114	Earth masses
   Equatorial radius:		3135.9	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		243.25	degrees Celcius
   Normal daytime temperature:	459.10	degrees Celcius
   Normal night temperature:	-184.15	degrees Celcius
   Maximum temperature:   	462.19	degrees Celcius
   Minimum temperature:   	-194.69	degrees Celcius
   Escape Velocity:		5.39	km/sec
   Molecular weight retained:	27.30 and above
   Surface acceleration:	463.59	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.056
   Length of year:		76.10	days
   Length of day:		1826.40	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.527	AU
   Mass:			0.013	Earth masses
   Equatorial radius:		1518.4	km
   Density:			5.256	grams/cc
   Eccentricity of orbit:	0.024
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		152.70	degrees Celcius
   Maximum temperature:   	351.55	degrees Celcius
   Minimum temperature:   	-216.05	degrees Celcius
   Escape Velocity:		2.60	km/sec
   Molecular weight retained:	117.20 and above
   Surface acceleration:	223.04	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.083
   Length of year:		132.70	days
   Length of day:		3184.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.602	AU
   Mass:			0.715	Earth masses
   Equatorial radius:		5740.6	km
   Density:			5.395	grams/cc
   Eccentricity of orbit:	0.079
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		128.51	degrees Celcius
   Normal daytime temperature:	235.60	degrees Celcius
   Normal night temperature:	10.63	degrees Celcius
   Maximum temperature:   	261.84	degrees Celcius
   Minimum temperature:   	-20.93	degrees Celcius
   Escape Velocity:		9.97	km/sec
   Molecular weight retained:	7.99 and above
   Surface acceleration:	865.60	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.052
   Length of year:		162.15	days
   Length of day:		83.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	1.201	AU
   Mass:			2.539	Earth masses
   Equatorial radius:		8650.5	km
   Density:			5.598	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		1.38	Earth gees
   Surface pressure:		5.077	Earth atmospheres
   Surface temperature:		40.29	degrees Celcius
   Normal daytime temperature:	42.13	degrees Celcius
   Normal night temperature:	38.33	degrees Celcius
   Maximum temperature:   	54.02	degrees Celcius
   Minimum temperature:   	25.87	degrees Celcius
   Escape Velocity:		15.30	km/sec
   Molecular weight retained:	3.39 and above
   Surface acceleration:	1353.33	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.492
   Length of year:		456.84	days
   Length of day:		13.09	hours
   Boiling point of water:	150.9	degrees Celcius
   Hydrosphere percentage:	77.22
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.01
   liquids at surface:
				Ethanol      melts at -114  boils at 126
				Mercury      melts at -39   boils at 443
				Bromine      melts at -7    boils at 105
				Water        melts at 0     boils at 151
				Francium     melts at 27    boils at 806
				Cesium       melts at 28    boils at 838
				Gallium      melts at 30    boils at 2768
				Rubidium     melts at 39    boils at 819
   gasses in atmosphere:
				Nitrogen          0.7%  PP   33.4 mb
				Helium           99.3%  PP 5043.8 mb


Planet 5	
   Distance from primary:	1.478	AU
   Mass:			1/217.1	Earth masses
   Equatorial radius:		1077.8	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-17.30	degrees Celcius
   Normal daytime temperature:	33.41	degrees Celcius
   Normal night temperature:	-68.78	degrees Celcius
   Maximum temperature:   	58.93	degrees Celcius
   Minimum temperature:   	-94.42	degrees Celcius
   Escape Velocity:		1.85	km/sec
   Molecular weight retained:	232.84 and above
   Surface acceleration:	158.17	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.061
   Length of year:		623.47	days
   Length of day:		50.42	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 6	*gas giant*
   Distance from primary:	2.765	AU
   Mass:			12.299	Earth masses
   Equatorial radius:		23481.5	km
   Density:			1.355	grams/cc
   Eccentricity of orbit:	0.215
   Escape Velocity:		20.44	km/sec
   Molecular weight retained:	1.90 and above
   Surface acceleration:	889.51	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.528
   Length of year:		1595.06	days
   Length of day:		13.70	hours


Planet 7	*gas giant*
   Distance from primary:	4.701	AU
   Mass:			890.762	Earth masses
   Equatorial radius:		85585.7	km
   Density:			2.027	grams/cc
   Eccentricity of orbit:	0.054
   Escape Velocity:		91.11	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4849.52	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.547
   Length of year:		3531.30	days
   Length of day:		5.87	hours


Planet 8	
   Distance from primary:	7.900	AU
   Mass:			0.066	Earth masses
   Equatorial radius:		3487.4	km
   Density:			2.205	grams/cc
   Eccentricity of orbit:	0.184
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.002	Earth atmospheres
   Surface temperature:		-168.09	degrees Celcius
   Normal daytime temperature:	-153.73	degrees Celcius
   Normal night temperature:	-182.50	degrees Celcius
   Maximum temperature:   	-130.14	degrees Celcius
   Minimum temperature:   	-206.94	degrees Celcius
   Escape Velocity:		3.87	km/sec
   Molecular weight retained:	52.97 and above
   Surface acceleration:	214.86	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.243
   Length of year:		7703.90	days
   Length of day:		32.70	hours
   Boiling point of water:	-14.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	13.39
   liquids at surface:
				Ozone        melts at -193  boils at -160


Planet 9	*gas giant*
   Distance from primary:	11.569	AU
   Mass:			444.180	Earth masses
   Equatorial radius:		75310.4	km
   Density:			1.484	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		68.59	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3123.12	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.526
   Length of year:		13643.64	days
   Length of day:		7.31	hours


Planet 10	*gas giant*
   Distance from primary:	24.020	AU
   Mass:			40.896	Earth masses
   Equatorial radius:		39917.5	km
   Density:			0.917	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		28.59	km/sec
   Molecular weight retained:	0.97 and above
   Surface acceleration:	1023.51	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.498
   Length of year:		40838.98	days
   Length of day:		12.78	hours


Planet 11	
   Distance from primary:	43.334	AU
   Mass:			0.162	Earth masses
   Equatorial radius:		4703.1	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.65	degrees Celcius
   Normal daytime temperature:	-220.96	degrees Celcius
   Normal night temperature:	-232.27	degrees Celcius
   Maximum temperature:   	-206.13	degrees Celcius
   Minimum temperature:   	-247.47	degrees Celcius
   Escape Velocity:		5.24	km/sec
   Molecular weight retained:	28.92 and above
   Surface acceleration:	291.81	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.148
   Length of year:		98964.34	days
   Length of day:		28.06	hours
   Boiling point of water:	-57.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 12	
   Distance from primary:	49.940	AU
   Mass:			0.144	Earth masses
   Equatorial radius:		4521.3	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.21	degrees Celcius
   Normal daytime temperature:	-224.85	degrees Celcius
   Normal night temperature:	-235.46	degrees Celcius
   Maximum temperature:   	-215.11	degrees Celcius
   Minimum temperature:   	-245.75	degrees Celcius
   Escape Velocity:		5.03	km/sec
   Molecular weight retained:	31.33 and above
   Surface acceleration:	280.20	cm/sec2
   Axial tilt:			68	degrees
   Planetary albedo:		0.162
   Length of year:		122435.78	days
   Length of day:		28.63	hours
   Boiling point of water:	-58.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


