                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504830c
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6281 K
Stellar class: F8
Age: 1.729 billion years  (5.227 billion left on main sequence)
Habitable ecosphere radius: 1.257 AU

Planets present at:
1	  0.378 AU	no atmosphere
2	  0.425 AU	no atmosphere
3	  0.592 AU	no atmosphere
4	  0.979 AU	greenhouse
5	  1.537 AU	cold
6	  1.823 AU	cold
7	  3.303 AU	gas giant
8	  5.356 AU	cold
9	 11.024 AU	gas giant
10	 16.635 AU	gas giant
11	 23.885 AU	no atmosphere
12	 31.451 AU	no atmosphere
13	 43.021 AU	no atmosphere
14	 48.018 AU	no atmosphere



Planet 1	
   Distance from primary:	0.378	AU
   Mass:			0.029	Earth masses
   Equatorial radius:		1977.0	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		228.90	degrees Celcius
   Normal daytime temperature:	441.72	degrees Celcius
   Normal night temperature:	-187.93	degrees Celcius
   Maximum temperature:   	444.87	degrees Celcius
   Minimum temperature:   	-198.41	degrees Celcius
   Escape Velocity:		3.39	km/sec
   Molecular weight retained:	69.04 and above
   Surface acceleration:	290.81	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.051
   Length of year:		80.88	days
   Length of day:		1941.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.425	AU
   Mass:			0.238	Earth masses
   Equatorial radius:		3997.9	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		198.28	degrees Celcius
   Maximum temperature:   	407.46	degrees Celcius
   Minimum temperature:   	-205.51	degrees Celcius
   Escape Velocity:		6.89	km/sec
   Molecular weight retained:	16.71 and above
   Surface acceleration:	594.11	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.067
   Length of year:		96.47	days
   Length of day:		2315.18	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.592	AU
   Mass:			0.250	Earth masses
   Equatorial radius:		4060.4	km
   Density:			5.320	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		125.22	degrees Celcius
   Maximum temperature:   	317.50	degrees Celcius
   Minimum temperature:   	-221.42	degrees Celcius
   Escape Velocity:		7.00	km/sec
   Molecular weight retained:	16.19 and above
   Surface acceleration:	603.66	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.075
   Length of year:		158.85	days
   Length of day:		3812.43	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.979	AU
   Mass:			0.872	Earth masses
   Equatorial radius:		6124.1	km
   Density:			5.417	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.95	Earth gees
   Surface pressure:		71.258	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		331.20	degrees Celcius
   Maximum temperature:   	336.28	degrees Celcius
   Minimum temperature:   	324.99	degrees Celcius
   Escape Velocity:		10.66	km/sec
   Molecular weight retained:	6.99 and above
   Surface acceleration:	927.06	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.586
   Length of year:		337.70	days
   Length of day:		16.23	hours
   Boiling point of water:	271.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 647
				Francium     melts at 27    boils at 1114
				Cesium       melts at 28    boils at 1155
				Gallium      melts at 30    boils at 3634
				Rubidium     melts at 39    boils at 1130
				Potassium    melts at 63    boils at 1243
				Sodium       melts at 98    boils at 1413
				Sulfur       melts at 113   boils at 775
				Indium       melts at 157   boils at 3162
				Lithium      melts at 181   boils at 2092
				Selenium     melts at 217   boils at 1126
				Tin          melts at 232   boils at 3955
				Polonium     melts at 254   boils at 1530
				Bismuth      melts at 271   boils at 2409
				Astatine     melts at 302   boils at 618
				Thallium     melts at 304   boils at 2253
				Cadmium      melts at 321   boils at 1242
				Lead         melts at 328   boils at 2682
   gasses in atmosphere:
				Nitrogen         99.2%  PP 70656.3 mb
				Phosphorus        0.6%  PP  393.0 mb
				CarbonDioxide     0.1%  PP   42.2 mb
				Ozone             0.1%  PP   40.5 mb
				Ethanol           0.1%  PP   42.7 mb


Planet 5	
   Distance from primary:	1.537	AU
   Mass:			0.811	Earth masses
   Equatorial radius:		5980.6	km
   Density:			5.408	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		0.92	Earth gees
   Surface pressure:		0.511	Earth atmospheres
   Surface temperature:		-15.59	degrees Celcius
   Normal daytime temperature:	-10.06	degrees Celcius
   Normal night temperature:	-21.43	degrees Celcius
   Maximum temperature:   	14.42	degrees Celcius
   Minimum temperature:   	-47.39	degrees Celcius
   Escape Velocity:		10.40	km/sec
   Molecular weight retained:	7.34 and above
   Surface acceleration:	903.98	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.320
   Length of year:		664.06	days
   Length of day:		15.97	hours
   Boiling point of water:	82.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	4.31
   Ice cover percentage:	29.24
   liquids at surface:
				Ethanol      melts at -114  boils at 62
				Mercury      melts at -39   boils at 327
   gasses in atmosphere:
				Oxygen           41.5%  PP  212.0 mb
				Nitrogen         58.4%  PP  298.8 mb


Planet 6	
   Distance from primary:	1.823	AU
   Mass:			0.836	Earth masses
   Equatorial radius:		6039.8	km
   Density:			5.412	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.663	Earth atmospheres
   Surface temperature:		-72.51	degrees Celcius
   Normal daytime temperature:	-68.71	degrees Celcius
   Normal night temperature:	-76.53	degrees Celcius
   Maximum temperature:   	-50.74	degrees Celcius
   Minimum temperature:   	-95.79	degrees Celcius
   Escape Velocity:		10.50	km/sec
   Molecular weight retained:	7.19 and above
   Surface acceleration:	913.49	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.658
   Length of year:		857.69	days
   Length of day:		15.87	hours
   Boiling point of water:	89.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.09
   Ice cover percentage:	94.32
   liquids at surface:
				Ethanol      melts at -114  boils at 68
				Chlorine     melts at -101  boils at -41
				Ammonia      melts at -78   boils at -41
   gasses in atmosphere:
				Oxygen           33.9%  PP  225.1 mb
				Nitrogen         65.9%  PP  437.4 mb


Planet 7	*gas giant*
   Distance from primary:	3.303	AU
   Mass:			800.619	Earth masses
   Equatorial radius:		80700.5	km
   Density:			2.174	grams/cc
   Eccentricity of orbit:	0.169
   Escape Velocity:		88.95	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4902.45	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.539
   Length of year:		2089.72	days
   Length of day:		5.84	hours


Planet 8	
   Distance from primary:	5.356	AU
   Mass:			0.937	Earth masses
   Equatorial radius:		8349.4	km
   Density:			2.298	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.602	Earth atmospheres
   Surface temperature:		-137.21	degrees Celcius
   Normal daytime temperature:	-133.79	degrees Celcius
   Normal night temperature:	-140.86	degrees Celcius
   Maximum temperature:   	-116.13	degrees Celcius
   Minimum temperature:   	-160.12	degrees Celcius
   Escape Velocity:		9.46	km/sec
   Molecular weight retained:	8.87 and above
   Surface acceleration:	536.16	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.373
   Length of year:		4318.49	days
   Length of day:		20.70	hours
   Boiling point of water:	86.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	39.94
   liquids at surface:
				Ozone        melts at -193  boils at -118
   gasses in atmosphere:
				Oxygen           38.4%  PP  231.2 mb
				Nitrogen         61.6%  PP  370.6 mb


Planet 9	*gas giant*
   Distance from primary:	11.024	AU
   Mass:			992.837	Earth masses
   Equatorial radius:		95005.7	km
   Density:			1.652	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		91.30	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4386.50	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.518
   Length of year:		12737.08	days
   Length of day:		6.17	hours


Planet 10	*gas giant*
   Distance from primary:	16.635	AU
   Mass:			3.761	Earth masses
   Equatorial radius:		19335.0	km
   Density:			0.742	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		12.46	km/sec
   Molecular weight retained:	5.12 and above
   Surface acceleration:	401.18	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.476
   Length of year:		23641.63	days
   Length of day:		20.41	hours


Planet 11	
   Distance from primary:	23.885	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1972.5	km
   Density:			2.192	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		0.12	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-211.81	degrees Celcius
   Normal daytime temperature:	-200.86	degrees Celcius
   Normal night temperature:	-222.67	degrees Celcius
   Maximum temperature:   	-184.97	degrees Celcius
   Minimum temperature:   	-238.74	degrees Celcius
   Escape Velocity:		2.18	km/sec
   Molecular weight retained:	166.54 and above
   Surface acceleration:	120.83	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.162
   Length of year:		40673.29	days
   Length of day:		43.60	hours
   Boiling point of water:	-96.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


Planet 12	
   Distance from primary:	31.451	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		5358.1	km
   Density:			2.231	grams/cc
   Eccentricity of orbit:	0.073
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-219.13	degrees Celcius
   Normal daytime temperature:	-212.89	degrees Celcius
   Normal night temperature:	-225.31	degrees Celcius
   Maximum temperature:   	-199.34	degrees Celcius
   Minimum temperature:   	-239.66	degrees Celcius
   Escape Velocity:		5.98	km/sec
   Molecular weight retained:	22.18 and above
   Surface acceleration:	334.01	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.150
   Length of year:		61458.77	days
   Length of day:		26.22	hours
   Boiling point of water:	-49.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   liquids at surface:
				Fluorine     melts at -220  boils at -216


Planet 13	
   Distance from primary:	43.021	AU
   Mass:			0.158	Earth masses
   Equatorial radius:		4668.5	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.85	degrees Celcius
   Normal daytime temperature:	-221.15	degrees Celcius
   Normal night temperature:	-232.45	degrees Celcius
   Maximum temperature:   	-208.90	degrees Celcius
   Minimum temperature:   	-245.28	degrees Celcius
   Escape Velocity:		5.20	km/sec
   Molecular weight retained:	29.36 and above
   Surface acceleration:	289.60	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.139
   Length of year:		98319.91	days
   Length of day:		28.16	hours
   Boiling point of water:	-57.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 14	
   Distance from primary:	48.018	AU
   Mass:			0.197	Earth masses
   Equatorial radius:		5021.7	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.24	degrees Celcius
   Normal daytime temperature:	-224.02	degrees Celcius
   Normal night temperature:	-234.36	degrees Celcius
   Maximum temperature:   	-210.76	degrees Celcius
   Minimum temperature:   	-248.06	degrees Celcius
   Escape Velocity:		5.60	km/sec
   Molecular weight retained:	25.31 and above
   Surface acceleration:	312.27	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.136
   Length of year:		115938.99	days
   Length of day:		27.12	hours
   Boiling point of water:	-51.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


