                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048852
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6147 K
Stellar class: F9
Age: 5.856 billion years  (0.925 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.373 AU	no atmosphere
2	  0.447 AU	no atmosphere
3	  0.585 AU	no atmosphere
4	  0.792 AU	no atmosphere
5	  0.966 AU	greenhouse
6	  1.232 AU	no atmosphere
7	  1.426 AU	gas giant
8	  2.769 AU	gas giant
9	  3.690 AU	gas giant
10	  5.967 AU	gas giant
11	 10.284 AU	gas giant
12	 18.120 AU	gas giant
13	 39.434 AU	no atmosphere
14	 51.570 AU	no atmosphere



Planet 1	
   Distance from primary:	0.373	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2083.4	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		233.17	degrees Celcius
   Normal daytime temperature:	446.89	degrees Celcius
   Normal night temperature:	-186.72	degrees Celcius
   Maximum temperature:   	449.91	degrees Celcius
   Minimum temperature:   	-196.81	degrees Celcius
   Escape Velocity:		3.57	km/sec
   Molecular weight retained:	62.14 and above
   Surface acceleration:	306.57	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.073
   Length of year:		79.10	days
   Length of day:		1898.43	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.447	AU
   Mass:			0.293	Earth masses
   Equatorial radius:		4279.3	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		190.38	degrees Celcius
   Maximum temperature:   	397.90	degrees Celcius
   Minimum temperature:   	-207.93	degrees Celcius
   Escape Velocity:		7.38	km/sec
   Molecular weight retained:	14.56 and above
   Surface acceleration:	637.20	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.066
   Length of year:		103.69	days
   Length of day:		2488.51	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.585	AU
   Mass:			1/101.2	Earth masses
   Equatorial radius:		1389.7	km
   Density:			5.254	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		132.64	degrees Celcius
   Maximum temperature:   	326.64	degrees Celcius
   Minimum temperature:   	-219.94	degrees Celcius
   Escape Velocity:		2.38	km/sec
   Molecular weight retained:	139.94 and above
   Surface acceleration:	204.08	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.060
   Length of year:		155.38	days
   Length of day:		3729.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.792	AU
   Mass:			0.142	Earth masses
   Equatorial radius:		3368.6	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.047
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		74.20	degrees Celcius
   Maximum temperature:   	253.61	degrees Celcius
   Minimum temperature:   	-228.26	degrees Celcius
   Escape Velocity:		5.80	km/sec
   Molecular weight retained:	23.63 and above
   Surface acceleration:	498.63	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.075
   Length of year:		244.80	days
   Length of day:		5875.16	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	0.966	AU
   Mass:			0.436	Earth masses
   Equatorial radius:		4881.1	km
   Density:			5.353	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.74	Earth gees
   Surface pressure:		18.018	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		88.09	degrees Celcius
   Maximum temperature:   	96.79	degrees Celcius
   Minimum temperature:   	78.89	degrees Celcius
   Escape Velocity:		8.44	km/sec
   Molecular weight retained:	11.14 and above
   Surface acceleration:	730.24	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.587
   Length of year:		329.64	days
   Length of day:		22.13	hours
   Boiling point of water:	201.3	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 528
				Water        melts at 0     boils at 201
				Francium     melts at 27    boils at 935
				Cesium       melts at 28    boils at 970
				Gallium      melts at 30    boils at 3129
				Rubidium     melts at 39    boils at 949
				Phosphorus   melts at 44    boils at 431
				Potassium    melts at 63    boils at 1048
   gasses in atmosphere:
				Nitrogen         99.3%  PP 17896.2 mb
				CarbonDioxide     0.2%  PP   32.9 mb
				Methane           0.1%  PP    9.0 mb
				Ammonia           0.1%  PP   10.0 mb
				Ozone             0.2%  PP   32.9 mb
				Ethanol           0.2%  PP   33.8 mb


Planet 6	
   Distance from primary:	1.232	AU
   Mass:			0.264	Earth masses
   Equatorial radius:		4136.1	km
   Density:			5.322	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.63	Earth gees
   Surface pressure:		0.068	Earth atmospheres
   Surface temperature:		10.86	degrees Celcius
   Normal daytime temperature:	27.90	degrees Celcius
   Normal night temperature:	-6.82	degrees Celcius
   Maximum temperature:   	56.53	degrees Celcius
   Minimum temperature:   	-36.53	degrees Celcius
   Escape Velocity:		7.13	km/sec
   Molecular weight retained:	15.60 and above
   Surface acceleration:	615.24	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.217
   Length of year:		475.16	days
   Length of day:		20.77	hours
   Boiling point of water:	38.2	degrees Celcius
   Hydrosphere percentage:	43.59
   Cloud cover percentage:	23.90
   Ice cover percentage:	2.66
   liquids at surface:
				Ethanol      melts at -114  boils at 21
				Mercury      melts at -39   boils at 253
				Water        melts at 0     boils at 39
   gasses in atmosphere:
				Oxygen           96.6%  PP   65.8 mb
				CarbonDioxide     1.5%  PP    1.0 mb
				Ammonia           0.1%  PP    0.1 mb
				Ozone             1.6%  PP    1.1 mb
				Krypton           0.1%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	1.426	AU
   Mass:			3.543	Earth masses
   Equatorial radius:		15462.8	km
   Density:			1.367	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		13.52	km/sec
   Molecular weight retained:	4.34 and above
   Surface acceleration:	590.93	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.524
   Length of year:		591.24	days
   Length of day:		16.84	hours


Planet 8	*gas giant*
   Distance from primary:	2.769	AU
   Mass:			1.868	Earth masses
   Equatorial radius:		13558.5	km
   Density:			1.069	grams/cc
   Eccentricity of orbit:	0.160
   Escape Velocity:		10.48	km/sec
   Molecular weight retained:	7.23 and above
   Surface acceleration:	405.15	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.534
   Length of year:		1600.54	days
   Length of day:		20.31	hours


Planet 9	*gas giant*
   Distance from primary:	3.690	AU
   Mass:			74.652	Earth masses
   Equatorial radius:		40716.4	km
   Density:			1.578	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		38.24	km/sec
   Molecular weight retained:	0.54 and above
   Surface acceleration:	1795.73	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.527
   Length of year:		2461.15	days
   Length of day:		9.64	hours


Planet 10	*gas giant*
   Distance from primary:	5.967	AU
   Mass:			6.917	Earth masses
   Equatorial radius:		21175.1	km
   Density:			1.039	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		16.14	km/sec
   Molecular weight retained:	3.05 and above
   Surface acceleration:	615.14	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.479
   Length of year:		5061.23	days
   Length of day:		16.48	hours


Planet 11	*gas giant*
   Distance from primary:	10.284	AU
   Mass:			1417.303	Earth masses
   Equatorial radius:		104649.8	km
   Density:			1.765	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		103.93	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5160.90	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.494
   Length of year:		11430.72	days
   Length of day:		5.69	hours


Planet 12	*gas giant*
   Distance from primary:	18.120	AU
   Mass:			29.426	Earth masses
   Equatorial radius:		35435.8	km
   Density:			0.944	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		25.74	km/sec
   Molecular weight retained:	1.20 and above
   Surface acceleration:	934.52	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.510
   Length of year:		26784.71	days
   Length of day:		13.37	hours


Planet 13	
   Distance from primary:	39.434	AU
   Mass:			0.286	Earth masses
   Equatorial radius:		5669.9	km
   Density:			2.236	grams/cc
   Eccentricity of orbit:	0.025
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-224.13	degrees Celcius
   Normal daytime temperature:	-218.62	degrees Celcius
   Normal night temperature:	-229.57	degrees Celcius
   Maximum temperature:   	-202.88	degrees Celcius
   Minimum temperature:   	-245.85	degrees Celcius
   Escape Velocity:		6.34	km/sec
   Molecular weight retained:	19.76 and above
   Surface acceleration:	354.32	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.152
   Length of year:		85994.59	days
   Length of day:		25.46	hours
   Boiling point of water:	-43.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 14	
   Distance from primary:	51.570	AU
   Mass:			0.126	Earth masses
   Equatorial radius:		4327.3	km
   Density:			2.215	grams/cc
   Eccentricity of orbit:	0.019
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.94	degrees Celcius
   Normal daytime temperature:	-225.57	degrees Celcius
   Normal night temperature:	-236.20	degrees Celcius
   Maximum temperature:   	-212.52	degrees Celcius
   Minimum temperature:   	-249.55	degrees Celcius
   Escape Velocity:		4.81	km/sec
   Molecular weight retained:	34.24 and above
   Surface acceleration:	267.85	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.158
   Length of year:		128608.30	days
   Length of day:		29.28	hours
   Boiling point of water:	-61.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


