                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b3d
Stellar mass: 1.09 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6196 K
Stellar class: F8
Age: 1.755 billion years  (5.471 billion left on main sequence)
Habitable ecosphere radius: 1.227 AU

Planets present at:
1	  0.355 AU	no atmosphere
2	  0.492 AU	no atmosphere
3	  1.166 AU	gas giant
4	  1.939 AU	gas giant
5	  3.862 AU	cold
6	  4.704 AU	gas giant
7	  5.747 AU	gas giant
8	  8.831 AU	gas giant
9	 13.576 AU	no atmosphere
10	 24.537 AU	gas giant
11	 40.390 AU	no atmosphere
12	 49.549 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.355	AU
   Mass:			0.062	Earth masses
   Equatorial radius:		2562.8	km
   Density:			5.275	grams/cc
   Eccentricity of orbit:	0.149
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		235.69	degrees Celcius
   Normal daytime temperature:	448.66	degrees Celcius
   Normal night temperature:	-174.99	degrees Celcius
   Maximum temperature:   	452.39	degrees Celcius
   Minimum temperature:   	-187.96	degrees Celcius
   Escape Velocity:		4.40	km/sec
   Molecular weight retained:	40.99 and above
   Surface acceleration:	377.82	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.074
   Length of year:		73.93	days
   Length of day:		1314.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.492	AU
   Mass:			0.402	Earth masses
   Equatorial radius:		4750.6	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.117
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		160.81	degrees Celcius
   Maximum temperature:   	361.41	degrees Celcius
   Minimum temperature:   	-211.37	degrees Celcius
   Escape Velocity:		8.21	km/sec
   Molecular weight retained:	11.77 and above
   Surface acceleration:	709.94	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.059
   Length of year:		120.71	days
   Length of day:		2290.00	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	*gas giant*
   Distance from primary:	1.166	AU
   Mass:			5.051	Earth masses
   Equatorial radius:		16919.1	km
   Density:			1.488	grams/cc
   Eccentricity of orbit:	0.182
   Escape Velocity:		15.43	km/sec
   Molecular weight retained:	3.33 and above
   Surface acceleration:	703.72	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.472
   Length of year:		440.68	days
   Length of day:		15.43	hours


Planet 4	*gas giant*
   Distance from primary:	1.939	AU
   Mass:			17.401	Earth masses
   Equatorial radius:		25320.3	km
   Density:			1.530	grams/cc
   Eccentricity of orbit:	0.140
   Escape Velocity:		23.41	km/sec
   Molecular weight retained:	1.45 and above
   Surface acceleration:	1082.37	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.511
   Length of year:		945.58	days
   Length of day:		12.42	hours


Planet 5	
   Distance from primary:	3.862	AU
   Mass:			0.841	Earth masses
   Equatorial radius:		6051.6	km
   Density:			5.412	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.522	Earth atmospheres
   Surface temperature:		-132.57	degrees Celcius
   Normal daytime temperature:	-129.59	degrees Celcius
   Normal night temperature:	-135.70	degrees Celcius
   Maximum temperature:   	-110.68	degrees Celcius
   Minimum temperature:   	-156.35	degrees Celcius
   Escape Velocity:		10.53	km/sec
   Molecular weight retained:	7.17 and above
   Surface acceleration:	915.39	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.602
   Length of year:		2657.78	days
   Length of day:		15.84	hours
   Boiling point of water:	82.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	73.45
   liquids at surface:
				Ozone        melts at -193  boils at -119
   gasses in atmosphere:
				Oxygen           39.8%  PP  207.3 mb
				Nitrogen         60.2%  PP  314.1 mb


Planet 6	*gas giant*
   Distance from primary:	4.704	AU
   Mass:			1.578	Earth masses
   Equatorial radius:		13536.0	km
   Density:			0.908	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		9.64	km/sec
   Molecular weight retained:	8.54 and above
   Surface acceleration:	343.45	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.497
   Length of year:		3573.06	days
   Length of day:		22.05	hours


Planet 7	*gas giant*
   Distance from primary:	5.747	AU
   Mass:			2.475	Earth masses
   Equatorial radius:		15694.6	km
   Density:			0.914	grams/cc
   Eccentricity of orbit:	0.090
   Escape Velocity:		11.21	km/sec
   Molecular weight retained:	6.31 and above
   Surface acceleration:	400.70	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.468
   Length of year:		4825.02	days
   Length of day:		20.42	hours


Planet 8	*gas giant*
   Distance from primary:	8.831	AU
   Mass:			1281.239	Earth masses
   Equatorial radius:		100668.8	km
   Density:			1.792	grams/cc
   Eccentricity of orbit:	0.094
   Escape Velocity:		100.75	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5041.73	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.503
   Length of year:		9174.10	days
   Length of day:		5.76	hours


Planet 9	
   Distance from primary:	13.576	AU
   Mass:			1/389.2	Earth masses
   Equatorial radius:		1187.8	km
   Density:			2.188	grams/cc
   Eccentricity of orbit:	0.052
   Surface gravity:		0.07	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-193.15	degrees Celcius
   Normal daytime temperature:	-175.62	degrees Celcius
   Normal night temperature:	-210.59	degrees Celcius
   Maximum temperature:   	-156.44	degrees Celcius
   Minimum temperature:   	-229.48	degrees Celcius
   Escape Velocity:		1.31	km/sec
   Molecular weight retained:	460.08 and above
   Surface acceleration:	72.63	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.176
   Length of year:		17517.66	days
   Length of day:		56.24	hours
   Boiling point of water:	-77.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	5.17


Planet 10	*gas giant*
   Distance from primary:	24.537	AU
   Mass:			47.738	Earth masses
   Equatorial radius:		41990.9	km
   Density:			0.920	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		30.11	km/sec
   Molecular weight retained:	0.88 and above
   Surface acceleration:	1079.68	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.521
   Length of year:		42560.51	days
   Length of day:		12.44	hours


Planet 11	
   Distance from primary:	40.390	AU
   Mass:			0.249	Earth masses
   Equatorial radius:		5417.4	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.181
   Surface gravity:		0.34	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-226.10	degrees Celcius
   Normal daytime temperature:	-220.69	degrees Celcius
   Normal night temperature:	-231.42	degrees Celcius
   Maximum temperature:   	-203.95	degrees Celcius
   Minimum temperature:   	-248.44	degrees Celcius
   Escape Velocity:		6.05	km/sec
   Molecular weight retained:	21.68 and above
   Surface acceleration:	337.87	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.156
   Length of year:		89889.44	days
   Length of day:		26.07	hours
   Boiling point of water:	-47.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 12	
   Distance from primary:	49.549	AU
   Mass:			0.193	Earth masses
   Equatorial radius:		4986.4	km
   Density:			2.224	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.57	degrees Celcius
   Normal daytime temperature:	-225.49	degrees Celcius
   Normal night temperature:	-235.54	degrees Celcius
   Maximum temperature:   	-210.89	degrees Celcius
   Minimum temperature:   	-250.36	degrees Celcius
   Escape Velocity:		5.56	km/sec
   Molecular weight retained:	25.68 and above
   Surface acceleration:	309.99	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.147
   Length of year:		122138.93	days
   Length of day:		27.22	hours
   Boiling point of water:	-51.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


