                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b01
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.50
Stellar temperature: 6161 K
Stellar class: F8
Age: 3.965 billion years  (3.269 billion left on main sequence)
Habitable ecosphere radius: 1.226 AU

Planets present at:
1	  0.341 AU	no atmosphere
2	  0.625 AU	greenhouse
3	  1.221 AU	gas giant
4	  1.724 AU	no atmosphere
5	  2.710 AU	gas giant
6	  3.975 AU	no atmosphere
7	  7.398 AU	gas giant
8	 17.893 AU	gas giant
9	 32.728 AU	gas giant
10	 50.830 AU	no atmosphere



Planet 1	
   Distance from primary:	0.341	AU
   Mass:			0.148	Earth masses
   Equatorial radius:		3416.0	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		247.54	degrees Celcius
   Normal daytime temperature:	464.06	degrees Celcius
   Normal night temperature:	-180.97	degrees Celcius
   Maximum temperature:   	467.06	degrees Celcius
   Minimum temperature:   	-191.22	degrees Celcius
   Escape Velocity:		5.88	km/sec
   Molecular weight retained:	22.97 and above
   Surface acceleration:	505.78	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.061
   Length of year:		69.69	days
   Length of day:		1672.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.625	AU
   Mass:			0.623	Earth masses
   Equatorial radius:		5485.7	km
   Density:			5.382	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.84	Earth gees
   Surface pressure:		41.858	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		315.69	degrees Celcius
   Maximum temperature:   	333.02	degrees Celcius
   Minimum temperature:   	250.65	degrees Celcius
   Escape Velocity:		9.51	km/sec
   Molecular weight retained:	8.77 and above
   Surface acceleration:	825.11	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.477
   Length of year:		173.22	days
   Length of day:		4157.22	hours
   Boiling point of water:	242.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 597
				Francium     melts at 27    boils at 1039
				Cesium       melts at 28    boils at 1077
				Gallium      melts at 30    boils at 3422
				Rubidium     melts at 39    boils at 1054
				Potassium    melts at 63    boils at 1161
				Sodium       melts at 98    boils at 1321
				Sulfur       melts at 113   boils at 718
				Indium       melts at 157   boils at 2976
				Lithium      melts at 181   boils at 1964
				Selenium     melts at 217   boils at 1050
				Tin          melts at 232   boils at 3726
				Polonium     melts at 254   boils at 1432
				Bismuth      melts at 271   boils at 2263
				Astatine     melts at 302   boils at 569
				Thallium     melts at 304   boils at 2116
   gasses in atmosphere:
				Nitrogen         98.7%  PP 41322.1 mb
				Phosphorus        0.8%  PP  353.1 mb
				CarbonDioxide     0.1%  PP   42.0 mb
				Ozone             0.1%  PP   40.3 mb
				Ethanol           0.1%  PP   43.0 mb


Planet 3	*gas giant*
   Distance from primary:	1.221	AU
   Mass:			3.669	Earth masses
   Equatorial radius:		15473.4	km
   Density:			1.413	grams/cc
   Eccentricity of orbit:	0.121
   Escape Velocity:		13.75	km/sec
   Molecular weight retained:	4.20 and above
   Surface acceleration:	611.07	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.544
   Length of year:		472.77	days
   Length of day:		16.58	hours


Planet 4	
   Distance from primary:	1.724	AU
   Mass:			0.140	Earth masses
   Equatorial radius:		3357.5	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.067
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.019	Earth atmospheres
   Surface temperature:		-65.18	degrees Celcius
   Normal daytime temperature:	-48.00	degrees Celcius
   Normal night temperature:	-82.62	degrees Celcius
   Maximum temperature:   	-22.94	degrees Celcius
   Minimum temperature:   	-108.59	degrees Celcius
   Escape Velocity:		5.78	km/sec
   Molecular weight retained:	23.79 and above
   Surface acceleration:	496.95	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.445
   Length of year:		792.70	days
   Length of day:		21.72	hours
   Boiling point of water:	15.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	52.42
   liquids at surface:
				Ethanol      melts at -114  boils at -0
   gasses in atmosphere:
				CarbonDioxide    45.4%  PP    8.7 mb
				Ozone            50.5%  PP    9.7 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           3.5%  PP    0.7 mb
				Xenon             0.4%  PP    0.1 mb


Planet 5	*gas giant*
   Distance from primary:	2.710	AU
   Mass:			141.068	Earth masses
   Equatorial radius:		47939.6	km
   Density:			1.827	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		48.45	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2447.82	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.507
   Length of year:		1562.37	days
   Length of day:		8.26	hours


Planet 6	
   Distance from primary:	3.975	AU
   Mass:			0.218	Earth masses
   Equatorial radius:		3880.4	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.050	Earth atmospheres
   Surface temperature:		-134.44	degrees Celcius
   Normal daytime temperature:	-125.66	degrees Celcius
   Normal night temperature:	-143.46	degrees Celcius
   Maximum temperature:   	-104.25	degrees Celcius
   Minimum temperature:   	-166.38	degrees Celcius
   Escape Velocity:		6.69	km/sec
   Molecular weight retained:	17.75 and above
   Surface acceleration:	576.20	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.489
   Length of year:		2776.17	days
   Length of day:		19.97	hours
   Boiling point of water:	32.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	65.98
   gasses in atmosphere:
				Fluorine          0.5%  PP    0.2 mb
				Argon             4.1%  PP    2.0 mb
				Neon              9.1%  PP    4.5 mb
				Krypton          86.4%  PP   43.1 mb


Planet 7	*gas giant*
   Distance from primary:	7.398	AU
   Mass:			1438.358	Earth masses
   Equatorial radius:		102604.0	km
   Density:			1.900	grams/cc
   Eccentricity of orbit:	0.104
   Escape Velocity:		105.74	km/sec
   Molecular weight retained:	0.07 and above
   Surface acceleration:	5448.51	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.536
   Length of year:		7033.40	days
   Length of day:		5.54	hours


Planet 8	*gas giant*
   Distance from primary:	17.893	AU
   Mass:			208.261	Earth masses
   Equatorial radius:		62855.8	km
   Density:			1.197	grams/cc
   Eccentricity of orbit:	0.046
   Escape Velocity:		51.41	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2102.11	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.482
   Length of year:		26502.10	days
   Length of day:		8.91	hours


Planet 9	*gas giant*
   Distance from primary:	32.728	AU
   Mass:			1.790	Earth masses
   Equatorial radius:		16506.5	km
   Density:			0.568	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		9.30	km/sec
   Molecular weight retained:	9.18 and above
   Surface acceleration:	261.92	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.499
   Length of year:		65577.59	days
   Length of day:		25.25	hours


Planet 10	
   Distance from primary:	50.830	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		4559.9	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-231.43	degrees Celcius
   Normal daytime temperature:	-226.25	degrees Celcius
   Normal night temperature:	-236.50	degrees Celcius
   Maximum temperature:   	-215.46	degrees Celcius
   Minimum temperature:   	-247.78	degrees Celcius
   Escape Velocity:		5.08	km/sec
   Molecular weight retained:	30.79 and above
   Surface acceleration:	282.66	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.154
   Length of year:		126927.27	days
   Length of day:		28.51	hours
   Boiling point of water:	-59.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


