                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047c01
Stellar mass: 1.09 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6272 K
Stellar class: F8
Age: 2.331 billion years  (4.869 billion left on main sequence)
Habitable ecosphere radius: 1.230 AU

Planets present at:
1	  0.386 AU	no atmosphere
2	  0.479 AU	no atmosphere
3	  0.600 AU	no atmosphere
4	  0.981 AU	greenhouse
5	  1.638 AU	gas giant
6	  2.632 AU	no atmosphere
7	  4.031 AU	gas giant
8	  7.034 AU	gas giant
9	 11.347 AU	gas giant
10	 19.684 AU	gas giant
11	 29.695 AU	gas giant
12	 50.250 AU	no atmosphere



Planet 1	
   Distance from primary:	0.386	AU
   Mass:			0.066	Earth masses
   Equatorial radius:		2608.0	km
   Density:			5.276	grams/cc
   Eccentricity of orbit:	0.095
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		214.98	degrees Celcius
   Normal daytime temperature:	424.74	degrees Celcius
   Normal night temperature:	-190.89	degrees Celcius
   Maximum temperature:   	427.82	degrees Celcius
   Minimum temperature:   	-200.90	degrees Celcius
   Escape Velocity:		4.48	km/sec
   Molecular weight retained:	39.57 and above
   Surface acceleration:	384.56	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.078
   Length of year:		83.79	days
   Length of day:		2010.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.479	AU
   Mass:			0.299	Earth masses
   Equatorial radius:		4309.4	km
   Density:			5.329	grams/cc
   Eccentricity of orbit:	0.012
   Surface gravity:		0.65	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		166.45	degrees Celcius
   Maximum temperature:   	368.45	degrees Celcius
   Minimum temperature:   	-212.60	degrees Celcius
   Escape Velocity:		7.44	km/sec
   Molecular weight retained:	14.35 and above
   Surface acceleration:	641.82	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.065
   Length of year:		115.88	days
   Length of day:		2781.01	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.600	AU
   Mass:			0.211	Earth masses
   Equatorial radius:		3841.3	km
   Density:			5.312	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		118.51	degrees Celcius
   Maximum temperature:   	309.15	degrees Celcius
   Minimum temperature:   	-222.51	degrees Celcius
   Escape Velocity:		6.62	km/sec
   Molecular weight retained:	18.12 and above
   Surface acceleration:	570.25	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.074
   Length of year:		162.66	days
   Length of day:		3903.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.981	AU
   Mass:			0.357	Earth masses
   Equatorial radius:		4568.2	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.69	Earth gees
   Surface pressure:		11.513	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		82.25	degrees Celcius
   Maximum temperature:   	92.63	degrees Celcius
   Minimum temperature:   	71.30	degrees Celcius
   Escape Velocity:		7.89	km/sec
   Molecular weight retained:	12.75 and above
   Surface acceleration:	681.71	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.513
   Length of year:		339.92	days
   Length of day:		20.01	hours
   Boiling point of water:	182.1	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 496
				Water        melts at 0     boils at 182
				Francium     melts at 27    boils at 886
				Cesium       melts at 28    boils at 920
				Gallium      melts at 30    boils at 2992
				Rubidium     melts at 39    boils at 899
				Phosphorus   melts at 44    boils at 402
				Potassium    melts at 63    boils at 994
   gasses in atmosphere:
				Nitrogen         98.9%  PP 11385.5 mb
				CarbonDioxide     0.3%  PP   34.6 mb
				Methane           0.1%  PP    8.4 mb
				Ammonia           0.1%  PP   10.3 mb
				Ozone             0.3%  PP   35.6 mb
				Ethanol           0.3%  PP   35.4 mb


Planet 5	*gas giant*
   Distance from primary:	1.638	AU
   Mass:			48.913	Earth masses
   Equatorial radius:		33744.0	km
   Density:			1.816	grams/cc
   Eccentricity of orbit:	0.198
   Escape Velocity:		34.00	km/sec
   Molecular weight retained:	0.69 and above
   Surface acceleration:	1713.04	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.546
   Length of year:		733.93	days
   Length of day:		9.88	hours


Planet 6	
   Distance from primary:	2.632	AU
   Mass:			0.142	Earth masses
   Equatorial radius:		3371.4	km
   Density:			5.297	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.015	Earth atmospheres
   Surface temperature:		-97.91	degrees Celcius
   Normal daytime temperature:	-83.13	degrees Celcius
   Normal night temperature:	-112.87	degrees Celcius
   Maximum temperature:   	-61.38	degrees Celcius
   Minimum temperature:   	-135.56	degrees Celcius
   Escape Velocity:		5.80	km/sec
   Molecular weight retained:	23.59 and above
   Surface acceleration:	499.05	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.349
   Length of year:		1494.35	days
   Length of day:		21.46	hours
   Boiling point of water:	11.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	40.45
   liquids at surface:
				Ethanol      melts at -114  boils at -4
				Chlorine     melts at -101  boils at -90
   gasses in atmosphere:
				Ozone            93.0%  PP   14.0 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           6.1%  PP    0.9 mb
				Xenon             0.7%  PP    0.1 mb


Planet 7	*gas giant*
   Distance from primary:	4.031	AU
   Mass:			118.533	Earth masses
   Equatorial radius:		47087.7	km
   Density:			1.620	grams/cc
   Eccentricity of orbit:	0.029
   Escape Velocity:		44.81	km/sec
   Molecular weight retained:	0.40 and above
   Surface acceleration:	2131.89	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.503
   Length of year:		2832.79	days
   Length of day:		8.85	hours


Planet 8	*gas giant*
   Distance from primary:	7.034	AU
   Mass:			48.256	Earth masses
   Equatorial radius:		37950.4	km
   Density:			1.260	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		31.85	km/sec
   Molecular weight retained:	0.78 and above
   Surface acceleration:	1336.16	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.472
   Length of year:		6528.67	days
   Length of day:		11.18	hours


Planet 9	*gas giant*
   Distance from primary:	11.347	AU
   Mass:			292.970	Earth masses
   Equatorial radius:		66831.3	km
   Density:			1.400	grams/cc
   Eccentricity of orbit:	0.083
   Escape Velocity:		59.13	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2615.79	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.530
   Length of year:		13373.51	days
   Length of day:		7.99	hours


Planet 10	*gas giant*
   Distance from primary:	19.684	AU
   Mass:			16.935	Earth masses
   Equatorial radius:		30466.3	km
   Density:			0.855	grams/cc
   Eccentricity of orbit:	0.021
   Escape Velocity:		21.06	km/sec
   Molecular weight retained:	1.79 and above
   Surface acceleration:	727.58	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.547
   Length of year:		30567.82	days
   Length of day:		15.15	hours


Planet 11	*gas giant*
   Distance from primary:	29.695	AU
   Mass:			15.925	Earth masses
   Equatorial radius:		30967.9	km
   Density:			0.765	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		20.25	km/sec
   Molecular weight retained:	1.94 and above
   Surface acceleration:	662.20	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.521
   Length of year:		56638.13	days
   Length of day:		15.88	hours


Planet 12	
   Distance from primary:	50.250	AU
   Mass:			0.189	Earth masses
   Equatorial radius:		4950.2	km
   Density:			2.224	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.89	degrees Celcius
   Normal daytime temperature:	-225.83	degrees Celcius
   Normal night temperature:	-235.84	degrees Celcius
   Maximum temperature:   	-209.73	degrees Celcius
   Minimum temperature:   	-251.89	degrees Celcius
   Escape Velocity:		5.52	km/sec
   Molecular weight retained:	26.06 and above
   Surface acceleration:	307.67	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.152
   Length of year:		124677.83	days
   Length of day:		27.32	hours
   Boiling point of water:	-52.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


