                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504842b
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.59
Stellar temperature: 6370 K
Stellar class: F7
Age: 2.369 billion years  (4.550 billion left on main sequence)
Habitable ecosphere radius: 1.261 AU

Planets present at:
1	  0.351 AU	no atmosphere
2	  0.827 AU	greenhouse
3	  2.053 AU	high pressure
4	  3.007 AU	gas giant
5	  3.841 AU	gas giant
6	  4.856 AU	gas giant
7	  8.014 AU	gas giant
8	 13.334 AU	gas giant
9	 19.596 AU	no atmosphere
10	 40.935 AU	gas giant



Planet 1	
   Distance from primary:	0.351	AU
   Mass:			0.150	Earth masses
   Equatorial radius:		3433.4	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		242.81	degrees Celcius
   Normal daytime temperature:	458.41	degrees Celcius
   Normal night temperature:	-182.89	degrees Celcius
   Maximum temperature:   	461.46	degrees Celcius
   Minimum temperature:   	-193.25	degrees Celcius
   Escape Velocity:		5.91	km/sec
   Molecular weight retained:	22.74 and above
   Surface acceleration:	508.41	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.090
   Length of year:		72.55	days
   Length of day:		1741.13	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.827	AU
   Mass:			1.506	Earth masses
   Equatorial radius:		7314.1	km
   Density:			5.493	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		1.14	Earth gees
   Surface pressure:		176.800	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		539.29	degrees Celcius
   Maximum temperature:   	542.21	degrees Celcius
   Minimum temperature:   	533.47	degrees Celcius
   Escape Velocity:		12.82	km/sec
   Molecular weight retained:	4.83 and above
   Surface acceleration:	1122.77	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.448
   Length of year:		262.00	days
   Length of day:		15.42	hours
   Boiling point of water:	330.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1265
				Cesium       melts at 28    boils at 1310
				Gallium      melts at 30    boils at 4058
				Rubidium     melts at 39    boils at 1282
				Potassium    melts at 63    boils at 1408
				Sodium       melts at 98    boils at 1596
				Indium       melts at 157   boils at 3536
				Lithium      melts at 181   boils at 2349
				Selenium     melts at 217   boils at 1278
				Tin          melts at 232   boils at 4414
				Polonium     melts at 254   boils at 1726
				Bismuth      melts at 271   boils at 2700
				Thallium     melts at 304   boils at 2527
				Cadmium      melts at 321   boils at 1407
				Lead         melts at 328   boils at 3003
				Zinc         melts at 420   boils at 1637
				Tellurium    melts at 450   boils at 1771
   gasses in atmosphere:
				Sulfur           19.2%  PP 33878.2 mb
				Nitrogen         80.3%  PP 141893.4 mb
				Phosphorus        0.4%  PP  676.9 mb


Planet 3	
   Distance from primary:	2.053	AU
   Mass:			2.353	Earth masses
   Equatorial radius:		8442.5	km
   Density:			5.580	grams/cc
   Eccentricity of orbit:	0.288
   Surface gravity:		1.34	Earth gees
   Surface pressure:		5.794	Earth atmospheres
   Surface temperature:		-13.23	degrees Celcius
   Normal daytime temperature:	-11.78	degrees Celcius
   Normal night temperature:	-14.76	degrees Celcius
   Maximum temperature:   	0.14	degrees Celcius
   Minimum temperature:   	-27.30	degrees Celcius
   Escape Velocity:		14.91	km/sec
   Molecular weight retained:	3.57 and above
   Surface acceleration:	1316.58	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.296
   Length of year:		1024.23	days
   Length of day:		13.21	hours
   Boiling point of water:	155.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	9.53
   Ice cover percentage:	25.79
   liquids at surface:
				Ethanol      melts at -114  boils at 131
				Mercury      melts at -39   boils at 451
   gasses in atmosphere:
				Nitrogen          0.9%  PP   50.7 mb
				Helium           99.1%  PP 5743.3 mb


Planet 4	*gas giant*
   Distance from primary:	3.007	AU
   Mass:			250.901	Earth masses
   Equatorial radius:		57066.1	km
   Density:			1.926	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		59.22	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	3072.45	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.493
   Length of year:		1815.42	days
   Length of day:		7.37	hours


Planet 5	*gas giant*
   Distance from primary:	3.841	AU
   Mass:			1.714	Earth masses
   Equatorial radius:		13602.5	km
   Density:			0.972	grams/cc
   Eccentricity of orbit:	0.016
   Escape Velocity:		10.02	km/sec
   Molecular weight retained:	7.90 and above
   Surface acceleration:	369.37	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.485
   Length of year:		2621.53	days
   Length of day:		21.27	hours


Planet 6	*gas giant*
   Distance from primary:	4.856	AU
   Mass:			3.522	Earth masses
   Equatorial radius:		17113.1	km
   Density:			1.003	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		12.81	km/sec
   Molecular weight retained:	4.84 and above
   Surface acceleration:	479.55	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.493
   Length of year:		3725.37	days
   Length of day:		18.66	hours


Planet 7	*gas giant*
   Distance from primary:	8.014	AU
   Mass:			13.162	Earth masses
   Equatorial radius:		26209.9	km
   Density:			1.043	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		20.01	km/sec
   Molecular weight retained:	1.98 and above
   Surface acceleration:	764.08	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.540
   Length of year:		7899.29	days
   Length of day:		14.79	hours


Planet 8	*gas giant*
   Distance from primary:	13.334	AU
   Mass:			862.410	Earth masses
   Equatorial radius:		92612.6	km
   Density:			1.549	grams/cc
   Eccentricity of orbit:	0.120
   Escape Velocity:		86.18	km/sec
   Molecular weight retained:	0.11 and above
   Surface acceleration:	4009.71	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.451
   Length of year:		16933.87	days
   Length of day:		6.45	hours


Planet 9	
   Distance from primary:	19.596	AU
   Mass:			0.449	Earth masses
   Equatorial radius:		6573.9	km
   Density:			2.254	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.42	Earth gees
   Surface pressure:		0.001	Earth atmospheres
   Surface temperature:		-203.76	degrees Celcius
   Normal daytime temperature:	-196.50	degrees Celcius
   Normal night temperature:	-210.99	degrees Celcius
   Maximum temperature:   	-181.72	degrees Celcius
   Minimum temperature:   	-226.87	degrees Celcius
   Escape Velocity:		7.38	km/sec
   Molecular weight retained:	14.58 and above
   Surface acceleration:	414.09	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.147
   Length of year:		30204.08	days
   Length of day:		23.55	hours
   Boiling point of water:	-33.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.12
   gasses in atmosphere:
				Neon             100.0%  PP    0.5 mb


Planet 10	*gas giant*
   Distance from primary:	40.935	AU
   Mass:			2.550	Earth masses
   Equatorial radius:		18602.7	km
   Density:			0.565	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		10.46	km/sec
   Molecular weight retained:	7.26 and above
   Surface acceleration:	293.82	cm/sec2
   Axial tilt:			65	degrees
   Planetary albedo:		0.550
   Length of year:		91191.80	days
   Length of day:		23.84	hours


