                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950484fd
Stellar mass: 1.10 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6179 K
Stellar class: F8
Age: 1.133 billion years  (5.758 billion left on main sequence)
Habitable ecosphere radius: 1.264 AU

Planets present at:
1	  0.310 AU	no atmosphere
2	  0.659 AU	no atmosphere
3	  0.863 AU	greenhouse
4	  2.068 AU	gas giant
5	  4.108 AU	gas giant
6	  9.428 AU	gas giant
7	 13.522 AU	cold
8	 24.224 AU	gas giant
9	 39.286 AU	gas giant
10	 46.818 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.310	AU
   Mass:			0.240	Earth masses
   Equatorial radius:		4005.9	km
   Density:			5.318	grams/cc
   Eccentricity of orbit:	0.215
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		280.35	degrees Celcius
   Normal daytime temperature:	501.24	degrees Celcius
   Normal night temperature:	-150.82	degrees Celcius
   Maximum temperature:   	505.57	degrees Celcius
   Minimum temperature:   	-167.32	degrees Celcius
   Escape Velocity:		6.91	km/sec
   Molecular weight retained:	16.64 and above
   Surface acceleration:	595.33	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.067
   Length of year:		60.06	days
   Length of day:		931.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.659	AU
   Mass:			0.172	Earth masses
   Equatorial radius:		3587.1	km
   Density:			5.303	grams/cc
   Eccentricity of orbit:	0.093
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		105.71	degrees Celcius
   Normal daytime temperature:	227.47	degrees Celcius
   Normal night temperature:	-33.33	degrees Celcius
   Maximum temperature:   	249.30	degrees Celcius
   Minimum temperature:   	-62.42	degrees Celcius
   Escape Velocity:		6.18	km/sec
   Molecular weight retained:	20.81 and above
   Surface acceleration:	531.65	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.075
   Length of year:		186.11	days
   Length of day:		116.09	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 3	
   Distance from primary:	0.863	AU
   Mass:			1.595	Earth masses
   Equatorial radius:		7450.6	km
   Density:			5.502	grams/cc
   Eccentricity of orbit:	0.091
   Surface gravity:		1.17	Earth gees
   Surface pressure:		227.715	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		544.25	degrees Celcius
   Maximum temperature:   	546.74	degrees Celcius
   Minimum temperature:   	538.85	degrees Celcius
   Escape Velocity:		13.07	km/sec
   Molecular weight retained:	4.65 and above
   Surface acceleration:	1145.76	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.479
   Length of year:		279.24	days
   Length of day:		14.53	hours
   Boiling point of water:	349.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1313
				Cesium       melts at 28    boils at 1359
				Gallium      melts at 30    boils at 4193
				Rubidium     melts at 39    boils at 1331
				Potassium    melts at 63    boils at 1461
				Sodium       melts at 98    boils at 1654
				Indium       melts at 157   boils at 3654
				Lithium      melts at 181   boils at 2431
				Selenium     melts at 217   boils at 1326
				Tin          melts at 232   boils at 4561
				Polonium     melts at 254   boils at 1788
				Bismuth      melts at 271   boils at 2793
				Thallium     melts at 304   boils at 2614
				Cadmium      melts at 321   boils at 1459
				Lead         melts at 328   boils at 3105
				Zinc         melts at 420   boils at 1696
				Tellurium    melts at 450   boils at 1835
   gasses in atmosphere:
				Sulfur           18.0%  PP 41065.4 mb
				Nitrogen         81.4%  PP 185387.4 mb
				Phosphorus        0.4%  PP  822.5 mb


Planet 4	*gas giant*
   Distance from primary:	2.068	AU
   Mass:			22.206	Earth masses
   Equatorial radius:		27264.3	km
   Density:			1.563	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		25.49	km/sec
   Molecular weight retained:	1.22 and above
   Surface acceleration:	1191.32	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.497
   Length of year:		1034.62	days
   Length of day:		11.84	hours


Planet 5	*gas giant*
   Distance from primary:	4.108	AU
   Mass:			379.933	Earth masses
   Equatorial radius:		66089.3	km
   Density:			1.878	grams/cc
   Eccentricity of orbit:	0.038
   Escape Velocity:		67.71	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3468.84	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.473
   Length of year:		2895.89	days
   Length of day:		6.94	hours


Planet 6	*gas giant*
   Distance from primary:	9.428	AU
   Mass:			924.417	Earth masses
   Equatorial radius:		91797.1	km
   Density:			1.705	grams/cc
   Eccentricity of orbit:	0.034
   Escape Velocity:		89.62	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4374.71	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.527
   Length of year:		10061.74	days
   Length of day:		6.18	hours


Planet 7	
   Distance from primary:	13.522	AU
   Mass:			0.637	Earth masses
   Equatorial radius:		7369.3	km
   Density:			2.272	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.276	Earth atmospheres
   Surface temperature:		-189.71	degrees Celcius
   Normal daytime temperature:	-186.56	degrees Celcius
   Normal night temperature:	-193.07	degrees Celcius
   Maximum temperature:   	-172.57	degrees Celcius
   Minimum temperature:   	-208.63	degrees Celcius
   Escape Velocity:		8.30	km/sec
   Molecular weight retained:	11.51 and above
   Surface acceleration:	467.93	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.354
   Length of year:		17303.64	days
   Length of day:		22.16	hours
   Boiling point of water:	67.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	34.61
   liquids at surface:
				Ozone        melts at -193  boils at -126
   gasses in atmosphere:
				Nitrogen         100.0%  PP  276.3 mb


Planet 8	*gas giant*
   Distance from primary:	24.224	AU
   Mass:			68.440	Earth masses
   Equatorial radius:		46476.6	km
   Density:			0.973	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		34.27	km/sec
   Molecular weight retained:	0.68 and above
   Surface acceleration:	1263.50	cm/sec2
   Axial tilt:			56	degrees
   Planetary albedo:		0.530
   Length of year:		41488.73	days
   Length of day:		11.50	hours


Planet 9	*gas giant*
   Distance from primary:	39.286	AU
   Mass:			0.962	Earth masses
   Equatorial radius:		13948.7	km
   Density:			0.506	grams/cc
   Eccentricity of orbit:	0.070
   Escape Velocity:		7.42	km/sec
   Molecular weight retained:	14.43 and above
   Surface acceleration:	197.18	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.522
   Length of year:		85693.41	days
   Length of day:		29.11	hours


Planet 10	
   Distance from primary:	46.818	AU
   Mass:			0.056	Earth masses
   Equatorial radius:		3314.0	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.86	degrees Celcius
   Normal daytime temperature:	-222.52	degrees Celcius
   Normal night temperature:	-235.09	degrees Celcius
   Maximum temperature:   	-206.70	degrees Celcius
   Minimum temperature:   	-250.78	degrees Celcius
   Escape Velocity:		3.68	km/sec
   Molecular weight retained:	58.71 and above
   Surface acceleration:	204.01	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.139
   Length of year:		111482.50	days
   Length of day:		33.55	hours
   Boiling point of water:	-73.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


