                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488ea
Stellar mass: 1.11 solar masses
Stellar radius: 1.08 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6152 K
Stellar class: F8
Age: 5.871 billion years  (0.891 billion left on main sequence)
Habitable ecosphere radius: 1.280 AU

Planets present at:
1	  0.330 AU	no atmosphere
2	  0.380 AU	no atmosphere
3	  0.407 AU	no atmosphere
4	  0.487 AU	no atmosphere
5	  0.860 AU	greenhouse
6	  1.162 AU	greenhouse
7	  1.646 AU	high pressure
8	  2.888 AU	gas giant
9	  4.191 AU	gas giant
10	  9.289 AU	gas giant
11	 22.861 AU	gas giant
12	 44.510 AU	gas giant
13	 51.219 AU	no atmosphere



Planet 1	
   Distance from primary:	0.330	AU
   Mass:			0.033	Earth masses
   Equatorial radius:		2072.1	km
   Density:			5.265	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.31	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		267.44	degrees Celcius
   Normal daytime temperature:	488.11	degrees Celcius
   Normal night temperature:	-175.92	degrees Celcius
   Maximum temperature:   	491.30	degrees Celcius
   Minimum temperature:   	-187.27	degrees Celcius
   Escape Velocity:		3.55	km/sec
   Molecular weight retained:	62.82 and above
   Surface acceleration:	304.90	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.063
   Length of year:		65.70	days
   Length of day:		1576.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.380	AU
   Mass:			1/240.7	Earth masses
   Equatorial radius:		1041.3	km
   Density:			5.251	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.16	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		230.81	degrees Celcius
   Maximum temperature:   	446.95	degrees Celcius
   Minimum temperature:   	-197.31	degrees Celcius
   Escape Velocity:		1.78	km/sec
   Molecular weight retained:	249.44 and above
   Surface acceleration:	152.81	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.057
   Length of year:		81.46	days
   Length of day:		1955.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 3	
   Distance from primary:	0.407	AU
   Mass:			0.230	Earth masses
   Equatorial radius:		3949.6	km
   Density:			5.316	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.60	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		213.88	degrees Celcius
   Maximum temperature:   	426.41	degrees Celcius
   Minimum temperature:   	-201.76	degrees Celcius
   Escape Velocity:		6.81	km/sec
   Molecular weight retained:	17.13 and above
   Surface acceleration:	586.74	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.061
   Length of year:		89.98	days
   Length of day:		2159.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 4	
   Distance from primary:	0.487	AU
   Mass:			1/7419	Earth masses
   Equatorial radius:		332.2	km
   Density:			5.246	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.05	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		170.75	degrees Celcius
   Maximum temperature:   	373.77	degrees Celcius
   Minimum temperature:   	-212.17	degrees Celcius
   Escape Velocity:		0.57	km/sec
   Molecular weight retained:	2452.96 and above
   Surface acceleration:	48.71	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.070
   Length of year:		117.98	days
   Length of day:		2831.56	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 5	
   Distance from primary:	0.860	AU
   Mass:			0.305	Earth masses
   Equatorial radius:		4337.6	km
   Density:			5.330	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.66	Earth gees
   Surface pressure:		9.092	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		101.92	degrees Celcius
   Normal daytime temperature:	106.19	degrees Celcius
   Normal night temperature:	96.74	degrees Celcius
   Maximum temperature:   	115.89	degrees Celcius
   Minimum temperature:   	86.69	degrees Celcius
   Escape Velocity:		7.49	km/sec
   Molecular weight retained:	14.16 and above
   Surface acceleration:	646.16	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.457
   Length of year:		276.85	days
   Length of day:		40.91	hours
   Boiling point of water:	172.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 480
				Francium     melts at 27    boils at 862
				Cesium       melts at 28    boils at 895
				Gallium      melts at 30    boils at 2924
				Rubidium     melts at 39    boils at 875
				Phosphorus   melts at 44    boils at 388
				Potassium    melts at 63    boils at 968
				Sodium       melts at 98    boils at 1106
   gasses in atmosphere:
				Water             5.7%  PP  519.1 mb
				CarbonDioxide    27.5%  PP 2498.6 mb
				Methane           2.9%  PP  261.6 mb
				Ammonia           4.2%  PP  382.5 mb
				Ozone            28.7%  PP 2607.4 mb
				Ethanol          28.5%  PP 2593.4 mb
				Argon             0.1%  PP   10.6 mb
				Neon              0.3%  PP   26.6 mb
				Krypton           1.9%  PP  170.5 mb
				Xenon             0.2%  PP   21.5 mb


Planet 6	
   Distance from primary:	1.162	AU
   Mass:			2.746	Earth masses
   Equatorial radius:		8868.4	km
   Density:			5.617	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		1.42	Earth gees
   Surface pressure:		642.045	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		556.51	degrees Celcius
   Maximum temperature:   	557.91	degrees Celcius
   Minimum temperature:   	552.17	degrees Celcius
   Escape Velocity:		15.71	km/sec
   Molecular weight retained:	3.21 and above
   Surface acceleration:	1392.18	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.515
   Length of year:		434.99	days
   Length of day:		13.03	hours
   Boiling point of water:	440.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1545
				Cesium       melts at 28    boils at 1598
				Gallium      melts at 30    boils at 4848
				Rubidium     melts at 39    boils at 1566
				Potassium    melts at 63    boils at 1715
				Sodium       melts at 98    boils at 1936
				Indium       melts at 157   boils at 4230
				Lithium      melts at 181   boils at 2827
				Selenium     melts at 217   boils at 1560
				Tin          melts at 232   boils at 5269
				Polonium     melts at 254   boils at 2090
				Bismuth      melts at 271   boils at 3242
				Thallium     melts at 304   boils at 3037
				Cadmium      melts at 321   boils at 1713
				Lead         melts at 328   boils at 3600
				Zinc         melts at 420   boils at 1985
				Tellurium    melts at 450   boils at 2144
   gasses in atmosphere:
				Sulfur            0.2%  PP  996.3 mb
				Nitrogen          0.7%  PP 4367.4 mb
				Helium           99.2%  PP 636653.2 mb


Planet 7	
   Distance from primary:	1.646	AU
   Mass:			1.536	Earth masses
   Equatorial radius:		7361.3	km
   Density:			5.496	grams/cc
   Eccentricity of orbit:	0.028
   Surface gravity:		1.15	Earth gees
   Surface pressure:		2.334	Earth atmospheres
   Surface temperature:		3.61	degrees Celcius
   Normal daytime temperature:	6.20	degrees Celcius
   Normal night temperature:	0.86	degrees Celcius
   Maximum temperature:   	20.98	degrees Celcius
   Minimum temperature:   	-14.75	degrees Celcius
   Escape Velocity:		12.90	km/sec
   Molecular weight retained:	4.77 and above
   Surface acceleration:	1130.72	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.178
   Length of year:		733.24	days
   Length of day:		14.29	hours
   Boiling point of water:	124.9	degrees Celcius
   Hydrosphere percentage:	81.03
   Cloud cover percentage:	24.87
   Ice cover percentage:	6.38
   liquids at surface:
				Ethanol      melts at -114  boils at 102
				Mercury      melts at -39   boils at 399
				Bromine      melts at -7    boils at 82
				Water        melts at 0     boils at 125
   gasses in atmosphere:
				Oxygen            2.3%  PP   54.0 mb
				Nitrogen         97.5%  PP 2276.2 mb
				CarbonDioxide     0.1%  PP    1.2 mb
				Ozone             0.1%  PP    1.2 mb


Planet 8	*gas giant*
   Distance from primary:	2.888	AU
   Mass:			3.301	Earth masses
   Equatorial radius:		16062.3	km
   Density:			1.137	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		12.80	km/sec
   Molecular weight retained:	4.84 and above
   Surface acceleration:	510.26	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.524
   Length of year:		1703.47	days
   Length of day:		18.09	hours


Planet 9	*gas giant*
   Distance from primary:	4.191	AU
   Mass:			178.384	Earth masses
   Equatorial radius:		53046.6	km
   Density:			1.705	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		51.79	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2528.01	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.504
   Length of year:		2978.01	days
   Length of day:		8.13	hours


Planet 10	*gas giant*
   Distance from primary:	9.289	AU
   Mass:			1117.642	Earth masses
   Equatorial radius:		96806.4	km
   Density:			1.758	grams/cc
   Eccentricity of orbit:	0.064
   Escape Velocity:		95.96	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4755.91	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.496
   Length of year:		9813.75	days
   Length of day:		5.93	hours


Planet 11	*gas giant*
   Distance from primary:	22.861	AU
   Mass:			2.704	Earth masses
   Equatorial radius:		18004.9	km
   Density:			0.661	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		10.94	km/sec
   Molecular weight retained:	6.63 and above
   Surface acceleration:	332.58	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.547
   Length of year:		37944.12	days
   Length of day:		22.41	hours


Planet 12	*gas giant*
   Distance from primary:	44.510	AU
   Mass:			0.751	Earth masses
   Equatorial radius:		13101.7	km
   Density:			0.477	grams/cc
   Eccentricity of orbit:	0.104
   Escape Velocity:		6.76	km/sec
   Molecular weight retained:	17.35 and above
   Surface acceleration:	174.58	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.463
   Length of year:		103083.62	days
   Length of day:		30.93	hours


Planet 13	
   Distance from primary:	51.219	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		2465.6	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.67	degrees Celcius
   Normal daytime temperature:	-223.77	degrees Celcius
   Normal night temperature:	-237.43	degrees Celcius
   Maximum temperature:   	-210.97	degrees Celcius
   Minimum temperature:   	-250.24	degrees Celcius
   Escape Velocity:		2.73	km/sec
   Molecular weight retained:	106.43 and above
   Surface acceleration:	151.26	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.148
   Length of year:		127248.10	days
   Length of day:		38.97	hours
   Boiling point of water:	-87.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.04


