                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048032
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6262 K
Stellar class: F8
Age: 1.746 billion years  (5.307 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.384 AU	no atmosphere
2	  0.559 AU	no atmosphere
3	  1.126 AU	greenhouse
4	  2.265 AU	gas giant
5	  4.227 AU	gas giant
6	  7.300 AU	gas giant
7	 11.273 AU	no atmosphere
8	 17.632 AU	gas giant
9	 21.280 AU	no atmosphere
10	 33.229 AU	gas giant
11	 45.775 AU	gas giant



Planet 1	
   Distance from primary:	0.384	AU
   Mass:			0.041	Earth masses
   Equatorial radius:		2222.8	km
   Density:			5.268	grams/cc
   Eccentricity of orbit:	0.042
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		220.15	degrees Celcius
   Maximum temperature:   	434.09	degrees Celcius
   Minimum temperature:   	-199.81	degrees Celcius
   Escape Velocity:		3.81	km/sec
   Molecular weight retained:	54.56 and above
   Surface acceleration:	327.25	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.069
   Length of year:		83.10	days
   Length of day:		1994.35	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.559	AU
   Mass:			0.511	Earth masses
   Equatorial radius:		5142.5	km
   Density:			5.365	grams/cc
   Eccentricity of orbit:	0.185
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.80	degrees Celcius
   Normal daytime temperature:	324.53	degrees Celcius
   Normal night temperature:	-206.42	degrees Celcius
   Maximum temperature:   	328.11	degrees Celcius
   Minimum temperature:   	-216.58	degrees Celcius
   Escape Velocity:		8.91	km/sec
   Molecular weight retained:	10.01 and above
   Surface acceleration:	771.07	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.086
   Length of year:		146.02	days
   Length of day:		2411.25	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	1.126	AU
   Mass:			2.932	Earth masses
   Equatorial radius:		9055.7	km
   Density:			5.634	grams/cc
   Eccentricity of orbit:	0.198
   Surface gravity:		1.45	Earth gees
   Surface pressure:		793.681	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		627.90	degrees Celcius
   Maximum temperature:   	628.79	degrees Celcius
   Minimum temperature:   	623.20	degrees Celcius
   Escape Velocity:		16.07	km/sec
   Molecular weight retained:	3.07 and above
   Surface acceleration:	1425.89	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.426
   Length of year:		417.19	days
   Length of day:		12.75	hours
   Boiling point of water:	462.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1601
				Cesium       melts at 28    boils at 1656
				Gallium      melts at 30    boils at 5006
				Rubidium     melts at 39    boils at 1623
				Potassium    melts at 63    boils at 1776
				Sodium       melts at 98    boils at 2005
				Indium       melts at 157   boils at 4369
				Lithium      melts at 181   boils at 2923
				Selenium     melts at 217   boils at 1617
				Tin          melts at 232   boils at 5440
				Polonium     melts at 254   boils at 2163
				Bismuth      melts at 271   boils at 3351
				Thallium     melts at 304   boils at 3140
				Cadmium      melts at 321   boils at 1775
				Lead         melts at 328   boils at 3720
				Zinc         melts at 420   boils at 2055
				Tellurium    melts at 450   boils at 2218
   gasses in atmosphere:
				Sulfur            0.1%  PP  694.0 mb
				Nitrogen          0.4%  PP 3462.1 mb
				Helium           99.5%  PP 789504.9 mb


Planet 4	*gas giant*
   Distance from primary:	2.265	AU
   Mass:			66.328	Earth masses
   Equatorial radius:		37847.0	km
   Density:			1.746	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		37.39	km/sec
   Molecular weight retained:	0.57 and above
   Surface acceleration:	1846.61	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.468
   Length of year:		1189.81	days
   Length of day:		9.51	hours


Planet 5	*gas giant*
   Distance from primary:	4.227	AU
   Mass:			16.362	Earth masses
   Equatorial radius:		26504.6	km
   Density:			1.254	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		22.19	km/sec
   Molecular weight retained:	1.61 and above
   Surface acceleration:	928.84	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.537
   Length of year:		3033.53	days
   Length of day:		13.41	hours


Planet 6	*gas giant*
   Distance from primary:	7.300	AU
   Mass:			1067.971	Earth masses
   Equatorial radius:		93839.4	km
   Density:			1.844	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		95.27	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4836.47	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.495
   Length of year:		6874.28	days
   Length of day:		5.88	hours


Planet 7	
   Distance from primary:	11.273	AU
   Mass:			0.133	Earth masses
   Equatorial radius:		4403.3	km
   Density:			2.216	grams/cc
   Eccentricity of orbit:	0.089
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.010	Earth atmospheres
   Surface temperature:		-186.51	degrees Celcius
   Normal daytime temperature:	-176.59	degrees Celcius
   Normal night temperature:	-196.53	degrees Celcius
   Maximum temperature:   	-156.32	degrees Celcius
   Minimum temperature:   	-217.94	degrees Celcius
   Escape Velocity:		4.90	km/sec
   Molecular weight retained:	33.06 and above
   Surface acceleration:	272.68	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.253
   Length of year:		13212.31	days
   Length of day:		29.02	hours
   Boiling point of water:	5.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	17.53
   liquids at surface:
				Ozone        melts at -193  boils at -152


Planet 8	*gas giant*
   Distance from primary:	17.632	AU
   Mass:			218.342	Earth masses
   Equatorial radius:		63565.5	km
   Density:			1.213	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		52.34	km/sec
   Molecular weight retained:	0.29 and above
   Surface acceleration:	2154.93	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.545
   Length of year:		25837.36	days
   Length of day:		8.80	hours


Planet 9	
   Distance from primary:	21.280	AU
   Mass:			0.288	Earth masses
   Equatorial radius:		5682.7	km
   Density:			2.236	grams/cc
   Eccentricity of orbit:	0.038
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-207.55	degrees Celcius
   Normal daytime temperature:	-200.19	degrees Celcius
   Normal night temperature:	-214.89	degrees Celcius
   Maximum temperature:   	-182.76	degrees Celcius
   Minimum temperature:   	-233.29	degrees Celcius
   Escape Velocity:		6.35	km/sec
   Molecular weight retained:	19.67 and above
   Surface acceleration:	355.15	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.166
   Length of year:		34266.65	days
   Length of day:		25.43	hours
   Boiling point of water:	-43.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.10
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


Planet 10	*gas giant*
   Distance from primary:	33.229	AU
   Mass:			0.466	Earth masses
   Equatorial radius:		11149.3	km
   Density:			0.480	grams/cc
   Eccentricity of orbit:	0.074
   Escape Velocity:		5.78	km/sec
   Molecular weight retained:	23.80 and above
   Surface acceleration:	149.57	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.463
   Length of year:		66863.28	days
   Length of day:		33.42	hours


Planet 11	*gas giant*
   Distance from primary:	45.775	AU
   Mass:			0.435	Earth masses
   Equatorial radius:		11222.9	km
   Density:			0.439	grams/cc
   Eccentricity of orbit:	0.085
   Escape Velocity:		5.56	km/sec
   Molecular weight retained:	25.67 and above
   Surface acceleration:	137.78	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.475
   Length of year:		108109.99	days
   Length of day:		34.82	hours


