                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504852a
Stellar mass: 1.10 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6204 K
Stellar class: F8
Age: 3.353 billion years  (3.532 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.348 AU	no atmosphere
2	  0.496 AU	no atmosphere
3	  0.886 AU	greenhouse
4	  1.220 AU	no atmosphere
5	  1.902 AU	cold
6	  2.234 AU	cold
7	  3.279 AU	gas giant
8	  6.695 AU	gas giant
9	 10.101 AU	gas giant
10	 16.453 AU	no atmosphere
11	 24.344 AU	gas giant
12	 39.149 AU	gas giant
13	 50.371 AU	no atmosphere



Planet 1	
   Distance from primary:	0.348	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		1967.3	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.037
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		246.64	degrees Celcius
   Normal daytime temperature:	463.05	degrees Celcius
   Normal night temperature:	-181.89	degrees Celcius
   Maximum temperature:   	466.13	degrees Celcius
   Minimum temperature:   	-192.45	degrees Celcius
   Escape Velocity:		3.37	km/sec
   Molecular weight retained:	69.72 and above
   Surface acceleration:	289.37	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.084
   Length of year:		71.55	days
   Length of day:		1717.29	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.496	AU
   Mass:			0.504	Earth masses
   Equatorial radius:		5116.9	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.177
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		162.23	degrees Celcius
   Normal daytime temperature:	359.59	degrees Celcius
   Normal night temperature:	-199.19	degrees Celcius
   Maximum temperature:   	363.12	degrees Celcius
   Minimum temperature:   	-209.80	degrees Celcius
   Escape Velocity:		8.86	km/sec
   Molecular weight retained:	10.11 and above
   Surface acceleration:	767.06	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.085
   Length of year:		121.70	days
   Length of day:		2041.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.886	AU
   Mass:			1.250	Earth masses
   Equatorial radius:		6885.2	km
   Density:			5.463	grams/cc
   Eccentricity of orbit:	0.027
   Surface gravity:		1.07	Earth gees
   Surface pressure:		132.970	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		419.95	degrees Celcius
   Maximum temperature:   	423.68	degrees Celcius
   Minimum temperature:   	414.48	degrees Celcius
   Escape Velocity:		12.03	km/sec
   Molecular weight retained:	5.48 and above
   Surface acceleration:	1051.31	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.601
   Length of year:		290.28	days
   Length of day:		16.05	hours
   Boiling point of water:	310.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1214
				Cesium       melts at 28    boils at 1258
				Gallium      melts at 30    boils at 3916
				Rubidium     melts at 39    boils at 1231
				Potassium    melts at 63    boils at 1353
				Sodium       melts at 98    boils at 1534
				Sulfur       melts at 113   boils at 851
				Indium       melts at 157   boils at 3410
				Lithium      melts at 181   boils at 2263
				Selenium     melts at 217   boils at 1226
				Tin          melts at 232   boils at 4260
				Polonium     melts at 254   boils at 1660
				Bismuth      melts at 271   boils at 2602
				Thallium     melts at 304   boils at 2435
				Cadmium      melts at 321   boils at 1352
				Lead         melts at 328   boils at 2895
				Zinc         melts at 420   boils at 1574
   gasses in atmosphere:
				Nitrogen         99.2%  PP 131925.3 mb
				Phosphorus        0.5%  PP  690.8 mb
				CarbonDioxide     0.1%  PP   74.5 mb
				Ethanol           0.1%  PP   75.4 mb


Planet 4	
   Distance from primary:	1.220	AU
   Mass:			0.286	Earth masses
   Equatorial radius:		4249.0	km
   Density:			5.327	grams/cc
   Eccentricity of orbit:	0.150
   Surface gravity:		0.64	Earth gees
   Surface pressure:		0.072	Earth atmospheres
   Surface temperature:		12.12	degrees Celcius
   Normal daytime temperature:	28.26	degrees Celcius
   Normal night temperature:	-4.61	degrees Celcius
   Maximum temperature:   	59.50	degrees Celcius
   Minimum temperature:   	-37.14	degrees Celcius
   Escape Velocity:		7.33	km/sec
   Molecular weight retained:	14.77 and above
   Surface acceleration:	632.54	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.206
   Length of year:		469.13	days
   Length of day:		19.84	hours
   Boiling point of water:	39.4	degrees Celcius
   Hydrosphere percentage:	40.36
   Cloud cover percentage:	23.57
   Ice cover percentage:	2.40
   liquids at surface:
				Ethanol      melts at -114  boils at 22
				Mercury      melts at -39   boils at 255
				Water        melts at 0     boils at 40
   gasses in atmosphere:
				Oxygen           99.2%  PP   71.6 mb
				CarbonDioxide     0.3%  PP    0.2 mb
				Ammonia           0.1%  PP    0.0 mb
				Ozone             0.3%  PP    0.3 mb


Planet 5	
   Distance from primary:	1.902	AU
   Mass:			1.160	Earth masses
   Equatorial radius:		6721.4	km
   Density:			5.453	grams/cc
   Eccentricity of orbit:	0.115
   Surface gravity:		1.04	Earth gees
   Surface pressure:		1.021	Earth atmospheres
   Surface temperature:		-74.58	degrees Celcius
   Normal daytime temperature:	-71.67	degrees Celcius
   Normal night temperature:	-77.65	degrees Celcius
   Maximum temperature:   	-52.17	degrees Celcius
   Minimum temperature:   	-98.57	degrees Celcius
   Escape Velocity:		11.73	km/sec
   Molecular weight retained:	5.77 and above
   Surface acceleration:	1024.30	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.666
   Length of year:		912.57	days
   Length of day:		14.99	hours
   Boiling point of water:	100.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.08
   Ice cover percentage:	84.40
   liquids at surface:
				Ethanol      melts at -114  boils at 79
				Chlorine     melts at -101  boils at -34
				Ammonia      melts at -78   boils at -33
   gasses in atmosphere:
				Oxygen            0.8%  PP    8.4 mb
				Nitrogen         99.0%  PP 1010.7 mb
				CarbonDioxide     0.1%  PP    0.5 mb
				Ozone             0.1%  PP    0.5 mb


Planet 6	
   Distance from primary:	2.234	AU
   Mass:			0.465	Earth masses
   Equatorial radius:		4983.1	km
   Density:			5.358	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.214	Earth atmospheres
   Surface temperature:		-85.36	degrees Celcius
   Normal daytime temperature:	-78.91	degrees Celcius
   Normal night temperature:	-92.11	degrees Celcius
   Maximum temperature:   	-57.23	degrees Celcius
   Minimum temperature:   	-115.28	degrees Celcius
   Escape Velocity:		8.62	km/sec
   Molecular weight retained:	10.68 and above
   Surface acceleration:	746.13	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.537
   Length of year:		1161.81	days
   Length of day:		17.56	hours
   Boiling point of water:	61.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.03
   Ice cover percentage:	80.33
   liquids at surface:
				Ethanol      melts at -114  boils at 43
				Chlorine     melts at -101  boils at -58
   gasses in atmosphere:
				Oxygen           21.5%  PP   46.0 mb
				Nitrogen         78.3%  PP  167.5 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.279	AU
   Mass:			99.457	Earth masses
   Equatorial radius:		43871.7	km
   Density:			1.681	grams/cc
   Eccentricity of orbit:	0.155
   Escape Velocity:		42.52	km/sec
   Molecular weight retained:	0.44 and above
   Surface acceleration:	2060.66	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.466
   Length of year:		2065.75	days
   Length of day:		9.00	hours


Planet 8	*gas giant*
   Distance from primary:	6.695	AU
   Mass:			1100.392	Earth masses
   Equatorial radius:		93862.7	km
   Density:			1.899	grams/cc
   Eccentricity of orbit:	0.045
   Escape Velocity:		96.70	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	4980.82	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.535
   Length of year:		6018.77	days
   Length of day:		5.79	hours


Planet 9	*gas giant*
   Distance from primary:	10.101	AU
   Mass:			70.433	Earth masses
   Equatorial radius:		43570.9	km
   Density:			1.215	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		35.91	km/sec
   Molecular weight retained:	0.62 and above
   Surface acceleration:	1479.54	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.548
   Length of year:		11170.17	days
   Length of day:		10.63	hours


Planet 10	
   Distance from primary:	16.453	AU
   Mass:			0.200	Earth masses
   Equatorial radius:		5041.8	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.029	Earth atmospheres
   Surface temperature:		-200.16	degrees Celcius
   Normal daytime temperature:	-193.34	degrees Celcius
   Normal night temperature:	-207.13	degrees Celcius
   Maximum temperature:   	-175.21	degrees Celcius
   Minimum temperature:   	-226.58	degrees Celcius
   Escape Velocity:		5.62	km/sec
   Molecular weight retained:	25.11 and above
   Surface acceleration:	313.56	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.290
   Length of year:		23223.16	days
   Length of day:		27.07	hours
   Boiling point of water:	22.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.96


Planet 11	*gas giant*
   Distance from primary:	24.344	AU
   Mass:			116.560	Earth masses
   Equatorial radius:		54304.9	km
   Density:			1.039	grams/cc
   Eccentricity of orbit:	0.121
   Escape Velocity:		41.38	km/sec
   Molecular weight retained:	0.46 and above
   Surface acceleration:	1576.20	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.453
   Length of year:		41787.67	days
   Length of day:		10.29	hours


Planet 12	*gas giant*
   Distance from primary:	39.149	AU
   Mass:			0.831	Earth masses
   Equatorial radius:		13359.1	km
   Density:			0.497	grams/cc
   Eccentricity of orbit:	0.130
   Escape Velocity:		7.04	km/sec
   Molecular weight retained:	16.01 and above
   Surface acceleration:	185.60	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.529
   Length of year:		85236.01	days
   Length of day:		30.00	hours


Planet 13	
   Distance from primary:	50.371	AU
   Mass:			1/126.6	Earth masses
   Equatorial radius:		1726.6	km
   Density:			2.190	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.11	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.65	degrees Celcius
   Normal daytime temperature:	-222.64	degrees Celcius
   Normal night temperature:	-238.47	degrees Celcius
   Maximum temperature:   	-210.54	degrees Celcius
   Minimum temperature:   	-250.44	degrees Celcius
   Escape Velocity:		1.91	km/sec
   Molecular weight retained:	217.49 and above
   Surface acceleration:	105.70	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.155
   Length of year:		124399.21	days
   Length of day:		46.62	hours
   Boiling point of water:	-100.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


