                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048aca
Stellar mass: 1.11 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6441 K
Stellar class: F7
Age: 2.435 billion years  (4.267 billion left on main sequence)
Habitable ecosphere radius: 1.287 AU

Planets present at:
1	  0.436 AU	no atmosphere
2	  0.524 AU	no atmosphere
3	  1.010 AU	greenhouse
4	  1.605 AU	cold
5	  2.104 AU	gas giant
6	  2.495 AU	cold
7	  5.539 AU	gas giant
8	 14.534 AU	gas giant
9	 23.535 AU	no atmosphere
10	 28.087 AU	gas giant
11	 47.931 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.436	AU
   Mass:			0.059	Earth masses
   Equatorial radius:		2513.9	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.104
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		196.62	degrees Celcius
   Normal daytime temperature:	402.05	degrees Celcius
   Normal night temperature:	-192.93	degrees Celcius
   Maximum temperature:   	405.24	degrees Celcius
   Minimum temperature:   	-203.01	degrees Celcius
   Escape Velocity:		4.32	km/sec
   Molecular weight retained:	42.61 and above
   Surface acceleration:	370.53	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.075
   Length of year:		99.85	days
   Length of day:		1946.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.524	AU
   Mass:			0.513	Earth masses
   Equatorial radius:		5148.8	km
   Density:			5.365	grams/cc
   Eccentricity of orbit:	0.071
   Surface gravity:		0.79	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		158.06	degrees Celcius
   Maximum temperature:   	358.29	degrees Celcius
   Minimum temperature:   	-215.55	degrees Celcius
   Escape Velocity:		8.92	km/sec
   Molecular weight retained:	9.98 and above
   Surface acceleration:	772.07	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.053
   Length of year:		131.41	days
   Length of day:		3153.80	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	1.010	AU
   Mass:			1.460	Earth masses
   Equatorial radius:		7240.4	km
   Density:			5.488	grams/cc
   Eccentricity of orbit:	0.078
   Surface gravity:		1.13	Earth gees
   Surface pressure:		154.164	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		414.29	degrees Celcius
   Maximum temperature:   	417.78	degrees Celcius
   Minimum temperature:   	409.16	degrees Celcius
   Escape Velocity:		12.68	km/sec
   Molecular weight retained:	4.94 and above
   Surface acceleration:	1110.42	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.558
   Length of year:		351.78	days
   Length of day:		14.73	hours
   Boiling point of water:	321.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1240
				Cesium       melts at 28    boils at 1284
				Gallium      melts at 30    boils at 3989
				Rubidium     melts at 39    boils at 1257
				Potassium    melts at 63    boils at 1381
				Sodium       melts at 98    boils at 1566
				Sulfur       melts at 113   boils at 870
				Indium       melts at 157   boils at 3474
				Lithium      melts at 181   boils at 2307
				Selenium     melts at 217   boils at 1253
				Tin          melts at 232   boils at 4339
				Polonium     melts at 254   boils at 1694
				Bismuth      melts at 271   boils at 2652
				Thallium     melts at 304   boils at 2482
				Cadmium      melts at 321   boils at 1380
				Lead         melts at 328   boils at 2950
   gasses in atmosphere:
				Nitrogen         99.3%  PP 153059.2 mb
				Phosphorus        0.5%  PP  725.7 mb


Planet 4	
   Distance from primary:	1.605	AU
   Mass:			0.551	Earth masses
   Equatorial radius:		5270.2	km
   Density:			5.371	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.81	Earth gees
   Surface pressure:		0.269	Earth atmospheres
   Surface temperature:		-56.09	degrees Celcius
   Normal daytime temperature:	-49.49	degrees Celcius
   Normal night temperature:	-63.03	degrees Celcius
   Maximum temperature:   	-27.36	degrees Celcius
   Minimum temperature:   	-86.56	degrees Celcius
   Escape Velocity:		9.13	km/sec
   Molecular weight retained:	9.52 and above
   Surface acceleration:	791.13	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.619
   Length of year:		705.32	days
   Length of day:		17.09	hours
   Boiling point of water:	67.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.27
   Ice cover percentage:	76.09
   liquids at surface:
				Ethanol      melts at -114  boils at 47
				Chlorine     melts at -101  boils at -55
				Ammonia      melts at -78   boils at -55
   gasses in atmosphere:
				Oxygen           36.6%  PP   98.3 mb
				Nitrogen         63.3%  PP  170.0 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.104	AU
   Mass:			47.755	Earth masses
   Equatorial radius:		34085.8	km
   Density:			1.721	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		33.43	km/sec
   Molecular weight retained:	0.71 and above
   Surface acceleration:	1639.11	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.542
   Length of year:		1057.94	days
   Length of day:		10.10	hours


Planet 6	
   Distance from primary:	2.495	AU
   Mass:			1.338	Earth masses
   Equatorial radius:		7039.2	km
   Density:			5.474	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		1.10	Earth gees
   Surface pressure:		1.307	Earth atmospheres
   Surface temperature:		-97.45	degrees Celcius
   Normal daytime temperature:	-95.21	degrees Celcius
   Normal night temperature:	-99.81	degrees Celcius
   Maximum temperature:   	-79.10	degrees Celcius
   Minimum temperature:   	-117.19	degrees Celcius
   Escape Velocity:		12.31	km/sec
   Molecular weight retained:	5.24 and above
   Surface acceleration:	1076.84	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.671
   Length of year:		1366.18	days
   Length of day:		14.61	hours
   Boiling point of water:	107.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	85.47
   liquids at surface:
				Ethanol      melts at -114  boils at 86
				Chlorine     melts at -101  boils at -29
   gasses in atmosphere:
				Oxygen            2.3%  PP   30.0 mb
				Nitrogen         97.6%  PP 1275.9 mb


Planet 7	*gas giant*
   Distance from primary:	5.539	AU
   Mass:			896.744	Earth masses
   Equatorial radius:		86913.9	km
   Density:			1.949	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		90.71	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4734.01	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.532
   Length of year:		4514.05	days
   Length of day:		5.94	hours


Planet 8	*gas giant*
   Distance from primary:	14.534	AU
   Mass:			200.415	Earth masses
   Equatorial radius:		60842.5	km
   Density:			1.270	grams/cc
   Eccentricity of orbit:	0.078
   Escape Velocity:		51.26	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2159.01	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.479
   Length of year:		19207.40	days
   Length of day:		8.80	hours


Planet 9	
   Distance from primary:	23.535	AU
   Mass:			0.113	Earth masses
   Equatorial radius:		4180.7	km
   Density:			2.213	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-210.42	degrees Celcius
   Normal daytime temperature:	-202.31	degrees Celcius
   Normal night temperature:	-218.49	degrees Celcius
   Maximum temperature:   	-186.85	degrees Celcius
   Minimum temperature:   	-234.73	degrees Celcius
   Escape Velocity:		4.65	km/sec
   Molecular weight retained:	36.72 and above
   Surface acceleration:	258.55	cm/sec2
   Axial tilt:			42	degrees
   Planetary albedo:		0.154
   Length of year:		39587.34	days
   Length of day:		29.81	hours
   Boiling point of water:	-61.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 10	*gas giant*
   Distance from primary:	28.087	AU
   Mass:			25.705	Earth masses
   Equatorial radius:		35310.9	km
   Density:			0.833	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		24.10	km/sec
   Molecular weight retained:	1.37 and above
   Surface acceleration:	822.13	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.538
   Length of year:		51609.11	days
   Length of day:		14.25	hours


Planet 11	
   Distance from primary:	47.931	AU
   Mass:			0.266	Earth masses
   Equatorial radius:		5540.9	km
   Density:			2.234	grams/cc
   Eccentricity of orbit:	0.087
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.91	degrees Celcius
   Normal daytime temperature:	-223.88	degrees Celcius
   Normal night temperature:	-233.85	degrees Celcius
   Maximum temperature:   	-207.18	degrees Celcius
   Minimum temperature:   	-250.63	degrees Celcius
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.71 and above
   Surface acceleration:	345.90	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.156
   Length of year:		115056.50	days
   Length of day:		25.77	hours
   Boiling point of water:	-47.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


