                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048186
Stellar mass: 1.10 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6364 K
Stellar class: F7
Age: 4.935 billion years  (2.073 billion left on main sequence)
Habitable ecosphere radius: 1.251 AU

Planets present at:
1	  0.355 AU	no atmosphere
2	  0.499 AU	no atmosphere
3	  0.922 AU	greenhouse
4	  1.162 AU	greenhouse
5	  1.846 AU	cold
6	  2.257 AU	cold
7	  2.821 AU	gas giant
8	  4.303 AU	gas giant
9	  9.486 AU	gas giant
10	 12.815 AU	gas giant
11	 19.345 AU	gas giant
12	 34.376 AU	no atmosphere
13	 45.083 AU	gas giant



Planet 1	
   Distance from primary:	0.355	AU
   Mass:			0.038	Earth masses
   Equatorial radius:		2170.2	km
   Density:			5.267	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		242.49	degrees Celcius
   Maximum temperature:   	461.00	degrees Celcius
   Minimum temperature:   	-193.28	degrees Celcius
   Escape Velocity:		3.72	km/sec
   Molecular weight retained:	57.25 and above
   Surface acceleration:	319.45	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.058
   Length of year:		73.80	days
   Length of day:		1771.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.499	AU
   Mass:			0.540	Earth masses
   Equatorial radius:		5236.2	km
   Density:			5.370	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		0.80	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		158.94	degrees Celcius
   Maximum temperature:   	359.08	degrees Celcius
   Minimum temperature:   	-211.84	degrees Celcius
   Escape Velocity:		9.07	km/sec
   Molecular weight retained:	9.65 and above
   Surface acceleration:	785.78	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.083
   Length of year:		122.96	days
   Length of day:		2337.93	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.922	AU
   Mass:			1.280	Earth masses
   Equatorial radius:		6939.1	km
   Density:			5.467	grams/cc
   Eccentricity of orbit:	0.018
   Surface gravity:		1.08	Earth gees
   Surface pressure:		165.242	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		484.29	degrees Celcius
   Maximum temperature:   	487.49	degrees Celcius
   Minimum temperature:   	478.75	degrees Celcius
   Escape Velocity:		12.13	km/sec
   Molecular weight retained:	5.39 and above
   Surface acceleration:	1060.23	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.451
   Length of year:		308.62	days
   Length of day:		16.17	hours
   Boiling point of water:	325.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1252
				Cesium       melts at 28    boils at 1297
				Gallium      melts at 30    boils at 4024
				Rubidium     melts at 39    boils at 1270
				Potassium    melts at 63    boils at 1395
				Sodium       melts at 98    boils at 1581
				Indium       melts at 157   boils at 3505
				Lithium      melts at 181   boils at 2328
				Selenium     melts at 217   boils at 1265
				Tin          melts at 232   boils at 4377
				Polonium     melts at 254   boils at 1710
				Bismuth      melts at 271   boils at 2676
				Thallium     melts at 304   boils at 2505
				Cadmium      melts at 321   boils at 1394
				Lead         melts at 328   boils at 2977
				Zinc         melts at 420   boils at 1622
				Tellurium    melts at 450   boils at 1755
   gasses in atmosphere:
				Sulfur           21.6%  PP 35744.8 mb
				Nitrogen         77.7%  PP 128439.9 mb
				Phosphorus        0.4%  PP  710.8 mb


Planet 4	
   Distance from primary:	1.162	AU
   Mass:			0.571	Earth masses
   Equatorial radius:		5330.7	km
   Density:			5.374	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.82	Earth gees
   Surface pressure:		30.246	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		152.19	degrees Celcius
   Maximum temperature:   	159.26	degrees Celcius
   Minimum temperature:   	144.66	degrees Celcius
   Escape Velocity:		9.24	km/sec
   Molecular weight retained:	9.30 and above
   Surface acceleration:	800.64	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.458
   Length of year:		436.93	days
   Length of day:		17.71	hours
   Boiling point of water:	225.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 569
				Francium     melts at 27    boils at 997
				Cesium       melts at 28    boils at 1034
				Gallium      melts at 30    boils at 3303
				Rubidium     melts at 39    boils at 1011
				Phosphorus   melts at 44    boils at 467
				Potassium    melts at 63    boils at 1115
				Sodium       melts at 98    boils at 1270
				Sulfur       melts at 113   boils at 686
				Iodine       melts at 114   boils at 340
   gasses in atmosphere:
				Nitrogen         99.6%  PP 30112.5 mb
				CarbonDioxide     0.1%  PP   30.5 mb
				Ozone             0.1%  PP   29.4 mb
				Ethanol           0.1%  PP   31.1 mb


Planet 5	
   Distance from primary:	1.846	AU
   Mass:			0.616	Earth masses
   Equatorial radius:		5465.2	km
   Density:			5.381	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.84	Earth gees
   Surface pressure:		0.388	Earth atmospheres
   Surface temperature:		-76.00	degrees Celcius
   Normal daytime temperature:	-70.98	degrees Celcius
   Normal night temperature:	-81.28	degrees Celcius
   Maximum temperature:   	-51.31	degrees Celcius
   Minimum temperature:   	-102.34	degrees Celcius
   Escape Velocity:		9.48	km/sec
   Molecular weight retained:	8.84 and above
   Surface acceleration:	821.88	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.650
   Length of year:		874.93	days
   Length of day:		16.76	hours
   Boiling point of water:	75.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.08
   Ice cover percentage:	91.41
   liquids at surface:
				Ethanol      melts at -114  boils at 56
				Chlorine     melts at -101  boils at -50
				Ammonia      melts at -78   boils at -49
   gasses in atmosphere:
				Oxygen            1.5%  PP    5.8 mb
				Nitrogen         98.3%  PP  381.1 mb
				CarbonDioxide     0.1%  PP    0.3 mb
				Ozone             0.1%  PP    0.3 mb


Planet 6	
   Distance from primary:	2.257	AU
   Mass:			0.370	Earth masses
   Equatorial radius:		4624.5	km
   Density:			5.342	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.142	Earth atmospheres
   Surface temperature:		-91.92	degrees Celcius
   Normal daytime temperature:	-84.35	degrees Celcius
   Normal night temperature:	-99.80	degrees Celcius
   Maximum temperature:   	-62.84	degrees Celcius
   Minimum temperature:   	-122.75	degrees Celcius
   Escape Velocity:		7.99	km/sec
   Molecular weight retained:	12.43 and above
   Surface acceleration:	690.41	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.568
   Length of year:		1182.33	days
   Length of day:		18.26	hours
   Boiling point of water:	53.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	78.01
   liquids at surface:
				Ethanol      melts at -114  boils at 34
				Chlorine     melts at -101  boils at -64
   gasses in atmosphere:
				Oxygen            9.6%  PP   13.6 mb
				Nitrogen         90.1%  PP  128.4 mb
				Methane           0.1%  PP    0.1 mb
				Ozone             0.2%  PP    0.3 mb


Planet 7	*gas giant*
   Distance from primary:	2.821	AU
   Mass:			194.118	Earth masses
   Equatorial radius:		52705.3	km
   Density:			1.892	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		54.20	km/sec
   Molecular weight retained:	0.27 and above
   Surface acceleration:	2786.74	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.537
   Length of year:		1652.24	days
   Length of day:		7.74	hours


Planet 8	*gas giant*
   Distance from primary:	4.303	AU
   Mass:			130.518	Earth masses
   Equatorial radius:		48623.6	km
   Density:			1.620	grams/cc
   Eccentricity of orbit:	0.060
   Escape Velocity:		46.27	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	2201.48	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.488
   Length of year:		3112.17	days
   Length of day:		8.71	hours


Planet 9	*gas giant*
   Distance from primary:	9.486	AU
   Mass:			7.731	Earth masses
   Equatorial radius:		22775.3	km
   Density:			0.934	grams/cc
   Eccentricity of orbit:	0.135
   Escape Velocity:		16.45	km/sec
   Molecular weight retained:	2.93 and above
   Surface acceleration:	594.39	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.502
   Length of year:		10189.65	days
   Length of day:		16.76	hours


Planet 10	*gas giant*
   Distance from primary:	12.815	AU
   Mass:			550.514	Earth masses
   Equatorial radius:		81033.7	km
   Density:			1.476	grams/cc
   Eccentricity of orbit:	0.024
   Escape Velocity:		73.61	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3343.30	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.479
   Length of year:		15987.51	days
   Length of day:		7.07	hours


Planet 11	*gas giant*
   Distance from primary:	19.345	AU
   Mass:			38.196	Earth masses
   Equatorial radius:		38512.5	km
   Density:			0.954	grams/cc
   Eccentricity of orbit:	0.051
   Escape Velocity:		28.12	km/sec
   Molecular weight retained:	1.00 and above
   Surface acceleration:	1026.96	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.539
   Length of year:		29673.71	days
   Length of day:		12.75	hours


Planet 12	
   Distance from primary:	34.376	AU
   Mass:			0.126	Earth masses
   Equatorial radius:		4330.6	km
   Density:			2.215	grams/cc
   Eccentricity of orbit:	0.081
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-221.88	degrees Celcius
   Normal daytime temperature:	-215.36	degrees Celcius
   Normal night temperature:	-228.33	degrees Celcius
   Maximum temperature:   	-202.63	degrees Celcius
   Minimum temperature:   	-241.72	degrees Celcius
   Escape Velocity:		4.82	km/sec
   Molecular weight retained:	34.19 and above
   Surface acceleration:	268.06	cm/sec2
   Axial tilt:			60	degrees
   Planetary albedo:		0.150
   Length of year:		70298.05	days
   Length of day:		29.27	hours
   Boiling point of water:	-59.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 13	*gas giant*
   Distance from primary:	45.083	AU
   Mass:			0.543	Earth masses
   Equatorial radius:		11952.0	km
   Density:			0.454	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		6.02	km/sec
   Molecular weight retained:	21.91 and above
   Surface acceleration:	151.57	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.479
   Length of year:		105575.72	days
   Length of day:		33.20	hours


