                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048b04
Stellar mass: 1.11 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.66
Stellar temperature: 6239 K
Stellar class: F8
Age: 5.559 billion years  (1.135 billion left on main sequence)
Habitable ecosphere radius: 1.288 AU

Planets present at:
1	  0.427 AU	no atmosphere
2	  0.577 AU	no atmosphere
3	  0.922 AU	greenhouse
4	  1.227 AU	
5	  2.112 AU	high pressure
6	  3.421 AU	gas giant
7	  6.345 AU	cold
8	  9.568 AU	gas giant
9	 19.089 AU	gas giant
10	 42.012 AU	gas giant



Planet 1	
   Distance from primary:	0.427	AU
   Mass:			0.132	Earth masses
   Equatorial radius:		3287.5	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		203.39	degrees Celcius
   Maximum temperature:   	413.75	degrees Celcius
   Minimum temperature:   	-204.84	degrees Celcius
   Escape Velocity:		5.66	km/sec
   Molecular weight retained:	24.82 and above
   Surface acceleration:	486.41	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.063
   Length of year:		96.70	days
   Length of day:		2320.73	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.577	AU
   Mass:			0.435	Earth masses
   Equatorial radius:		4878.0	km
   Density:			5.353	grams/cc
   Eccentricity of orbit:	0.001
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		134.29	degrees Celcius
   Maximum temperature:   	328.73	degrees Celcius
   Minimum temperature:   	-219.68	degrees Celcius
   Escape Velocity:		8.44	km/sec
   Molecular weight retained:	11.15 and above
   Surface acceleration:	729.76	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.085
   Length of year:		151.94	days
   Length of day:		3646.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.922	AU
   Mass:			1.271	Earth masses
   Equatorial radius:		6923.7	km
   Density:			5.466	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		1.08	Earth gees
   Surface pressure:		136.104	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		417.50	degrees Celcius
   Maximum temperature:   	421.23	degrees Celcius
   Minimum temperature:   	412.03	degrees Celcius
   Escape Velocity:		12.10	km/sec
   Molecular weight retained:	5.42 and above
   Surface acceleration:	1057.69	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.595
   Length of year:		306.87	days
   Length of day:		16.44	hours
   Boiling point of water:	312.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1218
				Cesium       melts at 28    boils at 1262
				Gallium      melts at 30    boils at 3927
				Rubidium     melts at 39    boils at 1235
				Potassium    melts at 63    boils at 1357
				Sodium       melts at 98    boils at 1539
				Sulfur       melts at 113   boils at 854
				Indium       melts at 157   boils at 3420
				Lithium      melts at 181   boils at 2270
				Selenium     melts at 217   boils at 1230
				Tin          melts at 232   boils at 4272
				Polonium     melts at 254   boils at 1665
				Bismuth      melts at 271   boils at 2610
				Thallium     melts at 304   boils at 2442
				Cadmium      melts at 321   boils at 1356
				Lead         melts at 328   boils at 2904
   gasses in atmosphere:
				Nitrogen         99.2%  PP 134953.9 mb
				Phosphorus        0.6%  PP  771.8 mb
				CarbonDioxide     0.1%  PP   85.8 mb
				Ethanol           0.1%  PP   87.2 mb


Planet 4	
   Distance from primary:	1.227	AU
   Mass:			0.995	Earth masses
   Equatorial radius:		6394.0	km
   Density:			5.432	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.99	Earth gees
   Surface pressure:		1.014	Earth atmospheres
   Surface temperature:		20.98	degrees Celcius
   Normal daytime temperature:	25.48	degrees Celcius
   Normal night temperature:	16.18	degrees Celcius
   Maximum temperature:   	45.94	degrees Celcius
   Minimum temperature:   	-5.42	degrees Celcius
   Escape Velocity:		11.14	km/sec
   Molecular weight retained:	6.39 and above
   Surface acceleration:	970.77	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.353
   Length of year:		471.12	days
   Length of day:		15.74	hours
   Boiling point of water:	100.4	degrees Celcius
   Hydrosphere percentage:	72.03
   Cloud cover percentage:	77.67
   Ice cover percentage:	0.76
   liquids at surface:
				Ethanol      melts at -114  boils at 79
				Mercury      melts at -39   boils at 358
				Bromine      melts at -7    boils at 60
				Water        melts at 0     boils at 100
   gasses in atmosphere:
				Oxygen           17.2%  PP  174.4 mb
				Nitrogen         82.6%  PP  837.9 mb
				CarbonDioxide     0.1%  PP    0.6 mb
				Ozone             0.1%  PP    0.6 mb


Planet 5	
   Distance from primary:	2.112	AU
   Mass:			1.798	Earth masses
   Equatorial radius:		7744.8	km
   Density:			5.524	grams/cc
   Eccentricity of orbit:	0.119
   Surface gravity:		1.22	Earth gees
   Surface pressure:		2.706	Earth atmospheres
   Surface temperature:		-74.37	degrees Celcius
   Normal daytime temperature:	-72.68	degrees Celcius
   Normal night temperature:	-76.15	degrees Celcius
   Maximum temperature:   	-58.38	degrees Celcius
   Minimum temperature:   	-91.43	degrees Celcius
   Escape Velocity:		13.61	km/sec
   Molecular weight retained:	4.29 and above
   Surface acceleration:	1195.71	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.653
   Length of year:		1063.73	days
   Length of day:		13.87	hours
   Boiling point of water:	129.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.10
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 106
				Chlorine     melts at -101  boils at -15
				Ammonia      melts at -78   boils at -14
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2702.4 mb


Planet 6	*gas giant*
   Distance from primary:	3.421	AU
   Mass:			378.771	Earth masses
   Equatorial radius:		64931.3	km
   Density:			1.974	grams/cc
   Eccentricity of orbit:	0.026
   Escape Velocity:		68.21	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3582.68	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.495
   Length of year:		2192.02	days
   Length of day:		6.83	hours


Planet 7	
   Distance from primary:	6.345	AU
   Mass:			0.497	Earth masses
   Equatorial radius:		6794.6	km
   Density:			2.259	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.162	Earth atmospheres
   Surface temperature:		-149.25	degrees Celcius
   Normal daytime temperature:	-143.17	degrees Celcius
   Normal night temperature:	-155.66	degrees Celcius
   Maximum temperature:   	-123.67	degrees Celcius
   Minimum temperature:   	-176.83	degrees Celcius
   Escape Velocity:		7.63	km/sec
   Molecular weight retained:	13.62 and above
   Surface acceleration:	428.90	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.304
   Length of year:		5540.81	days
   Length of day:		23.14	hours
   Boiling point of water:	55.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	30.63
   liquids at surface:
				Ozone        melts at -193  boils at -131
   gasses in atmosphere:
				Oxygen           11.7%  PP   18.9 mb
				Nitrogen         88.1%  PP  142.7 mb
				Methane           0.2%  PP    0.2 mb


Planet 8	*gas giant*
   Distance from primary:	9.568	AU
   Mass:			286.320	Earth masses
   Equatorial radius:		65198.2	km
   Density:			1.474	grams/cc
   Eccentricity of orbit:	0.112
   Escape Velocity:		59.18	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2686.09	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.545
   Length of year:		10255.94	days
   Length of day:		7.89	hours


Planet 9	*gas giant*
   Distance from primary:	19.089	AU
   Mass:			302.116	Earth masses
   Equatorial radius:		70151.4	km
   Density:			1.249	grams/cc
   Eccentricity of orbit:	0.102
   Escape Velocity:		58.61	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2448.16	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.460
   Length of year:		28902.94	days
   Length of day:		8.26	hours


Planet 10	*gas giant*
   Distance from primary:	42.012	AU
   Mass:			1.895	Earth masses
   Equatorial radius:		17066.8	km
   Density:			0.544	grams/cc
   Eccentricity of orbit:	0.105
   Escape Velocity:		9.41	km/sec
   Molecular weight retained:	8.97 and above
   Surface acceleration:	259.41	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.539
   Length of year:		94402.42	days
   Length of day:		25.38	hours


