                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504869d
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6278 K
Stellar class: F8
Age: 2.243 billion years  (4.594 billion left on main sequence)
Habitable ecosphere radius: 1.271 AU

Planets present at:
1	  0.413 AU	no atmosphere
2	  0.546 AU	no atmosphere
3	  1.215 AU	gas giant
4	  2.235 AU	cold
5	  4.022 AU	gas giant
6	  5.283 AU	gas giant
7	  8.562 AU	gas giant
8	 19.559 AU	gas giant
9	 41.517 AU	gas giant
10	 51.068 AU	no atmosphere



Planet 1	
   Distance from primary:	0.413	AU
   Mass:			0.246	Earth masses
   Equatorial radius:		4043.4	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		206.19	degrees Celcius
   Maximum temperature:   	417.08	degrees Celcius
   Minimum temperature:   	-203.51	degrees Celcius
   Escape Velocity:		6.97	km/sec
   Molecular weight retained:	16.33 and above
   Surface acceleration:	601.07	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.080
   Length of year:		92.11	days
   Length of day:		2210.68	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.546	AU
   Mass:			0.260	Earth masses
   Equatorial radius:		4113.8	km
   Density:			5.322	grams/cc
   Eccentricity of orbit:	0.179
   Surface gravity:		0.62	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		145.66	degrees Celcius
   Normal daytime temperature:	339.28	degrees Celcius
   Normal night temperature:	-204.22	degrees Celcius
   Maximum temperature:   	342.83	degrees Celcius
   Minimum temperature:   	-214.52	degrees Celcius
   Escape Velocity:		7.09	km/sec
   Molecular weight retained:	15.77 and above
   Surface acceleration:	611.82	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.062
   Length of year:		140.11	days
   Length of day:		2343.04	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	*gas giant*
   Distance from primary:	1.215	AU
   Mass:			8.628	Earth masses
   Equatorial radius:		19788.7	km
   Density:			1.589	grams/cc
   Eccentricity of orbit:	0.215
   Escape Velocity:		18.65	km/sec
   Molecular weight retained:	2.28 and above
   Surface acceleration:	878.64	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.456
   Length of year:		465.46	days
   Length of day:		13.80	hours


Planet 4	
   Distance from primary:	2.235	AU
   Mass:			0.839	Earth masses
   Equatorial radius:		6047.1	km
   Density:			5.412	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.576	Earth atmospheres
   Surface temperature:		-80.08	degrees Celcius
   Normal daytime temperature:	-76.18	degrees Celcius
   Normal night temperature:	-84.20	degrees Celcius
   Maximum temperature:   	-57.15	degrees Celcius
   Minimum temperature:   	-104.63	degrees Celcius
   Escape Velocity:		10.52	km/sec
   Molecular weight retained:	7.18 and above
   Surface acceleration:	914.66	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.562
   Length of year:		1161.43	days
   Length of day:		15.85	hours
   Boiling point of water:	85.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.05
   Ice cover percentage:	81.42
   liquids at surface:
				Ethanol      melts at -114  boils at 65
				Chlorine     melts at -101  boils at -43
   gasses in atmosphere:
				Oxygen           21.9%  PP  126.2 mb
				Nitrogen         78.0%  PP  449.4 mb


Planet 5	*gas giant*
   Distance from primary:	4.022	AU
   Mass:			3.157	Earth masses
   Equatorial radius:		16308.5	km
   Density:			1.039	grams/cc
   Eccentricity of orbit:	0.138
   Escape Velocity:		12.43	km/sec
   Molecular weight retained:	5.14 and above
   Surface acceleration:	473.41	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.452
   Length of year:		2804.45	days
   Length of day:		18.78	hours


Planet 6	*gas giant*
   Distance from primary:	5.283	AU
   Mass:			3.069	Earth masses
   Equatorial radius:		16546.4	km
   Density:			0.967	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		12.16	km/sec
   Molecular weight retained:	5.37 and above
   Surface acceleration:	447.09	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.503
   Length of year:		4221.49	days
   Length of day:		19.33	hours


Planet 7	*gas giant*
   Distance from primary:	8.562	AU
   Mass:			841.747	Earth masses
   Equatorial radius:		88571.5	km
   Density:			1.729	grams/cc
   Eccentricity of orbit:	0.145
   Escape Velocity:		87.06	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4278.91	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.452
   Length of year:		8699.17	days
   Length of day:		6.25	hours


Planet 8	*gas giant*
   Distance from primary:	19.559	AU
   Mass:			206.056	Earth masses
   Equatorial radius:		62940.1	km
   Density:			1.179	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		51.10	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2074.29	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.498
   Length of year:		30063.59	days
   Length of day:		8.97	hours


Planet 9	*gas giant*
   Distance from primary:	41.517	AU
   Mass:			1.746	Earth masses
   Equatorial radius:		16667.3	km
   Density:			0.538	grams/cc
   Eccentricity of orbit:	0.088
   Escape Velocity:		9.14	km/sec
   Molecular weight retained:	9.50 and above
   Surface acceleration:	250.67	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.520
   Length of year:		92997.74	days
   Length of day:		25.81	hours


Planet 10	
   Distance from primary:	51.068	AU
   Mass:			0.015	Earth masses
   Equatorial radius:		2147.3	km
   Density:			2.193	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.13	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.91	degrees Celcius
   Normal daytime temperature:	-223.64	degrees Celcius
   Normal night temperature:	-238.03	degrees Celcius
   Maximum temperature:   	-209.96	degrees Celcius
   Minimum temperature:   	-251.48	degrees Celcius
   Escape Velocity:		2.38	km/sec
   Molecular weight retained:	140.46 and above
   Surface acceleration:	131.60	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.161
   Length of year:		126871.66	days
   Length of day:		41.78	hours
   Boiling point of water:	-92.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


