                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d36
Stellar mass: 1.09 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.52
Stellar temperature: 6083 K
Stellar class: F9
Age: 2.235 billion years  (4.921 billion left on main sequence)
Habitable ecosphere radius: 1.234 AU

Planets present at:
1	  0.311 AU	no atmosphere
2	  0.445 AU	no atmosphere
3	  0.514 AU	no atmosphere
4	  0.609 AU	no atmosphere
5	  0.923 AU	greenhouse
6	  1.439 AU	cold
7	  1.810 AU	high pressure
8	  3.159 AU	gas giant
9	  6.068 AU	gas giant
10	 14.566 AU	gas giant
11	 22.150 AU	gas giant
12	 47.700 AU	gas giant



Planet 1	
   Distance from primary:	0.311	AU
   Mass:			0.058	Earth masses
   Equatorial radius:		2502.0	km
   Density:			5.274	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		269.75	degrees Celcius
   Normal daytime temperature:	490.63	degrees Celcius
   Normal night temperature:	-172.87	degrees Celcius
   Maximum temperature:   	493.72	degrees Celcius
   Minimum temperature:   	-183.88	degrees Celcius
   Escape Velocity:		4.30	km/sec
   Molecular weight retained:	43.02 and above
   Surface acceleration:	368.76	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.086
   Length of year:		60.76	days
   Length of day:		1458.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.445	AU
   Mass:			0.021	Earth masses
   Equatorial radius:		1799.6	km
   Density:			5.260	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		184.06	degrees Celcius
   Maximum temperature:   	390.10	degrees Celcius
   Minimum temperature:   	-208.80	degrees Celcius
   Escape Velocity:		3.09	km/sec
   Molecular weight retained:	83.37 and above
   Surface acceleration:	264.56	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.063
   Length of year:		103.67	days
   Length of day:		2488.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.514	AU
   Mass:			0.462	Earth masses
   Equatorial radius:		4974.8	km
   Density:			5.357	grams/cc
   Eccentricity of orbit:	0.064
   Surface gravity:		0.76	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		151.86	degrees Celcius
   Maximum temperature:   	350.61	degrees Celcius
   Minimum temperature:   	-216.26	degrees Celcius
   Escape Velocity:		8.61	km/sec
   Molecular weight retained:	10.71 and above
   Surface acceleration:	744.85	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.065
   Length of year:		128.89	days
   Length of day:		3093.48	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.609	AU
   Mass:			0.116	Earth masses
   Equatorial radius:		3151.0	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		114.65	degrees Celcius
   Maximum temperature:   	304.32	degrees Celcius
   Minimum temperature:   	-223.19	degrees Celcius
   Escape Velocity:		5.42	km/sec
   Molecular weight retained:	27.04 and above
   Surface acceleration:	465.86	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.090
   Length of year:		166.23	days
   Length of day:		3989.50	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 5	
   Distance from primary:	0.923	AU
   Mass:			0.398	Earth masses
   Equatorial radius:		4734.1	km
   Density:			5.347	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.72	Earth gees
   Surface pressure:		15.141	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		114.30	degrees Celcius
   Maximum temperature:   	123.59	degrees Celcius
   Minimum temperature:   	104.46	degrees Celcius
   Escape Velocity:		8.18	km/sec
   Molecular weight retained:	11.85 and above
   Surface acceleration:	707.39	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.439
   Length of year:		310.21	days
   Length of day:		20.12	hours
   Boiling point of water:	193.7	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 515
				Francium     melts at 27    boils at 915
				Cesium       melts at 28    boils at 950
				Gallium      melts at 30    boils at 3075
				Rubidium     melts at 39    boils at 929
				Phosphorus   melts at 44    boils at 420
				Potassium    melts at 63    boils at 1026
				Sodium       melts at 98    boils at 1171
				Sulfur       melts at 113   boils at 625
				Iodine       melts at 114   boils at 300
   gasses in atmosphere:
				Nitrogen         99.2%  PP 15026.2 mb
				Water             0.1%  PP   11.2 mb
				CarbonDioxide     0.2%  PP   27.4 mb
				Methane           0.1%  PP    8.3 mb
				Ammonia           0.1%  PP    9.6 mb
				Ozone             0.2%  PP   28.0 mb
				Ethanol           0.2%  PP   28.0 mb


Planet 6	
   Distance from primary:	1.439	AU
   Mass:			0.503	Earth masses
   Equatorial radius:		5115.8	km
   Density:			5.364	grams/cc
   Eccentricity of orbit:	0.120
   Surface gravity:		0.78	Earth gees
   Surface pressure:		0.261	Earth atmospheres
   Surface temperature:		-21.23	degrees Celcius
   Normal daytime temperature:	-13.34	degrees Celcius
   Normal night temperature:	-29.51	degrees Celcius
   Maximum temperature:   	11.81	degrees Celcius
   Minimum temperature:   	-56.08	degrees Celcius
   Escape Velocity:		8.86	km/sec
   Molecular weight retained:	10.12 and above
   Surface acceleration:	766.89	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.357
   Length of year:		603.52	days
   Length of day:		17.41	hours
   Boiling point of water:	66.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	3.39
   Ice cover percentage:	41.57
   liquids at surface:
				Ethanol      melts at -114  boils at 47
				Mercury      melts at -39   boils at 300
   gasses in atmosphere:
				Oxygen           43.7%  PP  114.2 mb
				Nitrogen         56.1%  PP  146.6 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.2 mb


Planet 7	
   Distance from primary:	1.810	AU
   Mass:			2.249	Earth masses
   Equatorial radius:		8321.4	km
   Density:			5.570	grams/cc
   Eccentricity of orbit:	0.116
   Surface gravity:		1.32	Earth gees
   Surface pressure:		4.741	Earth atmospheres
   Surface temperature:		-65.91	degrees Celcius
   Normal daytime temperature:	-64.62	degrees Celcius
   Normal night temperature:	-67.27	degrees Celcius
   Maximum temperature:   	-53.32	degrees Celcius
   Minimum temperature:   	-79.27	degrees Celcius
   Escape Velocity:		14.68	km/sec
   Molecular weight retained:	3.68 and above
   Surface acceleration:	1295.36	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.702
   Length of year:		851.71	days
   Length of day:		13.32	hours
   Boiling point of water:	148.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.22
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 124
				Chlorine     melts at -101  boils at -3
				Ammonia      melts at -78   boils at -2
				Radon        melts at -71   boils at -35
   gasses in atmosphere:
				Nitrogen          1.2%  PP   55.6 mb
				Helium           98.8%  PP 4685.6 mb


Planet 8	*gas giant*
   Distance from primary:	3.159	AU
   Mass:			395.621	Earth masses
   Equatorial radius:		65556.6	km
   Density:			2.004	grams/cc
   Eccentricity of orbit:	0.073
   Escape Velocity:		69.38	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3671.01	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.539
   Length of year:		1962.67	days
   Length of day:		6.75	hours


Planet 9	*gas giant*
   Distance from primary:	6.068	AU
   Mass:			404.629	Earth masses
   Equatorial radius:		69677.1	km
   Density:			1.707	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		68.06	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3323.66	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.533
   Length of year:		5224.33	days
   Length of day:		7.09	hours


Planet 10	*gas giant*
   Distance from primary:	14.566	AU
   Mass:			38.799	Earth masses
   Equatorial radius:		37826.5	km
   Density:			1.023	grams/cc
   Eccentricity of orbit:	0.129
   Escape Velocity:		28.60	km/sec
   Molecular weight retained:	0.97 and above
   Surface acceleration:	1081.35	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.463
   Length of year:		19440.97	days
   Length of day:		12.43	hours


Planet 11	*gas giant*
   Distance from primary:	22.150	AU
   Mass:			91.621	Earth masses
   Equatorial radius:		50328.0	km
   Density:			1.026	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		38.10	km/sec
   Molecular weight retained:	0.55 and above
   Surface acceleration:	1442.49	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.450
   Length of year:		36455.76	days
   Length of day:		10.76	hours


Planet 12	*gas giant*
   Distance from primary:	47.700	AU
   Mass:			0.898	Earth masses
   Equatorial radius:		13921.0	km
   Density:			0.475	grams/cc
   Eccentricity of orbit:	0.186
   Escape Velocity:		7.17	km/sec
   Molecular weight retained:	15.43 and above
   Surface acceleration:	184.75	cm/sec2
   Axial tilt:			67	degrees
   Planetary albedo:		0.533
   Length of year:		115221.36	days
   Length of day:		30.07	hours


