                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f9504886f
Stellar mass: 1.11 solar masses
Stellar radius: 1.06 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6203 K
Stellar class: F8
Age: 3.996 billion years  (2.781 billion left on main sequence)
Habitable ecosphere radius: 1.278 AU

Planets present at:
1	  0.421 AU	no atmosphere
2	  0.810 AU	greenhouse
3	  1.234 AU	no atmosphere
4	  1.630 AU	no atmosphere
5	  1.836 AU	cold
6	  2.645 AU	gas giant
7	  4.600 AU	gas giant
8	  9.195 AU	gas giant
9	 17.315 AU	gas giant
10	 33.334 AU	no atmosphere
11	 47.087 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.421	AU
   Mass:			0.354	Earth masses
   Equatorial radius:		4556.5	km
   Density:			5.339	grams/cc
   Eccentricity of orbit:	0.106
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		203.88	degrees Celcius
   Normal daytime temperature:	410.83	degrees Celcius
   Normal night temperature:	-190.48	degrees Celcius
   Maximum temperature:   	414.11	degrees Celcius
   Minimum temperature:   	-201.06	degrees Celcius
   Escape Velocity:		7.87	km/sec
   Molecular weight retained:	12.81 and above
   Surface acceleration:	679.89	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.069
   Length of year:		95.00	days
   Length of day:		1841.60	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.810	AU
   Mass:			1.216	Earth masses
   Equatorial radius:		6824.3	km
   Density:			5.459	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		1.06	Earth gees
   Surface pressure:		109.765	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		497.89	degrees Celcius
   Maximum temperature:   	501.84	degrees Celcius
   Minimum temperature:   	491.35	degrees Celcius
   Escape Velocity:		11.92	km/sec
   Molecular weight retained:	5.59 and above
   Surface acceleration:	1041.25	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.437
   Length of year:		253.25	days
   Length of day:		17.83	hours
   Boiling point of water:	298.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1182
				Cesium       melts at 28    boils at 1225
				Gallium      melts at 30    boils at 3825
				Rubidium     melts at 39    boils at 1199
				Potassium    melts at 63    boils at 1317
				Sodium       melts at 98    boils at 1495
				Indium       melts at 157   boils at 3330
				Lithium      melts at 181   boils at 2208
				Selenium     melts at 217   boils at 1194
				Tin          melts at 232   boils at 4162
				Polonium     melts at 254   boils at 1618
				Bismuth      melts at 271   boils at 2540
				Thallium     melts at 304   boils at 2376
				Cadmium      melts at 321   boils at 1316
				Lead         melts at 328   boils at 2826
				Zinc         melts at 420   boils at 1534
				Tellurium    melts at 450   boils at 1661
   gasses in atmosphere:
				Sulfur           21.6%  PP 23732.2 mb
				Nitrogen         77.7%  PP 85318.9 mb
				Phosphorus        0.4%  PP  472.0 mb


Planet 3	
   Distance from primary:	1.234	AU
   Mass:			0.245	Earth masses
   Equatorial radius:		4035.1	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.049	Earth atmospheres
   Surface temperature:		10.81	degrees Celcius
   Normal daytime temperature:	29.34	degrees Celcius
   Normal night temperature:	-8.31	degrees Celcius
   Maximum temperature:   	55.37	degrees Celcius
   Minimum temperature:   	-35.21	degrees Celcius
   Escape Velocity:		6.96	km/sec
   Molecular weight retained:	16.40 and above
   Surface acceleration:	599.79	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.202
   Length of year:		475.79	days
   Length of day:		20.61	hours
   Boiling point of water:	32.0	degrees Celcius
   Hydrosphere percentage:	35.46
   Cloud cover percentage:	18.79
   Ice cover percentage:	2.82
   liquids at surface:
				Ethanol      melts at -114  boils at 15
				Mercury      melts at -39   boils at 243
				Water        melts at 0     boils at 32
   gasses in atmosphere:
				CarbonDioxide    45.0%  PP   22.0 mb
				Ammonia           2.0%  PP    1.0 mb
				Ozone            48.0%  PP   23.5 mb
				Chlorine          1.1%  PP    0.6 mb
				Argon             0.1%  PP    0.1 mb
				Neon              0.4%  PP    0.2 mb
				Krypton           2.9%  PP    1.4 mb
				Xenon             0.4%  PP    0.2 mb


Planet 4	
   Distance from primary:	1.630	AU
   Mass:			0.119	Earth masses
   Equatorial radius:		3178.6	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.056
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.012	Earth atmospheres
   Surface temperature:		-53.29	degrees Celcius
   Normal daytime temperature:	-33.50	degrees Celcius
   Normal night temperature:	-73.31	degrees Celcius
   Maximum temperature:   	-7.13	degrees Celcius
   Minimum temperature:   	-100.50	degrees Celcius
   Escape Velocity:		5.47	km/sec
   Molecular weight retained:	26.57 and above
   Surface acceleration:	470.01	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.423
   Length of year:		722.60	days
   Length of day:		22.49	hours
   Boiling point of water:	8.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	43.99
   liquids at surface:
				Ethanol      melts at -114  boils at -7
   gasses in atmosphere:
				CarbonDioxide    44.6%  PP    5.4 mb
				Ozone            51.0%  PP    6.2 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           3.9%  PP    0.5 mb
				Xenon             0.5%  PP    0.1 mb


Planet 5	
   Distance from primary:	1.836	AU
   Mass:			0.883	Earth masses
   Equatorial radius:		6150.4	km
   Density:			5.418	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		0.95	Earth gees
   Surface pressure:		0.621	Earth atmospheres
   Surface temperature:		-64.26	degrees Celcius
   Normal daytime temperature:	-60.21	degrees Celcius
   Normal night temperature:	-68.53	degrees Celcius
   Maximum temperature:   	-39.92	degrees Celcius
   Minimum temperature:   	-90.25	degrees Celcius
   Escape Velocity:		10.70	km/sec
   Molecular weight retained:	6.93 and above
   Surface acceleration:	931.30	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.603
   Length of year:		863.69	days
   Length of day:		15.73	hours
   Boiling point of water:	87.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.15
   Ice cover percentage:	80.51
   liquids at surface:
				Ethanol      melts at -114  boils at 67
				Chlorine     melts at -101  boils at -42
				Ammonia      melts at -78   boils at -42
   gasses in atmosphere:
				Oxygen            1.5%  PP    9.5 mb
				Nitrogen         98.3%  PP  610.0 mb
				CarbonDioxide     0.1%  PP    0.4 mb
				Ozone             0.1%  PP    0.4 mb


Planet 6	*gas giant*
   Distance from primary:	2.645	AU
   Mass:			5.479	Earth masses
   Equatorial radius:		18487.0	km
   Density:			1.237	grams/cc
   Eccentricity of orbit:	0.042
   Escape Velocity:		15.38	km/sec
   Molecular weight retained:	3.36 and above
   Surface acceleration:	639.35	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.465
   Length of year:		1493.62	days
   Length of day:		16.16	hours


Planet 7	*gas giant*
   Distance from primary:	4.600	AU
   Mass:			862.970	Earth masses
   Equatorial radius:		84676.4	km
   Density:			2.028	grams/cc
   Eccentricity of orbit:	0.055
   Escape Velocity:		90.16	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4799.65	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.517
   Length of year:		3421.61	days
   Length of day:		5.90	hours


Planet 8	*gas giant*
   Distance from primary:	9.195	AU
   Mass:			188.605	Earth masses
   Equatorial radius:		57570.6	km
   Density:			1.410	grams/cc
   Eccentricity of orbit:	0.013
   Escape Velocity:		51.12	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2269.30	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.549
   Length of year:		9679.06	days
   Length of day:		8.58	hours


Planet 9	*gas giant*
   Distance from primary:	17.315	AU
   Mass:			233.285	Earth masses
   Equatorial radius:		64571.0	km
   Density:			1.236	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		53.68	km/sec
   Molecular weight retained:	0.28 and above
   Surface acceleration:	2231.26	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.524
   Length of year:		25011.01	days
   Length of day:		8.65	hours


Planet 10	
   Distance from primary:	33.334	AU
   Mass:			0.123	Earth masses
   Equatorial radius:		4294.8	km
   Density:			2.214	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.27	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-220.36	degrees Celcius
   Normal daytime temperature:	-213.62	degrees Celcius
   Normal night temperature:	-227.04	degrees Celcius
   Maximum temperature:   	-198.86	degrees Celcius
   Minimum temperature:   	-242.39	degrees Celcius
   Escape Velocity:		4.78	km/sec
   Molecular weight retained:	34.77 and above
   Surface acceleration:	265.78	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.138
   Length of year:		66829.85	days
   Length of day:		29.40	hours
   Boiling point of water:	-61.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 11	*gas giant*
   Distance from primary:	47.087	AU
   Mass:			1.099	Earth masses
   Equatorial radius:		14707.7	km
   Density:			0.493	grams/cc
   Eccentricity of orbit:	0.178
   Escape Velocity:		7.72	km/sec
   Molecular weight retained:	13.32 and above
   Surface acceleration:	202.57	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.496
   Length of year:		112199.32	days
   Length of day:		28.72	hours


