                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950481f0
Stellar mass: 1.10 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.57
Stellar temperature: 6387 K
Stellar class: F7
Age: 3.120 billion years  (3.874 billion left on main sequence)
Habitable ecosphere radius: 1.253 AU

Planets present at:
1	  0.438 AU	no atmosphere
2	  0.890 AU	greenhouse
3	  1.666 AU	cold
4	  2.318 AU	gas giant
5	  3.665 AU	gas giant
6	  5.317 AU	gas giant
7	 11.440 AU	gas giant
8	 17.644 AU	gas giant
9	 33.805 AU	gas giant
10	 45.681 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.438	AU
   Mass:			0.417	Earth masses
   Equatorial radius:		4809.1	km
   Density:			5.350	grams/cc
   Eccentricity of orbit:	0.128
   Surface gravity:		0.73	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		189.33	degrees Celcius
   Normal daytime temperature:	392.94	degrees Celcius
   Normal night temperature:	-193.19	degrees Celcius
   Maximum temperature:   	396.26	degrees Celcius
   Minimum temperature:   	-203.60	degrees Celcius
   Escape Velocity:		8.32	km/sec
   Molecular weight retained:	11.48 and above
   Surface acceleration:	719.03	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.075
   Length of year:		101.09	days
   Length of day:		1876.12	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.890	AU
   Mass:			1.809	Earth masses
   Equatorial radius:		7759.3	km
   Density:			5.525	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		1.22	Earth gees
   Surface pressure:		338.223	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		593.15	degrees Celcius
   Maximum temperature:   	594.98	degrees Celcius
   Minimum temperature:   	587.83	degrees Celcius
   Escape Velocity:		13.64	km/sec
   Molecular weight retained:	4.27 and above
   Surface acceleration:	1198.18	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.452
   Length of year:		292.55	days
   Length of day:		14.62	hours
   Boiling point of water:	381.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1394
				Cesium       melts at 28    boils at 1443
				Gallium      melts at 30    boils at 4422
				Rubidium     melts at 39    boils at 1413
				Potassium    melts at 63    boils at 1549
				Sodium       melts at 98    boils at 1753
				Indium       melts at 157   boils at 3856
				Lithium      melts at 181   boils at 2569
				Selenium     melts at 217   boils at 1408
				Tin          melts at 232   boils at 4808
				Polonium     melts at 254   boils at 1894
				Bismuth      melts at 271   boils at 2950
				Thallium     melts at 304   boils at 2762
				Cadmium      melts at 321   boils at 1548
				Lead         melts at 328   boils at 3278
				Zinc         melts at 420   boils at 1797
				Tellurium    melts at 450   boils at 1943
   gasses in atmosphere:
				Sulfur           18.9%  PP 63757.9 mb
				Nitrogen         80.6%  PP 272578.5 mb
				Phosphorus        0.4%  PP 1274.1 mb


Planet 3	
   Distance from primary:	1.666	AU
   Mass:			1.228	Earth masses
   Equatorial radius:		6846.9	km
   Density:			5.461	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		1.07	Earth gees
   Surface pressure:		1.331	Earth atmospheres
   Surface temperature:		-74.29	degrees Celcius
   Normal daytime temperature:	-71.74	degrees Celcius
   Normal night temperature:	-76.98	degrees Celcius
   Maximum temperature:   	-55.13	degrees Celcius
   Minimum temperature:   	-94.78	degrees Celcius
   Escape Velocity:		11.96	km/sec
   Molecular weight retained:	5.55 and above
   Surface acceleration:	1044.97	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.746
   Length of year:		749.80	days
   Length of day:		14.85	hours
   Boiling point of water:	108.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.09
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 86
				Chlorine     melts at -101  boils at -29
				Ammonia      melts at -78   boils at -28
   gasses in atmosphere:
				Oxygen            0.4%  PP    5.5 mb
				Nitrogen         99.4%  PP 1324.0 mb
				CarbonDioxide     0.1%  PP    0.7 mb
				Ozone             0.1%  PP    0.7 mb


Planet 4	*gas giant*
   Distance from primary:	2.318	AU
   Mass:			4.795	Earth masses
   Equatorial radius:		17616.1	km
   Density:			1.252	grams/cc
   Eccentricity of orbit:	0.041
   Escape Velocity:		14.73	km/sec
   Molecular weight retained:	3.66 and above
   Surface acceleration:	616.17	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.509
   Length of year:		1230.66	days
   Length of day:		16.47	hours


Planet 5	*gas giant*
   Distance from primary:	3.665	AU
   Mass:			5.356	Earth masses
   Equatorial radius:		18901.5	km
   Density:			1.132	grams/cc
   Eccentricity of orbit:	0.115
   Escape Velocity:		15.03	km/sec
   Molecular weight retained:	3.51 and above
   Surface acceleration:	597.79	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.502
   Length of year:		2446.60	days
   Length of day:		16.72	hours


Planet 6	*gas giant*
   Distance from primary:	5.317	AU
   Mass:			587.158	Earth masses
   Equatorial radius:		76726.4	km
   Density:			1.855	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		78.12	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3977.46	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.465
   Length of year:		4271.28	days
   Length of day:		6.48	hours


Planet 7	*gas giant*
   Distance from primary:	11.440	AU
   Mass:			26.341	Earth masses
   Equatorial radius:		33072.8	km
   Density:			1.039	grams/cc
   Eccentricity of orbit:	0.104
   Escape Velocity:		25.20	km/sec
   Molecular weight retained:	1.25 and above
   Surface acceleration:	960.34	cm/sec2
   Axial tilt:			50	degrees
   Planetary albedo:		0.460
   Length of year:		13491.11	days
   Length of day:		13.19	hours


Planet 8	*gas giant*
   Distance from primary:	17.644	AU
   Mass:			333.705	Earth masses
   Equatorial radius:		71909.1	km
   Density:			1.281	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		60.84	km/sec
   Molecular weight retained:	0.21 and above
   Surface acceleration:	2573.56	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.495
   Length of year:		25830.34	days
   Length of day:		8.06	hours


Planet 9	*gas giant*
   Distance from primary:	33.805	AU
   Mass:			5.169	Earth masses
   Equatorial radius:		22511.6	km
   Density:			0.646	grams/cc
   Eccentricity of orbit:	0.072
   Escape Velocity:		13.53	km/sec
   Molecular weight retained:	4.33 and above
   Surface acceleration:	406.73	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.503
   Length of year:		68534.79	days
   Length of day:		20.27	hours


Planet 10	
   Distance from primary:	45.681	AU
   Mass:			0.140	Earth masses
   Equatorial radius:		4478.9	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.79	degrees Celcius
   Normal daytime temperature:	-223.23	degrees Celcius
   Normal night temperature:	-234.24	degrees Celcius
   Maximum temperature:   	-210.21	degrees Celcius
   Minimum temperature:   	-247.69	degrees Celcius
   Escape Velocity:		4.99	km/sec
   Molecular weight retained:	31.93 and above
   Surface acceleration:	277.50	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.162
   Length of year:		107657.33	days
   Length of day:		28.77	hours
   Boiling point of water:	-57.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


