                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048511
Stellar mass: 1.10 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.60
Stellar temperature: 6294 K
Stellar class: F8
Age: 1.448 billion years  (5.441 billion left on main sequence)
Habitable ecosphere radius: 1.265 AU

Planets present at:
1	  0.322 AU	no atmosphere
2	  0.441 AU	no atmosphere
3	  0.768 AU	greenhouse
4	  1.027 AU	greenhouse
5	  2.497 AU	gas giant
6	  4.865 AU	cold
7	  8.050 AU	gas giant
8	 12.982 AU	no atmosphere
9	 20.727 AU	gas giant
10	 29.980 AU	gas giant
11	 39.035 AU	no atmosphere
12	 44.652 AU	no atmosphere
13	 51.003 AU	no atmosphere



Planet 1	
   Distance from primary:	0.322	AU
   Mass:			0.057	Earth masses
   Equatorial radius:		2482.0	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		271.14	degrees Celcius
   Normal daytime temperature:	492.49	degrees Celcius
   Normal night temperature:	-174.21	degrees Celcius
   Maximum temperature:   	495.47	degrees Celcius
   Minimum temperature:   	-184.83	degrees Celcius
   Escape Velocity:		4.26	km/sec
   Molecular weight retained:	43.72 and above
   Surface acceleration:	365.78	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.059
   Length of year:		63.57	days
   Length of day:		1525.71	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.441	AU
   Mass:			0.165	Earth masses
   Equatorial radius:		3542.1	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		191.40	degrees Celcius
   Maximum temperature:   	399.02	degrees Celcius
   Minimum temperature:   	-207.13	degrees Celcius
   Escape Velocity:		6.10	km/sec
   Molecular weight retained:	21.35 and above
   Surface acceleration:	524.84	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.064
   Length of year:		101.92	days
   Length of day:		2446.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.768	AU
   Mass:			0.424	Earth masses
   Equatorial radius:		4837.3	km
   Density:			5.351	grams/cc
   Eccentricity of orbit:	0.159
   Surface gravity:		0.74	Earth gees
   Surface pressure:		13.841	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		152.99	degrees Celcius
   Maximum temperature:   	163.94	degrees Celcius
   Minimum temperature:   	141.28	degrees Celcius
   Escape Velocity:		8.37	km/sec
   Molecular weight retained:	11.34 and above
   Surface acceleration:	723.43	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.444
   Length of year:		234.34	days
   Length of day:		22.18	hours
   Boiling point of water:	189.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 509
				Francium     melts at 27    boils at 906
				Cesium       melts at 28    boils at 940
				Gallium      melts at 30    boils at 3047
				Rubidium     melts at 39    boils at 919
				Phosphorus   melts at 44    boils at 414
				Potassium    melts at 63    boils at 1016
				Sodium       melts at 98    boils at 1159
				Sulfur       melts at 113   boils at 618
				Iodine       melts at 114   boils at 296
   gasses in atmosphere:
				Nitrogen         99.4%  PP 13755.7 mb
				Water             0.1%  PP    8.8 mb
				CarbonDioxide     0.1%  PP   19.7 mb
				Ammonia           0.1%  PP    7.8 mb
				Ozone             0.1%  PP   20.2 mb
				Ethanol           0.1%  PP   20.0 mb


Planet 4	
   Distance from primary:	1.027	AU
   Mass:			1.543	Earth masses
   Equatorial radius:		7371.7	km
   Density:			5.497	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		1.15	Earth gees
   Surface pressure:		229.076	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		469.45	degrees Celcius
   Maximum temperature:   	472.16	degrees Celcius
   Minimum temperature:   	464.63	degrees Celcius
   Escape Velocity:		12.92	km/sec
   Molecular weight retained:	4.75 and above
   Surface acceleration:	1132.46	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.499
   Length of year:		362.40	days
   Length of day:		14.41	hours
   Boiling point of water:	350.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1314
				Cesium       melts at 28    boils at 1360
				Gallium      melts at 30    boils at 4197
				Rubidium     melts at 39    boils at 1332
				Potassium    melts at 63    boils at 1462
				Sodium       melts at 98    boils at 1655
				Indium       melts at 157   boils at 3657
				Lithium      melts at 181   boils at 2433
				Selenium     melts at 217   boils at 1327
				Tin          melts at 232   boils at 4564
				Polonium     melts at 254   boils at 1790
				Bismuth      melts at 271   boils at 2795
				Thallium     melts at 304   boils at 2617
				Cadmium      melts at 321   boils at 1461
				Lead         melts at 328   boils at 3108
				Zinc         melts at 420   boils at 1698
				Tellurium    melts at 450   boils at 1837
   gasses in atmosphere:
				Sulfur           18.2%  PP 41744.4 mb
				Nitrogen         81.2%  PP 186054.3 mb
				Phosphorus        0.4%  PP  835.8 mb


Planet 5	*gas giant*
   Distance from primary:	2.497	AU
   Mass:			369.249	Earth masses
   Equatorial radius:		62876.8	km
   Density:			2.120	grams/cc
   Eccentricity of orbit:	0.185
   Escape Velocity:		68.44	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3724.58	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.524
   Length of year:		1372.23	days
   Length of day:		6.70	hours


Planet 6	
   Distance from primary:	4.865	AU
   Mass:			0.391	Earth masses
   Equatorial radius:		4706.3	km
   Density:			5.345	grams/cc
   Eccentricity of orbit:	0.039
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.122	Earth atmospheres
   Surface temperature:		-143.00	degrees Celcius
   Normal daytime temperature:	-137.30	degrees Celcius
   Normal night temperature:	-148.92	degrees Celcius
   Maximum temperature:   	-116.76	degrees Celcius
   Minimum temperature:   	-171.23	degrees Celcius
   Escape Velocity:		8.14	km/sec
   Molecular weight retained:	12.00 and above
   Surface acceleration:	703.08	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.473
   Length of year:		3734.56	days
   Length of day:		18.07	hours
   Boiling point of water:	49.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	61.18
   liquids at surface:
				Ozone        melts at -193  boils at -134
   gasses in atmosphere:
				Oxygen           76.1%  PP   92.9 mb
				Nitrogen         23.8%  PP   29.1 mb


Planet 7	*gas giant*
   Distance from primary:	8.050	AU
   Mass:			1282.289	Earth masses
   Equatorial radius:		99667.3	km
   Density:			1.848	grams/cc
   Eccentricity of orbit:	0.077
   Escape Velocity:		101.30	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5147.77	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.477
   Length of year:		7934.29	days
   Length of day:		5.70	hours


Planet 8	
   Distance from primary:	12.982	AU
   Mass:			0.314	Earth masses
   Equatorial radius:		5851.1	km
   Density:			2.239	grams/cc
   Eccentricity of orbit:	0.107
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.061	Earth atmospheres
   Surface temperature:		-187.63	degrees Celcius
   Normal daytime temperature:	-181.35	degrees Celcius
   Normal night temperature:	-194.13	degrees Celcius
   Maximum temperature:   	-161.93	degrees Celcius
   Minimum temperature:   	-215.20	degrees Celcius
   Escape Velocity:		6.55	km/sec
   Molecular weight retained:	18.52 and above
   Surface acceleration:	366.19	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.270
   Length of year:		16277.37	days
   Length of day:		25.04	hours
   Boiling point of water:	36.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	24.42
   liquids at surface:
				Ozone        melts at -193  boils at -139
   gasses in atmosphere:
				Fluorine         49.2%  PP   29.8 mb
				Neon             50.8%  PP   30.8 mb


Planet 9	*gas giant*
   Distance from primary:	20.727	AU
   Mass:			9.473	Earth masses
   Equatorial radius:		25768.6	km
   Density:			0.790	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		17.12	km/sec
   Molecular weight retained:	2.71 and above
   Surface acceleration:	568.89	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.496
   Length of year:		32838.55	days
   Length of day:		17.14	hours


Planet 10	*gas giant*
   Distance from primary:	29.980	AU
   Mass:			14.173	Earth masses
   Equatorial radius:		29887.3	km
   Density:			0.758	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		19.45	km/sec
   Molecular weight retained:	2.10 and above
   Surface acceleration:	632.75	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.477
   Length of year:		57121.75	days
   Length of day:		16.25	hours


Planet 11	
   Distance from primary:	39.035	AU
   Mass:			0.096	Earth masses
   Equatorial radius:		3955.0	km
   Density:			2.210	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-224.70	degrees Celcius
   Normal daytime temperature:	-218.28	degrees Celcius
   Normal night temperature:	-231.03	degrees Celcius
   Maximum temperature:   	-208.01	degrees Celcius
   Minimum temperature:   	-241.91	degrees Celcius
   Escape Velocity:		4.40	km/sec
   Molecular weight retained:	41.08 and above
   Surface acceleration:	244.28	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.144
   Length of year:		84868.62	days
   Length of day:		30.66	hours
   Boiling point of water:	-64.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


Planet 12	
   Distance from primary:	44.652	AU
   Mass:			0.197	Earth masses
   Equatorial radius:		5015.4	km
   Density:			2.225	grams/cc
   Eccentricity of orbit:	0.054
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-227.84	degrees Celcius
   Normal daytime temperature:	-222.45	degrees Celcius
   Normal night temperature:	-233.14	degrees Celcius
   Maximum temperature:   	-211.26	degrees Celcius
   Minimum temperature:   	-244.95	degrees Celcius
   Escape Velocity:		5.59	km/sec
   Molecular weight retained:	25.38 and above
   Surface acceleration:	311.86	cm/sec2
   Axial tilt:			64	degrees
   Planetary albedo:		0.164
   Length of year:		103833.35	days
   Length of day:		27.14	hours
   Boiling point of water:	-50.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 13	
   Distance from primary:	51.003	AU
   Mass:			1/271.2	Earth masses
   Equatorial radius:		1339.7	km
   Density:			2.189	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		0.08	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.91	degrees Celcius
   Normal daytime temperature:	-222.09	degrees Celcius
   Normal night temperature:	-239.51	degrees Celcius
   Maximum temperature:   	-205.76	degrees Celcius
   Minimum temperature:   	-254.60	degrees Celcius
   Escape Velocity:		1.48	km/sec
   Molecular weight retained:	361.57 and above
   Surface acceleration:	81.94	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.155
   Length of year:		126755.66	days
   Length of day:		52.94	hours
   Boiling point of water:	-108.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.02


