                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048158
Stellar mass: 1.10 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6381 K
Stellar class: F7
Age: 1.573 billion years  (5.441 billion left on main sequence)
Habitable ecosphere radius: 1.250 AU

Planets present at:
1	  0.377 AU	no atmosphere
2	  0.504 AU	no atmosphere
3	  0.751 AU	no atmosphere
4	  0.843 AU	no atmosphere
5	  1.249 AU	
6	  1.777 AU	gas giant
7	  3.625 AU	gas giant
8	  6.589 AU	gas giant
9	 15.578 AU	gas giant
10	 25.224 AU	gas giant
11	 34.974 AU	gas giant
12	 49.603 AU	no atmosphere



Planet 1	
   Distance from primary:	0.377	AU
   Mass:			0.095	Earth masses
   Equatorial radius:		2951.3	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.098
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		226.91	degrees Celcius
   Normal daytime temperature:	439.27	degrees Celcius
   Normal night temperature:	-188.22	degrees Celcius
   Maximum temperature:   	442.48	degrees Celcius
   Minimum temperature:   	-198.88	degrees Celcius
   Escape Velocity:		5.07	km/sec
   Molecular weight retained:	30.85 and above
   Surface acceleration:	435.88	cm/sec2
   Axial tilt:			11	degrees
   Planetary albedo:		0.059
   Length of year:		80.82	days
   Length of day:		1939.64	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.504	AU
   Mass:			0.323	Earth masses
   Equatorial radius:		4420.9	km
   Density:			5.333	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		156.86	degrees Celcius
   Maximum temperature:   	356.50	degrees Celcius
   Minimum temperature:   	-214.32	degrees Celcius
   Escape Velocity:		7.63	km/sec
   Molecular weight retained:	13.62 and above
   Surface acceleration:	658.97	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.080
   Length of year:		124.94	days
   Length of day:		2998.60	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.751	AU
   Mass:			0.018	Earth masses
   Equatorial radius:		1683.7	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		80.43	degrees Celcius
   Maximum temperature:   	261.38	degrees Celcius
   Minimum temperature:   	-227.49	degrees Celcius
   Escape Velocity:		2.89	km/sec
   Molecular weight retained:	95.27 and above
   Surface acceleration:	247.44	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.069
   Length of year:		226.79	days
   Length of day:		5443.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93
				Potassium    melts at 63    boils at 415


Planet 4	
   Distance from primary:	0.843	AU
   Mass:			0.238	Earth masses
   Equatorial radius:		3998.0	km
   Density:			5.317	grams/cc
   Eccentricity of orbit:	0.009
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		58.86	degrees Celcius
   Normal daytime temperature:	94.62	degrees Celcius
   Normal night temperature:	22.68	degrees Celcius
   Maximum temperature:   	124.59	degrees Celcius
   Minimum temperature:   	-7.93	degrees Celcius
   Escape Velocity:		6.89	km/sec
   Molecular weight retained:	16.71 and above
   Surface acceleration:	594.13	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.088
   Length of year:		269.80	days
   Length of day:		24.47	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Phosphorus   melts at 44    boils at 93


Planet 5	
   Distance from primary:	1.249	AU
   Mass:			0.953	Earth masses
   Equatorial radius:		6305.0	km
   Density:			5.427	grams/cc
   Eccentricity of orbit:	0.174
   Surface gravity:		0.97	Earth gees
   Surface pressure:		0.882	Earth atmospheres
   Surface temperature:		15.47	degrees Celcius
   Normal daytime temperature:	20.16	degrees Celcius
   Normal night temperature:	10.50	degrees Celcius
   Maximum temperature:   	43.53	degrees Celcius
   Minimum temperature:   	-14.21	degrees Celcius
   Escape Velocity:		10.98	km/sec
   Molecular weight retained:	6.58 and above
   Surface acceleration:	956.31	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.329
   Length of year:		486.78	days
   Length of day:		15.59	hours
   Boiling point of water:	96.6	degrees Celcius
   Hydrosphere percentage:	67.26
   Cloud cover percentage:	46.40
   Ice cover percentage:	1.80
   liquids at surface:
				Ethanol      melts at -114  boils at 75
				Mercury      melts at -39   boils at 351
				Bromine      melts at -7    boils at 57
				Water        melts at 0     boils at 97
   gasses in atmosphere:
				Oxygen           30.1%  PP  265.7 mb
				Nitrogen         69.7%  PP  615.0 mb


Planet 6	*gas giant*
   Distance from primary:	1.777	AU
   Mass:			20.442	Earth masses
   Equatorial radius:		26304.4	km
   Density:			1.603	grams/cc
   Eccentricity of orbit:	0.082
   Escape Velocity:		24.90	km/sec
   Molecular weight retained:	1.28 and above
   Surface acceleration:	1178.14	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.453
   Length of year:		826.30	days
   Length of day:		11.91	hours


Planet 7	*gas giant*
   Distance from primary:	3.625	AU
   Mass:			27.827	Earth masses
   Equatorial radius:		30542.1	km
   Density:			1.394	grams/cc
   Eccentricity of orbit:	0.085
   Escape Velocity:		26.96	km/sec
   Molecular weight retained:	1.09 and above
   Surface acceleration:	1189.64	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.502
   Length of year:		2407.27	days
   Length of day:		11.85	hours


Planet 8	*gas giant*
   Distance from primary:	6.589	AU
   Mass:			1220.089	Earth masses
   Equatorial radius:		96698.3	km
   Density:			1.925	grams/cc
   Eccentricity of orbit:	0.067
   Escape Velocity:		100.32	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5203.46	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.510
   Length of year:		5889.94	days
   Length of day:		5.67	hours


Planet 9	*gas giant*
   Distance from primary:	15.578	AU
   Mass:			63.566	Earth masses
   Equatorial radius:		43883.7	km
   Density:			1.073	grams/cc
   Eccentricity of orbit:	0.064
   Escape Velocity:		33.99	km/sec
   Molecular weight retained:	0.69 and above
   Surface acceleration:	1316.30	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.501
   Length of year:		21446.03	days
   Length of day:		11.27	hours


Planet 10	*gas giant*
   Distance from primary:	25.224	AU
   Mass:			48.694	Earth masses
   Equatorial radius:		42265.3	km
   Density:			0.920	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		30.31	km/sec
   Molecular weight retained:	0.86 and above
   Surface acceleration:	1087.04	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.475
   Length of year:		44186.50	days
   Length of day:		12.40	hours


Planet 11	*gas giant*
   Distance from primary:	34.974	AU
   Mass:			2.545	Earth masses
   Equatorial radius:		18362.6	km
   Density:			0.586	grams/cc
   Eccentricity of orbit:	0.171
   Escape Velocity:		10.51	km/sec
   Molecular weight retained:	7.18 and above
   Surface acceleration:	300.94	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.543
   Length of year:		72145.94	days
   Length of day:		23.56	hours


Planet 12	
   Distance from primary:	49.603	AU
   Mass:			0.057	Earth masses
   Equatorial radius:		3321.3	km
   Density:			2.203	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.47	degrees Celcius
   Normal daytime temperature:	-224.37	degrees Celcius
   Normal night temperature:	-236.45	degrees Celcius
   Maximum temperature:   	-211.01	degrees Celcius
   Minimum temperature:   	-249.95	degrees Celcius
   Escape Velocity:		3.69	km/sec
   Molecular weight retained:	58.45 and above
   Surface acceleration:	204.47	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.148
   Length of year:		121858.85	days
   Length of day:		33.52	hours
   Boiling point of water:	-73.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


