                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f07
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6362 K
Stellar class: F7
Age: 2.382 billion years  (4.711 billion left on main sequence)
Habitable ecosphere radius: 1.241 AU

Planets present at:
1	  0.364 AU	no atmosphere
2	  0.493 AU	no atmosphere
3	  0.643 AU	greenhouse
4	  1.037 AU	greenhouse
5	  1.748 AU	gas giant
6	  2.365 AU	no atmosphere
7	  3.330 AU	no atmosphere
8	  5.053 AU	gas giant
9	  9.653 AU	gas giant
10	 15.648 AU	gas giant
11	 21.412 AU	gas giant
12	 38.883 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.364	AU
   Mass:			0.114	Earth masses
   Equatorial radius:		3131.7	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.291
   Surface gravity:		0.47	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		231.72	degrees Celcius
   Normal daytime temperature:	442.45	degrees Celcius
   Normal night temperature:	-164.88	degrees Celcius
   Maximum temperature:   	447.06	degrees Celcius
   Minimum temperature:   	-181.29	degrees Celcius
   Escape Velocity:		5.38	km/sec
   Molecular weight retained:	27.38 and above
   Surface acceleration:	462.95	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.077
   Length of year:		76.69	days
   Length of day:		1011.55	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.493	AU
   Mass:			0.099	Earth masses
   Equatorial radius:		2987.3	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		160.76	degrees Celcius
   Maximum temperature:   	361.45	degrees Celcius
   Minimum temperature:   	-213.90	degrees Celcius
   Escape Velocity:		5.13	km/sec
   Molecular weight retained:	30.11 and above
   Surface acceleration:	441.28	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.074
   Length of year:		121.08	days
   Length of day:		2905.98	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.643	AU
   Mass:			0.588	Earth masses
   Equatorial radius:		5384.3	km
   Density:			5.377	grams/cc
   Eccentricity of orbit:	0.053
   Surface gravity:		0.82	Earth gees
   Surface pressure:		34.501	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		285.12	degrees Celcius
   Maximum temperature:   	294.64	degrees Celcius
   Minimum temperature:   	273.37	degrees Celcius
   Escape Velocity:		9.33	km/sec
   Molecular weight retained:	9.11 and above
   Surface acceleration:	809.11	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.527
   Length of year:		179.95	days
   Length of day:		58.21	hours
   Boiling point of water:	232.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 580
				Francium     melts at 27    boils at 1013
				Cesium       melts at 28    boils at 1051
				Gallium      melts at 30    boils at 3351
				Rubidium     melts at 39    boils at 1028
				Potassium    melts at 63    boils at 1133
				Sodium       melts at 98    boils at 1290
				Sulfur       melts at 113   boils at 699
				Indium       melts at 157   boils at 2913
				Lithium      melts at 181   boils at 1921
				Selenium     melts at 217   boils at 1024
				Tin          melts at 232   boils at 3648
				Polonium     melts at 254   boils at 1399
				Bismuth      melts at 271   boils at 2214
   gasses in atmosphere:
				Nitrogen         98.8%  PP 34086.6 mb
				Phosphorus        0.8%  PP  272.7 mb
				CarbonDioxide     0.1%  PP   31.3 mb
				Ozone             0.1%  PP   31.1 mb
				Ethanol           0.1%  PP   31.9 mb


Planet 4	
   Distance from primary:	1.037	AU
   Mass:			1.014	Earth masses
   Equatorial radius:		6433.5	km
   Density:			5.435	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		1.00	Earth gees
   Surface pressure:		107.641	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		381.06	degrees Celcius
   Maximum temperature:   	385.16	degrees Celcius
   Minimum temperature:   	375.52	degrees Celcius
   Escape Velocity:		11.21	km/sec
   Molecular weight retained:	6.31 and above
   Surface acceleration:	977.19	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.488
   Length of year:		368.89	days
   Length of day:		15.73	hours
   Boiling point of water:	296.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1178
				Cesium       melts at 28    boils at 1221
				Gallium      melts at 30    boils at 3816
				Rubidium     melts at 39    boils at 1195
				Potassium    melts at 63    boils at 1314
				Sodium       melts at 98    boils at 1491
				Sulfur       melts at 113   boils at 824
				Indium       melts at 157   boils at 3322
				Lithium      melts at 181   boils at 2202
				Selenium     melts at 217   boils at 1191
				Tin          melts at 232   boils at 4152
				Polonium     melts at 254   boils at 1614
				Bismuth      melts at 271   boils at 2534
				Thallium     melts at 304   boils at 2370
				Cadmium      melts at 321   boils at 1313
				Lead         melts at 328   boils at 2820
   gasses in atmosphere:
				Nitrogen         99.2%  PP 106775.3 mb
				Phosphorus        0.5%  PP  568.0 mb
				CarbonDioxide     0.1%  PP   60.8 mb
				Ozone             0.1%  PP   54.6 mb
				Ethanol           0.1%  PP   61.5 mb


Planet 5	*gas giant*
   Distance from primary:	1.748	AU
   Mass:			24.006	Earth masses
   Equatorial radius:		27545.4	km
   Density:			1.639	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		26.36	km/sec
   Molecular weight retained:	1.14 and above
   Surface acceleration:	1261.69	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.509
   Length of year:		807.39	days
   Length of day:		11.51	hours


Planet 6	
   Distance from primary:	2.365	AU
   Mass:			0.176	Earth masses
   Equatorial radius:		3619.6	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.55	Earth gees
   Surface pressure:		0.033	Earth atmospheres
   Surface temperature:		-98.58	degrees Celcius
   Normal daytime temperature:	-86.02	degrees Celcius
   Normal night temperature:	-111.41	degrees Celcius
   Maximum temperature:   	-62.72	degrees Celcius
   Minimum temperature:   	-135.91	degrees Celcius
   Escape Velocity:		6.23	km/sec
   Molecular weight retained:	20.44 and above
   Surface acceleration:	536.58	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.501
   Length of year:		1270.45	days
   Length of day:		20.71	hours
   Boiling point of water:	25.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	62.20
   liquids at surface:
				Ethanol      melts at -114  boils at 8
				Chlorine     melts at -101  boils at -82
   gasses in atmosphere:
				Ozone            93.4%  PP   31.0 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           5.7%  PP    1.9 mb
				Xenon             0.7%  PP    0.2 mb


Planet 7	
   Distance from primary:	3.330	AU
   Mass:			0.315	Earth masses
   Equatorial radius:		4383.0	km
   Density:			5.332	grams/cc
   Eccentricity of orbit:	0.013
   Surface gravity:		0.67	Earth gees
   Surface pressure:		0.097	Earth atmospheres
   Surface temperature:		-120.54	degrees Celcius
   Normal daytime temperature:	-113.04	degrees Celcius
   Normal night temperature:	-128.32	degrees Celcius
   Maximum temperature:   	-92.25	degrees Celcius
   Minimum temperature:   	-150.63	degrees Celcius
   Escape Velocity:		7.57	km/sec
   Molecular weight retained:	13.86 and above
   Surface acceleration:	653.14	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.507
   Length of year:		2123.24	days
   Length of day:		18.75	hours
   Boiling point of water:	45.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	69.24
   gasses in atmosphere:
				Oxygen           91.2%  PP   88.0 mb
				Nitrogen          8.8%  PP    8.5 mb


Planet 8	*gas giant*
   Distance from primary:	5.053	AU
   Mass:			1232.652	Earth masses
   Equatorial radius:		94922.0	km
   Density:			2.057	grams/cc
   Eccentricity of orbit:	0.106
   Escape Velocity:		101.77	km/sec
   Molecular weight retained:	0.08 and above
   Surface acceleration:	5455.64	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.515
   Length of year:		3961.03	days
   Length of day:		5.53	hours


Planet 9	*gas giant*
   Distance from primary:	9.653	AU
   Mass:			3.391	Earth masses
   Equatorial radius:		17947.2	km
   Density:			0.837	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		12.28	km/sec
   Molecular weight retained:	5.27 and above
   Surface acceleration:	419.89	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.535
   Length of year:		10477.73	days
   Length of day:		19.95	hours


Planet 10	*gas giant*
   Distance from primary:	15.648	AU
   Mass:			11.337	Earth masses
   Equatorial radius:		26566.8	km
   Density:			0.863	grams/cc
   Eccentricity of orbit:	0.143
   Escape Velocity:		18.45	km/sec
   Molecular weight retained:	2.33 and above
   Surface acceleration:	640.53	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.549
   Length of year:		21623.21	days
   Length of day:		16.15	hours


Planet 11	*gas giant*
   Distance from primary:	21.412	AU
   Mass:			110.760	Earth masses
   Equatorial radius:		53016.6	km
   Density:			1.061	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		40.82	km/sec
   Molecular weight retained:	0.48 and above
   Surface acceleration:	1571.45	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.480
   Length of year:		34608.28	days
   Length of day:		10.31	hours


Planet 12	*gas giant*
   Distance from primary:	38.883	AU
   Mass:			2.605	Earth masses
   Equatorial radius:		18664.4	km
   Density:			0.572	grams/cc
   Eccentricity of orbit:	0.116
   Escape Velocity:		10.55	km/sec
   Molecular weight retained:	7.13 and above
   Surface acceleration:	298.24	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.488
   Length of year:		84700.89	days
   Length of day:		23.67	hours


