                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950485ec
Stellar mass: 1.10 solar masses
Stellar radius: 1.00 solar radii
Stellar luminosity: 1.61
Stellar temperature: 6365 K
Stellar class: F7
Age: 2.930 billion years  (3.930 billion left on main sequence)
Habitable ecosphere radius: 1.268 AU

Planets present at:
1	  0.390 AU	no atmosphere
2	  0.514 AU	no atmosphere
3	  0.533 AU	no atmosphere
4	  0.761 AU	greenhouse
5	  1.281 AU	
6	  1.559 AU	high pressure
7	  3.164 AU	gas giant
8	  7.383 AU	gas giant
9	 13.678 AU	gas giant
10	 26.926 AU	gas giant
11	 44.595 AU	gas giant



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.390	AU
   Mass:			0.120	Earth masses
   Equatorial radius:		3184.2	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.193
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		221.61	degrees Celcius
   Normal daytime temperature:	431.59	degrees Celcius
   Normal night temperature:	-179.02	degrees Celcius
   Maximum temperature:   	435.46	degrees Celcius
   Minimum temperature:   	-192.24	degrees Celcius
   Escape Velocity:		5.48	km/sec
   Molecular weight retained:	26.47 and above
   Surface acceleration:	470.85	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.065
   Length of year:		84.57	days
   Length of day:		1373.81	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.514	AU
   Mass:			1/103.1	Earth masses
   Equatorial radius:		1380.8	km
   Density:			5.254	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.21	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		158.64	degrees Celcius
   Maximum temperature:   	358.86	degrees Celcius
   Minimum temperature:   	-214.78	degrees Celcius
   Escape Velocity:		2.37	km/sec
   Molecular weight retained:	141.76 and above
   Surface acceleration:	202.77	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.056
   Length of year:		128.12	days
   Length of day:		3074.96	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.533	AU
   Mass:			0.076	Earth masses
   Equatorial radius:		2735.3	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		148.57	degrees Celcius
   Maximum temperature:   	346.38	degrees Celcius
   Minimum temperature:   	-216.58	degrees Celcius
   Escape Velocity:		4.70	km/sec
   Molecular weight retained:	35.96 and above
   Surface acceleration:	403.57	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.077
   Length of year:		135.23	days
   Length of day:		3245.57	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.761	AU
   Mass:			1.020	Earth masses
   Equatorial radius:		6445.4	km
   Density:			5.436	grams/cc
   Eccentricity of orbit:	0.119
   Surface gravity:		1.00	Earth gees
   Surface pressure:		86.947	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		444.13	degrees Celcius
   Maximum temperature:   	448.87	degrees Celcius
   Minimum temperature:   	437.28	degrees Celcius
   Escape Velocity:		11.23	km/sec
   Molecular weight retained:	6.29 and above
   Surface acceleration:	979.14	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.566
   Length of year:		230.72	days
   Length of day:		19.27	hours
   Boiling point of water:	283.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1144
				Cesium       melts at 28    boils at 1186
				Gallium      melts at 30    boils at 3720
				Rubidium     melts at 39    boils at 1161
				Potassium    melts at 63    boils at 1277
				Sodium       melts at 98    boils at 1450
				Sulfur       melts at 113   boils at 798
				Indium       melts at 157   boils at 3238
				Lithium      melts at 181   boils at 2144
				Selenium     melts at 217   boils at 1156
				Tin          melts at 232   boils at 4048
				Polonium     melts at 254   boils at 1570
				Bismuth      melts at 271   boils at 2468
				Thallium     melts at 304   boils at 2308
				Cadmium      melts at 321   boils at 1276
				Lead         melts at 328   boils at 2747
				Zinc         melts at 420   boils at 1487
   gasses in atmosphere:
				Nitrogen         99.1%  PP 86204.8 mb
				Phosphorus        0.6%  PP  487.3 mb
				CarbonDioxide     0.1%  PP   53.3 mb
				Ozone             0.1%  PP   48.1 mb
				Ethanol           0.1%  PP   54.0 mb


Planet 5	
   Distance from primary:	1.281	AU
   Mass:			0.435	Earth masses
   Equatorial radius:		4876.9	km
   Density:			5.353	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.74	Earth gees
   Surface pressure:		0.191	Earth atmospheres
   Surface temperature:		9.50	degrees Celcius
   Normal daytime temperature:	19.91	degrees Celcius
   Normal night temperature:	-1.42	degrees Celcius
   Maximum temperature:   	45.11	degrees Celcius
   Minimum temperature:   	-27.86	degrees Celcius
   Escape Velocity:		8.44	km/sec
   Molecular weight retained:	11.15 and above
   Surface acceleration:	729.59	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.215
   Length of year:		503.99	days
   Length of day:		18.07	hours
   Boiling point of water:	59.4	degrees Celcius
   Hydrosphere percentage:	53.31
   Cloud cover percentage:	25.29
   Ice cover percentage:	3.36
   liquids at surface:
				Ethanol      melts at -114  boils at 40
				Mercury      melts at -39   boils at 288
				Bromine      melts at -7    boils at 23
				Water        melts at 0     boils at 59
   gasses in atmosphere:
				Oxygen           58.6%  PP  111.9 mb
				Nitrogen         41.2%  PP   78.7 mb
				CarbonDioxide     0.1%  PP    0.1 mb
				Ozone             0.1%  PP    0.1 mb


Planet 6	
   Distance from primary:	1.559	AU
   Mass:			1.950	Earth masses
   Equatorial radius:		7948.9	km
   Density:			5.540	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		1.25	Earth gees
   Surface pressure:		3.134	Earth atmospheres
   Surface temperature:		8.01	degrees Celcius
   Normal daytime temperature:	10.20	degrees Celcius
   Normal night temperature:	5.68	degrees Celcius
   Maximum temperature:   	23.71	degrees Celcius
   Minimum temperature:   	-8.55	degrees Celcius
   Escape Velocity:		13.99	km/sec
   Molecular weight retained:	4.06 and above
   Surface acceleration:	1230.71	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.238
   Length of year:		676.88	days
   Length of day:		13.68	hours
   Boiling point of water:	134.4	degrees Celcius
   Hydrosphere percentage:	73.51
   Cloud cover percentage:	33.08
   Ice cover percentage:	3.65
   liquids at surface:
				Ethanol      melts at -114  boils at 111
				Mercury      melts at -39   boils at 415
				Bromine      melts at -7    boils at 90
				Water        melts at 0     boils at 134
   gasses in atmosphere:
				Oxygen            2.0%  PP   62.8 mb
				Nitrogen         97.8%  PP 3066.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.164	AU
   Mass:			593.009	Earth masses
   Equatorial radius:		73616.6	km
   Density:			2.121	grams/cc
   Eccentricity of orbit:	0.129
   Escape Velocity:		80.15	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4363.64	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.500
   Length of year:		1955.89	days
   Length of day:		6.19	hours


Planet 8	*gas giant*
   Distance from primary:	7.383	AU
   Mass:			158.264	Earth masses
   Equatorial radius:		53742.7	km
   Density:			1.455	grams/cc
   Eccentricity of orbit:	0.159
   Escape Velocity:		48.46	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	2185.16	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.471
   Length of year:		6975.87	days
   Length of day:		8.74	hours


Planet 9	*gas giant*
   Distance from primary:	13.678	AU
   Mass:			472.105	Earth masses
   Equatorial radius:		77817.2	km
   Density:			1.430	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		69.56	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3109.04	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.519
   Length of year:		17582.66	days
   Length of day:		7.33	hours


Planet 10	*gas giant*
   Distance from primary:	26.926	AU
   Mass:			2.867	Earth masses
   Equatorial radius:		18582.0	km
   Density:			0.638	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		11.09	km/sec
   Molecular weight retained:	6.45 and above
   Surface acceleration:	331.16	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.454
   Length of year:		48595.59	days
   Length of day:		22.46	hours


Planet 11	*gas giant*
   Distance from primary:	44.595	AU
   Mass:			0.474	Earth masses
   Equatorial radius:		11461.5	km
   Density:			0.449	grams/cc
   Eccentricity of orbit:	0.031
   Escape Velocity:		5.74	km/sec
   Molecular weight retained:	24.09 and above
   Surface acceleration:	143.76	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.527
   Length of year:		103577.15	days
   Length of day:		34.09	hours


