                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b14
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.50
Stellar temperature: 6323 K
Stellar class: F7
Age: 3.801 billion years  (3.431 billion left on main sequence)
Habitable ecosphere radius: 1.226 AU

Planets present at:
1	  0.326 AU	no atmosphere
2	  0.454 AU	no atmosphere
3	  0.623 AU	greenhouse
4	  0.929 AU	greenhouse
5	  1.444 AU	gas giant
6	  1.703 AU	cold
7	  2.238 AU	cold
8	  3.240 AU	gas giant
9	  4.425 AU	cold
10	  6.089 AU	gas giant
11	 12.468 AU	gas giant
12	 25.639 AU	gas giant
13	 47.366 AU	no atmosphere



Planet 1	
   Distance from primary:	0.326	AU
   Mass:			0.130	Earth masses
   Equatorial radius:		3274.5	km
   Density:			5.294	grams/cc
   Eccentricity of orbit:	0.034
   Surface gravity:		0.49	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		257.93	degrees Celcius
   Normal daytime temperature:	476.50	degrees Celcius
   Normal night temperature:	-177.17	degrees Celcius
   Maximum temperature:   	479.63	degrees Celcius
   Minimum temperature:   	-188.14	degrees Celcius
   Escape Velocity:		5.63	km/sec
   Molecular weight retained:	25.02 and above
   Surface acceleration:	484.44	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.072
   Length of year:		65.09	days
   Length of day:		1562.24	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.454	AU
   Mass:			0.012	Earth masses
   Equatorial radius:		1461.7	km
   Density:			5.255	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.22	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		177.54	degrees Celcius
   Maximum temperature:   	382.03	degrees Celcius
   Minimum temperature:   	-209.93	degrees Celcius
   Escape Velocity:		2.51	km/sec
   Molecular weight retained:	126.48 and above
   Surface acceleration:	214.69	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.067
   Length of year:		106.96	days
   Length of day:		2567.08	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.623	AU
   Mass:			0.717	Earth masses
   Equatorial radius:		5744.0	km
   Density:			5.395	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.88	Earth gees
   Surface pressure:		40.592	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		326.29	degrees Celcius
   Maximum temperature:   	344.08	degrees Celcius
   Minimum temperature:   	259.31	degrees Celcius
   Escape Velocity:		9.98	km/sec
   Molecular weight retained:	7.98 and above
   Surface acceleration:	866.13	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.437
   Length of year:		172.01	days
   Length of day:		4128.27	hours
   Boiling point of water:	240.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 594
				Francium     melts at 27    boils at 1035
				Cesium       melts at 28    boils at 1073
				Gallium      melts at 30    boils at 3410
				Rubidium     melts at 39    boils at 1050
				Potassium    melts at 63    boils at 1157
				Sodium       melts at 98    boils at 1316
				Sulfur       melts at 113   boils at 715
				Indium       melts at 157   boils at 2966
				Lithium      melts at 181   boils at 1957
				Selenium     melts at 217   boils at 1046
				Tin          melts at 232   boils at 3713
				Polonium     melts at 254   boils at 1427
				Bismuth      melts at 271   boils at 2255
				Astatine     melts at 302   boils at 567
				Thallium     melts at 304   boils at 2108
				Cadmium      melts at 321   boils at 1156
   gasses in atmosphere:
				Nitrogen         98.9%  PP 40131.9 mb
				Phosphorus        0.7%  PP  301.9 mb
				CarbonDioxide     0.1%  PP   35.2 mb
				Ozone             0.1%  PP   33.9 mb
				Ethanol           0.1%  PP   35.9 mb


Planet 4	
   Distance from primary:	0.929	AU
   Mass:			0.393	Earth masses
   Equatorial radius:		4717.2	km
   Density:			5.346	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		0.72	Earth gees
   Surface pressure:		12.878	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		101.99	degrees Celcius
   Maximum temperature:   	111.87	degrees Celcius
   Minimum temperature:   	91.52	degrees Celcius
   Escape Velocity:		8.15	km/sec
   Molecular weight retained:	11.94 and above
   Surface acceleration:	704.77	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.471
   Length of year:		313.45	days
   Length of day:		21.80	hours
   Boiling point of water:	186.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 503
				Francium     melts at 27    boils at 898
				Cesium       melts at 28    boils at 932
				Gallium      melts at 30    boils at 3025
				Rubidium     melts at 39    boils at 911
				Phosphorus   melts at 44    boils at 409
				Potassium    melts at 63    boils at 1007
				Sodium       melts at 98    boils at 1150
   gasses in atmosphere:
				Nitrogen         99.1%  PP 12766.3 mb
				Water             0.1%  PP   10.1 mb
				CarbonDioxide     0.2%  PP   27.5 mb
				Methane           0.1%  PP    7.3 mb
				Ammonia           0.1%  PP    8.5 mb
				Ozone             0.2%  PP   28.1 mb
				Ethanol           0.2%  PP   28.2 mb


Planet 5	*gas giant*
   Distance from primary:	1.444	AU
   Mass:			5.430	Earth masses
   Equatorial radius:		17592.2	km
   Density:			1.423	grams/cc
   Eccentricity of orbit:	0.052
   Escape Velocity:		15.69	km/sec
   Molecular weight retained:	3.22 and above
   Surface acceleration:	699.74	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.537
   Length of year:		607.94	days
   Length of day:		15.46	hours


Planet 6	
   Distance from primary:	1.703	AU
   Mass:			0.780	Earth masses
   Equatorial radius:		5905.2	km
   Density:			5.404	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.572	Earth atmospheres
   Surface temperature:		-71.47	degrees Celcius
   Normal daytime temperature:	-67.33	degrees Celcius
   Normal night temperature:	-75.85	degrees Celcius
   Maximum temperature:   	-46.88	degrees Celcius
   Minimum temperature:   	-97.76	degrees Celcius
   Escape Velocity:		10.26	km/sec
   Molecular weight retained:	7.54 and above
   Surface acceleration:	891.90	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.675
   Length of year:		778.30	days
   Length of day:		16.09	hours
   Boiling point of water:	85.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.11
   Ice cover percentage:	91.20
   liquids at surface:
				Ethanol      melts at -114  boils at 65
				Chlorine     melts at -101  boils at -43
				Ammonia      melts at -78   boils at -43
   gasses in atmosphere:
				Oxygen            2.6%  PP   15.0 mb
				Nitrogen         97.2%  PP  556.1 mb
				CarbonDioxide     0.1%  PP    0.4 mb
				Ozone             0.1%  PP    0.4 mb


Planet 7	
   Distance from primary:	2.238	AU
   Mass:			0.362	Earth masses
   Equatorial radius:		4588.8	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.041
   Surface gravity:		0.70	Earth gees
   Surface pressure:		0.140	Earth atmospheres
   Surface temperature:		-100.19	degrees Celcius
   Normal daytime temperature:	-92.89	degrees Celcius
   Normal night temperature:	-107.79	degrees Celcius
   Maximum temperature:   	-71.54	degrees Celcius
   Minimum temperature:   	-130.62	degrees Celcius
   Escape Velocity:		7.93	km/sec
   Molecular weight retained:	12.63 and above
   Surface acceleration:	684.88	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.633
   Length of year:		1172.85	days
   Length of day:		18.33	hours
   Boiling point of water:	52.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	79.64
   liquids at surface:
				Ethanol      melts at -114  boils at 34
				Chlorine     melts at -101  boils at -64
   gasses in atmosphere:
				Oxygen           26.5%  PP   37.1 mb
				Nitrogen         73.2%  PP  102.4 mb
				Methane           0.1%  PP    0.1 mb
				Ozone             0.2%  PP    0.3 mb


Planet 8	*gas giant*
   Distance from primary:	3.240	AU
   Mass:			7.447	Earth masses
   Equatorial radius:		20633.1	km
   Density:			1.210	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		16.97	km/sec
   Molecular weight retained:	2.76 and above
   Surface acceleration:	697.61	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.489
   Length of year:		2042.39	days
   Length of day:		15.47	hours


Planet 9	
   Distance from primary:	4.425	AU
   Mass:			0.822	Earth masses
   Equatorial radius:		6006.6	km
   Density:			5.410	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.93	Earth gees
   Surface pressure:		0.559	Earth atmospheres
   Surface temperature:		-136.91	degrees Celcius
   Normal daytime temperature:	-134.11	degrees Celcius
   Normal night temperature:	-139.86	degrees Celcius
   Maximum temperature:   	-117.93	degrees Celcius
   Minimum temperature:   	-157.54	degrees Celcius
   Escape Velocity:		10.45	km/sec
   Molecular weight retained:	7.28 and above
   Surface acceleration:	908.16	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.542
   Length of year:		3259.64	days
   Length of day:		15.90	hours
   Boiling point of water:	84.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	81.73
   liquids at surface:
				Ozone        melts at -193  boils at -119
   gasses in atmosphere:
				Oxygen            2.7%  PP   15.2 mb
				Nitrogen         97.2%  PP  543.4 mb


Planet 10	*gas giant*
   Distance from primary:	6.089	AU
   Mass:			821.881	Earth masses
   Equatorial radius:		85747.1	km
   Density:			1.860	grams/cc
   Eccentricity of orbit:	0.011
   Escape Velocity:		87.43	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4457.69	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.523
   Length of year:		5256.60	days
   Length of day:		6.12	hours


Planet 11	*gas giant*
   Distance from primary:	12.468	AU
   Mass:			420.007	Earth masses
   Equatorial radius:		74837.5	km
   Density:			1.430	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		66.90	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	2990.59	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.452
   Length of year:		15410.04	days
   Length of day:		7.47	hours


Planet 12	*gas giant*
   Distance from primary:	25.639	AU
   Mass:			30.646	Earth masses
   Equatorial radius:		37035.8	km
   Density:			0.861	grams/cc
   Eccentricity of orbit:	0.008
   Escape Velocity:		25.69	km/sec
   Molecular weight retained:	1.20 and above
   Surface acceleration:	890.99	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.518
   Length of year:		45465.22	days
   Length of day:		13.69	hours


Planet 13	
   Distance from primary:	47.366	AU
   Mass:			0.226	Earth masses
   Equatorial radius:		5252.6	km
   Density:			2.229	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.70	degrees Celcius
   Normal daytime temperature:	-224.64	degrees Celcius
   Normal night temperature:	-234.67	degrees Celcius
   Maximum temperature:   	-210.78	degrees Celcius
   Minimum temperature:   	-248.91	degrees Celcius
   Escape Velocity:		5.86	km/sec
   Molecular weight retained:	23.10 and above
   Surface acceleration:	327.18	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.155
   Length of year:		114168.53	days
   Length of day:		26.50	hours
   Boiling point of water:	-49.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


