                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048842
Stellar mass: 1.11 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.63
Stellar temperature: 6178 K
Stellar class: F8
Age: 4.312 billion years  (2.471 billion left on main sequence)
Habitable ecosphere radius: 1.277 AU

Planets present at:
1	  0.336 AU	no atmosphere
2	  0.561 AU	no atmosphere
3	  0.928 AU	greenhouse
4	  1.396 AU	high pressure
5	  2.421 AU	high pressure
6	  3.316 AU	gas giant
7	  6.284 AU	gas giant
8	 13.106 AU	gas giant
9	 25.442 AU	gas giant
10	 35.864 AU	no atmosphere
11	 47.153 AU	gas giant



Planet 1	
   Distance from primary:	0.336	AU
   Mass:			0.162	Earth masses
   Equatorial radius:		3522.7	km
   Density:			5.301	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.53	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		260.88	degrees Celcius
   Normal daytime temperature:	480.23	degrees Celcius
   Normal night temperature:	-177.93	degrees Celcius
   Maximum temperature:   	483.32	degrees Celcius
   Minimum temperature:   	-188.81	degrees Celcius
   Escape Velocity:		6.06	km/sec
   Molecular weight retained:	21.59 and above
   Surface acceleration:	521.90	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.068
   Length of year:		67.67	days
   Length of day:		1624.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.561	AU
   Mass:			0.095	Earth masses
   Equatorial radius:		2953.0	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.44	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		141.53	degrees Celcius
   Maximum temperature:   	337.74	degrees Celcius
   Minimum temperature:   	-218.42	degrees Celcius
   Escape Velocity:		5.08	km/sec
   Molecular weight retained:	30.82 and above
   Surface acceleration:	436.14	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.057
   Length of year:		145.84	days
   Length of day:		3500.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.928	AU
   Mass:			1.237	Earth masses
   Equatorial radius:		6862.9	km
   Density:			5.462	grams/cc
   Eccentricity of orbit:	0.243
   Surface gravity:		1.07	Earth gees
   Surface pressure:		156.172	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		432.13	degrees Celcius
   Maximum temperature:   	435.85	degrees Celcius
   Minimum temperature:   	426.57	degrees Celcius
   Escape Velocity:		11.99	km/sec
   Molecular weight retained:	5.52 and above
   Surface acceleration:	1047.62	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.584
   Length of year:		310.22	days
   Length of day:		16.07	hours
   Boiling point of water:	321.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1242
				Cesium       melts at 28    boils at 1287
				Gallium      melts at 30    boils at 3995
				Rubidium     melts at 39    boils at 1260
				Potassium    melts at 63    boils at 1384
				Sodium       melts at 98    boils at 1568
				Sulfur       melts at 113   boils at 872
				Indium       melts at 157   boils at 3480
				Lithium      melts at 181   boils at 2311
				Selenium     melts at 217   boils at 1255
				Tin          melts at 232   boils at 4346
				Polonium     melts at 254   boils at 1697
				Bismuth      melts at 271   boils at 2657
				Thallium     melts at 304   boils at 2486
				Cadmium      melts at 321   boils at 1382
				Lead         melts at 328   boils at 2955
				Zinc         melts at 420   boils at 1609
   gasses in atmosphere:
				Nitrogen         99.2%  PP 154908.6 mb
				Phosphorus        0.5%  PP  844.6 mb
				CarbonDioxide     0.1%  PP   92.3 mb
				Ethanol           0.1%  PP   93.5 mb


Planet 4	
   Distance from primary:	1.396	AU
   Mass:			2.454	Earth masses
   Equatorial radius:		8556.2	km
   Density:			5.590	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		1.36	Earth gees
   Surface pressure:		6.084	Earth atmospheres
   Surface temperature:		19.80	degrees Celcius
   Normal daytime temperature:	21.38	degrees Celcius
   Normal night temperature:	18.11	degrees Celcius
   Maximum temperature:   	31.42	degrees Celcius
   Minimum temperature:   	7.59	degrees Celcius
   Escape Velocity:		15.12	km/sec
   Molecular weight retained:	3.47 and above
   Surface acceleration:	1336.63	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.493
   Length of year:		572.77	days
   Length of day:		13.16	hours
   Boiling point of water:	157.4	degrees Celcius
   Hydrosphere percentage:	97.88
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.80
   liquids at surface:
				Ethanol      melts at -114  boils at 133
				Mercury      melts at -39   boils at 454
				Bromine      melts at -7    boils at 111
				Water        melts at 0     boils at 157
   gasses in atmosphere:
				Nitrogen          0.8%  PP   51.5 mb
				Helium           99.2%  PP 6032.1 mb


Planet 5	
   Distance from primary:	2.421	AU
   Mass:			1.623	Earth masses
   Equatorial radius:		7493.0	km
   Density:			5.506	grams/cc
   Eccentricity of orbit:	0.205
   Surface gravity:		1.18	Earth gees
   Surface pressure:		2.421	Earth atmospheres
   Surface temperature:		-98.85	degrees Celcius
   Normal daytime temperature:	-97.27	degrees Celcius
   Normal night temperature:	-100.54	degrees Celcius
   Maximum temperature:   	-82.50	degrees Celcius
   Minimum temperature:   	-116.41	degrees Celcius
   Escape Velocity:		13.14	km/sec
   Molecular weight retained:	4.59 and above
   Surface acceleration:	1152.93	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.721
   Length of year:		1307.90	days
   Length of day:		14.12	hours
   Boiling point of water:	126.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.02
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 103
				Chlorine     melts at -101  boils at -17
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2418.9 mb


Planet 6	*gas giant*
   Distance from primary:	3.316	AU
   Mass:			52.392	Earth masses
   Equatorial radius:		36396.8	km
   Density:			1.550	grams/cc
   Eccentricity of orbit:	0.003
   Escape Velocity:		33.88	km/sec
   Molecular weight retained:	0.69 and above
   Surface acceleration:	1577.17	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.518
   Length of year:		2097.28	days
   Length of day:		10.29	hours


Planet 7	*gas giant*
   Distance from primary:	6.284	AU
   Mass:			582.280	Earth masses
   Equatorial radius:		77489.2	km
   Density:			1.786	grams/cc
   Eccentricity of orbit:	0.056
   Escape Velocity:		77.42	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3867.13	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.476
   Length of year:		5466.98	days
   Length of day:		6.57	hours


Planet 8	*gas giant*
   Distance from primary:	13.106	AU
   Mass:			417.726	Earth masses
   Equatorial radius:		74777.5	km
   Density:			1.426	grams/cc
   Eccentricity of orbit:	0.005
   Escape Velocity:		66.75	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	2979.13	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.538
   Length of year:		16467.78	days
   Length of day:		7.49	hours


Planet 9	*gas giant*
   Distance from primary:	25.442	AU
   Mass:			4.483	Earth masses
   Equatorial radius:		21056.2	km
   Density:			0.685	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		13.03	km/sec
   Molecular weight retained:	4.68 and above
   Surface acceleration:	403.19	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.473
   Length of year:		44566.53	days
   Length of day:		20.35	hours


Planet 10	
   Distance from primary:	35.864	AU
   Mass:			0.221	Earth masses
   Equatorial radius:		5207.9	km
   Density:			2.228	grams/cc
   Eccentricity of orbit:	0.026
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-221.97	degrees Celcius
   Normal daytime temperature:	-215.98	degrees Celcius
   Normal night temperature:	-227.89	degrees Celcius
   Maximum temperature:   	-201.73	degrees Celcius
   Minimum temperature:   	-242.83	degrees Celcius
   Escape Velocity:		5.81	km/sec
   Molecular weight retained:	23.50 and above
   Surface acceleration:	324.28	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.138
   Length of year:		74590.69	days
   Length of day:		26.61	hours
   Boiling point of water:	-49.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


Planet 11	*gas giant*
   Distance from primary:	47.153	AU
   Mass:			0.363	Earth masses
   Equatorial radius:		10647.6	km
   Density:			0.429	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		5.21	km/sec
   Molecular weight retained:	29.21 and above
   Surface acceleration:	127.62	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.526
   Length of year:		112449.01	days
   Length of day:		36.18	hours


