                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e0b
Stellar mass: 1.09 solar masses
Stellar radius: 1.07 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6085 K
Stellar class: F9
Age: 1.297 billion years  (5.831 billion left on main sequence)
Habitable ecosphere radius: 1.238 AU

Planets present at:
1	  0.409 AU	no atmosphere
2	  0.572 AU	no atmosphere
3	  0.651 AU	no atmosphere
4	  1.075 AU	greenhouse
5	  1.461 AU	high pressure
6	  1.852 AU	no atmosphere
7	  3.075 AU	gas giant
8	  6.300 AU	gas giant
9	  8.957 AU	no atmosphere
10	 14.360 AU	gas giant
11	 25.050 AU	gas giant
12	 51.468 AU	gas giant



Planet 1	
   Distance from primary:	0.409	AU
   Mass:			0.247	Earth masses
   Equatorial radius:		4045.8	km
   Density:			5.319	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		205.60	degrees Celcius
   Maximum temperature:   	416.42	degrees Celcius
   Minimum temperature:   	-203.71	degrees Celcius
   Escape Velocity:		6.98	km/sec
   Molecular weight retained:	16.31 and above
   Surface acceleration:	601.43	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.052
   Length of year:		91.36	days
   Length of day:		2192.72	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.572	AU
   Mass:			0.357	Earth masses
   Equatorial radius:		4568.3	km
   Density:			5.340	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		131.46	degrees Celcius
   Maximum temperature:   	325.36	degrees Celcius
   Minimum temperature:   	-220.51	degrees Celcius
   Escape Velocity:		7.89	km/sec
   Molecular weight retained:	12.75 and above
   Surface acceleration:	681.71	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.054
   Length of year:		151.21	days
   Length of day:		3629.06	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.651	AU
   Mass:			1/135.8	Earth masses
   Equatorial radius:		1260.0	km
   Density:			5.253	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.19	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		102.66	degrees Celcius
   Maximum temperature:   	289.32	degrees Celcius
   Minimum temperature:   	-224.82	degrees Celcius
   Escape Velocity:		2.16	km/sec
   Molecular weight retained:	170.31 and above
   Surface acceleration:	184.97	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.087
   Length of year:		183.68	days
   Length of day:		4408.26	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	
   Distance from primary:	1.075	AU
   Mass:			2.079	Earth masses
   Equatorial radius:		8114.7	km
   Density:			5.553	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		1.28	Earth gees
   Surface pressure:		464.594	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		489.42	degrees Celcius
   Maximum temperature:   	491.37	degrees Celcius
   Minimum temperature:   	485.23	degrees Celcius
   Escape Velocity:		14.30	km/sec
   Molecular weight retained:	3.88 and above
   Surface acceleration:	1259.36	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.604
   Length of year:		389.40	days
   Length of day:		13.59	hours
   Boiling point of water:	409.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1465
				Cesium       melts at 28    boils at 1517
				Gallium      melts at 30    boils at 4624
				Rubidium     melts at 39    boils at 1485
				Potassium    melts at 63    boils at 1628
				Sodium       melts at 98    boils at 1840
				Indium       melts at 157   boils at 4033
				Lithium      melts at 181   boils at 2691
				Selenium     melts at 217   boils at 1480
				Tin          melts at 232   boils at 5027
				Polonium     melts at 254   boils at 1987
				Bismuth      melts at 271   boils at 3089
				Thallium     melts at 304   boils at 2893
				Cadmium      melts at 321   boils at 1626
				Lead         melts at 328   boils at 3431
				Zinc         melts at 420   boils at 1886
				Tellurium    melts at 450   boils at 2038
   gasses in atmosphere:
				Sulfur            0.6%  PP 2917.9 mb
				Nitrogen          3.0%  PP 13964.4 mb
				Helium           96.3%  PP 447623.1 mb


Planet 5	
   Distance from primary:	1.461	AU
   Mass:			1.664	Earth masses
   Equatorial radius:		7552.9	km
   Density:			5.510	grams/cc
   Eccentricity of orbit:	0.060
   Surface gravity:		1.19	Earth gees
   Surface pressure:		2.172	Earth atmospheres
   Surface temperature:		9.34	degrees Celcius
   Normal daytime temperature:	12.04	degrees Celcius
   Normal night temperature:	6.47	degrees Celcius
   Maximum temperature:   	28.75	degrees Celcius
   Minimum temperature:   	-11.16	degrees Celcius
   Escape Velocity:		13.25	km/sec
   Molecular weight retained:	4.52 and above
   Surface acceleration:	1163.07	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.241
   Length of year:		617.48	days
   Length of day:		14.07	hours
   Boiling point of water:	122.7	degrees Celcius
   Hydrosphere percentage:	66.13
   Cloud cover percentage:	31.56
   Ice cover percentage:	3.33
   liquids at surface:
				Ethanol      melts at -114  boils at 100
				Mercury      melts at -39   boils at 395
				Bromine      melts at -7    boils at 80
				Water        melts at 0     boils at 123
   gasses in atmosphere:
				Oxygen            8.5%  PP  184.9 mb
				Nitrogen         91.3%  PP 1983.6 mb


Planet 6	
   Distance from primary:	1.852	AU
   Mass:			0.206	Earth masses
   Equatorial radius:		3812.6	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.036
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.046	Earth atmospheres
   Surface temperature:		-74.36	degrees Celcius
   Normal daytime temperature:	-61.35	degrees Celcius
   Normal night temperature:	-87.70	degrees Celcius
   Maximum temperature:   	-37.55	degrees Celcius
   Minimum temperature:   	-112.64	degrees Celcius
   Escape Velocity:		6.57	km/sec
   Molecular weight retained:	18.40 and above
   Surface acceleration:	565.87	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.538
   Length of year:		880.70	days
   Length of day:		20.18	hours
   Boiling point of water:	30.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	65.84
   liquids at surface:
				Ethanol      melts at -114  boils at 14
   gasses in atmosphere:
				CarbonDioxide    46.6%  PP   21.2 mb
				Ozone            49.6%  PP   22.6 mb
				Fluorine          0.3%  PP    0.2 mb
				Neon              0.2%  PP    0.1 mb
				Krypton           2.9%  PP    1.3 mb
				Xenon             0.3%  PP    0.2 mb


Planet 7	*gas giant*
   Distance from primary:	3.075	AU
   Mass:			74.019	Earth masses
   Equatorial radius:		40108.5	km
   Density:			1.637	grams/cc
   Eccentricity of orbit:	0.049
   Escape Velocity:		38.37	km/sec
   Molecular weight retained:	0.54 and above
   Surface acceleration:	1834.88	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.476
   Length of year:		1885.03	days
   Length of day:		9.54	hours


Planet 8	*gas giant*
   Distance from primary:	6.300	AU
   Mass:			1019.950	Earth masses
   Equatorial radius:		91510.1	km
   Density:			1.899	grams/cc
   Eccentricity of orbit:	0.040
   Escape Velocity:		94.28	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4857.13	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.509
   Length of year:		5520.03	days
   Length of day:		5.86	hours


Planet 9	
   Distance from primary:	8.957	AU
   Mass:			0.083	Earth masses
   Equatorial radius:		3765.9	km
   Density:			2.208	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.24	Earth gees
   Surface pressure:		0.006	Earth atmospheres
   Surface temperature:		-176.56	degrees Celcius
   Normal daytime temperature:	-164.17	degrees Celcius
   Normal night temperature:	-189.02	degrees Celcius
   Maximum temperature:   	-147.89	degrees Celcius
   Minimum temperature:   	-206.15	degrees Celcius
   Escape Velocity:		4.18	km/sec
   Molecular weight retained:	45.36 and above
   Surface acceleration:	232.35	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.253
   Length of year:		9369.74	days
   Length of day:		31.44	hours
   Boiling point of water:	-3.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	20.56
   liquids at surface:
				Ozone        melts at -193  boils at -156


Planet 10	*gas giant*
   Distance from primary:	14.360	AU
   Mass:			29.918	Earth masses
   Equatorial radius:		35015.9	km
   Density:			0.994	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		26.10	km/sec
   Molecular weight retained:	1.16 and above
   Surface acceleration:	973.07	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.540
   Length of year:		19021.14	days
   Length of day:		13.10	hours


Planet 11	*gas giant*
   Distance from primary:	25.050	AU
   Mass:			39.419	Earth masses
   Equatorial radius:		39749.8	km
   Density:			0.896	grams/cc
   Eccentricity of orbit:	0.194
   Escape Velocity:		28.12	km/sec
   Molecular weight retained:	1.00 and above
   Surface acceleration:	994.89	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.481
   Length of year:		43822.45	days
   Length of day:		12.96	hours


Planet 12	*gas giant*
   Distance from primary:	51.468	AU
   Mass:			0.398	Earth masses
   Equatorial radius:		11047.8	km
   Density:			0.421	grams/cc
   Eccentricity of orbit:	0.187
   Escape Velocity:		5.36	km/sec
   Molecular weight retained:	27.63 and above
   Surface acceleration:	130.03	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.534
   Length of year:		129069.48	days
   Length of day:		35.84	hours


