                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047e73
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6185 K
Stellar class: F8
Age: 4.344 billion years  (2.770 billion left on main sequence)
Habitable ecosphere radius: 1.239 AU

Planets present at:
1	  0.350 AU	no atmosphere
2	  0.742 AU	greenhouse
3	  1.005 AU	greenhouse
4	  1.464 AU	high pressure
5	  2.548 AU	gas giant
6	  6.223 AU	gas giant
7	 13.835 AU	gas giant
8	 28.707 AU	no atmosphere
9	 30.130 AU	gas giant
10	 46.757 AU	no atmosphere



Planet 1	
   Distance from primary:	0.350	AU
   Mass:			0.200	Earth masses
   Equatorial radius:		3771.4	km
   Density:			5.309	grams/cc
   Eccentricity of orbit:	0.084
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		244.17	degrees Celcius
   Normal daytime temperature:	460.06	degrees Celcius
   Normal night temperature:	-182.55	degrees Celcius
   Maximum temperature:   	463.20	degrees Celcius
   Minimum temperature:   	-193.30	degrees Celcius
   Escape Velocity:		6.50	km/sec
   Molecular weight retained:	18.81 and above
   Surface acceleration:	559.61	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.058
   Length of year:		72.22	days
   Length of day:		1733.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.742	AU
   Mass:			0.412	Earth masses
   Equatorial radius:		4789.4	km
   Density:			5.349	grams/cc
   Eccentricity of orbit:	0.092
   Surface gravity:		0.73	Earth gees
   Surface pressure:		14.692	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		134.32	degrees Celcius
   Maximum temperature:   	147.45	degrees Celcius
   Minimum temperature:   	119.22	degrees Celcius
   Escape Velocity:		8.28	km/sec
   Molecular weight retained:	11.57 and above
   Surface acceleration:	715.98	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.555
   Length of year:		223.57	days
   Length of day:		66.51	hours
   Boiling point of water:	192.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 513
				Francium     melts at 27    boils at 912
				Cesium       melts at 28    boils at 947
				Gallium      melts at 30    boils at 3065
				Rubidium     melts at 39    boils at 926
				Phosphorus   melts at 44    boils at 418
				Potassium    melts at 63    boils at 1023
				Sodium       melts at 98    boils at 1167
				Sulfur       melts at 113   boils at 623
				Iodine       melts at 114   boils at 299
   gasses in atmosphere:
				Nitrogen         99.2%  PP 14569.5 mb
				Water             0.1%  PP   10.7 mb
				CarbonDioxide     0.2%  PP   30.2 mb
				Methane           0.1%  PP    7.9 mb
				Ammonia           0.1%  PP    9.0 mb
				Ozone             0.2%  PP   30.8 mb
				Ethanol           0.2%  PP   31.1 mb


Planet 3	
   Distance from primary:	1.005	AU
   Mass:			0.421	Earth masses
   Equatorial radius:		4822.7	km
   Density:			5.350	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		0.74	Earth gees
   Surface pressure:		14.402	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		100.06	degrees Celcius
   Maximum temperature:   	109.46	degrees Celcius
   Minimum temperature:   	90.11	degrees Celcius
   Escape Velocity:		8.34	km/sec
   Molecular weight retained:	11.41 and above
   Surface acceleration:	721.15	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.424
   Length of year:		352.10	days
   Length of day:		20.20	hours
   Boiling point of water:	191.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 511
				Francium     melts at 27    boils at 910
				Cesium       melts at 28    boils at 945
				Gallium      melts at 30    boils at 3059
				Rubidium     melts at 39    boils at 924
				Phosphorus   melts at 44    boils at 416
				Potassium    melts at 63    boils at 1020
				Sodium       melts at 98    boils at 1165
   gasses in atmosphere:
				Nitrogen         99.3%  PP 14297.6 mb
				Water             0.1%  PP    9.8 mb
				CarbonDioxide     0.2%  PP   25.3 mb
				Methane           0.1%  PP    7.4 mb
				Ammonia           0.1%  PP    8.4 mb
				Ozone             0.2%  PP   25.7 mb
				Ethanol           0.2%  PP   26.0 mb


Planet 4	
   Distance from primary:	1.464	AU
   Mass:			2.038	Earth masses
   Equatorial radius:		8062.4	km
   Density:			5.549	grams/cc
   Eccentricity of orbit:	0.144
   Surface gravity:		1.27	Earth gees
   Surface pressure:		4.368	Earth atmospheres
   Surface temperature:		12.12	degrees Celcius
   Normal daytime temperature:	13.99	degrees Celcius
   Normal night temperature:	10.13	degrees Celcius
   Maximum temperature:   	27.49	degrees Celcius
   Minimum temperature:   	-4.05	degrees Celcius
   Escape Velocity:		14.20	km/sec
   Molecular weight retained:	3.94 and above
   Surface acceleration:	1250.30	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.295
   Length of year:		618.80	days
   Length of day:		13.60	hours
   Boiling point of water:	145.6	degrees Celcius
   Hydrosphere percentage:	95.30
   Cloud cover percentage:	57.61
   Ice cover percentage:	2.26
   liquids at surface:
				Ethanol      melts at -114  boils at 121
				Mercury      melts at -39   boils at 434
				Bromine      melts at -7    boils at 100
				Water        melts at 0     boils at 146
   gasses in atmosphere:
				Nitrogen          6.3%  PP  273.4 mb
				Helium           93.7%  PP 4093.8 mb


Planet 5	*gas giant*
   Distance from primary:	2.548	AU
   Mass:			7.038	Earth masses
   Equatorial radius:		19876.0	km
   Density:			1.279	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		16.81	km/sec
   Molecular weight retained:	2.81 and above
   Surface acceleration:	710.44	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.496
   Length of year:		1421.33	days
   Length of day:		15.33	hours


Planet 6	*gas giant*
   Distance from primary:	6.223	AU
   Mass:			2321.126	Earth masses
   Equatorial radius:		116182.3	km
   Density:			2.112	grams/cc
   Eccentricity of orbit:	0.238
   Escape Velocity:		126.23	km/sec
   Molecular weight retained:	0.05 and above
   Surface acceleration:	6857.38	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.531
   Length of year:		5408.42	days
   Length of day:		4.94	hours


Planet 7	*gas giant*
   Distance from primary:	13.835	AU
   Mass:			131.926	Earth masses
   Equatorial radius:		53804.6	km
   Density:			1.209	grams/cc
   Eccentricity of orbit:	0.105
   Escape Velocity:		44.22	km/sec
   Molecular weight retained:	0.41 and above
   Surface acceleration:	1817.32	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.457
   Length of year:		17979.90	days
   Length of day:		9.59	hours


Planet 8	
   Distance from primary:	28.707	AU
   Mass:			0.212	Earth masses
   Equatorial radius:		5142.6	km
   Density:			2.227	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.33	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.02	degrees Celcius
   Normal daytime temperature:	-210.41	degrees Celcius
   Normal night temperature:	-223.57	degrees Celcius
   Maximum temperature:   	-198.97	degrees Celcius
   Minimum temperature:   	-235.83	degrees Celcius
   Escape Velocity:		5.74	km/sec
   Molecular weight retained:	24.11 and above
   Surface acceleration:	320.07	cm/sec2
   Axial tilt:			62	degrees
   Planetary albedo:		0.151
   Length of year:		53751.63	days
   Length of day:		26.79	hours
   Boiling point of water:	-49.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09
   liquids at surface:
				Fluorine     melts at -220  boils at -216
				Oxygen       melts at -218  boils at -213


Planet 9	*gas giant*
   Distance from primary:	30.130	AU
   Mass:			12.327	Earth masses
   Equatorial radius:		28755.8	km
   Density:			0.740	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		18.49	km/sec
   Molecular weight retained:	2.32 and above
   Surface acceleration:	594.49	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.543
   Length of year:		57795.72	days
   Length of day:		16.76	hours


Planet 10	
   Distance from primary:	46.757	AU
   Mass:			0.253	Earth masses
   Equatorial radius:		5447.7	km
   Density:			2.232	grams/cc
   Eccentricity of orbit:	0.082
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.03	degrees Celcius
   Normal daytime temperature:	-223.97	degrees Celcius
   Normal night temperature:	-233.99	degrees Celcius
   Maximum temperature:   	-208.30	degrees Celcius
   Minimum temperature:   	-249.89	degrees Celcius
   Escape Velocity:		6.08	km/sec
   Molecular weight retained:	21.44 and above
   Surface acceleration:	339.84	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.143
   Length of year:		111733.00	days
   Length of day:		26.00	hours
   Boiling point of water:	-47.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


