                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b35
Stellar mass: 1.09 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6214 K
Stellar class: F8
Age: 4.132 billion years  (3.095 billion left on main sequence)
Habitable ecosphere radius: 1.227 AU

Planets present at:
1	  0.331 AU	no atmosphere
2	  0.502 AU	no atmosphere
3	  0.573 AU	no atmosphere
4	  0.626 AU	no atmosphere
5	  0.673 AU	greenhouse
6	  1.003 AU	no atmosphere
7	  1.214 AU	high pressure
8	  1.430 AU	cold
9	  3.453 AU	gas giant
10	  5.657 AU	cold
11	  7.630 AU	cold
12	 10.099 AU	gas giant
13	 22.297 AU	gas giant
14	 37.517 AU	gas giant



Planet 1	
   Distance from primary:	0.331	AU
   Mass:			0.166	Earth masses
   Equatorial radius:		3545.9	km
   Density:			5.302	grams/cc
   Eccentricity of orbit:	0.074
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.93	degrees Celcius
   Normal daytime temperature:	474.14	degrees Celcius
   Normal night temperature:	-178.27	degrees Celcius
   Maximum temperature:   	477.28	degrees Celcius
   Minimum temperature:   	-189.23	degrees Celcius
   Escape Velocity:		6.10	km/sec
   Molecular weight retained:	21.30 and above
   Surface acceleration:	525.42	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.057
   Length of year:		66.67	days
   Length of day:		1600.19	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Distance from primary:	0.502	AU
   Mass:			1/191.8	Earth masses
   Equatorial radius:		1123.1	km
   Density:			5.252	grams/cc
   Eccentricity of orbit:	0.023
   Surface gravity:		0.17	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		153.21	degrees Celcius
   Maximum temperature:   	352.16	degrees Celcius
   Minimum temperature:   	-215.38	degrees Celcius
   Escape Velocity:		1.92	km/sec
   Molecular weight retained:	214.38 and above
   Surface acceleration:	164.84	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.084
   Length of year:		124.70	days
   Length of day:		2992.88	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.573	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1647.4	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.006
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		128.30	degrees Celcius
   Maximum temperature:   	321.20	degrees Celcius
   Minimum temperature:   	-220.28	degrees Celcius
   Escape Velocity:		2.82	km/sec
   Molecular weight retained:	99.52 and above
   Surface acceleration:	242.08	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.064
   Length of year:		151.86	days
   Length of day:		3644.53	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.626	AU
   Mass:			0.028	Earth masses
   Equatorial radius:		1969.4	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		111.43	degrees Celcius
   Maximum temperature:   	300.29	degrees Celcius
   Minimum temperature:   	-223.78	degrees Celcius
   Escape Velocity:		3.38	km/sec
   Molecular weight retained:	69.57 and above
   Surface acceleration:	289.68	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.059
   Length of year:		173.33	days
   Length of day:		4159.88	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.673	AU
   Mass:			0.641	Earth masses
   Equatorial radius:		5537.4	km
   Density:			5.385	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.85	Earth gees
   Surface pressure:		44.185	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		312.01	degrees Celcius
   Maximum temperature:   	322.46	degrees Celcius
   Minimum temperature:   	297.12	degrees Celcius
   Escape Velocity:		9.61	km/sec
   Molecular weight retained:	8.60 and above
   Surface acceleration:	833.31	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.424
   Length of year:		193.38	days
   Length of day:		119.36	hours
   Boiling point of water:	244.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 602
				Francium     melts at 27    boils at 1046
				Cesium       melts at 28    boils at 1085
				Gallium      melts at 30    boils at 3442
				Rubidium     melts at 39    boils at 1061
				Potassium    melts at 63    boils at 1169
				Sodium       melts at 98    boils at 1330
				Sulfur       melts at 113   boils at 724
				Indium       melts at 157   boils at 2994
				Lithium      melts at 181   boils at 1976
				Selenium     melts at 217   boils at 1057
				Tin          melts at 232   boils at 3748
				Polonium     melts at 254   boils at 1442
				Bismuth      melts at 271   boils at 2277
				Astatine     melts at 302   boils at 574
				Thallium     melts at 304   boils at 2129
   gasses in atmosphere:
				Nitrogen         98.8%  PP 43636.4 mb
				Phosphorus        0.8%  PP  361.3 mb
				CarbonDioxide     0.1%  PP   42.7 mb
				Ozone             0.1%  PP   40.6 mb
				Ethanol           0.1%  PP   43.7 mb


Planet 6	
   Distance from primary:	1.003	AU
   Mass:			0.072	Earth masses
   Equatorial radius:		2694.1	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.058
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		30.29	degrees Celcius
   Normal daytime temperature:	86.03	degrees Celcius
   Normal night temperature:	-26.65	degrees Celcius
   Maximum temperature:   	115.31	degrees Celcius
   Minimum temperature:   	-56.60	degrees Celcius
   Escape Velocity:		4.63	km/sec
   Molecular weight retained:	37.07 and above
   Surface acceleration:	397.41	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.063
   Length of year:		351.95	days
   Length of day:		46.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499


Planet 7	
   Distance from primary:	1.214	AU
   Mass:			2.144	Earth masses
   Equatorial radius:		8195.0	km
   Density:			5.560	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		1.30	Earth gees
   Surface pressure:		4.106	Earth atmospheres
   Surface temperature:		18.74	degrees Celcius
   Normal daytime temperature:	20.71	degrees Celcius
   Normal night temperature:	16.64	degrees Celcius
   Maximum temperature:   	32.89	degrees Celcius
   Minimum temperature:   	3.85	degrees Celcius
   Escape Velocity:		14.45	km/sec
   Molecular weight retained:	3.80 and above
   Surface acceleration:	1273.30	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.452
   Length of year:		468.49	days
   Length of day:		13.56	hours
   Boiling point of water:	143.4	degrees Celcius
   Hydrosphere percentage:	82.41
   Cloud cover percentage:	76.02
   Ice cover percentage:	1.04
   liquids at surface:
				Ethanol      melts at -114  boils at 119
				Mercury      melts at -39   boils at 430
				Bromine      melts at -7    boils at 98
				Water        melts at 0     boils at 143
   gasses in atmosphere:
				Nitrogen          2.2%  PP   91.5 mb
				Helium           97.8%  PP 4014.1 mb


Planet 8	
   Distance from primary:	1.430	AU
   Mass:			0.707	Earth masses
   Equatorial radius:		5719.5	km
   Density:			5.394	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.88	Earth gees
   Surface pressure:		0.439	Earth atmospheres
   Surface temperature:		-0.14	degrees Celcius
   Normal daytime temperature:	6.32	degrees Celcius
   Normal night temperature:	-6.95	degrees Celcius
   Maximum temperature:   	29.52	degrees Celcius
   Minimum temperature:   	-31.47	degrees Celcius
   Escape Velocity:		9.93	km/sec
   Molecular weight retained:	8.05 and above
   Surface acceleration:	862.24	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.208
   Length of year:		598.66	days
   Length of day:		16.46	hours
   Boiling point of water:	78.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	12.71
   Ice cover percentage:	9.27
   liquids at surface:
				Ethanol      melts at -114  boils at 58
				Mercury      melts at -39   boils at 321
				Bromine      melts at -7    boils at 41
   gasses in atmosphere:
				Oxygen           39.3%  PP  172.7 mb
				Nitrogen         60.5%  PP  266.0 mb


Planet 9	*gas giant*
   Distance from primary:	3.453	AU
   Mass:			380.020	Earth masses
   Equatorial radius:		65308.3	km
   Density:			1.947	grams/cc
   Eccentricity of orbit:	0.033
   Escape Velocity:		68.12	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	3553.10	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.540
   Length of year:		2246.21	days
   Length of day:		6.86	hours


Planet 10	
   Distance from primary:	5.657	AU
   Mass:			0.802	Earth masses
   Equatorial radius:		7940.3	km
   Density:			2.287	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.456	Earth atmospheres
   Surface temperature:		-142.02	degrees Celcius
   Normal daytime temperature:	-138.18	degrees Celcius
   Normal night temperature:	-146.11	degrees Celcius
   Maximum temperature:   	-120.10	degrees Celcius
   Minimum temperature:   	-165.84	degrees Celcius
   Escape Velocity:		8.98	km/sec
   Molecular weight retained:	9.85 and above
   Surface acceleration:	507.40	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.344
   Length of year:		4712.32	days
   Length of day:		21.28	hours
   Boiling point of water:	79.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	39.11
   liquids at surface:
				Ozone        melts at -193  boils at -121
   gasses in atmosphere:
				Oxygen            3.1%  PP   14.3 mb
				Nitrogen         96.8%  PP  441.8 mb


Planet 11	
   Distance from primary:	7.630	AU
   Mass:			0.523	Earth masses
   Equatorial radius:		6910.5	km
   Density:			2.261	grams/cc
   Eccentricity of orbit:	0.050
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.169	Earth atmospheres
   Surface temperature:		-162.98	degrees Celcius
   Normal daytime temperature:	-157.71	degrees Celcius
   Normal night temperature:	-168.53	degrees Celcius
   Maximum temperature:   	-139.59	degrees Celcius
   Minimum temperature:   	-188.33	degrees Celcius
   Escape Velocity:		7.77	km/sec
   Molecular weight retained:	13.15 and above
   Surface acceleration:	436.72	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.309
   Length of year:		7381.39	days
   Length of day:		22.93	hours
   Boiling point of water:	56.7	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	29.38
   liquids at surface:
				Ozone        melts at -193  boils at -131
   gasses in atmosphere:
				Oxygen           23.1%  PP   39.1 mb
				Nitrogen         76.8%  PP  130.0 mb
				Methane           0.1%  PP    0.1 mb


Planet 12	*gas giant*
   Distance from primary:	10.099	AU
   Mass:			311.968	Earth masses
   Equatorial radius:		67423.6	km
   Density:			1.452	grams/cc
   Eccentricity of orbit:	0.078
   Escape Velocity:		60.75	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2736.69	cm/sec2
   Axial tilt:			41	degrees
   Planetary albedo:		0.465
   Length of year:		11235.00	days
   Length of day:		7.81	hours


Planet 13	*gas giant*
   Distance from primary:	22.297	AU
   Mass:			218.815	Earth masses
   Equatorial radius:		64945.4	km
   Density:			1.140	grams/cc
   Eccentricity of orbit:	0.170
   Escape Velocity:		51.84	km/sec
   Molecular weight retained:	0.30 and above
   Surface acceleration:	2068.81	cm/sec2
   Axial tilt:			46	degrees
   Planetary albedo:		0.453
   Length of year:		36860.24	days
   Length of day:		8.99	hours


Planet 14	*gas giant*
   Distance from primary:	37.517	AU
   Mass:			1.731	Earth masses
   Equatorial radius:		16533.6	km
   Density:			0.547	grams/cc
   Eccentricity of orbit:	0.159
   Escape Velocity:		9.14	km/sec
   Molecular weight retained:	9.51 and above
   Surface acceleration:	252.54	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.467
   Length of year:		80472.47	days
   Length of day:		25.72	hours


