                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047f17
Stellar mass: 1.09 solar masses
Stellar radius: 0.99 solar radii
Stellar luminosity: 1.54
Stellar temperature: 6327 K
Stellar class: F7
Age: 2.042 billion years  (5.049 billion left on main sequence)
Habitable ecosphere radius: 1.242 AU

Planets present at:
1	  0.429 AU	no atmosphere
2	  0.718 AU	greenhouse
3	  1.159 AU	no atmosphere
4	  1.510 AU	
5	  2.133 AU	gas giant
6	  3.956 AU	gas giant
7	  6.277 AU	no atmosphere
8	  8.937 AU	gas giant
9	 13.880 AU	gas giant
10	 26.015 AU	gas giant
11	 50.066 AU	no atmosphere



Planet 1	
   Distance from primary:	0.429	AU
   Mass:			0.205	Earth masses
   Equatorial radius:		3805.5	km
   Density:			5.311	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.58	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		191.41	degrees Celcius
   Maximum temperature:   	399.13	degrees Celcius
   Minimum temperature:   	-207.09	degrees Celcius
   Escape Velocity:		6.56	km/sec
   Molecular weight retained:	18.47 and above
   Surface acceleration:	564.80	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.080
   Length of year:		98.23	days
   Length of day:		2357.64	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.718	AU
   Mass:			1.104	Earth masses
   Equatorial radius:		6613.5	km
   Density:			5.446	grams/cc
   Eccentricity of orbit:	0.094
   Surface gravity:		1.03	Earth gees
   Surface pressure:		119.227	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		507.56	degrees Celcius
   Maximum temperature:   	511.44	degrees Celcius
   Minimum temperature:   	500.97	degrees Celcius
   Escape Velocity:		11.54	km/sec
   Molecular weight retained:	5.96 and above
   Surface acceleration:	1006.58	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.532
   Length of year:		212.58	days
   Length of day:		18.55	hours
   Boiling point of water:	303.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1195
				Cesium       melts at 28    boils at 1239
				Gallium      melts at 30    boils at 3863
				Rubidium     melts at 39    boils at 1212
				Potassium    melts at 63    boils at 1333
				Sodium       melts at 98    boils at 1512
				Indium       melts at 157   boils at 3364
				Lithium      melts at 181   boils at 2231
				Selenium     melts at 217   boils at 1208
				Tin          melts at 232   boils at 4204
				Polonium     melts at 254   boils at 1636
				Bismuth      melts at 271   boils at 2567
				Thallium     melts at 304   boils at 2401
				Cadmium      melts at 321   boils at 1331
				Lead         melts at 328   boils at 2856
				Zinc         melts at 420   boils at 1551
				Tellurium    melts at 450   boils at 1679
   gasses in atmosphere:
				Sulfur           20.7%  PP 24655.0 mb
				Nitrogen         78.7%  PP 93821.2 mb
				Phosphorus        0.4%  PP  491.6 mb


Planet 3	
   Distance from primary:	1.159	AU
   Mass:			1/1035	Earth masses
   Equatorial radius:		640.5	km
   Density:			5.248	grams/cc
   Eccentricity of orbit:	0.004
   Surface gravity:		0.10	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		8.97	degrees Celcius
   Maximum temperature:   	169.89	degrees Celcius
   Minimum temperature:   	-235.82	degrees Celcius
   Escape Velocity:		1.10	km/sec
   Molecular weight retained:	659.69 and above
   Surface acceleration:	93.94	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.089
   Length of year:		435.76	days
   Length of day:		10458.30	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 4	
   Distance from primary:	1.510	AU
   Mass:			1.318	Earth masses
   Equatorial radius:		7004.3	km
   Density:			5.471	grams/cc
   Eccentricity of orbit:	0.146
   Surface gravity:		1.09	Earth gees
   Surface pressure:		1.418	Earth atmospheres
   Surface temperature:		6.06	degrees Celcius
   Normal daytime temperature:	9.48	degrees Celcius
   Normal night temperature:	2.44	degrees Celcius
   Maximum temperature:   	29.77	degrees Celcius
   Minimum temperature:   	-19.03	degrees Celcius
   Escape Velocity:		12.25	km/sec
   Molecular weight retained:	5.29 and above
   Surface acceleration:	1071.04	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.183
   Length of year:		647.98	days
   Length of day:		14.67	hours
   Boiling point of water:	109.9	degrees Celcius
   Hydrosphere percentage:	63.42
   Cloud cover percentage:	25.17
   Ice cover percentage:	4.41
   liquids at surface:
				Ethanol      melts at -114  boils at 88
				Mercury      melts at -39   boils at 374
				Bromine      melts at -7    boils at 68
				Water        melts at 0     boils at 110
   gasses in atmosphere:
				Oxygen           21.7%  PP  307.1 mb
				Nitrogen         78.2%  PP 1109.4 mb


Planet 5	*gas giant*
   Distance from primary:	2.133	AU
   Mass:			50.991	Earth masses
   Equatorial radius:		34887.4	km
   Density:			1.714	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		34.14	km/sec
   Molecular weight retained:	0.68 and above
   Surface acceleration:	1670.69	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.534
   Length of year:		1087.95	days
   Length of day:		10.00	hours


Planet 6	*gas giant*
   Distance from primary:	3.956	AU
   Mass:			86.773	Earth masses
   Equatorial radius:		42891.3	km
   Density:			1.569	grams/cc
   Eccentricity of orbit:	0.158
   Escape Velocity:		40.17	km/sec
   Molecular weight retained:	0.49 and above
   Surface acceleration:	1880.98	cm/sec2
   Axial tilt:			20	degrees
   Planetary albedo:		0.505
   Length of year:		2748.13	days
   Length of day:		9.42	hours


Planet 7	
   Distance from primary:	6.277	AU
   Mass:			0.352	Earth masses
   Equatorial radius:		6074.1	km
   Density:			2.244	grams/cc
   Eccentricity of orbit:	0.000
   Surface gravity:		0.39	Earth gees
   Surface pressure:		0.087	Earth atmospheres
   Surface temperature:		-152.85	degrees Celcius
   Normal daytime temperature:	-145.09	degrees Celcius
   Normal night temperature:	-160.96	degrees Celcius
   Maximum temperature:   	-127.87	degrees Celcius
   Minimum temperature:   	-179.53	degrees Celcius
   Escape Velocity:		6.80	km/sec
   Molecular weight retained:	17.16 and above
   Surface acceleration:	380.87	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.321
   Length of year:		5493.38	days
   Length of day:		24.56	hours
   Boiling point of water:	43.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	29.15
   liquids at surface:
				Ozone        melts at -193  boils at -136
   gasses in atmosphere:
				Fluorine          8.7%  PP    7.6 mb
				Argon             2.0%  PP    1.7 mb
				Neon             10.9%  PP    9.5 mb
				Krypton          78.4%  PP   68.5 mb


Planet 8	*gas giant*
   Distance from primary:	8.937	AU
   Mass:			90.921	Earth masses
   Equatorial radius:		46534.9	km
   Density:			1.287	grams/cc
   Eccentricity of orbit:	0.170
   Escape Velocity:		39.48	km/sec
   Molecular weight retained:	0.51 and above
   Surface acceleration:	1674.35	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.526
   Length of year:		9331.04	days
   Length of day:		9.99	hours


Planet 9	*gas giant*
   Distance from primary:	13.880	AU
   Mass:			312.067	Earth masses
   Equatorial radius:		69171.1	km
   Density:			1.345	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		59.99	km/sec
   Molecular weight retained:	0.22 and above
   Surface acceleration:	2600.99	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.503
   Length of year:		18055.67	days
   Length of day:		8.01	hours


Planet 10	*gas giant*
   Distance from primary:	26.015	AU
   Mass:			27.489	Earth masses
   Equatorial radius:		35886.0	km
   Density:			0.849	grams/cc
   Eccentricity of orbit:	0.004
   Escape Velocity:		24.72	km/sec
   Molecular weight retained:	1.30 and above
   Surface acceleration:	851.22	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.492
   Length of year:		46348.93	days
   Length of day:		14.01	hours


Planet 11	
   Distance from primary:	50.066	AU
   Mass:			0.171	Earth masses
   Equatorial radius:		4787.5	km
   Density:			2.221	grams/cc
   Eccentricity of orbit:	0.044
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.47	degrees Celcius
   Normal daytime temperature:	-225.29	degrees Celcius
   Normal night temperature:	-235.56	degrees Celcius
   Maximum temperature:   	-211.54	degrees Celcius
   Minimum temperature:   	-249.61	degrees Celcius
   Escape Velocity:		5.33	km/sec
   Molecular weight retained:	27.89 and above
   Surface acceleration:	297.22	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.140
   Length of year:		123749.18	days
   Length of day:		27.80	hours
   Boiling point of water:	-53.9	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


