                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950482b8
Stellar mass: 1.10 solar masses
Stellar radius: 1.01 solar radii
Stellar luminosity: 1.58
Stellar temperature: 6293 K
Stellar class: F8
Age: 3.208 billion years  (3.760 billion left on main sequence)
Habitable ecosphere radius: 1.256 AU

Planets present at:
1	  0.414 AU	no atmosphere
2	  0.577 AU	no atmosphere
3	  0.913 AU	greenhouse
4	  0.951 AU	greenhouse
5	  1.929 AU	gas giant
6	  3.390 AU	gas giant
7	  6.280 AU	gas giant
8	 10.864 AU	gas giant
9	 23.871 AU	gas giant
10	 34.464 AU	gas giant
11	 48.871 AU	no atmosphere



Planet 1	
   Distance from primary:	0.414	AU
   Mass:			0.077	Earth masses
   Equatorial radius:		2750.0	km
   Density:			5.279	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		201.59	degrees Celcius
   Maximum temperature:   	411.59	degrees Celcius
   Minimum temperature:   	-204.85	degrees Celcius
   Escape Velocity:		4.72	km/sec
   Molecular weight retained:	35.57 and above
   Surface acceleration:	405.75	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.087
   Length of year:		92.87	days
   Length of day:		2228.78	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.577	AU
   Mass:			0.141	Earth masses
   Equatorial radius:		3364.4	km
   Density:			5.296	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		132.20	degrees Celcius
   Maximum temperature:   	326.20	degrees Celcius
   Minimum temperature:   	-220.24	degrees Celcius
   Escape Velocity:		5.79	km/sec
   Molecular weight retained:	23.69 and above
   Surface acceleration:	497.99	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.056
   Length of year:		152.91	days
   Length of day:		3669.95	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.913	AU
   Mass:			0.634	Earth masses
   Equatorial radius:		5518.0	km
   Density:			5.384	grams/cc
   Eccentricity of orbit:	0.103
   Surface gravity:		0.85	Earth gees
   Surface pressure:		31.171	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		211.95	degrees Celcius
   Maximum temperature:   	219.24	degrees Celcius
   Minimum temperature:   	203.99	degrees Celcius
   Escape Velocity:		9.57	km/sec
   Molecular weight retained:	8.66 and above
   Surface acceleration:	830.24	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.445
   Length of year:		304.11	days
   Length of day:		18.69	hours
   Boiling point of water:	227.0	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 571
				Francium     melts at 27    boils at 1000
				Cesium       melts at 28    boils at 1038
				Gallium      melts at 30    boils at 3314
				Rubidium     melts at 39    boils at 1015
				Phosphorus   melts at 44    boils at 469
				Potassium    melts at 63    boils at 1119
				Sodium       melts at 98    boils at 1275
				Sulfur       melts at 113   boils at 689
				Indium       melts at 157   boils at 2881
				Lithium      melts at 181   boils at 1898
   gasses in atmosphere:
				Nitrogen         99.6%  PP 31050.4 mb
				CarbonDioxide     0.1%  PP   26.4 mb
				Ozone             0.1%  PP   25.9 mb
				Ethanol           0.1%  PP   26.8 mb


Planet 4	
   Distance from primary:	0.951	AU
   Mass:			1.964	Earth masses
   Equatorial radius:		7967.1	km
   Density:			5.541	grams/cc
   Eccentricity of orbit:	0.096
   Surface gravity:		1.26	Earth gees
   Surface pressure:		354.095	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		515.39	degrees Celcius
   Maximum temperature:   	517.53	degrees Celcius
   Minimum temperature:   	510.69	degrees Celcius
   Escape Velocity:		14.02	km/sec
   Molecular weight retained:	4.04 and above
   Surface acceleration:	1233.85	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.585
   Length of year:		323.25	days
   Length of day:		14.12	hours
   Boiling point of water:	385.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1404
				Cesium       melts at 28    boils at 1453
				Gallium      melts at 30    boils at 4451
				Rubidium     melts at 39    boils at 1423
				Potassium    melts at 63    boils at 1560
				Sodium       melts at 98    boils at 1765
				Indium       melts at 157   boils at 3880
				Lithium      melts at 181   boils at 2586
				Selenium     melts at 217   boils at 1418
				Tin          melts at 232   boils at 4839
				Polonium     melts at 254   boils at 1907
				Bismuth      melts at 271   boils at 2970
				Thallium     melts at 304   boils at 2781
				Cadmium      melts at 321   boils at 1559
				Lead         melts at 328   boils at 3300
				Zinc         melts at 420   boils at 1810
				Tellurium    melts at 450   boils at 1956
   gasses in atmosphere:
				Sulfur           18.5%  PP 65551.6 mb
				Nitrogen         80.9%  PP 286606.1 mb
				Phosphorus        0.4%  PP 1310.7 mb


Planet 5	*gas giant*
   Distance from primary:	1.929	AU
   Mass:			15.705	Earth masses
   Equatorial radius:		24516.1	km
   Density:			1.521	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		22.60	km/sec
   Molecular weight retained:	1.55 and above
   Surface acceleration:	1042.00	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.537
   Length of year:		933.60	days
   Length of day:		12.66	hours


Planet 6	*gas giant*
   Distance from primary:	3.390	AU
   Mass:			118.498	Earth masses
   Equatorial radius:		46328.9	km
   Density:			1.700	grams/cc
   Eccentricity of orbit:	0.025
   Escape Velocity:		45.17	km/sec
   Molecular weight retained:	0.39 and above
   Surface acceleration:	2201.64	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.460
   Length of year:		2175.18	days
   Length of day:		8.71	hours


Planet 7	*gas giant*
   Distance from primary:	6.280	AU
   Mass:			40.895	Earth masses
   Equatorial radius:		35760.4	km
   Density:			1.276	grams/cc
   Eccentricity of orbit:	0.010
   Escape Velocity:		30.20	km/sec
   Molecular weight retained:	0.87 and above
   Surface acceleration:	1275.29	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.465
   Length of year:		5484.60	days
   Length of day:		11.44	hours


Planet 8	*gas giant*
   Distance from primary:	10.864	AU
   Mass:			293.354	Earth masses
   Equatorial radius:		66499.9	km
   Density:			1.423	grams/cc
   Eccentricity of orbit:	0.134
   Escape Velocity:		59.32	km/sec
   Molecular weight retained:	0.23 and above
   Surface acceleration:	2645.39	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.504
   Length of year:		12474.07	days
   Length of day:		7.95	hours


Planet 9	*gas giant*
   Distance from primary:	23.871	AU
   Mass:			177.730	Earth masses
   Equatorial radius:		61353.0	km
   Density:			1.098	grams/cc
   Eccentricity of orbit:	0.182
   Escape Velocity:		48.07	km/sec
   Molecular weight retained:	0.34 and above
   Surface acceleration:	1882.90	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.476
   Length of year:		40635.96	days
   Length of day:		9.42	hours


Planet 10	*gas giant*
   Distance from primary:	34.464	AU
   Mass:			0.265	Earth masses
   Equatorial radius:		9473.2	km
   Density:			0.444	grams/cc
   Eccentricity of orbit:	0.122
   Escape Velocity:		4.72	km/sec
   Molecular weight retained:	35.64 and above
   Surface acceleration:	117.54	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.454
   Length of year:		70511.91	days
   Length of day:		37.70	hours


Planet 11	
   Distance from primary:	48.871	AU
   Mass:			0.098	Earth masses
   Equatorial radius:		3983.7	km
   Density:			2.210	grams/cc
   Eccentricity of orbit:	0.046
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.03	degrees Celcius
   Normal daytime temperature:	-224.33	degrees Celcius
   Normal night temperature:	-235.61	degrees Celcius
   Maximum temperature:   	-211.51	degrees Celcius
   Minimum temperature:   	-248.76	degrees Celcius
   Escape Velocity:		4.43	km/sec
   Molecular weight retained:	40.49 and above
   Surface acceleration:	246.08	cm/sec2
   Axial tilt:			55	degrees
   Planetary albedo:		0.147
   Length of year:		119069.50	days
   Length of day:		30.55	hours
   Boiling point of water:	-63.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


