                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047b77
Stellar mass: 1.09 solar masses
Stellar radius: 0.98 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6317 K
Stellar class: F7
Age: 5.548 billion years  (1.671 billion left on main sequence)
Habitable ecosphere radius: 1.228 AU

Planets present at:
1	  0.319 AU	no atmosphere
2	  0.558 AU	no atmosphere
3	  0.857 AU	greenhouse
4	  1.526 AU	gas giant
5	  2.051 AU	high pressure
6	  3.581 AU	gas giant
7	  6.169 AU	gas giant
8	  7.792 AU	no atmosphere
9	 15.652 AU	gas giant
10	 26.006 AU	gas giant
11	 45.091 AU	gas giant



Planet 1	
   Distance from primary:	0.319	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		3409.2	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		263.02	degrees Celcius
   Normal daytime temperature:	482.59	degrees Celcius
   Normal night temperature:	-175.28	degrees Celcius
   Maximum temperature:   	485.83	degrees Celcius
   Minimum temperature:   	-186.82	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.07 and above
   Surface acceleration:	504.75	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.078
   Length of year:		63.06	days
   Length of day:		1513.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.558	AU
   Mass:			0.239	Earth masses
   Equatorial radius:		4003.3	km
   Density:			5.318	grams/cc
   Eccentricity of orbit:	0.150
   Surface gravity:		0.61	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.44	degrees Celcius
   Maximum temperature:   	327.69	degrees Celcius
   Minimum temperature:   	-217.34	degrees Celcius
   Escape Velocity:		6.90	km/sec
   Molecular weight retained:	16.66 and above
   Surface acceleration:	594.94	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.066
   Length of year:		146.09	days
   Length of day:		2592.03	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.857	AU
   Mass:			0.989	Earth masses
   Equatorial radius:		6381.3	km
   Density:			5.432	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.99	Earth gees
   Surface pressure:		99.758	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		451.28	degrees Celcius
   Maximum temperature:   	455.69	degrees Celcius
   Minimum temperature:   	444.71	degrees Celcius
   Escape Velocity:		11.12	km/sec
   Molecular weight retained:	6.42 and above
   Surface acceleration:	968.71	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.437
   Length of year:		277.85	days
   Length of day:		19.00	hours
   Boiling point of water:	292.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1166
				Cesium       melts at 28    boils at 1209
				Gallium      melts at 30    boils at 3781
				Rubidium     melts at 39    boils at 1183
				Potassium    melts at 63    boils at 1300
				Sodium       melts at 98    boils at 1476
				Indium       melts at 157   boils at 3292
				Lithium      melts at 181   boils at 2181
				Selenium     melts at 217   boils at 1178
				Tin          melts at 232   boils at 4114
				Polonium     melts at 254   boils at 1598
				Bismuth      melts at 271   boils at 2510
				Thallium     melts at 304   boils at 2348
				Cadmium      melts at 321   boils at 1299
				Lead         melts at 328   boils at 2793
				Zinc         melts at 420   boils at 1515
				Tellurium    melts at 450   boils at 1640
   gasses in atmosphere:
				Sulfur           24.3%  PP 24218.8 mb
				Nitrogen         75.0%  PP 74820.3 mb
				Phosphorus        0.5%  PP  479.7 mb
				CarbonDioxide     0.1%  PP   54.6 mb
				Ethanol           0.1%  PP   55.7 mb


Planet 4	*gas giant*
   Distance from primary:	1.526	AU
   Mass:			9.673	Earth masses
   Equatorial radius:		20912.5	km
   Density:			1.509	grams/cc
   Eccentricity of orbit:	0.068
   Escape Velocity:		19.21	km/sec
   Molecular weight retained:	2.15 and above
   Surface acceleration:	882.07	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.501
   Length of year:		660.27	days
   Length of day:		13.77	hours


Planet 5	
   Distance from primary:	2.051	AU
   Mass:			1.504	Earth masses
   Equatorial radius:		7310.7	km
   Density:			5.492	grams/cc
   Eccentricity of orbit:	0.005
   Surface gravity:		1.14	Earth gees
   Surface pressure:		2.268	Earth atmospheres
   Surface temperature:		-89.55	degrees Celcius
   Normal daytime temperature:	-87.80	degrees Celcius
   Normal night temperature:	-91.40	degrees Celcius
   Maximum temperature:   	-74.70	degrees Celcius
   Minimum temperature:   	-105.45	degrees Celcius
   Escape Velocity:		12.81	km/sec
   Molecular weight retained:	4.84 and above
   Surface acceleration:	1122.21	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.731
   Length of year:		1028.64	days
   Length of day:		14.32	hours
   Boiling point of water:	124.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.04
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 101
				Chlorine     melts at -101  boils at -19
   gasses in atmosphere:
				Nitrogen         99.9%  PP 2266.0 mb
				Ozone             0.1%  PP    1.1 mb


Planet 6	*gas giant*
   Distance from primary:	3.581	AU
   Mass:			24.350	Earth masses
   Equatorial radius:		29390.5	km
   Density:			1.369	grams/cc
   Eccentricity of orbit:	0.012
   Escape Velocity:		25.71	km/sec
   Molecular weight retained:	1.20 and above
   Surface acceleration:	1124.17	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.498
   Length of year:		2372.57	days
   Length of day:		12.19	hours


Planet 7	*gas giant*
   Distance from primary:	6.169	AU
   Mass:			848.554	Earth masses
   Equatorial radius:		86635.0	km
   Density:			1.862	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		88.38	km/sec
   Molecular weight retained:	0.10 and above
   Surface acceleration:	4508.49	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.540
   Length of year:		5358.97	days
   Length of day:		6.09	hours


Planet 8	
   Distance from primary:	7.792	AU
   Mass:			0.102	Earth masses
   Equatorial radius:		4040.8	km
   Density:			2.211	grams/cc
   Eccentricity of orbit:	0.063
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.006	Earth atmospheres
   Surface temperature:		-169.28	degrees Celcius
   Normal daytime temperature:	-156.46	degrees Celcius
   Normal night temperature:	-182.20	degrees Celcius
   Maximum temperature:   	-139.13	degrees Celcius
   Minimum temperature:   	-200.41	degrees Celcius
   Escape Velocity:		4.49	km/sec
   Molecular weight retained:	39.34 and above
   Surface acceleration:	249.70	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.238
   Length of year:		7616.13	days
   Length of day:		30.33	hours
   Boiling point of water:	-1.6	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	16.39
   liquids at surface:
				Ozone        melts at -193  boils at -155
   gasses in atmosphere:
				Argon            100.0%  PP    6.3 mb


Planet 9	*gas giant*
   Distance from primary:	15.652	AU
   Mass:			457.329	Earth masses
   Equatorial radius:		78178.9	km
   Density:			1.366	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		68.31	km/sec
   Molecular weight retained:	0.17 and above
   Surface acceleration:	2983.94	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.494
   Length of year:		21667.22	days
   Length of day:		7.48	hours


Planet 10	*gas giant*
   Distance from primary:	26.006	AU
   Mass:			1.656	Earth masses
   Equatorial radius:		15827.9	km
   Density:			0.596	grams/cc
   Eccentricity of orbit:	0.035
   Escape Velocity:		9.13	km/sec
   Molecular weight retained:	9.52 and above
   Surface acceleration:	263.53	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.469
   Length of year:		46435.58	days
   Length of day:		25.18	hours


Planet 11	*gas giant*
   Distance from primary:	45.091	AU
   Mass:			0.648	Earth masses
   Equatorial radius:		12605.0	km
   Density:			0.462	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		6.40	km/sec
   Molecular weight retained:	19.36 and above
   Surface acceleration:	162.66	cm/sec2
   Axial tilt:			66	degrees
   Planetary albedo:		0.457
   Length of year:		106018.19	days
   Length of day:		32.05	hours


