                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047d71
Stellar mass: 1.09 solar masses
Stellar radius: 1.04 solar radii
Stellar luminosity: 1.53
Stellar temperature: 6157 K
Stellar class: F8
Age: 1.234 billion years  (5.915 billion left on main sequence)
Habitable ecosphere radius: 1.235 AU

Planets present at:
1	  0.363 AU	no atmosphere
2	  0.426 AU	no atmosphere
3	  0.566 AU	no atmosphere
4	  0.630 AU	no atmosphere
5	  0.914 AU	greenhouse
6	  1.255 AU	no atmosphere
7	  1.687 AU	gas giant
8	  3.031 AU	cold
9	  3.867 AU	high pressure
10	  4.579 AU	cold
11	  6.600 AU	gas giant
12	  9.625 AU	no atmosphere
13	 15.960 AU	gas giant
14	 22.682 AU	gas giant
15	 32.940 AU	gas giant
16	 47.292 AU	no atmosphere



Planet 1	
   Distance from primary:	0.363	AU
   Mass:			0.016	Earth masses
   Equatorial radius:		1642.8	km
   Density:			5.258	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		234.58	degrees Celcius
   Maximum temperature:   	451.46	degrees Celcius
   Minimum temperature:   	-195.47	degrees Celcius
   Escape Velocity:		2.82	km/sec
   Molecular weight retained:	100.08 and above
   Surface acceleration:	241.41	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.054
   Length of year:		76.34	days
   Length of day:		1832.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.426	AU
   Mass:			0.097	Earth masses
   Equatorial radius:		2971.9	km
   Density:			5.285	grams/cc
   Eccentricity of orbit:	0.069
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.48	degrees Celcius
   Maximum temperature:   	400.44	degrees Celcius
   Minimum temperature:   	-206.80	degrees Celcius
   Escape Velocity:		5.11	km/sec
   Molecular weight retained:	30.42 and above
   Surface acceleration:	438.97	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.077
   Length of year:		97.13	days
   Length of day:		2331.23	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.566	AU
   Mass:			0.027	Earth masses
   Equatorial radius:		1942.7	km
   Density:			5.263	grams/cc
   Eccentricity of orbit:	0.016
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.17	degrees Celcius
   Maximum temperature:   	327.25	degrees Celcius
   Minimum temperature:   	-219.45	degrees Celcius
   Escape Velocity:		3.33	km/sec
   Molecular weight retained:	71.50 and above
   Surface acceleration:	285.73	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.054
   Length of year:		148.88	days
   Length of day:		3573.11	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.630	AU
   Mass:			0.350	Earth masses
   Equatorial radius:		4541.6	km
   Density:			5.338	grams/cc
   Eccentricity of orbit:	0.022
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		111.31	degrees Celcius
   Normal daytime temperature:	184.85	degrees Celcius
   Normal night temperature:	34.43	degrees Celcius
   Maximum temperature:   	214.18	degrees Celcius
   Minimum temperature:   	3.30	degrees Celcius
   Escape Velocity:		7.85	km/sec
   Molecular weight retained:	12.90 and above
   Surface acceleration:	677.59	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.060
   Length of year:		175.01	days
   Length of day:		50.02	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 5	
   Distance from primary:	0.914	AU
   Mass:			1.178	Earth masses
   Equatorial radius:		6753.8	km
   Density:			5.455	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		1.05	Earth gees
   Surface pressure:		121.894	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		449.99	degrees Celcius
   Maximum temperature:   	453.71	degrees Celcius
   Minimum temperature:   	444.28	degrees Celcius
   Escape Velocity:		11.79	km/sec
   Molecular weight retained:	5.71 and above
   Surface acceleration:	1029.63	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.443
   Length of year:		305.76	days
   Length of day:		15.32	hours
   Boiling point of water:	305.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1199
				Cesium       melts at 28    boils at 1243
				Gallium      melts at 30    boils at 3874
				Rubidium     melts at 39    boils at 1216
				Potassium    melts at 63    boils at 1337
				Sodium       melts at 98    boils at 1516
				Indium       melts at 157   boils at 3373
				Lithium      melts at 181   boils at 2237
				Selenium     melts at 217   boils at 1212
				Tin          melts at 232   boils at 4215
				Polonium     melts at 254   boils at 1641
				Bismuth      melts at 271   boils at 2574
				Thallium     melts at 304   boils at 2408
				Cadmium      melts at 321   boils at 1335
				Lead         melts at 328   boils at 2864
				Zinc         melts at 420   boils at 1556
				Tellurium    melts at 450   boils at 1684
   gasses in atmosphere:
				Sulfur           19.3%  PP 23580.0 mb
				Nitrogen         80.1%  PP 97589.1 mb
				Phosphorus        0.4%  PP  471.4 mb


Planet 6	
   Distance from primary:	1.255	AU
   Mass:			0.086	Earth masses
   Equatorial radius:		2853.0	km
   Density:			5.282	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.43	Earth gees
   Surface pressure:		0.008	Earth atmospheres
   Surface temperature:		-28.87	degrees Celcius
   Normal daytime temperature:	-4.52	degrees Celcius
   Normal night temperature:	-53.48	degrees Celcius
   Maximum temperature:   	21.97	degrees Celcius
   Minimum temperature:   	-80.56	degrees Celcius
   Escape Velocity:		4.90	km/sec
   Molecular weight retained:	33.03 and above
   Surface acceleration:	421.16	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.402
   Length of year:		491.41	days
   Length of day:		24.14	hours
   Boiling point of water:	1.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	46.59
   liquids at surface:
				Ethanol      melts at -114  boils at -13
				Mercury      melts at -39   boils at 193
   gasses in atmosphere:
				CarbonDioxide    37.0%  PP    2.8 mb
				Ozone            46.6%  PP    3.5 mb
				Chlorine         11.6%  PP    0.9 mb
				Krypton           4.2%  PP    0.3 mb
				Xenon             0.6%  PP    0.0 mb


Planet 7	*gas giant*
   Distance from primary:	1.687	AU
   Mass:			11.376	Earth masses
   Equatorial radius:		22097.7	km
   Density:			1.504	grams/cc
   Eccentricity of orbit:	0.028
   Escape Velocity:		20.26	km/sec
   Molecular weight retained:	1.93 and above
   Surface acceleration:	929.07	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.465
   Length of year:		766.16	days
   Length of day:		13.41	hours


Planet 8	
   Distance from primary:	3.031	AU
   Mass:			0.534	Earth masses
   Equatorial radius:		5217.4	km
   Density:			5.369	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		0.80	Earth gees
   Surface pressure:		0.211	Earth atmospheres
   Surface temperature:		-107.41	degrees Celcius
   Normal daytime temperature:	-101.81	degrees Celcius
   Normal night temperature:	-113.27	degrees Celcius
   Maximum temperature:   	-80.07	degrees Celcius
   Minimum temperature:   	-136.69	degrees Celcius
   Escape Velocity:		9.04	km/sec
   Molecular weight retained:	9.72 and above
   Surface acceleration:	782.82	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.488
   Length of year:		1845.68	days
   Length of day:		17.13	hours
   Boiling point of water:	61.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	62.78
   liquids at surface:
				Ethanol      melts at -114  boils at 42
   gasses in atmosphere:
				Oxygen           71.8%  PP  151.2 mb
				Nitrogen         28.2%  PP   59.4 mb


Planet 9	
   Distance from primary:	3.867	AU
   Mass:			1.816	Earth masses
   Equatorial radius:		7768.8	km
   Density:			5.526	grams/cc
   Eccentricity of orbit:	0.077
   Surface gravity:		1.22	Earth gees
   Surface pressure:		3.342	Earth atmospheres
   Surface temperature:		-127.23	degrees Celcius
   Normal daytime temperature:	-126.12	degrees Celcius
   Normal night temperature:	-128.41	degrees Celcius
   Maximum temperature:   	-115.15	degrees Celcius
   Minimum temperature:   	-140.26	degrees Celcius
   Escape Velocity:		13.65	km/sec
   Molecular weight retained:	4.26 and above
   Surface acceleration:	1199.81	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.646
   Length of year:		2659.39	days
   Length of day:		13.84	hours
   Boiling point of water:	136.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -96
   gasses in atmosphere:
				Oxygen            2.0%  PP   66.6 mb
				Nitrogen         98.0%  PP 3273.8 mb


Planet 10	
   Distance from primary:	4.579	AU
   Mass:			0.991	Earth masses
   Equatorial radius:		6384.9	km
   Density:			5.432	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.99	Earth gees
   Surface pressure:		0.827	Earth atmospheres
   Surface temperature:		-143.55	degrees Celcius
   Normal daytime temperature:	-141.39	degrees Celcius
   Normal night temperature:	-145.82	degrees Celcius
   Maximum temperature:   	-126.05	degrees Celcius
   Minimum temperature:   	-162.64	degrees Celcius
   Escape Velocity:		11.13	km/sec
   Molecular weight retained:	6.41 and above
   Surface acceleration:	969.28	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.622
   Length of year:		3426.24	days
   Length of day:		15.39	hours
   Boiling point of water:	94.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	88.74
   liquids at surface:
				Ozone        melts at -193  boils at -114
   gasses in atmosphere:
				Oxygen           46.8%  PP  387.0 mb
				Nitrogen         53.2%  PP  439.6 mb


Planet 11	*gas giant*
   Distance from primary:	6.600	AU
   Mass:			988.056	Earth masses
   Equatorial radius:		91032.3	km
   Density:			1.869	grams/cc
   Eccentricity of orbit:	0.032
   Escape Velocity:		93.04	km/sec
   Molecular weight retained:	0.09 and above
   Surface acceleration:	4754.78	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.465
   Length of year:		5921.44	days
   Length of day:		5.93	hours


Planet 12	
   Distance from primary:	9.625	AU
   Mass:			0.097	Earth masses
   Equatorial radius:		3969.2	km
   Density:			2.210	grams/cc
   Eccentricity of orbit:	0.097
   Surface gravity:		0.25	Earth gees
   Surface pressure:		0.006	Earth atmospheres
   Surface temperature:		-179.76	degrees Celcius
   Normal daytime temperature:	-168.11	degrees Celcius
   Normal night temperature:	-191.48	degrees Celcius
   Maximum temperature:   	-147.24	degrees Celcius
   Minimum temperature:   	-213.36	degrees Celcius
   Escape Velocity:		4.41	km/sec
   Molecular weight retained:	40.79 and above
   Surface acceleration:	245.17	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.250
   Length of year:		10441.93	days
   Length of day:		30.61	hours
   Boiling point of water:	-2.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	17.12
   liquids at surface:
				Ozone        melts at -193  boils at -155


Planet 13	*gas giant*
   Distance from primary:	15.960	AU
   Mass:			21.459	Earth masses
   Equatorial radius:		32067.1	km
   Density:			0.929	grams/cc
   Eccentricity of orbit:	0.115
   Escape Velocity:		23.10	km/sec
   Molecular weight retained:	1.49 and above
   Surface acceleration:	832.21	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.531
   Length of year:		22295.16	days
   Length of day:		14.17	hours


Planet 14	*gas giant*
   Distance from primary:	22.682	AU
   Mass:			5.506	Earth masses
   Equatorial radius:		22206.6	km
   Density:			0.717	grams/cc
   Eccentricity of orbit:	0.080
   Escape Velocity:		14.06	km/sec
   Molecular weight retained:	4.01 and above
   Surface acceleration:	445.29	cm/sec2
   Axial tilt:			33	degrees
   Planetary albedo:		0.463
   Length of year:		37774.35	days
   Length of day:		19.37	hours


Planet 15	*gas giant*
   Distance from primary:	32.940	AU
   Mass:			10.197	Earth masses
   Equatorial radius:		27418.0	km
   Density:			0.706	grams/cc
   Eccentricity of orbit:	0.061
   Escape Velocity:		17.22	km/sec
   Molecular weight retained:	2.68 and above
   Surface acceleration:	540.93	cm/sec2
   Axial tilt:			52	degrees
   Planetary albedo:		0.473
   Length of year:		66108.74	days
   Length of day:		17.57	hours


Planet 16	
   Distance from primary:	47.292	AU
   Mass:			0.160	Earth masses
   Equatorial radius:		4685.5	km
   Density:			2.220	grams/cc
   Eccentricity of orbit:	0.122
   Surface gravity:		0.30	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-229.61	degrees Celcius
   Normal daytime temperature:	-224.27	degrees Celcius
   Normal night temperature:	-234.86	degrees Celcius
   Maximum temperature:   	-210.21	degrees Celcius
   Minimum temperature:   	-249.22	degrees Celcius
   Escape Velocity:		5.22	km/sec
   Molecular weight retained:	29.14 and above
   Surface acceleration:	290.68	cm/sec2
   Axial tilt:			54	degrees
   Planetary albedo:		0.159
   Length of year:		113729.89	days
   Length of day:		28.11	hours
   Boiling point of water:	-56.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


