                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f950488c2
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.64
Stellar temperature: 6229 K
Stellar class: F8
Age: 3.904 billion years  (2.863 billion left on main sequence)
Habitable ecosphere radius: 1.279 AU

Planets present at:
1	  0.433 AU	no atmosphere
2	  0.480 AU	no atmosphere
3	  0.702 AU	no atmosphere
4	  1.605 AU	gas giant
5	  4.173 AU	gas giant
6	 10.461 AU	gas giant
7	 14.640 AU	gas giant
8	 22.268 AU	gas giant
9	 32.487 AU	gas giant
10	 46.231 AU	no atmosphere
11	 51.112 AU	no atmosphere



Planet 1	
   Distance from primary:	0.433	AU
   Mass:			0.344	Earth masses
   Equatorial radius:		4514.4	km
   Density:			5.337	grams/cc
   Eccentricity of orbit:	0.035
   Surface gravity:		0.69	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		198.30	degrees Celcius
   Maximum temperature:   	407.55	degrees Celcius
   Minimum temperature:   	-206.03	degrees Celcius
   Escape Velocity:		7.80	km/sec
   Molecular weight retained:	13.06 and above
   Surface acceleration:	673.38	cm/sec2
   Axial tilt:			16	degrees
   Planetary albedo:		0.064
   Length of year:		98.91	days
   Length of day:		2373.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 2	
   Distance from primary:	0.480	AU
   Mass:			0.035	Earth masses
   Equatorial radius:		2114.2	km
   Density:			5.266	grams/cc
   Eccentricity of orbit:	0.048
   Surface gravity:		0.32	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		172.96	degrees Celcius
   Maximum temperature:   	376.56	degrees Celcius
   Minimum temperature:   	-211.90	degrees Celcius
   Escape Velocity:		3.63	km/sec
   Molecular weight retained:	60.34 and above
   Surface acceleration:	311.14	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.077
   Length of year:		115.52	days
   Length of day:		2772.52	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.702	AU
   Mass:			0.219	Earth masses
   Equatorial radius:		3889.7	km
   Density:			5.313	grams/cc
   Eccentricity of orbit:	0.253
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		97.98	degrees Celcius
   Maximum temperature:   	283.58	degrees Celcius
   Minimum temperature:   	-224.10	degrees Celcius
   Escape Velocity:		6.70	km/sec
   Molecular weight retained:	17.67 and above
   Surface acceleration:	577.61	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.055
   Length of year:		204.17	days
   Length of day:		2919.82	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491


Planet 4	*gas giant*
   Distance from primary:	1.605	AU
   Mass:			48.588	Earth masses
   Equatorial radius:		33511.0	km
   Density:			1.842	grams/cc
   Eccentricity of orbit:	0.214
   Escape Velocity:		34.01	km/sec
   Molecular weight retained:	0.69 and above
   Surface acceleration:	1725.42	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.500
   Length of year:		705.68	days
   Length of day:		9.84	hours


Planet 5	*gas giant*
   Distance from primary:	4.173	AU
   Mass:			616.689	Earth masses
   Equatorial radius:		76145.5	km
   Density:			1.993	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		80.37	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4241.48	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.515
   Length of year:		2957.50	days
   Length of day:		6.28	hours


Planet 6	*gas giant*
   Distance from primary:	10.461	AU
   Mass:			9.204	Earth masses
   Equatorial radius:		24115.4	km
   Density:			0.936	grams/cc
   Eccentricity of orbit:	0.075
   Escape Velocity:		17.45	km/sec
   Molecular weight retained:	2.61 and above
   Surface acceleration:	631.16	cm/sec2
   Axial tilt:			40	degrees
   Planetary albedo:		0.547
   Length of year:		11746.14	days
   Length of day:		16.27	hours


Planet 7	*gas giant*
   Distance from primary:	14.640	AU
   Mass:			79.073	Earth masses
   Equatorial radius:		46439.4	km
   Density:			1.127	grams/cc
   Eccentricity of orbit:	0.079
   Escape Velocity:		36.85	km/sec
   Molecular weight retained:	0.58 and above
   Surface acceleration:	1462.16	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.488
   Length of year:		19444.53	days
   Length of day:		10.69	hours


Planet 8	*gas giant*
   Distance from primary:	22.268	AU
   Mass:			1.096	Earth masses
   Equatorial radius:		13808.2	km
   Density:			0.594	grams/cc
   Eccentricity of orbit:	0.059
   Escape Velocity:		7.96	km/sec
   Molecular weight retained:	12.53 and above
   Surface acceleration:	229.33	cm/sec2
   Axial tilt:			51	degrees
   Planetary albedo:		0.539
   Length of year:		36482.49	days
   Length of day:		26.99	hours


Planet 9	*gas giant*
   Distance from primary:	32.487	AU
   Mass:			23.279	Earth masses
   Equatorial radius:		34741.0	km
   Density:			0.792	grams/cc
   Eccentricity of orbit:	0.138
   Escape Velocity:		23.12	km/sec
   Molecular weight retained:	1.49 and above
   Surface acceleration:	769.17	cm/sec2
   Axial tilt:			61	degrees
   Planetary albedo:		0.490
   Length of year:		64283.70	days
   Length of day:		14.74	hours


Planet 10	
   Distance from primary:	46.231	AU
   Mass:			0.143	Earth masses
   Equatorial radius:		4517.5	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.148
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.27	degrees Celcius
   Normal daytime temperature:	-222.67	degrees Celcius
   Normal night temperature:	-233.78	degrees Celcius
   Maximum temperature:   	-204.83	degrees Celcius
   Minimum temperature:   	-251.39	degrees Celcius
   Escape Velocity:		5.03	km/sec
   Molecular weight retained:	31.38 and above
   Surface acceleration:	279.95	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.138
   Length of year:		109130.12	days
   Length of day:		28.64	hours
   Boiling point of water:	-57.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08


Planet 11	
   Distance from primary:	51.112	AU
   Mass:			0.023	Earth masses
   Equatorial radius:		2469.7	km
   Density:			2.195	grams/cc
   Eccentricity of orbit:	0.014
   Surface gravity:		0.15	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.50	degrees Celcius
   Normal daytime temperature:	-223.57	degrees Celcius
   Normal night temperature:	-237.28	degrees Celcius
   Maximum temperature:   	-211.89	degrees Celcius
   Minimum temperature:   	-249.12	degrees Celcius
   Escape Velocity:		2.74	km/sec
   Molecular weight retained:	106.07 and above
   Surface acceleration:	151.52	cm/sec2
   Axial tilt:			59	degrees
   Planetary albedo:		0.137
   Length of year:		126862.48	days
   Length of day:		38.93	hours
   Boiling point of water:	-88.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03


