                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048792
Stellar mass: 1.11 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.62
Stellar temperature: 6218 K
Stellar class: F8
Age: 5.404 billion years  (1.402 billion left on main sequence)
Habitable ecosphere radius: 1.274 AU

Planets present at:
1	  0.318 AU	no atmosphere
2	  0.571 AU	no atmosphere
3	  0.868 AU	greenhouse
4	  1.594 AU	gas giant
5	  2.578 AU	cold
6	  3.596 AU	gas giant
7	  4.731 AU	no atmosphere
8	 13.124 AU	gas giant
9	 27.928 AU	gas giant
10	 35.590 AU	no atmosphere
11	 47.343 AU	no atmosphere



Planet 1	
   Distance from primary:	0.318	AU
   Mass:			0.099	Earth masses
   Equatorial radius:		2992.3	km
   Density:			5.286	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.45	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		273.56	degrees Celcius
   Normal daytime temperature:	495.36	degrees Celcius
   Normal night temperature:	-173.16	degrees Celcius
   Maximum temperature:   	498.40	degrees Celcius
   Minimum temperature:   	-184.05	degrees Celcius
   Escape Velocity:		5.14	km/sec
   Molecular weight retained:	30.01 and above
   Surface acceleration:	442.04	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.078
   Length of year:		62.39	days
   Length of day:		1497.33	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.571	AU
   Mass:			0.786	Earth masses
   Equatorial radius:		5920.6	km
   Density:			5.405	grams/cc
   Eccentricity of orbit:	0.133
   Surface gravity:		0.91	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		137.30	degrees Celcius
   Maximum temperature:   	332.54	degrees Celcius
   Minimum temperature:   	-217.44	degrees Celcius
   Escape Velocity:		10.29	km/sec
   Molecular weight retained:	7.50 and above
   Surface acceleration:	894.35	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.060
   Length of year:		149.72	days
   Length of day:		2752.31	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.868	AU
   Mass:			0.809	Earth masses
   Equatorial radius:		5976.5	km
   Density:			5.408	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.92	Earth gees
   Surface pressure:		48.726	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		213.51	degrees Celcius
   Maximum temperature:   	219.57	degrees Celcius
   Minimum temperature:   	206.80	degrees Celcius
   Escape Velocity:		10.39	km/sec
   Molecular weight retained:	7.35 and above
   Surface acceleration:	903.32	cm/sec2
   Axial tilt:			24	degrees
   Planetary albedo:		0.593
   Length of year:		280.95	days
   Length of day:		20.15	hours
   Boiling point of water:	250.2	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 610
				Francium     melts at 27    boils at 1059
				Cesium       melts at 28    boils at 1099
				Gallium      melts at 30    boils at 3480
				Rubidium     melts at 39    boils at 1075
				Phosphorus   melts at 44    boils at 503
				Potassium    melts at 63    boils at 1184
				Sodium       melts at 98    boils at 1346
				Sulfur       melts at 113   boils at 734
				Indium       melts at 157   boils at 3027
				Lithium      melts at 181   boils at 1999
   gasses in atmosphere:
				Nitrogen         99.6%  PP 48547.4 mb
				CarbonDioxide     0.1%  PP   40.0 mb
				Ozone             0.1%  PP   36.4 mb
				Ethanol           0.1%  PP   40.8 mb


Planet 4	*gas giant*
   Distance from primary:	1.594	AU
   Mass:			6.124	Earth masses
   Equatorial radius:		18311.8	km
   Density:			1.423	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		16.33	km/sec
   Molecular weight retained:	2.98 and above
   Surface acceleration:	728.32	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.493
   Length of year:		699.38	days
   Length of day:		15.15	hours


Planet 5	
   Distance from primary:	2.578	AU
   Mass:			0.388	Earth masses
   Equatorial radius:		4698.0	km
   Density:			5.345	grams/cc
   Eccentricity of orbit:	0.007
   Surface gravity:		0.72	Earth gees
   Surface pressure:		0.143	Earth atmospheres
   Surface temperature:		-103.60	degrees Celcius
   Normal daytime temperature:	-96.59	degrees Celcius
   Normal night temperature:	-110.91	degrees Celcius
   Maximum temperature:   	-76.30	degrees Celcius
   Minimum temperature:   	-132.63	degrees Celcius
   Escape Velocity:		8.12	km/sec
   Molecular weight retained:	12.04 and above
   Surface acceleration:	701.78	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.584
   Length of year:		1438.53	days
   Length of day:		18.10	hours
   Boiling point of water:	53.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	72.34
   liquids at surface:
				Ethanol      melts at -114  boils at 34
   gasses in atmosphere:
				Oxygen            5.5%  PP    7.9 mb
				Nitrogen         94.2%  PP  134.8 mb
				Methane           0.1%  PP    0.1 mb
				Ozone             0.2%  PP    0.3 mb


Planet 6	*gas giant*
   Distance from primary:	3.596	AU
   Mass:			462.586	Earth masses
   Equatorial radius:		69176.8	km
   Density:			1.994	grams/cc
   Eccentricity of orbit:	0.037
   Escape Velocity:		73.03	km/sec
   Molecular weight retained:	0.15 and above
   Surface acceleration:	3854.88	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.528
   Length of year:		2367.40	days
   Length of day:		6.58	hours


Planet 7	
   Distance from primary:	4.731	AU
   Mass:			0.174	Earth masses
   Equatorial radius:		3602.4	km
   Density:			5.304	grams/cc
   Eccentricity of orbit:	0.010
   Surface gravity:		0.54	Earth gees
   Surface pressure:		0.030	Earth atmospheres
   Surface temperature:		-145.18	degrees Celcius
   Normal daytime temperature:	-135.75	degrees Celcius
   Normal night temperature:	-154.80	degrees Celcius
   Maximum temperature:   	-116.67	degrees Celcius
   Minimum temperature:   	-175.20	degrees Celcius
   Escape Velocity:		6.20	km/sec
   Molecular weight retained:	20.63 and above
   Surface acceleration:	533.98	cm/sec2
   Axial tilt:			37	degrees
   Planetary albedo:		0.452
   Length of year:		3574.94	days
   Length of day:		20.74	hours
   Boiling point of water:	23.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	56.77
   liquids at surface:
				Ozone        melts at -193  boils at -145
   gasses in atmosphere:
				Argon             5.4%  PP    1.6 mb
				Krypton          94.6%  PP   27.9 mb


Planet 8	*gas giant*
   Distance from primary:	13.124	AU
   Mass:			659.132	Earth masses
   Equatorial radius:		85441.5	km
   Density:			1.508	grams/cc
   Eccentricity of orbit:	0.339
   Escape Velocity:		78.44	km/sec
   Molecular weight retained:	0.13 and above
   Surface acceleration:	3600.59	cm/sec2
   Axial tilt:			49	degrees
   Planetary albedo:		0.470
   Length of year:		16503.14	days
   Length of day:		6.81	hours


Planet 9	*gas giant*
   Distance from primary:	27.928	AU
   Mass:			0.901	Earth masses
   Equatorial radius:		13292.9	km
   Density:			0.547	grams/cc
   Eccentricity of orbit:	0.000
   Escape Velocity:		7.35	km/sec
   Molecular weight retained:	14.68 and above
   Surface acceleration:	203.38	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.497
   Length of year:		51279.33	days
   Length of day:		28.66	hours


Planet 10	
   Distance from primary:	35.590	AU
   Mass:			0.078	Earth masses
   Equatorial radius:		3690.7	km
   Density:			2.207	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.23	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-222.16	degrees Celcius
   Normal daytime temperature:	-215.19	degrees Celcius
   Normal night temperature:	-229.04	degrees Celcius
   Maximum temperature:   	-198.77	degrees Celcius
   Minimum temperature:   	-245.75	degrees Celcius
   Escape Velocity:		4.10	km/sec
   Molecular weight retained:	47.25 and above
   Surface acceleration:	227.62	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.138
   Length of year:		73769.47	days
   Length of day:		31.77	hours
   Boiling point of water:	-67.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


Planet 11	
   Distance from primary:	47.343	AU
   Mass:			0.267	Earth masses
   Equatorial radius:		5543.8	km
   Density:			2.234	grams/cc
   Eccentricity of orbit:	0.067
   Surface gravity:		0.35	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.93	degrees Celcius
   Normal daytime temperature:	-223.90	degrees Celcius
   Normal night temperature:	-233.86	degrees Celcius
   Maximum temperature:   	-210.42	degrees Celcius
   Minimum temperature:   	-247.84	degrees Celcius
   Escape Velocity:		6.19	km/sec
   Molecular weight retained:	20.69 and above
   Surface acceleration:	346.09	cm/sec2
   Axial tilt:			53	degrees
   Planetary albedo:		0.162
   Length of year:		113178.17	days
   Length of day:		25.76	hours
   Boiling point of water:	-46.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


