                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047fc1
Stellar mass: 1.09 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6215 K
Stellar class: F8
Age: 1.895 billion years  (5.173 billion left on main sequence)
Habitable ecosphere radius: 1.244 AU

Planets present at:
1	  0.375 AU	no atmosphere
2	  0.479 AU	no atmosphere
3	  0.758 AU	greenhouse
4	  1.293 AU	high pressure
5	  2.019 AU	no atmosphere
6	  2.454 AU	gas giant
7	  5.688 AU	gas giant
8	 12.467 AU	gas giant
9	 28.493 AU	gas giant
10	 46.141 AU	no atmosphere
11	 49.208 AU	no atmosphere



Planet 1	
   Distance from primary:	0.375	AU
   Mass:			0.055	Earth masses
   Equatorial radius:		2457.5	km
   Density:			5.273	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.37	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		228.01	degrees Celcius
   Maximum temperature:   	443.61	degrees Celcius
   Minimum temperature:   	-197.84	degrees Celcius
   Escape Velocity:		4.22	km/sec
   Molecular weight retained:	44.60 and above
   Surface acceleration:	362.14	cm/sec2
   Axial tilt:			12	degrees
   Planetary albedo:		0.051
   Length of year:		80.25	days
   Length of day:		1926.07	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361


Planet 2	
   Distance from primary:	0.479	AU
   Mass:			0.309	Earth masses
   Equatorial radius:		4356.5	km
   Density:			5.331	grams/cc
   Eccentricity of orbit:	0.017
   Surface gravity:		0.66	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		169.94	degrees Celcius
   Maximum temperature:   	372.73	degrees Celcius
   Minimum temperature:   	-212.02	degrees Celcius
   Escape Velocity:		7.52	km/sec
   Molecular weight retained:	14.04 and above
   Surface acceleration:	649.05	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.055
   Length of year:		115.82	days
   Length of day:		2779.66	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285


Planet 3	
   Distance from primary:	0.758	AU
   Mass:			0.757	Earth masses
   Equatorial radius:		5846.9	km
   Density:			5.401	grams/cc
   Eccentricity of orbit:	0.141
   Surface gravity:		0.90	Earth gees
   Surface pressure:		48.938	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		241.06	degrees Celcius
   Maximum temperature:   	247.34	degrees Celcius
   Minimum temperature:   	234.02	degrees Celcius
   Escape Velocity:		10.16	km/sec
   Molecular weight retained:	7.69 and above
   Surface acceleration:	882.57	cm/sec2
   Axial tilt:			22	degrees
   Planetary albedo:		0.596
   Length of year:		230.21	days
   Length of day:		19.47	hours
   Boiling point of water:	250.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 611
				Francium     melts at 27    boils at 1060
				Cesium       melts at 28    boils at 1099
				Gallium      melts at 30    boils at 3482
				Rubidium     melts at 39    boils at 1075
				Phosphorus   melts at 44    boils at 504
				Potassium    melts at 63    boils at 1184
				Sodium       melts at 98    boils at 1347
				Sulfur       melts at 113   boils at 734
				Indium       melts at 157   boils at 3029
				Lithium      melts at 181   boils at 2000
				Selenium     melts at 217   boils at 1071
				Tin          melts at 232   boils at 3790
   gasses in atmosphere:
				Nitrogen         99.7%  PP 48778.6 mb
				CarbonDioxide     0.1%  PP   33.2 mb
				Ozone             0.1%  PP   32.6 mb
				Ethanol           0.1%  PP   33.7 mb


Planet 4	
   Distance from primary:	1.293	AU
   Mass:			2.404	Earth masses
   Equatorial radius:		8500.3	km
   Density:			5.585	grams/cc
   Eccentricity of orbit:	0.021
   Surface gravity:		1.35	Earth gees
   Surface pressure:		5.644	Earth atmospheres
   Surface temperature:		18.54	degrees Celcius
   Normal daytime temperature:	20.18	degrees Celcius
   Normal night temperature:	16.80	degrees Celcius
   Maximum temperature:   	31.09	degrees Celcius
   Minimum temperature:   	5.36	degrees Celcius
   Escape Velocity:		15.02	km/sec
   Molecular weight retained:	3.52 and above
   Surface acceleration:	1326.77	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.542
   Length of year:		513.17	days
   Length of day:		13.19	hours
   Boiling point of water:	154.7	degrees Celcius
   Hydrosphere percentage:	93.91
   Cloud cover percentage:	89.52
   Ice cover percentage:	0.98
   liquids at surface:
				Ethanol      melts at -114  boils at 130
				Mercury      melts at -39   boils at 449
				Bromine      melts at -7    boils at 108
				Water        melts at 0     boils at 155
   gasses in atmosphere:
				Nitrogen          0.8%  PP   45.4 mb
				Helium           99.2%  PP 5598.3 mb


Planet 5	
   Distance from primary:	2.019	AU
   Mass:			0.106	Earth masses
   Equatorial radius:		3060.8	km
   Density:			5.288	grams/cc
   Eccentricity of orbit:	0.118
   Surface gravity:		0.46	Earth gees
   Surface pressure:		0.012	Earth atmospheres
   Surface temperature:		-79.01	degrees Celcius
   Normal daytime temperature:	-61.43	degrees Celcius
   Normal night temperature:	-96.79	degrees Celcius
   Maximum temperature:   	-34.52	degrees Celcius
   Minimum temperature:   	-124.67	degrees Celcius
   Escape Velocity:		5.26	km/sec
   Molecular weight retained:	28.67 and above
   Surface acceleration:	452.30	cm/sec2
   Axial tilt:			23	degrees
   Planetary albedo:		0.433
   Length of year:		1001.89	days
   Length of day:		22.59	hours
   Boiling point of water:	8.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	52.24
   liquids at surface:
				Ethanol      melts at -114  boils at -7
   gasses in atmosphere:
				Ozone            92.0%  PP   11.0 mb
				Argon             0.1%  PP    0.0 mb
				Krypton           7.0%  PP    0.8 mb
				Xenon             0.9%  PP    0.1 mb


Planet 6	*gas giant*
   Distance from primary:	2.454	AU
   Mass:			56.638	Earth masses
   Equatorial radius:		36389.8	km
   Density:			1.677	grams/cc
   Eccentricity of orbit:	0.001
   Escape Velocity:		35.23	km/sec
   Molecular weight retained:	0.64 and above
   Surface acceleration:	1705.63	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.520
   Length of year:		1342.49	days
   Length of day:		9.90	hours


Planet 7	*gas giant*
   Distance from primary:	5.688	AU
   Mass:			650.368	Earth masses
   Equatorial radius:		79539.4	km
   Density:			1.844	grams/cc
   Eccentricity of orbit:	0.108
   Escape Velocity:		80.76	km/sec
   Molecular weight retained:	0.12 and above
   Surface acceleration:	4099.53	cm/sec2
   Axial tilt:			36	degrees
   Planetary albedo:		0.542
   Length of year:		4732.74	days
   Length of day:		6.38	hours


Planet 8	*gas giant*
   Distance from primary:	12.467	AU
   Mass:			352.307	Earth masses
   Equatorial radius:		71011.3	km
   Density:			1.404	grams/cc
   Eccentricity of orbit:	0.030
   Escape Velocity:		62.90	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2786.16	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.535
   Length of year:		15362.09	days
   Length of day:		7.74	hours


Planet 9	*gas giant*
   Distance from primary:	28.493	AU
   Mass:			10.624	Earth masses
   Equatorial radius:		27398.1	km
   Density:			0.737	grams/cc
   Eccentricity of orbit:	0.212
   Escape Velocity:		17.59	km/sec
   Molecular weight retained:	2.57 and above
   Surface acceleration:	564.38	cm/sec2
   Axial tilt:			47	degrees
   Planetary albedo:		0.545
   Length of year:		53105.84	days
   Length of day:		17.20	hours


Planet 10	
   Distance from primary:	46.141	AU
   Mass:			0.109	Earth masses
   Equatorial radius:		4123.7	km
   Density:			2.212	grams/cc
   Eccentricity of orbit:	0.122
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.84	degrees Celcius
   Normal daytime temperature:	-223.08	degrees Celcius
   Normal night temperature:	-234.50	degrees Celcius
   Maximum temperature:   	-207.11	degrees Celcius
   Minimum temperature:   	-250.48	degrees Celcius
   Escape Velocity:		4.59	km/sec
   Molecular weight retained:	37.75 and above
   Surface acceleration:	254.94	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.137
   Length of year:		109440.59	days
   Length of day:		30.02	hours
   Boiling point of water:	-64.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.05


Planet 11	
   Distance from primary:	49.208	AU
   Mass:			0.140	Earth masses
   Equatorial radius:		4478.1	km
   Density:			2.217	grams/cc
   Eccentricity of orbit:	0.003
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.23	degrees Celcius
   Normal daytime temperature:	-224.85	degrees Celcius
   Normal night temperature:	-235.50	degrees Celcius
   Maximum temperature:   	-213.00	degrees Celcius
   Minimum temperature:   	-247.81	degrees Celcius
   Escape Velocity:		4.98	km/sec
   Molecular weight retained:	31.95 and above
   Surface acceleration:	277.44	cm/sec2
   Axial tilt:			57	degrees
   Planetary albedo:		0.137
   Length of year:		120528.88	days
   Length of day:		28.77	hours
   Boiling point of water:	-60.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06


