                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95047bfd
Stellar mass: 1.09 solar masses
Stellar radius: 1.05 solar radii
Stellar luminosity: 1.51
Stellar temperature: 6126 K
Stellar class: F9
Age: 1.851 billion years  (5.349 billion left on main sequence)
Habitable ecosphere radius: 1.230 AU

Planets present at:
1	  0.328 AU	no atmosphere
2	  0.413 AU	no atmosphere
3	  0.555 AU	no atmosphere
4	  0.682 AU	no atmosphere
5	  1.033 AU	greenhouse
6	  1.135 AU	greenhouse
7	  1.464 AU	no atmosphere
8	  1.930 AU	cold
9	  2.492 AU	cold
10	  3.505 AU	gas giant
11	  6.243 AU	gas giant
12	  9.768 AU	cold
13	 12.985 AU	gas giant
14	 28.495 AU	gas giant
15	 44.597 AU	no atmosphere



Planet 1	
   Distance from primary:	0.328	AU
   Mass:			0.019	Earth masses
   Equatorial radius:		1726.6	km
   Density:			5.259	grams/cc
   Eccentricity of orbit:	0.066
   Surface gravity:		0.26	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		255.96	degrees Celcius
   Normal daytime temperature:	474.14	degrees Celcius
   Normal night temperature:	-177.84	degrees Celcius
   Maximum temperature:   	477.31	degrees Celcius
   Minimum temperature:   	-188.96	degrees Celcius
   Escape Velocity:		2.96	km/sec
   Molecular weight retained:	90.58 and above
   Surface acceleration:	253.78	cm/sec2
   Axial tilt:			18	degrees
   Planetary albedo:		0.077
   Length of year:		65.80	days
   Length of day:		1579.17	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545


Planet 2	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.413	AU
   Mass:			0.341	Earth masses
   Equatorial radius:		4501.0	km
   Density:			5.337	grams/cc
   Eccentricity of orbit:	0.114
   Surface gravity:		0.68	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		198.10	degrees Celcius
   Normal daytime temperature:	403.59	degrees Celcius
   Normal night temperature:	-190.39	degrees Celcius
   Maximum temperature:   	406.99	degrees Celcius
   Minimum temperature:   	-201.28	degrees Celcius
   Escape Velocity:		7.77	km/sec
   Molecular weight retained:	13.14 and above
   Surface acceleration:	671.33	cm/sec2
   Axial tilt:			17	degrees
   Planetary albedo:		0.082
   Length of year:		92.80	days
   Length of day:		1769.89	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.555	AU
   Mass:			0.148	Earth masses
   Equatorial radius:		3413.6	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.52	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.18	degrees Celcius
   Maximum temperature:   	327.35	degrees Celcius
   Minimum temperature:   	-219.48	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.01 and above
   Surface acceleration:	505.41	cm/sec2
   Axial tilt:			15	degrees
   Planetary albedo:		0.084
   Length of year:		144.53	days
   Length of day:		3468.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 4	
   Distance from primary:	0.682	AU
   Mass:			0.120	Earth masses
   Equatorial radius:		3188.4	km
   Density:			5.291	grams/cc
   Eccentricity of orbit:	0.043
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		94.97	degrees Celcius
   Maximum temperature:   	279.76	degrees Celcius
   Minimum temperature:   	-225.74	degrees Celcius
   Escape Velocity:		5.48	km/sec
   Molecular weight retained:	26.40 and above
   Surface acceleration:	471.48	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.068
   Length of year:		196.94	days
   Length of day:		4726.46	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415


Planet 5	
   Distance from primary:	1.033	AU
   Mass:			1.449	Earth masses
   Equatorial radius:		7222.6	km
   Density:			5.486	grams/cc
   Eccentricity of orbit:	0.002
   Surface gravity:		1.13	Earth gees
   Surface pressure:		179.345	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		454.03	degrees Celcius
   Maximum temperature:   	457.10	degrees Celcius
   Minimum temperature:   	448.98	degrees Celcius
   Escape Velocity:		12.65	km/sec
   Molecular weight retained:	4.96 and above
   Surface acceleration:	1107.43	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.425
   Length of year:		367.28	days
   Length of day:		14.62	hours
   Boiling point of water:	331.8	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1267
				Cesium       melts at 28    boils at 1313
				Gallium      melts at 30    boils at 4066
				Rubidium     melts at 39    boils at 1285
				Potassium    melts at 63    boils at 1411
				Sodium       melts at 98    boils at 1599
				Indium       melts at 157   boils at 3542
				Lithium      melts at 181   boils at 2354
				Selenium     melts at 217   boils at 1280
				Tin          melts at 232   boils at 4422
				Polonium     melts at 254   boils at 1729
				Bismuth      melts at 271   boils at 2705
				Thallium     melts at 304   boils at 2532
				Cadmium      melts at 321   boils at 1410
				Lead         melts at 328   boils at 3009
				Zinc         melts at 420   boils at 1640
				Tellurium    melts at 450   boils at 1775
   gasses in atmosphere:
				Sulfur           18.7%  PP 33513.0 mb
				Nitrogen         80.7%  PP 144808.2 mb
				Phosphorus        0.4%  PP  670.4 mb


Planet 6	
   Distance from primary:	1.135	AU
   Mass:			0.295	Earth masses
   Equatorial radius:		4292.3	km
   Density:			5.328	grams/cc
   Eccentricity of orbit:	0.030
   Surface gravity:		0.65	Earth gees
   Surface pressure:		8.176	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		40.93	degrees Celcius
   Maximum temperature:   	52.24	degrees Celcius
   Minimum temperature:   	29.01	degrees Celcius
   Escape Velocity:		7.41	km/sec
   Molecular weight retained:	14.47 and above
   Surface acceleration:	639.20	cm/sec2
   Axial tilt:			30	degrees
   Planetary albedo:		0.484
   Length of year:		423.32	days
   Length of day:		19.58	hours
   Boiling point of water:	168.5	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.01
   liquids at surface:
				Ethanol      melts at -114  boils at 143
				Mercury      melts at -39   boils at 473
				Bromine      melts at -7    boils at 121
				Water        melts at 0     boils at 169
				Francium     melts at 27    boils at 851
				Cesium       melts at 28    boils at 885
				Gallium      melts at 30    boils at 2894
				Rubidium     melts at 39    boils at 864
   gasses in atmosphere:
				CarbonDioxide    40.9%  PP 3344.7 mb
				Methane           5.2%  PP  424.1 mb
				Ammonia           8.1%  PP  659.7 mb
				Ozone            42.6%  PP 3480.4 mb
				Argon             0.1%  PP    4.6 mb
				Neon              0.5%  PP   44.5 mb
				Krypton           2.4%  PP  195.4 mb
				Xenon             0.3%  PP   22.6 mb


Planet 7	
   Distance from primary:	1.464	AU
   Mass:			0.024	Earth masses
   Equatorial radius:		1870.7	km
   Density:			5.261	grams/cc
   Eccentricity of orbit:	0.020
   Surface gravity:		0.28	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-21.26	degrees Celcius
   Normal daytime temperature:	11.95	degrees Celcius
   Normal night temperature:	-54.67	degrees Celcius
   Maximum temperature:   	37.71	degrees Celcius
   Minimum temperature:   	-80.68	degrees Celcius
   Escape Velocity:		3.21	km/sec
   Molecular weight retained:	77.13 and above
   Surface acceleration:	275.08	cm/sec2
   Axial tilt:			31	degrees
   Planetary albedo:		0.058
   Length of year:		620.02	days
   Length of day:		30.60	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144


Planet 8	
   Distance from primary:	1.930	AU
   Mass:			0.970	Earth masses
   Equatorial radius:		6339.8	km
   Density:			5.429	grams/cc
   Eccentricity of orbit:	0.008
   Surface gravity:		0.98	Earth gees
   Surface pressure:		1.006	Earth atmospheres
   Surface temperature:		-82.44	degrees Celcius
   Normal daytime temperature:	-79.55	degrees Celcius
   Normal night temperature:	-85.50	degrees Celcius
   Maximum temperature:   	-62.13	degrees Celcius
   Minimum temperature:   	-104.22	degrees Celcius
   Escape Velocity:		11.04	km/sec
   Molecular weight retained:	6.51 and above
   Surface acceleration:	961.96	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.690
   Length of year:		938.42	days
   Length of day:		15.46	hours
   Boiling point of water:	100.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.06
   Ice cover percentage:	100.00
   liquids at surface:
				Ethanol      melts at -114  boils at 79
				Chlorine     melts at -101  boils at -34
   gasses in atmosphere:
				Oxygen           16.2%  PP  162.6 mb
				Nitrogen         83.8%  PP  842.6 mb


Planet 9	
   Distance from primary:	2.492	AU
   Mass:			1.182	Earth masses
   Equatorial radius:		6761.0	km
   Density:			5.455	grams/cc
   Eccentricity of orbit:	0.045
   Surface gravity:		1.05	Earth gees
   Surface pressure:		1.051	Earth atmospheres
   Surface temperature:		-102.24	degrees Celcius
   Normal daytime temperature:	-99.78	degrees Celcius
   Normal night temperature:	-104.84	degrees Celcius
   Maximum temperature:   	-83.34	degrees Celcius
   Minimum temperature:   	-122.60	degrees Celcius
   Escape Velocity:		11.81	km/sec
   Molecular weight retained:	5.70 and above
   Surface acceleration:	1030.81	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.669
   Length of year:		1376.64	days
   Length of day:		14.93	hours
   Boiling point of water:	101.4	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.01
   Ice cover percentage:	84.38
   liquids at surface:
				Ethanol      melts at -114  boils at 80
   gasses in atmosphere:
				Oxygen           14.6%  PP  153.0 mb
				Nitrogen         85.4%  PP  897.5 mb


Planet 10	*gas giant*
   Distance from primary:	3.505	AU
   Mass:			347.799	Earth masses
   Equatorial radius:		63708.9	km
   Density:			1.919	grams/cc
   Eccentricity of orbit:	0.018
   Escape Velocity:		65.99	km/sec
   Molecular weight retained:	0.18 and above
   Surface acceleration:	3417.18	cm/sec2
   Axial tilt:			35	degrees
   Planetary albedo:		0.483
   Length of year:		2296.16	days
   Length of day:		6.99	hours


Planet 11	*gas giant*
   Distance from primary:	6.243	AU
   Mass:			27.322	Earth masses
   Equatorial radius:		31830.7	km
   Density:			1.209	grams/cc
   Eccentricity of orbit:	0.048
   Escape Velocity:		26.16	km/sec
   Molecular weight retained:	1.16 and above
   Surface acceleration:	1075.36	cm/sec2
   Axial tilt:			38	degrees
   Planetary albedo:		0.548
   Length of year:		5459.34	days
   Length of day:		12.46	hours


Planet 12	
   Distance from primary:	9.768	AU
   Mass:			0.737	Earth masses
   Equatorial radius:		7726.5	km
   Density:			2.281	grams/cc
   Eccentricity of orbit:	0.075
   Surface gravity:		0.50	Earth gees
   Surface pressure:		0.300	Earth atmospheres
   Surface temperature:		-175.02	degrees Celcius
   Normal daytime temperature:	-171.51	degrees Celcius
   Normal night temperature:	-178.75	degrees Celcius
   Maximum temperature:   	-153.30	degrees Celcius
   Minimum temperature:   	-198.85	degrees Celcius
   Escape Velocity:		8.72	km/sec
   Molecular weight retained:	10.43 and above
   Surface acceleration:	492.53	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.322
   Length of year:		10685.65	days
   Length of day:		21.59	hours
   Boiling point of water:	69.5	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	29.51
   liquids at surface:
				Ozone        melts at -193  boils at -125
				Methane      melts at -183  boils at -173
   gasses in atmosphere:
				Oxygen           53.1%  PP  159.0 mb
				Nitrogen         46.9%  PP  140.6 mb


Planet 13	*gas giant*
   Distance from primary:	12.985	AU
   Mass:			472.356	Earth masses
   Equatorial radius:		77690.2	km
   Density:			1.437	grams/cc
   Eccentricity of orbit:	0.007
   Escape Velocity:		69.64	km/sec
   Molecular weight retained:	0.16 and above
   Surface acceleration:	3120.87	cm/sec2
   Axial tilt:			39	degrees
   Planetary albedo:		0.478
   Length of year:		16367.47	days
   Length of day:		7.32	hours


Planet 14	*gas giant*
   Distance from primary:	28.495	AU
   Mass:			17.210	Earth masses
   Equatorial radius:		31568.5	km
   Density:			0.781	grams/cc
   Eccentricity of orbit:	0.015
   Escape Velocity:		20.85	km/sec
   Molecular weight retained:	1.83 and above
   Surface acceleration:	688.69	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.531
   Length of year:		53239.78	days
   Length of day:		15.57	hours


Planet 15	
   Distance from primary:	44.597	AU
   Mass:			0.341	Earth masses
   Equatorial radius:		6009.3	km
   Density:			2.242	grams/cc
   Eccentricity of orbit:	0.061
   Surface gravity:		0.38	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.03	degrees Celcius
   Normal daytime temperature:	-223.10	degrees Celcius
   Normal night temperature:	-232.88	degrees Celcius
   Maximum temperature:   	-207.00	degrees Celcius
   Minimum temperature:   	-249.27	degrees Celcius
   Escape Velocity:		6.73	km/sec
   Molecular weight retained:	17.54 and above
   Surface acceleration:	376.60	cm/sec2
   Axial tilt:			34	degrees
   Planetary albedo:		0.161
   Length of year:		104244.90	days
   Length of day:		24.70	hours
   Boiling point of water:	-43.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.08
   gasses in atmosphere:
				Neon             100.0%  PP    0.2 mb


