                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048087
Stellar mass: 1.10 solar masses
Stellar radius: 1.03 solar radii
Stellar luminosity: 1.56
Stellar temperature: 6208 K
Stellar class: F8
Age: 2.884 billion years  (4.157 billion left on main sequence)
Habitable ecosphere radius: 1.247 AU

Planets present at:
1	  0.363 AU	no atmosphere
2	  0.570 AU	no atmosphere
3	  0.723 AU	greenhouse
4	  1.123 AU	greenhouse
5	  1.402 AU	gas giant
6	  2.173 AU	gas giant
7	  3.600 AU	no atmosphere
8	  4.737 AU	cold
9	  7.973 AU	gas giant
10	 16.877 AU	gas giant
11	 29.236 AU	gas giant
12	 45.778 AU	no atmosphere



Planet 1	
   Distance from primary:	0.363	AU
   Mass:			0.123	Earth masses
   Equatorial radius:		3213.8	km
   Density:			5.292	grams/cc
   Eccentricity of orbit:	0.032
   Surface gravity:		0.48	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		236.45	degrees Celcius
   Normal daytime temperature:	450.80	degrees Celcius
   Normal night temperature:	-185.29	degrees Celcius
   Maximum temperature:   	453.79	degrees Celcius
   Minimum temperature:   	-195.32	degrees Celcius
   Escape Velocity:		5.53	km/sec
   Molecular weight retained:	25.98 and above
   Surface acceleration:	475.31	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.055
   Length of year:		76.35	days
   Length of day:		1832.39	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645


Planet 2	
   Distance from primary:	0.570	AU
   Mass:			0.147	Earth masses
   Equatorial radius:		3409.8	km
   Density:			5.298	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.51	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		133.23	degrees Celcius
   Maximum temperature:   	327.44	degrees Celcius
   Minimum temperature:   	-219.82	degrees Celcius
   Escape Velocity:		5.87	km/sec
   Molecular weight retained:	23.06 and above
   Surface acceleration:	504.84	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.059
   Length of year:		150.16	days
   Length of day:		3603.83	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Mercury      melts at -39   boils at 144
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202


Planet 3	
   Distance from primary:	0.723	AU
   Mass:			0.768	Earth masses
   Equatorial radius:		5875.9	km
   Density:			5.403	grams/cc
   Eccentricity of orbit:	0.015
   Surface gravity:		0.90	Earth gees
   Surface pressure:		58.228	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		402.81	degrees Celcius
   Maximum temperature:   	408.79	degrees Celcius
   Minimum temperature:   	394.87	degrees Celcius
   Escape Velocity:		10.21	km/sec
   Molecular weight retained:	7.61 and above
   Surface acceleration:	887.19	cm/sec2
   Axial tilt:			13	degrees
   Planetary albedo:		0.493
   Length of year:		214.67	days
   Length of day:		24.41	hours
   Boiling point of water:	260.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1084
				Cesium       melts at 28    boils at 1124
				Gallium      melts at 30    boils at 3551
				Rubidium     melts at 39    boils at 1100
				Potassium    melts at 63    boils at 1211
				Sodium       melts at 98    boils at 1377
				Sulfur       melts at 113   boils at 753
				Indium       melts at 157   boils at 3089
				Lithium      melts at 181   boils at 2042
				Selenium     melts at 217   boils at 1096
				Tin          melts at 232   boils at 3865
				Polonium     melts at 254   boils at 1492
				Bismuth      melts at 271   boils at 2352
				Thallium     melts at 304   boils at 2199
				Cadmium      melts at 321   boils at 1210
				Lead         melts at 328   boils at 2619
   gasses in atmosphere:
				Nitrogen         99.0%  PP 57651.1 mb
				Phosphorus        0.7%  PP  378.8 mb
				CarbonDioxide     0.1%  PP   42.5 mb
				Ozone             0.1%  PP   40.3 mb
				Ethanol           0.1%  PP   43.2 mb


Planet 4	
   Distance from primary:	1.123	AU
   Mass:			0.116	Earth masses
   Equatorial radius:		3151.5	km
   Density:			5.290	grams/cc
   Eccentricity of orbit:	0.011
   Surface gravity:		0.47	Earth gees
   Surface pressure:		1.106	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		36.91	degrees Celcius
   Normal daytime temperature:	43.77	degrees Celcius
   Normal night temperature:	29.37	degrees Celcius
   Maximum temperature:   	63.44	degrees Celcius
   Minimum temperature:   	8.71	degrees Celcius
   Escape Velocity:		5.42	km/sec
   Molecular weight retained:	27.03 and above
   Surface acceleration:	465.94	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.042
   Length of year:		415.18	days
   Length of day:		25.14	hours
   Boiling point of water:	102.8	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.03
   liquids at surface:
				Ethanol      melts at -114  boils at 81
				Mercury      melts at -39   boils at 362
				Bromine      melts at -7    boils at 62
				Water        melts at 0     boils at 103
				Francium     melts at 27    boils at 684
				Cesium       melts at 28    boils at 712
				Gallium      melts at 30    boils at 2423
   gasses in atmosphere:
				CarbonDioxide    44.4%  PP  491.3 mb
				Ozone            51.0%  PP  564.3 mb
				Argon             0.1%  PP    0.9 mb
				Krypton           3.9%  PP   43.3 mb
				Xenon             0.5%  PP    5.6 mb


Planet 5	*gas giant*
   Distance from primary:	1.402	AU
   Mass:			4.969	Earth masses
   Equatorial radius:		17076.3	km
   Density:			1.424	grams/cc
   Eccentricity of orbit:	0.058
   Escape Velocity:		15.23	km/sec
   Molecular weight retained:	3.42 and above
   Surface acceleration:	679.61	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.494
   Length of year:		579.30	days
   Length of day:		15.69	hours


Planet 6	*gas giant*
   Distance from primary:	2.173	AU
   Mass:			21.703	Earth masses
   Equatorial radius:		27225.6	km
   Density:			1.535	grams/cc
   Eccentricity of orbit:	0.062
   Escape Velocity:		25.21	km/sec
   Molecular weight retained:	1.25 and above
   Surface acceleration:	1167.61	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.548
   Length of year:		1117.71	days
   Length of day:		11.96	hours


Planet 7	
   Distance from primary:	3.600	AU
   Mass:			0.204	Earth masses
   Equatorial radius:		3797.4	km
   Density:			5.310	grams/cc
   Eccentricity of orbit:	0.031
   Surface gravity:		0.57	Earth gees
   Surface pressure:		0.032	Earth atmospheres
   Surface temperature:		-120.63	degrees Celcius
   Normal daytime temperature:	-109.80	degrees Celcius
   Normal night temperature:	-131.67	degrees Celcius
   Maximum temperature:   	-88.46	degrees Celcius
   Minimum temperature:   	-154.29	degrees Celcius
   Escape Velocity:		6.54	km/sec
   Molecular weight retained:	18.55 and above
   Surface acceleration:	563.56	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.394
   Length of year:		2384.17	days
   Length of day:		20.19	hours
   Boiling point of water:	24.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	46.79
   gasses in atmosphere:
				Fluorine          0.9%  PP    0.3 mb
				Argon             3.0%  PP    1.0 mb
				Neon              6.5%  PP    2.1 mb
				Krypton          89.5%  PP   28.4 mb


Planet 8	
   Distance from primary:	4.737	AU
   Mass:			1.006	Earth masses
   Equatorial radius:		6415.7	km
   Density:			5.434	grams/cc
   Eccentricity of orbit:	0.029
   Surface gravity:		0.99	Earth gees
   Surface pressure:		1.012	Earth atmospheres
   Surface temperature:		-150.75	degrees Celcius
   Normal daytime temperature:	-148.91	degrees Celcius
   Normal night temperature:	-152.70	degrees Celcius
   Maximum temperature:   	-133.77	degrees Celcius
   Minimum temperature:   	-169.34	degrees Celcius
   Escape Velocity:		11.18	km/sec
   Molecular weight retained:	6.35 and above
   Surface acceleration:	974.30	cm/sec2
   Axial tilt:			27	degrees
   Planetary albedo:		0.693
   Length of year:		3598.57	days
   Length of day:		15.35	hours
   Boiling point of water:	100.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	100.00
   liquids at surface:
				Ozone        melts at -193  boils at -112
   gasses in atmosphere:
				Oxygen            2.2%  PP   22.4 mb
				Nitrogen         97.7%  PP  989.0 mb


Planet 9	*gas giant*
   Distance from primary:	7.973	AU
   Mass:			582.620	Earth masses
   Equatorial radius:		79210.2	km
   Density:			1.673	grams/cc
   Eccentricity of orbit:	0.199
   Escape Velocity:		76.59	km/sec
   Molecular weight retained:	0.14 and above
   Surface acceleration:	3703.07	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.496
   Length of year:		7850.25	days
   Length of day:		6.72	hours


Planet 10	*gas giant*
   Distance from primary:	16.877	AU
   Mass:			130.679	Earth masses
   Equatorial radius:		54522.9	km
   Density:			1.150	grams/cc
   Eccentricity of orbit:	0.084
   Escape Velocity:		43.72	km/sec
   Molecular weight retained:	0.42 and above
   Surface acceleration:	1753.02	cm/sec2
   Axial tilt:			28	degrees
   Planetary albedo:		0.464
   Length of year:		24193.76	days
   Length of day:		9.76	hours


Planet 11	*gas giant*
   Distance from primary:	29.236	AU
   Mass:			15.599	Earth masses
   Equatorial radius:		30706.0	km
   Density:			0.769	grams/cc
   Eccentricity of orbit:	0.020
   Escape Velocity:		20.13	km/sec
   Molecular weight retained:	1.96 and above
   Surface acceleration:	659.76	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.544
   Length of year:		55169.39	days
   Length of day:		15.91	hours


Planet 12	
   Distance from primary:	45.778	AU
   Mass:			0.274	Earth masses
   Equatorial radius:		5596.4	km
   Density:			2.235	grams/cc
   Eccentricity of orbit:	0.070
   Surface gravity:		0.36	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-228.31	degrees Celcius
   Normal daytime temperature:	-223.24	degrees Celcius
   Normal night temperature:	-233.29	degrees Celcius
   Maximum temperature:   	-210.62	degrees Celcius
   Minimum temperature:   	-246.50	degrees Celcius
   Escape Velocity:		6.25	km/sec
   Molecular weight retained:	20.29 and above
   Surface acceleration:	349.52	cm/sec2
   Axial tilt:			58	degrees
   Planetary albedo:		0.137
   Length of year:		108096.98	days
   Length of day:		25.64	hours
   Boiling point of water:	-45.1	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.09


