                         SYSTEM  CHARACTERISTICS
Random seed: 0x12f95048049
Stellar mass: 1.09 solar masses
Stellar radius: 1.02 solar radii
Stellar luminosity: 1.55
Stellar temperature: 6257 K
Stellar class: F8
Age: 1.419 billion years  (5.631 billion left on main sequence)
Habitable ecosphere radius: 1.246 AU

Planets present at:
1	  0.312 AU	no atmosphere
2	  0.433 AU	no atmosphere
3	  0.728 AU	greenhouse
4	  1.085 AU	greenhouse
5	  2.010 AU	gas giant
6	  2.878 AU	gas giant
7	  5.873 AU	gas giant
8	  8.066 AU	gas giant
9	 15.258 AU	gas giant
10	 28.779 AU	no atmosphere
11	 37.044 AU	gas giant
12	 49.943 AU	no atmosphere



Planet 1	
   Planet's rotation is in a resonant spin lock with primary.
   Distance from primary:	0.312	AU
   Mass:			0.073	Earth masses
   Equatorial radius:		2701.7	km
   Density:			5.278	grams/cc
   Eccentricity of orbit:	0.190
   Surface gravity:		0.41	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		273.74	degrees Celcius
   Normal daytime temperature:	493.63	degrees Celcius
   Normal night temperature:	-155.75	degrees Celcius
   Maximum temperature:   	497.76	degrees Celcius
   Minimum temperature:   	-171.23	degrees Celcius
   Escape Velocity:		4.64	km/sec
   Molecular weight retained:	36.86 and above
   Surface acceleration:	398.54	cm/sec2
   Axial tilt:			21	degrees
   Planetary albedo:		0.070
   Length of year:		60.97	days
   Length of day:		996.20	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800
				Selenium     melts at 217   boils at 361
				Tin          melts at 232   boils at 1645
				Polonium     melts at 254   boils at 545
				Bismuth      melts at 271   boils at 943


Planet 2	
   Distance from primary:	0.433	AU
   Mass:			0.224	Earth masses
   Equatorial radius:		3919.3	km
   Density:			5.315	grams/cc
   Eccentricity of orbit:	0.040
   Surface gravity:		0.59	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		192.74	degrees Celcius
   Maximum temperature:   	400.64	degrees Celcius
   Minimum temperature:   	-206.61	degrees Celcius
   Escape Velocity:		6.76	km/sec
   Molecular weight retained:	17.40 and above
   Surface acceleration:	582.13	cm/sec2
   Axial tilt:			26	degrees
   Planetary albedo:		0.060
   Length of year:		99.43	days
   Length of day:		2386.32	hours
   Boiling point of water:	-273.0	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 356
				Cesium       melts at 28    boils at 374
				Gallium      melts at 30    boils at 1499
				Rubidium     melts at 39    boils at 363
				Potassium    melts at 63    boils at 415
				Sodium       melts at 98    boils at 491
				Sulfur       melts at 113   boils at 202
				Indium       melts at 157   boils at 1285
				Lithium      melts at 181   boils at 800


Planet 3	
   Distance from primary:	0.728	AU
   Mass:			0.977	Earth masses
   Equatorial radius:		6354.7	km
   Density:			5.430	grams/cc
   Eccentricity of orbit:	0.059
   Surface gravity:		0.98	Earth gees
   Surface pressure:		92.339	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		506.01	degrees Celcius
   Maximum temperature:   	510.34	degrees Celcius
   Minimum temperature:   	498.98	degrees Celcius
   Escape Velocity:		11.07	km/sec
   Molecular weight retained:	6.48 and above
   Surface acceleration:	964.38	cm/sec2
   Axial tilt:			14	degrees
   Planetary albedo:		0.447
   Length of year:		216.88	days
   Length of day:		17.78	hours
   Boiling point of water:	287.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Francium     melts at 27    boils at 1154
				Cesium       melts at 28    boils at 1196
				Gallium      melts at 30    boils at 3746
				Rubidium     melts at 39    boils at 1170
				Potassium    melts at 63    boils at 1287
				Sodium       melts at 98    boils at 1461
				Indium       melts at 157   boils at 3261
				Lithium      melts at 181   boils at 2160
				Selenium     melts at 217   boils at 1166
				Tin          melts at 232   boils at 4077
				Polonium     melts at 254   boils at 1582
				Bismuth      melts at 271   boils at 2486
				Thallium     melts at 304   boils at 2325
				Cadmium      melts at 321   boils at 1286
				Lead         melts at 328   boils at 2767
				Zinc         melts at 420   boils at 1499
				Tellurium    melts at 450   boils at 1624
   gasses in atmosphere:
				Sulfur           20.9%  PP 19270.0 mb
				Nitrogen         78.5%  PP 72479.2 mb
				Phosphorus        0.4%  PP  384.3 mb


Planet 4	
   Distance from primary:	1.085	AU
   Mass:			0.424	Earth masses
   Equatorial radius:		4837.3	km
   Density:			5.351	grams/cc
   Eccentricity of orbit:	0.049
   Surface gravity:		0.74	Earth gees
   Surface pressure:		14.361	Earth atmospheres    GREENHOUSE EFFECT
   Surface temperature:		67.93	degrees Celcius
   Maximum temperature:   	76.96	degrees Celcius
   Minimum temperature:   	58.42	degrees Celcius
   Escape Velocity:		8.37	km/sec
   Molecular weight retained:	11.34 and above
   Surface acceleration:	723.41	cm/sec2
   Axial tilt:			29	degrees
   Planetary albedo:		0.536
   Length of year:		394.47	days
   Length of day:		18.26	hours
   Boiling point of water:	191.4	degrees Celcius
   Hydrosphere percentage:	100.00
   Cloud cover percentage:	100.00
   Ice cover percentage:	0.00
   liquids at surface:
				Ethanol      melts at -114  boils at 165
				Mercury      melts at -39   boils at 511
				Water        melts at 0     boils at 191
				Francium     melts at 27    boils at 910
				Cesium       melts at 28    boils at 944
				Gallium      melts at 30    boils at 3058
				Rubidium     melts at 39    boils at 923
				Phosphorus   melts at 44    boils at 416
				Potassium    melts at 63    boils at 1020
   gasses in atmosphere:
				Nitrogen         99.6%  PP 14304.2 mb
				CarbonDioxide     0.1%  PP   19.7 mb
				Ammonia           0.1%  PP    8.1 mb
				Ozone             0.1%  PP   20.2 mb


Planet 5	*gas giant*
   Distance from primary:	2.010	AU
   Mass:			119.472	Earth masses
   Equatorial radius:		44488.2	km
   Density:			1.936	grams/cc
   Eccentricity of orbit:	0.159
   Escape Velocity:		46.28	km/sec
   Molecular weight retained:	0.37 and above
   Surface acceleration:	2407.23	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.528
   Length of year:		994.72	days
   Length of day:		8.33	hours


Planet 6	*gas giant*
   Distance from primary:	2.878	AU
   Mass:			13.068	Earth masses
   Equatorial radius:		24039.4	km
   Density:			1.342	grams/cc
   Eccentricity of orbit:	0.103
   Escape Velocity:		20.82	km/sec
   Molecular weight retained:	1.83 and above
   Surface acceleration:	901.75	cm/sec2
   Axial tilt:			19	degrees
   Planetary albedo:		0.543
   Length of year:		1704.65	days
   Length of day:		13.61	hours


Planet 7	*gas giant*
   Distance from primary:	5.873	AU
   Mass:			3.451	Earth masses
   Equatorial radius:		17301.8	km
   Density:			0.951	grams/cc
   Eccentricity of orbit:	0.076
   Escape Velocity:		12.61	km/sec
   Molecular weight retained:	4.99 and above
   Surface acceleration:	459.79	cm/sec2
   Axial tilt:			45	degrees
   Planetary albedo:		0.499
   Length of year:		4967.68	days
   Length of day:		19.06	hours


Planet 8	*gas giant*
   Distance from primary:	8.066	AU
   Mass:			242.909	Earth masses
   Equatorial radius:		61434.4	km
   Density:			1.495	grams/cc
   Eccentricity of orbit:	0.014
   Escape Velocity:		56.16	km/sec
   Molecular weight retained:	0.25 and above
   Surface acceleration:	2566.61	cm/sec2
   Axial tilt:			25	degrees
   Planetary albedo:		0.512
   Length of year:		7992.92	days
   Length of day:		8.07	hours


Planet 9	*gas giant*
   Distance from primary:	15.258	AU
   Mass:			355.925	Earth masses
   Equatorial radius:		72422.7	km
   Density:			1.337	grams/cc
   Eccentricity of orbit:	0.023
   Escape Velocity:		62.61	km/sec
   Molecular weight retained:	0.20 and above
   Surface acceleration:	2706.13	cm/sec2
   Axial tilt:			32	degrees
   Planetary albedo:		0.526
   Length of year:		20793.26	days
   Length of day:		7.86	hours


Planet 10	
   Distance from primary:	28.779	AU
   Mass:			0.146	Earth masses
   Equatorial radius:		4544.0	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.033
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-217.36	degrees Celcius
   Normal daytime temperature:	-210.42	degrees Celcius
   Normal night temperature:	-224.25	degrees Celcius
   Maximum temperature:   	-195.93	degrees Celcius
   Minimum temperature:   	-239.47	degrees Celcius
   Escape Velocity:		5.06	km/sec
   Molecular weight retained:	31.01 and above
   Surface acceleration:	281.64	cm/sec2
   Axial tilt:			48	degrees
   Planetary albedo:		0.157
   Length of year:		53888.90	days
   Length of day:		28.56	hours
   Boiling point of water:	-59.2	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.06
   liquids at surface:
				Fluorine     melts at -220  boils at -217
				Oxygen       melts at -218  boils at -213


Planet 11	*gas giant*
   Distance from primary:	37.044	AU
   Mass:			4.543	Earth masses
   Equatorial radius:		21855.5	km
   Density:			0.621	grams/cc
   Eccentricity of orbit:	0.081
   Escape Velocity:		12.88	km/sec
   Molecular weight retained:	4.79 and above
   Surface acceleration:	379.30	cm/sec2
   Axial tilt:			43	degrees
   Planetary albedo:		0.460
   Length of year:		78697.55	days
   Length of day:		20.99	hours


Planet 12	
   Distance from primary:	49.943	AU
   Mass:			0.149	Earth masses
   Equatorial radius:		4579.5	km
   Density:			2.218	grams/cc
   Eccentricity of orbit:	0.135
   Surface gravity:		0.29	Earth gees
   Surface pressure:		0.000	Earth atmospheres
   Surface temperature:		-230.64	degrees Celcius
   Normal daytime temperature:	-225.37	degrees Celcius
   Normal night temperature:	-235.81	degrees Celcius
   Maximum temperature:   	-209.49	degrees Celcius
   Minimum temperature:   	-251.65	degrees Celcius
   Escape Velocity:		5.10	km/sec
   Molecular weight retained:	30.53 and above
   Surface acceleration:	283.91	cm/sec2
   Axial tilt:			44	degrees
   Planetary albedo:		0.148
   Length of year:		123197.49	days
   Length of day:		28.44	hours
   Boiling point of water:	-57.3	degrees Celcius
   Hydrosphere percentage:	0.00
   Cloud cover percentage:	0.00
   Ice cover percentage:	0.07


