extern double luminosity(double mass_ratio);
extern int  orb_zone(double orb_radius);
extern double volume_radius(double mass, double density);
extern double kothari_radius(double mass, int giant, int zone);
extern double empirical_density(double mass, double orb_radius, int gas_giant);
extern double volume_density(double mass, double equat_radius);
extern double period(double separation, double small_mass, double large_mass);
extern double day_length(double mass, double radius, double eccentricity, double density, double orb_radius, double orb_period, int giant, double mass_ratio);
extern int  inclination(double orb_radius);
extern double escape_vel(double mass, double radius);
extern double rms_vel(double molecular_weight, double orb_radius);
extern double molecule_limit(double mass, double equat_radius);
extern double acceleration(double mass, double radius);
extern double gravity(double acceleration);
extern int  grnhouse(int zone, double orb_radius, double r_greenhouse);
extern double vol_inventory(double mass, double escape_vel, double rms_vel, double stellar_mass, int zone, int greenhouse_effect);
extern double pressure(double volatile_gas_inventory, double equat_radius, double gravity);
extern double boiling_point(double surf_pressure);
extern double hydro_fraction(double volatile_gas_inventory, double planet_radius);
extern double cloud_fraction(double surf_temp, double smallest_MW_retained, double equat_radius, double hydro_fraction);
extern double ice_fraction(double hydro_fraction, double surf_temp);
extern double eff_temp(double ecosphere_radius, double orb_radius, double albedo);
extern double green_rise(double optical_depth, double effective_temp, double surf_pressure);
extern double planet_albedo(double water_fraction, double cloud_fraction, double ice_fraction, double surf_pressure);
extern double opacity(double molecular_weight, double surf_pressure);
extern void iterate_surface_temp(planet_pointer * planet);
extern void iterate_surface_temp_moon(planet_pointer * primary, planet_pointer * planet);
